### PR TITLE
YOLOv10 CoreML exports on non Apple systems

### PR DESCRIPTION
**Pull request by RyanHir**
`coremltools` supports exports on non-Apple devices and this behavior can be seen when exporting YOLOv5-YOLOv9 models on Linux. However the functionality is broken with the YOLOv10 family of models.

This patch just removes the macOS check when performing the explicit cast. 

Previously working (Linux):
`yolo export model=yolov8n.pt format=coreml` 

Previously broken (Linux):
`yolo export model=yolov10n.pt format=coreml`

Now fixed (Linux)
`yolo export model=yolov10n.pt format=coreml`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated the code to improve compatibility and simplify conditional checks.

### 📊 Key Changes
- Removed the conditional import `MACOS` and the associated platform-specific check.
- Ensured indices are always converted to `torch.int64` for compatibility with MPS and CoreML.

### 🎯 Purpose & Impact
- **Simplification**: By removing the `MACOS` import and conditional logic, the code is cleaner and easier to maintain.
- **Compatibility**: Always converting indices to `torch.int64` supports broader device compatibility, avoiding specific errors with MPS and CoreML. This makes the software more robust and allows it to function seamlessly across different hardware platforms.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RyanHir oh interesting, thank you for the fix! Is there a way to combine the div op with the int64 cast by using a torch command instead, i.e. `y = x.div(2, dtype=...)` of the builtin // command?

**Comment by RyanHir** [comment]
@glenn-jocher Looking at the pytorch docs, it does not look like that is possible.

**Comment by glenn-jocher** [comment]
@RyanHir thanks for checking the PyTorch docs. If combining the operations isn't feasible, your current approach should be fine. Let us know if you encounter any issues.

**Comment by RyanHir** [comment]
At the moment I am not seeing issues, but i have not done super thorough testing. I dont imagine this will break existing models, since there are no weights involved, and are only indexes for the gather operations. perhaps I am wrong here.

**Comment by glenn-jocher** [comment]
@RyanHir can you try https://github.com/ultralytics/ultralytics/pull/15796? This is a full refactor of the postprocess function I just did after discovering some code issues. Speeds it up by 2x and should remove your problem. Let me know if this works for you.

**Comment by glenn-jocher** [comment]
@RyanHir PR merged into #15796, will be part of `ultralytics 8.2.82` today. Thank you for your contributions!

**Comment by RyanHir** [comment]
Thanks. #15796 appears to work for what I wanted to achieve with this PR

**Pull request merged**
