### PR TITLE
Add JetPack6 Docker for NVIDIA Jetson Orin Series

### LINKED ISSUE #14699: How to do Jetpack 6 and Ultralytics Install (Without Docker)
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

There are currently instructions for a native install not using docker found here for Jetpack 5: https://docs.ultralytics.com/guides/nvidia-jetson/

I'm wondering, if it is possible to install for Jetpack 6?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by lakshanthad**
@glenn-jocher FYI
This Docker is based on the latest JetPack6 version which supports all Jetson Orin devices. 
It is tested on [this workflow run](https://github.com/ultralytics/ultralytics/actions/runs/10104244796/job/27942907227) and builds successfully.

Just to give an overview, based on the JetPack versions, these are the supported devices.
JP4 - Jetson Nano, TX2, Xavier NX, AGX Xavier
JP5 - Jetson Xavier NX, AGX Xavier, AGX Orin, Orin NX and Orin Nano
JP6 - Jetson AGX Orin, Orin NX and Orin Nano Series

I understand that having 3 Docker containers for Jetson is a little too much, but according to the feedback from NVIDIA Jetson team, it seems that Xavier NX, AGX Xavier users still need JP5 and Orin users need the latest JP6.

Once this PR is approved, I can update the docs accordingly.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added support for Jetson JetPack 6.x Docker images in the GitHub Actions workflow and created a corresponding Dockerfile.

### 📊 Key Changes
- **GitHub Actions Workflow Update**:
  - Introduced a new option `Dockerfile-jetson-jetpack6` with a default value set to `true`.
  - Added steps to build and tag Docker images using `Dockerfile-jetson-jetpack6`.
  
- **New Dockerfile**:
  - Created `Dockerfile-jetson-jetpack6` to support JetPack 6.x series on various NVIDIA Jetson devices like AGX Orin, Orin NX, and Orin Nano.

### 🎯 Purpose & Impact
- **Purpose**:
  - Enhance the Ultralytics setup to support the latest Jetson hardware using JetPack 6.x.
  
- **Impact**:
  - Users with newer Jetson devices will benefit from out-of-the-box support, enabling smoother deployment of YOLO models.
  - It expands the versatility of Ultralytics software for various edge AI applications on NVIDIA hardware. 🚀

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR adds support for Docker images tailored to Jetson JetPack 6, enhancing compatibility for NVIDIA Jetson devices 🖥️💪.

### 📊 Key Changes
- **New Workflow Configuration:**
  - Added an option to use `Dockerfile-jetson-jetpack6`.
  - Updated Docker build tags and platforms.

- **New Dockerfile:**
  - Introduced `Dockerfile-jetson-jetpack6` for building an image supporting JetPack6.x environments.
  - Configured dependencies and environment for Jetson AGX Orin, Orin NX, and Orin Nano Series.

- **Updates in Existing Dockerfiles:**
  - Added a `RUN rm *.whl` command to clean up wheel files post-installation in `Dockerfile-jetson-jetpack4` and `Dockerfile-jetson-jetpack5`.

### 🎯 Purpose & Impact
- **Broadened Hardware Support:** 
  - Enables the use of YOLOv8 on the latest NVIDIA Jetson hardware, improving performance and capabilities for edge AI applications 🚀.
- **Cleaner Docker Images:** 
  - Removing unnecessary files post-installation reduces image size, leading to faster deployment and less storage usage 📦.
- **Improved Configuration Flexibility:** 
  - The ability to select JetPack versions in the GitHub Actions workflow simplifies CI/CD processes and enhances development efficiency 🔧.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@lakshanthad got it, thanks @lakshanthad! Let's merge this and then please submit a new PR with the updated docs.

**Review by glenn-jocher — APPROVED** [review]

**Comment by lakshanthad** [comment]
@glenn-jocher sounds good! Thanks for cleaning up!

**Comment by glenn-jocher** [comment]
@lakshanthad I left these in as pip doesn't recognize these as valid wheel URLs unfortunately (typical NVIDIA)

ADD https://nvidia.box.com/shared/static/gjqofg7rkg97z3gc8jeyup6t8n9j8xjw.whl onnxruntime_gpu-1.8.0-cp38-cp38-linux_aarch64.whl

**Comment by glenn-jocher** [comment]
@lakshanthad PR merged!

**Comment by lakshanthad** [comment]
Thanks! @glenn-jocher

**Pull request merged**
