### PR TITLE
Add `integrations/gradio` Docs page

### PR DESCRIPTION
**Pull request by glenn-jocher**
@WangQvQ @AyushExel this demo code is not working for me, the preview thumbnails are broken, can you debug please?

Screenshot 2024-01-31 at 17 23 53

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing Gradio integration for interactive YOLOv8 object detection and corrections to DOTAv2 training code snippet.

### 📊 Key Changes
- 📝 Updated documentation for training models on the DOTAv2 dataset with the correct command.
- 🎉 Added new Gradio integration documentation for interactive object detection using Ultralytics YOLOv8.
- 🧑‍🏫 Created a Gradio web interface that allows users to upload images, adjust detection parameters, and view results in real time.
- ✂️ Provided a quick start Python code for setting up a Gradio interface with YOLOv8.
- 📚 Updated the documentation navigation to include Gradio integration.
- 🪲 Fixed inaccurate documentation in `metrics.py` concerning mAP50 and mAP75 descriptions.

### 🎯 Purpose & Impact
- 🚀 The new Gradio integration enables easy access and demonstration of YOLOv8's capabilities without needing programming knowledge, enhancing user experience and outreach.
- 🐛 Correcting the DOTAv2 training command ensures users adopt the accurate model file and avoid potential confusion.
- 🔍 By fixing the descriptions in `metrics.py`, the documentation accurately reflects the metric calculations, allowing developers to correctly interpret performance metrics.
- 📖 The Gradio integration provides a practical example, fostering education and experimentation in AI and object detection for a broad audience.

### CODE REVIEW

**Comment by WangQvQ** [comment]
@glenn-jocher It seems that this is the url problem, I think you can use the path of the local image, like this
```
examples=[
        ["ultralytics/assets/bus.jpg", 0.25, 0.45],
        ["ultralytics/assets/zidane.jpg", 0.25, 0.45],
    ]
```

**Comment by glenn-jocher** [comment]
@WangQvQ ok I fixed it now by using i.e. `ASSETS / "bus.jpg"`

Screenshot 2024-02-01 at 15 16 25

**Comment by glenn-jocher** [comment]
@WangQvQ PR merged, thank you for your contributions!

**Comment by glenn-jocher** [comment]
Screenshot 2024-02-07 at 02 59 58

Screenshot 2024-02-07 at 02 59 43 (1)

**Pull request merged**
