### PR TITLE
Update MLP module for RTDETR backward compatibility

### LINKED ISSUE #14874: Transformer activation bug.
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

_No response_

### Bug

image (4)

AttributeError: 'MLP' object has no attribute 'act'

I don't know why, but it seems that the act declared in the MLP class is not initialized properly.
I don't understand the cause of this, but if you find out why, I would appreciate it if you could let me know.

So I downgraded the version and use it. 8.1.24 (error is on newest version 8.2.70)
In this version, there is no act applied to that part. 
image (5)

### Environment

Python 3.10.12, torch 2.4.0+cu121, Ubuntu 22.04.3 LTS, Disk RAM is free enough. ultralytics==8.2.70

### Minimal Reproducible Example

detector = RTDETR('redetr-x.pt)

### Additional

Here is error log.

```
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 563, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/home/work/.local/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 234, in stream_inference
    self.model.warmup(imgsz=(1 if self.model.pt or self.model.triton else self.dataset.bs, 3, *self.imgsz))
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 639, in warmup
    self.forward(im)  # warmup
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 456, in forward
    y = self.model(im, augment=augment, visualize=visualize, embed=embed)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 102, in forward
    return self.predict(x, *args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 120, in predict
    return self._predict_once(x, profile, visualize, embed)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/tasks.py", line 141, in _predict_once
    x = m(x)  # run
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/modules/head.py", line 446, in forward
    embed, refer_bbox, enc_bboxes, enc_scores = self._get_decoder_input(feats, shapes, dn_embed, dn_bbox)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/modules/head.py", line 525, in _get_decoder_input
    refer_bbox = self.enc_bbox_head(top_k_features) + top_k_anchors
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1562, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/work/.local/lib/python3.10/site-packages/ultralytics/nn/modules/transformer.py", line 189, in forward
    x = self.act(layer(x)) if i < self.num_layers - 1 else layer(x)
  File "/home/work/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1729, in __getattr__
    raise AttributeError(f"'{type(self).__name__}' object has no attribute '{name}'")
AttributeError: 'MLP' object has no attribute 'act'
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated the codebase to improve compatibility with specific torch versions and enhanced the robustness of transformer modules.

### 📊 Key Changes
- **CLI Tests**: Added a conditional check for `TORCH_1_9` to ensure specific commands run only when using PyTorch 1.9.
- **Transformer Module**: Modified forward pass logic to use `getattr` for activation function and sigmoid application, increasing code flexibility.

### 🎯 Purpose & Impact
- **Improved Compatibility**:
  - Ensures smooth operation with PyTorch 1.9, making the tool more versatile across different torch versions.
- **Code Flexibility**:
  - Enhances the transformer module by making the activation and sigmoid application more adaptable and robust. 
  - Users benefit from more reliable performance and fewer version-related issues.

📈🛠️ These adjustments collectively enhance the tool's durability and user experience across diverse environments.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher I wanted to add test for rtdetr inference on pretrained weights since our CI tests didn't catch the `MLP` issue , but seems like there's module in rtdetr that torch==1.8.0 does not have.
pic-240802-1417-42
So I eventually removed it in https://github.com/ultralytics/ultralytics/pull/14901/commits/72c8be9f3b7684661711ed356e38335a195eab88.

**Comment by glenn-jocher** [comment]
@Laughing-q you can use the TORCH_1_8 constant in utils/torch_utils to add a conditional check to the new RTDETR test.

**Comment by Laughing-q** [comment]
@glenn-jocher updated in https://github.com/ultralytics/ultralytics/pull/14901/commits/9de83941cd08d260d73312e1730733bf69dc5f9f

**Comment by glenn-jocher** [comment]
@Laughing-q @Laughing-q test looks good, but I wish we didn't have to create an instance on every forward pass. Not sure what the best solution here is, but I'll merge anyway for now.

**Pull request merged**
