### PR TITLE
Add simple-utilities.md Docs page

### PR DESCRIPTION
**Pull request by Burhan-Q**
Thought that it might be helpful to showcase some helpful/useful functions that can be reused or extend functionality for users. I would even say these would be good references for learning coding (I'm biased b/c that's how I learned). Still a work in progress, hence setting to Draft, but wanted to open a PR to get feedback about if this is a worthwhile effort to continue. 🚀 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Documentation enhancement and new utilities guide for Ultralytics users.

### 📊 Key Changes
- Added documentation flags `-f` and `--dirtyreload` for `mkdocs serve`.
- Introduced a comprehensive new document `simple-utilities.md` in the usage section, detailing many utilities such as dataset auto-annotation, format conversion, image compression, dataset auto-splitting, and more.

### 🎯 Purpose & Impact
- The `-f` flag allows users to specify the `mkdocs.yml` location, offering flexibility for documentation sources.
- The `--dirtyreload` flag accelerates live documentation editing by only rebuilding changed files.
- The new utilities guide empowers users with tools to streamline workflow, easing tasks like data preparation, annotation, and image processing which benefits developers looking to enhance their productivity with Ultralytics software.

### CODE REVIEW

**Comment by Burhan-Q** [comment]
@glenn-jocher if/when you have a chance to check out the content here, I'm curious to hear your thoughts on if I should continue to build out this page or not.

**Comment by Burhan-Q** [comment]
code

**Comment by Burhan-Q** [comment]
Renamed to `simple-utilities` added H1 title (excluding hyphen) rebuilt pages locally to verify still working 🚀

**Comment by glenn-jocher** [comment]
@Burhan-Q awesome, looks good! Merging now :)

**Pull request merged**
