### PR TITLE
add flexibility to class Tuner: now it's possible to create custom search space and pass it in __init__, without changing source code

### PR DESCRIPTION
**Pull request by kirill-ionkin**
This PR created, bases on issue: https://github.com/ultralytics/ultralytics/issues/6856

### Summary
🛠️🚀🔧

Updated the `tuner` class to enable more customization of hyperparameter optimization. Moved and changed the `self.args` and `self.space` attributes to use configuration dictionaries.

> _`Tuner` of the dark, unleash your power_
> _Search the `space` for the optimal solution_
> _`self.args` is your key, configure your destiny_
> _Break the limits of the default execution_

### Walkthrough
* Allow custom hyperparameter search space for tuner ([link](https://github.com/ultralytics/ultralytics/pull/6882/files?diff=unified&w=0#diff-d42d1b8bc1c237d1e34d8da7ab7ab8130ad4eab91e795d5030271dafb52565d9L68-R68))
* Use configuration dictionary for tuner arguments ([link](https://github.com/ultralytics/ultralytics/pull/6882/files?diff=unified&w=0#diff-d42d1b8bc1c237d1e34d8da7ab7ab8130ad4eab91e795d5030271dafb52565d9R92))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced flexibility in hyperparameter space configuration for tuning.

### 📊 Key Changes
- Added the option to pass a custom hyperparameter space via the `args` dictionary.
- Prioritized 'space' in `args` if present, before falling back to the default hyperparameter space definition.

### 🎯 Purpose & Impact
- 🎨 Allows users to easily define or override the hyperparameter space for model tuning without modifying the codebase.
- 🚀 Potentially improves model performance by enabling finer control over the tuning process.
- 🛠 Simplifies the process of experimenting with different hyperparameters, leading to more efficient and targeted model optimization.

### CODE REVIEW

**Comment by kirill-ionkin** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@kirill-ionkin PR merged! Should be live in the next release later today or tomorrow. Thank you for your contributions.

**Comment by kirill-ionkin** [comment]
@glenn-jocher, i'm so glad)

**Comment by glenn-jocher** [comment]
@kirill-ionkin great to hear! 😊 Your enthusiasm and contributions help make YOLOv8 better for everyone! 🚀

**Pull request merged**
