### PR TITLE
Update docstring

### PR DESCRIPTION
**Pull request by AdiEcho**
Update checks.py to add docstring parameter 'max_dim'.
Update tasks.py to add docstring parameter 'detailed'.

### Summary
:mag::bar_chart::sparkles:

This pull request adds new parameters to the `info` and `check_imgsz` functions in the `ultralytics/nn/tasks.py` and `ultralytics/utils/checks.py` modules, respectively. These parameters enable more fine-grained control and validation of the model and input properties.

> _`ultralytics` grows_
> _adding more parameters, dims_
> _autumn of models_

### Walkthrough
* Add a new parameter `detailed` to the `info` method of the `BaseModel` class to enable printing detailed model information ([link](https://github.com/ultralytics/ultralytics/pull/4192/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R164))
* Support multi-dimensional inputs for the ultralytics models by adding a new parameter `max_dim` to the `check_imgsz` function in `ultralytics/utils/checks.py` ([link](https://github.com/ultralytics/ultralytics/pull/4192/files?diff=unified&w=0#diff-5b30bb601bc6484cdfcca11c382b45064aecc5b1024571f2984f6d4c74b89095R54))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the utility functions and methods for better clarity and functionality.

### 📊 Key Changes
- Added documentation for new parameters `iou_thres`, `image_shape`, and `raw_output` in `bbox_iou` function.
- Included new `detailed` argument in the `info` method, enabling detailed model information output.
- Clarified the purpose of the `_apply` method and defined the argument type (`function`).
- Improved the `load` method's description for loading model weights.
- Introduced a new `max_dim` parameter in `check_imgsz` to limit the maximum number of dimensions.

### 🎯 Purpose & Impact
- 📈 **Enhanced Clarity**: Clearer documentation helps users understand how to use functions and what to expect from them.
- 🧠 **Extended Functionality**: New parameters add flexibility to existing functions (`bbox_iou` and `check_imgsz`), allowing for more specific and controlled behavior.
- 👀 **Detailed Insights**: The `detailed` flag in the `info` method provides users with in-depth information about the model, beneficial for debugging or optimizing.
- 🏗 **Robust Loading**: Explicitly describing the loading process for model weights clarifies the proper usage and ensures correct implementation.
- 🌐 **Potential Impact**: These changes could improve the user experience for developers interacting with the Ultralytics codebase, leading to better model performance and easier troubleshooting.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AdiEcho thank you for the PR!

**Comment by glenn-jocher** [comment]
@AdiEcho please write a new comment that says: 

I have read the CLA Document and I sign the CLA

**Comment by AdiEcho** [comment]
I have read the CLA Document and I sign the CLA

**Comment by AdiEcho** [comment]
> @AdiEcho please write a new comment that says:
> 
> I have read the CLA Document and I sign the CLA

@glenn-jocher Finish.

**Comment by AdiEcho** [comment]
recheck

**Comment by glenn-jocher** [comment]
@AdiEcho yay thank you!

**Pull request merged**
