### PR TITLE
Removing cpu-info persistence for Docker images

### PR DESCRIPTION
**Pull request by ambitious-octopus**
No need to store cpu-info. This also creates a problem with docker containers giving incorrect `yolo check` information.
```
docker run ultralytics/ultralytics:latest yolo check
```
leads to:
```
Ultralytics YOLOv8.2.100 🚀 Python-3.10.14 torch-2.3.1 CPU (AMD EPYC 7763 64-Core Processor)
Setup complete ✅ (16 CPUs, 15.3 GB RAM, 348.5/383.3 GB disk)

OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.14
Install             git
RAM                 15.29 GB
CPU                 AMD EPYC 7763 64-Core Processor
CUDA                None
```

In this case the CPU: AMD EPYC 7763 64-Core Processor is the one of the github runner.

Which is incorrect.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR cleans up Dockerfiles in the Ultralytics repository by removing unnecessary build files. 🧹

### 📊 Key Changes
- Added commands to delete build-related files across multiple Dockerfiles.
- Specifically removed `persistent_cache.json` and other temporary files.

### 🎯 Purpose & Impact
- **Improved Disk Usage:** Frees up space by eliminating unnecessary files.
- **Cleaner Builds:** Ensures Docker images are less cluttered, enhancing maintainability.
- **No Functional Changes:** Users will experience no change in functionality, only cleaner and slightly smaller Docker images.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ambitious-octopus, thank you for submitting a pull request to the `ultralytics/ultralytics` repository! 🚀 This is an automated response, and an Ultralytics engineer will assist you soon. Meanwhile, please review the checklist below to ensure smooth integration:

- ✅ **Define a Purpose**: Make sure your PR description clearly outlines the purpose of removing CPU info persistence. If there's a related issue, link it in your description. Keep your commit messages clear and aligned with our project's standards.
- ✅ **Synchronize with Source**: Ensure your PR is up-to-date with the `main` branch. If not, update your branch by using 'Update branch' or running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: All Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks should pass. If any issues arise, address them promptly.
- ✅ **Update Documentation**: Please update relevant documentation for any changes made, if necessary.
- ✅ **Add Tests**: If applicable, add or revise tests to accommodate your changes, confirming that all pass successfully.
- ✅ **Sign the CLA**: Ensure you've signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first PR by writing "I have read the CLA Document and I sign the CLA" in a new comment.
- ✅ **Minimize Changes**: Restrict your changes to what's necessary for correcting the CPU info issue. Remember, _“It is not daily increase but daily decrease, hack away the unessential.”_ — Bruce Lee

If you've encountered a bug, please provide a Minimum Reproducible Example (MRE) to help us understand the issue better. For further information, check out our [Contributing Guide](https://docs.ultralytics.com/help/contributing).

Your efforts are greatly appreciated, and we're thrilled to have you contribute to Ultralytics! 🚀🔥

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/ultralytics/pull/16373

**Comment by glenn-jocher** [comment]
@ambitious-octopus we should just prevent saving this info on TESTS_RUNNING. We need to cache this to prevent running on every CLI command as the operations is very expensive.

**Review by ambitious-octopus — COMMENTED** [review]
@glenn-jocher What about this solution?
I added a new docker build argument `NO_CACHE`. If you build with `--build-arg NO_CACHE=true` it will remove the persist cache.

# cache=true
```
docker build -t ultralytics/ultralytics:cpu -f docker/Dockerfile-cpu . --build-arg NO_CACHE=true && docker run ultralytics/ultralytics:cpu ls /root/.config/Ultralytics
```
Output: 
```
Arial.Unicode.ttf
Arial.ttf
settings.json
```

# no argument
```
docker build -t ultralytics/ultralytics:cpu -f docker/Dockerfile-cpu . && docker run ultralytics/ultralytics:cpu ls /root/.config/Ultralytics
```
Output: 
```
Arial.Unicode.ttf
Arial.ttf
persistent_cache.json
settings.json
```

**Review by glenn-jocher — APPROVED** [review]
Slight changes

**Comment by glenn-jocher** [comment]
@ambitious-octopus looks good, I tweaked slightly to hard code the removal and merge some other `rm` commands!

**Pull request merged**
