### PR TITLE
Added back CoreML int8 quantization support

### PR DESCRIPTION
**Pull request by laclouis5**
This PR adds back the CoreML int8 quantization using kmeans palettization, which uses the new API introduced in `coremltools7.0b1`. This PR also removes the FP16 quantization option (`half` flag) since MLProgram uses FP16 weight quantization and FP16 execution by default. See PR #4043 and #1791 for more details.

### Summary
🚀🆕📱

This change improves the performance and compatibility of Core ML models exported by `exporter.py` by using the latest coremltools API. It also removes outdated and deprecated code.

> _Sing, O Muse, of the swift and skillful coder_
> _Who updated the `exporter.py` with wisdom and grace_
> _And made the Core ML models run like the wind_
> _On many a device with different face and space_

### Walkthrough
* Optimize and quantize Core ML models using coremltools.optimize.coreml module ([link](https://github.com/ultralytics/ultralytics/pull/4185/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cR469), [link](https://github.com/ultralytics/ultralytics/pull/4185/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL492-R499))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of CoreML model export with updated quantization technique.

### 📊 Key Changes
- Introduced an import of `coremltools.optimize.coreml` as `cto`.
- Changed the quantization mode from `'kmeans_lut'` to `'kmeans'` and removed the 16-bit option, now only using 8-bit and 32-bit quantization.
- Added new quantization configuration and optimization steps using CoreML tools.

### 🎯 Purpose & Impact
- These changes aim to improve the CoreML model export process, particularly focusing on the quantization of weights to reduce the model size and potentially increase performance on compatible hardware.
- Users can expect more efficient CoreML models for deployment, especially when using quantization for machine learning tasks on iOS devices. This could lead to faster inference times and better usability in mobile applications. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@laclouis5 thanks for the PR! Have you tested this method of int8 export?

I haven't tried to do int8 CoreML inference in a while, I'll try with main and this PR today.

**Comment by laclouis5** [comment]
@glenn-jocher Yes, I tested this method on some neural networks I developed and trained and also on YOLOv8. Usually, the performance drop is very small and negligible. I'll try to download COCO dataset and I'll post the results here.

Apple CoreMLTools documentation is also very great and their quantization performance [section](https://coremltools.readme.io/docs/performance-impact) also shows that int8 palettization does not decrease the accuracy by a significant amount.

**Comment by glenn-jocher** [comment]
@laclouis5 ok, sounds good enough to me. PR merged!

**Comment by laclouis5** [comment]
I couldn't download COCO so I checked the accuracy of quantized models on COCO128. I tested YOLOv8-n and YOLOv8-x both in 640x640. Quantized YOLOv8-n has 45.3% v.s. 45.4%mAP50-95 for the non quantized version. Quantized YOLOv8-x shows no performance drop, both networks have 66.5% mAP50-95.

**Comment by glenn-jocher** [comment]
@laclouis5 this sounds promising, it's fantastic that the quantized models performed comparably with their respective non-quantized versions. Thanks for sharing these results! 

Our team always appreciates helpful insights from the community and your contribution could help others in their work with YOLOv8. If you have more findings or issues that need to be addressed, feel free to reach out. Happy coding!

**Comment by laclouis5** [comment]
Thanks! Here are some insights and future directions I'll try to implement if I have the time and ressources:

* Apple has shown impressive performance with 4-bits Training-Time Quantization (requires a re-training step) which exhibits very little to no performance drop (less than 1% mAP). They even show good performance with 2-bits quantization but the accuracy drop is quite noticeable at this quantization level (-5% mAP).
* On the TensorRT side, there is also INT8 quantization that yields greatly improved throughput compared to FP16 on modern hardware (around 2X).
* Models can be exported in ONNX FP16, which halves the model size on disk at usually no accuracy cost. Also, ONNX models can compete with TensorRT speed on NVIDIA hardware if `onnxruntime-gpu` is configured to take advantage of Tensor Cores FP16 units.
* ONNX Runtime can be configured to use the `CoreMLExecutionProvider` on Apple platforms (using the package `onnxruntime-silicon` for example), which makes the ONNX format very interoperable and fast.

**Comment by pderrenger** [comment]
@laclouis5 These are some really interesting insights and future directions! It's great to see the potential for performance improvements and efficiency gains across different platforms and technologies.

If you do get the time and resources to implement these, your efforts could greatly benefit the YOLOv8 community and beyond. Don't hesitate to reach out if you need any support or have further findings to share. Keep up the good work!

**Comment by glenn-jocher** [comment]
@pderrenger, your exploration into advanced quantization techniques and cross-platform optimizations is truly appreciated! Your contributions could significantly enhance the efficiency and performance of YOLOv8. We're here to support your endeavors, so please keep us updated on your progress. Thank you for your commitment to improving the YOLOv8 ecosystem! 🚀

**Comment by glenn-jocher** [comment]
@pderrenger, your exploration into advanced quantization techniques and cross-platform optimizations is truly appreciated! Your contributions could significantly enhance the efficiency and performance of YOLOv8. We're here to support your endeavors and look forward to any updates. Keep pushing the boundaries! 🚀

**Pull request merged**
