### PR TITLE
`ultralytics 8.3.52` AutoBatch CUDA computation improvements

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added a new utility for monitoring CUDA memory usage to optimize model performance and logging. 🚀

### 📊 Key Changes
- **New `cuda_memory_usage` utility function**: Tracks and manages CUDA memory usage during operations.
- **Integration with `profile` function**: Record detailed memory usage statistics during model profiling.
- **Version bump**: Updated package version to `8.3.52`.

### 🎯 Purpose & Impact
- **Purpose**: Improve memory management and profiling by dynamically tracking CUDA memory usage, reducing the chance of out-of-memory errors and optimizing resource usage.
- **Impact**: Offers developers better insights into GPU memory usage, making debugging and optimization more efficient. Enhanced logging improves transparency and traceability. 📈

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Laughing-q, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any relevant issues. Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Continuous Integration (CI) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our Contributor License Agreement (CLA) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For more guidance, please refer to our contributing guide. Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

**Review by Burhan-Q — COMMENTED** [review]
Maybe updating https://github.com/ultralytics/ultralytics/blob/fbff76bb829a05da8ffc89ccd6c5948c442b2f90/ultralytics/utils/autobatch.py#L56-L58

to 
```python
 if device.type in {"cpu", "mps"} and torch.cuda.is_available(): 
```

Would mean that downstream conditionals using `torch.cuda.is_available()` could be removed?

**Comment by Laughing-q** [comment]
@Burhan-Q are you referring to:
```python
 if device.type in {"cpu", "mps"} or not torch.cuda.is_available(): 
```
instead of 
```python
 if device.type in {"cpu", "mps"} and torch.cuda.is_available(): 
```

**Comment by Burhan-Q** [comment]
@Laughing-q :laughing: yes

**Comment by glenn-jocher** [comment]
@Laughing-q PR merged into 8.3.52. Great work!!

**Pull request merged**
