### PR TITLE
Added clear callback

### PR DESCRIPTION
**Pull request by Toutatis64**
Enable capacity to disable specific callbacks for models, for example to bypass some of them (like mlflow)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactoring comments and enhancing event callback functionality in Ultralytics YOLO model class.

### 📊 Key Changes
- Simplified comments in the properties `names`, `device`, and `transforms`.
- Added `clear_callback` method to reset event callbacks.

### 🎯 Purpose & Impact
- 🧹 Streamlining code for better readability and maintenance.
- 🔄 The new `clear_callback` method allows users to reset callbacks for specific events, providing better control and flexibility over event handling within the model. This can be particularly useful when dynamically changing the behavior of models during training or inference.

### CODE REVIEW

**Comment by AyushExel** [comment]
Good idea! Thanks for the PR

**Comment by Toutatis64** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@Toutatis64 sure, how can I help you?

**Comment by Toutatis64** [comment]
> @Toutatis64 sure, how can I help you?

the recheck was to relaunch the CI cd process that failed due to validation of CLA :) Waiting for integration on my end :)

**Comment by glenn-jocher** [comment]
@Toutatis64 thank you for the PR!

**Pull request merged**
