### PR TITLE
Docs updates: Add Explorer to tab, YOLOv5 in Guides and Usage in Quickstart

### PR DESCRIPTION
**Pull request by AyushExel**
@glenn-jocher 
I checked with a couple of links and it doesn't break anything so I think this is in accordance with what you said. Looks like this 
Screenshot 2024-01-09 at 10 53 38 PM

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced functionality and documentation updates for Ultralytics Explorer and YOLO models.

### 📊 Key Changes
- 🔗 Fixed Markdown link (from `(Ultralytics Explorer API)[api.md]` to `[Ultralytics Explorer API](api.md)`) in Explorer GUI documentation.
- ✨ Added natural language search capability details to Ultralytics Explorer and dataset documentation.
- 📝 Updated and reformatted code for object blurring and cropping guides.
- 🛠 Added new `Explorer` documentation section within the Python usage guide.
- 🧹 Organized YOLOv5 tutorials and environment setup details by moving them into a separate, structured section.
- 📐 Refactored `tests/test_explorer.py` with comments and assert statements for clarity.
- 🧱 Minor improvement and clarity adjustments in internal code documentation across various modules (e.g., `head.py`, `tasks.py`, `basetrack.py`, `downloads.py`, etc.).

### 🎯 Purpose & Impact
- 🌐 Link correction improves navigation in documentation.
- 🧠 Natural language search enhancements will allow for more intuitive dataset searches and querying, broadening the tool's accessibility.
- 📖 Documentation reorganization offers a clearer understanding of functionalities and navigation ease for new users.
- ✅ Testing improvements bolster reliability and maintainability of the codebase.
- 📚 Internal documentation refinements aid developers in understanding the code structure and contributing effectively.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel only 1 warning on docs build:
```
mkdocs build -f docs/mkdocs.yml

WARNING -  griffe: ultralytics/data/explorer/explorer.py:418: No type or annotation for returned value 1
```

**Comment by AyushExel** [comment]
type annotations was added by Burhan yesterday. I guess it complains because ask ai feature was added after that and its not annotated

**Comment by AyushExel** [comment]
Should not be problem..It basically complains that some part of the file is annotated and other is not

**Comment by glenn-jocher** [comment]
@AyushExel yes, we need to format these as Google-style docstrings with proper types in the returns as the partial fixes I made in https://github.com/ultralytics/ultralytics/pull/7438/commits/4e6ead02b62bacc6ea38a996e17ff0baf306964d

Here are the return examples, the first is when you return the value directly, the second is if a defined variable is returned.
```
Returns:
    (type): description
    (type) name: description
```

**Comment by glenn-jocher** [comment]
@AyushExel also we need docstrings for all classes/functions, it looks like I let these slip through last time without realizing.
https://github.com/ultralytics/ultralytics/blob/53150a925b0c359e5c353cd49cc0e105774d5e51/ultralytics/data/explorer/utils.py#L16-L40

**Comment by AyushExel** [comment]
@glenn-jocher why dostring non-user facing functions? Only the functions that are supposed to be used/ docs read by user should be docstringed not the util functions unless there's a reason to do so?

**Comment by glenn-jocher** [comment]
They can be single-line docstrings, but they all need them. All the functions and classes in the repo have them now, it's part of coding standard. Also Mkdocs will parse these when creating the reference section, so the content there helps for Google searches etc. for docs for users to find us better.

**Comment by glenn-jocher** [comment]
@AyushExel added docstrings to each Explorer test in https://github.com/ultralytics/ultralytics/pull/7438/commits/6ba9ce543b4ebb039c3359e57e982058f58424db

**Comment by glenn-jocher** [comment]
@AyushExel added new Explorer pages to reference section, which will now enjoy all our new docstrings :)

**Comment by glenn-jocher** [comment]
@AyushExel ok cleaned up a lot of docstrings, ran docs/build_reference.py to rebuild the reference section, and fixed an explorer tests bug from using Image.show() in the tests.

Merging now!

**Pull request merged**
