### PR TITLE
object detection, instance segmentation and classification training and validation with Roboflow datasets

### PR DESCRIPTION
**Pull request by SkalskiP**
With those changes, Ultralytics YOLOv8 can use Roboflow datasets to train and validate object detection, instance segmentation, and classification models.

## Train with Roboflow datasets

```bash
yolo task=detect \
mode=train \
data=https://app.roboflow.com/roboflow-jvuqo/hard-hat-sample-jbobo/2 \
roboflow_api_key=<API_KEY>\
epochs=3
```

```bash
yolo task=classify \
mode=train \
data=https://universe.roboflow.com/food-hfbxu/scanpray/1 \
roboflow_api_key=<API_KEY>\
epochs=3
```

```bash
yolo task=segment \
mode=train \
data=https://universe.roboflow.com/burhan-6fhqx/animals-xxrpv/dataset/4 \
roboflow_api_key=<API_KEY>\
epochs=3
```

## Validate with Roboflow datasets

```bash
yolo task=detect \
mode=val \
data=https://app.roboflow.com/roboflow-jvuqo/hard-hat-sample-jbobo/2 \
roboflow_api_key=<API_KEY>\
model=runs/detect/train/weights/best.pt
```

```bash
yolo task=segment \
mode=val data=https://universe.roboflow.com/burhan-6fhqx/animals-xxrpv/dataset/4 \
roboflow_api_key=<API_KEY>\
model=runs/segment/train/weights/best.pt
```

```bash
yolo task=classify \
mode=val \
data=https://universe.roboflow.com/food-hfbxu/scanpray/1 \
roboflow_api_key=<API_KEY>\
model=runs/classify/train/weights/best.pt
```

### Summary
🔑🌐🚀

This pull request adds support for Roboflow datasets in the `ultralytics/yolo` package. It modifies the `ultralytics/yolo/data/utils.py`, `ultralytics/yolo/engine/model.py`, and `ultralytics/yolo/engine/validator.py` files to handle Roboflow dataset URLs. It also adds a new configuration option `roboflow_api_key` to the `ultralytics/yolo/configs/default.yaml` file.

> _Unleash the power of Roboflow_
> _With your API key in the config file_
> _Train your YOLO on any dataset_
> _Validate your results with no regret_

### Walkthrough
*  Add support for Roboflow dataset URLs ([link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-bba72212f83b03d4262d08ebe351339ded7d1322e3ddd72566e28271aad1e275R110-R113), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58R6), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58L18-R19), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58R295-R333), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cR8), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cR187-R191), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-7646fc7a670fe6bbcbf9e637a707139b362bd3b118be7faca28bff7d9b7450c3L12-R12), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-7646fc7a670fe6bbcbf9e637a707139b362bd3b118be7faca28bff7d9b7450c3R75-R80))
  *  Add `roboflow_api_key` option to `default.yaml` ([link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-bba72212f83b03d4262d08ebe351339ded7d1322e3ddd72566e28271aad1e275R110-R113))
  *  Import `re` module and `check_requirements` function in `data/utils.py` ([link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58R6), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58L18-R19))
  *  Define functions to parse, resolve, and download Roboflow datasets in `data/utils.py` ([link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58R295-R333))
  *  Import and call `check_dataset_roboflow` function in `train` method of `YOLO` class in `engine/model.py` ([link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cR8), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cR187-R191))
  *  Import and call `check_dataset_roboflow` function in `__init__` method of `BaseValidator` class in `engine/validator.py` ([link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-7646fc7a670fe6bbcbf9e637a707139b362bd3b118be7faca28bff7d9b7450c3L12-R12), [link](https://github.com/ultralytics/ultralytics/pull/295/files?diff=unified&w=0#diff-7646fc7a670fe6bbcbf9e637a707139b362bd3b118be7faca28bff7d9b7450c3R75-R80))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of Roboflow integration for model training and validation.

### 📊 Key Changes
- Updated `requirements.txt` to specify a minimum version for Roboflow.
- Added functions to extract Roboflow metadata and handle Roboflow datasets.
- Integrated Roboflow datasets into YOLO's training and validation processes.

### 🎯 Purpose & Impact
- **Easier Integration**: Users can now easily use Roboflow datasets with Ultralytics YOLO models.
- **Automated Handling**: Simplifies dataset management by automating format resolution and downloading.
- **Enhanced Flexibility**: Provides support for using external datasets, streamlining the workflow for users leveraging Roboflow.

### CODE REVIEW

**Comment by SkalskiP** [comment]
I have read the CLA Document and I sign the CLA

**Comment by SkalskiP** [comment]
@AyushExel could you help me out? Why is that `pre-commit.ci - pr` failing? I know it is because `yapf`. ut it doesn't give to many details. How can I fix that?

**Comment by AyushExel** [comment]
Something's preventing pre-commit from pushing updates. I'll try converting it from draft to PR to check

**Comment by SkalskiP** [comment]
@AyushExel, it still fails...

**Comment by SkalskiP** [comment]
@AyushExel and @glenn-jocher we are ready for review :)

**Comment by prince0310** [comment]
can you try by removing the space in default.yaml file at 111 and shift line 114 and 115 to 113 and 114 respetively

**Comment by SkalskiP** [comment]
@prince0310 are you planning to merge that PR?

**Comment by SkalskiP** [comment]
@fcakyon you plan to maintain that fork? ;)

**Comment by RizwanMunawar** [comment]
Hi @SkalskiP! Thanks for the PR, your changes look good. However, there haven't been any updates on this PR since last year.

Just so you know, we’ve already added a few Roboflow datasets in the [Ultralytics Docs](https://docs.ultralytics.com/), such as [crack segmentation](https://docs.ultralytics.com/datasets/segment/crack-seg/), [carparts-seg](https://docs.ultralytics.com/datasets/segment/carparts-seg/), and [package-seg](https://docs.ultralytics.com/datasets/segment/package-seg/). We may add support for more datasets in the future.

I’m closing it for now. However, feel free to submit a new PR if you identify any issues or optimizations for the Ultralytics codebase.

Thanks and regards,  
The Ultralytics Team

**Pull request closed without merging**
