### PR TITLE
`ultralytics 8.2.96` new `results[0].to_df` Pandas, XML and CSV methods

### PR DESCRIPTION
**Pull request by MatthewNoyce**
Added a method to convert the results returned from the summary method into a pandas DataFrame like mentioned in #8650

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced data export functionality with new methods for formatting results.

### 📊 Key Changes
- **Deprecation**: Replaced `tojson()` with `to_json()`.
- **New Methods**: Added `to_df()`, `to_csv()`, and `to_xml()` for exporting results.
- **Testing Updates**: Adjusted tests to use the new methods.

### 🎯 Purpose & Impact
- **Improved Usability**: Simplifies the process of exporting detection results to various formats like DataFrame, CSV, and XML. 🗂️
- **Data Flexibility**: Allows users to work with detection data in commonly used formats for better integration and analysis. 📊
- **Smooth Transition**: Deprecation warning for `tojson()` helps existing users transition to the updated method. ⚠️

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @MatthewNoyce, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues) like issue #8650. Ensure your commit messages are clear, concise, and adhere to the project's conventions.
  
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it using the 'Update branch' button or by running `git pull` and `git merge main` locally.

- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.

- ✅ **Update Documentation**: Make sure to update the relevant [documentation](https://docs.ultralytics.com) for the new `todataframe` feature in `results.py`.

- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing. This ensures the robustness of the new `todataframe` method.

- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.

- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your feature addition. 🏆 Remember, _"It is not daily increase but daily decrease, hack away the unessential."_ — Bruce Lee

For additional help, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions.

Thank you for enhancing our data handling capabilities with this PR! 🎉 An Ultralytics engineer will review it soon. 🚀

**Review by ambitious-octopus — CHANGES_REQUESTED** [review]
Hey @MatthewNoyce, interesting feature.
However, I get an error:

```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
res = model.predict()
res[0].toxml()
```
Output:
```
File ~???????????????/ultralytics/engine/results.py:841, in Results.todataframe(self, normalize, decimals)
    822 """
    823 Converts detection results to a Pandas Dataframe.
    824
   (...)
    837     >>> print(df_result)
    838 """
    839 import pandas as pd
--> 841 return pd.DataFrame(self.summary(normalize=normalize, decimals=decimals))

AttributeError: 'list' object has no attribute 'summary'
```

**Comment by MatthewNoyce** [comment]
Thank you for your feedback @ambitious-octopus. I cant work out how to import this branch like you have done in your testing, but the methods I have updated work on my machine now, but I havent been able to test them fully. If you could give me some guidance on how to use this branch as an import that would be very helpful and would avoid having to push the changes without fully testing them.

**Comment by MatthewNoyce** [comment]
I just realised that my fix will not work :). I forgot to do anything with the `todataframe()` method so I will try and sort that out now

**Comment by glenn-jocher** [comment]
No worries! Take your time to implement the `todataframe()` method. If you need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
@MatthewNoyce cleaned this up and added tests. Also passthrough args and kwargs for pandas methods.

Screenshot 2024-09-17 at 21 08 45

**Review by ambitious-octopus — COMMENTED** [review]
@MatthewNoyce During development I recommend that you install the package as an editable (`pip install -e /path/to/ultralytics`).
1. Clone to the repository
2. Checkout to the branch you are working on
3. Install the package as [editable](https://setuptools.pypa.io/en/latest/userguide/development_mode.html) (`pip install -e /path/to/ultralytics`)
4. Any changes you make to the package you can test directly.

Let me know if I can help you with anything else. Thanks again for the PR.

**Comment by glenn-jocher** [comment]
@MatthewNoyce fails on to XML for OBB models in https://github.com/ultralytics/ultralytics/actions/runs/10909469945/job/30277752740

**Pull request merged**
