### PR TITLE
Fix socket ResourceWarning

### PR DESCRIPTION
**Pull request by MichaelCurrie**
The socket connection returned by `socket.create_connection` was not being closed, leading to a ResourceWarning.

This code closes the connection properly.

Example to replicate this issue:

```python
# Force warnings to be errors
import warnings
warnings.filterwarnings("error")

with warnings.catch_warnings():
    # We have to ignore a DeprecationWarning: module 'sre_constants' is deprecated
    # in matplotlib._fontconfig_pattern.py
    warnings.filterwarnings("ignore", category=DeprecationWarning)

    import ultralytics

# Trigger the warning
y = ultralytics.YOLO
```

Running the above code gives the following warning:

```
ResourceWarning: unclosed <socket.socket fd=1424, family=2, type=1, proto=0, laddr=('192.168.1.146', 56550), raddr=('1.1.1.1', 53)>
```

I have read the CLA Document and I sign the CLA

### Summary
🐛🧹📝

Improved the `is_online` function in `ultralytics/yolo/utils/__init__.py` by closing the socket connection and renaming a variable. This was part of a code quality and readability improvement for the ultralytics/yolo/utils module.

> _`is_online` fixed_
> _socket closed after testing_
> _autumn leaves no trace_

### Walkthrough
* Close socket connection after testing it in `is_online` function ([link](https://github.com/ultralytics/ultralytics/pull/2807/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137L375-R383)) to avoid ResourceWarning and rename variable `server` to `host` to match argument name of `socket.create_connection` in `ultralytics/yolo/utils/__init__.py`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced network robustness in connectivity check function.

### 📊 Key Changes
- Refactored variable name from `server` to `host` for clarity.
- Introduced a variable `test_connection` to manage the socket connection.
- Added an `else` block to close the `test_connection` socket after a successful check to prevent potential resource warnings.

### 🎯 Purpose & Impact
- The purpose of these changes is to improve code clarity and maintain resource hygiene by explicitly closing socket connections.
- The potential impact includes more reliable and cleaner runtime behavior, with fewer warnings for users implementing the Ultralytics YOLO framework in environments where network connectivity checks occur. 🌐🛠️

### CODE REVIEW

**Comment by MichaelCurrie** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

**Comment by MichaelCurrie** [comment]
I have read the CLA Document and I sign the CLA

**Comment by MichaelCurrie** [comment]
recheck

**Comment by glenn-jocher** [comment]
@MichaelCurrie thanks for the PR! Was not aware of this issue. Your fix looks good. Could I simplify it to just adding a .close() to the original L377 here?

```diff
-             socket.create_connection((server, 53), timeout=2)  # connect to (server, port=53)
+            socket.create_connection((server, 53), timeout=2)  # connect to (server, port=53).close()
```

**Comment by MichaelCurrie** [comment]
Please do what you prefer, however.  Probably my comment `"# If the connection was successful, close it to avoid a ResourceWarning"` it not necessary if you think we should get rid of it as superfluous.

It's an honour to PR you!  Thanks for YOLOv8.

**Comment by glenn-jocher** [comment]
@MichaelCurrie got it thanks! I'll leave as is to keep it simple, but yes I get your point, thanks for your contributions!

**Comment by glenn-jocher** [comment]
Merged for 8.0.108 today.

**Pull request merged**
