### PR TITLE
Added `torch.distributed.is_available()` check before `torch.distributed.is_initialized()`

### LINKED ISSUE #612: AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

PyTorch Hub

### Bug

I'm getting:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.yolo.engine.model import YOLO
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/__init__.py", line 3, in <module>
    from . import v8
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8 import classify, detect, segment
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/__init__.py", line 3, in <module>
    from ultralytics.yolo.v8.classify.predict import ClassificationPredictor, predict
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/v8/classify/predict.py", line 5, in <module>
    from ultralytics.yolo.engine.predictor import BasePredictor
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/engine/predictor.py", line 34, in <module>
    from ultralytics.nn.autobackend import AutoBackend
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/nn/autobackend.py", line 15, in <module>
    from ultralytics.yolo.utils import LOGGER, ROOT, yaml_load
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/__init__.py", line 544, in <module>
    SETTINGS = get_settings()
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/__init__.py", line 503, in get_settings
    with torch_distributed_zero_first(RANK):
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/home/xavier2/.local/lib/python3.8/site-packages/ultralytics/yolo/utils/torch_utils.py", line 34, in torch_distributed_zero_first
    initialized = torch.distributed.is_initialized()  # prevent 'Default process group has not been initialized' errors
AttributeError: module 'torch.distributed' has no attribute 'is_initialized'
```
when importing `YOLO` from `ultralytics`.

### Environment

- YOLO: Ultralytics YOLOv8.0.18 🚀 Python-3.8.10 torch-1.13.0a0+936e9305.nv22.11 CUDA:0 (Xavier, 6855MiB)
- OS: Ubuntu 20.04
- Python: 3.8.10
- Platform: Jetson Xavier NX

### Minimal Reproducible Example

First, I installed ultralytics, using `pip install ultralytics`.

Then, run `from ultralytics import YOLO`
image

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by bid-p**
Resolves #612 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvement in distributed training initialization check within Ultralytics YOLO utils.

### 📊 Key Changes
- Modified the initialization check in `torch_distributed_zero_first` from `is_initialized` to a combination of `is_available` and `is_initialized`.

### 🎯 Purpose & Impact
- **Purpose:** To prevent the error 'Default process group has not been initialized' during distributed training setups.
- **Impact:** Ensures a more robust check for the availability and initialization of distributed training processes, which can lead to smoother execution and better user experiences for developers using distributed training with Ultralytics YOLO.

### CODE REVIEW

**Comment by bid-p** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/ultralytics/assets/blob/main/documents/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I sign the CLA

**Comment by bid-p** [comment]
recheck

**Comment by AyushExel** [comment]
Please sign the CLA. Looks good otherwise

**Comment by bid-p** [comment]
I have read the CLA Document and I sign the CLA

**Comment by bid-p** [comment]
> Please sign the CLA. Looks good otherwise 

Done, thanks!

**Comment by pderrenger** [comment]
@bid-p thank you for signing the CLA! Your contribution is much appreciated 🙌. If you have any more questions or need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
@pderrenger Your contribution is now merged. Thank you for supporting the YOLOv8 community! If you need further assistance, don't hesitate to reach out. Happy coding! 🚀

**Pull request merged**
