### PR TITLE
`ultralytics 8.2.83` fix SAM2 CLI usage

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR updates the documentation and code to include comparisons between various SAM (Segment Anything Model) versions and Ultralytics' YOLOv8, enhancing clarity and information for users.

### 📊 Key Changes
- 📝 Updated documentation to compare Meta's SAM 2 models with YOLOv8 segmentation models.
- 📈 Revised comparison metrics (model size, parameters, CPU speed) for better readability.
- 📚 Adjusted example Python code to include profiling for SAM2-t, SAM2-b, SAM-b, and MobileSAM.
- 🔄 Code base version bump from 8.2.82 to 8.2.83.
- 🔨 Minor adjustments in module imports and model initialization logic.

### 🎯 Purpose & Impact
- 💡 **Clarity:** Provides detailed, clear comparisons between segmentation models, helping users understand the performance differences.
- ⏱️ **Efficiency:** Showcases YOLOv8's efficiency compared to SAM models, highlighting significant differences in speed and size.
- 🤖 **Usability:** The updated examples make it easier for developers to profile different models.
- 🚀 **Improved Documentation:** Enhances user guidance through better organization and presentation of information.

### CODE REVIEW

**Comment by Alarmod** [comment]
@glenn-jocher
```
ultralytics==8.3.82
```
Non exist version in merge

**Comment by glenn-jocher** [comment]
Thank you for pointing that out. The correct version should be `ultralytics==8.2.83`. Please update your package and try again.

**Comment by Alarmod** [comment]
@glenn-jocher
I am about line ```Tests run on a 2023 Apple M2 Macbook with 16GB of RAM using torch==2.3.1 and ultralytics==8.3.82``` in https://github.com/ultralytics/ultralytics/blob/main/docs/en/models/sam-2.md

Now text with wrong version

**Comment by glenn-jocher** [comment]
@Alarmod thank you for catching that. The correct version should be `ultralytics==8.2.83`. We'll update the documentation accordingly.

**Pull request merged**
