### PR TITLE
`ultralytics 8.1.18` add cmake for building onnxsim on aarch64

### PR DESCRIPTION
**Pull request by lakshanthad**
onnxsim does not have pre-built binaries for aarch64.
https://pypi.org/project/onnxsim/#files

When exporting to tflite and exporting to onnx with simplify on aarch64 devices, it will try to download the tar.gz (20.1MB) file and compile onnxsim on the device. However, this needs `cmake` for the build process. All the other architectures have pre-built binaries and have no problem.

So I have included cmake inside onnx export with simplify and tflite exports. The reason I included cmake separately without combining it with other packages is that if cmake is included together with onnxsim inside `check_requirements()`, it will have the following error:

```
pi@raspberrypi:~ $ yolo export model=yolov8n.pt format=onnx simplify
Ultralytics YOLOv8.1.16 🚀 Python-3.11.2 torch-2.2.0 CPU (Cortex-A76)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

PyTorch: starting from 'yolov8n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (6.2 MB)
requirements: Ultralytics requirements ['cmake', 'onnxsim>=0.4.33'] not found, attempting AutoUpdate...
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [8 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6er09w5u/onnxsim_9b0aac316a144e64a73932b33fa051c1/setup.py", line 67, in <module>
          assert CMAKE, 'Could not find "cmake" executable!'
      AssertionError: Could not find "cmake" executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
requirements: ❌ Command 'pip install --no-cache "cmake" "onnxsim>=0.4.33" ' returned non-zero exit status 1.
```

So `cmake` need to be installed separately at first.

I have read the CLA Document and I hereby sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved ARM64 Dockerfile and package requirements management.

### 📊 Key Changes
- Removed `cmake` from Dockerfile for ARM64 builds, optimizing the installation layer.
- Updated the Ultralytics package version from 8.1.17 to 8.1.18.
- Added conditional checks to install `cmake` if exporting to ONNX on an ARM64 system.
- Adjusted TensorFlow package requirement logic to handle ARM64 architecture and restricted versioning for non-ARM64 systems.
- Restricted `flatbuffers` version to below 100 to avoid potential future conflicts.

### 🎯 Purpose & Impact
- **Purpose:** These changes streamline the Docker build process for ARM64 and ensure compatibility and stability when exporting models using different platforms.
- **Impact:** Users benefit from a smoother experience with Docker on ARM64, and developers gain clarity on package dependencies during model exporting, particularly with TensorFlow and ONNX. This may also enhance overall performance and maintainability of the Ultralytics codebase. 🚀

### CODE REVIEW

**Comment by lakshanthad** [comment]
@glenn-jocher FYI

**Comment by glenn-jocher** [comment]
Maybe do this?

```python
suffix = '-macos' if MACOS else '-aarch64' if ARM64 else '' if cuda else '-cpu'
version = '' if ARM64 else '<=12.13.1'
check_requirements(f"tensorflow{suffix}{version}")
```

**Comment by glenn-jocher** [comment]
@lakshanthad ok I've closed #8345 in favor of this PR. Updated the code slightly and waiting on CI now.

**Comment by lakshanthad** [comment]
> Maybe do this?
> 
> ```python
> suffix = '-macos' if MACOS else '-aarch64' if ARM64 else '' if cuda else '-cpu'
> version = '' if ARM64 else '<=12.13.1'
> check_requirements(f"tensorflow{suffix}{version}")
> ```

@glenn-jocher 
typo there. should be 2.13.1

**Comment by lakshanthad** [comment]
@glenn-jocher 
The rest looks good. thanks for the modifications.

**Comment by glenn-jocher** [comment]
@lakshanthad PR merged with patch version bump, nice work on this!

**Comment by lakshanthad** [comment]
Great! @glenn-jocher Thank you!

**Pull request merged**
