### PR TITLE
add argparse support

### PR DESCRIPTION
**Pull request by semihhdemirel**
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced usability of YOLOv8 OpenCV ONNX example with command-line arguments. 🖼️🐍

### 📊 Key Changes
- Added `argparse` to handle command-line arguments for specifying the ONNX model and image file.
- Updated the main function to accept ONNX model and input image as arguments, allowing dynamic input.
- Included the new usage format in the README to reflect how to run the script with custom model and image paths.

### 🎯 Purpose & Impact
- **Flexibility**: Users can now run the script with any ONNX model and image without modifying the code. 🔄
- **Ease of Use**: Simplifies testing different models and images, making the example more user-friendly. 👨‍💻👩‍💻
- **Documentation**: Updated instructions guide users on the new way to use the script, avoiding confusion. 📚

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@semihhdemirel thank you! Please sign CLA by writing on a new message:

I have read the CLA Document and I sign the CLA

**Comment by semihhdemirel** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@semihhdemirel thank you for your contributions! PR is merged into `updates` branch for deployment with next release in a few days!

**Comment by semihhdemirel** [comment]
Thank you

**Comment by glenn-jocher** [comment]
@semihhdemirel you're welcome! If you have any other questions or issues, please don't hesitate to reach out. Have a great day!

**Pull request merged**
