### PR TITLE
Optimize label display

### PR DESCRIPTION
**Pull request by sunmooncode**
1. Consider the current situation where the label width exceeds the image boundary.

2. The existing code considers the height of the label exceeds the image boundary, then draw the label downward, but this is also insufficient, when the target is small, there will be the entire label obscured to recognize the object. Optimization when the height exceeds the image boundary, the label will be drawn to the entire target box below.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved label positioning for bounding boxes in image plotting.

### 📊 Key Changes
- Enhanced `box_label` function to consider image boundaries when positioning labels.
-  Introduced checks for label positioning to ensure they do not go outside image edges.
- Adjusted code for both `PIL` and `cv2` to reflect the above improvements.

### 🎯 Purpose & Impact
- Ensures labels are more readable by keeping them within image boundaries 🎯.
- Enhances visual clarity for users when reviewing plotted images 🖼️.
- Prevents labels from being cut off, improving overall user experience 🖥️.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@sunmooncode can you provide some before and after images to illustrate the changes in this PR?

**Comment by sunmooncode** [comment]
@glenn-jocher of course！
The first picture is the current effect, the second is the improved effect.

**1.This is an improvement beyond the upper boundary of the image.** 
image image

**2.Improvements beyond the right boundary of the image.**
image image

**Comment by glenn-jocher** [comment]
@sunmooncode thank you for sharing the before and after images! The improvements are quite clear and significantly enhance the readability of the labels, especially when they exceed the image boundaries. 🎉

To ensure we can fully evaluate and integrate these changes, could you please provide a minimum reproducible code example that demonstrates the issue and the improvements? This will help us verify the bug and the effectiveness of your solution. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on what to include.

Additionally, please confirm that you are using the most recent versions of `torch` and `ultralytics`. If not, kindly upgrade to the latest versions and test your changes again to ensure compatibility.

Looking forward to your response and thank you for contributing to the Ultralytics community! 🚀

**Comment by sunmooncode** [comment]
Continued to optimize the details. In the previous section, only the upper and right boundaries of the label were considered. But when the target box is large enough, the label goes beyond the lower border, so the label is drawn in the upper corner of the box.

**Comment by glenn-jocher** [comment]
Thank you for the detailed explanation and the before-and-after images! The improvements are clear and significantly enhance the readability of labels, especially when they exceed image boundaries. 🎉

To ensure we can fully evaluate and integrate these changes, could you please provide a minimum reproducible code example that demonstrates the issue and the improvements? This will help us verify the bug and the effectiveness of your solution. You can refer to our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example) for more details on what to include.

Additionally, please confirm that you are using the most recent versions of `torch` and `ultralytics`. If not, kindly upgrade to the latest versions and test your changes again to ensure compatibility.

Looking forward to your response and thank you for contributing to the Ultralytics community! 🚀

**Pull request closed without merging**
