### PR TITLE
Add support to exporting or inference with TensorRT 10.0.0b6, and fix bugs when exporting a tensorrt file .engine with flag half=True or when inference

### PR DESCRIPTION
**Pull request by ZouJiu1**
1. I have checked for Existing Contributions: Before submitting, my contribution is unique and complementary.

2. No related issues.

3. 
**Purpose**: There have three things, I fix two bug with onnx and tensorrt, and I add a new feature with newest tensorrt version 10.0.0\*

i. A bug fix:  When export a tensorrt file with half=True flag to a .engine from yolov8n.pt, If I use codes like below, the exported .engine file’s input and output is float32 not float16(half)

because in [engine\exporter.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L240) file line 240 `if self.args.half and onnx and self.device.type != "cpu":`, it will only convert image to float16 when exporting onnx, when exporting tensorrt with half=true, it will pass this code line, the exported .engine input and output tensor will be torch.float32, not torch.float16. Eventually, we will get a float32 input and output tensorrt file .engin not float16.

```python []
model = YOLO(r'yolov8n.pt')  # load a pretrained model (recommended for training)
results0 = model.export(format='engine', simplify=True, half=True, device='cuda:0')    # onnx,engine
```
ii. A new feature: I install tensorrt 10.0.06(the newest version now) in window11, and I want to convert a yolov8x.pt file trained myself to a tensorrt file and infer in half mode, so I encounter a lot of problems, the original codes are not suitable for tensorrt 10.0.06 . finally, I have to add new codes to convert half-float16 tensorrt file and infer with it. Of course, I success to convert and infer with half engine file.

iii. A bug fix: When I infer with a FP16 tensorrt model .engine, the output is wrong, because self.output_name have no tensor, it length is 0. Also, len(self.bindings)=0, len(self.output_names)=0 in [autobackend.py#L465-L477](https://github.com/ultralytics/ultralytics/blob/04f5ba4da051f5684afd60c681f1f6a71e1eb058/ultralytics/nn/autobackend.py#L527-L539), so I add some codes to add these variables to this class with self in [autobackend.py#L242-L257](https://github.com/ultralytics/ultralytics/blob/04f5ba4da051f5684afd60c681f1f6a71e1eb058/ultralytics/nn/autobackend.py#L297-L303).
```
                self.output_names = output_names
                self.fp16 = fp16
                self.binding_addrs = binding_addrs
                self.bindings = bindings
                self.dynamic = dynamic
                self.context = context
```

**the reference website** 
[tensorrt-1000-ea/migration-guide](https://docs.nvidia.com/deeplearning/tensorrt/archives/tensorrt-1000-ea/migration-guide/index.html#trtexec)
[tensorrt-10.0.0 all document](https://docs.nvidia.com/deeplearning/tensorrt/archives/index.html#trt_10)
------------------------------------------------------------------------------------------------------------------
All tests are passed, the test codes I used like below, including the environment in my test computer. I used the yolov8n.pt from github and the yolov8x.pt trained myself to test.

finally, the tensorrt 10.0.06 can really speed up the inference, and reduce the time spending in inference.

``` python []
import os
import gc
import sys
sys.path.append(r'E:\work\codeRepo\deploy\jz\ultralytics')
from ultralytics import YOLO # newest version from "git clone and git pull"
os.environ['CUDA_VISIBLE_DEVICES'] = '0'

'''
Platform: Window11

Ultralytics YOLOv8.1.44 🚀 Python-3.9.18 torch-2.2.1+cu118 CUDA:0 (NVIDIA GeForce RTX 4070 Ti, 12282MiB)

onnx 1.16.0 opset 17

TensorRT 10.0.0b6:  
https://developer.nvidia.com/downloads/compute/machine-learning/tensorrt/10.0.0/zip/TensorRT-10.0.0.6.Windows10.win10.cuda-11.8.zip

nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2022 NVIDIA Corporation
Built on Wed_Sep_21_10:41:10_Pacific_Daylight_Time_2022
Cuda compilation tools, release 11.8, V11.8.89
Build cuda_11.8.r11.8/compiler.31833905_0
'''
if __name__ == '__main__':
    model = YOLO(r'yolov8n.pt')  # load a pretrained model (recommended for training)
    results = model.export(format='onnx', simplify=True, half=True, device='cuda:0')    # onnx,engine
    results0 = model.export(format='engine', simplify=True, half=True, device='cuda:0')    # onnx,engine
    del model
    gc.collect()
    model = YOLO(r"E:\work\yolov8n.engine")
    result = model.predict('https://ultralytics.com/images/bus.jpg', save=True)
```

I have read the CLA Document and I sign the CLA

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@ZouJiu1 thanks for the PR! I'm excited for TRT 10 compatibility. 

Can you try to refactor your PR to reduce code duplication between 7,8 and 10 versions to an absolute minimum? Thank you!

**Comment by glenn-jocher** [comment]
@ZouJiu1 does #9516 by @Burhan-Q solve TRT 10 export for you?

**Comment by glenn-jocher** [comment]
@ZouJiu1 thanks for the changes here! I've taken all of them except the last one, because all local variables are assigned as class attributes by this line, including `output_names`, etc.
```python
self.__dict__.update(locals())  # assign all variables to self
```

**Comment by ZouJiu1** [comment]
> @ZouJiu1 thanks for the PR! I'm excited for TRT 10 compatibility.
> 
> Can you try to refactor your PR to reduce code duplication between 7,8 and 10 versions to an absolute minimum? Thank you!

finding you have done this work in commit [83a26996ff308f7a341a6135a81cc88830995d44](https://github.com/ultralytics/ultralytics/pull/9840/commits/83a26996ff308f7a341a6135a81cc88830995d44). 
I added your modification to this repo, and tests with yolov8n.pt and yolov8x.pt were passed.

thank you.

**Comment by glenn-jocher** [comment]
Hey @ZouJiu1! 🎉 Really appreciate your efforts and quick response. It's fantastic to hear that the changes from commit [83a26996ff308f7a341a6135a81cc88830995d44](https://github.com/ultralytics/ultralytics/pull/9840/commits/83a26996ff308f7a341a6135a81cc88830995d44) have been integrated successfully on your end, and that your tests passed smoothly with both `yolov8n.pt` and `yolov8x.pt`.

Great collaboration! Thanks again for your contribution towards enhancing TRT 10 compatibility. 🚀 Let's continue making YOLOv8 even better together!

**Pull request merged**
