### PR TITLE
Replace explorer notebook with `explorer.md` docs page

### LINKED ISSUE #18458: Docs error in new `mistune` package
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

_No response_

### Bug

Docs build error started today in new `mistune 3.1.0`:

```
INFO    -  Converting notebook (execute=False): /home/runner/work/ultralytics/ultralytics/docs/en/datasets/explorer/explorer.ipynb
ERROR   -  Error reading page 'datasets/explorer/explorer.ipynb': 'MathBlockParser' object has no attribute 'parse_axt_heading'
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.12.8/x64/bin/mkdocs", line 8, in <module>
    sys.exit(cli())
             ^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/click/core.py", line 1161, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/click/core.py", line 1082, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/click/core.py", line 1697, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/click/core.py", line 14[43](https://github.com/ultralytics/ultralytics/actions/runs/12539746413/job/34966190841#step:9:44), in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/click/core.py", line 788, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/mkdocs/__main__.py", line 288, in build_command
    build.build(cfg, dirty=not clean)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/mkdocs/commands/build.py", line 310, in build
    _populate_page(file.page, config, files, dirty)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/mkdocs/commands/build.py", line 167, in _populate_page
    page.render(config, files)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/mkdocs_jupyter/plugin.py", line 123, in new_render
    body = convert.nb2html(
           ^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/mkdocs_jupyter/nbconvert2.py", line 149, in nb2html
    content, resources = exporter.from_filename(
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/exporters/templateexporter.py", line 386, in from_filename
    return super().from_filename(filename, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/exporters/exporter.py", line 201, in from_filename
    return self.from_file(f, resources=resources, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/exporters/templateexporter.py", line 392, in from_file
    return super().from_file(file_stream, resources, **kw)  # type:ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/exporters/exporter.py", line 220, in from_file
    return self.from_notebook_node(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/exporters/html.py", line 268, in from_notebook_node
    html, resources = super().from_notebook_node(nb, resources, **kw)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/exporters/templateexporter.py", line 424, in from_notebook_node
    output = self.template.render(nb=nb_copy, resources=resources)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/jinja2/environment.py", line 1295, in render
    self.environment.handle_exception()
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/jinja2/environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/mkdocs_jupyter/templates/mkdocs_html/notebook.html.j2", line 92, in top-level template code
    {%- set vars = {"cell_id": 0 } -%}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/lab/index.html.j2", line 4, in top-level template code
    {% from 'jupyter_widgets.html.j2' import jupyter_widgets %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line 3, in top-level template code
    {% from 'cell_id_anchor.j2' import cell_id_anchor %}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/base/display_priority.j2", line 1, in top-level template code
    {%- extends 'base/null.j2' -%}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/base/null.j2", line 26, in top-level template code
    {%- block body -%}
    ^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/base/null.j2", line 29, in block 'body'
    {%- block body_loop -%}
^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/base/null.j2", line 31, in block 'body_loop'
    {%- block any_cell scoped -%}
^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/base/null.j2", line 87, in block 'any_cell'
    {%- block markdowncell scoped-%} {%- endblock markdowncell -%}
^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/share/jupyter/nbconvert/templates/lab/base.html.j2", line 109, in block 'markdowncell'
    {%- set html_value=cell.source  | markdown2html | strip_files_prefix -%}
    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/exporters/html.py", line 243, in markdown2html
    return MarkdownWithMath(renderer=renderer).render(source)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/nbconvert/filters/markdown_mistune.py", line [47](https://github.com/ultralytics/ultralytics/actions/runs/12539746413/job/34966190841#step:9:48)1, in __init__
    block = MathBlockParser()
            ^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/site-packages/mistune/block_parser.py", line 111, in __init__
    name: getattr(self, 'parse_' + name) for name in self.SPECIFICATION
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MathBlockParser' object has no attribute 'parse_axt_heading'. Did you mean: 'parse_atx_heading'?
Traceback (most recent call last):
  File "/home/runner/work/ultralytics/ultralytics/docs/build_docs.py", line 309, in <module>
Building docs from /home/runner/work/ultralytics/ultralytics/docs
    main()
  File "/home/runner/work/ultralytics/ultralytics/docs/build_docs.py", line 293, in main
    subprocess.run(f"mkdocs build -f {DOCS.parent}/mkdocs.yml --strict", check=True, shell=True)
  File "/opt/hostedtoolcache/Python/3.12.8/x64/lib/python3.12/subprocess.py", line [57](https://github.com/ultralytics/ultralytics/actions/runs/12539746413/job/34966190841#step:9:58)1, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command 'mkdocs build -f /home/runner/work/ultralytics/ultralytics/mkdocs.yml --strict' returned non-zero exit status 1.
```

### Environment

NA

### Minimal Reproducible Example

```
python docs/build_docs.py
```

### Additional

Linked to https://github.com/lepture/mistune/issues/403

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher @Laughing-q Hi, I think this is the perfect long-term solution :)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
This PR removes support for Jupyter-based documentation while introducing a more robust markdown-based approach for dataset exploration documentation, transitioning the ecosystem fully to Ultralytics HUB for data exploration.  

---

### 📊 Key Changes  
- **Deprecated Jupyter Notebooks**: Removed `explorer.ipynb` files and related dependencies (e.g., `mkdocs-jupyter`).  
- **Introduced Explorer Markdown Docs**: Migrated the dataset Explorer example to a markdown-based format (`explorer.md`).  
- **MkDocs Configuration Update**: Modified `mkdocs.yml` to reflect the removal of the Jupyter plugin and updated navigation to link to the new markdown file.  

---

### 🎯 Purpose & Impact  
- **Purpose**:  
  - Simplify documentation maintenance by shifting from mixed Jupyter and markdown formats to markdown-only.  
  - Encourage users to migrate to Ultralytics HUB, which provides enhanced no-code data exploration features.  

- **Impact**:  
  - Improves documentation accessibility and web compatibility. 📖✨  
  - Reduces reliance on notebook tools, streamlining workflows.  
  - May initially impact users who relied solely on the deprecated Jupyter-based documentation. 🧑‍💻  

This change supports a cleaner, more maintainable future for Ultralytics documentation while promoting the more capable HUB platform. 🚀

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your changes in your PR description and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues), if applicable. Make sure your commit messages are clear and aligned with the project's conventions.
- ✅ **Synchronize with Source**: Ensure your PR is up-to-date with the `main` branch of the [ultralytics repository](https://github.com/ultralytics/ultralytics). If needed, merge or rebase the latest changes to prevent conflicts.
- ✅ **Check CI Pipelines**: Verify that all Continuous Integration (CI) checks have passed. You can reference more about our CI approach in the [help docs](https://docs.ultralytics.com/help/CI/).
- ✅ **Update Documentation**: If you are introducing new features or significantly modifying current ones, update the relevant [documentation](https://docs.ultralytics.com/) to reflect the changes.
- ✅ **Run Tests**: Make sure to add tests where necessary and confirm that all tests pass successfully to prevent regressions.
- ✅ **Sign the CLA**: If this is your first contribution, please sign our [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA" in this PR.
- ✅ **Minimize Changes**: Keep your contributions concise and focused only on what's necessary for the improvement or fix.  

Here's a 📝 summary of your PR:

### 🌟 Summary
This PR transitions the existing Explorer example content from a Jupyter notebook format (`explorer.ipynb`) to a more user-accessible Markdown (`explorer.md`) documentation page. The new documentation includes detailed guides, examples, and explanations to assist users in leveraging the Ultralytics Explorer API for advanced data exploration tasks like semantic searches, SQL queries, and AI-driven natural language analysis. 🐱‍👓

### ⚙️ Key Updates
- Replacing `docs/en/datasets/explorer/explorer.ipynb` notebook file with `docs/en/datasets/explorer/explorer.md`.
- Markdown includes easy-to-follow examples, visuals, and links for better accessibility and user engagement.  
- Highlights key Explorer features such as embeddings creation, similarity search visualization, SQL capabilities, and LanceDB-based raw vector operations.

---

We appreciate your contribution 🙌 and will ensure this PR gets reviewed promptly by an Ultralytics engineer. Thank you for helping to improve our codebase and documentation! 🚀 If you have any further details to add or questions to ask, feel free to comment below.

**Comment by glenn-jocher** [comment]
@RizwanMunawar was going to pin `mistune` to 3.0.2 but this might be a better solution as it should also speed up docs builds.

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes, and also I have optimized the images for that docs page! The total size of images is now reduced from 5MB to 1MB :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar can you also remove the mkdocs-jupyter dependencies since the notebook is removed?

**Comment by RizwanMunawar** [comment]
@glenn-jocher This PR is ready from myside, Once all checks pass, maybe we can merge it. Thank you!

**Comment by UltralyticsAssistant** [comment]
🎉 The PR is officially merged—thank you, @RizwanMunawar and @glenn-jocher, for this fantastic contribution! 🙌 By transitioning from Jupyter Notebooks to markdown for dataset exploration docs, you've made Ultralytics' ecosystem simpler, cleaner, and future-ready. 📖✨

As Marcus Aurelius once said, *"What stands in the way becomes the way."* Your work has navigated challenges and streamlined workflows, making documentation more accessible while paving the path to empower users through the Ultralytics HUB. 🚀 Your efforts will have a lasting impact. Thank you for helping us build a better future, one commit at a time! 💡

**Comment by Laughing-q** [comment]
@RizwanMunawar Nice work on this!!! Thanks!

**Pull request merged**
