### PR TITLE
Fix the incorrect description

### LINKED ISSUE #14061: In cfg.yaml,imgsz comment error
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

In cfg.yaml, the imgsz comment says: ’list[w,h] for predict and export modes', but it is actually read as list[h,w] in the code running.

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by zhixuwei**
The description here about the order of the dimensions of the image is wrong, the correct order is [height, width].

Fix this issue [#14061](https://github.com/ultralytics/ultralytics/issues/14061)

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Minor image size dimension correction in the configuration file.

### 📊 Key Changes
- Adjusted the description for image size (`imgsz`) in the default configuration file to correctly state the order of dimensions for prediction and export modes from `[width, height]` to `[height, width]`.

### 🎯 Purpose & Impact
- **Accuracy**: Ensures the documentation accurately reflects the code's functionality, reducing confusion.
- **User Experience**: Helps users configure image sizes correctly, leading to fewer errors and streamlined workflows.

### CODE REVIEW

**Comment by zhixuwei** [comment]
By tracing the use of the parameter `imgsz`, we can conclude that when the parameter type is list, the correct order is [height, width].
This is a typical example, ultralytics/data/augment py - > the LetterBox: obtain undistorted resize the image.
The value of `new_shape `is derived from the parameter `imgsz`
```python
class LetterBox:
    """Resize image and padding for detection, instance segmentation, pose."""

    def __init__(self, new_shape=(640, 640), auto=False, scaleFill=False, scaleup=True, center=True, stride=32):
        """Initialize LetterBox object with specific parameters."""
        self.new_shape = new_shape
        ...


    def __call__(self, labels=None, image=None):
        """Return updated labels and image with added border."""
        if labels is None:
            labels = {}
        img = labels.get("img") if image is None else image
        shape = img.shape[:2]  # current shape [height, width]
        new_shape = labels.pop("rect_shape", self.new_shape)
        if isinstance(new_shape, int):
            new_shape = (new_shape, new_shape)

        # Scale ratio (new / old)
        r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])
        if not self.scaleup:  # only scale down, do not scale up (for better val mAP)
            r = min(r, 1.0)

        # Compute padding
        ratio = r, r  # width, height ratios
        new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
        dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]  # wh padding
        if self.auto:  # minimum rectangle
            dw, dh = np.mod(dw, self.stride), np.mod(dh, self.stride)  # wh padding
        elif self.scaleFill:  # stretch
            dw, dh = 0.0, 0.0
            new_unpad = (new_shape[1], new_shape[0])
            ratio = new_shape[1] / shape[1], new_shape[0] / shape[0]  # width, height ratios

        if self.center:
            dw /= 2  # divide padding into 2 sides
            dh /= 2

        if shape[::-1] != new_unpad:  # resize
            img = cv2.resize(img, new_unpad, interpolation=cv2.INTER_LINEAR)
        top, bottom = int(round(dh - 0.1)) if self.center else 0, int(round(dh + 0.1))
        left, right = int(round(dw - 0.1)) if self.center else 0, int(round(dw + 0.1))
        img = cv2.copyMakeBorder(
            img, top, bottom, left, right, cv2.BORDER_CONSTANT, value=(114, 114, 114)
        )  # add border
        ...
```

**Comment by zhixuwei** [comment]
In addition, the operation of images in the program is mainly achieved through OpenCV, and its default order of shapes is [height, width, channel]😊

**Comment by glenn-jocher** [comment]
@zhixuwei thank you for your observation! You are absolutely correct that OpenCV uses the [height, width, channel] format for image shapes. This aligns with our internal handling of image dimensions, where the `imgsz` parameter, when provided as a list, follows the [height, width] order.

To ensure clarity and consistency, we will update the documentation to reflect this accurately. If you encounter any further discrepancies or have additional insights, please don't hesitate to share them. Your feedback is invaluable in helping us improve.

If you haven't already, please verify that this issue persists with the latest version of our package. Additionally, providing a minimum reproducible example can greatly assist us in diagnosing and addressing any issues more efficiently. You can find more details on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your contribution to the Ultralytics community! 🚀

**Comment by zhixuwei** [comment]
> @zhixuwei thank you for your observation! You are absolutely correct that OpenCV uses the [height, width, channel] format for image shapes. This aligns with our internal handling of image dimensions, where the `imgsz` parameter, when provided as a list, follows the [height, width] order.
> 
> To ensure clarity and consistency, we will update the documentation to reflect this accurately. If you encounter any further discrepancies or have additional insights, please don't hesitate to share them. Your feedback is invaluable in helping us improve.
> 
> If you haven't already, please verify that this issue persists with the latest version of our package. Additionally, providing a minimum reproducible example can greatly assist us in diagnosing and addressing any issues more efficiently. You can find more details on creating one [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
> 
> Thank you for your contribution to the Ultralytics community! 🚀

@glenn-jocher The incorrect description of the order in which the parameter `imgszis `of type list refers only to the file `ultralytics/cfg/default.yaml`, and the pr has fixed the error description in this file.

Do I need to do other operations on this issue?

**Comment by glenn-jocher** [comment]
Hi @zhixuwei,

Thank you for your prompt response and for addressing the issue in `ultralytics/cfg/default.yaml`. Your fix is much appreciated!

At this point, no further actions are required from your side regarding this issue. We will review your PR and ensure that the documentation reflects the correct order for the `imgsz` parameter as [height, width].

If you encounter any other discrepancies or have additional feedback, please feel free to share. Your contributions are invaluable in helping us maintain the quality and accuracy of our project.

Thank you once again for your diligence and support! 😊

**Comment by glenn-jocher** [comment]
@zhixuwei yes you are correct, thank you for the fix!

**Comment by glenn-jocher** [comment]
@zhixuwei PR merged!

**Comment by zhixuwei** [comment]
> @zhixuwei PR merged!

@glenn-jocher Thank you. That's wonderful news😊

**Comment by glenn-jocher** [comment]
@zhixuwei You're welcome! We're glad to have your contribution merged. If you have any more insights or run into any other issues, feel free to reach out. Your feedback is invaluable to us. Happy coding! 🚀

**Pull request merged**
