### PR TITLE
Add model comparison graphs in `benchmark.md`

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher Users can select models and view graphs that update dynamically based on their checkbox selections.

https://github.com/user-attachments/assets/a73a7e64-5377-4143-a734-0023a36d1393

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR enhances the benchmarking documentation with interactive visualization features for comparing different YOLO models.

### 📊 Key Changes
- Added a new section for **Benchmark Visualization** in the benchmarking documentation.
- Introduced an interactive chart using **Chart.js** to graphically display model performance.
- Users can now select/deselect algorithms like YOLOv5, YOLOv6, YOLOv7, YOLOv8, and others through checkboxes to visualize their speed and mean Average Precision (mAP).
- Included benchmark data for each model showcasing different version metrics (speed and mAP).

### 🎯 Purpose & Impact
- **Purpose:** To provide an intuitive way for users to compare the performance of various YOLO models using an interactive chart, enhancing the user's ability to make informed decisions on model usage.
- **Impact:** This makes it easier for both technical and non-technical users to assess and understand model performance visually, facilitating better insights and comparisons without delving into complex data manually. 🖼️📈

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting a pull request to the `ultralytics` repository! 🚀 We're excited to see contributions that enhance our project. Here's a helpful checklist to ensure your PR process is smooth:

- ✅ **Purpose and Description**: Make sure your PR description clearly explains the purpose of adding model comparison graphs in `benchmark.md`. It would be beneficial to link any [related issues](https://github.com/ultralytics/ultralytics/issues) to provide context.
- ✅ **Keep Up-to-date**: Your PR should be synchronized with the `main` branch of the `ultralytics` repository. If it isn't, please update it by triggering the 'Update branch' button on GitHub or executing `git pull` and `git merge main` commands locally.
- ✅ **CI Check Marks**: Ensure that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass successfully. Address any issues if checks fail to prevent integration delays.
- ✅ **Document Your Changes**: Since you've updated `benchmark.md`, please also verify that all necessary documentation reflects your modifications. Check out this [documentation guide](https://docs.ultralytics.com) for assistance.
- ✅ **Testing**: If your changes affect functionality, consider adding or updating test cases to cover your features. Run all tests to confirm they pass without errors.
- ✅ **CLA Signing**: If this is your first contribution to Ultralytics, you need to sign the [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/). Please write "I have read the CLA Document and I sign the CLA" in a comment on the PR to complete this process.
- ✅ **Minimum Changes**: Aim to keep your PR concise, including only what's essential for the task. Reminder from Bruce Lee, _"It's not the daily increase but daily decrease. Hack away at the unessential."_

For more information on our contribution workflow, please check out the [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions, feel free to add them here or in the relevant issues section. This is an automated message, but rest assured, an Ultralytics engineer will review your PR soon. Thank you for helping advance our platform! 🎉

**Comment by RizwanMunawar** [comment]
Updated version 👍🏻 

Screenshot 2024-10-28 204343

**Comment by RizwanMunawar** [comment]
@glenn-jocher good to merge :) I have performed testing locally and it's working fine 👍🏻

**Comment by glenn-jocher** [comment]
Merged, super cool addition!!!

**Pull request merged**
