### PR TITLE
Add `windows-latest` to CI Tests

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved compatibility and testing across different operating systems and Python environments.

### 📊 Key Changes
- Expanded continuous integration (CI) testing to include `windows-latest` alongside `ubuntu-latest` and `macos-14`.
- Modified test cases for exporting models, using decorators for conditional test skipping based on the operating system, specifically addressing TensorFlow installation conflicts on Windows and macOS.
- Improved error handling and feedback in utility checks, specifically by introducing warnings in `checks.check_imshow()`.

### 🎯 Purpose & Impact
- **Wider Compatibility:** Including Windows in CI testing 🖥️ ensures that the software is more robust and functional across a broader range of systems, reducing user issues related to platform-specific bugs.
- **Enhanced Testing:** The updates in test scripts 🧪 make it clearer when and why certain tests are skipped, leading to a more transparent and manageable testing process.
- **Better User Feedback:** The modified utility checks, especially with the new warning in `check_imshow()`, provide users with clearer guidance and troubleshooting assistance 🛠️, improving the overall user experience.

Ultimately, these changes aim to enhance the reliability and accessibility of Ultralytics' projects, making them more user-friendly and easier to deploy across various environments.

### CODE REVIEW

**Comment by Burhan-Q** [comment]
@glenn-jocher it's odd, the test `tests/test_cli.py::test_train[detect-yolov8n-coco8.yaml]` failed for me locally 

```bash
FAILED tests/test_cli.py::test_train[detect-yolov8n-coco8.yaml] - subprocess.CalledProcessError: Command '['yolo', 'train', 'detect', 'model=yolov8n.yaml', 'data=coco8.yaml', 'imgsz=32', 'epochs=1', 'cache=disk']' re...
=================================================================== 1 failed in 30.05s ===================================================================
```

**Comment by Burhan-Q** [comment]
Maybe the CLI test is getting missed, but the `test_train_scratch` and `test_train_pretrained` shouldn't be missed. 

<details><summary>CI test runner results</summary>
<p>

image
image

</p>
</details> 


The only thing I can think of is that for whatever reason on the runners, the `Dataloader` isn't running with multi-processing. The macOS runner has 3 CPUs and the Windows one has 4 CPUs, but that doesn't seem like it would prevent that from using multi-processing.

**Comment by Burhan-Q** [comment]
I tested locally with `model.train(data="coco8.yaml", workers=0)` and the error wasn't thrown. Looks like this is why:

https://github.com/ultralytics/ultralytics/blob/28cb2f2213e08e0767c8142ec7b1b31d2ded306f/ultralytics/engine/trainer.py#L166-L173

Would it make sense to add `workers=1` to at least one of the CI tests?

**Comment by Burhan-Q** [comment]
If I force CPU training locally, without specifying `workers=0` no error occurs, so it only pops up when using a CUDA device

**Comment by Burhan-Q** [comment]
Looks like I was able to get the tests to fail when going back to using `os.sched_setaffinity` and then adding a check for `TESTS_RUNNING` in `trainer.py` in [aeb02d3](https://github.com/ultralytics/ultralytics/pull/11233/commits/aeb02d33ed27930dcecb5310334cc8fef1a3f3e0).

**Comment by glenn-jocher** [comment]
@Burhan-Q thanks for the edits! Yes you are correct this was the cause. Multiple workers are disabled on CPU and MPS training because the actual forward and backward passes are the bottlenecks in those environments, not the dataloading.

When multiple workers are introduced the tests now cover that code, but there is an extreme slowdown, i.e. 10m -> 17m (before your commit and after your commit) for ubuntu tests to run, which is the reason I disabled them originally on CPU, so I think after seeing the result we should keep this part of the code as-is.

Nice working getting the coverage on that though, which was the original concern here (now we see why it's not covered :)

**Pull request merged**
