### PR TITLE
Remove unused code

### PR DESCRIPTION
**Pull request by glenn-jocher**
### Summary
🗑️🚚🆙

Removed unused and irrelevant constants from `ultralytics/data/augment.py`, `ultralytics/data/utils.py` and `ultralytics/utils/torch_utils.py`. Moved some constants to a more suitable module. Simplified and organized the code according to the latest project dependencies and requirements.

> _`POSE_FLIPLR_INDEX`_
> _Gone with the autumn leaves_
> _Code is simpler now_

### Walkthrough
*  Simplify and update data augmentation module by removing unused and irrelevant constants ([link](https://github.com/ultralytics/ultralytics/pull/4327/files?diff=unified&w=0#diff-8945a175b39a1efcabd4d2fb09b583d2f25409f05038ca9a0f1165e39ee48528L20-L22)) and keeping only the relevant torch version constants ([link](https://github.com/ultralytics/ultralytics/pull/4327/files?diff=unified&w=0#diff-9bd07d929cb8522458c879bd81a82d9af468ffbc215e762f39b2a50a601758d7L28-R28))
*  Move `IMAGENET_MEAN` and `IMAGENET_STD` constants from `ultralytics/data/utils.py` to `ultralytics/utils/general.py` for better code organization and modularity ([link](https://github.com/ultralytics/ultralytics/pull/4327/files?diff=unified&w=0#diff-ec08ff3087043c4949ebd4c16ec17073bdb827e25ff1840d1eb7c87841b8911cL31-L32))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated documentation and code for improved clarity and maintainability.

### 📊 Key Changes
- Reformatted examples in documentation to improve readability.
- Removed certain redundant blocks of code and methods across multiple files, streamlining overall codebase.
- Implemented syntactic and formatting adjustments to enhance maintainability.

### 🎯 Purpose & Impact
- 📚 Clearer documentation makes it easier for users to implement and use Ultralytics AI models.
- 🛠 Reduced code complexity aids future development and reduces potential for errors.
- 🌱 These improvements should facilitate a better user and developer experience with Ultralytics software.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel hey I discovered a lot of unused code inside the repo, so I'm trying to clean it up in this PR. 

I removed a lot of functions from sam, including the entire MaskData class that was unused. I've been doing this by installing pre-commit locally and then uncommenting this dead code checker:

https://github.com/ultralytics/ultralytics/blob/1c753cbce6493654d5c40575d935babdcd463d11/.pre-commit-config.yaml#L70-L73

Not all the suggestions are good, as some functions are used in the dataset YAMLs for example and the checker doesn't see that, but it is catching a lot of unused constants and functions/classes.

**Comment by onuralpszr** [comment]
> @Laughing-q @AyushExel hey I discovered a lot of unused code inside the repo, so I'm trying to clean it up in this PR.
> 
> I removed a lot of functions from SAM, including the entire MaskData class that was unused. I've been doing this by installing pre-commit locally and then uncommenting this dead code checker:
> 
> https://github.com/ultralytics/ultralytics/blob/1c753cbce6493654d5c40575d935babdcd463d11/.pre-commit-config.yaml#L70-L73
> 
> Not all the suggestions are good, as some functions are used in the dataset YAMLs for example and the checker doesn't see that, but it is catching a lot of unused constants and functions/classes.

Just an idea but instead of using "dead" using unittest and Coverage and Coverage can show unused codes and lines as well. %100 Coverage means all codes are used.  In long run using tests with coverage are better

**Comment by AyushExel** [comment]
Looks good @glenn-jocher !

**Comment by glenn-jocher** [comment]
@onuralpszr this is a great idea! I've seen other repos with coverage reports, but I've never used it myself and don't know how to plug it into our CI to generate reports. Could you help us out with this?

In the meantime I'll merge this PR.

**Comment by glenn-jocher** [comment]
@onuralpszr good news, I've started adding Coverage in https://github.com/glenn-jocher/ultralytics, and it seems to be going well. Coverage for our CI is at 54% currently, a little low, but we have a many integrations that we don't test, like the logging integrations and many of the newer models like SAM etc. Either way it seems like a great start to have this info handy. I've also augmented our upcoming docs page with this info, i.e.

Screenshot 2023-08-13 at 15 05 03

I've actual found this isn't quite as useful as dead in finding actual dead code though. A lot of the unused code removed in this PR does actually run, it simply serves no purpose as it's not used anywhere else.

**Comment by onuralpszr** [comment]
> @onuralpszr this is a great idea! I've seen other repos with coverage reports, but I've never used it myself and don't know how to plug it into our CI to generate reports. Could you help us out with this?
> 
> In the meantime I'll merge this PR.

First of course I can help with this I just want focused on other issue I was testing and found bit more problem I had to fix which I did and I see that you did some coverage test which is great and one question how is it that not useful as dead  ? I did not understand this ?

**Comment by onuralpszr** [comment]
A tiny note that I also check coverage you also need to do `negative` tests as well in order to hit negative status codes for example a case cannot but null and If does you do something and so you need to make a null test and make sure you hit that too.

**Comment by glenn-jocher** [comment]
@onuralpszr hmm ok got it! dead was really useful for catching code that runs but that doesn't actually serve any purpose, i.e. I was defining some constants such as TORCH_1_11 that were not used anywhere, so the code shows as covered, but it's actually a dead end. 

Coverage is super useful also though of course :)

It's helping me see I need to run more tests on it now, and we probably have significant duplication of some code regions too, i.e. running both CLI and Python tests of the same thing, like a torchscript export.

**Comment by onuralpszr** [comment]
> I was defining some constants such as TORCH_1_11 that were not used anywhere, so the code shows as covered, but it's actually a dead end.

that is TRUE it is going to load as variable but can you give it a shot for this tool

https://github.com/jendrikseipp/vulture 

I know you just added dead but check vulture too If you did not

**Comment by glenn-jocher** [comment]
@onuralpszr oh awesome ok, I'll check out vulture. No I didn't add dead, I only added locally for some manual runs of pre-commit but it's still commented in main branch.

**Comment by glenn-jocher** [comment]
@onuralpszr full code coverage now added in https://github.com/ultralytics/ultralytics/pull/4336! 

This is great, a huge improvement. We have some work to do and now we can see it.

**Comment by onuralpszr** [comment]
@glenn-jocher awesome let me know what you need so I can also do help and make sure cover more code :))

**Pull request merged**
