### PR TITLE
fast and simple process batch

### PR DESCRIPTION
**Pull request by yermandy**
### Summary
🚀🧹🕺

Simplify and optimize the validation logic for both detection and pose models in `ultralytics/models/yolo/detect/val.py` and `ultralytics/models/yolo/pose/val.py` by using PyTorch tensors and operations instead of numpy arrays and loops. Handle edge cases and improve code readability and performance.

> _`DetectionValidator`_
> _Simpler, faster, consistent_
> _Autumn of the code_

### Walkthrough
*  Simplify and optimize the logic for calculating correct detections and poses based on IoU and class matching using PyTorch tensors and operations ([link](https://github.com/ultralytics/ultralytics/pull/3889/files?diff=unified&w=0#diff-023bb20ae0db3d69310690d02fbea0e2a6d57e5cf3878f00ea1cd097761fd7b5L161-R175), [link](https://github.com/ultralytics/ultralytics/pull/3889/files?diff=unified&w=0#diff-87c04c65554f867c15a5425248ea5642ba95c9ed23cca06db823a369d47d1d9fL127-R142))
*  Handle the edge case where there are no detections or labels by returning an empty tensor of the correct shape and device ([link](https://github.com/ultralytics/ultralytics/pull/3889/files?diff=unified&w=0#diff-023bb20ae0db3d69310690d02fbea0e2a6d57e5cf3878f00ea1cd097761fd7b5L161-R175), [link](https://github.com/ultralytics/ultralytics/pull/3889/files?diff=unified&w=0#diff-87c04c65554f867c15a5425248ea5642ba95c9ed23cca06db823a369d47d1d9fL127-R142))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimized true positive calculation in Ultralytics YOLO detection validation.

### 📊 Key Changes
- Replaced a manual loop for determining true positives with a vectorized approach.
- Introduced a check for empty IoU matrix to handle edge cases gracefully.
- Simplified the code by using PyTorch operations for class matching and IoU thresholding.

### 🎯 Purpose & Impact
- 🚀 **Efficiency**: The new approach is likely more computationally efficient, reducing validation time.
- 🛠 **Reliability**: By handling cases with no IoU matches, the code is now more robust.
- 🧑‍💻 **Code Quality**: Cleaner, more readable code makes future maintenance easier.
- 📈 **User Experience**: Users can expect faster model evaluation with potentially more accurate validation results.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@yermandy I tested this PR and the results are not aligned with the existing metrics (i.e. the mAP is incorrect in this PR).

### Detect model benchmarks in `main` branch:
Screenshot 2023-07-22 at 16 45 49


### This PR

Screenshot 2023-07-22 at 16 48 02

**Comment by yermandy** [comment]
Hello everybody, I have a question as well as a proposal.

First, the question: Is there a reason why each `process_batch` function looks so complicated involving transfer between `torch` and `numpy`, a few `np.unique`, `torch.cat`, `torch.where` operations? It is also not vectorised. Proposal: Why do not we just directly say that something is true positive if class is correct and iou is above the threshold.

Besides the fact, that my solution is **much** faster, it gives better results. It also gives slightly different results:

f1
prc

Is there anyone who has explanation for this? I think my implementation should be correct in principle. Do I miss something?

**Comment by yermandy** [comment]
@glenn-jocher I agree that mAP is different (something I have also noticed) but I cannot find any problem (edge case where the logic does not hold) with the proposed solution

**Comment by glenn-jocher** [comment]
@yermandy yes, the reason for the numpy ops is that the numpy ops in the current loop are actually faster than the same PyTorch ops. 

We don't really have much flexibility to modify mAP calculations, these have to be exact and never change over time. We currently compare against pycocotools as our reference, it is widely interpreted as the gold standard in mAP calculation, but it is very slow, hence the Ultralytics implementation. 

What we need here is a before/after comparison of repo-mAP vs pycocotools mAP on the COCO dataset. If the differences are the same or smaller then your implementation would merit consideration, but these are places that we must be extremely careful with any modifications.

**Comment by glenn-jocher** [comment]
@yermandy also I think you might be seeing higher mAP from yours and assuming this is "better", when it may simply be less accurate representation of the true/pycocotools mAP.

**Comment by yermandy** [comment]
@glenn-jocher got it, thank you for your clarification!

**Comment by glenn-jocher** [comment]
@yermandy you're welcome! If you have any more questions or need further clarification, please don't hesitate to ask. I'm here to help. Remember, while performance improvements are valuable, we prioritize maintaining accuracy and precision, especially when it comes to something like mAP calculations. Changes in these critical areas need to be rigorously tested against established standards like pycocotools. Happy coding!

**Comment by glenn-jocher** [comment]
@yermandy I've tested this PR on YOLOv8n with COCO val, and it is producing a incorrect mAP value vs main branch. The only way we can consider any modifications to our mAP computation is if your PR produces identical or closer results to pycocotools. 


### Main branch: 37.1 mAP vs 37.3 pycocotools mAP (very close)
```bash
yolo val model=yolov8n.pt data=coco.yaml

Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100% 6.23M/6.23M [00:00<00:00, 59.4MB/s]
Ultralytics YOLOv8.0.141 🚀 Python-3.10.6 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...
100% 755k/755k [00:00<00:00, 17.0MB/s]
val: Scanning /content/datasets/coco/labels/val2017... 4952 images, 48 backgrounds, 0 corrupt: 100% 5000/5000 [00:03<00:00, 1587.33it/s]
val: New cache created: /content/datasets/coco/labels/val2017.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 313/313 [01:22<00:00,  3.78it/s]
                   all       5000      36335      0.633      0.475      0.521      0.371
                person       5000      10777      0.754      0.673      0.745      0.514
               bicycle       5000        314      0.687      0.392      0.457      0.265
                   car       5000       1918      0.646      0.515      0.561      0.364
            motorcycle       5000        367       0.71       0.58      0.655      0.413
              airplane       5000        143      0.814      0.766      0.832      0.653
                   bus       5000        283      0.746      0.643      0.739       0.62
                 train       5000        190      0.798       0.77      0.834      0.646
                 truck       5000        414      0.549      0.399      0.435      0.293
                  boat       5000        424      0.583        0.3      0.377       0.21
         traffic light       5000        634      0.644      0.345      0.409      0.211
          fire hydrant       5000        101       0.85      0.703      0.774      0.609
             stop sign       5000         75      0.695       0.64      0.692       0.63
         parking meter       5000         60      0.631        0.5      0.558      0.441
                 bench       5000        411       0.57      0.258      0.296      0.193
                  bird       5000        427      0.686      0.358      0.425      0.278
                   cat       5000        202      0.776      0.824      0.856      0.652
                   dog       5000        218      0.656      0.701      0.729      0.591
                 horse       5000        272        0.7      0.653      0.693      0.525
                 sheep       5000        354      0.609      0.667      0.662       0.46
                   cow       5000        372      0.697      0.601      0.682      0.487
              elephant       5000        252      0.702      0.833      0.821      0.629
                  bear       5000         71      0.847      0.775      0.842      0.689
                 zebra       5000        266      0.808      0.797      0.882      0.658
               giraffe       5000        232      0.857      0.828      0.885      0.683
              backpack       5000        371      0.489      0.156      0.197        0.1
              umbrella       5000        407      0.631      0.504      0.542      0.359
               handbag       5000        540      0.479      0.126      0.169     0.0848
                   tie       5000        252      0.686      0.361      0.429      0.268
              suitcase       5000        299      0.566      0.431      0.502      0.342
               frisbee       5000        115      0.748      0.774      0.767      0.584
                  skis       5000        241      0.609      0.323      0.366      0.188
             snowboard       5000         69      0.483      0.319      0.388      0.266
           sports ball       5000        260      0.713      0.438      0.474      0.329
                  kite       5000        327      0.605       0.52      0.558       0.38
          baseball bat       5000        145      0.585      0.386      0.403      0.216
        baseball glove       5000        148      0.669      0.473      0.512      0.302
            skateboard       5000        179      0.721      0.608      0.663      0.451
             surfboard       5000        267      0.624      0.473      0.507      0.309
         tennis racket       5000        225      0.702      0.618      0.671      0.397
                bottle       5000       1013      0.612      0.387      0.454      0.298
            wine glass       5000        341      0.659      0.352       0.42       0.27
                   cup       5000        895      0.584      0.443      0.488       0.35
                  fork       5000        215      0.583      0.318      0.389      0.263
                 knife       5000        325      0.505      0.163      0.174      0.106
                 spoon       5000        253       0.41      0.146       0.16     0.0988
                  bowl       5000        623      0.589      0.494      0.529       0.39
                banana       5000        370      0.549      0.319      0.374      0.233
                 apple       5000        236      0.414      0.242      0.227      0.156
              sandwich       5000        177       0.57      0.486      0.463      0.349
                orange       5000        285      0.439      0.418      0.369      0.281
              broccoli       5000        312      0.476       0.34      0.368      0.209
                carrot       5000        365      0.446      0.293      0.307      0.189
               hot dog       5000        125       0.76      0.432      0.497      0.364
                 pizza       5000        284      0.658      0.613      0.658      0.503
                 donut       5000        328      0.575      0.494      0.515      0.408
                  cake       5000        310      0.533       0.39      0.437      0.292
                 chair       5000       1771      0.581       0.34      0.403      0.257
                 couch       5000        261      0.593      0.552      0.585      0.434
          potted plant       5000        342      0.521      0.386      0.385      0.225
                   bed       5000        163       0.55      0.552      0.589      0.427
          dining table       5000        695      0.529       0.44      0.435      0.293
                toilet       5000        179      0.721      0.737      0.775      0.642
                    tv       5000        288      0.771      0.635      0.715      0.553
                laptop       5000        231      0.682      0.662      0.699       0.58
                 mouse       5000        106      0.634      0.651      0.708      0.527
                remote       5000        283       0.43      0.223       0.27       0.16
              keyboard       5000        153      0.595      0.604       0.65      0.482
            cell phone       5000        262      0.548      0.351        0.4       0.28
             microwave       5000         55      0.616      0.545      0.643      0.514
                  oven       5000        143      0.643      0.448      0.511      0.349
               toaster       5000          9      0.726      0.222      0.436      0.314
                  sink       5000        225      0.568      0.444      0.508      0.337
          refrigerator       5000        126      0.662      0.587       0.65      0.511
                  book       5000       1129      0.489      0.111      0.197     0.0969
                 clock       5000        267       0.75      0.607      0.667      0.457
                  vase       5000        274      0.588      0.453      0.453      0.321
              scissors       5000         36      0.689      0.333      0.332      0.278
            teddy bear       5000        190      0.669      0.558      0.604       0.42
            hair drier       5000         11          1          0    0.00492    0.00377
            toothbrush       5000         57      0.402      0.193      0.236      0.164
Speed: 0.3ms preprocess, 4.1ms inference, 0.0ms loss, 1.3ms postprocess per image
Saving runs/detect/val/predictions.json...

Evaluating pycocotools mAP using runs/detect/val/predictions.json and /content/datasets/coco/annotations/instances_val2017.json...
loading annotations into memory...
Done (t=0.39s)
creating index...
index created!
Loading and preparing results...
DONE (t=2.33s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=79.18s).
Accumulating evaluation results...
DONE (t=16.35s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.373
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.185
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.410
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.535
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.320
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.588
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.366
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.653
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.768
Results saved to runs/detect/val
```

## This PR: 40.2 mAP vs 37.3 pycocotools mAP (indicates incorrect PR mAP)

```bash
yolo val model=yolov8n.pt data=coco.yaml

Downloading https://github.com/ultralytics/assets/releases/download/v0.0.0/yolov8n.pt to 'yolov8n.pt'...
100% 6.23M/6.23M [00:00<00:00, 310MB/s]
Ultralytics YOLOv8.0.141 🚀 Python-3.10.6 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients
Downloading https://ultralytics.com/assets/Arial.ttf to '/root/.config/Ultralytics/Arial.ttf'...
100% 755k/755k [00:00<00:00, 110MB/s]
val: Scanning /content/datasets/coco/labels/val2017... 4952 images, 48 backgrounds, 0 corrupt: 100% 5000/5000 [00:02<00:00, 2185.00it/s]
val: New cache created: /content/datasets/coco/labels/val2017.cache
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100% 313/313 [01:14<00:00,  4.21it/s]
                   all       5000      36335      0.581      0.571      0.631      0.402
                person       5000      10777       0.72      0.798      0.868      0.558
               bicycle       5000        314      0.619      0.529      0.665      0.321
                   car       5000       1918      0.601      0.655      0.708      0.402
            motorcycle       5000        367      0.679      0.736      0.829      0.472
              airplane       5000        143      0.737       0.88      0.929      0.687
                   bus       5000        283      0.657      0.724      0.801      0.636
                 train       5000        190      0.723      0.821       0.91      0.675
                 truck       5000        414       0.46       0.49      0.484      0.296
                  boat       5000        424      0.558      0.465      0.581      0.267
         traffic light       5000        634      0.598      0.453       0.57       0.25
          fire hydrant       5000        101      0.783      0.723      0.831      0.622
             stop sign       5000         75      0.582       0.64       0.71      0.637
         parking meter       5000         60      0.603      0.582      0.682      0.474
                 bench       5000        411      0.475      0.333      0.407      0.223
                  bird       5000        427      0.582      0.445       0.54      0.306
                   cat       5000        202      0.725      0.881      0.903      0.664
                   dog       5000        218      0.647      0.794      0.809      0.611
                 horse       5000        272      0.695      0.755      0.818      0.566
                 sheep       5000        354      0.576      0.797      0.753      0.483
                   cow       5000        372      0.643      0.694       0.79      0.521
              elephant       5000        252      0.711      0.958      0.885      0.656
                  bear       5000         71      0.808      0.831      0.908      0.707
                 zebra       5000        266      0.794      0.897      0.956      0.691
               giraffe       5000        232      0.877      0.923      0.968      0.719
              backpack       5000        371      0.379      0.224      0.287      0.121
              umbrella       5000        407      0.637      0.698       0.75      0.419
               handbag       5000        540       0.41      0.194      0.256      0.103
                   tie       5000        252      0.659       0.48      0.643      0.332
              suitcase       5000        299      0.537      0.554      0.626      0.381
               frisbee       5000        115      0.649        0.8       0.82      0.602
                  skis       5000        241      0.521      0.437      0.571      0.244
             snowboard       5000         69      0.426      0.463      0.518      0.307
           sports ball       5000        260      0.634      0.452      0.502      0.338
                  kite       5000        327      0.551      0.612      0.648      0.406
          baseball bat       5000        145      0.643       0.62      0.702       0.29
        baseball glove       5000        148      0.587      0.561      0.624      0.333
            skateboard       5000        179      0.698      0.697      0.808      0.498
             surfboard       5000        267      0.602       0.64      0.721      0.375
         tennis racket       5000        225      0.708      0.778      0.848      0.463
                bottle       5000       1013       0.55        0.5      0.578      0.332
            wine glass       5000        341      0.565      0.422      0.535      0.292
                   cup       5000        895      0.505      0.523      0.553      0.364
                  fork       5000        215      0.527       0.42      0.543      0.309
                 knife       5000        325      0.386      0.209      0.275      0.131
                 spoon       5000        253      0.362      0.209      0.257      0.124
                  bowl       5000        623        0.5      0.589      0.599      0.406
                banana       5000        370      0.516      0.451      0.529      0.276
                 apple       5000        236      0.382      0.309       0.29      0.172
              sandwich       5000        177       0.46       0.52      0.506      0.353
                orange       5000        285      0.387      0.495      0.409      0.286
              broccoli       5000        312      0.448       0.49      0.481      0.241
                carrot       5000        365      0.389      0.436      0.411      0.217
               hot dog       5000        125      0.648        0.5      0.685      0.401
                 pizza       5000        284      0.623      0.694      0.735       0.53
                 donut       5000        328      0.509      0.567      0.579      0.426
                  cake       5000        310      0.506      0.495      0.539       0.32
                 chair       5000       1771      0.504      0.453      0.533       0.29
                 couch       5000        261      0.506      0.632      0.637      0.426
          potted plant       5000        342       0.44      0.462      0.496      0.258
                   bed       5000        163      0.547      0.725      0.728      0.467
          dining table       5000        695      0.483      0.551       0.56      0.332
                toilet       5000        179      0.689       0.83      0.884      0.674
                    tv       5000        288      0.688      0.719      0.798      0.579
                laptop       5000        231      0.667      0.762      0.812      0.609
                 mouse       5000        106      0.632      0.755      0.795      0.559
                remote       5000        283      0.408      0.318      0.368      0.185
              keyboard       5000        153      0.549      0.719       0.77      0.525
            cell phone       5000        262      0.505      0.412      0.491      0.303
             microwave       5000         55      0.553      0.618      0.691      0.531
                  oven       5000        143      0.574      0.615      0.684        0.4
               toaster       5000          9      0.494      0.222      0.442      0.315
                  sink       5000        225      0.579      0.618      0.674      0.387
          refrigerator       5000        126      0.637      0.706      0.776      0.548
                  book       5000       1129      0.444      0.247      0.345      0.135
                 clock       5000        267      0.701      0.652      0.763      0.482
                  vase       5000        274      0.493      0.546      0.535      0.341
              scissors       5000         36      0.563      0.333      0.413      0.294
            teddy bear       5000        190      0.638      0.676      0.756      0.467
            hair drier       5000         11          1          0    0.00492    0.00377
            toothbrush       5000         57      0.418      0.298      0.384      0.209
Speed: 0.3ms preprocess, 4.1ms inference, 0.0ms loss, 1.7ms postprocess per image
Saving /content/ultralytics/runs/detect/val/predictions.json...

Evaluating pycocotools mAP using /content/ultralytics/runs/detect/val/predictions.json and /content/datasets/coco/annotations/instances_val2017.json...
loading annotations into memory...
Done (t=0.59s)
creating index...
index created!
Loading and preparing results...
DONE (t=3.50s)
creating index...
index created!
Running per image evaluation...
Evaluate annotation type *bbox*
DONE (t=78.41s).
Accumulating evaluation results...
DONE (t=17.35s).
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.373
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.525
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.405
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.185
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.410
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.535
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.320
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.532
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.588
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.366
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.653
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.768
Results saved to /content/ultralytics/runs/detect/val
```

**Comment by yermandy** [comment]
This is quite satisfying for me now, I am crossing the PR. If someone is interested, this is what I did:

In here: 
https://github.com/ultralytics/ultralytics/blob/15f79d6f35f2921ab04dc5db22b23edf4088bae5/ultralytics/models/yolo/pose/val.py#L53

``` python
    def update_metrics(self, preds, batch):
        """Metrics."""
        for k, v in batch.items():
            if isinstance(v, torch.Tensor):
                batch[k] = v.cpu()
            
        for si, pred in enumerate(preds):
            pred = pred.cpu()
        
        ... # rest of the function
```

Also, replace `self.device` with `pred.device` everywhere in this function

**Comment by yermandy** [comment]
I also noticed that for my machine, doing nms on cpu is much faster. Which means that everything after forward pass can be computed on cpu. For convenience, I added parameter to `default.yaml` which when active, transfers resources back to cpu after the forward pass is done.

**Comment by glenn-jocher** [comment]
@yermandy thank you for your helpful feedback and proposed improvements. These are good catch and could certainly benefit those with different hardware configurations who aim for speed optimization.

Performing non-maximum suppression (NMS) calculations on the CPU instead of the GPU can potentially be more efficient for certain hardware configurations. Moreover, judicious resource management, such as transferring data back to the CPU after certain computations and avoiding unnecessary data transfers, can indeed save considerable computational resources and time. It's a great idea to add a parameter in the `default.yaml` to control this behavior.

However, as different users may have different hardware configurations, the most efficient approach can vary. We'll consider incorporating these changes, as it is essential to provide options for users to optimize according to their specific setups.

In terms of your observation about `batch["img"]` not being used after the forward pass, this is a valuable insight. Another computational saving can be achieved by avoiding unnecessary movements of this data back and forth to the CPU.

Please remember that while these improvements work well for your specific scenario, they may not be universally optimal, so we welcome further feedback and recommendations from the wider community to continuously optimize the YOLOv8 model.

**Pull request closed without merging**
