### PR TITLE
`ultralytics 8.3.28` new Solutions CLI commands

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher Hi, this is the [Ultralytics Solutions](https://docs.ultralytics.com/solutions/#solutions) CLI Pull Request. With this update, users can now directly use solutions through the CLI, while API support remains fully available. No changes to documentation or user-side adjustments are needed for arguments or method calls. To access the CLI functionality, users simply need to upgrade the Ultralytics Python Package.

### Usage

```sh

# Run the default counting solution   
yolo solutions   # If no source is provided, the default video will be downloaded from assets.

# Specify a solution with a custom video source
yolo solutions count source="path/to/video/file.mp4"

# Use different solution types with a defined source
yolo solutions heatmap source="path/to/video/file.mp4"
yolo solutions queue source="path/to/video/file.mp4"
yolo solutions workout source="path/to/video/file.mp4"
yolo solutions speed source="path/to/video/file.mp4"

# Use heatmap with object counting
yolo solutions heatmap region=[(20, 400), (1080, 404), (1080, 360), (20, 360)]

# Analytics solution with a specific chart type
yolo solutions analytics analytics_type="pie" source="path/to/video/file.mp4"
yolo solutions analytics analytics_type="bar" source="path/to/video/file.mp4"
yolo solutions analytics analytics_type="line" source="path/to/video/file.mp4"
yolo solutions analytics analytics_type="area" source="path/to/video/file.mp4"
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This update introduces a new feature enabling the execution of predefined solutions within the YOLO ecosystem through a command-line interface.

### 📊 Key Changes
- **Solution Command Integration**: Added a new CLI handler `yolo solutions` for processing predefined computer vision tasks such as object counting, heatmaps, and more.
- **Documentation Update**: Enhanced guides to include CLI and Python examples for each solution.
- **Workflow Adjustments**: Minor updates to GitHub actions for continuous integration and documentation generation.
- **Version Bump**: Incremented version from 8.3.27 to 8.3.28.

### 🎯 Purpose & Impact
- **Simplified Solution Execution**: Users can now easily run complex computer vision tasks with simple CLI commands, enhancing usability for non-programmers. 📂
- **Expanded Analytic Capabilities**: New solutions offer tools like speed estimation and queue management, aiding in domains like video surveillance and traffic monitoring. 🎥
- **Improved Documentation**: Better guidance for users on how to leverage these new capabilities effectively. 📝

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a smooth integration of your work, we've outlined some essential steps below. An Ultralytics engineer will review your PR soon! 😊

- ✅ **Define a Purpose**: Please ensure your PR description clearly explains the purpose and scope of the changes you've implemented, and consider linking any relevant [issues](https://github.com/ultralytics/ultralytics/issues). It's important to ensure your commit messages are clear and adhere to our conventions.
- ✅ **Synchronize with Source**: Verify that your branch is up to date with the `ultralytics/ultralytics` `main` branch. If it's not, you can update it by clicking the 'Update branch' button on the PR page or by executing `git pull` and `git merge main` in your local repository.
- ✅ **Ensure CI Checks Pass**: Make sure that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are green. If any checks fail, please address these before a final review.
- ✅ **Update Documentation**: Any new or modified features should be accompanied by updates to our [documentation](https://docs.ultralytics.com) to ensure that users can make the most of your enhancements.
- ✅ **Add Tests**: Consider adding or updating tests to cover your changes. It's crucial that all tests pass successfully.
- ✅ **Sign the CLA**: If this is your inaugural contribution to Ultralytics, you will need to read and sign our [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/). You can do so by commenting "I have read the CLA Document and I sign the CLA" in this PR.
- ✅ **Minimize Changes**: Aim to limit your changes to only what's necessary for this enhancement or fix, making it easier to understand and review.

For more detailed guidance, please check out our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions or require further clarification, feel free to ask in the comments. Thank you for your contribution to making Ultralytics even better! 🚀

**Comment by glenn-jocher** [comment]
@RizwanMunawar looks good!

One thing we need for CLI is automatic running of commands without arguments, i.e. `yolo predict`, `yolo val`, `yolo train`, etc all work without any additional arguments for quick demos. Can you update this PR to do the same here?

This would mean that we have official videos/images for the solutions that we download from the assets if they are not present locally.

**Comment by RizwanMunawar** [comment]
### New Usage

```sh
yolo solutions  # be default object counting solution will be called.
yolo solutions heatmap args  # call the heatmap solution with args
yolo solutions queue args  # call the queue solution with args
```

**Comment by RizwanMunawar** [comment]
**Solutions Help**

Added new command `yolo solutions-help` for displaying the usage information for [Ultralytics Solutions](https://docs.ultralytics.com/solutions/).

**Message**

```
Arguments received: ['yolo', 'solutions-help']. Ultralytics 'yolo solutions' usage overview:

      yolo SOLUTIONS SOLUTION ARGS

      Where SOLUTIONS (required) is a keyword
            SOLUTION (optional) is one of ['count', 'heatmap', 'queue', 'speed', 'workout', 'analytics']
            ARGS (optional) are any number of custom 'arg=value' pairs like 'show_in=True' that override defaults.
              See all ARGS at https://docs.ultralytics.com/usage/cfg or with 'yolo cfg'

  1. Call object counting solution
      yolo solutions count source="path/to/video/file.mp4" region=[(20, 400), (1080, 404), (1080, 360), (20, 360)]

  2. Call heatmaps solution
      yolo solutions heatmap colormap=cv2.COLORMAP_PARAULA model=yolo11n.pt

  3. Call queue management solution
      yolo solutions queue region=[(20, 400), (1080, 404), (1080, 360), (20, 360)] model=yolo11n.pt

  4. Call workouts monitoring solution for push-ups
      yolo solutions workout model=yolo11n-pose.pt kpts=[6, 8, 10]
```

**Comment by glenn-jocher** [comment]
@RizwanMunawar looks good!

**Comment by glenn-jocher** [comment]
@RizwanMunawar I reviewed the changes and they look good. We want to keep all CLI argument handling inside cfg/init like we're going now, but we want all actual method running to happen within the solutions, including any downloading of assets and dimensions/directories etc. that may be required. Can you move this code into the Solutions themselves (maybe in the base solutions class)?

Also we want "help" to just be another type of solution command like "yolo solutions heatmap", i.e. "yolo solutions help", which just displays the help options.

**Comment by RizwanMunawar** [comment]
@glenn-jocher sure, I will update the things accordingly. Thanks 👍🏻

**Comment by glenn-jocher** [comment]
@RizwanMunawar PR merged!

**Pull request merged**
