### PR TITLE
Update OBB predict examples with boats.jpg

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR updates the default image used in examples and configurations from a bus to a boat image for the YOLO model.

### 📊 Key Changes
- Changed example image in the documentation from "bus.jpg" to "boats.jpg".
- Updated URLs for sample images in multiple documentation files and a tutorial notebook.
- Adjusted the default source in the configuration files for object bounding box (OBB) tasks to use a boat image.

### 🎯 Purpose & Impact
- **Consistency Improvement**: Aligns all training and prediction examples to consistently use a boat image, which may provide a more relevant context for users working with certain datasets.
- **User Clarity**: Helps users more easily follow tutorials and examples as they interface with the more commonly referenced "boats.jpg" image, enhancing learning and troubleshooting experiences.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For a more efficient review, we recommend ensuring that your changes are minimal and focused on the core implementation of the OBB support you are introducing. If you haven't done so already, please provide a brief test case or example (MRE) demonstrating the integration and functionality of the OBB features. This will help us immensely in understanding and validating your contributions. 😊

This is an automated response, and an Ultralytics engineer will also assist you soon. For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

**Comment by jk4e** [comment]
Hi @RizwanMunawar,

Great enhancement! I've also been thinking about this for a while but wasn't sure about the process of adding it to the Ultralytics Assets Repository. Could you also add those images there? Then we (I can try to submit a PR here) could update the examples for OBB in the docs and notebooks to make more sense. Currently, 'https://ultralytics.com/images/bus.jpg' is used, and the result clearly doesn't make sense for OBB (it may even confuse more users than help):

E.g., final output of the predict examples from [Docs - Tasks - OBB - Predict](https://docs.ultralytics.com/tasks/obb/#predict) (Bus is clearly not a tennis court. Example images make totally now sens here)

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolo11n-obb.pt")  # load an official model
model = YOLO("path/to/best.pt")  # load a custom model

# Predict with the model
results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image
```


output2

**Note:** Minor thing: Would it be better to convert those `.png` files to `.jpg` as well? This would make them consistent with the other images in assets like 'bus.jpg' and 'zidane.jpg'.

Thanks! 🚀

**Comment by RizwanMunawar** [comment]
@jk4e Hi, Nice feedback! Yes, this is something we have been discussing for some time. Regarding your queries here is my response :)

**1 - I've also been thinking about this for a while but wasn't sure about the process of adding it to the Ultralytics Assets Repository. Could you also add those images there?**
- The processed images are already added in the [OBB Docs.](https://docs.ultralytics.com/tasks/obb/#visual-samples)

**2- Do we need to change any code examples?**
- Well, we don't need to change anything. When the user calls `yolo obb predict` or `yolo obb track`, by default OBB assets will be used. Yes in the [OBB Predict code snippet](https://docs.ultralytics.com/tasks/obb/#predict) `results = model("https://ultralytics.com/images/bus.jpg")` we will need to replace the path with obb asset path i.e i.e `https://ultralytics.com/images/vehicles.jpg`. Can you please make this change? Other than that, everything is good to go. I have updated the notebook section for OBB where changes were required :) 

**3-  Would it be better to convert those .png files to .jpg as well? This would make them consistent with the other images in assets like 'bus.jpg' and 'zidane.jpg'?**
- Yes you are right. I have updated the image extension to match with other assets extensions and good to go :)

**Edit:** Maybe you can make changes in this PR directly 👍🏻 

Thanks! 🚀

**Comment by Laughing-q** [comment]
@RizwanMunawar The idea is good! Nice job! In my opinion I think we probably just want one more image and put it together with current `bus.jpg` and `zidane.jpg` in the same directory.
@glenn-jocher

**Comment by RizwanMunawar** [comment]
@Laughing-q Thanks for reviewing :) I have updated things accordingly. I was thinking, maybe it would be better to add OBB images in a different folder :)

@Jk4e Hi, I have updated the notebook and docs. In case anything is missing, you can update :)

@glenn-jocher need your feedback on this, please. Thanks

**Review by Laughing-q — APPROVED** [review]

**Comment by Laughing-q** [comment]
@RizwanMunawar Is it possible to compress the image a bit? like we usually do for images we stick in docs? or you've already done that?

**Comment by RizwanMunawar** [comment]
@Laughing-q Yes, I have already compressed it :)

**Comment by jk4e** [comment]
@RizwanMunawar found some missing examples and updated them. Unfortunately, I tried to commit it directly to the branch, but had to create a PR #17072. (no access, or did I do something wrong?)

```
jk4e@jk4e:~/project/ultralytics$ git checkout -b obb_assets upstream/obb_assets
Branch 'obb_assets' set up to track remote branch 'obb_assets' from 'upstream'.
Switched to a new branch 'obb_assets'
jk4e@jk4e::~/project/ultralytics$ git add .
jk4e@jk4e:~/project/ultralytics$ git commit -m "Update examples in docs"
[obb_assets 169732e8] Update examples in docs
 2 files changed, 3 insertions(+), 3 deletions(-)
jk4e@jk4e::~/project/ultralytics$ git push upstream obb_assets

```

Error message:
```
remote: Permission to ultralytics/ultralytics.git denied to jk4e.
fatal: unable to access 'https://github.com/ultralytics/ultralytics.git/': The requested URL returned error: 403
```

**Comment by RizwanMunawar** [comment]
@jk4e Ah I see, Thanks for the quick fixes, Yes no worries, separate PR is also good. Let me try to merge it into this branch :)

**Comment by RizwanMunawar** [comment]
@glenn-jocher Hi, based on your feedback the obb image ("boats.jpg") has been removed from the repository, this image is uploaded in the assets :)

I have tested the changes locally and it's working fine. Thanks

**Review by glenn-jocher — APPROVED** [review]

**Pull request merged**
