### PR TITLE
Optimize new absolute confusion matrix

### PR DESCRIPTION
**Pull request by darouwan**
1. When normalized=False, output int in confusion matrix
2. Add confusion_matrix_normalized.png in clearml

### Summary
📊🔄🔎

This pull request enhances the confusion matrix functionality for the YOLOv5 model and its integration with ClearML. It adds the option to log and visualize the normalized confusion matrix in `clearml.py` and to format the values as floats or integers in `metrics.py`.

> _`ClearML` callback_
> _logs confusion matrix plots_
> _autumn of learning_

### Walkthrough
* Enable normalized confusion matrix visualization for ClearML callback ([link](https://github.com/ultralytics/ultralytics/pull/2472/files?diff=unified&w=0#diff-a815296cb22a8ba6127487e136b0996e9885c93d79f23f92ad858437b2c9af66L122-R122))
* Add conditional formatting option to `ConfusionMatrix.plot` method ([link](https://github.com/ultralytics/ultralytics/pull/2472/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL330-R330))

Optimize new confusion matrix
1. When normalized=False, output int in confusion matrix
2. Add confusion_matrix_normalized.png in clearml

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of Training Results Visualization in Callbacks

### 📊 Key Changes
- Added 'confusion_matrix_normalized.png' to the list of files logged at the end of training in ClearML and Neptune callbacks.
- Updated the annotation format in confusion matrix plotting function to display floats for normalized matrices and integers for non-normalized matrices.

### 🎯 Purpose & Impact
- Users now benefit from an additional normalized confusion matrix plot, which provides a better view of the model's performance across classes, especially when classes are imbalanced.
- The improved annotation format helps in understanding the actual number of instances or the proportions, depending on whether the matrix is normalized or not, which enhances result interpretation.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@darouwan looks good! I wonder if we can make the fontsize a function of the class count. You'd have to experiment to get a good equation, but ya the font seems too small for low-classcount datasets currently.

**Comment by darouwan** [comment]
@glenn-jocher Great suggestion. I need to confirm that the numbers only show when the number of classes is less than 30, right?

**Comment by glenn-jocher** [comment]
@darouwan thank you for reaching out and contributing to the YOLOv8 repository. Yes, that is correct. By default, the numbers in the confusion matrix are displayed as integers only if the number of classes is less than 30. If there are more classes, the values are shown in scientific notation. However, you can modify this behavior by setting the `fmt` parameter of the `ConfusionMatrix.plot` method to a string format that suits your needs. Please let us know if you have any further questions or concerns, we are always happy to help.

**Comment by darouwan** [comment]
@glenn-jocher I tested several parameters, the trickiest part is the imbalanced value. Even using scientific notation, some huge value is hard to show in the confusion matrix. If I set the font size smaller, the rest part will be too small. 
image
image

**Comment by glenn-jocher** [comment]
Hello @darouwan, thank you for your feedback and for testing the confusion matrix functionality in YOLOv8. We appreciate your efforts to fine-tune the parameters and address the issues with imbalanced values and font sizes. We understand that this can be challenging, especially when dealing with datasets that have large variations in class counts or class imbalances. 

To address this issue, we suggest experimenting with different string formats and font sizes until you find a combination that works well for your dataset. You may also consider using log scales or normalization techniques to adjust the values and improve the visualization. Additionally, you can try to crop or resize the matrix plot to focus on the specific region of interest and improve the readability.   

We hope this helps. Please let us know if you have any further questions or suggestions, we are always happy to assist you.

**Pull request merged**
