### PR TITLE
Add ruff-pre-commit function

### PR DESCRIPTION
**Pull request by Zengyf-CVer**
I have read the CLA Document and I sign the CLA

### Summary
🎨🐍🚨

This pull request adds a new pre-commit hook to format and fix Python code with the ruff tool, and updates the `DetectionModel` class to use a named function instead of a lambda expression.

> _`ruff` formats code_
> _a pre-commit hook ensures_
> _style guide is met_

### Walkthrough
* Add a pre-commit hook to format and fix Python code with ruff ([link](https://github.com/ultralytics/ultralytics/pull/1821/files?diff=unified&w=0#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9R30-R35))
* Refactor lambda expression to named function in `DetectionModel.__init__` ([link](https://github.com/ultralytics/ultralytics/pull/1821/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L189-R192))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved code quality and functionality in the Ultralytics repository.

### 📊 Key Changes
- Added a new pre-commit hook using Ruff for linting and auto-fixing code issues.
- Refactored the forward function definition for clarity in specific model classes.

### 🎯 Purpose & Impact
- **Enhanced Code Quality**: The Ruff pre-commit hook ensures cleaner code and automates fixes, reducing manual code review effort. 🔍
- **Improved Maintainability**: More readable code with the refactored function, helping developers understand and modify code more easily. 🛠️

These changes aim to streamline development processes and improve the quality of contributions.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Zengyf-CVer your new pre-commit is failing because we have a 120 character line limit.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher I was able to solve this problem with this PR https://github.com/ultralytics/ultralytics/pull/1823

**Comment by glenn-jocher** [comment]
@Zengyf-CVer, I'm glad to hear that the issue was resolved with the Pull Request you submitted. We encourage contributors to follow our coding conventions, such as adhering to a 120 character line limit. Thank you for your valuable contribution to Ultralytics YOLOv8! If you have any further questions or issues, don't hesitate to ask. Also, be sure to check out our documentation at https://docs.ultralytics.com for more information.

**Comment by ambitious-octopus** [comment]
Duplicate!

**Pull request closed without merging**
