### PR TITLE
Create deployment-options.md

### PR DESCRIPTION
**Pull request by abirami-vina**
### Summary
📄🚀🧭

This change adds a new guide on `deployment-options.md` to the `./docs/guides` directory, explaining the different export formats for YOLOv8 models and how to choose the best one for a project. The change improves the documentation and user experience of YOLOv8.

> _`YOLOv8` guides_
> _Export formats explained well_
> _Autumn of learning_

### Walkthrough
*  Add a new guide on deployment options for YOLOv8 models ([link](https://github.com/ultralytics/ultralytics/pull/6160/files?diff=unified&w=0#diff-7a26e31def1bd9b215ea425fb366b18f4cc519a99044e94b214e593984341b33R1-R303))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Guide on choosing the ideal deployment option for YOLOv8 models.

### 📊 Key Changes
- A **new comprehensive guide** added to the documentation detailing deployment options for YOLOv8.
- **Comparative analysis table** provided to summarize performance, compatibility, and other key aspects of each deployment choice.
- Sections outlining **community and support** resources available for users and developers.

### 🎯 Purpose & Impact
- **Assist users** in selecting the best model deployment method matching their performance and environmental needs.
- **Simplify decision-making** by providing a high-level overview and comparison of various deployment options.
- **Strengthen the YOLOv8 community** by highlighting available support and discussion platforms.
- Potential to **improve model deployment efficiency**, security, and performance across diverse hardware ecosystems.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@abirami-vina woohoo nice!

**Comment by glenn-jocher** [comment]
@abirami-vina could you rename this file to `model_deployment_options.md`? 

I think it's good to go then. The last time I renamed one of these files the authorship chain was interrupted, so it would be best if you did this commit. Thanks!

**Comment by glenn-jocher** [comment]
For /hub/app

Screenshot 2023-11-07 at 13 17 37 (1)

**Comment by glenn-jocher** [comment]
for /hub/app/

Screenshot 2023-11-07 at 18 11 21

**Comment by abirami-vina** [comment]
> for /hub/app/
> 
> Screenshot 2023-11-07 at 18 11 21

@glenn-jocher Thanks. I've changed the file name. Is there anything with respect to this that I need to edit as well?

**Comment by glenn-jocher** [comment]
@abirami-vina yes, we should include more internal links and code examples. 

For internal links we don't actually have a page for each export format or integration yet other than OpenVINO at https://docs.ultralytics.com/integrations/openvino/, but we do have simple export code examples at https://docs.ultralytics.com/modes/export/.

I'm not sure if we want to show a code example for each format, it may be repetitive since the only thing that changes is the format=... line.

The table in the export page certainly provides very good examples though and should also probably be shown in this page no?
https://docs.ultralytics.com/modes/export/

**Comment by abirami-vina** [comment]
@glenn-jocher I've added the links you recommended. I'll keep in mind that internal linking is important. Thanks. 

Including the table, might be a little repetitive so I've mentioned it and linked it instead.

**Comment by glenn-jocher** [comment]
@abirami-vina ok got it! I'll merge this.

**Comment by glenn-jocher** [comment]
@abirami-vina PR merged! Thank you for your contributions :)

**Pull request merged**
