### PR TITLE
Fix the incorrect description

### PR DESCRIPTION
**Pull request by zhixuwei**
The description here about the order of the dimensions of the image is wrong, the correct order is [height, width].

Fix this issue [#14061](https://github.com/ultralytics/ultralytics/issues/14061)

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This GitHub pull request makes minor updates to the workflow settings, improves error handling, and bumps the version number.

### 📊 Key Changes
- **Workflow Configuration**: Removed the `push` trigger for the 'main' branch in GitHub Actions.
- **Documentation**: Small cleanup in the `yolov10.md` file.
- **Version Update**: Increased version number from `8.2.43` to `8.2.44`.
- **Improved Error Handling**: Updated image loading to log a warning instead of raising an error when an image can't be read.

### 🎯 Purpose & Impact
- **Workflow Efficiency**: Simplifying GitHub Actions triggers 🎯 makes the workflow more straightforward and reduces unnecessary runs.
- **Cleaner Docs**: Minor documentation cleanup 📄 for better readability.
- **Version Bump**: Reflects minor improvements and bug fixes 🚀.
- **User Experience**: Logging a warning instead of stopping on an image read error provides a more resilient and informative experience 👍.

### CODE REVIEW

**Comment by zhixuwei** [comment]
This pr does not use the branch that fixes the problem, now close this pr, and the new pr is in the [#14066](https://github.com/ultralytics/ultralytics/pull/14066)

**Comment by glenn-jocher** [comment]
@zhixuwei thank you for the update! I appreciate your diligence in addressing the issue. I'll review the new PR [#14066](https://github.com/ultralytics/ultralytics/pull/14066) to ensure the problem is resolved. If you encounter any further issues or have additional questions, please don't hesitate to reach out. 😊

**Comment by zhixuwei** [comment]
> @zhixuwei thank you for the update! I appreciate your diligence in addressing the issue. I'll review the new PR [#14066](https://github.com/ultralytics/ultralytics/pull/14066) to ensure the problem is resolved. If you encounter any further issues or have additional questions, please don't hesitate to reach out. 😊

It is my honor. 😊

**Comment by glenn-jocher** [comment]
Thank you, @zhixuwei! Your contributions are highly valued. I'll proceed with the review of PR [#14066](https://github.com/ultralytics/ultralytics/pull/14066) to ensure the issue is resolved. If you have any further questions or run into any other issues, feel free to let us know. We're here to help! 😊

**Pull request closed without merging**
