### PR TITLE
[Example] YOLO-Series(v5-11) ONNXRuntime Rust

### PR DESCRIPTION
**Pull request by jamjamjon**
This PR focuses on the Rust example code, with two main points:

1. Fixes the issue where the YOLOv8-ONNXRuntime-Rust code was unable to automatically link to the onnxruntime dynamic library after modifications by others, and includes code formatting adjustments (using `rust-fmt`).  #17309 

2. Given the rapid iteration of YOLO models and updates in ONNXRuntime, I’ve added a new YOLO-Series-ONNXRuntime-Rust codebase with minimal dependencies, featuring the following characteristics:

- **Extensive Model Compatibility**: Supports `YOLOv5`, `YOLOv6`, `YOLOv7`, `YOLOv8`, `YOLOv9`, `YOLOv10`, `YOLO11`, `YOLO-world`, `RTDETR`, and others, covering a wide range of YOLO versions.
- **Versatile Task Coverage**: Includes `Classification`, `Segmentation`, `Detection`, `Pose`, and `OBB`.
- **Precision Flexibility**: Works with `FP16` and `FP32` ONNX models.
- **Execution Providers**: Accelerated support for `CPU`, `CUDA`, `CoreML`, and `TensorRT`.
- **Dynamic Input Shapes**: Dynamically adjusts to variable `batch`, `width`, and `height` dimensions for flexible model input.
- **Flexible Data Loading**: The `DataLoader` handles images, folders, videos, and video streams.
- **Real-Time Display and Video Export**: `Viewer` provides real-time frame visualization and video export functions, similar to OpenCV’s `imshow()` and `imwrite()`.
- **Enhanced Annotation and Visualization**: The `Annotator` facilitates comprehensive result rendering, with support for bounding boxes (HBB), oriented bounding boxes (OBB), polygons, masks, keypoints, and text labels.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces a new Rust-based demo for YOLO tasks using ONNXRuntime, supporting multiple YOLO versions and extensive functionalities.

### 📊 Key Changes
- Added a Rust demo for YOLO-series tasks with ONNXRuntime, supporting tasks like Classification, Segmentation, Detection, Pose, and Oriented Bounding Box (OBB).
- Included support for YOLO versions from v5 through v11, along with alternative models.
- Enhanced the integration of ONNXRuntime with features for dynamic input shapes and execution provider flexibility (CPU, CUDA, CoreML, TensorRT).
- Updated the ONNXRuntime handling in the existing YOLOv8 Rust demo, improving library linking instructions and expanding execution capabilities.

### 🎯 Purpose & Impact
- **Purpose**: This update provides a comprehensive Rust implementation for running YOLO models, making it easier for developers to perform various machine vision tasks efficiently and flexibly.
- **Impact**: Users will benefit from improved model compatibility, execution speed, and usability enhancements, enabling more robust application development in Rust with state-of-the-art YOLO models.🎉

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @jamjamjon, thank you for submitting your PR to the `ultralytics/ultralytics` repository! This is an automated response to guide you through the process. An Ultralytics engineer will also be on hand to assist you soon. 😊

Here's a quick checklist to help ensure your pull request smoothly integrates into our codebase:

- ✅ **Clearly State the Purpose**: It looks like your PR introduces enhancements to the Rust example codes, addressing previous issues with library linking and extending capability across multiple YOLO model versions. Please ensure that your explanation in the PR description is detailed and links to any related [issues](https://github.com/ultralytics/ultralytics/issues) if applicable.
- ✅ **Synchronize with Main**: Ensure your branch is up-to-date with the `main` branch of `ultralytics/ultralytics`. Resolve any merge conflicts and ensure compatibility by running `git pull` and `git merge main` if necessary.
- ✅ **CI Check Completion**: Verify that all Continuous Integration (CI) checks have passed. If there are any failures, kindly take steps to resolve them. Check our CI documentation for assistance if needed: [CI Help](https://docs.ultralytics.com/help/CI/).
- ✅ **Update Documentation**: If your changes affect the functionality or usage of the existing systems, update the relevant [documentation](https://docs.ultralytics.com) accordingly.
- ✅ **Include Tests**: Ensure that any new features or bug fixes include unit tests or integration tests where applicable. Confirm that all existing tests pass successfully.
- ✅ **Sign the CLA**: If this is your first contribution to Ultralytics, please sign the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA" in this PR.
- ✅ **Minimize Change Scope**: Strive to keep your changes concise and relevant to the issue. Avoid unnecessary modifications. To echo Bruce Lee's wisdom: _"It's not the daily increase but daily decrease. Hack away at the unessential."_

For additional support, our [Contributing Guide](https://docs.ultralytics.com/help/contributing) is a great resource. If you have any questions or need further clarification, feel free to leave a comment. Thank you for your invaluable contributions and support! 🚀

**Comment by glenn-jocher** [comment]
@jamjamjon this is great work! Thank you for your contributions, PR merged!

**Comment by glenn-jocher** [comment]
@jamjamjon it would be really cool to add some benchmarks here for Python ONNXRuntime vs Rust. I think there's a lot of users that would be curious to see the speed improvements.

**Comment by jamjamjon** [comment]
I will conduct this comparative test when I have time, and I will submit an update then.

**Comment by glenn-jocher** [comment]
@jamjamjon thank you for your initiative! We look forward to your update whenever you're ready.

**Pull request merged**
