### PR TITLE
Docs: Added "Getting Started" documentation for Ultralytics HUB

### PR DESCRIPTION
**Pull request by priytosh-tripathi**
The document meets the following points:
1. Creating an account
2. Getting Started with Dataset
3. Training a Model
4. Deploying a Model
5. How to report / comment and request features.

The documentation is a draft guide for the original HUB getting started documentation.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing cloud training and updates to dataset handling on Ultralytics HUB!

### 📊 Key Changes
- Added a new Cloud Training guide to provide users with a detailed tutorial on model training using the Ultralytics cloud platform.
- Refreshed dataset upload and sharing process, now with more straightforward guidance and updated screenshots.
- Updated model training and deployment instructions with clearer steps and visual aids.
- Simplified the quickstart guide, focusing on an intuitive start with Ultralytics HUB and highlighting the ease of integrating models with third-party applications.
- Streamlined the documentation on model sharing, editing, and deletion for better user understanding.
- Enhanced the datasets.md file by refining the process and updating the images with new links.
- Improved the models.md with a condensed explanation of the training options, streamlined the model previewing process, and presented a cohesive structure for deploying and sharing models.
- Elucidated the inference API documentation with an updated screenshot.

### 🎯 Purpose & Impact
- Helps users efficiently utilize cloud resources for AI model training, leading to faster and more user-friendly model creation.
- Updated and clarified documentation aims to improve the user experience, making it easier to upload, share, and manage datasets and models.
- Enhanced guides support users from account creation to model deployment, fostering a smooth and accessible journey through the platform's capabilities.

### CODE REVIEW

**Comment by priytosh-tripathi** [comment]
I have read the CLA Document and I sign the CLA

**Comment by RizwanMunawar** [comment]
@priytosh-tripathi awesome work, but I guess a few images are very large, can we compress them?

Screenshot 2024-02-12 153230

**Comment by kalenmike** [comment]
We need to make some adjustments to the way we are handling the images here, so lets not merge yet. @glenn-jocher Can we do a quick chat so I understand better where you want to store the images?

**Comment by glenn-jocher** [comment]
@priytosh-tripathi thanks for the PR!

Yes, to clarify to everyone, as @RizwanMunawar was saying, introducing images into this repository codebase is strictly controlled and in nearly all circumstances  prohibited. 

**Only code should ever be introduced in git commits.** 

Images, videos and media will lead to a huge expansion in size of this repository, as every `git clone` and `git pull` command will pull every image ever introduced, as well as all of it's updates and replacements for all time, causing very expensive, very slow operations that will slow down workflows for thousands of people.

For a sustainable library that may have to last decades, we must very strictly control what can come in the gate, therefore the best practice currently for images is to:

1. Reduce largest dimension to 1920 maximum.
2. Pass through tinypng.com or tinyjpg.com
3. Drag and drop into a PR comment.
4. Link the generated URL to where it's needed.

**Comment by glenn-jocher** [comment]
And to clarify further, the above steps should create images around ~400kB or less, so the even hosting the ~1MB files for use in the Docs is also prohibited, these must be resized to <1920 and optimized using tinypng.com or tinyjpg.com

**Comment by priytosh-tripathi** [comment]
Hi @glenn-jocher ,

Thankyou for the suggestions (also @RizwanMunawar ). I have made the necessary changes as discussed above in this PR. Once finalised, I'll transfer this to a new clean PR for standard implementation of the doc.

**Comment by kalenmike** [comment]
@glenn-jocher We are using this PR for review, don't merge this as the images still exist in other commits. We filter and force remove or create a clean PR before this is ready for submission.

**Comment by glenn-jocher** [comment]
@kalenmike ok got it, I'll just let this one sit for a bit (it's in good company with all the other PRs 😂)

**Comment by priytosh-tripathi** [comment]
Hi @RizwanMunawar @glenn-jocher @kalenmike ,
Thankyou for your valuable feedbacks, after integrating all the feedbacks, I've created a new PR to maintain the uniformity in our SCM procedures, please find the new PR here:
https://github.com/ultralytics/ultralytics/pull/8174

I would be closing this PR for now,.

**Pull request closed without merging**
