### PR TITLE
[WIP]Refactor

### PR DESCRIPTION
**Pull request by Laughing-q**
### Summary
:recycle::books::hammer_and_wrench:

This pull request refactors the ultralytics package by moving the yolo subpackage to the top level and renaming the files and modules accordingly. This simplifies the import statements and the documentation structure. The pull request also updates the tests and examples to use the new module locations and names.

> _Sing, O Muse, of the mighty refactor that reshaped the code_
> _Of ultralytics, the skillful builder of YOLO models,_
> _How they moved and renamed the modules with swift and careful strokes_
> _And updated the import statements, like the gods who shift the poles._

### Walkthrough
*  Refactor utils module to be a top-level package and update import statements in various files ([link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-5cfa04e1ac6cf15d3e088375fb3e6988979e65360130a6e837459fa22dd9c59cL13-R13), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-6d9ff66732e3f612566f6c8e4ad3b6db2cfab0c3f06f11776d72b39ea4213220L65-R65), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-bb5cf7919612f5a526e139896c15b09fba0cf48c14cfaf740566eb7d621aee7bL30-R30), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-c126129d1acbfd2e959449cfc21aa78cd3b1c64661368ca387341b3ee69b3520L243-R243), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-ad6e812b8c8c788acce898aa5146a63b452f7b9875528d9db7fb1a689264cd94L8-R9), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-8eb622789bc750d2aad29d5426d995d376cbd3847fdc62ec2e42c8bbf8f2aae8L6-R7), F8L6L6, [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-51deb1ccb3a8b618784df2e2abfbc3b056436f1db72d1896d5102f9906978492L12-R13), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-51deb1ccb3a8b618784df2e2abfbc3b056436f1db72d1896d5102f9906978492L105-R105), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-b6202fa6738a34b56894dce00b24b8a4e4d7f4b1cbf1b04db6860f6b0f9635ceL8-R11), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-c02fb3f9e86e97bf85f07211aed56aa04774504a61eeff07a08471bbdea14556L12-R12), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-3e855cdd9b7d5f61f061a19aa1e4d05f63fb94b1dbbdfe75ddf9ef3db14796e0L5-R5), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-e8bb4966653e657a3bfc4a4c892ccdcf3c486a982016d2e51631b5b9393c2c5fL12-R18), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-75efef96e07c9d4ff2cd886cf936b1ee920f98058cf4abd2194a668f90d3655fL9-R10))
*  Refactor engine and data modules to be top-level packages and update import statements in various files ([link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-882061b431ed3670f5b4a045ae0f4e1f140cc785db77fe77585b820bdec6f73dL6-R8), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-e8bb4966653e657a3bfc4a4c892ccdcf3c486a982016d2e51631b5b9393c2c5fL12-R18), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-3e855cdd9b7d5f61f061a19aa1e4d05f63fb94b1dbbdfe75ddf9ef3db14796e0L5-R5), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-b6202fa6738a34b56894dce00b24b8a4e4d7f4b1cbf1b04db6860f6b0f9635ceL8-R11))
*  Rename files from yolo subdirectory to top-level directory ([link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-732d61cb4969eff986cec58058000b2949ea3b429a97ca5a1045897e754145c5), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-a6a6d5d9db8b1784a3cc45b1e6ac93597733ba5cf9f5947ec9e39193c90102b1), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-8945a175b39a1efcabd4d2fb09b583d2f25409f05038ca9a0f1165e39ee48528), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-0b2d0be08e156856d63e748af252444d26d092bf1ca32e56c4a25074efccc4c9))
*  Change file name from `docs/models/sam.md` to `docs/build_reference.py` and update import statements in various files ([link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-6d9ff66732e3f612566f6c8e4ad3b6db2cfab0c3f06f11776d72b39ea4213220L99-R99), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-bb5cf7919612f5a526e139896c15b09fba0cf48c14cfaf740566eb7d621aee7bL74-R74), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-cc3f027dd6bed4eb36cc55a8749053fc0003fe91b987000894baa43ec1c9a5adL87-R87), [link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-c126129d1acbfd2e959449cfc21aa78cd3b1c64661368ca387341b3ee69b3520L283-R283))
*  Change print statement for trainer arguments in `examples/tutorial.ipynb` ([link](https://github.com/ultralytics/ultralytics/pull/3410/files?diff=unified&w=0#diff-628f2a1367635512a2709420a09de67583ea73f4c37dc2312d5eac23f1d71294L303-R303))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

### 🌟 Summary
Export models to various formats including ONNX, TensorRT, CoreML, TensorFlow, TensorFlow Lite, and others.

### 📊 Key Changes
- Introduced a class `Exporter` to handle model export to different formats.
- Added new functions `export_torchscript`, `export_onnx`, `export_engine`, and others for dedicated export operations.
- Created decorators and helpers like `try_export` and `export_formats` to support export functionalities.
- Implemented device selection and checks to ensure compatibility with export format requirements.

### 🎯 Purpose & Impact
- Enables users to convert trained models into various formats suitable for deployment in different environments.
- Provides flexibility in deploying models to a range of devices and platforms, enhancing usability.
- Ensures model interoperability, making models accessible for a broader audience.
- Streamlines the process of model conversion, thus saving time and reducing complexity for end-users.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel ok I think the PR is ready to review.
- Currently the `ultralytics/ folder looks like this:
pic-selected-230628-1142-02

- For backward compatibility, I kept these old files in `ultralytics/yolo` with just one import line and a warning, for example current `ultralytics/yolo/cfg/__inint__.py` looks like this:
    ```python
    # Ultralytics YOLO 🚀, AGPL-3.0 license
    from ultralytics.cfg import *
    from ultralytics.utils import LOGGER

    LOGGER.warning(
        "WARNING ⚠️ 'ultralytics.yolo.cfg' is deprecated and will be removed. Please use 'ultralytics.cfg' instead.")
    ```
    BTW the `pre-commit` failed is also because the import way like `from ultralytics.cfg import *`.
- Our classify model and pose model rely on `ultralytics.yolo.data` and `ultralytics.yolo.utils` respectively, which means simply loading these models would raise a warning msg similar to the above one. So we have to update our official classify model and pose model, and simply loading the model with pytorch and save it again in this branch would work, like this:
    ```python
    ckpt = torch.load("yolov8n-cls.pt")
    torch.save(ckpt, "yolov8n-cls.pt")
    ```

**Comment by Laughing-q** [comment]
Loading classify and pose model directly in this branch:
pic-selected-230628-1202-39
Loading classify and pose model directly in this branch but after the re-load-save process:
```python
import torch
ckpt = torch.load("weights/yolov8n-cls.pt")
torch.save(ckpt, "yolov8n-cls.pt")

ckpt = torch.load("weights/yolov8n-pose.pt")
torch.save(ckpt, "yolov8n-pose.pt")
```
pic-selected-230628-1203-21

**Comment by glenn-jocher** [comment]
@Laughing-q this looks good, but see https://results.pre-commit.ci/run/github/535360445/1688064320.1giBRwCwTAqWEP3wjuJb8A for precommit issues related to top level imports

**Comment by glenn-jocher** [comment]
@Laughing-q oh I get it, so these are all for backwards compatibility it seems.

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel @fcakyon I think we might be able to perform the refactor a bit differently, but attempting to load models and then on modulenotfound error we can reload after adding new module paths like this:

```path
import importlib
import sys
import torch

# Dynamically import the module with its new name
new_module = importlib.import_module('ultralytics.utils')

# Set the module in sys.modules under its old name
sys.modules['ultralytics.yolo.utils'] = new_module

# Now, you can load an older PyTorch model
model = torch.load('path_to_old.pt')
```

**Comment by glenn-jocher** [comment]
@Laughing-q can you try loading older models in this branch after running this code:

```python
import importlib
import sys
import torch

# Set modules in sys.modules under their old name
for m in 'cfg', 'data', 'engine', 'utils':
    sys.modules[f'ultralytics.yolo.{m}'] = importlib.import_module(f'ultralytics.{m}')

# Now, you can load older PyTorch models
model = torch.load('path_to_old_model.pt')

```

**Comment by Laughing-q** [comment]
> @Laughing-q can you try loading older models in this branch after running this code:
> 
> ```python
> import importlib
> import sys
> import torch
> 
> # Set modules in sys.modules under their old name
> for m in 'cfg', 'data', 'engine', 'utils':
>     sys.modules[f'ultralytics.yolo.{m}'] = importlib.import_module(f'ultralytics.{m}')
> 
> # Now, you can load older PyTorch models
> model = torch.load('path_to_old_model.pt')
> ```

yeah it works smoothly.

**Comment by Laughing-q** [comment]
@glenn-jocher Actually we can maintain backwards compatibility by adding some code(adding these lines with green plus sign) in `ultralytics/__init__.py`:
pic-selected-230630-0957-52
and directly remove these outdated files in `ultralyticsyolo/`.

But one disadvantage of this is it seems we can't raise a warning this way to inform users to use `ultralytics` directly instead of using `ultralytics.yolo`, cause if I add warning msg in `ultralytics/__init__.py` users would get the warning anyway when they import `ultralytics` whether they use the new import way(without `yolo`) or the outdated way(with `yolo`).

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel @fcakyon ok I moved `models/` and `datasets/` into `cfg/ and create a new `models/` folder to keep vit models and tracker, and now the structure looks like this, which I think it's much better:
pic-selected-230630-1045-04
Also I left yolo in top level since:
- we need `ultralytics/yolo` for now for backward compatibility.
- like Ayush said yolo series are our major models, maybe it deserves a independent top level folder. We can just put all other models and methods we implemented in `ultralytics/models`.

**Comment by Laughing-q** [comment]
closing this one since I'm not sure if I won't break anything working correctly while solving these conflicts. I'll open another one tomorrow.

**Pull request closed without merging**
