### PR TITLE
Use `zip` or `tarfile` for `classify` task

### PR DESCRIPTION
**Pull request by Burhan-Q**
Issue for HUB incompatibility raised by @kalenmike Follows same logic as `check_det_dataset()` for `.zip` or `.tarfile` archives

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced dataset handling in Ultralytics with support for local zip and tar files.

### 📊 Key Changes
- Added conditional checks to determine if the `dataset` parameter is a local zip or tar file.
- Implemented use of `check_file()` function to ensure dataset file integrity.
- Utilized `safe_download()` to handle these files, providing extraction to the datasets directory without deletion.

### 🎯 Purpose & Impact
- **Facilitates Local Dataset Use**: Users can now directly pass zip or tar dataset files without needing a URL, making local experimentation easier.
- **Ensures Data Integrity**: With the `check_file()` function, datasets are verified, reducing errors during dataset loading.
- **Streamlines Data Preparation**: Automatic handling and extraction of dataset files simplifies the model training setup process for users.

### CODE REVIEW

**Comment by Burhan-Q** [comment]
Looks like the CI benchmark that's failing is due to an issue with `pnnx` which I don't think the work I did would impact (not certain). From the command before the error, it looks like there might be an extra directory in the file path `ncnn: running '/home/runner/work/ultralytics/ultralytics/ultralytics/pnnx...` maybe there are supposed to be 3 `ultralytics` directories but that's the only thing that jumped out to me.

```
ncnn: running '/home/runner/work/ultralytics/ultralytics/ultralytics/pnnx path with spaces/yolov8n-seg.torchscript ncnnparam=path with spaces/yolov8n-seg_ncnn_model/model.ncnn.param ncnnbin=path with spaces/yolov8n-seg_ncnn_model/model.ncnn.bin ncnnpy=path with spaces/yolov8n-seg_ncnn_model/model_ncnn.py pnnxparam=path with spaces/yolov8n-seg_ncnn_model/model.pnnx.param pnnxbin=path with spaces/yolov8n-seg_ncnn_model/model.pnnx.bin pnnxpy=path with spaces/yolov8n-seg_ncnn_model/model_pnnx.py pnnxonnx=path with spaces/yolov8n-seg_ncnn_model/model.pnnx.onnx fp16=0 device=cpu inputshape="[1, 3, 160, 160]"'

ncnn: export failure ❌ 2.7s: [Errno 8] Exec format error: '/home/runner/work/ultralytics/ultralytics/ultralytics/pnnx'
```

**Comment by Burhan-Q** [comment]
Looks like #8480 should fix

**Comment by glenn-jocher** [comment]
@Burhan-Q yeah I'll merge this into that. PNNX changed their filename format to support aarch64 on linux which crashed the auto-download functionality there. It happens sometimes when I try to get too fancy but I think I have a fix.

**Comment by glenn-jocher** [comment]
@Burhan-Q @kalenmike merged into 8.1.19 PR

**Pull request merged**
