### PR TITLE
Comet integration fix

### PR DESCRIPTION
**Pull request by yaricom**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Comet logging integrations to improve tracking of various evaluation metrics and plots in Ultralytics YOLO.

### 📊 Key Changes
- Added logging of plot images for new metric types (Segment, Pose) alongside existing detection metrics.
- Updated confusion matrix logging to include both normalized and non-normalized matrices.
- Modified plot generation code to include more specific plot naming based on metric type.
- Changed project creation log reference from "yolov8" to "ultralytics".
- Enhanced image logging to include `train_batch` and `val_batch` images post-training.

### 🎯 Purpose & Impact
- **Improved Metric Tracking**: By integrating additional metrics, users can now track and analyze detailed performance aspects of segmentation and pose tasks, not just detection.
- **Comprehensive Logging**: Logging both normalized and non-normalized confusion matrices offers deeper insights into model accuracy and error distribution.
- **Version Update**: Reflecting the version change helps maintain consistency and clarity in project provenance.
- **Enhanced Visualization**: Including more training and validation images aids in better visualization of model behavior and debugging potential issues.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Comet integration for more comprehensive logging of plots and metrics in Ultralytics YOLO 🚀.

### 📊 Key Changes
- Integrated additional metrics classes (`ClassifyMetrics`, `DetMetrics`, `OBBMetrics`, `PoseMetrics`, `SegmentMetrics`) into the Comet callback.
- Revised plot logging logic to accommodate specific tasks like segmentation and pose detection with new prefixes.
- Enhanced logging for confusion matrices, including both standard and normalized versions.
- Modified model creation log statement to reflect "ultralytics" instead of "yolov8".
- Adjusted the timing and conditions under which training and validation batch images are logged.

### 🎯 Purpose & Impact
- **Improved Insights**: Provides users with more detailed and task-specific visual plots and metrics, thus enhancing the capability to analyze model performance.
- **Task-Specific Logging**: By aligning metrics logging with specific tasks (e.g., segmentation, pose detection), users gain clarity on different model outputs.
- **Richer Experimentation**: Increased logging coverage supports deeper experimentation, which can be valuable for both expert developers wanting detailed insights and non-experts seeking straightforward visual information.
- **Consistency Update**: The change in model creation logging from "yolov8" to "ultralytics" ensures consistency across the platform.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @yaricom, thank you for submitting a fantastic PR to the `ultralytics/ultralytics` repository! 🚀 Your contributions to enhancing Comet logging integrations are very much appreciated. To ensure a smooth integration, could you please review and complete the following checklist:

- ✅ **Define the Purpose**: Make sure your PR description clearly elucidates the objective of your changes, and link to any [related issues](https://github.com/ultralytics/ultralytics/issues) if they exist. This helps other team members and contributors understand the context better.
- ✅ **Keep Your Branch Updated**: Ensure your branch is up-to-date with the `main` branch of `ultralytics/ultralytics`. If necessary, synchronize it by clicking the 'Update branch' button or executing `git pull` and `git merge main` on your local repository.
- ✅ **Continuous Integration (CI) Checks**: Confirm that all required [CI checks](https://docs.ultralytics.com/help/CI/) are passing. Address any failures to facilitate merging your contributions.
- ✅ **Documentation Updates**: For any new or modified features, update the relevant [documentation](https://docs.ultralytics.com) to ensure users can easily follow and utilize the latest capabilities.
- ✅ **Comprehensive Testing**: Include or modify tests as necessary to accompany your changes, ensuring they pass successfully.
- ✅ **Contributor License Agreement (CLA)**: Please double-check that you have signed our [CLA](https://docs.ultralytics.com/help/CLA/) if this is your initial contribution to Ultralytics. To do so, add a comment stating, "I have read the CLA Document and I sign the CLA."
- ✅ **Minimize Extraneous Modifications**: Focus your adjustments on the essential elements needed to address your feature request or bug. As Bruce Lee aptly said, "It is not daily increase but daily decrease, hack away the unessential."

For detailed contribution instructions, refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions or need further assistance, feel free to leave a comment below. This message is a part of our automated response, and an Ultralytics engineer will review your PR shortly. Thanks for helping make Ultralytics better with your efforts! 🎉

**Comment by yaricom** [comment]
I have read the CLA Document and I sign the CLA

**Review by ambitious-octopus — COMMENTED** [review]
Hey @yaricom I don't have enough experience with comet ml, but maybe you do. Why upload raw plot images if comet ml has this feature already built in?

Example: comet ml already has a tab for confusion matrix (very useful) why uploading the raw image too?

image

**Comment by glenn-jocher** [comment]
@yaricom changes look good!

@ambitious-octopus most of the loggers are just uploading images at this point, but we do have plot info the training results objects. This would probably require much more integration and customization per logger though (W&B, Comet, etc.), so this seems like a good improvement without complicating things.

**Comment by Lothiraldan** [comment]
@ambitious-octopus @glenn-jocher Hi, I'm Boris, Integrations Product Manager at Comet. Logging Confusion Matrices with images examples is something that we would like to do in our Ultralytics integration. We support it in the platform, the current pain point is that we couldn't find an easy way to associate images for each cell of the matrix. If we could works together to find a way, it would make some of our common users very happy.

**Comment by glenn-jocher** [comment]
Hi Boris, thanks for reaching out. While we appreciate the interest, we currently focus on maintaining our open-source projects and cannot engage in direct collaborations. However, feel free to explore our public resources and documentation for potential solutions.

**Pull request merged**
