### PR TITLE
Results, DFL and AIGym fixes

### LINKED ISSUE #14064: ai_gym list assignment index out of range
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

bug report

When I used the demo on  [the official website](https://docs.ultralytics.com/guides/workouts-monitoring/) to predict my video, the list overflowed. I found that the list created at the beginning was too small. In subsequent frames, the number of keypoints was greater than the capacity of the list.

bug report2

### Environment

Ultralytics YOLOv8.2.45 🚀 Python-3.9.6 torch-2.3.1 CPU (Apple M3)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 156.1/460.4 GB disk)

OS                  macOS-14.3-arm64-arm-64bit
Environment         Darwin
Python              3.9.6
Install             pip
RAM                 16.00 GB
CPU                 Apple M3
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.5
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

```python
import cv2

from ultralytics import YOLO, solutions

model = YOLO("yolov8n-pose.pt")
cap = cv2.VideoCapture("fwc0.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

video_writer = cv2.VideoWriter("workouts.avi", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

gym_object = solutions.AIGym(
    line_thickness=2,
    view_img=True,
    pose_type="pushup",
    kpts_to_check=[6, 8, 10],
)

frame_count = 0
while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    frame_count += 1
    results = model.track(im0, verbose=False)  # Tracking recommended
    # results = model.predict(im0)  # Prediction also supported
    im0 = gym_object.start_counting(im0, results, frame_count)
    video_writer.write(im0)

cv2.destroyAllWindows()
video_writer.release()

```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by ambitious-octopus**
This PR fixes Issue #14064.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Simplified the workout monitoring logic in Ultralytics YOLOv8 by removing unnecessary frame count tracking.

### 📊 Key Changes
- 🗑️ Removed `frame_count` variable from the workout monitoring functions in both the documentation and the `ai_gym.py` code.
- 📉 Erased initializations based on `frame_count` in the `start_counting` method.
- 🧮 Added checks to dynamically update counting lists only when new poses are detected.

### 🎯 Purpose & Impact
- 🛠️ **Simplification:** By eliminating the frame counting, the code becomes easier to understand and maintain.
- 🚀 **Efficiency:** Dynamically adjusting counting lists ensures robustness and correctness, even with varying numbers of detected keypoints.
- 🧘 **User Experience:** Users setting up workout monitoring will find the setup more intuitive and less error-prone.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR simplifies the workout monitoring documentation and configuration files while correcting model reference names.

### 📊 Key Changes
- 🔀 Removed `frame_count` variable and its usages in workout monitoring script.
- ✏️ Corrected model reference names from `YOLOv8` to `YOLOv10` in config files.
- 📄 Added a new author to `mkdocs_github_authors.yaml`.

### 🎯 Purpose & Impact
- 🔍 **Simplified Code**: Removing `frame_count` streamlines the script, reducing complexity for developers.
- ✅ **Accuracy**: Corrected references ensure proper model usage and prevent confusion.
- 👥 **Author Recognition**: Updated authors file to acknowledge contributions from new developers.

### CODE REVIEW

**Comment by RizwanMunawar** [comment]
@ambitious-octopus Nice work on this, But Please send me a review before merging to the main!

Thank you!

**Review by RizwanMunawar — APPROVED** [review]
@ambitious-octopus Awesome work :)

**Comment by RizwanMunawar** [comment]
@ambitious-octopus Great job, thanks for the bug fix! :)

@glenn-jocher I believe this PR is ready to be merged now. :)

**Comment by glenn-jocher** [comment]
@ambitious-octopus @RizwanMunawar nice, thanks guys!! There's been something strange going on with GitHub, it's stuck on the "checking for ability to merge" statement for all open PRs so I'm waiting for this to clear up and then I'll merge.

Screenshot 2024-06-28 at 19 51 50

**Comment by glenn-jocher** [comment]
@ambitious-octopus @RizwanMunawar guys always make sure that PRs and issues are linked together correctly. This PR was not linked correctly and I've had to do this myself. If you can't do it from the PR then start from the issue, but simply saying "fixes #..." in a comment is not sufficient and not acceptable.

Screenshot of how to link this PR from the Issue URL https://github.com/ultralytics/ultralytics/issues/14064
Screenshot 2024-06-29 at 17 58 53

**Pull request merged**
