### PR TITLE
Update Triton Inference Server guide

### PR DESCRIPTION
**Pull request by Y-T-G**
Updated to latest docker image because a user reported facing `Unsupported model IR version: 10, max supported IR version: 9` error with the older image. Also added instructions for enabling GPU inference.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the Triton Inference Server guide, including optional TensorRT configuration for improved GPU inference and updating to a newer Triton server version.

### 📊 Key Changes
- Added optional TensorRT configuration to enable GPU inference with precision mode set to FP16.
- Updated Triton Inference Server image tag from version `23.09` to `24.09`, increasing the image size from 6.4 GB to 8.57 GB.

### 🎯 Purpose & Impact
- **Improved Performance**: TensorRT configuration aims to enhance the performance of GPU inference by optimizing computations, although the initial run may be slower due to engine conversion.
- **Up-to-date Environment**: Updating the Triton server version ensures users have access to the latest features and optimizations, although at the cost of a larger image size.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

This is an automated response, but an Ultralytics engineer will review your PR and assist shortly. 😊

**Review by Burhan-Q — APPROVED** [review]
Looks good to me. Is there a issue we can link to this PR or was it from an external community?

**Comment by Y-T-G** [comment]
@Burhan-Q It was from Discord.

https://discord.com/channels/1089800235347353640/1098248998629933146/1297674538296807475

**Comment by glenn-jocher** [comment]
@Y-T-G PR merged!

**Pull request merged**
