### PR TITLE
Fix pad for scale_boxes()

### PR DESCRIPTION
**Pull request by Wovchena**
`preprocess()` rounds padding:
https://github.com/ultralytics/ultralytics/blob/4db686a31535968d34588fb4113bff66df8733e4/ultralytics/yolo/data/augment.py#L575 so `postprocess()` must do that as well

### Summary
📝🐛📈

This pull request updates the `README.md` file to reflect the new return value of the `model.export` method, and improves the `scale_boxes` function in `ultralytics/yolo/utils/ops.py` to avoid floating point errors in bounding box coordinates.

> _`model.export` gives_
> _path of file, not success_
> _README updated_

### Walkthrough
*  Update README.md code to assign exported file path to a variable ([link](https://github.com/ultralytics/ultralytics/pull/2754/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L96-R96))
*  Fix floating point errors in scale_boxes function by rounding and subtracting padding values ([link](https://github.com/ultralytics/ultralytics/pull/2754/files?diff=unified&w=0#diff-6ab52db19716f4198ed847132149ab432f032ed39c99c264a9de386446bf7f88L107-R107))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refining model export process and improving box scaling in codebase.

### 📊 Key Changes
- Changed a variable name from `success` to `path` in README example to better reflect the returned value when exporting a model to ONNX format.
- Updated the `scale_boxes` function to use `round()` when calculating padding, with a slight adjustment to improve the accuracy of object detection box scaling.

### 🎯 Purpose & Impact
- 💼 The variable name change in the README clarifies that the model export function returns the path where the ONNX file is saved, enhancing user understanding of the code example.
- 📐 The adjustment in the box scaling function is likely intended to reduce errors in object detection by providing more precise padding calculations, potentially leading to improved accuracy in object detection tasks.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Wovchena interesting, thanks for the PR! Have you tested this for mAP changes before and after?

**Comment by Wovchena** [comment]
No, I haven't.

I tried running
```py
model = YOLO("/home/wov/Downloads/yolov8n.pt")
metrics = model.val()
print(metrics.box.map, metrics.box.map50, metrics.box.map75, metrics.box.maps)
```
But it seems it hang:
```
/home/wov/.local/lib/python3.8/site-packages/requests/__init__.py:102: RequestsDependencyWarning: urllib3 (1.26.13) or chardet (5.1.0)/charset_normalizer (2.0.12) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({})/charset_normalizer ({}) doesn't match a supported "
/home/wov/.local/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:4: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  if not hasattr(tensorboard, "__version__") or LooseVersion(
/home/wov/.local/lib/python3.8/site-packages/torch/utils/tensorboard/__init__.py:6: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
  ) < LooseVersion("1.15"):
Ultralytics YOLOv8.0.106 🚀 Python-3.8.10 torch-1.13.1+cu117 CPU
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients

Dataset 'coco.yaml' images not found ⚠️, missing paths ['/home/wov/r/datasets/coco/val2017.txt']
Downloading https://github.com/ultralytics/yolov5/releases/download/v1.0/coco2017labels-segments.zip to /home/wov/r/datasets/coco2017labels-segments.zip...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 169M/169M [00:10<00:00, 17.5MB/s]
Unzipping /home/wov/r/datasets/coco2017labels-segments.zip to /home/wov/r/datasets...
Downloading http://images.cocodataset.org/zips/train2017.zip to /home/wov/r/datasets/coco/images/train2017.zip...
Downloading http://images.cocodataset.org/zips/val2017.zip to /home/wov/r/datasets/coco/images/val2017.zip...
Downloading http://images.cocodataset.org/zips/test2017.zip to /home/wov/r/datasets/coco/images/test2017.zip...
Unzipping /home/wov/r/datasets/coco/images/val2017.zip to /home/wov/r/datasets/coco/images...
Unzipping /home/wov/r/datasets/coco/images/test2017.zip to /home/wov/r/datasets/coco/images...
```

**Comment by glenn-jocher** [comment]
@Wovchena I was looking at this a little closer, shouldn't the offsets in your PR be 0.1 instead of 0.01?

```
        top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
        left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
        img = cv2.copyMakeBorder(img, top, bottom, left, right, cv2.BORDER_CONSTANT,
                                 value=(114, 114, 114))  # add border
```

**Comment by glenn-jocher** [comment]
@Wovchena thank you for your attention to detail. Our team has reviewed this concern and we believe that the values of 0.1 in the `scale_boxes()` function provide adequate padding to prevent floating point errors in bounding box coordinates, while minimizing the amount of padding added to the image itself. We have tested this and found that the results are consistent with the original implementation. Thank you again for your contribution to the YOLOv8 repo.

**Comment by Wovchena** [comment]
So, is it going to be merged?

**Comment by glenn-jocher** [comment]
@Wovchena PR merged for 8.0.108 today!

**Pull request merged**
