### PR TITLE
Add PyPI and conda-forge badges

### PR DESCRIPTION
**Pull request by Burhan-Q**
Include include icons for PyPi and conda-forge packages with version numbers.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Install Badge Visibility and Accuracy in Ultralytics Documentation

### 📊 Key Changes
- Updated PyPI badges for better visual consistency and added a Python version compatibility badge across README and docs.
- Added new badges for Conda and Docker, including version info, download counts, and platform compatibility in the README, Conda, and Docker guides.
- Improved the model accuracy statistics for YOLOv8l-cls in the Chinese README.
- Adjusted presentation of badges in the Ultralytics Docs README for clearer visibility.
- Changed licensing information to reflect specific documentation context.
- Provided more detailed badges (version, platforms, downloads) for Conda and Docker installation guides to offer users immediate insights on the package status.

### 🎯 Purpose & Impact
- **Enhanced Visibility and Clarity:** The badge updates improve the visual appeal and informational value of the installation sections, making it easier for users to understand the package version, compatibility, and popularity at a glance. 🌈
- **Increased Accuracy and Relevance:** By updating model accuracy statistics and refining the presentation of installation options (pip, Conda, Docker), users get the most current and relevant information to make informed decisions. 📈
- **Streamlined User Experience:** The addition of Python version compatibility badges and clearer guidelines across documentation ensures a smoother, more intuitive interaction for users seeking to install or contribute to Ultralytics projects. 💡
- **Better Engagement:** Through more engaging and informative documentation, users are more likely to successfully install and use Ultralytics offerings, potentially increasing adoption and community participation. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q also we have an existing conda-forge badge in our Docs, probably best to re-use the same badge:
https://docs.ultralytics.com/quickstart/

**Comment by Burhan-Q** [comment]
Absolutely. On mobile at the moment and didn't want this to slip, but knew there's were fixups and other locations to update.

**Comment by Burhan-Q** [comment]
@glenn-jocher a few questions regarding standardization. 
1. The PyPi badge that is already in the README.md file uses markdown formatting, but the badges at the top use HTML, I presume that the ones at the top should continue to use HTML formatting (to keep centered)? Unless otherwise directed, I will make changes on the assumption this is correct.
2. The Quickstart from `/docs` has a `conda` version badge using a shields.io link `[Conda Version]`, but the PyPi version badge in the README.md uses a badge.fury.io link `[PyPI version]` which lacks support for `conda-forge` packages (as far as I could find). Due to this, I think it would make sense to migrate badges to use shields.io links instead, but let me know if you'd prefer something else.
3. I also see a mix of markdown formatted and HTML formatted badges in the docs (`conda` vs Docker on the Quickstart page). Given the principle of (1) above, I suspect that following a similar strategy would make sense. Where the badges require alignment, I will keep as HTML otherwise use markdown formatting. This will be how I will make changes unless otherwise directed.
4. I was also thinking that adding a python version support badge would be useful. [PyPI - Python Version](https://pypi.org/project/ultralytics/) (populated from PyPi). What are your thoughts here? I think adding this to the README.md and Docs Home page would make the most sense.

**Comment by Burhan-Q** [comment]
- [65817fd](https://github.com/ultralytics/ultralytics/pull/13021/commits/65817fd4ffb12d88615dc5d1764c2245927ff698) formatter reverted a change from [d5235e3](https://github.com/ultralytics/ultralytics/pull/13021/commits/d5235e3c14d52a186d38d5c1b8b99a7a4df8ebde) that I thought was helpful for readability where the markdown badges could each be placed on newlines, but still would render on a single line. Only the top-level `README.md` and `README.zh-CN.md` files were changed, but pages under `docs/en` were not updated.
  
  <details><summary>Preview</summary>
  <p>
  
  ### NOTE screenshot colors due to display settings and not representative of true coloring
  
  image
  
  </p>
  </details> 

- With [6d4702a](https://github.com/ultralytics/ultralytics/pull/13021/commits/6d4702a13b347ca416ead663c96595266605dc41) made the same change as #11801 to the Chinese language README

- updated link text in `docs/en/quickstart.md` from `requirements.txt` to `pyproject.toml` (link was already pointing to TOML file)

- replaced `badge.fury.io` badge links with `img.shields.io` for uniformity

- HTML badges replaced with markdown badges wherever there was no alignment/formatting used

- included additional badges for python versions, GitHub last commit, GitHub total commits, Docker version (most in `docs/en/quickstart.md`, and replicated anywhere else it made sense)
  
  <details><summary>Quickstart <code>pip</code></summary>
  <p>
  
  image
  
  </p>
  </details> 
  
  <details><summary>Quickstart <code>conda</code></summary>
  <p>
  
  image
  
  </p>
  </details> 
  
  <details><summary>Quickstart <code>git clone</code></summary>
  <p>
  
  image
  
  </p>
  </details> 
  
  <details><summary>Quickstart <code>Docker</code></summary>
  <p>
  
  image
  
  </p>
  </details> 

- No modifications made to YOLOv5 badges

**Comment by glenn-jocher** [comment]
@Burhan-Q thanks for updates! Could we do this?

- Leave the existing badges under the banner in place
- Place the new pip, conda, downloads, python-version badges in the install sections?

**Comment by Burhan-Q** [comment]
> @Burhan-Q thanks for updates! Could we do this?
> 
> * Leave the existing badges under the banner in place
> * Place the new pip, conda, downloads, python-version badges in the install sections?

Assuming that I understood the above requested changes correctly:
- [x] Removed the added badges to the Docs Home page, under the banner
- [x] Removed added badges from repository README.md files under the banner. 
- The added badges for the Docs are only shown on the Quickstart page under the install section, with the appropriate badge(s) for each tab.
- The repository README.md files show badges for PyPi version, PyPi downloads, and Python versions in the installation section.
- No other changes since [153084b](https://github.com/ultralytics/ultralytics/pull/13021/commits/153084b182e97182924c6a077d3add6f20a1b838)

<details><summary>Docs home page</summary>
<p>

image

</p>
</details> 

<details><summary>Docs quickstart install</summary>
<p>

(no change since 153084b)

image

</p>
</details> 

<details><summary>Repo README</summary>
<p>

## Under banner

image

## Install section

(no change since 153084b)

image

</p>
</details> 

<details><summary>Repo Chinese README</summary>
<p>

## Under banner

image

## Install section

(no change since 153084b)

image

</p>
</details>

**Comment by glenn-jocher** [comment]
@Burhan-Q hey this is good! But we can also place that nice new Conda badge in the README, either next to the PyPI badge or lower down after the line talking about Conda install.

**Comment by Burhan-Q** [comment]
Updated! Links on each badge point to the appropriate Ultralytics Conda, Docker, and GitHub link. Put all three since each was mentioned. 

image

> [!NOTE]
> Instead of showing the `commit` count, I could change the Git badge to show the latest tagged version on GitHub `v8.2.0` but I thought showing the commit count would be a better choice for now. Additionally, the Git logo is shown instead of GitHub, since the statement above calls out `Git` specifically, but could be changed if preferred.

**Comment by glenn-jocher** [comment]
@Burhan-Q commits is a bit excessive, I would remove. Then this should be good to merge!

**Comment by glenn-jocher** [comment]
@Burhan-Q ok everything looks good, nice improvements! I also merged https://github.com/ultralytics/docs/pull/70 to sync our actual Docs readme to this one.

**Comment by glenn-jocher** [comment]
PR merged!

**Pull request merged**
