### PR TITLE
add resnet18 and resnet34 model config

### PR DESCRIPTION
**Pull request by Lornatang**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
New ResNet-based image classification models and enhanced neural network modules added.

### 📊 Key Changes
- Added **BasicBlock** and **BasicLayer** classes for ResNet-18/34 layers.
- Introduced new configuration files (`yolov8-cls-resnet18.yaml` and `yolov8-cls-resnet34.yaml`) for YOLOv8 image classification using ResNet architectures.
- Updated module initialization to include **BasicLayer**.

### 🎯 Purpose & Impact
- 🧠 **Enhanced Modeling**: The new BasicBlock and BasicLayer classes enable more flexible and efficient ResNet-18/34 architectures, improving model customization.
- 📸 **Better Image Classification**: With the new config files, users can leverage ResNet-based YOLOv8 models for improved image classification tasks.
- 👩‍💻 **Developer Friendly**: Streamlines the process of defining and using ResNet-based layers, making it easier for developers to experiment and optimize models.

### CODE REVIEW

**Comment by Lornatang** [comment]
Whether this merger I successfully signed CLA?

**Comment by Lornatang** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Lornatang** [comment]
@glenn-jocher Hey, this PR you'll merge?

**Comment by glenn-jocher** [comment]
Hello @Lornatang,

Thank you for your interest in this PR! We appreciate your engagement. The PR introduces ResNet18 and ResNet34 configurations for YOLOv8 classification models, along with a new `BasicLayer` architecture to enhance modularity and flexibility. These additions aim to expand our model variety and improve customization options for image classification tasks.

Before we proceed with merging, we will conduct a thorough review to ensure everything aligns with our coding standards and performs as expected. If you have any specific feedback or suggestions regarding this PR, please feel free to share them.

Thanks again for your contribution and support! 🚀

**Pull request closed without merging**
