### PR TITLE
Optimize Example YOLO post-processing speed

### PR DESCRIPTION
**Pull request by franklinOliveira**
Evaluating the inference time using Coral Accelerator, i can observer that the post-processing function consumes around 530ms of Banana Pi P2 Zero time. After the proposed change, this time reduced to around 70ms.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimized the YOLOv8-OpenCV-tflite example for faster and more efficient processing.

### 📊 Key Changes
- Transposed predictions outside loops for efficiency.
- Vectorized extraction of bounding boxes, scores, and class IDs.
- Combined Non-Maximum Suppression (NMS) tasks for all detections in a single step.
- Precomputed image scaling (gain) and padding once, rather than repeatedly.

### 🎯 Purpose & Impact
- 🏃‍♂️ **Faster Processing:** Improved the speed by reducing redundant calculations.
- 🔍 **Enhanced Efficiency:** Streamlined detection by processing multiple predictions simultaneously.
- 📈 **Better Performance:** Optimizations may lead to quicker inference times, enhancing usability in real-time applications.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @franklinOliveira, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to help get your contribution integrated smoothly. An Ultralytics engineer will review your changes soon. In the meantime, please review the following checklist:

- ✅ **Define a Purpose**: Ensure your PR description clearly explains the purpose of these optimizations and links to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Your commit messages should be clear and adhere to our guidelines.
- ✅ **Synchronize with Source**: Confirm your branch is up to date with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by using the 'Update branch' button or running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. Address any issues if they arise.
- ✅ **Update Documentation**: Update relevant [documentation](https://docs.ultralytics.com) for these performance improvements.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, ensuring all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by writing "I have read the CLA Document and I sign the CLA" as a comment if this is your first PR with us.
- ✅ **Minimize Changes**: Limit changes to what's necessary for the optimization. _"It is not daily increase but daily decrease, hack away the unessential."_ — Bruce Lee

If helpful, please provide a minimum reproducible example (MRE) for better clarity on the performance improvements observed.

For more guidance, check our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to ask questions here. Thanks for helping enhance Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@franklinOliveira please sign the CLA like this below to allow us to integrate your work! Thank you! In a new message write:

I have read the CLA Document and I sign the CLA

**Comment by franklinOliveira** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@franklinOliveira PR merged! Thank you for your contributions!

**Pull request merged**
