### PR TITLE
`__getattr__` support to access YOLO attributes via Model class

### PR DESCRIPTION
**Pull request by WYYAHYT**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Introduced changes to streamline attribute access and improve model behavior in the Ultralytics engine.

### 📊 Key Changes  
- 🔄 Removed `self.training` in the model to ensure consistent access to `self.model.training`.  
- 🧩 Added a `__getattr__` method, enabling direct access to attributes of the underlying model through the parent `Model` class.

### 🎯 Purpose & Impact  
- 🚀 **Enhanced usability:** Users can now directly query model attributes (e.g., `stride`, `task`) from the `Model` object, making interaction with the model simpler and more intuitive.  
- 🛠️ **Cleaner handling of training state:** By removing `self.training`, the implementation reduces potential conflicts in managing the training state.  
- 💡 **Improved developer experience:** More seamless and consistent access to model internals ensures smoother development and debugging for users.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @WYYAHYT, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Thank you for clearly outlining your PR's purpose! Your summary and description are detailed, and the improvements to the `Model` class are well-described. If there are related [issues](https://github.com/ultralytics/ultralytics/issues), please link to them for completeness.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: As your PR introduces changes to the `Model` class, ensure any related [documentation](https://docs.ultralytics.com) is appropriately updated for users.
- ✅ **Add Tests**: If applicable, please include or update tests to ensure the new `__getattr__` functionality and `super().training` removal work as expected. Confirm that all tests are passing to guarantee stability.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: You've done a great job keeping your changes focused on enhancing attribute access and removing unnecessary complexity! Maintaining a small, purposeful diff ensures easier reviewing.  

_"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. One of our engineers will review your PR soon. Thanks again for contributing to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@WYYAHYT seems like a very cool idea. Any downside to this?

**Comment by WYYAHYT** [comment]
@glenn-jocher Not yet, I have checked it already,  there was no downside found during my use. After all, it acts like a bridge between `wrapped model` and `inner model` and does no affects on either connected "coasts".

**Comment by glenn-jocher** [comment]
Thank you for confirming, @WYYAHYT. If there are no downsides or concerns, your PR will be reviewed by the team shortly. We appreciate your effort in improving the usability and functionality of the `Model` class!

**Comment by glenn-jocher** [comment]
@WYYAHYT PR merged. Thank you for your contributions!

**Pull request merged**
