### PR TITLE
Ray tune AHB hyper parameter tuning & W&B support

### LINKED ISSUE #330: Evolve for yolov8
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, is there a --evolve method for yolov8, if so, can I get instructions on how to run it?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by AyushExel**
`pip install "ray[tune]"`
Usage:
```
model = YOLO('yolov8n.pt')
result = model.tune(data="coco128.yaml", space={"epochs": tune.choice([2,3,6]),
                                                "lr0": tune.uniform(0.001,0.1), 
                                                "imgsz":tune.choice([16,32,64])}, max_samples=3)
```

### Summary
📦🎛️🐛

This pull request adds a new feature to the ultralytics/yolo package: hyperparameter optimization with Ray Tune. It also improves the documentation, readability, and consistency of some existing modules.

> _Oh we're tuning up the YOLO with the Ray Tune callbacks_
> _We're searching for the best params with the AHB and PBT_
> _We're loading up the data with the `get_dataloader` method_
> _And we're fixing up the comments to make the code look neat_

### Walkthrough
*  Add `tune` method to `YOLO` class to enable hyperparameter tuning using Ray Tune ([link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cR382-R468))
*  Define Ray Tune callbacks in `raytune.py` module and integrate them with base callbacks in `base.py` module ([link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-fc87378d52ab79f3c996bad383d2e49722c2841db7c7414ceb8876aff0f6a2c8R1-R15), [link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-9fc76880dc9f2de05ad711555618b1501ea5a833756ff6884e0839fe2b150f0bL157-R160))
*  Define utilities for hyperparameter tuning using Ray Tune in `tuner.py` module ([link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-b1729b763cbaa3709b267481a09ee9bae7455750784b32e2acacefccfd97934eR1-R31))
*  Add docstring to `load_inference_source` function in `build.py` module ([link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL165-R176))
*  Explain the use of `setattr` to attach source types to dataset object in `build.py` module ([link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL195-R207))
*  Change the order of arguments `mode` and `rank` in `get_dataloader` method of `DetectionTrainer` class to match parent class in `train.py` module ([link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L24-R24))
*  Remove empty line and change comments to improve code readability and style consistency in `model.py` and `trainer.py` modules ([link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL359), [link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L116-R116), [link](https://github.com/ultralytics/ultralytics/pull/1796/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L246-R246))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduction of hyper-parameter tuning capability in the Ultralytics YOLO model training engine using Ray Tune.

### 📊 Key Changes
- 🛠️ **Hyper-parameter Tuning Functionality**: Added `tune` method to the `model.py` allowing users to run hyper-parameter optimization.
- 🧩 **Ray Tune Integration**: Included necessary libraries from `ray` package to support the tuning process.
- 🔄 **Callbacks Support**: Expanded existing callbacks in `base.py` to work with `raytune.py`. 
- 🔍 **Default Search Space**: Implemented default hyper-parameter space in `tuner.py` if a custom one is not provided by the user.

### 🎯 Purpose & Impact
- ✨ **Enhanced Model Performance**: Users can now optimize their model's hyper-parameters to achieve better performance metrics.
- ⚙️ **Automation & Efficiency**: Automates the process of hyper-parameter search, potentially saving users time and effort in manual experimentation.
- 📈 **Customization and Flexibility**: Provides a structure to define custom search spaces, fitting a variety of use cases and datasets.
- 🔌 **Integration with Wandb**: Supports integration with Weights & Biases (Wandb) for logging and visualizing tuning experiments.

### CODE REVIEW

**Comment by N-Friederich** [comment]
@AyushExel Thanks for the implementation. Srry, I haven't had time in the past weeks.

**Comment by PalTAJ** [comment]
Hello, i was trying to replicate this following the instructions above, i get the error below:

`
TuneError: The Ray Tune run failed. Please inspect the previous error messages for a cause. After fixing the issue, you can restart the run from scratch or continue this run. To continue this run, you can use tuner = Tuner.restore("runs/_tune_2023-04-23_09-02-18").
 `

**Comment by glenn-jocher** [comment]
@PalTAJ the error message you received indicates that there may have been an issue during the hyperparameter tuning process. The error message is not providing enough information about the root cause of the issue, so it's hard to troubleshoot further without more context. Some possible reasons might include incorrect hyperparameters or the absence of some necessary dependencies for Ray Tune. It's also possible that there was an issue with the setup of the project itself. I suggest reviewing the instructions again and making sure all steps were followed correctly. You can also check if the issue is documented on the issue tracker of the repository or you can reach out to the Ultralytics YOLOv8 community for support.

**Comment by AyushExel** [comment]
@PalTAJ are you following this tutorial https://docs.ultralytics.com/usage/hyperparameter_tuning/?h=tune ?

**Comment by PalTAJ** [comment]
i found a solution for this problem, but it only worked on python 3.9.
i first cloned the ultralytics repo then went to model.py file , where we have the following code:

`        tuner_callbacks = [WandbLoggerCallback(project='yolov8_tune') if wandb else None]

        # Create the Ray Tune hyperparameter search tuner
        tuner = tune.Tuner(trainable_with_resources,
                           param_space=space,
                           tune_config=tune.TuneConfig(scheduler=asha_scheduler, num_samples=max_samples),
                           run_config=RunConfig(callbacks=tuner_callbacks, local_dir="./runs")

                          )
`

if we change callback in run_config variable to None directly or removed that line, the process will run.
example:
`run_config=RunConfig(callbacks=None, local_dir="./runs")`

i understand that the following code returns [None] and for this to work i needed to simply change it to None.

`tuner_callbacks = [WandbLoggerCallback(project="yolov8_tune") if wandb else None]`

as you can see im not using wandb.

**Comment by AyushExel** [comment]
Ohh I think wandb is not optional then. Okay good to know. I'll fix this

**Comment by glenn-jocher** [comment]
Removed TODO label as completed in a separate PR.

**Pull request closed without merging**
