### PR TITLE
Adds back-off retry attempts when saving model

### PR DESCRIPTION
**Pull request by psaxton**
Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:

1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.

2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.

3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.

4. **Ultralytics Contributor License Agreement (CLA)**: To uphold the quality and integrity of our project, we require all contributors to sign the CLA. Please confirm your agreement by commenting below:

    _I have read the CLA Document and I hereby sign the CLA_

For more detailed guidance and best practices on contributing, refer to our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing). Your adherence to these guidelines ensures a faster and more effective review process.

This works around the #7087. The cause I've observed is that the previous file is still open by my anti-virus software when yolo attempts to write the next _last.pt_ file. I often encounter this issue when training a small model (yolov8n) against a small dataset with many epochs. I am able to resume the previous training, but there is a large amount of additional delay each time I need to restart. Setting `save_periods` to a larger value does not resolve the issue entirely as the CLI still writes _last.pt_ for each epoch.

This PR introduces a basic back-off loop to re-attempt the save up to 5 times after a short delay.

** Ultralytics Contributor License Agreement:** _I have read the CLA Document and I hereby sign the CLA_

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved reliability for saving models.

### 📊 Key Changes
- Added a test to ensure `torch_save` handles `RuntimeError` correctly.
- Enhanced `torch_save` to retry saving up to 3 times with exponential backoff.

### 🎯 Purpose & Impact
- The changes aim to make saving models with `torch.save` more robust, particularly when encountering transient save-related errors.
- Users benefit from reduced failure rates when saving models, especially in environments with possible file-system delays or security software interactions. ⏳💾

### CODE REVIEW

**Comment by psaxton** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by glenn-jocher** [comment]
@psaxton hi, is there a bug report that this resolves or a reproducible example we can see that would merit the addition?

Also where are you defining the new variables you introduced like `delay`? The PR seems broken to me.

**Comment by psaxton** [comment]
The bug report is #7087 as mentioned in the op. The problem can be reproduced by attempting to run many epochs (150 in my case) using a small model (yolov8n) against a small dataset (23 images in my case) while having a slow corporate mandated antivirus process locking the last.pt file for an extra second or two on each epoch.

I see now that I copy/paste failed on my submission. The `num_retries` and `delay` values are local to the function. I just pushed a fix for that.

I'm writing a test case that proves the `torch_save` function will attempt 5 tries and then throw if the underlying `_torch_save` function throws a RuntimeError. I've included the test in that commit since the current HEAD is broken anyway.

**Comment by psaxton** [comment]
Sorry for the multiple commits. I'm not normally a python developer and can't seem to get `pytest` to run the tests locally. This should succeed.

**Comment by psaxton** [comment]
I have read the CLA Document and I sign the CLA

**Comment by psaxton** [comment]
recheck

**Comment by psaxton** [comment]
@glenn-jocher Sorry for the circus there. I believe this PR now valid and ready.

**Comment by glenn-jocher** [comment]
@psaxton No worries at all, and thank you for the update! We'll review the changes and get back to you shortly. Your patience and contributions are much appreciated! 🙌

**Comment by glenn-jocher** [comment]
@psaxton PR merged! Thank you for your contributions.

**Pull request merged**
