### PR TITLE
Release 8.0.4 fixes

### LINKED ISSUE #188: asset does not exist
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

YOLOv8s summary: 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8s.pt', 'source=0']
Traceback (most recent call last):
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\cli.py", line 52, in cli
    func(cfg)
  File "D:\YOLOv8\venv\lib\site-packages\hydra\main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\v8\detect\predict.py", line 92, in predict
    predictor()
  File "D:\YOLOv8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 152, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 136, in setup
    self.dataset = LoadImages(source, imgsz=imgsz, stride=stride, auto=pt, vid_stride=self.args.vid_stride)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: D:\YOLOv8\venv\Lib\site-packages\ultralytics\assets does not exist

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### Environment

YOLOv8s summary: 168 layers, 11156544 parameters, 0 gradients, 28.6 GFLOPs
Error executing job with overrides: ['task=detect', 'mode=predict', 'model=yolov8s.pt', 'source=0']
Traceback (most recent call last):
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\cli.py", line 52, in cli
    func(cfg)
  File "D:\YOLOv8\venv\lib\site-packages\hydra\main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\v8\detect\predict.py", line 92, in predict
    predictor()
  File "D:\YOLOv8\venv\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 152, in __call__
    model = self.model if self.done_setup else self.setup(source, model)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 136, in setup
    self.dataset = LoadImages(source, imgsz=imgsz, stride=stride, auto=pt, vid_stride=self.args.vid_stride)
  File "D:\YOLOv8\venv\lib\site-packages\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 171, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: D:\YOLOv8\venv\Lib\site-packages\ultralytics\assets does not exist

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #236: Unable to see predictions on test data.
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I have tried to train on a custom dataset where training is completed successfully. The detection/prediction script works correctly as well but cannot see the images after detection has completed. There are bunch of empty folders created after  running the script with the name of images. Same issue with videos.

Here is a screenshot of the issue ..
Untitled

### Environment

Environment : Google Colab

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #252: Models not present as download
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Your links are not working, the downloads for the example models in your top page are leadings to a 404 page. 

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by AyushExel**
TODO:
- [ ] Don't use DDP by default in cli  @Laughing-q I've tried to fix it can you check? I guess it was a cli specific problem
- [x] use `cfg` as special key to set config file

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactor and adjust configuration management, modify model download URLs, and adapt test scripts to a new directory structure.

### 📊 Key Changes
- Changed model download URLs from the `yolo/v8/models` subdirectory to a more general `models` directory.
- Updated model download references to point to a new repository `ultralytics/assets/releases`.
- Reworked CLI syntax for specifying a custom config file from `--cfg name.yaml` to `cfg=name.yaml`.
- Adjusted test scripts to use new data sources and reflected changes in test setups (e.g., `mnist160` instead of `imagenette160`).
- Made various codebase improvements, including removing redundant outputs in predictors and ensuring only necessary arguments are used.

### 🎯 Purpose & Impact
- Streamlining the directory structure and improving model download links help in maintaining a clean repository structure. 🧹
- Updated CLI syntax improves consistency and reduces potential confusion for users when passing custom configs. 🛠
- Adapting test scripts ensures that all tests remain functional after directory and URL changes, supporting regression testing. 🧪
- Codebase improvements remove unnecessary outputs and clean up argument handling, leading to a more efficient and less error-prone experience both for developers and users. 👨‍💻👩‍💻

### CODE REVIEW

**Comment by AyushExel** [comment]
@Laughing-q what does select_device('') return for you?

**Comment by Laughing-q** [comment]
@AyushExel cuda:0

**Comment by AyushExel** [comment]
Okay can you test again.. I tested, the self.args.device is set to '' in the trainer.. I don't understand why this is happening.
Maybe because of this line in train() function?
`world_size = torch.cuda.device_count()`
I think we need to call set device before calling this line

**Comment by Laughing-q** [comment]
@AyushExel it still launched DDP. 
> I think we need to call set device before calling this line

I remember we're calling select_Device in Trainer.__init__.

**Comment by Laughing-q** [comment]
@AyushExel ok I know that's because these lines need we point out device.
[https://github.com/ultralytics/ultralytics/blob/55b313b167d2e65910058ca5710483c90a8208c4/ultralytics/yolo/utils/torch_utils.py#L70-L73](https://github.com/ultralytics/ultralytics/blob/55b313b167d2e65910058ca5710483c90a8208c4/ultralytics/yolo/utils/torch_utils.py#L70-L73)

**Comment by Laughing-q** [comment]
@AyushExel can we just set `device: 0` as default?

**Comment by AyushExel** [comment]
@Laughing-q oh then just checking `if device is not None` should work? If you confirm I'll add it to this PR

**Comment by Laughing-q** [comment]
@AyushExel you mean device='' and update the condition to `if device is not None`?
it'll raise an error
image

**Comment by Laughing-q** [comment]
oh BTW can you also update the assert msg?

**Comment by AyushExel** [comment]
> @AyushExel can we just set `device: 0` as default?
This will throw error on cpu devices.. I tried with `yolo device=0` on my mac

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q default should be device=None or device='', and then in order of priority:

1. If CUDA is available defaults to device 0
2. If MPS is available (Apple M1/M2) defaults to 'mps'
3. Defaults to 'cpu'

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q all pending PRs merged into this PR now

**Comment by glenn-jocher** [comment]
@gokulnath30 and @partheee please add a comment in this PR with the following text:

I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q ok I see there's a DDP issue in main. I'll debug it on the server and try and push a fix in this branch. 

One important thing can you guys go through all the bug issues and link them here to this PR? Then they will be automatically closed one we merge this PR :)

Screenshot 2023-01-11 at 16 49 45

**Comment by AyushExel** [comment]
https://github.com/ultralytics/ultralytics/issues/236
https://github.com/ultralytics/ultralytics/issues/188

**Comment by AyushExel** [comment]
@glenn-jocher please verify the last commit that I made ^.. Module attribute was undefined for onnx case so I set the default value to None. It fixes this issue for me - https://github.com/ultralytics/ultralytics/issues/266
It is okay to keep it None or should be initialized.

**Comment by glenn-jocher** [comment]
@AyushExel seems fine, but I've added a TODO to test against other backends.

We need a comprehensive export and inference CI to test these like we have in YOLOv5 benchmarks.py

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q merging this now, will handle DDP in a separate fix PR.

**Pull request merged**
