### PR TITLE
`ultralytics 8.2.24` set ENV `OMP_NUM_THREADS=1`

### PR DESCRIPTION
**Pull request by glenn-jocher**
@Laughing-q can you test this PR to see if moving the ENV definitions earlier in the imports fixes the high CPU-usage problem?

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements in Ultralytics software improve efficiency and organization.

### 📊 Key Changes
- Removed a line of code testing YOLO export to TFLite format in CI workflow.
- Updated the software version to 8.2.24.
- Set environment variable to reduce CPU usage during training.
- Reorganized model imports for cleaner code structure.
- Improved the string formatting for table names in the data explorer.
- Simplified assertion for return types to cleaner syntax.
- Streamlined the GUI layout logic for displaying images.
- Made `FastSAM` and `NAS` models explicitly available for import.

### 🎯 Purpose & Impact
- **Efficiency Boost:** Setting `OMP_NUM_THREADS` reduces CPU overload during training, potentially speeding up the process for users. 🚀
- **Code Cleanliness:** Reorganizing imports and streamlining assertions and layout logic makes the codebase more maintainable and understandable. ✔️
- **User Access:** Explicitly including `FastSAM` and `NAS` in the package's `__all__` list makes these models easier to access and work with, broadening the toolbox for developers and researchers. 🛠️
- **Streamlined Development:** Removal of TFLite format export test and version bump facilitate smoother development and deployment processes, ensuring users get the latest, most efficient version. 🔄

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher nope it didn't work out to me.
pic-240528-1042-43

**Comment by glenn-jocher** [comment]
@Laughing-q ok I've moved it up as high as it can go, can you retry now?

**Comment by Laughing-q** [comment]
> @Laughing-q ok I've moved it up as high as it can go, can you retry now?

I think I've tried the same thing, but didn't work out...let me test it again

**Comment by Laughing-q** [comment]
@glenn-jocher it's working!!!
pic-240528-1650-56

**Comment by glenn-jocher** [comment]
@Laughing-q yay awesome!!

**Review by Laughing-q — APPROVED** [review]

**Pull request merged**
