### PR TITLE
Support Multilanguage for imread and imwrite

### PR DESCRIPTION
**Pull request by developer0hye**
### Summary
📷🌐😊

Added `imread` and `imwrite` functions to handle filenames with emojis or non-ASCII characters in `ultralytics/yolo/utils/__init__.py`. Redefined cv2 functions to use the new wrappers for better compatibility and robustness.

> _`imread`, `imwrite`_
> _wrap OpenCV functions_
> _autumn of emojis_

### Walkthrough
*  Define new functions `imread` and `imwrite` to handle filenames with emojis or non-ASCII characters ([link](https://github.com/ultralytics/ultralytics/pull/2103/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137L737-R753))
*  Redefine OpenCV functions `cv2.imread` and `cv2.imwrite` to use the new wrappers ([link](https://github.com/ultralytics/ultralytics/pull/2103/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137L737-R753))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of OpenCV functions to support multilingual file paths.

### 📊 Key Changes
- Added a custom `imread` function to handle reading images using file paths with non-ASCII characters.
- Implemented a custom `imwrite` function that ensures images are saved to paths containing multilingual characters.
- Upgraded the `imshow` function to correctly display window titles with non-ASCII characters.

### 🎯 Purpose & Impact
- **Purpose**: To overcome issues with OpenCV's standard functions that struggle with file paths containing non-ASCII, especially multilingual characters. 
- **Impact**: These changes will allow Ultralytics users with multilingual environments to read, write, and display images without encountering errors due to path encoding issues. This makes their tools more accessible globally. 🌍✨

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@developer0hye great idea, thanks for the PR! 

I've updated the implementation to match YOLOv5.

**Comment by developer0hye** [comment]
@glenn-jocher Jocher, I couldn't load an image containing Korean with the modified code.

my command: yolo train task=detect model=yolov8n.yaml pretrained=yolov8n.pt epochs=300 workers=0


image

`Path(inspect.stack()[0].filename).parent.parent.as_posix() in inspect.stack()[-1].filename` returns False


image

image

image

**Comment by glenn-jocher** [comment]
Hello @developer0hye, sorry to hear that you are experiencing issues with file paths containing Korean characters. It looks like you provided some screenshots, which is a great way to help identify the issue. It seems that the `Path` method is failing to identify the correct path, resulting in the error you encountered. Can you confirm that the file exists in the provided path, and that you are using the correct path syntax? If you continue to encounter issues, please let me know and we can investigate further. Additionally, feel free to refer to our documentation at https://docs.ultralytics.com for more information on file handling with YOLOv8.

**Comment by developer0hye** [comment]
@glenn-jocher Thanks for reviewing it!

I confirmed that the file existed in the provided path.

**Comment by glenn-jocher** [comment]
@developer0hye, thanks for confirming that the file exists in the provided path, and it sounds like the path syntax is correct. It's possible that the issue might be related to how Python is interpreting the Korean characters in the file path. I would recommend trying to use the unicode escape sequence for the Korean characters in the file path, which should help Python recognize the path correctly. You can refer to our documentation at https://docs.ultralytics.com for more information on how to handle unicode characters in file paths.

**Pull request merged**
