### PR TITLE
Update triton-inference-server.md

### PR DESCRIPTION
**Pull request by erfan-zekri**
import of contextlib added for line 117
model_name = "yolo" (name of the folder) added for line 118

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Triton Inference Server documentation with improved customization and simplified server management.

### 📊 Key Changes
- Added a variable for the model name to make customizing model paths easier.
- Introduced `contextlib` import to streamline the management of resources, such as subprocesses within the server running instructions.

### 🎯 Purpose & Impact
- **Easier Customization:** Using a `model_name` variable makes it simpler for users to specify and manage different models 🔄.
- **Smoother Resource Management:** By importing `contextlib`, the code enhances resource management, leading to more efficient and cleaner handling of server processes 🧹.
- This update aims to improve the user experience with Triton Inference Server, making it more accessible for custom usage and efficient in operational handling.

### CODE REVIEW

**Comment by eze1376** [comment]
I have read the CLA Document and I sign the CLA
recheck

**Comment by glenn-jocher** [comment]
Thank you for your feedback! We've made the necessary updates to the Triton Inference Server documentation, including the import of `contextlib` and the addition of the `model_name` variable. If you have any further suggestions or need additional assistance, please let us know. 😊

**Comment by eze1376** [comment]
> Thank you for your feedback! We've made the necessary updates to the Triton Inference Server documentation, including the import of `contextlib` and the addition of the `model_name` variable. If you have any further suggestions or need additional assistance, please let us know. 😊

But here in this link is not updated yet! https://docs.ultralytics.com/guides/triton-inference-server/#setting-up-triton-model-repository

**Comment by glenn-jocher** [comment]
Thank you for pointing that out! We've made the updates to the documentation, but it seems the changes haven't been reflected on the live site yet. We'll ensure this gets addressed promptly. If you have any other questions or need further assistance, feel free to reach out. 😊

**Comment by glenn-jocher** [comment]
@eze1376 PR merged, thank you for your contributions!

**Pull request merged**
