### PR TITLE
Improve YOLOv8 ONNX Runtime c++ example for all OS with `CmakeList.txt` support

### LINKED ISSUE #4273: Yolov8 onnxruntime cpp example only runs on windows
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

I was working a project based on cpp and I notice that example in here only works for windows and also using windows OS only header files. 

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by onuralpszr**
Hello, I was looking for onnxruntime cpp example and I notice that current example only works for windows so for that reason I changed headers and add CmakeList.txt file for compile in Linux and MacOS. I also added classNames for showing in top of box drawings and remove classNum param and match with "classNames" size based on other C++ example in repository. 

feat: 🚀 copy onnxruntime.dll to compiled folder for windows systems
docs:  📝adding CLI method for onnx export and remove classNum param
docs: 📝 refactor readme deps
feat: 🚀 add PNG support in example code
feat: 🚀 Write class labels in result picture
feat: 🚀 Adding class names 
feat: 🚀 change example code for support Linux and MacOS
feat: ✨ adding .gitignore for example project
feat: ✨ adding cmakelists.txt file

I tested those changes on Linux (Fedora 38) , MacOS  , Windows 11. I make sure it compiles on all of them and works for all of them with cmake 

Fix: #4273

### Summary
:hammer_and_wrench::mag::memo:

This pull request enhances the `examples/YOLOv8-ONNXRuntime-CPP` project, which demonstrates how to use ONNX Runtime C++ to perform YOLOv8 object detection. It improves the code quality, functionality, compatibility, and documentation of the project, and adds a CMakeLists.txt file to simplify the build process.

> _We unleash the beast of YOLOv8_
> _With ONNX Runtime on C++_
> _We optimize the code and the build_
> _We detect the objects of our fate_

### Walkthrough
*  Add the `CMakeLists.txt` file to configure the build system and specify the dependencies, options, and targets for the project ([link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-0eab08b13100cbf366bb5dd1e60d53ef94d7328b4d4710606a36b4abb114a9e4R1-R67))
*  Update the `inference.cpp` file to fix the dependent type name resolution, improve the indentation and readability, add conditional compilation for Windows, remove unused macro, and optimize the vector insertion ([link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L5), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L32-R31), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L43-R43), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L78-R82), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L89-R93), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L99), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L154-R157), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L162-R169), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L206-R210), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8R217), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8a52ad28c0e0fa1a4348a3b3d4380f9abafe6985bb935a1eec74d3b77b76fca8L269-R277))
*  Update the `inference.h` file to add conditional compilation for Windows, remove redundant variable, and add the classes vector ([link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-f5d599dd06fc6fe16f8d0baa50c155992f0769af08495431ad265ad74dc4f90fL3-R14), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-f5d599dd06fc6fe16f8d0baa50c155992f0769af08495431ad265ad74dc4f90fR28), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-f5d599dd06fc6fe16f8d0baa50c155992f0769af08495431ad265ad74dc4f90fL31-L32), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-f5d599dd06fc6fe16f8d0baa50c155992f0769af08495431ad265ad74dc4f90fL58-R68))
*  Update the `main.cpp` file to use the current path and the images subdirectory for the input images, support png images, display the labels of the detected objects, and use the GPU inference option by default ([link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-28cb94013fc250e467cb539711a034a9e30df3189162a7739f4593042bf93b63L2-R34), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-28cb94013fc250e467cb539711a034a9e30df3189162a7739f4593042bf93b63L36-R48))
*  Update the `README.md` file to remove the Visual Studio recommendation, update the export command for the model, and fix a typo in the initialization of the DCSP_INIT_PARAM structure ([link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8dcaf249262d078e57bbf538f19ad18478ae52f4909bd5d3eb32dd923cd95a4bL5-L6), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8dcaf249262d078e57bbf538f19ad18478ae52f4909bd5d3eb32dd923cd95a4bL28-R39), [link](https://github.com/ultralytics/ultralytics/pull/4274/files?diff=unified&w=0#diff-8dcaf249262d078e57bbf538f19ad18478ae52f4909bd5d3eb32dd923cd95a4bL42-R49))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
PR adds C++ example for YOLOv8 inference with ONNX Runtime.

### 📊 Key Changes
- Added a new C++ example with CMake support for YOLOv8 inference using the ONNX Runtime.
- Changed tensor processing and post-processing within the inference code.
- Removed various Windows-specific includes and macros to improve portability.
- Set C++17 as the standard to enable filesystem support.
- Included command for exporting a YOLO model to ONNX format from the terminal.
- Defined the dependencies and clarified versions for cross-platform building.

### 🎯 Purpose & Impact
- 🚀 Enhances the repository by providing a practical C++ example that demonstrates how to perform object detection with YOLOv8 models using the ONNX Runtime, which is beneficial for deployment in industrial contexts.
- ✅ Supports cross-platform compatibility by accommodating Windows, Linux, and macOS, making it accessible to a wider range of developers.
- 🌐 Encourages the adoption of Ultralytics models by showcasing their integration in different programming environments and frameworks.
- 🔄 Changes to inference coding practices can offer subtle improvements in performance and consistency across platforms, benefiting developers aiming to deploy machine learning models efficiently.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@onuralpszr thanks for the PR! Two quick questions:

- Can we remove the .gitignore file here as we already have one in root?
- Is it possible to read the default COCO class names from the YAML here rather than hardcoding them in `inference.h`?
https://github.com/ultralytics/ultralytics/blob/c9be1f3cce89778f79fb462797b8ca0300e3813d/ultralytics/cfg/datasets/coco.yaml#L16-L98

**Comment by onuralpszr** [comment]
@glenn-jocher  you have your yaml parser and I remove .gitignore as well.

**Comment by glenn-jocher** [comment]
@onuralpszr awesome! I like the emojis is the commits :)

**Comment by onuralpszr** [comment]
> @onuralpszr awesome! I like the emojis is the commits :)

I am glad you like it :)

**Comment by glenn-jocher** [comment]
@onuralpszr thank you for your constructive feedback! We made sure to apply those suggestions into the YOLOv8 ONNX Runtime C++ example. We've added support for all Operating Systems, and for ease of deployment, we've also added a `CmakeList.txt`. To add more details to the output, class names are now shown on top of the bounding boxes in the results.

We're pleased that the modifications are helpful and work well for you! If you have any more suggestions or feedback, please feel free to share!

**Comment by onuralpszr** [comment]
> @onuralpszr thank you for your constructive feedback! We made sure to apply those suggestions into the YOLOv8 ONNX Runtime C++ example. We've added support for all Operating Systems, and for ease of deployment, we've also added a `CmakeList.txt`. To add more details to the output, class names are now shown on top of the bounding boxes in the results.
> 
> We're pleased that the modifications are helpful and work well for you! If you have any more suggestions or feedback, please feel free to share!

I am glad it help out.  I missed a tiny a bit of docs. May I open direct PR without create an issue to handle that ?

**Comment by glenn-jocher** [comment]
@onuralpszr Sure, feel free to open a PR directly for small documentation adjustments. We always welcome contributions that make our codebase clearer for everyone. Thanks for your initiative in improving the YOLOv8 project!

**Pull request merged**
