### PR TITLE
Update results.py feat-save_in_csv feature

### PR DESCRIPTION
**Pull request by akashAD98**
feature: https://github.com/ultralytics/ultralytics/issues/4996

### Summary
📄📊🆕

Enhanced `save_txt` function in `ultralytics/engine/results.py` to support csv output for different tasks.

> _We face the doom of different tasks_
> _We need to save our predictions fast_
> _We unleash the power of `save_txt`_
> _We choose the format: txt or csv_

### Walkthrough
*  Add a new feature to save predictions in a csv file ([link](https://github.com/ultralytics/ultralytics/pull/4998/files?diff=unified&w=0#diff-24af401e53ffc5ce49197395e1e3d7111344ad31b08cbb2bee9377614da98955L280-R280), [link](https://github.com/ultralytics/ultralytics/pull/4998/files?diff=unified&w=0#diff-24af401e53ffc5ce49197395e1e3d7111344ad31b08cbb2bee9377614da98955L293-R300), [link](https://github.com/ultralytics/ultralytics/pull/4998/files?diff=unified&w=0#diff-24af401e53ffc5ce49197395e1e3d7111344ad31b08cbb2bee9377614da98955R314), [link](https://github.com/ultralytics/ultralytics/pull/4998/files?diff=unified&w=0#diff-24af401e53ffc5ce49197395e1e3d7111344ad31b08cbb2bee9377614da98955L314-R331))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of results saving with additional CSV output support.

### 📊 Key Changes
- Extended `save_txt` function to also save results in CSV format.
- Added support for writing detection/classification results to both `.txt` and `.csv` files.
- CSV output includes columns for `Image Name`, `Confidence`, and `Detection`.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: To provide users with a more standardized and widely-used format for analyzing and sharing detection results.
- 🚀 **Impact**: Users can now easily import results into spreadsheet software, databases, or other analysis tools, simplifying their workflows and improving compatibility with other systems.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@akashAD98 thanks for the PR! Can you please review the failing CI tests and implement fixes for those? Thanks!

**Comment by akashAD98** [comment]
below is code, i saw there is option in save_conf, so i simply writeen code for saving the results in csv file


is there anything i can cotribute this in repo? in the documention or code part?

image


```
import os
import csv

# Directory containing the text files
folder_path = '/content/drive/MyDrive/ai_healt/testing_real_images/op/unhelathypart2/predict/labels'

# Create and open the output CSV file
with open('/content/ops/output_csv.csv', mode='w', newline='') as csv_file:
    csv_writer = csv.writer(csv_file)
    csv_writer.writerow(['text file', 'class id', 'bounding box', 'confidence'])

    # Iterate through the text files in the folder
    for filename in os.listdir(folder_path):
        if filename.endswith(".txt"):
            with open(os.path.join(folder_path, filename), 'r') as txt_file:
                lines = txt_file.readlines()
                for line in lines:
                    # Split the line into components
                    components = line.strip().split()
                    if len(components) == 6:
                        class_id, x, y, w, h, confidence = map(float, components)
                        
                        # Write data to the CSV file
                        csv_writer.writerow([filename, int(class_id), f'{x} {y} {w} {h}', confidence])

print("CSV file 'output_csv.csv' has been created.")


```

**Comment by glenn-jocher** [comment]
@akashAD98 hi, thanks for sharing your code snippet! 

You seem to have developed a feature that saves the detection results of YOLOv8 in a CSV file. That's great! As it is now, our save function stores the results in TXT files. You've found a way to enhance it. 

Introducing such an option in the YOLOv8 repository could indeed be a valuable improvement and a useful feature for many users. Your code to parse .txt files to .csv may be adapted to being directly integrated into the YOLOv8 prediction script, as an additional saving option. 

Before submitting a pull request, please make sure that your feature works smoothly and doesn't hinder the existing functionalities in any way. Also bear in mind that changes may be requested during the review process to match the code style we maintain throughout the repository. 

I am looking forward to your contribution!

**Comment by glenn-jocher** [comment]
@akashAD98 I think the issue is that save_txt is used for a variety of tasks and models, and the PR code may not be robust to all these use cases. 

Is the ideal end-result that save_txt arguments will also output a single *.csv file in the run directory containing all images and predictions?

The code should be able to handle videos and streaming sources also, including combinations of videos and images in directories, and also support segment, pose and classify outputs.

**Comment by akashAD98** [comment]
> @akashAD98 I think the issue is that save_txt is used for a variety of tasks and models, and the PR code may not be robust to all these use cases.
> 
> Is the ideal end-result that save_txt arguments will also output a single *.csv file in the run directory containing all images and predictions?
> 
> The code should be able to handle videos and streaming sources also, including combinations of videos and images in directories, and also support segment, pose and classify outputs.

let me try all this & will give better code

**Comment by glenn-jocher** [comment]
@akashAD98 That sounds like a good plan. Please make sure your code can handle all outlined cases and supports these variety of tasks and models as well. Once your code can robustly save to .csv along with existing save_txt function, please feel free to submit another PR for review. Thank you for your contribution!

**Pull request closed without merging**
