### PR TITLE
`ultralytics 8.2.82` YOLOv10 CoreML, Edge TPU and TF.js export support

### PR DESCRIPTION
**Pull request by glenn-jocher**
@Burhan-Q @Laughing-q

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated YOLOv10 documentation and improved model export support for various formats.

### 📊 Key Changes
- Enhanced export support table in YOLOv10 documentation.
- Updated post-processing logic in `head.py` for predictions.
- Version bump from 8.2.81 to 8.2.82.

### 🎯 Purpose & Impact
- **Improved Clarity:** The export support table now includes additional details such as exported model inference and specific notes for each format, making it clearer for users. 📃✅
- **Enhanced Processing:** The refined post-processing logic in `head.py` ensures more robust handling of model predictions, which could lead to better performance. 📈🤖
- **Version Update:** The bump to version 8.2.82 signifies ongoing improvements and stability enhancements. 🚀✨

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q @Laughing-q PR speeds up postprocess ops by 2x, i.e. for batch=4 I see 1.2ms before to 0.5ms now.

**Comment by Laughing-q** [comment]
@glenn-jocher Unfortunately this PR causes mAP drop: 38.4(main) --> 37.4(this branch)
```python
yolo detect val data=coco.yaml batch=128 half model=yolov10n.pt
```
I also found there's something we could simplify in the post-processing but also caused a slightly mAP drop so I left a note there.

**Comment by glenn-jocher** [comment]
@Laughing-q ah, yes I think I understand. This PR is just outputting the top 300 anchors per image, but does not have `multi_label` enabled.

I'll see if I can update to output the top 300 labels with multiple of different classes from the same anchor allowed.

**Comment by glenn-jocher** [comment]
@Laughing-q ok latest changes keep mAP, gather op replaced by index op that seems to resolve all export issues.

```
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.384
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets=100 ] = 0.538
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets=100 ] = 0.417
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.190
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.424
 Average Precision  (AP) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.546
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=  1 ] = 0.323
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 10 ] = 0.540
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets=100 ] = 0.603
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= small | maxDets=100 ] = 0.378
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=medium | maxDets=100 ] = 0.660
 Average Recall     (AR) @[ IoU=0.50:0.95 | area= large | maxDets=100 ] = 0.779
```

**Comment by rromanchuk** [comment]
I'm trying to grok this PR, specifically RE CoreML.  

Is there an example vanilla one liner demonstrating `format=coreml model=yolov10n.pt` to sanity test against  latest main?

Trying to find find a test to guide, but looks like these only cover v8? 
https://github.com/ultralytics/ultralytics/blob/main/tests/test_exports.py#L121

**Comment by glenn-jocher** [comment]
@rromanchuk to export a YOLOv10 model to CoreML, you can use the following one-liner:

```bash
yolo export model=yolov10n.pt format=coreml
```

This will create a `yolov10n.mlpackage` file. For more details, please refer to the latest documentation.

**Pull request merged**
