### PR TITLE
Improve TFLite INT8 detection accuracy

### PR DESCRIPTION
**Pull request by adamp87**
This PR addresses issue #7371. It fixes a bug of the TFLite INT8 model accuracy degradation, due to numerical instability. Furthermore, it improves the accuracy compared to previously claimed results.

The improvements done by #1695 could not be reproduced. Normalization have been reordered to have better numerical stability. After changing the code, higher detection accuracy can be achieved compared to claimed results.

I have read the CLA Document and I sign the CLA
I have read the CLA Document and I hereby sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved bounding box normalization during model export for TFLite and Edge TPU compatibility.

### 📊 Key Changes
- Changed normalization of bounding box coordinates when exporting models to TFLite or Edge TPU format.
- Moved from dividing by image size to using a precomputed normalization factor.

### 🎯 Purpose & Impact
- 📈 Increases numerical stability during the prediction phase, reducing errors especially when quantizing models.
- 🔍 Ensures better accuracy for integer-based quantization on lightweight platforms like TFLite and Edge TPUs, making AI more accessible on mobile and edge devices.

### CODE REVIEW

**Comment by adamp87** [comment]
recheck

**Comment by adamp87** [comment]
recheck

**Comment by adamp87** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@adamp87 thanks for the PR! Yes this makes sense.

**Comment by adamp87** [comment]
@glenn-jocher yes, I have documented it in issue #7371

I could not reproduce the before validation results, so I had to rely on the reported values in #1695. Please see issue #7371 for mode detail, but in short here are the results, running yolo8n with image size 640 on the COCO validation dataset:

| Model | mAP50 | mAP50-95 | Note |
| ------------- | ------------- | ------------- | ------------- |
| After |  48.4 | 32.7  |  |
| Before |  46.4  |  28.7  | https://github.com/ultralytics/ultralytics/pull/1695#issuecomment-1518653422 |

**Comment by glenn-jocher** [comment]
@adamp87 oh wow, that's a huge improvement. I haven't looked at this in detail yet but I see it's adding a DFL op while note removing any similar op, so will this result in extra compute in the head for all models? Or is it only applied to exported INT8 models?

I'll try to get some baseline results later today if I have time.

**Comment by adamp87** [comment]
@glenn-jocher actually while exporting, the dbox at line  https://github.com/adamp87/ultralytics/blob/11cfee83764496794483169f424ee0d43cded825/ultralytics/nn/modules/head.py#L73 overwrites dbox at line https://github.com/adamp87/ultralytics/blob/11cfee83764496794483169f424ee0d43cded825/ultralytics/nn/modules/head.py#L61, therefore it should not add any extra operation. I thought the code will look cleaner, but you are right, it would be easier to read if line 61 would be in an 'else' branch of the "if export".

I made a screenshot of the before and after model using netron.app, after the changes the model has one less Mul, one less Cat, and an extra Reshape. Screenshots are also in issue #7371 

Regarding the baseline, I opened a brand new Colab and executed:
```
!pip install ultralytics
!yolo export model=yolov8n.pt data=coco128.yaml format=tflite int8
!yolo val model=yolov8n_saved_model/yolov8n_full_integer_quant.tflite data=coco128.yaml
```
And could not reproduce the results for the subset COCO128 mentioned in #1695

**Comment by glenn-jocher** [comment]
@adamp87 Thanks for the clarification and for providing the additional details. It's good to hear that the changes are specific to the export process and won't affect the compute during training or inference for non-exported models. The netron.app visualizations and your methodical approach to reproducing the baseline are much appreciated. We'll review the changes and the impact on the model's architecture as per your PR and issue documentation. Keep up the great work! 🚀

**Comment by glenn-jocher** [comment]
@adamp87 I've run a few benchmarks here with full COCO:

- yolov8n.pt default: 37.4 mAP (reproduced README result)
- yolov8n_float16.tflite: 37.3 mAP
- yolov8n_int8.tflite: 35.9 mAP
- yolov8n_integer_quant.tflite: 0.081 mAP
- yolov8n_full_integer_quant.tflite: 0.081 mAP

Commands for the int8 models are i.e.:
```bash
yolo val task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant.tflite imgsz=640 data=coco.yaml int8
```

Can you provide the same values on your branch?

**Comment by adamp87** [comment]
@glenn-jocher yes, I ran it overnight on Colab, inferencing on CPU. Here are the results:

yolov8n.pt default: 0.374
yolov8n_float16.tflite: 0.373
yolov8n_int8.tflite: 0.359
yolov8n_integer_quant.tflite: 0.328
yolov8n_full_integer_quant.tflite: 0.329

For completeness, here is the full notebook with all the outputs: 
[validation.zip](https://github.com/ultralytics/ultralytics/files/13857744/validation.zip)

I also saved the run folder if needed, let me know.

**Comment by glenn-jocher** [comment]
@adamp87 Excellent, those results look promising, especially for the INT8 models. Thanks for running those benchmarks and for sharing the notebook. We'll take a look at the details and get back to you. Great job on this! 👍

**Comment by Skillnoob** [comment]
fyi there is #4495 which has a similar goal of improving tflite int8 accuracy

**Comment by glenn-jocher** [comment]
@Skillnoob yes I've seen that one, how do you think this PR compares to that one? 

This is a simpler solution and the results seem outstanding.

**Comment by Skillnoob** [comment]
After looking at the changes I agree this is much simpler than the approach I mentioned

**Comment by adamp87** [comment]
To my understanding it is a different solution in the sense of it splits the head into two parts. It applies the convolution cv2 and cv3 in the quantized model, but the rest (DFL, sigmoid on scores) will be done outside the quantized model. It does achieve a higher accuracy around (+1.9%), I do mention it in my issue #7371, but I agree with Glenn that it is a much more complicated code.

I would suggest if one would like to go that way, simply detach the head, export the model and apply the head afterwards. This can be done with yolov7 when exporting without the "--grid" param.

Please note that the #4495 might have also other improvements that I missed.

**Comment by glenn-jocher** [comment]
@adamp87 ok, let's try this! Merged into 238 branch for release with `ultralytics 8.0.238` later tonight.

**Comment by glenn-jocher** [comment]
@adamp87 ok deployed in 8.0.238. I tested and am getting much improved results, but a little lower than yours:

`ultralytics 8.0.238` results:

yolov8n.pt default: 0.374
yolov8n_float16.tflite: 0.373
yolov8n_int8.tflite: 0.359
yolov8n_integer_quant.tflite: 0.300
yolov8n_full_integer_quant.tflite: 0.297

I used i.e. `yolo val task=detect model=yolov8n_saved_model/yolov8n_full_integer_quant.tflite imgsz=640 data=coco.yaml int8`

**Comment by adamp87** [comment]
@glenn-jocher might be maybe the conversion is done without the calibration data? I do the export as:

`yolo export model=yolov8n.pt data=coco128.yaml format=tflite int8 imgsz=640`

Adding "data=coco128.yaml" improves mAP also

**Comment by glenn-jocher** [comment]
@adamp87 That's a good point. Including the calibration data during the export process can indeed lead to better quantization and thus improved mAP. Thanks for highlighting this! 👍

**Comment by adamp87** [comment]
@glenn-jocher sounds good, happy to hear! Thanks for the merging! 👍

One more comment on the solution proposed by #4495. It validates a retrained model which uses ReLU6 activation function. Metric mAP 34.7 was mentioned here https://github.com/ultralytics/ultralytics/pull/1695#issuecomment-1652904495. Theoretically ReLU6 loses less accuracy during quantization. In my opinion a fair comparison between the metrics provided in this pull request and #4495 is not possible. For a fair evaluation the same model should be quantized in both ways and compared.

**Comment by glenn-jocher** [comment]
@adamp87 You're welcome, and thank you for your contribution!

Regarding the comparison with #4495, you make a valid point. A direct comparison would indeed require quantizing the same model with both methods to ensure a fair evaluation. The use of ReLU6 in #4495 could affect quantization differently, so we'll consider this when reviewing the results. Appreciate your insights! 👍

**Comment by adamp87** [comment]
Hi @glenn-jocher,

im so sorry to disturb you here with this, but with the commit "783033f" my private email went into the co-author list. I modified in the settings now to hide it, but could you please help me out with modifying it in the commit to this 7806910+adamp87@users.noreply.github.com

I will delete this message from here later then.

Thank you so much for it!

**Comment by glenn-jocher** [comment]
Hi @adamp87,

No worries at all! I'll take care of updating the commit author information to maintain your privacy. Once it's done, feel free to delete your message as needed.

**Comment by adamp87** [comment]
Hi @glenn-jocher,
please dont forget to edit my email to 7806910+adamp87@users.noreply.github.com int commit 783033f

Thank you so much

**Comment by glenn-jocher** [comment]
Hi @adamp87,

I'll make sure to address this promptly. Thank you for the reminder.

**Comment by adamp87** [comment]
Hi @glenn-jocher ,

for reference I did train a model with ReLU6 and tested different options together with OpenVINO, which are documented here: https://github.com/ultralytics/ultralytics/pull/7516#issuecomment-1913636777

The main point is that an unquantized head (`decode_bbox`, scores) do achieve higher accuracy, in my case ~2.4%, compared to a quantized head with normalized pixels. In my opinion the best solution would be to exclude the head from quantization in the converted TFLite model. Not sure if that is possible with the current version of onnx2tf, but this way no code modification would be necessary in the ultralytics repo. I have made an issue at the onnx2tf repo, lets see if it is possible: https://github.com/PINTO0309/onnx2tf/issues/578

Note that if the head is not quantized, pixel coordinate normalization would not be necessary.

**Comment by glenn-jocher** [comment]
Hi @adamp87,

Thanks for sharing your findings and for the initiative on exploring the quantization effects with OpenVINO. Excluding the head from quantization is indeed an interesting approach to potentially retain higher accuracy. We'll keep an eye on the issue you've opened with onnx2tf and see if this can be integrated in the future. Your contributions are greatly appreciated! 🌟

**Pull request merged**
