### PR TITLE
Add Signature ✍️ dataset in docs

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Ultralytics introduces a Signature Detection Dataset to enhance document verification and fraud detection capabilities.

### 📊 Key Changes
- **Added Signature Dataset:** A new dataset focused on detecting signatures within documents is introduced, aimed at supporting document verification and fraud detection research.
- **Updated Dataset Descriptions:** Improved and concise descriptions for existing datasets to better reflect their contents and purposes.
- **Datasets List Expansion:** The overall list of supported datasets has been expanded, including the newly added Signature dataset.

### 🎯 Purpose & Impact
- **Enhanced Model Training:** The Signature Detection Dataset provides valuable data for training computer vision models to identify signatures in various documents, which is crucial for automating document verification processes and enhancing fraud detection systems.
- **Broader Research Applications:** By incorporating a diverse range of datasets, Ultralytics facilitates a wider spectrum of computer vision research and real-world applications, from autonomous vehicles and retail environment understanding to disease diagnosis and wildlife research.
- **Improved User Experience:** By updating dataset descriptions and expanding the list of supported datasets, Ultralytics aims to offer a more user-friendly experience, helping researchers and developers find the most suitable datasets for their projects more efficiently.

🔍 **Impact to Users:** Users and researchers now have access to a richer repository of datasets for a variety of applications. The addition of the Signature Detection Dataset specifically enhances capabilities in legal and financial document processing, potentially reducing fraud and improving the accuracy of automated systems.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar thanks for the PR! 

I just noticed that the datasets/index.md and datasets/detect/index.md page are out of sync. They both have a list of the detect datasets that both need updating when a new dataset is created.

**Comment by glenn-jocher** [comment]
@RizwanMunawar I've updated both docs now. Please make sure you update both for new datasets, thanks!

**Comment by RizwanMunawar** [comment]
@glenn-jocher got it, good catch :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar PR merged!! Nice work here :)

**Pull request merged**
