### PR TITLE
Add CI for monitoring `ultralytics solutions` status

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher Let's keep this PR open, i am working on this :)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR modifies various documentation and code components to change the data structure for class names from dictionaries to lists, and introduces new tests for the Ultralytics YOLO solutions.

### 📊 Key Changes
- Updated documentation to reflect changing `classes_names` from `dict` to `list`.
- Modified several solution modules (`object_counter.py`, `queue_management.py`, `speed_estimation.py`) to accommodate this change.
- Added new test cases in `test_solutions.py` to ensure new features and updates work correctly.

### 🎯 Purpose & Impact
- **Consistency & Simplicity**: Changing to lists simplifies the data structure, making it more consistent and easier to handle across different parts of the code.
- **Improved Documentation**: The updated docs make it easier for users to understand how to use the framework.
- **Enhanced Testing**: The addition of new test cases improves overall reliability and ensures new changes do not introduce bugs.

Overall, these updates streamline the framework, enhance user comprehension, and ensure robustness via thorough testing. 📈🔧

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar best way to do this is to add a `test_solutions.py` file to the tests and place everything you need there. Then these will automatically be run by the existing CI:
https://github.com/ultralytics/ultralytics/tree/main/tests

**Comment by RizwanMunawar** [comment]
Ah got it @glenn-jocher, let me update than :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar it's working! Good to merge?

**Comment by RizwanMunawar** [comment]
@glenn-jocher not yet. I am working on this, hopefully by end of this week it will be good to go :)

**Comment by RizwanMunawar** [comment]
@glenn-jocher closing this PR opened new PR with additional changes!!!

**Pull request closed without merging**
