### PR TITLE
`ultralytics 8.3.53` New Export argument validation

### LINKED ISSUE #16732: export YOLO11 onnx with NMS
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I used the following code to export my model with ONNX and enabled  NMS:

`path = model.export(format="onnx", nms=True)`

However, the exported ONNX model doesn't seem to include NMS. Could you please let me know how to properly add NMS to the exported ONNX model? Additionally, what are the confidence threshold and IoU threshold values used for NMS in the official reported mAP?

### Additional

_No response_

### LINKED ISSUE #17454: Exporting model as half precision torchscript doesn't reduce the model size by half
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

image
The models exported as full precision torchscript and half precision torchscripts respectively have almost the same model size.
However, when I export the model i written in pytorch into half precision torchscript format model, the model size was reduced by half compared with the model exported as full precision torchscript.
Is there any other way to reduce the yolo model size exported as torchscipt?

### Additional

_No response_

### LINKED ISSUE #18109: The inference time of the int8 exported ONNX model is abnormal.
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use model.export() to convert yolov11n.pt to ONNX, I found that the inference time of the model with int8 precision is not significantly different from the model without int8 precision (based on the average inference time of n runs in the same environment).

Average inference time   (Inference count of 100)
yolov11n.onnx with int8 true: 32.57 ms
yolov11n.onnx with int8 False: 22.34 ms

Average inference time   (Inference count of 1000)
yolov11n.onnx with int8 true: 22.38 ms
yolov11n.onnx with int8 False: 22.34 ms

Is this phenomenon normal? If not, could you provide some troubleshooting ideas?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Y-T-G**
Right now, we don't check if the passed argument is valid for the format, which leads to confusion when the export goes through, but the behavior remains unaltered.

**W/O PR**
```python
In [7]: model.export(format="onnx", int8=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)

ONNX: starting export with onnx 1.15.0 opset 19...
ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 1.4s, saved as 'yolo11n.onnx' (10.2 MB)

Export complete (1.7s)
Results saved to /ultralytics
Predict:         yolo predict task=detect model=yolo11n.onnx imgsz=640 int8 
Validate:        yolo val task=detect model=yolo11n.onnx imgsz=640 data=/usr/src/ultralytics/ultralytics/cfg/datasets/coco.yaml int8 
Visualize:       https://netron.app
Out[7]: 'yolo11n.onnx'
```
```python
In [8]: model.export(format="onnx", nms=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)

ONNX: starting export with onnx 1.15.0 opset 19...
ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 1.0s, saved as 'yolo11n.onnx' (10.2 MB)

Export complete (1.3s)
Results saved to /ultralytics
Predict:         yolo predict task=detect model=yolo11n.onnx imgsz=640  
Validate:        yolo val task=detect model=yolo11n.onnx imgsz=640 data=/usr/src/ultralytics/ultralytics/cfg/datasets/coco.yaml  
Visualize:       https://netron.app
Out[8]: 'yolo11n.onnx'
```

**W/ PR**
```python
In [10]: model.export(format="onnx", nms=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 model.export(format="onnx", nms=True)

File /ultralytics/ultralytics/engine/model.py:738, in Model.export(self, **kwargs)
    730 custom = {
    731     "imgsz": self.model.args["imgsz"],
    732     "batch": 1,
   (...)
    735     "verbose": False,
    736 }  # method defaults
    737 args = {**self.overrides, **custom, **kwargs, "mode": "export"}  # highest priority args on the right
--> 738 return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)

File /ultralytics/ultralytics/engine/exporter.py:267, in Exporter.__call__(self, model)
    264 self.device = select_device("cpu" if self.args.device is None else self.args.device)
    266 # Argument compatibility checks
--> 267 validate_args(fmt, self.args)
    268 if imx and not self.args.int8:
    269     LOGGER.warning("WARNING ⚠️ IMX only supports int8 export, setting int8=True.")

File /ultralytics/ultralytics/engine/exporter.py:159, in validate_args(format, passed_args)
    157 not_default = getattr(passed_args, arg, None) != getattr(DEFAULT_CFG, arg, None)
    158 if not_default:
--> 159     assert arg in valid_args, f"ERROR ❌️ argument '{arg}' is not supported for format='{format}'"

AssertionError: ERROR ❌️ argument 'nms' is not supported for format='onnx'
```
```python
In [5]: model.export(format="onnx", int8=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 model.export(format="onnx", int8=True)

File /ultralytics/ultralytics/engine/model.py:738, in Model.export(self, **kwargs)
    730 custom = {
    731     "imgsz": self.model.args["imgsz"],
    732     "batch": 1,
   (...)
    735     "verbose": False,
    736 }  # method defaults
    737 args = {**self.overrides, **custom, **kwargs, "mode": "export"}  # highest priority args on the right
--> 738 return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)

File /ultralytics/ultralytics/engine/exporter.py:267, in Exporter.__call__(self, model)
    264 self.device = select_device("cpu" if self.args.device is None else self.args.device)
    266 # Argument compatibility checks
--> 267 validate_args(fmt, self.args)
    268 if imx and not self.args.int8:
    269     LOGGER.warning("WARNING ⚠️ IMX only supports int8 export, setting int8=True.")

File /ultralytics/ultralytics/engine/exporter.py:159, in validate_args(format, passed_args)
    157 not_default = getattr(passed_args, arg, None) != getattr(DEFAULT_CFG, arg, None)
    158 if not_default:
--> 159     assert arg in valid_args, f"ERROR ❌️ argument '{arg}' is not supported for format='{format}'"

AssertionError: ERROR ❌️ argument 'int8' is not supported for format='onnx'
```

Closes https://github.com/ultralytics/ultralytics/issues/18109
Closes https://github.com/ultralytics/ultralytics/issues/16732
Closes https://github.com/ultralytics/ultralytics/issues/17454

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced export functionality in Ultralytics YOLO 🚀 with improved argument validation and updated format configurations for better user experience.

### 📊 Key Changes
- Added a new `validate_args` function to validate export arguments against supported formats.
- Updated the export format configurations to include specific supported arguments (e.g., `half`, `int8`, `batch`).
- Modified the logic in export and benchmarking flows to utilize improved argument validation.
- Bumped version from `8.3.52` to `8.3.53`.

### 🎯 Purpose & Impact
- **Stronger Validation 🔒**: Reduces errors by ensuring users provide only supported arguments for each export format, leading to more robust and predictable exports.
- **Enhanced Compatibility ⚙️**: Updated export format configurations make it easier to understand and utilize format-specific features like dynamic batching, half-precision, and more.
- **Improved Usability 🛠️**: Clearer error messages and validations improve user experience and help developers debug faster.
- **Future-Proofing 🚀**: Laying the groundwork for scalable and extensible exporting capabilities in diverse machine learning pipelines.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless review process and optimal integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the rationale behind your changes in the PR description. Linking to any [relevant issues](https://github.com/ultralytics/ultralytics/issues) you've addressed (as you've done—great job!) is highly appreciated. Ensure commit messages are clear and follow the project's guidelines.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the latest `main` branch of `ultralytics/ultralytics`. If your branch is outdated, please click 'Update branch' or run `git pull` and `git merge main` locally to fix potential merge conflicts.
- ✅ **Ensure CI Checks Pass**: Verify that all required [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If you encounter failures, look into resolving the issues to maintain the project's code quality.
- ✅ **Update Documentation**: Update any relevant sections in the [documentation](https://docs.ultralytics.com) to reflect the changes you're introducing, particularly details about argument compatibility for export formats.
- ✅ **Add Tests**: Ensure you've created or modified tests to validate your changes, as applicable, and confirm that all tests succeed. Robust test coverage helps maintain the integrity of the codebase.
- ✅ **Sign the CLA**: If this is your first PR to the Ultralytics repository, ensure you’ve signed our [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA."
- ✅ **Minimize Changes**: Aim for the smallest set of effective changes required to implement your fix or feature. Conciseness is essential for easier review and debugging.

We’d also encourage you to elaborate on any updates to error messages and their anticipated impact on user workflows. This PR appears to enhance argument validation during export, providing users with clearer feedback on incorrect configurations. 🎉 Great work!

For additional details, reference the [Contributing Guide](https://docs.ultralytics.com/help/contributing) to ensure alignment with our contribution standards. If you have any questions or need further guidance, feel free to leave a comment below. An Ultralytics engineer will assist you soon. 💪✨

Thank you for helping improve Ultralytics' tools! 🚀

**Comment by glenn-jocher** [comment]
@Y-T-G good idea! Would it make sense to incorporate these into the existing export_formats dict here instead of creating a second dict?

https://github.com/ultralytics/ultralytics/blob/7f37790134527e328c475ac292efdc39b1cd7b5e/ultralytics/engine/exporter.py#L103-L119

**Comment by Y-T-G** [comment]
@glenn-jocher I guess we can. Seems more organized that way.

**Comment by Y-T-G** [comment]
@glenn-jocher @ambitious-octopus The workflow keeps performing a merge, even after I revert it.

**Comment by Y-T-G** [comment]
@glenn-jocher Moved the args to `export_formats`

**Comment by glenn-jocher** [comment]
@Y-T-G thanks for the changes! Looks like we have some CI errors now though:

```
FAILED tests/test_engine.py::test_export - AssertionError: ERROR ❌️ argument 'batch' is not supported for format='torchscript'
FAILED tests/test_exports.py::test_export_onnx - AssertionError: ERROR ❌️ argument 'dynamic' is not supported for format='onnx'
FAILED tests/test_exports.py::test_export_coreml - AssertionError: ERROR ❌️ argument 'nms' is not supported for format='coreml'
```

**Comment by UltralyticsAssistant** [comment]
🎉 PR Merged! A huge thank you to @Y-T-G and @glenn-jocher for your incredible contributions to enhancing Ultralytics YOLO 🚀! Your work on refining export functionality and argument validation not only makes the library more robust but also paves the way for a smoother, better user experience. 🌟 

As Aristotle once said, *"Excellence is never an accident. It is the result of high intention, sincere effort, and intelligent execution."* Your dedication embodies this excellence, and your efforts are shaping tools that will empower users and developers around the world.

Keep inspiring and innovating — together, we move AI forward! 🚀❤️

**Pull request merged**
