### PR TITLE
Fix tflite int8 scaling

### PR DESCRIPTION
**Pull request by democat3457**
Part of #1695, with calibration section removed until further testing can be made.

This PR merges the changes manually into main, accounting for the file structure changes.

### Summary
🛠️🚀🌐

This pull request enhances the TFLite and EdgeTPU compatibility of the model by normalizing and unnormalizing the `xywh` coordinates of bounding boxes and default boxes. This reduces the quantization error and improves the accuracy of integer models.

> _Sing, O Muse, of the skillful coder who refined the model_
> _Of bounding boxes, that swift and accurate detector_
> _Of objects in the images, and made it more compatible_
> _With TFLite and EdgeTPU, those tiny and wise predictors._

### Walkthrough
*  Mitigate quantization error of integer models for TFLite and EdgeTPU by normalizing xywh coordinates of bounding boxes and default boxes with input image size when exporting the model ([link](https://github.com/ultralytics/ultralytics/pull/3837/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9R418-R425), [link](https://github.com/ultralytics/ultralytics/pull/3837/files?diff=unified&w=0#diff-06038a7c9e9c565760881118b974c2f2fe7aee7c78bb6c142d1498d0d9614639R61-R70))
* Simplify code logic by removing redundant normalization of xywh coordinates to pixels when not exporting the model in `autobackend.py` ([link](https://github.com/ultralytics/ultralytics/pull/3837/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L425))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved model accuracy for non-classification tasks in TFLite/EdgeTPU.

### 📊 Key Changes
- 🧮 Added post-processing to re-scale bounding box coordinates with image size in TFLite/EdgeTPU models.
- ✂️ Removed redundant scaling code that normalized bounding boxes to pixel values.
- 🔄 Added normalization of bounding box coordinates during export to TFLite/EdgeTPU format to mitigate quantization error.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: To improve the accuracy of bounding box predictions for object detection tasks by compensating for quantization errors during model export.
- 💡 **Impact**: Users can expect more accurate object localization from models deployed on TFLite/EdgeTPU platforms, particularly for tasks other than classification. This change could be crucial for applications requiring precise object detection, like automated driving or surveillance.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@democat3457 thanks for the PR! Does this resolve some/most of the TFLite INT8 quantization accuracy loss?

Also can the autobackend.py part be done like this in a single line?
```python
x[:, :4] *= [w, h, w, h] 
```

**Comment by democat3457** [comment]
> @democat3457 thanks for the PR! Does this resolve some/most of the TFLite INT8 quantization accuracy loss?

Well, now we can get actual outputs now, since the input/output coordinates are no longer squished to 0 through quantization, as mentioned in the original PR. There's still some slight accuracy loss due to the calibration issue mentioned, but that's enough changes for a second PR.

> Also can the autobackend.py part be done like this in a single line?
> 
> ```python
> x[:, :4] *= [w, h, w, h] 
> ```

done!

**Comment by democat3457** [comment]
It would seem that according to the CI, that I can't actually do that in a single line 😆

**Comment by democat3457** [comment]
Alright I got the CI to work, and in almost a single line too!

**Comment by glenn-jocher** [comment]
@democat3457 thanks for the updates! I think the original is probably clearer to understand so I left it in place. 

Please submit a separate PR for int8 calibration using an example dataset when that is ready.

**Pull request merged**
