### PR TITLE
Fix `np.empty_like` and `torch.empty_like` input type

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
A new utility function `empty_like` was added to improve tensor and array handling, simplifying code and enhancing maintainability.  

### 📊 Key Changes  
- Added a new utility function `empty_like` to `ultralytics.utils.ops`, which generates an empty tensor or array with the same shape and dtype (float32) as the input.
- Updated multiple functions (`xyxy2xywh`, `xywh2xyxy`, `xywhn2xyxy`, `xyxy2xywhn`) to use the new `empty_like` function instead of inline implementations involving `torch.empty_like` and `np.empty_like`.
- Documentation updates to reflect the new `empty_like` function.

### 🎯 Purpose & Impact  
- 🔧 **Code Simplification**: Centralizing logic with `empty_like` reduces code duplication and makes future maintenance easier.  
- 🚀 **Performance Assurance**: The functionality remains fast and reliable for operations on bounding box transformations, maintaining existing performance.  
- 📚 **Improved Clarity**: Users benefit from cleaner, well-structured code with clear, reusable utilities.  

This change enhances the usability of the library while preserving its high performance for bounding box operations. 🎉

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Laughing-q, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

Your PR looks great, and the addition of explicit data types for bounding box conversion enhances precision and reliability. 🎯💪 To help speed up the review process:

- If possible, provide relevant test results or examples demonstrating the benefit of the proposed changes.
- If these changes address a specific issue, make sure to link to it in your PR description.

For additional insights on best practices, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t worry about the automated nature of this response 🤖—an Ultralytics engineer will review and provide additional feedback soon.

Thank you for contributing to Ultralytics! 🚀

**Comment by Laughing-q** [comment]
@glenn-jocher @RizwanMunawar A extension of this [PR](https://github.com/ultralytics/ultralytics/pull/18049). :) To fix the issue when the final outputs of these functions are less than 1 and with integer type, the values become 0 directly.

**Comment by glenn-jocher** [comment]
@Laughing-q good idea! Can you investigate whether we should use `float` or `np.float32` for numpy float 32 type? 

Also can you refactor this into a function, i.e.

```python
def empty_like(x):
   """Creates empty torch.Tensor or np.ndarray with same shape as input and float32 dtype."""
   return torch.empty_like(x, dtype=torch.float32) if isinstance(x, torch.Tensor) else np.empty_like(x, dtype=np.float32)
```

**Comment by Laughing-q** [comment]
@glenn-jocher Yes make sense! I'll take a look at the float deprecation(what's the numpy version you were using? I don't remember seeing any deprecation in my test though). BTW the reason why I used `np.float32` is because by default `float` referring to float64.

**Comment by glenn-jocher** [comment]
@Laughing-q ah yes that's right np likes float64 defaults. Ok let's update https://github.com/ultralytics/ultralytics/pull/18049 then to fix this implementation to also use `np.float32`.

If you don't see any warnings then I think this should be correct.

**Comment by Laughing-q** [comment]
@glenn-jocher ok I've put `empty_like` as a independent function. And yes I don't see any deprecation though even I upgraded my numpy version to `2.1.3`.
tested with main branch:
pic-241206-1916-06

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@Laughing-q great work, PR merged!

**Pull request merged**
