### PR TITLE
Update train.md

### PR DESCRIPTION
**Pull request by arkylin**
Adding single quotes is necessary for proper execution. Without adding single quotes, the program will report an error.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced clarity in training device specification for YOLOv8n documentation.

### 📊 Key Changes
- Clarified the default device setting in the training documentation by adding quotation marks to `'cpu'` in the specification.

### 🎯 Purpose & Impact
- **Enhances clarity:** Makes it clearer for developers and users how the default device is identified in the code, reducing potential confusion.
- **Improves consistency:** Using quotation marks around `cpu` aligns with standard coding practices, ensuring consistency in how strings are represented in documentation.
- **Potential impact:** Helps users correctly understand the behavior of the software when no device argument is passed, ensuring a smoother experience for those training YOLOv8n models, especially for newcomers.

### CODE REVIEW

**Comment by arkylin** [comment]
recheck

**Comment by glenn-jocher** [comment]
@arkylin absolutely, let's recheck that for you! If there's anything specific you'd like me to look into or any error messages you're encountering, please let me know. It could help in pinpointing the issue quicker. 😊

**Comment by arkylin** [comment]
@glenn-jocher 
```
Traceback (most recent call last):
  File "a.py", line 16, in <module>
    results = model(source=image_path,save=True,classes=[2],show_boxes=False,conf=0.6,device=cpu)
NameError: name 'cpu' is not defined
```
You must add single quotes around the cpu statement to make it a string in order for the program to run correctly, thank you.

**Comment by glenn-jocher** [comment]
Hey there! 😊 You're absolutely right, the `device` argument should indeed be a string. So your line should be updated to use `'cpu'` like so:

```python
results = model(source=image_path, save=True, classes=[2], show_boxes=False, conf=0.6, device='cpu')
```

Thanks for catching that! If there's anything else you need help with, feel free to shout. Happy coding! 🚀

**Comment by glenn-jocher** [comment]
@arkylin PR merged, thank you for your contributions!

**Pull request merged**
