### PR TITLE
Fix queue `counts`

### LINKED ISSUE #15970: Improvement regarding queue_management.py
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

For Queue Management solution I need the queue counts outside the program and populate it in another visualization. Already there is a method called 'counts' you created but it returns '0' every time. Since I checked queue_management.py while displaying queue counts you refreshing it to 0 for some idle reason. So, by keeping your code as it is, I added some changes by creating a function to get queue counts outside to print in local system code. It is hard to add change in local system every time I install ultralytics library. Can I contribute it? Will you add as a contribution for me?

### Additional
I created a pull request by add changes
url : https://github.com/ultralytics/ultralytics/pull/15971

_No response_

### PR DESCRIPTION
**Pull request by CharanPrasadK**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved queue management algorithm by adjusting the count reset behavior.

### 📊 Key Changes
- Modified the `extract_and_process_tracks` method to reset counts at the start of each frame instead of after displaying frames.

### 🎯 Purpose & Impact
- **Enhanced Accuracy**: Ensures counts are more accurate by resetting counts at the beginning of each frame processing. 📈
- **Performance Consistency**: Provides a reliable and consistent performance for queue management solutions in video streams. 🎥

### CODE REVIEW

**Comment by TechWolf21** [comment]
I have read the CLA Document and I sign the CLA

**Comment by TechWolf21** [comment]
I raised an issue regarding this,
url : https://github.com/ultralytics/ultralytics/issues/15970

**Comment by glenn-jocher** [comment]
@RizwanMunawar can you review please?

@TechWolf21 not sure I understand, this code seems to be defining the queue counts directly from `self.counts`, so why not just use `self.counts` directly?

**Comment by RizwanMunawar** [comment]
@TechWolf21 Hi, thanks for raising the issue and submitting the PR. I've tested the queue management, and the queue `counts` are functioning as expected. But yes you can not access the count, outside the function. It will be always zero, Only change we need to reset the count at the start of the function and that's all, we don't need to define any additional code.

**Note:** The queue counts update with every frame, resetting the counter to zero each time. This approach provides real-time queue counts, unlike general object counting, where all objects are counted collectively.

**Comment by RizwanMunawar** [comment]
@TechWolf21 Ok I have updated things and you will be able to access the queue management using the mentioned code below.

```python
import cv2

from ultralytics import YOLO, solutions

model = YOLO("yolov8n.pt")
cap = cv2.VideoCapture("Path/to/video/file.mp4")

assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

video_writer = cv2.VideoWriter("queue_management.avi", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

queue_region = [(20, 400), (1080, 404), (1080, 360), (20, 360)]

queue = solutions.QueueManager(
    names=model.names,
    reg_pts=queue_region,
    line_thickness=3,
    fontsize=1.0,
    region_color=(255, 144, 31),
    view_img=True
)

while cap.isOpened():
    success, im0 = cap.read()

    if success:
        tracks = model.track(im0, show=False, persist=True, verbose=False)
        out = queue.process_queue(im0, tracks)
        print(f"Queue Counts {queue.counts}")
        video_writer.write(im0)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
        continue

    print("Video frame is empty or video processing has been successfully completed.")
    break

cap.release()
cv2.destroyAllWindows()
```

@glenn-jocher I think the PR is good to go 👍🏻 

Thanks,
Ultralytics Team!

**Comment by TechWolf21** [comment]
@glenn-jocher 
@RizwanMunawar  I saw the change in queue_management.py, You removed self.counts=0 , So, for this action in real-time, instead of updating queue.counts  frame by frame the counts will get added to existing count.
For Example,
For a 1 min video clip assume there are 5people and 4people and 3 people at bill counter as the video goes on, Its detects and give queue counts but while printing that queue.count it will not get updated in real-time by giving 5,4,3  as outputs. Instead the counts are getting added in real-time to give 5,9,12 as output . So, that's the reason I added additional code to access queue.counts.

**Comment by glenn-jocher** [comment]
@RizwanMunawar @TechWolf21 PR merged! Please let us know if this solves your issue and let us know if there are any other areas we can improve :)

**Comment by TechWolf21** [comment]
@glenn-jocher  and @RizwanMunawar this doesn't solve my issue, Please review my above comment  which you can understand issue. I am also giving the same comment here. 
" I saw the change in queue_management.py that @RizwanMunawar removed self.counts=0 , So, for this action in real-time, instead of updating queue.counts frame by frame the counts will get added to existing count.
this, self.counts=0 is needed to refresh every frame and for additional to that I added and used queue_count to access self.counts in real-time before refreshing it to '0'.
For Example,
For a 1 min video clip assume there are 5people and 4people and 3 people at bill counter as the video goes on, Its detects and give queue counts but while printing that queue.count it will not get updated in real-time by giving 5,4,3 as outputs. Instead the counts are getting added in real-time to give 5,9,12 as output . So, that's the reason I added additional code to access queue.counts."

**Comment by glenn-jocher** [comment]
@TechWolf21 got it. Is there really no way to access the counts property directly?

@RizwanMunawar can you take another look here to see if we are addressing @TechWolf21's requirements?

**Comment by TechWolf21** [comment]
@glenn-jocher There is way we to  access counts property but the output not accurate it returns either 0 or incrementing value frame by frame but not the accurate updated counts value. So, I added additional code.
Here, counts property is accessible but there is no use the value is incorrect. But, It is needed to refreshed to 0 for updating it in real time.

**Comment by TechWolf21** [comment]
> @glenn-jocher There is way we to access counts property but the output not accurate it returns either 0 or incrementing value frame by frame but not the accurate updated counts value. So, I added additional code. Here, counts property is accessible but there is no use the value is incorrect. But, It is needed to refreshed to 0 for updating it in real time.

**Comment by TechWolf21** [comment]
Oh! nice I see @glenn-jocher and @RizwanMunawar  made changes 2hrs ago.
url: https://github.com/ultralytics/ultralytics/compare/3158f6c29bc2f72f1ac4010fc4768283e804d3c6...8066bb976c993b2fcce6660381d68d47ff5f8bf5
replaced line 92 and 135 in queue_management.py.
Now the issue is resolved.
That's a nice idea to reset count in extract_and_process_frames method. 
Thank you for your quick responses and fixing the issue.
Thank you,
@glenn-jocher 
@RizwanMunawar

**Comment by glenn-jocher** [comment]
You're welcome! We're glad to hear the issue is resolved. If you have any more questions or need further assistance, feel free to reach out.

**Pull request merged**
