### PR TITLE
Create yolov9.yaml

### PR DESCRIPTION
**Pull request by Supernova1744**
Add YOLOv9 Scales

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing the next-gen YOLOv9 model configuration for enhanced object detection. 🚀

### 📊 Key Changes
- Introduced a new YOLO version, **YOLOv9**, with a focus on improved accuracy and efficiency. 
- New configuration file `yolov9.yaml` added, featuring **618 layers**, **25,590,912 parameters**, and **104.0 GFLOPs**.
- The model supports **80 classes** with scalable architecture options (n, s, m, l, x) for varying depth, width, and max_channels, accommodating different computational power needs.
- Incorporates a **GELAN backbone** and **SPPELAN** head for backbone and detection layers, respectively, introducing advanced layers like `RepNCSPELAN4` and `ADown` for optimal performance.
- Provides compound scaling constants for tailored model scaling, ensuring flexibility across different application requirements and hardware capabilities.

### 🎯 Purpose & Impact
- **Purpose**: To push the boundaries of object detection models with YOLOv9, offering higher precision, scalability, and efficiency for real-world applications.
- **Impact**: Users and developers can expect more accurate object detection results across a wide range of conditions with enhanced processing speed, thanks to the optimized model structure. The flexibility in scaling allows for better performance adjustments based on hardware constraints, making YOLOv9 versatile for both high-end systems and devices with limited computational resources.

With these advancements, YOLOv9 stands to revolutionize object detection tasks, broadening the horizon for innovations in various fields such as autonomous driving, surveillance, and augmented reality. 🛠️💡

### CODE REVIEW

**Comment by Supernova1744** [comment]
I have read the CLA Document and I sign the CLA

**Comment by faridamousa** [comment]
where can i find yolov9.yaml?

**Comment by glenn-jocher** [comment]
Hello! YOLOv9, including the `yolov9.yaml` file, is currently experimental and not officially released in the Ultralytics repository. For now, you can explore all publicly available models and configurations [here](https://docs.ultralytics.com/models). If you're looking for the latest updates and potentially experimental branches, I recommend keeping an eye on our GitHub repository. Thanks for your interest! 🚀

**Comment by faridamousa** [comment]
hi.
the same exact thing happened with me in yolov8
________________________________________
From: Glenn Jocher ***@***.***
Sent: Sunday, May 12, 2024 12:14 PM
To: ultralytics/ultralytics
Cc: Farida Hisham Saeed Mohamed Mousa; Comment
Subject: [EXTERNAL EMAIL] - Re: [ultralytics/ultralytics] Create yolov9.yaml (PR #9848)

Hello! YOLOv9, including the yolov9.yaml file, is currently experimental and not officially released in the Ultralytics repository. For now, you can explore all publicly available models and configurations here<https://docs.ultralytics.com/models>. If you're looking for the latest updates and potentially experimental branches, I recommend keeping an eye on our GitHub repository. Thanks for your interest! 🚀

**Pull request closed without merging**
