### PR TITLE
Update Dockerfile for Raspberry Pi Support

### PR DESCRIPTION
**Pull request by lakshanthad**
This PR updates Docker support for the latest Raspberry Pi Bookworm OS which is based on Debian 12. 

I have read the CLA Document and I hereby sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Adding Docker support for Raspberry Pi 🥧🐍

### 📊 Key Changes
- New `Dockerfile-raspberrypi` file for building Ultralytics images on Raspberry Pi
- Based on the Debian Bookworm image for ARM64 architectures
- Installation of dependencies tailored to Raspberry Pi compatibility
- Provides a YOLOv8n pretrained model file for immediate use

### 🎯 Purpose & Impact
- 🎯 **Purpose**: Enhance the accessibility of Ultralytics software on Raspberry Pi devices, making it possible to run Ultralytics in a containerized environment on ARM64 devices.
- 👥 **Impact**: Raspberry Pi users can now easily deploy Ultralytics in Docker, leveraging the ease of Docker for managing dependencies and environments. This expands the reach of Ultralytics to a wider range of platforms and could potentially boost adoption for edge computing applications on Raspberry Pi.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to Dockerfile for ARM64: Switch to Debian base and add needed packages.

### 📊 Key Changes
- 🍏 Expanded compatibility to include Apple's M2 and future M3 chips alongside the M1, as well as other ARM architectures.
- 🐧 Switched from an Ubuntu base image to a Debian "bookworm-slim" base image for the ARM64 Docker build.
- 👷‍♂️ Added `cmake` and `build-essential` to the list of installed packages, required for building `onnxsim` when exporting models to `tflite` format.

### 🎯 Purpose & Impact
- 🔨 The compatibility expansion ensures broader support for users with newer Apple Silicon chips and maintains support for other popular ARM architectures.
- 🛠 The switch to Debian may provide a more lightweight and streamlined container environment.
- ✨ The additional packages allow for enhanced functionality within the Docker environment, enabling users to perform more tasks without additional setup, especially in model conversions.
- 🚀 These updates aim to improve the overall developer and user experience by ensuring compatibility, easing deployment, and reducing potential issues when interacting with Ultralytics projects on ARM64 platforms.

### CODE REVIEW

**Comment by lakshanthad** [comment]
I have read the CLA Document and I sign the CLA

**Comment by lakshanthad** [comment]
@glenn-jocher

**Comment by glenn-jocher** [comment]
@lakshanthad thanks, looks good! This won't autodeploy to Dockerhub without some additions to the Action also in https://github.com/ultralytics/ultralytics/blob/main/.github/workflows/docker.yaml

**Comment by glenn-jocher** [comment]
@lakshanthad also we need some updates to the Docs Quickstart page that explains the Dockerfile types and their purpose in https://github.com/ultralytics/ultralytics/blob/main/docs/en/quickstart.md, I think just adding this Dockerfile to the bullet points there should suffice.

**Comment by glenn-jocher** [comment]
@lakshanthad additionally add a line to https://docs.ultralytics.com/guides/docker-quickstart/#verify-nvidia-runtime-with-docker

**Comment by glenn-jocher** [comment]
@lakshanthad was reviewing this some more and it's unclear to me the benefits of creating two arm64/v8 images. Since we already have `Dockerfile-arm64` with an ubuntu base, we'd have two nearly identical Dockerfiles with duplicate maintenance no?

Also we get hurt on our security scans if our image bases have more vulnerabilities, and a check between the two bases shows that:

- Slim bookworm is larger than ubuntu 22.04
- Slim bookworm introduces an additional High Severity vulnerability

I used Dockerhub to check both:

- [Ubuntu 22.04](https://hub.docker.com/layers/library/ubuntu/22.04/images/sha256-0cbbf3da525db002984815828355ce8c9ceb09720d3c7bd2210ae5a7084d5804?context=explore&tab=vulnerabilities )
- [Slim bookworm](https://hub.docker.com/layers/library/debian/bookworm-slim/images/sha256-0102d8e816536746a71f0450e86e61fadd5298a89daa33fcf68b630dac766ee4?context=explore&tab=vulnerabilities)

Screenshot 2024-02-10 at 19 52 31

**Comment by lakshanthad** [comment]
Hello @glenn-jocher,
I understand your concerns. The reason I created a separate Dockerfile for Raspberry Pi with Debian slim bookworm (Debian 12) is that the latest official Raspberry Pi OS Bookworm (based on Debian 12) is running the same flavor and thought would be better to have a Docker which has similar environment as the RPi OS (example: Debian bookworm and latest RPi OS has same Python version). In this way, if there are any issues need to fix for Raspberry Pi OS side, we can reflect the same changes for the Docker image based on Bookworm. Also I did not notice those vulnerabilities early on because I referred to this particular Docker: 
https://hub.docker.com/layers/arm64v8/debian/bookworm-slim/images/sha256-0102d8e816536746a71f0450e86e61fadd5298a89daa33fcf68b630dac766ee4?context=explore. 
I am not sure the same vulnerabilities from the official Debian link you shared will be reflected on this repo.

**Comment by lakshanthad** [comment]
@glenn-jocher If you are on the same page as me with my previous comment, I can make further changes as well inside the below files to reflect the new "raspberrypi" Dockerfile.

- https://github.com/ultralytics/ultralytics/blob/main/.github/workflows/docker.yaml
- https://github.com/ultralytics/ultralytics/blob/main/docs/en/quickstart.md
- https://github.com/ultralytics/ultralytics/blob/main/docs/en/guides/docker-quickstart.md

In this case, we can get rid of "arm64" Dockerfile. But that will remain us with wanting another Dockerfile for Apple Silicon as well.

**Comment by lakshanthad** [comment]
Also for the official Debian package, there are no more vulnerabilities anymore:
https://hub.docker.com/layers/library/debian/bookworm-slim/images/sha256-6bdbd579ba71f6855deecf57e64524921aed6b97ff1e5195436f244d2cb42b12?context=explore

**Comment by lakshanthad** [comment]
@glenn-jocher FYI

**Comment by lakshanthad** [comment]
Please test on Apple Silicon and verify as well. I do not have Apple Silicon to test here.

**Comment by glenn-jocher** [comment]
@lakshanthad ah, we'll have to send you a Macbook too now 😂

Apple M1 runners are actually available for free now in GitHub, i.e. the `macos-14` runners in the CI above are running on Apple M1 chips, I wonder if we should add Docker tests on these.

**Comment by lakshanthad** [comment]
> @lakshanthad ah, we'll have to send you a Macbook too now 😂

haha. will be nice to have Apple silicon :)

You can make the call to add the Docker tests on the M1 chips. I think there is nothing to lose by adding that.

**Comment by glenn-jocher** [comment]
@lakshanthad yeah that would be really nice, but also a bit complicated right now since we're running all Docker publishing and testing right now on a single `ubuntu-latest` type in https://github.com/ultralytics/ultralytics/blob/main/.github/workflows/docker.yaml


@Burhan-Q can you add a TODO to update docker.yaml for arm64-runner build and testing on `macos-14`?

**Comment by glenn-jocher** [comment]
@lakshanthad PR merged!!

**Pull request merged**
