### PR TITLE
Rename `model_id` to `model.id`

### PR DESCRIPTION
**Pull request by kaikai23**
In function `on_model_save`, there is sometimes an error `AttributeError: 'HUBTrainingSession' object has no attribute 'model_id'` if model_id is not initialized through `_set_train_args`, because `_set_train_args` function is not always invoked for a HUBTrainingSession Object.

changing `session.model_id` to `session.model.id` fix this problem.

    _I have read the CLA Document and I hereby sign the CLA_

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved model checkpoint upload logging in Ultralytics' utilities.

### 📊 Key Changes
- Fixed the logging statement to correctly display the model ID during checkpoint upload.

### 🎯 Purpose & Impact
- 🔍 **Clarity**: Ensures that log messages correctly reflect the model's ID, improving the clarity of log outputs.
- 🛠️ **Debugging and Tracking**: Facilitates better tracking and debugging for developers by providing accurate information in the logs.
- ⏱️ **Efficiency**: Minor refinement which contributes to overall code maintainability and developer experience.

### CODE REVIEW

**Comment by kaikai23** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@kalenmike @hassaanfarooq01 what do you guys think of this? Has the `model_id` usage here been deprecated?

**Review by hassaanfarooq01 — APPROVED** [review]
LGTM!

**Comment by hassaanfarooq01** [comment]
> @kalenmike @hassaanfarooq01 what do you guys think of this? Has the `model_id` usage here been deprecated?

@glenn-jocher: It appears correct to me. Upon reviewing, I did not find model_id being used in the code.

**Comment by glenn-jocher** [comment]
Got it thanks @hassaanfarooq01, will merge this PR!

**Pull request merged**
