### PR TITLE
Update NVIDIA Jetson Doc with more TensorRT Benchmarks

### PR DESCRIPTION
**Pull request by lakshanthad**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated benchmarks for YOLOv8 on NVIDIA Jetson devices, adding new TensorRT formats.

### 📊 Key Changes
- Updated image link in NVIDIA Jetson guide.
- Added TensorRT FP32, FP16, and INT8 formats to benchmark tables across all YOLOv8 model types.

### 🎯 Purpose & Impact
- **Enhanced Performance**: New TensorRT formats offer improved speed and efficiency, particularly FP16 and INT8.
- **User Benefit**: Users can now choose from multiple optimization levels depending on their specific needs for speed and accuracy.

### CODE REVIEW

**Comment by lakshanthad** [comment]
@glenn-jocher Added TensorRT FP16 and INT8 benchmarks to highlight the improved inference performance on edge devices.

**Comment by iurisilvio** [comment]
@lakshanthad Heads up here, there is a JiaT75 commit in your PR. 👀

**Comment by lakshanthad** [comment]
Good catch @iurisilvio! Closing this and re-opening with a new branch.

**Comment by bcomnes** [comment]
Can someone clarify why JiaT75 commits are present in this repo?

**Comment by glenn-jocher** [comment]
The presence of JiaT75 commits may be unintentional or part of a contributor's branch. Please ensure contributions align with the repository's guidelines and avoid including unrelated commits. You can also contact the contributor for clarification.

**Pull request closed without merging**
