### PR TITLE
`plotting` cleanup

### PR DESCRIPTION
**Pull request by RizwanMunawar**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR refines various visualization methods across `heatmap.py`, `object_counter.py`, `parking_management.py`, and `plotting.py` to improve efficiency, readability, and maintainability when rendering annotations and analytics.

### 📊 Key Changes
- **Simplified Visualization Methods**:
  - Removed unnecessary parameters (e.g., `margin`) in several methods like `display_analytics` and `display_objects_labels`.
  - Replaced custom annotation methods with native OpenCV methods for efficiency and clarity, including handling text and drawing shapes.
- **Refactored Logic**:
  - Unified and streamlined text/background color assignment logic.
  - Enhanced methods like `plot_angle_and_count_and_stage` for more modular and consistent drawing logic by introducing helper methods.
- **Updated Parameter Documentation**:
  - Improved inline docstrings for functions, specifying optional parameters and better articulating expected behavior.
- **Enhanced Code Readability**:
  - Consolidated logic for calculating text sizes, aligning rectangles, and centering text or circles.

### 🎯 Purpose & Impact
- **Improved Maintainability**:
  - Streamlined code simplifies debugging and future feature updates.
- **Performance Gains**:
  - Using more native OpenCV operations reduces computational overhead.
- **Better Documentation**:
  - Clearer function descriptions make the code more accessible to developers.
- **Enhanced User Experience**:
  - Precise and visually consistent annotations offer cleaner visual feedback for applications like object counting, heatmaps, and parking management. 🚗📊

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting a PR to the `ultralytics/ultralytics` repository! 🚀 This is an automated response, and an Ultralytics engineer will review your changes soon. In the meantime, please ensure the following checklist is completed:

- ✅ **Purpose Clarity**: Clearly describe the purpose of your changes, and link to any [related issues](https://github.com/ultralytics/ultralytics/issues) in your PR description. Make sure your commit messages are clear and follow the established conventions.
- ✅ **Base Synchronization**: Ensure your branch is up-to-date with the `main` branch. If your branch is behind, please update it using the 'Update branch' button or by executing `git pull` and `git merge main` locally.
- ✅ **Pass CI Checks**: Confirm that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. Resolve any failing checks promptly to ensure your PR is ready for review.
- ✅ **Document Updates**: Provide updates to the [documentation](https://docs.ultralytics.com) for any features or changes that may require it.
- ✅ **Test Coverage**: Include or update tests as necessary to cover your changes, and make sure all tests pass successfully.
- ✅ **Sign the CLA**: If this is your first contribution to an Ultralytics repository, please sign the [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/) by adding a comment saying "I have read the CLA Document and I sign the CLA".
- ✅ **Focus on Essentials**: Limit your modifications to the core changes necessary for your update. Remember the wisdom: _"It is not daily increase, but daily decrease. Hack away at the unessential."_ — Bruce Lee

For any questions or further guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Thank you for your contributions and support! 😊

**Comment by RizwanMunawar** [comment]
@glenn-jocher, `mkdocs.yml --strict` is causing an issue during the Docs check, but I'm not exactly sure what's happening. There doesn't seem to be any error in the logs.

**Comment by glenn-jocher** [comment]
You have to open up the CI and see the error and then fix it manually. It's usually missing rags in docstrings or missing types for args

**Comment by RizwanMunawar** [comment]
@glenn-jocher I think this PR is good to merge :) Thanks

**Pull request closed without merging**
