### PR TITLE
New AGLU activation module

### PR DESCRIPTION
**Pull request by glenn-jocher**
@Laughing-q from https://github.com/kostas1515/AGLU

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing a new activation function module (AGLU) for neural networks in Ultralytics, alongside updated documentation.

### 📊 Key Changes
- **New file `activation.md`:** Added a comprehensive reference document for activation functions.
- **Author update:** Added `hasanghaffari93` to list of contributors.
- **Updated navigation:** Included the activation functions reference in the documentation sidebar.
- **New activation module `AGLU.py`:** Implemented the AGLU (Adaptive Generalized Linear Unit) activation function in Python.

### 🎯 Purpose & Impact
- **Enhanced Documentation:** Makes it easier for developers to understand and use activation functions in the Ultralytics framework 📚.
- **Recognition:** Acknowledges new contributors, fostering community growth 🌱.
- **Improved Usability:** Provides a powerful new activation function that can improve neural network performance, offering users more options for customization and potentially better results 🚀.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q @Laughing-q  this new AGLU activation looks insanely slow. When applied to every activation layer in YOLOv8n:

### Main with SiLU activations

```
YOLOv8n summary (fused): 281 layers, 3,152,018 parameters, 32,034 gradients, 8.7 GFLOPs
...
Speed: 1.5ms preprocess, 43.8ms inference, 0.3ms postprocess per image at shape (1, 3, 640, 384)
```

### AGLU activations

```
YOLOv8n summary (fused): 281 layers, 3,152,018 parameters, 32,034 gradients, 8.7 GFLOPs
...
Speed: 1.2ms preprocess, 71.9ms inference, 0.3ms postprocess per image at shape (1, 3, 640, 384)
```

**Comment by Puiching-Memory** [comment]
Hello! Is there any improvement in accuracy for this new activation function?

**Comment by glenn-jocher** [comment]
@Puiching-Memory hello! The AGLU activation function may offer improved performance in certain scenarios, but results can vary based on the specific model and dataset. It's best to experiment and evaluate its impact on your use case.

**Comment by Burhan-Q** [comment]
@Puiching-Memory this was added from the source implementation for future experimentation. The activation function is parametric and might not give the same results for all uses. I would recommend reading the publication to learn more https://arxiv.org/pdf/2407.08567

**Pull request merged**
