### PR TITLE
Update outputs

### PR DESCRIPTION
**Pull request by Laughing-q**
@AyushExel @glenn-jocher 
- make the Predictor a python generator, then there won't be a memory problem.
- return segments coordinate instead of masks.

python interface usage:
segmentation:
```python
model = YOLO("weights/yolov8n-seg.pt")
for output in model.predict(source="ultralytics/assets"):
    if output:
        print(output['det'].shape)   # ndarray, Nx6, include box, cls score and cls
        print(len(output['segment']))  # List[ndarray], each element is the corresponding coordinate of segment
```
detection:
```python
model = YOLO("weights/yolov8n.pt")
for output in model.predict(source="ultralytics/assets"):
    if output:
        print(output['det'].shape)   # ndarray, Nx6, include box, cls score and cls
```
cls:
```python
model = YOLO("weights/yolov8n-cls.pt")
for output in model.predict(source="ultralytics/assets"):
    if output:
        print(output['prob'].shape)   # ndarray, shape: (num_class, )
```
set a arg `return_outputs` to control whether to return outputs.
`return_outputs=True` by default in python interface.
`return_outputs=False` by default in cli mode.

If don't want the outputs in python interface, just set it to `False`.
```python
model = YOLO("weights/yolov8n-cls.pt")
model.predict(source="ultralytics/assets", return_outputs=False):
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactoring prediction functionality to support iterative result generation and optional result return in Ultralytics YOLO models.

### 📊 Key Changes
- Modified tests to iterate through predictions instead of relying on a direct list length check.
- Added an optional `return_outputs` flag to the `predict()` method to control the output behavior.
- Updated predictors to act as generators yielding results upon each iteration if `return_outputs` is set to `True`.
- Altered client-facing scripts to reflect generator behavior and handle the option of not returning outputs.
- Removed unused accumulation of `all_outputs` in favor of yielding or returning individual predictions.

### 🎯 Purpose & Impact
- **Purpose**: To enhance the prediction methods by providing more flexible output handling and allowing incremental processing of results.
- **Impact for Developers**: More control over how prediction results are processed and presented, making integration into larger applications smoother.
- **Impact for Users**: Potential for improved performance and memory usage when handling large numbers of predictions, as not all results need to be kept in memory at once. 🚀

### CODE REVIEW

**Comment by AyushExel** [comment]
@Laughing-q okay perfect! let's discuss this later today. I'll add some docs so we have them at the same time as release

**Comment by glenn-jocher** [comment]
recheck

**Comment by AyushExel** [comment]
@Laughing-q do we have a function in place to convert segment coordinates to masks?

**Comment by Laughing-q** [comment]
@AyushExel here, but it serves dataset. never tested independently.
[https://github.com/ultralytics/ultralytics/blob/55b313b167d2e65910058ca5710483c90a8208c4/ultralytics/yolo/data/utils.py#L133-L151](https://github.com/ultralytics/ultralytics/blob/55b313b167d2e65910058ca5710483c90a8208c4/ultralytics/yolo/data/utils.py#L133-L151)

**Comment by glenn-jocher** [comment]
@Laughing-q good to merge?

**Comment by glenn-jocher** [comment]
Merged into 8.0.3 fixes

**Pull request merged**
