### PR TITLE
`ultralytics 8.2.61` fix `num_threads` for CPU training

### LINKED ISSUE #14488: Training a model using ARM64 devices utilizes only one core
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

When training a model on ARM64 devices only one CPU core out of 4 or 8 (depending on the device) will be used.

I tested it on RPi5 (BCM2712) and OrangePi5 Plus (RK3855), same result.
I tested it in a docker container and standalone, same result.
settings of: batch=4, device='cpu', workers=4 does not seem to have an effect.

image

### Environment

Ultralytics YOLOv8.2.58 🚀 Python-3.11.2 torch-2.3.1 CPU (Cortex-A55)
Setup complete ✅ (8 CPUs, 15.6 GB RAM, 43.7/225.9 GB disk)

OS                  Linux-6.1.43-vendor-rk35xx-aarch64-with-glibc2.36
Environment         Linux
Python              3.11.2
Install             git
RAM                 15.59 GB
CPU                 Cortex-A55
CUDA                None

numpy               ✅ 1.23.5<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.14.0>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

# train.py: 

from ultralytics import YOLO

model = YOLO("yolov8n.yaml")  # build a new model from scratch

results = model.train(data="config.yaml", epochs=1, batch=4, device='cpu', workers=4)  # train the model

# config.yaml:
path: /usr/src/ultralytics/data  
train: images/train  
val: images/validation 

names:
  0: alpaca

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR enhances documentation processing and configuration handling in the Ultralytics library.

### 📊 Key Changes
- **Documentation Updates:**
  - Added functionality to convert plaintext links to HTML hyperlinks in generated documentation.
  - Improved docstring handling with new options in `mkdocs.yml`.
- **Configuration Handling Enhancements:**
  - Enhanced type annotations and added detailed docstrings to several configuration-related functions.
- **Version Update:** 
  - Bumped library version from `8.2.60` to `8.2.61`.
- **Device Selection:**
  - Adjusted CPU training settings to reset OMP_NUM_THREADS where applicable.

### 🎯 Purpose & Impact
- **Improved User Documentation:**
  - Easier navigation with clickable links directly in the HTML docs.
  - Clearer and more compliant docstrings for better code understanding and documentation generation.
- **Enhanced Config Management:**
  - Better handling and validation of configurations increases reliability and usability for users.
- **Optimized CPU Performance:**
  - More efficient CPU utilization during training by managing thread settings.

These improvements collectively enhance user experience by providing clearer documentation and more robust configuration management, along with optimized resource usage during training. 🚀

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher @Burhan-Q From the [torch docs page](https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html#runtime-api) I think we could also use `torch.set_num_threads(1)` instead of using `os.environ["OMP_NUM_THREADS"]` at the top of our input for the issue me and Burhan encountered within local python env, but not sure if it'd work, since currently all the gpus on server are busy I could test this out later some time and submit another PR if it works.

**Comment by Laughing-q** [comment]
> @glenn-jocher @Burhan-Q From the [torch docs page](https://pytorch.org/docs/stable/notes/cpu_threading_torchscript_inference.html#runtime-api) I think we could also use `torch.set_num_threads(1)` instead of using `os.environ["OMP_NUM_THREADS"]=1` at the very top of our import for the issue me and Burhan encountered within local python env, but not sure if it'd work, since currently all the gpus on server are busy I could test this out later some time and submit another PR if it works.

@Burhan-Q @glenn-jocher ok just tested the idea on server but it didn't work, let's stick the `os.environ["OMP_NUM_THREADS"]=1` at the very top of import.

**Comment by glenn-jocher** [comment]
@Laughing-q ok got it. This looks like a good fix. I'll test now on macbook.

**Comment by glenn-jocher** [comment]
No it's not working for me. 

### this PR (100% util)
Screenshot 2024-07-19 at 17 49 54

### if I comment out the ultralytics/__init__ ENV setting (~600% util)
Screenshot 2024-07-19 at 17 51 17

**Comment by glenn-jocher** [comment]
@Laughing-q @Burhan-Q does this PR actually speed up CPU training for you? On my M2 Macbook VOC training went from 9s/it (main) to 7s/it (this PR), but CPU util went from 100% to 600%, which seems like a very poor tradeoff.

**Comment by Laughing-q** [comment]
@glenn-jocher yes it speeds up cpu training for me, which works just like I manually comment the ENV code. let me do a test real quick and post it here

**Comment by Laughing-q** [comment]
@glenn-jocher 
```bash
yolo detect train model=yolov8n.pt data=coco128.yaml epochs=20 device=cpu
```
### main branch
```bash
1/20         0G      1.155      1.494      1.217        215        640: 100%|██████████| 8/8 [00:37<00:00,  4.63s/it]
```
one core used:
pic-240720-0008-54
### main branch with the ENV commented
```bash
1/20         0G      1.155      1.494      1.217        215        640: 100%|██████████| 8/8 [00:12<00:00,  1.52s/it]
```
multi cores used:
pic-240720-0009-33
### this PR
```bash
1/20         0G      1.155      1.494      1.217        215        640: 100%|██████████| 8/8 [00:11<00:00,  1.50s/it]
```
8 cores used since `NUM_THREADS=min(8, max(1, os.cpu_count() - 1))`
pic-240720-0011-02

**Comment by glenn-jocher** [comment]
@Laughing-q oh wow, ok so it looks like it is working at least in Linux environments, so I think we should go ahead and merge.

**Comment by Laughing-q** [comment]
@glenn-jocher oh wait! did you explicitly set `device=cpu`(I guess it's `mps` on Mac?), if not then the PR would not work for you since I added the `torch.set_num_threads` in the `if cpu or mps` flow that works only when explicitly set device to cpu/mps.
If this is the case then we'll need to put this line to somewhere else in the function. Could you do the update? I've shut down my system. Thanks!

**Comment by glenn-jocher** [comment]
@Laughing-q oh I get it now, if the device is not explicitly set the new line does not run, makes sense. I'll check it out.

**Comment by Burhan-Q** [comment]
Following example from @Laughing-q run on person Linux system

## On Main branch

```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20         0G      1.135      1.433      1.236        278        640: 8/8 [01:50<00:00, 13.82s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:37<00:00,  9.29s/it]
                   all        128        929      0.657      0.534      0.615      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20         0G      1.109      1.341      1.237        167        640: 8/8 [01:47<00:00, 13.43s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:35<00:00,  8.98s/it]
                   all        128        929      0.682      0.546      0.629      0.467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20         0G      1.194      1.388      1.235        239        640: 8/8 [01:45<00:00, 13.24s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:35<00:00,  8.85s/it]
                   all        128        929      0.676      0.566      0.645      0.479
```

image

## On this PR

```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20         0G      1.135      1.433      1.236        278        640: 8/8 [00:43<00:00,  5.43s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:15<00:00,  3.81s/it]
                   all        128        929      0.657      0.534      0.615      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20         0G      1.109      1.341      1.237        167        640: 8/8 [00:43<00:00,  5.40s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:15<00:00,  3.77s/it]
                   all        128        929      0.682      0.546      0.629      0.467

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20         0G      1.194      1.388      1.235        239        640: 8/8 [00:41<00:00,  5.24s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:14<00:00,  3.61s/it]
                   all        128        929      0.676      0.566      0.645      0.479
```

image

## Linux System Info

<details><summary>Details</summary>
<p>

```
Ultralytics YOLOv8.2.60 🚀 Python-3.10.12 torch-2.2.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5924MiB)
Setup complete ✅ (12 CPUs, 15.6 GB RAM, 88.3/101.0 GB disk)

OS                  Linux-6.6.10-76060610-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             git
RAM                 15.56 GB
CPU                 AMD Ryzen 5 1600 Six-Core Processor
CUDA                12.1

matplotlib          ✅ 3.8.1>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.2.0>=1.8.0
torchvision         ✅ 0.17.0>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0
```

</p>
</details>

**Comment by Burhan-Q** [comment]
## Windows 10 test

## On Main

```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20         0G      1.135      1.433      1.236        278        640: 8/8 [01:29<00:00, 11.21s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:35<00:00,  8.98s/it]
                   all        128        929      0.657      0.534      0.615      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20         0G      1.109      1.341      1.237        167        640: 8/8 [01:29<00:00, 11.13s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:35<00:00,  8.92s/it]
                   all        128        929      0.682      0.546      0.629      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20         0G      1.194      1.388      1.235        239        640: 8/8 [01:33<00:00, 11.69s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:35<00:00,  8.94s/it]
                   all        128        929      0.675      0.566      0.645      0.479
```

**NOTE** %-load shown for all CPU cores
image

## On this PR

```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       1/20         0G      1.135      1.433      1.236        278        640: 8/8 [00:34<00:00,  4.31s/it]   
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:13<00:00,  3.39s/it]
                   all        128        929      0.657      0.534      0.615      0.457

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       2/20         0G      1.109      1.341      1.237        167        640: 8/8 [00:32<00:00,  4.03s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:12<00:00,  3.14s/it]
                   all        128        929      0.682      0.546      0.629      0.468

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
       3/20         0G      1.194      1.388      1.235        239        640: 8/8 [00:32<00:00,  4.01s/it]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 4/4 [00:12<00:00,  3.15s/it]
                   all        128        929      0.675      0.566      0.645      0.479
```

image

## Windows 10 System Info

<details><summary>Details</summary>
<p>


```
Ultralytics YOLOv8.2.60 🚀 Python-3.10.9 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)
Setup complete ✅ (12 CPUs, 31.9 GB RAM, 762.0/1863.0 GB disk)

OS                  Windows-10-10.0.19045-SP0       
Environment         Windows
Python              3.10.9
Install             git
RAM                 31.86 GB
CPU                 Intel Core(TM) i5-10600K 4.10GHz
CUDA                12.1

matplotlib          ✅ 3.8.1>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 10.1.0>=7.1.2  
pyyaml              ✅ 6.0.1>=5.3.1  
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 2.1.1+cu121>=1.8.0 
torchvision         ✅ 0.16.1+cu121>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 5.9.6
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.1.3>=1.1.4  
seaborn             ✅ 0.13.0>=0.11.0
```

</p>
</details>

**Comment by Burhan-Q** [comment]
Looks like Linux and Windows both see a significant increase on CPU training

**Comment by glenn-jocher** [comment]
@Laughing-q looks good, works correctly on M2 mac also, though same limited speedup. I'll go ahead and merge!

Note I've combined with some docs updates for reference landing page of cfg/init

**Comment by tilobormann** [comment]
thanks for the fix. It works now :-) not as much improvement as expected but quite a bit. Thanks

**Comment by pderrenger** [comment]
Glad to hear the fix is working for you! While the improvement might not be as significant as expected, it's good to know there's a noticeable difference. If you have any further questions or need additional assistance, feel free to ask.

**Comment by Y-T-G** [comment]
It's possible to perform distributed training on CPU.

https://stackoverflow.com/a/75049344

I wonder if this will provide more speedup than this approach.

**Pull request merged**
