### PR TITLE
Update version of PyTorch <2.0

### PR DESCRIPTION
**Pull request by gustavo-moura**
This pull request is to address the bug in the latest version of PyTorch, which produces the following error message:

"File "/opt/conda/envs/.../lib/python3.10/site-packages/torch/nn/modules/conv.py", line 459, in _conv_forward return F.conv2d(input, weight, bias, self.stride,
RuntimeError: GET was unable to find an engine to execute this computation"

After some investigation, I found that this error is caused by a compatibility issue between PyTorch and some other libraries used in the project. Specifically, the PyTorch version used in the project is not compatible with the other dependencies, which leads to the above error.

To solve this issue, I propose enforcing the PyTorch package to be in the version <2.0, and Torchvision <0.15, which is compatible with the other dependencies used in the project. I have tested this solution on my local machine and verified that it resolves the error.

Therefore, I suggest updating the project requirements to include:

torch>=1.7.0,<2.0
torchvision>=0.8.1,<0.15

I hope this solution will be helpful in resolving the issue, and I am happy to provide any further assistance.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR appears to have no code changes. It might be a placeholder, draft, or for discussion purposes only.

### 📊 Key Changes
- No changes detected in the PR diff.

### 🎯 Purpose & Impact
- Since there are no code modifications, there is no direct impact on the project's functionality.
- The PR may be intended for non-code related discussions or future preparations that are not yet reflected in the codebase.
- Users and developers can expect no changes or impact from this PR until further updates are provided.

### CODE REVIEW

**Comment by gustavo-moura** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@gustavo-moura hi! Thanks for letting us know of a dependency conflict. 

We have CI running successfully with PyTorch 2.0, and we want all users to be able to use 2.0 since this is the latest major release with a lot of improvements. 

Can you explain the exact dependency conflicts?

**Comment by glenn-jocher** [comment]
@gustavo-moura thank you for your interest in contributing to Ultralytics YOLOv8! We appreciate the time and effort you put into creating this pull request. After careful review, we have decided to close the current PR as it doesn't align with the project's roadmap or objectives.

However, we would like to encourage you to continue contributing to the project in the future! Your ideas and contributions are valuable to us, and we look forward to seeing more from you. Please keep an eye on our open issues and feel free to propose new features or improvements that can help enhance YOLOv8. Your participation in our community is important to us.

**Comment by GDbbq** [comment]
PyTorch version 2.0.1, NVIDIA 1080ti, I encountered the same problem. Changing to PyTorch 1.13 can solve it.

**Comment by glenn-jocher** [comment]
@GDbbq thank you for reporting the issue and sharing your solution! It's great to hear that downgrading to PyTorch 1.13 helped resolve the issue you encountered on YOLOv8. This may be because there are incompatibilities between the PyTorch version you were using and YOLOv8, which have been addressed in PyTorch 1.13. It's always a good idea to double-check which versions of required dependencies are compatible with the main repository. Again, we appreciate your contribution to the YOLOv8 community!

**Comment by Nghingtim** [comment]
I met the same problems. I solved by 
Successfully installed torch-1.13.0 torchvision-0.14.0

**Comment by glenn-jocher** [comment]
@Nghingtim thank you for reporting the issue and sharing your solution! We're glad to hear that downgrading to PyTorch 1.13 and installing torchvision 0.14.0 helped resolve the problem you encountered on YOLOv8. It's possible that there were version incompatibilities between the specific versions you were previously using and YOLOv8. By installing the recommended versions, you were able to successfully run YOLOv8. We appreciate your contribution and feedback to the YOLOv8 community!

**Comment by Sathyxn** [comment]
any ideas on how to install torchvision 0.14.0 its not available through pip

**Comment by pderrenger** [comment]
@Sathyxn you can install a specific version of torchvision using the following command:

```bash
pip install torchvision==0.14.0
```

This will install torchvision version 0.14.0 specifically. If the version you specify is available, it will be downloaded and installed.

**Pull request merged**
