### PR TITLE
Hyperparameter tune resume

### PR DESCRIPTION
**Pull request by finlaymorrison**
Added an additional argument to the tuner which allows for the resumption of previous tuning runs. The argument is used to point to a CSV file generated in a previous run, the contents of which are copied to the CSV file for the new run. This PR is a solution to #6674 .

### Summary
:sparkles::memo::wrench:

This pull request adds a feature to resume or refine model tuning using a custom fitness file. It modifies the `Tuner` class in `ultralytics/engine/tuner.py` and the `tune` settings in `ultralytics/cfg/default.yaml` to support this feature.

> _`Tune` your fate with a file of the past_
> _`Tuner` of doom, resume or refine your task_
> _`Path` of power, handle the files with ease_
> _Custom fitness, unleash the beast within_

### Walkthrough
*  Add `fitness_file` option to `tune` settings in `default.yaml` ([link](https://github.com/ultralytics/ultralytics/pull/6699/files?diff=unified&w=0#diff-732d61cb4969eff986cec58058000b2949ea3b429a97ca5a1045897e754145c5R64-R66))
*  Import `Path` class from `pathlib` module in `tuner.py` ([link](https://github.com/ultralytics/ultralytics/pull/6699/files?diff=unified&w=0#diff-d42d1b8bc1c237d1e34d8da7ab7ab8130ad4eab91e795d5030271dafb52565d9R23))
*  Use `fitness_file` argument to copy existing fitness data to `tune_csv` attribute of `Tuner` instance in `tuner.py` ([link](https://github.com/ultralytics/ultralytics/pull/6699/files?diff=unified&w=0#diff-d42d1b8bc1c237d1e34d8da7ab7ab8130ad4eab91e795d5030271dafb52565d9R171-R177))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the hyperparameter tuning process with resume capability.

### 📊 Key Changes
- Added a flag `exist_ok` to allow resumption if the project directory already exists.
- Introduced a check to determine which iteration to start from, based on existing results.

### 🎯 Purpose & Impact
- The purpose of the changes is to enable the hyperparameter tuner to pick up from the last completed iteration rather than starting over, saving time and resources.
- Users can now resume interrupted tuning sessions without losing progress, resulting in a more efficient hyperparameter optimization workflow. 🔄

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@finlaymorrison thank you for the PR and for addressing issue #6674 concerning hyperparameter tuning resumption. 🙌

The addition of the capability to resume tuning from a previous run by leveraging an existing CSV fitness file is a valuable feature for our community. It enhances the user experience by providing flexibility and efficiency, especially when iterative tuning is a common practice.

As the PR involves the `Tuner` class and tuning settings configuration, I'd like to remind contributors that any code-level discussion, review, or further clarification should take place within the PR thread to ensure a focused and effective conversation about the implementation details.

For anyone integrating this feature into their workflows, the concepts introduced will be documented appropriately, accessible through our Ultralytics documentation.

Once this feature has been reviewed and integrated, it should considerably simplify the tuning process, saving time and computational resources for users. We appreciate your meaningful contribution to the YOLOv8 project—teamwork makes the dream work! 🚀😄

**Comment by finlaymorrison** [comment]
Ahh brilliant! It was rather unclear that this is a feature so I would recommend this to be documented. The only result for resuming hyperparameter tuning I get from searching is Issue #5892, where your comments suggest that such a feature does not exist

"That being said, I agree that it might be beneficial to have a feature that saves the state of the tuning process after each iteration, allowing for a restart from the last completed iteration in case of interruptions. We'll take this into consideration for the future. Thank you for your feedback and please let us know how your tuning goes!"

**Comment by finlaymorrison** [comment]
Upon testing I confirmed that you were suggesting a different implementation of this feature as opposed to an already existing feature, and so I put together a commit to implement the changes as you suggested.

I find it somewhat confusing that the `name` argument when using the tuner is actually used as the name of each of the training runs, and the tune run itself has it's name set to simply `"name"`. From my point of view it would make sense to have the `name` parameter be for the tune directory, and then each of the training runs should be nested inside this directory in their own subdirectory to keep the workspace clean. I am not familiar with any technical challenges with this approach though, and this is probably something that could be discussed in a separate issue if you think that this could do with changing.

**Comment by glenn-jocher** [comment]
@finlaymorrison apologies for any confusion. My previous comment was indeed a suggestion for how the feature could be implemented, rather than stating that the feature already exists. To clarify, the idea is to leverage existing `project` and `name` arguments to control the resumption of tuning, not that this functionality is currently available.

As for your observation about the directory structure, I appreciate your input. The current setup with the `name` argument is linked directly to individual training runs for simplicity, but I see how your proposal could offer a cleaner workspace.

This is a point worth considering, and it would definitely merit a separate discussion. I suggest opening a new issue to deliberate this further with the community and the Ultralytics team. There could indeed be technical implications or use cases that need to be considered when reorganizing the directory structure for training and tuning runs.

I'd like to thank you for engaging with the project, thinking critically about its architecture, and for your efforts to contribute. User insights like yours are invaluable in the pursuit of enhancing our tools. 🌟

**Comment by finlaymorrison** [comment]
I can attest t the fact that the existing arguments, one specifying the project directory and one for the name is a little confusing initially. I personally think that sort of organisation is best handled by the user too.

In response to your second comment, I have run tests which verify that it resumes from the last completed iteration.

**Comment by glenn-jocher** [comment]
@finlaymorrison hey I just checked the code and it seems that the resume functionality is already in the code as this line will simply load any existing tuning results CSV that is found:
https://github.com/ultralytics/ultralytics/blob/79c1923b3341a0128d64e536dae48c37c293149f/ultralytics/engine/tuner.py#L115

So I think my original usage is already in place but simply requires exist_ok=True, which makes sense as otherwise project/name will be incremented to prevent overwriting during train/predict/val/tune etc.

**Comment by finlaymorrison** [comment]
Yeah so I also realized that the single line of adding `args.exist_ok=True` allows for resumption, but I added the other logic to resume from the previous iteration, so the remaining code is simply to figure out what iteration was the last iteration completed.

When it comes to your point about there being two tune directories in the directory, with this change this would no longer occur. The only way to have a run called `tune2` is if you run the code in a project which already has a `tune` directory; however, with this change this would no longer be possible, as if you were to run a tuning run in the same directory it would simply resume from the previous `tune` run.

This does however sort of loop back to the fact that the current system for projects and run names being somewhat confusing.

**Comment by finlaymorrison** [comment]
@glenn-jocher Could I get some updates on this as to whether you are expecting me to make any further changes to this PR before it can potentially be merged?

**Comment by finlaymorrison** [comment]
Hi @glenn-jocher ,

Do you happen to know of a timeline as to when you expect this to be merged into the main branch, assuming there are no issues with the changes? Thanks.

**Comment by glenn-jocher** [comment]
@finlaymorrison hi there,

We don't have a specific timeline for the merge. The review process is underway and if all checks out, it'll be merged promptly. Please keep an eye on the PR for any updates or requests for further information. Thanks for your patience! 🚀

**Comment by Thorwig** [comment]
Hi @glenn-jocher,

I was wondering if this feature has been implemented yet.
Thanks for your work on yolov8, it's truly amazing!

**Comment by glenn-jocher** [comment]
@Thorwig hi there! 😊

Thanks for the kind words! If you're referring to a specific feature, could you please clarify which one? We're constantly updating YOLOv8, so I'd love to give you the most accurate info.

Cheers!

**Comment by ArnauCampanera** [comment]
Hello @glenn-jocher ! I think @Thorwig was referring to the main topic of this thread, which was a PR for implementing the ability to resume a tuning process that might have been stopped for some reason.

Your last message about the PR was "The review process is underway and if all checks out, it'll be merged promptly.", but it was four months ago.

I am also very interested in the implementation of this feature as my tuning suddenly stopped this morning after 300 iterations :( . I tried using the 'resume' argument and the 'exist_ok=True' but it is not working yet.

Hopefully you can give as a clue as where the process is right now. Thank you for the amazing work!

**Comment by glenn-jocher** [comment]
Hi there! 👋

Thanks for bringing this up, and I'm sorry to hear about the interruption in your tuning process. We understand how crucial the resume functionality is, especially for long and resource-intensive tuning sessions.

To update you on the PR discussion: we've been making progress behind the scenes to ensure the feature is integrated smoothly and efficiently. These things sometimes take a little longer than anticipated, but please rest assured it's on our radar.

In the meantime, a temporary workaround might involve manually adjusting your starting point based on the last completed iteration, though I realize it's far from ideal. If you're working with a `.yaml` file for the tuning config, you might attempt to manually set the start iteration to bypass previously completed ones.

```yaml
start_iteration: 301  # Assuming 300 iterations were completed
```

Thank you for your patience and for the kind words about YOLOv8. We're all in this together, and your feedback is incredibly valuable to us. Keep an eye on the updates, and we hope to get this sorted for you soon!

Cheers! 🚀

**Comment by snehitvaddi** [comment]
Hello @glenn-jocher & Team!
Has the "Resume a tuning process from where it left" been implemented and merged?
Any update on how to implement that please?

**Comment by glenn-jocher** [comment]
Hi @snehitvaddi,

Thank you for your interest. The "Resume a tuning process from where it left" feature is still under review and has not yet been merged. We appreciate your patience and will update the repository with detailed instructions once it's available. For now, please ensure you are using the latest package versions, as updates and fixes are continuously being made.

**Comment by glenn-jocher** [comment]
Hi @ArnauCampanera,

Thanks for reaching out. The feature is still under review, and we're working to ensure it's implemented correctly. We appreciate your patience and understanding. If you have any more questions, feel free to ask here.

**Comment by glenn-jocher** [comment]
Hi @ArnauCampanera,

Thank you for your patience. The feature is still under review. Please keep an eye on the PR for updates. We appreciate your support and understanding!

**Comment by mounish-cresco** [comment]
If you want to use this feature ,copy this code and paste into your tuner.py code .
`# Ultralytics YOLO 🚀, AGPL-3.0 license
"""
This module provides functionalities for hyperparameter tuning of the Ultralytics YOLO models for object detection,
instance segmentation, image classification, pose estimation, and multi-object tracking.

Hyperparameter tuning is the process of systematically searching for the optimal set of hyperparameters
that yield the best model performance. This is particularly crucial in deep learning models like YOLO,
where small changes in hyperparameters can lead to significant differences in model accuracy and efficiency.

Example:
    Tune hyperparameters for YOLOv8n on COCO8 at imgsz=640 and epochs=30 for 300 tuning iterations.
    ```python
    from ultralytics import YOLO

    model = YOLO('yolov8n.pt')
    model.tune(data='coco8.yaml', epochs=10, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)
    ```
"""
import random
import shutil
import subprocess
import time

import numpy as np
import torch

from ultralytics.cfg import get_cfg, get_save_dir
from ultralytics.utils import DEFAULT_CFG, LOGGER, callbacks, colorstr, remove_colorstr, yaml_print, yaml_save
from ultralytics.utils.plotting import plot_tune_results


class Tuner:
    """
    Class responsible for hyperparameter tuning of YOLO models.

    The class evolves YOLO model hyperparameters over a given number of iterations
    by mutating them according to the search space and retraining the model to evaluate their performance.

    Attributes:
        space (dict): Hyperparameter search space containing bounds and scaling factors for mutation.
        tune_dir (Path): Directory where evolution logs and results will be saved.
        tune_csv (Path): Path to the CSV file where evolution logs are saved.

    Methods:
        _mutate(hyp: dict) -> dict:
            Mutates the given hyperparameters within the bounds specified in `self.space`.

        __call__():
            Executes the hyperparameter evolution across multiple iterations.

    Example:
        Tune hyperparameters for YOLOv8n on COCO8 at imgsz=640 and epochs=30 for 300 tuning iterations.
        ```python
        from ultralytics import YOLO

        model = YOLO('yolov8n.pt')
        model.tune(data='coco8.yaml', epochs=10, iterations=300, optimizer='AdamW', plots=False, save=False, val=False)
        ```
    """

    def __init__(self, args=DEFAULT_CFG, _callbacks=None):
        """
        Initialize the Tuner with configurations.

        Args:
            args (dict, optional): Configuration for hyperparameter evolution.
        """
        self.args = get_cfg(overrides=args)
        self.space = {  # key: (min, max, gain(optional))
            # 'optimizer': tune.choice(['SGD', 'Adam', 'AdamW', 'NAdam', 'RAdam', 'RMSProp']),
            'lr0': (1e-5, 1e-1),
            'lrf': (0.0001, 0.1),  # final OneCycleLR learning rate (lr0 * lrf)
            'momentum': (0.7, 0.98, 0.3),  # SGD momentum/Adam beta1
            'weight_decay': (0.0, 0.001),  # optimizer weight decay 5e-4
            'warmup_epochs': (0.0, 5.0),  # warmup epochs (fractions ok)
            'warmup_momentum': (0.0, 0.95),  # warmup initial momentum
            'box': (1.0, 20.0),  # box loss gain
            'cls': (0.2, 4.0),  # cls loss gain (scale with pixels)
            'dfl': (0.4, 6.0),  # dfl loss gain
            'hsv_h': (0.0, 0.1),  # image HSV-Hue augmentation (fraction)
            'hsv_s': (0.0, 0.9),  # image HSV-Saturation augmentation (fraction)
            'hsv_v': (0.0, 0.9),  # image HSV-Value augmentation (fraction)
            'degrees': (0.0, 45.0),  # image rotation (+/- deg)
            'translate': (0.0, 0.9),  # image translation (+/- fraction)
            'scale': (0.0, 0.95),  # image scale (+/- gain)
            'shear': (0.0, 10.0),  # image shear (+/- deg)
            'perspective': (0.0, 0.001),  # image perspective (+/- fraction), range 0-0.001
            'flipud': (0.0, 1.0),  # image flip up-down (probability)
            'fliplr': (0.0, 1.0),  # image flip left-right (probability)
            'mosaic': (0.0, 1.0),  # image mixup (probability)
            'mixup': (0.0, 1.0),  # image mixup (probability)
            'copy_paste': (0.0, 1.0)}  # segment copy-paste (probability)
        self.args.exist_ok = True  # If the project directory already exists, resume from last completed iteration.
        self.tune_dir = get_save_dir(self.args, name='tune')
        self.tune_csv = self.tune_dir / 'tune_results.csv'
        self.callbacks = _callbacks or callbacks.get_default_callbacks()
        self.prefix = colorstr('Tuner: ')
        callbacks.add_integration_callbacks(self)
        LOGGER.info(f"{self.prefix}Initialized Tuner instance with 'tune_dir={self.tune_dir}'\n"
                    f'{self.prefix}💡 Learn about tuning at https://docs.ultralytics.com/guides/hyperparameter-tuning')

    def _mutate(self, parent='single', n=5, mutation=0.8, sigma=0.2):
        """
        Mutates the hyperparameters based on bounds and scaling factors specified in `self.space`.

        Args:
            parent (str): Parent selection method: 'single' or 'weighted'.
            n (int): Number of parents to consider.
            mutation (float): Probability of a parameter mutation in any given iteration.
            sigma (float): Standard deviation for Gaussian random number generator.

        Returns:
            (dict): A dictionary containing mutated hyperparameters.
        """
        if self.tune_csv.exists():  # if CSV file exists: select best hyps and mutate
            # Select parent(s)
            x = np.loadtxt(self.tune_csv, ndmin=2, delimiter=',', skiprows=1)
            fitness = x[:, 0]  # first column
            n = min(n, len(x))  # number of previous results to consider
            x = x[np.argsort(-fitness)][:n]  # top n mutations
            w = x[:, 0] - x[:, 0].min() + 1E-6  # weights (sum > 0)
            if parent == 'single' or len(x) == 1:
                # x = x[random.randint(0, n - 1)]  # random selection
                x = x[random.choices(range(n), weights=w)[0]]  # weighted selection
            elif parent == 'weighted':
                x = (x * w.reshape(n, 1)).sum(0) / w.sum()  # weighted combination

            # Mutate
            r = np.random  # method
            r.seed(int(time.time()))
            g = np.array([v[2] if len(v) == 3 else 1.0 for k, v in self.space.items()])  # gains 0-1
            ng = len(self.space)
            v = np.ones(ng)
            while all(v == 1):  # mutate until a change occurs (prevent duplicates)
                v = (g * (r.random(ng) < mutation) * r.randn(ng) * r.random() * sigma + 1).clip(0.3, 3.0)
            hyp = {k: float(x[i + 1] * v[i]) for i, k in enumerate(self.space.keys())}
        else:
            hyp = {k: getattr(self.args, k) for k in self.space.keys()}

        # Constrain to limits
        for k, v in self.space.items():
            hyp[k] = max(hyp[k], v[0])  # lower limit
            hyp[k] = min(hyp[k], v[1])  # upper limit
            hyp[k] = round(hyp[k], 5)  # significant digits

        return hyp

    def __call__(self, model=None, iterations=10, cleanup=True):
        """
        Executes the hyperparameter evolution process when the Tuner instance is called.

        This method iterates through the number of iterations, performing the following steps in each iteration:
        1. Load the existing hyperparameters or initialize new ones.
        2. Mutate the hyperparameters using the `mutate` method.
        3. Train a YOLO model with the mutated hyperparameters.
        4. Log the fitness score and mutated hyperparameters to a CSV file.

        Args:
           model (Model): A pre-initialized YOLO model to be used for training.
           iterations (int): The number of generations to run the evolution for.
           cleanup (bool): Whether to delete iteration weights to reduce storage space used during tuning.

        Note:
           The method utilizes the `self.tune_csv` Path object to read and log hyperparameters and fitness scores.
           Ensure this path is set correctly in the Tuner instance.
        """

        starting_iter = 0
        if self.tune_csv.exists():
            x = np.loadtxt(self.tune_csv, ndmin=2, delimiter=',', skiprows=1)
            starting_iter = x.shape[0]
            LOGGER.info(
                f'{self.prefix}Resuming hyperparameter tuning at {self.tune_dir} from iteration {starting_iter+1}')

        t0 = time.time()
        best_save_dir, best_metrics = None, None
        (self.tune_dir / 'weights').mkdir(parents=True, exist_ok=True)
        for i in range(starting_iter, iterations):
            # Mutate hyperparameters
            mutated_hyp = self._mutate()
            LOGGER.info(f'{self.prefix}Starting iteration {i + 1}/{iterations} with hyperparameters: {mutated_hyp}')

            metrics = {}
            train_args = {**vars(self.args), **mutated_hyp}
            save_dir = get_save_dir(get_cfg(train_args))
            weights_dir = save_dir / 'weights'
            ckpt_file = weights_dir / ('best.pt' if (weights_dir / 'best.pt').exists() else 'last.pt')
            try:
                # Train YOLO model with mutated hyperparameters (run in subprocess to avoid dataloader hang)
                cmd = ['yolo', 'train', *(f'{k}={v}' for k, v in train_args.items())]
                return_code = subprocess.run(cmd, check=True).returncode
                metrics = torch.load(ckpt_file)['train_metrics']
                assert return_code == 0, 'training failed'

            except Exception as e:
                LOGGER.warning(f'WARNING ❌️ training failure for hyperparameter tuning iteration {i + 1}\n{e}')

            # Save results and mutated_hyp to CSV
            fitness = metrics.get('fitness', 0.0)
            log_row = [round(fitness, 5)] + [mutated_hyp[k] for k in self.space.keys()]
            headers = '' if self.tune_csv.exists() else (','.join(['fitness'] + list(self.space.keys())) + '\n')
            with open(self.tune_csv, 'a') as f:
                f.write(headers + ','.join(map(str, log_row)) + '\n')

            # Get best results
            x = np.loadtxt(self.tune_csv, ndmin=2, delimiter=',', skiprows=1)
            fitness = x[:, 0]  # first column
            best_idx = fitness.argmax()
            best_is_current = best_idx == i
            if best_is_current:
                best_save_dir = save_dir
                best_metrics = {k: round(v, 5) for k, v in metrics.items()}
                for ckpt in weights_dir.glob('*.pt'):
                    shutil.copy2(ckpt, self.tune_dir / 'weights')
            elif cleanup:
                shutil.rmtree(ckpt_file.parent)  # remove iteration weights/ dir to reduce storage space

            # Plot tune results
            plot_tune_results(self.tune_csv)

            # Save and print tune results
            header = (f'{self.prefix}{i + 1}/{iterations} iterations complete ✅ ({time.time() - t0:.2f}s)\n'
                      f'{self.prefix}Results saved to {colorstr("bold", self.tune_dir)}\n'
                      f'{self.prefix}Best fitness={fitness[best_idx]} observed at iteration {best_idx + 1}\n'
                      f'{self.prefix}Best fitness metrics are {best_metrics}\n'
                      f'{self.prefix}Best fitness model is {best_save_dir}\n'
                      f'{self.prefix}Best fitness hyperparameters are printed below.\n')
            LOGGER.info('\n' + header)
            data = {k: float(x[best_idx, i + 1]) for i, k in enumerate(self.space.keys())}
            yaml_save(self.tune_dir / 'best_hyperparameters.yaml',
                      data=data,
                      header=remove_colorstr(header.replace(self.prefix, '# ')) + '\n')
            yaml_print(self.tune_dir / 'best_hyperparameters.yaml')`

Example use : 
`from ultralytics import YOLO

# Initialize the YOLO model
model = YOLO("yolo11n.pt")

# Tune hyperparameters on COCO8 for 30 epochs
model.tune(data="tuner.yaml", epochs=30, iterations=21, optimizer="auto", plots=True, save=True, val=False,device=0,batch=64,exist_ok=True)`

if you want to continue tuning even after finishing the iterations . just make the iterations value more than the previous iterations ie if the iterations=20 is done to continue start the iterations from iterations=21 then the program will run for 21-20 =1 iteration

**Comment by glenn-jocher** [comment]
Thank you for your input. While we appreciate the enthusiasm, we recommend avoiding manual modifications to the core `tuner.py` file as it may lead to maintenance challenges and conflicts with future updates. Instead, we are actively working on enhancing the resume functionality natively within the project. Please keep an eye on the repository for official updates. Let us know if you encounter any specific issues!

**Pull request closed without merging**
