### PR TITLE
Update color branding

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher @pderrenger 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
No code changes in this PR.

### 📊 Key Changes
- No changes have been made as the diff is empty.

### 🎯 Purpose & Impact
- Since there are no changes, this PR has no direct impact on the software or its users. 🛑

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar thanks for the PR! I can't tell what this looks like, can you show some before and after images here?

**Comment by RizwanMunawar** [comment]
> @RizwanMunawar thanks for the PR! I can't tell what this looks like, can you show some before and after images here?

@glenn-jocher sure. Some colors do require a text background color black in new branding, so I added a check for this :)

| Old Branding | New Branding |
|:------------------:|:----------------:|
| Old Branding | New Branding |

**Comment by glenn-jocher** [comment]
@RizwanMunawar doesn't the black here need to be updated to dark blue based on @pderrenger 's guidance from Humbleteam?

**Comment by RizwanMunawar** [comment]
> @RizwanMunawar doesn't the black here need to be updated to dark blue based on @pderrenger 's guidance from Humbleteam?

@glenn-jocher updated to dark blue. Thank you!!!

**Comment by RizwanMunawar** [comment]
@glenn-jocher Final changes results :)

| Old Branding | New Branding |
|:------------------:|:----------------:|
| Old Branding | New Branding |

**Comment by glenn-jocher** [comment]
@sergiuwaxmann hey FYI we need to coordinate a change here for the updated box color palette. This PR is doing this in YOLO (few changes still needed), but we also want to do this in HUB at the same time. @pderrenger has the 20-color palette for the bounding boxes and also for the font colors (dark font for light colors and light font for dark colors).

**Comment by sergiuwaxmann** [comment]
@glenn-jocher Cool, thanks!
I will update you when I have this ready in [Ultralytics HUB](https://hub.ultralytics.com) (probably tomorrow).

**Comment by sergiuwaxmann** [comment]
@glenn-jocher @RizwanMunawar 
The PR for HUB Web is ready.

However, I want to point out that the super light colors don't work well in HUB Web (see example below)...
color_light

**Pull request closed without merging**
