### PR TITLE
[WIP] Add solutions to CLI

### PR DESCRIPTION
**Pull request by AyushExel**
- Mapped all the solutions functions to cli `yolo solutions {name}` as directed by @RizwanMunawar 
- @glenn-jocher might have other opinions on naming the solutions
- @RizwanMunawar the solutions don't do anything out of the box. A window pops up and disappears. I think we need to set more inputs or something? Please take a look

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing a straightforward way to run AI solutions in Ultralytics projects!

### 📊 Key Changes
- Added a new function `handle_solutions` to easily run different AI solutions.
- This function maps specific solutions (`workout`, `count`, `heatmap`, `speed-estimate`, `distance-calculator`) to their respective Python scripts.
- Included error handling for invalid solution inputs, ensuring users are guided to proper usage.

### 🎯 Purpose & Impact
- **Simplifies Execution:** Users can now run various AI solutions directly, making it more accessible to apply Ultralytics AI to real-world problems. 🌍
- **Ensures Flexibility and Guidance:** Offers a clear, flexible way to explore Ultralytics' capabilities, with error guidance for smoother user experiences. 🔄
- **Potential for Expansion:** This structure allows easy addition of more AI solutions in the future, expanding the toolkit available to users. 🚀

This update makes diving into Ultralytics AI solutions more intuitive and efficient, promising a better user journey through direct, simplified interactions with diverse AI functionalities.

### CODE REVIEW

**Comment by RizwanMunawar** [comment]
@AyushExel thanks :)

I think we will need to update the internal functions first, at the moment CLI linkage directly might not be possible!

**Comment by AyushExel** [comment]
okay got it! you can push changes to this branch itself if you want

**Comment by RizwanMunawar** [comment]
@AyushExel got it! Yes that's a good idea, let keep this PR open so we can both work and review things?

**Comment by glenn-jocher** [comment]
@AyushExel @RizwanMunawar guys this won't make it in tonight, but I'll leave it open for future updates :)

**Comment by RizwanMunawar** [comment]
@glenn-jocher Yes it will take sometime as I need to update some code modules in solution directory :)

**Pull request closed without merging**
