### PR TITLE
`ultralytics 8.0.54` TFLite export improvements and fixes

### LINKED ISSUE #1406: improved yolov8 model
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I made some changes on original yolov8s.yaml file. I added attention model.  How will I train this model by using pretrained coco yolov8s.pt file. can yolov8 transfer same layers' weights 

### Additional

_No response_

### LINKED ISSUE #1451: AutoBatch on nano fails memory allocation after a few epochs
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

[Output.txt](https://github.com/ultralytics/ultralytics/files/10986579/Output.txt)

AutoBatch: Computing optimal batch size for imgsz=480
AutoBatch: CUDA:0 (NVIDIA GeForce RTX 4090) 23.99G total, 0.22G reserved, 0.05G allocated, 23.71G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
     3011043       4.609         0.285         76.89         15.98        (1, 3, 480, 480)                    list
     3011043       9.218         0.445         17.64         12.85        (2, 3, 480, 480)                    list
     3011043       18.44         0.470         18.99         14.43        (4, 3, 480, 480)                    list
     3011043       36.87         0.719         21.39          16.5        (8, 3, 480, 480)                    list
     3011043       73.75         1.197         20.45         17.97       (16, 3, 480, 480)                    list
AutoBatch: Using batch-size 281 for CUDA:0 16.87G/23.99G (70%) ✅

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/2 [00:33<?, ?it/s]

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 2.41 GiB (GPU 0; 23.99 GiB total capacity; 17.92 GiB already allocated; 0 bytes free; 21.17 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

### Environment

Ultralytics YOLOv8.0.53 🚀 Python-3.8.10 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 4090, 24564MiB)
WSL2 Ubuntu 20.04.6 LTS
Torch '2.0.0+cu117'
Tensorflow '2.11.0'

### Minimal Reproducible Example

!yolo task=detect mode=train model=yolov8n.pt imgsz=480 data=v8.yaml epochs=100 batch=-1 patience = 20 name=runs/detect/result_1

### Additional

It seems the auto batch is flying too close to the sun, and while it starts off ok after 2-4 epochs it gives a memory allocation error. Scaling back the batch size will allow it to train. I've only seen this with the nano model, i guess a the smaller size generally allows for a more finely tuned batch size.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #1459: WARNING  TensorBoard not initialized correctly, not logging this run. 'NoneType' object is not callable
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

WARNING  TensorBoard not initialized correctly, not logging this run. 'NoneType' object is not callable

### Environment

Ultralytics YOLOv8.0.53  Python-3.9.12 torch-2.1.0.dev20230315+cu118 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 8192MiB)

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
PR introduces multiple enhancements and bug fixes to the Ultralytics codebase, primarily focusing on string quoting style and loading pretrained models.

### 📊 Key Changes
- 📑 Standardization of string quoting within the codebase (double quotes changed to single quotes).
- 🔄 Additional functionality to load a pre-trained model using a YAML configuration file and transfer weights.
- 🧹 Refactored code and enforced consistency across all documentation and examples.
- 🔍 Minor bug fixes and refactoring in the core library to improve functionality and readability.
- 🧠 Improvements to the model training process, including the ability to load pre-trained weights and rebuild a model from YAML configuration.
- ✨ Updated version number of the `ultralytics` package.

### 🎯 Purpose & Impact
- 🔗 The standardization of string quotes to single quotes enhances the uniformity of the code.
- 🚀 Enhancements to model loading allow users to more easily leverage pre-trained weights, which can accelerate the development and training of models.
- 👓 Clear and consistent documentation improves ease of use and understanding for new users and developers.
- 🐞 Bug fixes and refactoring improve the stability and efficiency of the code, leading to a smoother user experience.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel here's the new syntax for creating a new custom model and transferring weights:


Screenshot 2023-03-16 at 13 15 07


Screenshot 2023-03-16 at 13 15 11

**Comment by hamedgorji** [comment]
After the following update ```ultralytics 8.0.54 TFLite export improvements and fixes#1447 ```
` !yolo export model=yolov8n.pt format=edgetpu` doesn't export edgetpu.
https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb#scrollTo=CYIjW4igCjqD

**Comment by glenn-jocher** [comment]
@hamedgorji CI for EdgeTPU export is working correctly (as always, no change in 8.0.54). If this step were to fail our entire CI fails and you'd see red CI notices on the main README.
https://github.com/ultralytics/ultralytics/actions/runs/4448538240/jobs/7811480673?pr=1347
Screenshot 2023-03-17 at 15 38 21

**Comment by hamedgorji** [comment]
@glenn-jocher I've tested your google colab right now, and it's working fine (Yesterday, I got an error). Thanks

**Comment by hamedgorji** [comment]
@glenn-jocher Hi Glenn,
I am still trying to solve the issue, and I asked a question on the `onnx2tf` GitHub page, and he answered my question. 
[https://github.com/PINTO0309/onnx2tf/issues/263](url)
Would it be possible to make some modifications to the exporting process based on what is suggested there?

**Comment by glenn-jocher** [comment]
@hamedgorji great! Yes please submit a PR with any recommended changes and we will review there. All export code is in exporter.py:
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/exporter.py

**Comment by hamedgorji** [comment]
@glenn-jocher  based on the discussion here [https://github.com/ultralytics/ultralytics/issues/1185](url), one possible solution could be using a different activation function during training. I checked the yolov8 codes, and `SiLu` is used as the default activation function. If we could select the activation function like the optimizer, I can train my model using, for example, ReLU and report the results. 
I would appreciate it if we could have something like the following for the activation function
`optimizer: SGD  # optimizer to use, choices=['SGD', 'Adam', 'AdamW', 'RMSProp']`

`Activation: SiLU  # Activation to use, choices=['SiLU', 'ReLU', ...]`

**Comment by glenn-jocher** [comment]
@hamedgorji @mikel-brostrom yes, you can do this by defining an activation fiend in your model YAML, i.e. default is:
```yaml
activation: nn.SiLU()
```

This feature is still experimental.

**Comment by hamedgorji** [comment]
@glenn-jocher I use `yolov8n.yaml` you mean add `activation: nn.ReLU()` in this yaml?
```

# Ultralytics YOLO 🚀, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # scales module repeats
width_multiple: 0.25  # scales convolution channels

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]]  # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]]  # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]]  # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]]  # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]]  # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]]  # 9

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 6], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 12

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 4], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 15 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 18 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 21 (P5/32-large)

  - [[15, 18, 21], 1, Detect, [nc]]  # Detect(P3, P4, P5)

```

**Comment by hamedgorji** [comment]
@glenn-jocher great, I will add it, and I want to train my model from scratch `model = YOLO("yolov8n.yaml")`. 

```
# Ultralytics YOLO 🚀, GPL-3.0 license

# Parameters
nc: 80  # number of classes
depth_multiple: 0.33  # scales module repeats
width_multiple: 0.25  # scales convolution channels
activation: nn.ReLU()
```

**Comment by glenn-jocher** [comment]
@hamedgorji then yeah that code looks good!

**Comment by 35grain** [comment]
@hamedgorji definitely let us know how it works out for you!

**Comment by hamedgorji** [comment]
@35grain Unfortunately didn't work

**Comment by mikel-brostrom** [comment]
Could you give more details @hamedgorji? Only changing the activation, retraining and exporting dind't work? What error did you get?

**Comment by hamedgorji** [comment]
@mikel-brostrom I changed the activation function to `ReLU`, and everything was almost the same as `SiLU`, (I got a bit better result using `ReLU`). I never got an error, I can always convert the model to edgetpu, but the problem is the model cannot detect anything. Even one step before converting to edgetpu` (best-ReLU_full_integer_quant.tflite)` doesn't detect anything too.

**Comment by mikel-brostrom** [comment]
I see. Could you share your TFLite model here?

**Comment by mikel-brostrom** [comment]
Ok, basically the exact same issues as with YOLOX

**Comment by hamedgorji** [comment]
You are right. I've checked another model that works fine on edgetpu. It doesn't have sigmoid.
How can we solve it?
[test_edgetpu.zip](https://github.com/ultralytics/ultralytics/files/11064214/test_edgetpu.zip)

**Comment by mikel-brostrom** [comment]
The most realistic solution I can think of at the moment is to compute it outside the model

**Comment by motokimura** [comment]
Hi @glenn-jocher 

I’m concerned the incorrect calibration setting causes the accuracy degradation of static quantized YOLOv8 model.
In the current implementation, it seems that images normalized with ImageNet mean and std are used for YOLOv8 quantization. Is this intended?

As I posted [here](https://github.com/PINTO0309/onnx2tf/issues/269#issuecomment-1484849556), the images normalized with ImageNet mean and std are used for the calibration since onnx2tf’s `-qcind` option is not specified [here](https://github.com/ultralytics/ultralytics/blob/ec10002a4ade5a43abb9d5765f77eefddf98904b/ultralytics/yolo/engine/exporter.py#L527-L529).

If YOLOv8 doesn’t expect such normalized images as the input, we need to generate calibration data with an appropriate input normalization and pass it to onnx2tf through `-qcind` option.

Please correct me if there is any misunderstanding because I’m not so familiar with the input pre-processing logic used in YOLOv8.

**Comment by glenn-jocher** [comment]
@motokimura thanks for investigating this! 

**YOLOv8 does not apply ImageNet mean and normalization to any tasks/model, not even Classification models.** The only preprocessing that is involved is changing uint8 inputs 0-255 to float by dividing by 255, reducing the input range from 0-1.

**Comment by motokimura** [comment]
@glenn-jocher thanks for your reply.
I'll further investigate this and post the result here.

**Comment by hamedgorji** [comment]
Just an update.
I trained the model with `ReLU6`; as before, just the dynamic range format works `(best-relu6_dynamic_range_quant_edgetpu.tflite)`. 
I still couldn't figure out why the `full_integer_quant ` doesn't work.

**Comment by motokimura** [comment]
I created a PR https://github.com/ultralytics/ultralytics/pull/1695 to solve the problem that YOLOv8n integer models detect nothing. I hope this helps you.

**Comment by glenn-jocher** [comment]
Thank you for submitting the PR! Our team will review it as soon as possible and provide feedback or merge the changes if everything looks good. We appreciate your contribution and efforts towards improving YOLOv8n. If you have any other suggestions or improvements, feel free to create new feature requests or issues on our GitHub page. Thanks again!

**Comment by hamedgorji** [comment]
> I created a PR #1695 to solve the problem that YOLOv8n integer models detect nothing. I hope this helps you.

Great, thank you so much. That would be a great help.

**Comment by glenn-jocher** [comment]
@hamedgorji thank you for your contribution! We appreciate your effort in helping improve our software. I'll take a look at the PR and give it a review as soon as possible. If there are any issues or suggestions, I'll let you know. Thanks again for your support!

**Pull request merged**
