### PR TITLE
Fix increment `+=2` bug in object_counter.py

### PR DESCRIPTION
**Pull request by mianusman618**
In case of count by "line points" its adding 2 in counter by each passing object instead of adding 1 in value. Updated to resolve the issue. Issue raised on docs page as well. Video Reference for false output:- https://bit.ly/obj_count_wrong

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced accuracy in object counting within counting regions.

### 📊 Key Changes
- Corrected the increment of `in` count in the class-wise count from 2 to 1 for object tracking.

### 🎯 Purpose & Impact
- **Purpose:** This change aims to fix an error in the counting logic where objects entering a specified region were being counted twice instead of just once. By adjusting the increment from 2 to 1, the counting now accurately reflects the number of objects entering the region.
- **Impact:** Users deploying object counting solutions will experience more precise and reliable count metrics, leading to improved analytics and decision-making based on the count data. This can significantly enhance the utility of applications in various sectors, including retail, transportation, and surveillance, by providing more accurate people or object flow statistics. 📈

### CODE REVIEW

**Comment by mianusman618** [comment]
I have read the CLA Document and I sign the CLA

**Comment by mianusman618** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@RizwanMunawar is this PR good to merge?

**Review by RizwanMunawar — APPROVED** [review]
@mianusman618 Thanks for fixing the minor bug :)

@glenn-jocher yes, we can merge this PR :)

Thanks

**Comment by mianusman618** [comment]
Thank you for acknowledging the bug fix!! Contributing to such a valuable resource is truly satisfactory.
Really appreciate the outstanding efforts made to make YOLO simpler for everyone. Kudos to @glenn-jocher and team.

**Comment by glenn-jocher** [comment]
Thank you so much for your kind words and contribution! 🙌 It's wonderful to have such supportive and engaged community members. Your efforts help us all move forward together. Keep up the great work! 👍

**Comment by glenn-jocher** [comment]
@mianusman618 PR merged, thank you for this fix and please let us know if you spot any other problems :)

**Pull request merged**
