### PR TITLE
Bugfix: Changed the order of sigmoid binarization and upsampling to achieve better segmentation edges.

### PR DESCRIPTION
**Pull request by zxDeepDiver**
…moother segmentation edges.

We  made this correction and found that the segmentation edges are better.

Here is the FastSAM' results:

Before:
image

After the change:
image

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR modifies the mask processing functions to remove the `sigmoid` activation and adjusts the mask threshold comparison.

### 📊 Key Changes
- Removed the `.sigmoid()` activation from mask processing functions.
- Changed mask threshold comparison from `.gt_(0.5)` to `.gt_(0)`.

### 🎯 Purpose & Impact
- **Simplified Processing**: By removing the sigmoid, the code becomes simpler and potentially faster as it omits an unnecessary operation.
- **Adjusting Mask Logic**: Changing the threshold might affect how masks are generated, potentially making them more inclusive or less filtered. Users may see changes in the output masks from their models, which could impact the performance and accuracy of object detection tasks.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@zxDeepDiver wow this looks a lot better! What are the impacts on mAP?

Also please submit a new comment for the CLA bot with this:

I have read the CLA Document and I sign the CLA

**Comment by zxDeepDiver** [comment]
Due to computational power issues, we have not yet observed mAP, but theoretically, it should have little impact.

**Comment by zxDeepDiver** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@zxDeepDiver does this cover high resolution masks with `retina_masks`=True?
https://github.com/ultralytics/ultralytics/blob/e30b7c24f22b98dcf30ca5d23871659f861acadd/ultralytics/cfg/default.yaml#L64

**Comment by zxDeepDiver** [comment]
Yes,  as in
https://github.com/ultralytics/ultralytics/blob/f5c0395a0577f4a4f35bc53124a2262d1b96d41b/ultralytics/models/yolo/segment/predict.py#L50C28-L50C40

if retina_mask=True, process_mask_native is called. 

The process_mask_native function is included in this pull request.

> @zxDeepDiver does this cover high resolution masks with `retina_masks`=True?
> 
> https://github.com/ultralytics/ultralytics/blob/e30b7c24f22b98dcf30ca5d23871659f861acadd/ultralytics/cfg/default.yaml#L64

**Comment by glenn-jocher** [comment]
@zxDeepDiver awesome! Merged into local branch to test on our server.

**Pull request merged**
