### PR TITLE
[Example] YOLOv8-ONNXRuntime

### PR DESCRIPTION
**Pull request by semihhdemirel**
### Summary
🚀📝📸

This pull request adds a new project to the examples folder: `YOLOv8-ONNXRuntime`. This project demonstrates how to use ONNX Runtime to run object detection with a YOLOv8 model. It includes a `main.py` file that contains the detection code and a `README.md` file that explains the project and its usage.

> _`YOLOv8` detects_
> _Objects with `ONNX Runtime`_
> _Readme guides users_

### Walkthrough
*  Implement object detection using YOLOv8 ONNX model and ONNX Runtime ([link](https://github.com/ultralytics/ultralytics/pull/2992/files?diff=unified&w=0#diff-ad6e812b8c8c788acce898aa5146a63b452f7b9875528d9db7fb1a689264cd94L1-R224))
* Document the project and provide usage examples ([link](https://github.com/ultralytics/ultralytics/pull/2992/files?diff=unified&w=0#diff-b2490b79616547ec61b4c6276989424900cb90a6bde750a748344df8a23de00cR1-R44))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of YOLOv8 ONNX Runtime for Python.

### 📊 Key Changes
- Added a new example demonstrating the use of YOLOv8 with ONNX Runtime in Python.
- Included instructions for setting up the environment and required dependencies for both GPU and CPU users.
- Provided a script (`main.py`) that performs object detection using the YOLOv8 ONNX model and visualizes the results.

### 🎯 Purpose & Impact
- 🚀 Enhances the accessibility of YOLOv8 for developers by enabling inference with ONNX Runtime, which can optimize model performance across a variety of platforms.
- 🧠 Offers users flexibility with both GPU and CPU options, catering to those with different hardware capabilities.
- 💡 Facilitates easier prototyping and deployment by providing a straightforward example that can be built upon for custom applications.

### CODE REVIEW

**Comment by AyushExel** [comment]
Thanks for the contribution, looks great!
Can you also add your contribution to the table in `Examples/README.md` ? Thanks!

**Comment by semihhdemirel** [comment]
I added my contribution to the table. Thank you.

**Comment by AyushExel** [comment]
@glenn-jocher This is good to go!

**Comment by glenn-jocher** [comment]
@semihhdemirel thank you for your ONNXRuntime example!

**Comment by semihhdemirel** [comment]
@glenn-jocher Thank you.

**Comment by glenn-jocher** [comment]
@semihhdemirel you're welcome! Let us know if you have any further questions or need any help with YOLOv8. We're always here to assist you.

**Pull request merged**
