### PR TITLE
Fix MPS float64 issue

### PR DESCRIPTION
**Pull request by wilsonlmh**
This one line fix issue like #246 . Similar changes found in #1512 for other files. Maybe it'll be some more similar fixes we can apply to fix this float64 unsupported issue in other places. Feel free to append/edit.

### Summary
🔧🚀📦

Fix data type mismatch for bounding box tensors in mixed precision training. Use `dtype` argument to convert `batch['bboxes']` to the same type as other tensors in `ultralytics/yolo/v8/detect/train.py`.

> _`batch['bboxes']` cast_
> _to match other tensors - kire_
> _mixed precision training_

### Walkthrough
*  Enable mixed precision training using `torch.cuda.amp` module (F0L

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR appears to be an empty or placeholder pull request with no actual code changes included.

### 📊 Key Changes
- No code changes are present in the PR.

### 🎯 Purpose & Impact
- Since there are no changes, there is no direct impact or benefits resulting from this PR.
- It's possible this PR was opened by mistake, or it might be a preliminary setup for future code contributions.

💡 Given there's no content in the PR, it's recommended to check with the author for clarification or wait for updates if it's expected to be populated with code changes later on.

### CODE REVIEW

**Comment by wilsonlmh** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@wilsonlmh thanks for the PR! Do you know where these float64 values are originating from? As far as I know there should be no float64 ops in any part of YOLO. If we could track down the source maybe we could fix it there?

**Comment by wilsonlmh** [comment]
> @wilsonlmh thanks for the PR! Do you know where these float64 values are originating from? As far as I know there should be no float64 ops in any part of YOLO. If we could track down the source maybe we could fix it there?

Oh I'm very new to machine learning, I almost only know how to power on my computer haha. So I have no idea on the root cause. I was just searching around #1512 and found the similarity and try to apply it blindly and it works! I got successfully trained model using MPS with this patch.

My command is:
`yolo task=detect mode=train model=yolov8n.pt data=<something>/data.yaml epochs=100 imgsz=416 plots=True`

My Mac is Macbook Air M1 8GB 7-core model.

**Comment by glenn-jocher** [comment]
@wilsonlmh ok @Laughing-q has traced the source of the issue to some numpy functions creating float64, and we've solved the bug at the source of the problem now in https://github.com/ultralytics/ultralytics/pull/1956

**Pull request merged**
