### PR TITLE
Search for model metadata with TensorFlow GraphDef

### PR DESCRIPTION
**Pull request by Burhan-Q**
When using TensorFlow GraphDef `.pb` model with `AutoBackend` there was no attempt to load the metadata YAML from the `saved_model` directory. Adds attempt to find metadata file, assuming the `.pb` file is in the same directory as the `saved_model` directory. If not found, passes silently.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated metadata handling for TensorFlow GraphDef models in autobackend.

### 📊 Key Changes
- Added a mechanism to try retrieving metadata from a possible SavedModel file alongside the GraphDef file.
- Enhanced metadata processing to confirm metadata is a dictionary before using it.
- Improved the logic for handling segment tasks and undefined names in GraphDef models.

### 🎯 Purpose & Impact
- **Metadata Retrieval**: Enhances the ability to gather supplementary model information, leading to more informed processing.
- **Robustness**: Ensures that only valid metadata is used, preventing potential issues from incorrect data types.
- **Flexibility in Model Handling**: Allows more seamless handling of segment tasks, improving user experience for specific TensorFlow models.

Overall, these changes improve the robustness and flexibility of working with TensorFlow GraphDef models, providing a smoother and more reliable user experience. 🚀

### CODE REVIEW

**Comment by Burhan-Q** [comment]
- [ ] TODO resolve issue with segmentation model

<details><summary>CI Benchmark error</summary>
<p>

```
TensorFlow GraphDef: starting export with tensorflow 2.16.1...
TensorFlow GraphDef: export success ✅ 3.9s, saved as 'path with spaces/yolov8n-seg.pb' (13.1 MB)

Export complete (31.4s)
Results saved to /home/runner/work/ultralytics/ultralytics/path with spaces
Predict:         yolo predict task=segment model=path with spaces/yolov8n-seg.pb imgsz=160  data=coco.yaml
Validate:        yolo val task=segment model=path with spaces/yolov8n-seg.pb imgsz=160 data=coco.yaml  
Visualize:       https://netron.app/
Loading path with spaces/yolov8n-seg.pb for TensorFlow GraphDef inference...

Traceback (most recent call last):
  File "/home/runner/work/ultralytics/ultralytics/ultralytics/utils/benchmarks.py", line 126, in benchmark
    exported_model.predict(ASSETS / "bus.jpg", imgsz=imgsz, device=device, half=half)
  File "/home/runner/work/ultralytics/ultralytics/ultralytics/engine/model.py", line 453, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
                                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ultralytics/ultralytics/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/runner/work/ultralytics/ultralytics/ultralytics/engine/predictor.py", line 255, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ultralytics/ultralytics/ultralytics/models/yolo/segment/predict.py", line 30, in postprocess
    p = ops.non_max_suppression(
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/ultralytics/ultralytics/ultralytics/utils/ops.py", line [235](https://github.com/ultralytics/ultralytics/actions/runs/9387491195/job/25850532202?pr=13389#step:8:236), in non_max_suppression
    output = [torch.zeros((0, 6 + nm), device=prediction.device)] * bs
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to create tensor with negative dimension -882: [0, -882]
```

</p>
</details>

**Comment by Burhan-Q** [comment]
Not sure if it would make sense to update docs to show that Metadata is supported since I assume that it's possible the `pb` file could be moved

**Comment by Burhan-Q** [comment]
macos-14 + python-3.11 ✔️ [passes all GraphDef benchmarks](https://github.com/ultralytics/ultralytics/actions/runs/9387491195/job/25852380443?pr=13389#step:8:227)
ubuntu-latest + python-3.11 ❌ [failing at GraphDef `val` benchmark](https://github.com/ultralytics/ultralytics/actions/runs/9387491195/job/25864204316#step:8:225)

Might be related to #13390

**Comment by Burhan-Q** [comment]
More evidence pointing to this being OS based. Issue observed on `Ubuntu 22.04.3 LTS` (Ultralytics $\lambda$ server) but **not** on `Pop!_OS 22.04 LTS`

```
Operating System: Ubuntu 22.04.3 LTS              
Kernel: Linux 5.15.0-91-generic
Architecture: x86-64

Operating System: Pop!_OS 22.04 LTS               
Kernel: Linux 6.6.10-76060610-generic
Architecture: x86-64
```

**Comment by glenn-jocher** [comment]
@Burhan-Q PR merged, nice work!

**Pull request merged**
