### PR TITLE
[Example] YOLOv8-OpenCV-ONNX-Python

### PR DESCRIPTION
**Pull request by frdteknikelektro**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Ultralytics adds Python support for YOLOv8 with OpenCV ONNX inference.

### 📊 Key Changes
- Added a new example: YOLOv8 OpenCV ONNX Python integration.
- Provided scripts for installing dependencies and running YOLOv8 ONNX models.
- Included Python code (`main.py`) demonstrating how to perform image inference using YOLOv8 model and OpenCV.

### 🎯 Purpose & Impact
- 🎨 Expands the accessibility of YOLOv8 to Python users preferring OpenCV for image processing.
- 🚀 Enables developers to easily deploy YOLOv8 models in OpenCV environments, streamlining the path from model training to practical application.
- 📈 Potentially increases the adoption of YOLOv8 by offering straightforward integration with popular OpenCV library.

### CODE REVIEW

**Comment by AyushExel** [comment]
thanks. Please sign the CLA

**Comment by frdteknikelektro** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@frdteknikelektro we already have bus.jpg in ultralytics/yolo/assets/bus.jpg

**Comment by frdteknikelektro** [comment]
Deleted

**Comment by glenn-jocher** [comment]
@frdteknikelektro thanks for the update! We also already have class names in coco.yaml and cooc128.yaml. These can be read like this. Can you please delete the class names txt file you have and load the existing class names from a yaml? You can read the yamls like this:

```python
file = 'coco128.yaml'
with open(file, errors='ignore', encoding='utf-8') as f:
        classes = yaml.safe_load(f.read())['names']
```

**Comment by glenn-jocher** [comment]
@frdteknikelektro see https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/data/datasets/coco128.yaml for example

https://github.com/ultralytics/ultralytics/blob/e799592718b6fc5b0dc26dd99dbdc61b6ac98c0d/ultralytics/yolo/data/datasets/coco128.yaml#L16-L98

**Comment by AyushExel** [comment]
@frdteknikelektro I think once you make these changes, it'll be good to go:
* Use existing class names somewhere from the repo
* remove requirements.txt as opencv-python is already a dependency of ultralytics

**Comment by AyushExel** [comment]
@frdteknikelektro @glenn-jocher removed the classes.txt and requirements.txt and tested the workflow steps. It's working! I'll merge this when tests pass.
We now have Inference examples in these formats:
* ONNX c++
* ONNX python
* ONNX C# .Net

**Comment by binn77** [comment]
When using this example for classification, it incorrectly determines the class number.

Export example.
`yolo export model=best.pt imgsz=128 format=onnx opset=12`

**Comment by AyushExel** [comment]
Should work for detection only currently.

**Comment by frdteknikelektro** [comment]
@AyushExel @glenn-jocher  Thanks . This week a bit busy for me.

Btw anyone know how to implement YOLOv8 for android? or is it not possible yet?
And FYI it seems model onnx converted from YOLOv8 only working latest Python OpenCV (4.7) and need opset=12 option.

**Pull request merged**
