### PR TITLE
`ultralytics 8.3.49` Docker images `uv pip install`

### PR DESCRIPTION
**Pull request by pderrenger**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Updated Dockerfiles to prioritize safe and system-compatible Python packages installation using `uv pip` for enhanced reliability and security. Also incremented version to v8.3.49.

### 📊 Key Changes  
- Replaced `pip install` commands with `uv pip install --system` across multiple Dockerfiles for package management.
- Implemented `uv` tool to better handle Python environment isolation and package installation integrity.
- Adjusted installation flags like `--index-strategy` and added `--break-system-packages` where necessary.
- Incremented software version from `8.3.48` to `8.3.49`.

### 🎯 Purpose & Impact  
- **Enhanced Stability**: `uv pip` ensures safer installations by isolating the environment and mitigating potential dependency conflicts. 🛡️  
- **Improved Compatibility**: System-level installations with proper safeguards reduce errors on diverse setups. 🌍  
- **Infrastructure Upgrade**: Docker containers are now more robust for development and deployment. 🚀  
- **Version Update**: Reflects the changes and upgrades for tracking and transparency. 📈  

Users updating their Docker environments will benefit from safer deployments and improved reliability.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @pderrenger, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a smooth review and integration of your changes, we kindly ask that you review the following checklist:

- ✅ **Describe the Purpose**: Please ensure that your PR description clearly outlines the purpose of your changes and links to any relevant [issues](https://github.com/ultralytics/ultralytics/issues). Provide context on why these changes are necessary and their expected impact.
- ✅ **Sync with Latest Code**: Verify that your branch is up-to-date with the latest `main` branch of this repository. If it's not, please click the 'Update branch' button on GitHub or use the following commands locally:
  ```
  git fetch origin
  git merge origin/main
  ```
- ✅ **Check CI/CD Tests**: Ensure that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) tests are passing. If any issues arise, please review and resolve them to maintain compatibility.
- ✅ **Update Documentation**: Confirm that the relevant [documentation](https://docs.ultralytics.com) pages have been updated to reflect your changes, if applicable.
- ✅ **Include Tests**: If your PR introduces new functionality or modifies existing behavior, please add or update tests to verify that everything works as intended.
- ✅ **Sign the CLA**: If this is your first contribution to Ultralytics, please review and sign our [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/). You can do so by commenting "I have read the CLA Document and I sign the CLA" on this PR.
- ✅ **Minimize Changes**: Keep changes as focused and minimal as possible. Only include what's necessary for the feature or bug fix. As Bruce Lee said, _"Hack away the unessential."_ 😉

We also noticed that your PR involves updates to Dockerfiles and introduces `uv`, a custom pip management system for dependency installations. This is a significant change and may impact existing workflows. To streamline the review:

1. **Confirm Compatibility**: Please provide any details, if available, on compatibility between `uv` and the existing `pip` workflows to ensure that backward compatibility is not compromised.
2. 🐳 **Test Cases**: Did you test these updated Dockerfiles across multiple environments (e.g., CPU vs. GPU, different architectures)? Please share any additional test results to help with validation.

For more contributing guidelines and tips, please see our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you require further assistance or have specific questions, feel free to leave a comment. A member of the Ultralytics team will also review and assist you soon. 😊

Thank you for contributing to Ultralytics and helping us improve! 🚀

**Comment by glenn-jocher** [comment]
@lakshanthad can you test these Jetson dockerfiles to see if they still work?

**Comment by lakshanthad** [comment]
Sure @glenn-jocher. Will get back here after testing.

**Comment by lakshanthad** [comment]
@glenn-jocher I have tested on all JetPack versions. JetPack5 and 6 are all good. However, when I try on JetPack4, the following error is there:

```sh
Step 14/17 : RUN python3 -m pip install --upgrade pip uv
 ---> Running in c071ed461d7f
Collecting pip
  Downloading https://files.pythonhosted.org/packages/ef/7d/500c9ad20238fcfcb4cb9243eede163594d7020ce87bd9610c9e02771876/pip-24.3.1-py3-none-any.whl (1.8MB)
Collecting uv
  Downloading https://files.pythonhosted.org/packages/ca/1c/8c40ec75c26656bec9ada97833a437b49fd443b5d6dfd61d6dda8ad90cbe/uv-0.5.7.tar.gz (2.4MB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ModuleNotFoundError: No module named 'setuptools'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-z7znwiky/uv/
The command '/bin/sh -c python3 -m pip install --upgrade pip uv' returned a non-zero code: 1
```

I have pushed a commit for a workaround where we install `uv` separately. Then the problem is gone and the image gets built. This could be related to maybe JetPack4 image using Python3.8 vs others using Python3.10+.

**Comment by glenn-jocher** [comment]
@lakshanthad awesome! Good fix. Is this good to merge then?

**Comment by glenn-jocher** [comment]
Can you provide an approving review if all good?

**Review by lakshanthad — APPROVED** [review]
Good to go!

**Pull request merged**
