### PR TITLE
Suppress NNPACK and Torch Profiler verbosity

### PR DESCRIPTION
**Pull request by glenn-jocher**
Inspired by https://github.com/ultralytics/yolov5/pull/12989

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved settings and environment configuration for more stable and quiet operation.

### 📊 Key Changes
- Enhanced comments to clarify the introduction of environment variables in settings.
- Added settings to suppress verbose warnings and outputs:
  - For TensorFlow, to minimize compiler warnings.
  - For PyTorch, to prevent "NNPACK could not initialize" warnings.
  - For the PyTorch profiler (Kineto), to reduce verbose output related to computing FLOPs (Floating Point Operations per Second).

### 🎯 Purpose & Impact
- **Smoother User Experience**: Reduces the noise from unnecessary warnings, making it easier for developers and users to focus on relevant information. 🚀
- **Better Performance Insight**: By controlling the verbosity of the PyTorch profiler, users get more digestible and relevant performance metrics. 📉
- **Enhanced Development Environment**: Helps in maintaining a clean console, facilitating easier debugging and cleaner logs for users and developers alike. 🧑‍💻

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q should allow for silent integration of torch profiler.

**Comment by glenn-jocher** [comment]
@inisis I'm doing updates now to `ultralytics` based on your feedback starting with this PR to implement the ENV variable settings and then a future one to experiment with eliminating the `thop` dependency for FLOPs computation and using instead the built-in torch profiler.

**Comment by glenn-jocher** [comment]
@inisis the fixes here appear to be working!

Do you know how we can suppress this output here? This shows up every time in our Colab notebook when training a model:
https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb

I just tested and it's still happening after merging this PR, so the loggers must be different.

Screenshot 2024-05-13 at 04 18 52

**Comment by glenn-jocher** [comment]
@inisis awesome! Yes please could you submit a PR? Thank you!

**Comment by inisis** [comment]
@glenn-jocher https://github.com/ultralytics/ultralytics/pull/12670 maybe we can discuss here

**Comment by glenn-jocher** [comment]
Sure, let's discuss the details of PR #12670 here. If there are specific aspects or changes in the PR that you'd like to address or highlight, please feel free to point them out! Looking forward to your insights. 🚀

**Pull request merged**
