### PR TITLE
TensorRT10 with JetPack 6.0 Docs update

### PR DESCRIPTION
**Pull request by Burhan-Q**
- [x] Adds CLI example for exporting to TensorRT with INT8 quantization (thanks @lakshanthad for raising this)
- [x] Expands python example for exporting TensorRT with INT8 quantization
- [x] Moves classification metrics to appropriate row
- [x] Adds TensorRT 10 and JetPack 6 benchmarks for Jetson Orin NX (@lakshanthad)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to TensorRT Documentation and Performance Updates

### 📊 Key Changes
- **Documentation Update:** Revised and expanded the TensorRT integration guide to include more detailed examples for Python and CLI.
- **Performance Benchmarks:** Updated performance benchmarks for various model precisions (FP32, FP16, INT8) on the NVIDIA Jetson Orin NX 16GB, showcasing improvements in inference times.
- **Enhanced Export Options:** Now explicitly includes steps to export models with dynamic axes and INT8 quantization, plus tips on maximizing batch sizes and memory allocation for better performance.
- **Intuitive Examples:** Added clear examples for exporting a YOLO model to TensorRT format and running inference with the exported model.

### 🎯 Purpose & Impact
- **Smoother TensorRT Integration:** With detailed examples and clear documentation, users can more easily integrate Ultralytics models with NVIDIA's TensorRT for enhanced performance.
- **Improved Inference Speed:** Updated benchmarks demonstrate the efficiency gains possible with the latest software versions, useful for those deploying models on NVIDIA hardware.
- **Flexibility in Model Deployment:** The additional details on model export options give developers better tools for optimizing their models for specific hardware, leading to faster, more efficient AI applications.

These changes aim to streamline the process for developers looking to leverage TensorRT's powerful optimization capabilities with Ultralytics models, ultimately leading to faster AI-driven insights and applications. 🚀

### CODE REVIEW

**Comment by lakshanthad** [comment]
@Burhan-Q JP6.0 with TRT10 benchmarks for Jetson Orin NX are updated!

**Comment by Burhan-Q** [comment]
@lakshanthad I was actually thinking it could be good to keep both results (add a tab for the new version). What do you think tho? Would it be worth showing results for an older + newer version? The difference isn't _that_ big, so probably okay to just use the TensorRT10 numbers.

**Comment by lakshanthad** [comment]
@Burhan-Q I initially had the same idea as yours but the difference isn't that big yes. That is why I just replaced the numbers.

**Comment by glenn-jocher** [comment]
@Burhan-Q @lakshanthad awesome guys, great updates. PR merged!!

**Pull request merged**
