### PR TITLE
Dataset embedding/similarity search

### PR DESCRIPTION
**Pull request by AyushExel**
TODO:
- [ ] Docs
- [x] Reuse existing table via factory method, without overwriting

### Summary
📄🔌🧠

Added a new feature to extract embeddings from different layers of the network using the `AutoBackend` and `BaseModel` classes. Created a new class `EmbeddingsPredictor` and a new file `ultralytics/yolo/data/embedding.py` to use this feature for the YOLO detection task and to generate a table of embeddings for a given model and dataset.

> _Oh we are the coders of the sea, and we work on the `AutoBackend`_
> _We can extract embeddings from any layer, with the `BaseModel` and its pack_
> _Heave away, heave away, on the count of three_
> _We'll build a table of embeddings, with the `EmbeddingsPredictor` class_

### Walkthrough
*  Add `embed_from` argument to `BaseModel.predict` and `AutoBackend.forward` methods to enable embedding extraction from intermediate layers ([link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L295-R295), [link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9R303), [link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L314-R315), [link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L47-R47), [link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R56), [link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L62-R65), [link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L72-R79), [link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L83-R93))
*  Implement `EmbeddingsPredictor` class in `ultralytics/yolo/data/embedding.py` to yield embeddings along with predictions from a `YOLO` model ([link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-753fd8272614885d8075fb8c0fb3333f999b65489dc079211041b22f68bfba28R1-R66))
*  Define helper functions in `ultralytics/yolo/data/embedding.py` to get the train split of a dataset and to build a table of embeddings for a given model and data ([link](https://github.com/ultralytics/ultralytics/pull/3094/files?diff=unified&w=0#diff-753fd8272614885d8075fb8c0fb3333f999b65489dc079211041b22f68bfba28R1-R66))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduction of embedding features for the YOLO Explorer class in Ultralytics.

### 📊 Key Changes
- Excluded `ultralytics/__init__.py` from `isort` import sorting to prevent unintended import reordering.
- Added a new test module `test_lance.py` for `Explorer` class, covering various functionalities like creating, accessing, and manipulating embeddings.
- Updated the package `__init__.py` to include `Explorer` class from `data.embedding`, expanding the available import scope.
- Modified `autobackend.py` and `tasks.py` to allow YOLO models to return embeddings at a specified layer using `embed_from` arguments.
- Added a new `embedding.py` file in `yolo/data` directory, introducing the `Explorer` class for embedding space exploration and manipulation, as well as the `EmbeddingsPredictor` class for embedding generation.

### 🎯 Purpose & Impact
- 🚀 Enables users to generate and explore embedding spaces, facilitating tasks like similarity search and data analysis within datasets.
- 🔍 Provides tools to find similar images in a dataset and reduce data dimensions for visualization and data cleaning.
- 💾 Allows users to persist changes, reset the dataset to its original state, or persist to a new state after modifications, making dataset curation more efficient.
- ✨ With embedding supports, users can more effectively train and fine-tune models on curated datasets, potentially leading to better performance and accuracy.

### CODE REVIEW

**Comment by AyushExel** [comment]
@glenn-jocher @Laughing-q @fcakyon This is done from my end. I've added more details on Slack. This'll help us to expand more towards the beginning of the training/dataset lifecycle.

@glenn-jocher I'm stopping the work on this here. Please confirm if you plan to have this or not, and I'll focus on other projects.

**Comment by glenn-jocher** [comment]
@AyushExel thanks! I'll take a look at this soon. Just merged a PR from a user also into this PR.

**Comment by AyushExel** [comment]
@glenn-jocher I'll send the ipynb file over slack that you can try this with.

**Comment by AyushExel** [comment]
Closing this

**Pull request closed without merging**
