### PR TITLE
New dataset: human8

### PR DESCRIPTION
**Pull request by ambitious-octopus**
New HUMAN8 dataset, which includes 8 instances from coco2017 annotated with weight, height, age, gender and race attributes. 

I haven't worked on a documentation page. Since it's a new task, I ask @Burhan-Q for guidance? Currently, the dataset section of the documentation includes the following categories: Detection, Segmentation, Pose, Classification, Oriented Bounding Boxes, and Multi-Object Tracking. Should we consider adding a new section?

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing the new HUMAN8 dataset configuration for YOLO model training!

### 📊 Key Changes
- 📁 Added a new dataset configuration file `human8.yaml`.
- 🧑‍🤝‍🧑**Dataset Details**: HUMAN8 comprises 8 images from COCO train2017 with enhanced annotations including weight, height, gender, age, and race.
- 📥 Provides a download URL for easy dataset access.
- 🗂️ Structured for straightforward integration into training/validation workflows with YOLO.

### 🎯 Purpose & Impact
- 🎨 **Diversity and Precision**: Allows YOLO model training on more diverse human attributes beyond the usual object detection, enhancing model responsiveness to a wider array of human features.
- ⚙️ **Ease of Use**: Simplifies the process of experimenting with and utilizing the HUMAN8 dataset, potentially broadening the community of users and contributors.
- 🚀 **Innovation Potential**: Sets a foundation for more inclusive and detailed datasets, encouraging nuanced model developments and applications.

### CODE REVIEW

**Comment by ambitious-octopus** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Burhan-Q** [comment]
@ambitious-octopus AFAIK this will be a new task, so it would require an update to the `tasks` page as well as a new section on the `datasets` page. For now, I think that it's probably more important (and easier) to work on the new `task` page. The new dataset page will be something we'll have to figure out, but I'm guessing it'll look _very_ similar to the COCO8 dataset page.

**Comment by glenn-jocher** [comment]
Does HUMAN stand for Human Universal Metrics and Analytics Network? haha

**Comment by Burhan-Q** [comment]
@glenn-jocher I think it _has to_ now 😂

**Comment by glenn-jocher** [comment]
@ambitious-octopus the zip contents are not correct, both README and LICENSE are out of date or incorrect, i.e. license should be AGPL instead of GPL and README is out of date, you can use coco8 here as an example:
See https://github.com/ultralytics/yolov5/releases/download/v1.0/coco8.zip

Dataset zips are all currently uploaded to yolov5 v1.0 release assets, we should continue this simply for consistency.

**Comment by glenn-jocher** [comment]
TODO: Docs page

**Comment by ambitious-octopus** [comment]
docs image
image

**Comment by glenn-jocher** [comment]
@ambitious-octopus merged into Human PR!!

**Pull request merged**
