### PR TITLE
`ultralytics 8.0.18` new python callbacks and minor fixes

### PR DESCRIPTION
**Pull request by AyushExel**
@glenn-jocher @Laughing-q 
@mikel-brostrom
## Add callback support in python interface:
This PR adds callback support. You can access batch or results list from the callback..
Here's an example.
```python
def on_predict_batch_end(predictor):
        # results -> List[batch_size]
        predictor.results[0].foo = "bar"
def test_callback():
    model = YOLO(MODEL)
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    result = model.predict(SOURCE)

    assert result[0].foo == "bar", "Callback test_failed"
```

* adds option to hide bboxes from segment prediction.
`yolo segment predict source=... boxes=False`
bus

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to Ultralytics codebase with improvements in documentation, error handling, and code maintenance.

### 📊 Key Changes
- ⚙️ Updated URLs in documentation from `config/` to `cfg/`.
- 🛠 Added single quotes around YouTube URLs.
- ✨ Revised error messages to include a link to format support documentation.
- 🔗 Corrected references to dataset checking functions.
- 🧰 Simplified export formats listing in `exporter.py`.
- 🧹 Removed unnecessary code in `torch_utils.py` regarding task guessing.
- 📝 Standardized callback lists in `callbacks/base.py`.
- 🖊️ Minor revisions and clarifications in docstrings and messages.
- 🎉 Introduced `emojis.py` for more expressive messaging.
- 🆕 Added new `boxes` option to show or hide boxes in segmentation predictions.

### 🎯 Purpose & Impact
- 🔗 Corrected links ensure users access the right documentation resources.
- 📈 Single quotes around URLs prevent terminal issues, enhancing usability.
- 🚀 Improved error messages help users quickly identify unsupported formats.
- 🧼 Refactoring for clarity and correctness improves codebase maintainability and readability.
- 🎨 Introducing emojis creates a friendly and engaging user interface.

### CODE REVIEW

**Comment by AyushExel** [comment]
@fcakyon predictor callbacks get `predictor` object, trainer callback gets trainer object. Here's all of them. We don't have them on docs but I'll add a callback section soon.
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/utils/callbacks/base.py

**Comment by mikel-brostrom** [comment]
With:

`ultralytics                  8.0.17`

I run:

```python
from ultralytics import YOLO

def on_predict_batch_end(predictor):
        # results -> List[batch_size]
        predictor.results[0].foo = "bar"
        
def test_callback():
    model = YOLO("yolov8n.pt")
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    result = model.predict(source="0")

    assert result[0].foo == "bar", "Callback test_failed"

test_callback()
```

```bash
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
AttributeError: 'YOLO' object has no attribute 'add_callback'
```

**Comment by mikel-brostrom** [comment]
I am checking this out. I have this:

```python
from ultralytics.yolo.engine.model import YOLO

def on_predict_batch_end(predictor):
        # results -> List[batch_size]
        print(predictor.save_dir)
        
        
def test_callback():
    model = YOLO("yolov8n.pt")
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    results = model.predict(source="0", show=False, stream=True)
    for i, result in enumerate(results):
        print(result)
    
test_callback()
```

which works fine. Any advice on how to return `im0` for each stream in `on_predict_batch_end` along with `boxes, conf, cls`?

**Comment by AyushExel** [comment]
> I am checking this out. I have this:
> 
> ```python
> from ultralytics.yolo.engine.model import YOLO
> 
> def on_predict_batch_end(predictor):
>         # results -> List[batch_size]
>         print(predictor.save_dir)
>         
>         
> def test_callback():
>     model = YOLO("yolov8n.pt")
>     model.add_callback("on_predict_batch_end", on_predict_batch_end)
>     results = model.predict(source="0", show=False, stream=True)
>     for i, result in enumerate(results):
>         print(result)
>     
> test_callback()
> ```
> 
> which works fine. Any advice on how to return `im0` for each stream in `on_predict_batch_end` along with `boxes, conf, cls`? I don't see any getter or as an attribute either in `Results` or `BasePredictor` classes. I would need this as I pass the original image to other models for tracking purposes 😄

@mikel-brostrom yes! I've turned batch into a class variable. So you can access it like this for each batch inside the callback as -> `predictor.batch` 
and it contains all these
```
path, im, im0s, vid_cap, s = batch
```

**Comment by mikel-brostrom** [comment]
Nice! I see @AyushExel. I ended up doing the following.

```python
from ultralytics.yolo.engine.model import YOLO

def on_predict_batch_end(predictor):
    # results -> List[batch_size]
    print(type(predictor.results[0]))
    print((len(predictor.results)))
    path, im, im0s, vid_cap, s = predictor.batch
    predictor.results = zip(predictor.results, im0s[0])
        
def test_callback():
    model = YOLO("yolov8n.pt")
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    results = model.predict(source="0", show=False, stream=True)
    for i, result in enumerate(results):
        print(result)
    
test_callback()
```

Is this the way you envision it to be used? Will this be part of the next pip release?

**Comment by AyushExel** [comment]
@mikel-brostrom yes! most probably it'll be merged and deployed tonight

**Comment by mikel-brostrom** [comment]
This is however weird:

```python
from ultralytics.yolo.engine.model import YOLO


def on_predict_batch_end(predictor):
    # results -> List[batch_size]
    path, im, im0s, vid_cap, s = predictor.batch
    print('on_predict_batch_end', im0s[0].shape)
    predictor.results = zip(predictor.results, im0s[0])
        
        
def test_callback():
    model = YOLO("yolov8n.pt")
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    results = model.predict(source="0", show=False, stream=True)
    for i, (result, im0) in enumerate(results):
        print('test_callback', im0.shape)
    
test_callback()
```

Output:

```bash
on_predict_batch_end (480, 640, 3)
test_callback (640, 3)
```

Can you reproduce?

**Comment by AyushExel** [comment]
@mikel-brostrom I think you don't have to do this:
```
predictor.results = zip(predictor.results, im0s[0])
```
im0s is already a list and so is results..So you can probably do this:
```
predictor.results = zip(predictor.results, im0s)
```
Does that work for you?

**Comment by mikel-brostrom** [comment]
Yes, this works:

```python
from ultralytics.yolo.engine.model import YOLO


def on_predict_batch_end(predictor):
    # results -> List[batch_size]
    path, im, im0s, vid_cap, s = predictor.batch
    print('on_predict_batch_end', im0s[0].shape)
    predictor.results = zip(predictor.results, im0s)
        
        
def test_callback():
    model = YOLO("yolov8n.pt")
    model.add_callback("on_predict_batch_end", on_predict_batch_end)
    results = model.predict(source="0", show=False, stream=True)
    for i, (result, im0) in enumerate(results):
        print('test_callback', im0.shape)
    
test_callback()
```

Output:

```bash
on_predict_batch_end (480, 640, 3)
test_callback (480, 640, 3)
```

Thank again!

**Comment by AyushExel** [comment]
@glenn-jocher windows test is failing but others pass. Do you know if its an issue?

**Comment by glenn-jocher** [comment]
@AyushExel windows CI seems fine, it's just slow.

**Comment by glenn-jocher** [comment]
@AyushExel ah yes I see the crash. Seems like some issue here in windows.
```
  File "d:\a\ultralytics\ultralytics\ultralytics\yolo\utils\callbacks\tensorboard.py", line 15 in on_pretrain_routine_start
```

**Comment by AyushExel** [comment]
@glenn-jocher okay I get it now. In tb.py the callbacks are not updated to list. This isn't caught on other platforms so maybe windows has it on by default.

**Comment by AyushExel** [comment]
> @AyushExel would it be possible to include the label in segmentation visualization?

Hmmm yeah totally forgot about that.. where do you think it should be included in case there's no box?

**Comment by glenn-jocher** [comment]
@AyushExel CI's passing! I'll merge our other PRs into this one now.

**Pull request merged**
