### PR TITLE
Add YOLOv9 Scales support

### PR DESCRIPTION
**Pull request by Supernova1744**
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing the much-anticipated YOLOv9 configuration! 🚀

### 📊 Key Changes
- **New Configuration File:** Launch of the YOLOv9 model configuration in YAML format, enabling advanced AI capabilities.
- **Flexible Scaling:** Offers multiple scales (n, s, m, l, x) to adjust depth, width, and max_channels, accommodating various compute capabilities.
- **Enhanced Backbone:** Utilizes a 'gelan backbone' for improved feature extraction, with multiple layers and innovative structures like RepNCSPELAN4 and ADown.
- **Advanced Head:** Integration of an advanced head structure that includes nn.Upsample and Concat operations, improving object detection precision across different object sizes.

### 🎯 Purpose & Impact
- **Versatility:** The introduction of scales enhances YOLOv9’s versatility, allowing it to be tailored to different hardware capabilities, from IoT devices to cloud servers.
- **Improved Accuracy:** The gelan backbone and sophisticated head design aim to increase model accuracy, especially in detecting small, medium, and large-sized objects.
- **Broader Accessibility:** By adding this configuration, Ultralytics makes state-of-the-art object detection more accessible, paving the way for developers and researchers to push the boundaries of what's possible in AI applications.

Expect these updates to bring significant enhancements in object detection tasks, boasting improved accuracy, speed, and adaptability across a wide array of applications. 🌈✨

### CODE REVIEW

**Comment by Pbatch** [comment]
Do you know how the reparameterization works for the smaller models?

**Comment by glenn-jocher** [comment]
The reparameterization in smaller YOLO models (like YOLOv8n) typically involves adjusting the model architecture to be more efficient while maintaining effectiveness. It often reduces the depth and width of the neural network to make the model lighter and faster, suitable for devices with limited computational resources. This adjustment involves changes to layers, filters, and sometimes kernel sizes.

For example, in YOLOv8n, the model might use fewer convolutional layers or reduce the number of filters in each layer compared to a larger version like YOLOv8x. Here's a basic representation of how you might adjust the configuration for smaller models:

```yaml
# Example of reparameterization in the model configuration
depth_multiple: 0.33  # model depth (layers)
width_multiple: 0.50  # layer channel width (filters)
```

These multipliers scale down the depth and width of the network, making it more efficient while still striving to capture the essential patterns required for detection tasks.

**Comment by Pbatch** [comment]
Bad @glenn-jocher bot. 

I am specifically referring to this: https://github.com/WongKinYiu/yolov9/blob/main/tools/reparameterization.ipynb

**Comment by glenn-jocher** [comment]
Hello! Thanks for referring to the specific notebook on reparameterization. It appears you're looking into the details of how YOLOv9 adjusts its architecture for different model sizes.

In that notebook, reparameterization is shown as a method to modify the architecture dynamically based on the model's depth and width, allowing for efficient scaling across various hardware capabilities without losing efficacy. This process ensures that even smaller models (like the 'n' or 's' variants) remain effective by thoughtfully reducing the model's complexity.

If you have any more detailed questions or need further clarification, feel free to ask! Happy coding! 😊

**Comment by Pbatch** [comment]
@glenn-jocher how much wood would a woodchuck chuck, if a woodchuck could chuck wood?

**Comment by glenn-jocher** [comment]
@Pbatch hello! Great question, but I think you might have the wrong forum for that. 😉 If there's anything YOLOv8 related you need help with, feel free to ask! Happy coding! 🚀

**Pull request closed without merging**
