### PR TITLE
Decrease default confidence threshold to start tracking new tracks

### LINKED ISSUE #14821: track error
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

In a video with dense small objects, I can predict the objects normally using model.predict. But when I use model.track, only the first frame of multiple objects are correctly identified, and only a few objects in subsequent frames are identified. Please help, thx

results = model.track(file_path, show=True)
results = model.predict(file_path, show=True)

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Y-T-G**
Closes #14821

This has to be explained too often to users, i.e. how to download the tracker yaml file manually, lower the threshold and pass it as arg to `model.track()`, indicating that the default threshold is higher than what most people are expecting. Most people expect `model.track()` to have similar detections as `model.predict()`. The higher new track threshold drops a lot of predictions compared to `model.predict()`. Lowered it to match the default `model.predict()` confidence threshold.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Thresholds for initialization and association in BoT-SORT and ByteTrack trackers have been lowered to improve tracking performance.

### 📊 Key Changes
- **Track High Threshold:** Reduced from 0.5 to 0.25 for both BoT-SORT and ByteTrack.
- **New Track Threshold:** Lowered from 0.6 to 0.25 for both trackers.
  
### 🎯 Purpose & Impact
- **Enhanced Detection Initiation:** Lower thresholds allow the trackers to initiate new tracks more easily, potentially improving tracking of objects with lower confidence scores.
- **Improved Association:** By reducing the high thresholds, the trackers are more capable of associating detections that might have been missed previously, thus refining tracking accuracy.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 pull request! This is an automated response to guide you through the process of contributing your improvements. An Ultralytics engineer will review your PR soon. Meanwhile, please ensure the following checklist is complete:

- ✅ **Define a Purpose**: Make sure your PR description clearly explains the change. You’ve done a great job detailing the purpose and impact of lowering the `new_track_thresh`! If possible, link to any related [issues](https://github.com/ultralytics/ultralytics/issues).
- ✅ **Synchronize with Source**: Ensure your PR is up-to-date with the `ultralytics/ultralytics` `main` branch. You can use the 'Update branch' button on GitHub or `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass. If any checks fail, please investigate and resolve the issues.
- ✅ **Update Documentation**: Update any relevant [documentation](https://docs.ultralytics.com) if your changes affect the usage or functionality of the library.
- ✅ **Add Tests**: Where applicable, include or update tests to cover your changes and confirm they all pass.
- ✅ **Sign the CLA**: Please sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if it's your first contribution by commenting "I have read the CLA Document and I sign the CLA".
- ✅ **Minimize Changes**: Focus your PR changes only to what is necessary for this update to reduce risks and simplify review.

For more information on the process of contributing, please check out our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have questions, feel free to leave a comment. Thanks again for your contribution to improving Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@Y-T-G looks good! Do you think this might cause too many FPs though?

**Comment by glenn-jocher** [comment]
@Laughing-q what do you think of these new lower track thresholds?

**Comment by Y-T-G** [comment]
@glenn-jocher FPs should be the same amount as what they see with `predict()`.

If the user desires a higher threshold, it's easier to increase the confidence threshold by passing `conf` as an argument (applied at the prediction level). As opposed to decreasing the confidence threshold which requires downloading the tracker yaml file, editing it, and then passing the path as an argument to `track()`, since this occurs at the tracker level.

I also noticed that there's a lower default prediction confidence threshold when using `track()`:

https://github.com/ultralytics/ultralytics/blob/8d203cf40dadb9343241d2f65bd4c84820f27430/ultralytics/engine/model.py#L598

**Comment by Laughing-q** [comment]
@Y-T-G Thanks for the PR! Personally I prefer not to change the default behaviors since there definitely are users our there are using our default tracker settings. We can not directly update the args, which might break some users workflow. Are there any issues that users want to lower the thresholds? which I could understand the cases better. Thanks

**Comment by Laughing-q** [comment]
@Y-T-G @glenn-jocher ok the lower threshold looks good to me since we also have 0.25 as default threshold for predict mode so I guess it's ok to make this more consistent.
@Y-T-G One suggestion though, for something that users are asking frequently we could maintain a list snippets of the answers and correct directions, so we could directly copy and send the snippets to users to explain what's going on.

**Review by Laughing-q — APPROVED** [review]
Approved! It's good to make the tracker thresholds consistent with predict thresholds.

**Comment by Y-T-G** [comment]
> @Y-T-G One suggestion though, for something that users are asking frequently we could maintain a list snippets of the answers and correct directions, so we could directly copy and send the snippets to users to explain what's going on.


@Laughing-q Thanks. I have a personal list of reference links of my answers that I use in case the question is repeated. So that they can also see any other follow-up questions.

**Comment by glenn-jocher** [comment]
@Y-T-G @Laughing-q PR merged, thanks guys!

**Comment by akdenmikail** [comment]
# Ultralytics YOLO 🚀, AGPL-3.0 license
# Default YOLO tracker settings for BoT-SORT tracker https://github.com/NirAharon/BoT-SORT

tracker_type: botsort # tracker type, ['botsort', 'bytetrack']
track_high_thresh: 0.5 # threshold for the first association
track_low_thresh: 0.1 # threshold for the second association
new_track_thresh: 0.25 # threshold for init new track if the detection does not match any tracks
track_buffer: 30 # buffer to calculate the time when to remove tracks
match_thresh: 0.8 # threshold for matching tracks
fuse_score: True # Whether to fuse confidence scores with the iou distances before matching
# min_box_area: 10  # threshold for min box areas(for tracker evaluation, not used for now)

# BoT-SORT settings
gmc_method: sparseOptFlow # method of global motion compensation
# ReID model related thresh (not supported yet)
proximity_thresh: 0.5
appearance_thresh: 0.25
with_reid: False


        results = model.track(frame,persist=True,tracker="custom.yaml", classes=classes_to_count)
        
track

Hello, thank you very much for your help. I applied what you said but I still could not get the result I wanted. I wonder if this is the maximum detection it can do or am I still missing something somewhere.

**Comment by Y-T-G** [comment]
>track_high_thresh: 0.5 # threshold for the first association
@akdenmikail You also have to reduce `track_high_thresh` to `0.25`

**Comment by Y-T-G** [comment]
@akdenmikail  You can increase `track_buffer` to a higher value like `120`

**Comment by akdenmikail** [comment]
> @akdenmikail You can increase `track_buffer` to a higher value like `120`

Thank you very much. So what do you think about deepsort real time fps reduction?

**Comment by Y-T-G** [comment]
@akdenmikail DeepSORT is older than BotSORT that's used by `ultralytics`. It very likely wouldn't be better.

**Pull request merged**
