### PR TITLE
Replace `lap` with `scipy` for tracking linear assignment

### LINKED ISSUE #1328: Error when using track task
### Search before asking

- [x] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection, Other

### Bug

Hello everyone,
I want to use the tracking proposed by yolov8 and I get an error during this attempt

Here is the error:
```
requirements: YOLOv8 requirement "lap" not found, attempting AutoUpdate...
  error: subprocess-exited-with-error

  × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [37 lines of output]
      Partial import of lap during the build process.
      C:\Users\user\AppData\Local\Temp\pip-install-sgqy8emk\lap_89774f47aeab407cb3f1c1646bd0f43f\setup.py:223: DeprecationWarning:

        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html


        from numpy.distutils.core import setup
      Generating cython files
      running install
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "lap._lapjv" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      running build_py
      creating build
      creating build\lib.win-amd64-3.9
      creating build\lib.win-amd64-3.9\lap
      copying lap\lapmod.py -> build\lib.win-amd64-3.9\lap
      copying lap\__init__.py -> build\lib.win-amd64-3.9\lap
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1077] : testing flags (/O2)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\user\AppData\Local\Temp\pip-install-sgqy8emk\lap_89774f47aeab407cb3f1c1646bd0f43f\build\temp.win-amd64-3.9\Release\ccompiler_opt_cache_ext.py
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.
WARNING: You are using pip version 22.0.4; however, version 23.0.1 is available.
You should consider upgrading via the 'C:\Users\user\Downloads\test\test\Scripts\python.exe -m pip install --upgrade pip' command.
requirements:  Command 'pip install "lap"  ' returned non-zero exit status 1.
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\user\Downloads\test\test\Scripts\yolo.exe\__main__.py", line 7, in <module>
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\yolo\cfg\__init__.py", line 317, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\yolo\engine\model.py", line 224, in track
    from ultralytics.tracker import register_tracker
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\__init__.py", line 3, in <module>
    from .track import register_tracker
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\track.py", line 10, in <module>
    from .trackers import BOTSORT, BYTETracker
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\trackers\__init__.py", line 3, in <module>
    from .bot_sort import BOTSORT
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\trackers\bot_sort.py", line 7, in <module>
    from ..utils import matching
  File "C:\Users\user\Downloads\test\test\lib\site-packages\ultralytics\tracker\utils\matching.py", line 3, in <module>
    import lap
ModuleNotFoundError: No module named 'lap'
```

### Environment

- Ultralytics YOLOv8.0.51  Python-3.9.13 torch-1.13.1+cpu CPU
- Setup complete  (8 CPUs, 7.8 GB RAM, 135.5/475.9 GB disk)
- Windows 11 22H2

### Minimal Reproducible Example

What I did:
```bash
py -m venv test
.\test\Scripts\activate
pip install ultralytics
yolo segment predict model=yolov8n-seg.pt source=0 show=true # work
yolo track model=yolov8n-seg.pt source=0 show=true # error
```

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
Replaces `lap` with `scipy` for tracking linear assignment, eliminating `lap` dependency. May resolve https://github.com/ultralytics/ultralytics/issues/1328

@Laughing-q 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of object tracking via improved assignment calculations and expanded video support.

### 📊 Key Changes
- 🔄 The `linear_assignment` function in `matching.py` now optionally uses SciPy for calculations.
- 🚀 New `use_scipy` parameter to enable/disable the use of SciPy in `linear_assignment`.
- 🌐 Added 'webm' to supported video formats in `utils.py`.

### 🎯 Purpose & Impact
- 🆙 The update offers an alternative method for solving linear assignment problems, potentially improving tracking efficiency.
- 🎥 Support for 'webm' expands compatibility, allowing users to work with a wider range of video formats.
- 🛠️ Despite the integration, there's a caution against using SciPy due to incorrect results, indicating a need for further validation/testing.
- ⚙️ Users can toggle SciPy usage, allowing them to test performance or revert to the proven original method if necessary.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher tested the new implementation but still not working correctly:
```python
import lap
from scipy.optimize import linear_sum_assignment
import numpy as np

test_round = 10

def compare_array(a, b):
    if a.shape == b.shape:
        return (a == b).all()
    else:
        return False

def linear_assignment_lap(cost_matrix, thresh=0.0):
    if cost_matrix.size == 0:
        return (
            np.empty((0, 2), dtype=int),
            tuple(range(cost_matrix.shape[0])),
            tuple(range(cost_matrix.shape[1])),
        )
    matches, unmatched_a, unmatched_b = [], [], []

    # TODO: investigate scipy.optimize.linear_sum_assignment() for lap.lapjv()
    _, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)

    matches.extend([ix, mx] for ix, mx in enumerate(x) if mx >= 0)
    unmatched_a = np.where(x < 0)[0]
    unmatched_b = np.where(y < 0)[0]
    matches = np.asarray(matches)
    return matches, unmatched_a, unmatched_b


def linear_assignment_scipy(cost_matrix, thresh=0.0):
    # Linear assignment function with scipy replacing lap.lapjv
    if cost_matrix.size == 0:
        return (
            np.empty((0, 2), dtype=int),
            tuple(range(cost_matrix.shape[0])),
            tuple(range(cost_matrix.shape[1])),
        )

    # cost, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)  # lap.lapjv usage (old)
    y, x = linear_sum_assignment(cost_matrix)  # row y, col x
    matches = np.asarray([[i, x] for i, x in enumerate(x) if cost_matrix[i, x] < thresh])

    unmatched = np.ones(cost_matrix.shape)
    for i, xi in enumerate(x):
        unmatched[i, xi] = 0.0
    # for i, xi in matches:
    # unmatched[i, xi] = 0.0
    unmatched_a = np.where(unmatched.all(1))[0]
    unmatched_b = np.where(unmatched.all(0))[0]

    return matches, unmatched_a, unmatched_b

for i in range(test_round):
    cost_matrix = np.random.random((5, 6))
    results = []
    for thresh in np.arange(start=0.1, stop=1, step=0.1):
        # print(f"-------{thresh}---------")
        match_lap, unmatch_a_lap, unmatch_b_lap = linear_assignment_lap(cost_matrix, thresh=thresh)
        match_scipy, unmatch_a_scipy, unmatch_b_scipy = linear_assignment_scipy(cost_matrix, thresh=thresh)
        results.append(
            all(
                [
                    compare_array(match_lap, match_scipy),
                    compare_array(unmatch_a_lap, unmatch_a_scipy),
                    compare_array(unmatch_b_lap, unmatch_b_scipy),
                ]
            )
        )
    print(results)
```

**Comment by glenn-jocher** [comment]
@Laughing-q got it, thanks! I'll try and work on this today.

**Comment by glenn-jocher** [comment]
@Laughing-q good test script! I experimented a bit and wasn't able to make them match perfectly. It looks like they have slightly different matching strategies. lap will match the lowest cost pairs first (producing less matches), while scipy seems to produce more matches, but possibly also more incorrect ones. For example in this matrix scipy will match both first and second rows with costs (0.467137 and 0.17011683), while lap only matches second row with cost 0.01719772:

```python
cost_matrix = np.asarray([[0.64154993, 0.467137, 0.80487143],
                          [0.17011683, 0.01719772, 0.44287542]])
```

**Comment by glenn-jocher** [comment]
@Laughing-q I used this updated test script. Was not able to align the two. I also see significant differences in tracking benchmark videos like this one: https://motchallenge.net/vis/MOT17-04-DPM

I've added *.webm video formats to the list of supported video formats. scipy creates > 1000 tracks over the video while lap creates < 50.

```python
import lap
import numpy as np
from scipy.optimize import linear_sum_assignment

test_round = 10


def compare_array(a, b):
    return (a == b).all() if a.shape == b.shape else False


def linear_assignment(cost_matrix, thresh=0.0, use_scipy=False):
    # Linear assignment function with scipy replacing lap.lapjv
    if cost_matrix.size == 0:
        return np.empty((0, 2), dtype=int), tuple(range(cost_matrix.shape[0])), tuple(range(cost_matrix.shape[1]))

    if use_scipy:
        y, x = linear_sum_assignment(cost_matrix)  # row y, col x
        matches = np.asarray([[i, x] for i, x in enumerate(x) if cost_matrix[i, x] <= thresh])
        unmatched = np.ones(cost_matrix.shape)
        for i, xi in matches:
            unmatched[i, xi] = 0.0
        unmatched_a = np.where(unmatched.all(1))[0]
        unmatched_b = np.where(unmatched.all(0))[0]
    else:  # use lap
        _, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)
        matches = np.asarray([[ix, mx] for ix, mx in enumerate(x) if mx >= 0])
        unmatched_a = np.where(x < 0)[0]
        unmatched_b = np.where(y < 0)[0]

    return matches, unmatched_a, unmatched_b


for i in range(test_round):
    cost_matrix = np.random.random((5, 6))
    results = []
    for thresh in np.arange(start=0.1, stop=.9, step=0.1):
        match_lap, unmatch_a_lap, unmatch_b_lap = linear_assignment(cost_matrix, thresh=thresh, use_scipy=False)
        match_scipy, unmatch_a_scipy, unmatch_b_scipy = linear_assignment(cost_matrix, thresh=thresh, use_scipy=True)
        results.append(
            all(
                [
                    compare_array(match_lap, match_scipy),
                    compare_array(unmatch_a_lap, unmatch_a_scipy),
                    compare_array(unmatch_b_lap, unmatch_b_scipy),
                ]
            )
        )
    print(results)

```

**Comment by Laughing-q** [comment]
@glenn-jocher yeah verified the scipy one, which the results look weird to me.
with scipy:
pic-full-230310-0944-25

with lap:
pic-full-230310-0945-03

**Comment by glenn-jocher** [comment]
@Laughing-q ok I've given up on the replacement for now. I've implemented it in this PR as a option to explore in the future but defaulted to `lap` just as we use now.

**Comment by Pbatch** [comment]
I think a lot of the differences between scipy and lap come from the way that the threshold is handled.

@glenn-jocher if I copy your code but set all the distances above the threshold to a large number (say 999999), then the results are much better.

```python
import lap
import numpy as np
from scipy.optimize import linear_sum_assignment

test_round = 10


def compare_array(a, b):
    return (a == b).all() if a.shape == b.shape else False


def linear_assignment(cost_matrix, thresh=0.0, use_scipy=False):
    # Linear assignment function with scipy replacing lap.lapjv
    if cost_matrix.size == 0:
        return np.empty((0, 2), dtype=int), tuple(range(cost_matrix.shape[0])), tuple(range(cost_matrix.shape[1]))

    if use_scipy:
        # Discourage above-threshold matches
        cost_matrix[cost_matrix > thresh] = 999999
        y, x = linear_sum_assignment(cost_matrix)  # row y, col x
        matches = np.asarray([[i, x] for i, x in enumerate(x) if cost_matrix[i, x] <= thresh])
        unmatched = np.ones(cost_matrix.shape)
        for i, xi in matches:
            unmatched[i, xi] = 0.0
        unmatched_a = np.where(unmatched.all(1))[0]
        unmatched_b = np.where(unmatched.all(0))[0]
    else:  # use lap
        _, x, y = lap.lapjv(cost_matrix, extend_cost=True, cost_limit=thresh)
        matches = np.asarray([[ix, mx] for ix, mx in enumerate(x) if mx >= 0])
        unmatched_a = np.where(x < 0)[0]
        unmatched_b = np.where(y < 0)[0]

    return matches, unmatched_a, unmatched_b


for i in range(test_round):
    cost_matrix = np.random.random((5, 6))
    results = []
    for thresh in np.arange(start=0.1, stop=.9, step=0.1):
        match_lap, unmatch_a_lap, unmatch_b_lap = linear_assignment(cost_matrix, thresh=thresh, use_scipy=False)
        match_scipy, unmatch_a_scipy, unmatch_b_scipy = linear_assignment(cost_matrix, thresh=thresh, use_scipy=True)
        results.append(
            all(
                [
                    compare_array(match_lap, match_scipy),
                    compare_array(unmatch_a_lap, unmatch_a_scipy),
                    compare_array(unmatch_b_lap, unmatch_b_scipy),
                ]
            )
        )
    print(results)
```    
gives
```
[True, True, True, True, True, True, True, True]
[True, True, True, True, True, True, True, True]
[True, True, True, True, True, True, True, True]
[True, True, True, True, True, True, True, True]
[True, True, True, True, True, True, True, True]
[True, True, True, True, True, True, True, True]
[True, True, True, True, True, True, True, True]
```

What do you think about this modification?

**Comment by Pbatch** [comment]
I have also discovered a significant bug which has vastly improved the results on my data.

This line is incorrect
```python
matches = np.asarray([[i, x] for i, x in enumerate(x) if cost_matrix[i, x] <= thresh])
```

It should be
```python
matches = np.asarray([[y, x] for x, y in zip(x, y) if cost_matrix[y, x] <= thresh])
```

We can only use ```enumerate``` when the cost_matrix is square (From the docs, "in the case of a square cost matrix the row indices will be equal to ```np.arange(cost_matrix.shape[0])```.").

This matters in practice as during testing I had row idx like
```
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 15 16 17 18 19 20 21 22 23 24
 25 26 27 29 30 31]
```
Value 14 is missing, so every matching after that point was incorrect.

**Comment by glenn-jocher** [comment]
@Pbatch that's an interesting find! Your discovery highlights the importance of understanding the context of the code and thoroughly testing code that we write or use. 

It's also essential to understand that several ways exist in which one can select matching pairs to form optimal assignments, and they can be different across different algorithm implementations, such as `lap` and `scipy`. Therefore, when using these libraries, one should rely on the library's documentation to understand the operation fully, potential differences, and when to use one over the other in your specific use case.

**Pull request merged**
