### PR TITLE
Reduced NCNN ARM64 thread usage

### LINKED ISSUE #13449: NCNN model - passing config parameters
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've discovered an issue related to Rockchip devices using the RK3588 system on a chip, and potentially other Linux devices using a big/little CPU configuration, namely:

If you invoke an NCNN model you will get very slow performance as the device tries to use all the cores on the RK3588, in my case I was getting about 4 FPS for a 640 x 320 video. However, if you make a small change to autobackend.py, in the model load section for ncnn, namely adding a line limiting the number of threads to the number of big cores: 

`       
    net.opt.num_threads = 4
`
Setting the number of threads to eight is slower, six is slower. 

I don't think this is specific to Ultralytics or YOLO as I've observed similar things with TorchScript and other models, I think its just how my operating system and python handle the big/little configuration. 

My question is: is there an efficient way to pass this parameter to autobackend.py when the model is loaded from 

`model = YOLO("path/to/ncnn/model")` 

I was thinking of overriding methods and/or just writing a custom implementation, but figured I'd ask the question here before I wrote dozens of line of code just to pass a single parameter to ncnn.Net(). I.e., why reinvent the wheel if I can just pass a parameter, and always installing Ultralytics in editable model and then changing the source code whenever I want to use NCNN + the RK3588 for a project seems less than idea? 

Other technical details:

- I'm running Ubuntu 22.04, community distro: https://github.com/Joshua-Riek/ubuntu-rockchip
- The Rockchip RK3588 chip has eight cores and my device has 16 GB of RAM
- I tested this via cloning the Ultralytics repo and installing it into a conda environment via "pip3 install -e ."
- The tests were with yolov8n.pt converted to NCNN
- When running things the standard way all of my cores are above 95% and I get 4 FPS, when I make the small change to the # of threads four cores run at 70-80% and the rest are basically idle 

Finally, if it matters, here is the code I was running 
```

import asyncio
import cv2
import json
import ncnn
import os
import sys
from ultralytics import YOLO

parent_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.append(parent_dir)

from common_utils.logging_utils import LoggingUtilities  # noqa: E402

logger = LoggingUtilities.console_out_logger("NCNN Tracker")


IMG_SIZE = (640, 640)


class ObjectTracker:

    def __init__(self, model_name: str, file_path: str):

        self.logger = logger

        self.model = self.get_model(model_name)

        self.stream_object = self.get_streaming_object(file_path)

        # analyze video
        asyncio.run(self.analyze_video(self.stream_object))

    def get_model(self, model_name: str) -> object:

        # create model
        model = YOLO(model_name)

        return model

    def get_streaming_object(self, file_path: str):

        cap = cv2.VideoCapture(file_path)
        assert cap.isOpened(), "Error reading video file"

        return cap

    def read_video(self, stream_object: object):

        success, frame = stream_object.read()

        if not success:
            logger.info('No file or processing complete')
            self.shutdown()

        return self.pre_process(frame)

    def pre_process(self, frame):

        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        shape = frame.shape[:2]

        if shape != IMG_SIZE:
            frame = self.letter_box(frame, shape, (640, 640), (0, 0, 0))

        return frame

    def letter_box(self, frame, shape, new_shape, pad_color):

        # Resize and pad image while meeting stride-multiple constraints
        # Scale ratio
        r = min(new_shape[0] / shape[0], new_shape[1] / shape[1])

        # Compute padding
        # ratio = r  # width, height ratios
        new_unpad = int(round(shape[1] * r)), int(round(shape[0] * r))
        dw, dh = new_shape[1] - new_unpad[0], new_shape[0] - new_unpad[1]

        dw /= 2  # divide padding into 2 sides
        dh /= 2

        if shape[::-1] != new_unpad:  # resize
            frame = cv2.resize(frame, new_unpad,
                               interpolation=cv2.INTER_LINEAR)

        top, bottom = int(round(dh - 0.1)), int(round(dh + 0.1))
        left, right = int(round(dw - 0.1)), int(round(dw + 0.1))
        frame = cv2.copyMakeBorder(frame, top, bottom, left, right,
                                   cv2.BORDER_CONSTANT, value=pad_color)

        return frame

    async def analyze_video(self, stream_object: object):

        frame_count = 0
        avg_fps = 0
        total_latency = 0
        fps_sum = 0

        while stream_object.isOpened():

            frame = self.read_video(stream_object)
            frame_count += 1

            # the video data object contains extensive data on each frame of
            # the video video shape, xy coordintes for each object, object
            # classes and data on inferencing and processing speed.
            video_data = self.inference(frame)

            # parse out key data from the video data object
            fps_sum, total_latency, avg_fps, \
                avg_latency, frame_message =\
                await self.parse_video_data(video_data,
                                            frame_count,
                                            fps_sum,
                                            total_latency)

            await self.write_on_frame(frame, frame_message, (5, 25))

            # create JSON payload
            await self.build_payload(avg_fps,
                                     avg_latency,
                                     frame_count)

            # Visualize the results on the frame
            annotated_frame = video_data[0].plot()

            # Display the annotated frame
            cv2.imshow("YOLOv8 Tracking", annotated_frame)

            # Break the loop if 'q' is pressed
            if cv2.waitKey(1) & 0xFF == ord("q"):
                self.shutdown()
                break

    def inference(self, frame: object):

        return self.model(frame, task="detect", verbose=False)

    async def write_on_frame(self, frame: object, text: str,
                             coordinates: tuple):

        cv2.putText(frame, text, coordinates,
                    cv2.FONT_HERSHEY_SIMPLEX, 1, (0, 255, 0), 2)

    async def parse_video_data(self, data: object,
                               frame_count: int,
                               fps_sum: int,
                               total_latency: float) -> dict:

        inferencing_latency = round((sum(data[0].speed.values())), 2)
        fps = round((1000 / inferencing_latency), 2)

        fps_sum = fps_sum + fps
        total_latency += inferencing_latency

        avg_fps = round((fps_sum/frame_count), 2)
        avg_latency = round((total_latency/frame_count), 2)
        frame_message = (f'Avg FPS: {avg_fps}')

        return fps_sum, total_latency, avg_fps, avg_latency, frame_message

    async def build_payload(self, avg_fps: float,
                            inferencing_latency: float,
                            frame_count: int) -> dict:

        payload = {"avg_fps": avg_fps,
                   "avg_inferencing_latency(ms)": inferencing_latency}

        if frame_count % 200 == 0:
            self.logger.info(f'Current payload: {payload}')

        # convert to json
        return json.dumps(payload)

    def shutdown(self):

        self.stream_object.release()
        cv2.destroyAllWindows()
        sys.exit()


# pass the model name, path to video and list of classes to be tracked

tracking = ObjectTracker("./yolov8n_ncnn_model",
                         "../videos/1171461-sd_640_360_30fps.mp4")
```

Thanks in advance. 

Also, happy to submit a PR if this is something best handled by updating the code base so that users can pass number of threads for certain models. 

-M

### Additional

_No response_

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced core utilization for edge inference on ARM64 architectures.

### 📊 Key Changes
- Imported `NUM_THREADS` from `ultralytics.utils`.
- Updated Vulkan compute net options to optimize thread utilization:
  - Adjusted `net.opt.num_threads` to use only "big" cores for ARM64 environments.

### 🎯 Purpose & Impact
- **Purpose**: Improve performance for edge inference on ARM64 devices by better utilizing CPU cores.
- **Impact**: 🏎️ Faster and more efficient model inference on devices like the Jetson or Raspberry Pi, leading to smoother performance for applications running on these platforms.

### CODE REVIEW

**Comment by lakshanthad** [comment]
@glenn-jocher it seems that the main branch does not have bad performance as @MarkhamLee mentioned and this PR does not differ results from `main` branch. Are you certain you got only 4FPS? 

I have tested on both RPi5 and RK3588. The below are on RK3588 for both `main` branch and this PR:

### Validation

```sh
(env) radxa@rock-5b:~/YOLOv8/ultralytics$ yolo val task=detect model=yolov8n_ncnn_model imgsz=640 data=coco8.yaml
Ultralytics YOLOv8.2.29 🚀 Python-3.9.2 torch-2.3.1 CPU (Cortex-A55)
Loading yolov8n_ncnn_model for NCNN inference...
Forcing batch=1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning /home/radxa/YOLOv8/datasets/coco8/labels/val.cache... 4 images, 0 backgrounds, 0 corrupt: 100%|██████████| 4/4 [00:0
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:00<00:00,  7.95
                   all          4         17      0.664      0.833      0.806      0.603
                person          3         10      0.722        0.5      0.527      0.268
                   dog          1          1       0.37          1      0.497      0.348
                 horse          1          2      0.777          1      0.995      0.747
              elephant          1          2      0.874        0.5      0.828      0.366
              umbrella          1          1      0.607          1      0.995      0.995
          potted plant          1          1      0.636          1      0.995      0.895
Speed: 7.4ms preprocess, 60.0ms inference, 0.0ms loss, 23.4ms postprocess per image
```

### Inference on webcam feed

```sh
(env) radxa@rock-5b:~/YOLOv8/ultralytics$ yolo detect predict model=yolov8n_ncnn_model source="1" show
Ultralytics YOLOv8.2.29 🚀 Python-3.9.2 torch-2.3.1 CPU (Cortex-A55)
Loading yolov8n_ncnn_model for NCNN inference...

1/1: 1... Success ✅ (inf frames of shape 640x480 at 30.00 FPS)

0: 640x640 1 person, 2 chairs, 2 beds, 94.4ms
0: 640x640 1 person, 2 chairs, 2 beds, 101.2ms
0: 640x640 1 person, 2 chairs, 2 beds, 73.0ms
0: 640x640 1 person, 2 chairs, 2 beds, 49.3ms
0: 640x640 1 person, 2 chairs, 2 beds, 59.3ms
0: 640x640 1 person, 2 chairs, 2 beds, 76.2ms
0: 640x640 1 person, 2 chairs, 2 beds, 50.6ms
0: 640x640 1 person, 2 chairs, 2 beds, 70.8ms
0: 640x640 1 person, 2 chairs, 2 beds, 60.2ms
0: 640x640 1 person, 2 chairs, 2 beds, 61.9ms
0: 640x640 1 person, 2 chairs, 2 beds, 60.4ms
0: 640x640 1 person, 2 chairs, 2 beds, 69.3ms
0: 640x640 1 person, 2 chairs, 2 beds, 64.3ms
0: 640x640 1 person, 2 chairs, 2 beds, 66.3ms
0: 640x640 1 person, 2 chairs, 2 beds, 62.5ms
0: 640x640 1 person, 2 chairs, 2 beds, 59.0ms
0: 640x640 1 person, 2 chairs, 2 beds, 77.5ms
0: 640x640 1 person, 2 chairs, 2 beds, 63.4ms
0: 640x640 1 person, 2 chairs, 2 beds, 67.1ms
0: 640x640 1 person, 2 chairs, 2 beds, 61.3ms
0: 640x640 1 person, 2 chairs, 2 beds, 67.4ms
0: 640x640 1 person, 2 chairs, 2 beds, 59.8ms
0: 640x640 1 person, 2 chairs, 2 beds, 64.0ms
0: 640x640 1 person, 2 chairs, 2 beds, 59.4ms
0: 640x640 1 person, 2 chairs, 2 beds, 59.9ms
0: 640x640 1 person, 2 chairs, 2 beds, 63.0ms
0: 640x640 1 person, 2 chairs, 2 beds, 64.7ms
0: 640x640 1 person, 2 chairs, 2 beds, 67.7ms
0: 640x640 1 person, 2 chairs, 2 beds, 64.7ms
0: 640x640 1 person, 2 chairs, 2 beds, 63.1ms
0: 640x640 1 person, 2 chairs, 2 beds, 64.5ms
0: 640x640 1 person, 2 chairs, 2 beds, 64.6ms
0: 640x640 1 person, 2 chairs, 2 beds, 62.7ms
0: 640x640 1 person, 2 chairs, 2 beds, 67.3ms
0: 640x640 1 person, 2 chairs, 2 beds, 61.6ms
0: 640x640 1 person, 2 chairs, 2 beds, 63.5ms
0: 640x640 1 person, 2 chairs, 2 beds, 63.4ms
```

**Comment by MarkhamLee** [comment]
After doing a lot more testing, I'd say this probably doesn't need to be a PR unless there are other use cases related to threads, instead some documentation notes:

* An environment that works for TF Lite will likely cause issues with NCNN and other formats/don't assume the same environment will support all export formats. 
* If things are running slow on a Rockchip 3588 device, check your core use in Htop, if you see all eight with heavy use, try rebuilding your environment as you should only see four in use when things are running well 

More details below....

@lakshanthad I have a several different environments, where I see the slow performance on my OrangePi 5Plus, running Ubuntu 22.04 across multiple OS installations (I have a couple of drives I swap in and out): 
`
(yolo_projects) markham@orangepi5plus-2204-node0:~/Documents/tests$ yolo val task=detect model=yolov8n_ncnn_model imgsz=640 data=coco8.yaml
Ultralytics YOLOv8.2.16 🚀 Python-3.10.14 torch-2.3.0 CPU (Cortex-A55)
Loading yolov8n_ncnn_model for NCNN inference...
Forcing batch=1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning /home/markham/Documents/GitHub/computer-vision-demo-reel/orangepi5plus_ncnn_detect/datasets/coco8/labels/val.cache... 4 images, 0
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 4/4 [00:02<00:00,  1.78it/s]
                   all          4         17      0.664      0.833      0.806      0.603
                person          4         10      0.722        0.5      0.527      0.268
                   dog          4          1       0.37          1      0.497      0.348
                 horse          4          2      0.777          1      0.995      0.747
              elephant          4          2      0.874        0.5      0.828      0.366
              umbrella          4          1      0.607          1      0.995      0.995
          potted plant          4          1      0.636          1      0.995      0.895
Speed: 9.0ms preprocess, 251.6ms inference, 0.0ms loss, 252.4ms postprocess per image
Results saved to runs/detect/val3
💡 Learn more at https://docs.ultralytics.com/modes/val
(yolo_projects) markham@orangepi5plus-2204-node0:~/Documents/tests$ 
`

After doing more testing, I "think" this is actually a dependency issue that arises when you adjust dependencies so that TF Lite exports can run successfully. I.e., I always adjust my environments to be able to run TF Lite, but when I created fresh environments and didn't bother with TF after seeing your results, I got similar results as you. Also worth noting that my benchmark results in an environment where TF Lite fails to run are faster across the board:

With TF Lite able to run 
Screenshot from 2024-06-09 20-12-59


Without TF Lite 
Screenshot from 2024-06-09 16-53-36

I saw the faster results with versions 8.2.15 and 8.2.29, so I'm fairly sure it's a TF dependencies issue and not related to Ultralytics.

On the thread/core front, I did notice that when things ran slow, all eight cores saw heavy use:

Screenshot from 2024-06-09 18-57-30

When things run fast, only four cores see heavy use:
Screenshot from 2024-06-09 19-00-55

I did deploy the current GH repo to a fresh environment in editable mode and experiment with changing the number of threads, not passing that parameter or specifying four threads was usually about the same, specifying one thread, two, six, eight, etc., was always slower. Seems my intuition was right about the relevance of threads, just wrong about the the root cause. It also means that "something" under the hood is specifically targeting the four "big" cores.

**Comment by lakshanthad** [comment]
@MarkhamLee Thank you very much for your detailed testing :) It is interesting to see that TF-enabled environments are causing this issue. Yeah, my initial testing above is without a TF-enabled environment. So, I will look more into this and get back.

**Comment by lakshanthad** [comment]
@MarkhamLee Could you share a screenshot of `pip list` and `yolo checks` when things ran slow vs things ran fast. Thanks.

**Comment by MarkhamLee** [comment]
> @MarkhamLee Could you share a screenshot of `pip list` and `yolo checks` when things ran slow vs things ran fast. Thanks.

Here is the pip for 8.2.3 that ran slow out of the box:

`certifi==2024.6.2
charset-normalizer==3.3.2
contourpy==1.2.1
cycler==0.12.1
distlib==0.3.8
filelock==3.14.0
fonttools==4.53.0
fsspec==2024.6.0
idna==3.7
imutils==0.5.4
Jinja2==3.1.4
kiwisolver==1.4.5
MarkupSafe==2.1.5
matplotlib==3.9.0
mpmath==1.3.0
ncnn==1.0.20240410
networkx==3.3
numpy==1.26.4
opencv-python==4.10.0.82
packaging==24.1
pandas==2.2.2
pillow==10.3.0
platformdirs==4.2.2
portalocker==2.8.2
psutil==5.9.8
py-cpuinfo==9.0.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
scipy==1.13.1
seaborn==0.13.2
six==1.16.0
sympy==1.12.1
thop==0.1.1.post2209072238
torch==2.3.1
torchvision==0.18.1
tqdm==4.66.4
typing_extensions==4.12.2
tzdata==2024.1
ultralytics==8.2.3
ultralytics-thop==0.2.8
urllib3==2.2.1
virtualenv==20.26.2
`
This is for an 8.2.18 environment that runs slow for NCNN, but has no problems exporting TFLite 
`absl-py==2.1.0
astunparse==1.6.3
cachetools==5.3.3
certifi==2024.6.2
charset-normalizer==3.3.2
cmake==3.29.5
coloredlogs==15.0.1
contourpy==1.2.1
cycler==0.12.1
distlib==0.3.8
filelock==3.14.0
flatbuffers==24.3.25
fonttools==4.53.0
fsspec==2024.6.0
gast==0.4.0
google-auth==2.30.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.64.1
h5py @ file:///croot/h5py_1715094734337/work
humanfriendly==10.0
idna==3.7
imutils==0.5.4
Jinja2==3.1.4
keras==2.13.1
kiwisolver==1.4.5
libclang==18.1.1
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
mdurl==0.1.2
mpmath==1.3.0
ncnn==1.0.20240410
networkx==3.3
numpy==1.24.3
oauthlib==3.2.2
onnx==1.16.1
onnx-graphsurgeon==0.5.2
onnx2tf==1.17.5
onnxruntime==1.18.0
onnxsim==0.4.36
opencv-python==4.10.0.82
opt-einsum==3.3.0
packaging==24.1
pandas==2.2.2
pillow==10.3.0
platformdirs==4.2.2
portalocker==2.8.2
protobuf==4.25.3
psutil==5.9.8
py-cpuinfo==9.0.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pybind11==2.12.0
Pygments==2.18.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
requests-oauthlib==2.0.0
rich==13.7.1
rsa==4.9
scipy==1.13.1
seaborn==0.13.2
six==1.16.0
sng4onnx==1.0.4
sympy==1.12.1
tensorboard==2.13.0
tensorboard-data-server==0.7.2
tensorflow==2.13.1
tensorflow-cpu-aws==2.13.1
tensorflow-estimator==2.13.0
tensorflow-io-gcs-filesystem==0.37.0
termcolor==2.4.0
tflite-support==0.1.0a1
thop==0.1.1.post2209072238
torch==2.3.1
torchvision==0.18.1
tqdm==4.66.4
typing_extensions==4.5.0
tzdata==2024.1
ultralytics==8.2.18
urllib3==2.2.1
virtualenv==20.26.2
Werkzeug==3.0.3
wrapt==1.16.0`

Fast just = versions that run normal out of the box like the 8.2.29 results from the other day. 

It's a weird issue.

**Comment by MarkhamLee** [comment]
Also, got this from the latest version. 

Notice inference speed is consistent, it's the post processing with the wild variances. 

Screenshot from 2024-06-11 01-41-33

The pip is as follows:
`certifi==2024.6.2
charset-normalizer==3.3.2
contourpy==1.2.1
cycler==0.12.1
distlib==0.3.8
filelock==3.14.0
fonttools==4.53.0
fsspec==2024.6.0
idna==3.7
imutils==0.5.4
Jinja2==3.1.4
kiwisolver==1.4.5
MarkupSafe==2.1.5
matplotlib==3.9.0
mpmath==1.3.0
ncnn @ git+https://github.com/Tencent/ncnn.git@093c5168982eaedd141210f71fbbc1951968ca2b
networkx==3.3
numpy==1.26.4
opencv-python==4.10.0.82
packaging==24.1
pandas==2.2.2
pillow==10.3.0
platformdirs==4.2.2
portalocker==2.8.2
psutil==5.9.8
py-cpuinfo==9.0.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
scipy==1.13.1
seaborn==0.13.2
six==1.16.0
sympy==1.12.1
torch==2.3.1
torchvision==0.18.1
tqdm==4.66.4
typing_extensions==4.12.2
tzdata==2024.1
ultralytics==8.2.31
ultralytics-thop==0.2.8
urllib3==2.2.1
virtualenv==20.26.2`

BUT, another environment with the latest, completely normal 
Screenshot from 2024-06-11 01-46-09

The pip is as follows:
`absl-py==2.1.0
anyio==4.4.0
astor==0.8.1
astunparse==1.6.3
attrs==23.2.0
cachetools==5.3.3
cattrs==23.2.3
certifi==2024.6.2
charset-normalizer==3.3.2
chex==0.1.86
coloredlogs==15.0.1
contourpy==1.2.1
coremltools==7.2
cycler==0.12.1
decorator==5.1.1
distlib==0.3.8
etils==1.7.0
exceptiongroup==1.2.1
filelock==3.14.0
flatbuffers==24.3.25
flax==0.8.4
fonttools==4.53.0
fsspec==2024.6.0
gast==0.4.0
google-auth==2.30.0
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
grpcio==1.64.1
h11==0.14.0
h5py @ file:///croot/h5py_1715094734337/work
httpcore==1.0.5
httpx==0.27.0
humanfriendly==10.0
idna==3.7
importlib_resources==6.4.0
imutils==0.5.4
jax==0.4.28
jaxlib==0.4.28
Jinja2==3.1.4
keras==2.15.0
kiwisolver==1.4.5
libclang==18.1.1
Markdown==3.6
markdown-it-py==3.0.0
MarkupSafe==2.1.5
matplotlib==3.9.0
mdurl==0.1.2
ml-dtypes==0.3.2
mpmath==1.3.0
msgpack==1.0.8
namex==0.0.8
ncnn==1.0.20240410
nest-asyncio==1.6.0
networkx==3.3
numpy==1.23.5
oauthlib==3.2.2
onnx==1.16.1
onnx-graphsurgeon==0.5.2
onnx2tf==1.22.3
onnxruntime==1.18.0
onnxslim==0.1.28
opencv-python==4.10.0.82
openvino==2024.0.0
openvino-telemetry==2024.1.0
opt-einsum==3.3.0
optax==0.2.2
optree==0.11.0
orbax-checkpoint==0.5.15
packaging==23.2
paddlepaddle==2.6.1
pandas==2.2.2
pillow==10.3.0
platformdirs==4.2.2
portalocker==2.8.2
protobuf==3.20.3
psutil==5.9.8
py-cpuinfo==9.0.0
pyaml==24.4.0
pyasn1==0.6.0
pyasn1_modules==0.4.0
pybind11==2.12.0
Pygments==2.18.0
pyparsing==3.1.2
python-dateutil==2.9.0.post0
pytz==2024.1
PyYAML==6.0.1
requests==2.32.3
requests-oauthlib==2.0.0
rich==13.7.1
rsa==4.9
scipy==1.13.1
seaborn==0.13.2
six==1.16.0
sng4onnx==1.0.4
sniffio==1.3.1
sympy==1.12.1
tensorboard==2.15.2
tensorboard-data-server==0.7.2
tensorflow==2.15.1
tensorflow-cpu-aws==2.15.1
tensorflow-estimator==2.15.0
tensorflow-hub==0.16.1
tensorflow-io-gcs-filesystem==0.37.0
tensorflow_decision_forests==1.8.1
tensorflowjs==4.19.0
tensorstore==0.1.61
termcolor==2.4.0
tf_keras==2.15.1
tflite-support==0.1.0a1
toolz==0.12.1
torch==2.3.1
torchvision==0.18.1
tqdm==4.66.4
typing_extensions==4.5.0
tzdata==2024.1
ultralytics==8.2.31
ultralytics-thop==0.2.8
urllib3==2.2.1
virtualenv==20.26.2
Werkzeug==3.0.3
wrapt==1.14.1
wurlitzer==3.1.0
x2paddle==1.4.1
zipp==3.19.2`

It's all quite vexing to say the least.

**Comment by glenn-jocher** [comment]
Hi @MarkhamLee,

Thank you for providing the detailed information and screenshots. It’s clear that the issue is quite intricate, especially with the variance in post-processing times and the differences in performance based on the environment setup.

### Observations:
1. **Post-Processing Variance**: The wild variances in post-processing times are indeed unusual. This could be influenced by several factors including the specific versions of dependencies, the underlying hardware, and how the CPU cores are being utilized.
2. **Dependency Differences**: The differences in `pip list` between the environments that run slow and those that run fast are notable. It seems that environments optimized for TF Lite might be causing issues with NCNN performance.
3. **Core Utilization**: Your observation about the core usage is interesting. When things run slow, all eight cores are heavily used, whereas only four cores are used when things run fast. This suggests that the threading configuration might be suboptimal in certain environments.

### Next Steps:
1. **Reproducible Example**: To help us investigate further, could you provide a minimum reproducible example? This will allow us to replicate the issue on our end. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).
2. **Environment Comparison**: Since you have environments where the issue does not occur, it would be helpful to compare the specific versions of critical dependencies like `torch`, `ncnn`, and `ultralytics`. Ensuring that the bug occurs in the most recent versions of these packages is crucial.
3. **Threading Configuration**: Given the core usage differences, it might be worth experimenting with explicitly setting the number of threads in your environment. You can do this by setting the `OMP_NUM_THREADS` environment variable or using threading libraries to control the number of threads.

### Example Code for Thread Configuration:
```python
import os
os.environ['OMP_NUM_THREADS'] = '4'  # Set the number of threads to 4

from ultralytics import YOLO

# Load the model
model = YOLO("yolov8n_ncnn_model")

# Run inference
results = model("https://ultralytics.com/images/bus.jpg")
```

### Additional Resources:
- For more details on TensorRT export and optimization, you can visit our [TensorRT integration guide](https://docs.ultralytics.com/integrations/tensorrt/).

We appreciate your patience and collaboration in resolving this issue. Please let us know if you have any further insights or if there are specific tests you would like us to run.

**Comment by nihui** [comment]
ncnn will automatically distinguish big and little cores and set the number of threads to the number of physical big cores. Unless you are willing to completely control the number of threads and the affinity binding strategy of threads yourself, keeping the default should be the best choice.

**Comment by glenn-jocher** [comment]
Hi @nihui,

Thank you for your detailed observations and the comprehensive information you've provided. It's clear you've put a lot of effort into diagnosing this issue, and we appreciate your diligence. 😊

### Key Points:
1. **NCNN Thread Management**: As you mentioned, NCNN automatically distinguishes between big and little cores and optimizes thread usage accordingly. This is generally the best approach unless there's a specific need to manually control thread affinity and count.
2. **Post-Processing Variance**: The significant variance in post-processing times is indeed unusual and warrants further investigation.

### Next Steps:
To help us get to the bottom of this, could you please provide a minimum reproducible example? This will allow us to replicate the issue on our end and investigate further. You can find more details on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the most recent versions of `torch` and `ultralytics`. If you haven't already, please upgrade your packages and try running your tests again. This will help us ensure that any potential bugs have not already been addressed in the latest updates.

### Example Code for Thread Configuration:
If you still wish to experiment with thread configuration, you can set the number of threads explicitly using the `OMP_NUM_THREADS` environment variable:

```python
import os
os.environ['OMP_NUM_THREADS'] = '4'  # Set the number of threads to 4

from ultralytics import YOLO

# Load the model
model = YOLO("yolov8n_ncnn_model")

# Run inference
results = model("https://ultralytics.com/images/bus.jpg")
```

### Additional Resources:
For more details on TensorRT export and optimization, you can visit our [TensorRT integration guide](https://docs.ultralytics.com/integrations/tensorrt/).

We appreciate your patience and collaboration in resolving this issue. Please let us know if you have any further insights or if there are specific tests you would like us to run. Your feedback is invaluable in helping us improve our tools and support.

**Comment by glenn-jocher** [comment]
@nihui got it, thanks a lot!

**Pull request closed without merging**
