### PR TITLE
Update modules.py

### PR DESCRIPTION
**Pull request by Yulv-git**
Fix some comments.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to neural network modules with comments and architecture refinements.

### 📊 Key Changes
- 🛠 Adjusted parameter comment order in `Bottleneck` class for clarity.
- 🏷 Renamed `CBAM` class comment to accurately reflect its purpose as a Convolutional Block Attention Module.
- 🧼 Modified the `C1` class comment and removed unnecessary arguments to align with its role as a CSP Bottleneck with 1 convolution.

### 🎯 Purpose & Impact
- 💡 Improves code readability and maintainability by clarifying parameter roles and order.
- 🧠 Refines neural network architecture, potentially enhancing performance or efficiency.
- 🚀 Provides a clearer understanding for developers and users on how the neural network components operate, leading to easier modifications and troubleshooting.

### CODE REVIEW

**Comment by Yulv-git** [comment]
I have read the CLA Document and I sign the CLA.

**Comment by Yulv-git** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://github.com/ultralytics/assets/blob/main/documents/CLA.md) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I sign the CLA
> 
> You can retrigger this bot by commenting **recheck** in this Pull Request

I have read the CLA Document and I sign the CLA

**Comment by Yulv-git** [comment]
I have read the CLA Document and I sign the CLA

**Comment by AyushExel** [comment]
Thanks for the PR!

**Comment by glenn-jocher** [comment]
@Yulv-git good fixes!

**Pull request merged**
