### PR TITLE
Added the ability to freeze layers (copied from the Yolo5) #562

### PR DESCRIPTION
**Pull request by theATM**
Hi not sure if helpful but I copied the freeze code from the Yolov5 to enable the freezing of the layers
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced model training customization with layer freezing support.

### 📊 Key Changes
- Added a new `freeze` parameter to `default.yaml` configuration to specify the number of layers to freeze.
- Updated `trainer.py` to process the `freeze` argument and apply the layer freezing during model setup.

### 🎯 Purpose & Impact
- **Purpose**: The ability to freeze layers is intended to allow users to fix the weights of certain parts of the model during training. This can help when fine-tuning a pre-trained model on new data by keeping the base layers static and only adjusting the weights of the higher-level, task-specific layers.
- **Impact**: Users can now improve training efficiency and potentially achieve better performance by customizing which layers get trained. This feature is particularly useful for transfer learning scenarios. 🔄🔒

### CODE REVIEW

**Comment by kvnptl** [comment]
Is it integrated into the main repo for YOLOv8?

**Comment by glenn-jocher** [comment]
@kvnptl thank you for your interest in YOLOv8. Yes, layer freezing has been added to the main YOLOv8 repository. You can use this feature by specifying the layers to be frozen in the command-line arguments or in the configuration file. If you encounter any issues or have further questions, please don't hesitate to let us know. Thank you for using YOLOv8!

**Comment by kvnptl** [comment]
Thank you for the reply.
I checked the default.yaml file but I couldn't find the freeze parameter there. Could you please show me one example of how to pass that as an argument?

**Comment by glenn-jocher** [comment]
@kvnptl you can pass the `--freeze` flag followed by a comma-separated list of layer numbers to freeze those specific layers during training. For example, if you want to freeze the first and second conv layers, you can set `--freeze 0,1` as an argument when running the train.py script. 
Alternatively, you can add the `freeze` parameter to the YAML configuration file with a list of frozen layers as values, like this:
```
freeze:
  - 0
  - 1
```
I hope this helps. Please let me know if you have any further questions.

**Comment by kvnptl** [comment]
I am getting an error `SyntaxError: 'freeze' is not a valid YOLO argument.` using below code.
```
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
model.train(data="my_data.yaml",
            epochs=10,
            imgsz=640,
            batch=16,
            name="yolov8_testing",
            device=0,
            freeze=[0, 1, 2, 3, 4, 5],  # freeze layers
            )
```

**Comment by glenn-jocher** [comment]
@kvnptl thank you for using YOLOv8! The `freeze` parameter is not a valid argument for the `YOLO` class in the Ultralytics YOLOv8 implementation. Instead, you can pass in a `cfg` file that specifies which layers to freeze during training. The `cfg` file should have a `[net]` section that includes a `frozen` parameter with a list of layer numbers to freeze. For example, to freeze the first two convolutional layers, your `cfg` file might look like this:
```
[net]
# Other parameters...
frozen = 0, 1
```
You can pass in the path to the `cfg` file via the `--cfg` flag during training.
I hope this helps! Please don't hesitate to let us know if you have any further questions or issues.

**Comment by sandau-matt** [comment]
Hi @glenn-jocher, I don't see the `--freeze` flag on `main`'s [engine/trainer.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/trainer.py) as is shown in this PR's diff. Does this flag live elsewhere in the YOLOv8 implementation? Thanks!

**Pull request closed without merging**
