### PR TITLE
[example] add yolov8 segmentation onnxruntime python demo

### PR DESCRIPTION
**Pull request by jamjamjon**
I find no yolov8 segmentation demo provided in examples directory. Some people want to deploy yolov8-seg models with ONNXRuntime or other frameworks, while not importing PyTorch. So I write a simple segmentation demo using Numpy and OpenCV.

----------------------
# PR Update

## Summary
This pull request adds a new example project that implements ONNXRuntime-based YOLOv8 segmentation which not relying on PyTorch. Just Numpy and OpenCV. It includes a main.py file that implements the model and a README.md file that explains the project and how to run it.

## Walkthrough
 - Provide usage instructions
 - Add docstrings for class and methods
 - Support FP32 and FP16 model

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added YOLOv8 Segmentation with ONNXRuntime in Python example.

### 📊 Key Changes
- 🧩 New example directory `YOLOv8-Segmentation-ONNXRuntime-Python` with code and README.
- ✨ README.md details how to run segmentation with YOLOv8 using ONNX Runtime.
- 🛠 Main script `main.py` added for running segmentation in Python.
- 📝 Updated contribution guidelines in `examples/README.md`.

### 🎯 Purpose & Impact
- 🚀 Enables users to perform image segmentation without PyTorch, relying solely on ONNX Runtime.
- 🔍 Supports FP32 and FP16 precision, optimizing performance across devices.
- 🤝 Expanded community contribution guidelines streamline the process for contributors.
- 🌐 Promotes interoperability and easier setup, broadening access to machine learning applications.

### CODE REVIEW

**Comment by jamjamjon** [comment]
demo
Result would be like this.

**Comment by glenn-jocher** [comment]
@jamjamjon thank you for your suggestion. Adding an ONNXRuntime-based YOLOv8 segmentation demo could indeed be beneficial, especially for those who wish to deploy their models using different frameworks without relying on PyTorch.

Your demonstration result looks exciting! For practical implementation in this repo, a couple of steps need to be followed. The segmentation demo would first need to parse the model's output, which, in the case of YOLOv8-seg, would likely be a segmentation map. This could be handled with Numpy since the output would typically have a simple format, such as Height x Width x Classes.

To display or save the results visually, OpenCV could be used. With the segmentation map, we could apply a color map to visualize different segments more clearly, similar to what you have shown in your result.

However, do keep in mind that adding a new feature like this would require rigorous testing to ensure compatibility with existing codebase and functionality. If you are interested in contributing this feature, I encourage you to open a pull request. We greatly appreciate community contributions and would be excited to review your implementation. Thank you for your dedication to improving Ultralytics YOLO.

**Comment by jamjamjon** [comment]
This is a PR. I think I've done all you said. Should I add some comment to `class` and `methods`? Or what else parts should I fix?

**Comment by glenn-jocher** [comment]
@jamjamjon hello, thank you for your contribution. I'm glad to see your active engagement with our YOLOv8 repository.

Adding comments to classes and methods is always an excellent step towards making code more understandable and maintainable. It assists both current and future developers in understanding what the code is about, thus making it easier to work with.

The following are some of the key areas you might consider while enhancing your pull request:

1. **Functionality**: Ensure the code is working as expected without any errors. Test it thoroughly under various conditions to ensure its robustness.

2. **Code Quality**: Follow good coding practices, maintain consistent formatting, and consider refactoring any complex or confusing sections of code to improve clarity.

3. **Documentation**: To improve code readability, consider adding docstrings to your classes and methods, providing a brief description of their purpose and functionality, and specifying input/output parameters.

4. **Tests**: If possible, include relevant tests to validate that the additions or changes to the code function as intended.

As part of the reviewing process, we may also offer some suggestions for improvement.

Thank you again for your contribution to the YOLOv8 project. We look forward to reviewing your pull request.

**Comment by jamjamjon** [comment]
I've refactored the code and re-write the README.md. Providing usage instructions. Adding docstrings for class and methods. Making code easy to understand. I tested on a lot of images with several segmentation models and the code was working fine. Please review this PR.

**Comment by glenn-jocher** [comment]
@jamjamjon PR merged! Thank you for your contributions :)

**Pull request merged**
