### PR TITLE
New HUB Cloud Training docs page

### PR DESCRIPTION
**Pull request by priytosh-tripathi**
This branch introduces Getting started guide for Cloud training which documents details about features, procedures and steps.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements in CI workflow and the addition of cloud training documentation.

### 📊 Key Changes
- Updated CI workflow to ignore paths related to documentation changes.
- Created new cloud training documentation page.
- Updated dataset and models documentation for enhanced clarity and consistency.

### 🎯 Purpose & Impact
- **CI Workflow Change**: Prevents unnecessary CI runs for documentation updates 🛠️, optimizing workflow efficiency.
- **Cloud Training Doc**: Provides users with detailed guidance on cloud-based AI model training ☁️, enhancing user experience.
- **Documentation Revisions**: Improve the quality and accessibility of information 📚, making it easier for users to utilize the platform effectively.

### CODE REVIEW

**Review by kalenmike — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@priytosh-tripathi @kalenmike awesome, nice job guys!

**Comment by glenn-jocher** [comment]
@priytosh-tripathi @kalenmike good job with the image alt text too, that will help the page SEO

**Comment by glenn-jocher** [comment]
@priytosh-tripathi @kalenmike oh just noticed something. We should try to avoid non-descriptive link alt text, so i.e. `[here](https://...)` should instead be something like "Read more at our [getting started guide](https://...)"

**Comment by priytosh-tripathi** [comment]
Hi @glenn-jocher ,
Should I fix the issue with [here] text at priority right before we merge this?

**Comment by glenn-jocher** [comment]
@priytosh-tripathi yeah please fix. Here's an example:

```diff
- Read more about creating and other details of a Model [here](models.md)
+ Read more about creating models at the [HUB Models page](models.md)
```

**Comment by priytosh-tripathi** [comment]
@glenn-jocher The changes replacing [here] at alt-text is pushed.

**Comment by glenn-jocher** [comment]
@priytosh-tripathi looks good!

**Comment by glenn-jocher** [comment]
@priytosh-tripathi @kalenmike PR merged, nice work!!

**Pull request merged**
