### PR TITLE
Build with `opencv-python` in headless version

### LINKED ISSUE #7056: Questions about using headless opencv
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I have two questions regarding using `opencv-python-headless` instead of the default `opencv-python` dependency.

1) Enabling a build with `opencv-python-headless` : I have read about similar requests from other issues, for example #3480 proposed a way to fix this which didn't work out. Could you please give an update about any on-going efforts or what do you see as the proper way to enable this in the future?

2) Do you know if a CUDA build of opencv-python( or the  headless version) will be compatible with the YOLOv8 model? For example, I can see some benefits of using a CUDA build to resize the images during preprocessing [here](https://github.com/ultralytics/ultralytics/blob/b206b68ac65f3341749205d49da98da83e22cc6d/ultralytics/data/augment.py#L723-L726), but that requires additional changes to the cv2 API as well as the image type according to [ref](https://www.simonwenkel.com/notes/software_libraries/opencv/resizing-images-using-nvidia-gpus-opencv-pytorch-tensorflow.html). So even if I manage to build a CUDA version, it won't work out-of-box with Ultralytics, am I right?

### Use case

I am using Ultralytics YOLOv8 model in a production environment that does not have the graphics library required by `opencv-python`:

```
>> import cv2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.10/site-packages/cv2/{}init{}.py", line 181, in <module>
    bootstrap()
  File "/layers/com.bloomberg.ds.buildpacks.pip/requirements/lib/python3.10/site-packages/cv2/{}init{}.py", line 153, in bootstrap
    native_module = importlib.import_module("cv2")
  File "/opt/bb/lib/python3.10/importlib/{}init{}.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: libGL.so.1: cannot open shared object file: No such file or directory
```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Pandede**
Resolves #7056 #4422 

copilot:all

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Switch to OpenCV headless for reduced package size and dependencies.

### 📊 Key Changes
- Changed the OpenCV dependency to `opencv-python-headless` instead of `opencv-python`.
- Updated the version pinning to require at least version 4.6.0 of `opencv-python-headless`.

### 🎯 Purpose & Impact
- The purpose of this change is to reduce the size and number of dependencies required by replacing the full OpenCV package with a headless version that doesn't include any GUI functionality or unnecessary bloat.
- This could potentially lower the installation time and the space required for projects using this repository.
- The impact on end-users is likely to be minimal, as long as they don't depend on OpenCV's GUI features within this project, further contributing to a leaner project footprint. 📦

### CODE REVIEW

**Comment by Pandede** [comment]
recheck

I have read the CLA Document and I sign the CLA

**Comment by Pandede** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Pandede** [comment]
recheck

**Comment by glenn-jocher** [comment]
@Pandede hello, and thank you for signing the CLA! For the recheck regarding the build with `opencv-python-headless`, I assume you're looking to use YOLOv8 in an environment without GUI support, such as a server or a Docker container without X server. The headless version is indeed beneficial for such cases.

The change to the headless version should not affect the functionality of YOLOv8 as long as you don't require any GUI features from OpenCV. If you encounter any issues during this process, please feel free to raise them on the issues page with relevant details. Our team is here to help!

Remember, for further clarification on model functionalities and tasks, you can always refer to our [docs](https://docs.ultralytics.com). Happy coding! 🚀

**Comment by Pandede** [comment]
I'm trying to fix this with the similar idea to #3480: Install the headless version with `ultralytics[headless]` 
Unfortunately, it's still an issue because `setuptools` has not supported "default" extra_require yet.
I may ask for the progress about the PR in `setuptools` or seek for the another solution.

**Comment by glenn-jocher** [comment]
@Pandede hello! Installing the headless version via `ultralytics[headless]` is a good approach, but as you've discovered, the `setuptools` limitation with "default" `extra_require` currently complicates this process.

Your options are indeed to either monitor the progress of the relevant PR in the `setuptools` repository for a resolution or to explore alternative solutions for installing the headless version of the dependencies. Keep an eye on `setuptools` updates, and in the meantime, manual specification of the headless packages might be necessary.

We appreciate your patience and contribution to improving the installation process. If you have any more concerns or ideas, our issue tracker is the place to bring them up. 🛠️

**Comment by glenn-jocher** [comment]
@Pandede thanks for the PR! The problem is we can't adopt this as default because then many out-of-the-box commands will no longer work like `yolo predict show`.

**Comment by Pandede** [comment]
Alright I got it, I may close this PR as it broke many of functions. I would like to seek for the appropriate solution for this issue in future. Thanks to your reply!

**Comment by glenn-jocher** [comment]
@Pandede thanks for the update, and no worries! Your initiative is much appreciated. Looking forward to any future contributions you might have. Don't hesitate to reach out if you find another solution. Happy coding! 🚀

**Pull request closed without merging**
