### PR TITLE
Added warning message for Test Time Augmentation 

### PR DESCRIPTION
**Pull request by ambitious-octopus**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced validation process with added Test Time Augmentation warning.

### 📊 Key Changes
- Introduced a warning message for Test Time Augmentation during validation.

### 🎯 Purpose & Impact
- **Purpose**: Alert users when Test Time Augmentation is enabled to inform them about potential variability in results.
- **Impact**: Helps users understand why validation results might not be consistent, aiding in better debugging and model evaluation. 🛠️

### CODE REVIEW

**Comment by Laughing-q** [comment]
@ambitious-octopus probably adding this warning to trainer? since the confusion seems more like launching training with `augment` and some users consider it's a trigger to enable augmentation.

**Comment by glenn-jocher** [comment]
@ambitious-octopus does `yolo val augment` produce non-deterministic mAP?

**Comment by Laughing-q** [comment]
@ambitious-octopus I think @glenn-jocher is right, probably we don't want this warning actually, since currently user lauching training with/without `augment=True` would get the same evaluation results(except for detection task with TTA might get higher metrics, but still won't affect user's training experience). 
The issue we talked about yesterday is because the user was not using the latest version of our package(the one without the recent `predict_augment` fix) and he got incorrect results on pose task with `augment=True`. But since now the it's fixed and pose inference with `augment=True` should perform single-scale inference as well so the user should get it work by upgrading to the latest version. I mean even users consider this argument is for training augmentation they won't get any inconsistent results anyway. What do you think?

**Comment by glenn-jocher** [comment]
@ambitious-octopus @Laughing-q yes let's close I think this is not needed. 

I see we do have a bit of confusion though with `augment=False`, which is the default but doesn't apply to training. Maybe we could default it to None and then assume other values based on mode:

- predict > `False if None`
- val > `False if None`
- train > `True if None` (then users can use this to disable all augmentation by passing `augment=False`
- export > ignore

**Pull request closed without merging**
