### PR TITLE
Update `fraction` arg to employ a random selection

### LINKED ISSUE #8233: fraction randomly instead of slice
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

If you have several joined datasets, you can delete one of them with slice.

### Use case

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by johnnynunez**
better if you have datasets unified

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved image selection for diverse dataset sampling 📸✨

### 📊 Key Changes
- Introduced randomness in selecting a subset of image files for datasets when not using the full dataset.

### 🎯 Purpose & Impact
- **Purpose**: This change aims to make dataset samples more diverse by randomly selecting images instead of taking the first portion of the dataset. This can help in training models to be more robust and perform better across varied data.
- **Impact**: Users employing a fraction of the dataset for model training or evaluation will now get a more diverse and possibly more representative sample of the whole dataset. This could lead to improvements in model accuracy and generalization.

### CODE REVIEW

**Comment by johnnynunez** [comment]
#8233

**Comment by glenn-jocher** [comment]
@johnnynunez thank you for the summary of the pull request. It's great to see improvements aimed at enhancing the diversity of training data, which is crucial for building robust machine learning models. Randomizing the selection of dataset images can indeed help in preventing order bias and potentially lead to better generalization. This change could be particularly beneficial for users working with subsets of larger datasets or when computational resources are limited. Keep up the good work! If there are any specific issues or questions related to this PR, feel free to ask.

**Comment by Burhan-Q** [comment]
Actually, I found that there is a function for accomplishing this while looking at something else. It appears to be something to use as a standalone utility to do the dataset splitting.

https://github.com/ultralytics/ultralytics/blob/2f22ff4ae66e86c53def72d52eb2e61ec924172e/ultralytics/data/utils.py#L615-L647

**Comment by glenn-jocher** [comment]
@johnnynunez yes agree with @Burhan-Q here, the function is working as intended, it's simply using the first X percent of the dataset rather than sampling it randomly.

I suppose the only conceivable drawback is that the images in this first percent of the dataset can be replaced by changing the seed. @Burhan-Q what do you think? With the default settings, i.e. same seed the randomization is almost the same as the slice op.

My main usage for this was for training on the first i.e. 1% or 10% of huge datasets like OIV7 and Objects365 while developing and debugging.

**Comment by Burhan-Q** [comment]
@glenn-jocher I agree that this good as-is, especially given the argument description in the docs does not mention anything about randomly splitting the data:

> Specifies the fraction of the dataset to use for training. Allows for training on a subset of the full dataset, useful for experiments or when resources are limited.

There's also this https://github.com/ultralytics/ultralytics/blob/2f22ff4ae66e86c53def72d52eb2e61ec924172e/ultralytics/data/utils.py#L615-L647 which I commented about in the referenced PR, which can be used for randomly sampling/splitting the dataset. Maybe it could be worth while to reference this function in the docs table in the `fraction` argument description for anyone who may want something more randomized.

**Comment by johnnynunez** [comment]
For example in my case I have put together 4 datasets and converted them into coco format. As I am doing experiments to try to improve the architecture of Yolov8 I make 50 epochs but then I saw the slice so I could be eliminating 3/4 datasets, and this is a serious mistake. With my selection I may be randomly picking items from each dataset.

**Comment by johnnynunez** [comment]
I've checked and this is not working with DDP
Traceback (most recent call last):
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/data/dataset.py", line 118, in get_labels
    assert cache["hash"] == get_hash(self.label_files + self.im_files)  # identical hash
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home-net/jnunez/.config/Ultralytics/DDP/_temp_0bt0fjx2140671656347216.py", line 12, in <module>
    results = trainer.train()
              ^^^^^^^^^^^^^^^
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/engine/trainer.py", line 208, in train
    self._do_train(world_size)
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/engine/trainer.py", line 322, in _do_train
    self._setup_train(world_size)
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/engine/trainer.py", line 286, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/data/build.py", line 87, in build_yolo_dataset
    return YOLODataset(
           ^^^^^^^^^^^^
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/data/dataset.py", line 42, in __init__
    super().__init__(*args, **kwargs)
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/data/base.py", line 74, in __init__
    self.labels = self.get_labels()
                  ^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/data/dataset.py", line 120, in get_labels
    cache, exists = self.cache_labels(cache_path), False  # run cache ops
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/data/dataset.py", line 108, in cache_labels
    save_dataset_cache_file(self.prefix, path, x)
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/data/dataset.py", line 354, in save_dataset_cache_file
    path.with_suffix(".cache.npy").rename(path)  # remove .npy suffix
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/pathlib.py", line 1175, in rename
    os.rename(self, target)
FileNotFoundError: [Errno 2] No such file or directory: '/data-fast/108-data3/jnunez/datasets/custom_dataset_v2/labels/train.cache.npy' -> '/data-fast/108-data3/jnunez/datasets/custom_dataset_v2/labels/train.cache'
[2024-02-19 14:00:28,191] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1611273 closing signal SIGTERM
[2024-02-19 14:00:28,193] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1611274 closing signal SIGTERM
[2024-02-19 14:00:28,194] torch.distributed.elastic.multiprocessing.api: [WARNING] Sending process 1611275 closing signal SIGTERM
[2024-02-19 14:00:33,171] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 3 (pid: 1611276) of binary: /home-net/jnunez/miniconda3/envs/small-fast-detector/bin/python3
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/site-packages/torch/distributed/run.py", line 816, in <module>
    main()
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 347, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/site-packages/torch/distributed/run.py", line 812, in main
    run(args)
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/site-packages/torch/distributed/run.py", line 803, in run
    elastic_launch(
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 135, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 268, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
/home-net/jnunez/.config/Ultralytics/DDP/_temp_0bt0fjx2140671656347216.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-02-19_14:00:28
  host      : cudahpc08.cvc.uab.es
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 1611276)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
Traceback (most recent call last):
  File "/home-net/jnunez/project/detector/small-fast-detector/finetune.py", line 24, in <module>
    model.train(
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/engine/model.py", line 389, in train
    self.trainer.train()
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/engine/trainer.py", line 203, in train
    raise e
  File "/home-net/jnunez/project/detector/small-fast-detector/ultralytics/engine/trainer.py", line 201, in train
    subprocess.run(cmd, check=True)
  File "/home-net/jnunez/miniconda3/envs/small-fast-detector/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home-net/jnunez/miniconda3/envs/small-fast-detector/bin/python3', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '36555', '/home-net/jnunez/.config/Ultralytics/DDP/_temp_0bt0fjx2140671656347216.py']' returned non-zero exit status 1.

**Comment by glenn-jocher** [comment]
@johnnynunez hi there! It sounds like you're doing some interesting work combining multiple datasets for your YOLOv8 experiments. If you're concerned about the dataset slicing potentially leaving out some of your data, you might want to consider shuffling your combined dataset before training. This way, you can ensure that your training and validation sets are randomly sampled from across all your datasets.

Here's a quick example of how you could shuffle your dataset in Python:

```python
import random
from pathlib import Path

# Assuming 'data' is a list of your dataset image file paths
data = list(Path('path/to/your/dataset').rglob('*.jpg'))
random.shuffle(data)

# Now you can slice the first X percent for training
fraction = 0.25  # For example, using 25% of the data
split = int(len(data) * fraction)
train_data = data[:split]
val_data = data[split:]
```

This way, you're randomly selecting from all your datasets for both training and validation. Hope this helps, and best of luck with your experiments! 🚀

**Comment by glenn-jocher** [comment]
@johnnynunez I've decided to merge this in as I believe it makes sense. Thank you for your contributions to YOLO!

**Pull request merged**
