### PR TITLE
Update docstrings of mouse_callback function for Homework purpose

### PR DESCRIPTION
**Pull request by orancs11**
Dear Reviewer,

At the beginning of the semester for our Software Architecture lecture, we were tasked with selecting a project to analyze. After careful consideration, we chose a project that met the specified requirements. As we approach the end of the semester, our final assignment involves making a valid change to the selected project, committing and pushing the modification, and communicating with the project owner to discuss our updates.

Given that our team does not have specific requirements related to mathematical or other technical changes, we decided to modify a function's docstring within the project. This adjustment serves as our contribution to the project.

This request is part of our homework, and we appreciate your time in reviewing and providing feedback on our changes.

Thank you for your consideration.

Sincerely,
Orhan Murat Tuncer, Cansu Zeynep Kars, Ece Büşra Civelek, Fatma Sena Alpakut

Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:

1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.

2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.

3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.

4. **Ultralytics Contributor License Agreement (CLA)**: To uphold the quality and integrity of our project, we require all contributors to sign the CLA. Please confirm your agreement by commenting below:

    _I have read the CLA Document and I hereby sign the CLA_

For more detailed guidance and best practices on contributing, refer to our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing). Your adherence to these guidelines ensures a faster and more effective review process.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced mouse interaction for YOLOv8 Region Counter example.

### 📊 Key Changes
- Expanded the documentation of the `mouse_callback` function.
- Added a detailed description of mouse events, including parameters and global variables affected.
- Included specific actions taken on different mouse events like left button down, movement, and button up.

### 🎯 Purpose & Impact
- **Improved Clarity:** The updated comments provide greater understanding for developers on how mouse interactions are handled.
- **Enhanced Usability:** End users will benefit from smoother region selection and manipulation during object counting with YOLOv8.
- **Educational Value:** With the inclusion of an example, new developers can quickly learn how to implement similar functionality in their applications.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Acenath much better, thank you for the update!

**Comment by glenn-jocher** [comment]
@Acenath PR merged!

**Comment by Acenath** [comment]
Thank you for your assistance. Good work!

**Comment by glenn-jocher** [comment]
@Acenath you're welcome! If you have any more questions in the future, feel free to reach out. Have a great day! 😊

**Pull request merged**
