### PR TITLE
Corrects CONTRIBUTING.md relative link to CLA.md

### PR DESCRIPTION
**Pull request by Burhan-Q**
Found that CLA document link was pointing to a dead link. Updated to use `docs/en/help/CLA.md` instead. No other changes or review was made of this document, just noticed this and wanted to update the link to prevent 404 page error (on GitHub).

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updates to the CONTRIBUTING.md file to improve documentation clarity and consistency.

### 📊 Key Changes
- Added a **FAQ section** to help contributors with common questions.
- **Hyperlinks** updated to point to documentation on Ultralytics' website.
- Improved wording and formatting for **Google-style docstring examples**.
- Enhanced clarity in steps for **CLA signing** and **reporting bugs**.

### 🎯 Purpose & Impact
- **Easier Navigation**: Direct links to online resources make it simpler for contributors to find detailed information.
- **Improved Documentation**: Clarifies expectations for code documentation, improving code readability and maintenance.
- **Support for Contributors**: The new FAQ section provides quick answers and guidance, encouraging more efficient and informed contributions. 📚✨

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q looks like the Doc is generally out of sync with https://docs.ultralytics.com/help/contributing/

**Comment by Burhan-Q** [comment]
@glenn-jocher took a longer look and updated the contents of `CONTRIBUTING.md` to match the docs version, and made sure that the links for `CI.md`, `minimum_reproducible_example.md`, and `CLA.md` are all relative to this file's location.

**Comment by glenn-jocher** [comment]
@Burhan-Q got it, thank you!

**Comment by glenn-jocher** [comment]
@Burhan-Q I've simplified this by

1. Updating all docs contributing page URLs to absolute web URLs for commonality.
2. Copying the web guide to the local guide
3. Simply replacing "===" with "####" and de-indenting the examples to translate from MkDocs flavored markdown to GitHub flavored markdown. 

Both pages should be near-identical now, URLs are synced to absolute web (better for backlinks).

**Review by glenn-jocher — APPROVED** [review]

**Pull request merged**
