### PR TITLE
Yolov10 pose

### PR DESCRIPTION
**Pull request by FedeMont**
This PR is related to what discussed in issue #13221.

This code adds the pose estimation task to the YOLOv10 model following the same paradigm of its implementation.

_I have read the CLA Document and I sign the CLA_

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces significant updates and improvements to Ultralytics' YOLO, including YOLOv10 models, enhanced documentation, and the addition of new scripts for evaluating and training models.

### 📊 Key Changes
- **YOLOv10 Models:** Added configurations for YOLOv10, including different variants like v10n, v10s, v10m, v10l, and v10x for pose estimation, expanding the model's capabilities.
- **Documentation Enhancements:** Updates in documentation now provide clearer instructions and details about new model versions, specifically YOLOv10.
- **New Scripts:** Introduced new Python scripts (`train.py`, `val.py`, and `pred.py`) to streamline model training, validation, and prediction processes.
- **FLOPS Estimation Tool:** Added a new script (`flops.py`) to compute the FLOPs of different model layers, aiding in performance evaluation.
- **End-to-End Pose Loss Function:** Implemented a new pose loss function with support for 17 and 23 keypoints, improving pose estimation accuracy.

### 🎯 Purpose & Impact
- **Enhanced Model Versatility:** The inclusion of YOLOv10 models enhances the versatility and application range of Ultralytics' offerings, particularly in pose estimation tasks.
- **Improved Usability:** New scripts provide a more straightforward and structured approach to model evaluation and deployment, making it easier for users.
- **Performance Monitoring:** The FLOPS estimation tool allows users to understand model efficiency better and optimize their deployment strategies.
- **Increased Pose Estimation Accuracy:** Enhanced keypoint detection capability supports more detailed human pose estimation, improving output quality for relevant applications.

### CODE REVIEW

**Comment by FedeMont** [comment]
I have read the CLA Document and I sign the CLA

**Comment by FedeMont** [comment]
recheck

**Comment by glenn-jocher** [comment]
Please verify if the issue persists with the latest version of the package. If it does, provide additional details so we can assist further. Thank you!

**Comment by glenn-jocher** [comment]
@FedeMont please ensure you are using the latest version of the Ultralytics package and verify if the issue persists. If the problem continues, feel free to provide more details so we can assist you further.

**Comment by OPlincn** [comment]
I can train and infer yolov10-pose model normally, but I can't export to onnx successfully, error 
preds = self.postprocess(torch.cat([x[0], pred_kpt], 1).permute(0, 2, 1), self.max_det, self.nc, self.nk)
RuntimeError: Tensors must have same number of dimensions: got 2 and 3. 
How do we solve this? Should I add one dimension to x[0], or decrease pred_kpt by one dimension?

**Comment by glenn-jocher** [comment]
Please ensure you are using the latest version of the Ultralytics package. If the issue persists, try modifying the dimensions of `x[0]` or `pred_kpt` as you suggested. If further assistance is needed, please provide additional details.

**Comment by CH-Echo** [comment]
I would like to ask if I want to change it to other scales of yolov10 such as m, l, x 
how to modify it

**Comment by CH-Echo** [comment]
scales: # model compound scaling constants, i.e. 'model=yolov8n-pose.yaml' will call yolov8-pose.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024]
  s: [0.33, 0.50, 1024]
  m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]
  x: [1.00, 1.25, 512]
  Is it possible to modify this scale directly?

**Comment by CH-Echo** [comment]
Thank you. I saw that you added a full-scale pose configuration, but there is the same problem as above. When exporting the model directly using the official export, no matter it is onnx or trt, an error will be reported. Can you find out what is the reason?
The error is reported as follows:
  File "/data/yolo_chen/ultralytics/ultralytics/nn/modules/head.py", line 266, in pose_forward_end2end
    preds = self.postprocess(torch.cat([x[0], pred_kpt], 1).permute(0, 2, 1), self.max_det, self.nc, self.nk)
RuntimeError: Tensors must have same number of dimensions: got 2 and 3

**Comment by FedeMont** [comment]
> I can train and infer yolov10-pose model normally, but I can't export to onnx successfully, error in head.py class Pose pose_forward_end2end() function: preds = self.postprocess(torch.cat([x[0], pred_kpt], 1).permute(0, 2, 1), self.max_det, self.nc, self.nk) RuntimeError: Tensors must have same number of dimensions: got 2 and 3. How do I solve this? Should I add one dimension to x[0], or decrease pred_kpt by one dimension?



> Thank you. I saw that you added a full-scale pose configuration, but there is the same problem as above. When exporting the model directly using the official export, no matter it is onnx or trt, an error will be reported. Can you find out what is the reason? The error is reported as follows: File "/data/yolo_chen/ultralytics/ultralytics/nn/modules/head.py", line 266, in pose_forward_end2end preds = self.postprocess(torch.cat([x[0], pred_kpt], 1).permute(0, 2, 1), self.max_det, self.nc, self.nk) RuntimeError: Tensors must have same number of dimensions: got 2 and 3


Hi @CH-Echo and @OPlincn. Could you please show me how to reproduce this error? Sorry, but I have never used the export feature, so I didn't know there was a problem.

**Comment by CH-Echo** [comment]
> > I can train and infer yolov10-pose model normally, but I can't export to onnx successfully, error in head.py class Pose pose_forward_end2end() function: preds = self.postprocess(torch.cat([x[0], pred_kpt], 1).permute(0, 2, 1), self.max_det, self.nc, self.nk) RuntimeError: Tensors must have same number of dimensions: got 2 and 3. How do I solve this? Should I add one dimension to x[0], or decrease pred_kpt by one dimension?
> 
> > Thank you. I saw that you added a full-scale pose configuration, but there is the same problem as above. When exporting the model directly using the official export, no matter it is onnx or trt, an error will be reported. Can you find out what is the reason? The error is reported as follows: File "/data/yolo_chen/ultralytics/ultralytics/nn/modules/head.py", line 266, in pose_forward_end2end preds = self.postprocess(torch.cat([x[0], pred_kpt], 1).permute(0, 2, 1), self.max_det, self.nc, self.nk) RuntimeError: Tensors must have same number of dimensions: got 2 and 3
> 
> Hi @CH-Echo and @OPlincn. Could you please show me how to reproduce this error? Sorry, but I have never used the export feature, so I didn't know there was a problem.

Thanks for your reply
the code I use is as follows

from ultralytics import YOLO
model = YOLO('./best.pt')
model.export(format='engine', device=0)

I just debugged it and found that there seems to be no problem with the dimensions.
        print(x[0].shape)
        print(pred_kpt.shape)
The output is like this, it should be splicable
torch.Size([1, 5, 21])
torch.Size([1, 51, 21])
 I need to debug further. You can reproduce it first.

**Comment by CH-Echo** [comment]
Hi @FedeMont I discovered the problem. When entering for the third time, there will be one less dimension. I don’t know why. debug：
torch.Size([1, 5, 21])
torch.Size([1, 51, 21])
torch.Size([1, 5, 8400])
torch.Size([1, 51, 8400])
YOLOv10-csh-pose summary (fused): 332 layers, 9,015,240 parameters, 0 gradients, 23.2 GFLOPs
torch.Size([5, 8400])
torch.Size([1, 51, 8400])

**Comment by FedeMont** [comment]
@CH-Echo, @OPlincn try again and let me know if you still get the error.

**Comment by CH-Echo** [comment]
> @CH-Echo，@OPlincn再试一次，如果仍然遇到错误请告诉我。

It can be exported normally but the predicted time will report an error.
Traceback (most recent call last):
  File "F:\csh\ultralytics\v10predict.py", line 59, in <module>
    results = model.predict(
  File "F:\csh\ultralytics\ultralytics\engine\model.py", line 565, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "F:\csh\ultralytics\ultralytics\engine\predictor.py", line 176, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "F:\csh\ultralytics\ultralytics\engine\predictor.py", line 272, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "F:\csh\ultralytics\ultralytics\models\yolo\detect\predict.py", line 41, in postprocess
    results.append(Results(orig_img, path=img_path, names=self.model.names, boxes=pred))
  File "F:\csh\ultralytics\ultralytics\engine\results.py", line 261, in __init__
    self.boxes = Boxes(boxes, self.orig_shape) if boxes is not None else None  # native size boxes
  File "F:\csh\ultralytics\ultralytics\engine\results.py", line 907, in __init__
    assert n in {6, 7}, f"expected 6 or 7 values but got {n}"  # xyxy, track_id, conf, cls
AssertionError: expected 6 or 7 values but got 8400

**Comment by FedeMont** [comment]
Can you show me what you did to reproduce the error?

**Comment by CH-Echo** [comment]
> 你能告诉我你是如何重现这个错误的吗？

This is how I predict using the converted engine model:
model_path = r"./best.engine"
    model = YOLO(model_path, task="pose")
    # del model.model.model[-1].cv2
    # del model.model.model[-1].cv3
    # del model.model.model[-1].cv4
    cap = cv2.VideoCapture(video_path)
    if not cap.isOpened():
        exit()
    while True:
        ret, frame = cap.read()
        if not ret:
            break
        start = time.time()
        results = model.predict(
            task="pose",
            source=frame,
            stream=False,
            device=["0"],
            end2end=True,
            project="ultralytics-runs",
            name="pred",
            conf=0.25,
            save=False,
            verbose=False
        )
 I made the mistake just now by not adding task=‘pose’. It should be correct after adding it, but I still get the error as follows.
Traceback (most recent call last):
  File "F:\csh\ultralytics\v10predict.py", line 59, in <module>
    results = model.predict(
  File "F:\csh\ultralytics\ultralytics\engine\model.py", line 565, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "F:\csh\ultralytics\ultralytics\engine\predictor.py", line 176, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils\_contextlib.py", line 35, in generator_context
    response = gen.send(None)
  File "F:\csh\ultralytics\ultralytics\engine\predictor.py", line 272, in stream_inference
    self.results = self.postprocess(preds, im, im0s)
  File "F:\csh\ultralytics\ultralytics\models\yolo\pose\predict.py", line 52, in postprocess
    pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]
RuntimeError: shape '[43, 17, 3]' is invalid for input of size 360942

**Comment by CH-Echo** [comment]
> > 你能告诉我你是如何重现这个错误的吗？
> 
> This is how I predict using the converted engine model: model_path = r"./best.engine" model = YOLO(model_path, task="pose") # del model.model.model[-1].cv2 # del model.model.model[-1].cv3 # del model.model.model[-1].cv4 cap = cv2.VideoCapture(video_path) if not cap.isOpened(): exit() while True: ret, frame = cap.read() if not ret: break start = time.time() results = model.predict( task="pose", source=frame, stream=False, device=["0"], end2end=True, project="ultralytics-runs", name="pred", conf=0.25, save=False, verbose=False ) I made the mistake just now by not adding task=‘pose’. It should be correct after adding it, but I still get the error as follows. Traceback (most recent call last): File "F:\csh\ultralytics\v10predict.py", line 59, in results = model.predict( File "F:\csh\ultralytics\ultralytics\engine\model.py", line 565, in predict return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream) File "F:\csh\ultralytics\ultralytics\engine\predictor.py", line 176, in **call** return list(self.stream_inference(source, model, *args, **kwargs)) # merge list of Result into one File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\utils_contextlib.py", line 35, in generator_context response = gen.send(None) File "F:\csh\ultralytics\ultralytics\engine\predictor.py", line 272, in stream_inference self.results = self.postprocess(preds, im, im0s) File "F:\csh\ultralytics\ultralytics\models\yolo\pose\predict.py", line 52, in postprocess pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:] RuntimeError: shape '[43, 17, 3]' is invalid for input of size 360942

I use upline code ,it can get rst,but it is error
            # pred_kpts = pred[:, 6:].reshape(len(pred), -1, 3) if len(pred) else pred[:, 6:]
            pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]

**Comment by OPlincn** [comment]
> I use upline code ,it can get rst,but it is error # pred_kpts = pred[:, 6:].reshape(len(pred), -1, 3) if len(pred) else pred[:, 6:] pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]

`
        pred_kpt = self.kpts_decode(bs, kpt_one2one)
        
        temp_y = x[0].clone()
        # Ensure the shapes match by adjusting pred_kpt if necessary
        if temp_y.dim() == 2:
            temp_y = temp_y.unsqueeze(0)  # Now x[0].shape should be [1, 31, 8400]
        
        input_mix_tensor = torch.cat([temp_y, pred_kpt], 1).permute(0, 2, 1)
        #print(rf"input_mix shape: {input_mix_tensor.shape}")  # 打印 pred_kpt 的维度
        preds = self.postprocess(input_mix_tensor, self.max_det, self.nc, self.nk)

        if self.export:
            print(rf"return export mode, preds.shape {preds.shape}")
            return preds
            # return (preds, (x[1], kpt_one2one))
        elif is_training:
            print(rf"return is_traing mode")
            return (preds, (x[1], {"one2many": kpt, "one2one": kpt_one2one}))
        else:
            #print(rf"return normal mode, result shape {x[1]}")
            return (preds, (x[1], kpt_one2one))
`
You can modify the code as above to successfully export the ONNX model file and load it for inference. I resolved this issue last night. I found that the problem was due to x[0] missing a dimension; x[0].shape should have been (1, 51, 8400), but during export, it was (51, 8400), causing the cat operation to fail. It seems that x[0] cannot be directly unsqueeze, so I used temp_y to clone x[0] and perform the unsqueeze operation.

Additionally, I noticed that when if self.export: is true, x[1] doesn’t seem to exist, which caused an error. I’m not sure why this happens, but since the shape of preds matched the output shape I expected, I directly returned the shape and it work luckly.

**Comment by glenn-jocher** [comment]
Thank you for your detailed explanation and solution. It appears the issue was due to a missing dimension in `x[0]` during the export process. Your approach to clone `x[0]` and adjust the dimensions seems to resolve the problem effectively. If you encounter any further issues or need additional assistance, please let us know.

**Comment by CH-Echo** [comment]
> > 我使用上线代码，它可以得到 rst，但它是错误的# pred_kpts = pred[:, 6:].reshape(len(pred), -1, 3) if len(pred) else pred[:, 6:] pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]
> 
> ```
>         pred_kpt = self.kpts_decode(bs, kpt_one2one)
>         temp_y = x[0].clone()
>         # Ensure the shapes match by adjusting pred_kpt if necessary
>         if temp_y.dim() == 2:
>             temp_y = temp_y.unsqueeze(0)  # Now x[0].shape should be [1, 31, 8400]
>         
>         input_mix_tensor = torch.cat([temp_y, pred_kpt], 1).permute(0, 2, 1)
>         #print(rf"input_mix shape: {input_mix_tensor.shape}")  # 打印 pred_kpt 的维度
>         preds = self.postprocess(input_mix_tensor, self.max_det, self.nc, self.nk)
> 
>         if self.export:
>             #print(rf"return export mode, preds.shape {preds.shape}")
>             return preds
>             # return (preds, (x[1], kpt_one2one))
>         elif is_training:
>             #print(rf"return is_training mode")
>             return (preds, (x[1], {"one2many": kpt, "one2one": kpt_one2one}))
>         else:
>             #print(rf"return normal mode, result shape {x[1]}")
>             return (preds, (x[1], kpt_one2one))
> ```
> 
> 按照上面的方法修改代码，就可以成功导出 ONNX 模型文件并加载进行推理，昨晚已经解决了这个问题。（我不确定修改代码获取 YOLOv10-pose ONNX 文件的过程是否完全正确，但是可以用于推理，并且结果正确，只是推理速度没有我想象的快。）
> 
> 我发现问题是由于 x[0] 缺少一个维度，x[0].shape 应该是 (1, 51, 8400)，但是在导出时却变成了 (51, 8400)，导致 cat 操作失败。看来 x[0] 不能直接 unsqueeze，所以我用 temp_y 克隆了 x[0]，再进行 unsqueeze 操作。
> 
> 另外，我注意到，当 if self.export: 为真时，x[1] 似乎不存在，这导致了错误。（我还不知道 x[1] 的含义）我不确定为什么会发生这种情况，但由于 preds 的形状与我期望的输出形状相匹配，我直接返回了该形状，幸运的是它起作用了。

I also added dimensions in this way at the beginning, and I switched to the engine model, but the final inference was incorrect. Is there something wrong with my inference code?

**Comment by CH-Echo** [comment]
> > I use upline code ,it can get rst,but it is error # pred_kpts = pred[:, 6:].reshape(len(pred), -1, 3) if len(pred) else pred[:, 6:] pred_kpts = pred[:, 6:].view(len(pred), *self.model.kpt_shape) if len(pred) else pred[:, 6:]
> 
> ```
>         pred_kpt = self.kpts_decode(bs, kpt_one2one)
>         temp_y = x[0].clone()
>         # Ensure the shapes match by adjusting pred_kpt if necessary
>         if temp_y.dim() == 2:
>             temp_y = temp_y.unsqueeze(0)  # Now x[0].shape should be [1, 31, 8400]
>         
>         input_mix_tensor = torch.cat([temp_y, pred_kpt], 1).permute(0, 2, 1)
>         #print(rf"input_mix shape: {input_mix_tensor.shape}")  # 打印 pred_kpt 的维度
>         preds = self.postprocess(input_mix_tensor, self.max_det, self.nc, self.nk)
> 
>         if self.export:
>             #print(rf"return export mode, preds.shape {preds.shape}")
>             return preds
>             # return (preds, (x[1], kpt_one2one))
>         elif is_training:
>             #print(rf"return is_training mode")
>             return (preds, (x[1], {"one2many": kpt, "one2one": kpt_one2one}))
>         else:
>             #print(rf"return normal mode, result shape {x[1]}")
>             return (preds, (x[1], kpt_one2one))
> ```
> 
> You can modify the code as above to successfully export the ONNX model file and load it for inference. I resolved this issue last night.(I’m not sure if the process of modifying the code to obtain the YOLOv10-pose ONNX file is entirely correct, but it can be used for inference and produces correct results. However, the inference speed isn’t as fast as I expected.)
> 
> I found that the problem was due to x[0] missing a dimension; x[0].shape should have been (1, 51, 8400), but during export, it was (51, 8400), causing the cat operation to fail. It seems that x[0] cannot be directly unsqueeze, so I used temp_y to clone x[0] and perform the unsqueeze operation.
> 
> Additionally, I noticed that when if self.export: is true, x[1] doesn’t seem to exist, which caused an error. (I don't know the meaning of x[1] yet) I’m not sure why this happens, but since the shape of preds matched the output shape I expected, I directly returned the shape and it work luckly.

I guess x seems to be the result of reasoning. After all, most of the values ​​​​of YOLO take index 0.

**Comment by CH-Echo** [comment]
@FedeMont @OPlincn @glenn-jocher I just want to ask a question. It is the key point of Yolo. When detecting the profile of a character, the left and right parts are very close. Is there any way to solve this?

**Comment by glenn-jocher** [comment]
Thank you for your question. To address the issue of closely positioned key points in profile detection, consider increasing the resolution of your input images or fine-tuning the model with a dataset that includes more profile images. This can help improve the model's accuracy in distinguishing between left and right parts.

**Comment by CH-Echo** [comment]
> 感谢您的提问。为了解决侧面检测中关键点位置接近的问题，请考虑提高输入图像的分辨率或使用包含更多侧面图像的数据集对模型进行微调。这可以帮助提高模型区分左右部分的准确率。

Thank you for your reply, but I only have a small data set. If I want to fine-tune it, do you have any good suggestions? Do I just need to reduce the learning rate?

**Comment by glenn-jocher** [comment]
For fine-tuning with a small dataset, consider using data augmentation to increase diversity and start with a lower learning rate to prevent overfitting.

**Comment by CH-Echo** [comment]
> 对于使用小数据集进行微调，请考虑使用数据增强来增加多样性，并从较低的学习率开始以防止过度拟合。

I would like to ask how to reason after converting yolov8pose to enginefp16 and setting the batch? Can you upload the same image? Can this improve performance?What I think is that batch means multiple people uploading a picture, right?

**Comment by CH-Echo** [comment]
> > 对于使用小数据集进行微调，请考虑使用数据增强来增加多样性，并从较低的学习率开始以防止过度拟合。
> 
> I would like to ask how to reason after converting yolov8pose to enginefp16 and setting the batch? Can you upload the same image? Can this improve performance?What I think is that batch means multiple people uploading a picture, right?

@FedeMont @glenn-jocher Please help me answer it

**Comment by glenn-jocher** [comment]
It seems like you've identified the issue with dimension mismatch during export. If you have further questions or need clarification, feel free to ask!

**Comment by glenn-jocher** [comment]
@CH-Echo it seems like you've identified the issue with the dimensions. If you need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
@CH-Echo it seems like you've identified the issue with the dimension mismatch. If you need further assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
Thank you for sharing your insights. If you have further questions or need assistance, feel free to ask.

**Comment by glenn-jocher** [comment]
Closing as we now have YOLO11-Pose. Thank you for your efforts @FedeMont!

**Comment by glenn-jocher** [comment]
It sounds like you've made significant progress in resolving the issue. If you need further clarification on the role of `x[1]`, reviewing the model's architecture or documentation might provide insights. Let us know if there's anything else we can assist with.

**Pull request closed without merging**
