### PR TITLE
Harsha open source 

### PR DESCRIPTION
**Pull request by SaiNithinn**
### Summary
:sparkles::computer::memo:

This pull request adds a new feature of an interactive interface for the YOLOV8 model, implemented in `main.py` and documented in `README.md`. The interface allows users to upload, convert, and download images using different YOLOV8 models for object detection, classification, pose estimation, and segmentation. The interface depends on the `ultralytics` library and the model files in the repository.

> _`main.py` adds GUI_
> _YOLOV8 models in action_
> _Autumn leaves of code_

### Walkthrough
*  Add a new file `main.py` that contains the code for the interactive interface for the YOLOV8 model ([link](https://github.com/ultralytics/ultralytics/pull/3272/files?diff=unified&w=0#diff-b10564ab7d2c520cdd0243874879fb0a782862c3c902ab535faabe57d5a505e1R1-R207))
*  Update the README.md file to describe the new feature and the libraries used to implement it ([link](https://github.com/ultralytics/ultralytics/pull/3272/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R21-R22))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduced a new user-friendly graphical interface for YOLOv8 to simplify object detection tasks.

### 📊 Key Changes
- Added `YOLOV8_GUI`, a graphical user interface using Tkinter.
- Provides easy options to input images/videos and configure detection parameters.
- New `main.py` script with GUI functionalities for uploading, detecting, classifying, posing, and segmenting objects.

### 🎯 Purpose & Impact
- **Enhances Accessibility**: Makes YOLOv8 more accessible to non-technical users by providing a simple interface. 🖥️
- **Encourages Community Contribution**: Open-source nature encourages enhancements and bug fixes from the community. 🤝
- **Broader Audience Reach**: Aims to engage more users including researchers and enthusiasts by simplifying complex processes. 🌍

### CODE REVIEW

**Comment by SaiNithinNartuo** [comment]
recheck

**Comment by glenn-jocher** [comment]
@SaiNithinNartuo thank you for the PR! This would be best placed in the examples/ directory. Can you show screenshots of what this looks like?

**Comment by HarshaVardhanYellanki** [comment]
I have read the CLA Document and I sign the CLA

**Comment by HarshaVardhanYellanki** [comment]
> @SaiNithinNartuo thank you for the PR! This would be best placed in the examples/ directory. Can you show screenshots of what this looks like?
YOLO GUI 1
YOLO GUI 2

Yeah sure!!!

**Comment by SaiNithinNartuo** [comment]
> @SaiNithinNartuo thank you for the PR! This would be best placed in the examples/ directory. Can you show screenshots of what this looks like?

Sir see the pictures that my friend shared

**Comment by AyushExel** [comment]
@SaiNithinNartuo hey, thanks for the PR. This looks great, can you add it to the the Examples/ folder instead of the main repo? Thanks!

**Comment by HarshaVardhanYellanki** [comment]
> @SaiNithinNartuo hey, thanks for the PR. This looks great, can you add it to the the Examples/ folder instead of the main repo? Thanks!

Yeah done sir

**Comment by glenn-jocher** [comment]
@HarshaVardhanYellanki, Thanks for your swift response, really appreciate your efforts! It's great to know that the changes have been moved to the Examples/ folder. Could you please push these updates to your remote branch so that I can review them? Let me know if you need any further assistance.

**Comment by SaiNithinNartuo** [comment]
> @HarshaVardhanYellanki, Thanks for your swift response, really appreciate your efforts! It's great to know that the changes have been moved to the Examples/ folder. Could you please push these updates to your remote branch so that I can review them? Let me know if you need any further assistance.

Yes sir, made necessary updates. You could review now and let me know your response.

**Comment by SaiNithinNartuo** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@SaiNithinNartuo, thanks for signing the CLA. We appreciate your contribution to the open source community and to the YOLOv8 project. Your pull request is important to us. We will review it as soon as possible. In the meanwhile, if you have any questions or require any assistance, feel free to ask. Thanks again for your contribution!

**Review by ambitious-octopus — COMMENTED** [review]
We already have `yolo streamlit-predict`, I don't think we need another GUI. Closing.
cc @RizwanMunawar

**Pull request closed without merging**
