### PR TITLE
Corrected mistakes in README.md

### PR DESCRIPTION
**Pull request by izam-mohammed**
Corrected some spelling mistakes and grammar mistakes in README.md file.

Eg :- replaced the word 'intallation' with the correct word 'installation'

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved documentation for readability and corrected a typo in the README.

### 📊 Key Changes
- Amended a phrase for grammatical accuracy from "quickstart intallation" to "a quickstart installation."
- Fixed the spelling of "visualize" from "visualise" for consistency with American English.

### 🎯 Purpose & Impact
- Enhances clarity of the installation process description, making it easier for new users to follow.
- Corrected spelling supports uniformity in documentation, aiding in professional presentation and readability.

### CODE REVIEW

**Comment by izam-mohammed** [comment]
I have read the CLA Document and I sign the CLA

**Comment by izam-mohammed** [comment]
recheck

**Comment by izam-mohammed** [comment]
I only corrected some grammar and spelling mistakes. Didn't even touches the core files.Then why showing this test fail ??????

**Comment by glenn-jocher** [comment]
@izam-mohammed CI looks all good. Thank you for your contributions!

**Comment by izam-mohammed** [comment]
I wonder how can I become a member of Ultralytic's Github page as well as the company ???

**Pull request merged**
