### PR TITLE
Create pyproject.toml

### PR DESCRIPTION
**Pull request by Zengyf-CVer**
I have read the CLA Document and I sign the CLA

### Summary
:wrench::art::no_entry_sign:

Add ruff configuration to `pyproject.toml` to ignore line length rule. This allows the code to follow the ultralytics style guide.

> _`ruff` tool config_
> _ignores long lines in Python_
> _autumn leaves its mark_

### Walkthrough
*  Configure ruff tool to ignore E501 rule ([link](https://github.com/ultralytics/ultralytics/pull/1823/files?diff=unified&w=0#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711R1-R4))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added a `pyproject.toml` file to the project to configure code formatting rules, specifically ignoring certain style violations.

### 📊 Key Changes
- Introduced a `pyproject.toml` file.
- Configured `ruff` to ignore `E501` (line length) rule.

### 🎯 Purpose & Impact
- **Purpose**: Streamlines code formatting by allowing exceptions for line length readability.
- **Impact**: Makes collaboration smoother by relaxing some style constraints, improving code legibility. 📏👥

### CODE REVIEW

**Comment by Zengyf-CVer** [comment]
@glenn-jocher The premise of verifying this PR is that I need you to pass this PR: https://github.com/ultralytics/ultralytics/pull/1824

**Comment by glenn-jocher** [comment]
@Zengyf-CVer hello, thank you for submitting your PR. Before we can merge it, we need to ensure that it meets our code standards and requirements. 
To do this, we will carefully review the changes you've proposed and provide feedback as needed. Keep in mind that our goal is 
to maintain a high-quality codebase and ensure that all contributions are in line with our project's goals and objectives. 
Thanks for your patience and understanding!

**Comment by glenn-jocher** [comment]
@Zengyf-CVer hi! After taking a look at this I see it adds a project toml file to the project root directory. Can you explain what this does and the thinking behind it?

**Comment by Zengyf-CVer** [comment]
@glenn-jocher This toml file is functionally equivalent to setup.cfg, but some pre-commit components need to run in the toml file.

**Comment by Zengyf-CVer** [comment]
@glenn-jocher You can refer to the documentation of this project: https://github.com/pyscript/pyscript/blob/main/pyproject.toml

**Comment by glenn-jocher** [comment]
@Zengyf-CVer I understand now, thank you for explaining. So as you mentioned, the pyproject.toml file contains configuration for pre-commit hooks 
that the project uses. These hooks enable automated checks for things like code formatting, syntax errors, and best practices. Adding 
this file to the project allows us to automate some of these tasks and ensure that our code is always in a consistent and clean state.

**Comment by glenn-jocher** [comment]
@Zengyf-CVer maybe I'm not understanding well, but I'm not sure the 3 PRs here are a net benefit to most users or help with the core repo purpose of training and deploying YOLO models. Would the changes be better suited for a fork of YOLOv8 perhaps?

**Review by ambitious-octopus — COMMENTED** [review]
We just have a `pyproject.toml`, closing.

**Pull request closed without merging**
