### PR TITLE
MPS unified memory cache empty 

### PR DESCRIPTION
**Pull request by Oil3**
Hi,
a bold claim.

Using `torch.mps.empty_cache() `for macOS with MPS device, drastically betters memory management: I found out when I realized the duration of my single class, yolov8, 8000 images, 45000 objects training , was massively reduced, nearly 50% (40% speed increase).

I did some test with default settings and 9000 augmented images generated from the 4 "coco" images dataset, and the results showed a significant, `25% speed increase` (30% duration reduction) starting from epoch 2.
Screenshot 2024-08-31 at 13 26 54
Screenshot 2024-08-31 at 16 34 34

image

I had previously made a long message to explain the two aspects of macOS' unified memory administration of virtual memory, but let's make it short:
vmem can be considered unlimited,
vmem "chunks" double in size each time

This causes issues because it's not flushed, it's not unlimited, it's much slower.

My understanding of the effects of the change, is that when emptying the cache, unneeded RAM is freed, which reduces the needs for virtual memory.

As usual with me, it's two lines of code.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced memory management for MacOS users to improve training performance and stability.

### 📊 Key Changes
- Added a conditional check for MacOS to use `torch.mps.empty_cache()` for memory clearing.
- Retained `torch.cuda.empty_cache()` for non-MacOS platforms.

### 🎯 Purpose & Impact
- 🖥️ Improves GPU memory management on MacOS devices by optimizing the use of unified memory.
- 🚀 Reduces the likelihood of running out of memory during model training, enhancing stability.
- 📈 Enables better performance and resource utilization for MacOS users, potentially reducing training interruptions.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Oil3 thank you for sharing your findings on using `torch.mps.empty_cache()` to improve training performance on macOS. Your insights into memory management are valuable, and we appreciate your contribution. If you encounter any issues, please ensure you're using the latest version of the package.

**Comment by glenn-jocher** [comment]
@Oil3 this is excellent!! I've cleared the export issues and re-running CI now. Once it's green we can merge into the next release.

**Comment by glenn-jocher** [comment]
@Oil3 PR merged! 

Awesome work on this one, I'll share it with the team!

**Comment by Oil3** [comment]
@glenn-jocher hi to the team and praise to you, amazing project you made!!

**Comment by glenn-jocher** [comment]
Thank you for your kind words! The success of the project is thanks to the incredible YOLO community and the Ultralytics team. If you have any questions or need assistance, feel free to ask!

**Pull request merged**
