### PR TITLE
Add track IDs to save_txt in `track` mode

### LINKED ISSUE #1357: add save_id option for track
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I cannot find the option for saving track id in text file.
I'd like to contribute about this feature.

Let me know if i miss something.
Thank you!

### Use case
```
yolo track source=... save_txt=True
# cls *bbox
yolo track source=... save_txt=True save_id=True
# cls *bbox track_id
yolo track source=... save_txt=True save_id=True save_conf=True
# cls *bbox conf track_id
```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by ZeroAct**
issue #1357

### additional
- if track id is `None` and `save_id` is `True`, tack id is set to `-1`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactoring object detection and segmentation output code for clarity and maintainability.

### 📊 Key Changes
- Unified object IDs across detection and segmentation by creating a single line of code for generating these IDs.
- Simplified file writing code by streamlining the formation of the line to be written, considering whether an object ID is present.
- Improved annotation code by using a more concise way to generate labels, including the object ID if available.

### 🎯 Purpose & Impact
- **Enhanced Code Readability:** Refactored code is more readable and easier to maintain, helping developers understand and modify the code base.
- **Consistency Across Modules:** A consistent way of handling object IDs simplifies the integration of different data types (detection and segmentation) within the same framework.
- **Flexibility:** The changes allow for future adjustments in how data is exported and visualized without extensive code restructuring.
- **Non-disruptive to Users:** These internal code changes have minimal to no immediate impact on the end user experience but lay the groundwork for future improvements.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@ZeroAct ok I've made some cleanups. I think we should output track IDs to txt automatically in track mode. This makes the most sense, and this way we can avoid adding additional arguments to default.yaml, which is already quite long.

**Comment by glenn-jocher** [comment]
@ZeroAct @Laughing-q actually this is a good question, if tracking can a track ID be equal to None?

**Comment by glenn-jocher** [comment]
@ZeroAct PR merged into updates branch for 8.0.54 tomorrow. Thank you for your contributions!

**Comment by ZeroAct** [comment]
@glenn-jocher 
It looks more simple and clear!
Thank you.

**Comment by ZeroAct** [comment]
@glenn-jocher 
I have discovered that the track ID field may be `None`, which means that the resulting text file could contain a variable number of items.

I tested on two video with following queries.
```
# works fine
yolo track tracker=bytetrack.yaml model=yolov8m.pt imgsz=640 save=True save_txt=True save_conf=True project=track_test name=track_test vid_stride=10 source=https://www.youtube.com/watch?v=ORrrKXGx2SE

# no track ID (first frame has track ID, and following frames do not have track ID)
yolo track tracker=bytetrack.yaml model=yolov8m.pt imgsz=640 save=True save_txt=True save_conf=True project=track_test name=track_test vid_stride=10 source=https://www.youtube.com/watch?v=-d_iBRRVlVE
```

**Pull request merged**
