### PR TITLE
New yolov8 practical application with streamlit

### PR DESCRIPTION
**Pull request by Taoheed-O**
Added a new application folder to the examples folder in the repo.
This application makes use of the YOLO pre-trained model as a detector used in an app created with the streamlit library.
    _I have read the CLA Document and I hereby sign the CLA_

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
A new example application for object detection using YOLO models is added to the repository.

### 📊 Key Changes
- **New Example App:** Added a Streamlit-based application for object detection using YOLOv3 and YOLOv8.
- **Functionality:** Supports image, video, and webcam detection.
- **UI Components:** Utilizes Streamlit options for user interaction and model configuration.
- **Helper Functions:** Includes helpers for loading models and displaying detection results.
- **Documentation:** Basic instructions provided in the README for setup and usage.

### 🎯 Purpose & Impact
- **Purpose:** To provide a user-friendly application as an example for real-time object detection using YOLO models.
- **Impact:** Simplifies the setup and demonstration of object detection capabilities, making it accessible to both developers and non-technical users. 🖼️📹📷

### CODE REVIEW

**Comment by AyushExel** [comment]
Thanks man!
Please also link a demo, maybe just upload the video you used on Linkedin

**Comment by Taoheed-O** [comment]
here is a demo.

https://github.com/ultralytics/ultralytics/assets/64612602/f9d2bc12-810a-4682-9516-f37b32324f3d

**Comment by Taoheed-O** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Taoheed-O** [comment]
pre-commit.ci autofix

**Comment by AyushExel** [comment]
please fix pre-commit

**Comment by Taoheed-O** [comment]
pre-commit.ci autofix

**Comment by Taoheed-O** [comment]
fixed

**Comment by glenn-jocher** [comment]
@Taoheed-O great, thanks for the update! 👍 If there's anything else that needs attention, feel free to reach out.

**Comment by glenn-jocher** [comment]
@AyushExel can you review this PR and see if the streamlit usage looks good?

**Comment by AyushExel** [comment]
I will review it this weekend

**Comment by glenn-jocher** [comment]
Absolutely, take your time! If you have any questions or need further clarification while reviewing, feel free to reach out. Happy reviewing! 😊

**Comment by RizwanMunawar** [comment]
@Taoheed-O Hi, thanks for your PR! It’s a great idea, but we added support for the Streamlit application last month. You can run it directly using the CLI command `yolo streamlit-predict`.

For now, we don’t need a similar application. However, I recommend checking out [Ultralytics Streamlit Inference](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/solutions/streamlit_inference.py), and feel free to submit new PRs if you spot any issues or see opportunities for optimization in the existing Streamlit application.

I am closing this PR and we are looking forward to reviewing your future contributions!

Best regards,  
The Ultralytics Team

**Pull request closed without merging**
