### PR TITLE
`ultralytics 8.1.37` fix empty `sys.argv` bug

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced system arguments handling in Ultralytics software components.

### 📊 Key Changes
- Introduced a fallback for `sys.argv` to prevent issues when it's empty.
- Updated version number from 8.1.36 to 8.1.37.
- Improved argument parsing reliability across the system.
- Unified approach to detect and manage command-line interface (CLI) operations.

### 🎯 Purpose & Impact
- 🛠 **Stability Increase**: The fix ensures the system behaves predictably even if `sys.argv` is unexpectedly empty, avoiding potential crashes or undefined behaviors. This is critical for both direct users and automated systems interacting with Ultralytics software.
- 🔄 **Consistency Across Environments**: By seamlessly adapting to situations where `sys.argv` might be empty (e.g., during certain types of automated executions or unconventional startup scenarios), this update makes the software more robust and consistent, regardless of the operating environment.
- 👥 **User and Developer Experience**: This change might go unnoticed by many users, but it significantly improves the experience for those working in specific environments or with custom setups by ensuring functionality remains intact. Developers will find debugging and custom integration tasks simpler, with less risk of encountering edge-case errors related to system argument handling.

### CODE REVIEW

**Comment by TurbineJoshua** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@TurbineJoshua I'm expanding the sys.argv safety around the repo to all the places it's used. I think this should work as sys.argv should not change. Here I'm only reading it once, making it safe and then importing it everywhere else.

**Comment by TurbineJoshua** [comment]
> @TurbineJoshua I'm expanding the sys.argv safety around the repo to all the places it's used. I think this should work as sys.argv should not change. Here I'm only reading it once, making it safe and then importing it everywhere else.

This makes total sense to me - thank you for doing this. [Even Guido agrees](https://github.com/python/cpython/issues/85781#issuecomment-1093881186). :)

**Comment by glenn-jocher** [comment]
@TurbineJoshua PR merged, will publish as `ultralytics 8.1.37` in a minute.

Let us know if you have any other issues or spot any other areas for improvement :)

**Pull request merged**
