### PR TITLE
Fix `instance` area method format-change bug

### PR DESCRIPTION
**Pull request by Buckler89**
- Updated areas method to optionally revert format after calculation.
https://github.com/ultralytics/ultralytics/issues/10418

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced flexibility in calculating box areas for different formats.

### 📊 Key Changes
- Removed the forced conversion to "xyxy" format when calculating box areas.
- Added direct area calculation support for different bbox formats: "xyxy" and "xywh" or "ltwh".

### 🎯 Purpose & Impact
- **Purpose:** To streamline area calculation by supporting direct calculations in both "xyxy" (corner points) and "xywh" or "ltwh" (width-height formats) without needing to convert between formats.
- **Impact:** Users benefit from more efficient computations and code simplicity, improving performance and usability across various applications involving bounding box operations. 🚀

### CODE REVIEW

**Comment by Buckler89** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Buckler89** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@Buckler89 thanks but we want to solve the bug without introducing additional arguments. Instead of your current implementation please do this:

1. Check the xyxy format
2. If xyxy return the area, otherwise convert a copy to xyxy and then return the area.

**Comment by glenn-jocher** [comment]
@Buckler89 I've updated the PR for faster and simpler area computation that still solves the original issue. Merging now. 

Please let us know if this resolves your original issue, and feel free to submit PRs for any other improvements you spot!

**Pull request merged**
