### PR TITLE
`ultralytics 8.2.91` fix `v10DetectLoss` module rename for YOLOv10

### LINKED ISSUE #13931: AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' >
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

when using yolov10 trained model with below code
```
from ultralytics import YOLO

model = YOLO('myV10Model.pt')
```

It throws error `AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' >`, any ideas?

### Environment

Ultralytics YOLOv8.2.41 🚀 Python-3.8.10 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4090 D, 24209MiB)
Setup complete ✅ (16 CPUs, 125.7 GB RAM, 379.9/1832.2 GB disk)

OS                  Linux-5.15.0-107-generic-x86_64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             git
RAM                 125.68 GB
CPU                 AMD Ryzen 7 5700X 8-Core Processor
CUDA                12.1

numpy               ✅ 1.24.4<2.0.0,>=1.23.5
matplotlib          ✅ 3.5.2>=3.3.0
opencv-python       ✅ 4.6.0.66>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #14072: AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss'>
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

I encountered an `AttributeError` when trying to load my custom-trained YOLOv10x model. However, there is no issue when loading the pre-trained `yolov10s.pt` model.

### Error Message
plaintext
    result = unpickler.load()
(***_env) PS D:\***\***\***\***> & C:/Users/***/anaconda3/envs/***_env/python.exe d:/***/***/***/***.py
Traceback (most recent call last):
  File "d:\***\***\***\***.py", line 4, in <module>
    model = YOLO("yolov10x.pt")
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\engine\model.py", line 149, in __init__
    self._load(model, task=task)
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\engine\model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/anaconda3/envs/***_env\Lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/anaconda3/envs\***_env\Lib\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***/AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\***/AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\***/anaconda3/envs\\***_env\\Lib\\site-packages\\ultralytics\\utils\\loss.py'>

### Environment Information:

Python version: 3.12
Ultralytics version: 8.2.45
Operating System: Windows

```python
from ultralytics import YOLO

# Load a pre-trained YOLOv10 model
model = YOLO("yolov10x.pt")

# Perform object detection on an image
results = model.track(0, save=True, show=True, conf=0.15)

### LINKED ISSUE #14170: AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\JFerreira\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\ultralytics\\utils\\loss.py'
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

PS C:\Users\JFerreira\Desktop\Models\_testing> & C:/Users/JFerreira/AppData/Local/Programs/Python/Python310/python.exe c:/Users/JFerreira/Desktop/Models/_testing/inf_test.py
8.2.48
Traceback (most recent call last):
  File "c:\Users\JFerreira\Desktop\Models\_testing\inf_test.py", line 16, in <module>
    main()
  File "c:\Users\JFerreira\Desktop\Models\_testing\inf_test.py", line 7, in main
    model = ultralytics.YOLO('C:/Users/JFerreira/Desktop/Models/_testing/models/YOLOv10n.pt')
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__       
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 149, in __init__
    self._load(model, task=task)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\engine\model.py", line 230, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load        
    ckpt = torch.load(file, map_location="cpu")
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1025, in load
    return _load(opened_zipfile,
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1446, in _load
    result = unpickler.load()
  File "C:\Users\JFerreira\AppData\Local\Programs\Python\Python310\lib\site-packages\torch\serialization.py", line 1439, in find_class
    return super().find_class(mod_name, name)
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\JFerreira\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\ultralytics\\utils\\loss.py'>
PS C:\Users\JFerreira\Desktop\Models\_testing> 

### Environment

_No response_

### Minimal Reproducible Example

import torch
import ultralytics

def main():
    # Load the trained model
    print(ultralytics.__version__)
    model = ultralytics.YOLO('C:/Users/JFerreira/Desktop/Models/_testing/models/YOLOv10n.pt')

    # Dataset path
    dataset_path = 'C:/Users/JFerreira/Desktop/Models/_testing/test_dataset/airsim.yaml'

    # Run inference on the dataset and gather metrics
    model.val(data=dataset_path)

if __name__ == '__main__':
    main()

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #14676: AttributeError: Can't get attribute 'v10DetectLoss' on module 'ultralytics.utils.loss' from 'path_to_ultralytics/utils/loss.py'
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

I am encountering an issue while trying to run a script with YOLOv10 using UltraLytics. The error traceback is as follows:

The script fails with an AttributeError related to v10DetectLoss in ultralytics.utils.loss.

I have tried multiple versions of torch and torchvision to resolve this issue, but it persists. Any guidance or suggestions to fix this issue would be greatly appreciated.

Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Install the latest PowerShell for new features and improvements! https://aka.ms/PSWindows

PS D:\***\***_tespit\yolov10\***_modelx> & C:/ProgramData/anaconda3/python.exe d:/***/***_tespit/yolov10/***_modelx/yolov10x_tek_camera.py
Traceback (most recent call last):
  File "d:\***\***_tespit\yolov10\***_modelx\yolov10x_tek_camera.py", line 4, in <module>
    model = YOLO("yolov10x.pt")
            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\models\yolo\model.py", line 23, in __init__
    super().__init__(model=model, task=task, verbose=verbose)
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\engine\model.py", line 141, in __init__
    self._load(model, task=task)
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\engine\model.py", line 293, in _load
    self.model, self.ckpt = attempt_load_one_weight(weights)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\nn\tasks.py", line 855, in attempt_load_one_weight
    ckpt, weight = torch_safe_load(weight)  # load ckpt
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\nn\tasks.py", line 781, in torch_safe_load
    ckpt = torch.load(file, map_location="cpu")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1026, in load
    return _load(opened_zipfile,
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1438, in _load
    result = unpickler.load()
             ^^^^^^^^^^^^^^^^
  File "C:\Users\***\AppData\Roaming\Python\Python312\site-packages\torch\serialization.py", line 1431, in find_class
    return super().find_class(mod_name, name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from 'C:\\Users\\***\\AppData\\Roaming\\Python\\Python312\\site-packages\\ultralytics\\utils\\loss.py'>

### Environment
Windows 11 Visual Studi Code

### Minimal Reproducible Example

```Python
from ultralytics import YOLO

# Load a pre-trained YOLOv10x model
model = YOLO("yolov10x.pt")

# Perform object detection on an image or video (0 for webcam)
results = model.track(0, save=True, show=True, conf=0.2)

# Display the results
results[0].show()

### LINKED ISSUE #15957: Hi @JoaoLopesFerreira99,
Hi @JoaoLopesFerreira99,

Thank you for reporting this issue and providing the detailed traceback and code snippet. It looks like you're encountering an `AttributeError` related to the `v10DetectLoss` attribute when attempting to load your YOLOv10 model.

To help us diagnose and resolve this issue more effectively, could you please verify the following:

1. **Ensure Latest Version**: Make sure you are using the latest version of the Ultralytics package. You can update it using:
    ```bash
    pip install --upgrade ultralytics
    ```

2. **Reproducible Example**: It's crucial to have a minimal reproducible example to pinpoint the problem accurately. Your provided code is a great start. Please ensure that the issue persists with the latest package version and provide any additional context if necessary. More details on creating a minimal reproducible example can be found [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

3. **Model Compatibility**: Verify that the model file `YOLOv10n.pt` is compatible with the version of the Ultralytics package you are using. Sometimes, models trained or saved with different versions might have compatibility issues.

Here's a slightly modified version of your script to ensure it aligns with the latest package updates:

```python
import torch
import ultralytics

def main():
    # Print the version of Ultralytics
    print(ultralytics.__version__)

    # Load the trained model
    model = ultralytics.YOLO('C:/Users/JFerreira/Desktop/Models/_testing/models/YOLOv10n.pt')

    # Dataset path
    dataset_path = 'C:/Users/JFerreira/Desktop/Models/_testing/test_dataset/airsim.yaml'

    # Run inference on the dataset and gather metrics
    model.val(data=dataset_path)

if __name__ == '__main__':
    main()
```

If the issue persists after these steps, please let us know. Providing any additional logs or context will be helpful. We appreciate your cooperation and look forward to resolving this issue promptly.

_Originally posted by @glenn-jocher in https://github.com/ultralytics/ultralytics/issues/14170#issuecomment-2205001147_

### LINKED ISSUE #16059: AttributeError: 'YOLOv10DetectionModel' object has no attribute 'args', when trying to access to v10DetectLoss.
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello Ultralytics team,

I am trying to use the base YOLOv10 model in PyTorch for a custom training loop and gain a deeper understanding of how the loss function, specifically ```v10DetectLoss``` (located in ```utils/loss.py```), works. I am initializing the model with the following setup:

```
import torch
from ultralytics.nn.tasks import YOLOv10DetectionModel
from ultralytics.utils import yaml_load, ops
from pathlib import Path
from ultralytics.utils.loss import v10DetectLoss


nc = 7  # num of classes
max_det = 50  # max num of detections per image
model_version = yaml_load(Path("yolov10n.yaml"))
model_version["nc"] = nc
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')
model = YOLOv10DetectionModel(model_version).to(device)
```

However, when I try to instantiate the loss function with the following code:

```
loss_fn = v10DetectLoss(model)
```

I receive the error:
```
AttributeError: 'YOLOv10DetectionModel' object has no attribute 'args'.
```

Could you please help me understand the root cause of this issue and how I can correctly instantiate the ```v10DetectLoss``` function? My goal is to replicate the training logic at a lower level to better comprehend how the loss function operates.

Thank you in advance for your assistance!

Here are the relevant versions of my dependencies:

```
PyTorch: 2.4.0
torchvision: 0.19.0
ultralytics: 8.1.34
numpy: 1.26.4
```

The model yaml file is this one:

```
# Parameters
nc: 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024] 

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, SCDown, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, SCDown, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9
  - [-1, 1, PSA, [1024]] # 10

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 13

  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 16 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 13], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 19 (P4/16-medium)

  - [-1, 1, SCDown, [512, 3, 2]]
  - [[-1, 10], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2fCIB, [1024, True, True]] # 22 (P5/32-large)

  - [[16, 19, 22], 1, v10Detect, [nc]] # Detect(P3, P4, P5)
```

### Additional

_No response_

### LINKED ISSUE #16146: AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from '/usr/local/lib/python3.10/dist-packages/ultralytics/utils/loss.py'>
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Export

### Bug

I have trained a YOLO v10 model [best(1).pt] on custom data. I need to convert it to TFLite. 

### Environment

Ultralytics YOLOv8.2.90 🚀 Python-3.10.12 torch-2.4.0+cu121 CPU (Intel Xeon 2.20GHz)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 32.9/107.7 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.20GHz
CUDA                None

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.4.0+cu121>=1.8.0
torchvision         ✅ 0.19.0+cu121>=0.9.0
tqdm                ✅ 4.66.5>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.1.4>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
ultralytics-thop    ✅ 2.0.6>=2.0.0
torch               ✅ 2.4.0+cu121!=2.4.0,>=1.8.0; sys_platform == "win32"

### Minimal Reproducible Example

from ultralytics import YOLO
# Load a model
model = YOLO('/content/best (1).pt')

# Export the model
model.export(format='tflite')

### Additional

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[<ipython-input-4-6e6c55dcf94b>](https://localhost:8080/#) in <cell line: 3>()
      1 from ultralytics import YOLO
      2 # Load a model
----> 3 model = YOLO('/content/best (1).pt')
      4 
      5 # Export the model

8 frames
[/usr/local/lib/python3.10/dist-packages/torch/serialization.py](https://localhost:8080/#) in find_class(self, mod_name, name)
   1513                     pass
   1514             mod_name = load_module_mapping.get(mod_name, mod_name)
-> 1515             return super().find_class(mod_name, name)
   1516 
   1517     # Load the data (which may in turn use `persistent_load` to load tensors)

AttributeError: Can't get attribute 'v10DetectLoss' on <module 'ultralytics.utils.loss' from '/usr/local/lib/python3.10/dist-packages/ultralytics/utils/loss.py'>

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Y-T-G**
Several issues concerning this, so might as well handle it in the code.

https://github.com/ultralytics/ultralytics/issues/14170
https://github.com/ultralytics/ultralytics/issues/14676
https://github.com/ultralytics/ultralytics/issues/14072
https://github.com/ultralytics/ultralytics/issues/13931
https://github.com/ultralytics/ultralytics/issues/16146
https://github.com/ultralytics/ultralytics/issues/16059
https://github.com/ultralytics/ultralytics/issues/15957

### CODE REVIEW

**Comment by Skillnoob** [comment]
Good idea, there are too many of these issues.

**Comment by Y-T-G** [comment]
@Laughing-q I see. Didn't know about this. Thanks.

**Comment by glenn-jocher** [comment]
@Y-T-G @Skillnoob @Laughing-q this is great, thanks for implementing this fix!

**Comment by glenn-jocher** [comment]
PR merged! Will publish with `8.2.91`

**Pull request merged**
