### PR TITLE
Remove `explorer` Integration

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
The Ultralytics Explorer has been deprecated in favor of the new Ultralytics HUB platform.

### 📊 Key Changes
- Deprecated the Ultralytics Explorer API and GUI.
- Removed related documentation and code.
- Introduced Ultralytics HUB as the replacement platform.

### 🎯 Purpose & Impact
- **Unified Platform**: Transition to Ultralytics HUB for enhanced, user-friendly features without coding.
- **Simplified Workflow**: Streamline data exploration and management in a no-code environment. 🚀
- **Continuous Support**: Users can now leverage advanced capabilities with Ultralytics HUB, ensuring a better user experience.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting a pull request to the `ultralytics/ultralytics` repository! 🚀 This is an automated response to guide you through the PR process, and an Ultralytics engineer will review your submission soon. Here's a quick checklist to ensure everything is in order:

- ✅ **Define a Purpose**: Make sure your pull request description clearly outlines the purpose of the changes and relates to any [existing issues](https://github.com/ultralytics/ultralytics/issues).
- ✅ **Synchronize with Source**: Ensure your pull request is up-to-date with the `main` branch of the repository. If it's not, you can update it by pressing the 'Update branch' button or executing `git pull` and `git merge main` on your local machine.
- ✅ **Pass All CI Checks**: Check that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass successfully. If any checks fail, please investigate and resolve the issues.
- ✅ **Update Documentation**: If your modifications affect the existing features, ensure that the [documentation](https://docs.ultralytics.com) is updated accordingly.
- ✅ **Include Tests**: If relevant, include or revise tests that validate your changes and verify that all tests pass.
- ✅ **Sign the CLA**: If this is your first pull request with Ultralytics, confirm you've signed the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by writing "I have read the CLA Document and I sign the CLA" in a new comment.
- ✅ **Minimize Changes**: Keep your changes to the **minimum necessary** for the feature or bug fix. Consider this quote to guide your efforts: _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

You can find additional tips in our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to reach out if you have questions. Thanks for your invaluable contribution to Ultralytics! 🎉

**Comment by glenn-jocher** [comment]
@RizwanMunawar thanks! Can you add the removed docs pages to the 301 redirects dict at the end of mkdocs.yml? Otherwise these will show as 404's.

**Comment by RizwanMunawar** [comment]
@glenn-jocher right, so actually there is no docs page deleted :)

**Comment by RizwanMunawar** [comment]
@glenn-jocher Each docs page content will be replaced by the content shown in the picture :)

Screenshot 2024-10-11 155622

**Comment by glenn-jocher** [comment]
@RizwanMunawar ah ok! I understand. Hmm ok let me think about this. Maybe if we keep the pages we just keep them as is with the note that Explorer is deprecated and requires <=8.3.9? Notice looks good though, we could just use that.

**Comment by RizwanMunawar** [comment]
Ok I got your point @glenn-jocher, let me update the docs pages then :)

**Comment by RizwanMunawar** [comment]
@glenn-jocher Ok, everything updated :)👍🏻 

Screenshot 2024-10-11 192424

**Comment by glenn-jocher** [comment]
@RizwanMunawar thanks for the updates. We don't want to use ???+ for MkDocs here, these are complicated and collapsable, the standard !!! is what we want.

**Comment by glenn-jocher** [comment]
@RizwanMunawar please delete all reference section pages, these should not be saved. These need to be listed as 301 redirects at the end of MkDocs.yaml. 

Reference section is entirely automated and should not have any manual edits whatsoever.

**Comment by glenn-jocher** [comment]
@RizwanMunawar looks good now! I fixed the notebook because it was showing a huge diff (i.e. +1000 - 1000) when in reality we are only adding +10. If we don't fix these then this huge diff makes it's way into the git chain and makes the repo bigger and heavier.

**Review by glenn-jocher — APPROVED** [review]

**Comment by RizwanMunawar** [comment]
Awesome @glenn-jocher! I’m curious, which tool do you use to update the notebook? Do you use Google Colab, or do you update it directly in PyCharm?

**Comment by glenn-jocher** [comment]
@RizwanMunawar oh my PyCharm is just community edition, so it doesn't let me edit notebooks, so I just end up trying to edit them (carefully) in the GitHub editor.

But for really big changes (or running notebooks with new versions of Ultralytics for example) I open them in Colab, then edit them there, then commit the change back to a PR using Colab directly.

**Comment by glenn-jocher** [comment]
Like this. But you have to be sure to pick the right PR branch (not main): 
Screenshot 2024-10-13 at 16 58 53

**Comment by glenn-jocher** [comment]
PR merged!

**Comment by RizwanMunawar** [comment]
Nice work on this @glenn-jocher + myself :)

**Pull request merged**
