### PR TITLE
Add YOLOv8 OpenVINO C++ Inference example

### PR DESCRIPTION
**Pull request by rlggyp**
This PR adds a new example for performing inference using YOLOv8 in C++ with OpenVINO and OpenCV API. The example demonstrates how to load and run YOLOv8 models in various formats and precisions using OpenVINO, enhancing the usability and flexibility of YOLOv8 for C++ developers.

### Features:
- [x] Support for ONNX and OpenVINO IR model formats
- [x] Support for FP32, FP16, and INT8 precisions
- [x] Support for loading models with dynamic shape

### Checklist:
- [x] Tested on local environment
- [x] Tested on Ubuntu `18.04`, `20.04`, `22.04`

#### Running using OpenVINO model
image
#### Running using ONNX model
image

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces a C++ example demonstrating how to perform inference with YOLOv8 models using OpenVINO.

### 📊 Key Changes
- Added CMakeLists.txt to configure and build the C++ example.
- Created a README.md with detailed instructions on dependencies, build, and usage.
- Implemented `inference.cc` and `inference.h` containing the core logic for loading YOLOv8 models and performing inference.
- Provided `main.cc` as an entry point to run inference on an input image with the specified model.

### 🎯 Purpose & Impact
- **Enhanced Performance**: Leverages OpenVINO for accelerated inference, supporting various precision modes (FP32, FP16, INT8).
- **User Flexibility**: Supports models in ONNX and OpenVINO IR formats with dynamic input shapes.
- **Ease of Use**: Detailed instructions and a comprehensive example make it easy for developers to integrate YOLOv8 with OpenVINO into their applications.
  
Overall, this addition makes it straightforward for developers to utilize YOLOv8 models in C++ applications with enhanced performance and flexibility. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@rlggyp PR Merged, thank you for your contributions!

**Comment by nidetaoge** [comment]
Sorry to disturb you, but the probability of the openvino model is lower than that of the onnx model, leading to the mis-detection of the targets. Precision should not degrade that much, right?

**Comment by rlggyp** [comment]
@nidetaoge Thank you for your comment! Could you clarify if your concern is based on the screenshot in the pull request, or have you tested it yourself? I recently re-tested both OpenVINO and ONNX formats and found they give the same accuracy results.

**Comment by nidetaoge** [comment]
@rlggyp Yes, the result of onnx or pt with python inference differs from openvino with C++ inference. By the way, I have met another problem. When running openvino C++ inference, inference_request_.infer() gets the right results, but calls segmentation fault randomly. I just replace to my model which only trained with a different dataset. How can I fix this? Thank you very much!

**Pull request merged**
