### PR TITLE
Add Roboflow integration guide

### PR DESCRIPTION
**Pull request by capjamesg**
This PR adds a Roboflow integration guide to the `Integrations` tab in the Ultralytics documentation, outlining the ways in which you can use Roboflow with Ultralytics for dataset management. We have included a few community testimonials of using Roboflow and Ultralytics toward the end. If there are more we should include, let me know!

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of Roboflow with Ultralytics for enhanced dataset management and model evaluation.

### 📊 Key Changes
- Updated the Roboflow link in the Ultralytics documentation to point to a new, dedicated Roboflow integration page.
- Added a comprehensive new document detailing how to use Roboflow with Ultralytics' YOLOv8 models for tasks including data collection, labeling, preprocessing, augmentation, dataset management, model testing, deployment, and evaluation.
- Included details about Roboflow Universe and Collect platforms for dataset creation and acquisition.
- Explained how to upload and label data, manage datasets, export in various formats, and deploy models via the Roboflow API.
- Showcased methods for model evaluation using features like confusion matrix and vector analysis for performance insights.

### 🎯 Purpose & Impact
- Simplifies the process of finding, preparing, and managing datasets for Ultralytics models, leading to more efficient and effective training sessions.
- Allows users to easily evaluate model performance and gain insights into potential improvements, promoting more accurate and reliable computer vision models.
- Enhances user experience by providing tools and detailed guidance on leveraging Roboflow's powerful dataset management and model evaluation features within Ultralytics' ecosystem.

### CODE REVIEW

**Comment by capjamesg** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@capjamesg thanks for the PR! Can you also add an entry in the docs/integrations/index.md page? Thanks!

**Comment by capjamesg** [comment]
Will do!

**Comment by capjamesg** [comment]
I have just added the requested link.

**Comment by glenn-jocher** [comment]
@capjamesg awesome! Last thing we need is to fix the image widths to their best width, otherwise they'll render very large sometimes. You can see an example of this using HTML here or if you have another preferred method you can use that also:

https://github.com/ultralytics/ultralytics/blob/896da0c0a06eca5230d5fff2dbd6fd9ce7cfc11d/docs/guides/kfold-cross-validation.md?plain=1#L13-L15

**Comment by capjamesg** [comment]
I have made the requested image size changes.

**Comment by glenn-jocher** [comment]
@capjamesg Perfect. I will review the amendments shortly. Thank you for your prompt responses and valuable contributions to this project.

**Comment by glenn-jocher** [comment]
@capjamesg PR merged! Thank you for your contributions to YOLO.

**Pull request merged**
