### PR TITLE
Integrate OpenVINO `CUMULATIVE_THROUGHPUT` mode batched inference

### PR DESCRIPTION
**Pull request by glenn-jocher**
@adrianboguszewski @Laughing-q @Burhan-Q now that I've completed updating our dataloaders for batched inference in https://github.com/ultralytics/ultralytics/pull/8817 I'm working on integrating this new capability with OpenVINO's LATENCY and CUMULATIVE_THROUGHPUT modes in this PR.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements in model initialization and inference modes for improved flexibility and performance.

### 📊 Key Changes
- 🔄 The parameter name in `AutoBackend` initialization changed from `model` to `weights` for clarity.
- ➕ Added `batch` parameter in various classes (`AutoBackend`, `predictor.py`, and `validator.py`) to support dynamic batch-size configurations.
- 🔧 In `AutoBackend`, the inference mode now adapts based on the batch size, switching between `LATENCY` and `CUMULATIVE_THROUGHPUT` for optimized performance.
- 🛠 Adjusted how inference results are handled in batches, consolidating individual predictions into a combined output for efficiency.

### 🎯 Purpose & Impact
- 🚀 These changes aim to make the model setup more intuitive and flexible, allowing users and developers to easily configure models with custom weights.
- 📈 The dynamic adjustment of inference modes based on batch size is designed to optimize the balance between speed and throughput, enhancing performance based on user needs.
- 💡 The update in handling inference results in batches will make processing large volumes of data more efficient, potentially speeding up applications like object detection in images and video streams.
- Overall, users should experience a more streamlined setup process, with the potential for noticeable performance gains in various scenarios.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@adrianboguszewski I think it's working, but it's a bit hard to tell based on these  If I export a model and run inference on a long video at batch=1 vs batch=8 I get these results on my M2 Macbook Pro on a 725-frame video.

```bash
yolo export model=yolov8n.pt format=openvino
```

And then 
```
yolo predict source=path/to/video.mp4 imgsz=640 batch=8
```

Results at `batch=1` and `batch=8` are:

- Speed: 1.6ms preprocess, 48.4ms inference, 0.4ms postprocess per image at shape (1, 3, 640, 384)
- Speed: 2.5ms preprocess, 39.8ms inference, 0.3ms postprocess per image at shape (8, 3, 640, 384)

I'm thinking I might need to run this on an Intel chip to see the full benefit as these are on Apple M2.

**Comment by adrianboguszewski** [comment]
I confirm it's working from the command line. But it crashes when running from the code and the exported model is dynamic and gives the wrong batch size when exported model is static.

**Comment by glenn-jocher** [comment]
@adrianboguszewski merging this now to include it in `ultralytics 8.1.27`

**Comment by adrianboguszewski** [comment]
@glenn-jocher what about the issues I mentioned above?

**Pull request merged**
