### PR TITLE
Fix `test_mlflow_keep_run_active()`

### PR DESCRIPTION
**Pull request by glenn-jocher**
Fix failing MLFlow test created in https://github.com/ultralytics/ultralytics/pull/8808 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced testing robustness for MLflow integration in automated CI environments.

### 📊 Key Changes
- Temporarily disabled a test due to consistent failures in scheduled CI, providing a link to the relevant PR as a reason.
- Refactored MLflow tests to improve readability and modularity.
- Introduced conditional logic to test different scenarios based on the environment variable `MLFLOW_KEEP_RUN_ACTIVE`.

### 🎯 Purpose & Impact
- **Increased Stability**: The temporary skipping of a failing test ensures CI stability until a fix is implemented.
- **Better Test Coverage**: The changes test MLflow's behavior under different configurations, ensuring the feature behaves as expected across various use cases.
- **Enhanced Developer Experience**: By skipping known failing tests and ensuring others accurately reflect intended functionality, developers can trust the CI process more, focusing on meaningful failures and improvements.

🔍 These adjustments make our integration tests more reliable and insightful, paving the way for smoother deployments and higher quality software.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/ultralytics/actions/runs/8238561604/job/22529777539

Screenshot 2024-03-11 at 20 35 57

**Comment by glenn-jocher** [comment]
@massimiliano96 I'm going to merge this now so tonight's scheduled CI doesn't fail (it runs every 24 hours). This PR disables the test completely, but please see if there's a fix that can be applied in a separate PR. Thank you!

**Comment by massimiliano96** [comment]
Hi @glenn-jocher, I'm troubleshooting an issue. While tests in my IDE pass, they fail from the terminal. Currently examining my VS Code settings.

**Comment by glenn-jocher** [comment]
@massimiliano96 hi there! It sounds like there might be an environment difference between your IDE and terminal. 😊 Could you try running `echo $PATH` in both your VS Code terminal and your external terminal to compare? Also, ensure that the Python interpreter is the same in both environments by running `which python`. This might help pinpoint the discrepancy!

**Comment by massimiliano96** [comment]
Hi @glenn-jocher, I've discovered that the disparity in my environment stemmed from having the ultralytics package installed on my machine. When running the test in the Terminal, it utilized the installed version, whereas in VSCode, it employed the module within the code. After uninstalling the ultralytics package, the test in the terminal succeeded. I'm now curious if the same issue is occurring in the CI pipeline.

**Comment by glenn-jocher** [comment]
@massimiliano96 hi there! 😊 It's great to hear you've identified the root cause of the discrepancy between your terminal and VSCode environments. Regarding the CI pipeline, it's indeed possible that a similar issue could occur if the pipeline is set up to use a different version of the ultralytics package than expected. To ensure consistency, you might want to explicitly specify the package version in your CI configuration or ensure it installs the package directly from your current codebase. This way, you can avoid version mismatches and ensure the CI environment mirrors your local setup as closely as possible. Here's a quick example on how to specify a package version in a CI config file:

```yaml
- name: Install dependencies
  run: pip install ultralytics==x.x.x
```

Or, to install directly from your codebase:

```yaml
- name: Install package
  run: pip install .
```

Hope this helps! Let me know if you have any more questions.

**Pull request merged**
