### PR TITLE
`ultralytics 8.2.50` new Streamlit live inference Solution

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
New Streamlit integration for real-time object detection with YOLOv8 and various documentation enhancements.

### 📊 Key Changes
- **Streamlit Integration**:
  - Added a new Streamlit application for real-time object detection using YOLOv8.
  - Created `streamlit_inference.py` to handle Streamlit-based webcam video inference.
- **Documentation Updates**:
  - Updated README with a new badge to link the Ultralytics Forums.
  - Adjusted several links in documentation to ensure they point to the relevant guides.
  - Added a comprehensive guide for setting up Streamlit live inference.
  - Included reference documentation for the new Streamlit functionality.
- **Code Improvements**:
  - Enhanced assert statements for better error messages.
  - General code cleanup and documentation improvements.

### 🎯 Purpose & Impact
- **Purpose**:
  - **Streamlit Integration**: To provide a user-friendly way to run real-time object detection directly in the browser with minimal setup.
  - **Documentation**: To ensure users have accurate guides and resources, improving overall usability and support.
- **Impact**:
  - **User Experience**: Users can now easily deploy and test YOLOv8 models in real-time through an intuitive web interface, widening accessibility.
  - **Developer Efficiency**: Clearer documentation and improved error messages facilitate faster troubleshooting and implementation.

Enjoy the seamless real-time detection and improved interaction with the Ultralytics community! 🚀✨

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar this is interesting, I ran it and it seems to work well. Could we make a few changes?

- Can we add an Ultralytics logo into the app somewhere, i.e. on the top right?
- Does it run with a streaming dataloader, i.e. `yolo predict source=0 show` for streaming inference? Not sure if is doing this now but it seems like it's instead loading/running per image?
- Make the IoU and Confidence values into sliders like our iOS app?
image

**Comment by glenn-jocher** [comment]
@RizwanMunawar looks like this for me:
Screenshot 2024-07-04 at 17 59 33

**Comment by RizwanMunawar** [comment]
@glenn-jocher, perfect. Please keep this PR open, and I will work on it.

- We can add LOGO, dropdown for all models, and sliders for IOU and NMS. All changes possible 👍🏻

**Comment by RizwanMunawar** [comment]
@glenn-jocher Good to go I think :)

- I have replaced the `NMS` and `IOU` text boxes with sliders!
- I have added all Ultralytics YOLOv8 models (Detection, Segmentation and Pose)
- Ultralytics Logo added :)

Screenshot 2024-07-04 220204

**Comment by RizwanMunawar** [comment]
@glenn-jocher addition (drop-down menu added)
Screenshot 2024-07-04 233638

**Comment by RizwanMunawar** [comment]
@glenn-jocher I think the PR is ready to go 👍🏻

**Comment by glenn-jocher** [comment]
@RizwanMunawar we've got this warning, I think we need to add the reference page to mkdocs.yml:
```
INFO    -  The following pages exist in the docs directory, but are not included in the "nav" configuration:
  - reference/solutions/streamlit_inference.md
 ```

**Comment by RizwanMunawar** [comment]
Correct, let me add this :) @glenn-jocher

**Comment by glenn-jocher** [comment]
@RizwanMunawar hey do you think Streamlit would be a good basis for future demos?

Not sure if we want to expand examples/demos with streamlit, then maybe we want a more scalable naming convention for CLI commands like `yolo streamlit-inference-demo` or `yolo streamlit-inference`, then we could build additional ones like `yolo streamlit-val` etc. 

Another option is 2 word CLI commands, i.e. we have this for HUB:

```
yolo hub login
yolo hub logout
```

Maybe we could do the same for streamlit?

```
yolo streamlit predict
yolo streamlit export
```

What do you think?

**Comment by RizwanMunawar** [comment]
@glenn-jocher I think we can proceed with mentioned naming convention :)

```
yolo streamlit predict    # for current demo!
yolo streamlit export
```

**Comment by RizwanMunawar** [comment]
@glenn-jocher super cool, classes selection dropdown menu added :) User can select multiple classes 👍🏻 

Screenshot 2024-07-06 001611

**Comment by glenn-jocher** [comment]
@RizwanMunawar haha this is so cool!

**Comment by glenn-jocher** [comment]
@RizwanMunawar I've updated the code to read the class names from coco.yaml. We don't want to duplicate COCO class names when they already exist in a single reference location like coco.yaml.

**Comment by glenn-jocher** [comment]
See https://github.com/ultralytics/ultralytics/pull/14210/commits/b22628e4d36a46ce200dd82630c3a43ad30fed16 for the correct way to use COCO class names.

One problem I see though is that since these names are not read from the model, the demo will break for other models no?

Shouldn't we read the class names on model load from `model.names`?

**Comment by RizwanMunawar** [comment]
@glenn-jocher Perfect. I believe the PR looks much improved and offers a more user-friendly interface. Users can now:
- Select from all Ultralytics YOLOv8 models (Segment, Detect, Pose)
- Utilize webcam and video support
- Experience a more intuitive class selection
- View FPS for additional information :)

You can review all the changes, but overall, I think it's ready to go 👍🏻

**Comment by RizwanMunawar** [comment]
> See [b22628e](https://github.com/ultralytics/ultralytics/commit/b22628e4d36a46ce200dd82630c3a43ad30fed16) for the correct way to use COCO class names.
> 
> One problem I see though is that since these names are not read from the model, the demo will break for other models like `yolov8n-oiv7.pt` no?
> 
> Shouldn't we read the class names on model load from `model.names`?

Ah nice catch, let's do that :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar oh I also updated the logo from the assets repo, but it's an SVG, not sure if this is compatible with Streamlit, can you test? 

This is the same logo that I use in all the other repo READMEs like https://github.com/ultralytics/template

**Comment by RizwanMunawar** [comment]
@glenn-jocher got it, let me verify If the logo is working or not!

**Comment by RizwanMunawar** [comment]
@glenn-jocher The new logo you added is working perfectly. Class names will now be read directly from `model.names`.

Everything looks good now :)

Screenshot 2024-07-06 004643

**Comment by glenn-jocher** [comment]
@RizwanMunawar awesome! I think we are good to go now, what do you think?

**Comment by glenn-jocher** [comment]
The UI is looking super nice here haha!!

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes I think we are good to go :) I have performed testing and everything is working well at the moment :)

**Comment by glenn-jocher** [comment]
Ok I'll merge once tests complete

**Comment by glenn-jocher** [comment]
@RizwanMunawar PR merged. Awesome work here!!

**Pull request merged**
