### PR TITLE
Intel Core Ultra benchmarks

### PR DESCRIPTION
**Pull request by ambitious-octopus**
## Integrated Intel® Arc™ GPU
image

## Intel® Meteor Lake CPU
image

## Integrated Intel® AI Boost NPU
image

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updates OpenVINO documentation and benchmarks for new Intel hardware.

### 📊 Key Changes
- Added benchmarks for Intel Ultra 7 155H Meteor Lake CPUs.
- Introduced benchmark data for integrated Intel Arc GPU and AI Boost NPU.
- Provided inference performance metrics for various YOLOv8 models (n, s, m, l, x) on different Intel hardware.

### 🎯 Purpose & Impact
- **Enhanced Documentation**: Provides up-to-date performance details for users considering or using Intel’s latest hardware.
- **Performance Insights**: Helps developers choose optimal hardware and configurations for their AI tasks by comparing inference times and model precision.
- **Broader Compatibility**: Showcases the compatibility and performance of Ultralytics models on varied Intel platforms, benefiting users with Intel setups.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced OpenVINO integration for Intel Ultra 7 155H CPU, featuring detailed performance benchmarks.

### 📊 Key Changes
- Added new documentation for Intel Ultra 7 155H CPU benchmarks.
- Detailed performance metrics for CPU, GPU, and NPU integrated in the Ultra 7 155H.
- Charts and tables displaying inference times and model sizes for YOLOv8 models.

### 🎯 Purpose & Impact
- **Purpose:** Provide insights on the performance capabilities of Intel's new Ultra 7 155H chips with YOLOv8 models.
- **Impact:** Helps users understand the efficiency and speed improvements in AI tasks, enhancing decision-making for hardware choices. 🖥️📈

### CODE REVIEW

**Review by adrianboguszewski — COMMENTED** [review]
Looks good! Could we also add bar charts like with the previous benchmarks?

**Comment by adrianboguszewski** [comment]
@ambitious-octopus could we also refresh this diagram?
image

**Comment by ambitious-octopus** [comment]
image

image

image

**Comment by glenn-jocher** [comment]
@ambitious-octopus I think there's something wrong with these images vs the current ones. The new ones look to be very poor quality. Are you using the plotting script I sent you over Slack?

**Review by ambitious-octopus — COMMENTED** [review]
@glenn-jocher Yes, maybe because of `avif` compression. Here is the code for documentation:

<p>
<details>
<summary>Plot Code</summary>

```python
import matplotlib.pyplot as plt
import pandas as pd

data_fp32 = {
    'YOLOv8n': {
        'PyTorch': 21.79,
        'TorchScript': 23.24,
        'ONNX': 37.22,
        'OpenVINO': 3.29,
    },
    'YOLOv8s': {
        'PyTorch': 31.89,
        'TorchScript': 32.71,
        'ONNX': 43.42,
        'OpenVINO': 3.92,
    },
    'YOLOv8m': {
        'PyTorch': 50.75,
        'TorchScript': 47.90,
        'ONNX': 63.16,
        'OpenVINO': 7.11,
    },
    'YOLOv8l': {
        'PyTorch': 77.45,
        'TorchScript': 85.71,
        'ONNX': 88.94,
        'OpenVINO': 9.37,
    },
    'YOLOv8x': {
        'PyTorch': 100.09,
        'TorchScript': 114.64,
        'ONNX': 110.32,
        'OpenVINO': 15.02,
    },
}

data_fp16 = {
    'YOLOv8n': {
        'PyTorch': 24.39,
        'TorchScript': 23.76,
        'ONNX': 37.37,
        'OpenVINO': 3.29,
    },
    'YOLOv8s': {
        'PyTorch': 30.60,
        'TorchScript': 34.40,
        'ONNX': 43.53,
        'OpenVINO': 3.91,
    },
    'YOLOv8m': {
        'PyTorch': 50.75,
        'TorchScript': 47.90,
        'ONNX': 63.16,
        'OpenVINO': 7.11,
    },
    'YOLOv8l': {
        'PyTorch': 78.55,
        'TorchScript': 84.75,
        'ONNX': 87.71,
        'OpenVINO': 9.38,
    },
    'YOLOv8x': {
        'PyTorch': 94.85,
        'TorchScript': 113.11,
        'ONNX': 111.00,
        'OpenVINO': 15.02,
    },
}

data_xeon = {
    'YOLOv8n': {
        'PyTorch': 24.36,
        'TorchScript': 23.93,
        'ONNX': 39.86,
        'OpenVINO': 11.34,
    },
    'YOLOv8s': {
        'PyTorch': 33.77,
        'TorchScript': 34.84,
        'ONNX': 43.23,
        'OpenVINO': 13.86,
    },
    'YOLOv8m': {
        'PyTorch': 53.91,
        'TorchScript': 53.51,
        'ONNX': 64.16,
        'OpenVINO': 28.79,
    },
    'YOLOv8l': {
        'PyTorch': 75.78,
        'TorchScript': 79.13,
        'ONNX': 88.45,
        'OpenVINO': 56.23,
    },
    'YOLOv8x': {
        'PyTorch': 96.60,
        'TorchScript': 114.28,
        'ONNX': 111.02,
        'OpenVINO': 83.28,
    },
}

data_arc = {
    'YOLOv8n': {
        'PyTorch': 88.79,
        'TorchScript': 102.66,
        'ONNX': 57.98,
        'OpenVINO': 8.52,
    },
    'YOLOv8s': {
        'PyTorch': 189.83,
        'TorchScript': 227.58,
        'ONNX': 142.03,
        'OpenVINO': 9.19,
    },
    'YOLOv8m': {
        'PyTorch': 411.64,
        'TorchScript': 517.12,
        'ONNX': 298.68,
        'OpenVINO': 12.55,
    },
    'YOLOv8l': {
        'PyTorch': 725.73,
        'TorchScript': 892.83,
        'ONNX': 576.11,
        'OpenVINO': 17.62,
    },
    'YOLOv8x': {
        'PyTorch': 988.92,
        'TorchScript': 1186.42,
        'ONNX': 768.90,
        'OpenVINO': 19.00,
    },
}

data_core = {
    'YOLOv8n': {
        'PyTorch': 104.61,
        'TorchScript': 112.39,
        'ONNX': 28.02,
        'OpenVINO': 23.53,
    },
    'YOLOv8s': {
        'PyTorch': 194.83,
        'TorchScript': 202.01,
        'ONNX': 65.74,
        'OpenVINO': 38.66,
    },
    'YOLOv8m': {
        'PyTorch': 355.23,
        'TorchScript': 424.78,
        'ONNX': 173.39,
        'OpenVINO': 69.80,
    },
    'YOLOv8l': {
        'PyTorch': 593.00,
        'TorchScript': 697.54,
        'ONNX': 342.15,
        'OpenVINO': 117.69,
    },
    'YOLOv8x': {
        'PyTorch': 804.65,
        'TorchScript': 921.46,
        'ONNX': 526.66,
        'OpenVINO': 158.73,
    },
}

data_ultra_npu = {
    'YOLOv8n': {
        'PyTorch': 36.98,
        'OpenVINO(FP32)': 16.68,
        'OpenVINO(INT8)': 14.6,
    },
    'YOLOv8s': {
        'PyTorch': 79.76,
        'OpenVINO(FP32)': 32.89,
        'OpenVINO(INT8)': 26.13,
    },
    'YOLOv8m': {
        'PyTorch': 201.44,
        'OpenVINO(FP32)': 54.4,
        'OpenVINO(INT8)': 30.7,
    },
    'YOLOv8l': {
        'PyTorch': 385.46,
        'OpenVINO(FP32)': 80.1,
        'OpenVINO(INT8)': 52.25,
    },
    'YOLOv8x': {
        'PyTorch': 609.4,
        'OpenVINO(FP32)': 104.79,
        'OpenVINO(INT8)': 64.96,
    },
}

data_ultra_cpu = {
    'YOLOv8n': {
        'PyTorch': 34.69,
        'OpenVINO(FP32)': 39.06,
        'OpenVINO(INT8)': 18.37,
    },
    'YOLOv8s': {
        'PyTorch': 79.9,
        'OpenVINO(FP32)': 82.6,
        'OpenVINO(INT8)': 29.51,
    },
    'YOLOv8m': {
        'PyTorch': 202.43,
        'OpenVINO(FP32)': 181.27,
        'OpenVINO(INT8)': 51.25,
    },
    'YOLOv8l': {
        'PyTorch': 385.87,
        'OpenVINO(FP32)': 347.75,
        'OpenVINO(INT8)': 91.66,
    },
    'YOLOv8x': {
        'PyTorch': 603.63,
        'OpenVINO(FP32)': 516.39,
        'OpenVINO(INT8)': 142.42,
    },
}

data_ultra_gpu = {
    'YOLOv8n': {
        'PyTorch': 35.95,
        'OpenVINO(FP32)': 8.32,
        'OpenVINO(INT8)': 9.88,
    },
    'YOLOv8s': {
        'PyTorch': 79.72,
        'OpenVINO(FP32)': 13.37,
        'OpenVINO(INT8)': 9.96,
    },
    'YOLOv8m': {
        'PyTorch': 202.05,
        'OpenVINO(FP32)': 28.07,
        'OpenVINO(INT8)': 21.11,
    },
    'YOLOv8l': {
        'PyTorch': 393.37,
        'OpenVINO(FP32)': 52.73,
        'OpenVINO(INT8)': 28.11,
    },
    'YOLOv8x': {
        'PyTorch':610.71,
        'OpenVINO(FP32)': 73.51,
        'OpenVINO(INT8)': 51.71,
    },
}

for data, title in (data_fp16, 'Flex GPU FP16 Precision'), \
        (data_fp32, 'Flex GPU FP32 Precision'), \
        (data_arc, 'Arc GPU'), \
        (data_xeon, 'Xeon CPU'), \
        (data_core, 'Core CPU'), \
        (data_ultra_cpu, 'Intel Core Ultra Meteor Lake CPU'), \
        (data_ultra_npu, 'Intel Core Ultra Meteor Lake NPU'), \
        (data_ultra_gpu, 'Intel Core Ultra Meteor Lake GPU'):
    # Grouped bar plot
    ax = pd.DataFrame(data).T.plot(kind='bar', figsize=(10, 5), colormap='viridis')
    ax.set_xlabel('Model Size')
    ax.set_ylabel('Inference Time (ms/im)')
    ax.set_title(f'Inference Time per Image by Model Size and Format ({title})')
    ax.grid(alpha=0.2)
    plt.xticks(rotation=0)
    # plt.legend(title='Format')
    plt.savefig(fname=f'OpenVINO - {title}.jpg', dpi=300, bbox_inches='tight')
```

</details>
</p>

**Review by ambitious-octopus — COMMENTED** [review]
@glenn-jocher I removed `seaborn` now the plots look like this. The layout seems wider:

image

**Comment by glenn-jocher** [comment]
@ambitious-octopus @adrianboguszewski looks good, PR merged!

**Pull request merged**
