### PR TITLE
Implement option to disable ClearML default logging

### PR DESCRIPTION
**Pull request by agfianf**
### Summary
📝🔧🚀

This pull request adds a feature to optionally disable ClearML logging in `clearml.py` and updates the documentation of the ClearML logging integration tutorial in `clearml_logging_integration.md` to reflect this option. This feature allows users to use a custom logging system with ClearML and YOLOv5.

> _`ClearML` is watching, logging all your moves_
> _But you can break the chains, set the variable to choose_
> _Your own custom logger, unleash your YOLO power_
> _No more default settings, this is your finest hour_

### Walkthrough
*  Add a new section to the ClearML logging integration tutorial to explain how to disable the default ClearML logging and use a custom logging system ([link](https://github.com/ultralytics/ultralytics/pull/3160/files?diff=unified&w=0#diff-e10d4cf8a0b37a20d7946ac04cc13abc743ec48caaddcfee6d25675a5990ffa3R242-R245))
*  Import the `os` module to access the environment variable `ULTRALYTICS_CLEARML_DISABLED` ([link](https://github.com/ultralytics/ultralytics/pull/3160/files?diff=unified&w=0#diff-a815296cb22a8ba6127487e136b0996e9885c93d79f23f92ad858437b2c9af66R3))
*  Check the value of `ULTRALYTICS_CLEARML_DISABLED` and set the `clearml` variable to `None` if it is `true` to disable the default ClearML logging ([link](https://github.com/ultralytics/ultralytics/pull/3160/files?diff=unified&w=0#diff-a815296cb22a8ba6127487e136b0996e9885c93d79f23f92ad858437b2c9af66R23-R25))
*  Add a log message to the `on_train_epoch_end` function in `clearml.py` to inform the users that ClearML is detected and auto logging is enabled ([link](https://github.com/ultralytics/ultralytics/pull/3160/files?diff=unified&w=0#diff-a815296cb22a8ba6127487e136b0996e9885c93d79f23f92ad858437b2c9af66R94-R97))

Solve #3063

Users can create your own clearml custom logging system by overriding the callbacks function and disabling the default ClearML logging. This will ensure that your custom logging does not mix with the default ClearML logging. To disable the default ClearML logging, set the environment variable `ULTRALYTICS_CLEARML_DISABLED=true`.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Expansion of ClearML integration in YOLOv5 documentation and update to allow custom logging.

### 📊 Key Changes
- Updated the YOLOv5 documentation to include how to disable default ClearML logging.
- Added an environment variable `ULTRALYTICS_CLEARML_DISABLED` to disable the default ClearML logging programmatically.
- Ensured that the logger informs users when ClearML logging is disabled using the new environment variable.
- Added informational logging to confirm when ClearML is enabled and that auto-logging will occur unless disabled.

### 🎯 Purpose & Impact
- Provides users with more control over their logging preferences when using ClearML with YOLOv5.
- Enables developers to implement custom ClearML logging without interference from the default logging system.
- Ensures transparency for users with log messages stating the status of ClearML logging.
- Potentially reduces clutter and confusion in logs for users who opt to use their custom logging setups. 🛠️⚙️

### CODE REVIEW

**Comment by muhammadAgfian96** [comment]
I have read the CLA Document and I sign the CLA

**Comment by muhammadAgfian96** [comment]
recheck

**Comment by muhammadAgfian96** [comment]
will solve this issue with SettingsManager. #3790 
Thanks @glenn-jocher !

**Comment by glenn-jocher** [comment]
@muhammadAgfian96 hi there,

Thanks for your contribution. Your idea for using a `SettingsManager` to address this issue sounds interesting! Feel free to submit a Pull Request with your proposed modifications for YOLOv8. Remember to ensure that your changes align with the current code base and the direction of the repo.

Once your PR is submitted, we will review it as soon as possible. We appreciate your help in enhancing the YOLOv8's codebase and functionality.

Best regards,
Glenn Jocher

**Pull request closed without merging**
