### PR TITLE
Fixes DDP with rt-detr checkpoints #3439

### LINKED ISSUE #3439: Cannot train RT-DETR on multi-gpu from checkpoint (works fine from scratch)
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

Single GPU training works fine with RT-DETR when :
* Loading from checkpoint (`rtdetr-l.pt`)
* Training from scratch (`rtdetr-l.yaml`)

It works on multi gpu only when training from scratch as when it try to run on multi GPU it errors with :  

```
DDP info: RANK 0, WORLD_SIZE 3, DEVICE cuda:0
wandb: Currently logged in as: lpn64. Use `wandb login --relogin` to force relogin
wandb: wandb version 0.15.4 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade
wandb: Tracking run with wandb version 0.15.2
wandb: Run data is saved locally in /opt/ultralytics/wandb/run-20230628_161623-5xhen8k2
wandb: Run `wandb offline` to turn off syncing.
wandb: Syncing run large 2.5 boost RT-DETR
wandb: ⭐️ View project at CENSORED
wandb: 🚀 View run at CENSORED
Overriding model.yaml nc=80 with nc=1
WARNING ⚠️ no model scale passed. Assuming scale='l'.
Transferred 926/941 items from pretrained weights
AMP: running Automatic Mixed Precision (AMP) checks with YOLOv8n...
AMP: checks passed ✅
train: Scanning /home/CENSORED/CENSORED/labels/train.cache... 1719 images, 9 backgrounds, 0 corrupt: 100%|██████████| 1719/1719 [00:00<?, ?it/s]
val: Scanning /home/CENSORED/CENSORED/labels/val.cache... 491 images, 1 backgrounds, 0 corrupt: 100%|██████████| 491/491 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/home/CENSORED/.config/Ultralytics/DDP/_temp_r_5xaqei139646217166880.py", line 9, in <module>
    trainer.train()
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
Traceback (most recent call last):
  File "/home/CENSORED/.config/Ultralytics/DDP/_temp_r_5xaqei139646217166880.py", line 9, in <module>
    self._do_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 267, in _setup_train
        trainer.train()self.resume_training(ckpt)

  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 584, in resume_training
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    start_epoch = ckpt['epoch'] + 1
KeyError: 'epoch'
    self._setup_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 267, in _setup_train
    self.resume_training(ckpt)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 584, in resume_training
    start_epoch = ckpt['epoch'] + 1
KeyError: 'epoch'
Plotting labels to /opt/ultralytics/runs/detect/large 2.5 boost RT-DETR12/labels.jpg...
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 3074218 closing signal SIGTERM
15
optimizer: SGD(lr=0.01, momentum=0.9) with parameter groups 143 weight(decay=0.0), 206 weight(decay=0.000515625), 226 bias(decay=0.0)
Traceback (most recent call last):
  File "/home/CENSORED/.config/Ultralytics/DDP/_temp_r_5xaqei139646217166880.py", line 9, in <module>
    trainer.train()
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 192, in train
    self._do_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 276, in _do_train
    self._setup_train(world_size)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 267, in _setup_train
    self.resume_training(ckpt)
  File "/opt/ultralytics/venv/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 584, in resume_training
    start_epoch = ckpt['epoch'] + 1
KeyError: 'epoch'
```

### Environment

4 A40 4GB Ubuntu Torch stable on GPU

### Minimal Reproducible Example

Command :

```
yolo detect train data=./your_dataset.yaml epochs=1250 imgsz=2048 patience=0 batch=6 model="rtdetr-l.pt" device=0,1,2  name="large 2.5 boost RT-DETR"

```

### Additional

_No response_

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by ExtReMLapin**
The pickle file of RT-DETR is missing some keys like optimizer, last epoch (should be -1).

Small pytorch warning after the first epoch but it seems to work so far, will close PR if it fails on the way.

### Summary
🛠️🔄🚫

Fix potential errors when resuming training from incomplete checkpoints. Add checks for checkpoint keys and set default values for missing fields in `trainer.py`.

> _`checkpoint` keys checked_
> _avoid errors when resuming_
> _cold winter training_

### Walkthrough
*  Add checks for checkpoint keys and set default values for missing fields ([link](https://github.com/ultralytics/ultralytics/pull/3440/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L584-R588)). This improves the robustness and compatibility of the resume training feature in `trainer.py`.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved checkpoint handling and fault tolerance in training resume functionality.

### 📊 Key Changes
- Added checks for dictionary keys before resuming training from a checkpoint.
- Ensures `start_epoch`, `optimizer`, and `best_fitness` are only accessed if they exist in the checkpoint.
- Added a fallback for `start_epoch` to be `-1` if the `'epoch'` key is not present.

### 🎯 Purpose & Impact
- 🛠️ **Increases Robustness**: Prevents potential crashes due to missing keys, allowing training to resume more reliably.
- ⏱️ **Saves Time**: Saves users from needing to restart training entirely if the checkpoint is missing some expected information.
- 🔄 **Flexible Checkpoints**: Enables the use of various checkpoint files that may not contain all the traditional state keys.

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
image
Spooky 👀

**Comment by ExtReMLapin** [comment]
No warning on second epoch

image

**Comment by glenn-jocher** [comment]
@ExtReMLapin hi there! Thank you for bringing this issue to our attention. I understand that you're not seeing the warning on the second epoch. 

The warning you encountered after the first epoch is a PyTorch warning and it seems to be related to the training process. However, it's important to note that warnings can be inconsistent and may not always appear in every epoch.

If you're not encountering any other errors or issues during the training process, it's likely safe to continue with the training. Please let us know if you have any further questions or concerns, and we'll be happy to assist you.

**Comment by glenn-jocher** [comment]
@ExtReMLapin thanks for the PR! I see that when we train the models from YAML the ckpt structure is correct, so we are just going to train new RTDETR models and replace the existing assets with those. This should take a few days.

**Comment by glenn-jocher** [comment]
@ExtReMLapin ok I've updated the official checkpoints now in https://github.com/ultralytics/ultralytics/issues/3439 to contain complete dictionaries. Please delete any local files and let the updated models autodownload, and then once you've verified these work correctly we can close this PR as no longer needed.

**Comment by ExtReMLapin** [comment]
Thank you glenn, there is still an experiment running on our server, I'll take a look as soon as it's finished running !

**Comment by glenn-jocher** [comment]
@ExtReMLapin hi there! Thank you for reaching out. No problem, please take your time to look into the experiment once it's finished running. If you have any questions or need further assistance, feel free to ask. We're here to help!

**Comment by ExtReMLapin** [comment]
It's fixed !

**Comment by glenn-jocher** [comment]
@ExtReMLapin hi there! 

Thank you for letting us know that the issue is fixed. We're glad to hear that it's resolved! If you have any further questions or need any assistance with YOLOv8, please feel free to ask. We're here to help!

**Pull request closed without merging**
