### PR TITLE
Set alternative Comet project name through environment variables

### PR DESCRIPTION
**Pull request by lukasugar**
### Summary
🏷️🗂️📝

Added support for custom project names in Comet.ml logging. Refactored `ultralytics/yolo/utils/callbacks/comet.py` to use a local variable for the project name.

> _`COMET_PROJECT_NAME`_
> _A new env var for logging_
> _Autumn leaves organize_

### Walkthrough
*  Add support for custom project name for Comet.ml logging ([link](https://github.com/ultralytics/ultralytics/pull/3013/files?diff=unified&w=0#diff-88156d2cb2225824b539d2eeeece9b6157773bd05beabc136066535690b0d046L70-R73))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement to support dynamic Comet project names in the Ultralytics YOLO library.

### 📊 Key Changes
- COMET_PROJECT_NAME environment variable support added.
- Falling back to command line `args.project` if the environment variable is not set.
- Logging updated to include both `args` parameters and the current Comet project name.

### 🎯 Purpose & Impact
- 🔧 This change increases flexibility by allowing users to easily switch between different Comet projects without altering code.
- 🧩 It aids in organizing and comparing different experimental runs or training sessions.
- 📈 Users will benefit from a more streamlined workflow when using Comet.ml with the Ultralytics YOLO models.

### CODE REVIEW

**Comment by lukasugar** [comment]
Motivation described in this issue: https://github.com/ultralytics/ultralytics/issues/2932

**Comment by lukasugar** [comment]
I have read the CLA Document and I sign the CLA

**Comment by lukasugar** [comment]
recheck

**Comment by DN6** [comment]
Hi @lukasugar. Setting the project name via an environment variable works right out of the box with the current integration. For example: 

```
import os

from ultralytics import YOLO

os.environ["COMET_PROJECT_NAME"] = "my-comet-env-project-name"

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# train the model
results = model.train(
    data="coco128.yaml",
    batch=16,
    optimizer="AdamW",
    save_period=1,
    save_json=True,
    epochs=5,
)
```

Alternatively, if you export the project name environment variable and then run the script, you will log to the specified project. 

```
export COMET_PROJECT_NAME=my-project-name
```

```
python my_yolo_script.py
```

**Comment by glenn-jocher** [comment]
@DN6 thanks for the info! While you're here, can I ask for your opinion on https://github.com/ultralytics/yolov5/pull/11648? I've cleaned up the integration a bit, addressed some warnings, but I was wondering if it makes sense to present the user with a timed-out Comet login field just like the way YOLOv5 handles W&B logging (if wandb installed, prompt user for signin, continue after 5-10 second timeout, skip logging if no signin performed and continue training normally).

**Comment by glenn-jocher** [comment]
Closing as not planned. @lukasugar please don't hesitate to submit future PRs, contributions are welcome. Thank you for the effort!

**Pull request closed without merging**
