### PR TITLE
Skip MNN export for Raspberry Pi and NVIDIA Jetson

### PR DESCRIPTION
**Pull request by lakshanthad**
@glenn-jocher FYI

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Add checks to prevent MNN export on Raspberry Pi and Jetson devices due to unsupported compatibility.

### 📊 Key Changes
- Added a condition to skip the `test_export_mnn` for Raspberry Pi devices in the test suite.
- Introduced a system check in the exporter code to raise an error when attempting to export to MNN format on both Raspberry Pi and NVIDIA Jetson.

### 🎯 Purpose & Impact
- **Improved Compatibility Checks**: Ensures that users don’t encounter errors when trying to export models to MNN format on unsupported devices like Raspberry Pi and Jetson, enhancing user experience by preventing failed exports. 🛡️
- **Increased Test Reliability**: By skipping the test on unsupported hardware, it reduces false negatives in test results, providing clearer insights during development and deployment. 🧪

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @lakshanthad, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear and concise, following the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please resolve the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Keep your changes to the **minimum** necessary for your enhancement. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If this issue involves unexpected export behavior on the specified devices, could you provide a minimum reproducible example (MRE) of the problem? This will help us better assess and integrate your changes.

This is an automated response, and an Ultralytics engineer will review your contribution soon. Thank you for helping enhance Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@lakshanthad I think we need to remove MNN from tests/exports.py then also no?

**Comment by lakshanthad** [comment]
@glenn-jocher sorry I missed that. Now all good.

**Comment by glenn-jocher** [comment]
@lakshanthad looks good, PR merged!

**Comment by lakshanthad** [comment]
Thanks! @glenn-jocher

**Pull request merged**
