### PR TITLE
Export tables (en) format with ref-links

### PR DESCRIPTION
**Pull request by Burhan-Q**
## Changes

- All `docs/en` Export Formats Tables updated to use markdown reference links (helps to prevent markdown table line wrap)
    - all reference links appended to end of markdown file
- `Metadata` column center aligned
- Adjusted width of column headers to match new column width in markdown table

Used VSCode regex pattern to find + replace all tables (excludes headers, for compatibility with other languages):
-  `\| \[PyTorch\]\(http.*\) *(\|.*\n){11,}`
    - NOTE: this will also pick up YOLOv5 tables (changes were discarded in this PR as these don't need to be modified)

### Preview of `mkdocs` rendering of table (dark mode)
`mkdocs` rendered table preview

### Summary
📝🔄🔗

This pull request updates the documentation of the export formats supported by the ultralytics platform in various files under the `docs/en` directory. It uses reference links for the formats and adds more details and links for each format in a consistent way. It affects the files `integrations.md`, `index.md`, `cli.md`, `benchmark.md`, `export.md`, `classify.md`, `detect.md`, `pose.md`, and `segment.md`.

> _The docs of the export formats needed some fixes_
> _So they added more details and reference links with `F0L30R30`_
> _They changed the tables in many files like `benchmark.md`_
> _And also in `export.md` and `detect.md`_
> _Now the docs are more consistent and informative with `F0L61R61`_

### Walkthrough
* Replace full URLs of export formats with reference links in tables across eight documentation files ([link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-c9d5515b2319e7431c8012e8c551f9bd0bbc22f7b87fa8209c167f80309b0349L32-R46), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-911d7848f77e8bcef9a0e9f2d05cecd89c6cccabda23551e907784b1f7575eb2L45-R59), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-302ae56b4720a23457cd187c4968a877ca9990c084b3ca65d02f54f37d286896L78-R108), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-039a49a0e1108cd98696a4fb610482afad76600040018008ef56968d08d2c956L94-R122), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-9cee0982d4ccd54293463b9f68bba96df998475e534df59daaa3ad4caf171445L157-R187), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-6003374c2b2b75e40562b45c87ecdfcd9972446188fbcb6b4c96823e31cedf79L169-R199), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-e87e01d4026722827f9d3a666bc3462191d94b935504d99bc5b4f636b7a70062L173-R203), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-d5f622e96b28ff55dc4b41ed47dcdcb429e47c4ace3a360cdf3cd504a2e03d29L174-R204), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-1c3934c354e3e4bb6e476edf124b38828a5058376d3b796873ae9c9ed44a77d1L173-R187))
* Add reference links for export formats at the end of each documentation file (`docs/en/hub/integrations.md`, `docs/en/integrations/index.md`, `docs/en/modes/benchmark.md`, `docs/en/modes/export.md`, `docs/en/tasks/classify.md`, `docs/en/tasks/detect.md`, `docs/en/tasks/pose.md`, `docs/en/tasks/segment.md`, `docs/en/usage/cli.md`) ([link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-c9d5515b2319e7431c8012e8c551f9bd0bbc22f7b87fa8209c167f80309b0349L63-R76), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-911d7848f77e8bcef9a0e9f2d05cecd89c6cccabda23551e907784b1f7575eb2L72-R84), [link](https://github.com/ultralytics/ultralytics/pull/6368/files?diff=unified&w=0#diff-1c3934c354e3e4bb6e476edf124b38828a5058376d3b796873ae9c9ed44a77d1L228-R241))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refinement of documentation related to export formats and external integrations.

### 📊 Key Changes
- Standardized the tables listing export formats for improved readability.
- Added comprehensive links to external resources, tools, and frameworks relevant to model exportation and deployment (e.g., PyTorch, ONNX, TensorRT, CoreML, and more).
- Included these links in various sections throughout the documentation, including integrations and usage instructions for different tasks (classification, detection, pose estimation, segmentation).

### 🎯 Purpose & Impact
- **Enhanced Clarity:** The documentation gets a clearer layout 🔍, making it easier for users to find and understand the available export formats and arguments.
- **Resource Accessibility:** Quick access to external resources provides users with a seamless workflow when exporting models to various formats and using different tools 🛠️.
- **User Confidence:** With better documentation and links to additional information, users are more likely to trust and effectively use Ultralytics’ tools and integrations 🤝.
- **Increased Visibility:** Listing and linking to various platforms may boost awareness and usage of Ultralytics' integrations within those ecosystems 🌐.
- **Educational Value:** The links can serve as an educational tool for users unfamiliar with certain formats or tools, contributing to the learning aspect of the platform 🎓.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q we could do a few optimizations here. If a table is reused a lot, we could call it with a snippet, and if a URL is re-used a lot, we could call it also with a snippet:
https://facelessuser.github.io/pymdown-extensions/extensions/snippets/

The problem with repeating tables though is that the column headers will not translate as they're not actually in the markdown files.

**Comment by glenn-jocher** [comment]
@Burhan-Q also noticed you have a change of OpenVINO link from our docs page to their website, we want this to direct to our webpage.

**Comment by glenn-jocher** [comment]
@Burhan-Q I think let's wait on this until we determine how useful the snippets integration can be here. 

Also one point here is that I'd rather these direct to our own docs as we do with OpenVINO, so the right solution is to create those docs pages under /integrations and then update these links to point to those *.md files.

I just haven't had time to create individual docs pages for each format yet:
Screenshot 2023-11-16 at 20 57 53

**Comment by Burhan-Q** [comment]
@glenn-jocher understood, would you like me to close this PR?

**Pull request closed without merging**
