### PR TITLE
Update Readme to add google colab link

### PR DESCRIPTION
**Pull request by ichsan2895**
Add google colab that contains training in custom dataset with `yolov5m-seg` vs `yolov7-seg` vs `yolov8m-seg`

### Summary
🖼️🔗🚀

This change updates the `README.md` file with a colab link for segmentation model comparison. The change is part of a pull request that adds segmentation models and datasets to the ultralytics repository.

> _`colab` notebook link_
> _compare segmentation models_
> _autumn leaves in view_

### Walkthrough
*  Introduce segmentation models and datasets based on yolov5, yolov7 and yolov8 (F1,F2,F3,F4,F5,F6,F7,F8,F9,F10,F11,F12,F13,F14,F15,F16,F17,F18,F19,F20,F21,F22,F23,F24,F25,F26,F27,F28,F29,F30,F31,F32,F33,F34,F35,F36,F37,F38,F39,F40,F41,F42,F43,F44,F45,F46,F47,F48,F49,F50,F51,F52,F53,F54,F55,F56,F57,F58,F59,F60,F61,F62,F63,F64,F65,F66,F67,F68,F69,F70,F71,F72,F73,F74,F75,F76,F77,F78,F79,F80,F81,F82,F83,F84,F85,F86,F87,F88,F89,F90,F91,F92,F93,F94,F95,F96,F97,F98,F99,F100

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added a Google Colab link for experimenting with segmentation models.

### 📊 Key Changes
- Included a Colab link in the README for testing `yolov5m-seg`, `yolov7-seg`, and `yolov8m-seg` models.

### 🎯 Purpose & Impact
- 🧪 **Ease of Experimentation**: Provides a quick, interactive way to compare different segmentation models.
- 🚀 **Accessibility**: Users can now easily test models without complex local setups, enhancing learning and exploration.

### CODE REVIEW

**Comment by ichsan2895** [comment]
I have read the CLA Document and I sign the CLA

**Comment by AyushExel** [comment]
Thanks for the PR!
2 things I'd change:
1. Instead of linking an external colab, we'd like to have the .ipynb file in the examples/ folder directly on the repo.
2. There is no need to setup 3 times. Ultralytics repo can support and yolo version. We just don't have the pre-trained models for all of them so we might have to wait for that. But it'll be a better approach as it would eliminate the need to 3 different repos

**Comment by ichsan2895** [comment]
> Thanks for the PR! 2 things I'd change:
> 
> 1. Instead of linking an external colab, we'd like to have the .ipynb file in the examples/ folder directly on the repo.
> 2. There is no need to setup 3 times. Ultralytics repo can support any yolo version(v3,v4,v,5,v6,v7). We just don't have the pre-trained models for all of them so we might have to wait for that. But it'll be a better approach as it would eliminate the need to setup 3 different repos

Yeah I still don't know how to make one time for setup. So I manually setup it for each version (especially yolov7 which have special branch u7 for segmentation instead of main branch)

**Comment by AyushExel** [comment]
@ichsan2895 yeah don't worry we'll provide a tutorial soon for setting up different models

**Comment by ichsan2895** [comment]
Thanks for that,
I created that notebook because some people (included me) curious about the performance of the new yolo, especially with custom dataset and segmentation.

Hopefully It will be published, so every contributor can see the performance of yolo with custom dataset that can be easily change from roboflow

**Comment by AyushExel** [comment]
Yes. We're working on many exciting things including all of which you mentioned. Can't wait to share an update soon. Stay tuned!

**Pull request closed without merging**
