### PR TITLE
Add more informative dataset not found error message

### PR DESCRIPTION
**Pull request by joseliraGB**
Github ultralytics/ultralytics ultralytics #1881
Can't change the default dir where YOLOV8 downloads example datasets
- "USER_CONFIG_DIR" is imported from ultralytics.yolo.utils
- A message to the user is added: "Please, check: {USER_CONFIG_DIR}/settings.yaml"
to allow quick troubleshooting of the issue
Deleted "name variable," which is not used in 
the function: "check_det_dataset()"
Deleted "clean_url" which is not used in shit module. I have read the CLA Document, and I sign the CLA

### Summary
📥💬🛠️

Refactored the `ultralytics.yolo.utils` module to use a variable for the global settings YAML file path and imported it in `ultralytics/yolo/data/utils.py` to improve user experience and customization of dataset download location.

> _Sing, O Muse, of the skillful coder who refactored_
> _The `utils` module of the `yolo` package, and made it more ordered_
> _By using a variable for the `SETTINGS_YAML` path_
> _That guides the users to download the dataset with less wrath_

### Walkthrough
*  Import and use `SETTINGS_YAML` variable to access global settings YAML file in `check_det_dataset` function ([link](https://github.com/ultralytics/ultralytics/pull/1936/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58L20-R21), [link](https://github.com/ultralytics/ultralytics/pull/1936/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58R250))
* Define `SETTINGS_YAML` variable in `ultralytics.yolo.utils` module to store the default path to global settings YAML file ([link](https://github.com/ultralytics/ultralytics/pull/1936/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137R493))
* Replace hardcoded paths with `SETTINGS_YAML` variable in `get_settings` and `set_settings` functions ([link](https://github.com/ultralytics/ultralytics/pull/1936/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137L594-R595), [link](https://github.com/ultralytics/ultralytics/pull/1936/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137L643-R644))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced configuration management for dataset directories.

### 📊 Key Changes
- Added a constant `SETTINGS_YAML` for the settings file path.
- Provided an informative note on how to change the dataset download directory through `SETTINGS_YAML`.

### 🎯 Purpose & Impact
- **Purpose**: To streamline user ability to configure settings and improve error messaging when dataset downloads fail.
- **Impact**: Users now have a clearer pathway to customize their dataset download directory, and receive more helpful error messages when something goes wrong. This contributes to a more user-friendly experience with Ultralytics software.

### CODE REVIEW

**Comment by joseliraGB** [comment]
TYPO: 
It should be: 'Deleted "clean_url" which is not used in this module. I have read the CLA Document, and I sign the CLA'

**Comment by joseliraGB** [comment]
Github ultralytics/ultralytics ultralytics https://github.com/ultralytics/ultralytics/issues/1881
Can't change the default dir where YOLOV8 downloads example datasets

"USER_CONFIG_DIR" is imported from ultralytics.yolo.utils
A message to the user is added: "Please, check: {USER_CONFIG_DIR}/settings.yaml"
to allow quick troubleshooting of the issue
Deleted "name variable," which is not used in
the function: "check_det_dataset()"
Deleted "clean_url" which is not used in this module. I have read the CLA Document, and I sign the CLA

**Comment by joseliraGB** [comment]
Hello Glenn,
I deleted it as it does not pass the automatic test. It says it is not used. 
The main issue is:
"USER_CONFIG_DIR" is imported from ultralytics.yolo.utils
A message to the user is added: "Please, check: {USER_CONFIG_DIR}/settings.yaml"
to allow quick troubleshooting of the issue.
Some users (including myself) were spending a lot of time figuring out this issue when they changed the directory of the datasets, and including a message will save them many hours

**Comment by glenn-jocher** [comment]
Hi there @joseliraGB, thank you for considering the user experience and for contributing to the YOLOv8 project. Adding the message to the user prompt is a great idea and will certainly help users identify and troubleshoot any issues with downloading datasets. It will positively impact the user experience and make it easier for them to work with the project. Keep up the good work and thanks for contributing!

**Pull request merged**
