### PR TITLE
Add YOLOv8 OBB training, validation and inference support

### LINKED ISSUE #4242: Help Wanted 🙏 Add Oriented Bounding Boxes (OBB) Task with DOTA v2 Training
Hello YOLOv8 Enthusiasts,

We are reaching out to the talented community to help add support for [DOTA v2](https://captain-whu.github.io/DOTA/dataset.html) training with Oriented Bounding Boxes (OBB) for our YOLOv8 repository. This addition will notably enhance our detection capabilities for remote sensing imagery, enabling superior performance for real-world applications.

Related to issue https://github.com/ultralytics/ultralytics/issues/624 and PR https://github.com/ultralytics/ultralytics/pull/1977

## Project Description:

Our primary objective with this issue is to integrate the DOTA v2 dataset into our YOLOv8 training pipeline, with a focus on Oriented Bounding Boxes. This demands crafting methods or functions to accommodate the unique data format of DOTA v2, and seamlessly incorporate it into our existing training framework.

## Example code:

```python
from yolov8 import YOLO

# Initialize a model
model = YOLO('yolov8n-obb.pt')  # load a pretrained OBB model

# Train the model on DOTA v2 with OBB
model.train(data='DOTAv2.yaml', epochs=30, imgsz=640)
```

In this envisaged example, the `data` argument would accept a configuration file specifically crafted for the DOTA v2 dataset with OBB, `'DOTAv2.yaml'`. This configuration file should encompass all essential details to fetch, process, and utilize the dataset during training.

## Expected Deliverables:

- Code that processes and manages the DOTA v2 dataset with Oriented Bounding Boxes.
- Comprehensive test cases to validate the flawless functioning of the added feature.
- Amended documentation, enlightening users on the ins and outs of this fresh capability.

## How to contribute:

1. Express your interest in this endeavor by commenting on this issue.
2. Fork the YOLOv8 repository.
3. Generate a fresh branch in your forked repository.
4. Execute the necessary code modifications.
5. Develop tests that corroborate the effectiveness of your code.
6. Revise the README and affiliated documentation accordingly.
7. Submit a detailed pull request, illuminating your changes, their relevance, and how they enhance the repository.

Every contribution, regardless of its magnitude, is deeply appreciated. Your efforts contribute massively to the broader community, and every input is treated with respect.

## Community Support:

To amplify its visibility, this issue will be pinned. If you need support or have inquiries, do not hesitate to contact us either on this thread or via our [Discord](https://ultralytics.com/discord).

Gratitude and best wishes on your coding journey!

Warm Regards,
The YOLOv8 Team

### PR DESCRIPTION
**Pull request by yoloyash**
EDIT: This PR merged into `obb` branch due to inactivity by original author. Work will continue there.

Hi, this is an initial commit to add the support for oriented bounding boxes as per the conversation with @AyushExel and @glenn-jocher and includes all the changes made in the commits linked to my previous PR #1958 . Will make the other code changes in dataloader and model files incrementally.
#624 

### Summary
📦🧭🎯

This pull request adds support for the obb (oriented bounding box) task to the ultralytics/nn and ultralytics/yolo packages. It defines a new OBBModel class, a new OBB module, and a new YAML configuration file for the YOLOv8 obb model. It also updates the existing files to enable the obb task and prepares the framework for the obb training, validation, and prediction logic.

> _We unleash the beast of YOLOv8_
> _With `obb` we dominate_
> _We detect the angles of our prey_
> _No one can escape our fate_

### Walkthrough
*  Add a new YAML file for the YOLOv8 obb model with orientation-aware bounding boxes ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-862c6566244eb7a4639186dd7eb437fad92c873c254ef2cf826510f378404291R1-R46))
*  Implement a new OBB class that inherits from the Detect class and adds an additional output for the orientation angles ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-7bb55fea226aca9e349baf67b2a6011df4f4a9b5863393d60666c22575cef95eR435-R456))
*  Implement a new OBBModel class that inherits from the DetectionModel class and uses the yolov8n-obb.yaml file as the default configuration ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R242-R251))
*  Add the OBB class to the list of modules that require the channel arguments in the parse_model function ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L478-R488))
*  Add cases for the obb task and the OBB module in the cfg2task and guess_model_task functions in `ultralytics/nn/tasks.py` ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R569-R570), [link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R595-R596), [link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R607-R608), [link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L598-R614))
*  Add the obb task to the valid tasks and modes and the default data and model files in `ultralytics/yolo/cfg/__init__.py` ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-daf1714127b012666c9fed39d0e75184c60be83f0c6bd3f9863f27113b1a6c22L17-R29))
*  Add the obb task to the TASK_MAP variable and import the OBBModel class in `ultralytics/yolo/engine/model.py` ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL8-R8), [link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL29-R31))
*  Add a new file for the obb task in `ultralytics/yolo/v8/obb/__init__.py` with placeholders for the obb trainer, validator, and predictor classes ([link](https://github.com/ultralytics/ultralytics/pull/1977/files?diff=unified&w=0#diff-7597c7f117d7bf0c87438d126b9939f366a60db58662d6e147475a1164b2f2f5R1))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Ultralytics adds oriented bounding box (OBB) support to YOLOv8 models.

### 📊 Key Changes
- Added a new task `'obb'` for oriented bounding box detection.
- New file `yolov8-obb.yaml` defines OBB model configuration.
- Implemented data augmentation operations for OBB, including affine transformations.
- `build.py` and `dataset.py` updated to handle new `'obb'` task during dataset build and loading.
- Incorporated new methods and classes like `OBBPredictor`, `OBBTrainer`, `OBBValidator`, `OBBMetrics`, and `v8OBBLoss` for handling the new OBB task.
- Modified `instances.py` to manage OBB-specific data such as theta angles.

### 🎯 Purpose & Impact
- This update enables the detection of arbitrarily rotated objects, enhancing the model's utility in various real-world scenarios like satellite and aerial imagery analysis.
- The newly added OBB task, alongside the supporting code, extends the model's functionality and allows users to tackle more complex computer vision problems.

### CODE REVIEW

**Comment by yoloyash** [comment]
I have read the CLA Document and I sign the CLA

**Comment by swamitagupta** [comment]
This looks very interesting! If you don't mind, I would like to contribute to this too @yoloyash @glenn-jocher

**Comment by AyushExel** [comment]
@swamitagupta sure everyone is welcome to contribute. Would you like to work on the dataloader or visualizer aspect? There are many such things needed to make this trainable

**Comment by glenn-jocher** [comment]
@yoloyash yes, it is a good idea to input the data in the DOTA format, which uses four corner points to define the bounding box, along with the class and difficulty level. We can then convert it to the (x,y,w,h,theta) format internally before caching it. This conversion can be performed using algorithms such as the minimum area rectangle method or the minimum volume parallelepiped method, which can compute the width, height, and orientation angle of the bounding box from its corner points. This will enable us to utilize the DOTA dataset for training and evaluation of the YOLOv8 model for oriented bounding box detection.

**Comment by yoloyash** [comment]
@glenn-jocher Sure. I have implemented the dataloader to accept and cache as you mentioned. Will be looking into the augmentations part now. And try the approaches you mentioned.

**Comment by glenn-jocher** [comment]
@yoloyash great to hear that you have implemented the dataloader to accept and cache data in DOTA format.  As for the augmentation part, we can apply geometric and photometric augmentations to the data to augment the dataset for improving the performance of the model. We can use image processing techniques such as image flipping, cropping, and color jittering for photometric augmentation, and affine transformations such as scaling, rotation, and shearing for geometric augmentation. Also keep in mind that while augmenting the data, we need to ensure that the ground-truth labels of the bounding boxes also get transformed accordingly.

**Comment by joramvdsluis** [comment]
> I found a list of projects that implemented OBB, maybe it will help someone. [OBB](https://github.com/sjinzh/awesome-yolo-object-detection#oriented-object-detection)

[mmroate](https://github.com/open-mmlab/mmrotate) could also be a very valuable repo to get some inspiration from. 

--

What are your thoughts about angle [definitions](https://mmrotate.readthedocs.io/en/latest/intro.html?highlight=angle%20#definition-of-rotated-box)?

The angle definitions above are mostly defined between ∈[-pi / 2, pi / 2).

I would opt for an angle definition of ∈[-pi, pi) -or ∈[-180, 180]) -. This is more convenient and intuitive to use then the angle∈[-pi / 2, pi / 2), it also allows the definition of a top/front for an object (e.g. car/LED). What do you think?

**Comment by glenn-jocher** [comment]
@joramvdsluis thanks for sharing these resources, they may come in handy during the development of OBB support in YOLOv8. As for the angle definition, I can see the benefits of using an angle range of [-pi, pi) or [-180, 180], as it is more intuitive and allows for defining a clear top/front for objects. The choice of angle definition also depends on the application and dataset being used. However, we need to ensure that the chosen angle definition is consistent across the entire dataset and training process, and that it does not affect the performance of the model.

**Comment by swamitagupta** [comment]
I have read the CLA Document and I sign the CLA

**Comment by swamitagupta** [comment]
Hi @AyushExel , 
I apologise for my late reply. I am working on the dataloaders with @yoloyash and have added support for different augmentations like flip, rotation, perspective etc till now.

**Comment by swamitagupta** [comment]
> @joramvdsluis thanks for sharing these resources, they may come in handy during the development of OBB support in YOLOv8. As for the angle definition, I can see the benefits of using an angle range of [-pi, pi) or [-180, 180], as it is more intuitive and allows for defining a clear top/front for objects. The choice of angle definition also depends on the application and dataset being used. However, we need to ensure that the chosen angle definition is consistent across the entire dataset and training process, and that it does not affect the performance of the model.

Currently the dataloaders accepts angles in the range -180 to 180 degrees which is normalised between [0,1]

**Comment by glenn-jocher** [comment]
@swamitagupta sure, I understand that the dataloaders accept angles in the range of -180 to 180 degrees, which is normalized between [0,1]. Using this angle range allows for a more intuitive definition of angles and enables defining a clear top/front for objects. It is crucial to ensure that the chosen angle definition is consistent across the entire dataset and training process, as it can impact the performance of the model. By normalizing the angles between [0,1], we can ensure that the model is trained on consistent and standardized data, which can improve the accuracy of the predictions. Nonetheless, we need to keep in mind that the angle range and normalization technique may vary depending on the application and dataset.

**Comment by yoloyash** [comment]
@glenn-jocher We've made changes to the dataloader to accept and treat data in the format mentioned by you. Would you mind going through the full changes once? If any changes need to be made to the data loading part we can change them right now easily. Going forward we will need some help from your side to finish the augmentations part since we're having trouble handling edge cases (objects which go outside the image area after applying augmentations such as rotation, mosaic etc). Any input on how to handle them would be very helpful.

**Comment by glenn-jocher** [comment]
@yoloyash sure, I would be happy to go through the changes you have made in the dataloader to accept and treat data in the format required for oriented bounding box detection. It is essential to ensure that the data is in a consistent format and meets the requirements of the model for efficient training and accurate predictions. As for the edge cases arising during augmentation, we can handle them by setting appropriate constraints and boundaries during the augmentation process. For example, when rotating an object, we can crop the resulting image by selecting only those pixels that are inside the original image area to avoid images with missing or invalid data. Similarly, when performing mosaic augmentation, we can ensure that the objects do not overlap with each other or go beyond the image boundaries. We can also experiment with various augmentation techniques and see which works best for our dataset and model. Nonetheless, it is crucial to handle edge cases meticulously during augmentation to avoid introducing any unwanted bias or errors in the dataset. Let me know if you have any further questions or suggestions on this matter.

**Comment by yoloyash** [comment]
@glenn-jocher Hi, I took your advice and implemented vMF loss in PyTorch for loss calculation of theta. Does this look okay? I'm currently using a custom function for implementing the Bessel function of the first kind. However, we can also use the implementation given by torch.special.i0. 

`def bessel_i0(x):
    x = torch.tensor(x) if not isinstance(x, torch.Tensor) else x
    ax = torch.abs(x)
    y = (x / 3.75) ** 2
    ans = torch.where(ax < 3.75, 1 + y * (3.5156229 + y * (3.0899424 + y * (1.2067492 + y * (0.2659732 + y * (0.360768e-1 + y * 0.45813e-2))))), torch.exp(ax) / torch.sqrt(ax) * (0.39894228 + y * (-0.39894228e-1 + y * (-0.362018e-2 + y * (0.163801e-2 + y * (-0.1031555e-1 + y * 0.2282967e-1))))))
    return ans

class VonMisesFisherLoss(nn.Module):
    def __init__(self, concentration=1.0):
        super().__init__()
        self.concentration = concentration

    def forward(self, predicted_angle, target_angle):
        # Convert angles to unit vectors
        predicted_vector = torch.stack([torch.cos(2 * torch.pi * predicted_angle),
                                        torch.sin(2 * torch.pi * predicted_angle)], dim=-1)
        target_vector = torch.stack([torch.cos(2 * torch.pi * target_angle),
                                     torch.sin(2 * torch.pi * target_angle)], dim=-1)

        # Compute the vMF loss
        dot_product = (predicted_vector * target_vector).sum(dim=-1)
        loss = -torch.log(torch.exp(self.concentration * dot_product).mean(dim=-1) / bessel_i0(self.concentration))

        return loss.mean()

vmf_loss = VonMisesFisherLoss(concentration=1.0)
theta_loss = vmf_loss(predicted_theta, target_theta)`

**Comment by AyushExel** [comment]
I've tried to resolve conflicts with main but please make sure that its working as expected

**Comment by Ykrowa** [comment]
wow. its looks like very cool. What about readme.md?

**Comment by glenn-jocher** [comment]
@Ykrowa thank you for your interest in YOLOv8! We are glad to hear that you found our implementation promising. As for the README.md file, we are constantly updating it to provide the most up-to-date information about the repository, including installation instructions, usage guidelines, and other relevant information. We understand the importance of having a comprehensive and easy-to-use documentation, and we are committed to making it as clear and concise as possible for the benefit of our users. If you have any specific questions or suggestions on how we can improve the README.md, feel free to let us know or submit a pull request. Once again, thank you for your support and interest in YOLOv8.

**Comment by haimat** [comment]
Hey guys, this OBB support looks really great, can't wait to try with our own projects.
Is this new feature already available in the main branch?
If so, how is one supposed to use it, i.e. how should we format the label.txt files?

**Comment by glenn-jocher** [comment]
@haimat thank you for your interest in YOLOv8! We are glad to hear that you find our OBB support promising. Yes, OBB support is available in the main branch of the repository. To use it, you need to format your label.txt files in a specific way. You should include the coordinates of the four corners of the bounding box, along with the angle of the bounding box. The four coordinates should be represented as: x1,y1,x2,y2,x3,y3,x4,y4 while the angle should be given in degrees. For orientation, 0 degrees corresponds to the positive x-axis, and the angle increases in the counterclockwise direction.  We hope this helps! If you have any further questions or clarifications, please do not hesitate to ask.

**Comment by sccrouch88** [comment]
> @haimat thank you for your interest in YOLOv8! We are glad to hear that you find our OBB support promising. Yes, OBB support is available in the main branch of the repository. To use it, you need to format your label.txt files in a specific way. You should include the coordinates of the four corners of the bounding box, along with the angle of the bounding box. The four coordinates should be represented as: x1,y1,x2,y2,x3,y3,x4,y4 while the angle should be given in degrees. For orientation, 0 degrees corresponds to the positive x-axis, and the angle increases in the counterclockwise direction. We hope this helps! If you have any further questions or clarifications, please do not hesitate to ask.

Hi folks - I'm excited about this feature as well!  A few questions/clarifications. (Been attempting to get the obb-dev branch to run w/ the DOTA_V2.0 dataset as a trial run). 

Is obb model training actually in the main branch? I'm not seeing the "obb" support developed in @yoloyash 's obb-dev folded into main.  

Do you expect the cli syntax to be something like "yolo obb train data= ...etc." 

Finally, a few label formatting questions for obb support. Do you expect the x1,y1,x2,y2,x3,y3,x4,y4 bounding box corner coordinates will be normalized to image extent in the same way as standard YOLO labels? Or will they be pixel values like DOTA_V2.0? Is class specified before corner coordinates on each line? Will "theta" be inferred from the corner coordinates in your internal conversion from DOTA to YOLO style or should that also be specified? Is this "difficulty" value from DOTA necessary?

Thanks and keep up the good work!

**Comment by yoloyash** [comment]
@sccrouch88 Hello! I think there's been a confusion here. OBB support is not yet fully supported. We're currently working to add support for it. We're making it so that the input format will be DOTA (x1,y1,x2,y2,..) and will be converted to xywh-theta format as per the implementation of cv2.minAreaRect(). We're experimenting with various loss functions for theta currently and will finish the PR soon. Thanks for your support!

**Comment by glenn-jocher** [comment]
Hi @sccrouch88, thank you for your interest in YOLOv8! However, it seems that there has been a misunderstanding regarding the current state of OBB support in our repository. We apologize for any confusion our earlier messages might have caused. Please note that OBB support is not yet fully supported in YOLOv8. We are currently working on adding support for it by experimenting with various loss functions for theta, and the conversion of DOTA format to xywh-theta format as per the implementation of cv2.minAreaRect(). Our team is working hard to get this implemented as soon as possible. We appreciate your support and encourage you to stay tuned for updates on our progress. If you have any further questions or concerns, please feel free to let us know. Thank you for your understanding.

**Comment by glenn-jocher** [comment]
@JustasBart thank you for your enthusiasm and interest in YOLOv8! We appreciate any help and support we can get from the community. Since YOLOv8 is a PyTorch implementation, most of the development and testing is done in Python. However, there are definitely ways in which you can contribute even if you are more comfortable with C++. We are currently working on optimizing the code for better performance and speed. Any contributions related to C++ optimization or improving the C++ inference code would be greatly appreciated. Additionally, if you have any feedback, suggestions, or bug reports to help us improve the repository, please do not hesitate to share them with us. Once again, thank you for your support, and we look forward to collaborating with you!

**Comment by Rohinivv96** [comment]
@glenn-jocher  Hi, I am very excited to use the OBB feature of YOLOv8.
Is this new feature of OBB now available in the main branch?

**Comment by egeakman** [comment]
Any news on this one?

**Comment by yoloyash** [comment]
@egeakman @arvisioncode @Rohinivv96 We have stalled the development on this as we need help in the process and as confirmed by @AyushExel, the Ultralytics team is currently busy with other leads. We will continue the work on this once we receive a response. Looking forward to adding the full support for oriented bounding boxes in yolov8.

**Comment by shotyme** [comment]
> @egeakman @arvisioncode @Rohinivv96 We have stalled the development on this as we need help in the process and as confirmed by @AyushExel, the Ultralytics team is currently busy with other leads. We will continue the work on this once we receive a response. Looking forward to adding the full support for oriented bounding boxes in yolov8.

Any ETA? The OBB support would be so amazing!

**Comment by glenn-jocher** [comment]
@shotyme hi there! Thank you for your interest in YOLOv8 and our OBB support. We apologize for any delays in the development process. At the moment, we don't have an exact ETA for the release of full support for oriented bounding boxes in YOLOv8. Our team is actively working on it, but we can't provide a specific timeline as we are currently focused on other priorities. Rest assured, we are committed to adding this feature and we appreciate your patience. We understand the excitement around OBB support and we'll keep the community updated on our progress. Thank you for your understanding and continued support!

**Comment by xiaofulee** [comment]
@yoloyash I ran the program, but it seems that some modules have not been implemented yet (OBBTrainer/OBBValidator/OBBPredictor), is there a plan to finish it later?

**Comment by glenn-jocher** [comment]
@xiaofulee Thank you for your interest in YOLOv8! Currently, the OBBTrainer, OBBValidator, and OBBPredictor modules have not been fully implemented in this repository. However, we are actively working on adding support for oriented bounding boxes in YOLOv8. Our team is experimenting with various loss functions for theta and exploring the conversion of DOTA format to xywh-theta format, as per the implementation of cv2.minAreaRect(). We appreciate your patience and understanding as we work towards completing these modules. Stay tuned for updates on our progress, and thank you for your support!

**Comment by JustasBart** [comment]
Hi guys, is this dead in the water by now or what? I thought it was going really well there for some time but it's beginning to drag into months and months... Any updates on this at all or not really?

Thanks! 🚀

**Comment by glenn-jocher** [comment]
@JustasBart hi there! We really appreciate your interest and patience. Support for Oriented Bounding Boxes (OBB) is indeed a significant feature we're excited about. However, implementing it demands a considerable effort and careful testing to ensure its accuracy and efficiency.

We assure you that the feature has not been abandoned. Our team is actively working on it among other priorities. Given the complexity of the task, it's taken a bit longer than expected. We understand that the wait might be frustrating, but we want to deliver a feature that meets the high standards set by the Ultralytics team and our community.

We don't have a precise timeline that we can share right now, but please do stay tuned for updates. We're as eager as you are to see this feature implemented and we appreciate your continued support. 🚀

**Comment by glenn-jocher** [comment]
@yoloyash @JustasBart and everyone else here on the OBB PR, thank you for your patience and apologies for the delay. We've been very busy making some important updates and structural changes to the repo (.i.e. ultralytics/yolo/utils/ directory was moved to ultralytics/utils primarily), but we are now freeing up some availability to dedicate to this effort. 

Due to significant refactor by @Laughing-q a number of directories were moved, and unfortunately this has resulted in a number of conflicts now. The two possible routes forward are:

- Resolve conflicts one by one.
- Submit a new PR based on the new repo structure.

There are no more large refactorings planned for the future so either route is safe to take, whatever is easiest.

In terms of training we want to provide support for training OBB on the DOTA dataset. This should be a separate PR and I can get that started. I just added support for Open Images V7 via a new open-images-v7.yaml, so I'm excited to add DOTA also.

Let me know the preferred route and I'll do my best to support this and get this reviewed and approved ASAP given the substantial delay so far. 

Thank you!

**Comment by glenn-jocher** [comment]
@yoloyash @JustasBart opened DOTAv2 dataset PR https://github.com/ultralytics/ultralytics/pull/4258 in support of this PR

**Comment by glenn-jocher** [comment]
@yoloyash @JustasBart @Kayzwer good news!! I've deconflicted this PR. I think I did this correctly but can you please review and verify that everything is working correctly?

**Comment by glenn-jocher** [comment]
@yoloyash @JustasBart @Kayzwer good news!! I've completed numerous tasks for OBB in https://github.com/ultralytics/ultralytics/pull/4258 and here.

- I've downloaded DOTAv2, converted it's labels to the new YOLO OBB label format and uploaded to get it ready for autodownload when called, i.e. `yolo train data=DOTAv2.yaml`
- I've created a new OBB docs pages that detail our new YOLO OBB labels format in https://docs.ultralytics.com/datasets/obb/
- I've created a new DOTAv2 dataset docs page that shows intended Usage examples and shows dataset information in https://docs.ultralytics.com/datasets/obb/dota-v2/
- I've created 2 new functions to transform boxes from xywhr (xywh, rotation) to xyxyxyxy (the 4 OBB xy points).
- I've deconflicted and updated this PR https://github.com/ultralytics/ultralytics/pull/1977 to bring it up to speed to `main` branch

@yoloyash as the lead author on the PR can you please review all changes and update the PR with any fixes or remaining items that are required?

**Comment by glenn-jocher** [comment]
@yoloyash hi there! Can you please take a look at the current PR and make any updates required? I've deconflicted this and brought it up to `main`, now we need to evaluate training and validation on DOTAv2, and then inference and export also, add to CI etc. 

Would you like to take the lead on this?

**Comment by yoloyash** [comment]
Hello @glenn-jocher. Thanks for the update. I’ll check it out!

**Comment by glenn-jocher** [comment]
@yoloyash ok I've added a task map to allow the YAMLs to build, but now there is an error in OBB head. I see it's set up for 180 vector estimates, but I'm not sure if this is the best idea. I think we just want to use the theta-based OBB version here for xywh theta:

https://docs.ultralytics.com/datasets/obb/

image

**Comment by glenn-jocher** [comment]
This PR merged into `obb` branch due to inactivity by original author. Work will continue there.

**Comment by karthikyerram** [comment]
@glenn-jocher really looking forward to this update. Can I know what is the status? Is it in the trainable state yet? when can we expect the release?
Looking forward to your answer.

**Comment by glenn-jocher** [comment]
@karthikyerram the OBB feature is actively being developed on the `obb` branch. It's not yet in a trainable state, but progress is being made. I'm hesitant to provide a specific release date, as development can be unpredictable. Stay tuned for updates, and we appreciate your enthusiasm and patience! 👀🚀

**Pull request merged**
