### PR TITLE
Chiragagarwals patch 2

### PR DESCRIPTION
**Pull request by chiragagarwals**
### Summary
🚨🚀📝

This pull request adds the `FOD_YOLOv8` package, which is a custom extension of the `ultralytics` package for foreign object detection using the YOLOv8 model. The package provides classes for training, predicting, and alerting with a buzzer sound when a foreign object is detected. The pull request also deletes several files related to GitHub workflows, issue templates, and other documentation that are not relevant for the `FOD_YOLOv8` package.

> _`FOD_YOLOv8` grows_
> _Adding custom modules for_
> _Detection and training_

### Walkthrough
*  Add `FOD_YOLOv8` package for foreign object detection using YOLOv8 model ([link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-7cae9db484e13d35ebc45ed49ab9f0663246afe2a7e0094d8fcece6b7c6d68a2L1-R6), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-670d660e539bdaecd37de882931da392f210dfae647706cb6f58d5e586ed446bR1-R43), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-dfcd8e5b8c1b21726ae2503ee3cb4efb579745289d29043173643daec7baf43fR1-R114), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-0c9fdf3b7a60bc4c63c6857d28a2d4f6e7941e7716b2eeebfae6ae8a91000fb0R1-R53))
  * Expose `CustomPredictor` and `CustomTrainer` classes in `__init__.py` ([link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-7cae9db484e13d35ebc45ed49ab9f0663246afe2a7e0094d8fcece6b7c6d68a2L1-R6))
  * Implement `custom_detector` module with `Buzzer` and `CustomPredictor` classes ([link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-670d660e539bdaecd37de882931da392f210dfae647706cb6f58d5e586ed446bR1-R43))
  * Implement `custom_trainer` module with `CustomTrainer` class ([link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-dfcd8e5b8c1b21726ae2503ee3cb4efb579745289d29043173643daec7baf43fR1-R114))
  * Implement `hyperparameter` module with `Hyperparameters` class ([link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-0c9fdf3b7a60bc4c63c6857d28a2d4f6e7941e7716b2eeebfae6ae8a91000fb0R1-R53))
* Delete unnecessary files from `ultralytics` repository ([link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-1c0d972ee49103af56fd608a77a28e1eb12f6908f263f0f183d46868fdcd8ea2), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-7c49a365610d935ce439e3f241cd3f5d1df89a95d1a674d11ebdb1e518c7335c), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-110f79955861ae4ccaccdf492ddfb32233675a625151b68435d183f4f8e3340e), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-b6087b0ddc2695a819e8199639ea5be88e1352a9a10774c7183eefa682e2dc76), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133dd), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-6318f5fc1ff2829ebbfd7846021a98d807a3b866fcfac669187f49fa22a40702), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-17e3400d876978d12bbad517dcf82312b54fa62723408b1ce011b2755458bdaf), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-7aa0bb52169dde77e9033b3f574e1c8e686f567ea884691c7aace8f6297d216e), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-a18ac139672d9f557f950ebe7df3f057ba19abe40d02ac2c81f72bcf44257b68), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-b5e0854ed0838024d5cc25b4e030922e34648b9ea8c432807e35495fb805b894), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-9b9f76394a441ff40bf8d7a0f3e0ddd7ae97abfa9a9a6abaedccf76dc4d51295), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-551d1fcf87f78cc3bc18a7b332a4dc5d8773a512062df881c5aba28a6f5c48d7), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-a618bbaa9618d3ffa70846c5371ca23ea8f71f3370d3aa5be5d2cf39b42b207b), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-63a9c44a44acf85fea213a857769990937107cf072831e1a26808cfde9d096b9), [link](https://github.com/ultralytics/ultralytics/pull/2541/files?diff=unified&w=0#diff-eca12c0a30e25b4b46522ebf89465a03ba72a03f540796c979137931d8f92055))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

### 🌟 Summary
Train, validate, and predict with YOLOv8 models using the Ultralytics AI assistant.

### 📊 Key Changes
- Added support for image classification.
- Implemented new CLI options for various tasks and modes.
- Created additional documentation and examples.

### 🎯 Purpose & Impact
- **Simplify AI Model Interactions**: Users can easily interact with YOLOv8 models for object detection, image classification, and other computer vision tasks.
- **Enhanced Accessibility**: New CLI commands make it more accessible for users to train, validate, and predict with YOLOv8 models without deep technical knowledge.
- **Educational Resources**: Additional documentation and examples serve as learning materials and reference guides for users of all skill levels.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
Closing as not planned.

**Comment by glenn-jocher** [comment]
@chiragagarwals you've removed the license file in this PR. 

This is prohibited. All derivative works of YOLOv8 are required to follow the AGPL license terms.

**Comment by chiragagarwals** [comment]
Yeah, I will make sure to follow the license term, it was an accidental PR which was supposed to be raised for a personal project.

**Comment by glenn-jocher** [comment]
@chiragagarwals thank you for being understanding and respecting the license terms of YOLOv8. It's important for all derivative works to follow the AGPL license to ensure an open and collaborative community. Let us know if you have any questions or need any help with future contributions.

**Pull request closed without merging**
