### PR TITLE
Remove unused arguments in Ultralytics `heatmaps`

### PR DESCRIPTION
**Pull request by RizwanMunawar**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refined heatmap feature by simplifying configuration parameters.

### 📊 Key Changes
- Removed `heatmap_alpha`, `decay_factor`, `imw`, and `imh` from configurations.
- Updated the default values directly in code rather than as user-configurable parameters.

### 🎯 Purpose & Impact
- 📉 **Simplified Configuration**: Reduces complexity for users by removing unnecessary parameters.
- 🛠️ **Improved Usability**: Ensures default settings are more appropriate for general use, enhancing user experience.
- 📈 **Consistent Performance**: Maintains essential functionality while streamlining code for easier maintenance.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for contributing to the `ultralytics/ultralytics` repository with your PR! 🚀 This is an automated response to help ensure a smooth integration of your feature. An Ultralytics engineer will review your submission soon.

Here's a quick checklist for your pull request:

- ✅ **Purpose & Clarity**: You've explained the purpose of your changes clearly in your PR description. Make sure you link any [related issues](https://github.com/ultralytics/ultralytics/issues) if applicable.
- ✅ **Branch Synchronization**: Ensure your branch is up-to-date with the `main` branch of `ultralytics/ultralytics`. Use the 'Update branch' button or execute `git pull` and `git merge main` if necessary.
- ✅ **Passing CI Checks**: Verify that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are successful. Address any failing checks to ensure a smooth merge.
- ✅ **Documentation**: Update all relevant [documentation](https://docs.ultralytics.com) to reflect your modifications or new features.
- ✅ **Testing**: Include or update tests to cover your code changes, ensuring all tests pass.
- ✅ **Contributor License Agreement (CLA)**: Confirm you have signed the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) for first-time contributions by writing "I have read the CLA Document and I sign the CLA" in a comment on this PR.
- ✅ **Minimal Changes**: Ensure your changes are concise and necessary for the improvement, avoiding any extraneous modifications. 🧘

For further guidance, please see our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have questions, feel free to leave a comment. Thank you for enhancing Ultralytics! 🎉

**Comment by glenn-jocher** [comment]
@RizwanMunawar looks good! Should this one be merged before https://github.com/ultralytics/ultralytics/pull/16671 or after?

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes, this should merge before :)

**Comment by glenn-jocher** [comment]
Ok perfect, PR merged!

**Pull request merged**
