### PR TITLE
plot() and box_label() Modification that Allows Manual Positioning of Class Labels

### PR DESCRIPTION
**Pull request by u-uzun**
Especially when working on PPE detection in industrial settings, the class labels of head-worn equipment such as helmets and masks usually collide with those of the persons/workers detected. This small modification allows the user to pass an additional parameter (tuple) to the plot() function (e.g. annotated_frame = results[0].plot(label_pos=(<class_id>, <position_index>) ) where position index 0: top-right, 1: top-left, 2: bottom-left, 3: bottom-right, and this will display the specified class's label where the index points. 

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary 
Enhanced label placement flexibility in image annotations for detection results.

### 📊 Key Changes
- Introduced a new parameter `label_pos` to the `plot` function to customize label placement.
- Updated the `box_label` method to respect the new label position, allowing labels to be drawn at specific corners of bounding boxes.
- Adjusted bounding box and label drawing logic to incorporate the specified label positions within annotated images.

### 🎯 Purpose & Impact
- **Improved Clarity**: Users can specify label positions, enhancing visual clarity by avoiding overlapping or misplaced labels in complex images.
- **Customization**: Provides flexibility in how annotated images are displayed, which may improve usability in various contexts such as reports or presentations.
- **User Control**: Empowers users to choose where labels appear, making the tool more adaptable to specific needs and preferences.

### CODE REVIEW

**Comment by u-uzun** [comment]
I have read the CLA Document and I sign the CLA

**Comment by u-uzun** [comment]
This is my very first PR on GitHub and I am very unfamiliar with how everything works. I got one error on the checklist and I am not sure if this is a major issue that needs to be fixed on my side:  The check for "Ultralytics Actions / format (pull_request_target)" gives the error "/Users/runner/work/_temp/08a05855-3c0b-408c-afe3-d7b589e788d0.sh: line 3: syntax error near unexpected token `('" I am unable to find a solution or workaround for this.

**Comment by glenn-jocher** [comment]
It looks like there's a syntax error in your script. Please check your code for any misplaced characters or syntax issues, especially around the area mentioned in the error message. If you need further assistance, reviewing the script line by line might help identify the problem.

**Comment by u-uzun** [comment]
> It looks like there's a syntax error in your script. Please check your code for any misplaced characters or syntax issues, especially around the area mentioned in the error message. If you need further assistance, reviewing the script line by line might help identify the problem.

Hello again,
I’ve reviewed my changes carefully, using related tools as well and there don’t appear to be any syntax or parentheses issues in the code itself. The error seems to be related to a shell script executed during the CI/CD process:

/Users/runner/work/_temp/748dca8b-ddd9-4e23-8edf-fff8dba1a542.sh: line 3: syntax error near unexpected token `('
This suggests a syntax error within a shell script, possibly in the GitHub Actions workflow or configuration. Could someone please assist in reviewing the CI/CD pipeline setup? Every other check seems to be sound. 

Thank you

**Comment by glenn-jocher** [comment]
Thank you for your diligence. The issue might be related to the GitHub Actions configuration. Please ensure the workflow files are correctly formatted. If the problem persists, consider checking the syntax in the CI/CD setup or consult the GitHub Actions documentation for guidance.

**Comment by Burhan-Q** [comment]
@u-uzun see [my reply](https://community.ultralytics.com/t/ultralytics-actions-format-pull-request-target-failing/395/3?u=burhanq) to your post on the forums

**Pull request closed without merging**
