### PR TITLE
fix yolo-thread-safe-inference.md

### PR DESCRIPTION
**Pull request by qwerdf4**
The previous code will cause errors, 
RuntimeError: can't register atexit after shutdown. The modified code can run normally

### Summary
🧵🔒📈

This pull request enhances the guide on `yolo-thread-safe-inference.md` by updating the code examples to use the `join` method and a simpler `predict` function. These changes improve the thread safety and performance of the YOLO inference.

> _In the dark of the night, we unleash the infernal power_
> _`yolo-thread-safe-inference` guides us to the final hour_
> _We synchronize the threads with the `join` method_
> _We simplify the `predict` function, no more regret_

### Walkthrough
* Improve thread safety and consistency of YOLO inference code in `docs/en/guides/yolo-thread-safe-inference.md` ([link](https://github.com/ultralytics/ultralytics/pull/7010/files?diff=unified&w=0#diff-9bda114dbd93b34b09a8d46e67ad20578b7c870a17f1bd8d8a0fe9733279824bL44-R49), [link](https://github.com/ultralytics/ultralytics/pull/7010/files?diff=unified&w=0#diff-9bda114dbd93b34b09a8d46e67ad20578b7c870a17f1bd8d8a0fe9733279824bL70-R79), [link](https://github.com/ultralytics/ultralytics/pull/7010/files?diff=unified&w=0#diff-9bda114dbd93b34b09a8d46e67ad20578b7c870a17f1bd8d8a0fe9733279824bL98-R111))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved thread handling in YOLO inference documentation and updated GitHub authors.

### 📊 Key Changes
- Added `.join()` to threading examples for better synchronization in inference scripts.
- Updated `mkdocs_github_authors.yaml` to include a new contributor.

### 🎯 Purpose & Impact
- 🧵 Enhances thread management in examples, ensuring inference results are more predictable and stable.
- 🤝 Acknowledges new contributions, fostering community and collaboration.

### CODE REVIEW

**Comment by qwerdf4** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Burhan-Q** [comment]
@qwerdf4 the code changes look reasonable to me. I think it might be helpful to provide an explanation to the file about what difference is between what you have added and the original. I'm not well studied with using `Threading` myself, and had to test it to see what changes.

**Comment by Burhan-Q** [comment]
@RizwanMunawar what are your thoughts on the changes here? Seems like there could be other additions that could be added to this page as well, since someone attempting to use this _exact_ example would have no output or saved results (at least that's what occurred in my testing).

<details><summary>Possible additional changes</summary>


```py
# Safe: Instantiating a single model inside each thread
from threading import Thread
from ultralytics import YOLO

def thread_safe_predict(image_path, model="yolov8n.pt",  *args, **kwargs):
    # Instantiate a new model inside the thread
    local_model = YOLO(model) # uses model argument instead of static text
    local_model.predict(image_path, *args, **kwargs)

images = ["assets/bus.jpg", "assets/zidane.jpg"]
threads = dict()
for ni, img in enumerate(images, 1):
    k = f't{ni}'
    threads[k] = Thread(target=thread_safe_predict, args=(img,), kwargs={'save':True}) # adds save argument
    threads[k].start()

_ = [v.join() for v in threads.values()]
```

</details>

**Comment by Burhan-Q** [comment]
@qwerdf4 please make sure to merge the latest changes from `ultralytics:main` into your fork

**Comment by RizwanMunawar** [comment]
@Burhan-Q Yes right! The modification seems acceptable. @qwerdf4, could you kindly provide comprehensive comments and an explanation for the alterations? This will facilitate understanding for everyone.

**Comment by RizwanMunawar** [comment]
> @RizwanMunawar what are your thoughts on the changes here? Seems like there could be other additions that could be added to this page as well, since someone attempting to use this _exact_ example would have no output or saved results (at least that's what occurred in my testing).
> 
> Possible additional changes
> ```python
> # Safe: Instantiating a single model inside each thread
> from threading import Thread
> from ultralytics import YOLO
> 
> def thread_safe_predict(image_path, model="yolov8n.pt",  *args, **kwargs):
>     # Instantiate a new model inside the thread
>     local_model = YOLO(model) # uses model argument instead of static text
>     local_model.predict(image_path, *args, **kwargs)
> 
> images = ["assets/bus.jpg", "assets/zidane.jpg"]
> threads = dict()
> for ni, img in enumerate(images, 1):
>     k = f't{ni}'
>     threads[k] = Thread(target=thread_safe_predict, args=(img,), kwargs={'save':True}) # adds save argument
>     threads[k].start()
> 
> _ = [v.join() for v in threads.values()]
> ```

@Burhan-Q Yes, the code will function correctly if the line for `thread.join` is placed within the for loop.

```python
# Safe: Instantiating a single model inside each thread
from threading import Thread
from ultralytics import YOLO

def thread_safe_predict(image_path, model="yolov8n.pt",  *args, **kwargs):
    # Instantiate a new model inside the thread
    local_model = YOLO(model) # uses model argument instead of static text
    local_model.predict(image_path, *args, **kwargs)

images = ["ultralytics1.png", "ultralytics2.png"]
threads = dict()
for ni, img in enumerate(images, 1):
    k = f't{ni}'
    threads[k] = Thread(target=thread_safe_predict, args=(img,), kwargs={'save':True}) # adds save argument
    threads[k].start()
    threads[k].join()
```

**Review by ambitious-octopus — COMMENTED** [review]
I'm closing this PR because it's invalid. Thanks for the PR @qwerdf4 but the error you found is related to the fact that you are using the wrong example. The example explains that it is not safe to use the same model on multiple threads.

**Pull request closed without merging**
