### PR TITLE
Fix counter overflow for video frame crop names, set default separator for same-frame detection counter

### LINKED ISSUE #3942: What is the naming scheme for crops when tracking?
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I've trained a detector and run it on a video, like so:

    yolo track model=$MODEL source=ex_2020_20200603_10.mp4 name=tracked_ex_2020_20200603_10.mp4 save save_crop save_txt

Note that the file name ends (except the mp4 suffix) in a number, which probably messes up things.  Labels are output with an object ID attached, and file names like `ex_2020_20200603_10_NNN`, where NNN is the frame number (variable digits).  Crops are output as `ex_2020_20200603_10MMM`, i.e. missing the underscore (which I think is a bug), and apart from the first MMM being empty and the next being 2, seems to just be a running count.  

My question is: how can I link the crops to the annotations in the labels?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by ketil-malde**
As requested by GJ in Issue #3942. -k

### Summary
🎞️🔢📝

This pull request improves the naming of cropped images and incremented paths in `ultralytics`. It adds frame numbers to the cropped image names when using video or webcam inputs, and changes the separator for incremented paths to a dash.

> _`frame` in file name_
> _helps to track cropped images_
> _useful for video_

### Walkthrough
*  Add frame number to cropped image file name for video and webcam modes ([link](https://github.com/ultralytics/ultralytics/pull/3982/files?diff=unified&w=0#diff-9fa2bf7f1273283680da3daeb8bae8e20cf8d477f838575796d2bf3b415bc534L181-R182)) in `predictor.py`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced result-saving capabilities in Ultralytics prediction engine.

### 📊 Key Changes
- Added `self.txt_path` attribute to hold the path for text results.
- Updated `write_results` method to support distinct filenames when saving crop images in non-image dataset modes.

### 🎯 Purpose & Impact
- The addition of `self.txt_path` enables more flexible handling of output text files, improving organization and access.
- The updated `write_results` method allows for unique naming of saved crop files based on dataset mode, preventing filename collisions and making it easier for users to locate and distinguish results from video or sequence data. This enhances the user experience when working with different types of datasets. 🔄

### CODE REVIEW

**Comment by ketil-malde** [comment]
I have read the CLA Document and I sign the CLA

I mean, this change is trivial enough not to be covered by copyrights and such, but sure.

**Comment by ketil-malde** [comment]
Um, do I need to comment to prod a rerun of the checks?  Okay, here goes...

**Comment by glenn-jocher** [comment]
recheck

**Comment by glenn-jocher** [comment]
@ketil-malde PR merged! Thank you for your contributions. I stripped the separator changed as this is not planned, but I left in the major crop change.

**Pull request merged**
