### PR TITLE
YOLOv8 INT8 TFLite Inference Example

### PR DESCRIPTION
**Pull request by wamiqraza**
Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:

1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.

2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.

3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.

4. **Ultralytics Contributor License Agreement (CLA)**: To uphold the quality and integrity of our project, we require all contributors to sign the CLA. Please confirm your agreement by commenting below:

   _I have read the CLA Document and I hereby sign the CLA_

For more detailed guidance and best practices on contributing, refer to our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing). Your adherence to these guidelines ensures a faster and more effective review process.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
New example showcasing YOLOv8 Int8 TFLite model with OpenCV for optimized object detection added to Ultralytics' examples.

### 📊 Key Changes
- Added a new script and README for YOLOv8 OpenCV INT8 TFLite Python example.
- The script includes steps for converting a YOLOv8 model to TFLite format, loading with OpenCV, and running inference.
- The README provides installation instructions and usage guides, including dependency installation and running the example code.

### 🎯 Purpose & Impact
- 🎛 **User-Friendly**: Offers a simple guide for users to leverage YOLOv8 with TFLite and OpenCV.
- 💨 **Efficiency**: Facilitates efficient inference on edge devices using quantized INT8 models.
- 🚀 **Accessibility**: Provides easier access for Python users to deploy YOLOv8 with potentially lower resources.
- 🔍 **Enhanced Detection**: Allows users to benefit from YOLOv8's detection capabilities with reduced precision models without significant compromise on accuracy.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@wamiqraza thanks for the PR!

We already provide built-in python inference for most export formats including TFLite, i.e.
```
yolo predict model=yolov8n.tflite source='path/to/image.jpg'
```

Does this PR provide additional functionality?

**Comment by wamiqraza** [comment]
@glenn-jocher thank you for your review. This PR indeed offers additional functionality beyond the existing Python inference for TFLite ,It's inspired by the [ONNX](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-OpenCV-ONNX-Python) and [this](https://github.com/ultralytics/ultralytics/tree/main/examples/YOLOv8-Segmentation-ONNXRuntime-Python). The existing built-in python inference CLI command often falls short in microcontroller contexts, specifically targeting the deployment of YOLOv8 with int8 tflite models on microcontrollers. This contribution addresses many community issues related to tflite and offers a numpy-based (instead of torch) solution for tflite deployments. It provides users with enhanced control for optimizing performance and outputs, which is crucial for microcontroller applications.

**Comment by glenn-jocher** [comment]
@wamiqraza ah got it! Ok then please refactor the image into the README as a URL link to this image and delete the image from this PR (only code should be placed in PRs, images should be hosted elsewhere and linked to), and then capitalize the class names correctly for "YOLOv8" (all upper-case). Thank you!

**Comment by wamiqraza** [comment]
@glenn-jocher, followed instruction as you advised and made a changes accordingly. Hope its now algined as per ultralytics guidelines.

**Comment by wamiqraza** [comment]
@glenn-jocher, welcome, and glad to be a part of enhancing the usability of YOLOv8. I will close my open issues related to tflite will refer audiance to PR and script implementation. Last thing about social channel what's advised to wait for your team to post then I do or !

**Comment by glenn-jocher** [comment]
@wamiqraza Thanks for your proactive approach in managing the related issues. For social channels, feel free to share your work once the PR is merged. We appreciate your contributions and enthusiasm! 🌟

**Comment by glenn-jocher** [comment]
@like-yo it seems there's a conflict with an already defined "StatusCode" object in your environment. This could be due to a version mismatch or duplicate installation of certain packages. Please ensure that all dependencies are correctly installed and up-to-date. If the issue persists, consider creating a new virtual environment and reinstalling the required packages. If you need further assistance, feel free to open an issue on the repo with full error logs and system details.

**Pull request merged**
