### PR TITLE
Fixed Open Image V7 caption typos

### PR DESCRIPTION
**Pull request by imyhxy**
I have read the CLA Document and I sign the CLA

### Summary
📊🔄🌐

Updated the speed metric in `README.md` and `README.zh-CN.md` to use Open Image V7 as the benchmark dataset. This improves the consistency and accuracy of the performance comparison.

> _Metrics harmonized_
> _`README` files updated_
> _Winter of data_

### Walkthrough
* Update the speed metric to use Open Image V7 dataset for consistency and accuracy in both English and Chinese README files ([link](https://github.com/ultralytics/ultralytics/pull/6645/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L142-R142), [link](https://github.com/ultralytics/ultralytics/pull/6645/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L142-R142))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvement in speed measurement accuracy for model benchmarks.

### 📊 Key Changes
- Updated the dataset reference for speed benchmarking from COCO to Open Image V7 in the English README.
- No changes made to the Chinese README (`README.zh-CN.md`) in this PR.

### 🎯 Purpose & Impact
- 🥅 **Purpose**: To provide users with benchmark speed information that is aligned with the data used in the model validation process.
- 🚀 **Impact**: Users will have a more accurate understanding of model performance, as speed is now reported on the same dataset as the performance metric (mAP), ensuring consistency and reliability in benchmarks.

### CODE REVIEW

**Comment by imyhxy** [comment]
I have read the CLA Document and I sign the CLA

**Comment by imyhxy** [comment]
recheck

**Comment by imyhxy** [comment]
recheck

**Comment by glenn-jocher** [comment]
@imyhxy ah! Thank you!

**Comment by glenn-jocher** [comment]
@imyhxy PR merged!

**Pull request merged**
