### PR TITLE
`ultralytics 8.2.8` fix `os.sched_setaffinity()` AttributeError

### PR DESCRIPTION
**Pull request by AMoldskred**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Ultralytics software updates to version 8.2.8 with minor enhancements. 🎉

### 📊 Key Changes
- **Version Update:** Updated the software version from 8.2.7 to 8.2.8.
- **Compatibility Improvement:** Added a check for Linux OS before setting thread affinity, improving compatibility across different operating systems (MacOS and Windows users, rejoice! 🐧💻🪟).

### 🎯 Purpose & Impact
- **Seamless Version Transition:** The version bump signifies improvements and potentially new features or bug fixes, offering users a smoother and more efficient experience.
- **Enhanced Compatibility:** The added OS check before setting thread affinity ensures the software can run without issues across different platforms, making Ultralytics more accessible and user-friendly for a broader audience. This change mainly impacts developers and users by reducing operating system-related errors, especially for those not using Linux. 🔄👥

Expect a more unified experience across various systems, and always ensure your environment is up to date with the latest version for optimal performance! 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AMoldskred oh wow, this is a serious bug. We should have Windows CI in place to catch this, this is our fault. I'll submit a separate PR for that.

**Comment by glenn-jocher** [comment]
@AMoldskred Windows CI is passing in PR https://github.com/ultralytics/ultralytics/pull/11233

Are you sure there is a windows issue?

**Comment by AMoldskred** [comment]
> @AMoldskred Windows CI is passing in PR #11233
> 
> Are you sure there is a windows issue?

Fairly certain, but I'm not able to reproduce since I don't have any windows devices. 

See for example this Stackoverflow thread:
[https://stackoverflow.com/questions/42538153/python-3-6-0-os-module-does-not-have-sched-getaffinity-method](https://stackoverflow.com/questions/42538153/python-3-6-0-os-module-does-not-have-sched-getaffinity-method)

**Comment by AMoldskred** [comment]
@glenn-jocher Also in the docs for os python package it says it is only available on some Unix platforms.
[https://docs.python.org/3/library/os.html#interface-to-the-scheduler](https://docs.python.org/3/library/os.html#interface-to-the-scheduler)

This is totally my fault. I should have read the docs a bit more carefully here😅

**Comment by glenn-jocher** [comment]
@AMoldskred oh this is wierd, getting the same error in macos too:

AttributeError: module 'os' has no attribute 'sched_setaffinity'

**Comment by glenn-jocher** [comment]
I wonder if the tests aren't reaching this function then.

**Comment by Burhan-Q** [comment]
Also confirmed on Windows `Ultralytics YOLOv8.2.7 🚀 Python-3.10.9 torch-2.1.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3080, 12288MiB)`

```py
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
result = model.train(data="coco8.yaml", epochs=16)
```

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Q:\ML_dev\ultra_repo\ultralytics-1\ultralytics\engine\model.py", line 673, in train
    self.trainer.train()
  File "Q:\ML_dev\ultra_repo\ultralytics-1\ultralytics\engine\trainer.py", line 199, in train
    self._do_train(world_size)
  File "Q:\ML_dev\ultra_repo\ultralytics-1\ultralytics\engine\trainer.py", line 353, in _do_train
    for i, batch in pbar:
  File "Q:\ML_dev\ultra_repo\ultralytics\.ultra_docs\lib\site-packages\tqdm\std.py", line 1182, in __iter__
    for obj in iterable:
  File "Q:\ML_dev\ultra_repo\ultralytics-1\ultralytics\data\build.py", line 50, in __iter__
    yield next(self.iterator)
  File "Q:\ML_dev\ultra_repo\ultralytics\.ultra_docs\lib\site-packages\torch\utils\data\dataloader.py", line 630, in __next__
    data = self._next_data()
  File "Q:\ML_dev\ultra_repo\ultralytics\.ultra_docs\lib\site-packages\torch\utils\data\dataloader.py", line 1345, in _next_data
    return self._process_data(data)
  File "Q:\ML_dev\ultra_repo\ultralytics\.ultra_docs\lib\site-packages\torch\utils\data\dataloader.py", line 1371, in _process_data
    data.reraise()
  File "Q:\ML_dev\ultra_repo\ultralytics\.ultra_docs\lib\site-packages\torch\_utils.py", line 694, in reraise
    raise exception
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "Q:\ML_dev\ultra_repo\ultralytics\.ultra_docs\lib\site-packages\torch\utils\data\_utils\worker.py", line 250, in _worker_loop
    init_fn(worker_id)
  File "Q:\ML_dev\ultra_repo\ultralytics-1\ultralytics\data\build.py", line 84, in seed_worker
    os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195
AttributeError: module 'os' has no attribute 'sched_setaffinity'
```

**Comment by glenn-jocher** [comment]
@Burhan-Q do you know what's going on in the Windows CI PR #11233 then? It seems like we don't have coverage of this function in our tests because the Windows CI tests I added are passing without issue (same for macos tests).

Strange. Anyways, merging this now to get this fix published!

**Comment by glenn-jocher** [comment]
@AMoldskred PR merged! Thanks for spotting this bug and submitting a fix. Will be live in a few minutes as `ultralytics 8.2.8`. I'll yank 8.2.7 from pypi to make sure no one downloads it by accident.

**Pull request merged**
