### PR TITLE
Use `shell=True` to run hyperparameter tuning

### LINKED ISSUE #18240: WARNING ❌️ training failure for hyperparameter tuning iteration 1 [Errno 2] No such file or directory: 'yolo'
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Greetings.

I am trying to hypertune my model using the following lines of code:

```
from ultralytics import YOLO

# Initialize the YOLO model
model = YOLO("ship.yaml").load('yolov8n.pt')
# Tune hyperparameters on COCO8 for 30 epochs
result_grid = model.tune(data="/lab_202/john/project/datasets/HRSID/data.yaml", epochs=30, iterations=300, optimizer="AdamW")
```

but getting the error. I have followed the installation guidelines. I am not sure where am I doing wrong.

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Y-T-G**
Closes https://github.com/ultralytics/ultralytics/issues/18240
https://github.com/ultralytics/ultralytics/issues/6053

The `yolo` command is sometimes not found. This is probably fixed by invoking it in `shell`.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Improved command execution for YOLO model training in the hyperparameter tuning process.

### 📊 Key Changes  
- Updated the subprocess call in the tuner to use `shell=True` by converting the command list into a single string (`" ".join(cmd)`).

### 🎯 Purpose & Impact  
- **Purpose**: Fix potential issues with training subprocess execution by enabling shell-based command execution.  
- **Impact**: Enhances compatibility and reliability during hyperparameter tuning, reducing training failures caused by subprocess management. 🚀  
- **Benefit to Users**: Ensures smoother and more robust YOLO training workflows when performing automatic hyperparameter optimization.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and refer to any relevant issues. Ensure your commit messages are clear, concise, and follow the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify that all Continuous Integration (CI) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed the Contributor License Agreement (CLA) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For further guidance, refer to the project's contributing documentation. Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@Y-T-G this is very strange, normally shell=True is not best practices, but I do see the bug reports from users. Let's see what https://github.com/furycurry says about the fix in this PR. If it works correctly here then we should merge this.

**Comment by Y-T-G** [comment]
@glenn-jocher This was also reported by another user [on Discord about a month ago](https://discord.com/channels/1089800235347353640/1098248998629933146/1308181662789800059).

It's indeed strange. Because the `yolo` command works for them, for example `yolo checks` runs for the user. But fails when trying to launch tuning for some reason.

**Comment by glenn-jocher** [comment]
@Y-T-G ok let's try it. I'll merge for 8.3.51. If we see any issues we can then revert.

**Pull request merged**
