### PR TITLE
Merge branch 'main' of https://github.com/ultralytics/ultralytics

### PR DESCRIPTION
**Pull request by jjlira**
### Summary
🛠️🗂️⚙️

Improved dataset configuration and warning message in `ultralytics/yolo/data/utils.py`. The changes allow users to specify dataset paths in a `settings.yaml` file in their user config directory.

> _`USER_CONFIG_DIR`_
> _A variable for paths_
> _Helps set up datasets_

### Walkthrough
* Import `USER_CONFIG_DIR` variable from `ultralytics.yolo.utils` module to access the settings.yaml file ([link](https://github.com/ultralytics/ultralytics/pull/1918/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58L20-R21))
* Modify warning message in `check_det_dataset` function to include dataset name and settings.yaml path ([link](https://github.com/ultralytics/ultralytics/pull/1918/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58L245-R247))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR appears to be a placeholder or error, as there are no code changes to summarize.

### 📊 Key Changes
- N/A (no actual changes present in the PR)

### 🎯 Purpose & Impact
- Since no changes are included, there isn't any direct impact or benefit to users from this PR.
- This could either be a mistake or an initial PR that will be updated with details later. Users and developers should await further updates for any meaningful changes.

### CODE REVIEW

**Comment by jjlira** [comment]
Github ultralytics/ultralytics ultralytics #1881
    Can't change the default dir where YOLOV8 downloads example datasets
    - "USER_CONFIG_DIR" is imported from ultralytics.yolo.utils
    - A message to the user is added:
    "Please, check: {USER_CONFIG_DIR}/settings.yaml"
    to allow quick troubleshoot of the issue
    
    I have read the CLA Document and I sign the CLA

**Comment by joseliraGB** [comment]
I have read the CLA Document and I sign the CLA

**Comment by jjlira** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@jjlira ok I've cleaned this up a bit and added a more informative error message in 8.0.73 which should help users understand their dataset directory and setting yaml to change it.

**Pull request merged**
