### PR TITLE
Run `--slow` tests for Raspberry Pi

### PR DESCRIPTION
**Pull request by glenn-jocher**
@lakshanthad please debug failing slow test(s) in this PR, I think we are almost there!

Slow tests fail on Explorer Tests in i.e. https://github.com/ultralytics/ultralytics/actions/runs/8715976528/job/23908727539?pr=10097

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enabling slow tests in CI and refining explorer tests for clarity and specificity. 🚀

### 📊 Key Changes
- **CI Configuration Adjusted**: Slow tests, previously commented out, are now included in the continuous integration (CI) process.
- **Explorer Test Enhancements**: Modified explorer tests to use a specific dataset (`coco8.yaml`) and targeted image queries, resulting in more predictable and concise test outcomes.

### 🎯 Purpose & Impact
- **Improving Test Coverage**: Running slow tests ensures more comprehensive validation, catching potential issues early. 🛠️
- **Increased Test Precision**: By using a specific dataset and adjusting the assertions, tests become more reliable, potentially reducing false positives/negatives. This leads to higher confidence in code changes. 🎯
- **Potential User Impact**: Users may experience more stable updates and features, as changes undergo thorough testing. This contributes to a smoother, more reliable user experience. 🌈

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@lakshanthad error is in test_similarity() test:

Screenshot 2024-04-17 at 20 34 10

https://github.com/ultralytics/ultralytics/blob/dae4ce8307fc38990b959cd5e783a7e3cd82eb3d/tests/test_explorer.py#L10-L25

**Comment by lakshanthad** [comment]
This error is gone when COCO128 dataset is downloaded manually into the Pi. in test_similarity(), it is trying to access images on the COCO128 dataset for some reason.
image_720

**Comment by glenn-jocher** [comment]
@lakshanthad tests fixed by updating to COCO8

**Comment by lakshanthad** [comment]
Sounds great! @glenn-jocher  Thanks for the support :)

**Pull request merged**
