### PR TITLE
Do RTDETR file suffix check using pathlib instead of string manipulations

### PR DESCRIPTION
**Pull request by birdcolour**
As written currently, the `RTDETR` model specifically can't accept a `Path` object because it checks the file extension using string methods. This PR brings it into line with the other models, which happily do so.

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced RT-DETR model initialization with improved file extension handling.

### 📊 Key Changes
- Imported `Path` from the `pathlib` module for file path manipulations.
- Refined model file extension check using `Path.suffix`.

### 🎯 Purpose & Impact
- 🧰 **Purpose:** To ensure that RT-DETR model initialization reliably checks supported file extensions, preventing user errors and improving the robustness of the implementation.
- 🔍 **Impact:** Users will experience more consistent validation of file types when initializing RT-DETR models, with potentially fewer errors and clearer restrictions on acceptable file formats (`.pt`, `.yaml`, `.yml`).

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced file extension validation for RT-DETR model initialization in Ultralytics' repository.

### 📊 Key Changes
- Imported `Path` from the `pathlib` library.
- Updated file extension check using `Path.suffix` for better file extension handling.

### 🎯 Purpose & Impact
- The purpose of the update is to improve the reliability of file extension checking during model initialization.
- This change benefits users by providing a more robust and error-resistant method of verifying whether a valid model file has been provided.
- Impact on end-users includes reduced potential for issues related to file extension misinterpretation, particularly in different operating system environments where case sensitivity can vary. 🔄

### CODE REVIEW

**Comment by birdcolour** [comment]
recheck

**Comment by birdcolour** [comment]
recheck

**Comment by glenn-jocher** [comment]
@birdcolour thank you for signing the CLA! Your contribution is much appreciated. If there's anything specific you need help with or further actions required, please let us know. Happy coding! 😊

**Comment by Burhan-Q** [comment]
@birdcolour simple but makes sense! Slowly be surly we'll update to using `pathlib.Path` methods as much as possible 🙌

**Review by Burhan-Q — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@birdcolour @Burhan-Q yes this is a good fix, we should employ pathlib.Path wherever possible, merging now!

**Pull request merged**
