### PR TITLE
Discord badge

### PR DESCRIPTION
**Pull request by Burhan-Q**
Adds dynamic Ultralytics Discord Server badge to repo `Readme.md`, `Readme.zh-CN.md`, and Docs `index.md` pages. Badge URL points to `ultralytics.com/discord` invite link. Since it's only a single line, badge added to all language docs pages.

### Dynamic HTML icon
<a href="https://ultralytics.com/discord">Discord</a>

### From Readme
image

### Summary
🌐📚💬

This pull request adds a Discord badge to the `README.md` file and its translations, as well as to the documentation index pages for different languages. The badge links to the Ultralytics Discord server and shows the number of online members. The purpose of this change is to increase the visibility and engagement of the Discord community for Ultralytics users.

> _`Badge` for Discord_
> _Across languages and docs_
> _Winter invites warmth_

### Walkthrough
*  Add a badge to link to the Ultralytics Discord server in the README files of different languages ([link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R19), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987R19), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-b41ae48c6d834c5ca3f18e7ff323eb7669bfbecbab5c3c0835c043167ee8f2abR35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-35819ada0b9f3d829de58502d6196481c557e290421c48808317967fbb0ef3daR35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-291b58e742821d1c04b74ee2b897ce7063ad1998c539881f68bafa9b499bc94eR35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-5cd0a48e2089ee09f41d08c029b4a94e7bda1030505f019de983ed57493e6810R35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-9075d97b39a3057dc6763329e64229ab2a6acb0f3efb40fcdd858bb4c894f662R35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-586ada7d4d3305922f65d06dde87ed55ee12ea757eb3d4a412e0b3bb56988687R35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-11c4d38a2b7be349072b8b398b8caabb2c150d5d9b92895789a5b63d89c531c3R35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-6d91249d5d2ef2c73181ca585846e0b953135218c7bb098888dd3d141718fc56R35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-1fa5f54a5c8f04710af9a3887a5957022fb69ef4b735ac83911d255567b0c566R35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-8ec22f5463933c0b6155b1f4d7decd8ecca3bc5fb12e27900148cba539a1f606R35), [link](https://github.com/ultralytics/ultralytics/pull/6799/files?diff=unified&w=0#diff-3e62baacd844a4d5b90475ba695ed47ad7b456c765057575874d81c8cb693d3cR37))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of a Discord community badge across Ultralytics documentation.

### 📊 Key Changes
- Added Discord badge to README.md files in multiple languages.
- Updated documentation indexes for Arabic (ar), German (de), English (en), Spanish (es), French (fr), Hindi (hi), Japanese (ja), Korean (ko), Portuguese (pt), Russian (ru), and Chinese (zh) to include the new Discord badge.

### 🎯 Purpose & Impact
- **Purpose:** To provide a direct link to the Ultralytics Discord community from project documentation, making it easier for users and contributors to join the conversation and get support.
- **Impact:** Enhances community engagement by promoting the Discord channel across various documentation pages, potentially increasing the number of active community members and fostering a collaborative environment.🤝🚀

### CODE REVIEW

**Comment by RizwanMunawar** [comment]
Nice work @Burhan-Q

**Comment by Burhan-Q** [comment]
@glenn-jocher I can rearrange to put it in the first row, and I think that Discord looks good if you do.

**Comment by glenn-jocher** [comment]
Ok this is probably the best all things considered. Smaller, aligns with the current badges, good discord logo contrast. What do you think?
Discord

**Comment by Burhan-Q** [comment]
@glenn-jocher honestly I think both will be good, but honestly I am a fan of purple, that said the white logo seems to pop a lot more so I'll use that one. I'll leave the text to just be "Discord" to keep this badge width down.

### Dark mode preview

image

image

### Light mode preview

image

image

**Pull request merged**
