### PR TITLE
Fix `h5py` wheel builds on arm64 Dockerfiles

### LINKED ISSUE #9945: Cannot install dependencies via Docker
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Install

### Bug

I'm trying to install ultralytics via Docker. 

My actions:
1. Download repository git@github.com:ultralytics/ultralytics.git
2. Go to the docker folder
3. docker build -t yolov8 .

And then it crashes at line 33:
RUN pip install --no-cache -e ".[export]"

image

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
@lakshanthad 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Upgrades and fixes in Dockerfiles and dependencies to enhance support for ARM64 and Jetson devices.

### 📊 Key Changes
- **Dockerfile-arm64 & Dockerfile-jetson:** Comments updated for clarity on dependencies needed for 'tflite_support', 'onnxsim', and TensorRT models. Added `pkg-config` and `libhdf5-dev` as requirements for building 'h5py==3.11.0' on ARM64.
- **pyproject.toml:** Adjusted dependencies to address building issues and deprecated functions. Specifically, excluded `h5py==3.11.0` for ARM64 to circumvent current build problems.

### 🎯 Purpose & Impact
- **Improved Clarity:** Comments in Dockerfiles are now more descriptive, helping developers understand dependency needs.
- **Enhanced Compatibility:** Dependency adjustments in `pyproject.toml` aim to fix building issues and deprecated functions, particularly for users on ARM64 and NVIDIA Jetson platforms.
- **Broader Support:** Including `pkg-config` and `libhdf5-dev` in the setup ensures broader compatibility and smoother setup processes for users working with TensorFlow on ARM64 architectures.

These changes should make it easier for users with ARM64 and Jetson devices to deploy and utilize Ultralytics' offerings, expanding the user base and improving the experience for existing users. 🚀

### CODE REVIEW

**Comment by lakshanthad** [comment]
@glenn-jocher I can check this locally and verify today. Where did you see this failing?

**Comment by glenn-jocher** [comment]
@lakshanthad I tracked down the issue to a new `h5py` version that lacks `aarch64` wheels, so the tensorflow installs on arm64 images are trying to build them. I found it simpler to just pin the install to !=3.11.0. Not sure why there are no aarch64 wheels in the h5py==3.11 release, maybe a mistake on their part.

**Comment by glenn-jocher** [comment]
Issue opened in https://github.com/h5py/h5py/issues/2408

**Comment by lakshanthad** [comment]
Sounds good! @glenn-jocher We can hopefully wait for h5py guys and revert back to original once fixed!

**Pull request merged**
