### PR TITLE
Fix crash due to overflow

### PR DESCRIPTION
**Pull request by Y-T-G**
The returned count will be negative when there are no targets. Add check to ensure non-negative counts.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Fixes an issue in the loss computation by ensuring tensor initialization accounts for edge cases where count is zero.

### 📊 Key Changes
- Modified tensor initialization to utilize `max(counts.max().item(), 0)` instead of `counts.max()`.
  
### 🎯 Purpose & Impact
- 🐛 **Bug Fix**: Prevents errors when the count of unique target indices is zero.
- ✅ **Improved Stability**: Ensures the loss computation runs smoothly without unexpected crashes.
- 🌐 **Broader Compatibility**: Better handling of edge cases improves the robustness of the model training process.

### CODE REVIEW

**Comment by Y-T-G** [comment]
The problem might actually be PyTorch related because `return_counts` is never supposed to return a negative value. But it does so in random occasions while using `mps` or `cuda` for PyTorch 2.3.1.

**Comment by Y-T-G** [comment]
https://github.com/ultralytics/ultralytics/issues/12999

**Comment by glenn-jocher** [comment]
@Y-T-G maybe the really large count exceeds the precision, i.e. int8 maxes out at +128 and int16 at around 16k.

**Comment by Y-T-G** [comment]
@glenn-jocher Yeah, that seems to be the issue. Seems like a problem with the PyTorch ops implementation. I haven't seen any issue about it on their repo though.

**Comment by glenn-jocher** [comment]
@Y-T-G I don't have time to debug, but can you see what the datatype is before being cast to int32 here?
counts.to(dtype=torch.int32).

The Int32 value type represents signed integers with values ranging from negative 2,147,483,648 through positive 2,147,483,647, so we can fit a very large number within here, i.e. up to almost 2.2B.

**Comment by Y-T-G** [comment]
@glenn-jocher I actually don't have an MPS device for testing. I found this issue being faced by someone else on Discord too on their MPS device. But the datatype most probably is int64.

I used this to check `9223372036854775807` value that was posted in that issue, and it comes out as -1 for all the signed datatypes except int64.

https://www.simonv.fr/TypesConvert/?integers

**Comment by glenn-jocher** [comment]
@Y-T-G wait but something can't be right there, as if we have i.e. `counts.max()=9223372036854775807` it will attempt to create a Tensor far too large to fit into any computer's memory no?

```
            counts = counts.to(dtype=torch.int32)
            out = torch.zeros(batch_size, counts.max(), ne - 1, device=self.device)
```

**Comment by Y-T-G** [comment]
@glenn-jocher 

Yeah. It's a good thing it crashes before it. It's not supposed to be that large.

The [OP](https://github.com/ultralytics/ultralytics/issues/12999) posted a reproduceable example where just a tensor with single value is returning counts that large when it's supposed to return 1.
```python
wzl_cpu = torch.tensor([0.0]).to('cpu')
wzl_mps = torch.tensor([0.0]).to('mps')
print(wzl_cpu.unique(return_counts=True))
# Output: (tensor([0.]), tensor([1]))

print(wzl_mps.unique(return_counts=True))
# Output: (tensor([0.], device='mps:0'), tensor([9223372036854775807], device='mps:0'))
```

**Comment by glenn-jocher** [comment]
@Y-T-G looks all good to me:

Screenshot 2024-07-28 at 16 47 28

**Comment by glenn-jocher** [comment]
@Y-T-G if this is reproducible for you though then this is definitely a `torch` bug and outside the scope of what we can do here. Please raise an issue directly on the torch repository and link to the bug reports here.

**Comment by LiYan1988** [comment]
I think it still makes sense to modify the code so that it works on mps devices. It could be a one line change of `_, counts = i.unique(return_counts=True)` to `_, counts = i.cpu().unique(return_counts=True)`

**Comment by pderrenger** [comment]
Thank you for the suggestion. Before making any changes, could you please verify if the issue persists with the latest versions of PyTorch and Ultralytics? If the problem continues, we can consider implementing a workaround for MPS devices.

**Comment by Y-T-G** [comment]
@LiYan1988 Are you able to reproduce the error?

**Comment by Ghost-LZW** [comment]
> @LiYan1988 Are you able to reproduce the error?

with latest versions of PyTorch(2.4.1) and Ultralytics(8.3.5), I can still reproduce the error on macOS.

```
Ultralytics 8.3.5 🚀 Python-3.12.3 torch-2.4.1 MPS (Apple M2 Pro)
...
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ultralytics/utils/loss.py", line 225, in __call__
    targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/ultralytics/utils/loss.py", line 189, in preprocess
    out = torch.zeros(batch_size, counts.max(), ne - 1, device=self.device)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: Trying to create tensor with negative dimension -1: [1, -1, 5]
```

**Comment by Ghost-LZW** [comment]
> > @glenn-jocher
> > Yeah. It's a good thing it crashes before it. It's not supposed to be that large.
> > The [OP](https://github.com/ultralytics/ultralytics/issues/12999) posted a reproduceable example where just a tensor with single value is returning counts that large when it's supposed to return 1.
> > ```python
> > wzl_cpu = torch.tensor([0.0]).to('cpu')
> > wzl_mps = torch.tensor([0.0]).to('mps')
> > print(wzl_cpu.unique(return_counts=True))
> > # Output: (tensor([0.]), tensor([1]))
> > 
> > print(wzl_mps.unique(return_counts=True))
> > # Output: (tensor([0.], device='mps:0'), tensor([9223372036854775807], device='mps:0'))
> > ```
> 
> @Ghost-LZW Can you run this code? What's the output?

This output is correct

```
(tensor([0.]), tensor([1]))
(tensor([0.], device='mps:0'), tensor([1], device='mps:0'))
```

**Comment by Y-T-G** [comment]
@Ghost-LZW Are you using a script or a notebook?

**Comment by Ghost-LZW** [comment]
@Y-T-G I did this in terminal, it's strange, when I dump the `i` and `counts` https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/loss.py#L186-L187, which are

```
(tensor([0.], device='mps:0'), tensor([-1], device='mps:0', dtype=torch.int32))
```

but when I `torch.load` it, I can't reproduce it.

**Comment by Y-T-G** [comment]
@Ghost-LZW Dump before

`counts = counts.to(dtype=torch.int32)`

**Comment by Ghost-LZW** [comment]
> @Ghost-LZW Dump before
> 
> `counts = counts.to(dtype=torch.int32)`

before `counts = counts.to(dtype=torch.int32)`, the `counts` is
```
tensor([9223372036854775807], device='mps:0')
```

I still can't reproduce the issue in a clean script..

**Comment by Y-T-G** [comment]
@Ghost-LZW What's `i`? 0?

Use `with open ("variable.pkl", "wb") as f: pickle.dump(i, f)` to dump `i` as pickle file.

Then load it in a different session.

**Comment by Ghost-LZW** [comment]
> @Ghost-LZW What's `i`? 0?
> 
> Use `with open ("variable.pkl", "wb") as f: pickle.dump(i, f)` to dump `i` as pickle file.
> 
> Then load it in a different session.

yes，that's what  I  did. and  i is  0

**Comment by Y-T-G** [comment]
@Ghost-LZW 
Run:
```python
for _ in range(1000):
    i = torch.tensor([0.0]).to('mps')
    _, cnts = i.unique(return_counts=True)
    if cnts.item() > 1:
        print(cnts)
```

**Comment by Ghost-LZW** [comment]
> @Ghost-LZW Run:
> 
> ```python
> for _ in range(1000):
>     i = torch.tensor([0.0]).to('mps')
>     _, cnts = i.unique(return_counts=True)
>     if cnts.item() > 1:
>         print(cnts)
> ```

still can't reproduce, event with python's gil multithread or multi process.

**Comment by glenn-jocher** [comment]
@Ghost-LZW it seems like the issue might be specific to certain environments or configurations. If you continue to encounter this problem, please ensure your software and libraries are up to date, and consider reaching out to the PyTorch community for further assistance.

**Pull request closed without merging**
