### PR TITLE
Improve clarity of how Rectangular training works

### PR DESCRIPTION
**Pull request by CySlider**
The current documentation suggests that you need to pass rectangular dimensions to imgsz, while in fact, even in this case, you need to specify a square with a single dimension passed to imgsz. rect=True will instead calculate an optimal aspect ratio for all images per batch to minimize necessary padding for that particular batch, while respecting the max canvas of imgsz*imgsz

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced description for rectangular training in documentation.

### 📊 Key Changes
- Updated the explanation of the `rect` mode in the training documentation.

### 🎯 Purpose & Impact
- **Purpose**: Provide a clearer understanding of the `rect` option used during training.
- **Impact**: Users will have a more accurate description of what enabling `rect` means, leading to better-informed decisions regarding its use and optimizing training efficiency. 🛠️

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@CySlider please sign CLA above

**Comment by CySlider** [comment]
I feel stupid... how do I sign it?

**Comment by CySlider** [comment]
I have read the CLA Document and I sign the CLA

**Comment by CySlider** [comment]
recheck

**Comment by glenn-jocher** [comment]
@CySlider PR merged! Thank you for your contributions :)

**Pull request merged**
