### PR TITLE
Update tasks.py to allow custom RTEDTRDecoder arguments

### PR DESCRIPTION
**Pull request by redrei**
I attempted to add custom arguments to create a smaller version of RTDETRDecoder in a yaml file, and got thwarted by the parser appending the channels to the end of the arguments list while the RTDETRDecoder has the channels as the second argument as seen in the definition of RTDETRDecoder
```
class RTDETRDecoder(nn.Module):
    export = False  # export mode

    def __init__(
            self,
            nc=80,
            ch=(512, 1024, 2048),
            hd=256,  # hidden dim
            nq=300,  # num queries
            ndp=4,  # num decoder points
            nh=8,  # num head
            ndl=6,  # num decoder layers
            d_ffn=1024,  # dim of feedforward
            dropout=0.,
            act=nn.ReLU(),
            eval_idx=-1,
            # training args
            nd=100,  # num denoising
            label_noise_ratio=0.5,
            box_noise_scale=1.0,
            learnt_init_query=False):
```

This is a quick, and hopefully quite harmless fix, at least it worked for me locally.

### Summary
🐛🚀🆕

Modify `parse_model` function in `ultralytics/nn/tasks.py` to support custom decoder `RTDETRDecoder` for object detection. Adjust the order of arguments passed to the decoder to match its expected signature.

> _`parse_model` changed_
> _to handle `RTDETRDecoder`_
> _autumn of objects_

### Walkthrough
*  Modify `parse_model` function to handle `RTDETRDecoder` model ([link](https://github.com/ultralytics/ultralytics/pull/3872/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L703-R706))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimized channel argument handling for RTDETRDecoder in the neural network module.

### 📊 Key Changes
- Tweaked the way channel arguments are passed to different model types during parsing.
- For `RTDETRDecoder`, channel arguments are now inserted at the second position in the argument list (index 1).

### 🎯 Purpose & Impact
- 🎯 **Purpose:** The change ensures that the `RTDETRDecoder` receives the correct channel information for better model configuration and initialization.
- 💡 **Impact:** This update improves the flexibility and correctness of model instantiation, particularly for `RTDETRDecoder`, potentially leading to better performance or easier debugging during model development and usage.
- 🚀 **For Users:** More robust model construction with potentially improved performance for tasks involving `RTDETRDecoder`.

### CODE REVIEW

**Comment by redrei** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@redrei could we do this instead?

```python
        elif m in (Detect, Segment, Pose, RTDETRDecoder):
            args.extend([[ch[x] for x in f], *args[1:]])
```

**Comment by glenn-jocher** [comment]
This might generalize the fix to all tasks if it works.

**Comment by glenn-jocher** [comment]
@redrei testing my change in https://github.com/ultralytics/ultralytics/pull/3872/commits/45c02ce88daa5f34312a8c6e138619f9c7ce5813

**Comment by glenn-jocher** [comment]
@redrei ok I think this PR is all set. I've gone with a slightly different implementation, please let me know if this works for you, and if not please submit a second PR with fixes.

**Comment by redrei** [comment]
It looks good to me!

**Comment by glenn-jocher** [comment]
@redrei great to hear! Please let me know if you encounter any issues or have any further questions or suggestions. Your feedback is crucial to us as it helps make YOLOv8 even better for everyone in the community. Don't hesitate to reach out or open new issues. Happy coding!

**Pull request merged**
