### PR TITLE
`ultralytics 8.2.79` YOLOv10 CoreML and MPS training "gather" op error fix

### PR DESCRIPTION
**Pull request by Oil3**
Hello, 
attempting a Yolov10 model export into a CoreML format failed at 99% because of a CoreML error with the "gather" op into "gather_along_axis".
Similarly, starting the training of a Yolov10 model using Metal Perfomance Shaders (MPS) for device, would immediately bring a failed assertion from the "MPSNDArrayGatherND" MPS kernel.

> ERROR - converting 'gather' op (located at: '23'):
> CoreML: export failure ❌ 4.5s: Op "boxes" (op_type: gather_along_axis) Input indices="1195" expects tensor or scalar of dtype from type domain ['int32'] but got tensor[1,300,4,fp32] 

> [...]/MetalPerformanceShaders/MPSNDArray/Kernels/MPSNDArrayGatherND.mm:255: failed assertion `Rank of updates array (1) must be greater than or equal to inner-most dimension of indices array (300)'

The issue appeared to be related to the Yolov10 n̶o̶n̶ ̶m̶a̶x̶i̶m̶u̶... "Post-Processing" part in the "head" module, specifically in the "torch.gather" operation between "boxes" and "indices".

Swapping with "simpler part" that's commented in the code allowed exporting, but I still couldn't train with "device=mps".
Other, working approach was to use "torch.arrange" instead of "torch.gather" but I was concerned about accuracy.

In the end, simply **setting the tensor explicitly to "int64" for the index just before the last "gather" operation fixed the issues.**

I wasn't sure about the implications for other platforms, although from my understanding the "torch.gather" op wants an "int64" anyway, so I put as condition "if torch.backends.mps.is_available()" for the change to only apply to the platform of the matter.

It's my first PR,
Kind regards,

--->
I have read the CLA Document and I sign the CLA

[Issues/13342](https://github.com/ultralytics/ultralytics/issues/13342)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved Metal Performance Shaders (MPS) compatibility in model post-processing.

### 📊 Key Changes
- Added a condition to convert tensor indices to "int64" type when MPS backend is available.

### 🎯 Purpose & Impact
- 🛠️ **Enhanced Compatibility**: Ensures seamless operation with Apple's Metal Performance Shaders (MPS) and CoreML, avoiding runtime errors.
- 🚀 **Improved Exporting**: Facilitates successful model export to CoreML format by preventing specific operational errors.
- 🔧 **User Experience**: Allows broader hardware support, particularly for users on Apple devices, ensuring models work efficiently without additional tweaks.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Minor version upgrade with code improvements for compatibility with macOS and CoreML.

### 📊 Key Changes
- Increased version from `8.2.78` to `8.2.79`.
- Added a check for `MACOS` to handle specific dtype settings in `postprocess` function in `ultralytics/nn/modules/head.py`.

### 🎯 Purpose & Impact
- **Compatibility Enhancements**: Ensures better performance and fewer errors on macOS and CoreML platforms by addressing dtype issues.
- **Code Maintenance**: Keeps the software versioning up-to-date, reflecting the latest changes and fixes.

### CODE REVIEW

**Comment by Oil3** [comment]
recheck

**Comment by glenn-jocher** [comment]
@Oil3 thanks for the PR! CI is failing for torch 1.8 backwards compatibility, can you resolve this please? Thank you!
Screenshot 2024-08-19 at 03 05 43

**Comment by glenn-jocher** [comment]
@Oil3 just realized my fix won't work for CoreML export. In this case you can use the MACOS boolean here, i.e. if MACOS: ...

**Comment by glenn-jocher** [comment]
@Oil3 you can do `from ultralytics.utils import MACOS` and also `ARM64` if you want to target only ARM macOS devices

**Comment by Oil3** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Oil3** [comment]
@glenn-jocher Hi,
tried to avoid imports and `if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():` did it just right :)

**Comment by glenn-jocher** [comment]
Thanks for the update! Glad to hear that `if hasattr(torch.backends, 'mps') and torch.backends.mps.is_available():` worked for you. If you encounter any further issues, please let us know.

**Comment by glenn-jocher** [comment]
@Oil3 I've simplified to if MACOS: since this is lower overhead (the boolean is already known), let's try this and please submit another PR if this doesn't work as expected. Thank you!

**Comment by glenn-jocher** [comment]
@Oil3 PR merged. Thank you for your contributions!

**Comment by glenn-jocher** [comment]
Thank you for your kind words and support! We're glad to hear that Ultralytics has been helpful for your projects. If you encounter any further issues or have more contributions, feel free to reach out. Happy coding!

**Pull request merged**
