### PR TITLE
Avoid CUDA round-trip for relevant export formats

### LINKED ISSUE #3724: Avoid CUDA round-trip for relevant export formats
Originally raised in https://github.com/ultralytics/ultralytics/pull/3722

I'm referring to the following situation:
```
model = YOLO("yolov8n_openvino_model")
results = model.track(source="https://www.youtube.com/watch?v=p5jj3J0zPsQ", stream=True)
```

In that case (also using ONNX, CoreML, etc.), we know the CUDA won't be used. However, the default device for the input is "cuda". So there is memory copying between GPU and CPU, which affects performance in any of these backends.
image

_Originally posted by @adrianboguszewski in https://github.com/ultralytics/ultralytics/issues/3722#issuecomment-1634530122_

### PR DESCRIPTION
**Pull request by glenn-jocher**
Attempt to resolve #3724

### Summary
🐛🚀🔊

This pull request enhances the `Predictor` classes in `ultralytics/vit/sam` and `ultralytics/yolo/engine` by fixing bugs, simplifying code, and adding features. It improves the performance and usability of the prediction modules for the vision transformer and YOLO models.

> _`Predictor` improved_
> _Bug fixed, code simplified_
> _Autumn leaves falling_

### Walkthrough
*  Avoid mutating default argument `overrides` in `Predictor` constructor ([link](https://github.com/ultralytics/ultralytics/pull/3727/files?diff=unified&w=0#diff-5d8eae79b5b3d11ebfbece419dd4e458cb07e6c67c1ac1a960e4f85fc158bb40L21-R23))
* Simplify expression for checking None inputs in `Predictor.predict` ([link](https://github.com/ultralytics/ultralytics/pull/3727/files?diff=unified&w=0#diff-5d8eae79b5b3d11ebfbece419dd4e458cb07e6c67c1ac1a960e4f85fc158bb40L93-R95))
* Add `verbose` parameter to `Predictor.setup_model` to control device information printing ([link](https://github.com/ultralytics/ultralytics/pull/3727/files?diff=unified&w=0#diff-5d8eae79b5b3d11ebfbece419dd4e458cb07e6c67c1ac1a960e4f85fc158bb40L287-R289))
* Use generator expression for creating `names` dictionary in `Predictor.setup_model` ([link](https://github.com/ultralytics/ultralytics/pull/3727/files?diff=unified&w=0#diff-5d8eae79b5b3d11ebfbece419dd4e458cb07e6c67c1ac1a960e4f85fc158bb40L309-R311))
* Remove redundant assignment of `model` and pass it directly to `AutoBackend` constructor in `predictor.py` ([link](https://github.com/ultralytics/ultralytics/pull/3727/files?diff=unified&w=0#diff-bd2831d027341da2474db760605211ea00b347396b0d708a4343a2b709eb3675L304-R304))
* Move assignment of `self.args.half` to after `AutoBackend` constructor in `predictor.py` to ensure consistency with device type ([link](https://github.com/ultralytics/ultralytics/pull/3727/files?diff=unified&w=0#diff-bd2831d027341da2474db760605211ea00b347396b0d708a4343a2b709eb3675R312-R313))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimized model compatibility and inference processes.

### 📊 Key Changes
- Added support for additional formats in FP16 checks.
- Streamlined device selection, defaulting to CPU if GPU is unavailable for certain cases.
- Enforced `attempt_download_asset` for non-local models.
- Improved code by removing redundant expressions.
- Refined model setup methods and updated usage of half-precision and device settings.
- Refined validator to update device and half settings.
- Cleaned up requirement checks by removing redundant code.

### 🎯 Purpose & Impact
- 🚀 Enhances cross-platform model support and simplifies device handling during inference, benefiting users by improving the adaptability of models to various environments.
- 🛠 Fixes and refactors make the codebase cleaner and easier to maintain.
- ⚡ Provides clearer warnings and error messages to users when dealing with unsupported formats or missing requirements, improving overall user experience.

### CODE REVIEW

**Comment by adrianboguszewski** [comment]
It looks good to me. Thanks :)
image

**Comment by glenn-jocher** [comment]
@adrianboguszewski ok awesome! I left the `.cpu()` call in there. Theoretically it should no longer be needed, but I can't be 100% sure there won't be a cuda tensor passed in, and if it's a CPU tensor the overhead is very small, i.e.

```python
import torch
x = torch.randn(1,3,640,640)
%timeit x.cpu()
315 ns ± 3.08 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

**Comment by adrianboguszewski** [comment]
That sounds good. The time in that case is negligible.

**Comment by glenn-jocher** [comment]
PR merged!

**Pull request merged**
