### PR TITLE
Update W&B docs.

### LINKED ISSUE #16704: Duplicated Wandb runs with multiple gpus
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Multi-GPU

### Bug

For one actual training run multiple Wandb runs are spawned when I use multiple gpus. I guess that problem because of use of `subprocess.run`, so no global `wandb.run` will be propagated to new process.

image
image

I suggest to propagate wandb run's project, name, and id to subprocess through [Environment](https://docs.wandb.ai/guides/track/environment-variables/) or ddp file (hard way), that should fix the issue.

### Environment

```
Ultralytics 8.3.5 🚀 Python-3.10.14 torch-2.4.0 CUDA:0 (Tesla T4, 15095MiB)
Setup complete ✅ (4 CPUs, 31.4 GB RAM, 5934.0/8062.4 GB disk)
```

Kaggle with GPU T4 x 2

### Minimal Reproducible Example

https://www.kaggle.com/code/dantetemplarwhowas/notebook915070977e

### Additional

It's hard for me to debug actual behavior because I have only one gpu on my local machine. Problem appears in Kaggle with GPU T4 x 2 accelerator.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Y-T-G**
Closes #16704 

Added environment variable setting to prevent duplicates.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced documentation with glossary links and integration updates for increased usability.

### 📊 Key Changes
- Added glossary links to terms like "accuracy," "object detection," "precision," and "recall" to improve documentation clarity.
- Modified Weights & Biases integration instructions, streamlining setup and usage.
- Updated Python and CLI code snippets for better readability and functionality.
- Added a new author entry in the `mkdocs_github_authors.yaml` file.

### 🎯 Purpose & Impact
- **Improved Understanding:** Glossary links help users, especially beginners, better understand technical terms. 📚
- **Simplified Integration:** Streamlined instructions make it easier for users to set up Weights & Biases with YOLO11, enhancing experiment tracking and visualization. 🚀
- **Enhanced Collaboration:** Updated author entries improve community collaboration and documentation contributions. 🤝

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting a pull request to the `ultralytics/ultralytics` repository! 🚀 Here's a quick checklist to ensure a smooth integration:

- ✅ **Define a Purpose**: Clearly describe the purpose of your update in the PR description, and reference any relevant [issues](https://github.com/ultralytics/ultralytics/issues) if applicable. Make sure your commit messages are clear and follow project conventions.
- ✅ **Synchronize with Source**: Ensure your branch is even with the `main` branch of `ultralytics/ultralytics`. You can update your branch by clicking 'Update branch' or running `git pull` followed by `git merge main`.
- ✅ **Ensure CI Checks Pass**: Confirm that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass. Address any failures as needed.
- ✅ **Update Documentation**: If your changes include feature updates, ensure the relevant [documentation](https://docs.ultralytics.com) is updated.
- ✅ **Add Tests**: If applicable, include or update tests for your changes, ensuring all tests pass.
- ✅ **Sign the CLA**: Make sure you've signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by writing "I have read the CLA Document and I sign the CLA" in a comment if this is your first PR.
- ✅ **Minimize Changes**: Keep your changes focused on the **minimum** necessary to achieve your goals. "It is not daily increase but daily decrease, hack away the unessential." — Bruce Lee

For additional guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). An Ultralytics engineer will review your submission soon. If you have questions, feel free to ask! Thank you for enhancing our documentation! 🌟💼

**Comment by glenn-jocher** [comment]
@Y-T-G actually the W&B docs are far away from the actual usage. All that's required is to do `wandb login` and then train and all your models will automatically sync. I guess doesn't make for much of a Docs page but we don't need any of the stuff that's showing now.

**Comment by Skillnoob** [comment]
I think the W&B docs page should be rewritten to a simpler guide, since ultralytics already has a W&B integration built in and the current guide is redundant.

**Comment by glenn-jocher** [comment]
@Skillnoob yeah that's what I mean. We can just basically explain two things:

- `wandb login` and `wandb enabled` and `wandb disabled`
- Setting wandb=False in Ultralytics Settings to also disable.
- Passing `project=YOUR_PROJECT_NAME` and `name=YOUR_MODEL_NAME` to pass to W&B project and model name.

I think that's it. There's really nothing else to it.

**Comment by Skillnoob** [comment]
@glenn-jocher I've implemented your suggestions, but the FAQ needs to be redone. I don't know how to trigger the automatic FAQ generation though.

**Comment by glenn-jocher** [comment]
@Skillnoob oh got it, I can do that! Just delete it and I can run the action on the branch.

**Comment by glenn-jocher** [comment]
Updated github authors YAML with @Skillnoob but let's try to use a consistent commit email, thanks!

**Comment by glenn-jocher** [comment]
Looks good @Skillnoob @Y-T-G, merging PR!

**Pull request merged**
