### PR TITLE
An example of ONNX implementation for instance Segmentation. 

### PR DESCRIPTION
**Pull request by sounok1234**
### Summary
🚀📝🎨

This pull request adds a new example project that shows how to use ONNX Runtime with YOLOv8 for object detection and segmentation. It includes a `main.py` file that implements the model and a `README.md` file that explains the project and how to run it.

> _`ONNX Runtime` runs_
> _YOLOv8 for detection_
> _and segmentation_

### Walkthrough
*  Implement YOLOv8 object detection and segmentation model using ONNX Runtime ([link](https://github.com/ultralytics/ultralytics/pull/4864/files?diff=unified&w=0#diff-777b61d0b0b7d5c30499c813b51ab1f0d9bdbfd854e3497af40931f481963c5eL1-R286))
* Document the project and provide usage instructions ([link](https://github.com/ultralytics/ultralytics/pull/4864/files?diff=unified&w=0#diff-f3259166f71bb4dee1a1aa4ce04d723ea39a0305fd068cef82788fbebecaf318R1-R43))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of YOLOv8 with ONNX Runtime support for GPU/CPU and segmentation capabilities.

### 📊 Key Changes
- New `examples/YOLOv8-ONNXRuntime-Segmentation` directory with README and Python script.
- README details installation and usage instructions for running YOLOv8 with ONNX Runtime.
- Python script (`main.py`) added for handling YOLOv8 object detection and segmentation using ONNX Runtime.
- New functionalities including preprocessing of images, drawing detection boxes and polygons, postprocessing of ONNX outputs, and main execution flow for detection.

### 🎯 Purpose & Impact
- 🚀 **Enhanced Compatibility**: Utilizing ONNX Runtime, which enables the YOLOv8 model to run on diverse platforms and with GPU acceleration.
- 🌐 **Broader Access**: Operation on both GPU and CPU environments increases accessibility.
- 🔍 **Improved Object Detection**: Introduction of segmentation masks adds precise object outline detection, improving use cases in complex environments.
- 🛠️ **Ease of Use**: With clear setup and usage instructions, users can quickly implement YOLOv8 for their image recognition tasks.
- 📈 **Performance Gains**: GPU support means faster processing times for image detection tasks, beneficial for real-time applications.

### CODE REVIEW

**Comment by sounok1234** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@sounok1234 thanks for the PR! ONNX inference (and inference for most export formats) is supported natively already for super simple deployment, i.e.:

```python
from ultralytics import YOLO

# Create a YOLO model
model = YOLO('yolov8n.pt')

# Export to ONNX
onnx_file = model.export(format='onnx')

# Load the ONNX model
onnx_model = YOLO('onnx_file')

# Run inference on CPU and GPU with ONNXRuntime
results = onnx_model('path/to/image.jpg')
```

**Comment by glenn-jocher** [comment]
You can see validation results and export checks here for YOLOv8 ONNX Segmentation models:
https://github.com/ultralytics/ultralytics/actions/runs/6153172479/job/16696606220

Screenshot 2023-09-12 at 20 51 43

**Comment by sounok1234** [comment]
Thanks for the quick reply @glenn-jocher! Damn, I missed that! Should I just close the PR then?

**Comment by glenn-jocher** [comment]
@sounok1234 hi, thanks for getting back to us! Yes, given that ONNX inference is natively supported in the current setup, your proposed changes might not be necessary at this time. We appreciate your contribution and are always open for further suggestions and improvements. Please feel free to close this PR. Thank you!

**Pull request closed without merging**
