### PR TITLE
Add `instance segmentation` and `vision-eye mapping` in Docs + Fix minor code bug in other `real-world-projects`

### LINKED ISSUE #6892: generate_heatmap crashes notebooks
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Other

### Bug

Hi, Ultralytics team,

I am having some troubles using the new heatmap feature on notebooks (Google Colab and Kaggle notebooks).

From what I've searched, this is due to the  cv2.imshow() function, not supported in notebooks.

The script that fails is [ultralytics/solutions/heatmap.py](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/solutions/heatmap.py), on line 171: `cv2.imshow('Ultralytics Heatmap', im0_with_heatmap)`

I wonder if this can be fixed so we can use the new heatmap feature in notebooks.

Many thanks to all Ultralytics team for the awesome work and lib, as always!

image

### Environment

Ultralytics YOLOv8.0.225 🚀 Python-3.10.12 torch-2.1.0+cu118 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 27.1/166.8 GB disk)

OS                  Linux-5.15.120+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.68 GB
CPU                 Intel Xeon 2.30GHz
CUDA                11.8

matplotlib          ✅ 3.7.1>=3.3.0
numpy               ✅ 1.23.5>=1.22.2
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.1.0+cu118>=1.8.0
torchvision         ✅ 0.16.0+cu118>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.12.2>=0.11.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1

### Minimal Reproducible Example

```

### https://docs.ultralytics.com/guides/heatmaps/#__tabbed_1_4

from ultralytics import YOLO
from ultralytics.solutions import heatmap
import cv2

model = YOLO("yolov8s.pt")   # YOLOv8 custom/pretrained model

cap = cv2.VideoCapture("path/to/video/file.mp4")  # Video file Path, webcam 0
assert cap.isOpened(), "Error reading video file"

# Region for object counting
count_reg_pts = [(20, 400), (1080, 404), (1080, 360), (20, 360)]

# Heatmap Init
heatmap_obj = heatmap.Heatmap()
heatmap_obj.set_args(colormap=cv2.COLORMAP_JET,
                     imw=cap.get(4),  # should same as im0 width
                     imh=cap.get(3),  # should same as im0 height
                     view_img=True,
                     count_reg_pts=count_reg_pts)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        exit(0)
    results = model.track(im0, persist=True)
    im0 = heatmap_obj.generate_heatmap(im0, tracks=results)

```

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by RizwanMunawar**
### Highlights

- This PR will hopefully resolve the issue #6892.
- Update the `object_counting.py` to display counts, when the user runs code in `colab` or `notebooks`.
- Fix the `colab` and `notebook` issues for all real-world applications.
- Include a Docs page on **VisionEye View Mapping with Ultralytics YOLOv8 🚀**: This feature empowers computers to pinpoint and focus on specific objects, resembling human eye observation.
- Introduce a Docs page on **Instance Segmentation and Object Tracking**: Enable users to visualize object segmentation for each instance with the help of object tracking
- Embed YouTube video for `object counting` in Docs. 

recheck
re-run

### Summary
📝🎨🏋️‍♂️

This pull request adds two new guides on instance segmentation and VisionEye mapping using YOLOv8, and updates the existing guides on heatmaps, object counting, and workouts monitoring with better code examples and fixes. It also modifies the `ultralytics/solutions/object_counter.py` and `ultralytics/utils/plotting.py` files to support the new features and improve the object counting labels.

> _We unleash the power of YOLOv8_
> _We segment and track the objects of fate_
> _We map the world with VisionEye_
> _We guide you through the code with pride_

### Walkthrough
*  Add two new guides on instance segmentation and VisionEye mapping using YOLOv8 ([link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-5774885f4e8a06c57ea38aa3cf0daa33840d2ab39990175e4452f0e900d75b0eR1-R125), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-a333cdaeadb47b8e70ffcc384b960a8029120d6a2f522e8bb8de0d2e9146678eR1-R125), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfR274-R275))
*  Update existing guides on heatmaps, object counting, and workouts monitoring with improved code examples and user feedback ([link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-a4662bf3737ed93deb7bf62b759ba3ab68caa23ba2f98c7d4517f36951d1b9dcL45-R58), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-a4662bf3737ed93deb7bf62b759ba3ab68caa23ba2f98c7d4517f36951d1b9dcL73-R88), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-a4662bf3737ed93deb7bf62b759ba3ab68caa23ba2f98c7d4517f36951d1b9dcL112-R124), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-a4662bf3737ed93deb7bf62b759ba3ab68caa23ba2f98c7d4517f36951d1b9dcL136-R158), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-f986f79eb725464a96a6029262317cbda2826fbf0e889150529f5256f2a75268L41-R53), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-f986f79eb725464a96a6029262317cbda2826fbf0e889150529f5256f2a75268L67-R83), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-f986f79eb725464a96a6029262317cbda2826fbf0e889150529f5256f2a75268L92-R112), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-f986f79eb725464a96a6029262317cbda2826fbf0e889150529f5256f2a75268R118), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-8497103381e2396b3a760f5e71d03ba2a178ae6ad10a7f1ffe73683b8463314fL48-R54), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-8497103381e2396b3a760f5e71d03ba2a178ae6ad10a7f1ffe73683b8463314fL65-R70), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-8497103381e2396b3a760f5e71d03ba2a178ae6ad10a7f1ffe73683b8463314fL79-R83), [link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-8497103381e2396b3a760f5e71d03ba2a178ae6ad10a7f1ffe73683b8463314fR89))
*  Add a new method to the Annotator class to draw segmented objects in bounding box shape with labels ([link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-471dc6902e48f880561beca675bfee38e440de6cd49a3de9432de27305d3cc6bL386-R404))
*  Move the incount and outcount labels outside the if statement in the object counter module ([link](https://github.com/ultralytics/ultralytics/pull/6972/files?diff=unified&w=0#diff-60d3917967eb034ef934fe2a66c41af86edc6b003e8b5a28b8abd592a4bbef25L142-R146))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to Ultralytics YOLOv8 documentation and code for heatmaps, object counting, and new guides on instance segmentation and tracking, and VisionEye View object mapping.

### 📊 Key Changes
- Improved clarity and added new features in heatmap generation.
- New file for instance segmentation and tracking guide.
- New file for VisionEye View object mapping guide.
- Better video frame handling and cleanup in various guides.
- Minor code improvements for readability.

### 🎯 Purpose & Impact
- 🔍 Easier understanding and usability of heatmap features.
- 💡 Introduction of detailed guides on instance segmentation and object tracking.
- 😲 Showcasing VisionEye's capabilities in a new guide.
- 🛠 More robust and user-friendly examples.
- 🧹 Ensures proper resource management, preventing potential memory leaks during video processing. 

These updates aim to enrich the documentation with additional guides and improve existing features, making them more intuitive and user-friendly. The changes enhance the learning experience for users and allow for more creative applications of Ultralytics YOLOv8 in real-world scenarios.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar looks great!

For the segmentation+tracking page should we call this by it's proper name, i.e. "Instance Segmentation and Tracking"?

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes I think the name you suggested is easy to understand. I will update the title soon!

**Comment by RizwanMunawar** [comment]
@glenn-jocher The title has been revised, and the instance segmentation now appears significantly improved.

|                                                          Instance Segmentation                                                          |                                                           Instance Segmentation + Object Tracking                                                            |
|:---------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| Ultralytics Instance Segmentation | Ultralytics Instance Segmentation with Object Tracking |
|                                                  Ultralytics Instance Segmentation 😍                                                   |                                                  Ultralytics Instance Segmentation with Object Tracking 🔥                                                   |

**Comment by glenn-jocher** [comment]
@RizwanMunawar can you replace the `cv2.FONT_HERSHEY_SIMPLEX` values here with just `0` as we have in most of the original Annotator functions?

Also please update the print() statements for something with less exclamation points, i.e.:

```diff
-              print("Information!!! -> Empty frame or Video Processing Finished!!!")
+              print("Video frame is empty or video processing has been successfully completed.")
```

**Comment by RizwanMunawar** [comment]
@glenn-jocher ok, nice check 👍🏻 

`cv2.FONT_HERSHEY_SIMPLEX` values are now updated with `0` in `plotting.py`. All print statements in `docs` have been updated!

```python
print("Video frame is empty or video processing has been successfully completed.")
```

**Comment by glenn-jocher** [comment]
@RizwanMunawar PR merged!

**Pull request merged**
