### PR TITLE
Updating links to the OpenVINO notebooks

### PR DESCRIPTION
**Pull request by andrei-kochin**
Updating the links to the OpenVINO notebooks to point to the 'latest' branch

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated links in the OpenVINO integration documentation for better user guidance.

### 📊 Key Changes
- Updated the link path to the YOLOv8 optimization tutorial to point to the 'latest' directory instead of 'main'.
- Modified the link for the API tutorial to also direct users to the 'latest' version of notebooks.

### 🎯 Purpose & Impact
- **Improved Accessibility**: By directing users to the 'latest' versions of notebooks, the documentation ensures users have access to the most current information and tutorials. 📚
- **Enhanced User Experience**: This change helps in avoiding potential confusion and ensures that users are not following outdated guides or tutorials, thereby improving their learning and development experience. 🛠️

These updates aim to streamline the learning process for developers and users engaging with OpenVINO through Ultralytics, enhancing both ease of use and overall satisfaction.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated OpenVINO documentation links for YOLOv8 optimization and API tutorial.

### 📊 Key Changes
- Changed the URL path from "main" to "latest" for the **YOLOv8 optimization notebook**.
- Updated the URL path for the **OpenVINO API tutorial** to its latest location.

### 🎯 Purpose & Impact
- **Up-to-date Information**: Ensures users have the most current resources and tutorials, enhancing learning and implementation efficiency.
- **Ease of Access**: Directs users to the right tutorials quickly, improving user experience and potentially speeding up the development and optimization process for projects using YOLOv8 with OpenVINO.
- **Broader Application**: By ensuring documentation links are current, developers and researchers can more effectively optimize and deploy AI models across various Intel hardware, targeting improvements in performance and versatility.

### CODE REVIEW

**Comment by andrei-kochin** [comment]
recheck

**Comment by andrei-kochin** [comment]
recheck

**Comment by andrei-kochin** [comment]
I have read the CLA Document and I sign the CLA

**Comment by andrei-kochin** [comment]
recheck

**Comment by glenn-jocher** [comment]
@andrei-kochin PR merged! Thank you for your contributions :)

**Pull request merged**
