### PR TITLE
`ultralytics 8.1.10` MLFlow, OBB, TFLite and INT8 fixes

### PR DESCRIPTION
**Pull request by Youho99**
Final fix for #6706 issue

Fix mlflow callback
Enable the MLFLOW logging of train losses, and learning rates

Activation of on_train_epoch_end
on_train_epoch_end refactor

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Ultralytics software advances with version bump and MLflow logging improvements.

### 📊 Key Changes
- Updated Ultralytics package version from 8.1.9 to 8.1.10.
- Enhanced MLflow logging by combining loss and learning rate metrics into a single logging step during training epochs.

### 🎯 Purpose & Impact
- **Version Update:** Keeps users up-to-date with the latest software version, indicating minor improvements or bug fixes.
- **Improved MLflow Logging:** Provides a more streamlined and efficient logging experience during training, which can help users better track and analyze their model's performance over time. This may be particularly beneficial for users involved in machine learning operations (MLOps) who require detailed training logs for workflow optimizations. 📈🤖

### CODE REVIEW

**Comment by Youho99** [comment]
I have read the CLA Document and I sign the CLA
recheck

**Comment by Youho99** [comment]
recheck

**Comment by glenn-jocher** [comment]
@Youho99 thank you for signing the CLA. Your contribution is acknowledged, and the recheck process has been initiated. 🔄 Please be patient as the checks are completed. If there are any updates or actions required from your side, we will reach out to you.

**Comment by glenn-jocher** [comment]
recheck

**Comment by Youho99** [comment]
I have read the CLA Document and I sign the CLA

**Pull request merged**
