### PR TITLE
Fix empty paths while saving images with PIL bytes input

### LINKED ISSUE #16681: YoloV8 prediction with save=True thorws erros with PIL Image
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

_No response_

### Bug

When yolov8x model is invoked with a PIL image with argument save=True, it doesn't save it and throws error.

cv2.error: OpenCV(4.7.0) /io/opencv/modules/imgcodecs/src/loadsave.cpp:692: error: (-2:Unspecified error) could not find a writer for the specified extension in function 'imwrite_'

### Environment

Ultralytics YOLOv8.1.26 🚀 Python-3.11.5 torch-2.3.1+cu121 CPU (Intel Core(TM) i7-10750H 2.60GHz)
Setup complete ✅ (12 CPUs, 15.3 GB RAM, 305.7/467.9 GB disk)

### Minimal Reproducible Example

image_url ='https://ultralytics.com/images/bus.jpg'
response = requests.get(image_url)
img = Image.open(BytesIO(response.content))

yolov8_model_path = 'pretrained_models/yolov8x.pt'
detection_model = YOLO(yolov8_model_path)

 results = detection_model(img, save=True)

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by SheffeyG**
As described in #16681, this PR fix empty paths by setting a default path value `image{i}.jpg`.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved image filename handling in data loader.

### 📊 Key Changes
- Modified the logic for assigning image filenames: now uses `"image{i}.jpg"` when the `filename` attribute is empty.

### 🎯 Purpose & Impact
- **Purpose:** Ensures each image is assigned a valid filename, preventing errors related to empty paths.
- **Impact:** Enhances robustness of the data loader, leading to smoother workflows and fewer interruptions for users. 📸🔧

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @SheffeyG, thank you for submitting a pull request to the `ultralytics/ultralytics` 🚀 repository!

Your contribution to fixing the issue of empty paths while saving images is much appreciated. To ensure a smooth integration, please go through the checklist below:

- ✅ **Define a Purpose**: Make sure the purpose of the fix is clearly explained in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues), such as #16681. Ensure clarity and adherence to commit message conventions.
- ✅ **Synchronize with Source**: Check if your PR is up-to-date with the `main` branch of `ultralytics/ultralytics`. If necessary, update your branch by clicking 'Update branch' or using `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Please review the results of all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks and address any failures.
- ✅ **Update Documentation**: If your changes introduce new behavior or modify existing features, make sure to update the relevant [documentation](https://docs.ultralytics.com).
- ✅ **Add Tests**: Include or update tests relevant to your changes and verify all are passing.
- ✅ **Sign the CLA**: If this is your first PR with Ultralytics, remember to sign the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA".
- ✅ **Request MRE**: If this fixes a bug, and you haven't already, please add a minimum reproducible example (MRE) to demonstrate the issue and validate the fix.

For further reading, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to reach out if you have questions or need clarification. An Ultralytics engineer will be with you shortly to assist further. Thank you for helping enhance Ultralytics! 🚀

🔍 Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)

**Comment by Laughing-q** [comment]
@SheffeyG Thanks for the PR! Actually I prefer to do the update in the `LoadPilAndNumpy` class and that's where we handle the PIL type as input.

**Review by Laughing-q — APPROVED** [review]

**Comment by SheffeyG** [comment]
@Laughing-q Noticed there's another line in loaders.py class `LoadTensor`
https://github.com/ultralytics/ultralytics/blob/50497218c25682458ea35b02dcc5d8a364f34591/ultralytics/data/loaders.py#L467
should we update this one too?

**Comment by Laughing-q** [comment]
@SheffeyG no worries this one is fine, it's for torch.Tensor.

**Review by ambitious-octopus — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@SheffeyG @Laughing-q PR merged!

**Pull request merged**
