### PR TITLE
`ultralytics 8.0.237` `cv2.CAP_PROP` fix and `in_counts` and `out_counts` displays

### PR DESCRIPTION
**Pull request by glenn-jocher**
@RizwanMunawar @Burhan-Q @Zengyf-CVer permanent docs fixes for transposed with-height on heatmaps and other recent video guides.

@RizwanMunawar can you please review?

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updating video capturing and heatmap enhancements in documentation and code.

### 📊 Key Changes
- Refactored video capture code to consolidate frame width, height, and frames per second into tuples.
- Modified video writer instantiation to use new tuples for clarity and consistency.
- Included additional view flags (`view_in_counts` and `view_out_counts`) to control object counter display settings.
- Updated heatmap initialization to ensure correct dimension order.
- Corrected object counter and heatmap related documentation to match code changes.
- Updated the library version from `8.0.236` to `8.0.237`.

### 🎯 Purpose & Impact
- **Code Readability:** Simplified video capture variables enhance readability and reduce redundancy.
- **Customizable Display:** Users can now decide whether to display in, out or both counts during object counting.
- **Bug Fixes:** Fixed heatmap array initialization to reflect proper dimensions, avoiding potential errors.
- **Updated Documentation:** Documentation now reflects latest code changes, providing accurate guidance to users.
- **Library Versioning:** Updated version number marks the progress and ensures users can reference the correct version.

### CODE REVIEW

**Review by RizwanMunawar — APPROVED** [review]
@glenn-jocher all good :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar can you update heatmaps.ipynb too?

**Comment by glenn-jocher** [comment]
@RizwanMunawar these are still left to update, I'll do the markdown file, can you do the two notebooks?
Screenshot 2024-01-07 at 18 22 05

**Comment by RizwanMunawar** [comment]
@glenn-jocher sure, give me a sec :)

**Comment by Burhan-Q** [comment]
I added a https://github.com/ultralytics/ultralytics/pull/7368#issuecomment-1880118697 to the old PR but it might have been the same time it was closed, so I wanted to make sure it was seen.

I believe the original proposed change in dfb477cbd1cade6b929a963a54d7456301c54a3d is still valid. This is because the `self.heatmap` "image-frame" will be set with the incorrect (Width, Height) shape for the empty `heatmap` array.

```py
self.im0.shape
>>> (1080, 1920, 3)

self.imh, self.imw = self.im0.shape[:2]

self.heatmap = np.zeros((int(self.imw), int(self.imh)), dtype=np.float32) # current L123 in heatmap.py
self.heatmap.shape
>>> (1920, 1080, 3)

```

Since the `cv2` uses the `(Height, Width)` for the array shape for images, then @Zengyf-CVer's original proposed change:

```diff
- self.heatmap = np.zeros((int(self.imw), int(self.imh)), dtype=np.float32) 
+ self.heatmap = np.zeros((int(self.imh), int(self.imw)), dtype=np.float32) 
```

**Comment by glenn-jocher** [comment]
@Burhan-Q oh, but @Zengyf-CVer original PR updated the python file shape order, this PR updates the docs feeding that python file, so if we transpose both we'll be back where we started.

**Comment by Burhan-Q** [comment]
<details><summary>Here's the exact code I just tested with</summary>
<p>

```py

from pathlib import Path
from ultralytics import YOLO
from ultralytics.solutions import heatmap
import cv2

model = YOLO("yolov8n.pt")

# This section is specific for my PC
video_file = r"F:\Downloads\pexels_videos_1192116 (1080p).mp4"
vid_path = Path(video_file)
cap = cv2.VideoCapture(video_file, 1400)

assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Video writer
save_path = vid_path.parent / (vid_path.stem + '_HEATMAP3' + vid_path.suffix)
video_writer = cv2.VideoWriter(save_path.as_posix(),
                                cv2.VideoWriter_fourcc(*'mp4v'),
                                fps,
                                (w, h))

# Init heatmap
heatmap_obj = heatmap.Heatmap()
heatmap_obj.set_args(colormap=cv2.COLORMAP_PARULA,
                        imw=w,
                        imh=h,
                        view_img=True,
                        shape="circle")

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break
    tracks = model.track(im0, persist=True, show=False)

    im0 = heatmap_obj.generate_heatmap(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()
```

</p>
</details> 

Still getting an error

```
0: 384x640 3 cars, 17.0ms
Speed: 4.0ms preprocess, 17.0ms inference, 5.0ms postprocess per image at shape (1, 3, 384, 640)

Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File ".yolo\lib\site-packages\ultralytics\solutions\heatmap.py", line 247, in generate_heatmap
    self.im0 = cv2.addWeighted(self.im0, 1 - self.heatmap_alpha, heatmap_colored, self.heatmap_alpha, 0)
cv2.error: OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\core\src\arithm.cpp:650: error: (-209:Sizes of input arguments do not match) The operation is neither 'array op array' (where arrays have the same size and the same number of channels), nor 'array op scalar', nor 'scalar op array' in function 'cv::arithm_op'
```

**Comment by RizwanMunawar** [comment]
@glenn-jocher Notebooks updated :)

I think everything will work fine as normal now onwards 👍🏻

**Comment by Burhan-Q** [comment]
The error in `heatmap.py` is because `self.im0.shape[:2] != self.heatmap.shape[:2]` and the issue is thrown at L247:

```py
self.im0 = cv2.addWeighted(self.im0, 1 - self.heatmap_alpha, heatmap_colored, self.heatmap_alpha, 0)
```

since it's trying to execute an operation on two arrays that don't have the same dimensions

**Comment by glenn-jocher** [comment]
@Burhan-Q ah ok, wow, good you checked! So if you apply @Zengyf-CVer fix then your test works correctly?

**Comment by glenn-jocher** [comment]
The pace of the PRs around here lately is kinda crazy. Since this should fix the bug I've incremented the patch number for this PR so it will publish to PyPI as 8.0.237.

**Comment by RizwanMunawar** [comment]
@glenn-jocher change the code based on @Burhan-Q recommendation, I think we are good to go now :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar ok it looks like your latest commit resolves @Burhan-Q and @Zengyf-CVer initial concern right?

**Comment by glenn-jocher** [comment]
Ok I merged @Zengyf-CVer original PR into this one so he gets authorship also as the OP. I'll merge this now after the CI goes green :)

**Comment by RizwanMunawar** [comment]
Yes hopefully @glenn-jocher I actually merged all the changes of @Zengyf-CVer and all other `caps` replaced :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar @Burhan-Q nice work guys!!!

**Pull request merged**
