### PR TITLE
emoji-safe logging using logging.Filter

### LINKED ISSUE #1999: Emoji Logging on Windows
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

https://github.com/ultralytics/ultralytics/blob/48c44837953f0c09571255339ef3e51aa90fbb8b/ultralytics/yolo/utils/__init__.py#L226-L229

What case needs this code block?

I tried to print file path and line number with messages. But I found an error with this code block on windows. Logger can't correctly log file path and line number with it.

image

### Additional

_No response_

### PR DESCRIPTION
**Pull request by developer0hye**
### Summary
🆕🐛📝

Added a new class `EmojiFilter` to handle emoji logging on Windows and updated the `LOGGER` variable in `ultralytics/yolo/utils/__init__.py`. This improves the logging functionality and compatibility across platforms.

> _To make logging more simple and stable_
> _A new class was added, `EmojiFilter`_
> _It prevents any glitches_
> _From those pesky emoticons_
> _And makes the output more readable_

### Walkthrough
*  Add a new class `EmojiFilter` to enable emoji-safe logging on Windows platforms ([link](https://github.com/ultralytics/ultralytics/pull/2030/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137R222-R225))
*  Simplify the `LOGGER` variable by using the `EmojiFilter` class instead of manually wrapping the log methods with the `emojis` function ([link](https://github.com/ultralytics/ultralytics/pull/2030/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137L227-R231))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated licensing from GPL-3.0 to AGPL-3.0 and other minor enhancements across multiple GitHub Actions workflows and repository files.

### 📊 Key Changes
- Changed the license from GPL-3.0 to AGPL-3.0 in CITATION.cff, LICENSE, README.md, setup.py, and contributing guidelines.
- Altered comments and added the `EmojiFilter` logging filter to handle emojis in logs, especially for Windows.
- Updated Dockerfile usage examples and other comments/documentation strings.
- Performed minor refactoring across various YAML files and code modules.

### 🎯 Purpose & Impact
- The license change to AGPL-3.0 👩‍⚖️ ensures that if the software or a derivative work is used on a network server, the source code must be made available to the community, fostering transparency and collaboration.
- The addition of the `EmojiFilter` 🚫🙂 enhances log compatibility with environments that do not support emojis, like some Windows terminals.
- Cleaned-up documentation 📑 and usage examples ensure users have up-to-date and accurate reference information.
- General code cleanup 🧹 and minor refactoring ensure the code quality remains high and maintainable.

### CODE REVIEW

**Comment by developer0hye** [comment]
It is related to #1999.

**Comment by developer0hye** [comment]
Every function call location always becomes with an original method with `lambda`. I could solve it with `Filter`.

image

**Comment by glenn-jocher** [comment]
@developer0hye very cool, thanks for the PR!

**Comment by glenn-jocher** [comment]
I'm going to add a windows CI to this PR temporarily to test on Windows.

**Comment by developer0hye** [comment]
@glenn-jocher Coooooooooool!

**Comment by glenn-jocher** [comment]
@developer0hye Windows works! Awesome, nice updates. Merging into updates branch for next release.

**Comment by developer0hye** [comment]
@glenn-jocher Thanks! It feels like it's been a while since I sent a meaningful PR. I am happy with it.

**Comment by glenn-jocher** [comment]
@developer0hye great to hear that you are satisfied with your contribution to the project! It's always exciting to see our contributions make a difference and add value to the community. Keep up the great work! If you have any more ideas or improvements to make, be sure to let us know.

**Pull request merged**
