### PR TITLE
feat(callbacks): track produced plots to simplify logging

### LINKED ISSUE #1909: Add callback on image / file saved
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

We need to see when trainer, validator, etc create images (samples, metric plots, etc) to be able to capture them in the loggers. I'm creating a logger (as well as some other things, like [`devcontainer` with GPU support](https://github.com/ultralytics/ultralytics/compare/main...shcheklein:ultralytics:main#diff-8c75d30eaaa096649631dde76e321d13a6849c64137f3f7f777429ef9fd6b9e2) that I plan also to contribute) for DVC [here](https://github.com/ultralytics/ultralytics/compare/main...shcheklein:ultralytics:main#diff-052c6262efa033fb56c6ac6241d151d7eb373ee01daa36cf70077f332078a216). I think we (and other loggers) can benefit a lot from this.

### Use case

Pretty much similar to what Comet logger already does in an ad-hoc way, e.g.:

```python
def _log_plots(experiment, trainer):
    plot_filenames = [trainer.save_dir / f'{plots}.png' for plots in EVALUATION_PLOT_NAMES]
    _log_images(experiment, plot_filenames, None)

    label_plot_filenames = [trainer.save_dir / f'{labels}.jpg' for labels in LABEL_PLOT_NAMES]
    _log_images(experiment, label_plot_filenames, None)
```

by hardcoding `EVALUATION_PLOT_NAMES`, etc. It's doable and a possible workaround, but it's fragile (if code changes in the core, it clearly breaks the logger). Also, it would be sad if we have to duplicate the same logic everywhere.

### Additional

Suggestion is to add a new type of callback, e.g. `on_train_image_save` or `on_train_plot_save`. An alternative is to have some instance dict where we could register all visualizations (e.g. trainer.visualizations? or `trainer.plots`)- downside can be that we don't know which image is per epoch, which one is at the end, etc.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by shcheklein**
Closes https://github.com/ultralytics/ultralytics/issues/1909

If the approach is fine in general, I'll add the same callback to the `Validator` and other base classes.

`timestamp` is need to determine if plot got updated.

### Summary
📊🎨🔌

This pull request adds a new feature to the `ultralytics/yolo` framework that allows trainers to store and manage plots generated during training. It introduces a new attribute `plots` and a new method `on_plot` to the `BaseTrainer` class, and modifies the plotting functions and the subclasses of `BaseTrainer` to use the `on_plot` callback. This feature enables trainers to perform custom actions on the plots, such as uploading them to a remote server or displaying them in a web interface.

> _Oh we are the trainers of YOLO, we plot and we save as we go_
> _We pass the `on_plot` to the functions, and handle the plots with our own_
> _Heave away, heave away, heave away on the count of three_
> _We are the trainers of YOLO, we plot and we save as we go_

### Walkthrough
*  Add a new attribute `plots` and a new method `on_plot` to the `BaseTrainer` class to store and register plots generated during training ([link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1R88), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1R537-R543))
* Modify the signature and body of the plotting functions in the `ultralytics/yolo/utils/plotting.py` module to accept and invoke an optional `on_plot` callback with the file name of the plot ([link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L231-R231), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L274-R281), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L304-R309), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L422-R432), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L459-R470), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L459-R470))
* Pass the `on_plot` attribute of the trainer as an argument to the plotting functions in the `plot_training_samples`, `plot_training_labels`, and `plot_metrics` methods of the subclasses of `BaseTrainer` in the `ultralytics/yolo/v8` submodules ([link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-734f7c7d5e997138ddb17cffc50e37008364bb3fdba26403ee9d145ce2764f69L132-R132), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-734f7c7d5e997138ddb17cffc50e37008364bb3fdba26403ee9d145ce2764f69L153-R154), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L125-R130), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L135-R136), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-990260aed22cad0e3a42309be3fee54d7dabc589b0bd5558d1e47f0f32adcc70L68-R73), [link](https://github.com/ultralytics/ultralytics/pull/2461/files?diff=unified&w=0#diff-69b3b40601c35cc60cecb5a813fe62a36840599d895ebd439501a87a91f85581L48-R59))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
The PR introduces a new callback mechanism for handling plot outputs in the Ultralytics YOLO training and validation pipeline.

### 📊 Key Changes
- Added an `on_plot` callback throughout various YOLO modules (`trainer.py`, `validator.py`, and multiple metric/util classes) to handle plot data and timestamps.
- Updated plotting functions (`plot_pr_curve`, `plot_mc_curve`, etc.) to accept an `on_plot` argument that gets invoked with the plot path and data when plots are rendered.
- Modified the training, validation, and metric classes for detection, segmentation, pose, and classification tasks to register plot data using the new `on_plot` callback.

### 🎯 Purpose & Impact
- The introduction of the `on_plot` callback allows for more flexible plot handling, such as external storage, custom logging, or real-time visualization.
- Users and developers can now easily integrate custom behaviors when plots are generated during model training and validation, enhancing the extensibility of the Ultralytics YOLO framework.
- The changes have the potential to improve the user experience by allowing for personalized plot management without altering the core plotting code. 📈🎨

### CODE REVIEW

**Comment by shcheklein** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@shcheklein thanks for the PR! This looks good to me. 

@AyushExel what do you think?

**Comment by shcheklein** [comment]
@glenn-jocher thanks! I'll continue working on this one to include validator at least and see if need tests for this. Hopefully this week-next week.

**Comment by AyushExel** [comment]
Thanks. Looks good!

**Comment by glenn-jocher** [comment]
@shcheklein great, sounds good! Let us know when it's ready for review.

**Comment by shcheklein** [comment]
Hey @glenn-jocher , it should be good to go. I've added the same logic to the Validator class. When it's released I'll be trying it on the DVCLive logger and do changes if needed.

**Comment by glenn-jocher** [comment]
@shcheklein PR merged into updates branch for 8.0.105 later today!

**Comment by shcheklein** [comment]
@glenn-jocher thanks! 🙏

**Comment by glenn-jocher** [comment]
@shcheklein you're welcome! It was a pleasure to work on this new feature for YOLOv8. Let us know if you have any other questions or concerns regarding YOLOv8. We're always happy to help.

**Pull request merged**
