### PR TITLE
New `MLFLOW_KEEP_RUN_ACTIVE` flag for enhanced MLflow run management

### PR DESCRIPTION
**Pull request by massimiliano96**
This commit introduces a new configuration option, `MLFLOW_KEEP_RUN_ACTIVE`, aimed at providing users with greater flexibility in managing MLflow runs. The `MLFLOW_KEEP_RUN_ACTIVE` flag is a boolean variable that determines whether to keep the MLflow run active after the completion of the training phase.

Here's a brief overview of the changes:
- The commit introduces the `keep_run_active` variable, which is derived from the `MLFLOW_KEEP_RUN_ACTIVE` environment variable. The default value is set to `False`, but users can customize it by setting the environment variable to 'True'.
- If `keep_run_active` is set to `False`, the MLflow run is automatically ended using `mlflow.end_run()`. The system logs a debug message confirming the closure.
- If `keep_run_active` is set to `True`, a notification is logged, reminding users to manually close the MLflow run using `mlflow.end_run()` when appropriate.

This enhancement provides users with more control over their MLflow runs and ensures a seamless integration of MLflow into their workflow. Upgrade your system today to take advantage of this new functionality and optimize your MLflow run management experience.

Usage example:

```
import mlflow
os.environ['MLFLOW_KEEP_RUN_ACTIVE'] = 'True'
YOLO('yolov8n-cls.yaml').train(data='imagenet10', imgsz=32, epochs=1, plots=False, device='cpu')
mlflow.log_image(custome_metric, "custom_metric_img.png")
mlflow.end_run()
```

In this example, the image "custom_metric_image.png" is logged within the same Yolov8 artifacts run.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced MLflow integration with option to keep runs active post-training.

### 📊 Key Changes
- Added `mlruns/` to `.gitignore` to avoid tracking MLflow run files.
- Introduced a new test to verify MLflow run status based on the environment variable `MLFLOW_KEEP_RUN_ACTIVE`.
- Implemented the handling for `MLFLOW_KEEP_RUN_ACTIVE` in MLflow callback, enabling users to control whether an MLflow run should remain active after training completion.

### 🎯 Purpose & Impact
- **Improved Flexibility**: Allows users more control over their MLflow runs, specifically enabling runs to remain active for additional logging or analysis after the initial training phase ends.
- **Enhanced Workflow**: Facilitates deeper integration with MLflow for more complex machine learning workflows, potentially improving experiment tracking and reproducibility.
- **User Experience**: With clear logging about the status of MLflow runs, users can better manage their experiment tracking and ensure clean run state management.

### CODE REVIEW

**Comment by massimiliano96** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@massimiliano96 PR merged, thank you for your contributions!

**Comment by massimiliano96** [comment]
@glenn-jocher I saw an issue in the tests, where I can put the fix?

**Comment by glenn-jocher** [comment]
Ah no worries, just submit a new PR, thank you!

**Comment by glenn-jocher** [comment]
@massimiliano96 I'm going to comment out the tests for now, please submit a fix when you can, thank you!

**Pull request merged**
