### PR TITLE
Disable FP16 val on AMP fail and improve AMP checks

### LINKED ISSUE #16290: YOLOv8-OBB - All the losses are 0 or nan during training and ) precision, recall metrics.
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

I have been facing this issue for a while now where during training of the YOLOv8_-obb model, all the losses are 0 or nan (in one dataset I was getting 0, in another I'm getting nan). And the precision and recall values are also 0. It remains like that even if I train for 1200 epochs.

This is how it looks like:
image

I have my labels in the required format as:
image

Config file is also set:
image

I have tried for over a month now, and I do not understand why this issue is arising.

### Environment

Ultralytics YOLOv8.2.77 🚀 Python-3.8.5 torch-2.0.1+cu117 CUDA:0 (NVIDIA T1200 Laptop GPU, 4096MiB)

### Minimal Reproducible Example

from ultralytics import YOLO

model = YOLO("yolov8s-obb.yaml")

res = model.train(data="myData.yaml", epochs=1200, imgsz=640, single_cls=True)

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #16302: The parameters BOX(P, R, mAP50, mAP50-95) are always 0 when the batch value is high.
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

**I am using a laptop with a GTX1650 graphics card with 4 GB of video memory. I train the YOLOv10m model, but the choice of model does not affect the result (I tried Yolov8n). Amp is disabled because it does not work on this video card. With batch = 4, during training, the BOX parameters (P, R, mAP50, mAP50-95) are always 0. At the same time, video memory consumption = 1.45 GB. Because of this, determining the best model does not work. If you reduce the batch value to 3, then everything works (video memory consumption = 1.2GB). With automatic batch detection (batch = -1), training takes place with an increased batch (batch = 5). This problem does not allow efficient use of the GPU.**

Batch = 4:
Ultralytics YOLOv8.2.94 🚀 Python-3.12.3 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolov10m.pt, data=./yolo_data_symbol/data.yaml, epochs=200, time=None, patience=100, batch=4, imgsz=288, save=True, save_period=-1, cache=False, device=cuda, workers=8, project=None, name=symbolDetectV10m3, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=False, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\symbolDetectV10m3  
Overriding model.yaml nc=80 with nc=22

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1     78720  ultralytics.nn.modules.block.SCDown          [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1    228672  ultralytics.nn.modules.block.SCDown          [384, 576, 3, 2]
  8                  -1  2   1689984  ultralytics.nn.modules.block.C2fCIB          [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1   1253088  ultralytics.nn.modules.block.PSA             [576, 576]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 17                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  2    831744  ultralytics.nn.modules.block.C2fCIB          [576, 384, 2, True]
 20                  -1  1    152448  ultralytics.nn.modules.block.SCDown          [384, 384, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  2   1911168  ultralytics.nn.modules.block.C2fCIB          [960, 576, 2, True]
 23        [16, 19, 22]  1   2306452  ultralytics.nn.modules.head.v10Detect        [22, [192, 384, 576]]
YOLOv10m summary: 498 layers, 16,509,604 parameters, 16,509,588 gradients, 64.1 GFLOPs

Transferred 787/799 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
train: Scanning D:\py\yolo_data_symbol\train\labels.cache... 798 images, 0 backgrounds, 0 corrupt: 100%|██████████| 798/798 [00:00<?, ?it/s]
val: Scanning D:\py\yolo_data_symbol\valid\labels.cache... 140 images, 0 backgrounds, 0 corrupt: 100%|██████████| 140/140 [00:00<?, ?it/s]
Plotting labels to runs\detect\symbolDetectV10m3\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000385, momentum=0.9) with parameter groups 129 weight(decay=0.0), 142 weight(decay=0.0005), 141 bias(decay=0.0)
Image sizes 288 train, 288 val
Using 8 dataloader workers
Logging results to runs\detect\symbolDetectV10m3
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/200      1.32G      1.789      4.298      1.802         53        288: 100%|██████████| 200/200 [00:51<00:00,  3.87it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 18/18 [00:04<00:00,  4.16it/s]
                   all        140       1166          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/200      1.45G      1.409      1.322      1.692         47        288: 100%|██████████| 200/200 [00:52<00:00,  3.79it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 18/18 [00:04<00:00,  4.35it/s]
                   all        140       1166          0          0          0          0

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      3/200      1.44G      1.357      1.026       1.69         17        288: 100%|██████████| 200/200 [00:55<00:00,  3.63it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 18/18 [00:03<00:00,  4.82it/s]
                   all        140       1166          0          0          0          0
_______________________________________________________________________________________________________________________________________

batch = 3:
Ultralytics YOLOv8.2.94 🚀 Python-3.12.3 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
engine\trainer: task=detect, mode=train, model=yolov10m.pt, data=./yolo_data_symbol/data.yaml, epochs=200, time=None, patience=100, batch=3, imgsz=288, save=True, save_period=-1, cache=False, device=cuda, workers=8, project=None, name=symbolDetectV10m2, exist_ok=False, pretrained=True, optimizer=auto, verbose=True, seed=0, deterministic=True, single_cls=False, rect=False, cos_lr=False, close_mosaic=10, resume=False, amp=False, fraction=1.0, profile=False, freeze=None, multi_scale=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, split=val, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, vid_stride=1, stream_buffer=False, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, embed=None, show=False, save_frames=False, save_txt=False, save_conf=False, save_crop=False, show_labels=True, show_conf=True, show_boxes=True, line_width=None, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, pose=12.0, kobj=1.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, bgr=0.0, mosaic=1.0, mixup=0.0, copy_paste=0.0, auto_augment=randaugment, erasing=0.4, crop_fraction=1.0, cfg=None, tracker=botsort.yaml, save_dir=runs\detect\symbolDetectV10m2  
Overriding model.yaml nc=80 with nc=22

                   from  n    params  module                                       arguments
  0                  -1  1      1392  ultralytics.nn.modules.conv.Conv             [3, 48, 3, 2]
  1                  -1  1     41664  ultralytics.nn.modules.conv.Conv             [48, 96, 3, 2]
  2                  -1  2    111360  ultralytics.nn.modules.block.C2f             [96, 96, 2, True]
  3                  -1  1    166272  ultralytics.nn.modules.conv.Conv             [96, 192, 3, 2]
  4                  -1  4    813312  ultralytics.nn.modules.block.C2f             [192, 192, 4, True]
  5                  -1  1     78720  ultralytics.nn.modules.block.SCDown          [192, 384, 3, 2]
  6                  -1  4   3248640  ultralytics.nn.modules.block.C2f             [384, 384, 4, True]
  7                  -1  1    228672  ultralytics.nn.modules.block.SCDown          [384, 576, 3, 2]
  8                  -1  2   1689984  ultralytics.nn.modules.block.C2fCIB          [576, 576, 2, True]
  9                  -1  1    831168  ultralytics.nn.modules.block.SPPF            [576, 576, 5]
 10                  -1  1   1253088  ultralytics.nn.modules.block.PSA             [576, 576]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 13                  -1  2   1993728  ultralytics.nn.modules.block.C2f             [960, 384, 2]
 14                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 15             [-1, 4]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 16                  -1  2    517632  ultralytics.nn.modules.block.C2f             [576, 192, 2]
 17                  -1  1    332160  ultralytics.nn.modules.conv.Conv             [192, 192, 3, 2]
 18            [-1, 13]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 19                  -1  2    831744  ultralytics.nn.modules.block.C2fCIB          [576, 384, 2, True]
 20                  -1  1    152448  ultralytics.nn.modules.block.SCDown          [384, 384, 3, 2]
 21            [-1, 10]  1         0  ultralytics.nn.modules.conv.Concat           [1]
 22                  -1  2   1911168  ultralytics.nn.modules.block.C2fCIB          [960, 576, 2, True]
 23        [16, 19, 22]  1   2306452  ultralytics.nn.modules.head.v10Detect        [22, [192, 384, 576]]
YOLOv10m summary: 498 layers, 16,509,604 parameters, 16,509,588 gradients, 64.1 GFLOPs

Transferred 787/799 items from pretrained weights
Freezing layer 'model.23.dfl.conv.weight'
train: Scanning D:\py\yolo_data_symbol\train\labels.cache... 798 images, 0 backgrounds, 0 corrupt: 100%|██████████| 798/798 [00:00<?, ?it/s]
val: Scanning D:\py\yolo_data_symbol\valid\labels.cache... 140 images, 0 backgrounds, 0 corrupt: 100%|██████████| 140/140 [00:00<?, ?it/s]
Plotting labels to runs\detect\symbolDetectV10m2\labels.jpg... 
optimizer: 'optimizer=auto' found, ignoring 'lr0=0.01' and 'momentum=0.937' and determining best 'optimizer', 'lr0' and 'momentum' automatically...
optimizer: AdamW(lr=0.000385, momentum=0.9) with parameter groups 129 weight(decay=0.0), 142 weight(decay=0.0004921875), 141 bias(decay=0.0)
Image sizes 288 train, 288 val
Using 8 dataloader workers
Logging results to runs\detect\symbolDetectV10m2
Starting training for 200 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/200      1.08G      1.765      4.128      1.807         48        288: 100%|██████████| 266/266 [01:06<00:00,  4.01it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 24/24 [00:04<00:00,  4.83it/s]
                   all        140       1166      0.635     0.0111     0.0209     0.0199

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      2/200      1.21G      1.448      1.309      1.702         57        288:  73%|███████▎  | 195/266 [00:46<00:18,  3.82it/s]

### Environment

Ultralytics YOLOv8.2.94 🚀 Python-3.12.3 torch-2.4.1+cu124 CUDA:0 (NVIDIA GeForce GTX 1650, 4096MiB)
Setup complete ✅ (12 CPUs, 23.4 GB RAM, 63.1/292.9 GB disk)

### Minimal Reproducible Example

import torch
from ultralytics import YOLO

if __name__ == '__main__':

    device = 'cuda' if torch.cuda.is_available() else 'cpu'

    data_path = './yolo_data_symbol/data.yaml'  

    model = YOLO("yolov10m.pt", task='detect') 

    epochs_size = 200  
    batch = 4  
    imgsize = 288  

    model.train(name='symbolDetectV10m', data=data_path, epochs=epochs_size, batch=batch, imgsz=imgsize, device=device, amp=False, half=False)

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Y-T-G**
Closes https://github.com/ultralytics/ultralytics/issues/16302, closes https://github.com/ultralytics/ultralytics/issues/16290?notification_referrer_id=NT_kwDOAetur7QxMjQxMjcxMzE1MDozMjIwNjUxMQ#issuecomment-2352996722

[Some GPUs have issues with AMP training](https://redd.it/1eqfl7t), yet they somehow pass AMP checks. So I added an explicit `half` inference in the `amp_checks`. I think it should catch such GPUs. I can't verify this fix since I don't have these GPUs. I asked the authors of the above issues to check if inference works for them when `half=True`. If it doesn't, then the check should correctly find this. However, @sascha93rus mentioned that the metrics are not 0 if the `batch` is set to 3 or lower, which is peculiar and might mean that we need to use a batch of 4 for AMP checks, in case it somehow produces correct results for single images even when `half=True`.

I also added an exception to FP16 validation when `amp=False` because [that leads to 0 metrics during validation](https://github.com/ultralytics/ultralytics/issues/16302,).

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced AMP validation and FP16 logic for improved performance during training.

### 📊 Key Changes
- Modified FP16 validation to depend on AMP settings, ensuring compatibility with non-CPU devices.
- Updated the AMP all-close check to use batch processing for FP32 and AMP inference, improving consistency.

### 🎯 Purpose & Impact
- 💻 **Improved Efficiency**: Ensures FP16 is used correctly during training when AMP is enabled, optimizing processing speed.
- 🔍 **Enhanced Validation**: More robust and reliable AMP check by using batch input, improving accuracy in performance assessment.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting your PR to the `ultralytics/ultralytics` repository! 🚀 This automated response will guide you through the necessary steps to ensure a smooth integration of your contribution. An Ultralytics engineer will review your PR shortly. 

Here's a checklist to get you started:

- ✅ **Define a Purpose**: Please ensure your PR description explains the intent of the changes clearly and links to any [relevant issues](https://github.com/ultralytics/ultralytics/issues) 🚀. Your commit messages should be clear and concise, following project conventions.
- ✅ **Synchronize with Source**: Make sure your PR is up to date with the `main` branch. If it's not, you can update it by clicking 'Update branch' or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Double-check that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks have passed. If there are any issues, please address them.
- ✅ **Update Documentation**: If your changes affect the documentation, update the relevant [documentation](https://docs.ultralytics.com).
- ✅ **Add Tests**: Include or update tests for your changes and confirm that all tests pass. This helps maintain the quality and stability of the codebase 🧪.
- ✅ **Sign the CLA**: If this is your first contribution, sign the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA".
- ✅ **Minimize Changes**: Keep changes to the minimum necessary for your feature or bug fix. "It is not daily increase but daily decrease, hack away the unessential." — Bruce Lee

For any further guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to leave a comment if you need assistance or have questions. Thank you for contributing to Ultralytics! 🎉

**Comment by Y-T-G** [comment]
Thanks to @sascha93rus for the tests.

As per the results posted from [his tests](https://github.com/ultralytics/ultralytics/issues/16302#issuecomment-2353477292), we don't need to check for `half` inference explicitly but rather run the inference with a batch of 7 or more to detect issues with these GPUs. I set it to 8 in the updated version. I also lowered the `imgsz=96` to avoid VRAM issues. The tests still work at that `imgsz`.

image

The PR should correctly detect these GPUs and disable AMP accordingly. And the validation will also no longer run in `half` precision when AMP is disabled.

**Comment by Y-T-G** [comment]
Relevant issue.

https://github.com/pytorch/pytorch/issues/58123

**Comment by glenn-jocher** [comment]
@Y-T-G got it thanks, but I think we've extremely modified the processing power consumed by these AMP checks.

If we expand the imgsz by 4 on each dim and the batch by 8 thats 4*4*8 = **128 times more FLOPs consumed here just to check AMP functionality.** 

I would not expand this arbitrarily anymore than absolutely required to achieve the desired result.

**Comment by glenn-jocher** [comment]
@Y-T-G yes this looks good!

**Comment by Laughing-q** [comment]
@Y-T-G @glenn-jocher I think the `self.args.amp` remains `True` even the `check_amp` fails since it update `trainer.amp` instead of `args.amp`. https://github.com/ultralytics/ultralytics/blob/c5bee7545cb5fe26e201c593f3920b4b462c73c1/ultralytics/engine/trainer.py#L264
Opened a PR to update it. https://github.com/ultralytics/ultralytics/pull/16333

**Pull request merged**
