### PR TITLE
Add `allow_background_images=True` in split_dota.py

### PR DESCRIPTION
**Pull request by Galasnow**
The default value of  'reserve' is set to 'True' to reserve images without label. Manually set it to 'False' to ignore these background images and therefore reduce dataset size. Solve Issue https://github.com/ultralytics/ultralytics/issues/15030

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Small enhancement to the `crop_and_save` function for better handling of background images.

### 📊 Key Changes
- Added `allow_background_images` parameter to the `crop_and_save` function.
- Modified logic to save image patches even if they contain no labels, based on the new parameter.

### 🎯 Purpose & Impact
- 🖼️ **Purpose**: Allow optional saving of background image patches without labels.
- 🌟 **Impact**: Facilitates the use of background images in training, potentially enhancing model training by providing more diverse data.

### CODE REVIEW

**Comment by Galasnow** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@Galasnow thank you for submitting a PR! I've cleaned up and will merge on CI pass.

**Comment by Galasnow** [comment]
Sorry, I did not respond immediately because I had fallen asleep. Thank you very much!

**Comment by pderrenger** [comment]
No problem at all! If you encounter any further issues or have additional questions, feel free to reach out. We're here to help!

**Pull request merged**
