### PR TITLE
`ultralytics 8.2.27` replace `onnxsim` with `onnxslim`

### PR DESCRIPTION
**Pull request by Kayzwer**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Simplified ONNX export and improved Docker image configuration for arm64 architecture. 

### 📊 Key Changes
- **Dockerfile Update:** Removed unnecessary `build-essential` package installation, streamlining Docker setup for arm64.
- **Export Documentation:** Clarified `simplify` option usage in model export settings.
- **Export Testing Enhancements:** Integrated `simplify` parameter in ONNX export test matrices and utilized `onnxslim` for model simplification in tests.
- **Software Dependencies:** Shifted from `onnxsim` to `onnxslim` to avoid complex dependencies like `cmake`.
- **Version Bump:** Updated project version to 8.2.27.

### 🎯 Purpose & Impact
- **Efficiency:** Removing `build-essential` from Dockerfile reduces image size and build time 💾.
- **Clarity:** Updated documentation and variable naming improve understanding of export options 📚.
- **Testing Robustness:** Expanded export test coverage increases confidence in model exports 🧪.
- **Simplification:** Replacing `onnxsim` with `onnxslim` avoids complications related to dependencies, simplifying user experience and installation process 🛠️.
- **Project Evolution:** Increment in project version marks progress and enhancement, readying for new features and improvements 🚀.

### CODE REVIEW

**Comment by Kayzwer** [comment]
@inisis I did not change the doc this time, I have no idea what conflict happened there.

**Comment by inisis** [comment]
@Kayzwer should we modify here to make onnxslim true. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L673

**Comment by Kayzwer** [comment]
> @Kayzwer should we modify here to make onnxslim true. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L673

I set slim=True by default in the config yaml file

**Comment by inisis** [comment]
> > @Kayzwer should we modify here to make onnxslim true. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L673
> 
> I set slim=True by default in the config yaml file

In order to test onnxslim only, I dont't think this is the right way, because it will call both.

**Comment by Kayzwer** [comment]
> > > @Kayzwer should we modify here to make onnxslim true. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L673
> > 
> > I set slim=True by default in the config yaml file
> 
> In order to test onnxslim only, I dont't think this is the right way, because it will call both.

no, I mean I did not set slim=True in code, I set it in config yaml file only

**Comment by inisis** [comment]
> > > > @Kayzwer should we modify here to make onnxslim true. https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L673
> > > 
> > > 
> > > I set slim=True by default in the config yaml file
> > 
> > 
> > In order to test onnxslim only, I dont't think this is the right way, because it will call both.
> 
> no, I mean I did not set slim=True in code, I set it in config yaml file only

but there are hard-coded part, and will not be affected by config yaml, as I mentioned before

**Comment by Burhan-Q** [comment]
@Kayzwer since the `onnx` export is used in a few other export formats, it would be good to update the unit test matrix functions (`test_export_*_matrix`) in `tests/test_export.py` and `tests/test_cuda.py` that would check the addition of the new argument; [see example](https://github.com/ultralytics/ultralytics/blob/c8b6a8bc37ce196a6b7e0c153539402db4383c16/tests/test_cuda.py#L22-L48). Additionally, with the addition of a new export argument, the docs tables (I think there are ~11) would all need to be updated to include this new argument.

**Comment by inisis** [comment]
@Kayzwer Can you add me as a collaborator in your [repo](https://github.com/Kayzwer/ultralytics/tree/main), this code needs to be changed.

**Comment by Kayzwer** [comment]
> @Kayzwer Can you add me as a collaborator in your [repo](https://github.com/Kayzwer/ultralytics/tree/main), this code needs to be changed.

invited

**Comment by inisis** [comment]
@Kayzwer I don't have permission to push

**Comment by Kayzwer** [comment]
image
holy shit github, I have no idea where to click to make an collaborator have write access

**Comment by Kayzwer** [comment]
> @Kayzwer I don't have permission to push

sry man, I cant do that, cause microsoft is piece of shit

**Comment by Kayzwer** [comment]
> @Kayzwer I don't have permission to push

I think you just take my code and make a pull request on ultralytics repo

**Comment by inisis** [comment]
Hi, @glenn-jocher @Burhan-Q @Kayzwer I have tested on my machine, and it works fines, this is pretty much the final version of code, please help review it ❤️❤️❤️, 

249a720c7c13ddce76f4f37686bf03a
5573315b96cc026f7cef645724f37c7
fd8870bb022395714c7daf8fcaf1043

**Comment by glenn-jocher** [comment]
Hi there! Thanks for sharing your work and the test results. 🚀 It looks like you've put a lot of effort into this. I'll review the code and get back to you with any feedback or suggestions. Keep up the great work!

**Review by Kayzwer — COMMENTED** [review]
no prob

**Comment by inisis** [comment]
@glenn-jocher Hi, can this be merged or if there are any other things to do. I have also tested on the latest yolov10.

**Comment by glenn-jocher** [comment]
Hi @inisis,

Thanks for your patience! The code has been tested on the latest YOLOv10 and works well. If there are any additional changes or reviews needed, please let me know. Looking forward to your feedback! 😊

**Comment by inisis** [comment]
@Kayzwer Hi, should we add some doc to it, I should have seen it before

**Comment by inisis** [comment]
@glenn-jocher Hi, docs are added, and I think this pr is ready. Thanks for your great work.

**Comment by glenn-jocher** [comment]
Hi @inisis,

Thank you for adding the documentation! It looks great. We'll review the PR shortly. Appreciate your contribution and the kind words! 😊

**Comment by glenn-jocher** [comment]
@Kayzwer hey could you upload two models, one exported with slim and the other with simplify? I'm trying to get a side-by-side comparison to understand the difference. Thank you!

**Comment by initialencounter** [comment]
Hi @glenn-jocher  , here are the comparison, the models are list here, with simmed one and slimmed one, [yolov8n_sim.zip](https://github.com/ultralytics/ultralytics/files/15492237/yolov8n_sim.zip) [yolov8n_slim.zip](https://github.com/ultralytics/ultralytics/files/15492256/yolov8n_slim.zip), and the details are listed here, 
d4c11f11e6b2e919927ba6f40e809b0e
a3acb174bfa38c7b98ee9ea9c82a7181

onnxslim can have less operators, and have better performance, for more comparsion, you can refer to https://github.com/ultralytics/ultralytics/pull/12683#issuecomment-2119551231
https://github.com/ultralytics/ultralytics/pull/12683#issuecomment-2118618317

**Comment by glenn-jocher** [comment]
Hi @initialencounter,

Thanks for providing the comparison models and detailed visuals! The differences in performance and operator count are quite clear. I'll review the additional comments for a deeper understanding. Great work on this! 🚀

**Comment by glenn-jocher** [comment]
@Kayzwer @inisis working on some onnxslim package updates in https://github.com/inisis/OnnxSlim/pull/2

**Comment by inisis** [comment]
Hi @glenn-jocher onnxslim release package updated

**Comment by Laughing-q** [comment]
@Kayzwer @inisis @glenn-jocher hey guys I ran into an error while trying inference based on the slim model:
```bash
yolo detect export model=yolov8n.pt format=onnx slim
yolo predict model=yolov8n.onnx imgsz=640
```
pic-240530-1857-42

**Comment by inisis** [comment]
> @Kayzwer @inisis @glenn-jocher hey guys I ran into an error while trying inference based on the slim model:
> 
> ```shell
> yolo detect export model=yolov8n.pt format=onnx slim
> yolo predict model=yolov8n.onnx imgsz=640
> ```
> 
> pic-240530-1857-42

@Laughing-q there is a version mismatch, can you provide your onnx and onnxruntime version, or you can refer to this https://onnxruntime.ai/docs/reference/compatibility.html

**Comment by Laughing-q** [comment]
here's my onnx-related packages:
pic-240530-1901-28
but actually the inference works properly to me when exporting onnx with `slim=False`, which is strange:
```bash
yolo detect export model=yolov8n.pt format=onnx slim=False
yolo predict model=yolov8n.onnx imgsz=640
```
pic-240530-1903-03

**Comment by glenn-jocher** [comment]
I'm trying in colab with these commands, haven't run yet:

```
!pip install git+https://github.com/Kayzwer/ultralytics@main

!yolo export format=onnx simplify
%mv yolov8n.onnx yolov8n-simplify.onnx
!yolo export format=onnx slim
%mv yolov8n.onnx yolov8n-slim.onnx

!yolo predict model=yolov8n-simplify.onnx
!yolo predict model=yolov8n-slim.onnx
```

**Comment by Laughing-q** [comment]
@inisis ok it seems issue from my side, I tried with `simplify=True` just now and encountered the same issue

**Comment by inisis** [comment]
> @inisis ok it seems issue from my side, I tried with `simplify=True` just now and encountered the same issue It's likely the error appears when trying to simplify onnx, could be a mismatch issue to me.
> 
> EDIT: the issue fixed after I rolled back onnx from 1.16.1 to 1.15

image

from the document, there is a strict version match, but it's a little big strange when using pip install, no version check warning are raised.

**Comment by Laughing-q** [comment]
@inisis @glenn-jocher My results of profiling slim/sim/original onnx model on my cpu and gpu:
| Model        | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>NVIDIA GeForce RTX 3060 TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|--------------|-----------------------|----------------------|--------------------------------|--------------------------------------------------------|--------------------|-------------------|
| yolov8m-sim  | 640                   | -                    | 196.02 ± 1.54 ms               | 0.00 ± 0.00 ms                                         | 0.0                | 0.0               |
| yolov8m-slim | 640                   | -                    | 200.67 ± 0.18 ms               | 0.00 ± 0.00 ms                                         | 0.0                | 0.0               |
| yolov8m      | 640                   | -                    | 202.15 ± 0.59 ms               | 0.00 ± 0.00 ms                                         | 0.0                | 0.0               |

| Model        | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>GPU ONNX<br>(ms) | Speed<br><sup>NVIDIA GeForce RTX 3060 TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|--------------|-----------------------|----------------------|--------------------------------|--------------------------------------------------------|--------------------|-------------------|
| yolov8m-sim  | 640                   | -                    | 15.32 ± 0.07 ms                | 0.00 ± 0.00 ms                                         | 0.0                | 0.0               |
| yolov8m-slim | 640                   | -                    | 15.63 ± 0.27 ms                | 0.00 ± 0.00 ms                                         | 0.0                | 0.0               |
| yolov8m      | 640                   | -                    | 15.82 ± 0.39 ms                | 0.00 ± 0.00 ms                                         | 0.0                | 0.0               |

my command:
```bash
pip install git+https://github.com/Kayzwer/ultralytics@main

mkdir onnx-test
yolo detect export model=yolov8m.pt format=onnx slim && mv yolov8m.onnx ./onnx-test/yolov8m-slim.onnx
yolo detect export model=yolov8m.pt format=onnx slim=False simplify && mv yolov8m.onnx ./onnx-test/yolov8m-sim.onnx
yolo detect export model=yolov8m.pt format=onnx slim=False && mv yolov8m.onnx ./onnx-test/yolov8m.onnx
```
```python
from ultralytics.utils.benchmarks import ProfileModels

models = ["./onnx-test/"]
ProfileModels(models).profile()
```
Note: for gpu speed I manually updated the [CPUExecutionProvider](https://github.com/ultralytics/ultralytics/blob/25e7054a9c065dda8af32c9b4aacae99db68f61b/ultralytics/utils/benchmarks.py#L456) to `CUDAExecutionProvider` and ran profile script again.

**Comment by inisis** [comment]
| Model | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>NVIDIA GeForce RTX 4090 TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|-------------|---------------------|--------------------|------------------------------|-----------------------------------|------------------|-----------------|
| yolov8m-sim        | 640 | - | 147.28 ± 6.24 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8m-slim       | 640 | - | 144.93 ± 5.12 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |

this is the result on my machine.

Profiling: ['onnx-test/yolov8m-sim.onnx', 'onnx-test/yolov8m-slim.onnx']
onnx-test/yolov8m-sim.onnx: 100%|██████████| 406/406 [01:05<00:00,  6.17it/s]
onnx-test/yolov8m-slim.onnx: 100%|██████████| 394/394 [01:00<00:00,  6.55it/s]

and I wonder why the iterations are not equal

**Comment by glenn-jocher** [comment]
@Laughing-q @Kayzwer thanks for the plots! I just discovered that slim was set to True as the default here, which meant it was being applied to both simplify=True and simplify=False exports. I fixed this in https://github.com/ultralytics/ultralytics/pull/12989/commits/199ab3160e16fc21a40834d7fa4616d32f09eea8 after your results were published. Can you re-run again with the latest version of this PR (I verified that now slim=False by default).

Screenshot 2024-05-30 at 14 05 50

**Comment by glenn-jocher** [comment]
@inisis ProfileModels class is time-based with `min_time=60` default argument meaning that profiling will run for 60 seconds before stopping.
https://github.com/ultralytics/ultralytics/blob/25e7054a9c065dda8af32c9b4aacae99db68f61b/ultralytics/utils/benchmarks.py#L288-L335

**Comment by Laughing-q** [comment]
@glenn-jocher no worries I noticed that! my command was with `slim=False` for `yolov8m-sim.onnx` and `yolov8m.onnx`.
```bash
pip install git+https://github.com/Kayzwer/ultralytics@main

mkdir onnx-test
yolo detect export model=yolov8m.pt format=onnx slim && mv yolov8m.onnx ./onnx-test/yolov8m-slim.onnx
yolo detect export model=yolov8m.pt format=onnx slim=False simplify && mv yolov8m.onnx ./onnx-test/yolov8m-sim.onnx
yolo detect export model=yolov8m.pt format=onnx slim=False && mv yolov8m.onnx ./onnx-test/yolov8m.onnx
```

**Comment by inisis** [comment]
@Laughing-q Can you try the dynamic shape model and even tensorrt

**Comment by inisis** [comment]
@glenn-jocher can you also try the dynamic shape export and manually set benchmark shape as 1,3,640,640

pip install git+https://github.com/Kayzwer/ultralytics@main

mkdir onnx-test
yolo detect export model=yolov8m.pt format=onnx slim dynamic imgsz=32 && mv yolov8m.onnx ./onnx-test/yolov8m-slim.onnx
yolo detect export model=yolov8m.pt format=onnx slim=False simplify dynamic imgsz=32 && mv yolov8m.onnx ./onnx-test/yolov8m-sim.onnx
yolo detect export model=yolov8m.pt format=onnx slim=False dynamic imgsz=32 && mv yolov8m.onnx ./onnx-test/yolov8m.onnx

**Comment by inisis** [comment]
here are what I got

| Model | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>NVIDIA GeForce RTX 4090 TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|-------------|---------------------|--------------------|------------------------------|-----------------------------------|------------------|-----------------|
| yolov8m-sim        | 32 | - | 144.15 ± 5.92 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8m-slim       | 32 | - | 142.81 ± 5.78 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |

**Comment by glenn-jocher** [comment]
@inisis @Kayzwer @Laughing-q I've re-run again on a Google Colab instance for YOLOv8n. New results show better speed for slim than sim, but best speed without either.

```bash
%%bash

pip install git+https://github.com/Kayzwer/ultralytics@main

mkdir onnx-test
model=yolov8n
yolo detect export model=$model.pt format=onnx slim && mv $model.onnx ./onnx-test/$model-slim.onnx
yolo detect export model=$model.pt format=onnx simplify && mv $model.onnx ./onnx-test/$model-sim.onnx
yolo detect export model=$model.pt format=onnx && mv $model.onnx ./onnx-test/$model.onnx
```

```python
from ultralytics.utils.benchmarks import ProfileModels

models = ["./onnx-test/"]
ProfileModels(models).profile()
```

| Model | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>Tesla T4 TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|-------------|---------------------|--------------------|------------------------------|-----------------------------------|------------------|-----------------|
| yolov8n-sim        | 640 | - | 796.16 ± 43.90 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n-slim       | 640 | - | 769.90 ± 45.77 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n            | 640 | - | 749.92 ± 66.65 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |

**Comment by glenn-jocher** [comment]
@Laughing-q @Kayzwer @inisis ok I got tired of profiling myself so I just updated the CI to do this. Results are:

### macos-14 M1 Arm64 runner

| Model | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>GPU TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|-------------|---------------------|--------------------|------------------------------|-----------------------------------|------------------|-----------------|
| yolov8n-sim.onnx        | 640 | - | 309.10 ± 20.55 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n-slim.onnx       | 640 | - | 250.31 ± 31.01 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n.onnx            | 640 | - | 254.38 ± 30.17 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |

### ubuntu-latest runner

| Model | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>GPU TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|-------------|---------------------|--------------------|------------------------------|-----------------------------------|------------------|-----------------|
| yolov8n-sim.onnx        | 640 | - | 228.11 ± 32.67 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n-slim.onnx       | 640 | - | 230.54 ± 31.97 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n.onnx            | 640 | - | 233.25 ± 34.85 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |

### windows-latest runner

Profiling failed due to extremely slow speeds, i.e. 10 seconds per image, not sure what happened here.

**Comment by inisis** [comment]
@glenn-jocher If two models have same number operators of same type, I don't think there should be any performance gap, but if the shapes are dynamic, the two models are different due to different optimization techniques, thus the difference in time should be counted and analyzed.

**Comment by glenn-jocher** [comment]
@inisis You're absolutely right! The presence of dynamic shapes can indeed lead to variations in performance due to different optimization paths taken during the model compilation process. This aspect definitely warrants a deeper analysis to fully understand the impact on inference times. Thank you for highlighting this point and for your appreciation! 🚀

**Comment by inisis** [comment]
Hi @glenn-jocher for dynamic shape model, the current benchmark workflow won't fit, because the input shape are represented in str,

**Comment by inisis** [comment]
Windows CI is trying 😂

**Comment by glenn-jocher** [comment]
Hi @inisis, thanks for the update! We'll look into refining the benchmark workflow to better accommodate dynamic shape models. Your insights are invaluable! 🚀

**Comment by glenn-jocher** [comment]
@Laughing-q @Kayzwer @inisis results with `dynamic=True`

### macos-14 M1 Arm64 runner

| Model | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>GPU TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|-------------|---------------------|--------------------|------------------------------|-----------------------------------|------------------|-----------------|
| yolov8n-sim        | 640 | - | 416.39 ± 87.44 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n-slim       | 640 | - | 404.46 ± 52.55 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n            | 640 | - | 376.98 ± 72.32 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |

### ubuntu-latest runner

| Model | size<br><sup>(pixels) | mAP<sup>val<br>50-95 | Speed<br><sup>CPU ONNX<br>(ms) | Speed<br><sup>GPU TensorRT<br>(ms) | params<br><sup>(M) | FLOPs<br><sup>(B) |
|-------------|---------------------|--------------------|------------------------------|-----------------------------------|------------------|-----------------|
| yolov8n-sim        | 640 | - | 236.14 ± 33.50 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n-slim       | 640 | - | 235.96 ± 30.32 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |
| yolov8n            | 640 | - | 234.92 ± 36.19 ms | 0.00 ± 0.00 ms | 0.0 | 0.0 |

### windows-latest runner

too slow...

**Comment by inisis** [comment]
> @Laughing-q @Kayzwer @inisis results with `dynamic=True`
> 
> ### macos-14 M1 Arm64 runner
> Model	size
> (pixels)	mAPval
> 50-95	Speed
> CPU ONNX
> (ms)	Speed
> GPU TensorRT
> (ms)	params
> (M)	FLOPs
> (B)
> yolov8n-sim.onnx	640	-	416.39 ± 87.44 ms	0.00 ± 0.00 ms	0.0	0.0
> yolov8n-slim.onnx	640	-	404.46 ± 52.55 ms	0.00 ± 0.00 ms	0.0	0.0
> yolov8n.onnx	640	-	376.98 ± 72.32 ms	0.00 ± 0.00 ms	0.0	0.0
> ### ubuntu-latest runner
> Model	size
> (pixels)	mAPval
> 50-95	Speed
> CPU ONNX
> (ms)	Speed
> GPU TensorRT
> (ms)	params
> (M)	FLOPs
> (B)
> yolov8n-sim.onnx	640	-	236.14 ± 33.50 ms	0.00 ± 0.00 ms	0.0	0.0
> yolov8n-slim.onnx	640	-	235.96 ± 30.32 ms	0.00 ± 0.00 ms	0.0	0.0
> yolov8n.onnx	640	-	234.92 ± 36.19 ms	0.00 ± 0.00 ms	0.0	0.0
> ### windows-latest runner
> too slow...

@glenn-jocher Thanks for sharing your results, so is this pr ready to be merged... Maybe the user can choose which one to use.

**Comment by Kayzwer** [comment]
> > @Laughing-q @Kayzwer @inisis results with `dynamic=True`
> > 
> > ### macos-14 M1 Arm64 runner
> > Model	size
> > (pixels)	mAPval
> > 50-95	Speed
> > CPU ONNX
> > (ms)	Speed
> > GPU TensorRT
> > (ms)	params
> > (M)	FLOPs
> > (B)
> > yolov8n-sim.onnx	640	-	416.39 ± 87.44 ms	0.00 ± 0.00 ms	0.0	0.0
> > yolov8n-slim.onnx	640	-	404.46 ± 52.55 ms	0.00 ± 0.00 ms	0.0	0.0
> > yolov8n.onnx	640	-	376.98 ± 72.32 ms	0.00 ± 0.00 ms	0.0	0.0
> > ### ubuntu-latest runner
> > Model	size
> > (pixels)	mAPval
> > 50-95	Speed
> > CPU ONNX
> > (ms)	Speed
> > GPU TensorRT
> > (ms)	params
> > (M)	FLOPs
> > (B)
> > yolov8n-sim.onnx	640	-	236.14 ± 33.50 ms	0.00 ± 0.00 ms	0.0	0.0
> > yolov8n-slim.onnx	640	-	235.96 ± 30.32 ms	0.00 ± 0.00 ms	0.0	0.0
> > yolov8n.onnx	640	-	234.92 ± 36.19 ms	0.00 ± 0.00 ms	0.0	0.0
> > ### windows-latest runner
> > too slow...
> 
> @glenn-jocher Thanks for sharing your results, so is this pr ready to be merged... Maybe the user can choose which one to use.

agree

**Comment by inisis** [comment]
> @Kayzwer @inisis I'm satisfied with the benchmarks here. It's unclear if there are super performance improvements, but I really like the package simplicity vs onnxsim that's not python native, requires cmake dependency for building install wheels etc, onnxslim is much simpler in that sense and should help with more robust installs across all the environments users run ultralytics in.
> 
> 
> 
> I'm replacing onnxsim with onnxslim now in this PR under the same `simplify` flag.

Hi @glenn-jocher personally I don't want to do comparison, it's up to you to make choice🤔. I'd rather keep both🫣

**Comment by glenn-jocher** [comment]
Hi @inisis, thanks for sharing your thoughts! We appreciate your input and understand the desire to maintain flexibility. The decision to streamline to `onnxslim` under the `simplify` flag is aimed at enhancing the installation process and ensuring consistency across various environments. However, we'll keep monitoring feedback and usage to ensure we meet the community's needs effectively. Your feedback is invaluable in this ongoing process! 🌟

**Comment by glenn-jocher** [comment]
@inisis @Kayzwer PR merged! Thank you for your contributions!

**Comment by lakshanthad** [comment]
Verified on RPi CI also and all ✅ :)
https://github.com/ultralytics/ultralytics/pull/13281

**Comment by inisis** [comment]
Hi @glenn-jocher should we apply this to other yolo repos like https://github.com/ultralytics/yolov5

**Comment by glenn-jocher** [comment]
Hi @inisis, great suggestion! It would be beneficial to maintain consistency across our repositories. Let's evaluate the integration on the YOLOv5 repo as well. I'll start by reviewing the current setup and testing to ensure a smooth transition. Thanks for pointing this out! 🚀

**Comment by inisis** [comment]
@glenn-jocher May I add you on linkedin, and this is [me ](https://www.linkedin.com/in/jin-yao-261986149/), I already sent an invitation

**Comment by glenn-jocher** [comment]
Hi @inisis,

Thank you for reaching out and for your interest in connecting on LinkedIn! I appreciate the invitation and will be sure to check it out. 😊

If you have any questions or need further assistance with Ultralytics projects, feel free to ask here. We're always happy to help and engage with the community!

**Pull request merged**
