### PR TITLE
Update NVIDIA Jetson Docs with JetPack 6

### PR DESCRIPTION
**Pull request by lakshanthad**
@glenn-jocher FYI

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated the NVIDIA Jetson documentation to support JetPack 6.0 and improved the installation instructions.

### 📊 Key Changes
- Added support for JetPack 6.0 across compatible Jetson devices.
- Introduced a JetPack version support table for different Jetson models.
- Provided Docker-based setup instructions for JetPack 4, 5, and 6.
- Updated manual installation steps for Ultralytics, PyTorch, Torchvision, and onnxruntime-gpu on JetPack 6.0.
- Clarified installation processes and fixed links in the documentation.

### 🎯 Purpose & Impact
- **Compatibility**: Ensures users can deploy Ultralytics on the latest JetPack 6.0 for enhanced performance on supported Jetson devices. 🚀
- **Ease of Setup**: Streamlines the setup process with clear Docker images and native installation guides for different JetPack versions. 🛠️
- **User Guidance**: Provides comprehensive instructions, making it easier for users to install and optimize YOLOv8 on their Jetson hardware. 📘

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@lakshanthad let's use markdown in the markdown files please:

|                    | JetPack 4 | JetPack 5 | JetPack 6 |
|--------------------|-----------|-----------|-----------|
| Jetson Nano        | ✅         | ❌         | ❌         |
| Jetson TX2         | ✅         | ❌         | ❌         |
| Jetson Xavier NX   | ✅         | ✅         | ❌         |
| Jetson AGX Xavier  | ✅         | ✅         | ❌         |
| Jetson AGX Orin    | ❌         | ✅         | ✅         |
| Jetson Orin NX     | ❌         | ✅         | ✅         |
| Jetson Orin Nano   | ❌         | ✅         | ✅         |

**Comment by glenn-jocher** [comment]
@lakshanthad you need to debug these failing Docs tests please. You've introduced broken links in this PR that you need to fix.

Screenshot 2024-08-05 at 02 18 15

**Comment by lakshanthad** [comment]
> @lakshanthad let's use markdown in the markdown files please:
> 
> JetPack 4	JetPack 5	JetPack 6
> Jetson Nano	✅	❌	❌
> Jetson TX2	✅	❌	❌
> Jetson Xavier NX	✅	✅	❌
> Jetson AGX Xavier	✅	✅	❌
> Jetson AGX Orin	❌	✅	✅
> Jetson Orin NX	❌	✅	✅
> Jetson Orin Nano	❌	✅	✅

Thank you. I will be aware of this next time @glenn-jocher

**Comment by lakshanthad** [comment]
@glenn-jocher broken links are fixed. Will keep an eye next time.

**Comment by glenn-jocher** [comment]
@lakshanthad great looks good now!

**Review by glenn-jocher — APPROVED** [review]

**Pull request merged**
