### PR TITLE
Update image resizing in `BaseDataset.load_image()` removes import

### PR DESCRIPTION
**Pull request by Burhan-Q**
Changed to use relative resizing with OpenCV instead of absolute resizing. Removes need for `math` import and removes extraneous calculation.

```diff
- w, h = (min(math.ceil(w0 * r), self.imgsz), min(math.ceil(h0 * r), self.imgsz))
- im = cv2.resize(im, (w, h), interpolation=cv2.INTER_LINEAR)
+ im = cv2.resize(im, None, None, fx=r, fy=r, interpolation=cv2.INTER_LINEAR)
```

Since `r` (ratio) is calculated using `max` of original image dimensions, `r` will always be minimal.

```py
r = self.imgsz / max(h0, w0)
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved image resizing logic in the Ultralytics YOLO data processing module.

### 📊 Key Changes
- Removed the use of `math.ceil` and specific size calculations when resizing images.
- Simplified the image resizing by directly scaling factors using the `cv2.resize` function.

### 🎯 Purpose & Impact
- **Simplification**: Streamlines the resizing code, making it easier to maintain and understand. 🛠️
- **Performance**: Potentially improves image processing speeds by eliminating redundant calculations. 🚀
- **Consistency**: Might lead to more consistent image scaling across various scenarios, improving model input consistency. 📈

### CODE REVIEW

**Comment by Burhan-Q** [comment]
Very curious! Benchmarks are failing with this change.

The `mAP50-95(M)` on all have dropped by $0.018$ but PyTorch has dropped $0.06$ for YOLOv8-seg

## On this PR Benchmarks (ubuntu-latest, 3.11, yolov8n)

```
Benchmarks complete for yolov8n-seg.pt on coco8-seg.yaml at imgsz=160 (291.15s)
                   Format Status❔  Size (MB)  metrics/mAP50-95(M)  Inference time (ms/im)     FPS
0                 PyTorch       ✅        6.7               0.2204                   24.11   41.47  <--
1             TorchScript       ✅       13.4               0.2803                   42.66   23.44
2                    ONNX       ✅       13.1               0.2803                    6.85  145.91
3                OpenVINO       ✅       13.2               0.2803                    6.42  155.72
4                TensorRT       ❌        0.0                  NaN                     NaN     NaN
5                  CoreML       ❎        6.6                  NaN                     NaN     NaN
6   TensorFlow SavedModel       ✅       32.8               0.2803                   71.96   13.90
7     TensorFlow GraphDef       ✅       13.1               0.2803                  104.17    9.60
8         TensorFlow Lite       ✅       13.1               0.2803                    9.67  103.45
9     TensorFlow Edge TPU       ❎        5.7                  NaN                     NaN     NaN
10          TensorFlow.js       ❎       13.2                  NaN                     NaN     NaN
11           PaddlePaddle       ✅       26.2               0.2803                   25.75   38.83
12                   NCNN       ✅       13.0               0.2803                    7.28  137.35
```

## On PR #14551 Benchmarks (ubuntu-latest, 3.11, yolov8n)

```
Benchmarks complete for yolov8n-seg.pt on coco8-seg.yaml at imgsz=160 (286.49s)
                   Format Status❔  Size (MB)  metrics/mAP50-95(M)  Inference time (ms/im)     FPS
0                 PyTorch       ✅        6.7               0.2868                   24.24   41.25
1             TorchScript       ✅       13.4               0.2984                   43.76   22.85
2                    ONNX       ✅       13.1               0.2984                    7.27  137.52
3                OpenVINO       ✅       13.2               0.2984                    6.38  156.65
4                TensorRT       ❌        0.0                  NaN                     NaN     NaN
5                  CoreML       ❎        6.6                  NaN                     NaN     NaN
6   TensorFlow SavedModel       ✅       32.8               0.2984                   72.38   13.82
7     TensorFlow GraphDef       ✅       13.1               0.2984                  110.95    9.01
8         TensorFlow Lite       ✅       13.1               0.2984                    9.52  105.09
9     TensorFlow Edge TPU       ❎        5.7                  NaN                     NaN     NaN
10          TensorFlow.js       ❎       13.2                  NaN                     NaN     NaN
11           PaddlePaddle       ✅       26.2               0.2984                   25.62   39.03
12                   NCNN       ✅       13.0               0.2984                    7.45  134.23
```

**Comment by Burhan-Q** [comment]
1 pixel difference in resizing, makes for quite the difference in the benchmark result. This result is not intuitive and it's not clear how 1 pixel would change the results so drastically.

```py
import math
from pathlib import Path

import cv2

imgsz = 160
imgs = Path("datasets/coco8/images").rglob("*.jpg")

for im in imgs:
    img = cv2.imread(im)
    img.shape
    h0,w0 = img.shape[:2]
    r = imgsz / max(h0,w0)
    cv2.resize(img, (min(math.ceil(w0 * r), imgsz), min(math.ceil(h0 * r), imgsz)), interpolation=cv2.INTER_LINEAR).shape
    cv2.resize(img, None, None, fx=r, fy=r, interpolation=cv2.INTER_LINEAR).shape
    print(_im)

>>> (480, 640, 3)    # original size
>>> (120, 160, 3)    # main resize
>>> (120, 160, 3)    # branch resize
>>> coco8/images/train/000000000009.jpg
>>> (426, 640, 3)
>>> (107, 160, 3)    # <-- different
>>> (106, 160, 3)
>>> coco8/images/train/000000000025.jpg
>>> (428, 640, 3)
>>> (107, 160, 3)
>>> (107, 160, 3)
>>> coco8/images/train/000000000030.jpg
>>> (425, 640, 3)
>>> (107, 160, 3)    # <-- different
>>> (106, 160, 3)
>>> coco8/images/train/000000000034.jpg
>>> (640, 481, 3)
>>> (160, 121, 3)
>>> (160, 120, 3)
>>> coco8/images/val/000000000036.jpg
>>> (478, 640, 3)
>>> (120, 160, 3)
>>> (120, 160, 3)
>>> coco8/images/val/000000000042.jpg
>>> (500, 381, 3)
>>> (160, 122, 3)
>>> (160, 122, 3)
>>> coco8/images/val/000000000049.jpg
>>> (488, 640, 3)
>>> (122, 160, 3)
>>> (122, 160, 3)
>>> coco8/images/val/000000000061.jpg
```

**Comment by Burhan-Q** [comment]
Testing on COCO validation (detect)

## Branch result
```
         Class     Images  Instances      Box(P          R      mAP50  mAP50-95)
           all       5000      36335      0.633      0.475      0.521      0.371
        person       2693      10777      0.753      0.673      0.745      0.514
           car        535       1918      0.648      0.515      0.562      0.364
           cat        184        202      0.776      0.824      0.855      0.653
    skateboard        127        179       0.72      0.603      0.664      0.455
        bottle        379       1013      0.608      0.384      0.453      0.297
          vase        137        274      0.586      0.449      0.452      0.322
    hair drier          9         11          1          0    0.00501    0.00384
    toothbrush         34         57      0.402      0.193      0.236      0.164
```

## Main Result

```
         Class     Images  Instances      Box(P          R      mAP50  mAP50-95)
           all       5000      36335      0.633      0.475      0.521      0.371
        person       2693      10777      0.754      0.673      0.745      0.514
           car        535       1918      0.646      0.515      0.561      0.364
           cat        184        202      0.776      0.824      0.856      0.652
    skateboard        127        179      0.721      0.608      0.663      0.451
        bottle        379       1013      0.612      0.387      0.454      0.298
          vase        137        274      0.588      0.453      0.453      0.321
    hair drier          9         11          1          0    0.00492    0.00377
    toothbrush         34         57      0.402      0.193      0.236      0.164
```

**Comment by glenn-jocher** [comment]
@Burhan-Q PR seems to be negatively impacting PyTorch model mAP, Benchmarks CI is failing.

**Comment by Burhan-Q** [comment]
Converted to draft. Leaving to continue testing when time permits. Will share learnings/findings here for future reference.

**Pull request closed without merging**
