### PR TITLE
simple simplify in models utils

### PR DESCRIPTION
**Pull request by Kayzwer**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR contains no code changes.

### 📊 Key Changes
- There are no modifications or updates in this PR.

### 🎯 Purpose & Impact
- No impact on the existing functionality or user experience.

### CODE REVIEW

**Comment by Kayzwer** [comment]
@glenn-jocher hey, check this out, I reduce the arithmetic operations in loss.py and ops.py

**Comment by glenn-jocher** [comment]
@Kayzwer thank you for your contribution! Reducing arithmetic operations in `loss.py` and `ops.py` can indeed enhance performance and maintainability. We'll review your changes to ensure they align with our optimization goals. If you haven't already, please verify that your modifications work with the latest package versions to ensure compatibility.

**Comment by Kayzwer** [comment]
@glenn-jocher please review this

**Comment by glenn-jocher** [comment]
Thank you for your contribution! We'll review your changes and get back to you shortly.

**Pull request closed without merging**
