### PR TITLE
Update CI to benchmark all models

### PR DESCRIPTION
**Pull request by glenn-jocher**
@AyushExel here's CI benchmarks for all model sizes

### Summary
🚀✅🆙

Updated CI workflow to test all YOLOv8 models. Added more values to the `model` matrix parameter in `.github/workflows/ci.yaml`.

> _`model` matrix grows_
> _testing all YOLOv8 variants_
> _autumn of CI_

### Walkthrough
* Expand the `model` matrix parameter in `.github/workflows/ci.yaml` to include all YOLOv8 variants ([link](https://github.com/ultralytics/ultralytics/pull/2662/files?diff=unified&w=0#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL67-R67))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Expanded model testing in CI workflows.

### 📊 Key Changes
- Updated the continuous integration (CI) configuration to test additional YOLOv8 models: `yolov8s`, `yolov8m`, `yolov8l`, and `yolov8x`.

### 🎯 Purpose & Impact
- **Broader Testing Coverage**: Ensures more YOLOv8 model variants are tested automatically, improving reliability across different model scales.
- **Enhanced Quality Assurance**: Helps catch potential issues earlier, ensuring a more robust and stable codebase for users. 🛡️

### CODE REVIEW

**Review by ambitious-octopus — COMMENTED** [review]
The PR is old now but the idea is interesting. At the moment we only CI-benchmark on yolov8n. What do you think @Burhan-Q @Laughing-q @lakshanthad ?

**Comment by Laughing-q** [comment]
@ambitious-octopus I feel like benchmarking yolov8n is enough to reflect the correctness of the model. Also I guess doing benchmark on all the sizes will slowdown our CI a lot?

**Comment by lakshanthad** [comment]
@ambitious-octopus agreed with @Laughing-q . I think we want to make the CIs finish as quickly as possible (unless we want to add something very important). Currently we even have `imgsz` set to 160 in our CIs.

**Comment by ambitious-octopus** [comment]
@lakshanthad @Laughing-q You've convinced me, I'm closing!

**Pull request closed without merging**
