### PR TITLE
`ultralytics 8.2.77` new `color_mode=instance` plot arg

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the image plotting features by adding a new option to specify the color mode for annotations.

### 📊 Key Changes
- **New `color_mode` Argument**: Introduced a `color_mode` parameter in the `plot()` function to specify the coloring scheme (`'instance'` or `'class'`).
- **Version Bump**: Incremented the module version from `8.2.76` to `8.2.77`.
- **Keypoint Plotting Update**: Updated keypoint plotting to support custom colors via `kpt_color` parameter.

### 🎯 Purpose & Impact
- **🚀 Enhanced Customization**: Users can now choose between coloring by instance or class, improving the visual differentiation in annotations.
- **🛠️ Improved Usability**: The addition of custom color support for keypoints offers more control over how keypoints are visualized, especially useful in complex visualizations.
- **🔄 Version Update**: The version bump ensures compatibility and signals the addition of new features to users.

Overall, these updates offer more flexibility and control over the annotation visualization, making it easier for users to interpret and customize their output images.

### CODE REVIEW

**Comment by Laughing-q** [comment]
Visualizations with `instance` argument:
```python
from ultralytics import YOLO, ASSETS

model = YOLO("yolov8n.pt")
model(source=ASSETS / "bus.jpg")[0].show(instance=True)
model = YOLO("yolov8n-seg.pt")
model(source=ASSETS / "bus.jpg")[0].show(instance=True)
model = YOLO("yolov8n-pose.pt")
model(source=ASSETS / "bus.jpg")[0].show(instance=True)
```
image
image
image

**Comment by RizwanMunawar** [comment]
Wow nice work @Laughing-q on this :)

**Comment by glenn-jocher** [comment]
@Laughing-q maybe it would be better to add a color_mode argument, this is more flexible for the future:

```markdown
| Argument     | Type            | Description                                                                | Default       |
| ------------ | --------------- | -------------------------------------------------------------------------- | ------------- |
| `conf`       | `bool`          | Include detection confidence scores.                                       | `True`        |
| `line_width` | `float`         | Line width of bounding boxes. Scales with image size if `None`.            | `None`        |
| `font_size`  | `float`         | Text font size. Scales with image size if `None`.                          | `None`        |
| `font`       | `str`           | Font name for text annotations.                                            | `'Arial.ttf'` |
| `pil`        | `bool`          | Return image as a PIL Image object.                                        | `False`       |
| `img`        | `numpy.ndarray` | Alternative image for plotting. Uses the original image if `None`.         | `None`        |
| `im_gpu`     | `torch.Tensor`  | GPU-accelerated image for faster mask plotting. Shape: (1, 3, 640, 640).   | `None`        |
| `kpt_radius` | `int`           | Radius for drawn keypoints.                                                | `5`           |
| `kpt_line`   | `bool`          | Connect keypoints with lines.                                              | `True`        |
| `labels`     | `bool`          | Include class labels in annotations.                                       | `True`        |
| `boxes`      | `bool`          | Overlay bounding boxes on the image.                                       | `True`        |
| `masks`      | `bool`          | Overlay masks on the image.                                                | `True`        |
| `probs`      | `bool`          | Include classification probabilities.                                      | `True`        |
| `show`       | `bool`          | Display the annotated image directly using the default image viewer.       | `False`       |
| `save`       | `bool`          | Save the annotated image to a file specified by `filename`.                | `False`       |
| `filename`   | `str`           | Path and name of the file to save the annotated image if `save` is `True`. | `None`        |
| `instance`   | `bool`          | Determine the plot color by instance rather than by category.              | `False`       |
| `color_mode` | `str` | Specify the color mode, e.g., 'instance' or 'class'. | `'class'` |
```

**Comment by Laughing-q** [comment]
@glenn-jocher Agree! I was thinking the same but just not sure about this, I figured a bool option would be less chance for users to pass wrong argument so I did this way. But I think you are right, I'll do the `color_mode` update tomorrow. :)

**Pull request merged**
