### PR TITLE
`ultralytics 8.3.17` accept spaces in CLI args

### PR DESCRIPTION
**Pull request by glenn-jocher**
@RizwanMunawar should help CLI issues

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced merging behavior for command-line arguments, especially those involving brackets.

### 📊 Key Changes
- Improved `merge_equals_args` function to handle values enclosed in brackets like `[]`, `()`, `{}`.
- Extended merging logic to accommodate complex argument patterns.

### 🎯 Purpose & Impact
- 🛠️ More robust parsing for command-line input, reducing errors.
- 📈 Supports advanced usage with multi-token values, benefiting both developers and users who script configurations.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @glenn-jocher, thank you for submitting a PR to the `ultralytics/ultralytics` repository! 🚀 This is an automated response, but rest assured, an Ultralytics engineer will review your submission soon. In the meantime, please check the following:

- ✅ **Define a Purpose**: Ensure your PR description clearly explains the purpose of the updates involving CLI brackets and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues).
- ✅ **Synchronize with Source**: Confirm your PR is in sync with the `main` branch of `ultralytics/ultralytics`. You can update it by clicking 'Update branch' or running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Ensure all Ultralytics [CI checks](https://docs.ultralytics.com/help/CI/) are passing. Address any failures if necessary.
- ✅ **Update Documentation**: Check if any related [documentation](https://docs.ultralytics.com) needs updates to align with your changes.
- ✅ **Add Tests**: Add or update tests if applicable to cover your changes and verify they all pass.
- ✅ **Sign the CLA**: If this is your first contribution, please sign our [CLA](https://docs.ultralytics.com/help/CLA/). You can do this by commenting "I have read the CLA Document and I sign the CLA."
- ✅ **Minimize Changes**: Limit your changes to the essential improvements around the merging behavior for the CLI brackets.

For additional information, refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to leave comments if you have any questions. Thanks for enhancing Ultralytics! 🌟

**Comment by glenn-jocher** [comment]
This one got super complicated, gonna set it aside for now.

**Comment by glenn-jocher** [comment]
BEFORE
Screenshot 2024-10-18 at 19 50 04

**Comment by glenn-jocher** [comment]
AFTER
Screenshot 2024-10-18 at 19 52 00

**Pull request merged**
