### PR TITLE
Fix tfjs exports for ARM64 Dockerfile

### PR DESCRIPTION
**Pull request by lakshanthad**
After this fix, all model exports except TensorRT, CoreML, and TF Edge TPU work for the Raspberry Pi Docker image

I have read the CLA Document and I hereby sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updating the Docker setup to enhance model export compatibility. 🚀

### 📊 Key Changes
- Modified Dockerfile to install additional dependencies for model exporting.
- Explicit installation of `onnxruntime` and a specific version of `numpy` to address compatibility issues.

### 🎯 Purpose & Impact
- **Purpose**: To ensure smoother model exporting to various formats (including TensorFlow.js) by fixing a known compatibility issue related to `numpy`.
- **Impact**: Users working with ARM64 architecture will experience more reliable model export operations, especially when dealing with TensorFlow.js. This update is crucial for maintaining compatibility and performance in model deployment. 🎉

### CODE REVIEW

**Comment by lakshanthad** [comment]
@glenn-jocher FYI

**Comment by lakshanthad** [comment]
@glenn-jocher please wait before merging. I have another push for this.

**Comment by glenn-jocher** [comment]
@lakshanthad ok! Let me know when it's ready. Nice commenting, helps explain the installation steps very well :)

**Comment by lakshanthad** [comment]
@glenn-jocher all good now

**Comment by glenn-jocher** [comment]
@lakshanthad awesome. PR merged!!

**Pull request merged**
