### PR TITLE
dill module support

### PR DESCRIPTION
**Pull request by vyskocj**
Replacing pickle with dill (if installed) to save model safer (see [https://github.com/ultralytics/ultralytics/issues/2668](https://github.com/ultralytics/ultralytics/issues/2668)).

### Summary
🐛🚀💬

Use `dill` module to save and load checkpoints with lambda functions. Fix bug in `trainer.py` that prevented loading checkpoints with `hyp` dictionary.

> _`dill` can save lambdas_
> _`pickle` fails to do so_
> _a bug fix for spring_

### Walkthrough
* Import `dill` module to save lambda functions in checkpoint ([link](https://github.com/ultralytics/ultralytics/pull/2697/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L417-R428))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved model serialization by integrating dill for saving lambda functions.

### 📊 Key Changes
- Integrated the use of `dill`, an advanced serialization library, as an alternative to `pickle`.
- Updated `torch.save` calls to use `dill` as the `pickle_module` if `dill` is available, impacting the saving of model checkpoints.
- Implemented these changes in both `trainer.py` and `torch_utils.py` for consistency and reliability in the serialization process.

### 🎯 Purpose & Impact
- **Purpose**: To enable the serialization (saving) of more complex objects, like lambda functions, which the default `pickle` module cannot handle.
- **Impact**: This change ensures that users can reliably save and load their models, including those with lambda functions, which could improve the usability of Ultralytics frameworks for more advanced use cases. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@vyskocj since this error is generated by wandb and not ultralytics, I'd recommend you raise a bug report on wandb and see if they can pursue a fix there.

Alternatively you can try a different logger like Comet, ClearML, MLFlow, etc. which all have great integrations with YOLOv8 also :)

**Comment by glenn-jocher** [comment]
Caltech 256

Screenshot 2023-05-18 at 21 44 31

**Comment by vyskocj** [comment]
I raised bug in wandb but even so I would recommend to integrate this improvement because that I found this issue with wandb (after I added a new hook to watch changes of model parameters and gradients during the training), it does not mean that the same issue will not happen by another user modification. Your code will be more stable and user friendly to guys like me, who do not want to reuse the existing models but want to modify the models structure and do not want to use the mmlab or detectron2 codes. The proposed change does not change behaviour and only if the user has installed the `dill` module, model saving via torch will be safer. It is on you, if you want to integrate this or not :) my code is currently running even with the added hook, so I am happy :)

**Comment by glenn-jocher** [comment]
@vyskocj got it.


@AyushExel what do you think of this? I haven't used `dill` but it seems to expand torch save to allow for more types without errors. It's got almost 1M daily downloads, so the package is mature, and this PR does not add it to dependencies.

**Comment by glenn-jocher** [comment]
@vyskocj we also have a torch.save() call is strip_optimizer() here that runs upon training completion. Perhaps it makes more sense to monkey patch torch.save() so that the dill module is used everywhere torch.save() is used?

Screenshot 2023-05-19 at 13 58 26

**Comment by vyskocj** [comment]
@glenn-jocher yes, you are right. Sorry, I found this line but was not sure what it is used for so I left it as is.

**Comment by AyushExel** [comment]
@vyskocj @glenn-jocher I think it's great as it's an optional addition. I find it a little strange that dill is imported as pickle even in the official usage of dill https://dill.readthedocs.io/en/latest/ . Doesn't this confuse users sometimes with the inbuilt pickle module from python?

**Comment by vyskocj** [comment]
@AyushExel I personally take it as standard python coding, especially since I saw this kind of use almost everywhere. It is not a problem to import it as "pickle_module" and be more programmer friendly. That is a good point.

**Comment by AyushExel** [comment]
@vyskocj yeah I think maybe something like `import dill as dill_pickle` or maybe even dill would be fine I guess

**Review by AyushExel — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@vyskocj I opened https://github.com/ultralytics/ultralytics/pull/2728 for this. It updates the torch.save functions in a single location, sometimes called monkey patching. Can you test this branch to see if this works for your use case?

**Comment by vyskocj** [comment]
I tried to run it and it seems that your torch_save function is not called, so it is not working to me

**Comment by glenn-jocher** [comment]
@vyskocj got it, thanks for the review! I've updated to fix the issues, can you try again?

**Pull request merged**
