### PR TITLE
Update link to CLI docs

### PR DESCRIPTION
**Pull request by jorislimonier**
The previous link was dead.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to README documentation link for CLI usage.

### 📊 Key Changes
- Modified the hyperlink pointing to the Command Line Interface (CLI) documentation

### 🎯 Purpose & Impact
- Ensures that users can find CLI usage examples more easily, improving accessibility to documentation 📚
- The updated link directs to a specific CLI usage section, potentially saving time for users looking for command examples ⌛
- No direct impact on software functionality, but contributes to better user experience 🌐

### CODE REVIEW

**Comment by jorislimonier** [comment]
I have read the CLA Document and I sign the CLA.

**Comment by jorislimonier** [comment]
recheck

**Comment by jorislimonier** [comment]
I have read the CLA Document and I sign the CLA

**Comment by jorislimonier** [comment]
recheck

**Comment by glenn-jocher** [comment]
@jorislimonier PR merged in check_links branch for merge into main today, thank you for your contributions!

**Comment by jorislimonier** [comment]
My pleasure!

**Comment by pderrenger** [comment]
@jorislimonier you're welcome! If you have any more questions or need further assistance with YOLOv8 or anything else, feel free to ask. Keep up the great work and happy coding!

**Pull request merged**
