### PR TITLE
Add gradio interactive object detection page

### PR DESCRIPTION
**Pull request by WangQvQ**
Hi there😸,

I've created a Pull Request for the Gradio page of ultralytics.  The new design is clean and user-friendly, and I believe it'll make a positive difference in the user experience.  If you think this improvement would benefit the project, would you mind considering merging the PR?

Thanks a bunch for your time and attention!

Snipaste_2024-01-24_12-39-35
Snipaste_2024-01-24_12-42-46
Snipaste_2024-01-24_12-43-18
Snipaste_2024-01-24_12-55-42

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing Gradio interface for easy YOLOv8 object detection in a user-friendly web application. 🎉

### 📊 Key Changes
- **New documentation added:** Instructions and code for setting up a Gradio interface with YOLOv8.
- **Gradio features highlighted:** Details on user-friendly interface, real-time adjustments, and broad accessibility.
- **Usage example provided:** Python code to create the Gradio interface for interactive object detection.

### 🎯 Purpose & Impact
- **Enhanced accessibility:** Non-technical users can now use YOLOv8 for object detection without coding knowledge.
- **Educational value:** An excellent tool for demonstrations and learning about object detection.
- **Rapid prototyping:** Users can quickly test different parameters and see immediate results, which can accelerate development and research.

### CODE REVIEW

**Comment by AyushExel** [comment]
Should we add it to examples folder instead?

**Comment by WangQvQ** [comment]
No, my code is brief enough for the user to "plug and play", and I think I can make the page more beautiful if I can add it to a folder, but it seems that the code will get complicated.

**Comment by glenn-jocher** [comment]
@WangQvQ hello 😸,

Thank you for your contribution and enthusiasm! We appreciate the effort you've put into enhancing the user experience with a Gradio interface. While we aim to keep the repository as streamlined as possible, we also recognize the value in making YOLOv8 more accessible.

We'll review your Pull Request closely and consider the balance between simplicity and added functionality. If the integration maintains the ease of use and doesn't overly complicate the codebase, it could indeed be a beneficial feature for the community.

Keep an eye on the PR for further updates and discussions. Your initiative is a testament to the collaborative spirit of the open-source community!

**Comment by glenn-jocher** [comment]
@WangQvQ @AyushExel merged into docs branch for further updates. Should be published to Docs later today or tomorrow. Thank you for your contributions!

**Pull request merged**
