### PR TITLE
`ultralytics 8.2.19` fix Conda CI relative import bug

### PR DESCRIPTION
**Pull request by Burhan-Q**
Related to #13005

Replaces relative import with absolute import in `tests/test_exports.py` to address CI issues.

- Changes the relative import statement `from . import MODEL, SOURCE` to an absolute import `from tests import MODEL, SOURCE`. This modification ensures compatibility with the CI process by avoiding relative import issues.

[Azure CI failure from conda-forge package](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=931639&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=986b1512-c876-5f92-0d81-ba851554a0a3&l=1078)
---

For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/ultralytics/ultralytics/issues/13005?shareId=d8094ac4-e0c7-427c-a03c-ba917b150fdd).

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactoring test imports for cleaner code and incrementing package version 🧼✨.

### 📊 Key Changes
- **Refactored Test Imports:** Replaced relative imports in test files with absolute imports from `tests` package for clarity and maintainability.
- **Version Update:** Incremented the package version from `8.2.18` to `8.2.19`.

### 🎯 Purpose & Impact
- **Cleaner Codebase:** The refactoring makes the test code cleaner and more straightforward, improving readability for developers and maintainability.
- **Preparation for New Features:** The version increment reflects changes and potentially sets the stage for new features or improvements in the next release.
- **User Experience:** While these changes are under the hood, they contribute to a more stable and reliable software, indirectly benefiting end-users by ensuring future additions and fixes are built on a clean, well-organized foundation. 🛠️🚀

### CODE REVIEW

**Comment by Burhan-Q** [comment]
[Most recent feedstock PR](https://github.com/conda-forge/ultralytics-feedstock/pull/197)

[Last version published 8.2.8 on May 3, 2024](https://anaconda.org/conda-forge/ultralytics/files)

**Comment by glenn-jocher** [comment]
@Burhan-Q yes, agree absolute imports are better, I think PEP also recommends this in most cases. 

But we also need **consistency** in the code, if you change one test_*.py file to absolute imports you should change all of them. 

Please apply the same change to the rest of the files and this should be good to go. Thanks!

**Comment by glenn-jocher** [comment]
> [Most recent feedstock PR](https://github.com/conda-forge/ultralytics-feedstock/pull/197)
> 
> [Last version published 8.2.8 on May 3, 2024](https://anaconda.org/conda-forge/ultralytics/files)

Ah good catch spotting this!

**Comment by Burhan-Q** [comment]
Not sure if it's need before merging, but I was thinking it would be good to double check a few of the slow tests. I can do this once I get to my desk.

**Comment by glenn-jocher** [comment]
@Burhan-Q no don't worry, I think the fast tests are using almost all of these imports so the change should be good to go. I've bumped the pip package number too so Conda should deploy a new version today also.

**Comment by glenn-jocher** [comment]
@Burhan-Q PR merged! Nice work :)

**Pull request merged**
