### PR TITLE
add a new solution, found illegal parking for city road ...

### PR DESCRIPTION
**Pull request by M4D-AI**
Hello everyone,

I am a computer vision enthusiast and also an engineer specializing in traffic algorithms. The Ultralytics community has been very inspiring in solving problems I encounter at work. Based on the community's solutions, I have made customized modifications to meet specific needs. As a way to give back to the community, I hope to share my experiences and contribute.

I have recently submitted a new solution aimed at addressing the issue of illegal parking in urban roads. This solution, based on the community’s computer vision algorithms, can quickly determine whether there are illegally parked vehicles within a specific area. Of course, you can also apply this solution on highways to check if there are vehicles stranded on the road, which is of great significance for road safety.

   _I have read the CLA Document and I sign the CLA_

> quick start
```
import cv2

from ultralytics import YOLO
from ultralytics.solutions.illegal_parking import IllegalParking

model = YOLO("yolov8n.pt")
names = model.model.names

cap = cv2.VideoCapture("video.mp4")
assert cap.isOpened(), "Error reading video file"
w, h, fps = (int(cap.get(x)) for x in (cv2.CAP_PROP_FRAME_WIDTH, cv2.CAP_PROP_FRAME_HEIGHT, cv2.CAP_PROP_FPS))

# Video writer
video_writer = cv2.VideoWriter("illegal_parking.mp4", cv2.VideoWriter_fourcc(*"mp4v"), fps, (w, h))

polygon_pts = [[(1500, 300), (1850, 300), (1850, 980), (1700, 900), (1500, 980)],
               [(500, 280), (1000, 280), (1000, 650), (500, 650)]]

# Init obj
obj = IllegalParking(
    polygon_coords=polygon_pts,
    names=names,
    view_img=False,
)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        print("Video frame is empty or video processing has been successfully completed.")
        break

    tracks = model.track(im0, persist=True, show=False, verbose=False)

    im0 = obj.found_illegal_parking(im0, tracks)
    video_writer.write(im0)

cap.release()
video_writer.release()
cv2.destroyAllWindows()

```
> Link Related Issues

Issues for illegal parking

   _I have read the CLA Document and I sign the CLA_

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added a new feature to detect and identify illegal parking in real-time video streams.

### 📊 Key Changes
- **New Script**: Introduced `illegal_parking.py` for detecting illegal parking.
- **Class Implementation**: Added `IllegalParking` class with methods for initialization, IoU calculation, track extraction, bounding box plotting, point-in-polygon checking, and illegal parking detection.
- **Real-Time Processing**: Integrated capabilities to process video frames and identify parked vehicles by tracking their movements over time.
- **Visualization**: Enhanced with support for annotated images showing illegal parking areas.

### 🎯 Purpose & Impact
- **Improved Surveillance**: Helps in better monitoring and management of parking areas by automatically identifying and flagging illegally parked vehicles.
- **User-Friendly Feedback**: Provides visual feedback through annotated images, making it easy to spot parking violations.
- **Customization**: Supports configuration of parking thresholds, polygon areas, and visualization settings to suit various applications.

### CODE REVIEW

**Comment by M4D-AI** [comment]
I have read the CLA Document and I sign the CLA

**Comment by RizwanMunawar** [comment]
@M4D-AI Hi, Thank you for the PR. 

We appreciate your valuable contribution and will review it in detail and provide our feedback soon.

Thanks and regards,
The Ultralytics Team

**Comment by M4D-AI** [comment]
> @M4D-AI Hi, Thank you for the PR.
> 
> We appreciate your valuable contribution and will review it in detail and provide our feedback soon.
> 
> Thanks and regards, The Ultralytics Team

image
Dear [RizwanMunawar](https://github.com/RizwanMunawar)
I tried searching for solutions to the problem, but was unable to resolve it correctly. This may be due to my unfamiliarity with Git operations. Could you provide some assistance?

**Comment by pderrenger** [comment]
Hi @M4D-AI,

Thank you for reaching out. Could you please provide more details about the specific issue you're encountering? This will help us better understand the problem and offer more targeted assistance. Additionally, ensure you are using the latest version of the Ultralytics package, as updates often resolve existing issues.

**Comment by M4D-AI** [comment]
> Hi @M4D-AI,
> 
> Thank you for reaching out. Could you please provide more details about the specific issue you're encountering? This will help us better understand the problem and offer more targeted assistance. Additionally, ensure you are using the latest version of the Ultralytics package, as updates often resolve existing issues.

Hi  [pderrenger](https://github.com/pderrenger),
Thanks for your help. There is  a workflow show "Some checks were not successful", and details is like images below,
image
image
it looks like no correctly Permission for github-actions[bot].and i dont know how to slove it. although I search this problem and tried to solve it.

**Comment by pderrenger** [comment]
Hi [pderrenger](https://github.com/pderrenger),

Thank you for providing the details. The issue seems to be related to GitHub Actions permissions. Please ensure that the GitHub Actions workflow has the necessary permissions to run. You can check this in your repository settings under "Actions" -> "General" and ensure that "Allow all actions and reusable workflows" is selected. Additionally, make sure that the workflow file is correctly configured and that there are no syntax errors. If the problem persists, updating to the latest version of the Ultralytics package might help resolve any underlying issues.

**Comment by M4D-AI** [comment]
1. The repository's Actions permissions are already set to Allow all actions and reusable workflows.
image

2. If I haven’t made any changes to the workflow configuration after forking the repository, it should work as expected without requiring any additional modifications, right?

3. The term "update" refers to clicking sync fork, and I have already done that.
image

I followed these steps to check, but the issue still isn't resolved. Is it possible that I didn't correctly implement these suggestions?

**Comment by pderrenger** [comment]
Thank you for the detailed information. Given that the Actions permissions are correctly set and you've synced your fork, the issue might be related to the specific changes or configurations in your forked repository. Please ensure that your fork is fully up-to-date with the upstream repository. Additionally, check if there are any discrepancies in the workflow files between your fork and the upstream repository. If the issue persists, try running the workflow locally to identify any potential errors. If you continue to face problems, please let us know, and we can further investigate.

**Comment by M4D-AI** [comment]
I found the configuration in the workflow`ci.yaml` file of the origin repo and my own repo, and checked whether they were consistent.
image
image

The results show that the two are consistent. The following is my verification method.

> a simple compare scripts
```
docs_my = """  Docs:
    # TODO: break this job out into it's own action with pull_request_target to allow changes to user forks
    if: github.repository == 'ultralytics/ultralytics'
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies
      - name: Install Dependencies
        run: pip install tqdm mkdocs-material "mkdocstrings[python]" mkdocs-jupyter mkdocs-redirects mkdocs-ultralytics-plugin
      - name: Update Docs Reference Section
        run: python docs/build_reference.py
      - name: Commit and Push Reference Section Changes
        run: |
          git pull origin ${{ github.head_ref || github.ref }}
          git add .
          git reset HEAD -- .github/workflows/  # workflow changes are not permitted with default token
          git config --global user.name "UltralyticsAssistant"
          git config --global user.email "web@ultralytics.com"
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update Ultralytics Docs Reference Section by https://ultralytics.com/actions"
            git push
          else
            echo "No changes to commit"
          fi
      - name: Build Docs and Check for Warnings
        run: python docs/build_docs.py
      - name: Commit and Push Docs changes
        continue-on-error: true
        if: always() && github.event_name == 'pull_request'
        run: |
          git pull origin ${{ github.head_ref || github.ref }}
          git add --update  # only add updated files
          git reset HEAD -- .github/workflows/  # workflow changes are not permitted with default token
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update Ultralytics Docs by https://ultralytics.com/actions"
            git push
          else
            echo "No changes to commit"
          fi"""

docs_origin = """  Docs:
    # TODO: break this job out into it's own action with pull_request_target to allow changes to user forks
    if: github.repository == 'ultralytics/ultralytics'
    runs-on: macos-14
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          ref: ${{ github.head_ref || github.ref }}
          fetch-depth: 0
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"
          cache: "pip" # caching pip dependencies
      - name: Install Dependencies
        run: pip install tqdm mkdocs-material "mkdocstrings[python]" mkdocs-jupyter mkdocs-redirects mkdocs-ultralytics-plugin
      - name: Update Docs Reference Section
        run: python docs/build_reference.py
      - name: Commit and Push Reference Section Changes
        run: |
          git pull origin ${{ github.head_ref || github.ref }}
          git add .
          git reset HEAD -- .github/workflows/  # workflow changes are not permitted with default token
          git config --global user.name "UltralyticsAssistant"
          git config --global user.email "web@ultralytics.com"
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update Ultralytics Docs Reference Section by https://ultralytics.com/actions"
            git push
          else
            echo "No changes to commit"
          fi
      - name: Build Docs and Check for Warnings
        run: python docs/build_docs.py
      - name: Commit and Push Docs changes
        continue-on-error: true
        if: always() && github.event_name == 'pull_request'
        run: |
          git pull origin ${{ github.head_ref || github.ref }}
          git add --update  # only add updated files
          git reset HEAD -- .github/workflows/  # workflow changes are not permitted with default token
          if ! git diff --staged --quiet; then
            git commit -m "Auto-update Ultralytics Docs by https://ultralytics.com/actions"
            git push
          else
            echo "No changes to commit"
          fi"""

print(f"length_my: {len(docs_my)} length_origin:{len(docs_origin)} is_equal:{docs_my==docs_origin}")

```
> run compare local
image

I then continued to execute `sync fork` and triggered the workflow, but the result was as expected, the same error as before.
image

In addition, does running the `workflow` operation locally refer to this? It automatically skips the `Docs` part. I don’t know how to avoid skipping it, or it’s because my local environment doesn’t support it.
image

This is my first time submitting a PR. I am not sure where the problem is because I rarely see the same problems as me in the PR records.

**Comment by pderrenger** [comment]
Thank you for the detailed information. It appears that the issue might be related to the permissions or tokens used in your workflow. Ensure that your forked repository has the necessary permissions and that the secrets (like `GITHUB_TOKEN`) are correctly configured. Additionally, try running the workflow locally using a tool like `act` to simulate GitHub Actions. This can help identify any environment-specific issues. If the problem persists, please verify that all dependencies are correctly installed and that there are no discrepancies in the environment setup.

**Comment by glenn-jocher** [comment]
Thank you for the detailed information. It appears the issue might be related to permissions or configuration settings. Please ensure your forked repository has the same GitHub Actions permissions as the original. If the problem persists, try re-forking the repository and reapplying your changes. If you continue to face issues, please let us know.

**Pull request closed without merging**
