### PR TITLE
`ultralytics 8.3.26` EdgeTPU Pose models fix

### LINKED ISSUE #17203: YOLOV8 Pose on Google Coral USB accelerator
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, I am trying to convert yolov8 pose model to EdgeTPU using yolo CLI.
I have successfully converted the model, everything works fine but not the full_integer_quant.tflite model.

I used the ultralytics code to infer the model, the int8 model work, but the full_integer_quant.tflite model return very bad result.
this is an example: 
test

This is the command I used to convert the model: `yolo export model=yolov8s-pose.pt format=edgetpu simplify=True imgsz=256 opset=17`
Thank you!

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated version to 8.3.26 with improved performance for pose estimation and compatibility fixes for various export formats.

### 📊 Key Changes
- **Version Update:** Incremented software version from 8.3.25 to 8.3.26.
- **Pose Task Adjustments:** Enhanced coordinate scaling for the pose task, ensuring better accuracy.
- **Export Compatibility:** Improved handling of keypoints for TFLite and EdgeTPU exports, adding numerical stability enhancements and specific fixes for NCNN.

### 🎯 Purpose & Impact
- **Improved Accuracy:** Enhancements in pose tasks ensure more precise pose estimation, beneficial in applications needing accurate human or animal movement tracking.
- **Export Flexibility:** Increased compatibility and stability with multiple export formats (TFLite, EdgeTPU, NCNN), making the model more versatile and easier to deploy across different platforms.
- **User Experience:** By addressing export bugs and performance tweaks, users gain smoother deployment processes and more reliable outputs in diverse use cases.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Laughing-q, thank you for submitting a pull request to the `ultralytics/ultralytics` repository! 🚀 This is an automated response to guide you through the review process, and an Ultralytics engineer will assist you soon.

Here's a checklist to help ensure a smooth review and integration of your changes:

- ✅ **Define a Purpose**: Please ensure your PR description clearly explains the purpose of your fix and links to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). It's great to provide context on how your changes enhance TFLite export capabilities and pose estimation.
- ✅ **Synchronize with Source**: Make sure your pull request is up-to-date with the `main` branch of `ultralytics/ultralytics`. You can update it by clicking 'Update branch' on GitHub or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: All Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks must pass. If you notice any failing checks, please resolve them before your PR can be merged.
- ✅ **Update Documentation**: If your changes involve new or modified features, please update the relevant [documentation](https://docs.ultralytics.com) to reflect these improvements.
- ✅ **Add Tests**: Where applicable, include or update tests to ensure your changes are fully covered. Ensure that all tests pass.
- ✅ **Sign the CLA**: If this is your first contribution, make sure you have signed the [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/) by adding a comment that says, "I have read the CLA Document and I sign the CLA."
- ✅ **Minimize Changes**: Concentrate your changes on the minimal necessary updates for this fix. As Bruce Lee said, "It is not daily increase but daily decrease, hack away the unessential."

If these tasks are completed, please tag the relevant reviewers or team members who can help move your pull request forward. If you have any doubts or need clarification, feel free to ask any questions in the comments. Thank you for contributing to Ultralytics' projects, and we appreciate your efforts! 💡🔧

**Comment by Laughing-q** [comment]
reproduce command:
```python
from ultralytics import YOLO

model = YOLO("yolov8s-pose.pt")
model.export(format="edgetpu", int8=True, imgsz=256)
model = YOLO("yolov8s-pose_saved_model/yolov8s-pose_full_integer_quant.tflite")
res = model.predict("ultralytics/assets/bus.jpg", imgsz=256, int8=True)
res[0].show()
```
main branch:
image

this PR:
image

**Comment by glenn-jocher** [comment]
@Laughing-q this is great work! I was looking at the YOLO11 exports on HUB and EdgeTPU Pose models were I think one of the only ones that consistently failed.

**Comment by glenn-jocher** [comment]
PR merged!

**Pull request merged**
