### PR TITLE
Add Python 3.12 compatibility

### PR DESCRIPTION
**Pull request by johnnynunez**
Working to compatibility 3.12

### CODE REVIEW

**Comment by johnnynunez** [comment]
Fixed:
https://github.com/apple/coremltools/pull/2143

**Comment by glenn-jocher** [comment]
@johnnynunez thanks for trying this!

@Burhan-Q opened this up a while ago at OpenVINO https://github.com/openvinotoolkit/openvino/issues/21560

@adrianboguszewski is there any way you could get the GitHub team to prioritize 3.12 support? OpenVINO is one of our constraints here for releasing `ultralytics` for Python 3.12

**Comment by glenn-jocher** [comment]
@johnnynunez maybe we could add conditional logic to skip OpenVINO benchmarks and tests for Python 3.12 environments? It would make sense to prioritize the release rather than wait for every export format to align also with 3.12 as not all users will employ every export format.

**Comment by johnnynunez** [comment]
> @johnnynunez maybe we could add conditional logic to skip OpenVINO benchmarks and tests for Python 3.12 environments? It would make sense to prioritize `ultralytics` 3.12 support rather than wait for every export format to align also with 3.12 as not all users will employ every export format.

We can do it. Only see that openvino has been merged the 3.12 support.
Coremltools must be skipped

**Comment by glenn-jocher** [comment]
@johnnynunez I've submitted fixes to tests to ignore CoreML and OpenVINO, but Benchmarks must also be ignored, and then some updates to pyproject.toml.

Strange that the CI is not running again on this PR, something is different here.

**Comment by johnnynunez** [comment]
@glenn-jocher openvino 2024 it will be soon https://github.com/openvinotoolkit/openvino/milestone/21

**Comment by johnnynunez** [comment]
What is clip library ? @glenn-jocher

**Comment by glenn-jocher** [comment]
@johnnynunez as the maintainer of the Ultralytics YOLOv8 repository, ensuring compatibility with Python 3.12 is an important task that involves several steps. Here's a general outline of the process:

1. **Review Python 3.12 Release Notes**: Start by reviewing the [Python 3.12 release notes](https://docs.python.org/3.12/whatsnew/3.12.html) to identify any new features, optimizations, or deprecated features that may affect the YOLOv8 codebase.

2. **Set Up a Python 3.12 Environment**: Create a new virtual environment with Python 3.12 to test the existing codebase. You can use `venv` or `conda` to manage your environments.

3. **Run Existing Tests**: Execute the current test suite with Python 3.12 to identify any immediate compatibility issues. Fix any failing tests by updating the code as needed.

4. **Update Dependencies**: Check if all dependencies are compatible with Python 3.12. Update `requirements.txt` or `setup.py` with versions of libraries that support Python 3.12.

5. **Manual Testing and Code Review**: Manually test the core functionalities of YOLOv8, such as training, validation, prediction, export, tracking, and benchmarking, to ensure they work as expected. Review the code for any deprecated Python features or patterns that need updating.

6. **Update CI/CD Pipelines**: Modify Continuous Integration (CI) and Continuous Deployment (CD) pipelines to include Python 3.12 in the testing matrix.

7. **Documentation**: Update the documentation to reflect the new compatibility with Python 3.12, including any changes in installation or usage instructions.

8. **Community Feedback**: Encourage the community to test the updated codebase with Python 3.12 and report any issues.

9. **Release**: Once all tests pass and no major issues are reported, officially release the new version of YOLOv8 with Python 3.12 support.

10. **Monitor Issues**: After the release, monitor the repository for any new issues related to Python 3.12 and address them promptly.

Remember to communicate these changes through the repository's `CHANGELOG`, release notes, and any other relevant communication channels to inform users of the new Python 3.12 compatibility.

**Pull request merged**
