### PR TITLE
Fix issue where settings yaml can be `None` in yolo/utils

### PR DESCRIPTION
**Pull request by Amjad50**
The issue happens when running ultralytics in multiprocessing scheme, for some reason, the other processes crash in that line.

This will also fix any possible issues with the file not being parsed correctly

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced robustness for settings configuration in YOLO utility functions.

### 📊 Key Changes
- Added a check to ensure `settings` is not None before comparing keys and types with defaults.
- Improved the settings initialization process to prevent potential errors when `settings` is `None`.

### 🎯 Purpose & Impact
- **Purpose**: Prevents crashes and unexpected behavior due to missing or improperly initialized settings when using YOLO utilities.
- **Impact**: Increases stability and reliability for users integrating YOLO utility functions into their projects by handling edge cases more gracefully. 🛠️🔍

### CODE REVIEW

**Comment by Amjad50** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@Amjad50 thanks for the PR! Can you please pair this with a bug report showing the problem and a way we can reproduce the potential bug? 

As the change is right now I don't understand the failure mode it is intended to address, so I can't judge the merits of changing the code here.

**Comment by Amjad50** [comment]
Hello @glenn-jocher , I didn't create an issue for my problem yet, but when I was looking for the error I found this issue https://github.com/ultralytics/ultralytics/issues/1323, the author just posted a code change directly into the site libraries.

I'm not able to reproduce the error when doing my multi-processing setup now for some reason.

But another way is to have an invalid `settings.yaml`

How to reproduce:
- create a python file with the line `import ultralytics`
- create empty file `$HOME/.config/Ultralytics/settings.yaml`  (for example, default config folder)
- run
- crash

**Comment by glenn-jocher** [comment]
Thank you @Amjad50 for providing the steps to reproduce the issue. It seems like the issue is related to an incorrect or invalid setting in `settings.yaml` causing the script to crash. It's always a good idea to make sure the configuration file is properly formatted and contains all the required settings. Additionally, it may be helpful to set up a proper error handling system to catch and log any errors that might occur during runtime, as this can help with debugging and troubleshooting.

**Comment by haimat** [comment]
> Thank you @Amjad50 for providing the steps to reproduce the issue. It seems like the issue is related to an incorrect or invalid setting in `settings.yaml` causing the script to crash. It's always a good idea to make sure the configuration file is properly formatted and contains all the required settings. Additionally, it may be helpful to set up a proper error handling system to catch and log any errors that might occur during runtime, as this can help with debugging and troubleshooting.

@glenn-jocher Is there a doc explaining all the possible configuration options fot the `settings.yaml` file?

**Comment by Amjad50** [comment]
The issue that the read yaml function will just return None if there is any issues with the file

**Comment by glenn-jocher** [comment]
@haimat yes, there is a documentation page for `settings.yaml` that explains its different sections and settings. You can find it on our website at https://docs.ultralytics.com/yolov5/configuration, which includes a description of each setting and what it does. It's important to note that if any errors occur in the `settings.yaml` file, such as missing or malformed settings, the program may crash or return `None`. Therefore, it's essential to carefully follow the configuration instructions to avoid issues with the file. It is also recommended to have proper error handling in place to catch and handle any errors that might occur at runtime.

**Comment by glenn-jocher** [comment]
@Amjad50 maybe a better solution would be to return an empty dictionary from yaml_load() rather than None?

**Comment by haimat** [comment]
> @haimat we don't have a docs page for settings (yet), simply `yolo settings` and `yolo settings reset` to view and reset these.

@glenn-jocher How do I know the purpose of each configuration option in that file --
for example, what does the `sync` option do in detail?

**Comment by glenn-jocher** [comment]
@haimat The `sync` setting in the `settings.yaml` file is used to specify whether or not to synchronize with cloud storage, including cloud providers like Google Drive, Azure Blob Storage, and others. If set to `True`, the program will attempt to synchronize with the specified cloud storage provider, while if set to `False`, the program will not attempt to synchronize with any cloud storage provider during runtime. It's important to note that enabling synchronization may require additional authentication and setup steps, depending on the cloud storage provider being used.

**Pull request merged**
