### PR TITLE
fix classify confusion matrix

### LINKED ISSUE #2016: Confusion matrix in classification not working properly!
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

Hi, I have been working new added feature confusion matrix for classification. and it seems always zero matrix!!

The issue:
I got this after running following cmd
```bash
yolo classify val data=/home/dev/avgit/defect_classification/dataset/T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS model="../../runs/classify/POT_T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS_Y8M_i512_b28/weights/best.pt"
Ultralytics YOLOv8.0.77 🚀 Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3080 Laptop GPU, 7982MiB)
YOLOv8m-cls summary (fused): 103 layers, 15765218 parameters, 0 gradients, 41.6 GFLOPs
               classes   top1_acc   top5_acc: 100%|██████████| 252/252 [00:16<00:00, 15.69it/s]
                   all      0.872          1
WARNING ⚠️ ConfusionMatrix plot failure: expected str, bytes or os.PathLike object, not NoneType
Speed: 0.2ms preprocess, 3.5ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to None
```
I have tried to add save_dir but I couldn't as follows
```bash
(av) dev@av2:~/avgit/defect_classification/code/ultralytics$ yolo classify val data=/home/dev/avgit/defect_classification/dataset/T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS model="../../runs/classify/POT_T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS_Y8M_i512_b28/weights/best.pt" save_dir="../../runs/classify
> ^C
(av) dev@av2:~/avgit/defect_classification/code/ultralytics$ yolo classify val data=/home/dev/avgit/defect_classification/dataset/T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS model="../../runs/classify/POT_T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS_Y8M_i512_b28/weights/best.pt" save_dir="../../runs/classify"
Traceback (most recent call last):
  File "/home/dev/.local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/dev/.local/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 335, in entrypoint
    check_cfg_mismatch(full_args_dict, overrides)
  File "/home/dev/.local/lib/python3.8/site-packages/ultralytics/yolo/cfg/__init__.py", line 178, in check_cfg_mismatch
    raise SyntaxError(string + CLI_HELP_MSG) from e
SyntaxError: 'save_dir' is not a valid YOLO argument. Similar arguments are i.e. ['save_crop=False', 'save=True', 'save_period=-1'].
```

And also save=True didn't help me :confused: 
```bash
(av) dev@av2:~/avgit/defect_classification/code/ultralytics$ yolo classify val data=/home/dev/avgit/defect_classification/dataset/T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS model="../../runs/classify/POT_T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS_Y8M_i512_b28/weights/best.pt" save=True
Ultralytics YOLOv8.0.77 🚀 Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3080 Laptop GPU, 7982MiB)
YOLOv8m-cls summary (fused): 103 layers, 15765218 parameters, 0 gradients, 41.6 GFLOPs
               classes   top1_acc   top5_acc: 100%|██████████| 252/252 [00:16<00:00, 15.62it/s]
                   all      0.872          1
WARNING ⚠️ ConfusionMatrix plot failure: expected str, bytes or os.PathLike object, not NoneType
Speed: 0.2ms preprocess, 3.5ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to None

```
After manually added this guy in code the confusion matrix is all zero
```python
class ClassificationValidator(BaseValidator):

    def __init__(self, dataloader=None, save_dir=None, pbar=None, args=None, _callbacks=None):
        super().__init__(dataloader, save_dir, pbar, args, _callbacks)
        self.args.task = 'classify'
        self.metrics = ClassifyMetrics()
        save_dir = "/home/dev/avgit/defect_classification/runs/classify/val"
        self.save_dir = save_dir
```
It seems it works if we add  self.print_results() after self.finalize_metrics() function in validator.py
```python
        stats = self.get_stats()
        self.check_stats(stats)
        self.print_results()
        print("11111111111111111 print_results")
        self.speed = dict(zip(self.speed.keys(), (x.t / len(self.dataloader.dataset) * 1E3 for x in dt)))
        self.finalize_metrics()
        print("2222222222222222222 print_results")
        self.print_results()
```
And the final output
```
(av) dev@av2:~/avgit/defect_classification/code/ultralytics$ yolo classify val data=/home/dev/avgit/defect_classification/dataset/T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS model="../../runs/classify/POT_T2W+PP+DDC2022+SU+AV+VAN++23MX-POT-A5XRD32C-CLS_Y8M_i512_b28/weights/best.pt"
Ultralytics YOLOv8.0.77 🚀 Python-3.8.16 torch-1.13.1+cu116 CUDA:0 (NVIDIA GeForce RTX 3080 Laptop GPU, 7982MiB)
YOLOv8m-cls summary (fused): 103 layers, 15765218 parameters, 0 gradients, 41.6 GFLOPs
               classes   top1_acc   top5_acc: 100%|██████████| 252/252 [00:15<00:00, 15.76it/s]
                   all      0.872          1
--------- self.matrix [[          0           0]
 [          0           0]]
11111111111111111 print_results
2222222222222222222 print_results
                   all      0.872          1
--------- self.matrix [[       1488         277]
 [        239        2023]]
Speed: 0.2ms preprocess, 3.5ms inference, 0.0ms loss, 0.0ms postprocess per image
Results saved to /home/dev/avgit/defect_classification/runs/classify/val
```

And now I have confusion matrix :+1: 

confusion_matrix

### Environment

```bash
(av) dev@av2:~/avgit/defect_classification/code/ultralytics$  pip list
Package                 Version              Editable project location
----------------------- -------------------- ------------------------------------------------------
absl-py                 1.4.0
albumentations          1.3.0
apturl                  0.5.2
bcrypt                  3.2.0
blinker                 1.4
Brlapi                  0.8.3
cachetools              5.3.0
certifi                 2022.12.7
chardet                 4.0.0
click                   8.0.3
colorama                0.4.4
coloredlogs             15.0.1
command-not-found       0.3
contourpy               1.0.7
coremltools             6.2
cryptography            3.4.8
cupshelpers             1.0
cycler                  0.11.0
dbus-python             1.2.18
defer                   1.0.6
distro                  1.7.0
distro-info             1.1build1
dnspython               2.1.0
duplicity               0.8.21
fasteners               0.14.1
flatbuffers             23.3.3
fonttools               4.38.0
future                  0.18.2
gitdb                   4.0.10
GitPython               3.1.31
google-auth             2.16.2
google-auth-oauthlib    0.4.6
gpg                     1.16.0-unknown
grpcio                  1.51.3
httplib2                0.20.2
humanfriendly           10.0
idna                    3.3
imageio                 2.26.0
importlib-metadata      4.6.4
importlib-resources     5.12.0
jeepney                 0.7.1
joblib                  1.2.0
keyring                 23.5.0
kiwisolver              1.4.4
language-selector       0.1
launchpadlib            1.10.16
lazr.restfulclient      0.14.4
lazr.uri                1.0.6
lazy_loader             0.1
lockfile                0.12.2
louis                   3.20.0
macaroonbakery          1.3.1
Mako                    1.1.3
Markdown                3.3.6
markdown-it-py          2.2.0
MarkupSafe              2.1.2
matplotlib              3.7.1
mdurl                   0.1.2
monotonic               1.6
more-itertools          8.10.0
mpmath                  1.3.0
natsort                 8.3.1
netifaces               0.11.0
networkx                3.0
numpy                   1.24.2
oauthlib                3.2.0
olefile                 0.46
onnx                    1.13.1
onnxruntime             1.14.1
onnxruntime-gpu         1.14.1
opencv-python           4.7.0.72
opencv-python-headless  4.7.0.72
packaging               23.0
pandas                  1.5.3
paramiko                2.9.3
pexpect                 4.8.0
Pillow                  9.4.0
pip                     22.0.2
prettytable             3.6.0
protobuf                3.20.3
psutil                  5.9.4
ptyprocess              0.7.0
pyasn1                  0.4.8
pyasn1-modules          0.2.8
pycairo                 1.20.1
pycups                  2.0.1
Pygments                2.14.0
PyGObject               3.42.1
PyJWT                   2.3.0
pymacaroons             0.13.0
PyNaCl                  1.5.0
pyparsing               2.4.7
pyRFC3339               1.1
python-apt              2.4.0+ubuntu1
python-dateutil         2.8.1
python-debian           0.1.43ubuntu1
pytz                    2022.1
PyWavelets              1.4.1
pyxdg                   0.27
PyYAML                  5.4.1
qudida                  0.0.4
reportlab               3.6.8
requests                2.25.1
requests-oauthlib       1.3.1
requests-toolbelt       0.9.1
rich                    13.3.2
rsa                     4.9
scikit-image            0.20.0
scikit-learn            1.1.2
scipy                   1.9.1
screen-resolution-extra 0.0.0
seaborn                 0.12.2
SecretStorage           3.3.1
sentry-sdk              1.16.0
setuptools              67.6.0
shapely                 2.0.1
six                     1.16.0
smmap                   5.0.0
ssh-import-id           5.11
sympy                   1.11.1
systemd-python          234
tensorboard             2.12.0
tensorboard-data-server 0.7.0
tensorboard-plugin-wit  1.8.1
thop                    0.1.1.post2209072238
threadpoolctl           3.1.0
tifffile                2023.2.28
torch                   1.13.1+cu116
torchaudio              0.13.1+cu116
torchvision             0.14.1+cu116
tqdm                    4.65.0
typing_extensions       4.5.0
ubuntu-advantage-tools  8001
ubuntu-drivers-common   0.0.0
ufw                     0.36.1
ultralytics             8.0.77               /home/dev/avgit/defect_classification/code/ultralytics
unattended-upgrades     0.1
urllib3                 1.26.14
usb-creator             0.3.7
wadllib                 1.3.6
wcwidth                 0.2.6
Werkzeug                2.2.3
wheel                   0.38.4
xdg                     5
xkit                    0.0.0
zipp                    3.15.0
```

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to classification validation in YOLOv8.

### 📊 Key Changes
- Removed redundant `self.save_dir` initialization in the constructor.
- Shifted the plotting of the confusion matrix inside `finalize_metrics()` method.

### 🎯 Purpose & Impact
- 🧹 **Code Cleanup:** The removal of the extra `self.save_dir` helps in keeping the codebase clean and more maintainable.
- 🖼️ **Plotting Logic Consolidation:** Moving the confusion matrix plotting to `finalize_metrics()` consolidates related logic in one place, making it easier to follow the code flow. This ensures that the creation of visual aids to understand model performance is done at the final step of metrics calculation, which is a logical place for such an operation. Users can expect to see their model's performance visualized (if enabled) after all evaluations are complete.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q looks good!

**Comment by AbdulManaf12** [comment]
@glenn-jocher Hello there is still a problem in the confusion matrix so I have found a way to fix it (ultralytics/yolo/engine/validator.py):
`stats = self.get_stats()
        self.check_stats(stats)
        self.print_results()
        self.speed = dict(zip(self.speed.keys(), (x.t / len(self.dataloader.dataset) * 1E3 for x in dt)))
        self.finalize_metrics()
        self.print_results()
        self.run_callbacks('on_val_end')`

After `self.finalize_metrics()`, i have added one more line `self.print_results()` which plots the confusion matrix updated.

**Comment by glenn-jocher** [comment]
@AbdulManaf12 thank you for sharing your solution for updating the confusion matrix in Ultralytics YOLOv8! It's great to see the community actively contributing to the project. Adding `self.print_results()` after `self.finalize_metrics()` to update the confusion matrix sounds like a good strategy. Remember to thoroughly test the changes and to consider the impact on other parts of the codebase. Additionally, we always recommend contributing to open-source projects via pull requests, which will allow for a more thorough review of your changes and ensure they align with the project's goals and standards.

**Comment by AbdulManaf12** [comment]
Thank you for the warm appreciation, @glenn-jocher! I'm glad that my solution for updating the confusion matrix in Ultralytics YOLOv8 has been well-received by the community. I appreciate your suggestion of adding `self.print_results()` after `self.finalize_metrics()` to update the confusion matrix and will definitely consider this strategy while making further contributions to the project.

I completely agree with you that thoroughly testing any changes and considering their impact on other parts of the codebase is crucial before submitting a pull request. I have taken these factors into consideration while implementing my updates and have submitted a pull request for review.

Thanks again for your support and guidance throughout this process. I look forward to making more contributions to this wonderful open-source community!

**Comment by Laughing-q** [comment]
@AbdulManaf12 Hey thanks for the reminding! The way you provided could solve this solution that's because `process_cls_preds` is done in `finalize_metrics` but it's plotted in `print_results` but current code here `print_results` is called before `finalize_metrics`, so basically there's nothing in the confusion matrix while we do plotting in `print_results` before we call `finalize_metrics`.
Actually I think this should have been solved in this PR because I moved confusion-matrix-plotting in `finalize_metrics` and now `process_cls_preds` and plotting are all in `finalize_metrics`, everything is working properly to me.
Can you test again with the latest version of package?

BTW actually this PR has just been merged to `updates` branch at the moment you commentted so the updates in this PR has not been merged to main at that moment(but now it's been merged into main branch).

**Pull request merged**
