### PR TITLE
Update predict.md to add .obb result prop

### PR DESCRIPTION
**Pull request by mgcrea**
Was confused why the `result.boxes` was empty on my working model and it took discord help to figure out the `.obb` prop, might be worth it to document it there as well. Thanks for the great lib!

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing Oriented Bounding Boxes (OBB) in prediction results!

### 📊 Key Changes
- Added support for Oriented Bounding Boxes (OBB) alongside existing detection outputs like bounding boxes, segmentation masks, and keypoints.

### 🎯 Purpose & Impact
- **Enhanced Detection**: This update allows for more precise localization of objects, especially in images where objects are closely packed or overlap, enhancing overall detection accuracy. 🎯
- **Improved Usability**: Developers working with complex scenes or requiring detailed spatial recognition will find this feature particularly useful. 🛠️
- **Broader Applications**: The inclusion of OBBs opens up new possibilities for applications in fields requiring detailed object orientation, such as satellite imagery analysis, autonomous driving, and robotic manipulation. 🌍🚗🤖

### CODE REVIEW

**Comment by mgcrea** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Burhan-Q** [comment]
@mgcrea saw your conversation in the Discord. Thanks for opening this PR. Two small asks

1. Can you use OBB instead of obb? It keeps things consistent 
2. Additionally can you put the new line under the last line `probs`? This will keep the ordering consistent as well

Much appreciated! Once you make those changes quick, I can approve your PR and it'll be ready to go to the final step 🚀

**Comment by mgcrea** [comment]
@Burhan-Q done 😉

**Review by Burhan-Q — APPROVED** [review]
Thank you!

**Comment by glenn-jocher** [comment]
@mgcrea @Burhan-Q PR merged! Thank you for your contributions :)

**Pull request merged**
