### PR TITLE
Remove smart_inference_mode from exporter

### PR DESCRIPTION
**Pull request by ambitious-octopus**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
The PR modifies the export process in the Ultralytics engine by removing a specific decorator to simplify the code.

### 📊 Key Changes
- Removed the `@smart_inference_mode()` decorator from the exporter function in `exporter.py`.

### 🎯 Purpose & Impact
- **Simplification**: By removing the decorator, the function is likely simplified, making it easier for users to understand and maintain.
- **Potential Debugging Ease**: This change might help in diagnosing issues or improving the flexibility of the exported model handling.
  
This update will primarily impact users utilizing the export functionalities of the Ultralytics engine, possibly improving the debugging experience while preserving the core functionality. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@ambitious-octopus maybe this is redundant? If AutoBackend is already wrapped only in Predict calls check if those Predict calls use their own decorators.

**Comment by glenn-jocher** [comment]
@ambitious-octopus actually please review this for Val also, both Val and Predict will call autobackend so let's make sure we are using only a single "smart inference" decorator and that the deeper levels don't get multiple decorators.

**Comment by glenn-jocher** [comment]
@ambitious-octopus any update here?

**Comment by glenn-jocher** [comment]
I think if you put a breakpoint here for debugging you can view the stack trace and see if the decorate is applied multiple times.

**Comment by Laughing-q** [comment]
@glenn-jocher I think the very first intention that @ambitious-octopus opened this PR is to test if everything works properly without this `smart_inference_mode`, because we need do a calibration training for sony export with `int8=True` and the `smart_inference_mode` here is preventing the training as no trainable parameters under this decorator.

Last week when I was trying to clean up the [sony export PR](https://github.com/ultralytics/ultralytics/pull/14878), I found why we added this `smart_inference_mode` at the very first place, which is inherited from [a yolov5 PR](https://github.com/ultralytics/yolov5/pull/4479/files#diff-74fc7d08922278c1afa6f5b36d1450c965185dbcbdb77a99e432b0f4edaaade2) that introduced `@torch.no_grad()`, and it was to remove the trainable parameters when exporting `saved_model` format by using `tensorflow`(from this comment: https://github.com/ultralytics/yolov5/pull/4479#issuecomment-917436225). 
And eventually I removed this line in the sony export PR as we are using `onnx2tf` package to get the `saved_model` format and it seems like we don't have these trainable parameters anymore. :) 
@ambitious-octopus @glenn-jocher Perhaps we could close this PR now? and probably test and investigate if it's using `smart_inference_mode` multiple times with `Autobackend` in other PR?

**Review by ambitious-octopus — COMMENTED** [review]
Closing in favor of #14878

**Pull request closed without merging**
