### PR TITLE
Add object blurring & object cropping modules in Ultralytics docs

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher 

|                                                          Object Cropping                                                       |                                                           Object Blurring                                             |
|:---------------------------------------------------------------------------------------------------------------------------------------:|:------------------------------------------------------------------------------------------------------------------------------------------------------------:|
| Object cropping | Object Blurring |

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced privacy and extraction capabilities with object blurring and cropping guides for YOLOv8.

### 📊 Key Changes
- Added a new guide on object blurring, detailing how to apply a blurring effect to specific detected objects in images and videos for privacy enhancement.
- Included a comprehensive tutorial on object cropping, which explains isolating and extracting detected objects from images and videos for focused analysis.
- Updated the navigation structure in the `mkdocs.yml` to include the new guides under the Real-World Projects section.

### 🎯 Purpose & Impact
- **Privacy Concerns**: The object blurring guide addresses privacy by teaching users how to conceal sensitive information in visual media.
- **Selective Processing**: The object cropping tutorial empowers users to focus on specific objects of interest, saving computational resources, and enabling detailed individual analyses.
- **User-Accommodating Documentation**: Both additions enrich the documentation, providing step-by-step instructions to help users implement these features effectively, potentially attracting a wider audience to the YOLOv8 technology.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar AWESOME!!

**Comment by glenn-jocher** [comment]
@RizwanMunawar remember we need to update guides/index.html when we add new pages also. I can do this here.

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes I know :) forget to add

**Comment by glenn-jocher** [comment]
@RizwanMunawar ok I've placed these after Object Counting, so now we have Object Counting, Object Cropping and Object Blurring in a row :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar PR merged!

**Comment by RizwanMunawar** [comment]
@glenn-jocher awesome work 👏

**Pull request merged**
