### PR TITLE
Add OpenVino INT8 support for detection and segmentation models

### PR DESCRIPTION
**Pull request by yoloyash**
Hello, I have implemented support for exporting to INT8 in OpenVino format using the self.args.int8 flag. This feature currently applies to the Detection and Segmentation models. On an RTX4090, the nano model's inference time has been reduced by almost half compared to the FP16 OpenVino model. @glenn-jocher, could you kindly review the PR and let me know if any further additions are required? #2894 

### Summary
🚀🧠📄

Added a feature to export YOLO models to OpenVINO with INT8 precision using NNCF. Fixed a bug in loading dataset yaml file in `exporter.py`.

> _`NNCF` quantizes_
> _YOLO models with OpenVINO_
> _`yaml_load` calibrates_

### Walkthrough
* Import `yaml_load` function to load dataset yaml file for OpenVINO INT8 quantization ([link](https://github.com/ultralytics/ultralytics/pull/2908/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdL66-R66))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated CI pipeline, included new file types, and refined code and documentation.

### 📊 Key Changes
- Modified the CI pipeline to handle TFLite export exceptions without failing.
- Updated dependencies for CoreML models, specifying a newer version (`coremltools>=7.0.b1`).
- Introduced support for a new CoreML model file type, `.mlpackage`.
- Adjusted DataLoader functionalities and class documentation.
- Improved dataset validation to include IOU matching between predictions and ground truth.
- Enhanced training by refining model benchmarks and export functionalities.

### 🎯 Purpose & Impact
- Ensuring the CI pipeline gracefully handles TFLite export issues promotes a stable development process.
- New CoreML dependency version addresses model exporting requirements, potentially offering new features or bug fixes.
- Adding the `.mlpackage` file type caters to evolving CoreML standards, ensuring compatibility and supporting newer iOS features.
- Refinements in data loading and class interfaces streamline usability for developers, making the system more robust and user-friendly.
- The incorporation of IOU matching logic into dataset validation allows for more accurate model performance assessments, which can lead to better model fine-tuning.
- Updates on model benchmarks and exports pave the way for more efficient model testing and deployment across various platforms, offering users a wider range of applications.

### CODE REVIEW

**Comment by yoloyash** [comment]
Hi @glenn-jocher, just wanted to give you a friendly reminder about the pending pull request. The changes made in this PR add support for INT8 quantization in openvino format for Detection and Segmentation models. We believe the code is in good shape and well-tested, but your expert eye can help us validate the work and catch any potential issues. If you could provide your feedback, it would be immensely helpful. Thanks for your time and contribution!

**Comment by glenn-jocher** [comment]
@yoloyash hi! Thank you for the reminder and for contributing to the YOLOv8 repository. I appreciate your efforts in adding support for INT8 quantization in Openvino format for Detection and Segmentation models. I will make sure to take a closer look at the pull request and provide my feedback soon. Keep up the good work!

**Comment by yoloyash** [comment]
> @yoloyash hi! Thank you for the reminder and for contributing to the YOLOv8 repository. I appreciate your efforts in adding support for INT8 quantization in Openvino format for Detection and Segmentation models. I will make sure to take a closer look at the pull request and provide my feedback soon. Keep up the good work!

Hello @glenn-jocher, I hope you're doing well amidst your busy schedule. I understand that you have many commitments, but I kindly request a moment of your time to review and merge the PR I submitted. I genuinely believe this feature will be incredibly helpful. Currently, converting the YOLOv8 OpenVino model to int8 requires a tedious process outlined in the OpenVino GitHub repository. By merging this PR, we can simplify the conversion process, making it more user-friendly. I'm confident that many users will find this feature valuable. I eagerly await your response regarding the merging of this PR. Thank you for considering my request.

**Comment by yoloyash** [comment]
@akashAD98 Currently, ultralytics package only converts the model to OpenVino format at FP16 [link](https://github.com/ultralytics/ultralytics/blob/HEAD/ultralytics/yolo/engine/exporter.py#L352). Correct me if I'm wrong but I couldn't find the option where I could convert the FP16 OV model to INT8 in the main branch of ultralytics. I have added the required code for it in my PR.

**Comment by varunjain3** [comment]
@yoloyash Hey Yash, I was wondering if you could help share some documentation on how I could export the model to int8 for Openvino? I tried reading your code, but seems like I'll need calibration dataset

**Comment by varunjain3** [comment]
Hey @yoloyash thanks for the quick response. Great work! I was also wondering if you think this quantization would work on the pose estimation model?

**Comment by yoloyash** [comment]
@varunjain3 Currently OpenVino has provided official support only for the segmentation and detection models [reference](https://github.com/openvinotoolkit/openvino_notebooks/blob/main/notebooks/230-yolov8-optimization/230-yolov8-optimization.ipynb). It might work for pose estimation models as well, but I haven't tested it yet.

**Comment by yoloyash** [comment]
Hello @glenn-jocher Did you get time to review the code?

**Comment by glenn-jocher** [comment]
@yoloyash hi there! Thank you for reaching out. I apologize for the delay in my response. I appreciate your patience. I assure you that I will review the code as soon as possible and provide my feedback. Thank you for your contribution and for being a part of the YOLOv8 repository.

**Comment by glenn-jocher** [comment]
@yoloyash hi there! Thank you for your interest in the INT8 quantization feature for YOLOv8. We appreciate your contribution and the value this feature brings to the OpenVino models. Our team is currently reviewing the PR and considering its inclusion in the repository. We understand the importance of simplifying the quantization process and improving the inference time. Rest assured, we will communicate any updates or decisions regarding the merging of this PR. Thank you for your patience and for being a valuable member of the YOLOv8 community.

**Pull request merged**
