### PR TITLE
support FastSAM directory inference and plot

### PR DESCRIPTION
**Pull request by HtwoOtwo**
### Summary
🔧🚀🎨

This pull request improves the `FastSAMPrompt` class for semantic image manipulation. It adds support for different source types, enhances the segmentation results, fixes bugs, and simplifies the code. It also uses `torch` for faster and more flexible image processing and plotting.

> _We face the doom of different sources_
> _We segment them with `FastSAMPrompt`_
> _We fix the bugs and simplify the code_
> _We torch the images and plot the results_

### Walkthrough
*  Modify `FastSAMPrompt` class to handle different sources and improve segmentation quality ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L11-R19), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L54-R77), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L89-R179), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L164-R216), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L200-R234), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L218-R250), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L240-R278), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L268-R309), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L288-R324), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L298-R338))
  * Add `source` argument to `__init__` method and use `results` attributes instead of `img_path` ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L11-R19))
  * Add `filter_masks` method to remove overlapping masks based on area and IoU ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L54-R77))
  * Iterate over `results` list and use `torch` for faster image processing in `plot` method ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L89-R179))
  * Use `torch` for faster computation and fix typo in `fast_show_mask` method ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L164-R216), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L200-R234))
  * Use `results` argument and raise error for invalid `source` in `_crop_image` method ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L218-R250))
  * Add optional calls to `filter_masks` and `segment_image` in `_crop_image` method ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438R260-R261), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438R268))
  * Use `results` argument and return modified `results` in `box_prompt`, `point_prompt`, `text_prompt`, and `everything_prompt` methods ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L240-R278), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L268-R309), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L288-R324), [link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L298-R338))
* Fix bug in `_get_bbox_from_mask` method by calculating bounding box dimensions from mask ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438R91-R92))
* Add comment to explain `check_requirements` call before importing `clip` ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L29-R26))
* Remove unused import of `pathlib.Path` ([link](https://github.com/ultralytics/ultralytics/pull/4621/files?diff=unified&w=0#diff-525486f27ba5eca08d7cfaca5bdb538fb7c4c7963005d75565cfd5912be42438L4))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved functionality and efficiency in FastSAMPrompt Class.

### 📊 Key Changes
- Replaced `img_path` with the more versatile `source` parameter in the `FastSAMPrompt` initializer.
- Refactored conditional statement that filters out masks below the size threshold to make code clearer.
- Added progress tracking with `tqdm` for plot generations.
- Changed contour visualization logic for better quality in plot outputs.
- Added error handling to prevent directories from being passed as invalid function sources.
- Code now saves plot images more robustly and closes figures to free memory.
- Enhanced box selection with `box_prompt` to consider object size.
- Masked image post-processing is now more consistent, and masks are stored efficiently.

### 🎯 Purpose & Impact
- 🔍 Generalize input source handling, improving the flexibility of the class.
- 📈 Enhance performance via cleaner code and progress bars for long-running tasks.
- 🖼️ Boost image plotting quality, leading to better output visuals for users.
- 🛠️ Ensure stable behavior by preventing unsupported input scenarios.
- 🧹 Improve memory management by closing unused figures, reducing the risk of resource depletion.
- 📐 Make box prompts smarter to improve mask selection based on size, impacting accuracy and usage.

### CODE REVIEW

**Comment by HtwoOtwo** [comment]
Dear author, I think FastSAMPrompt should support directory source input, I made some modifications for your reference.

**Comment by HtwoOtwo** [comment]
I have read the CLA Document and I sign the CLA

**Comment by HtwoOtwo** [comment]
> 

I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@HtwoOtwo **CLA Assistant Lite bot:** <br/>Thank you for your submission, we really appreciate it. Your CLA has been successfully signed! We'll check back shortly to make sure everything is correct and in order. In the meantime, you can check the status of your CLA [here](https://cla-assistant.io/).

**Comment by glenn-jocher** [comment]
recheck

**Comment by HtwoOtwo** [comment]
recheck

**Comment by HtwoOtwo** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I sign the CLA
> 
> **gezhi** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).You can retrigger this bot by commenting **recheck** in this Pull Request

**Comment by HtwoOtwo** [comment]
I have read the CLA Document and I sign the CLA

**Comment by HtwoOtwo** [comment]
recheck

**Comment by glenn-jocher** [comment]
**CLA Assistant Lite bot:** <br/> @HtwoOtwo, thank you for your submission. However, as per our records, you have not signed the CLA. Signing the CLA is important for us to be able to accept your contribution. You can sign the CLA by posting a Pull Request Comment in the same format as the one below.
   - - -
   I have read the CLA Document and I sign the CLA
   - - -
We appreciate your understanding and cooperation in this matter. Please let us know if you have any questions or need further assistance.

**Pull request closed without merging**
