### PR TITLE
Add YOLOv8 OpenVINO C++ inference example

### PR DESCRIPTION
**Pull request by rlggyp**
This PR adds a new example for performing inference using YOLOv8 in C++ with OpenVINO and OpenCV API. The example demonstrates how to load and run YOLOv8 models in various formats and precisions using OpenVINO, enhancing the usability and flexibility of YOLOv8 for C++ developers.

### Features:
- [x] Support for ONNX and OpenVINO IR model formats
- [x] Support for FP32, FP16, and INT8 precisions
- [x] Support for loading models with dynamic shape

### Checklist:
- [x] Tested on local environment
- [x] Tested on Ubuntu `18.04`, `20.04`, `22.04`

#### Running using OpenVINO model
image
#### Running using ONNX model
image

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
No changes were made in this PR.

### 📊 Key Changes
- None

### 🎯 Purpose & Impact
- This PR does not introduce any new functionality or changes. No impact on users.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@rlggyp thank you for your contribution! This new example for performing inference using YOLOv8 in C++ with OpenVINO and OpenCV API is a fantastic addition. It will undoubtedly enhance the usability and flexibility of YOLOv8 for C++ developers, especially with support for various model formats and precisions.

### Key Features:
- **Support for ONNX and OpenVINO IR model formats**: This broadens the range of models that can be used, making the example highly versatile.
- **Support for FP32, FP16, and INT8 precisions**: This allows users to choose the precision that best fits their performance and accuracy needs.
- **Support for loading models with dynamic shape**: This adds flexibility in handling different input sizes, which is crucial for many real-world applications.

### Checklist:
- **Tested on local environment**: Ensures that the example works as expected in a controlled setting.
- **Tested on Ubuntu `18.04`, `20.04`, `22.04`**: Verifies compatibility across multiple versions of a popular operating system.

### Screenshots:
The provided screenshots are a great way to visualize the example in action, showing the practical application of the code.

For anyone looking to get started with this example, make sure you have the latest versions of `torch` and `ultralytics` installed. If you encounter any issues, please provide a minimum reproducible code example so we can assist you better. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thanks again for your valuable contribution! If you have any further questions or need assistance, feel free to ask. 😊

**Comment by rlggyp** [comment]
@glenn-jocher Thank you for the positive feedback and for highlighting the key features of the example!

- Just to clarify, this example only requires the installation of OpenCV and OpenVINO, not torch or ultralytics.

If there's anything else you'd like me to address or if further adjustments are needed, please let me know. I’m happy to make any necessary changes.

Thanks again for your support! 😊

**Comment by glenn-jocher** [comment]
@rlggyp thank you for the clarification! It's great to know that the example only requires OpenCV and OpenVINO, which simplifies the setup for C++ developers.

If you have any further questions or need additional adjustments, feel free to reach out. We're here to help! 😊

**Comment by rlggyp** [comment]
Hello @glenn-jocher ,

I've made adjustments to the code following the Minimum Requirement Example (MRE). Can you help me by reviewing the changes in Pull Request #13839 

Thank you!

**Comment by glenn-jocher** [comment]
Hello @rlggyp,

Thank you for following the Minimum Reproducible Example (MRE) guidelines and for submitting Pull Request #13839. We appreciate your efforts in ensuring the code meets the required standards.

I'll review the changes in your PR shortly. In the meantime, please ensure that your code has been tested with the latest versions of `torch` and `ultralytics` to confirm that the issue persists. This helps us ensure compatibility and address any potential bugs effectively.

If you have any further questions or need additional assistance, feel free to ask. We're here to help! 😊

**Comment by rlggyp** [comment]
@glenn-jocher Thank you for responding

The example code doesn't use `torch` or `ultralytics`. Can you tell me how to test it with the newest versions of these? Would exporting new models with the latest torch and ultralytics be enough?

Thanks for your help!😊

**Comment by glenn-jocher** [comment]
Hello @rlggyp,

Thank you for your question and for your patience! 😊

To ensure compatibility and address any potential issues, you can indeed export new models using the latest versions of `torch` and `ultralytics`. Here’s a quick guide on how to do this:

1. **Update Packages**: First, make sure you have the latest versions of `torch` and `ultralytics` installed. You can update them using pip:
    ```bash
    pip install --upgrade torch ultralytics
    ```

2. **Export the Model**: Use the updated packages to export your model to the desired format (e.g., OpenVINO). Here’s an example in Python:
    ```python
    from ultralytics import YOLO

    # Load a YOLOv8n PyTorch model
    model = YOLO("yolov8n.pt")

    # Export the model to OpenVINO format
    model.export(format="openvino")
    ```

3. **Test with Example Code**: Once you have the exported model, you can use it with your C++ example code as planned.

This process ensures that the model is compatible with the latest updates and should help in identifying any issues.

If you encounter any specific problems during this process, please provide a minimum reproducible code example so we can assist you better. You can find more information on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Thank you for your cooperation, and feel free to reach out if you need further assistance!

**Pull request closed without merging**
