### PR TITLE
 Improve Home "Where to Start" Layout in Docs

### PR DESCRIPTION
**Pull request by jk4e**
Hi,

Redesigned "Where to Start" using [Card grid](https://squidfunk.github.io/mkdocs-material/reference/grids/) for better UX and easier future additions. Updated FAQ examples to clarify optional `TASK` argument and include `detect` explicitly for consistency. These changes aim to make the Home page clearer and more user-friendly.

Thanks! 🚀

New Layout of  "Where to Start" section:

grafik

For comparison, the current one:

grafik

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Revamped the documentation for a clearer and more engaging experience.

### 📊 Key Changes
- **Updated Documentation Format**: Refactored content with a grid card layout for improved readability and navigation.
- **Enhanced Descriptions**: Provided more detailed explanations of tasks and capabilities.
- **Command Clarifications**: Clarified command usage, including updates for task-specific training commands.

### 🎯 Purpose & Impact
- **User-Friendly Navigation**: The new layout and detailed descriptions help users find information quickly and easily. 📚
- **Improved Clarity**: By specifying task-specific commands, users can avoid confusion during model training. 🔍
- **Empowered Decision Making**: Additional licensing information aids users in understanding their options when working with Ultralytics' tools. 📝

### CODE REVIEW

**Review by ambitious-octopus — CHANGES_REQUESTED** [review]
Looks really nice, thanks @jk4e.
Two things:
1. Is it possible to make the cards clickable with a link bringing the user to the right page?
2. Is it possible to align the link at the bottom?
image

**Comment by jk4e** [comment]
@ambitious-octopus Thanks for your feedback and ideas. I will try to change the layout and get back to you. (may take a few days)  But I do not want to change too much from the Material for MkDocs references to keep it simple and maintainable for everyone.

**Comment by glenn-jocher** [comment]
@ambitious-octopus @jk4e there's another MkDocs tier that we aren't on with I think gives us access to some nicer features like this. We could also try to get on there, but I've been a bit confused about the deployment workflow there.
https://squidfunk.github.io/mkdocs-material/insiders/

**Comment by jk4e** [comment]
I did some research and testing. These are my results:
- @glenn-jocher I am a Material for MkDocs beginner. My opinion is that the insider version is not needed yet/here. This workflow will only introduce more complexity (e.g. Access management, GH Token, may be harder for community to build and PR to docs, different docs, …). I am a big fan of keeping it simple.
- @ambitious-octopus The alignment of the links I could achieve with a small fix. Making clickable cards with Material for MkDocs is possible (see [here](https://aws.github.io/copilot-cli/) in this example, but not an official feature (see [here](https://github.com/squidfunk/mkdocs-material/issues/6269)). (you have to create custom style see e.g. [here](https://github.com/aws/copilot-cli/blob/mainline/site/overrides/layouts/home.html)). That amount of code + more complexity I think is not really worth it.

I committed an improved version (V1).

## V1: Updated version looks like this (same UI behavior as [here](https://squidfunk.github.io/mkdocs-material/insiders/)):
grafik

## V2: This is an alternative version (same UI behavior as [here](https://squidfunk.github.io/mkdocs-material/setup/)):
```markdown
<div class="grid cards" markdown>
- :material-clock-fast: **[Getting Started]** – Install `ultralytics` with pip and get up and running in minutes to train a YOLO model
- :material-image: **[Predict]** – Predict on new images, videos and streams with YOLO
- :fontawesome-solid-brain: **[Train a Model]** – Train a new YOLO model on your own custom dataset from scratch or load and train on a pretrained model
- :material-magnify-expand: **[Explore Tasks]** – Discover YOLO tasks like detect, segment, classify, pose, OBB and track
- :rocket: **[Explore YOLO11 NEW]** – Discover Ultralytics' latest state-of-the-art YOLO11 models and their capabilities
- :material-scale-balance: **[Open Source, AGPL-3.0]** – Ultralytics offers two licensing options for YOLO: AGPL-3.0 License and Enterprise License
</div>
  [Getting Started]: quickstart.md
  [Predict]: modes/predict.md 
  [Train a Model]: modes/train.md
  [Explore Tasks]: tasks/index.md
  [Explore YOLO11 NEW]: models/yolo11.md
  [Open Source, AGPL-3.0]: https://www.ultralytics.com/license
```
grafik

## Clickable cards with a link

With the following two code snippets you can create clickable cards, but there are clear limitations in formatting. You cannot use markdown inside. To get a good result, you have to add custom styles, which is more complex, less maintainable, and also not as easy to understand as the built-in features you find examples and references in MkDocs docs.
```markdown
<div class="grid cards">
  <a href="#" class="card">Getting Started – Install ultralytics with pip and get up and running in minutes to train a YOLO model</a>
  <a href="#" class="card">Bar</a>
  <a href="#" class="card">Baz</a>
</div>
```
grafik

or 
```markdown
<div class="grid">
  <a href="#" class="md-button md-button--primary">Getting Started – Install ultralytics with pip and get up and running in minutes to train a YOLO model</a>
  <a href="#" class="md-button md-button--primary">Bar</a>
  <a href="#" class="md-button md-button--primary">Baz</a>
</div>
```
grafik


Please let me know what you think.

Thanks! 🚀

**Comment by glenn-jocher** [comment]
Thank you for your detailed feedback and suggestions. Keeping the layout simple and maintainable is indeed important. Your improvements and insights are valuable, and we'll consider them for future updates. If you have any further thoughts or questions, feel free to share.

**Comment by glenn-jocher** [comment]
@jk4e wow they both look great! We'll vote on the two designs at today's YOLO meeting and let you know!

**Comment by glenn-jocher** [comment]
@jk4e merging PR with the existing design, lets try this out!

**Pull request merged**
