### PR TITLE
Adding "classes" argument to segregate unwanted classes from pre-trained model inference.

### PR DESCRIPTION
**Pull request by Kamlesh364**
#### CLI

YOLOv8 may be used directly in the Command Line Interface (CLI) with a `yolo` command:

```bash
yolo predict model=yolov8n.pt source="https://ultralytics.com/images/bus.jpg" classes=[0,1,2,..]
```

#### Python

YOLOv8 may also be used directly in a Python environment, and accepts the
same [arguments](https://docs.ultralytics.com/config/) as in the CLI example above:

```python
from ultralytics import YOLO

# Load a model
model = YOLO("yolov8n.pt")  # load a pretrained model (recommended for training)

# Use the model
results = model.predict(source="https://ultralytics.com/images/bus.jpg", classes=[0,1,2,...])  # or
results = model(source="https://ultralytics.com/images/bus.jpg", classes=[0,1,2,...])   # predict on an image

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced filtering capabilities for object detection models by class.

### 📊 Key Changes
- Added a `classes` parameter in the default configuration file to specify which classes to filter during detection.
- Updated `predictor.py` to utilize the `classes` parameter during the postprocessing of predictions.
- Modified various prediction modules (`classify`, `detect`, `segment`) to handle the new `classes` filter during postprocessing.

### 🎯 Purpose & Impact
- **Purpose**: To give users the ability to specify which object classes should be included or excluded in the detection results. This is helpful when interest is only in specific classes.
- **Impact**: Users now have more control over their object detection output, which can lead to more tailored and efficient processing, especially in scenarios where only certain types of objects are relevant. This might improve both the usability and performance for a variety of applications. 🚀

### CODE REVIEW

**Comment by Kamlesh364** [comment]
recheck

**Comment by Kamlesh364** [comment]
recheck

**Comment by glenn-jocher** [comment]
@Kamlesh364 nice work! Minimal code, I like it.

**Comment by Kamlesh364** [comment]
> @Kamlesh364 nice work! Minimal code, I like it.

Thanks. @glenn-jocher

**Pull request merged**
