### PR TITLE
Update inference.cpp (bug)

### PR DESCRIPTION
**Pull request by umitkacar**
Use delete[] blob to prevent memory leaks.
Fix this variable: iParams.modelPath instead of  iParams.ModelPath

Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:

1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.

2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.

3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.

4. **Ultralytics Contributor License Agreement (CLA)**: To uphold the quality and integrity of our project, we require all contributors to sign the CLA. Please confirm your agreement by commenting below:

   _I have read the CLA Document and I hereby sign the CLA_

For more detailed guidance and best practices on contributing, refer to our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing). Your adherence to these guidelines ensures a faster and more effective review process.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to YOLOv8 ONNXRuntime C++ Inference Example

### 📊 Key Changes
- Corrected variable name for consistency (`iParams.ModelPath` to `iParams.modelPath`).
- Ensured proper array memory deallocation (`delete blob` to `delete[] blob`).

### 🎯 Purpose & Impact
- Improves code readability and adherence to naming conventions, leading to fewer errors.
- Prevents memory leaks by correctly deallocating memory for dynamically allocated arrays, contributing to better performance and stability.

### CODE REVIEW

**Comment by umitkacar** [comment]
I have read the CLA Document and I sign the CLA

**Review by AyushExel — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@umitkacar thank you for the PR!

**Comment by umitkacar** [comment]
Hopefully more PR will come!

Thank you too.

**Comment by glenn-jocher** [comment]
@umitkacar we're looking forward to it! Thanks for your support. 😊👍

**Pull request merged**
