### PR TITLE
Support for yolov8-pose model over Triton

### PR DESCRIPTION
**Pull request by hmurari**
### Summary
🕺🧠🛠️

The pull request adds support for pose models to the `AutoBackend` and `TritonRemoteModel` classes. It does this by adding and parsing the `names` and `kpt_shape` attributes, which are specific to pose models, in the files `ultralytics/nn/autobackend.py` and `ultralytics/utils/triton.py`.

> _`AutoBackend` grows_
> _Two new attributes for pose_
> _Winter of models_

### Walkthrough
*  Add support for pose models to `AutoBackend` and `TritonRemoteModel` classes ([link](https://github.com/ultralytics/ultralytics/pull/6477/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9R292-R295), [link](https://github.com/ultralytics/ultralytics/pull/6477/files?diff=unified&w=0#diff-7f656783461e04167c1f5b4a6a05ad9b68af1023cea3924da3233ad6430f2ec4R59-R65))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR appears to be a placeholder or administrative update with no code changes.

### 📊 Key Changes
- No code changes or updates are included in this PR.

### 🎯 Purpose & Impact
- As there are no code changes, there is no direct impact on the functionality or performance of the software. This could be a preparatory step for future updates or simply a maintenance task.
- Users will not experience any changes or updates from this PR directly.

### CODE REVIEW

**Comment by hmurari** [comment]
recheck

**Comment by glenn-jocher** [comment]
@hmurari thank you, this looks great! Can you please sign the CLA by writing this below? Thank you!


I have read the CLA Document and I sign the CLA

**Comment by hmurari** [comment]
I have read the CLA Document and I sign the CLA

**Comment by hmurari** [comment]
Recheck

**Comment by glenn-jocher** [comment]
@hmurari it appears that you have successfully signed the Contributor License Agreement (CLA). Your pull request for adding support for the YOLOv8-pose model over the Triton server seems to be a valuable contribution. If your changes align with our vision and pass all the necessary checks and reviews, the pull request can proceed towards merging. Thank you for your contribution to the Ultralytics YOLO community! 🌟

**Comment by glenn-jocher** [comment]
@hmurari was reviewing the PR. The names must be a dictionary with key: value from class_index: class_name. This is how we have it everywhere, i.e.:

Screenshot 2023-11-22 at 19 42 20

**Comment by hmurari** [comment]
Hello @glenn-jocher, thanks for the feedback. I have updated the PR while taking names as a dictionary with a key. Please let me know if you have any other comments.

This is an example triton config.pbtxt that was used for the pose model:

```
name: "yolov8m-pose"
platform: "onnxruntime_onnx"
max_batch_size: 0
input [
  {
    name: "images"
    data_type: TYPE_FP32
    dims: [1, 3, 640, 640 ]
  }
]
output [
  {
    name: "output0"
    data_type: TYPE_FP32
    dims: [1, 56, 8400]
    label_filename: "labels.txt"
  }
]
parameters: {
    key: "kpt_shape"
    value: {
        string_value: "[17, 3]"
    }
}
parameters: {
    key: "names"
    value: {
        string_value: "{0: 'person'}"
    }
}
```

**Comment by glenn-jocher** [comment]
@hmurari, I'm glad to hear that you've updated your pull request in alignment with the repository standards. If there are no additional comments or necessary changes highlighted by the reviewers and once all automated checks are passed successfully, a member of the core Ultralytics team will take a final look at your contribution and determine if it's ready for merging.

In the meantime, please make sure that:
1. Your branch is up to date with the base branch.
2. The PR passes all continuous integration tests.
3. You have resolved any merging conflicts that might have arisen.

If any other action is required from your side, we will let you know. Keep an eye on the pull request for any further requests for changes or updates from the reviewing team. Thank you again for your contribution to the improvement of YOLOv8! 🚀

**Comment by glenn-jocher** [comment]
@hmurari I removed the conversion of names to a list in the triton server class, but looking at this some more, shouldn't all of the metadata values simply be unpacked in triton server and converted into self.metadata? Then these could all be handled using the existing logic in autobackend here. Then Triton models would not be handled any differently than any other local ONNX model, which is ideal right?

https://github.com/ultralytics/ultralytics/blob/a5390de2f1091847b1036de9b11e82ca79772651/ultralytics/nn/autobackend.py#L301C15-L315

**Comment by hmurari** [comment]
Hi @glenn-jocher 
I wanted to confirm I have tested changes for `names` field being a dict, and it works seamlessly.

Regarding NVIDIA Triton to export APIs for accessing metadata: The only method they support is through parameters via `config.pbtxt` which is accessible through `triton_client.get_model_config()`. Even information like input and output shapes for the model is provided through config.pbtxt itself, instead of natively analyzing the model. They don't have a concept of a separate model metadata.yaml file, but instead ask everyone to go through config.pbtxt file itself. 

Here is link to their model configuration [document](https://github.com/triton-inference-server/server/blob/main/docs/user_guide/model_configuration.md#minimal-model-configuration), and here is one other recent issue they closed recommending folks to use config.pbtxt as a way to manage metadata for the models. [Example](https://github.com/triton-inference-server/server/issues/6529).

Please let me know if you need any other information about this and how to proceed further.

**Comment by glenn-jocher** [comment]
@hmurari, thank you for confirming the `names` field update. It's good to know it integrates well within the existing framework.

Regarding the model metadata handling with Triton, I appreciate your research and thorough explanation. It seems that adhering to the Triton standard of using `config.pbtxt` for metadata management is our viable option. Given that Triton encourages the use of the `config.pbtxt` for such purposes, we should align with that methodology to ensure interoperability and ease of use for our users working with Triton.

To proceed, let's implement a mechanism that extracts the necessary metadata from the `config.pbtxt` using `triton_client.get_model_config()` as you mentioned. This approach should work dynamically without requiring any API changes and maintain the current user experience.

If you feel confident in this approach and it aligns with our project goals, please integrate it with your pull request and inform us once the updated solution is ready for review. Your contribution is crucial for the community leveraging NVIDIA Triton with YOLOv8, and we're excited to see this feature progressing.

Keep us posted on your developments. If you have any questions or need further clarification, don't hesitate to ask. Thank you once again for your dedication and contribution! 🌟👍

**Comment by hmurari** [comment]
Thanks @glenn-jocher for your response. From my side, I have tested and confirm the following. 

1. Pose scenario works with yolov5s-pose, yolov5m-pose, yolov5l-pose with triton.
2. Detect and Segment use-cases work as expected, I could find nothing that is broken because of this.
3. model.track is working as expected with all three types of models (pose + track, detect+track, segment+track).
4. PR is up to date with all the changes and ready to merge.

I look forward for the reviewing team to look at the PR again - and I can help answer any questions, or make required changes according to their suggestions. Thank you!

**Comment by glenn-jocher** [comment]
That's fantastic to hear, @hmurari. It sounds like you've been thorough with your testing across various scenarios, ensuring the changes integrate well with the different model use-cases and the tracking functionality.

Since your PR is up-to-date and ready to merge, I'll alert the reviewing team to take another look. They'll review your final changes, and if everything checks out, they'll proceed with the merge process.

We appreciate your diligence and the extensive testing you've performed. Your contributions are valuable to maintaining the robustness and versatility of YOLOv8, and I'm sure the community will benefit from your efforts.

If the reviewing team has any questions or requires further changes, they will reach out via the PR comments. Otherwise, if all goes smoothly, your PR should be merged soon.

Thank you once again for your contribution and for keeping the standards of the project high. Your collaborative spirit is what makes the open-source community thrive! 🎉🙌

Keep an eye on the PR, and feel free to engage with any additional feedback or questions from the reviewers.

**Comment by hmurari** [comment]
Hi @glenn-jocher Any update on this merge request? Let me know if you need anything else from me.

**Comment by hmurari** [comment]
Hello @glenn-jocher 
Wanted to check if there was any update to this merge request? Thanks!

**Comment by glenn-jocher** [comment]
@hmurari happy New Year! 🎉 The reviewing team is still going through the merge request. We'll update you on the PR thread as soon as there's progress. Thanks for your patience!

**Comment by cesarandreslopez** [comment]
Would love to see this merged!

**Comment by glenn-jocher** [comment]
@cesarandreslopez thank you for your interest in YOLOv8 and its integration with Triton! 🚀

Currently, we are focused on ensuring that YOLOv8 models, including the pose estimation models, work seamlessly within the Ultralytics ecosystem. While we don't have specific documentation for Triton support for YOLOv8-pose at the moment, you can export YOLOv8 models to ONNX format using the `export` mode, which may then be used with Triton.

If you have any further questions or need assistance with exporting models, feel free to reach out. We're here to help!

**Comment by cesarandreslopez** [comment]
Understood, @glenn-jocher, I just wanted to state that the @hmurari suggestion here works perfectly for the Triton Yolo-pose, and it seems to be a simple enough pull by adding the params in the config.pbtxt file in triton and the modification suggested to autobackend and triton.py it works as intended. His suggestions are also standard to how triton expects it's configuration.

**Comment by glenn-jocher** [comment]
Thanks for the feedback! It's great to hear that @cesarandreslopez's approach aligns well with Triton's configuration standards and is working smoothly for YOLO-pose. We'll take a closer look at the suggested changes and consider them for integration. Your input is much appreciated! 🌟

**Comment by glenn-jocher** [comment]
@sketch16 hello! 🌈

Thanks for reaching out and sharing your approach! It looks like you've found a creative way to get around the empty parameters issue with `triton_client.get_model_config()` in the Triton server by manually updating the model's `__dict__`. This is a pretty neat solution! 

Just one quick tip: ensure that the keys and values you're adding (like `"names"` and `"kpt_shape"`) align with the expected structure and types for your YOLOv8 model to avoid any unexpected behavior during predictions.

If there's anything else we can assist you with or if you have further observations to share, feel free to drop a message. Happy coding! 🚀

**Pull request closed without merging**
