### PR TITLE
Fix `torch.amp` has no attribute `GradScaler`

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary 
Simplified the handling of gradient scaling in the training code.

### 📊 Key Changes
- Removed the check for `TORCH_1_13`.
- Unified the initialization of `GradScaler` to always use `torch.cuda.amp.GradScaler`.

### 🎯 Purpose & Impact
- **Purpose**: To streamline the code by removing version-specific checks.
- **Impact**: Easier maintenance and fewer conditional checks, making the code cleaner. This has no direct impact on functionality for end-users but improves code readability and maintainability.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher I encountered the error while trying to train a model. It seems like related to https://github.com/ultralytics/ultralytics/pull/14633
pic-240724-1303-40

**Comment by glenn-jocher** [comment]
@Laughing-q oh that's strange. This is meant to fix this warning that shows up without this, i.e. from this PR:

Screenshot 2024-07-24 at 09 27 32

**Comment by Laughing-q** [comment]
@glenn-jocher I see, maybe it's because of the latest 2.4.0 pytorch, and they might not update the docs yet.
Also why the warning appears only in test_yolov10, I mean there are other training in our tests right?

**Comment by djdll** [comment]
我在yolo classify train 中必须amp=false才可以进行训练

**Comment by pderrenger** [comment]
感谢您的反馈。请确保您使用的是最新版本的Ultralytics软件包。如果问题仍然存在，请提供更多详细信息以便我们进一步调查。

**Comment by djdll** [comment]
@pderrenger   ```
File "/home/dujiang/miniconda3/envs/yolov8/lib/python3.10/site-packages/ultralytics/engine/trainer.py", line 270, in _setup_train
    torch.amp.GradScaler("cuda", enabled=self.amp)
AttributeError: module 'torch.amp' has no attribute 'GradScaler'
```
ultralytics        8.2.64  torch              2.1.0
torch.amp=>改为torch.cuda.amp
```
    self._scale = torch.full((), self._init_scale, dtype=torch.float32, device=dev)
TypeError: full() received an invalid combination of arguments - got (tuple, str, device=torch.device, dtype=torch.dtype), but expected one of:
 * (tuple of ints size, Number fill_value, *, tuple of names names, torch.dtype dtype, torch.layout layout, torch.device device, 
bool pin_memory, bool requires_grad)
 * (tuple of ints size, Number fill_value, *, Tensor out, torch.dtype dtype, torch.layout layout, torch.device device, bool pin_memory, bool requires_grad)
```
amp=false train正常无报错

**Comment by pderrenger** [comment]
@djdll thank you for reporting this issue. It appears that the error is related to the use of `torch.amp.GradScaler` in your environment. This should be `torch.cuda.amp.GradScaler`. Please ensure you are using the latest versions of both the Ultralytics package and PyTorch. If the issue persists, try setting `amp=False` as a temporary workaround. Let us know if you continue to experience problems after these steps.

**Comment by djdll** [comment]
@pderrenger thank you ,upgrading to the latest version of torch fixed the issue.torch==2.4.0

**Comment by pderrenger** [comment]
@djdll great to hear that upgrading to the latest version of PyTorch resolved the issue! If you encounter any further problems or have additional questions, feel free to reach out. Happy training!

**Pull request merged**
