### PR TITLE
Enhanced tracking and counting in 'object_counter.py'

### PR DESCRIPTION
**Pull request by VM8198**
Thank you 🙏 for your contribution to [Ultralytics](https://ultralytics.com) 🚀! Your effort in enhancing our repositories is greatly appreciated. To streamline the process and assist us in integrating your Pull Request (PR) effectively, please follow these steps:

1. **Check for Existing Contributions**: Before submitting, kindly explore existing PRs to ensure your contribution is unique and complementary.

2. **Link Related Issues**: If your PR addresses an open issue, please link it in your submission. This helps us better understand the context and impact of your contribution.

3. **Elaborate Your Changes**: Clearly articulate the purpose of your PR. Whether it's a bug fix or a new feature, a detailed description aids in a smoother integration process.

4. **Ultralytics Contributor License Agreement (CLA)**: To uphold the quality and integrity of our project, we require all contributors to sign the CLA. Please confirm your agreement by commenting below:

    _I have read the CLA Document and I hereby sign the CLA_

For more detailed guidance and best practices on contributing, refer to our ✅ [Contributing Guide](https://docs.ultralytics.com/help/contributing). Your adherence to these guidelines ensures a faster and more effective review process.

Object counting is updated based on the track history. based on the tracking history, the counting is getting increased. So, if the detected object is tracked more than 1 time in the region, than only the counter will get increased.  

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved object counting accuracy in Ultralytics' tracking software ✨

### 📊 Key Changes
- Added a check to consider the previous position of an object when counting.
- Updated the counting logic to use the change in position relative to the counting region's centroid.
- Ensured that an object is only counted once it crosses the counting region, using both its current and previous positions.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: This change aims to increase the accuracy of object counting, especially in scenarios where objects move close to the defined counting region.
- 💥 **Impact**: Users will experience more reliable counting results, reducing errors like double-counting or missed counts due to position fluctuations near the counting boundaries.

### CODE REVIEW

**Comment by VM8198** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@VM8198 thanks for the PR!

@RizwanMunawar can you take a look?

**Comment by RizwanMunawar** [comment]
@VM8198, appreciate the pull request. I've reviewed the changes. Could you clarify your statement about 'if the detected object is tracked more than 1 time in the region, then only the counter will get increased'? Typically, shouldn't an object be counted the first time it touches the region or line?

**Comment by VM8198** [comment]
You are correct @RizwanMunawar but what happens some times if we take the example of person counting, the person did not enter fully into the region and move back from the middle at that time the count should not increase. Also, I've updated the condition for counting. What previously happening that only x coordinate value was getting compared. At some points this condition was also breaking.  I've faced both issues today while running this on a video. and after this changes I did not faced the issues and worked really well that's why I've raised a PR here.

**Comment by RizwanMunawar** [comment]
Thank you for the updates, @VM8198. I appreciate the concept of excluding people who immediately backtrack from the region or line. Great job, by the way :)

@glenn-jocher, I believe we should proceed with merging the pull request as it addresses two issues in the current implementation.
- Currently, objects are counted when they enter the region line. However, there are instances where the initial points of objects intersect with the region area, but the objects then move away from the region. This pull request aims to resolve this issue.

**Comment by glenn-jocher** [comment]
@VM8198 PR merged, thank you for your contributions!

**Pull request merged**
