### PR TITLE
Fix `file_name` in `save_crop`

### LINKED ISSUE #17497: Save_crop method from Results with default params results in double file extension
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.


### Ultralytics YOLO Component

Predict

### Bug

Save_crop method in the Results object already adds file extension to the saved image (.jpg) and default value is set as 'im.jpg' so when using default behaviour we get a file named **"im.jpg.jpg"**
With this few examples
`results[0].save_crop(save_dir='../out')`
`results[0].save_crop(save_dir='../out', file_name='img.png')`
`results[0].save_crop(save_dir='../out', file_name='img')`
Here are the outputs in a File Explorer, only one without double extension is when you add file_name without any extension
![image](https://github.com/user-attachments/assets/873bb127-ca4e-439d-8f74-8aece55fd3fa)


### Environment

Setup complete ✅ (8 CPUs, 15.9 GB RAM, 477.1/931.5 GB disk) 

OS                  Windows-10-10.0.17763-SP0
Environment         Windows
Python              3.10.15
Install             pip
RAM                 15.94 GB
Disk                477.1/931.5 GB
CPU                 Intel Core(TM) i7-9700 3.00GHz
CPU count           8
GPU                 NVIDIA GeForce GTX 1660, 6144MiB
GPU count           1
CUDA                11.8

numpy               ✅ 1.26.3>=1.23.0                                                                                                                                                                                               
matplotlib          ✅ 3.9.2>=3.3.0 
opencv-python       ✅ 4.10.0.84>=4.6.0                                                                                                                                                                                             
pillow              ✅ 10.2.0>=7.1.2                                                                                                                                                                                                
pyyaml              ✅ 6.0.2>=5.3.1                                                                                                                                                                                                 
requests            ✅ 2.32.3>=2.23.0                                                                                                                                                                                               
scipy               ✅ 1.14.1>=1.4.1 
torch               ✅ 2.5.1+cu118>=1.8.0                                                                                                                                                                                           
torchvision         ✅ 0.20.1+cu118>=0.9.0                                                                                                                                                                                          
tqdm                ✅ 4.67.0>=4.64.0                                                                                                                                                                                               
psutil              ✅ 6.1.0                                                                                                                                                                                                        
py-cpuinfo          ✅ 9.0.0                                                                                                                                                                                                        
pandas              ✅ 2.2.3>=1.1.4                                                                                                                                                                                                 
seaborn             ✅ 0.13.2>=0.11.0                                                                                                                                                                                               
ultralytics-thop    ✅ 2.0.11>=2.0.0                                                                                                                                                                                                
numpy               ✅ 1.26.3<2.0.0; sys_platform == "darwin"                                                                                                                                                                       
torch               ✅ 2.5.1+cu118!=2.4.0,>=1.8.0; sys_platform == "win32"   

### Minimal Reproducible Example

```
model = YOLO('../model/yolov8s.pt')
results = model.predict(frame, conf=0.5)
results[0].save_crop(save_dir='../out')
```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by M3nxudo**
Fixed the default parameter for file_name in the save_crop method on line 721 (removed ".jpg" from it) since we already add the extension on line 753

Issue to fix #17497 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Corrected file saving method to ensure correct file extension handling during cropping operations.

### 📊 Key Changes
- Updated the code to correctly append a `.jpg` file extension to image files when saving cropped results.

### 🎯 Purpose & Impact
- **Improves File Handling**: Ensures that cropped images are saved with the correct `.jpg` extension, reducing potential errors in file management and improving workflow consistency.
- **Enhances User Experience**: Simplifies the saving process for users by automatically managing file extensions, preventing manual intervention or errors.

### CODE REVIEW

**Comment by M3nxudo** [comment]
I have read the CLA Document and I sign the CLA

**Comment by UltralyticsAssistant** [comment]
👋 Hello @M3nxudo, thank you for submitting a PR to the `ultralytics/ultralytics` repository! 🚀 Your efforts to enhance the file handling process are much appreciated. To facilitate a smooth merge process, please ensure the following:

- ✅ **Clarify the Purpose**: In your PR description, make sure to clearly explain the reason for your change and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues), such as the issue you mentioned: #17497.
- ✅ **Stay Updated**: Ensure your branch is up-to-date with the `ultralytics/ultralytics` `main` branch. You can update your branch by clicking the 'Update branch' button on GitHub or running `git pull` and `git merge main` in your local repository.
- ✅ **Verify CI Passes**: Double-check that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass. If there are any failing checks, attempt to resolve these issues.
- ✅ **Document Changes**: Please update the necessary [documentation](https://docs.ultralytics.com) to reflect your changes, if needed.
- ✅ **Test Coverage**: Add or update any relevant tests that cover your changes. Make sure all tests complete successfully.
- ✅ **Sign the CLA**: If this is your first contribution to Ultralytics, ensure you sign the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by adding a new comment stating, "I have read the CLA Document and I sign the CLA."
- ✅ **Keep It Concise**: Limit modifications to only what's necessary for your change. This helps maintain the focus and clarity of your contribution.

For additional guidance, please have a look at our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions or need further assistance, feel free to leave a comment here. This is an automated response, but rest assured, an Ultralytics engineer will review your PR soon. Thank you for contributing to Ultralytics! 🎉

**Comment by Y-T-G** [comment]
Did you test it? It doesn't seem like it would solve the issue.

**Comment by Y-T-G** [comment]
This line should be changed instead to use `.with_ext(".jpg")`

https://github.com/ultralytics/ultralytics/blob/2a55f96586b5941eb58041d7d4b78c41c5890ca8/ultralytics/engine/results.py#L753

**Comment by M3nxudo** [comment]
> This line should be changed instead to use `.with_suffix(".jpg")`
> 
> https://github.com/ultralytics/ultralytics/blob/2a55f96586b5941eb58041d7d4b78c41c5890ca8/ultralytics/engine/results.py#L753
> 
> That way, whether you pass with a filename with extension or without, it handles it accordingly.
> 
> ```python
> In [4]: Path("result.jpg").with_suffix(".jpg")
> Out[4]: PosixPath('result.jpg')
> 
> In [5]: Path("result").with_suffix(".jpg")
> Out[5]: PosixPath('result.jpg')
> ```

That for sure seems like a better option, i was only trying to fix the default parameter behaviour, but that is a more complete fix.

**Comment by M3nxudo** [comment]
> This line should be changed instead to use `.with_suffix(".jpg")`
> 
> https://github.com/ultralytics/ultralytics/blob/2a55f96586b5941eb58041d7d4b78c41c5890ca8/ultralytics/engine/results.py#L753
> 
> That way, whether you pass with a filename with extension or without, it handles it accordingly.
> 
> ```python
> In [4]: Path("result.jpg").with_suffix(".jpg")
> Out[4]: PosixPath('result.jpg')
> 
> In [5]: Path("result").with_suffix(".jpg")
> Out[5]: PosixPath('result.jpg')
> ```

Have been able to test locally with the complete fix and it now works for both the default parameters and user-input.
image
However now i'm not sure how to add to this PR the latest commit on my fork.

**Comment by glenn-jocher** [comment]
@M3nxudo thank you for updating the commit with the fix. Your approach using `.with_suffix(".jpg")` is a solid solution. The commit message looks good, but ensure it clearly describes the change and its purpose. If you need further assistance, feel free to ask!

**Comment by glenn-jocher** [comment]
@M3nxudo PR merged, thank you for your contributions.

**Pull request merged**
