### PR TITLE
`ultralytics 8.0.150` new Apple `*.mlpackage` export format

### LINKED ISSUE #2088: For an ML Program, extension must be .mlpackage (not .mlmodel)
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Ultralytics YOLOv8.0.81 🚀 Python-3.9.16 torch-2.0.0+cu118 CPU
Model summary (fused): 168 layers, 3014033 parameters, 0 gradients, 8.1 GFLOPs

PyTorch: starting from /content/drive/MyDrive/ColabNotebooks/bestGTSRB.pt with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 47, 8400) (5.9 MB)

CoreML: starting export with coremltools 6.3.0...
WARNING:coremltools:Tuple detected at graph output. This will be flattened in the converted model.
Converting PyTorch Frontend ==> MIL Ops: 100%|█████████▉| 523/525 [00:00<00:00, 3718.19 ops/s]
Running MIL frontend_pytorch pipeline: 100%|██████████| 5/5 [00:00<00:00, 202.43 passes/s]
Running MIL default pipeline: 100%|██████████| 56/56 [00:00<00:00, 141.97 passes/s]
Running MIL backend_neuralnetwork pipeline: 100%|██████████| 8/8 [00:00<00:00, 498.59 passes/s]
Translating MIL ==> NeuralNetwork Ops:  89%|████████▉ | 568/639 [00:00<00:00, 1626.08 ops/s]WARNING:coremltools:Const anchor_points was already added.
Translating MIL ==> NeuralNetwork Ops: 100%|██████████| 639/639 [00:00<00:00, 1769.38 ops/s]
CoreML Pipeline: starting pipeline with coremltools 6.3.0...
CoreML Pipeline: pipeline success
CoreML: export failure ❌ 6.4s: For an ML Program, extension must be .mlpackage (not .mlmodel)
[]

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

Cannot export model to CoreML format with nms

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
NOTE: This PR replaces https://github.com/ultralytics/ultralytics/pull/1791

### Summary
📁🆕🚀

Updated the code to support the new CoreML 5 format with `.mlpackage` files. Changed the file extension, name, and suffix for CoreML models in various files that handle export, inference, validation, backend selection, and benchmarking.

> _Sing, O Muse, of the swift and skillful coders_
> _Who changed the format of the CoreML models_
> _From `.mlmodel` to `.mlpackage`, the new and better way_
> _To support the features of the glorious CoreML 5._

### Walkthrough
*  Update file extension, name, and suffix for CoreML models from `.mlmodel` to `.mlpackage` to support CoreML 5 format ([link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL12-R12), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL38-R38), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL85-R85), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL472-R472), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-9fa2bf7f1273283680da3daeb8bae8e20cf8d477f838575796d2bf3b415bc534L23-R23), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L14-R14), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L71-R71), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-0aaacfa9e7ed54c1a6234cf053efec57da412817e8d8cf176f06e532359f06aaL17-R17))
*  Modify `exporter.py` to export models to CoreML 5 format using coremltools ([link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL472-R472))
*  Adjust `predictor.py` and `validator.py` to handle inference and validation with CoreML 5 models ([link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-9fa2bf7f1273283680da3daeb8bae8e20cf8d477f838575796d2bf3b415bc534L23-R23), [link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L14-R14))
*  Enhance `autobackend.py` to automatically select the best backend for CoreML 5 models ([link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L71-R71))
*  Update `benchmarks.py` to run benchmarks on CoreML 5 models ([link](https://github.com/ultralytics/ultralytics/pull/4043/files?diff=unified&w=0#diff-0aaacfa9e7ed54c1a6234cf053efec57da412817e8d8cf176f06e532359f06aaL17-R17))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Upgrade to CoreML 7.0 and enhance export functionality.

### 📊 Key Changes
- Updated dependencies to use CoreML tools `7.0.b1`, replacing the version range `>=6.0,<=6.2`.
- Changed the default CoreML export file extension from `.mlmodel` to `.mlpackage`.
- Enhanced the CoreML export process, including support for `mlmodel` legacy format if specified.
- Added `*.mlpackage` to `.gitignore`.
- Made sure `yolo export` command doesn't raise an exception by appending `|| true`.
- Updated documentation to reflect the new export file extension for CoreML.
- Included more aliases for export formats for improved user command flexibility.
- Adjusted package requirement checks to provide clearer feedback on missing components.

### 🎯 Purpose & Impact
- Provides users with up-to-date support for the latest CoreML tools for better performance and compatibility on Apple devices.
- Improves the export workflow by automatically adapting to the appropriate model packaging based on user inputs and system capabilities.
- Enhances developer experience by making the contributions and setup process smoother with updated ignore patterns and error handling in CI.
- Updated documentation helps users with seamless transition to new model export formats and tool versions.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
*.mlpackage directory created on export with these files:

Screenshot 2023-07-30 at 17 51 28

**Comment by glenn-jocher** [comment]
Benchmark results on M2 Macbook:


```
Ultralytics YOLOv8.0.145 🚀 Python-3.10.6 torch-2.0.1 CPU (Apple M2)
Setup complete ✅ (8 CPUs, 16.0 GB RAM, 327.9/460.4 GB disk)

Benchmarks complete for yolov8n.pt on coco8.yaml at imgsz=160 (331.90s)
                   Format Status❔  Size (MB)  metrics/mAP50-95(B)  Inference time (ms/im)
0                 PyTorch       ✅        6.2               0.2655                   10.45
1             TorchScript       ✅       12.3               0.3398                   21.38
2                    ONNX       ✅       12.1               0.3398                    3.65
3                OpenVINO       ❌        0.0                  NaN                     NaN
4                TensorRT       ❌        0.0                  NaN                     NaN
5                  CoreML       ✅       12.0               0.3417                    1.24
6   TensorFlow SavedModel       ✅       30.3               0.3398                   29.57
7     TensorFlow GraphDef       ✅       12.1               0.3398                   70.00
8         TensorFlow Lite       ✅       12.1               0.3398                    8.73
9     TensorFlow Edge TPU       ❌        0.0                  NaN                     NaN
10          TensorFlow.js       ❎       12.2                  NaN                     NaN
11           PaddlePaddle       ✅       24.3               0.3398                   34.12
12                   ncnn       ✅       12.1               0.2364                    5.17

```

**Comment by glenn-jocher** [comment]
@laclouis5 I implemented the metadata fix, but this now appears to break our tests that run on Python 3.11. Do you know any workaround?

**Comment by laclouis5** [comment]
@glenn-jocher I did some research and found that its likely an incompatibility of coremltools 6.3 with Python 3.11. I don't know why it is triggered in this specific case unfortunately.

I tried coremltools 7.0b1 (still in beta) for some of my projects and found no incompatibility with Python 3.11 and PyTorch 2.0 for now. Maybe we could try and use coremltools 7.0b1 instead of 6.3 if this is ok for you to use beta software?

**Comment by glenn-jocher** [comment]
> @glenn-jocher I did some research and found that its likely an incompatibility of coremltools 6.3 with Python 3.11. I don't know why it is triggered in this specific case unfortunately.
> 
> I tried coremltools 7.0b1 (still in beta) for some of my projects and found no incompatibility with Python 3.11 and PyTorch 2.0 for now. Maybe we could try and use coremltools 7.0b1 instead of 6.3 if this is ok for you to use beta software?

Sounds like a good idea, I've updated dependencies to 7.0.b1

**Comment by glenn-jocher** [comment]
@laclouis5 thanks for the INT8 PR. The status here is we are waiting on updates from our HUB team (web and app) led by @kalenmike to be able to accomodate the changes. Since the new format is a directory and carries a new type of suffix we need to coordinate changes there. 

Alternatively depending on the timeline and taking into account the long wait period on the original PR (since April) we may pin `ultralytics` versions used in the server to allow for more integration time there. We should have an answer either way this week I believe.

**Comment by glenn-jocher** [comment]
@laclouis5 ok I've implemented an update that adds a `format=mlmodel` off-menu value to allow us retrain the legacy *.mlmodel epxorts. The default `format=coreml` export will create *.mlpackage outputs. Everything seems fine but now that we are using  `convert_to='mlprogram'` I'm running into issues with the NMS pipeline, i.e. this code will produce errors now:

`yolo export format=coreml nms`

**Comment by glenn-jocher** [comment]
@laclouis5 PR merged! Thank you for the assistance on this.

**Comment by AphroDatalyst** [comment]
is it possible to have .mlpackage for yolov8-pose instead of .mlmodel?
if yes, how can we implement it?

**Comment by glenn-jocher** [comment]
@AphroDatalyst yes, it is indeed possible to have a .mlpackage for yolov8-pose. The .mlpackage format is a new format for Core ML models introduced with iOS 15 and macOS Monterey, and is supported starting from Core ML Tools 6.0.

To implement it, you'd first want to make sure you're using the latest version of Core ML Tools. When you're ready to convert your model, you'll use the `convert_to='mlprogram'` argument in the conversion function. After conversion, you can export your model using the .mlpackage extension instead of .mlmodel.

This feature is not yet thoroughly tested for the yolov8-pose, but feel free to give it a try and report any issues you encounter. Your feedback will be greatly appreciated as it helps improve support for the .mlpackage format.

**Pull request merged**
