### PR TITLE
`allow_empty=True` for Classify dataset class directories

### LINKED ISSUE #13936: Matching tag on classify validation
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Val

### Bug

I created a model that classify 4 classes (the image rotation : 0,90,180,270).
I trained the model with images in all classes.

But my test set only get 3 of 4 classes : 0,90,270 (there is no 180 for test), the set is 50 random images from all images I want to manage.

I got a little warning to say there were only 3 classes : 
```
test: /home/.../dataset/test... found 50 images in 3 classes: ERROR ❌️ requires 4 classes, not 3
```
What's more, I realized that the classes weren't managed by the name of the folders containing the images, but by their order.
In my case, the order was: 0,270,180,90.

However, 180 didn't exist, so the images contained in 90 were taken to be 180-true images, which is obviously not the case.

And if I put an empty folder, the process crash

```shell
Ultralytics YOLOv8.2.36 🚀 Python-3.10.12 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24241MiB)
YOLOv8x-cls summary (fused): 133 layers, 56128324 parameters, 0 gradients, 153.8 GFLOPs
train: /home/users/aimbert/Stage/data-yolo/dataset/hikariaPhotoRotation/train... found 400 images in 4 classes ✅
val: /home/users/aimbert/Stage/data-yolo/dataset/hikariaPhotoRotation/val... found 200 images in 4 classes ✅
test: /home/users/aimbert/Stage/data-yolo/dataset/hikariaPhotoRotation/test... found 50 images in 3 classes: ERROR ❌️ requires 4 classes, not 3
Traceback (most recent call last):
  File "/home/users/aimbert/.virtualenvs/yolo/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 591, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/model.py", line 528, in val
    validator(model=self.model)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/engine/validator.py", line 154, in __call__
    self.dataloader = self.dataloader or self.get_dataloader(self.data.get(self.args.split), self.args.batch)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/models/yolo/classify/val.py", line 85, in get_dataloader
    dataset = self.build_dataset(dataset_path)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/models/yolo/classify/val.py", line 81, in build_dataset
    return ClassificationDataset(root=img_path, args=self.args, augment=False, prefix=self.args.split)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/ultralytics/data/dataset.py", line 419, in __init__
    self.base = torchvision.datasets.ImageFolder(root=root)
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 328, in __init__
    super().__init__(
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 150, in __init__
    samples = self.make_dataset(
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 203, in make_dataset
    return make_dataset(
  File "/home/users/aimbert/.virtualenvs/yolo/lib/python3.10/site-packages/torchvision/datasets/folder.py", line 104, in make_dataset
    raise FileNotFoundError(msg)
FileNotFoundError: Found no valid file for the classes 180. Supported extensions are: .jpg, .jpeg, .png, .ppm, .bmp, .pgm, .tif, .tiff, .webp
```

Would it be possible to manage the prediction according to the folder name to avoid this kind of problem?

We could also add the possibility (etheir if the folder is absent or empty) to run an evaluation correctly

### Environment

Ultralytics YOLOv8.2.36 🚀 Python-3.10.12 torch-2.3.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24241MiB)
Setup complete ✅ (24 CPUs, 125.6 GB RAM, 72.9/147.1 GB disk)

OS                  Linux-5.15.0-112-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.12
Install             pip
RAM                 125.56 GB
CPU                 13th Gen Intel Core(TM) i7-13700
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.0.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.3>=2.23.0
scipy               ✅ 1.13.1>=1.4.1
torch               ✅ 2.3.1>=1.8.0
torchvision         ✅ 0.18.1>=0.9.0
tqdm                ✅ 4.66.1>=4.64.0
psutil              ✅ 6.0.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0

### Minimal Reproducible Example

With a folder 
- dataset
  - | train
    - | 0
    - | 90
    - | 180
    - | 270
  - | val
    - | 0
    - | 90
    - | 180
    - | 270
  - | test
    - | 0
    - | 90
    - | 270

```shell
CUDA_VISIBLE_DEVICES=0 yolo classify val model=models/model.pt data=dataset/ device=cuda:0 batch=256 plots=true split=test
```

### Additional

With some indication, I can help on a PR

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Alexis-IMBERT**
I have read the CLA Document and I sign the CLA

This PR is linked to [this issue](https://github.com/ultralytics/ultralytics/issues/13936)

For classifcation task, when you're validating a model on a dataset, if a class was empty, the validation crashed. And if there was no folder, the process run but could switch the missing class with another one, which distorts the results.

Now, there is still a potential switching class issue when a folder is missing, but there is no more if the folder is empty.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved dataset handling to support empty folders.

### 📊 Key Changes
- Updated the `ImageFolder` class from `torchvision` to allow empty folders by adding `allow_empty=True`.

### 🎯 Purpose & Impact
- **Flexibility**: Users can now include directories that might not contain any images without causing errors. This feature is particularly useful for dynamic or evolving datasets where the presence of images in all folders cannot be guaranteed at all times.
- **Robustness**: Enhances the usability of the data handling pipeline, making it more robust and user-friendly for a variety of real-world scenarios. 📁💡

### CODE REVIEW

**Comment by Alexis-IMBERT** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@Alexis-IMBERT PR merged, thank you for your contributions!

**Comment by vivekbiragoni** [comment]
# Issue Encoutered

## Description

While training a YOLO model using the Ultralytics library, I encountered an error related to the `ImageFolder` initialization. The error message indicates that the `ImageFolder` class received an unexpected keyword argument 'allow_empty'. I do not have test split, earlier it used to work fine, but i am facing this problem now.

## Error Trace

```plaintext
6 model = YOLO('https://hub.ultralytics.com/models/y5CuDHTRfWGJRCryUGh6 style="color:rgb(175,0,0)">')
7 results = model.train()

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/model.py:650, in Model.train(self, trainer, **kwargs)
647 self.model = self.trainer.model
649 self.trainer.hub_session = self.session # attach optional HUB session
650 self.trainer.train()
651 # Update model and cfg after training
652 if RANK in {-1, 0}:

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:204, in BaseTrainer.train(self)
201 ddp_cleanup(self, str(file))
203 else:
204 self._do_train(world_size)

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:323, in BaseTrainer._do_train(self, world_size)
321 if world_size > 1:
322 self._setup_ddp(world_size)
323 self._setup_train(world_size)
325 nb = len(self.train_loader) # number of batches
326 nw = max(round(self.args.warmup_epochs * nb), 100) if self.args.warmup_epochs > 0 else -1 # warmup iterations

File /opt/conda/lib/python3.10/site-packages/ultralytics/engine/trainer.py:287, in BaseTrainer._setup_train(self, world_size)
285 # Dataloaders
286 batch_size = self.batch_size // max(world_size, 1)
287 self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
288 if RANK in {-1, 0}:
289 # Note: When training DOTA dataset, double batch size could get OOM on images with >2000 objects.
290 self.test_loader = self.get_dataloader(
291 self.testset, batch_size=batch_size if self.args.task == "obb" else batch_size * 2, rank=-1, mode="val"
292 )

File /opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py:80, in ClassificationTrainer.get_dataloader(self, dataset_path, batch_size, rank, mode)
78 """Returns PyTorch DataLoader with transforms to preprocess images for inference."""
79 with torch_distributed_zero_first(rank): # init dataset *.cache only once if DDP
80 dataset = self.build_dataset(dataset_path, mode)
82 loader = build_dataloader(dataset, batch_size, self.args.workers, rank=rank)
83 # Attach inference transforms

File /opt/conda/lib/python3.10/site-packages/ultralytics/models/yolo/classify/train.py:75, in ClassificationTrainer.build_dataset(self, img_path, mode, batch)
73 def build_dataset(self, img_path, mode="train", batch=None):
74 """Creates a ClassificationDataset instance given an image path, and mode (train/test etc.)."""
75 return ClassificationDataset(root=img_path, args=self.args, augment=mode == "train", prefix=mode)

File /opt/conda/lib/python3.10/site-packages/ultralytics/data/dataset.py:421, in ClassificationDataset.init(self, root, args, augment, prefix)
419 # Base class assigned as attribute rather than used as base class to allow for scoping slow torchvision import
420 if TORCH_1_13: # 'allow_empty' argument first introduced in torch 1.13
421 self.base = torchvision.datasets.ImageFolder(root=root, allow_empty=True)
422 else:
423 self.base = torchvision.datasets.ImageFolder(root=root)

TypeError: ImageFolder.init() got an unexpected keyword argument 'allow_empty'
```

## Steps to Reproduce

1. Initialize a YOLO model using the Ultralytics library.

2.  Attempt to train the model using the .train() method.

3. Observe the error related to ImageFolder initialization.

## Expected Behavior
The model should train without encountering errors related to ImageFolder.

## Actual Behavior
The training process fails due to an unexpected keyword argument 'allow_empty' in the ImageFolder initialization.

## Environment
Python version: 3.10.13 | packaged by conda-forge | (main, Dec 23 2023, 15:36:39) [GCC 12.3.0]
Ultralytics version: 8.2.52
Torch version: 2.1.2
torchvision version: 0.16.2


image

**Comment by glenn-jocher** [comment]
Hi @vivekbiragoni,

Thank you for reporting this issue and providing detailed information. It seems like the error is related to the `allow_empty` argument in the `ImageFolder` class, which is available starting from `torchvision` version 0.13.0.

To help us diagnose the issue further, could you please provide a minimum reproducible example? This will allow us to replicate the problem on our end and investigate it more effectively. You can find guidelines for creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of the Ultralytics and Torch packages. You can update them using the following commands:

```bash
pip install --upgrade ultralytics
pip install --upgrade torch torchvision
```

If the issue persists after updating, please let us know along with the reproducible example, and we will look into it promptly.

Thank you for your cooperation! 😊

**Comment by vivekbiragoni** [comment]
pip install --upgrade ultralytics
pip install --upgrade torch torchvision

This resolved the issue thank you

**Comment by glenn-jocher** [comment]
Hi @vivekbiragoni,

I'm glad to hear that updating the packages resolved the issue! 🎉 If you encounter any more problems or have further questions, feel free to reach out. We're here to help!

Happy training! 🚀

**Pull request merged**
