### PR TITLE
Revert 1783 fix callbacks by reference

### LINKED ISSUE #1845: Regression: Callbacks stopped working due to #1795
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

PR https://github.com/ultralytics/ultralytics/pull/1795 broke the callbacks. Callbacks are not passed on to the trainer, validator and exporter classes and thus are not called anymore.

Callbacks used to be registerd by adding them to `callbacks.default_callbacks`. Now they are added to a local variable `self.callbacks`. The trainer, validator and export classes have no access to that variable and only call the default callbacks.

This seems to be fixed for the predictor class, though, by passing the callbacks via argument `_callbacks`. This should be implemented for the other classes as well.

### Environment

_No response_

### Minimal Reproducible Example

This code below should stop the training immediately once "on_train_start" callback is called. Instead training continues running.
```
import sys

from ultralytics import YOLO


def printme(trainer):
    print("CALLBACK PRINTME CALLED")
    sys.exit(1)


def train():
    model = YOLO()
    model.add_callback("on_train_start", printme)
    model.train(epochs=1, data="coco128.yaml")

train()
```

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update and refactoring related to YOLO model and callbacks in Ultralytics repository.

### 📊 Key Changes
- Incremented the package version to `8.0.64`.
- Removed unnecessary deep copy of `callbacks.default_callbacks` from the YOLO model initializer.
- Simplified and fixed the `is_hub_model` method's return conditions for more robust model path checking.
- Refactored the CLI check within the `predict` method for clarity.
- Changed the `add_callback` and `_reset_callbacks` methods from instance methods to static methods, ensuring callbacks are not unnecessarily instance-bound.

### 🎯 Purpose & Impact
- 🔍 The version bump signifies iterative improvements and minor fixes, ensuring users are up-to-date with the latest stable release.
- 🛠 The removal of deep copy operation for callbacks improves memory efficiency and likely the initialization speed of the YOLO model.
- 🧐 The more robust condition for model path checking in `is_hub_model` prevents errors and misunderstandings for model identification.
- 🧹 The refactoring of CLI argument checking in the `predict` method creates more readable and easily understandable code for developers.
- 📐 The change to static methods for managing callbacks standardizes the behavior across all instances, which might reduce issues related to state management for callbacks.

### CODE REVIEW

**Comment by AyushExel** [comment]
@glenn-jocher Okay merge this and then let's wait for @maltelorbach @dh031200 to redo the PR with tests.

Guys the problem with this solution was that the callbacks were getting added to the local copy but in the Trainer, validator and predictor the global copies are being used. So you need to update them in both places. We definitely need more tests so I'm happy to work with you guys on those.

**Comment by dh031200** [comment]
@glenn-jocher @AyushExel 
I will commit again by applying local copy to trainer, validator, and predictor.
Sorry for bothering you.
And your work and the way you work are so cool.
Actually, this is the first time I've contributed to open source.  I'm happy to work with you guys.

**Comment by AyushExel** [comment]
Sure no problem. Actually we should have had better tests in the first place. We appreciate you taking the time to contribute

**Comment by AyushExel** [comment]
@glenn-jocher There is one callback test here https://github.com/ultralytics/ultralytics/blob/main/tests/test_python.py#L185
But I'm not sure why that didn't fail in this case. I'll do some thinking around it and I've asked LQ to help with the plots() PR.

**Comment by dh031200** [comment]
@AyushExel Because I worked `fix callbacks by reference`PR only for predictor. And that test targeted `predictor`.

**Comment by glenn-jocher** [comment]
@dh031200 yes, it looks like you added a test for the callback to ensure that it is being properly called during training. This is a good practice to make sure that the callback is working as expected. Tests are important to ensure code stability and they help find any issues early on in the development process.

**Comment by maltelorbach** [comment]
Thanks for taking the time and fixing the issue so quickly. Awesome work!

**Comment by glenn-jocher** [comment]
@maltelorbach you're welcome! It was great working with you and we appreciate your contribution to the project. We believe that open source projects thrive on collaboration from different contributors. By working together, we can make the project better and more stable. We encourage you to continue contributing to open source projects in the future. Good luck!

**Pull request merged**
