### PR TITLE
Feature: Create HUB Models from CLI or Python Script

### PR DESCRIPTION
**Pull request by kalenmike**
This integration feature empowers users of the HUB platform to seamlessly create and manage models directly through the Command Line Interface (CLI) or via a Python script. It's designed to enhance the user experience by simplifying the model creation process.

It does not effect the current training process, simply login before training and ensure that hub is enabled (enabled by default) in your configuration to start syncing local models to HUB.

```python
from ultralytics import YOLO, hub

# Login to the Ultralytics HUB
hub.login(<API_KEY>, True)

# Create and train the model
model = YOLO('yolov8n.pt')
model.train()
```

Example Output:
```bash
Ultralytics HUB: View model at https://hub.ultralytics.com/models/9zpOWZSzNi07MxLM4am2 🚀
```

**Important:**
This PR is submitted for early testing. It installs the hub-sdk via git. Before merging we will deploy to PyPi and update this PR.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration and enhancement of Ultralytics HUB functionality in the project.

### 📊 Key Changes
- Added `hub-sdk` as a dependency in `pyproject.toml`.
- Replaced some direct hub utility calls with `hub_sdk.config`.
- Refactored `ultralytics/engine/model.py` to properly handle HUB sessions and model fetching.
- Modified `ultralytics/hub/__init__.py` to support improved hub API login and error management.
- Updated `ultralytics/hub/session.py` for better training session handling with the HUB.
- Improved hub authentication, request handling, and error messages across multiple files.

### 🎯 Purpose & Impact
- **Ease of Use:** The integration of `hub-sdk` simplifies interacting with Ultralytics HUB.
- **Enhanced Stability:** Authentication and session management updates make HUB interactions more stable.
- **Better Feedback:** Updated error messages and logging provide clearer information to users when issues arise.
- **Efficient Workflows:** Changes aim to create smoother workflows when using the HUB for training and managing AI models.

### CODE REVIEW

**Comment by kalenmike** [comment]
@glenn-jocher Provided the CI passes this should be good to go.

**Comment by kalenmike** [comment]
@glenn-jocher All deployed to production and PyPi, CI passed.

**Comment by glenn-jocher** [comment]
@kalenmike ok! Is this ready to merge to main now?

**Comment by kalenmike** [comment]
@glenn-jocher Yes, ready to merge.

**Comment by glenn-jocher** [comment]
@kalenmike can we update the CI? The current usage is breaking in main and will also break once we merge this. The usage is here:
https://github.com/ultralytics/ultralytics/blob/a92adf82311887256778fb8dc076300b90894465/.github/workflows/ci.yaml#L37-L90

**Comment by glenn-jocher** [comment]
The main script is here for training:
https://github.com/ultralytics/ultralytics/blob/a92adf82311887256778fb8dc076300b90894465/.github/workflows/ci.yaml#L60-L72


And then for inference:
https://github.com/ultralytics/ultralytics/blob/a92adf82311887256778fb8dc076300b90894465/.github/workflows/ci.yaml#L73-L89

**Comment by kalenmike** [comment]
@glenn-jocher I am not following, the usage should not have changed. What am I missing?

**Comment by kalenmike** [comment]
@glenn-jocher Ok I merged in some changes that fix the CI functions `reset_model` and `get_export`. There should not be any other changes needed in the CI as we kept the usage the same to prevent issues. The reason for the CI issue was that we removed the legacy authentication in the latest server release and missed that it was being used in these CI endpoints.

**Comment by glenn-jocher** [comment]
@kalenmike looks good now with hub-sdk v0.0.2! Merging PR!

**Pull request merged**
