### PR TITLE
Fix val=False bug

### LINKED ISSUE #586: EarlyStopping raises TypeError when training with `val=False` setting, as BaseTrainer.fitness is None
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

When training a segmentation model on my own custom dataset, I've found that a train run with setting `val=False` raises a TypeError after one epoch of training. Please see traceback:

```
Starting training for 2 epochs...
      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
        1/2         0G      2.769      4.483      4.415      1.707         32        256: 100%|██████████| 35/35 [07:29<00:00, 12.85s/it]
Traceback (most recent call last):
  File "/Applications/PyCharm.app/Contents/plugins/python/helpers/pydev/pydevd.py", line 1499, in _exec
    func()
  File "/Users/jeroen/.pyenv/versions/<snip>/lib/python3.9/site-packages/ultralytics/yolo/cfg/__init__.py", line 237, in entrypoint
    func(cfg)
  File "/Users/jeroen/.pyenv/versions/<snip>/lib/python3.9/site-packages/ultralytics/yolo/v8/segment/train.py", line 151, in train
    model.train(**vars(cfg))
  File "/Users/jeroen/.pyenv/versions/<snip>/lib/python3.9/site-packages/ultralytics/yolo/engine/model.py", line 201, in train
    self.trainer.train()
  File "/Users/jeroen/.pyenv/versions/<snip>/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 182, in train
    self._do_train(int(os.getenv("RANK", -1)), world_size)
  File "/Users/jeroen/.pyenv/versions/<snip>/lib/python3.9/site-packages/ultralytics/yolo/engine/trainer.py", line 343, in _do_train
    self.stop = self.stopper(epoch + 1, self.fitness)
  File "/Users/jeroen/.pyenv/versions/<snip>/lib/python3.9/site-packages/ultralytics/yolo/utils/torch_utils.py", line 387, in __call__
    if fitness >= self.best_fitness:  # >= 0 to allow for early zero-fitness stage of training
TypeError: '>=' not supported between instances of 'NoneType' and 'float'
``` 

### Environment

- YOLO V8, `ultralytics` Pip package `8.0.17`
- OS: MacOS 12.6.2 on 2020 Macbook Pro 13''
- CPU/GPU: M1 

### Minimal Reproducible Example

```bash
HYDRA_FULL_ERROR=1 yolo task=segment mode=train model=yolov8n-seg.pt \
                        data="$DATA" epochs=2 batch=64 \
                        imgsz=240 pretrained=True val=False \
                        cache=false lr=0.005
```

### Additional

Can be fixed by changing line 344 in `ultralytics.yolo.engine.trainer`

```python
    self.stop = self.stopper(epoch + 1, self.fitness) if self.fitness is not None else False
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by jarombouts**
PR relates to https://github.com/ultralytics/ultralytics/issues/586 where training with `val=False` causes the calculation of earlystopping criteria to fail with a ValueError, as `self.fitness` is `None`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduced an Early Stopping feature to the training process.

### 📊 Key Changes
- Added detailed docstrings explaining the Early Stopping class and its `__init__` and `__call__` methods.
- Implemented a check for `None` fitness, avoiding unwanted early stopping when validation is not used.

### 🎯 Purpose & Impact
- **Enhanced Documentation**: The carefully crafted docstrings provide developers and users a clear understanding of how early stopping works and how to instantiate and use the class.
- **Increased Training Efficiency**: Early Stopping prevents overfitting and can reduce training time by halting the learning process once the model stops improving, which is beneficial for both environmental sustainability 🌱 and cost savings 💰.

### CODE REVIEW

**Comment by jarombouts** [comment]
@AyushExel here's the PR for https://github.com/ultralytics/ultralytics/issues/586

**Comment by AyushExel** [comment]
Thanks. Merging this in the next release Updates PR

**Comment by glenn-jocher** [comment]
@jarombouts this looks good but I think we want this check inside the .stopper() method itself.

**Comment by glenn-jocher** [comment]
@jarombouts @AyushExel ok how does this look?

**Comment by AyushExel** [comment]
Looks good!

**Comment by jarombouts** [comment]
Yeah, looks nice! Thanks for the quick fix!

**Comment by AyushExel** [comment]
@glenn-jocher should I merge this in the release PR?

**Pull request merged**
