### PR TITLE
Update `OBB` assets and apply Ultralytics branding

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update image reference in documentation examples for YOLO model.

### 📊 Key Changes
- Changed image reference from 'bus.jpg' to 'ships.jpg' in code examples.
- Updated URL paths in the `CLI` and `Python` examples to reflect the new image.

### 🎯 Purpose & Impact
- **Clarification**: Uses a more suitable image for demonstrating model predictions.
- **Consistency**: Ensures examples are up-to-date with the latest image assets.
- **User Experience**: Simplifies and enhances understanding for both new and experienced users.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@RizwanMunawar wow it's really a good idea to add mark on images, but why the marks look different? can we use the same mark appearance? 
jnxKbkIixh

**Comment by Laughing-q** [comment]
@RizwanMunawar I think there's another place we can replace `bus.jpg` to `ships.jpg` in `modes/predict.md`
ZqwjrEMuJ0

**Comment by RizwanMunawar** [comment]
@Laughing-q Yes nice idea :) I just updated the branding and `modes/predict.md` so we are ready to go I guess?

**Comment by Laughing-q** [comment]
@RizwanMunawar yes I think it's ready! :)

**Comment by glenn-jocher** [comment]
@Laughing-q @RizwanMunawar hey awesome, this looks really good! We just need to downsize these images as they've grown a bit in KB, probably want watermark applied to original images in YOLOv5 assets (not in this repo, as they are already compressed). I can do this. Actually I think I might have done this manually with PIL. 

Also @RizwanMunawar can you make the watermark the same size for all 3? Ships looks much smaller than the other two

https://github.com/ultralytics/yolov5/releases/download/v1.0/zidane.jpg
https://github.com/ultralytics/yolov5/releases/download/v1.0/bus.jpg

**Comment by glenn-jocher** [comment]
@RizwanMunawar wait, @pderrenger also ways the watermark needs a little more edge clearance.

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes sure :)

**Comment by glenn-jocher** [comment]
Screenshot 2024-02-07 at 02 59 43
Screenshot 2024-02-07 at 02 59 58

**Comment by glenn-jocher** [comment]
@RizwanMunawar I'll merge this now and then let's update the assets later. Can you please add the logo to the full resolution zidane and bus.jpg images found in the YOLOv5 v1.0 assets (not the ones in this repo that are already compressed).

**Pull request closed without merging**
