### PR TITLE
New: Support for AWS Neuron Runtime

### PR DESCRIPTION
**Pull request by ianhco**
After a long time of monkey patching, I have decided to fork this repo and add support for [Neuron](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/) export and inference. I am not sure if this feature is in ultralytics' interest, but I guess I won't know until a PR is sent in.

Related issues:

https://github.com/ultralytics/yolov5/issues/8619
https://github.com/ultralytics/yolov5/issues/7739
https://github.com/ultralytics/yolov5/issues/2643

I understand these issues are from the yolov5, but sooner or later this repo will see an influx of such issues, I am currently not motivated to fork yolov5 as I am moving towards the better API provided on this repo (which also lacks this feature).

## Neuron (NeuronCore-v1)

- [x] Tested export
- [x] Tested inference

### Export:

Dependencies (Python<=3.8):

```sh
pip install -U \
    torch-neuron==1.13.1.* \
    neuron-cc[tensorflow] \
    --extra-index-url https://pip.repos.neuron.amazonaws.com # Change 1.13.1 with your torch version

pip install numpy==1.20 # export may fail if not numpy<=1.21.6,>=1.20
```

Supported args: `imgsz`, `half`, `dynamic`, `ccargs`

```python
from ultralytics import YOLO

model = YOLO("yolov8m.pt")
model.export(format="neuron") # default fp32
model.export(format="neuron", dynamic=True) # dynamic batching
model.export(format="neuron", half=True, dynamic=True) # fp32-cast-all-fp16
model.export(format="neuron", half=True, dynamic=True, ccargs=["--enable-fast-loading-neuron-binaries"]) # extra args to pass to neuron-cc
```

### Inference:

Run on Inf1 instances:

```python
from ultralytics import YOLO

model = YOLO("yolov8m.neuron", task="detect")
model('bus.jpg')
```

| Export | Inference Speed (/50) |
| ------- | ------------------ |
| yolov8m.pt (4vcpu) | 383.2ms |
| yolov8m.neuron | 40.1ms |
| yolov8m_fp16.neuron | 31.2ms |

## Neuronx (NeuronCore-v2)

- [x] Tested export
- [x] Tested inference

Dependencies (Python<=3.9):

```sh
sudo yum install aws-neuronx-collectives-2.* -y
sudo yum install aws-neuronx-runtime-lib-2.* -y # does not require neuron hardware
pip install -U \
    torch-neuronx==1.13.1.* \
    neuronx-cc==2.* \
    --extra-index-url https://pip.repos.neuron.amazonaws.com # Change 1.13.1 with your torch version
```

Supported args: `imgsz`, `half`, `fp8`, `dynamic`, `ccargs`

```python
from ultralytics import YOLO

model = YOLO("yolov8m.pt")
model.export(format="neuronx") # default fp32
model.export(format="neuronx", dynamic=True) # dynamic batching
model.export(format="neuronx", half=True, dynamic=True) # auto cast fp16
model.export(format="neuronx", fp8=True, dynamic=True) # auto cast fp8_e4m3
model.export(format="neuronx", half=True, dynamic=True, ccargs=["--enable-fast-loading-neuron-binaries"]) # extra args to pass to neuronx-cc
```

### Inference:

Run on Inf2 instances:

```python
from ultralytics import YOLO

model = YOLO("yolov8m.neuronx", task="detect")
model('bus.jpg')
```

| Export | Inference Speed (/50) |
| ------- | ------------------ |
| yolov8m.pt (4vcpu) | 383.5ms |
| yolov8m.neuronx | 15ms |
| yolov8m_fp16.neuronx | 10.3ms |

copilot:all

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated model benchmarking to skip specific formats, and introduced Neuron/Neuronx format support.

### 📊 Key Changes
- Added arguments to skip 'neuron' and 'neuronx' formats during benchmarking.
- Included Neuron and Neuronx as new deployment formats.
- Updated documentation to reflect new export capabilities.
- Implemented Neuron and Neuronx export functions in the exporter module.
- Adjusted model loading and inference to handle Neuron and Neuronx formats.

### 🎯 Purpose & Impact
- 💻 **Developers** can now benchmark models without certain formats, which helps when certain formats are not needed or not supported in specific environments.
- 🚀 **Deployment** capabilities are broadened with support for AWS Neuron and Neuronx, allowing users to deploy models on AWS Inferentia chips, potentially leading to cost-effective, high-performance inference.
- 📖 **Documentation updates** ensure users and developers are informed about new export options and usage.
- 🛠️ **Impact** on users is positive as they gain more flexibility and new options for deploying Ultralytics models on an expanded range of hardware.

### CODE REVIEW

**Comment by iann838** [comment]
I have read the CLA Document and I sign the CLA

**Comment by iann838** [comment]
It can't pass benchmark CI because the dependencies for neuron requires python<=3.8 and neuronx requires python<=3.9 + actual system dependencies, any idea to get this going ?

**Comment by glenn-jocher** [comment]
@iann838 this looks really good. I haven't used neuron myself, should we support both v1 and v2, i.e. is v1 intended for deprecation anytime soon or is it worth retaining support for it?

In light of Amazon's choice to severely restrict dependencies that will work with their neuron models it seems like we have no choice but to omit it from the CI. In any case I don't think we can benchmark these models anyways since the CI runners do not have access to the neuron hardware right?

**Comment by iann838** [comment]
@glenn-jocher v1 is not "deprecated" yet, but I wouldn't be surprised if it is in a year or two. In fact, v2 was intended to be training only at first. Exporting and compiling don't require neuron hardware (dependencies can be installed on CPU machines), but inference does (requires neuron devices on top of neuron drivers).

**Comment by glenn-jocher** [comment]
Thank you for your contribution @iann838. It sounds like supporting both v1 and v2 of AWS Neuron Runtime may be beneficial for the time being, although v1 may be deprecated in the near future. Your explanation of exporting and compiling not requiring Neuron hardware and inference requiring it is helpful for understanding the dependencies. It's unfortunate that the CI runners do not have access to the Neuron hardware, but that is outside of our control. We appreciate your efforts to improve the repo and look forward to reviewing your PR.

**Comment by vpetrog** [comment]
Have you also tested training on trn1?

**Comment by iann838** [comment]
@vpetrog No, this does not support training on Trn1, for it to support training on Trn1, we have to add `import torch_xla.core.xla_model as xm` then `model.to(xm.xla_device())` and after each step `xm.mark_step()`. This feature will be for another PR, but atm I don't see many requests (based on yolov5 and ultralytics list of issues), training on multi-GPU should be more than enough for yolo overall (I consider yolo to be medium-to-small-sized), training on Trn1 is more reasonable for bigger models like bert or other LLMs.

**Comment by iann838** [comment]
@glenn-jocher 
I added `skip_formats` to the `benchmark` function, the CI now has an extra argument `skip_formats=['neuron', 'neuronx']`. I got some questions tho, by default both neuron and neuronx will auto cast to half precision, but it has the option to not auto cast at all, what would be better:

- Default to disable auto cast, only auto cast to fp16 if `half=True`.
- Default to auto cast to fp16, disable auto cast if `half=False` (and not `None`).

For neuronx (v2) there is also the option to autocast to `fp8_e4m3`, if an argument is made available is `fp8` good?

**Comment by glenn-jocher** [comment]
@iann838 thank you for your contribution and adding the `skip_formats` argument to the `benchmark` function. As for your questions, it sounds like you have several options for auto casting and setting precision with Neuron and Neuronx to consider. In terms of default behavior, it's difficult to say which option would be better, as it may depend on the specific use case and individual preferences. It may be beneficial to provide users with the option to choose their own auto casting settings and precision by passing compiler arguments to the neuron compiler using an argument such as `ccargs`. This would allow users to pass any arguments that neuron-cc or neuronx-cc accepts and customize their settings to their specific needs.

**Comment by glenn-jocher** [comment]
> @glenn-jocher I added `skip_formats` to the `benchmark` function, the CI now has an extra argument `skip_formats=['neuron', 'neuronx']`. I got some questions tho, by default both neuron and neuronx will auto cast to half precision, but it has the option to not auto cast at all, what would be better:
> 
> * Default to disable auto cast, only auto cast to fp16 if `half=True`.
> * Default to auto cast to fp16, disable auto cast if `half=False` (and not `None`).
> 
> For neuronx (v2) there is also the option to autocast to `fp8_e4m3`, if an argument is made available is `fp8` good?
> 
> Another option would be to have an argument that passes compiler arguments to the neuron compiler (e.g. `ccargs=["--auto-cast", "all", "--auto-cast-type", "fp16"]`), the benefit here is that users can past any arguments that neuron-cc or neuronx-cc accepts.

@iann838 ok sounds good! Yes we should use the existing `half` and `int8` arguments for casting to PF16 and INT8, with FP32 the default export format. Let's start with that first.

**Comment by iann838** [comment]
@glenn-jocher it's not INT8 for neuron tho, it's FP8_E4M3, it seems unintuitive to use `int8` for this.

**Comment by glenn-jocher** [comment]
@iann838 thank you for bringing this to our attention. You're right, `FP8_E4M3` would be more appropriately named than `int8`, given its details. The intention of the `int8` argument is to enable INT8 quantization workflows that are supported by other frameworks such as TensorFlow, but this can be misleading for those who are specifically interested in the AWS Neuron Runtime FP8 quantization capabilities. We will consider changing `int8` to `fp8_e4m3` or a more descriptive name. Thanks again for your input!

**Comment by iann838** [comment]
@glenn-jocher
I added `fp8`, imo `_e4m3` is not needed, since if fp8 is used, it should always use the most accurate set available for the export for the same performance. Also added `ccargs` so users can pass extra arguments to the compiler.

This should be good to go now, I have manually tested export and inference with both formats and updated the opening comment of this PR with some local benchmarks. There is however one problem with `neuronx` export with auto cast `fp8_e4m3`, there is an internal attribute error on neuronx-cc, I have opened https://github.com/aws-neuron/aws-neuron-sdk/issues/680 for this matter.

**Comment by glenn-jocher** [comment]
Thank you for your contribution @iann838. It's great to see that you have added the `fp8` argument and `ccargs` option for passing extra arguments to the compiler. Your local benchmarks and manual testing is also helpful in validating the changes. We appreciate your efforts in identifying the internal attribute error with `neuronx-cc` and opening an issue for it. We will review your changes and incorporate them as appropriate. Thanks again!

**Comment by rromanchuk** [comment]
@iann838 this is nice, any chance you can branch and sync from latest upstream as a temporary fork?  looks pretty isolated, hopefully this gets merged soon

**Comment by alex-bronze-vision** [comment]
any news about merging this @iann838 ? It is a really great job!

**Comment by iann838** [comment]
@rromanchuk @alex-bronze-vision I opened this PR almost a year ago and synced it multiple times afterward; however, it was never accepted and merged, and as of right now I am no longer invested in supporting AWS Neuron. If you have a use case, you can check the commits and reimplement them with the latest updates of Ultralytics. I will be closing this PR.

**Comment by takipipo** [comment]
Any update on this ? I'm trying to achieve the same purpose via this [fork](https://github.com/takipipo/ultralytics/commit/9041c1d762c897de7b33112e0e5781e4b534e593) but this one is way more better. @iann838 @glenn-jocher

**Comment by glenn-jocher** [comment]
Hi @takipipo,

Thank you for your interest in this feature! Unfortunately, it appears that the original PR by @iann838 has been closed, and there are no current plans to merge it. However, you can still achieve similar functionality by referring to the commits in the PR and implementing them in your fork.

If you encounter any issues or need further assistance, please ensure you provide a reproducible example as outlined in our [minimum reproducible example guide](https://docs.ultralytics.com/help/minimum_reproducible_example). Additionally, make sure you are using the latest versions of the packages to verify that the issue persists.

Feel free to share any specific questions or challenges you face, and we'll do our best to assist you here. Thank you for your understanding and collaboration! 😊

**Pull request closed without merging**
