### PR TITLE
Add path property to Results

### PR DESCRIPTION
**Pull request by AyushExel**
@glenn-jocher @Laughing-q 
result.path will now return the input image path

I've made there arguments of results constructor mandatory because they're always needed:
`orig_img, path, names`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated results visualization method and added image path handling.

### 📊 Key Changes
- Renamed `visualize()` function to `plot()` for clarity.
- Added original image, image path, and class names to `Results` objects.
- Replaced print statements with `LOGGER` for better integration.
- Improved configuration files and tracking components structure.

### 🎯 Purpose & Impact
- The rename to `plot()` makes the function's purpose clearer – plotting results directly onto images.
- Storing the original image, its path, and class labels within `Results` objects makes it easier to reference them later, improving the usability of the results.
- Using `LOGGER` provides a standardized way to handle messages, making maintenance and debugging easier for developers.
- Refactoring helps organize the codebase, making future contributions and understanding the code simpler for both new and existing developers.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@AyushExel @glenn-jocher hey do we have to make `names` as a member of `Result`? I only see that `visualize` needs it and `names` is already a member of `model`. This is a little redundant to me.
```python
model = YOLO("yolov8n.pt")
model.names
results = model.predict()
results[0].names
results[0].visualize(...)
```
probably this would be better?
```python
model = YOLO("yolov8n.pt")
names = model.names
results = model.predict()
results[0].visualize(..., names=model.names)
```

**Comment by AyushExel** [comment]
I added it because most times users don't want to check docs themselves. So a visualize() function that works without any args would be the easiest. But I agree with you it being redundant. What do you think @glenn-jocher

**Comment by glenn-jocher** [comment]
@AyushExel PR merged!

**Comment by glenn-jocher** [comment]
> @AyushExel @glenn-jocher hey do we have to make `names` as a member of `Result`? I only see that `visualize` needs it and `names` is already a member of `model`. This looks a little redundant to me.
> 
> ```python
> model = YOLO("yolov8n.pt")
> model.names
> results = model.predict()
> results[0].names
> results[0].visualize(...)
> ```
> 
> probably this would be better?
> 
> ```python
> model = YOLO("yolov8n.pt")
> names = model.names
> results = model.predict()
> results[0].visualize(..., names=model.names)
> ```

Oops, just saw this convo. Yes I agree it's redundant, we should remove it from Results I think.

**Comment by glenn-jocher** [comment]
@AyushExel can you remove this in `updates` branch? I think that's the last change and then I'll merge and deploy 8.0.42.

**Comment by Laughing-q** [comment]
@glenn-jocher oh wait, the test failed in my case

**Comment by AyushExel** [comment]
@glenn-jocher If we remove it we should make `names` argument optional right? To make sure that plot() works without any arguments as well?

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel actually now that I think about no we don't want .plot()/.visualize() to require a names argument. We should probably leave it in results but not mention it in docs since it's a bit strange.

**Comment by AyushExel** [comment]
> @glenn-jocher oh wait, the test failed in my case `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor`

GPU tests on this branch?

**Comment by glenn-jocher** [comment]
> @glenn-jocher oh wait, the test failed in my case `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor`

Yes this is because one of our tests tries to output results to numpy directly. This is why I was asking before if we should move all results to CPU automatically. I think this makes more sense to keep CUDA memory free

**Comment by Laughing-q** [comment]
@AyushExel yeah

**Comment by glenn-jocher** [comment]
One problem we have is that Results is just a list, so i.e. names needs to be repeated many times etc. I think we want to convert Results into a single instance with list-like method like getitem etc. This way Results itself can only have one names dict etc.

This is a much bigger project but I think a worthwhile change for future releases.

**Comment by AyushExel** [comment]
@glenn-jocher I think lists are not copied but passed around by reference. So it should not cause any memory overhead

**Comment by glenn-jocher** [comment]
For example in YOLOv5 Autoshape the Detections object is just one instance, and it has one `self.names` dict. 

In YOLOv8 though if we do say 16 images in a batch then won't we have 16 names dicts sitting in memory?
Screenshot 2023-02-20 at 12 00 04

**Comment by Laughing-q** [comment]
@AyushExel True,  but each element(Result) in the list will have a `self.names`.

**Comment by AyushExel** [comment]
@glenn-jocher @Laughing-q oh yeah. The problem is that these are class variables..

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel 
> @glenn-jocher oh wait, the test failed in my case `TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor`

update this line [https://github.com/ultralytics/ultralytics/blob/217e7afa4b05b9f4a567a3791d4f3a83e05c9405/ultralytics/yolo/engine/results.py#L150](https://github.com/ultralytics/ultralytics/blob/217e7afa4b05b9f4a567a3791d4f3a83e05c9405/ultralytics/yolo/engine/results.py#L150) 
to:
```python
im_gpu = torch.as_tensor(img, dtype=torch.float16).to(masks.data.device).permute(2, 0, 1).flip(0).contiguous()
```
should solve the cuda issue.

**Comment by AyushExel** [comment]
@glenn-jocher @Laughing-q 
Okay. We can solve this..
```
def plot(...names=None):
   if not names:
        names = model.names
```
We can pass the model around without any memory implications right?

**Comment by glenn-jocher** [comment]
@Laughing-q oh great! One small optimization is that we can move device into to_tensor I think:
```
im_gpu = torch.as_tensor(img, dtype=torch.float16, device=masks.data.device).permute(2, 0, 1).flip(0).contiguous()
```

**Comment by Laughing-q** [comment]
@AyushExel @glenn-jocher also we need to remove this line as it should be moved to cpu first first `numpy()`.
[https://github.com/ultralytics/ultralytics/blob/217e7afa4b05b9f4a567a3791d4f3a83e05c9405/tests/test_python.py#L173](https://github.com/ultralytics/ultralytics/blob/217e7afa4b05b9f4a567a3791d4f3a83e05c9405/tests/test_python.py#L173)

**Comment by Laughing-q** [comment]
> 

I think this won't occupy much memory, probably we can leave this for now and try to optimize it once we want to make Result a list-like method?

**Comment by AyushExel** [comment]
Yeah agreed

**Comment by glenn-jocher** [comment]
Ok I've updated updates branch now with your two fixes @Laughing-q 

If names plotting is working now let's just remove it from the docs and we can work on a bigger update to Results later.

**Comment by glenn-jocher** [comment]
Ok I've removed the one reference in docs. I think we're all set now!

**Pull request merged**
