### PR TITLE
Updated SQL Query Plot Code

### PR DESCRIPTION
**Pull request by ankanpy**
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated documentation tools and enhanced data query visualization.

### 📊 Key Changes
- Removed the direct installation of `mkdocs-material` from GitHub in GitHub Actions workflow.
- Updated `pyproject.toml` to use a specific version of `mkdocs-material` (>=9.5.9) instead of the latest version.
- Modified documentation to demonstrate visualization of SQL query results rather than simply printing them.

### 🎯 Purpose & Impact
- **Clarity in Documentation**: By illustrating how to plot the results of an SQL query, users can better understand their data visually, leading to easier data analysis and model interpretation.
- **Stability in Documentation Builds**: Pinning `mkdocs-material` to a specific version ensures consistent documentation builds and prevents issues arising from new versions.
- **Smoother Development Workflow**: Removing the direct pip install from the GitHub master branch ensures that only stable releases of `mkdocs-material` are used, which reduces potential bugs or incompatibilities in the documentation process.

### CODE REVIEW

**Comment by 0xSynapse** [comment]
recheck

**Comment by glenn-jocher** [comment]
@0xSynapse thank you for your contribution to the Ultralytics community! 🚀

I have read the CLA Document and I hereby sign the CLA ✅

Regarding your PR, it's great to see enhancements that improve user experience and data interaction. Visualizing data is a crucial step in understanding and analyzing datasets effectively. Your addition of plotting capabilities for SQL query results is a valuable feature for users who work with the Dataset Explorer API.

We'll review the changes and get back to you if we have any questions or require further information. Keep up the excellent work! 👍

For future reference, please ensure that any PRs are submitted to the correct repository. This repo is focused on YOLOv8, and while we appreciate all contributions, it's important to maintain clarity and relevance across our projects.

Happy coding! 😊

**Review by AyushExel — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@AyushExel thanks for checking this out, all good to merge?

**Comment by AyushExel** [comment]
Yeah looks good

**Comment by glenn-jocher** [comment]
@0xSynapse merged! Thank you for your contributions 👍

**Comment by 0xSynapse** [comment]
Thank you @glenn-jocher , @AyushExel 

Love to contribute more!..

**Comment by glenn-jocher** [comment]
@0xSynapse thank you for your contribution to the Ultralytics repository! 🚀

I've reviewed your PR and it looks like you've made some valuable updates to the documentation tools and data query visualization. 👍

Just a couple of points to ensure a smooth integration:
- Please make sure that the specific version of `mkdocs-material` you've pinned in `pyproject.toml` is compatible with the rest of our documentation stack.
- For the visualization enhancements, it would be great if you could include some example plots in the PR to demonstrate the improvements.

Once again, we appreciate your efforts in improving the project. If you've already signed the CLA, we'll proceed with reviewing the changes in detail. 📝

Let's keep pushing the boundaries of what's possible with YOLOv8 and our other models! 🌟

**Pull request merged**
