### PR TITLE
Add new angle DFL- about oriented bounding box (OBB)

### PR DESCRIPTION
**Pull request by iscyy**
copilot:all

I have read the CLA Document and I sign the CLA

The purpose of this PR is to help use the new angular DFL loss for training the Oriented Bounding Box (OBB) task and integrate it into our YOLOv8 training pipeline for training the Oriented Bounding Box (OBB) task, which can be as easy as use_dfl control

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced YOLOv8 model training with angle awareness for oriented object detection.

### 📊 Key Changes
- Added a new configuration file for the `yolov8-obb-p6` model variant, with parameters for scaling and layers in the backbone and head of the network.
- Implemented angle-based Distribution Focal Loss (DFL) in the loss function to better account for object rotation.

### 🎯 Purpose & Impact
- 🎯 The enhancements to the YOLOv8 model structure and loss calculations optimize the model's ability to detect objects at various angles. 
- 🚀 These upgrades potentially improve the model's accuracy and performance, especially in scenarios where object orientations are significant, such as aerial imagery or scene understanding tasks.

### CODE REVIEW

**Comment by iscyy** [comment]
Function enhancement instructions come from: #7187 
@glenn-jocher @Laughing-q @RizwanMunawar

**Comment by glenn-jocher** [comment]
@iscyy acknowledged, and thank you for your interest in enhancing the YOLOv8 model with a new angular DFL loss for the OBB task. Your initiative to integrate this feature into our pipeline could benefit many users who require orientation-sensitive detection. We appreciate the community's efforts to improve and extend the capabilities of YOLOv8.

For further discussion on this feature enhancement, please ensure all communications and contributions align with our guidelines in our Contributing Guide, which is aimed at maintaining the repository's quality and coherence. Our team looks forward to reviewing your pull request and working together to evaluate the implementation and its impact on the model's performance.

Keep contributing, and let's continue making YOLOv8 better together! 🚀

**Comment by iscyy** [comment]
@glenn-jocher  I look forward to your review of the code and your constructive suggestions. You can discuss the code and optimize it at any time, thanks 👍

**Comment by glenn-jocher** [comment]
@iscyy thank you for submitting your code for review! Our team will take a look and provide feedback as soon as possible. We appreciate your contribution and effort to improve YOLOv8. Stay tuned! 👍

**Comment by Laughing-q** [comment]
@iscyy Thanks for the PR! I intended to implement dfl for angle but then figured probably using current dfl for bbox loss is also a good way for obb with minimal changes and already got pretty good results.
Perhaps I should try some experiments with angle dfl. Do you have any quantitative results with this angle dfl?

**Comment by iscyy** [comment]
@Laughing-q Hi, I conducted a comparative test training on the DOTAv2 data set, using yolov8s.pt pre-training weights(Transferred 361/397 items from pretrained weights), epoch=20(GPU limitations), and other settable parameters are consistent for fairness in the experiment.
Obtain the following experimental results
Experimental results without using angleDFL training (origin)
image

Experimental results using angleDFL training (use_angle_dfl)
image

It can be seen that using "use_angle_dfl" can detect more categories, improve the mAP (+0.5) of the DOTAv2 standard data set, and provide training logs.

Looking forward to your constructive opinions, Thanks.

**Comment by iscyy** [comment]
@Laughing-q hi, have you done this comparison experiment using this code? Thanks

**Comment by Laughing-q** [comment]
@iscyy Hey, this PR is automatically closed as the obb branch has been merged. You can create a new PR into main directly if you would like to. :)
Before that I have one question about this PR, I think we would also need to modify the head part of model when we implement DFL module for angle? just like what we've done for the bbox dfl module, we implemented it for both the loss part and head part.

**Pull request closed without merging**
