### PR TITLE
Fix Ray Tune error

### LINKED ISSUE #17379: ray tune fails with yolov8
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Hyperparameter Tuning

### Bug

Hi all!

I'm using ray to search the best hyper parameters for a custom yolov8s model.
When one training ends it raises the following exception:

2024-11-06 16:49:52,200	ERROR tune_controller.py:1331 -- Trial task failed for trial _tune_7a917_00000
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/ray/air/execution/_internal/event_manager.py", line 110, in resolve_future
    result = ray.get(future)
             ^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/worker.py", line 2745, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/worker.py", line 901, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ParserError): ray::ImplicitFunc.train() (pid=11597, ip=172.17.0.2, actor_id=5b95e8b8af49b9ff0079821c01000000, repr=_tune)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/tune/trainable/trainable.py", line 331, in train
    raise skipped from exception_cause(skipped)
  File "/opt/conda/lib/python3.11/site-packages/ray/air/_internal/util.py", line 104, in run
    self._ret = self._target(*self._args, **self._kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 45, in <lambda>
    training_func=lambda: self._trainable_func(self.config),
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/tune/trainable/function_trainable.py", line 250, in _trainable_func
    output = fn()
             ^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/utils/tuner.py", line 106, in _tune
    results = model_to_train.train(**config)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/model.py", line 802, in train
    self.trainer.train()
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 207, in train
    self._do_train(world_size)
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 445, in _do_train
    self.save_model()
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 523, in save_model
    "train_results": self.read_results_csv(),
                     ^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ultralytics/engine/trainer.py", line 505, in read_results_csv
    return pd.read_csv(self.csv).to_dict(orient="list")
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1026, in read_csv
    return _read(filepath_or_buffer, kwds)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 626, in _read
    return parser.read(nrows)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/readers.py", line 1923, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 234, in read
    chunks = self._reader.read_low_memory(nrows)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "parsers.pyx", line 838, in pandas._libs.parsers.TextReader.read_low_memory
  File "parsers.pyx", line 905, in pandas._libs.parsers.TextReader._read_rows
  File "parsers.pyx", line 874, in pandas._libs.parsers.TextReader._tokenize_rows
  File "parsers.pyx", line 891, in pandas._libs.parsers.TextReader._check_tokenize_status
  File "parsers.pyx", line 2061, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 15 fields in line 3, saw 16

Trial _tune_7a917_00000 errored after 49 iterations at 2024-11-06 16:49:52. Total running time: 3hr 32min 20s
Error file: /tmp/ray/session_2024-11-06_13-17-28_283877_9452/artifacts/2024-11-06_13-17-31/_tune_2024-11-06_13-17-31/driver_artifacts/_tune_7a917_00000_0_dfl=1.3515,lr0=0.0719,momentum=0.7717,weight_decay=0.0005_2024-11-06_13-17-31/error.txt

### Environment

Ultralytics 8.3.27 🚀 Python-3.11.9 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 4080, 16072MiB)

### Minimal Reproducible Example

# Load a model
model = YOLO("yolov8s.yaml")
dataset_yaml = "/dataset/fish-tune.yaml"
no_epochs = 50
iterations = 100

space ={
    "lr0": tune.uniform(0.008, 0.1),
    'momentum': tune.uniform(0.6, 0.98),
    'weight_decay': tune.uniform(0.0003, 0.0007),
    'dfl': tune.uniform(0.8, 1.8)
}

model.tune( data=dataset_yaml,
            space=space,
            epochs=no_epochs,
            iterations=iterations,
            batch=60,
            optimizer="SGD",
            plots=False,
            save=False,
            val=False,
            use_ray=True,
            gpu_per_trial=1)

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Y-T-G**
Closes https://github.com/ultralytics/ultralytics/issues/17379

Adding "epoch" to metrics causes the `results.csv`to be corrupt since that extra column gets written while saving metrics leading to an extra column.

**MRE**
```python
from ultralytics import YOLO
from ray import tune

model = YOLO("yolo11n.pt")

space = {
"lr0": tune.uniform(0.008, 0.1),
'momentum': tune.uniform(0.6, 0.98),
'weight_decay': tune.uniform(0.0003, 0.0007),
'dfl': tune.uniform(0.8, 1.8)
}

results = model.tune(data="coco128.yaml",
space=space,
epochs=10,
iterations=1,
use_ray=True,
gpu_per_trial=1)
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved integration with Ray Tune by updating how epoch metrics are reported.

### 📊 Key Changes
- Modified the `on_fit_epoch_end` function to adjust how training metrics are sent to Ray Tune at the end of each epoch.
- Simplified the reporting of metrics by directly including the incremented epoch number in the report dictionary.

### 🎯 Purpose & Impact
- 🛠️ Ensures compatibility with Ray Tune's current session handling, avoiding deprecated methods.
- 🚀 Enhances the accuracy of epoch reporting in metrics, potentially improving the clarity and reliability of the training process for users using Ray Tune for hyperparameter tuning.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Make sure the purpose of your fix or feature is clearly explained in your PR description. You’ve linked the relevant issue, which is fantastic! 🔗
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues to ensure a smooth merging process.
- ✅ **Update Documentation**: Please update any relevant [documentation](https://docs.ultralytics.com) for any new or modified features. This will help users understand and utilize your improvements.
- ✅ **Add Tests**: Include or update tests to cover your changes. Make sure all tests are passing to robustly validate your contributions.
- ✅ **Sign the CLA**: Ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your modifications to the **minimum** necessary for your bug fix or feature addition. ✂️ _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions or need further assistance, feel free to leave a comment. This is an automated response, and an Ultralytics engineer will also assist you soon. Thank you for your contribution to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@Y-T-G oh this is great! Was this the cause of the failing Ray scheduled tests? Can we re-enable them now?

**Comment by glenn-jocher** [comment]
@Y-T-G can you try running the disabled run here in an action to see if it passes? You can do this just by commenting the decorators for the test, it's in tests/test_integrations.py

**Comment by Y-T-G** [comment]
@glenn-jocher Looks like it still fails

**Comment by glenn-jocher** [comment]
@Y-T-G ok, then let's leave the test disabled.

**Comment by glenn-jocher** [comment]
@Y-T-G merged!

**Pull request merged**
