### PR TITLE
`ultralytics 8.0.37` add TFLite metadata in AutoBackend

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Various enhancements and fixes for improved function and compatibility across Ultralytics software tools.

### 📊 Key Changes
- Added `.pclprof` to `.gitignore` for profiling artifacts.
- Removed redundant link in `README.md`.
- Shifted `ipython` to the extras section in `requirements.txt`.
- Updated version number to `8.0.37` in `__init__.py`.
- Removed `hub` from the imports due to refactoring.
- Enforced `Colab` environment check for certain requests in `hub/utils.py`.
- Implemented metadata loading for better model parsing and consistent export structure in `autobackend.py`.
- Streamlined task guessing for models and made it more robust in `tasks.py`.
- Fixed and added missing `__all__` exports to various `__init__.py` files for cleaner imports.
- Improved exception handling for utility functions involving Jupyter and testing checks.
- Adjusted callbacks `__init__.py` for explicit function exposure.
- Enhanced user error messages for configuration mismatches.
- Modified `exporter.py` to utilize a less verbose flag during export.
- Updated `model.py` to ensure metrics are only set if the trainer has concluded successfully.
- Polished the user exception message when non-PyTorch models are given in contexts that require them.

### 🎯 Purpose & Impact
- Ensures proactive handling of profiling outputs to prevent unintentional commits 🚫.
- Cleaning up the `README` simplifies user access and maintainer updates 🧹.
- 📚 Clearer requirements assist developers in setting up environments for interactive work.
- Version increments 🏷️ help users track updates and stability in the toolchain.
- The `hub` module refactor and environment checks ensure compatibility and correct functionality in specific environments like Google Colab 🛠️.
- Enhanced metadata handling aligns with models across platforms for a homogenized experience 🔄.
- Improved task detection logic assists in automation flows, reducing the need for manual intervention 🤖.
- Explicit exports and error message improvements enhance user understanding of usage and debugging 📢.
- Reducing verbosity during exports keeps the focus on essential output, aiding in user focus and log management 👀.
- Accurate model metric setting helps users quickly access the latest model training results post-training completion 📊.

These changes contribute to an overall smoother user experience, a more intuitive development environment, and a clearer understanding of the codebase contributions for both developers and users of Ultralytics software tools.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@sergiossm with this PR TFLite inference now works in python. The TFLite files are inside the _saved_model directory, which is a little different than v5. Example usage is:

```
yolo export model=yolov8n.pt format=tflite
yolo predict model=yolov8n_saved_model/yolov8n_float16.tflite
```

You should see output like this for predict:
```
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.0.36 🚀 Python-3.10.6 torch-1.13.1 CPU
Loading yolov8n_saved_model/yolov8n_float16.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 10 nodes delegated out of 376 nodes with 10 partitions.


image 1/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x640 4 persons, 1 bus, 89.1ms
image 2/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 640x640 2 persons, 1 tie, 78.8ms
Speed: 3.5ms pre-process, 83.9ms inference, 8.1ms postprocess per image at shape (1, 3, 640, 640)
```

And TFLite models can now be validated also, i.e.:
```
yolo val model=yolov8n_saved_model/yolov8n_float16.tflite

WARNING ⚠️ 'data' is missing. Using detect default 'data=coco128.yaml'.
Ultralytics YOLOv8.0.36 🚀 Python-3.10.6 torch-1.13.1 CPU
Loading yolov8n_saved_model/yolov8n_float16.tflite for TensorFlow Lite inference...
INFO: Created TensorFlow Lite delegate for select TF ops.
INFO: TfLiteFlexDelegate delegate: 10 nodes delegated out of 376 nodes with 10 partitions.

Forcing --batch-size 1 square inference (1,3,640,640) for non-PyTorch models
val: Scanning /Users/glennjocher/PycharmProjects/datasets/coco128/labels/train2017.cache... 126 images, 2 backgrounds, 0 corrupt: 100%|██████████| 128/128 [00:00<?, ?it/s]
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 128/128 [00:09<00:00, 14.14it/s]
                   all        128        929      0.688      0.508      0.606      0.452

```

**Comment by glenn-jocher** [comment]
@akx ok it looks like ast worked up until here:
https://github.com/ultralytics/ultralytics/blob/20fe708f3197ebaaf98c7fa56db5378b26ee27ac/ultralytics/models/v8/yolov8n.yaml#L24

Screenshot 2023-02-14 at 14 05 25

**Comment by glenn-jocher** [comment]
@akx @developer0hye the ast line caused CI errors above, so I've reverted the changes with the new implementation commented out and a TODO added to revisit in https://github.com/ultralytics/ultralytics/pull/953/commits/18b83b7672ca5e1774a40b1a96d3499a27e806ed

**Comment by developer0hye** [comment]
@glenn-jocher I checked it! Thanks!

**Pull request merged**
