### PR TITLE
Feat: Added initial support for OBB

### LINKED ISSUE #624: Yolov8 OBB Task support (Oriented Bounding Box - Object Detection)
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Hi guys,

I'm just wondering of what could be the likelihood of discussing the OBB support for yolov8 sometime in the future?

I know that based on the 'Ultralytics Live Session of January 24th' there are certain priorities that will have to be taken care of first in order to bring the maturity of yolov8 to the point of yolov5 and that later there might be talk about implementing the Pose estimation etc...

But I've just been wondering if OBB support might ever make it on the table for this project?

I'm aware that there already exist certain options for training OBB models and even a specialised version of yolov5 that implements this.
However, none are quite as nicely maintained and as quick and easy to implement as the Ultralytics based project repositories and I would therefore love to see an OBB option with yolov8.

If I knew how I would even go as far as to implement it myself, but what do you guys think? Is this doable? Likely?

Thanks!

### Use case

In addition to the obvious scenarios (Such as satellite imagery of vehicles) I could totally see how this would work really well with things like electronics (Resistors/fuses/wire jumps/etc...) it should in theory help a lot when it comes to having a small enough dataset and having a good bit of overlap (Perhaps from parts being close together).

It would mainly benefit any objects that are stretched out in length where the bounding box is good if they are either vertical (|) or horizontal (---) but it becomes messy if they turn on say 45 degrees (\\) whereas with OBB it wouldn't matter.

Which could include things like:
- All sorts of Medical and other types equipment.
- Electricity poles (For things like self driving cars etc...).
- Cutlery (Forks, spoons, knives, etc...).
- Agriculture (For example for things like carrots on a conveyor belt).
- Automated electronics placement/inspection etc...

I think that there are endless examples of where this would be really useful to have as an option.

Standard
versus
OBB

Note the overlap of the components in each case...

### Real-World-Examples

Consider this case case:
SIPResistors_Good_Sample

Or this case:
Capacitors

Both of these cases will work perfectly fine with the current detection boxes.

However, now consider if the yellow (SIP_Resistor) parts were on an angle like so:
SIPResistors2
SIPResistors

Or consider this case right here (Where the shape of the object is a square, but the object can be on an angle):
Terminals

Or let's consider that we don't have that much data to begin with, but that we have components that are next to each other like so:
LEDs

### Real-World-Examples Using OBB

Now let's consider these tricky samples with OBB:
SIPResistors_OBB2
SIPResistors_OBB
Terminals_OBB
LEDs_OBB

I've ashed ChatGPT to build me a basic OBB labelling tool (Does not produce the actual labels) [OBB Labeling tool Python code](https://pastebin.com/RU8PR6aJ) and ironically for this dataset where the component sizes are more or less identical it was nearly easier and faster to label than the traditional labelling tools/approaches...

### Additional

This is definitely a low priority in comparison to what has to happen first, but I still firmly believe that this is worth looking into for the longer-term cycle of yolov8.

In the mean time I just wanted to bring it up for discussion :rocket: 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #1342: quadrilateral(polygon/convex) object detection
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Is there any way to get Polygon shape (instead of rect form) in Yolov8? 
Before: (x1, y1, x3, y3) / Wanted : (x1, y1, x2, y2, x3, y3, x4, y4)
I wanted to detect a quadrilateral bboxes or something convex items. 
I already know the Obb task related with YOLOv5 but, a few cases in my dataset is not only rotated but also, distorted.

i already tried segmentation task in YOLOv8, but segmentation accuracy is really low. So I can't get the contour of that segmentation mask.

Also, found related another [repo](https://github.com/XinzeLee/PolygonObjectDetection/) related with YOLOv5, but it looks like code from a very old version of Yolov5.

Which Part should i modify for the polygon shape in YOLOv8?
If you have any ideas, please help.. :)

### Additional

_No response_

### PR DESCRIPTION
**Pull request by yoloyash**
Hi, this is an initial commit to add the support for oriented bounding boxes as per the conversation with @AyushExel. I'm able to configure the dataloaders to accept theta based bounding boxes. However, I'm unable to figure out the loss part yet. 
#624 

### Summary
📦🛠️📐

This pull request adds a new feature for oriented bounding box detection using the YOLOv8 obb model. It implements a new module, task, and model for the 'detectobb' task, and updates the configuration files accordingly. It also removes some unused code from the modules file.

> _`detectobb` task_
> _YOLOv8 obb model_
> _autumn leaves rotate_

### Walkthrough
*  Add a new task for oriented bounding box detection ('detectobb') with a corresponding YAML configuration file and model class ([link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-862c6566244eb7a4639186dd7eb437fad92c873c254ef2cf826510f378404291R1-R46), [link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R242-R250), [link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-daf1714127b012666c9fed39d0e75184c60be83f0c6bd3f9863f27113b1a6c22L17-R29), [link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL8-R8), [link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL29-R32))
*  Extend the Detect module to handle the orientation output of the model and create a new DetectOBB module class ([link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-7bb55fea226aca9e349baf67b2a6011df4f4a9b5863393d60666c22575cef95eR435-R455), [link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L478-R487))
*  Update the functions that infer the task name from the configuration, the model structure, or the model file name to include the 'detectobb' task ([link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R568-R569), [link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R594-R595), [link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4R606-R607))
*  Remove an empty code block in the modules file ([link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-7bb55fea226aca9e349baf67b2a6011df4f4a9b5863393d60666c22575cef95eL487))
*  Import the DetectOBB class in the tasks file ([link](https://github.com/ultralytics/ultralytics/pull/1958/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L13-R13))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing YOLOv8-obb model for object detection with rotation!

### 📊 Key Changes
- 🔧 Added a new YOLOv8 model configuration designed for oriented bounding box (OBB) detection (`yolov8-obb.yaml`).
- 🏗️ Implemented a new OBB detection head (`OBB`) in the neural network modules to handle detection with orientation.
- 🛠 Extended `DetectionModel` to `OBBModel` to support oriented bounding box tasks.
- 🔄 Updated relevant engine and task management files to recognize and handle the 'obb' task.

### 🎯 Purpose & Impact
- 🎯 This update provides a foundation for detecting objects with orientation, which is crucial for tasks where object rotation is significant.
- 📈 For users and developers, this enhancement expands the capabilities of computer vision models by allowing for detection in more complex scenarios, such as aerial imagery where objects are not aligned with image axes.

### CODE REVIEW

**Comment by JustasBart** [comment]
Oh no way there's already an initial PR for this :open_mouth: you guys are absolute legends :heart: :rocket:

**Comment by glenn-jocher** [comment]
@yoloyash awesome, thanks for the PR! We want to add support for an initial full-scale dataset to train OBB with, as well as a tiny dataset for CI, i..e coco.yaml and coco8.yaml in the case of detection. You mentioned DOTA before as the main OBB benchmark dataset. Can you help us create a dataset yaml for this also?

@AyushExel should we call the new task 'detectobb' or just 'obb'? 

Screenshot 2023-04-11 at 13 17 17

**Comment by yoloyash** [comment]
I have read the CLA Document and I sign the CLA

**Comment by yoloyash** [comment]
recheck

**Comment by glenn-jocher** [comment]
@JustasBart i'm sorry, I'm not sure what you would like me to recheck. Could you please provide more information on what you need me to do?

**Comment by yoloyash** [comment]
@glenn-jocher DotaV2.0 dataset is available [here](https://opendatalab.com/91). Will be adding the yaml for the same in the next commit. The format for the bbox annotation in DOTA is (x1,y1,x2,y2,x3,y3,x4,y4). Currently, the modifications I've made to the repo convert the bbox to (x,y,w,h,theta) format before feeding it into the model so as to have minimal modifications to the codebase. The theta prediction task is treated as a classification task similar to predicting the class of the object. Additionally, due to the small size of the objects in the dataset, I'm dividing the dataset into tiles of 1024x1024 (with an overlap of 200 pixels) before feeding it to model as this is the standard in Aerial Object Detection. The output of the model is then combined into one single output following [this approach](https://github.com/ashnair1/dotadevkit). What are your thoughts on this approach? If all this is okay with you, I will proceed with committing the rest of the changes. Otherwise I'd be happy to modify my approach as per the requirements :)

**Comment by glenn-jocher** [comment]
> @glenn-jocher DotaV2.0 dataset is available [here](https://opendatalab.com/91). Will be adding the yaml for the same in the next commit. The format for the bbox annotation in DOTA is (x1,y1,x2,y2,x3,y3,x4,y4). Currently, the modifications I've made to the repo convert the bbox to (x,y,w,h,theta) format before feeding it into the model so as to have minimal modifications to the codebase. The theta prediction task is treated as a classification task similar to predicting the class of the object. Additionally, due to the small size of the objects in the dataset, I'm dividing the dataset into tiles of 1024x1024 (with an overlap of 200 pixels) before feeding it to model as this is the standard in Aerial Object Detection. The output of the model is then combined into one single output following [this approach](https://github.com/ashnair1/dotadevkit). What are your thoughts on this approach? If all this is okay with you, I will proceed with committing the rest of the changes. Otherwise I'd be happy to modify my approach as per the requirements :)

Hey this sounds great! For our format we probably want to treat rotation as a regression task though with sigmoid outputs from 0-1 just like our other regression values xywh. This 0-1 would span the -180 to 180 rotation range, or -2pi to 2pi radians.

Yes the large image slicing and overlap sounds good too. This is the same approach I used for https://github.com/ultralytics/xview-yolov3. 

We wanted to generalize this as a predict/val argument, to allow users to divide large images into smaller "chips", so this is a bit different than merging it into a dataloader, but yes it makes sense to provide support for this and then access it in both the dataloaders for val/predict/train.

**Comment by yoloyash** [comment]
> @yoloyash for CLA it looks like you made some contributions from a second account with the handle @yash. Could you sign into this PR with that account and paste the CLA message?

The initial commit was made from my local system’s git that the CLA bot incorrectly identified as a different account @yash as it’s the same as my first name. I'm relatively new to git and I'm extremely sorry for the confusion here. Is there a way I can rectify my username for the CLA bot? Otherwise, I can delete this PR and recreate a new one from my Github profile which also includes the changes you've suggested.

**Comment by yoloyash** [comment]
@JustasBart @glenn-jocher About the regression part for angle prediction, since angles are periodic in nature, we should look for a circular loss function right? [This article](https://zhuanlan.zhihu.com/p/358441134) by the author of yolov5_obb explains the problem better.

**Comment by glenn-jocher** [comment]
@JustasBart yes, you are correct. Since angles are periodic in nature, it is important to use a circular loss function that can handle this periodicity. A circular loss function is designed to handle angles by taking into account their periodic nature and treating differences at both extremes of the circle in a similar way. One such function is the Wrapped Normal Distribution Loss (WND loss), which is a circular version of the Gaussian distribution. The WND loss works by creating a normal distribution that wraps around the circle, which can handle periodicity and produce a smooth and continuous loss. Another option is the Von Mises Fisher loss (VMF loss), which models the angles as vectors on a hypersphere, and computes the distance between these vectors using a cosine similarity metric. Both the WND loss and the VMF loss are commonly used for angle regression in various computer vision tasks including object detection.

**Comment by glenn-jocher** [comment]
@yoloyash hey there buddy, sure if you want to submit a new PR with your single GitHub username that might work better. It may also be a CLA bot issue. 

Note I've made a few updates to the PR though, so be sure to include these if you resubmit.

**Comment by yoloyash** [comment]
Closing this PR as I have raised PR #1977 with the same changes.
@glenn-jocher @AyushExel

**Comment by glenn-jocher** [comment]
@yoloyash sure, I understand. As contributors to this project, it is important to maintain a professional tone and provide explanations of ideas and concepts in an informative and clear manner, without relying heavily on code examples. By doing so, we can effectively communicate our ideas to other contributors and users, and ensure that the project continues to grow and evolve in a collaborative and constructive way. It is important to be clear, concise, and respectful in our communication, and to always be open to feedback and constructive criticism.

**Comment by yoloyash** [comment]
> @yoloyash sure, I understand. As contributors to this project, it is important to maintain a professional tone and provide explanations of ideas and concepts in an informative and clear manner, without relying heavily on code examples. By doing so, we can effectively communicate our ideas to other contributors and users, and ensure that the project continues to grow and evolve in a collaborative and constructive way. It is important to be clear, concise, and respectful in our communication, and to always be open to feedback and constructive criticism.

Sure, will definitely be keeping this in mind moving forward! Thank you for your suggestions.

**Comment by glenn-jocher** [comment]
@yoloyash sure, I understand that as a contributor to this project, it is important to maintain a professional and collaborative environment. To effectively communicate ideas and concepts, it is important to explain them in a clear and concise manner that is easy for other contributors and users to understand. This can be achieved by providing informative explanations of the ideas and concepts without relying too heavily on code examples. It is also crucial to remain open to feedback and constructive criticism, and to approach communication with respect and professionalism. By doing so, we can ensure that the project continues to evolve and grow in a collaborative and productive way.

**Pull request closed without merging**
