### PR TITLE
Add Custom CLIP Model Download Path

### PR DESCRIPTION
**Pull request by wangsrGit119**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced text prompt handling in the `fastsam` model to support custom download locations for CLIP models.

### 📊 Key Changes
- Modified `text_prompt` method to include an optional `clip_download_root` parameter.
- Updated the CLIP model loading to use this new parameter if provided.

### 🎯 Purpose & Impact
- **Customization**: Allows users to specify where CLIP models should be downloaded, enhancing flexibility. 📂
- **User Experience**: Facilitates smoother workflows, especially in environments with specific directory requirements. 🌐

### CODE REVIEW

**Comment by wangsrGit119** [comment]
我已阅读 CLA 文件并签署 CLA

**Comment by wangsrGit119** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
recheck

**Comment by glenn-jocher** [comment]
@wangsrGit119 PR merged! Thank you for your contributions.

**Pull request merged**
