### PR TITLE
Add KaTeX support + updates to YOLOv9 model page

### PR DESCRIPTION
**Pull request by Burhan-Q**
- Adds KaTeX support for fast rendering of formula and mathematical symbols
   - ~~included fix for compatibility with `instant navigation` mentioned [in discussion](https://github.com/squidfunk/mkdocs-material/discussions/6807) and  https://github.com/squidfunk/mkdocs-material/pull/6823~~ this was a regression issue and was patched in https://github.com/squidfunk/mkdocs-material/commit/de46c4153b235a282502f6758a19140ca2c7be13
   
- Update formula on YOLOv9 to render using KaTeX (see screenshots)
    <details><summary>Dark mode rendered equations</summary>
    <p>

    image

    </p>
    </details> 

    <details><summary>Light mode rendered equations</summary>
    <p>

    image

    </p>
    </details> 

    <details><summary>Current non-rendered equations</summary>
    <p>

    image

    </p>
    </details> 

- Changed YOLOv9 performance table to use same headers from other docs pages and drop extraneous columns for S/M/L benchmarks (not included anywhere else in docs)

    - Table also updated with image sizes shown in GitHub repo (not found in paper)<br></br>

    <details><summary>Reformat YOLOv9 table</summary>
    <p>

    image

    </p>
    </details> 

    <details><summary>YOLOv8 table to compare</summary>
    <p>

    image

    </p>
    </details> 

    <details><summary>Current YOLOv9 table</summary>
    <p>

    image

    </p>
    </details> 

- Include link to YOLOv8 page on YOLOv8 text, removed hyphen between `v8` and `X`, and made lower-cased `x` for consistency with YOLOv8 docs

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of YOLOv9 documentation with better mathematical notation and KaTeX math rendering support.

### 📊 Key Changes
- Replaced Python code snippets with clearer LaTeX-like mathematical formulas in the YOLOv9 documentation.
- Added a new JavaScript file (`katex.js`) to enable rendering of LaTeX-like math directly on the webpage.
- Updated `mkdocs.yml` to include KaTeX CSS and JavaScript URLs for math rendering, and added the `arithmatex` extension to support this feature.

### 🎯 Purpose & Impact
- **Improved Readability:** The use of LaTeX-like syntax ($$...$$) for math in docs makes the content more reader-friendly for those familiar with mathematical notation.
- **Enhanced Documentation Quality:** The addition of KaTeX will display mathematical expressions more accurately and professionally in the browser, providing a better user experience.
- **Broader Audience Engagement:** With clearer representation of complex concepts, YOLOv9 can now engage a more diverse audience, including academia and research sectors, potentially increasing its adoption.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced YOLOv9 documentation with updated performance tables and clearer model comparisons.

### 📊 Key Changes
- 📐 Restructured YOLOv9 performance table for better readability.
- 🖋️ Added model input size to the performance table.
- 🔄 Changed the order of columns, leading with model size and AP metrics for clarity.
- 🔗 Linked YOLOv8-X to its respective documentation for easy reference.

### 🎯 Purpose & Impact
- 📖 Makes it easier for users to understand model performance at a glance.
- 🤖 Helps in selecting the appropriate YOLOv9 model variant based on accuracy and computational requirements.
- 🚀 Enhances accessibility to model details, potentially driving more informed decisions regarding model use in applications.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q oh hey thanks! I was struggling with the latex equations originally and finally gave up and switched to python code instead. I'm not sure what's better now since the new updates aren't as readable in Markdown if viewed from an IDE or a on our github page. What do you think? 

New table 100% looks great, can you submit a separate PR just for that?

**Comment by glenn-jocher** [comment]
@Burhan-Q BTW the original with latex looked like this:

```
### Information Bottleneck Principle

The Information Bottleneck Principle reveals a fundamental challenge in deep learning: as data passes through successive layers of a network, the potential for information loss increases. This phenomenon is mathematically represented as:

\[I(X, X) \geq I(X, f_{\theta}(X)) \geq I(X, g_{\phi}(f_{\theta}(X))),\]

where \(I\) denotes mutual information, and \(f\) and \(g\) represent transformation functions with parameters \(\theta\) and \(\phi\), respectively. YOLOv9 counters this challenge by implementing Programmable Gradient Information (PGI), which aids in preserving essential data across the network's depth, ensuring more reliable gradient generation and, consequently, better model convergence and performance.

### Reversible Functions

The concept of Reversible Functions is another cornerstone of YOLOv9's design. A function is deemed reversible if it can be inverted without any loss of information, as expressed by:

\[X = v_{\zeta}(r_{\psi}(X)),\]

with \(\psi\) and \(\zeta\) as parameters for the reversible and its inverse function, respectively. This property is crucial for deep learning architectures, as it allows the network to retain a complete information flow, thereby enabling more accurate updates to the model's parameters. YOLOv9 incorporates reversible functions within its architecture to mitigate the risk of information degradation, especially in deeper layers, ensuring the preservation of critical data for object detection tasks.
```

**Comment by Laughing-q** [comment]
@Burhan-Q @glenn-jocher For IDE I think there should be some tools or plugins can preview these formulas, but yes it's not readable on github page for users(actually it can be, with some sort of browser plugin, but can't assume that every user has that).

**Comment by glenn-jocher** [comment]
@Burhan-Q yeah maybe we should leave the code as is, especially considering we'd need to load additional javascript for all the pages just for the equations here on this one page. 

In GitHub the individual letters render correctly but not the equation enclosed with $$

Screenshot 2024-03-01 at 11 19 27

**Comment by Burhan-Q** [comment]
@glenn-jocher understood. I wanted to try the native KaTeX first because it will render nicely on the site but I do understand that it's also beneficial to have it render prettier in the markdown file too. Already have a backup plan to insert images for the equations and there are Unicode versions of the Greek letters that should work ψ, θ, ϕ for the inline text. I'll update the PR to use these.

Do you still want me to split off the table update to a new PR as well?

**Comment by Burhan-Q** [comment]
yolov9_001-2
yolov9_002-2

**Comment by Burhan-Q** [comment]
@glenn-jocher updated with images and inline Unicode, removed KaTeX plugin from config and extra `.js` file

**Comment by Burhan-Q** [comment]
image

**Comment by glenn-jocher** [comment]
@Burhan-Q hey thanks for your effort here. I think there's no simple solution since each has it's drawbacks. Maybe if we start to incorporate more equations throughout the docs we should add the latex CSS support, but for now I think let's keep it simple and leave the python code in place (since we have a lot of that already present).

One interesting thing I thought is that I found you could replace the greek words with their symbols and they do seem to render correctly, though it looks kinda of funny since I've never actually seen python code with the symbols.

**Comment by glenn-jocher** [comment]
@Burhan-Q PR merged!

**Pull request merged**
