### PR TITLE
Validate arguments passed as dict to `settings.update()`

### LINKED ISSUE #18332: 'wanbd' environment variables
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

image
### **I use kaggle to train my model ,use notebook to code;I find this problem in previous yolov8 issues,but yolov11 failed.**
Changes to your `wandb` environment variables will be ignored because your `wandb' session has already started. For more information
on how to modify vour settings with wandb.inito arguments. please refer to the W&B docs.

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Y-T-G**
The arguments are not validated if passed as dictionary
`settings.update({"wandb": "true"})`.
causing issues like [this](https://github.com/ultralytics/ultralytics/issues/18332#issuecomment-2558180229).

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Improved code quality and error handling for settings, URLs, and string representations in the Ultralytics library.

### 📊 Key Changes  
- Refactored `JSONDict`'s string representation for better readability.  
- Added a new method to directly update a single key-value pair in settings using `__setitem__`.  
- Enhanced the `update` method to handle dictionary arguments and provide more detailed error messages for invalid keys or types.  
- Simplified the `clean_url` function by replacing `urllib.parse` with `unquote` for better clarity and performance.  

### 🎯 Purpose & Impact  
- 🛠️ **Better Usability**: The changes to `JSONDict` and the new `__setitem__` method make managing configuration settings more intuitive for users.  
- 🔍 **Enhanced Debugging**: Improved error messages help users quickly identify and fix issues with their settings.  
- 🌐 **Simplified Code**: Refactoring the URL handling function reduces code complexity and potential bugs.  
- ✅ Overall, these changes improve the user experience and maintainability of the library while making debugging easier.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any relevant issues. Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics Continuous Integration (CI) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our Contributor License Agreement (CLA) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For more guidance, please refer to our Contributing Guide. Don’t hesitate to leave a comment if you have any questions. An Ultralytics engineer will review your PR and provide feedback shortly. Thank you for contributing to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@Y-T-G I think this PR isn't necessary as in my tests updating settings via a dict works correctly:

```python
from ultralytics import settings

settings["clearml"]=False # works
settings.update(clearml=False) # works
settings.update({"clearml": False}) # works
```

Screenshot 2024-12-21 at 22 36 05

**Comment by Y-T-G** [comment]
@glenn-jocher Yes, dict update works fine. But the PR is to check if someone uses an invalid value to update the settings when passing a dict.

In the main branch, using passing wrong keys of values throws no error:

```python
In [3]: from ultralytics import settings

In [4]: settings.update({"blabla": "blabla"}) 

In [5]: print(settings)
JSONDict("/root/.config/Ultralytics/settings.json"):
{
  ...
  "wandb": true,
  "vscode_msg": true,
  "blabla": "blabla"
}
```

In the PR, this would fail:
```python
In [2]: settings.update({"blabla": "blabla"})
--------------------------------------------------------
KeyError               Traceback (most recent call last)
Cell In[2], line 1
----> 1 settings.update({"blabla": "blabla"})

File /ultralytics/ultralytics/utils/__init__.py:1246, in SettingsManager.update(self, *args, **kwargs)
   1244 for k, v in kwargs.items():
   1245     if k not in self.defaults:
-> 1246         raise KeyError(f"No Ultralytics setting '{k}'. {self.help_msg}")
   1247     t = type(self.defaults[k])
   1248     if not isinstance(v, t):

KeyError: "No Ultralytics setting 'blabla'. \nView Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'\nUpdate Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings."
```

**Comment by glenn-jocher** [comment]
@Y-T-G oh I see. Ok then we probably want to update `SettingsManager` directly to better override the base `dict` update methods, as when I tested the PR the normal dict update of `settings["key"]=value` isn't passing through the checks.

**Comment by UltralyticsAssistant** [comment]
🌟 **Your PR Has Been Merged!** 🌟  

Huge thanks to @Y-T-G, @glenn-jocher, and @codecov for your outstanding contributions! Your expertise in improving code quality, refining error handling, and making the Ultralytics library more intuitive and robust is truly appreciated. 

Every line of code you've touched in this PR speaks volumes—providing developers with better tools to debug, manage configurations, and achieve their goals more effortlessly. The improvements to `JSONDict`, streamlined URL handling, and enriched error messaging are not just technical upgrades—they’re steps towards empowering innovation and productivity for everyone who depends on this library. 🚀  

As Marcus Aurelius once said, *"If it is not right, do not do it; if it is not true, do not say it. Let your every deed be done with integrity."* Your attention to detail and commitment to excellence embody these words, and your work here is a meaningful leap toward a more seamless and efficient user experience.

Thank you for pouring your hearts, minds, and skills into this! Your contributions don’t just strengthen the library—they inspire others to build, create, and strive for excellence. ❤️ Keep being amazing! 👏

**Pull request merged**
