### PR TITLE
adds check_requirements in patches for torch_save

### LINKED ISSUE #7468: bug
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

I got an error when running the test code yolo classify val model=runs/classify/train10/weights/best.pt: runs/classify/train10/weights/best.pt appears to require 'dill', which is not in ultralytics requirements .
AutoInstall will run now for 'dill' but this feature will be removed in the future.

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Burhan-Q**
Possible fix for #7468 

[7468 Ultralytics CI](https://github.com/ultralytics/ultralytics/actions/workflows/ci.yaml)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced dependency management and patched `torch_save` function for better usability.

### 📊 Key Changes
- Introduced a check for `dill` requirement when the `pickle_module` is specified in `torch_save` arguments.
- Removed the previous try-except block for importing `dill` and replaced it with a requirement check, streamlining the import process.

### 🎯 Purpose & Impact
- **Purpose**: The changes are aimed at improving the code's robustness when custom serialization (`pickle_module`) is needed in saving PyTorch models.
- **Impact**: Users specifying a custom `pickle_module` for serialization will have `dill` automatically checked and installed if necessary, enhancing user experience by managing dependencies more efficiently. 🔄 Users who do not use custom serialization will not experience any impact, maintaining backward compatibility.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q thanks for the PR but we shouldn't need this package, it's not a requirement and no models should require it.

Do you know if the error is reproducible?

**Comment by glenn-jocher** [comment]
The dill addition was because a user was saying he'd prefer it to be used if it is available, but we don't want to force users to use it.

**Comment by glenn-jocher** [comment]
@fcakyon do know if the `dill` package is used by the new classification models somehow?

**Comment by glenn-jocher** [comment]
@Burhan-Q I've tested classification inference for all 5 YOLOv8.1 -cls models in an environment without `dill`, Colab, and everything seems fine, so unless there's a reproducible bug I don't think we should implement any changes here that automatically install un-needed dependencies on users systems. 

Screenshot 2024-01-11 at 20 51 25

**Comment by glenn-jocher** [comment]
Yeah I've seen things also. Maybe we could do a try except that catches only the dill issues and then installs dill?

**Comment by glenn-jocher** [comment]
@Burhan-Q there's also an exponential backoff PR in https://github.com/ultralytics/ultralytics/pull/7509 that affects the same function, strange that we received two so closely together. 

We could implement this also. If we allow for 3 with i.e. 0.5, 1.0, 2.0s gaps that would add 3.5s to an actual error. What do you think?

**Comment by Burhan-Q** [comment]
@glenn-jocher yeah that sounds good. Probably makes sense to go with #7509 instead of this PR

**Pull request closed without merging**
