### PR TITLE
fix len(masks) == 0 && classify out_features

### LINKED ISSUE #1073: RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 1152, 1152]
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Here is an error I get when training a segmentation model using DDP. I have not tested on one GPU but given I have had various issues with DDP, I thought maybe this is related to DDP as well.

File "/home/ubuntu/.config/Ultralytics/DDP/_temp_qo3qf6pr140061986570928.py", line 6, in <module>
    trainer.train()
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 187, in train
    self._do_train(RANK, world_size)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/ultralytics/yolo/engine/trainer.py", line 306, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/train.py", line 43, in criterion
    return self.compute_loss(preds, batch)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/ultralytics/yolo/v8/segment/train.py", line 91, in __call__
    masks = F.interpolate(masks[None], (mask_h, mask_w), mode="nearest")[0]
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/nn/functional.py", line 3922, in interpolate
    return torch._C._nn.upsample_nearest2d(input, output_size, scale_factors)
RuntimeError: Non-empty 4D data tensor expected but got a tensor with sizes [1, 0, 1152, 1152]
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 50792 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 50793 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 50794 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 50795 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 50796 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 50797 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 50798 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 7 (pid: 50799) of binary: /home/ubuntu/mambaforge/bin/python
Traceback (most recent call last):
  File "/home/ubuntu/mambaforge/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/ubuntu/mambaforge/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/run.py", line 766, in <module>
    main()
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/mambaforge/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 

### Additional

_No response_

### LINKED ISSUE #1094: Incorrect number of classes with multi-gpu training in classifier
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training, Multi-GPU

### Bug

When training yolov8 classifers with 
```
yolo classify train data=mnist160 model=yolov8n-cls.pt epochs=3 imgsz=64
```
, I could get a model with 10 classes. While training with multiple gpus as
```
yolo classify train data=mnist160 model=yolov8n-cls.pt epochs=3 imgsz=64 device=0,1
```
, the output shape of `best.pt` is 1000 (`out_features`) as the following image.

image

### Environment

- YOLOv8: Ultralytics YOLOv8.0.43 🚀 Python-3.10.8 torch-1.13.1 CUDA:0 (NVIDIA A100 80GB PCIe, 81085MiB)        
                                                      CUDA:1 (NVIDIA A100 80GB PCIe, 81085MiB)
- Python: 3.10.8
- OS: Ubuntu 18.04.6 LTS

### Minimal Reproducible Example

```
yolo classify train data=mnist160 model=yolov8n-cls.pt epochs=3 imgsz=64 device=0,1
```

### Additional

It is frustrating that even the output number of classes is 1000, the output log still contains 
```
Overriding model.yaml nc=1000 with nc=10
```

image

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
@glenn-jocher @AyushExel 
- fixed the `RuntimeError: Non-empty 4D data tensor expected...` error when `overlap_mask=False` + `mask_ratio != 4` + there're no objects in one batch while training.
- fixed the mismatch of the number of class when training classify with DDP mode

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved model setup in classification and refined loss computation in segmentation training for Ultralytics YOLOv8.

### 📊 Key Changes
- Added a line to reshape output layers in YOLOv8 classification training script.
- Refactored the segmentation loss calculation in YOLOv8, optimally positioning mask loss calculations.

### 🎯 Purpose & Impact
- Ensures classification models' output layers match the number of classes (`nc`) in the classification problem.
- Clarifies segmentation training code for better understanding and potentially improves execution by reorganizing loss calculations.
- These updates may lead to more accurate models and a smoother development experience when using Ultralytics YOLOv8 for classification and segmentation tasks. 🎓👍

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel  I tested classify after this commit [https://github.com/ultralytics/ultralytics/pull/1093/commits/703e020479c12451bff9005a325e26ffb50d9f78](https://github.com/ultralytics/ultralytics/pull/1093/commits/703e020479c12451bff9005a325e26ffb50d9f78) and it works fine to me. But I don't really know every details of classify task so please take a look at this one and make sure it makes senses to you guys.

**Comment by mehran66** [comment]
I can confirm that after using the updated code by @Laughing-q in this PR, my segmentation training runs all fine.

**Comment by glenn-jocher** [comment]
@Laughing-q one way to verify changes to different tasks is to review their benchmarks. There is not hard fail right now, but the cls benchmarks on imagenet10 should return about 0.71, so in the future I'll add hard fails if any of the cls val results drop below i.e. 0.70.

This will be great because for the first time we'll be testing that changes are not creating silent errors / impacting val results. For this PR the ClassificationModel Benchmarks are here, they look good. This does not include training, only val of official models, but it's the best way to check right now. In the future I'll add a train-val step with hard fails on the trained accuracy on a scheduled CI that may take several hours with more extensive tests.

https://github.com/ultralytics/ultralytics/actions/runs/4240610281/jobs/7369822698
Screenshot 2023-02-23 at 07 36 38

**Comment by glenn-jocher** [comment]
@Laughing-q PR merged!

**Pull request merged**
