### PR TITLE
Fix `mps.empty_cache()` for macOS without MPS

### PR DESCRIPTION
**Pull request by Skillnoob**
If PyTorch CPU is installed on a MacOS system and the trainer runs `torch.mps.empty_cache()`, it will crash due to the backend not being available.
It should also only be executed when the `mps` device is actually selected.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced memory management for Apple's MPS devices in training.

### 📊 Key Changes
- Added a condition to clear memory caches specifically for MPS device types on macOS.

### 🎯 Purpose & Impact
- **Improved Performance**: Helps manage memory effectively for users on macOS using MPS devices, preventing potential slowdowns or memory errors. 
- **User-Specific Optimization**: Ensures optimal training performance on Apple hardware, enhancing overall user experience. 🖥️🚀

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Skillnoob, thank you for your PR on the `ultralytics/ultralytics` repository! 🚀 

We're excited to see your contribution for improving memory management on MacOS with MPS devices. Here's a quick checklist to ensure everything is in perfect order:

- ✅ **Purpose Clarity**: Your PR description effectively explains the need to conditionally clear the MPS cache. Ensure any related issues are linked for context.
- ✅ **Stay Synced**: Confirm that your branch is up to date with the `main` branch. Use `git pull upstream main` to fetch and merge changes if needed.
- ✅ **Passing CI Checks**: Please verify that all Continuous Integration (CI) checks are successful. If you encounter any failures, address them promptly.
- ✅ **Documentation**: Check if the documentation needs updates regarding MacOS and MPS usage, and make sure those are included.
- ✅ **Add Tests**: If applicable, ensure there are tests covering this change to avoid regressions in future updates.
- ✅ **Sign the CLA**: Ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first PR. Comment "I have read the CLA Document and I sign the CLA" if you haven’t already done so.
- ✅ **Minimize Changes**: Keep changes minimal and focused solely on the bug - great job here!

For additional information, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have questions or need further assistance, feel free to add a comment in the PR. An Ultralytics engineer will review your submission soon. Thank you for contributing to Ultralytics! 🌟

**Comment by Oil3** [comment]
thanks for the fix, I didn't have that issue but I really had been looking for a way to explicitly target MPS, and ` if self.device.type == "mps"` was so right in front of m that I didn't see it thanks.

Question: do you mean you have MPS installed and feel the crash while training on CPU, or do you rather mean you do not have MPS installed?
I ask because I have MPS installed, and did not have the bug when I tried training various epochs on device=cpu.

**Comment by Skillnoob** [comment]
@Oil3 It happens when PyTorch CPU is installed. Since it currently only checks if you are on a MacOS device it will error out.
To be sure I made it only when the `mps` device is actually selected, as `select_device` handles that already.
https://github.com/ultralytics/ultralytics/blob/02e995383de4ee3754ceb96a993f91b070c71e77/ultralytics/utils/torch_utils.py#L210-L213

**Comment by Oil3** [comment]
amazing, i tested on my mps setups and displays mem good as well as 0 on cpu

**Comment by glenn-jocher** [comment]
@Oil3 looks good! Thank you for your contributions :)

**Pull request merged**
