### PR TITLE
Update information about YOLOv6 pretrained weights

### PR DESCRIPTION
**Pull request by Y-T-G**
There are no pretrained weights for YOLOv6 in Ultralytics, but the table lists `.pt` files.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Improved YOLOv6 documentation to clarify usage and showcase updated model configurations. 📖✨  

### 📊 Key Changes  
- Refined explanation for using YOLOv6 `*.yaml` files to build models in Python. 🧑‍💻  
- Updated the model table to replace `.pt` weights with `.yaml` configuration filenames for clarity. ✅  
- Added the new YOLOv6-X model to the table with detailed capabilities. 🚀  

### 🎯 Purpose & Impact  
- **Enhanced Clarity**: Simplifies understanding of how to use YOLOv6 models and their configurations. 🛠️  
- **Consistency**: Aligns documentation with updated filenames and usage patterns. 🔄  
- **User Empowerment**: Introduces users to the new YOLOv6-X variant, expanding model options for object detection tasks. 🎉

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Continuous Integration (CI) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our Contributor License Agreement (CLA) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

This is an automated response to help streamline the review process. An Ultralytics engineer will review your PR and assist further as soon as possible. Thank you for contributing to Ultralytics! 🚀

**Comment by Laughing-q** [comment]
@Y-T-G hmmm I thought it's ok we have the pt there since we don't provide the links for it like we do for other models i.e. 
pic-241230-1427-26

wait probably for better consistency and less misleading we should update the `Pre-trained Weights` to `Filenames`:
hvBGnXs2YK
UMHzwBMwO4

**Comment by Y-T-G** [comment]
@Laughing-q Alright, sure. Maybe I can change them to `.yaml` too instead?

**Comment by Laughing-q** [comment]
@Y-T-G yeah make sense to me

**Comment by UltralyticsAssistant** [comment]
✨ Exciting news—this PR is officially merged! 🎉 Huge thanks to @Y-T-G for leading the charge, with fantastic contributions from @Laughing-q and @glenn-jocher. Your efforts have truly elevated the YOLOv6 documentation, clarifying configurations and empowering users with the new YOLOv6-X model. 🚀📖  

As Marcus Aurelius once said, *"What we do now echoes in eternity."* Your work here will ripple through the community, making advanced AI more accessible and inspiring creators around the world. Thank you for making a difference! 🌟

**Pull request merged**
