### PR TITLE
Disable augmentators when not needed

### PR DESCRIPTION
**Pull request by r-romito**
Fixes this [issue](https://github.com/ultralytics/ultralytics/issues/1960)

### Summary
🌟🐛📝

This pull request enhances and fixes the data augmentation module for YOLO. It enables selective application of augmentations based on `hyp` parameters and corrects a syntax error in `augment.py`.

> _Unleash the beast of YOLO_
> _With data augmentation_
> _Conditional and flexible_
> _Based on the `hyp` dictation_

### Walkthrough
*  Conditionally apply data augmentations based on `hyp` values in `v8_transforms` ([link](https://github.com/ultralytics/ultralytics/pull/2003/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9L665-R671))
*  Fix syntax error in `RandomPerspective` call in `augment.py` ([link](https://github.com/ultralytics/ultralytics/pull/2003/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9L675-R678))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improve YOLOv8 image augmentation by making transforms configurable based on hyperparameters.

### 📊 Key Changes
- Modified the composition of image transformations.
- Made each transformation conditional on specific hyperparameters.
- Added a fallback to basic transformation if no conditions are met.

### 🎯 Purpose & Impact
- **Customization:** Allows users to enable or disable specific augmentations like Mosaic, CopyPaste, or RandomPerspective with greater flexibility.
- **Efficiency:** Reduces unnecessary processing by applying only relevant transformations.
- **User Control:** Empowers users to better tailor their model training, potentially improving training performance and accuracy.

### CODE REVIEW

**Comment by ExtReMLapin** [comment]
have you ran any cpu benchmark ?

**Comment by glenn-jocher** [comment]
@ExtReMLapin yes, we have run CPU benchmarks for YOLOv8. Our team has made significant improvements to the CPU performance since the initial release, and we continually optimize our code to achieve better results. We encourage users to experiment with different hardware configurations and settings to find the best performance and accuracy for their use case.

**Comment by ExtReMLapin** [comment]
Thanks for your answer glenn, but I meant with this pull request, vs without it

**Comment by pderrenger** [comment]
@ExtReMLapin Apologies for the confusion. At this time, we haven't run specific CPU benchmarks for this pull request. However, we continuously evaluate performance improvements, and your feedback on the performance impact of this pull request would be greatly appreciated. Thank you for your contribution!

**Comment by samsheff** [comment]
Hey @r-romito @glenn-jocher ! 

Is there any update on this? This would be really helpful to a lot of people, including me. Let me know if I can contribute somehow or help get this done.

Thanks!

**Comment by glenn-jocher** [comment]
Hi @samsheff,

Thank you for your interest and willingness to contribute! We appreciate your patience. Currently, there hasn't been a specific update on this issue. However, your offer to help is very much welcomed.

To move forward, could you please provide a minimum reproducible code example if you haven't already? This will help us understand the issue better and work towards a solution. You can find more details on how to create one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example). 

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. Sometimes, updating these packages can resolve unexpected issues.

If you have any specific ideas or code contributions, feel free to share them. Your collaboration can significantly speed up the process for everyone involved.

Thanks again for your support and enthusiasm! 😊

**Review by ambitious-octopus — COMMENTED** [review]
A decision on this has already been made in #15985. PR closed.

**Comment by sehyun-lee288** [comment]
Suggestion for the documentation. 

Please explicitly mention in the documentation that thin objects may be filtered out during training label preprocessing, which can cause some labels to be missing in the training set but not in the validation set. This behavior is not always obvious, especially when data augmentation is disabled `scale=0, translate=0, degrees=0, translate=0, shear=0, perspective=0` and can cause confusion for users working with thin objects.
Adding a clear note about this limitation would help users avoid unnecessary debugging and understand the root cause when some labels are missing for thin objects.

**Comment by glenn-jocher** [comment]
@cogito288 excellent suggestion! You're absolutely right that this behavior with thin objects being filtered during preprocessing can be confusing, especially when augmentations are disabled. This would be a valuable addition to our [data augmentation documentation](https://docs.ultralytics.com/guides/yolo-data-augmentation/).

Would you be interested in submitting a documentation PR to add this clarification? You can contribute by following our [contributing guide](https://docs.ultralytics.com/help/contributing/) - documentation improvements are always welcome and help the entire community avoid these debugging headaches.

**Pull request closed without merging**
