### PR TITLE
Ensure CenterCrop is consistent with the torchvision CenterCrop

### PR DESCRIPTION
**Pull request by timstokman**
This PR ensures the CenterCrop is consistent with torchvision centercrop, see: #3029 

If we start with this image (32x100):

person

It will now be preprocessed like this (with imgsz 24, 50, 124):

person_24
person_50
person_124

### Summary
🐛🚀🧪

The pull request adds a new test function for `classify_transforms` and improves the `CenterCrop` class to handle large crop sizes and avoid off-by-one errors. The changes aim to enhance the image preprocessing for classification tasks.

> _Oh we are the coders of the `CenterCrop` class_
> _We pad and we round to make our images pass_
> _We test all the cases with `pytest` and `numpy`_
> _And we sing as we work on the classify task_

### Walkthrough
*  Add and modify tests for image preprocessing for classification tasks in `test_engine.py` ([link](https://github.com/ultralytics/ultralytics/pull/3050/files?diff=unified&w=0#diff-882061b431ed3670f5b4a045ae0f4e1f140cc785db77fe77585b820bdec6f73dL5-R10), [link](https://github.com/ultralytics/ultralytics/pull/3050/files?diff=unified&w=0#diff-882061b431ed3670f5b4a045ae0f4e1f140cc785db77fe77585b820bdec6f73dR130-R138))
*  Improve the `CenterCrop` class in `augment.py` to handle larger target sizes and avoid off-by-one errors ([link](https://github.com/ultralytics/ultralytics/pull/3050/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9L882-R896))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhances image preprocessing for classification with dynamic resize and padding support in Ultralytics's YOLO package.

### 📊 Key Changes
- Imported additional modules such as `numpy` and `pytest` for enhanced testing functionality.
- Added a new pytest function `test_preprocessing_classify` to validate the updated preprocessing behavior.
- Modified the `__call__` method in the image processing class to handle images where padding might be necessary.

### 🎯 Purpose & Impact
- The purpose of these changes is to improve the robustness of the image preprocessing step in classification tasks, especially when input images are not the exact size expected by the model.
- Users can now expect the model to handle varying image sizes more gracefully by adding padding when the desired crop is larger than the input image, thus avoiding any potential issues with aspect ratio and sizing.
- The added test ensures that the preprocessing step is thoroughly checked for correctness, which enhances the reliability of the software.

### CODE REVIEW

**Comment by timstokman** [comment]
Not entirely sure why TensorRT is failing here. Is this pipeline relevant?

**Comment by glenn-jocher** [comment]
@timstokman thanks for your question! In regards to TensorRT failing, it is possible that the TensorRT engine you are trying to load may not be compatible with the version of TensorRT installed on your system. Additionally, some model architectures may not be supported by TensorRT, so it may be worth double checking that the model architecture can actually be optimized by TensorRT. 

As for the pipeline you mentioned, it would be helpful to provide more information on what pipeline is failing and at which stage. This will help with debugging and providing a more accurate answer to your question.

**Comment by glenn-jocher** [comment]
@timstokman maybe a glitch, I'll re-run the CI.

**Comment by timstokman** [comment]
So, it doesn't look like it's a glitch. Still a little strange though. This code is benchmarking existing checkpoints with the new code, and it only fails with the exported TensorRT model.

It might make sense that a model that is trained with one preprocessing method doesn't perform quite as well with another method if it's not retrained first. But it only seems to happen with TensorRT here. If that was the issue I would've expected to see that happen with all the exports. 

The displayed model-size is 0MB, and all the results are NaN, so that suggests an export error or inability to test TensorRT in that pipeline. Except other PRs also have that issue when executing the pipeline: https://github.com/ultralytics/ultralytics/actions/runs/5174273714/jobs/9320408573?pr=3013 , and they're not failing the test.

So either:

* My PR is triggering a failure in a already wobbly test (I'm seeing a lot of strange results here for the same pipeline in other PRs or on main)
* The preprocessing code is interacting strangely with the TensorRT runtime here and triggering some sort of failure that's not happening for other runtime exports

**Comment by glenn-jocher** [comment]
@timstokman checked this out. The CI fail is unrelated to TensorRT, all export formats are failing due to a drop in classification accuracy with this PR:
```
AssertionError: HARD FAIL: one or more metric(s) < floor 0.61
```

Main branch achieves CI classification accuracy of >0.61 for all formats, so this CI is here to catch changes such as this that affect model accuracy.

**Comment by timstokman** [comment]
Ah, that makes more sense. The logs were a little unclear. We're changing the preprocessing here, for some images that'll give drastically model input. So given the model checkpoint was trained with the old preprocessing method, and now validated with a different preprocessing method.. That'll give rise to some accuracy drops.

I ran a quick hyperparameter search on my own dataset (has many different sizes and aspect ratios):
* Letterbox + Resize OR just resize as preprocessing seem to work best
* Letterbox without resize or the torchvision centercrop have drops in accuracy
* The current yolov8 centercrop is worst

Depending on the dataset this is a hyperparameter with a decent effect size.

I suspect that a PR with the preprocessing fully configurable might be easier to merge. No need to retrain checkpoints before we merge.

**Comment by glenn-jocher** [comment]
@timstokman thanks for the feedback! You're correct - this PR changes the preprocessing, which is expected to affect model performance. We're doing our best to improve performance across our test suite, but it's possible that some changes won't work as well for all datasets. 

Regarding making preprocessing fully configurable, while it's an interesting idea, it would require retraining models for every new pre-processing method. We'll keep this in mind for future updates. Thanks again for the input!

**Comment by timstokman** [comment]
@glenn-jocher See #3029 for context for this change. What I'm going to do is:

* Close this PR for now
* Create a PR that:
  * Adds the new suggested preprocessing options in the linked issue #3029 
  * Keep the current classification preprocessing setup as default so there's no change to the accuracy of the checkpoint

**Comment by glenn-jocher** [comment]
@timstokman hi there! Thank you for reaching out. I understand that you'd like to add new preprocessing options in line with the suggestions in issue #3029. To address your concern, we will be closing this PR for now and opening a new PR that adds the new preprocessing options you've suggested. 

In this new PR, we will ensure that the current classification preprocessing setup remains the default option. This will ensure that there is no change to the accuracy of the checkpoint. Thank you for your input and please let us know if you have any further questions or concerns.

**Pull request closed without merging**
