### PR TITLE
Pin `duckdb<=0.9.2` to avoid 0.10.0 errors

### PR DESCRIPTION
**Pull request by AyushExel**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Adjusting database dependencies to prevent bugs.

### 📊 Key Changes
- Specified a maximum version (`<=0.9.2`) for the `duckdb` dependency.
- Removed a commented-out dependency `scikit-learn==0.19.2`.

### 🎯 Purpose & Impact
- 🛠️ **Bug prevention**: The change guards against a known bug in `duckdb` version `0.10.0`, ensuring stability.
- 🔄 **Current compatibility**: Users' projects will not accidentally upgrade to a buggy version of `duckdb`, preserving the integrity of their data operations.
- 🧹 **Clean-up**: Eliminating the commented-out dependency makes the configuration cleaner and more maintainable.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel thanks for the PR! Should we raise a bug report with duckdb too?

**Comment by glenn-jocher** [comment]
It looks like even their own CI is failing...
https://github.com/duckdb/duckdb

Screenshot 2024-02-13 at 19 32 49

I think let's try to loosen the pin a bit to <= to let the pip constraint resolver have some wiggle room, otherwise it may be backed into a corner in busier environments. What do you think?

**Review by glenn-jocher — APPROVED** [review]

**Comment by johnnynunez** [comment]
Duckdb must updated for python 3.12...

**Comment by glenn-jocher** [comment]
@johnnynunez thank you for the update. It's important to maintain compatibility and stability in the dependencies, and pinning `duckdb` to `<=0.9.2` is a prudent measure to avoid known issues with the `0.10.0` release. Removing outdated or commented-out dependencies also helps keep the project clean and manageable.

If anyone encounters issues related to `duckdb` or other dependencies, please feel free to raise an issue in the repository, and we'll address it as promptly as possible. Your contributions and feedback help us improve and ensure the best experience for the entire community.

**Pull request merged**
