### PR TITLE
Create InkML_to_jpg

### PR DESCRIPTION
**Pull request by frankvp11**
Hello!
I encourage you to change the things that you wish, as the file itself that I am adding is in relatively poor bunch very much so functioning condition. The reason that I made this file was because I was trying to use inkML files to train on Yolov8. However, there are no interpreters anywhere that get it the way that yolo needs it. In this file, there are three helper functions, and one main function called complete. In the complete function, it can be found that I place rectangles on the images. These are the bounding boxes, should a user want to use the bounding boxes in labels, they would need to use the converter found in utils/ops (xyxy2xywh). Essentially, calling the complete function (with the input and output directories) will create an image from an InkML file that contains the contents of the InkML (like the text) and the bounding boxes around said objects. 

If you'd like me to make more changes so that it's more robust, I'd be happy to, otherwise I'll just leave it here in the case other users could make use out of it? 

### Summary
🖋️📦📷

Added a new file `ultralytics/yolo/data/InkML_to_jpg` that contains a function to convert InkML files to JPG images with bounding boxes. This function enables using the CROHME dataset of handwritten mathematical expressions for object detection with YOLOv5.

> _`InkML` to `JPG`_
> _Bounding boxes for math expressions_
> _A tool for vision_

### Walkthrough
*  Add a function to convert InkML files to JPG images with bounding boxes ([link](https://github.com/ultralytics/ultralytics/pull/2591/files?diff=unified&w=0#diff-f35446e9fb619c7c87dd9976ea17d0869f1916a0bf33605f8f3576284931f220R1-R153)-)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of InkML to JPG conversion with bounding box functionality for handwritten data.

### 📊 Key Changes
- A new file `InkML_to_jpg` is added for converting InkML files to images.
- Parsing InkML data to extract coordinates and strokes with XML parsing.
- Generating images from strokes and saving them as JPG files.
- Extracting trace data from InkML files, sorting, and grouping by IDs.
- Calculating minimum and maximum coordinates for trace groups (bounding box).
- A complete function that overlays bounding boxes on the generated images.
- Example usage code demonstrating the entire process from InkML to image with boxes.

### 🎯 Purpose & Impact
- **Purpose:** This addition is meant to facilitate the pre-processing of handwritten data in the InkML format, making it more accessible for image processing and machine learning tasks.
- **Impact to users:**
  - Allows users to convert complex InkML files to widely-used JPG format.
  - Automated extraction of bounding boxes will be helpful for tasks such as character recognition, data labeling, and dataset creation in handwriting recognition projects.
  - Enhances the capabilities of Ultralytics software by adding support for a new data format, potentially expanding its user base.

### CODE REVIEW

**Comment by frankvp11** [comment]
I have read the CLA Document and I sign the CLA

**Comment by frankvp11** [comment]
recheck

**Comment by glenn-jocher** [comment]
@frankvp11 hello,

Thank you for reaching out to us. The `recheck` command in YOLOv8 is used to re-evaluate certain test datasets on previously saved checkpoints. This can be useful for double-checking results or for running tests after making changes to the code. 

To use the `recheck` command, you need to provide the path to the saved checkpoint as well as the YAML file that contains the test dataset definitions. The command will then iterate over the dataset and evaluate the model's performance on each image. 

Please let us know if you have any further questions or concerns.

Best regards,  
Glenn Jocher  
Author and Maintainer, Ultralytics YOLOv8 repo

**Comment by frankvp11** [comment]
Sorry for the late reply.
The conversion from inkML to jpg (or other image formats) is becoming increasingly useful.
I have found lots of data relating to text to be in the format of inkML. This is because of the growing use of tablets for image labelling. The problem with labelling images with a tablet is that it often times saves the annotations in this format. I have found personally multiple datasets already containing math images that were in the inkML format. I can imagine that there are quite a few more that exist besides just math equations. This would open yolov8 up to a new (albeit less commonly used) annotation format.

**Comment by glenn-jocher** [comment]
@frankvp11 hello,

The conversion from InkML to image formats such as JPG is becoming increasingly useful in the image labeling world. InkML is a growing format for image labeling, especially with the increasing use of tablets. Saving annotations in this format is a common occurrence with tablet labeling, making this type of conversion handy. 

InkML to image format conversion opens up new annotation formats that YOLOv8 can handle besides commonly used annotation formats. This makes it easier to work with datasets that contain InkML files such as those containing math equations or text. 

If you have any further questions or concerns, please feel free to ask.

Best regards,  
Glenn Jocher  
Author and Maintainer, Ultralytics YOLOv8 repo

**Pull request closed without merging**
