### PR TITLE
apply data augmentations on specific classs

### PR DESCRIPTION
**Pull request by akashAD98**
apply data augmentations while model training, lets say I want to add flip-up effect to id 2,5,7 & other class with other effects we can do this easily

### Summary
🚴‍♂️🚶‍♂️🔧

Modified `Albumentations` class to enable class-specific augmentations for COCO dataset. This aims to enhance the YOLO model's detection of person and bicycle classes.

> _We face the doom of the COCO dataset_
> _The person and the bicycle elude our sight_
> _We unleash the `Albumentations` wrath_
> _To enhance our YOLO model's might_

### Walkthrough
*  Add optional argument `aug_ids` to `Albumentations` class to specify class IDs for specific augmentations ([link](https://github.com/ultralytics/ultralytics/pull/1005/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9L551-R555))
*  Define two sets of augmentations for different classes: `T_0_1` for person and bicycle, and `T_other` for the rest ([link](https://github.com/ultralytics/ultralytics/pull/1005/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9L560-R569))
*  Create two `Compose` objects for the two sets of augmentations and assign them to `transform_0_1` and `transform_other` attributes ([link](https://github.com/ultralytics/ultralytics/pull/1005/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9L567-R585))
*  Apply different augmentations depending on the class labels of the input image and bounding boxes in `__call__` method ([link](https://github.com/ultralytics/ultralytics/pull/1005/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9R599-R621))
*  Update `LOGGER.info` statements to print the augmentations for each set separately ([link](https://github.com/ultralytics/ultralytics/pull/1005/files?diff=unified&w=0#diff-13d355434447b3961ec61d1c80bedc2b6db2d98ab0df572eb036f4e8b536aee9L567-R585))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced image augmentation in YOLOv8 using custom Albumentations. 📷✨

### 📊 Key Changes
- Introduced `aug_ids` parameter to select specific augmentations for classes.
- Defined separate augmentation sets for different class IDs.
- Improved logging for augmentation application steps.

### 🎯 Purpose & Impact
- **Customization**: Allows tailored augmentations per class, improving flexibility. 🎛️
- **Better Results**: Enhances image processing by applying suitable transformations, potentially improving model accuracy. 📈
- **User Feedback**: Improved logging ensures users are well-informed about applied augmentations. 📋

### CODE REVIEW

**Comment by AyushExel** [comment]
I don't understand a few things.
* ids are hardcoded so that'll break the default behavior and only apply augmentation to 0,1 classes.
* The default values of augmentation are changed.
* Some augmentations are commented out
* __call__ method is implemented twice

**Comment by akashAD98** [comment]
@AyushExel ill fix it

**Comment by akashAD98** [comment]
I have read the CLA Document and I sign the CLA

**Review by ambitious-octopus — COMMENTED** [review]
The idea is interesting, but the PR is invalid at this point. Closing!

**Pull request closed without merging**
