### PR TITLE
Add argument validation for export

### LINKED ISSUE #16732: export YOLO11 onnx with NMS
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I used the following code to export my model with ONNX and enabled  NMS:

`path = model.export(format="onnx", nms=True)`

However, the exported ONNX model doesn't seem to include NMS. Could you please let me know how to properly add NMS to the exported ONNX model? Additionally, what are the confidence threshold and IoU threshold values used for NMS in the official reported mAP?

### Additional

_No response_

### LINKED ISSUE #17454: Exporting model as half precision torchscript doesn't reduce the model size by half
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

image
The models exported as full precision torchscript and half precision torchscripts respectively have almost the same model size.
However, when I export the model i written in pytorch into half precision torchscript format model, the model size was reduced by half compared with the model exported as full precision torchscript.
Is there any other way to reduce the yolo model size exported as torchscipt?

### Additional

_No response_

### LINKED ISSUE #18109: The inference time of the int8 exported ONNX model is abnormal.
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When I use model.export() to convert yolov11n.pt to ONNX, I found that the inference time of the model with int8 precision is not significantly different from the model without int8 precision (based on the average inference time of n runs in the same environment).

Average inference time   (Inference count of 100)
yolov11n.onnx with int8 true: 32.57 ms
yolov11n.onnx with int8 False: 22.34 ms

Average inference time   (Inference count of 1000)
yolov11n.onnx with int8 true: 22.38 ms
yolov11n.onnx with int8 False: 22.34 ms

Is this phenomenon normal? If not, could you provide some troubleshooting ideas?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Y-T-G**
Right now, we don't check if the passed argument is valid for the format, which leads to confusion when the export goes through, but the behavior remains unaltered.

**W/O PR**
```python
In [7]: model.export(format="onnx", int8=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
WARNING ⚠️ INT8 export requires a missing 'data' arg for calibration. Using default 'data=coco8.yaml'.
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)

ONNX: starting export with onnx 1.15.0 opset 19...
ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 1.4s, saved as 'yolo11n.onnx' (10.2 MB)

Export complete (1.7s)
Results saved to /ultralytics
Predict:         yolo predict task=detect model=yolo11n.onnx imgsz=640 int8 
Validate:        yolo val task=detect model=yolo11n.onnx imgsz=640 data=/usr/src/ultralytics/ultralytics/cfg/datasets/coco.yaml int8 
Visualize:       https://netron.app
Out[7]: 'yolo11n.onnx'
```
```python
In [8]: model.export(format="onnx", nms=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)

ONNX: starting export with onnx 1.15.0 opset 19...
ONNX: slimming with onnxslim 0.1.34...
ONNX: export success ✅ 1.0s, saved as 'yolo11n.onnx' (10.2 MB)

Export complete (1.3s)
Results saved to /ultralytics
Predict:         yolo predict task=detect model=yolo11n.onnx imgsz=640  
Validate:        yolo val task=detect model=yolo11n.onnx imgsz=640 data=/usr/src/ultralytics/ultralytics/cfg/datasets/coco.yaml  
Visualize:       https://netron.app
Out[8]: 'yolo11n.onnx'
```

**W/ PR**
```python
In [10]: model.export(format="onnx", nms=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[10], line 1
----> 1 model.export(format="onnx", nms=True)

File /ultralytics/ultralytics/engine/model.py:738, in Model.export(self, **kwargs)
    730 custom = {
    731     "imgsz": self.model.args["imgsz"],
    732     "batch": 1,
   (...)
    735     "verbose": False,
    736 }  # method defaults
    737 args = {**self.overrides, **custom, **kwargs, "mode": "export"}  # highest priority args on the right
--> 738 return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)

File /ultralytics/ultralytics/engine/exporter.py:267, in Exporter.__call__(self, model)
    264 self.device = select_device("cpu" if self.args.device is None else self.args.device)
    266 # Argument compatibility checks
--> 267 validate_args(fmt, self.args)
    268 if imx and not self.args.int8:
    269     LOGGER.warning("WARNING ⚠️ IMX only supports int8 export, setting int8=True.")

File /ultralytics/ultralytics/engine/exporter.py:159, in validate_args(format, passed_args)
    157 not_default = getattr(passed_args, arg, None) != getattr(DEFAULT_CFG, arg, None)
    158 if not_default:
--> 159     assert arg in valid_args, f"ERROR ❌️ argument '{arg}' is not supported for format='{format}'"

AssertionError: ERROR ❌️ argument 'nms' is not supported for format='onnx'
```
```python
In [5]: model.export(format="onnx", int8=True)
Ultralytics 8.3.49 🚀 Python-3.10.14 torch-2.5.1+cu124 CPU (AMD EPYC 7V12 64-Core Processor)
---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
Cell In[5], line 1
----> 1 model.export(format="onnx", int8=True)

File /ultralytics/ultralytics/engine/model.py:738, in Model.export(self, **kwargs)
    730 custom = {
    731     "imgsz": self.model.args["imgsz"],
    732     "batch": 1,
   (...)
    735     "verbose": False,
    736 }  # method defaults
    737 args = {**self.overrides, **custom, **kwargs, "mode": "export"}  # highest priority args on the right
--> 738 return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)

File /ultralytics/ultralytics/engine/exporter.py:267, in Exporter.__call__(self, model)
    264 self.device = select_device("cpu" if self.args.device is None else self.args.device)
    266 # Argument compatibility checks
--> 267 validate_args(fmt, self.args)
    268 if imx and not self.args.int8:
    269     LOGGER.warning("WARNING ⚠️ IMX only supports int8 export, setting int8=True.")

File /ultralytics/ultralytics/engine/exporter.py:159, in validate_args(format, passed_args)
    157 not_default = getattr(passed_args, arg, None) != getattr(DEFAULT_CFG, arg, None)
    158 if not_default:
--> 159     assert arg in valid_args, f"ERROR ❌️ argument '{arg}' is not supported for format='{format}'"

AssertionError: ERROR ❌️ argument 'int8' is not supported for format='onnx'
```

Closes https://github.com/ultralytics/ultralytics/issues/18109
Closes https://github.com/ultralytics/ultralytics/issues/16732
Closes https://github.com/ultralytics/ultralytics/issues/17454

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Introduced argument validation for export formats to ensure compatibility during model export.  

### 📊 Key Changes  
- Added a new `validate_args` function to check if export arguments are compatible with the selected export format.  
- Defined a list of supported arguments for multiple export formats (e.g., TorchScript, ONNX, CoreML).  
- Updated documentation to include the new `validate_args` function.  
- Removed Sony IMX500 documentation reference from integrations.  

### 🎯 Purpose & Impact  
- 📋 **Improved robustness**: Ensures incompatible arguments are flagged early, preventing errors during export.  
- ✅ **Better user guidance**: Clear checks for argument compatibility reduce confusion for users.  
- 🚀 **Streamlined model exports**: Enhances reliability across different export formats, improving overall user experience.  
- 📉 **Minor impact on docs**: The Sony IMX500 integration reference was removed, signaling it may no longer be supported.  

This update improves reliability for developers and users exporting models across various formats! 🌟

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For additional tips and guidance, refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). 

💡 A couple of suggestions for this PR to ensure smooth collaboration:
1. Confirm that the updated argument validation logic handles edge cases gracefully (e.g., default behaviors when no arguments are passed).
2. If not already included, please provide a minimum reproducible example (MRE) that demonstrates the enhancements or resolves the reported issues, so we can easily test your changes.

Thank you for your contribution towards improving the export functionality! An Ultralytics engineer will review this PR and assist shortly. 🚀✨

**Comment by Y-T-G** [comment]
@ambitious-octopus I think we are using the same branch 👀

**Comment by glenn-jocher** [comment]
@Y-T-G seems like a mixup with #18185?

**Comment by Y-T-G** [comment]
@glenn-jocher I created it again so that @ambitious-octopus could debug this one. It's adding commits that I didn't push. It happened again with the new PR. I didn't push the merge commits and changes to mkdocs.

**Pull request closed without merging**
