### PR TITLE
Enable `result.show()` for Jupyter notebooks

### LINKED ISSUE #16572: no "view" rule for type "image/png" on jupyter notebook
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi :)
I'm trying to plot results object in a Jupyter Notebook, but I've this error.
image

### Additional

_No response_

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhances image display functionality in Jupyter notebooks.

### 📊 Key Changes
- Added `IS_JUPYTER` check to differentiate image display handling.
- Integrated `check_requirements` to ensure IPython is available in Jupyter notebooks.
- Modified `show` method to use IPython's display in Jupyter environments.

### 🎯 Purpose & Impact
- 🖥️ **Improved Jupyter notebook experience**: Automatically displays images using IPython, enhancing user interaction and visualization in notebooks.
- 📦 **Dependency management**: Ensures required packages are present, reducing errors related to missing dependencies in Jupyter.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @glenn-jocher, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to assist you in ensuring a smooth integration of your work. An Ultralytics engineer will also review your submission soon.

Please go through the following checklist to ensure all requirements are met:

- ✅ **Define a Purpose**: Clearly state the purpose of your fix or feature in the PR description and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear and follow the project's conventions.
- ✅ **Synchronize with Source**: Verify your PR is up to date with the `main` branch. If needed, update by clicking 'Update branch' or running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Check that all relevant [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. Address any failures accordingly.
- ✅ **Update Documentation**: If needed, update the relevant [documentation](https://docs.ultralytics.com) for any changes or new features.
- ✅ **Add Tests**: Include or update tests to cover any new changes, and ensure that they all pass.
- ✅ **Sign the CLA**: Confirm you've signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/). If it’s your first PR, mention "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Focus your changes on what is necessary for your feature or bug fix. 
   > _"Hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For detailed guidance, refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions or need further clarification, feel free to leave a comment.

Thank you for your valuable contribution to Ultralytics! 🌟🎉

**Comment by glenn-jocher** [comment]
Screenshot 2024-09-30 at 18 27 28

**Review by ambitious-octopus — APPROVED** [review]
I was solving the same problem, this solution seems better than `from google.colab.patches import cv2_imshow`

**Comment by glenn-jocher** [comment]
@ambitious-octopus yes this was the strategy I had for YOLOv5 and it looks like I forgot to port this over when we did YOLOv8. 

This should let notebook users show images (Colab and other notebooks too like Kaggle etc.)

**Pull request merged**
