### PR TITLE
[Example] Add example application for .NET

### PR DESCRIPTION
**Pull request by dme-compunet**
### Summary
:sparkles::computer::camera:

Added a new YOLO example application in C# using ONNX and ImageSharp to `examples/README.md`. This demonstrates how to use YOLO with different technologies and frameworks.

> _`YOLO` in C sharp_
> _Using `ONNX` and `ImageSharp`_
> _A new example_

### Walkthrough
* Add a new example of YOLO with C# and ONNX to the table in `examples/README.md` ([link](https://github.com/ultralytics/ultralytics/pull/3311/files?diff=unified&w=0#diff-49aaa2819e35a856818ecec8c9fa7e1c79ad028d3f44bd749736353cfb51bac9L8-R11))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
New YOLO .NET ONNX example with ImageSharp is added to the Ultralytics examples list.

### 📊 Key Changes
- Added a new example link for YOLO .NET ONNX ImageSharp in the examples README.

### 🎯 Purpose & Impact
- Expands application examples to include C# developers using the ImageSharp library.
- Offers a new resource for developers interested in implementing YOLO with C# and .NET, potentially increasing the adoption and versatility of YOLO models.
- Provides a direct link to Compuet's repository, where users can find a practical usage of YOLOv8 with the ImageSharp library for image processing in .NET environments.

### CODE REVIEW

**Comment by dme-compunet** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@dme-compunet hi, thank you for your contribution!

I have one request. Can you please correct the capitalization on your repo (and in your README and code comments) to "YOLOv8"? Thanks!

Once this is done let me know and we'll get this merged :)

**Comment by dme-compunet** [comment]
Hi @glenn-jocher, you are welcome!
In code I preferred sticking to the C# naming conventions, but in prose I made sure to write “YOLOv8”

**Comment by glenn-jocher** [comment]
@dme-compunet hi there. I took a look through the repo. YOLOv8 is an acronym that stands for You Only Look Once version 8, so our branding guidelines require uppercase YOLO and lowercase v. See https://ultralytics.com/brand for details.

It would be great if you could update these locations and any others in comments/text. I understand the code capitalization can vary but please update the text locations, thank you!

**Comment by dme-compunet** [comment]
I have now renamed the repo to YOLOv8, @glenn-jocher is it okay now?

**Comment by glenn-jocher** [comment]
@dme-compunet hi there! Thank you for making the updates. Renaming the repo to "YOLOv8" aligns with our branding guidelines. Great job! Your contribution is greatly appreciated. If you have any more questions or need further assistance, feel free to ask. We're here to help. Keep up the fantastic work!

**Comment by glenn-jocher** [comment]
@dme-compunet PR merged! Thank you for your contributions :)

**Pull request merged**
