### PR TITLE
Fix TFLite Segment mask rows 1-4 normalization

### LINKED ISSUE #9385: tflite inference in segmentation wrongly scales the first 4 upper pixels of the image
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

The faulty code is in forward of`autobackend.py` for tflite as it updates **each** output by denormalizing. Instead it should not affect the mask output:

```python
for output in self.output_details:
    x = self.interpreter.get_tensor(output["index"])
    if integer:
        scale, zero_point = output["quantization"]
        x = (x.astype(np.float32) - zero_point) * scale  # re-scale
    if x.ndim > 2:  # if task is not classification
        # Denormalize xywh by image size. See https://github.com/ultralytics/ultralytics/pull/1695
        # xywh are normalized in TFLite/EdgeTPU to mitigate quantization error of integer models
        x[:, [0, 2]] *= w
        x[:, [1, 3]] *= h
    y.append(x)
```

You can see the problem in this picture, it only affects the very top of the masks, so it is often a silent problem. In the following I visualize just one of the 32 masks:

Screenshot from 2024-03-28 17-54-53

### Environment

only for tflite in segmentation

### Minimal Reproducible Example

self explanatory

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by charlesollion**
Update autobackend.py: fix ndim ==3 for tflite to exclude mask tensor
fixes #9385 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved tensor handling for non-classification tasks in neural network backend.

### 📊 Key Changes
- Adjusted condition for handling tensor dimensions in callbacks: the code now precisely targets tensors with exactly 3 dimensions instead of more than 2.

### 🎯 Purpose & Impact
- **Enhanced precision**: This change aims to exclude 4-dimensional tasks (like masks) from a normalization process meant for non-classification tasks, improving the accuracy for object detection and segmentation models.
- **Better compatibility**: Ensures the neural network backend processes only relevant data shapes, leading to fewer errors and potentially faster inference times.
- **Impact**: Users working with non-classification tasks (e.g., object detection) may notice improved model performance and accuracy due to more precise data handling.

### CODE REVIEW

**Comment by charlesollion** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by glenn-jocher** [comment]
@charlesollion thank you for signing the CLA! Your contribution is immensely valuable to the YOLOv8 community. 🌟 If you have any more questions or need further assistance as you contribute, feel free to reach out. Happy coding! 👩‍💻👨‍💻

**Comment by glenn-jocher** [comment]
@charlesollion thanks! It looks like the CLA message may not have worked. Can you try again with this message:

I have read the CLA Document and I sign the CLA

**Comment by charlesollion** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@charlesollion PR merged! Thank you for catching this hard-to-find bug and submitting this fix. Let us know if you spot any other bugs or areas for improvement :)

**Pull request merged**
