### PR TITLE
Concat all segments by default for multi-part masks

### LINKED ISSUE #16733: Sometimes bounding box coordinates are correct, but the mask is either missing or only covers a very small part of the detected object
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict

### Bug

Similar to "closed" bug report: https://github.com/ultralytics/ultralytics/issues/7704

### Environment

Ultralytics 8.3.0 🚀 Python-3.9.18 torch-1.13.0+cu116 CUDA:0 (NVIDIA A100-SXM4-40GB, 40444MiB)
YOLO11x-seg summary (fused): 491 layers, 62,007,903 parameters, 0 gradients, 318.5 GFLOPs

### Minimal Reproducible Example

image_src = cv2.imread(img_path)

results = model.predict(
    source=image_src, save=False, conf=0.4, imgsz=cfg['imgsz']
)

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Y-T-G**
Resolves https://github.com/ultralytics/ultralytics/issues/16733

If the mask of an object is split into multiple segments, `ultralytics` currently returns the largest segment during conversion from mask to segments. But most users would rather the segments in this scenario are concatenated.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved segmentation strategy in the `masks2segments` function to offer more comprehensive options.

### 📊 Key Changes
- Updated the `masks2segments` function to default to a new strategy "all".
- Introduced `merge_multi_segment` from `ultralytics.data.converter` for merging segments when using the "all" strategy.

### 🎯 Purpose & Impact
- **Better Segmentation Handling:** By shifting the default strategy from "largest" to "all", the function can now handle multiple segments more comprehensively, potentially producing more accurate and detailed segmentation results.
- **User Flexibility:** Allows users to choose between a comprehensive view ("all") and a focused approach ("largest"), catering to different use cases and preferences.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting a PR to the `ultralytics/ultralytics` repository! 🚀 

To facilitate a smooth integration of your contribution, please ensure you have covered the following checklist:

- ✅ **Purpose Definition**: Clearly articulate the purpose of your fix or feature in the PR description. Mention and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues) you are addressing.
- ✅ **Stay Updated**: Ensure your branch is up-to-date with the `main` branch. You can sync by selecting the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Pass CI Checks**: Verify that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are successful. If any checks fail, make sure to resolve them promptly.
- ✅ **Documentation Update**: Reflect your changes in the relevant [documentation](https://docs.ultralytics.com) to ensure users are well-informed of any new or adjusted features.
- ✅ **Testing**: Add or update tests as needed to validate your changes. Confirm that all tests are passing.
- ✅ **Sign the CLA**: If this is your first contribution, please sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by commenting “I have read the CLA Document and I sign the CLA.”
- ✅ **Minimal Changes**: Aim to keep your changes as focused as possible on the specific bug fix or feature addition. "It is not daily increase but daily decrease, hack away the unessential" — Bruce Lee

For further assistance, please refer to the [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions, don't hesitate to ask. An Ultralytics engineer will be with you shortly to assist further. Thank you for contributing! 🌟

**Comment by Skillnoob** [comment]
Agree with this change, there were multiple issues in the past with the same issue and this behavior makes more sense.

**Comment by Laughing-q** [comment]
@Y-T-G Thanks for the PR! But in fact concatenating all the masks can result a wired mask like this https://github.com/ultralytics/ultralytics/issues/16733#issuecomment-2406365538 because all the coordinates might not be closed as a boundary of the object. And that's why we return the largest one, it might be a part of the whole object but the boundary is correct.

**Comment by Y-T-G** [comment]
@Laughing-q That's true. There's an inherent limitation with the format not being able to represent masks that are split up. I guess we should at least show a warning when this behavior occurs.

**Comment by glenn-jocher** [comment]
@Laughing-q could create splits in masks by joining segments with an `float("nan")` separator?

**Comment by Laughing-q** [comment]
> @Laughing-q could create splits in segments by joining segment-groups with an `float("nan")` separator?

hmmm I tried but did not work to me as we need to scale coordinates to original image size domain and nan does not work with it, we could also add some logic to do this but it'll be a bit complicated.

@glenn-jocher @Y-T-G I think we can not satisfy every users cases and the `largest` option in fact works in most cases(in my opinion). Apparently there's way to get all the segments but need some customization on our code, which I would recommend we create and provide the customized code in our docs page. Then we can refer the docs to our users. What do you guys think?
something like:
```python
from ultralytics.utils import ops
model = YOLO("yolo11n-seg.pt")
for r in model.predict():
    segments = ops.masks2segments(r.masks.data, strategy="all")  # each segment is a list
    segments = [[ops.scale_coords(r.masks.shape[1:], x, r.orig_shape) for x in xy] for xy in segments]
```
We can deprecate `concat` since it usually returns distorted segments, and probably update it to `all` and return a list contains all the segments for each mask.

**Comment by Y-T-G** [comment]
@Laughing-q It can work I guess. Should be better than concat.

**Comment by wsd3val** [comment]
Amazed this hasn't been addressed more thoroughly previously. Currently benchmarking YOLOv11 against another network and found very low segmentation performance, on closer inspection found that only the largest segmentations were returned. Pretty misleading to have result.masks only return a subset of the masks plotted using results.show()!

**Comment by Laughing-q** [comment]
@Y-T-G @glenn-jocher Hey guys! actually we have a function `merge_multi_segment` to merge all the separate segments into one, that I created years ago to merge multiple segments from COCO dataset into one before converting to yolo format. And it works to the COCO2YOLO conversion, perhaps we could directly implement it here. 
I've updated it in https://github.com/ultralytics/ultralytics/pull/16826/commits/c37c1a25807e086f852abeb89b62e1673372cc6a and tested it works to me. Can you test it as well? @Y-T-G  THanks!

**Comment by Y-T-G** [comment]
@Laughing-q Seems to work pretty well from my tests.

**Review by glenn-jocher — APPROVED** [review]

**Pull request merged**
