### PR TITLE
SmileTracker(Bytetrack+Appearance)

### PR DESCRIPTION
**Pull request by johnnynunez**
Paper: https://arxiv.org/abs/2211.08824
Repository: https://github.com/pingyang1117/SMILEtrack_Official

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements and updates for Ultralytics repository with no code changes. 🚀

### 📊 Key Changes
- No actual code changes were made. 🚫💻

### 🎯 Purpose & Impact
- Since this PR does not include any code alterations, there is no direct impact or immediate benefits to the end-users. ☁️
- It's possible this PR was made by mistake or for housekeeping purposes such as updating documentation, working on non-code files, or preparing the codebase for future changes. 🗂️✨

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@johnnynunez hello! Thanks for bringing the SmileTracker project to our attention. It's always great to see the community developing new tracking technologies that build on existing methodologies like ByteTrack.

While SmileTracker is an interesting project that integrates appearance features into tracking, it is separate from the YOLOv8 repo and Ultralytics work. If you're looking to enhance tracking performance in YOLOv8, you can certainly look into methods like this for inspiration, but be mindful of license compatibilities and integration challenges.

For tracking within the Ultralytics ecosystem, our YOLOv8 model includes object tracking capabilities that you can use for real-time applications, which you can learn more about in our documentation under the "[Track](https://docs.ultralytics.com/modes/track)" mode section. It offers practical and efficient ways to perform object tracking with the models we've constructed.

Should you have specific issues or questions about YOLOv8 and its tracking functionality, don't hesitate to reach out or consult our documentation. The Ultralytics team and community are here to support users in their endeavors to create innovative AI-based solutions. Happy coding! 😊🚀

**Comment by glenn-jocher** [comment]
@johnnynunez on review, I appreciate the effort here, but the number of files added (+441 files) is far too high, and the number of lines changed (+441,000) is absolutely crazy. 

This is far more than the entire ultralytics repo itself, so we can not accept this PR as is.

For integrating new trackers please see the code in the existing trackers files, which is extremely minimal, fast and lightweight.

**Comment by glenn-jocher** [comment]
@johnnynunez It's great to hear that you're taking steps to refine your contribution by focusing on the essential files! Streamlining the integration process will definitely help maintain the efficiency and clarity of the repository. As you work on that, aiming to keep the additions modular and in line with the architectural principles of YOLOv8 will be crucial.

If you haven't already, I suggest reviewing our "[Export](https://docs.ultralytics.com/modes/export)" and "[Track](https://docs.ultralytics.com/modes/track)" mode documentation to ensure compatibility with the existing codebase and APIs. This will help you better understand the design patterns used in YOLOv8 and facilitate a smoother integration of new features, such as your implementation of a new tracker.

Remember to keep your PRs focused and incremental, as smaller changes are typically easier to review and integrate. Your efforts to optimize and contribute are truly valued, and we're looking forward to seeing your refined work. Keep up the innovative approach, and if you have any questions during the process, don't hesitate to reach out to the community! 😄👍

**Comment by glenn-jocher** [comment]
@johnnynunez also I should introduce you to @Laughing-q, my co-author who managed most of the botsort and bytetrack integration. If you have any tracking-related questions he should be able to assist.

**Comment by johnnynunez** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@johnnynunez thanks for the cleanup! Looks much better :)

I noticed you placed new modules and models in tracker/ but all modules must be defined here:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/nn

And all models must be created in the models directory:
https://github.com/ultralytics/ultralytics/tree/main/ultralytics/models

Also can we introduce the tracker without introducing models? i.e. BotSort and ByteTrack can be applied directly to YOLOv8 or RDETR models, they are model-independent. We want new trackers to likewise be model independent.


@Laughing-q did most of the existing tracker integration, he can help answer questions as well.

**Comment by bit-scientist** [comment]
@johnnynunez Is there any progress on that? I would like to test if it works on my videos.

**Pull request closed without merging**
