### PR TITLE
`ultralytics 8.3.15` new TPU device-selection ability

### PR DESCRIPTION
**Pull request by lalayants**
Allows one to choose TPU device, if multiple are available. I needed this for launching multiple docker containers with Coral Dual Edge TPU with two cores. Without modification, second container raises error, because both are trying to access the first core

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Allows one to choose TPU device
This PR improves code readability by refactoring and restructuring the `autobackend.py` file.

### 📊 Key Changes
- Allows one to choose TPU device
- Reformatted and reorganized code for enhanced clarity.
- Added detailed comments to improve code understanding.
- Managed imports for smoother readability.

### 🎯 Purpose & Impact
- **Improved Readability**: The changes make the code easier to read and maintain, benefiting developers.
- **Functional Changes**: This update allows users to choose TPU device.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved guides and backend support for running Coral Edge TPU models on Raspberry Pi with better TPU management.

### 📊 Key Changes
- Updated documentation for exporting and running models on Coral Edge TPU.
- Enhanced TPU library handling and version checks in the backend.
- Improved code formatting for better readability and maintenance.

### 🎯 Purpose & Impact
- **User Guidance**: Clarifies steps for setting up Coral Edge TPU with Raspberry Pi, ensuring smoother installation and usage.
- **Performance Enhancement**: Allows selecting multiple TPUs for inference, optimizing resource usage.
- **Code Quality**: Improved readability and maintainability of backend code, contributing to easier future updates.

### CODE REVIEW

**Comment by lalayants** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Skillnoob** [comment]
Do you have a code example how someone would actually use this to select a different tpu?

**Comment by lalayants** [comment]
> Do you have a code example how someone would actually use this to select a different tpu?
Yeah, below is an example of docker-compose setup. As you can see, you just need to add environment variable TPU_DEVICE. For non-docker usage, just setup it any preferable way. 
```
services:
  yolo_1:
    build:
      context: .
    image: image
    container_name: yolo_1
    command: [ "/bin/bash", "-ci", "python3 yolo_test/v8_tpu.py" ]
    ipc: host
    stdin_open: true
    tty: true
    restart: always
    network_mode: host
    working_dir: /workspace/
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./yolo_test:/workspace/yolo_test
    environment:
      TPU_DEVICE: ":0"

   yolo_2:
    build:
      context: .
    image: image
    container_name: yolo_1
    command: [ "/bin/bash", "-ci", "python3 yolo_test/v8_tpu.py" ]
    ipc: host
    stdin_open: true
    tty: true
    restart: always
    network_mode: host
    working_dir: /workspace/
    privileged: true
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./yolo_test:/workspace/yolo_test
    environment:
      TPU_DEVICE: ":1"
```

**Comment by Skillnoob** [comment]
@lalayants which device number would be the first one? 0 or 1

**Comment by Skillnoob** [comment]
@lalayants I've updated the relevant documentation for your changes.

**Comment by Skillnoob** [comment]
The device selection now uses the device argument instead of setting a environment variable, which should be much more convenient to use.

**Comment by Skillnoob** [comment]
@Laughing-q this is ready for review.

**Comment by Laughing-q** [comment]
@lalayants @Skillnoob I noticed besides the actual changes this PR are making there are a lot code format updates, can we revert that? For example:
pic-241011-1542-40

**Comment by Skillnoob** [comment]
Yeah, the code formats can be reverted, they weren't done by me.

**Comment by Skillnoob** [comment]
@Laughing-q I've removed the unnecessary reformat.

**Comment by Laughing-q** [comment]
@Skillnoob @lalayants Looks good to me!

**Review by Laughing-q — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@Skillnoob @Laughing-q @lalayants thank you all! PR merged :)

**Pull request merged**
