### PR TITLE
Support OpenVINO>=2023.0

### PR DESCRIPTION
**Pull request by aleksandr-mokrov**
Support openvino>=2023.0. 
ONNX is not longer required for convertation into openvino format.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Upgraded OpenVINO dependency and refined OpenVINO export functionality for enhanced model deployment.

### 📊 Key Changes
- Updated the OpenVINO package requirement from `openvino-dev` to `openvino`.
- Simplified the OpenVINO export process in the codebase, tightening integration and improving the export workflow.
- Adjusted the model serialization for OpenVINO to include float16 compression support explicitly, aligning with export options.
- Enhanced the naming conventions and pattern matching within the INT8 quantization process for better clarity and maintainability.

### 🎯 Purpose & Impact
- **Smoother Integration and Setup**: By switching to `openvino` from `openvino-dev`, users can expect a more streamlined setup process, reducing compatibility issues. 🛠️
- **Improved Export Workflows**: These changes make exporting models to OpenVINO format more intuitive and flexible, particularly with options like FP16 compression, which can reduce model size and potentially improve performance on compatible hardware. 💨
- **Enhanced Quantization Support**: The updates in pattern matching and naming conventions during INT8 quantization aim to improve the reliability of quantized models, ensuring that they maintain high accuracy while benefiting from reduced computational resources. 🎛️
- **Overall, users can expect improved performance and ease of use when deploying models to environments that leverage OpenVINO for inference**, making this update particularly impactful for developers working in Edge computing or IoT devices where resource efficiency is key. 🚀

### CODE REVIEW

**Comment by aleksandr-mokrov** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@aleksandr-mokrov thank you for the PR! We have an existing PR in https://github.com/ultralytics/ultralytics/pull/8417 for this purpose. Can you please review and update that PR with these improvements? Thank you!

**Comment by glenn-jocher** [comment]
@aleksandr-mokrov BTW is it true that we no longer need `openvino-dev` for export? That would be really nice! I don't think this update is fully factored in to #8417 by @adrianboguszewski

**Comment by aleksandr-mokrov** [comment]
> @aleksandr-mokrov BTW is it true that we no longer need `openvino-dev` for export? That would be really nice! I don't think this update is fully factored in to #8417 by @adrianboguszewski
Yes, `openvino-dev` is no longer needed. `openvino` package is enough.

**Comment by glenn-jocher** [comment]
@aleksandr-mokrov closing this PR as changes merged in earlier #8417 PR by @adrianboguszewski.

Thank you for your contributions though, we value them greatly and please feel free to contribute any new features or bug fixes you find in the future!

**Pull request closed without merging**
