### PR TITLE
Added onnx fp16 export

### PR DESCRIPTION
**Pull request by ambitious-octopus**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced ONNX export capabilities with support for half-precision (FP16) models, improving model performance and efficiency.

### 📊 Key Changes
- Added a feature to export ONNX models in half-precision (FP16).
- Incorporated `float16` conversion utilizing `onnxconverter-common`.
- Adjusted inference logic to recognize half-precision inputs during model session setup.

### 🎯 Purpose & Impact
- **Performance Improvement**: Exporting models in FP16 can reduce model size and improve inference speed, particularly beneficial for deployment on resource-constrained devices.
- **User Flexibility**: Provides users with more options for exporting models tailored to specific hardware capabilities, enhancing versatility in deployment scenarios.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ambitious-octopus, thank you for submitting an `ultralytics/ultralytics` 🚀 pull request! This is an automated response to guide you through the PR process, and an Ultralytics engineer will assist you shortly.

Here's a checklist to help ensure a smooth integration:

- ✅ **Define a Purpose**: You've outlined the purpose of your PR well, detailing the support for half-precision (FP16) ONNX export and its benefits like faster inference and reduced model size. Please ensure any [relevant issues](https://github.com/ultralytics/ultralytics/issues) are linked in your PR description.
- ✅ **Synchronize with Source**: Ensure your branch is up-to-date with the `main` branch of the `ultralytics/ultralytics` repo. You can do this by clicking 'Update branch' or by running `git pull` and `git merge main` locally.
- 🔍 **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any tests fail, please investigate and resolve the issues.
- 📘 **Update Documentation**: If necessary, update our [documentation](https://docs.ultralytics.com) to reflect your changes or new features.
- 🧪 **Add Tests**: Check that your changes are covered by existing tests or add new tests to ensure everything functions as expected.
- 📝 **Sign the CLA**: Please confirm you've signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first contribution. Simply add a comment stating: "I have read the CLA Document and I sign the CLA."
- 🛠️ **Minimize Changes**: Aim for making changes that are as minimal as possible while still achieving the PR's purpose. This makes the review process smoother and ensures easier maintenance later.

For a detailed guide on contributing, please see our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have questions or need further assistance, feel free to leave a comment here. Thank you for contributing to Ultralytics! 🚀💪

**Comment by glenn-jocher** [comment]
@ambitious-octopus is there another solution that doesn't require another 3rd party package? 

ONNX exports in FP16 on CUDA devices that can then be used for CPU inference currently.

**Comment by inisis** [comment]
I think onnxslim has this feature already, but with same dependency

**Comment by glenn-jocher** [comment]
@inisis thank you for the suggestion. We'll consider it for future updates. If you have any other questions, feel free to ask!

**Comment by inisis** [comment]
@ambitious-octopus Can we try using this to make it a concise
```
        if self.args.simplify:
            try:
                import onnxslim
                LOGGER.info(f"{prefix} slimming with onnxslim {onnxslim.__version__}...")
                model_onnx = onnxslim.slim(model_onnx, dtype="fp16" if self.args.half else None)
            except Exception as e:
                LOGGER.warning(f"{prefix} simplifier failure: {e}")
```

**Pull request closed without merging**
