### PR TITLE
C++-TensorRT-Inference

### PR DESCRIPTION
**Pull request by JunJie1213855**
### Brief
This example accelerates YOLOv8 localization functionality by relying on third-party libraries such as TensorRT, CUDA, and OpenCV in the C++programming language.
Meanwhile, my example code folder is located repo/example/YOLOv8-TensorRT-Inference

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of TensorRT inference example for YOLOv8.

### 📊 Key Changes
- Added CMake configuration files for building TensorRT inference examples.
- Introduced code for TensorRT-based inference in `TRTInfer` class.
- Provided a sample script for running TensorRT inference on YOLOv8 models.
- Documentation updated with setup and execution instructions.
- Added utility functions for handling CUDA memory and type conversions.

### 🎯 Purpose & Impact
- **Enhanced Performance**: Leverages TensorRT for optimized model inference on NVIDIA hardware, improving speed and efficiency. 🚀
- **User Accessibility**: Simplifies the process for users to set up and run YOLOv8 models with TensorRT. 👥
- **Documentation**: Clear guidance helps users navigate setup and execution, reducing setup time. 📚

### CODE REVIEW

**Comment by 5p6** [comment]
I have read the CLA Document and I sign the CLA

**Comment by UltralyticsAssistant** [comment]
👋 Hello @5p6, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your feature addition. _"It is not the daily increase but the daily decrease, hack away the unessential."_

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

This is an automated response, and an Ultralytics engineer will assist you soon. 😊

**Review by ambitious-octopus — CHANGES_REQUESTED** [review]
Hey @5p6, this is awesome. But we just have a cpp example folder (`ultralytics/examples/YOLOv8-CPP-Inference`). What about integrating cpp TensorRT inference in the example instead of creating a new one?

**Comment by 5p6** [comment]
> Hey @5p6, this is awesome. But we just have a cpp example folder (`ultralytics/examples/YOLOv8-CPP-Inference`). What about integrating cpp TensorRT inference in the example instead of creating a new one?

Do you mean to combine 'ultralytics/examples/YOLOv8-CPP-Inference' and 'cpp TensorRT inference' as an example? like
```bash
* ultralytics/examples/YOLOv8-CPP-Inference
   *  Inferece
      *  infercence.cpp
      *  infercence.h
      *  utility.cc
      *  utility.h
      * TRTInfer.cc
      * TRTInfer.h
  * main.cc
  * README.md
  * CMakeLists.txt
```

**Comment by glenn-jocher** [comment]
Integrating the C++ TensorRT inference into the existing `YOLOv8-CPP-Inference` example sounds like a great idea. This approach would streamline the examples and enhance usability.

**Comment by ambitious-octopus** [comment]
@5p6 This seems like a better solution.

**Comment by 5p6** [comment]
> @5p6 This seems like a better solution.

Okay,I will modify it with this method next.

**Comment by glenn-jocher** [comment]
Great! Let me know if you need any further assistance.

**Pull request closed without merging**
