### PR TITLE
Implementing Resource Release Mechanism for Stream Loading

### PR DESCRIPTION
**Pull request by gustavosett**
Dear @glenn-jocher and ultralytics team!

I recently encountered an issue in my FastAPI application where the webcam resources were not released properly when using YOLOv8's generator functionality. This led to difficulties in managing and restarting the webcam, especially when dealing with connection problems.

https://github.com/ultralytics/ultralytics/issues/4246

To address this issue, I have introduced a mechanism that ensures proper handling and release of the camera and other video stream resources. Below are the changes:

1. Running Flag for Threads: I have introduced a self.running flag to control the reading of frames in a dedicated thread, enabling a graceful shutdown of the reading process when required.

2. Storing Video Capture Objects: I have created a list self.caps to store VideoCapture objects associated with each stream. This ensures that we have direct control over these objects to release them when necessary.

3. Release Mechanism in close Method: A new close method has been implemented to gracefully stop the threads, release the VideoCapture objects, and destroy any OpenCV windows. This ensures that all resources are properly freed.

4. Robust Error Handling: I have also taken care to include exception handling in case of connection problems and ensured that the resources are properly released even when an error occurs.

Thank you for your amazing work on YOLOv8, and I'm looking forward to hearing your thoughts on these enhancements!

### Summary
🔄🎥🛑

This pull request enhances the `LoadStreams` class in `ultralytics/data/loaders.py` to handle stream sources and threads more robustly and efficiently. It introduces new attributes and methods to control the stream loading and closing processes.

> _`LoadStreams` class_
> _manages sources and threads_
> _with `running` flag_

### Walkthrough
*  Add a `running` attribute and a `close` method to the `LoadStreams` class in `loaders.py` to control the stream loader lifecycle and release resources ([link](https://github.com/ultralytics/ultralytics/pull/4285/files?diff=unified&w=0#diff-3687f61e2371eaae4d90d58bf3aa6be449b113677b3ce104fd0d868b7df441deR37), [link](https://github.com/ultralytics/ultralytics/pull/4285/files?diff=unified&w=0#diff-3687f61e2371eaae4d90d58bf3aa6be449b113677b3ce104fd0d868b7df441deL79-R81), [link](https://github.com/ultralytics/ultralytics/pull/4285/files?diff=unified&w=0#diff-3687f61e2371eaae4d90d58bf3aa6be449b113677b3ce104fd0d868b7df441deR96-R108))
*  Add a `caps` attribute to the `LoadStreams` class in `loaders.py` to store the `cv2.VideoCapture` objects for each stream source and avoid creating duplicates ([link](https://github.com/ultralytics/ultralytics/pull/4285/files?diff=unified&w=0#diff-3687f61e2371eaae4d90d58bf3aa6be449b113677b3ce104fd0d868b7df441deR45), [link](https://github.com/ultralytics/ultralytics/pull/4285/files?diff=unified&w=0#diff-3687f61e2371eaae4d90d58bf3aa6be449b113677b3ce104fd0d868b7df441deL54-R70))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced video stream handling and cleanup in data loader.

### 📊 Key Changes
- Added a `running` flag to manage stream reading threads.
- Stored `cv2.VideoCapture` objects within the `LoadStreams` class.
- Implemented a `close` method to properly release video streams and resources.

### 🎯 Purpose & Impact
- The `running` flag 🏃 provides better control over thread execution, leading to efficient use of system resources.
- Storing video capture objects 📹 ensures better management of stream sources and improves code readability.
- Introducing the `close` method 🚪 ensures that video streams are correctly terminated, preventing resource leaks and potential application crashes, leading to a more robust stream handling for users.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@gustavosett thanks for the PR! One of the constraints on the streamloader is that it needs to be able to handle single streams i.e. `source='https://youtu.be/Zgi9g1ksQHc'` but also multiple streaming sources as in `source=path/to/sources.streams`. The latter case is handled by batch inference. 

We don't have a simple test for streaming so it's not part of the CI. Can you verify that both cases work correctly with this PR?

**Comment by glenn-jocher** [comment]
@gustavosett I'm updating the docs in http://127.0.0.1:8000/modes/predict/#inference-sources for more clarity on the two streaming source formats. The *.streams file should work with just repeating the same YouTube URL on each line (no comma at end of line), i.e. the list.streams content could just be:

### `list.streams` text file contents:
```txt
https://youtu.be/Zgi9g1ksQHc
https://youtu.be/Zgi9g1ksQHc
https://youtu.be/Zgi9g1ksQHc
https://youtu.be/Zgi9g1ksQHc
```

Screenshot 2023-08-10 at 18 36 14

**Comment by gustavosett** [comment]
We encountered an error in the main branch related to handling streams in the list.streams text file, specifically with how video frames are received and displayed. You can see the problem in [my testing video](https://www.youtube.com/watch?v=gi2f61v_9yw). I fixed a "pop error," but the main issue, unrelated to my last commit, still remains. It involves the frame handling mechanism, as illustrated in the code snippet below:

```py
    def __next__(self):
        """Returns source paths, transformed and original images for processing."""
        self.count += 1

        # Wait until a frame is available in each buffer
        while not all(self.imgs):
            if not all(x.is_alive() for x in self.threads) or cv2.waitKey(1) == ord('q'):  # q to quit
                cv2.destroyAllWindows()
                raise StopIteration
            time.sleep(1 / min(self.fps))

        # Get and remove the next frame from imgs buffer, replacing None with dummy image
        images = []
        for x, shp in zip(self.imgs, self.shape):
            if x:
                # Use the actual image if available, otherwise use a dummy image
                img = x.pop(0) if x else np.zeros(shp, dtype=np.uint8)
                images.append(img)

        return self.sources, images, None, ''
```

The main challenge seems to be in understanding how this part of the code interacts with other parts of the application that may contribute to the overall issue with frame reception and display. Additional investigation and possibly more context could help pinpoint the root cause of the problem.

Resume: I successfully implemented a pull request that functions as intended. However, an issue persists within the main branch. I have managed to identify and apply a partial solution, but further action may be required to fully resolve the problem.

**Comment by glenn-jocher** [comment]
@gustavosett thank you for bringing this to our attention and for sharing your partial solution. 

In line with your suggestion, the error appears to be related to how frames are handled when reading from multiple streams. The current approach creates a queue of images from each source and waits till all queues have an image before proceeding. If, for whatever reason, one stream is slower or drops frames, it could lead to delayed processing or even skipping frames from other streams. 

Your updated approach appears to address this by using a dummy image if a frame is not available, allowing the processing to continue and preventing the queue from being blocked. It is indeed a valuable suggestion, showing deep understanding of the issue.

However, as you mentioned, this solution is only partial and the problem could be intertwined with other parts of the program. It is crucial to dig further into how the frames are read, stored, and processed within the application. We appreciate your time and effort put into this issue and encourage continuous contributions to make our project even better. We will also conduct further internal investigations to resolve the reported issue.

Thanks again for your contribution. Great work!

**Comment by gustavosett** [comment]
Thank you for your comprehensive feedback @glenn-jocher.

Regarding the pull request, I'd like to clarify that it operates flawlessly and is primed for a merge. It has been thoroughly tested and behaves as anticipated.

As for the identified bug, I'm committed to diving deeper into this. Outside of my regular working hours, I plan to allocate some time specifically to gain a better understanding and to explore potential comprehensive solutions, setting aside the [partial fix I initially proposed](https://github.com/ultralytics/ultralytics/pull/4285/commits/b8080c91239e8ea5673364d4677fbea0a5b57e73).

It's crucial to understand the significance of the main functionality I implemented. It serves as a foundational piece for the stream generator, ensuring releasing resources and more efficient operations. Its proper integration is paramount for the overall performance and user experience.

I appreciate your support and patience. I believe that by collaborating, we can ensure the best quality for your project.

**Comment by glenn-jocher** [comment]
@gustavosett, thank you for your diligent work in ensuring the pull request functions as expected. It's great to hear that the tests have been passed successfully.

We highly value your commitment to further investigating the bug previously identified. It's important to us that we provide the most efficient and reliable solution to our users. Your dedication to understanding the complexities of this issue and providing a comprehensive solution is commendable.

We recognize the essential role the feature you've implemented plays in the stream generator, and its contribution to resource release and enhanced efficiency is significant. Ensuring its seamless integration is indeed a key priority, and we appreciate your efforts in delivering high-quality solutions.

Your dedication and continuous collaboration are greatly valued. Let's keep moving forward to improve the quality of our project and deliver excellent user experiences. Thank you for your ongoing contributions.

**Comment by glenn-jocher** [comment]
@gustavosett got it! This looks good, I'll revert the streams fix and work on that separately.

**Comment by glenn-jocher** [comment]
@gustavosett to provide more info, we need to add a flag to streaming that controls whether to stream live or to buffer (default). 

Buffered streaming is appropriate for i.e. YouTube videos where you want to capture every frame (current default), but live streaming is more appropriate for i.e. RTSP cameras where you always want the latest frame so they don't back up.

Multi-streaming should be able to handle live streams of different sizes and frame rates, passing either the previous frame or a black frame for streams that are lagging or problematic.

**Comment by MitchFuchs** [comment]
Hi @gustavosett and @glenn-jocher 

Thanks for this PR and addition of the release mechanism. 

Can you help me figure out how I can call the close() method after the model.predict and result generator are being initiated?

`model = YOLO('best.pt')` 
`results = model(source='tcp://172.0.0.1:8888', stream=True, verbose=False)`
`    while True:`
`        for result in results: `
`            --> call close() method from here`


Thanks a lot for your help,
Mitch

**Comment by glenn-jocher** [comment]
@MitchFuchs hello Mitch,

Once you've started the generator with `model.predict`, the close method should be attached to the object that's yielding your results. In the provided code snippet, you're using a loop to iterate over `results`, which is the generator.

Given the scenario that you want to stop the generator and close the stream, you must do it outside the inner loop, since the inner loop is focused on iterating over the results being generated.

Here's an outline of what you would typically do:

1. Initiate the generator as you have done.
2. Iterate through your results within the loop. 
3. Conditionally or at some determined point, break from the loop.
4. Once outside the loop, call the `close()` method on the generator or the object containing the generator.

The `close()` method would be responsible for releasing the resources used by the generator. The tricky part is determining the right moment to exit the loop and ensure proper clean-up. This often depends on the specific application logic or user interaction, like monitoring a flag, receiving a signal, or detecting a particular input.

Please note that while the pseudo-code concept should generally hold, it must be adapted to the object's methods and properties specific to the YOLOv8 implementation you are working with.

Thank you for using the YOLOv8 model, and I hope this guidance proves helpful.

**Comment by ysm121736590** [comment]
results = model.predict(video_path, stream=True)
try:
    for r in results:
        # 可视化结果
        annotated_frame = r.plot()
        cv2.imshow("YOLOv8 Inference", annotated_frame)
        # 按住q键盘播放结束
        if cv2.waitKey(40) & 0xFF == ord("q"):
            break
except Exception as e:
    print(e)

results.close()        
try:
    print(next(results)) # 这里会引发 StopIteration 错误
except StopIteration as e:
    print("Generator is closed")
    
print(getgeneratorstate(results))

hello，I have closed the generator object，but the stream video_path haven't been release.
can you help me please?

**Comment by glenn-jocher** [comment]
@ysm121736590 hello,

After calling `results.close()`, the generator should be properly closed, and resources associated with the stream should be released. If the video stream is still occupied, it might be due to the underlying video capture object not being released correctly.

Please ensure that the `close()` method in the generator is implemented to release all resources, including the video capture object. If the issue persists, it could be related to the environment or a bug that needs further investigation.

If you're confident that the `close()` method is correctly implemented and the issue remains, please open an issue on the GitHub repository with detailed information about your environment and the steps to reproduce the problem, so we can look into it further.

Thank you for reaching out, and we appreciate your patience as we work to resolve this.

**Comment by xxddff** [comment]
`results.close()` doesn’t seem to work for me. It appears to close the generator, but it doesn’t stop the stream. I have to manually execute `model.predictor.dataset.close()` to close the stream and release the resources. I’m not sure if this is the expected behavior.

**Comment by gustavosett** [comment]
> `results.close()` doesn’t seem to work for me. It appears to close the generator, but it doesn’t stop the stream. I have to manually execute `model.predictor.dataset.close()` to close the stream and release the resources. I’m not sure if this is the expected behavior.


Definitely, this is not expected, open an Issue with more information so we can try to reproduce.

**Comment by glenn-jocher** [comment]
@gustavosett thank you for your detailed message and for taking the initiative to enhance the resource management in the YOLOv8's generator functionality. The changes you've proposed are indeed crucial for ensuring that resources such as webcam streams are properly released, especially in a web server environment like FastAPI where resources can be tied up across multiple requests.

The introduction of a `self.running` flag is a standard approach to manage the execution flow of threads, and it's great to see that you've implemented it to control the frame reading process. Storing `VideoCapture` objects in a list (`self.caps`) is also a good practice for managing multiple streams and releasing them when necessary.

The `close` method you've added is essential for cleaning up resources, and it's important that it's called appropriately when the application is shutting down or when the streams are no longer needed. Exception handling is also key to ensuring that resources are released even when errors occur, which can often be the case with network streams or hardware issues.

Your contribution to the Ultralytics YOLOv8 project is greatly appreciated. To proceed with integrating your enhancements, please follow these steps:

1. **Fork the Repository**: If you haven't already, fork the Ultralytics YOLOv8 repository on GitHub.

2. **Implement Your Changes**: Create a new branch in your fork and implement the changes you've described. Make sure to test your changes thoroughly to ensure they work as expected.

3. **Document Your Changes**: Update the documentation and comments in the code to reflect the new functionality and the purpose of the changes you've made.

4. **Submit a Pull Request (PR)**: Once you're confident in your changes, submit a PR to the main Ultralytics YOLOv8 repository. In your PR description, explain the problem you encountered, the solution you've implemented, and any additional context or testing you've performed.

5. **Sign the CLA**: As part of the PR process, you'll need to sign the Ultralytics Contributor License Agreement (CLA). You can do this by simply writing the following statement in a PR comment:
   ```
   I have read the CLA Document and I hereby sign the CLA
   ```

6. **PR Review**: The Ultralytics team will review your PR, run additional tests, and provide feedback or request changes if necessary.

7. **PR Merge**: Once your PR is approved, it will be merged into the main codebase.

Your proactive approach to improving the YOLOv8 project is commendable, and we're looking forward to seeing your PR. If you have any questions or need further assistance with the contribution process, please don't hesitate to ask.

Thank you once again for your contribution and for supporting the YOLOv8 and Ultralytics community!

**Pull request merged**
