### PR TITLE
fix bug in the ConfusionMatrix class

### LINKED ISSUE #18407: There may be a bug in the ConfusionMatrix class.
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

_No response_

### Bug

There exists a pred_box A and a gt_box B, but the IoU of A and B is 0. In this case, the FNs will increase by 1, but the FPs will not.
image

### Environment

。。。

### Minimal Reproducible Example

。。。

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by yuzhj**
Closes https://github.com/ultralytics/ultralytics/issues/18407

When a prediction doesn't match any ground truth, and a ground truth doesn't match any prediction, we expect the confusion matrix to show 1 FP and 1 FN.

However, current implementation only shows 1 FN and no FP.

**Minimum Reproducible Code**
```python
from ultralytics.utils.metrics import ConfusionMatrix
import torch

matrix = ConfusionMatrix(nc=1)
detections = torch.tensor([[50, 50, 100, 100, 0.6, 0]])
gt_bboxes = torch.tensor([[200, 200, 300, 300]])
gt_cls = torch.tensor([0])

matrix.process_batch(detections, gt_bboxes, gt_cls)

print(matrix.matrix)
```

**main**
```python
In [8]: print(matrix.matrix)
[[          0           0]
 [          1           0]]
```

**PR**
```python
In [9]: print(matrix.matrix)
[[          0           1]
 [          1           0]]
```

### CODE REVIEW

**Comment by yuzhj** [comment]
I have read the CLA Document and I sign the CLA

**Comment by yuzhj** [comment]
I have read the CLA Document and I sign the CLA

**Comment by yuzhj** [comment]
@Y-T-G please check the code.

**Review by Y-T-G — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@yuzhj PR merged! Thank you for contributing this fix.

**Pull request merged**
