### PR TITLE
Fix learning rate gap on resume

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvements in training scheduling and more informative logging.

### 📊 Key Changes
- Optimizer step warning suppression moved and simplified within the training loop.
- Scheduling based on time now occurs directly after an epoch ends rather than inside a warning suppression block.
- Introduction of a more descriptive logging prefix (`EarlyStopping: `) for better clarity on training halts due to lack of improvement.

### 🎯 Purpose & Impact
- **Enhanced Efficiency 🏃‍♂️**: Moving the learning rate scheduler step outside of a warning suppression block streamlines the training process, potentially reducing confusion and improving code maintainability.
- **Time-Based Scheduling 🕒**: Adjusting the scheduler after each epoch based on the average epoch duration and desired training time allows for more precise control over the training duration, making it easier to fit training into specific time slots.
- **Improved User Experience 📈**: Introducing a colored "EarlyStopping:" prefix to logs makes it immediately clear when training has been halted due to no observed improvement, enhancing user understanding and control over the training process.

These changes aim to simplify the training loop for better performance, more precise time management, and clearer communication of important training events, all of which contribute to a more efficient and user-friendly training experience.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher please take a look and check if I break anything. Thanks!

**Comment by glenn-jocher** [comment]
@Laughing-q that would be super nice we could get rid of all that timed training logic, but I think I had to include it for a reason. One test for timed training is we need to run with less time and more time than the default epochs count. I'll run some tests on this.

**Comment by glenn-jocher** [comment]
Oh I think I remember now, we need to update the LR scheduler to hit lrf on `epochs` epoch, I think this logic handles that. 

If we don't then timed training won't be optimal as the LR scheduler will be fixed to hit lrf on the default `epochs` instead of the updated `epochs`

**Comment by glenn-jocher** [comment]
@Laughing-q ok I moved the scheduler.step() line to the beginning of the train loop instead of the end. The new LR will always be 1 step ahead of the previous one, but I think this fine. Resume looks good now. I CTRL+C a run 3 times and resumed 3 times here:

Screenshot 2024-04-01 at 23 37 32

Screenshot 2024-04-01 at 23 38 01

Screenshot 2024-04-01 at 23 38 33

What do you think?

**Comment by Laughing-q** [comment]
@glenn-jocher Looks good to me! 
Actually this is interesting, moving `scheduler.step()` to the beginning seems to be the correct one. I launched four training to test the lr change:
- `main` branch, default settings vs `warmup_epochs=0`(to check out what the lr looks like if scheduler starts working at the beginning.)
image

- current branch, default settings vs `warmup_epochs=0`, which does `scheduler.step()` at the beginning.
bWlth7HKgV

**Comment by glenn-jocher** [comment]
Nice!!

**Comment by glenn-jocher** [comment]
@Laughing-q PR merged!

**Pull request merged**
