### PR TITLE
To pass required classes and suppress unwanted by non_max_suppression operation, in prediction task.

### PR DESCRIPTION
**Pull request by Kamlesh364**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of prediction and filtering in the Ultralytics YOLO model

### 📊 Key Changes
- Added multiple new configuration parameters in `default.yaml` for additional control over predictions and visualization.
- Extended the `predict` method in `model.py` and `predictor.py` with an optional `classes` parameter to filter predictions by specific classes.
- Updated postprocessing methods in `predict.py` across various modules (like classify, detect, and segment) to incorporate the `classes` filter.

### 🎯 Purpose & Impact
- 🎛️ The additional configuration parameters provide users more flexibility in how predictions are handled and results are presented.
- 🎨 The introduction of a `classes` parameter allows for class-specific predictions, which can enhance the model's practicality in real-world scenarios.
- 🛠️ Overall, these changes can improve the user experience by offering more tailored outputs and potentially increasing the efficiency of the model by focusing on relevant objects.

### CODE REVIEW

**Comment by Kamlesh364** [comment]
recheck

**Comment by Kamlesh364** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Kamlesh364** [comment]
recheck

**Comment by AyushExel** [comment]
Thanks for the PR. Can you please resolve merge conflicts?

**Comment by Kamlesh364** [comment]
recheck

**Comment by Kamlesh364** [comment]
recheck

**Comment by Kamlesh364** [comment]
recheck

**Pull request closed without merging**
