### PR TITLE
Update predict.md to correct Results' attributes

### PR DESCRIPTION
**Pull request by bogdan-galileo**
Correct list of attributes of class `Results` by adding `orig_shape`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Documentation update for prediction results in Ultralytics.

### 📊 Key Changes
- Renamed `Results.prob` to `Results.probs` for clarity.
- Added `Results.orig_shape` to include the original image size.

### 🎯 Purpose & Impact
- 📝 Clarifies the terminology by using plural form (`probs`) to indicate there are multiple class probabilities.
- 🌆 Provides users with the original image dimensions, useful for post-processing or when displaying the results on the original images.

### CODE REVIEW

**Comment by bogdan-galileo** [comment]
I have read the CLA Document and I sign the CLA

**Comment by bogdan-galileo** [comment]
recheck

**Comment by glenn-jocher** [comment]
@bogdan-galileo PR merged! Thank you for your contributions.

**Comment by UltralyticsAssistant** [comment]
A potential fix for this issue has been merged in [PR #18850](https://github.com/ultralytics/ultralytics/pull/18850) 🎉. 

### Key Changes in the PR  
This update simplifies and clarifies the documentation for the Ultralytics HUB Shared Inference API usage limits. Specifically:  
- The explanation of API usage limits has been streamlined by merging free and Pro user limits into one general description, making the information more accessible and concise.  
- Pro user-specific details regarding higher usage limits have been removed for a more unified and clear user experience.

These changes are aimed at improving documentation clarity while reducing redundancy, which may help address the issue you've raised. Huge thanks to @sergiuwaxmann for their contributions here! 🙌  

### How to Test the Fix  
To confirm if this resolves your issue, you can test the latest changes with:  
```bash
pip install git+https://github.com/ultralytics/ultralytics.git@main
```  
Alternatively, you can await the next official release on PyPI to incorporate this update.  

### Feedback Request  
If you get a chance to test or review the updated documentation, feedback on whether this resolves the issue would be greatly appreciated! If the issue persists or if there's additional feedback, please let us know so we can continue improving.  

Thank you again for bringing up this issue and helping us enhance the project! 🙏 All feedback and further insights are always welcome. 🚀

**Pull request merged**
