### PR TITLE
Fix model re-fuse() in inference loops

### LINKED ISSUE #456: Model not accepting numpy / PIL inputs
I tried to use an image as input that is in ndarray-format. According to the docs this should work. 

```from ultralytics import YOLO
import numpy
import cv2


model = YOLO("best.pt")
image2 = cv2.imread("zidane.jpg")
model.predict(source=image2, show="True")
```

I'm getting the following Output when running this script:

```
Ultralytics YOLOv8.0.6  Python-3.7.6 torch-1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2080, 8192MiB)
Fusing layers... 
Model summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Traceback (most recent call last):
  File "D:\Desktop\yolov8\ultralytics\Sohmlord.py", line 8, in <module>
    model.predict(source=image2, show="True")
  File "C:\Users\Admin\AppData\Roaming\Python\Python37\site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "D:\Desktop\yolov8\ultralytics\ultralytics\yolo\engine\model.py", line 130, in predict
    predictor.setup(model=self.model, source=source, return_outputs=return_outputs)
  File "D:\Desktop\yolov8\ultralytics\ultralytics\yolo\engine\predictor.py", line 150, in setup
    vid_stride=self.args.vid_stride)
  File "D:\Desktop\yolov8\ultralytics\ultralytics\yolo\data\dataloaders\stream_loaders.py", line 163, in __init__
    p = str(Path(p).resolve())
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 1161, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\pathlib.py", line 205, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] Die Syntax für den Dateinamen, Verzeichnisnamen oder die Datenträgerbezeichnung ist falsch: '[[[38 48 72]\n  [40 50 74]\n  [40 51 73]\n  ...\n  [25 21 56]\n  [21 19 55]\n  [17 15 51]]\n\n [[37 47 71]\n  [37 47 71]\n  [37 48 70]\n  ...\n  [24 20 55]\n  [18 16 52]\n  [13 11 47]]\n\n [[41 51 75]\n  [39 49 73]\n  [37 48 70]\n  ...\n  [24 20 56]\n  [20 16 52]\n  [16 12 48]]\n\n ...\n\n [[48 43 40]\n  [49 44 41]\n  [48 43 40]\n  ...\n  [49 49 35]\n  [49 49 35]\n  [50 50 36]]\n\n [[49 42 39]\n  [49 42 39]\n  [49 42 39]\n  ...\n  [50 49 35]\n  [50 49 35]\n  [51 50 36]]\n\n [[48 41 38]\n  [48 41 38]\n  [48 41 38]\n  ...\n  [50 49 35]\n  [50 49 35]\n  [51 50 36]]]'
```

it seems that it is trying to interpret that ndarray as a filename.

### LINKED ISSUE #468: Model layers are fusing between predictions
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

Is it possible to prevent the model from fusing and logging?

I was testing the `YOLOv8.0.9` release. And it is still fusing and logging between predictions. Is it possible to turn that off? Or I could use the model differently to get the expected behavior.

`get_video_frames_generator(SOURCE_VIDEO_PATH)` is just returning the video frame generator. As promised, I can now use `np.ndarray` for inference, but it is still fuseing. 

Screenshot 2023-01-18 at 14 39 41

### Environment

Google Colab

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #474: RuntimeError: Boolean value of Tensor with more than one value is ambiguous
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When I run classification model:

```python
model = YOLO(f'{HOME}/yolov8n-cls.pt')
results = model.predict(source='https://media.roboflow.com/notebooks/examples/dog.jpeg', conf=0.25)
```

nothing has happened yet, but when I want to display results I get:

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[/usr/local/lib/python3.8/dist-packages/IPython/core/formatters.py](https://localhost:8080/#) in __call__(self, obj)
    700                 type_pprinters=self.type_printers,
    701                 deferred_pprinters=self.deferred_printers)
--> 702             printer.pretty(obj)
    703             printer.flush()
    704             return stream.getvalue()

4 frames
[/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/results.py](https://localhost:8080/#) in __repr__(self)
     90         if self.masks:
     91             s = s + self.masks.__repr__() + '\n'
---> 92         if self.probs:
     93             s = s + self.probs.__repr__()
     94         s += f'original size: {self.orig_shape}\n'

RuntimeError: Boolean value of Tensor with more than one value is ambiguous
```

### Environment

Google Colab

### Minimal Reproducible Example

```
model = YOLO(f'{HOME}/yolov8n-cls.pt')
results = model.predict(source='https://media.roboflow.com/notebooks/examples/dog.jpeg', conf=0.25)
print(results)
```

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #479: FileNotFoundError: /usr/local/lib/python3.8/dist-packages/ultralytics/assets does not exist
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Requirement already satisfied: ultralytics in /usr/local/lib/python3.8/dist-packages (8.0.9)
Requirement already satisfied: torch>=1.7.0 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (1.13.1+cu116)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (1.21.6)
Requirement already satisfied: opencv-python>=4.1.1 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (4.6.0.66)
Requirement already satisfied: seaborn>=0.11.0 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (0.11.2)
Requirement already satisfied: requests>=2.23.0 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (2.25.1)
Requirement already satisfied: hydra-core>=1.2.0 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (1.3.1)
Requirement already satisfied: pandas>=1.1.4 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (1.3.5)
Requirement already satisfied: psutil in /usr/local/lib/python3.8/dist-packages (from ultralytics) (5.4.8)
Requirement already satisfied: scipy>=1.4.1 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (1.7.3)
Requirement already satisfied: Pillow>=7.1.2 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (7.1.2)
Requirement already satisfied: matplotlib>=3.2.2 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (3.2.2)
Requirement already satisfied: torchvision>=0.8.1 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (0.14.1+cu116)
Requirement already satisfied: thop>=0.1.1 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (0.1.1.post2209072238)
Requirement already satisfied: tensorboard>=2.4.1 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (2.9.1)
Requirement already satisfied: sentry-sdk in /usr/local/lib/python3.8/dist-packages (from ultralytics) (1.13.0)
Requirement already satisfied: PyYAML>=5.3.1 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (6.0)
Requirement already satisfied: ipython in /usr/local/lib/python3.8/dist-packages (from ultralytics) (7.9.0)
Requirement already satisfied: GitPython>=3.1.24 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (3.1.30)
Requirement already satisfied: tqdm>=4.64.0 in /usr/local/lib/python3.8/dist-packages (from ultralytics) (4.64.1)
Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.8/dist-packages (from GitPython>=3.1.24->ultralytics) (4.0.10)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from hydra-core>=1.2.0->ultralytics) (21.3)
Requirement already satisfied: importlib-resources in /usr/local/lib/python3.8/dist-packages (from hydra-core>=1.2.0->ultralytics) (5.10.2)
Requirement already satisfied: antlr4-python3-runtime==4.9.* in /usr/local/lib/python3.8/dist-packages (from hydra-core>=1.2.0->ultralytics) (4.9.3)
Requirement already satisfied: omegaconf<2.4,>=2.2 in /usr/local/lib/python3.8/dist-packages (from hydra-core>=1.2.0->ultralytics) (2.3.0)
Requirement already satisfied: python-dateutil>=2.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.2.2->ultralytics) (2.8.2)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.2.2->ultralytics) (3.0.9)
Requirement already satisfied: kiwisolver>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.2.2->ultralytics) (1.4.4)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.8/dist-packages (from matplotlib>=3.2.2->ultralytics) (0.11.0)
Requirement already satisfied: pytz>=2017.3 in /usr/local/lib/python3.8/dist-packages (from pandas>=1.1.4->ultralytics) (2022.7)
Requirement already satisfied: chardet<5,>=3.0.2 in /usr/local/lib/python3.8/dist-packages (from requests>=2.23.0->ultralytics) (4.0.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages (from requests>=2.23.0->ultralytics) (2022.12.7)
Requirement already satisfied: idna<3,>=2.5 in /usr/local/lib/python3.8/dist-packages (from requests>=2.23.0->ultralytics) (2.10)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages (from requests>=2.23.0->ultralytics) (1.26.14)
Requirement already satisfied: setuptools>=41.0.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (57.4.0)
Requirement already satisfied: google-auth-oauthlib<0.5,>=0.4.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (0.4.6)
Requirement already satisfied: tensorboard-plugin-wit>=1.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (1.8.1)
Requirement already satisfied: werkzeug>=1.0.1 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (1.0.1)
Requirement already satisfied: wheel>=0.26 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (0.38.4)
Requirement already satisfied: google-auth<3,>=1.6.3 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (2.16.0)
Requirement already satisfied: absl-py>=0.4 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (1.3.0)
Requirement already satisfied: grpcio>=1.24.3 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (1.51.1)
Requirement already satisfied: protobuf<3.20,>=3.9.2 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (3.19.6)
Requirement already satisfied: tensorboard-data-server<0.7.0,>=0.6.0 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (0.6.1)
Requirement already satisfied: markdown>=2.6.8 in /usr/local/lib/python3.8/dist-packages (from tensorboard>=2.4.1->ultralytics) (3.4.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.8/dist-packages (from torch>=1.7.0->ultralytics) (4.4.0)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (0.7.5)
Requirement already satisfied: backcall in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (0.2.0)
Requirement already satisfied: decorator in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (4.4.2)
Requirement already satisfied: pygments in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (2.6.1)
Requirement already satisfied: pexpect in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (4.8.0)
Requirement already satisfied: jedi>=0.10 in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (0.18.2)
Requirement already satisfied: prompt-toolkit<2.1.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (2.0.10)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.8/dist-packages (from ipython->ultralytics) (5.7.1)
Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.8/dist-packages (from gitdb<5,>=4.0.1->GitPython>=3.1.24->ultralytics) (5.0.0)
Requirement already satisfied: six>=1.9.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->ultralytics) (1.15.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->ultralytics) (5.2.1)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->ultralytics) (4.9)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.8/dist-packages (from google-auth<3,>=1.6.3->tensorboard>=2.4.1->ultralytics) (0.2.8)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.8/dist-packages (from google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.4.1->ultralytics) (1.3.1)
Requirement already satisfied: parso<0.9.0,>=0.8.0 in /usr/local/lib/python3.8/dist-packages (from jedi>=0.10->ipython->ultralytics) (0.8.3)
Requirement already satisfied: importlib-metadata>=4.4 in /usr/local/lib/python3.8/dist-packages (from markdown>=2.6.8->tensorboard>=2.4.1->ultralytics) (6.0.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.8/dist-packages (from prompt-toolkit<2.1.0,>=2.0.0->ipython->ultralytics) (0.2.5)
Requirement already satisfied: zipp>=3.1.0 in /usr/local/lib/python3.8/dist-packages (from importlib-resources->hydra-core>=1.2.0->ultralytics) (3.11.0)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.8/dist-packages (from pexpect->ipython->ultralytics) (0.7.0)
Requirement already satisfied: pyasn1<0.5.0,>=0.4.6 in /usr/local/lib/python3.8/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard>=2.4.1->ultralytics) (0.4.8)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.8/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<0.5,>=0.4.1->tensorboard>=2.4.1->ultralytics) (3.2.2)
Ultralytics YOLOv8.0.9 🚀 Python-3.8.10 torch-1.13.1+cu116 CPU
Fusing layers... 
YOLOv8n summary: 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs
Traceback (most recent call last):
  File "/usr/local/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cli.py", line 141, in entrypoint
    cli(cfg)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/cli.py", line 82, in cli
    func(cfg)
  File "/usr/local/lib/python3.8/dist-packages/hydra/main.py", line 79, in decorated_main
    return task_function(cfg_passthrough)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/detect/predict.py", line 89, in predict
    predictor.predict_cli()
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 165, in predict_cli
    for _ in gen:  # running CLI inference without accumulating any outputs (do not modify)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 171, in stream_inference
    self.setup(source, model)
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/engine/predictor.py", line 139, in setup
    self.dataset = LoadImages(source,
  File "/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/data/dataloaders/stream_loaders.py", line 172, in __init__
    raise FileNotFoundError(f'{p} does not exist')
FileNotFoundError: /usr/local/lib/python3.8/dist-packages/ultralytics/assets does not exist

### Environment

Google Colab Environment

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces improvements and fixes across version, profiling, model fusion, CLI, and datasets, enhancing the Ultralytics YOLO software.

### 📊 Key Changes
- Bumped software version from 8.0.8 to 8.0.9.
- Improved layer profiling by cloning inputs to avoid in-place modifications.
- Enhanced model fusion to improve computational efficiency and check for model fusion status.
- Simplified and error-protected CLI command parsing.
- Refactored dataset download scripts to use new utility functions and removed unnecessary imports.
- Made minor updates to training and prediction tasks for classification, detection, and segmentation.
- Increased configurability and robustness with args handling and code refactoring.

### 🎯 Purpose & Impact
- Ensuring consistent software versioning 🔄.
- Providing accurate profiling of layers for better performance analysis 📈.
- Improving model efficiency by simplifying fusion checks and operations ⚙️.
- Streamlining command usage for end users through a more user-friendly CLI 🖥️.
- Enhancing maintainability and clarity by refactoring dataset-related scripts 🛠️.
- Improving user experience and reducing the potential for errors during training and prediction tasks 🏋️‍♂️.
- Overall, these changes contribute to a more robust, efficient, and user-friendly software suite for computer vision applications 🤖.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel found this line that's causing the 64 floor minimum:
https://github.com/ultralytics/ultralytics/blob/cc3c774bde86ffce694d202b7383da6cc1721c1b/ultralytics/yolo/engine/trainer.py#L208

**Comment by glenn-jocher** [comment]
@AyushExel ok don't worry, I think we can leave the floor at 32. I confirmed the models have a stride attribute, so the P6 models should automatically show gs=64 while P5 will show gs=32.

**Comment by glenn-jocher** [comment]
@AyushExel ok I made that one change, I'll merge and deploy after CI now. 

Also add rejection of KeyboardInterrupt and CUDA OOM from logging.

**Comment by glenn-jocher** [comment]
@AyushExel wait we have a problem. 

Pretrained models loaded should have some args reset to default like v5loader. How can I do this in engine/model?

**Comment by AyushExel** [comment]
@glenn-jocher add `args.pop("v5loader",None)` here
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/yolo/engine/model.py#L230

**Comment by glenn-jocher** [comment]
@AyushExel ok all set. All popped 'half' because CoreML test was quantizing to FP16 by default because it had half=True.

I think this explains a lot, many sentry bugs were showing v5loader=True and I had no idea why.

**Pull request merged**
