### PR TITLE
TAL speed improvements

### PR DESCRIPTION
**Pull request by glenn-jocher**
### Summary
🚀🧠🔧

This pull request optimizes and cleans up the code for temporal action localization in `./ultralytics/yolo/utils/tal.py` by using more PyTorch built-in functions and reducing complexity.

> _Sing, O Muse, of the swift and skillful coder_
> _Who in `./ultralytics/yolo/utils/tal.py` wrought_
> _A wondrous work of PyTorch, like Hephaestus' fire_
> _That forged the thunderbolts of Zeus, the king of gods._

### Walkthrough
*  Simplify and optimize the logic of selecting the highest overlaps and the topk candidates between predicted and ground truth boxes using expand, argmax, one_hot, permute, sum and tile methods ([link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650L44-R49), [link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650L179-R193))
* Replace the repeat method with the expand method to save memory and computation when creating views of tensors with different sizes ([link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650L135-R134), [link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650L149-R158), [link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650L233-R230))
* Replace the custom one-hot encoding function with the built-in F.one_hot function for faster and simpler encoding ([link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650L233-R230))
* Replace the pow and mul methods with their in-place versions pow_ and mul_ to avoid creating intermediate tensors ([link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650L149-R158))
* Import the torch.nn.functional module as F to use some of its functions such as one_hot and softmax ([link](https://github.com/ultralytics/ultralytics/pull/2761/files?diff=unified&w=0#diff-22c6f18a2e37e82741ff0de69ebc5d20a17f6c7a378f1bda19f4d7896d106650R5))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved efficiency in bounding box calculations for object detection.

### 📊 Key Changes
- 🚀 Switched from `.clamp(0)` to `.clamp_(0)` for in-place operations, enhancing performance.
- 📐 Replaced `.repeat()` with `.expand()` to avoid unnecessary data copying.
- 🔄 Changed `.t()` to `.T` for transpose operations to align with recent PyTorch conventions.

### 🎯 Purpose & Impact
- ⏱ **Performance:** The switch to in-place operations reduces memory overhead and can lead to faster computations.
- 📦 **Memory Efficiency:** Using `.expand()` rather than `.repeat()` reduces memory usage as it shares the same data instead of creating copies.
- 🛠 **Code Modernization:** Adopting `.T` for transposes reflects up-to-date PyTorch practices, increasing code readability and maintainability.

🏁 Overall, these changes contribute to a more efficient and modern codebase with potentially better performance and lower memory footprint during object detection tasks.

### CODE REVIEW

**Comment by Zephyr69** [comment]
How much gpu mem did this save?

**Comment by glenn-jocher** [comment]
@Zephyr69 oh I'm not sure, that's a good question. The changes were mostly meant for speed. `get_box_metrics()` is about twice as fast.

**Comment by bit-scientist** [comment]
> temporal action localization in `./ultralytics/yolo/utils/tal.py`

@glenn-jocher, you might need some attention in generated contens like this. I believe the code and the whole commits have nothing to do with temporal action localization.

**Comment by glenn-jocher** [comment]
Thank you for pointing that out! You are correct; the changes in `./ultralytics/yolo/utils/tal.py` are unrelated to temporal action localization. We'll review and ensure the commit description aligns with the actual modifications.

**Pull request merged**
