### PR TITLE
Explorer: Ask AI feature & plotting enhance

### PR DESCRIPTION
**Pull request by AyushExel**
Allows user to ask for samples in natural languge
- updated colab
- Dashboard
- compressed image assets.

@glenn-jocher currently this uses gpt-turbo-3.5 and it works well. Not sure if using GPT4 would be better

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the Ultralytics Explorer with AI-driven natural language query capabilities and updated visual documentation.

### 📊 Key Changes
- Added ability to use natural language to search/filter datasets via the `ask_ai` method.
- Included new visual assets and examples in the explorer's documentation notebook.
- Removed the `dash.md` file and updated related documentation links.
- Introduced the `plot_query_result` utility function to visualize query results.
- Enforced dependency versions for `lancedb` and `streamlit`.
- Updated the Explorer's GUI code to incorporate AI queries and improved error handling.
- Renamed the dashboard document for consistency.
- Improved SQL query handling with robustness checks and OpenAI integration for natural language processing.

### 🎯 Purpose & Impact
- The natural language search feature powered by large language models (LLMs) aims to make data querying more intuitive and accessible for users without deep knowledge of SQL.
- Improved visualizations and documentation will help users understand and utilize the Explorer's capabilities more effectively.
- Dependency version restrictions ensure compatibility and prevent issues from arising due to updates or changes in external libraries.
- By exposing the Explorer's capabilities through a user-friendly GUI, the update aims to expand its user base and enhance the overall user experience, potentially inviting more users to explore and engage with their datasets using Ultralytics technology.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
The new usage would be i.e.:

### CLI

```bash
yolo settings openai_key="..."
yolo explorer  # automatically knows openai_key now and in the future
```

### Python

```python
from ultralytics import settings

# Update a setting (saved to disk for now and future use)
settings.update({'openai_key': '...'})

# Run Explorer
# ...
```

**Comment by AyushExel** [comment]
@glenn-jocher updated

**Review by RizwanMunawar — APPROVED** [review]
@AyushExel Image compression is looking good now :)

**Comment by glenn-jocher** [comment]
@AyushExel looks good, I like the prompt! Let's make the model name parameterized so they can change if they want.

We also need a dashboard.md that is missing now, but I'll merge like this for updating tomorrow.

**Pull request merged**
