### PR TITLE
Replace `onnx2tf` usage from CLI to Python

### LINKED ISSUE #8394: Change onnx2tf cli command call to python sdk
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

During the Yolov8 export to tflite, the `onnx2tf` cli command is called using this command:
``` python
cmd = f'onnx2tf -i "{f_onnx}" -o "{f}" -nuo {verbosity} {int8}'.strip()
subprocess.run(cmd, shell=True)
```

This can cause issues with things like IDE debuggers (I'm using VSCode), because the python environment that is used when the script is run does not apply to the command line, so that line fails.

There is an sdk alternative, like so

``` python
import onnx2tf

onnx2tf.convert(
    input_onnx_file_path=f_onnx,
    output_folder_path=f,
    not_use_onnxsim=True, # -nuo
    verbosity="info", # or "error"
    output_integer_quantized_tflite=True, # int8
)
```

This would simplify the script, not having to call it from the shell.
I am willing to work on a PR if that would help.

### Environment

On an M1 macbook pro, I tried to run the YOLOv8 exporter to tflite in the VSCode debugger tool, and it failed saying it couldn't find the command "onnx2tf", because the debugger environment doesn't extend to the shell

### Minimal Reproducible Example

Run the following from VSCode using the python debugger

``` python
from ultralytics import YOLO

model = YOLO("yolov8n.pt")
model.export(format="tflite")
```

It should show this in the terminal: `/bin/sh: onnx2tf: command not found`
And it will fail later in the export when it tries to load the saved_model, which was never made

`OSError: SavedModel file does not exist at: yolov8n_saved_model/{saved_model.pbtxt|saved_model.pb}`

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by ALMerrill**
closes #8394

Currently, during the tflite export, `onnx2tf` is called using `subprocess.run`, which can cause environment issues at times, like when debugging in VSCode. onnx2tf has a python sdk that matches the cli, so this changes to use that, with the `onnx2tf.convert` function, passing in the same arguments that were passed to the cli command.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced TensorFlow SavedModel export functionality with new quantization options.

### 📊 Key Changes
- Changed verbosity argument setup to use string values rather than commands.
- Added an option to specify quantization type (`oiqt` and `qt` variables).
- Implemented conditional logic for generating INT8 calibration images if data is provided.
- Replaced previous command-line subprocess call with a direct `onnx2tf.convert` function call.
- Refined input data specification through a new `cind` variable for custom input handling.

### 🎯 Purpose & Impact
- 🎯 The purpose of these changes is to streamline TensorFlow model exports and allow for more efficient and flexible quantization processes.
- 🖥️ Users benefit from a more robust export pipeline, potentially leading to faster and smaller models suitable for resource-constrained environments like mobile devices.
- 🚀 This could significantly impact those deploying AI models to edge devices by simplifying the process and providing additional quantization configuration options.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Model Exporting for Additional Platforms and Improved Quantization

### 📊 Key Changes
- Added support for NCNN model format in the exporter capabilities. 🆕
- Replaced manual command-line calls to onnx2tf conversion with direct usage of the onnx2tf library API. 🔄
- Updated integer (INT8) quantization approach to use the onnx2tf library's functionality. 🔢
- Removed unnecessary import (`shutil`) when clearing the output folder before exporting. 🧹
- Adjusted the verbosity levels for the onnx2tf conversion process to be passed as direct arguments instead of strings. 📢
- Implemented the use of a temporary numpy file to store calibration images necessary for INT8 quantization. 🖼️
- Removed redundant conversion flags and refactored the TensorFlow.js conversion command for clarity. ✂️

### 🎯 Purpose & Impact
- **NCNN Model Support:** Allows users to export models to NCNN format for deployment on platforms that use NCNN, opening up a wider range of use cases. 📲
- **Direct API Usage:** Results in cleaner code and potentially more reliable exports due to using the onnx2tf library's built-in functions. 🛠️
- **Improved Quantization:** Enhances the export process for INT8 quantization, which can lead to more efficient models, particularly for edge devices with lower computational power. 💡
- **Cleaner Export Directory:** Ensures that the export directory is clean for each export, preventing any potential issues from leftovers from previous export operations. 🚮
- **Better Logging:** The revised verbosity levels can help users better understand the export process or debug issues if they arise. 📊
- **Increased Accessibility:** The changes collectively make it easier for users to export their models and potentially improve performance on target devices. 🎯

These updates may lead to a smoother experience for developers and users working with exported Ultralytics models and could help in practical deployments on varied platforms.

### CODE REVIEW

**Comment by ALMerrill** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@ALMerrill I've returned both quantization methods to "per-tensor" since this is the current method. Do you have any info on the per-channel change you implemented for non-int8?

**Comment by glenn-jocher** [comment]
@ALMerrill PR merged! Please double check my updates to make sure I didn't break anything here. Thank you for your contibutions!

**Comment by ALMerrill** [comment]
@glenn-jocher huh, sorry no I must have just added that wrong, looking back at it. Good catch, looks good!

**Comment by glenn-jocher** [comment]
@ALMerrill No worries at all! 😄 Thanks for double-checking and for your contributions. If there's anything else you notice or any further improvements you'd like to suggest, feel free to share. Happy coding!

**Comment by ALMerrill** [comment]
@glenn-jocher Sounds great! Happy to help.

**Pull request merged**
