### PR TITLE
Add Japanese README

### PR DESCRIPTION
**Pull request by eltociear**
I created Japanese translated README.

### Summary
🖼️🌐🇯🇵

This pull request adds a Japanese translation of the README file and updates the English and Chinese versions to include a link to it. It also adds a banner image and a language selector to the top of each README file. These changes aim to enhance the presentation and accessibility of the repository for different audiences.

> _`README` updated_
> _Banner, languages added_
> _Autumn of YOLO_

### Walkthrough
*  Add a banner image and a language selector to the README files in English, Chinese, and Japanese ([link](https://github.com/ultralytics/ultralytics/pull/4267/files?diff=unified&w=0#diff-4363f5cdfbf3792c03d3a3350dc270c31f005c6ef368a14c41e56165b4836b93R1-R269),  ). The banner image links to the Ultralytics website and showcases the YOLOv8 model. The language selector allows users to switch between the three versions of the README file.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Japanese README for YOLOv8 has been added to the Ultralytics repository.

### 📊 Key Changes
- Added `README.ja-JP.md` to the repository, providing comprehensive documentation in Japanese.

### 🎯 Purpose & Impact
- **Accessibility**: This change allows Japanese-speaking users to access detailed YOLOv8 documentation, enhancing usability for non-English speakers. 🌏
- **Community Support**: Facilitates broader engagement from the Japanese AI community. 🤝

### CODE REVIEW

**Comment by eltociear** [comment]
I have read the CLA Document and I sign the CLA

**Comment by eltociear** [comment]
recheck

**Comment by glenn-jocher** [comment]
@eltociear hello,

I noticed your message, "recheck", but it's not entirely clear what troubleshooting or support you're seeking related to the YOLOv8 model. Could you be more specific about the issue or question you're encountering? Any additional information—such as your use case, any error messages you’ve received, or functions of the model you're unsure about—could be quite helpful for me to understand better and provide specific assistance.

Looking forward to your response.

Best,
Glenn Jocher

**Comment by eltociear** [comment]
@glenn-jocher Sorry, I had to remove `recheck` as it is the word for checking CLA signatures.

**Comment by glenn-jocher** [comment]
Hello @eltociear,

Thank you for the clarification. Please feel free to proceed with the contributions to the repository.

The addition of a translated README in Japanese would indeed contribute greatly to making YOLOv8 more accessible to the Japanese-speaking community. Thank you for your valuable effort in this extension. Remember that translations, like any other contributions, are most effective when they are maintained over time to incorporate any updates or changes.

If you ever have any questions or need further assistance, please don't hesitate to reach out.

Best,
Glenn

**Comment by eltociear** [comment]
@glenn-jocher Thank you for your reply.
I will continue to update the README as we see fit.

**Comment by glenn-jocher** [comment]
@eltociear hello,

Your commitment to maintaining the translated README is highly appreciated. This will certainly ensure that our Japanese-speaking community continues to have accessible resources for working with YOLOv8.

Remember, your expertise and contributions are valuable to the YOLOv8 community, helping us to improve and refine the model together. So, please feel free to continue making such impactful contributions and share your ideas or feedback.

Thank you again for your ongoing support. 

Best,
Glenn

**Review by kawa-mi — APPROVED** [review]

**Review by ambitious-octopus — COMMENTED** [review]
@glenn-jocher Do you think we need a Japanese README? Now that @john-rocky  is with us we can have his review too.

**Comment by glenn-jocher** [comment]
@ambitious-octopus I think we're well served now with the Japanese docs pages at https://docs.ultralytics.com/ja so we can close this.

@eltociear thank you so much for your contributions. We are closing as not required since we have migrated our translation effort for Japanese users at https://docs.ultralytics.com/ja.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.

**Pull request closed without merging**
