### PR TITLE
Improve JetPack5 Dockerfile for NVIDIA Jetson

### LINKED ISSUE #17345: Missing GPU support in the ultralytics/ultralytics:latest-jetson-jetpack5 image
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train, Predict, Integrations

### Bug

The container image ultralytics/ultralytics:latest-jetson-jetpack5 for NVIDIA Jetson devices does not support GPU usage in the Phython environment. Therefore it cannot be used with ultralytics HUB when GPU is enabled. Only training and prediction on CPU is possible. 
In general the container image supports GPU, but only from the CLI where is no HUB integration. 

Details can be found here: #17291

### Environment

output from the CLI: `yolo checks`
WARNING ⚠️ torchvision==0.14 is incompatible with torch==2.0.
Run 'pip install torchvision==0.15' to fix torchvision or 'pip install -U torch torchvision' to update both.
For a full compatibility table see https://github.com/pytorch/vision#installation
Creating new Ultralytics Settings v0.0.6 file ✅ 
View Ultralytics Settings with 'yolo settings' or at '/root/.config/Ultralytics/settings.json'
Update Settings with 'yolo settings key=value', i.e. 'yolo settings runs_dir=path/to/dir'. For help see https://docs.ultralytics.com/quickstart/#ultralytics-settings.
Ultralytics 8.3.27 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CPU (ARMv8 Processor rev 0 (v8l))
Setup complete ✅ (6 CPUs, 6.7 GB RAM, 87.3/468.3 GB disk)

OS                  Linux-5.10.216-tegra-aarch64-with-glibc2.29
Environment         Linux
Python              3.8.10
Install             git
RAM                 6.67 GB
Disk                87.3/468.3 GB
CPU                 ARMv8 Processor rev 0 (v8l)
CPU count           6
GPU                 None
GPU count           None
CUDA                None

numpy               ✅ 1.23.5>=1.23.0
matplotlib          ✅ 3.7.5>=3.3.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.2>=5.3.1
requests            ✅ 2.28.2>=2.23.0
scipy               ✅ 1.10.1>=1.4.1
torch               ✅ 2.0.0a0+ec3941ad.nv23.2>=1.8.0
torchvision         ✅ 0.14.1a0+5e8e2f1>=0.9.0
tqdm                ✅ 4.66.6>=4.64.0
psutil              ✅ 6.1.0
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.10>=2.0.0
numpy               ✅ 1.23.5<2.0.0; sys_platform == "darwin"
torch               ✅ 2.0.0a0+ec3941ad.nv23.2!=2.4.0,>=1.8.0; sys_platform == "win32"

system settings:
image

### Minimal Reproducible Example

setting up the training in ultralytics HUB with GPU enabled. 
```
>>> from ultralytics import YOLO, checks, hub
>>> checks()
Ultralytics 8.3.27 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CPU (ARMv8 Processor rev 0 (v8l))
Setup complete ✅ (6 CPUs, 6.7 GB RAM, 87.3/468.3 GB disk)
>>> 
>>> hub.login('<token>')
requirements: Ultralytics requirement ['hub-sdk>=0.0.12'] not found, attempting AutoUpdate...
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Collecting hub-sdk>=0.0.12
  Downloading hub_sdk-0.0.14-py3-none-any.whl.metadata (10 kB)
Requirement already satisfied: requests in /usr/local/lib/python3.8/dist-packages/requests-2.28.2-py3.8.egg (from hub-sdk>=0.0.12) (2.28.2)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.8/dist-packages/certifi-2022.12.7-py3.8.egg (from requests->hub-sdk>=0.0.12) (2022.12.7)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.8/dist-packages/charset_normalizer-3.0.1-py3.8.egg (from requests->hub-sdk>=0.0.12) (3.0.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.8/dist-packages/idna-3.4-py3.8.egg (from requests->hub-sdk>=0.0.12) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.8/dist-packages/urllib3-1.26.14-py3.8.egg (from requests->hub-sdk>=0.0.12) (1.26.14)
Downloading hub_sdk-0.0.14-py3-none-any.whl (42 kB)
Installing collected packages: hub-sdk
Successfully installed hub-sdk-0.0.14

requirements: AutoUpdate success ✅ 4.7s, installed 1 package: ['hub-sdk>=0.0.12']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect

Ultralytics HUB: New authentication successful ✅
True
>>> 
>>> model = YOLO('https://hub.ultralytics.com/models/Eq3yr2SSLFuZfoh8EFWP')
Ultralytics HUB: View model at https://hub.ultralytics.com/models/Eq3yr2SSLFuZfoh8EFWP 🚀
>>> results = model.train()
Ultralytics 8.3.27 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/ultralytics/ultralytics/engine/model.py", line 796, in train
    self.trainer = (trainer or self._smart_load("trainer"))(overrides=args, _callbacks=self.callbacks)
  File "/ultralytics/ultralytics/engine/trainer.py", line 103, in __init__
    self.device = select_device(self.args.device, self.args.batch)
  File "/ultralytics/ultralytics/utils/torch_utils.py", line 192, in select_device
    raise ValueError(
ValueError: Invalid CUDA 'device=0' requested. Use 'device=cpu' or pass valid CUDA device(s) if available, i.e. 'device=0' or 'device=0,1,2,3' for Multi-GPU.

torch.cuda.is_available(): False
torch.cuda.device_count(): 0
os.environ['CUDA_VISIBLE_DEVICES']: all
See https://pytorch.org/get-started/locally/ for up-to-date torch install instructions if no CUDA devices are seen by torch.

>>> 
```
**following the CLI guide for Jetson GPU support works** 

```
root@ultralytics-demo:/ultralytics# yolo export model=yolo11n.pt format=engine device=0
WARNING ⚠️ torchvision==0.14 is incompatible with torch==2.0.
Run 'pip install torchvision==0.15' to fix torchvision or 'pip install -U torch torchvision' to update both.
For a full compatibility table see https://github.com/pytorch/vision#installation
Ultralytics 8.3.27 🚀 Python-3.8.10 torch-2.0.0a0+ec3941ad.nv23.02 CUDA:0 (Xavier, 6833MiB)
YOLO11n summary (fused): 238 layers, 2,616,248 parameters, 0 gradients, 6.5 GFLOPs

PyTorch: starting from 'yolo11n.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (5.4 MB)
requirements: Ultralytics requirement ['onnxslim'] not found, attempting AutoUpdate...
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager, possibly rendering your system unusable.It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv. Use the --root-user-action option if you know what you are doing and want to suppress this warning.
Collecting onnxslim
  Downloading onnxslim-0.1.36-py3-none-any.whl.metadata (2.9 kB)
Requirement already satisfied: onnx in /usr/local/lib/python3.8/dist-packages (from onnxslim) (1.17.0)
Requirement already satisfied: sympy in /usr/local/lib/python3.8/dist-packages (from onnxslim) (1.11.1)
Requirement already satisfied: packaging in /usr/local/lib/python3.8/dist-packages (from onnxslim) (20.9)
Requirement already satisfied: numpy>=1.20 in /usr/local/lib/python3.8/dist-packages (from onnx->onnxslim) (1.23.5)
Requirement already satisfied: protobuf>=3.20.2 in /usr/local/lib/python3.8/dist-packages (from onnx->onnxslim) (4.25.5)
Requirement already satisfied: pyparsing>=2.0.2 in /usr/local/lib/python3.8/dist-packages (from packaging->onnxslim) (3.1.4)
Requirement already satisfied: mpmath>=0.19 in /usr/local/lib/python3.8/dist-packages (from sympy->onnxslim) (1.2.1)
Downloading onnxslim-0.1.36-py3-none-any.whl (140 kB)
Installing collected packages: onnxslim
Successfully installed onnxslim-0.1.36

requirements: AutoUpdate success ✅ 5.8s, installed 1 package: ['onnxslim']
requirements: ⚠️ Restart runtime or rerun command for updates to take effect


ONNX: starting export with onnx 1.17.0 opset 16...
====== Diagnostic Run torch.onnx.export version 2.0.0a0+ec3941ad.nv23.02 =======
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

ONNX: slimming with onnxslim 0.1.36...
ONNX: export success ✅ 14.2s, saved as 'yolo11n.onnx' (10.2 MB)

TensorRT: starting export with TensorRT 8.5.2.2...
[11/04/2024-22:07:52] [TRT] [I] [MemUsageChange] Init CUDA: CPU +183, GPU +0, now: CPU 1608, GPU 4779 (MiB)
[11/04/2024-22:07:55] [TRT] [I] [MemUsageChange] Init builder kernel library: CPU +106, GPU +131, now: CPU 1736, GPU 4920 (MiB)
[11/04/2024-22:07:55] [TRT] [I] ----------------------------------------------------------------
[11/04/2024-22:07:55] [TRT] [I] Input filename:   yolo11n.onnx
[11/04/2024-22:07:55] [TRT] [I] ONNX IR version:  0.0.10
[11/04/2024-22:07:55] [TRT] [I] Opset version:    16
[11/04/2024-22:07:55] [TRT] [I] Producer name:    pytorch
[11/04/2024-22:07:55] [TRT] [I] Producer version: 2.0.0
[11/04/2024-22:07:55] [TRT] [I] Domain:           
[11/04/2024-22:07:55] [TRT] [I] Model version:    0
[11/04/2024-22:07:55] [TRT] [I] Doc string:       
[11/04/2024-22:07:55] [TRT] [I] ----------------------------------------------------------------
[11/04/2024-22:07:55] [TRT] [W] onnx2trt_utils.cpp:375: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
TensorRT: input "images" with shape(1, 3, 640, 640) DataType.FLOAT
TensorRT: output "output0" with shape(1, 84, 8400) DataType.FLOAT
TensorRT: building FP32 engine as yolo11n.engine
[11/04/2024-22:07:57] [TRT] [I] ---------- Layers Running on DLA ----------
[11/04/2024-22:07:57] [TRT] [I] ---------- Layers Running on GPU ----------
[11/04/2024-22:07:57] [TRT] [I] [GpuLayer] CONVOLUTION: /model.0/conv/Conv
...
[11/04/2024-22:07:57] [TRT] [I] [MemUsageChange] Init cuBLAS/cuBLASLt: CPU +0, GPU +0, now: CPU 1726, GPU 4920 (MiB)
[11/04/2024-22:07:57] [TRT] [I] [MemUsageChange] Init cuDNN: CPU +0, GPU +0, now: CPU 1726, GPU 4920 (MiB)
```
and GPU is used: 
image

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by lakshanthad**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Updated the Dockerfile for JetPack 5 to improve compatibility, streamline dependencies, and ensure the latest tools are available for YOLO models on NVIDIA Jetson devices. 🚀  

### 📊 Key Changes  
- 🆕 Updated base image to `nvcr.io/nvidia/l4t-jetpack:r35.4.1`, which aligns with JetPack 5.1.2.  
- 🔄 Simplified dependencies installation and cleaned up unnecessary components like OpenCV-related removals.  
- 🔼 Upgraded ONNX Runtime GPU to version 1.18.0 and updated Torch/TorchVision installations with specific Aarch64 builds.  
- 🚀 Improved TensorRT compatibility by adjusting dependencies.  

### 🎯 Purpose & Impact  
- ✅ Ensures compatibility with NVIDIA JetPack 5.1.2 for better performance and reliability on Jetson devices like Xavier and Orin.  
- 📉 Reduces build complexity and potential conflicts by streamlining package installations.  
- ⚡ Improves performance for exporting and running YOLO models on edge AI environments.  
- 🛠 Makes it easier for developers to deploy and experiment with YOLO models on Jetson platforms with up-to-date configurations.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @lakshanthad, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any relevant issues. Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics Continuous Integration (CI) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our Contributor License Agreement (CLA) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

This is an automated response to help streamline the review process. An Ultralytics engineer will review your PR and assist you as soon as possible. Thank you for contributing! 🚀

**Comment by lakshanthad** [comment]
@glenn-jocher I have rebased JetPack5 Dockerfile image from `nvcr.io/nvidia/l4t-pytorch:r35.2.1-pth2.0-py3` to `nvcr.io/nvidia/l4t-jetpack:r35.4.1` since NVIDIA stopped providing updates to `nvcr.io/nvidia/l4t-pytorch:xxx` images and now relying on `nvcr.io/nvidia/l4t-jetpack:xxx` moving forward. We are using `nvcr.io/nvidia/l4t-jetpack:xxx` for JetPack6 Docker as well.

This update ensures the below GitHub issue is resolved it will be automatically closed after this merge:
https://github.com/ultralytics/ultralytics/issues/17345

I have verified this change with the below Docker CI:
https://github.com/ultralytics/ultralytics/actions/runs/12441110487

Also I was able to remove unnecessary dependencies as a result of this update.

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@lakshanthad got it!

**Comment by glenn-jocher** [comment]
@lakshanthad this is the first PR I've tested our new Ultralytics Actions 0.0.27 on that adds a message to all linked Issues notifying the user of the merge, requesting confirmation of the fix and encouraging future issues. Looks like it's working well!

**Comment by lakshanthad** [comment]
@glenn-jocher Looks like it is a great addition and great to see its working well!

**Comment by lakshanthad** [comment]
@glenn-jocher I have noticed you delete the branch manually every time you merge a PR. Do you think this can be automated as well?

**Pull request merged**
