### PR TITLE
Add metadata of model info when using triton inference server

### PR DESCRIPTION
**Pull request by quanqigu**
When deploy onnx model to triton server, and config ultralytics to use the model in triton inference server, there's exception occured.
```
Traceback (most recent call last):
  File "/Users/evilkylin/Projects/argus/workers/face_tracker/tracker.py", line 145, in <module>
    tracked_objs = tracker.track_video("/Users/evilkylin/Downloads/5fd83cfa-e74b-4f29-bd7d-a65d3e671520_trans.mp4")
  File "/Users/evilkylin/Projects/argus/workers/face_tracker/tracker.py", line 46, in track_video
    track_rets = self.model.track(frame, tracker="botsort.yaml", show=self.debug, save=self.debug)
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/model.py", line 611, in track
    return self.predict(source=source, stream=stream, **kwargs)
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/model.py", line 564, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
    return list(self.stream_inference(source, model, *args, **kwargs))  # merge list of Result into one
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 274, in stream_inference
    s[i] += self.write_results(i, Path(paths[i]), im, s)
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 334, in write_results
    string += f"{result.verbose()}{result.speed['inference']:.1f}ms"
  File "/Users/evilkylin/Projects/miniconda3/envs/argus/lib/python3.10/site-packages/ultralytics/engine/results.py", line 647, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
```

The original discussion about this issue is [here](https://github.com/orgs/ultralytics/discussions/9406#discussioncomment-10479347)

The original test code like
```python
from ultralytics import YOLO
model_path = "grpc://localhost:80/yolov8-face"
model = YOLO(model=model_path, task='pose')
track_rets = model.track(frame, tracker="botsort.yaml", show=True)
```

In this PR, I have added a metainfo to the triton backend as the attributes like names, kpt_shape and task are not initilized. Now we can add meta info when initialized the mode like this.

```python
model = YOLO(model=model_path, task='pose', metadata="metadata.yaml")
```
the metadata.yaml is like this extracted from onnx.
```yaml
kpt_shape: "[5, 3]"
description: "Ultralytics YOLOv8n-pose model trained on ..."
names: "{0: 'face'}"
task: "pose"
license: "AGPL-3.0 License (https://ultralytics.com/license)"
date: "2024-08-28T16:50:32.940728"
batch: "8"
version: "8.2.74"
docs: "https://docs.ultralytics.com"
author: "Ultralytics"
stride: "32"
imgsz: "[640, 640]"
```

As I am newbie here, and I only test the track mode with a Face Pose model, not sure if there's other place should be updated. 

Hope get you feedback. Thanks.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added metadata support to the YOLO model and related components 🛠️📄

### 📊 Key Changes
- Added a new `metadata` parameter to various model initialization methods.
- Updated the `setup_model` method to handle the `metadata` parameter.

### 🎯 Purpose & Impact
- **Enhanced Model Initialization**: The new parameter allows for more flexibility and customization during the model setup phase.
- **Improved Documentation and Tracking**: By incorporating metadata, users and systems can better document, track, and manage additional information about the models.
  
Overall, these changes improve the user experience by offering more detailed and customizable model configurations. 📈🔧

### CODE REVIEW

**Comment by quanqigu** [comment]
I have read the CLA Document and I sign the CLA

**Comment by quanqigu** [comment]
> @quanqigu could you review the failing CI tests?

Will do.

**Comment by quanqigu** [comment]
@glenn-jocher I have fixed the unit test.

There's something compatibility when using setup_model with metadata, looks like SAM don't use AutoBackend to initialize model, so I can't deliver the metadata to them.

So the solution is to deliver the metadata to the overrides which is used in every Predictor.

What do you think?

**Comment by glenn-jocher** [comment]
Thanks for addressing the unit test. Delivering the metadata to the overrides used in every Predictor sounds like a solid approach. Please proceed with that solution.

**Comment by quanqigu** [comment]
Ah, the current commit has adopted the overrides to deliver metadata. From my test, it is good.

**Comment by glenn-jocher** [comment]
Great to hear that the current commit with overrides for metadata delivery is working well in your tests. If you encounter any further issues, feel free to reach out.

**Comment by glenn-jocher** [comment]
@quanqigu I reviewed the changes but don't understand the changes to default.yaml. We can not accept additional arguments here, metadata is not modifiable, it is a property of the models.

**Comment by quanqigu** [comment]
@glenn-jocher Without adding metadata into default.yaml, it won't allow me to deliver metadata to the overrides because there's a validator to check if the custom config item is in default.yaml...

**Comment by glenn-jocher** [comment]
Thank you for the clarification. Instead of modifying `default.yaml`, consider handling metadata within the model initialization or setup functions directly to avoid validation issues.

**Comment by quanqigu** [comment]
Now, it will set metadata to predictor if there's no metadata.

**Comment by glenn-jocher** [comment]
Thank you for the update. Please ensure that the metadata is correctly set within the predictor and test thoroughly to confirm it resolves the issue.

**Comment by quanqigu** [comment]
From my test, it does solve the issue. We can use model hosted on triton.

**Comment by glenn-jocher** [comment]
Thank you for confirming that the solution works with the model hosted on Triton. If you encounter any further issues or have additional questions, feel free to reach out.

**Comment by quanqigu** [comment]
Is this PR okay to merge? @glenn-jocher

**Comment by glenn-jocher** [comment]
Thank you for your contribution. The PR looks good from your tests. We'll proceed with a final review and merge it if everything checks out.

**Comment by quanqigu** [comment]
Glad to here that. I have another topic to need to discuss about large dependencies, it is too bigger. https://github.com/orgs/ultralytics/discussions/16008

**Comment by glenn-jocher** [comment]
Thank you for bringing this up. Please check the discussion thread for updates and suggestions on managing large dependencies.

**Comment by glenn-jocher** [comment]
@quanqigu I've reviewed the PR but I'm not sure we need this. The package will automatically search for a metadata.yaml next to the model for exported formats like SavedModel etc. that we do not have support for internal metadata, so there should be no need to define an additional path to a file:

Many other formats like CoreML, ONNX, TensorRT, etc. include internal metadata already and have no need for an external metadata file:

Screenshot 2024-09-07 at 20 02 39

**Comment by quanqigu** [comment]
@glenn-jocher I understand the examples what you mentioned, I guess all of these model file are locally accessible. But when model is hosted in triton inference server, you only have remote API to inference, the package is not able to get metadata.

I suggest you can have a try, if it support, that is great. We don't need this PR to do extra work.

PS: there's related issue about this https://github.com/ultralytics/ultralytics/issues/16038.

**Comment by glenn-jocher** [comment]
@quanqigu thank you for the suggestion. We'll review the related issue and consider improvements for handling metadata with Triton-hosted models. Your feedback is valuable, and we'll keep it in mind for future updates.

**Comment by quanqigu** [comment]
can you give any suggestion how to set metadata for triton?

**Comment by glenn-jocher** [comment]
You can set metadata for Triton by creating a `metadata.yaml` file with the necessary details and loading it during model initialization. If you need further assistance, feel free to ask in the community discussions.

**Comment by quanqigu** [comment]
So how to that? Can you show the example with the code? 

Current PR is trying to load the metadata.yaml, but you say there's other way, so what is that way? I am confused by what you are talking, you response looks like a chatbot missing context...I am upset for this PR, so I close this PR.

**Pull request closed without merging**
