### PR TITLE
`ultralytics 8.0.126` Ray Tune refactoring

### PR DESCRIPTION
**Pull request by glenn-jocher**
Refactor Ray Tune into tuner.py. Possibly prepare to add YOLOv5 hyp evolution also in tuner.py as a separate function.

### Summary
🧹🔧🚀

This pull request refactors and simplifies the hyperparameter tuning code of the `YOLO` class. It removes an unused import and a redundant parameter from `ultralytics.yolo.engine.model`, and moves the Ray Tune logic to a new module `ultralytics.yolo.utils.tuner`.

> _To improve the `model` module's state_
> _They removed an import that was late_
> _And refactored the `tune`_
> _To a function in `utils`_
> _That uses Ray Tune to search and update_

### Walkthrough
*  Refactor the tuning logic of the `YOLO` class by extracting it to a separate function `run_ray_tune` in `ultralytics.yolo.utils.tuner` ([link](https://github.com/ultralytics/ultralytics/pull/3511/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL414-R411), [link](https://github.com/ultralytics/ultralytics/pull/3511/files?diff=unified&w=0#diff-b1729b763cbaa3709b267481a09ee9bae7455750784b32e2acacefccfd97934eR45-R125))
* Simplify the signature of the `tune` method of the `YOLO` class by using `*args` and `**kwargs` instead of listing all the possible arguments ([link](https://github.com/ultralytics/ultralytics/pull/3511/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL390-R390))
* Add the import of `NUM_THREADS` from `ultralytics.yolo.utils` in `ultralytics.yolo.utils.tuner`, since it is used by the `run_ray_tune` function ([link](https://github.com/ultralytics/ultralytics/pull/3511/files?diff=unified&w=0#diff-b1729b763cbaa3709b267481a09ee9bae7455750784b32e2acacefccfd97934eL3-R3))
* Remove the unused import of `NUM_THREADS` from `ultralytics.yolo.utils` in `ultralytics.yolo.engine.model` ([link](https://github.com/ultralytics/ultralytics/pull/3511/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cL12-R12))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated continuous integration, hyperparameter documentation, and version bump for improved performance and usability.

### 📊 Key Changes
- 🔧 Adjusted benchmark hard fail thresholds for classification and pose models.
- 📝 Simplified hyperparameter tuning documentation with clearer instructions and an optional W&B integration.
- 🧮 Integrate more straightforward hyperparameter tuning using `run_ray_tune` utility in the YOLO model class.
- 🔍 Ensured more robust error handling in the benchmarking script.
- 🎉 Included mappings for tasks to their corresponding data and metrics for consistency.
- ⬆️ Bumped Ultralytics version to '8.0.126'.

### 🎯 Purpose & Impact
- 🎭 The modified hard fail values prevent benchmarks from incorrectly failing, improving reliability.
- 📚 Hyperparameter tuning documentation revisions make it easier for users to optimize their models effectively, whether they are beginners or experts.
- 🛠️ Refactoring model `tune` method streamlines the tuning process, aiding developers in enhancing model performance with less complexity.
- 🤖 Tighter benchmark error checks enhance the script's resilience across diverse scenarios, ensuring solid performance reporting.
- 🪪 Simplified task-to-dataset/metric correlation leads to cleaner code and easier understanding of data workflow.
- 🔄 Incrementing the software version number signals improvements and bug fixes to users, encouraging them to update for the best experience.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel this is a Ray Tune refactor and cleanup. I think everything still works correctly, but one thing I don't understand is why at the end of the tuning session all metrics print out except the one that we've asked for, which is `metrics/mAP50-95(B)`:


```
Trial _tune_b97be_00009 completed.
== Status ==
Current time: 2023-07-04 01:34:01 (running for 00:02:37.23)
Using AsyncHyperBand: num_stopped=0
Bracket: Iter 10.000: None
Logical resource usage: 7.0/8 CPUs, 0/0 GPUs
Result logdir: /Users/glennjocher/PycharmProjects/ultralytics/runs/tune/_tune_2023-07-04_01-31-22
Number of trials: 10/10 (10 TERMINATED)
+-------------------+------------+-----------------+-----------+----------+--------------+-----------+----------+-----------+------------+-----------+----------+------------+----------+----------+------------+----------+---------------+-----------+---------+-------------+-----------------+-------------------+----------------+--------+------------------+------------------------+---------------------+--------------------+
| Trial name        | status     | loc             |       box |      cls |   copy_paste |   degrees |   fliplr |    flipud |      hsv_h |     hsv_s |    hsv_v |        lr0 |      lrf |    mixup |   momentum |   mosaic |   perspective |     scale |   shear |   translate |   warmup_epochs |   warmup_momentum |   weight_decay |   iter |   total time (s) |   metrics/precision(B) |   metrics/recall(B) |   metrics/mAP50(B) |
|-------------------+------------+-----------------+-----------+----------+--------------+-----------+----------+-----------+------------+-----------+----------+------------+----------+----------+------------+----------+---------------+-----------+---------+-------------+-----------------+-------------------+----------------+--------+------------------+------------------------+---------------------+--------------------|
| _tune_b97be_00000 | TERMINATED | 127.0.0.1:29231 | 0.0899757 | 1.35348  |    0.987713  |   3.14537 | 0.20417  | 0.81718   | 0.0112337  | 0.0117206 | 0.180757 | 0.0540397  | 0.65891  | 0.791916 |   0.614128 | 0.722558 |   6.32291e-05 | 0.581455  | 9.84815 |   0.408     |        2.84159  |         0.373677  |    0.000822812 |     11 |          15.1989 |               0.631585 |            0.65     |           0.629745 |
| _tune_b97be_00001 | TERMINATED | 127.0.0.1:29231 | 0.107092  | 3.84756  |    0.753408  |   0.94927 | 0.116204 | 0.834814  | 0.0385748  | 0.730645  | 0.53101  | 0.0691727  | 0.192001 | 0.961259 |   0.609994 | 0.532051 |   0.000280134 | 0.699742  | 2.35258 |   0.896452  |        3.71391  |         0.608592  |    0.000516007 |     11 |          14.4288 |               0.638009 |            0.65     |           0.631174 |
| _tune_b97be_00002 | TERMINATED | 127.0.0.1:29231 | 0.0548746 | 1.15135  |    0.0200919 |  38.9578  | 0.747606 | 0.848047  | 0.0264099  | 0.630871  | 0.172647 | 0.017458   | 0.899404 | 0.853864 |   0.686975 | 0.515584 |   0.000927339 | 0.295507  | 1.28227 |   0.649386  |        0.331358 |         0.710855  |    0.000439222 |     11 |          14.5587 |               0.628968 |            0.65     |           0.639805 |
| _tune_b97be_00003 | TERMINATED | 127.0.0.1:29231 | 0.110165  | 3.80355  |    0.154916  |  37.9268  | 0.169105 | 0.319102  | 0.00730187 | 0.849557  | 0.630805 | 0.00568573 | 0.909064 | 0.970189 |   0.831785 | 0.486653 |   0.000158575 | 0.0609385 | 8.5127  |   0.632697  |        4.92059  |         0.689783  |    0.000315465 |     11 |          14.4215 |               0.645141 |            0.65     |           0.640799 |
| _tune_b97be_00004 | TERMINATED | 127.0.0.1:29231 | 0.151679  | 3.42019  |    0.235081  |  16.4544  | 0.365754 | 0.0292913 | 0.0593324  | 0.132394  | 0.547281 | 0.0433089  | 0.391005 | 0.504431 |   0.975448 | 0.854273 |   0.000650414 | 0.302093  | 1.10767 |   0.119656  |        4.79392  |         0.0621253 |    0.000706029 |     11 |          14.9237 |               0.664351 |            0.65     |           0.632369 |
| _tune_b97be_00005 | TERMINATED | 127.0.0.1:29231 | 0.1594    | 3.44335  |    0.569787  |  23.0299  | 0.757017 | 0.471973  | 0.0361272  | 0.605398  | 0.335276 | 0.0923762  | 0.102342 | 0.972152 |   0.760898 | 0.489922 |   0.000113338 | 0.744288  | 3.00722 |   0.442797  |        1.991    |         0.044856  |    0.000978756 |     11 |          15.3235 |               0.75477  |            0.559338 |           0.63292  |
| _tune_b97be_00006 | TERMINATED | 127.0.0.1:29231 | 0.187691  | 0.946033 |    0.968077  |   3.26998 | 0.718363 | 0.777781  | 0.0651016  | 0.842957  | 0.87959  | 0.0448522  | 0.232776 | 0.437257 |   0.714048 | 0.222021 |   0.000427271 | 0.883819  | 5.62675 |   0.0481669 |        4.19073  |         0.931806  |    0.000707863 |     11 |          14.9139 |               0.752963 |            0.537864 |           0.637736 |
| _tune_b97be_00007 | TERMINATED | 127.0.0.1:29231 | 0.118032  | 3.21707  |    0.276183  |  35.7514  | 0.1364   | 0.994689  | 0.0206904  | 0.0165589 | 0.118085 | 0.0959115  | 0.991499 | 0.889405 |   0.632172 | 0.179618 |   0.000221131 | 0.487661  | 2.24087 |   0.731657  |        2.04626  |         0.631103  |    0.00092955  |     11 |          14.6986 |               0.734251 |            0.556369 |           0.641884 |
| _tune_b97be_00008 | TERMINATED | 127.0.0.1:29231 | 0.186262  | 3.18588  |    0.0543202 |  14.8315  | 0.663726 | 0.818494  | 0.0122171  | 0.450479  | 0.341141 | 0.0084637  | 0.413036 | 0.199654 |   0.77342  | 0.846318 |   0.000897536 | 0.620936  | 9.01102 |   0.0453497 |        1.57152  |         0.294543  |    0.000774763 |     11 |          14.9107 |               0.723764 |            0.55     |           0.631253 |
| _tune_b97be_00009 | TERMINATED | 127.0.0.1:29231 | 0.0354849 | 3.99198  |    0.394534  |  21.0633  | 0.102312 | 0.605899  | 0.0554795  | 0.215351  | 0.874247 | 0.0447916  | 0.219552 | 0.4493   |   0.701951 | 0.739877 |   9.20595e-05 | 0.199853  | 3.28133 |   0.584633  |        0.246102 |         0.94137   |    0.00050652  |     11 |          14.7727 |               0.727732 |            0.55     |           0.637772 |
+-------------------+------------+-----------------+-----------+----------+--------------+-----------+----------+-----------+------------+-----------+----------+------------+----------+----------+------------+----------+---------------+-----------+---------+-------------+-----------------+-------------------+----------------+--------+------------------+------------------------+---------------------+--------------------+
```

**Comment by glenn-jocher** [comment]
@AyushExel also where do I find the tuned/optimized hyp dict/vector?

**Comment by glenn-jocher** [comment]
@AyushExel I've also removed the train_args dict argument, now all additional train args can be passed normally. I've updated the Docs with this new usage, i.e.:


```python
from ultralytics import YOLO

# Define a YOLO model    
model = YOLO("yolov8n.pt")

# Run Ray Tune on the model
result = model.tune(data="coco128.yaml",
                    space={"lr0": tune.uniform(1e-5, 1e-1)},
                    epochs=50)
```

**Comment by AyushExel** [comment]
> is a Ray Tune refactor and cleanup. I think everything still works correctly, but one thing I don't understand is why at the end of the tuning session all metrics print out except the one that we've aske

The result object has a lot of information about the best metric, the best set of configs for that metric and many more things, which is one of the msps of Ray tune. Maybe we can copy an example from here to our docs as well https://docs.ray.io/en/latest/tune/examples/tune_analyze_results.html?

**Comment by AyushExel** [comment]
> 

looks good

**Review by AyushExel — APPROVED** [review]
Looks good. Maybe let's add how to interact with the result object to get the best run details in the docs as well?

**Comment by glenn-jocher** [comment]
@AyushExel oh wow yeah I see it now. Ok then the next step is instead of starting uniformly over the search space we want to use something more like a normal distribution centered on the initial hyp values. This can be clipped at the limits you have currently, but Normal or Normal-like is much better in my experience as the edges of the uniform distribution are typically very poor for most hyps. Do you know what the available search options are other than `tune.random()`?

**Pull request merged**
