### PR TITLE
Fix/mlflow

### LINKED ISSUE #1751: MLflow Error: "NoneType has no attribute log.param"
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Integrations

### Bug

When using `mlflow.autolog()`, `mlflow.autolog(disable=True) or `mlflow.start_run`, we get the following error when running the code on Databricks:

`MLflow Error: "NoneType has no attribute log.param"`

This is due to the fact that we set the `run` object to `None` in the `except` block. If you are running the experiment on Databricks, experiments will be automatically named `YOLOv8`, which will trigger an exception, since these names are invalid - consequently, `run` will be set to None and then the code tries to log params on top of an empty run object.

Code excerpt:

```python
try:
            run, active_run = mlflow, mlflow.start_run() if mlflow else None
            if active_run is not None:
                run_id = active_run.info.run_id
                LOGGER.info(f'{prefix}Using run_id({run_id}) at {mlflow_location}')
        except Exception as err:
            LOGGER.error(f'{prefix}Failing init - {repr(err)}')
            LOGGER.warning(f'{prefix}Continuing without Mlflow')
            run = None

        run.log_params(vars(trainer.model.args))
```

After the change I've done, we first check if there's already an active run; we create a new one if that's not the case. This solves the problem.

```python
try:
            active_run = mlflow.active_run()
            if not active_run:
                active_run = mlflow.start_run(experiment_id = experiment.experiment_id)
            run_id = active_run.info.run_id
            LOGGER.info(f'{prefix}Using run_id({run_id}) at {mlflow_location}')
            mlflow.log_params(vars(trainer.model.args))
        except Exception as err:
            LOGGER.error(f'{prefix}Failing init - {repr(err)}')
            LOGGER.warning(f'{prefix}Continuing without Mlflow')
```

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

I have the fixed the bug and tested locally. Currently working, will submit a PR to solve this issue.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by rafaelvp-db**
This PR solves the issue: https://github.com/ultralytics/ultralytics/issues/1751

In order to fix this, I made a small change in the MLflow Callback definition module (`yolo/utils/callbacks/mlflow.py`):

```python
try:
            active_run = mlflow.active_run()
            if not active_run:
                active_run = mlflow.start_run(experiment_id = experiment.experiment_id)
            run_id = active_run.info.run_id
            LOGGER.info(f'{prefix}Using run_id({run_id}) at {mlflow_location}')
            mlflow.log_params(vars(trainer.model.args))
        except Exception as err:
            LOGGER.error(f'{prefix}Failing init - {repr(err)}')
            LOGGER.warning(f'{prefix}Continuing without Mlflow')
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvement to MLflow experiment setup and logging in Ultralytics YOLO training callbacks.

### 📊 Key Changes
- Changed the default MLflow experiment name to include a `/Shared` prefix.
- Streamlined the MLflow run initiation process to handle ongoing runs.
- Removed unnecessary conditionals and redundancy in starting an MLflow run.

### 🎯 Purpose & Impact
- 🔨 **Purpose:** The changes are aimed at organizing MLflow experiments better by defaulting them into a shared directory (`/Shared`). It also simplifies the process of resuming or starting new MLflow runs by checking for an active run first.
- 📈 **Impact:** Users will experience a more consistent and possibly more intuitive MLflow integration when using Ultralytics YOLOv8. This could lead to easier experiment tracking and management, especially in shared environments.

### CODE REVIEW

**Comment by rafaelvp-db** [comment]
I have read the CLA Document and I sign the CLA

**Comment by rafaelvp-db** [comment]
@glenn-jocher would you mind taking a look?

**Comment by glenn-jocher** [comment]
@rafaelvp-db hello! Sure, I'd be happy to take a look. Can you provide me with some more information about your pull request and what you'd like me to review?

**Comment by rafaelvp-db** [comment]
@glenn-jocher the PR is related to this issue: https://github.com/ultralytics/ultralytics/issues/1751 - the issue contains a bit more details on the changes that were needed and that I implemented, as well as the code block in the initial PR description

I see that all tests have passed and also seen your comment in the issue - so will wait for the team to review/merge :)

**Comment by glenn-jocher** [comment]
@rafaelvp-db PR looks good! Thank you for your contributions.

**Comment by glenn-jocher** [comment]
@rafaelvp-db merged into updates branch for 8.0.60 release this weekend.

**Comment by rafaelvp-db** [comment]
Awesome @glenn-jocher - happy to help :)

**Pull request merged**
