### PR TITLE
Refactor all Ultralytics Solutions

### PR DESCRIPTION
**Pull request by glenn-jocher**
@RizwanMunawar this is an example refactor of the ObjectCounter class, removing the `set_args()` function and merging this functionality directly into the init() method which is more aligned with best practices. Also fixes the docstrings arguments which had become outdated.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

🌟 Summary
This PR introduces enhancements and new features to the Ultralytics AI assistant's solutions module for real-time video analytics, offering more robust and flexible functionalities across various applications.

📊 Key Changes
- Improved initialization and configuration for classes like AIGym, DistanceCalculation, and others, enabling streamlined setup with direct parameter passing.
- Enhanced object counting, heatmap generation, parking management, speed estimation, and more with flexible parameters for customization.
- Added support for new types of analytics, including pull-up and ab workout posture recognition in the AIGym module.

🎯 Purpose & Impact
- Simplifies and enriches the user's ability to deploy AI-powered video analysis for a wide range of applications, from fitness tracking to traffic management.
- Enables developers and users to customize and optimize their video analytics solutions more effectively, improving accuracy and user experience.
- Expands the capabilities of Ultralytics' solutions module, solidifying its position as a comprehensive tool for real-time video processing and analytics.

### CODE REVIEW

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes working on the similar stuff for all solutions :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar ok I've completed a full refactor but just for ObjectCounter. Can you use this PR as an example to update the rest?

I've made some really cool changes in the usage examples too. These are breaking changes unfortunately, but I think the initialization is now simpler and better aligned with best practices:

- We can import `solutions` and `YOLO` at the same time now with `from ultralytics import YOLO, solutions`
- I've brought the solutions classes up 1 level so we can now use them directly (I think) as i.e. `counter = solutions.ObjectCounter()`

Can you test this to see if it actually works correctly? If it works correctly we should 1) refactor the remaining solutions just like this one, then 2) create a new Solution baseclasss with the common arguments and methods to base all current and future solutions off of, i.e. `class ObjectCounter(Solution):`

**Comment by glenn-jocher** [comment]
The best improvement here is now that ObjectCounter can be created directly from solutions with `from ultralytics import solutions` and initialized at the same time:

```
        counter = solutions.ObjectCounter(
            view_img=True,
            reg_pts=region_points,
            classes_names=model.names,
            draw_tracks=True,
            line_thickness=2,
        )
```

**Comment by RizwanMunawar** [comment]
@glenn-jocher got it I completed almost all refactoring at level 1, i.e. The code will work for both new and old packages.
we dont need to change anything actually in docs, but at the backend, I have refactored the code in a way that the user can pass arguments in both ways


**Example 1 (Pass Arguments with function call)**
```python
# Init speed-estimation obj
speed_obj = speed_estimation.SpeedEstimator()
speed_obj.set_args(reg_pts=line_pts,
                   names=names,
                   view_img=True)
```

**Example #02 (Pass Arguments after function call)**
```python
# Init speed-estimation obj
speed_obj = speed_estimation.SpeedEstimator(reg_pts=line_pts,
                   names=names,
                   view_img=True)
```

**Comment by glenn-jocher** [comment]
@RizwanMunawar nice updates! But remember `solutions` is lowercase, not uppercase, so it needs to be `from ultralytics import YOLO, solutions`

**Comment by RizwanMunawar** [comment]
@glenn-jocher I think this PR is ready to merge, I have run the docs locally to test and the solutions pages are looking nice :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar awesome! Have you tested that the guides code actually works and doesn't throw any errors now?

**Comment by RizwanMunawar** [comment]
@glenn-jocher yes I have performed the testing locally with all the modified codes and these are working fine 👍🏻

**Comment by glenn-jocher** [comment]
@RizwanMunawar this updates the solutions classes and docs code blocks but does not update the actual guides tables yet, i.e. the arguments are out of date and there is no longer any set_args() method but it is referenced here in the title. This PR still needs work here as I've done initially for the the ObjectCounter() file.
Screenshot 2024-05-18 at 17 53 05

**Comment by glenn-jocher** [comment]
@RizwanMunawar also it seems the notebooks have been completely forgotten about and have not been changed at all (!)

https://github.com/ultralytics/ultralytics/blob/main/examples/object_counting.ipynb
https://github.com/ultralytics/ultralytics/blob/main/examples/heatmaps.ipynb
https://github.com/ultralytics/ultralytics/blob/main/examples/object_tracking.ipynb

**Comment by glenn-jocher** [comment]
@RizwanMunawar I've merged this PR to get this into main as I have other work I need to focus on today but please update all of the notebooks ASAP as they are all now showing incorrect usage examples. Thank you!

**Pull request merged**
