### PR TITLE
Decrease memory usage by 20% for a large number of classes

### LINKED ISSUE #13988: Issue with Training YOLOv8 on a Large Dataset with lack of memory and not good enough
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am encountering issues while training the YOLOv8 model on a dataset with 35,000 images and 10,000 classes. I am trying to train the model using images with a resolution of 1280x1280 but facing not enough memory error in my 8xV100 GPUs. My current parameters:

task=detect
mode=train
model=/home/e/yolov8x.pt
imgsz=1216
val=False
data=/home/e/dataset/small_21/data.yaml
epochs=60
batch=8
name=small_21
exist_ok=True
device=0,1,2,3,4,5,6,7
Are there any specific tips for setting hyperparameters, using data augmentation techniques, or other strategies to improve the model's performance on such a large and complex dataset?

Can I improve memory usage performance?

### Additional

_No response_

### PR DESCRIPTION
**Pull request by bobyard-com**
Please, be considerate about int64, and using integer for boolean masks.
We performed some experiments, the metrics are the same.

_I have read the CLA Document and I sign the CLA_

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces type consistency improvements for various tensor operations in the `ultralytics/ultralytics` project, ensuring compatibility and potentially averting issues related to data types.

### 📊 Key Changes
- Updated tensor concatenation and creation operations to explicitly define `dtype` as `np.int32` or `torch.int32` for better precision.
- Added `torch.cuda.empty_cache()` call after logging the TensorBoard graph if the device is CUDA-enabled to free up GPU memory.
- Enforced `dtype` change from `torch.int64` to `torch.int32` for certain tensor initializations and assignments.
- Ensured tensor operations within the target assignment and candidate selection process now properly cast boolean and integer types.

### 🎯 Purpose & Impact
- **Enhanced Compatibility**: By specifying integer data types (`np.int32` and `torch.int32`), the changes improve the compatibility of tensor operations, which can prevent potential type-mismatch errors.
- **Memory Management**: The addition of `torch.cuda.empty_cache()` efficiently manages GPU memory usage by clearing unoccupied cached memory, which can be particularly beneficial during extensive training sessions.
- **Consistency**: These modifications bring about more consistent handling of tensor data types across the project, reducing the likelihood of bugs and improving the robustness of the codebase.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@bobyard-com thank you for the PR. It looks like you've used 2 closing parentheses everywhere "))" instead of one ")". Can you please fix this?

Also do you have before/after training results? The changes in the precisions may affect training results and need to be tested to verify that the training accuracy has not been affected.

**Comment by bobyard-com** [comment]
Our bad, fixed.

**Comment by bobyard-com** [comment]
It is numbers of classes, which are converted to float during some computations. We just reconverted them back to integer. The only place where a narrowing happened is 
```
        ind = torch.zeros([2, self.bs, self.n_max_boxes], dtype=torch.long)  # 2, b, max_num_obj
        ind = torch.zeros([2, self.bs, self.n_max_boxes], dtype=torch.int32)  # 2, b, max_num_obj
```
We don't think anyone could potentially have max_num_obj > 2,147,483,647

**Comment by bobyard-com** [comment]
We had pretty large dataset so we did not have time to compare completely 
image
In our opinion it is the same, the minor difference is from a different random generator sequence.

**Comment by glenn-jocher** [comment]
Thank you for the update and for sharing your observations. It's great to hear that you believe the changes have not significantly impacted the metrics. 

To ensure the robustness of these modifications, it would be beneficial to run a few more tests, especially on smaller datasets where the results can be more easily compared. This will help confirm that the changes do not introduce any unintended side effects.

If you encounter any specific issues or have further questions during your testing, please feel free to share a reproducible example. This will help us provide more targeted assistance. You can find guidance on creating a minimum reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please make sure you are using the latest versions of the packages to ensure compatibility and benefit from the latest fixes and improvements.

Thank you for your contribution and for helping improve the project! 🚀

**Comment by glenn-jocher** [comment]
@bobyard-com see CI errors with error messages of `IndexError: tensors used as indices must be long, byte or bool tensors`

https://github.com/ultralytics/ultralytics/actions/runs/9678117622/job/26701181845?pr=13996

```
=========================== short test summary info ============================
FAILED tests/test_cli.py::test_train[detect-model1-coco8.yaml] - subprocess.CalledProcessError: Command '['yolo', 'train', 'detect', 'model=/home/runner/work/ultralytics/ultralytics/weights/yolov8n.pt', 'data=coco8.yaml', 'imgsz=32', 'epochs=1', 'cache=disk']' returned non-zero exit status 1.
FAILED tests/test_cli.py::test_train[obb-model2-dota8.yaml] - subprocess.CalledProcessError: Command '['yolo', 'train', 'obb', 'model=/home/runner/work/ultralytics/ultralytics/weights/yolov8n-obb.pt', 'data=dota8.yaml', 'imgsz=32', 'epochs=1', 'cache=disk']' returned non-zero exit status 1.
FAILED tests/test_cli.py::test_train[segment-model3-coco8-seg.yaml] - subprocess.CalledProcessError: Command '['yolo', 'train', 'segment', 'model=/home/runner/work/ultralytics/ultralytics/weights/yolov8n-seg.pt', 'data=coco8-seg.yaml', 'imgsz=32', 'epochs=1', 'cache=disk']' returned non-zero exit status 1.
FAILED tests/test_cli.py::test_train[pose-model4-coco8-pose.yaml] - subprocess.CalledProcessError: Command '['yolo', 'train', 'pose', 'model=/home/runner/work/ultralytics/ultralytics/weights/yolov8n-pose.pt', 'data=coco8-pose.yaml', 'imgsz=32', 'epochs=1', 'cache=disk']' returned non-zero exit status 1.
FAILED tests/test_engine.py::test_detect - IndexError: tensors used as indices must be long, byte or bool tensors
FAILED tests/test_engine.py::test_segment - IndexError: tensors used as indices must be long, byte or bool tensors
FAILED tests/test_python.py::test_train_scratch - IndexError: tensors used as indices must be long, byte or bool tensors
FAILED tests/test_python.py::test_train_pretrained - IndexError: tensors used as indices must be long, byte or bool tensors
FAILED tests/test_python.py::test_workflow - IndexError: tensors used as indices must be long, byte or bool tensors
FAILED tests/test_python.py::test_yolo_world - IndexError: tensors used as indices must be long, byte or bool tensors
FAILED tests/test_python.py::test_yolov10 - IndexError: tensors used as indices must be long, byte or bool tensors
====== 11 failed, 68 passed, 15 skipped, 12 warnings in 456.48s (0:07:36) ======
```

**Comment by bobyard-com** [comment]
Using int64 for indices is not reasonable. Should I change the tests?

**Comment by glenn-jocher** [comment]
@bobyard-com thank you for your feedback! Using `int64` for indices can indeed be excessive in many scenarios, especially when dealing with large datasets where memory efficiency is crucial. However, changing the tests might not be the optimal solution as it could mask underlying issues.

Instead, let's ensure that the code is correctly using `int32` where appropriate. If you encounter specific errors or issues, please provide a minimum reproducible example so we can better understand and address the problem. You can find guidance on creating a reproducible example [here](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please verify that you are using the latest versions of the packages to ensure compatibility and benefit from recent fixes and improvements.

If you have any specific sections of the code or errors you'd like to discuss, feel free to share them, and we'll be happy to assist further! 🚀

**Comment by vsarkhel** [comment]
This actually fixes some of the issues we have when working with satellite imagery with a large number of classes and large amounts of ground truth labels.

**Comment by glenn-jocher** [comment]
@bobyard-com the indexing precision requirement comes directly from `torch`, this is not something we have control over. The error message the tests are showing is purely originating in `torch` errors when attempting to index a Tensor with a low-precision integer, there is nothing we can do about this:

Screenshot 2024-06-29 at 17 51 54

I would focus on rescoping int32 usage where allowed and using int64 indexing where required. There is no alternative as far as I'm aware.

**Comment by glenn-jocher** [comment]
@bobyard-com merged into a new branch to experiment with, but initially this looks very problematic. If you'd like to submit a new PR that passes the basic tests that would be helpful.

**Pull request merged**
