### PR TITLE
`ultralytics 8.0.50` AMP check and YOLOv5u YAMLs

### LINKED ISSUE #1251: All results are drawed to first image when predict images list.
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

\ultralytics\yolo\v8\segment\predict.py

    def postprocess(self, preds, img, orig_img):
        # TODO: filter by classes
        p = ops.non_max_suppression(preds[0],
                                    self.args.conf,
                                    self.args.iou,
                                    agnostic=self.args.agnostic_nms,
                                    max_det=self.args.max_det,
                                    nc=len(self.model.names),
                                    classes=self.args.classes)
        results = []
        proto = preds[1][-1] if len(preds[1]) == 3 else preds[1]  # second output is len 3 if pt, but only 1 if exported
        for i, pred in enumerate(p):
            orig_img = orig_img[i] if isinstance(orig_img, list) else orig_img
            shape = orig_img.shape

====>>>> change the parameter name from orig_img to orig_imgs

    def postprocess(self, preds, img, orig_imgs):
        # TODO: filter by classes
        p = ops.non_max_suppression(preds[0],
                                    self.args.conf,
                                    self.args.iou,
                                    agnostic=self.args.agnostic_nms,
                                    max_det=self.args.max_det,
                                    nc=len(self.model.names),
                                    classes=self.args.classes)
        results = []
        proto = preds[1][-1] if len(preds[1]) == 3 else preds[1]  # second output is len 3 if pt, but only 1 if exported
        for i, pred in enumerate(p):
            orig_img = orig_imgs[i] if isinstance(orig_imgs, list) else orig_imgs
            shape = orig_img.shape

### Environment

_No response_

### Minimal Reproducible Example

from ultralytics import YOLO
import cv2

if __name__ == '__main__':
    model = YOLO("./runs/segment/train3/weights/best.pt")  # load a custom model

    img1 = cv2.imread('img1.jpg')
    img2 = cv2.imread('img2.jpg')
    img3 = cv2.imread('img3.jpg')

    # Predict with the model
    results = model([img1,img2,img3],conf = 0.5)  # predict on image list
    cv2.imwrite('img1_output.jpg', results[0].plot())
    cv2.imwrite('img2_output.jpg', results[1].plot())
    cv2.imwrite('img3_output.jpg', results[2].plot())

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #1265: classify data error
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

If  I don't specify model, it regards the data is not a classify dataset, even i queried `yolo classify train`.
I think it is confusing.

### Environment

- ultralytics==8.0.49

### Minimal Reproducible Example

does not work
```
yolo classify train data=imagenet100
```
does work
```
yolo train model=yolov8n-cls.pt data=imagenet100
yolo classify train model=yolov8n-cls.pt data=imagenet100
```

### Additional

_No response_

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
- PR brings updates to documentation, code quality improvements, and new features in YOLO models.

### 📊 Key Changes
- 📝 Corrected redundant "i.e." in documentation.
- 🌐 Added new YOLOv5 model configurations (yolov5s6u, yolov5m6u, yolov5l6u, yolov5x6u).
- ✅ Included new tests for image prediction with different model variants (segmentation, classification).
- 🚀 Launched inference on tensors directly.
- 🌈 Updated model initialization to be more informative and verbose.

### 🎯 Purpose & Impact
- 🔍 Improves code readability, consistency, and corrects minor documentation mistakes.
- 🚀 Enables the use of newer YOLOv5 models, potentially improving detection performance.
- 🧪 Expands testing to cover more model use cases, ensuring robustness.
- ➡️ Allows advanced users to input raw tensors for prediction, increasing flexibility.
- 💬 Offers better insight during model setup with enhanced verbosity, improving the debugging and development process.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q I've created a new AMP checks that run before training in PR #1263. Training will continue with `amp=False` if checks fail (using more CUDA memory).

FYI this will download a YOLOv8n pretrained model if one doesn't already exist locally, so if users get confused about why a YOLOv8n model is downloading when they ran a training command for a different model this is why. i.e. 

```bash
yolo train model=yolov8n-seg.pt
```

Screenshot 2023-03-03 at 13 21 31

**Comment by glenn-jocher** [comment]
@developer0hye ok I tried to update in https://github.com/ultralytics/ultralytics/pull/1263/commits/2d42fa6a4940a931eb23cde4ccf1e7a24925d515

**Comment by Yboktaya** [comment]
Please correct me if I am wrong, but It seems like the new amp_check functionality does not take into consideration the is_online outcome variable. 
I tried running a custom training with the YOLOv8m  within a container (offline) and I kept getting download failed (YOLOv8n)

**Comment by glenn-jocher** [comment]
@Yboktaya yes I think you're right. I haven't wanted to add any images to the pip package itself to reduce it's size, but that leaves us with no test images then. I'll try to work on a solution for offline AMP-check for 8.0.51. It's probably going to require packaging at least one image in the assets directory.

**Comment by glenn-jocher** [comment]
@Yboktaya BTW we can't use an empty tensor because we actually need to be able to detect objects in the image with and without AMP.

**Pull request merged**
