### PR TITLE
Update Python Dependency in README.md

### PR DESCRIPTION
**Pull request by harshdhamecha**
Updated Python dependency from Python >= 3.8 to Python>=3.9:
-  Type hinting with list[str] is only available in Python 3.9 and above. In earlier versions, the list type cannot be directly subscripted (e.g., list[str])

[#16906](https://github.com/ultralytics/ultralytics/issues/16906)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated Python version requirement in the README for Ultralytics package installation.

### 📊 Key Changes
- Changed the minimum required Python version from 3.8 to 3.9 in the installation instructions.

### 🎯 Purpose & Impact
- **Clarity**: Ensures users have the correct Python version for compatibility. ⏩
- **Up-to-Date**: Aligns with modern dependencies and security practices. 🔒
- **User Guidance**: Helps prevent installation errors related to Python version discrepancies. 🚫🐍

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated the README to require Python 3.9 or higher for the Ultralytics package installation.

### 📊 Key Changes
- The Python version requirement has been increased from 3.8 to 3.9 in the installation instructions of the README.

### 🎯 Purpose & Impact
- **Purpose:** This change ensures better compatibility and takes advantage of the latest features in Python, leading to improved performance and security.
- **Impact:** Users must have at least Python 3.9 installed to use the latest version of the Ultralytics package, encouraging them to update their Python environment to leverage new features and enhancements. 🐍🚀

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @harshdhamecha, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to help guide you through the process. An Ultralytics engineer will review your PR soon. In the meantime, here's a checklist to ensure a smooth integration:

- ✅ **Define a Purpose**: Please confirm that the purpose of your PR is clearly defined. You've updated the Python version requirement in the README, aligning it with type hint capabilities of Python 3.9 and above. Make sure to link any [relevant issues](https://github.com/ultralytics/ultralytics/issues) if applicable.
- ✅ **Synchronize with Source**: Ensure your PR is up-to-date with the `main` branch. If there's a discrepancy, update it by selecting 'Update branch' or using `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: All Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks should pass. Address any failures identified in the process.
- ✅ **Update Documentation**: Verify that any new or modified features have associated [documentation](https://docs.ultralytics.com).
- ✅ **Add Tests**: Include or update necessary tests for your changes, ensuring all tests are passing.
- ✅ **Sign the CLA**: Confirm you have signed the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/). If you haven't, state "I have read the CLA Document and I sign the CLA" in a new comment.
- ✅ **Minimize Changes**: Ensure your PR changes are minimal and necessary. Consider this quote _"It is not daily increase but daily decrease, hack away the unessential."_ — Bruce Lee

For further details, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have questions or require assistance, feel free to comment here. Thanks for contributing to Ultralytics! 🌟🐍

**Review by ambitious-octopus — CHANGES_REQUESTED** [review]
Hey, @harshdhamecha thanks for the PR. We have no known issues with python 3.8. Also, editing the readme is not enough, you should also edit the pyproject.toml file. The point here is that we have no evidence that ultralytics is incompatible with python 3.8. Have you done any further testing?

**Comment by Laughing-q** [comment]
@harshdhamecha Thanks for the PR! However I think current ultralytics package is compatible with python3.8 since we are having CI tests running on python3.8 and it all passes.
wNcZAp2nsb

**Comment by glenn-jocher** [comment]
@harshdhamecha thank you for the PR. We are fully 3.8 compatible and test for this daily as @Laughing-q mentioned.

**Pull request closed without merging**
