### PR TITLE
Allow setting val_period

### PR DESCRIPTION
**Pull request by AyushExel**
Usage:
```
yolo detect train val_period=10
```

### Summary
:sparkles::wrench::memo:

This pull request adds a new feature that allows the user to specify the validation frequency with the `val_period` argument and config option. It also modifies the callbacks to respect the `done_val` attribute of the trainer and only log or upload the validation metrics when the validation step is performed.

> _Sing, O Muse, of the valiant code warriors who strove_
> _To enhance the training process with a flexible `val_period`_
> _And how they modified the callbacks with skill and care_
> _To check the `done_val` attribute and log the metrics fair_

### Walkthrough
*  Add `val_period` option to control validation frequency ([link](https://github.com/ultralytics/ultralytics/pull/1609/files?diff=unified&w=0#diff-9d692d4ad15d420a92105fcd432fb1d2221b71d5af055bea3bd2b70523ce6743R15))
*  Implement `val_period` feature in `BaseTrainer` class ([link](https://github.com/ultralytics/ultralytics/pull/1609/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1R137), [link](https://github.com/ultralytics/ultralytics/pull/1609/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1R302), [link](https://github.com/ultralytics/ultralytics/pull/1609/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L359-R371))
*  Adjust logging and uploading conditions for validation metrics in callbacks ([link](https://github.com/ultralytics/ultralytics/pull/1609/files?diff=unified&w=0#diff-88156d2cb2225824b539d2eeeece9b6157773bd05beabc136066535690b0d046L35-R36), [link](https://github.com/ultralytics/ultralytics/pull/1609/files?diff=unified&w=0#diff-525fb733ac418d064f18eecf36263fdd635b2e0db15efe3c8f38397ba31cec9cL23-R25), [link](https://github.com/ultralytics/ultralytics/pull/1609/files?diff=unified&w=0#diff-7a5a4b862d4fe6ad4d3fab269c6cf4d16c8efac6d577f55bee25a0461b7fed32L36-R37))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved validation control in the training process by adding configurable validation intervals.

### 📊 Key Changes
- Added `val_period` parameter to `default.yaml` for setting validation intervals.
- Introduced `done_val` flag in the trainer to track if validation has been performed.
- Adjusted training loop to validate based on `val_period` setting.
- Modified callback functions (`comet.py`, `hub.py`, `tensorboard.py`) to log metrics conditionally based on the `done_val` flag.

### 🎯 Purpose & Impact
- **Enhanced Flexibility**: Users can now control the frequency of validation checks during training, which can help in managing computational resources more effectively.
- **Optimized Performance Logging**: Ensures that performance metrics are logged only after validation, leading to more accurate tracking of model performance.
- **Improved Resource Management**: Reducing unnecessary validation checks can save time and computational power, benefiting large-scale training sessions.

🚀 This change makes the training process more customizable and efficient for different user needs and scenarios.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel hey I took a look! I think what we want is a bit different. We'll still have train losses we can log every epoch that don't take any val time, so I think we want to continue to log every epoch like normal (to CSV, Comet, etc.), we just want val losses and metrics to be nan when not in a val_period epoch, i.e.:

```python
# normal epoch:
metrics = {train_losses: 0.123, val_losses: 0.123, val_metrics: 0.123}

# no-val epoch
metrics = {train_losses: 0.123, val_losses: nan, val_metrics: nan}
```

Most plotting tools will just skip the data if it's nan, so this should work perfectly with the loggers like Comet, TensorBoard etc.

Does this make sense?

**Comment by AyushExel** [comment]
@glenn-jocher csv logging will still work. It'll basically leave out the val metrics and log losses. I thought leaving them empty is better than Nans as users might think their metrics became Nans.
Screenshot 2023-03-25 at 10 54 56 PM

This is how csv at val_period=2 will look like.

And for loggers, I think losses are logged in `train_epoch_end` which'll behave like it used to. Val losses that are logged in `fit_epoch_end` will only be logged in val_period.
like this clearml log https://app.clear.ml/projects/6bfab9703aef46a4af1acf11e03647dc/experiments/4aa11809a9044ae6876db49f8867771c/output/metrics/scalar

Does that make sense?

**Comment by glenn-jocher** [comment]
@AyushExel yeah... I think while it looks like to the eye these models will be much harder to parse with existing files like pandas or numpy load_csv() etc., but I might be wrong. 

Also I think the changes to main are minimized if we just initialize metrics with nan and replace if val is run no?

**Comment by AyushExel** [comment]
Yeah. One thing I'm not sure about is how all the loggers handle Nans. If there's a standard convention to ignore Nans then we're fine but otherwise the curves might look weird. I think we'll need to confirm

**Comment by glenn-jocher** [comment]
W&B ignores them, so the others probably do also. Matplotlib likewise ignores them for plotting results.csv. BTW I just realized I don't think results.png will plot correctly unless results.csv is populated with nan's as I'm assuming every row must have the same number of columns. Have you tested this PR with val_period > 1 and checked results.png?

**Comment by rusmux** [comment]
@glenn-jocher Hi, this is a great feature and I'm really looking forward to it, as it would help reduce the training time in some cases. Are there any ideas when this will be merged with the main branch?

**Comment by glenn-jocher** [comment]
@rusmux hello,

Thank you for your interest in the new feature! I'm glad to hear that you find it useful. As for the merge with the main branch, I can't provide an exact timeline at the moment. The merge process involves careful consideration and testing to ensure the feature works seamlessly with the rest of the codebase and meets our quality standards. Rest assured, our team is working diligently to finalize the feature and merge it into the main branch as soon as possible. Keep an eye on the repository for any updates. 

If you have any further questions or need assistance with anything else, please feel free to ask.

Best regards,
Glenn Jocher

**Pull request closed without merging**
