### PR TITLE
Test ncnn onnx export

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR updates the continuous integration (CI) workflow and adds tests for model export functionality in the Ultralytics repository. 

### 📊 Key Changes
- **CI Workflow Update**: Adjusted conditions for running benchmarks -- they now trigger on scheduled events instead of on any non-dispatched workflow.
- **Platform and Version Support**: The CI now runs tests primarily on `windows-latest` and Python 3.11, removing older versions and other operating systems from regular checks.
- **Model Export Tests**: Added new test files `test_ncnn.py` and `test_onnx.py` to verify exporting models to NCNN and ONNX formats.
- **PNNX Release Update**: Updated default PNNX release version used in NCNN export from "20240410" to "20240819".

### 🎯 Purpose & Impact
- **Streamlined CI Process**: By focusing on `windows-latest` and Python 3.11, the CI process is streamlined to ensure efficient testing with up-to-date configurations.
- **Enhanced Testing**: The new model export tests ensure that models can reliably be exported to multiple formats, increasing the robustness of deployment options for developers.
- **Improved Reliability**: Updating the PNNX release ensures compatibility with the latest tools, mitigating potential issues with deprecated versions.

### CODE REVIEW

**Comment by inisis** [comment]
It only happens on Windows

**Comment by Laughing-q** [comment]
@inisis yes I figured the same

**Comment by Laughing-q** [comment]
@glenn-jocher do you know why the CI tests get stuck? I don't see any tests in progress but all the tests here are queued.
WE8HDUEVvR
pic-241030-1433-30

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Laughing-q, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to guide you through the contribution process. An Ultralytics engineer will also review your pull request soon. Meanwhile, please review the following checklist to ensure your contribution can be smoothly integrated:

- ✅ **Define a Purpose**: Please ensure your pull request clearly explains the purpose and benefits of your changes. You've noted the enhancements to the CI for NCNN export and testing 🎉. If there's a related issue, linking it in your description would be beneficial.
- ✅ **Synchronize with Source**: Make sure your branch is up-to-date with `ultralytics/ultralytics` `main`. If it's not, update it by using the 'Update branch' button or executing `git pull` followed by `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass. If any checks fail, please resolve these issues to proceed.
- ✅ **Update Documentation**: Update or mention updates needed for [documentation](https://docs.ultralytics.com) regarding the new NCNN format tests if necessary.
- ✅ **Add Tests**: Thank you for including the `test_ncnn.py` file! Ensure all new tests pass 🧪.
- ✅ **Sign the CLA**: If this is your first contribution, please confirm that you have signed the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by stating "I have read the CLA Document and I sign the CLA" in a comment.
- ✅ **Minimize Changes**: Limit changes to what's necessary for this CI enhancement. Abide by the _"hack away the unessential"_ principle mentioned by Bruce Lee.

For more detailed guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you encounter any challenges or have questions, feel free to ask. Thank you for enhancing our CI capabilities with this NCNN testing feature! 🚀🔍

**Pull request closed without merging**
