### PR TITLE
Add YOLOv5 tutorials to docs.ultralytics.com

### PR DESCRIPTION
**Pull request by glenn-jocher**
@AyushExel please help me start migrating all tutorials in YOLOv5 over to our Docs here. 

I've gotten this started with a YOLOv5 index page and our Train Custom Data tutorial. The implementation is not trivial, please do a diff between train_custom_data.md here and the original markdown in the YOLOv5 tutorial to see what changes are needed, and then apply the same sort of changes to the rest of the YOLOv5 tutorials. 

Screenshot 2023-03-27 at 20 19 11

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvements to Ultralytics YOLOv5 documentation and GitHub workflows for enhanced user experience.

### 📊 Key Changes
- GitHub workflow adjustments for broken link checks and YAML checks.
- Updated favicon for the documentation.
- Refined and streamlined YOLOv5 documentation structure.
- Inclusion of emojis for an engaging presentation.
- Expanded coverage of YOLOv5 features such as custom data training, model ensembling, pruning, hyperparameter evolution, transfer learning, test-time augmentation (TTA), and various export formats.
- Integration guides for Comet Logging and Neural Magic's DeepSparse for improved model monitoring and deployment.
- Enhanced Markdown extensions for better content formatting and code annotation in the documentation.
- Code formatting fixes and enhancements.

### 🎯 Purpose & Impact
- The updated workflows will ensure the robustness and reliability of repository checks.
- An updated favicon provides a refreshed brand image.
- The comprehensive and organized documentation ensures users have clear guidance for leveraging YOLOv5 capabilities, leading to more effective model training and deployment.
- The integration guides assist users in implementing advanced monitoring and deployment strategies, further increasing the potential and reach of YOLOv5 models in various applications.

### CODE REVIEW

**Comment by AyushExel** [comment]
Okay got it. Please don't merge this tonight. I'll take a detailed look in 2 hours.

**Comment by AyushExel** [comment]
@glenn-jocher okay understood the structure. Ping me whenever you're done with the changes. I'm not making any changes for now

**Comment by glenn-jocher** [comment]
@AyushExel ok I think I'm all done adding for now haha. I've got the first half of the YOLOv5 tutorials all added. Can you add the remaining bottom half that is still missing? It's not too hard, mostly copy pasting into new *.md files and then adding the file to mkdocs.yaml.

Then we'll have to do some cleanup for links etc.

Screenshot 2023-03-27 at 22 03 11

**Comment by AyushExel** [comment]
Okay Added the files. Now fixing links

**Comment by glenn-jocher** [comment]
@AyushExel yes I fixed a few :)

We need to update yolov5/index.md to point to the relative markdown files we have now rather than the older YOLOv5 wiki links, can you do that?

**Comment by glenn-jocher** [comment]
This is going to be great! Once we have this up we can start to update the links on YOLOv5.

**Comment by AyushExel** [comment]
@glenn-jocher ok links look good now

**Comment by glenn-jocher** [comment]
copilot:all

**Pull request merged**
