### PR TITLE
`ultralytics 8.2.73` Meta SAM2 Refactor 

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

### 🌟 Summary
This PR enhances the `ultralytics` documentation and model architecture by integrating new SAM 2 (Segment Anything Model 2) features and removing the outdated SAM 2 model.

### 📊 Key Changes
- **Documentation Updates**: Enhanced model documentation to include SAM 2 specifics.
- **New Files Added**:
  - `docs/en/reference/models/sam/modules/blocks.md`
  - `docs/en/reference/models/sam/modules/memory_attention.md`
  - `docs/en/reference/models/sam/modules/utils.md`
- **Model Integrations**:
  - Introduced SAM 2 architecture in `ultralytics/models/sam/`.
  - Updated `sam/models/` to integrate SAM 2 components like memory attention and encoders.
- **Removed Redundancies**: Deleted obsolete SAM 2 model documentation and code.

### 🎯 Purpose & Impact
- **Enhanced Capabilities**: SAM 2 models offer advanced, memory-based segmentation.
  - Better performance in segmentation tasks.
  - Improved user guidance for building and using SAM 2 models.
- **User Experience**: Simplified access to new models and detailed model-building instructions.
- **Maintenance**: Removing outdated references reduces code complexity.

Adding emojis and sections in your summary helps in improving readability and engagement for a diverse audience.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher This PR merged all the modules/files from `sam2/` into `sam/` folder and eliminated the former. Currently there's no `SAM2` class and `build_sam2` function, we can directly use `SAM` and `build_sam` to do inference or create model on both `SAM` and `SAM2` models.

When I migrated SAM2 implementations, for less duplication introduced I had to **import some modules from `sam/`**(some of them as super class and some of them are directly used in SAM 2 architecture. 
However for better user experience and better consistency we want to use `SAM` class directly load `sam2` models hence we need to **import `SAM2` class in `sam/` folder which is a circle import**, which was why I imported `build_sam2` and `SAM2Predictor` inside the function.
So I figured we better to integrate SAM2 implementation into `sam/`. What do you think?

**Comment by glenn-jocher** [comment]
@Laughing-q yes circular imports can be tricky. This is a huge change, would probably have been better to do this before we launched so we didn't publish the docs pages, but yes let me review and if it all looks good we can get this merged into 8.2.72 tomorrow.

Maybe I can update all the docstrings in the /sam folder too at the same time.

**Comment by glenn-jocher** [comment]
@Laughing-q merged https://github.com/ultralytics/ultralytics/pull/14928 and refactored those changes manually into this PR in https://github.com/ultralytics/ultralytics/pull/14867/commits/4a4dc97147a7bf46c2dbf37b0bfcd141d9eb5f68

**Comment by Laughing-q** [comment]
@glenn-jocher Thanks!

**Pull request merged**
