### PR TITLE
Update image link for Comet site

### PR DESCRIPTION
**Pull request by nerdyespresso**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
N/A - No content to summarize as PR contains no changes.

### 📊 Key Changes
- None, as the diff is empty.

### 🎯 Purpose & Impact
- No impact or purpose can be identified without any code changes.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@nerdyespresso thanks for the PR! Please write the below line in a new message to make the CLA bot happy. Thanks!

I have read the CLA Document and I sign the CLA

**Comment by nerdyespresso** [comment]
No problem! 😁

I have read the CLA Document and I sign the CLA.

**Comment by glenn-jocher** [comment]
recheck

**Comment by glenn-jocher** [comment]
@nerdyespresso PR merged!

**Pull request merged**
