### PR TITLE
Create comet-ml.md

### PR DESCRIPTION
**Pull request by abirami-vina**
### Summary
:sparkles::memo::camera_flash:

This pull request adds documentation for the Comet ML integration with Ultralytics YOLOv8. The new file `docs/integrations/comet-ml.md` explains how to use Comet ML to track and visualize the training and evaluation of YOLOv8 models. It also provides code examples and links to resources for further information.

> _`Comet ML` and `YOLOv8`_
> _Integrate for vision tasks_
> _A new doc explains_

### Walkthrough
* Add a new documentation file for Comet ML integration (`docs/integrations/comet-ml.md`)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing Comet ML integration with Ultralytics YOLOv8 for enhanced model training and logging.

### 📊 Key Changes
- 📝 Added a detailed guide for integrating Comet ML with YOLOv8 training, covering installation to usage and customization.
- 🛠️ Instructions on configuring Comet ML to work smoothly with YOLOv8 models.
- 🔍 Real-time monitoring and post-training analysis features, including system metrics and interactive confusion matrices.
- 🎨 Customizable logging options, which allow users to tailor the amount and interval of logging outputs to their needs.
- 🌐 Offline experiment management capabilities for situations with limited internet access.

### 🎯 Purpose & Impact
- 🚀 Simplifies the experiment management process, enabling developers to focus on model optimization.
- 📈 Offers real-time insights into model performance, allowing for quick and informed adjustments during training.
- ✨ Enhanced flexibility with logging, providing users with the ability to customize what data gets logged and how often.
- 🌍 Expands usability under limited connectivity by introducing offline logging, promoting accessibility in diverse environments.
- 🌟 Opens pathways for robust model analysis and performance improvements, making the model development cycle more efficient and data-driven.

### CODE REVIEW

**Comment by abirami-vina** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@abirami-vina wow this is great, thanks!!

**Comment by glenn-jocher** [comment]
@abirami-vina can you move this into the new /en/ directory please? Thanks!

**Comment by abirami-vina** [comment]
@glenn-jocher Thanks, I've moved it into the /en directory.

**Comment by glenn-jocher** [comment]
@abirami-vina awesome thank you! PR merged!

**Pull request merged**
