### PR TITLE
FEAT: MLFlow Integration

### PR DESCRIPTION
**Pull request by dankernel**
I have added the MLFlow Integration feature.
By utilizing the implemented callback functionality, I log and store artifacts with mlflow.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of MLflow for enhanced experiment tracking in Ultralytics YOLO.

### 📊 Key Changes
- **MLflow Support Added:** New callbacks related to MLflow have been integrated.
- **Experiment Tracking Enhancement:** Logging parameters, metrics, and model artifacts to MLflow.
- **New File Addition:** A `mlflow.py` file under the `callbacks` module which includes callback functions for different stages of the training process.

### 🎯 Purpose & Impact
- **Better Experiment Management:** Helps users track experiments more comprehensively by using MLflow's tracking features.
- **Model Versioning:** Facilitates easier model versioning and artifact storage using MLflow's model registry.
- **Impact on Users:** Users can now log, track, and compare model training sessions seamlessly within the MLflow ecosystem, boosting productivity and reproducibility. 🚀

### CODE REVIEW

**Comment by dankernel** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
As an AI language model, I am not able to verify your signature or your agreement to the CLA. However, please ensure that you have thoroughly read the CLA document and understand the expectations and obligations outlined in it before signing. If you have any questions or concerns, it is advisable to seek legal counsel or consult with the Ultralytics team before signing the CLA.

**Comment by dankernel** [comment]
@glenn-jocher
  
I have read the CLA and left a comment indicating my agreement.

The changes included in this PR are as follows:

The purpose of this PR is to integrate mlflow.
I have added mlflow functionality using the already implemented callbacks (ultralytics/yolo/utils/callbacks).
Metrics and artifacts are logged and stored.
Handling has been done for cases when mlflow is not used (when mlflow is not installed or MLFLOW_TRACKING_URI is not defined).

**Comment by glenn-jocher** [comment]
Hi there! Thank you for your contribution and for your comment indicating your agreement with the CLA. Integrating mlflow sounds like a great addition to YOLOv8. I'm glad to hear that you've added mlflow functionality using the already implemented callbacks. It's also great to hear that you've implemented handling for cases when mlflow is not used. 

Have you tested your implementation thoroughly? Do you have any questions or concerns about your implementation that I can help with?

**Comment by dankernel** [comment]
@glenn-jocher Thank you! 

I have already completed all the tests I can do. I have also handled a few exception cases as described above. A minor concern is that there may be different levels of metric logging and artifact storage for each user (what information to store, which artifacts to add/remove, as users have different requirements). However, since the implemented callbacks were used, this will most likely run according to the original code's intention. 

I hope my code contribution gets approved, and many people will use YOLOv8 with MLFlow.

**Comment by glenn-jocher** [comment]
That sounds great! It's good that you've already gone through all the tests and exception handling. As for the different levels of metric logging and artifact storage, you can always suggest this as a feature request in the YOLOv8 repository. That way, the development team can consider it for inclusion in future updates. 

In the meantime, congratulations on finishing your contribution! I hope it gets approved too, and that more people will benefit from it. Don't hesitate to reach out if you have any questions or concerns in the future.

**Comment by vissed-kad** [comment]
Hello Dankernel. This is a great feature and will be used a lot by our team. Thanks for implementing it!

I see that the experiment name is hardcoded. Could this become a variable?

**Comment by lorenzomammana** [comment]
Hi @dankernel 

I've also written an mlflow integrator, in my case it's inspired from lighting mlflowlogger, give it a look I think you can have some benefits in your code, it will allow to also log the generated images during and after train and val. 
What I'm missing is the ability to log models, maybe we can take the best from both words 😄.

```
import os
import re
from time import time
from typing import Any, Dict, List, Optional, cast

from aigo_research.utils.utils import get_logger
from mlflow.entities import Metric, Param
from mlflow.tracking import MlflowClient
from mlflow.tracking.context.registry import resolve_tags
from ultralytics.yolo.engine.trainer import BaseTrainer
from ultralytics.yolo.engine.validator import BaseValidator
from ultralytics.yolo.utils import LOGGER

log = get_logger(__name__)
MLFLOW_RUN_NAME = "mlflow.runName"


class MlflowLogger:
    """Helper class to log metrics and artifacts to mlflow"""

    mlflow_client: Optional[MlflowClient] = None
    run_id: str

    @classmethod
    def initialize_logger(cls, tracking_uri: str):
        """Initialize the mlflow client"""
        cls.mlflow_client = MlflowClient(tracking_uri=tracking_uri)

    @classmethod
    def log_metrics(cls, metrics: Dict[str, float], step: int = 0):
        """Log metrics to mlflow"""
        if cls.mlflow_client is None:
            raise ValueError("Mlflow client not initialized")

        metrics_list: List[Metric] = []
        timestamp_ms = int(time() * 1000)
        for k, v in metrics.items():
            # Mlflow doesn't allow some characters in the metric key
            new_k = re.sub("[^a-zA-Z0-9_/. -]+", " ", k)
            metrics_list.append(Metric(key=new_k, value=v, timestamp=timestamp_ms, step=step))
        cls.mlflow_client.log_batch(run_id=cls.run_id, metrics=metrics_list)

    @classmethod
    def log_hyperparameters(cls, params: Dict[str, Any]):
        """Log hyperparameters to mlflow"""
        if cls.mlflow_client is None:
            raise ValueError("Mlflow client not initialized")

        params_list = [Param(key=k, value=str(v)) for k, v in params.items()]
        # Log in chunks of 100 parameters (the maximum allowed by MLflow).
        for idx in range(0, len(params_list), 100):
            cls.mlflow_client.log_batch(run_id=cls.run_id, params=params_list[idx : idx + 100])

    @classmethod
    def log_artifact(cls, local_path: str, artifact_path: str):
        """Log an artifact to mlflow"""
        if cls.mlflow_client is None:
            raise ValueError("Mlflow client not initialized")

        cls.mlflow_client.log_artifact(run_id=cls.run_id, local_path=local_path, artifact_path=artifact_path)


def on_pretrain_routine_start(trainer: BaseTrainer):
    """Initialize mlflow client and create a run"""
    mlflow_tracking_uri = os.getenv("MLFLOW_TRACKING_URI")
    if mlflow_tracking_uri is not None:
        MlflowLogger.initialize_logger(tracking_uri=mlflow_tracking_uri)
    else:
        log.warning("MLFLOW_TRACKING_URI not set, skipping logging to mlflow")
        return

    assert MlflowLogger.mlflow_client is not None

    try:
        experiment_name = cast(str, trainer.args.project) or "YOLOv8"
        experiment = MlflowLogger.mlflow_client.get_experiment_by_name(name=experiment_name)
        if experiment is not None:
            experiment_id = experiment.experiment_id
        else:
            log.warning("Experiment with name %s not found. Creating it.", experiment_name)
            experiment_id = MlflowLogger.mlflow_client.create_experiment(name=experiment_name, artifact_location=None)

        data_basename = os.path.splitext(os.path.basename(trainer.args.data))[0]
        run_name = f"{trainer.args.model}_{data_basename}"
        tags = {MLFLOW_RUN_NAME: run_name}
        run = MlflowLogger.mlflow_client.create_run(experiment_id=experiment_id, tags=resolve_tags(tags))
        MlflowLogger.run_id = run.info.run_id
    except Exception as e:
        LOGGER.warning("WARNING ⚠️ Mlflow not initialized correctly, not logging this run. %s", e)


def on_train_start(trainer: BaseTrainer):
    """Log hyperparameters to mlflow"""
    if MlflowLogger.mlflow_client is not None:
        MlflowLogger.log_hyperparameters(trainer.args.__dict__)


def on_train_epoch_end(trainer: BaseTrainer):
    """Log metrics and artifacts to mlflow after each training epoch"""
    if MlflowLogger.mlflow_client is not None:
        MlflowLogger.log_metrics(
            metrics=trainer.label_loss_items(trainer.tloss, prefix="train"), step=trainer.epoch + 1
        )
        MlflowLogger.log_metrics(metrics={"epoch": trainer.epoch + 1, **trainer.lr}, step=trainer.epoch + 1)
        if trainer.epoch == 1 and trainer.args.task == "detect":
            for f in trainer.save_dir.glob("train_batch*.jpg"):
                MlflowLogger.log_artifact(local_path=str(f), artifact_path="train")
            MlflowLogger.log_artifact(local_path=str(trainer.save_dir / "labels.jpg"), artifact_path="train")
            MlflowLogger.log_artifact(
                local_path=str(trainer.save_dir / "labels_correlogram.jpg"), artifact_path="train"
            )
            MlflowLogger.log_artifact(local_path=str(trainer.save_dir / "args.yaml"), artifact_path="train")


def on_fit_epoch_end(trainer: BaseTrainer):
    """Log metrics and artifacts to mlflow after each validation epoch"""
    if MlflowLogger.mlflow_client is not None:
        MlflowLogger.log_metrics(metrics=trainer.metrics, step=trainer.epoch + 1)


def on_train_end(trainer: BaseTrainer):  # pylint: disable=unused-argument
    """Finalize the mlflow run"""
    if MlflowLogger.mlflow_client is not None:
        MlflowLogger.mlflow_client.set_terminated(MlflowLogger.run_id, status="FINISHED")


def on_val_end(validator: BaseValidator):
    """Log metrics and artifacts to mlflow after each validation/test call"""
    if MlflowLogger.mlflow_client is not None:
        metrics = validator.metrics.results_dict
        metrics = {f"{validator.args.split}/{k.replace('metrics/', '')}": v for k, v in metrics.items()}
        MlflowLogger.log_metrics(metrics=metrics, step=0)

        for f in validator.save_dir.glob("*"):
            if f.is_dir() or f.suffix not in [".jpg", ".png"] or "train" in f.name or f.name.startswith("labels"):
                continue

            MlflowLogger.log_artifact(local_path=str(f), artifact_path=validator.args.split)


def callbacks():
    """Return a dict of callbacks to be used by the trainer"""
    return {
        "on_pretrain_routine_start": on_pretrain_routine_start,
        "on_train_start": on_train_start,
        "on_train_epoch_end": on_train_epoch_end,
        "on_fit_epoch_end": on_fit_epoch_end,
        "on_train_end": on_train_end,
        "on_val_end": on_val_end,
    }

```

**Comment by glenn-jocher** [comment]
Hi there! That's great to hear that you have written an MLflow integrator for YOLOv8 training. MLflow is a great tool for tracking machine learning experiments and I'm sure others would find your code useful. As for logging the models, the easiest way to do this would be to save checkpoints during training and log those checkpoints as artifacts using the `MlflowLogger.log_artifact` function. These checkpoints can then be loaded and used for inference or further training.

**Comment by dankernel** [comment]
@lorenzomammana

Thank you. 
Your code has given me a lot of inspiration. Using your code, I will soon make better commits.

**Comment by glenn-jocher** [comment]
Hi @user, it's great to hear that you're finding our code useful! Feel free to ask any questions you may have or raise any issues you encounter, and we'll do our best to assist you. Additionally, if you're looking for more information on how to use YOLOv8, you can find detailed documentation at https://docs.ultralytics.com.

**Comment by dankernel** [comment]
@glenn-jocher Thank you!!

I hope the feature I developed will be used valuably. I will continue to update this part.

**Pull request merged**
