### PR TITLE
Quality of life changes for Benchmarking script

### PR DESCRIPTION
**Pull request by MarkhamLee**
Summary 

Added a couple of QOL changes to the benchmarking script, these are changes I made to benchmarks.py make the data easier to work with that I think the community will find useful. 

Changes:
* Added "*_ncnn_model/" to the gitignore to exclude those network weights from being added to the repo
* Added FPS calculation to the benchmark report; also added date and time (utc) to the report as well, so that when you're reviewing the logs you can see when a particular benchmark was run 
Screenshot from 2024-05-03 04-10-58
* Saved the pandas data frame as a csv, with the timestamp appended to it, in order to make the test results more portable 
* Added a simple file: test.py for running the tests, so you don't have to enter in the commands via the command line to run the benchmarks. 

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Performance benchmarks now include FPS (frames per second), and new file types added to .gitignore. 🏃💨🔧

### 📊 Key Changes
- Added `*_ncnn_model/` and `calibration_*.npy` to `.gitignore` to prevent specific model files and calibration images from being tracked.
- Updated benchmarking utility to calculate and include FPS (frames per second) alongside existing metrics.

### 🎯 Purpose & Impact
- 🚫📁 Ignoring additional files (`*_ncnn_model/` and `calibration_*.npy`) in `.gitignore` keeps the repository clean and prevents unnecessary files from being committed, easing collaboration and development workflows.
- 📈 Including FPS in benchmark results offers a more comprehensive understanding of model performance, facilitating better optimization and utilization choices for developers and users alike, potentially leading to smoother and more efficient AI solutions.

### CODE REVIEW

**Comment by MarkhamLee** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@MarkhamLee we can't support additional files and directories at the top level, these are more suitable for personal forks as they may not be as useful to other users as they are to yourself. 

After scanning the PR though I think what we can incorporate are your two changes to the gitignore for NCNN and calibration file ignoring. Can you strip the rest out?

**Comment by MarkhamLee** [comment]
@glenn-jocher no new files, makes sense, I'll go ahead and remove those. What are your thoughts on adding the FPS calculation and the more detailed time stamps to the results of the benchmarks.py script, since neither requires a new file?

**Comment by glenn-jocher** [comment]
@MarkhamLee FPS addition seems like a nice addition, but timestamp again is likely too user-specific, please remove. Thank you!

**Comment by MarkhamLee** [comment]
> @MarkhamLee FPS addition seems like a nice addition, but timestamp again is likely too user-specific, please remove. Thank you!

Changes made, tested and submitted. Let me know if there is anything else.

**Comment by glenn-jocher** [comment]
@MarkhamLee Thanks for the update and for making those changes! The FPS enhancement is a great addition. 🚀 I'll review the updated submission shortly. If anything else pops up, I'll let you know. Keep up the great work! 👍

**Comment by glenn-jocher** [comment]
@MarkhamLee PR merged. Thank you for your contributions!!

**Pull request merged**
