### PR TITLE
Increase DDP timeout to 3600s

### LINKED ISSUE #2642: duplicate logging folder spawn when DDP mode
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

duplicate folder spawn when train with DDP mode.
wandb projects are spawned duplicate too.
8.0.98 is okay, but 8.0.103 makes error.(8.0.101 makes error too)

### Environment

Using NGC 23.01 docker container

Hardware: NVDIA A100 Station(80G 4GPU)
Pytorch : 1.14.0a0+410ce96
Cuda : 12.01

### Minimal Reproducible Example

```
from ultralytics import YOLO

model = YOLO('yolov8x6.pt')  

model.train(
    data='config.yaml', 
    epochs=20, 
    patience=50,
    batch=64, 
    imgsz=1280,
    save=True,
    save_period=-1,
    cache=False, 
    device = '0,1,2,3',
    workers=16,
    project='my-project', 
    name='project100',
    exist_ok=False,
    pretrained=True, 
    optimizer='SGD',
    verbose=False,
    seed=0,
    deterministic=True,
    single_cls=False,
    rect=False,
    cos_lr=False,
    close_mosaic=0,
    resume=False,
    amp=True,
    lr0=0.01,
    lrf=0.01,
    momentum=0.937,
    weight_decay=0.0005,
    warmup_epochs=2,
    warmup_momentum=0.8,
    warmup_bias_lr=0.1,
    box=7.5,
    cls=0.5,
    dfl=1.5,
    pose=12.0,
    kobj=2.0,
    label_smoothing=0.0,
    nbs=64,
    overlap_mask=True,
    mask_ratio=4,
    dropout=0.0,
    val=True
)

```

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
Resolves https://github.com/ultralytics/ultralytics/issues/2642

@developer0hye 

### Summary
🕒🚫🚀

This pull request enhances the distributed training performance and memory efficiency of the `ultralytics/yolo` engine by adjusting the timeout and pre-caching settings in `trainer.py`.

> _Sing, O Muse, of the valiant YOLO engine, that swiftly trains_
> _the keen-eyed models to detect the objects in the images._
> _It faced a mighty challenge, when the training was distributed_
> _across the nodes, and had to synchronize the processes._

### Walkthrough
* Increase the timeout duration for distributed process group initialization to prevent NCCL timeout error ([link](https://github.com/ultralytics/ultralytics/pull/2657/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L12-R12), [link](https://github.com/ultralytics/ultralytics/pull/2657/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L200-R201)) in `trainer.py`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved robustness of distributed training setup in Ultralytics YOLO.

### 📊 Key Changes
- Removed pre-caching of the dataset before running DDP (Distributed Data Parallel) command to streamline the process.
- Set an environment variable `NCCL_BLOCKING_WAIT` to enforce a timeout in distributed training.
- Added a timeout parameter to `dist.init_process_group` to handle potential deadlocks in distributed training.

### 🎯 Purpose & Impact
- 🚀 Enhancing the training process by removing unnecessary steps, aiming to reduce startup time.
- 🛡️ Increasing the reliability of distributed training with better error handling for potential hang-ups or delays.
- 🤖 Users can benefit from more stable and efficient training experience for large-scale machine learning tasks.

### CODE REVIEW

**Comment by developer0hye** [comment]
When I read the docs, it seems that we have to modify environment variable.

https://pytorch.org/docs/stable/distributed.html#torch.distributed.init_process_group

image

Also I saw some [issues](https://github.com/pytorch/pytorch/issues/50820) related to setting timeout.

So I tried to implement a method to avoid this method.

**Comment by developer0hye** [comment]
@glenn-jocher 

Please check my new pr!

https://github.com/ultralytics/ultralytics/pull/2660

**Comment by glenn-jocher** [comment]
@developer0hye I think we have to test this further, as I'm also seeing a duplicate process beings started. Here for example I rand `yolo train device=5,6,7`, but I see device 5 with 2 threads, which is a bug introduced by the new setup method. Let's revert the change here and debug this more carefully before making any new changes. I'll add the environment variable you mentioned.

Screenshot 2023-05-17 at 02 03 18

**Comment by glenn-jocher** [comment]
@developer0hye ok added environment variable in https://github.com/ultralytics/ultralytics/pull/2657/commits/aadae4c07ceccae2b396c7a5b709827a5681ace4

**Comment by developer0hye** [comment]
@glenn-jocher Okay! I agree with you.

**Comment by glenn-jocher** [comment]
@developer0hye thank you for understanding. If you have any further questions or issues related to YOLOv8, please feel free to open a new issue on this repo. We will do our best to assist you.

**Pull request merged**
