### PR TITLE
Add Night Vision feature

### PR DESCRIPTION
**Pull request by MohamedAtef321**
For this issue of feature request #1568 

### Summary
🌙🔦📸

This pull request introduces a night vision feature to the `detect` and `val` modes of the YOLO model, which enhances the image brightness in low-light conditions. It modifies the `detect` and `val` modules, the `BasePredictor` and `BaseValidator` classes, the default configuration file, and the documentation to support the feature. It also adds a new module `night_vision.py` to the `utils` package, which contains the core functions for applying the feature to images.

> _Oh we are the coders of the night vision mode_
> _We make the images bright with a bit of code_
> _We use `detect` and `val` to test our skill_
> _And we document our work with a hearty will_

### Walkthrough
*  Add night vision feature to `detect` and `val` modes, which enhances the image brightness in dark environments using gamma correction ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-597c0ff446990af3bc46d0ec8bf12cd047c250472b8155ba60aa2dbc6eaec6f3R38-R178), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-9d692d4ad15d420a92105fcd432fb1d2221b71d5af055bea3bd2b70523ce6743R68-R72), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-bd2831d027341da2474db760605211ea00b347396b0d708a4343a2b709eb3675R109-R112), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-7646fc7a670fe6bbcbf9e637a707139b362bd3b118be7faca28bff7d9b7450c3R89-R92), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-4883c2418b8c591052f85257e4b233d0bc5e2bbffb3c27254ef92d7d12d849b2R1-R208), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-d47b2bd99d71bef47ccb82b27f8a102c04b98072070f94d0ba341fa3221f8b81L8-R32), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-d47b2bd99d71bef47ccb82b27f8a102c04b98072070f94d0ba341fa3221f8b81R69-R75), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02R15), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02R33-R39))
  * Add new arguments to `default.yaml` to control the activation and parameters of the night vision mode ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-9d692d4ad15d420a92105fcd432fb1d2221b71d5af055bea3bd2b70523ce6743R68-R72))
  * Add new module `night_vision.py` to `utils` package, which contains the core functions for applying and measuring the night vision mode ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-4883c2418b8c591052f85257e4b233d0bc5e2bbffb3c27254ef92d7d12d849b2R1-R208))
  * Add log messages to `BasePredictor` and `BaseValidator` classes to inform the user that the night vision mode is activated ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-bd2831d027341da2474db760605211ea00b347396b0d708a4343a2b709eb3675R109-R112), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-7646fc7a670fe6bbcbf9e637a707139b362bd3b118be7faca28bff7d9b7450c3R89-R92))
  * Modify `DetectionPredictor` class in `predict.py` to apply the night vision mode to the input image and the original image before saving and displaying the results ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-d47b2bd99d71bef47ccb82b27f8a102c04b98072070f94d0ba341fa3221f8b81L8-R32), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-d47b2bd99d71bef47ccb82b27f8a102c04b98072070f94d0ba341fa3221f8b81R69-R75))
  * Add new method `get_annotator` to `DetectionPredictor` class to return an `Annotator` object for plotting the detection results ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-d47b2bd99d71bef47ccb82b27f8a102c04b98072070f94d0ba341fa3221f8b81L8-R32))
  * Modify `val` function in `val.py` to apply the night vision mode to the batch of images before running the validation ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02R15), [link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02R33-R39))
  * Set the `device` argument to `cpu` in `val` function, as the `val` mode only works on CPU ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02R33-R39))
* Add a new section to the documentation of the `detect` mode in `docs/tasks/detect.md`, explaining the night vision feature and providing some examples ([link](https://github.com/ultralytics/ultralytics/pull/1569/files?diff=unified&w=0#diff-597c0ff446990af3bc46d0ec8bf12cd047c250472b8155ba60aa2dbc6eaec6f3R38-R178))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
A new "Night Vision" feature has been added to improve image brightness for better detection in dark environments. 🌚

### 📊 Key Changes
- **Night Vision Feature:** Introduced for "detect" and "val" modes, specifically on CPU.
- **Gamma Correction:** Allows image brightness adjustment using gamma values.
- **New Parameters:** `night_vision`, `image_gamma`, `min_gamma`, `max_gamma`, and `min_normalized_intensity`.
- **Documentation & Examples:** Updated documentation with examples and additional images.

### 🎯 Purpose & Impact
- **Improved Detection:** Enhances image processing capabilities in low-light conditions, resulting in better detection performance.
- **User Flexibility:** Users can adjust image brightness via fixed or automatic gamma settings.
- **Broader Usability:** Makes detection models more versatile in varying lighting conditions, especially beneficial for surveillance and monitoring tasks.

### CODE REVIEW

**Comment by AyushExel** [comment]
Very cool! Thanks for the PR. I'll test it out tomorrow

**Comment by MohamedAtef321** [comment]
@AyushExel  Thanks, and I am here for any edits or errors.

**Comment by AyushExel** [comment]
Hey, I was looking at this. Nice job. It should also work for videos, right? It'd be great if you could provide a example video link that would show clear differences between `night_vision` mode on and off. Like improved detections, better visibility etc.
I tried on this video but I don't really see any difference - https://www.youtube.com/watch?v=yipIbtSQ_b8&ab_channel=VictorLaforteza

Here's the command I used:
```
yolo predict model=yolov8n.pt source=https://youtu.be/yipIbtSQ_b8 show imgsz=320 night_vision=True
```

**Comment by ExtReMLapin** [comment]
image

**Comment by MohamedAtef321** [comment]
You shouldn't pass it like `night_vision=True`, instead you should pass it like `night_vision` or `night_vision=show` to see results, I have made a little documentation for this feature usage in the `docs/tasks/detect.md` file.

And here are the little documentation I am talking about :
 
------------------------------------------------------

## Night Vision Feature
If you use camera in a dark environment, then you may get poor results.\
We have made a preprocess feature to enhance image brightness, it actually may help you get better results in dark environments.

You can use Night Vision mode by adding parameter `night_vision` as follows:

Using CLI:
```bash
yolo detect predict model=path/to/best.pt source='https://ultralytics.com/images/bus.jpg' night_vision
```
and it has 3 modes:

1- Default mode:
> By not passing parameter `night_vision`, it will use the original image as it is.

2- Night Vision mode (Only apply on input image):
```bash
night_vision 
```
> It will apply night vision on input image, pass it to the model and get the result based on night-processed image, But the shown/saved image will be the original image without night filter.

3- Night Vision mode (Apply on both input image and shown/saved image):
```bash
night_vision=show
```
> It will apply night vision on input image, pass it to the model and get the result based on night-processed image, The shown/saved image will be also night-processed image with night filter applied.

An example to differentiate between Night Vision modes and their (Saved/Shown) results:

night_vision_example

**Comment by glenn-jocher** [comment]
@MohamedAtef321 I've experimented in the past with including CLAHE contrast fixes as part of the train/val/predict loaders, but was not able to produce mAP improvements when applying them to both train and val dataloaders, nor to only the val dataloader. 

The anecdotal result looks good, but I think what we need is a statistical improvement on a validation set, again either by training a model with CLAHE (or your solution) and then validating on the same, or simply validating existing pretrained models on val loaders that include a CLAHE-type transform on the input.

**Comment by MohamedAtef321** [comment]
> @MohamedAtef321 I've experimented in the past with including CLAHE contrast fixes as part of the train/val/predict loaders, but was not able to produce mAP improvements when applying them to both train and val dataloaders, nor to only the val dataloader.
> 
> The anecdotal result looks good, but I think what we need is a statistical improvement on a validation set, again either by training a model with CLAHE (or your solution) and then validating on the same, or simply validating existing pretrained models on val loaders that include a CLAHE-type transform on the input.

You are right, I have tried here "histogram equalization" and even CLAHE you will see its implementation commented in `night_vision.py` code.
And the result doesn't get better in all test cases.
I think I should make some research on image light enhancing algorithms.
I was just asking for this to be as an initialization of a branch working on this special case scenario  of dark environments, then we could achieve more improvements in it.

**Comment by MohamedAtef321** [comment]
Hello Back 👋

I have made some changes on the project, they are listed as follows:

    🟢 Changed the dark enhancement technique (from image equalization to gamma correction).
    🟢 Made it fully customizable with more (optional) parameters.
    🟢 Added night vision in detect mode not only to `predict`, but also `val` now is available (but only works with `device=cpu`).
    🟢 Rewrite the theory and usage in a little documentation in path `"ultralytics/docs/tasks/detect.md"`.

but not all I got is good news, there are bad ones:

    🔴 I have tried to validate it with `val` on COCO128 dataset, after some trials I couldn't get mAP better than the original one without `night_vision` option (maximum mAP with `night_vision` was as same as without it).

I don't know whether the problem is in the dataset or in the Night Vision technique I used, I also tried to validate it on COCO dataset but it took too long time to load and I thought it got frozen.

so I decided to let you see my work and try to validate it with the dataset you want, also it has more parameters to help you to get better results.

(It would be so helpful if you found any dataset focus on the situation of dark environments to validate the model on it.)

--- 

💻 This is the full command to run yolo in Night Vision Mode:

Using CLI:

With only one parameter `night_vision`:

```bash
yolo detect predict model=path/to/best.pt source='path/to/your/image.jpg' night_vision=show
```

With all of parameters added to customize the NV mode:

```bash
yolo detect predict model=path/to/best.pt source='path/to/your/image.jpg' night_vision=show image_gamma=auto min_normalized_intensity=0.25 min_gamma=0.6 max_gamma=1.0
```

---

here's the added part in documentation found in path `"ultralytics/docs/tasks/detect.md"` if you want to know more about how this Night Vision feature work, and how to use it:

## Night Vision Feature 🌚
> Note:\
&nbsp;&nbsp;&nbsp;&nbsp; This feature is available for `detect` mode.\
&nbsp;&nbsp;&nbsp;&nbsp; and `val` mode, only with `device=cpu`.
<details>
<summary>How does it work ⚙?</summary>

Gamma correction is pretty simple, it's just a non-linear transformation of the input image.\
It is used to adjust the overall brightness of the image.\
The formula for gamma correction is as follows:



where `Image_out` is the output normalized image, `Image_in` is the input normalized image, and `Gamma` is the gamma value (power).
> Note:\
&nbsp;&nbsp;&nbsp;&nbsp; 1- The value of `gamma` is between 0 and 1 (closer to 0 brighter, closer to 1 darker).\
&nbsp;&nbsp;&nbsp;&nbsp; 2- The value of both `Image_out` and `Image_in` pixels are between 0 and 1.

To make it more clear, let's take a look at the following example:

Let's assume we have an image with only one pixel, and its value is 0.8 (normalized value).\
Now, let's apply gamma correction as follows:

`Image_out = Image_in ^ gamma`

> when `gamma = 0`, then `Image_out = 1`\
when `gamma = 0.25`, then `Image_out = 0.94`\
when `gamma = 0.5`, then `Image_out = 0.89`\
when `gamma = 0.75`, then `Image_out = 0.84`\
when `gamma = 1`, then `Image_out = 0.8`

let's plot the results:

night_vision_gamma

> Note:\
&nbsp;&nbsp;&nbsp;&nbsp; Decreasing the value of `gamma` will make the image brighter.

</details>

<details>
<summary>How to use it 🚄?</summary>

There are some arguments added for Night Vision Feature :
1. [night_vision](#🔵-night_vision-parameter)
2. [image_gamma (Optional)](#🔵-image_gamma-parameter)
    - if integer or float number :
        * No need to pass any other parameters.

    - if 'auto', then you can pass the following parameters (all of them have values between 0 and 1):
        * 🟢 min_normalized_intensity (Optional)
        * 🟢 min_gamma (Optional)
        * 🟢 max_gamma (Optional)

these parameters are described as below:

### 🔵 **night_vision** parameter :
(default value is `False`)

If you use camera in a dark environment, then you may get poor results.\
We have made a preprocess feature to enhance image brightness, it actually may help you get better results in dark environments.

You can use Night Vision mode by adding parameter `night_vision` as follows:

Using CLI:
```bash
yolo detect predict model=path/to/best.pt source='https://ultralytics.com/images/bus.jpg' night_vision
```
and it has 3 modes:

1- Default mode:
> By not passing parameter `night_vision`, it will use the original image as it is.

2- Night Vision mode (Only apply on input image):
```bash
night_vision
```
Or
```bash
night_vision=true
```
> It will apply night vision on input image, pass it to the model and get the result based on night-processed image, But the shown/saved image will be the original image without night filter.

3- Night Vision mode (Apply on both input image and shown/saved image):
```bash
night_vision=show
```
> It will apply night vision on input image, pass it to the model and get the result based on night-processed image, The shown/saved image will be also night-processed image with night filter applied.

An example to differentiate between Night Vision modes and their (Saved/Shown) results:

night_vision_example

### 🔵 **image_gamma** parameter :
(default value is `auto`)

image_gamma parameter has 2 modes:

1- Fixed gamma value:

> If you want to use fixed gamma value (from 0 to 1), you can pass `image_gamma` parameter as follows:\
&nbsp;&nbsp;&nbsp;&nbsp; Note 1: 1 means no change in image brightness, 0 means white image.\
&nbsp;&nbsp;&nbsp;&nbsp; Note 2: Lower gamma value means more lightening applied to image (brighter image).

Using CLI:
```bash
yolo detect predict model=path/to/best.pt source='https://ultralytics.com/images/bus.jpg' night_vision=show image_gamma=0.8
```
> It will use fixed gamma value of 0.8

2- Auto gamma value:
> If you want to use auto gamma value, you can pass `image_gamma` parameter as follows:

Using CLI:
```bash
yolo detect predict model=path/to/best.pt source='https://ultralytics.com/images/bus.jpg' night_vision=show image_gamma=auto
```

It will test normalized image intensity (its value from 0 to 1), and its value describe image brightness (closer to 0 means dark image, closer to 1 means bright image).

> if it is less than `min_normalized_intensity` (default value is 0.25) meaning that image is dark, then it will use scaled gamma value (from `min_gamma` to `max_gamma`) - based on image intensity - to enhance image brightness.\
&nbsp;&nbsp;&nbsp;&nbsp; Note: `min_gamma` and `max_gamma` have default values of 0.6 and 1.0 respectively.

> if it is greater than `min_normalized_intensity` (default value is 0.25) meaning that image is bright, then it will use fixed gamma value of 1 (no change in image brightness).

For full customized gamma value, you can pass `min_normalized_intensity`, `min_gamma` and `max_gamma` as follows:

Using CLI:
```bash
yolo detect predict model=path/to/best.pt source='https://ultralytics.com/images/bus.jpg' night_vision=show image_gamma=auto min_normalized_intensity=0.5 min_gamma=0.8 max_gamma=1.0
```

An example to show effect of gamma (`image_gamma`) on image brightness  :

gamma_example


</details>

---

And here are some results I got recently (Before and After Night Vision) :

image
image
image
image
image
image



Finally I hope this could be helpful to you and also you get better results than me with a change in dataset or the added parameters. 🙏

I am very excited to get feedback from you about my work.

Thanks

**Comment by MohamedAtef321** [comment]
Have you tried and tested/validated the new night vision feature ?
I hope to get feedback from you soon. ⚡

**Comment by AyushExel** [comment]
Thanks for the work. We'll take a look and get back to you!

**Comment by glenn-jocher** [comment]
@MohamedAtef321 thank you for your work on this!

After a thorough review, we've decided not to merge your proposed changes at this time. While your contribution shows promise, it doesn't align with our current development goals or the project's direction. However, please don't let this discourage you. We encourage you to continue to contribute to open source projects and stay involved in the community.

We recognize and value the knowledge and experience you bring to the table. Your willingness to contribute is a testament to your commitment to the open-source community, and we would be more than happy to see you contribute to the project in the future.

Please don't hesitate to explore other open issues, suggest new features, or submit further pull requests. Your insights and expertise are always welcome.

**Comment by MohamedAtef321** [comment]
Thanks for your time, I understand your decision. However, I will not stop developing in this feature and I will try to make more validations for it, if I got better results I will share it with you.

Thanks @AyushExel @glenn-jocher

**Comment by glenn-jocher** [comment]
@MohamedAtef321 thank you for understanding our decision. We appreciate your commitment to developing the night vision feature and we welcome any future contributions you may have. We value your dedication to the open-source community and we look forward to seeing your progress. Please feel free to reach out if you have any questions or concerns.

**Comment by WangQvQ** [comment]
Hello, your work is very good, I have a small question to consult you, hope to get your reply, thank you.💖

Did you train the model with or without gamma processed data sets?
Does gamma correction only work in the inference of the model?

**Comment by glenn-jocher** [comment]
@WangQvQ hi there! Thank you for your kind words and reaching out with your question. 

Regarding the training of the YOLOv8 model, it's important to note that we didn't specifically train it with gamma processed datasets. However, YOLOv8 is designed to handle various types of input data, including gamma corrected images. 

In terms of gamma correction, it can be applied both during the training phase and the inference phase of the YOLOv8 model. Gamma correction helps to improve the overall quality and accuracy of the model's predictions by adjusting pixel values, particularly in low-light or high-contrast scenarios. 

Feel free to let me know if you have any further questions. I'm here to help! 💫

**Comment by MohamedAtef321** [comment]
Hello back 👋 YOLOv8 Team @AyushExel @glenn-jocher

--------------------------------------------------------------------------------------

We just wanted to let you know that :
- We wanted to share with you our celebration of our college graduation 🎓. We have graduated from "Electronics and Communications department  - Faculty of Engineering - Mansoura University - Egypt".
- We used your YOLOv8 in our graduation project, and we would really like to thank you from the bottom of our hearts for the time and effort you made with us, as you guided us to explore and use your magnificent work in YOLOv8 ✨. You replied quickly to the issues we made and really this accelerated our work.
- We also want to let you know that the Night Vision feature was just one of the little modifications we made to make your YOLOv8 suitable for our application in advanced driver-assistance system (ADAS).
- You could have a look on our graduation project from here [RTSD-Road-Traffic-Signs-Detection-System](https://github.com/MohamedAtef321/RTSD-Road-Traffic-Signs-Detection-System).
- Our Gorgeous Team :
- photo_2023-07-10_23-22-16

------------------------------------------------------------------------------

And for future work and contribution to YOLOv8. 
- We will not be satisfied with only Gamma Correction. We intend to implement more image processing techniques (like for example unsharp masking) as optional individual features to YOLOv8 to provide more options to make images clearer and enhanced before processing of YOLOv8 model.
  - **Note** : These features will be full optional to be independent and doesn't affect of your YOLOv8 Performance.
- We also intend to provide you with a benchmark and evaluation for every little detail we will make, to provide you with the clear insights you need to know about our work.

--------------------------------------------------------------------------------

Finally, It was our pleasure to talk with you and work on your wonderful work. we are excited to contribute to YOLOv8 and as we still learning, we will apply what we learn to your work.

Thanks @AyushExel @glenn-jocher 💖💖

**Review by ambitious-octopus — COMMENTED** [review]
Closing as not planned!

**Pull request closed without merging**
