### PR TITLE
Decathlon training

### PR DESCRIPTION
**Pull request by rbbb**
### Summary
🏋️‍♂️🔄🐛

This pull request adds a new `decathlon` task to the yolo package, which trains a model on multiple tasks using different datasets and prediction heads. It modifies the `ultralytics/cfg/__init__.py` file to support the new task and avoid warnings. It fixes the loss computation and aggregation in the `ultralytics/engine/trainer.py` file for the decathlon mode. It adds a new subpackage `ultralytics/models/yolo/decathlon` that contains the classes and functions for the decathlon task. It registers the decathlon task and its classes in the `ultralytics/models/yolo/model.py` file.

> _We train on multiple tasks, we switch the heads and datasets_
> _We face the decathlon challenge, we import the yolo package_
> _We fix the loss computation, we handle the NaNs in gradients_
> _We rock the decathlon mode, we are the `DecathlonTrainer`s_

### Walkthrough
*  Add support for a new task 'decathlon' that trains a single model on multiple tasks using different datasets and prediction heads ([link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-c02fb3f9e86e97bf85f07211aed56aa04774504a61eeff07a08471bbdea14556L16-R29), [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-d85395b639979a65be5ffda459dd071688c28222abea583cf25df1780d0e0d07L34-R40))
*  Implement a custom trainer class for the decathlon task that handles the logic of switching between different tasks, models, datasets, and optimizers during training (`ultralytics/models/yolo/decathlon/train.py`, [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-ecb610701352ee749053f25cf12277ca04dc50f12e8785626a059c9133bd79c0R1-R344))
*  Modify the computation of the running total loss and the gradients to avoid errors and NaN values when aggregating the loss from different tasks in the decathlon mode (`ultralytics/engine/trainer.py`, [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL346-R359), [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL386-R396))
*  Allow passing different tasks to the same model without raising a warning or ignoring the task argument by setting the model task to match the task argument (`ultralytics/cfg/__init__.py`, [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-c02fb3f9e86e97bf85f07211aed56aa04774504a61eeff07a08471bbdea14556L428-R433))
*  Make the decathlon module accessible from the yolo package and expose its classes and functions (`ultralytics/models/yolo/__init__.py`, [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-7bb0bb8a018eb6885d35c69879091dc25b89a04046f5b3ce71e82ddb1c6f65b7L3-R7), `ultralytics/models/yolo/decathlon/__init__.py`, [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-63ddd33bea1bf7ba1c810ddb7bfa84aa88978286a78903a50793464838ae4000R1-R8))
*  Implement empty predictor and validator classes for the decathlon task, which are required by the yolo package interface but not used (`ultralytics/models/yolo/decathlon/predict.py`, [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-ac13ca9c83a7fd7d1df95cf54cb6fa644b4420adb0a75e510210a4050bf375b6R1-R24), `ultralytics/models/yolo/decathlon/val.py`, [link](https://github.com/ultralytics/ultralytics/pull/5924/files?diff=unified&w=0#diff-200f5816683dd382832be6a29afb10611ab8754d9c4caba2aa60bb0cd98f89fbR1-R56))

/////// END OF COPILOT DESCRIPTION

Relevant papers:
- https://arxiv.org/abs/1806.08730
- https://arxiv.org/abs/1910.10683

Pseudo-code:
- for b in batchnumber
- for task_t in [imagenet, cifar, cocosegment, cocodetect]
- get batch b for task_t, model(b) with task_t's prediction head, loss of task_t, optimizer.step()

This was more difficult than pseudo-code because pytorch doesn't like the sharing of parameters and yolo model/trainer/loss/validation wasn't supposed to be changed at runtime.

@glenn-jocher I wrote this for fun and challenge, please tell me if this is of interest to you. The potential application is having one yolo instead of yolo-segment, yolo-detect, yolo-cls, etc ...

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing a new "decathlon" task to the Ultralytics YOLO framework for multi-task training and evaluation.

### 📊 Key Changes
- Added a new "decathlon" option to the list of tasks.
- Implemented `DecathlonTrainer`, `DecathlonPredictor`, and `DecathlonValidator` classes.
- Modified the trainer to handle multiple tasks dynamically.
- Integrated handling for different model heads and optimized resource management during training.

### 🎯 Purpose & Impact
- **Multi-task Learning**: Enables training across multiple tasks (e.g., detection and classification) in one setup, improving efficiency and resource usage.
- **Code Modularity**: Facilitates easier integration of additional tasks in the future.
- **Robust Training**: Ensures stable training by handling NaNs in gradients, enhancing model reliability.

### CODE REVIEW

**Comment by rbbb** [comment]
@glenn-jocher also, this 1 billion images single label dataset https://arxiv.org/abs/2306.07952

**Comment by glenn-jocher** [comment]
@rbbb thanks for sharing the dataset resource! We're always interested in large-scale and diverse datasets to improve our models. If you're considering training YOLOv8 on such a dataset or if you're facing any specific issues with it, feel free to share your experiences or questions. For training and implementation guidance, please refer to our documentation at https://docs.ultralytics.com. Happy training! 😊🚀

**Review by ambitious-octopus — COMMENTED** [review]
The idea is certainly interesting. The problems are many:
1. The supporting sources are related to language models
2. The PR is now old and quite difficult to test (I tried)
3. I don't know how much it makes sense on a theoretical level
4. 0 evidence of performance

In light of this, if @Laughing-q  has nothing to add I close this PR.

**Comment by rbbb** [comment]
Yes, please close the PR.

It is possible to make it work for vision networks, but since even Resnet is difficult to train from scratch, this is particularly difficult and unstable to train.

**Pull request closed without merging**
