### PR TITLE
Extend OpenVINO INT8 ignored scope

### PR DESCRIPTION
**Pull request by adamp87**
As discussed in PR #7516 at https://github.com/ultralytics/ultralytics/pull/7516#issuecomment-1929581353 , I have made the requested changes. Please merge this branch to the other branch and lets continue discussion there

### CODE REVIEW

**Comment by adamp87** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by glenn-jocher** [comment]
@adamp87 awesome, thanks for the PR! All benchmarks are passing now! 

One question I had was whether we've added almost all of the ops to the ignore list. Since we have all 4 major mathematical operations, is there really anything still undergoing quantization when exporting INT8 with this PR?

Can you tell what proportion of the weights/ops are quantized? Thanks!

**Comment by adamp87** [comment]
@glenn-jocher should we just merge this branch to the other branch and continue discussion there? This runs only 2 tests. This PR is not going to main, instead it goes to #7516

**Comment by adamp87** [comment]
To answer your question in short we only leave out from quantization the last few operations, where we calculate the pixel coordinates. In more detail:

Convolution and weights
NNCF with ignored_scope `".*/Conv.*"`, counts 127 nodes of `Conv `and `Mul`. This should be 60 Conv with SiLU activation and 7 Conv without activation. During export, we add 1 Conv to ignored_scope from the DFL, which anyways have non-trainable weights. So this is **~1.5% of the Conv and 0% of the trainable weights**.

Math Operations:
NNCF counts 72 (Add,Sub,Mul,Div) in total, where 60 should be Mul from the SiLU, 6 Add operations are in the backbone. The remaining in `Detect (model.22)` are a bit tricky, because I count in Netron 10, NNCF count 9 and it does not add up to 72. So lets assume during export we ignore 9, that is 9/72, which is **~12.5% of the Math operations**.

Considering speed with `benchmark_app -m yolov8n.xml -d CPU` from OpenVINO on my old i7-9750H CPU:
Before: 
[ INFO ] Latency:
[ INFO ]    Median:        58.26 ms
[ INFO ]    Average:       **60.52 ms**
[ INFO ]    Min:           49.73 ms
[ INFO ]    Max:           123.66 ms
After: 
[ INFO ] Latency:
[ INFO ]    Median:        59.18 ms
[ INFO ]    Average:       **60.70 ms**
[ INFO ]    Min:           50.36 ms
[ INFO ]    Max:           151.63 ms

**Comment by adrianboguszewski** [comment]
@adamp87 do I understand this correctly that the time before and after the quantization is the same?

**Comment by adamp87** [comment]
@adrianboguszewski Before and After modifying the code. So before is the main branch, after is the proposed changes. I edit my post accordingly. Sorry for the confusion

**Comment by adrianboguszewski** [comment]
As you are ignoring more nodes could you also show the difference in mAP and inference time before and after the quantization? I mean it for this branch (changes from this PR included)

**Comment by adrianboguszewski** [comment]
@adamp87 I mean inference time for FP32 and INT8 (quantized with this PR) :)

**Comment by adamp87** [comment]
Inference time for FP32

[ INFO ] Latency:
[ INFO ]    Median:        96.03 ms
[ INFO ]    Average:       97.60 ms
[ INFO ]    Min:           64.49 ms
[ INFO ]    Max:           173.58 ms

**Comment by glenn-jocher** [comment]
@adamp87 thanks for the numbers, this result looks excellent to me! I think we're safe to merge to your other PR and then into main if @adrianboguszewski agrees.

The mAP increase is significant and the speed change negligible vs main.

**Comment by glenn-jocher** [comment]
@adamp87 @adrianboguszewski PR merged into #7516, thank you for your contributions!

**Comment by glenn-jocher** [comment]
@adamp87 ah this is interesting, our Ultralytics Actions failed to run on this PR because it's not targeted to main. They may need an update to handle this use case.

**Pull request merged**
