### PR TITLE
Disable augmentation during training

### PR DESCRIPTION
**Pull request by ambitious-octopus**
cc: @Laughing-q.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces optional data augmentation during the training of YOLO models in the Ultralytics repository.

### 📊 Key Changes
- **Documentation Update**: Added `augmentation` as a configurable parameter in the training documentation.
- **Configuration Update**: Included `augmentation: True` as a default setting in `default.yaml`.
- **Code Update**: Modified data building scripts to enable or disable augmentation based on the new configuration setting.

### 🎯 Purpose & Impact
- **Enhanced Model Generalization**: Data augmentation improves the model's ability to generalize by introducing variability during training. 
- **User Customization**: Users can now easily toggle data augmentation on or off, providing greater flexibility in model training.
- **Improved Documentation**: Clearer documentation helps users understand and utilize the new `augmentation` feature effectively.

### CODE REVIEW

**Comment by Alarmod** [comment]
Why header of ticket "Disable augmentation during training"? 

```
augmentation: True # (bool) Enables data augmentation during training
cfg.augmentation if mode == "train" else False,
```
Here augmentation enabled for train mode by default and disabled for prediction or validation

**Comment by ambitious-octopus** [comment]
Hey @Alarmod, this PR allows the user to disable augmentation during training.

**Comment by Alarmod** [comment]
OK... But also exist param with name ```augment```, I use it to disable augmentation for final test of trained network (in train). So exist two parameters - augment and augmentation.

**Comment by ambitious-octopus** [comment]
@Alarmod `augment` argument is a `predict` ([docs](https://docs.ultralytics.com/modes/predict/#inference-arguments)) argument that enables Test Time Augmentation. We do not have a flag that disables augmentation in training, till this PR.

**Comment by Alarmod** [comment]
@ambitious-octopus 
But this argument work and I use it... See last [comment](https://github.com/ultralytics/ultralytics/issues/5912#issuecomment-1960501853) of @glenn-jocher

**Comment by glenn-jocher** [comment]
Thank you for pointing that out. We'll review the usage of the `augment` argument in training to ensure consistency and address any issues.

**Comment by glenn-jocher** [comment]
@ambitious-octopus we shouldn't add conflicting argument names. If we have a flag called augment let's enable that flag for training rather than adding a second argument `augmentation` that users will confuse with `augment`.

`imgsz` for example is used across modes like predict and train.

**Comment by glenn-jocher** [comment]
@ambitious-octopus but also training augmentations are handled individually so users can enable, disable, or modify them one by one, i.e. `scale=0.1` or `scale=0.0` to disable.

**Comment by ambitious-octopus** [comment]
@glenn-jocher You're absolutely right; I did reuse the `augment` argument in the predict function. I also believe that this addition could be quite helpful for debugging purposes. By adding this flag, we can not only disable augmentation when needed but also avoid initializing a set of instances responsible for augmentation, such as the `buffer` in `BaseDataset`.

We’re already seeing how the absence of this flag might lead to some confusion—for example, @Alarmod  assumed the argument was functional.

That being said, if you feel this PR isn't necessary, please feel free to close it.

**Review by ambitious-octopus — COMMENTED** [review]
Marked as a Draft because I'm fixing the CI errors for segmentation!

**Comment by Alarmod** [comment]
@ambitious-octopus 
Now this argument change Test Time Augmentation and it code working. Now In segmentation mode if I run model.train() with _augment=True_, this leads to an error (at the very end of code execution) due don't fixed code issue, need fix that situation... Argument pass augment pass to ultralytics internal functions over **kwargs...

https://github.com/ultralytics/ultralytics/issues/5912

How enable dataset aumentation and disable Test Time Augmentation?

**Comment by ambitious-octopus** [comment]
It appears we cannot reuse the augment `argument` because it's already utilized during `validation` for Test Time Augmentation (TTA), which doesn't function properly with segmentation tasks.

For instance, running the following command on the main branch:

```bash
yolo train segment model=yolov8n-seg.pt data=coco8-seg.yaml epochs=1 cache=disk augment=True
```
produces this error:
```
File "ultralytics/models/yolo/segment/val.py", line 83, in postprocess
    proto = preds[1][-1] if len(preds[1]) == 3 else preds[1]  # second output is len 3 if pt, but only 1 if exported
TypeError: object of type 'NoneType' has no len()
```
The same issue occurs with this code snippet:

```python
from ultralytics import YOLO

model = YOLO("yolov8n-seg.pt")
model.predict(augment=True)
```

This raises the question: Is it appropriate to use Test Time Augmentation during validation? 

Either way, it's important to clarify that TTA is not compatible with segmentation models, and this should be explicitly documented. What do you think @Laughing-q ?

Relevant code:
https://github.com/ultralytics/ultralytics/blob/95d54828bbd3fd3ba7df9ff7c075568f0b668506/ultralytics/engine/validator.py#L171-L187

**Comment by Alarmod** [comment]
_augment_ may be non binary, for examle
```
don't augument all - 0
augument train and don't augument Test Time - 1
don't augument train and augument Test Time - 2
augument all - 1
```

or full disable Test Time augmentation

**Comment by glenn-jocher** [comment]
Thank you for the suggestion. Currently, `augment` is used for Test Time Augmentation, which doesn't work with segmentation tasks. We'll consider your input for future improvements.

**Comment by Laughing-q** [comment]
@ambitious-octopus @Alarmod Nice catch! We actually had a warning msg for this but I just realized somehow it's removed, adding it back in this [PR](https://github.com/ultralytics/ultralytics/pull/16056)

**Pull request closed without merging**
