### PR TITLE
Auto-assign experiment name from model

### PR DESCRIPTION
**Pull request by glenn-jocher**
When `name=model` is passed.

### Summary
📝🗂️🎛️

Assign default model names based on YAML files in `ultralytics/yolo/cfg`. This change simplifies the configuration of custom models and avoids name conflicts.

> _`name` from `model`_
> _or user's choice, either way_
> _autumn leaves fall fast_

### Walkthrough
*  Assign model name to cfg dictionary if not specified (`[link](https://github.com/ultralytics/ultralytics/pull/2787/files?diff=unified&w=0#diff-daf1714127b012666c9fed39d0e75184c60be83f0c6bd3f9863f27113b1a6c22R118-R119)`)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refinement of configuration handling for YOLO models in Ultralytics software.

### 📊 Key Changes
- Improved special handling for `project` and `name` keys within configurations when their values are numeric.
- Addition of logic to set the value of the `name` key based on the `model` name, if `name` is explicitly set to 'model'.

### 🎯 Purpose & Impact
- Ensures that numeric values for project names and names are correctly converted to strings, avoiding potential type errors.
- Allows users to refer to the model directly within the configuration, making it more intuitive and streamlined. 👍
- Enhances configuration flexibility and consistency which can lead to fewer errors when setting up models. 🛠️

### CODE REVIEW

**Comment by AyushExel** [comment]
@glenn-jocher maybe when doing this, add a `LOGGER.info("name=model is a special override that sets the experiment name to the model name. Setting exp name to  {cfg.get("model")}")`

**Comment by glenn-jocher** [comment]
> LOGGER.info("name=model is a special override that sets the experiment name to the model name. Setting exp name to {cfg.get("model")}")

Good idea! I'll add a console printout.

**Comment by glenn-jocher** [comment]
@AyushExel BTW I added this because YOLOv5 has it and it's missing here. I use it to make my life easier when training/logging, i.e.:


```
sleep 0 && yolo detect train device=0 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg1.yaml > /dev/null 2>&1 &
sleep 2 && yolo detect train device=1 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg2.yaml > /dev/null 2>&1 &
sleep 4 && yolo detect train device=2 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg3.yaml > /dev/null 2>&1 &
sleep 6 && yolo detect train device=3 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg4.yaml > /dev/null 2>&1 &
sleep 8 && yolo detect train device=4 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg5.yaml > /dev/null 2>&1 &
sleep 10 && yolo detect train device=5 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg6.yaml > /dev/null 2>&1 &
sleep 12 && yolo detect train device=6 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg7.yaml > /dev/null 2>&1 &
sleep 14 && yolo detect train device=7 data=coco.yaml epochs=300 batch=128 project=exp8-1 cache=disk name=model model=yolov8s-Cg8.yaml > /dev/null 2>&1 &

```

**Comment by glenn-jocher** [comment]
Ok now a warning will print to screen:

```
yolo train name=model

WARNING ⚠️ 'model' is missing. Using default 'model=yolov8n.pt'.
WARNING ⚠️ 'data' is missing. Using default 'data=coco128.yaml'.
WARNING ⚠️ automatically updating 'name=model' to 'name=yolov8n'.
Ultralytics YOLOv8.0.108 🚀 Python-3.10.6 torch-1.13.1 CPU
```

**Pull request merged**
