### PR TITLE
Remove `verbose` arg from train docs.

### PR DESCRIPTION
**Pull request by Y-T-G**
`verbose` doesn't virtually do anything during training.

https://github.com/ultralytics/ultralytics/issues/17235#issuecomment-2445909000

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Removed the verbose option from training arguments documentation.

### 📊 Key Changes
- Deleted the `verbose` option from the training arguments documentation in `train-args.md`.

### 🎯 Purpose & Impact
- **Clarity**: The removal indicates this feature might no longer be supported or relevant, reducing confusion and streamlining options for users.
- **User Experience**: Simplifies training options, potentially reducing cognitive load for users configuring model training settings.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to guide you through our PR process. An Ultralytics engineer will also review your submission soon. Meanwhile, please ensure the following steps are completed to help facilitate a smooth review process:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description. In your case, it's great you've linked it to the relevant [issue](https://github.com/ultralytics/ultralytics/issues/17235) for context. 👍
- ✅ **Synchronize with Source**: Make sure your PR is up-to-date with the `ultralytics/ultralytics` `main` branch. Use the 'Update branch' button or run `git pull` and `git merge main` locally if needed.
- ✅ **Ensure CI Checks Pass**: Check that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are successful. If there are any issues, please address them.
- ✅ **Update Documentation**: You've done well to adjust the documentation. Ensure all other relevant parts are updated if needed. 📝
- ✅ **Sign the CLA**: Ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA" if this is your first contribution.
  
Please also minimize your changes to the **essential** modifications related to the documented issue. 📉

For further guidance, kindly refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don't hesitate to leave a comment if you require any assistance. Thank you for making the Ultralytics project even better! 🚀✨

**Review by ambitious-octopus — CHANGES_REQUESTED** [review]
@Y-T-G The problem with the issue you linked, is that the user is using a notebook and the outputs overflow the output cell. Maybe instead of removing the argument, it would be better to make it do what users expect. Maybe if `verbose=False`, we silence the loggers, what do you think?

**Comment by Y-T-G** [comment]
@ambitious-octopus I feel like that's a very unusual use case - to not want to see logs during training. But I guess it can be added.

The user can also redirect the logs as I suggested. Most notebooks allow running shell commands by prefixing with `!`. And if they still want to use Python API, they can create a Python script file and launch the training using the `!python script.py > logs.txt >2&1` command in the notebook and redirect the output.

**Comment by ambitious-octopus** [comment]
@Y-T-G Ok, you've convinced me :smiley: !

**Comment by glenn-jocher** [comment]
@Y-T-G PR merged!

**Pull request merged**
