### PR TITLE
feat: migrate hub code to sdk

### PR DESCRIPTION
**Pull request by hassaanfarooq01**
### Summary
🔀🆕🛠️

This pull request migrates the ultralytics package to use the new HUB SDK package for HUB API communication and model management. It updates the Model class, the HUBTrainingSession class, the hub callbacks, and the login function to use the new HUB SDK features and objects. It also removes or refactors some redundant or outdated code from the ultralytics.hub and ultralytics.utils modules.

> _`ultralytics.hub`_
> _Migrates to new HUB SDK_
> _Winter of changes_

### Walkthrough
*  Migrate to the new HUB SDK by using the `hub_sdk` package for authentication, session management, model creation, and model upload ([link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L8-R13), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-f7dddb3b6d840a691522cc45f718c3f2868e06c9827eb34394f9679634187f14L4-R48), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-85379178c8e65ebd6d21926e6c2e40266e8698733403b80d827818261904b733L4-R6), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-9a8f35e10c3ac02a449639cf43585490df23cfd85ccf328635b79214fe710bfaL3-R17), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-9a8f35e10c3ac02a449639cf43585490df23cfd85ccf328635b79214fe710bfaL49-R280), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-9a8f35e10c3ac02a449639cf43585490df23cfd85ccf328635b79214fe710bfaL152-R318), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-d693ce5357f986ca2cbcecfc9c3a937b2556b3d2245519d6beb72f17b57c14c2L3), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-d693ce5357f986ca2cbcecfc9c3a937b2556b3d2245519d6beb72f17b57c14c2L19-L20), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-bfbe3cd1c6ba73e6be6d3947b29e3fcaafcaa68d593dc97f2c7f08502e4bb212L6-R8))
*  Add a condition for creating a new model in HUB using the local training arguments in the `Model` class of `ultralytics/engine/model.py` ([link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L76-R98), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R356-R360))
*  Fix a bug that overwrites the local training arguments by the HUB training arguments if the session is not authenticated or has not loaded a model from HUB in the `Model` class of `ultralytics/engine/model.py` ([link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L321-R343))
*  Rename the `url` parameter to `identifier` in the `HUBTrainingSession` class of `ultralytics/hub/session.py` to support different types of model identifiers ([link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-9a8f35e10c3ac02a449639cf43585490df23cfd85ccf328635b79214fe710bfaL37-R40))
*  Display a progress bar for the final model upload in the `HUBTrainingSession` class of `ultralytics/hub/session.py` ([link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-9a8f35e10c3ac02a449639cf43585490df23cfd85ccf328635b79214fe710bfaL152-R318))
*  Use the `model.id` and `model_file` attributes instead of the `model_id` attribute in the `HUBCallback` class of `ultralytics/utils/callbacks/hub.py` to reflect the changes in the `HUBTrainingSession` class ([link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-bfbe3cd1c6ba73e6be6d3947b29e3fcaafcaa68d593dc97f2c7f08502e4bb212L15-R20), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-bfbe3cd1c6ba73e6be6d3947b29e3fcaafcaa68d593dc97f2c7f08502e4bb212L24-R34), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-bfbe3cd1c6ba73e6be6d3947b29e3fcaafcaa68d593dc97f2c7f08502e4bb212L42-R49), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-bfbe3cd1c6ba73e6be6d3947b29e3fcaafcaa68d593dc97f2c7f08502e4bb212L53-R65))
*  Use parentheses instead of braces to store the callbacks in the `HUBCallback` class of `ultralytics/utils/callbacks/hub.py` to preserve the order of the callbacks ([link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-bfbe3cd1c6ba73e6be6d3947b29e3fcaafcaa68d593dc97f2c7f08502e4bb212L79-R91), [link](https://github.com/ultralytics/ultralytics/pull/6547/files?diff=unified&w=0#diff-bfbe3cd1c6ba73e6be6d3947b29e3fcaafcaa68d593dc97f2c7f08502e4bb212L87-R99))

This PR introduces the Ultralyitcs HUB SDK as a dependency. We are still testing and this is not ready for merge yet.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the Ultralytics HUB integration within the Ultralytics AI library.

### 📊 Key Changes
- Refactoring and simplification of HUB API and session management.
- Added ability to save API key in settings after successful authentication.
- Improved rate-limiting and error handling for HUB requests.
- Enhanced model session management for training and uploading metrics and checkpoints.
- Centralized handling of environment variables for HUB API and Web roots.
- Added thread-based request queuing for HUB interactions.
- Deployment of HUBClient from the `hub_sdk` package for cleaner client-server communication.

### 🎯 Purpose & Impact
- 💻 **Developers**: Easier for developers to interact with the HUB. Cleaner API and session management make codebase maintenance and enhancements straightforward.
- ⚙️ **Functionality**: Models can now be created within the HUB if the task is 'train', and settings like the API key are automatically saved and reused.
- 🚀 **Usability**: User-facing aspects (like model checkpoints/metrics uploading, session handling, etc.) are now more resilient to failures and have clearer progress indication.
- 📈 **Performance**: Improved efficiency in API calls will reduce latency and potential bottlenecks when interacting with the HUB during training.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@hassaanfarooq01 please write a new message with this to make the CLA bot happy:

I have read the CLA Document and I sign the CLA

**Comment by hassaanfarooq01** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@hassaanfarooq01 thanks! It seems like CI is failing for benchmarks, can you try to debug this?

**Comment by kalenmike** [comment]
@glenn-jocher Lets hold off on taking this PR further until we can do some more test on our end.

**Comment by Burhan-Q** [comment]
Unable to connect using local resources and HUB API Key (key copied from Settings and Create a Model menu)

```py
from ultralytics import YOLO, checks, hub
checks()

hub.login(f'{APIKEY}')
>>> 2023-12-12 10:02:07,261 - hub_sdk.helpers.logger - WARNING - Q:\ML_dev\ultra_hub\.hub Invalid API key ⚠️
Ultralytics HUB: Retrieve API key from https://hub.ultralytics.com/settings?tab=api+keys
```

**Comment by Burhan-Q** [comment]
## Error loading model

```py
model = YOLO('https://stage.ultralytics.com/models/w1up9OjCVLUH7tAXR78D')

>>> 2023-12-12 11:07:24,722 - hub_sdk.helpers.logger - ERROR - Unauthorized: Please check your credentials.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "Q:\ML_dev\ultra_hub\repo\ultralytics\ultralytics\engine\model.py", line 87, in __init__
    self.session = get_hub_session(model)
  File "Q:\ML_dev\ultra_hub\repo\ultralytics\ultralytics\engine\model.py", line 81, in get_hub_session
    session = HUBTrainingSession(model)
  File "Q:\ML_dev\ultra_hub\repo\ultralytics\ultralytics\hub\session.py", line 68, in __init__
    self.load_model(model_id)  # Load existing model
  File "Q:\ML_dev\ultra_hub\repo\ultralytics\ultralytics\hub\session.py", line 74, in load_model
    self.model = self.client.model(model_id)
  File "Q:\ML_dev\ultra_hub\.hub\lib\site-packages\hub_sdk\hub_client.py", line 22, in wrapper
    return func(self, *args, **kwargs)
  File "Q:\ML_dev\ultra_hub\.hub\lib\site-packages\hub_sdk\hub_client.py", line 86, in model
    return Models(model_id, self.get_auth_header())
  File "Q:\ML_dev\ultra_hub\.hub\lib\site-packages\hub_sdk\modules\models.py", line 24, in __init__
    self.get_data()
  File "Q:\ML_dev\ultra_hub\.hub\lib\site-packages\hub_sdk\modules\models.py", line 40, in get_data
    resp = super().read(self.id).json()

AttributeError: 'NoneType' object has no attribute 'json'
```

**Pull request merged**
