### PR TITLE
Fix for v8 validation error for multiple directory

### PR DESCRIPTION
**Pull request by hardikdava**
This PR is a fix for v8/val.py regarding validation bug for dataset from multiple directory.

Actual error when multiple directories are included in yaml file.

```
self.is_coco = self.data.get('val', '').endswith(f'coco{os.sep}val2017.txt')  # is COCO dataset
AttributeError: 'list' object has no attribute 'endswith'
```

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Revamping README and Improving COCO Dataset Detection in Python Code

### 📊 Key Changes
- **README Code Example Updates**: Code snippets now show how to build a new YOLOv8 model, how to load a pretrained model, train, validate, predict and export the model in a structured format.
- **Validation Path Handling**: Enhanced the `val.py` script to correctly identify the COCO dataset through more flexible validation path checking.
- **Contributor Image Link**: Updated the link to the contributors' image to reflect the repository's proper path.

### 🎯 Purpose & Impact
- **Easier Onboarding**: The updated instructions in the README will make it easier for new users to understand how to use the YOLOv8 model in various ways, thereby enhancing the user experience.
- **Better Dataset Recognition**: The tweak in `val.py` ensures more reliable dataset detection, which is crucial for accurate performance measurement during validation.
- **Greater Acknowledgment of Contributors**: Fixing the contributor image link ensures that the contributions of the community are properly recognized and can be easily accessed by visitors.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@hardikdava thanks for the PR! Does this still work with COCO val?

**Comment by hardikdava** [comment]
@glenn-jocher i haven't checked it yet. But it should work without any issue.

**Comment by hardikdava** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@hardikdava I think this may not work correctly, if I put a breakpoint here for COCO128 for example I get this:

```
self.data.get('val', '')
Out[3]: '/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/yolo/v8/datasets/coco128/images/train2017'
```

**Comment by glenn-jocher** [comment]
@hardikdava made a change here that should resolve this if you are seeing a list here. Please test to make sure my fix works. Thanks!

**Comment by glenn-jocher** [comment]
@hardikdava merged into general updates and improvements PR I've started.

**Pull request merged**
