### PR TITLE
Add YOLO common issues guide to Docs

### PR DESCRIPTION
**Pull request by abirami-vina**
### Summary
:memo::mag::sparkles:

This change updates the documentation file `docs/guides/troubleshooting-common-issues.md` with metadata for the website and SEO. The file contains tips and solutions for common problems when using the YOLOv8 model.

> _`front matter` added_
> _for website and SEO_
> _autumn docs update_

### Walkthrough
*  Add front matter metadata for markdown file `docs/guides/troubleshooting-common-issues.md` ([link](https://github.com/ultralytics/ultralytics/pull/5218/files?diff=unified&w=0#diff-c81deffb6275dd420e94ea24becc20c64afe58dba288b281fa0d177da628cb69R1-R270))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
New comprehensive troubleshooting guide for YOLOv8 released.

### 📊 Key Changes
- Added a new document titled "Troubleshooting Common YOLOv8 Issues."
- Provided detailed troubleshooting steps for installation errors, model training, predictions, and deployment.
- Included tips on accelerating training with multiple GPUs, tracking training progress, extracting object dimensions, and dealing with GPU deployment.
- Mentioned resources for community support, official documentation, and forums.

### 🎯 Purpose & Impact
- To assist users in resolving common issues while working with YOLOv8, reducing project delays and frustrations.
- Helps improve user understanding of YOLOv8 functionalities and ensures optimal usage of the software.
- Encourages community engagement for additional support and knowledge sharing, enhancing user experience and collective know-how. 

Expect smoother workflows and more efficient problem-solving for developers and practitioners of YOLOv8! 🛠️💡🔗

### CODE REVIEW

**Comment by Abirami31** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@abirami-vina wow great Abirami, thanks!!

**Comment by glenn-jocher** [comment]
@abirami-vina ah I just realized, we use a fixed discord URL at https://ultralytics.com/discord

**Comment by glenn-jocher** [comment]
@abirami-vina a few edits here. We want to have consistent spacing horizontally in code blocks, i.e. zero spaces to the left, and vertically, leaving a space between code blocks and subsequent sections:

Screenshot 2023-10-04 at 16 57 47


Also we want consistent spacing in bullet/numbered lists (i.e. no spacing between elements like this):

- element 1
- element 2 with no space above or below
- element 3

**Comment by glenn-jocher** [comment]
@abirami-vina ah also for code blocks we want to do this:

```python
# Capitalize the first letter in a single-line code block with no code
x = 1  # lowercase the first letter when following code, and leave 2 spaces between code and comment

# Space above a single-line code block
y = 2 # some more comments
```

**Comment by glenn-jocher** [comment]
@abirami-vina note that many reformatters will do this for you. I use PyCharm reformat for READMEs and it works really well usually, but sometimes distorts the header section so I might select a section of my README file and then right-click and reformat. 

@RizwanMunawar good guidelines for docs/readmes/python formatting above :)

Screenshot 2023-10-04 at 17 04 19

**Comment by abirami-vina** [comment]
@glenn-jocher Thanks for the feedback! Great tips.

**Comment by glenn-jocher** [comment]
@abirami-vina you're welcome! I'm glad you found the tips helpful. If you have any more questions or encounter any issues while using YOLOv8, feel free to reach out. We're here to help. Happy detecting!

**Comment by glenn-jocher** [comment]
@abirami-vina changes look good, thanks!

**Comment by glenn-jocher** [comment]
@abirami-vina ok I've renamed to `yolo-common-issues` as recommended and added this docs page to mkdocs.yaml, where it's required to appear so that it shows in the published docs at https://docs.ultralytics.com. 

The YAML controls where the page appears, i.e. in what section etc.

**Comment by glenn-jocher** [comment]
@abirami-vina PR merged! Thank you for your contributions :)

**Pull request merged**
