### PR TITLE
Drop detections when nothing is tracked

### LINKED ISSUE #18315: Why Is the ID Missing in YOLOv11 Track TXT Files for Some Frames?
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello, I’m using YOLOv11 track feature to perform object tracking on a video and have set the save_txt=True parameter to save a TXT file for each frame. The expected format of the TXT file is [class] [x] [y] [w] [h] [id].
However, I noticed that in some frames, the generated TXT files only contain [class] [x] [y] [w] [h], and the id is missing. For other frames, everything works as expected, and each object is assigned an id.
Why does this happen, and what could be causing the id to be missing for certain frames? Any advice on how to debug or resolve this issue would be greatly appreciated.
For example, these two files: 21_30.txt and 21_31.txt
21_30.txt:
0 0.946493 0.393301 0.104344 0.0629925  
0 0.721501 0.292641 0.115405 0.0704058  
0 0.942954 0.248823 0.109893 0.0924631  
0 0.337594 0.28835 0.101674 0.0606051  
0 0.0629521 0.064694 0.125904 0.129388  
0 0.827286 0.462139 0.0459956 0.0285849  
0 0.0509619 0.303548 0.0988755 0.0668622  
0 0.772194 0.393046 0.0893066 0.0493231  
0 0.656966 0.465885 0.051681 0.0288903  
0 0.577296 0.502542 0.0495499 0.0296198  
0 0.737739 0.479306 0.0480726 0.0280851  
0 0.477201 0.391466 0.0779877 0.045223  
0 0.0187292 0.412359 0.0374583 0.0291709  
0 0.673812 0.49655 0.0530659 0.0317406  
0 0.172896 0.711939 0.0390737 0.0262861  
0 0.810739 0.445399 0.0455166 0.0252178  

21_31.txt:
0 0.808836 0.458968 0.0472189 0.0293597 203  

Similarly, 21_29.txt has the same format as 21_31.txt, with the last column being the id.
I don't understand why the id column is missing in frame 30 (21_30.txt).

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Y-T-G**
Avoids scenario as in https://github.com/ultralytics/ultralytics/issues/14667#issuecomment-2259014432 by dropping all detections when nothing is tracked as opposed keeping all detections.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improves the handling of tracking results when no tracks are found.

### 📊 Key Changes
- Updated `track.py` to handle cases when no tracking results are available by assigning an empty list to `predictor.results[i]`.

### 🎯 Purpose & Impact
- **Improved Stability**: Ensures the program does not encounter errors or unexpected behavior when no tracks are detected.
- **Enhanced User Experience**: Provides more robust and predictable performance, especially in scenarios where no objects are being tracked.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Y-T-G is this doing anything? Isn't this just selecting all tracks?
```
tracks = tracks[:, :-1]
```

**Comment by Laughing-q** [comment]
@Y-T-G  Hey thanks for the PR! But in my opinion this change doesn't fix the issue. :)

**Comment by Y-T-G** [comment]
@Laughing-q I think it removes the erratic behavior where detections suddenly disappear once something is tracked, and suddenly reappears when nothing is tracked. With this PR, the detections correspond with tracking.

No tracks = No returned detections

vs.

No tracks = Return all detections

**Comment by glenn-jocher** [comment]
@Laughing-q what's the final recommendation here? Approve, change or close? 

Thanks!

**Comment by Laughing-q** [comment]
@glenn-jocher @Y-T-G Let's close it since the original issue had been solved. 
I think it'd better to return all the predictions instead of eliminating them when there's no available tracks, leave the choice to users. I think there're users who want these predictions, and if some users don't want these predictions when no tracks they could ignore/eliminate them by manipulating the results we return.

**Pull request closed without merging**
