### PR TITLE
fix OBB train bug

### PR DESCRIPTION
**Pull request by shanglianlm0525**
The cv2.minAreaRect() function returns the rotation angle θ, which is the counterclockwise rotation from the x-axis to the first encountered edge of the rectangle. The length of this edge is w, and the length of the other edge is h. Thus, the range of θ is (0,90]. Therefore, when training an Oriented Bounding Box (OBB) detection model, a rectangle that was originally horizontal will be transformed into a vertical rectangle. As a result, the model ultimately learns a vertical rectangle. In OBB training, it is necessary to ensure that the handling of angles is consistent with the model's expectations to prevent the model from learning the wrong direction of the box.

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Fixes rotation angle issue for bounding boxes when using OpenCV.

### 📊 Key Changes
- Adjusts bounding box angle from 90 degrees to 0 degrees.
- Swaps width and height if the angle is corrected.

### 🎯 Purpose & Impact
- Ensures accurate bounding box representation by correcting rotation errors. 🛠️
- Improves the reliability of object detection, especially for augmented images. 📈

### CODE REVIEW

**Comment by Laughing-q** [comment]
@shanglianlm0525 Hi thanks for the PR! I guess we already have a function [regularize_boxes](https://github.com/ultralytics/ultralytics/blob/17477066ec2fd61d08652a22897e23d2040ff3e6/ultralytics/utils/ops.py#L768C1-L783C71) to do the same thing and we already have it in our predict inference to regularize the angle to [0, 90] range.
Also I remember I actually tried to regularize the boxes during training but it didn't work out and got lower mAP so I removed it from training. :) https://github.com/ultralytics/ultralytics/blob/17477066ec2fd61d08652a22897e23d2040ff3e6/ultralytics/models/yolo/obb/predict.py#L48

**Comment by shanglianlm0525** [comment]
It is possible, but performance may vary across different datasets. This is the result from training on my own dataset. The first one is the original, and the second one is the modified version.  
————————————————
 # train: no regularize cv2.minAreaRect
all       2000       6000          1          1      0.995      0.555
————————————————
# train: regularize cv2.minAreaRect
all       2000       6000          1          1      0.995      0.995
————————————————

**Comment by glenn-jocher** [comment]
@ambitious-octopus greetings failing here. Honestly we can just completely replace greetings action with an Ultralytics Action step. Let's do that instead and then we can delete greetings.yaml completely

**Comment by Y-T-G** [comment]
PaddleRS also does something similar.

https://github.com/PaddlePaddle/PaddleRS/blob/f62b46fd7fffc7429565c69f7ee4b0984efe64f2/paddlers/transforms/rbox_utils.py#L67


Also relevant issue: https://github.com/ultralytics/ultralytics/issues/15771

**Pull request closed without merging**
