### PR TITLE
`ultralytics 8.0.135` remove deprecated `v5loader`

### PR DESCRIPTION
**Pull request by glenn-jocher**
### Summary
:sparkles::wastebasket::memo:

This pull request adds new features and documentation for automatic dataset splitting, thread-safe locking, and CPU information, and removes the deprecated `v5loader` module and related arguments and options from the `ultralytics` package. The changes affect several files in the `ultralytics/yolo` and `ultralytics/datasets` subpackages, as well as the `docs`, `examples`, and `tests` directories. The pull request also updates the version number of the package to `8.0.135`.

> _The `ultralytics` team made some changes_
> _To improve their YOLOv8 ranges_
> _They added `autosplit`_
> _And removed `v5loader` bit by bit_
> _And updated their docs and their pages_

### Walkthrough
*  Increment the version number of the `ultralytics` package for the new release ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-b6202fa6738a34b56894dce00b24b8a4e4d7f4b1cbf1b04db6860f6b0f9635ceL3-R3))
*  Add the `autosplit` function to the `ultralytics.yolo.data.utils` module to split a dataset into train/val/test splits automatically and save the results into text files ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58R7), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-15f6dd1ea95b187a5b50c885f567bad50d006f1af1180508497a038247e9df58R526-R557))
*  Document the `autosplit` function in the `docs/reference/yolo/data/utils.md` file ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-d62f97761eee4f944ecd28f8195034c7a634695440840f12069a47498756fa36R70-R74))
*  Update the import statement of the `autosplit` function in the `ultralytics/datasets/xView.yaml` file to use the new location ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-946a4a9e1971b6c4cd5dbc9d91053d645d66b9d4d49d5a8eff024f1e5e44adf4L90-R90))
*  Remove the deprecated `v5loader` argument and module from the `ultralytics.yolo` package and its dependencies ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L247-R247), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L9-R10), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L31-R31), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02L10-R11), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02L189-R190), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-daf1714127b012666c9fed39d0e75184c60be83f0c6bd3f9863f27113b1a6c22L78-R78), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-9d692d4ad15d420a92105fcd432fb1d2221b71d5af055bea3bd2b70523ce6743L113-L115), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-882061b431ed3670f5b4a045ae0f4e1f140cc785db77fe77585b820bdec6f73dL68), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-f429d422678471556d2c2ed608ff74357ae0afb34eba388e30d1c3c300c93b19), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-b5a36704c9e89c800d5421ca686eb95f5ea807a89b52f290593c45333d634806))
*  Update the output of the `yolo/engine/trainer` in the `examples/tutorial.ipynb` notebook to reflect the changes in the arguments and options of the trainer class ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-628f2a1367635512a2709420a09de67583ea73f4c37dc2312d5eac23f1d71294L303-R303))
*  Add the `ThreadingLocked` class to the `ultralytics.yolo.utils` module to provide a thread-safe lock for a given object ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-1390055d0d26724bbf80e4737445158a6b99df7879391e8dc89db26268edd04fR21-R25))
*  Document the `ThreadingLocked` class in the `docs/reference/yolo/utils/__init__.md` file ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-1390055d0d26724bbf80e4737445158a6b99df7879391e8dc89db26268edd04fR21-R25))
*  Add the `get_cpu_info` function to the `ultralytics.yolo.utils.torch_utils` module to return the CPU information such as model, cores, and frequency ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-27b3a4eb60620c63d39142f6b0be707fc7aca5ccc3a13faf54d90a05db596014R26-R30))
*  Document the `get_cpu_info` function in the `docs/reference/yolo/utils/torch_utils.md` file ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-27b3a4eb60620c63d39142f6b0be707fc7aca5ccc3a13faf54d90a05db596014R26-R30))
*  Modify the `DetectionTrainer` and `DetectionValidator` classes in the `ultralytics/yolo/v8/detect/train.py` and `ultralytics/yolo/v8/detect/val.py` files to add new arguments such as `overlap_mask`, `mask_ratio`, and `dropout` and remove the reference to the `v5loader` argument in the docstring ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L20-R20), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L31-R31), [link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02L189-R190))
*  Remove the documentation pages for the `v5augmentations` and `v5loader` modules from the `mkdocs.yml` file ([link](https://github.com/ultralytics/ultralytics/pull/3744/files?diff=unified&w=0#diff-98d0f806abc9af24e6a7c545d3d77e8f9ad57643e27211d7a7b896113e420ed2L308-L309))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactor of Ultralytics YOLO data loaders and augmentation modules.

### 📊 Key Changes
- Deleted `v5augmentations.md` and `v5loader.md` documentation.
- Removed `v5loader=False` option from configs, as it's deprecated.
- Deleted `v5augmentations.py` and `v5loader.py` files.
- `autosplit()` function moved from `v5loader.py` to `utils.py`.
- Updated training and validation scripts to remove checks for `v5loader`.
- Implemented some loader and augmentation functionalities directly in training scripts.

### 🎯 Purpose & Impact
- 🧹 Cleanup: Removed deprecated YOLOv5 data loaders, simplifying the codebase.
- ✨ Improvements: Ensured latest loading and augmentation practices are used.
- 📝 Better documentation: Moved autosplit to a more semantically correct module (`utils.py`).
- ⚙️ Efficiency: Streamlined training/validation by integrating functionalities directly into scripts.
- 🤖 User and Developer Experience: Simplified setup and configuration by eliminating outdated options.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel I know you did some work with deprecated classes before. This is a config arg we are removing, i.e. after this PR if someone tries yolo train `v5loader=True` they'll get an error. Did you create a class/function to handle this or should I just leave as is?

**Comment by glenn-jocher** [comment]
The default handling seems to work fine also:

Screenshot 2023-07-15 at 01 02 40

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q with v5loader and autoshape both removed this reduces codebase by about -2000 lines :)

**Comment by AyushExel** [comment]
@glenn-jocher I think handle it in a deprication.py file with 
{feature: depricated_since} map. 
And the error should say 'feature x' is deprecated since 'version' so that users atleast know which version they can switch to. 
Now that pip usage has skyrocketed we need to follow some rules probably 😂

**Comment by glenn-jocher** [comment]
> @glenn-jocher I think handle it in a deprication.py file with {feature: depricated_since} map. And the error should say 'feature x' is deprecated since 'version' so that users atleast know which version they can switch to. Now that pip usage has skyrocketed we need to follow some rules probably 😂

Yeah I think you're right. Ok I'll merge this now so @Laughing-q can start refactoring tomorrow, and then I'll come up with a nice comprehensive deprecation solution in the next release that will better handle this new missing `v5loader` argument.

**Comment by nadinator** [comment]
I get an AttributeError when I try to use the autosplit function. I'm installing the lastest ultralytics with pip. Any idea what could be happening?

**Comment by glenn-jocher** [comment]
@nadinator hello,

Thank you for reaching out.

The `autosplit` function was introduced in `ultralytics` version `8.0.135`. Can you please confirm if you are using this version or a later one? 

You can check the version of `ultralytics` you have installed with the following command: `pip show ultralytics`.

If you're not on `8.0.135` or later, you can update `ultralytics` with the following command: `pip install --upgrade ultralytics`.

We hope this helps! Let us know if you have any other questions.

Best regards,
Your ultralytics team

**Comment by nadinator** [comment]
Hi Glenn, thanks for your reply. I'm using ultralytics version 8.0.23, which is why I'm confused.

**Comment by glenn-jocher** [comment]
@nadinator Thanks for your response. I see that you are using ultralytics version 8.0.23. The `autosplit` function was actually introduced in a later version of the package, specifically in version 8.0.135. It appears that you might need to upgrade your installed version to use this feature. Please consider upgrading your `ultralytics` package to the latest version. You can use pip's upgrade command to do this. I hope this clarifies the confusion.

**Pull request merged**
