### PR TITLE
Sort Triton model outputs

### PR DESCRIPTION
**Pull request by dustydust**
I have read the CLA Document and I sign the CLA

Sort model outputs that we get from triton_client.get_model_config method

https://github.com/ultralytics/ultralytics/issues/5922

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improving output sorting and model attribute definitions in the Triton helper class.

### 📊 Key Changes
- Added alphabetical sorting to Triton model outputs.
- Grouped model attribute definitions to enhance code organization.
- Maintained class functionalities for `InferRequestedOutput` and `InferInput`.

### 🎯 Purpose & Impact
- Ensuring a consistent order of outputs helps in reducing confusion when dealing with multiple outputs, which benefits users when they parse inference results.
- Code reorganization makes it easier for developers to read and maintain the code.
- The change is internal and should not affect users' existing code, but it sets the stage for more reliable and maintainable codebase in the future.🛠️🔄

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@dustydust thanks for the PR! Model outputs are already sorted by confidence.

**Comment by glenn-jocher** [comment]
@dustydust ah nevermind, this is the list of output tensors you are sorting. Ok let me see.

**Comment by glenn-jocher** [comment]
@dustydust so this change resolves your segment model inference issues and does not affect detect model inference?

**Comment by dustydust** [comment]
@glenn-jocher detect inference works. But this PR is the first part to let segment model inference works, the second part is coming, and I need you advice

We have an argument `self.model.names` here -> https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/segment/predict.py#L35 that points to list of model classes names. That list we read from local .onnx model file. If we use triton as a service that list is empty and triton doesn't provide an answer with class names

So we can: 
1) Remove this list and rewrite part of the method `non_max_suppression`
2) Provide this list from user

How would it be better and more comfortable?

**Comment by glenn-jocher** [comment]
@dustydust got it. All Ultralytics exported models including ONNX have metadata embedded inside them, including class names:

Screenshot 2023-10-26 at 19 42 17


Please write a quick message here with the following text to make the CLA bot happy:

I have read the CLA Document and I sign the CLA

**Comment by dustydust** [comment]
I have read the CLA Document and I sign the CLA

**Comment by dustydust** [comment]
@glenn-jocher give me some time, I'll try to get names from triton once again

**Comment by dustydust** [comment]
@glenn-jocher that's right, I've the same outputs order in my .onnx models.
But https://github.com/ultralytics/ultralytics/blob/main/ultralytics/utils/triton.py#L50 returns a reversed order of list 'output'

**Comment by glenn-jocher** [comment]
@dustydust ok got it! I've updated it a bit and merged into our upcoming 8.0.202 branch that should be published in a bit.

**Comment by dustydust** [comment]
@glenn-jocher thank you! Just in case I remind you about the second part of segmentation bug https://github.com/ultralytics/ultralytics/pull/5952#issuecomment-1781524248

**Comment by glenn-jocher** [comment]
@dustydust right, got it. The only reason we need the names is to figure out where the masks outputs start for segmentation, so i.e. for COCO the output would be:

4 box points + 80 classes + 32 masks

We need to know that there are 80 classes, otherwise, i.e. maybe there are 70 classes and 42 masks. In reality though unless a model is customized there will always be 32 segmentation masks. 

Oh actually I just realized, we can detect the number of masks directly from the second output, which will be of shape 1,32,160,60. This is really interesting, then we could use that info instead of the class count.

**Pull request merged**
