### PR TITLE
Add more tracking args for solutions

### LINKED ISSUE #17684: Dynamic parameters for object counter
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

how customize tracking parameters in object counter?

### Additional

hi
How can I customize tracking parameters or other parameters for counter object? I am working on project where I need to count  objects in roi with multiple rtsp-streams in real-time. The stream dropping out after some minutes and no option to name window name or other attributes in function count.

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher Hi, following [the user's request](https://github.com/orgs/ultralytics/discussions/8112#discussioncomment-11414558), I have added support for additional arguments in the tracking functionality. However, these arguments are not necessary for the object counting module. Thank you 😊

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Enhanced tracking functionality with advanced configuration options for improved flexibility and customization. 🚀  

### 📊 Key Changes  
- Added `track_add_args` to store additional tracking configuration parameters like `verbose`, `iou`, `conf`, `device`, and more. 🛠️  
- Updated tracking methods to utilize `track_add_args` for more customizable behavior during object tracking.  

### 🎯 Purpose & Impact  
- **Improved Customization**: Gives users greater control over tracking parameters, enabling adjustments for diverse use cases. 🎯  
- **Enhanced Flexibility**: Makes it easier to fine-tune object tracking, benefiting developers working with varied models, data, or environments. 🌐  
- **User Efficiency**: Reduces the need for hardcoding or manual adjustments, streamlining workflows. ⏱️  

This update increases the tool's adaptability and makes it more user-centric.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting an `ultralytics/ultralytics` 🚀 pull request! This is an automated response to help streamline the review process. An Ultralytics engineer will review and assist you soon. Meanwhile, please ensure the following checklist is completed to simplify the integration of your valuable contributions:

- ✅ **Define a Purpose**: Ensure your PR description clearly explains the purpose of your changes. You've done a great job linking [the user's request](https://github.com/orgs/ultralytics/discussions/8112#discussioncomment-11414558) and explaining the purpose of your additions! 🎉
- ✅ **Synchronize with Source**: Confirm your branch is up-to-date with the `ultralytics/ultralytics` `main` branch. Use the 'Update branch' button or run `git pull` and `git merge main` locally, if needed.
- ✅ **Ensure CI Checks Pass**: Verify that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) tests are successful. Please address any failing checks before proceeding.
- ✅ **Update Documentation**: If applicable, ensure relevant [documentation](https://docs.ultralytics.com) is updated to reflect these changes. Especially for newly introduced configurable parameters like `track_add_args`.
- ✅ **Add Tests**: Consider adding tests to verify the new tracking arguments work as intended. This will help maintain reliability and prevent regressions. 👍 
- ✅ **Sign the CLA**: If this is your first contribution, please ensure you have signed our [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/). Add a comment in your PR saying, "I have read the CLA Document and I sign the CLA."
- ✅ **Minimize Changes**: Ensure that only necessary changes are included in your PR. This makes it easier to review and test the update. Your changes look focused and well-thought-out so far! 🚀

For more information and contribution guidelines, please visit our [Contributing Guide](https://docs.ultralytics.com/help/contributing). 🤓 

Thank you for enhancing the tracking capabilities and making Ultralytics even more user-friendly! We appreciate your work on this flexible and powerful new feature. If you have any questions or need further clarification, feel free to leave a comment below. 🌟 

Happy coding!

**Comment by Y-T-G** [comment]
In my opinion, it should consume all the passed arguments in the constructor as needed by the object and the remaining should be assumed as being part of the `track` parameters and passed to the `track` method. That way pretty much all parameters of the `track` method can be accommodated.

**Comment by RizwanMunawar** [comment]
@Y-T-G You're right—good catch! This PR is designed to address that issue as well. Specifically, these five track-related arguments will now be included:

```"verbose", "iou", "conf", "device", "max_det", "half"```

Previously, we only had the `source`, `persist`, and `classes` arguments available. Based on my understanding, these are the major arguments that the track supports, but If you think any other argument can also be a part of that, please feel free to update this PR :)

**Comment by Y-T-G** [comment]
I think `tracker` should also be included.

**Comment by RizwanMunawar** [comment]
@Y-T-G Ok I have added the `tracker` argument as well! Thanks :)

@glenn-jocher, I think this PR is good to merge now. Thanks!

**Comment by glenn-jocher** [comment]
@RizwanMunawar @Y-T-G PR merged!

**Pull request merged**
