### PR TITLE
`lapx` package replacement for `lap`

### PR DESCRIPTION
**Pull request by glenn-jocher**
Regarding https://github.com/rathaROG/lapx/issues/1#issuecomment-1606336123

### Summary
🆕🐛🚀

Updated `matching.py` to use lapx instead of lap for linear assignment problems. This improves performance and simplifies installation.

> _`lapx` replaces `lap`_
> _Faster and easier to install_
> _No cython needed_

### Walkthrough
*  Switch to lapx package for linear assignment problems ([link](https://github.com/ultralytics/ultralytics/pull/3383/files?diff=unified&w=0#diff-c0f31e0ae934e7ee2136442e0bcee33fb63c71365c39f1fd339c69e2101b3bc1L16-R16))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to Python 3.11 and use lapx package for object tracking

### 📊 Key Changes
- 🐍 Changed CI workflow to test against Python 3.11 instead of Python 3.10.
- 📦 Transitioned to using the `lapx` package version `0.5.2` or higher for linear assignment in object tracking.

### 🎯 Purpose & Impact
- 🔍 The update in Python version for CI tests ensures compatibility with the latest Python release, future-proofing the project.
- 🚀 The switch to `lapx` for object matching seeks to provide a more reliable dependency source and potentially improve tracking performance or maintainability.
- ✅ Users might see improved stability and support, while developers can test their contributions against the latest Python environment.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@rathaROG ok I've tested lapx and it seems to work well on all 3 operating systems! Please make sure you're careful with future releases as this PR will cause the `ultralytics` package to install the latest version of `lapx` if tracking is attempted and `import lap` fails. Thanks!

**Comment by rathaROG** [comment]
> @rathaROG ok I've tested lapx and it seems to work well on all 3 operating systems! Please make sure you're careful with future releases as this PR will cause the `ultralytics` package to install the latest version of `lapx` if tracking is attempted and `import lap` fails. Thanks!

You're welcome and don't worry I'll disable my CI for PyPI until I'm sure any new version is safe to publish.

**Comment by glenn-jocher** [comment]
@rathaROG thank you for your contribution! We appreciate that you took the time to test `lapx` and confirm that it works well on different operating systems. We also appreciate your attention to future releases and ensuring that the installation of `lapx` is safe. It's great to see our community working together to improve the `ultralytics` package and make it more efficient for everyone. Thank you again for your work!

**Comment by rathaROG** [comment]
> @rathaROG thank you for your contribution! We appreciate that you took the time to test `lapx` and confirm that it works well on different operating systems. We also appreciate your attention to future releases and ensuring that the installation of `lapx` is safe. It's great to see our community working together to improve the `ultralytics` package and make it more efficient for everyone. Thank you again for your work!

Hi @glenn-jocher , I just want to let you know that the new `lapx` [v0.5.3](https://github.com/rathaROG/lapx/releases/tag/v0.5.3) has pretty much all native wheels on PyPI. Maybe `Utralytics` can completely replace `lap` with `lapx`?

Check PyPI -> https://pypi.org/project/lapx/#files

Tested on latest Linux Mint 21.2

image

Tested on WSL Ubuntu

image

Tested on native Windows 11

image

**Comment by glenn-jocher** [comment]
Hello @rathaROG,

Thank you for sharing the updates about `lapx` v0.5.3 and for providing the test results on different systems. The Ultralytics team is always open to improvements that can help make the package more efficient.

We're glad to hear that the latest `lapx` version includes all native wheels on PyPI. This improvement could indeed simplify the installation process and make it more efficient, which is important for many users of the YOLOv8 model.

Thank you again for your contribution! The Ultralytics team will certainly look into your suggestion. The YOLO community relies on active contributors like you who put in vital effort to ensure that the package and related projects continue to enhance. We will evaluate the compatibility of `lapx` v0.5.3 with our existing YOLOv8 package and, if it aligns well, consider incorporating it fully into our platform. 

As always, we appreciate your diligent testing and feedback. It helps us deliver a better experience for everyone who uses our projects. Please continue to share your observations and suggestions — you're helping make the technology better for all of us.

**Comment by rathaROG** [comment]
> Hello @rathaROG,
> 
> Thank you for sharing the updates about `lapx` v0.5.3 and for providing the test results on different systems. The Ultralytics team is always open to improvements that can help make the package more efficient.
> 
> We're glad to hear that the latest `lapx` version includes all native wheels on PyPI. This improvement could indeed simplify the installation process and make it more efficient, which is important for many users of the YOLOv8 model.
> 
> Thank you again for your contribution! The Ultralytics team will certainly look into your suggestion. The YOLO community relies on active contributors like you who put in vital effort to ensure that the package and related projects continue to enhance. We will evaluate the compatibility of `lapx` v0.5.3 with our existing YOLOv8 package and, if it aligns well, consider incorporating it fully into our platform.
> 
> As always, we appreciate your diligent testing and feedback. It helps us deliver a better experience for everyone who uses our projects. Please continue to share your observations and suggestions — you're helping make the technology better for all of us.

Thanks for the consideration. By the way, maybe the original `lap` authors come back in the future to update and improve their `lap` which is a good thing, and you can switch back to `lap`, but I will try my best the keep `lapx` in sync with any important future updates from `lap`.

**Comment by glenn-jocher** [comment]
Hello @rathaROG,

We truly appreciate your dedication and efforts towards maintaining `lapx` and keeping it updated. Whether we end up using `lap` or `lapx`, it's good to know that there are dedicated contributors like you who ensure that the libraries we use are constantly updated and improved. It provides a sense of reliability for us and the YOLOv8 community at large.

Your willingness to sync `lapx` with any future important updates from `lap` is highly commendable. These constant improvements contribute to the overall robustness of our package and the broader machine learning community.

Thank you once again for your commitment to improving `lapx`, contributing towards YOLOv8, and supporting our shared goal of making technology better.

Best Regards,
Ultralytics Team

**Comment by rathaROG** [comment]
Hello @glenn-jocher , 

I just want to let you know that the current `lapx==0.5.7` has all pre-built wheels for almost all OS platforms including ARM 64 for Windows and Linux. I suggest bumping to his version. Thanks! 

Bests,

image

**Comment by glenn-jocher** [comment]
@rathaROG hello there! 🎉

Thanks for the heads-up on `lapx==0.5.7` and its comprehensive platform support! That's great news 🚀. We'll definitely look into upgrading to this version to ensure better compatibility and ease of installation for our users. Your efforts to keep the library so well-maintained are truly appreciated!

Cheers!

**Comment by Laughing-q** [comment]
@rathaROG THanks for the headsup! I've submitted a PR to revert to `lap`. https://github.com/ultralytics/ultralytics/pull/17908

**Comment by rathaROG** [comment]
> @rathaROG THanks for the headsup! I've submitted a PR to revert to `lap`. #17908

@Laughing-q You're welcome! 

By the way, I know it isn't a problem, but the version of lap after the merged is `v0.5.12`, the code should be changed as well:

```python
    check_requirements("lap>=0.5.12")  # https://github.com/gatagat/lap
```

**Pull request merged**
