### PR TITLE
Revert `lapx` to `lap`

### PR DESCRIPTION
**Pull request by Laughing-q**
@glenn-jocher FYI https://github.com/ultralytics/ultralytics/pull/3383#issuecomment-2509804890

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Updated a package dependency in the tracker utility to ensure compatibility and stability. 🚀

### 📊 Key Changes  
- Modified the `requirements` check to use the `lap` package (version `>=0.5.12`) instead of `lapx`.  

### 🎯 Purpose & Impact  
- 🔧 Ensures better maintenance and compatibility by switching from `lapx` to the more commonly used `lap` package.  
- 🤝 Improves stability for users relying on tracking functionalities by aligning with industry-standard dependencies.  
- 🌟 Simplifies dependency management since `lap` is well-documented and widely supported.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Laughing-q, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

---

### Quick Notes on Your PR

Updating the dependency from `lapx` to `lap` to streamline the package requirement is a useful adjustment. Please ensure the following:
1. 💡 Confirm that all references to the `lapx` package are updated across the repository if necessary to avoid inconsistencies.
2. ✅ Double-check if related tests (if any) need adjustments to accommodate this change in dependency.

This is an automated response 🤖 to help speed up the review process, but rest assured, an Ultralytics engineer will also assist you soon. Thank you for your contribution and patience! 🌟

**Comment by glenn-jocher** [comment]
@Laughing-q before I switched from lap to lapx due to dependency and install issues in some environments, see https://github.com/ultralytics/ultralytics/pull/3383. 

Do you think this good to switch back now?

**Comment by glenn-jocher** [comment]
I checked https://piptrends.com/compare/lap-vs-lapx and lapx has more downloads these days, but it may be mostly because of us. Both only have `numpy` as their single dependency.

BTW I tried to eliminate lap/lapx last year by moving these computations to numpy/torch but was unable to, though I think it may be possible in principle.

**Comment by Laughing-q** [comment]
@glenn-jocher Yes I think probably we could directly switch back the `lap` now as currently `lapx` has been merged into the official `lap` and also `lapx` repo is archived and no longer maintained. https://github.com/rathaROG/lapx
About the install issues we encountered on the original `lap` package is because it didn't have pre-built python wheel so we needed to git clone the package locally and compile the implementation through c++, but now they have pre-built wheels and support various python versions. Also I checked the dependency there's only [numpy](https://github.com/gatagat/lap/blob/fcd28693c6623636419a352c01cf930278231a05/setup.py#L91).
pic-241204-1123-33

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@Laughing-q got it, sounds good! Merging PR.

**Pull request merged**
