### PR TITLE
`ultralytics 8.1.41` DDP resume untrained-checkpoint fix

### LINKED ISSUE #9329: Changing device with resume
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

How can I change the devices for multiple gpu training with resume??

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #9419: size mismatch error when finetuning a model with multiprocessing
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Train

### Bug

Using 8.1.27

I train a model from yolov8s.pt --> model1.pt. THEN,
I want to train a new model from model1.pt, but with a different number of classes

This works fine if using device="cpu" or device=0

When using multi-gpu, I get the following error before training begins:
```
optimizer: AdamW(lr=0.000714, momentum=0.9) with parameter groups 57 weight(decay=0.0), 64 weight(decay=0.0005), 63 bias(decay=0.0)
Traceback (most recent call last):
  File "/home/david/.config/Ultralytics/DDP/_temp_h9a53u9r139976720501584.py", line 12, in <module>
    results = trainer.train()
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 213, in train
    self._do_train(world_size)
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 327, in _do_train
    self._setup_train(world_size)
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 319, in _setup_train
    self.resume_training(ckpt)
  File "/home/david/ultralytics/ultralytics/engine/trainer.py", line 669, in resume_training
    self.ema.ema.load_state_dict(ckpt["ema"].float().state_dict())  # EMA
  File "/opt/conda/envs/bumlo/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for DetectionModel:
	size mismatch for model.22.cv3.0.2.weight: copying a param with shape torch.Size([9, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([11, 128, 1, 1]).
	size mismatch for model.22.cv3.0.2.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([11]).
	size mismatch for model.22.cv3.1.2.weight: copying a param with shape torch.Size([9, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([11, 128, 1, 1]).
	size mismatch for model.22.cv3.1.2.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([11]).
	size mismatch for model.22.cv3.2.2.weight: copying a param with shape torch.Size([9, 128, 1, 1]) from checkpoint, the shape in current model is torch.Size([11, 128, 1, 1]).
	size mismatch for model.22.cv3.2.2.bias: copying a param with shape torch.Size([9]) from checkpoint, the shape in current model is torch.Size([11]).
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21516 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21517 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 21518 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 21515) of binary: /opt/conda/envs/bumlo/bin/python3.10
```

The full command I used for training looks like this:
```
yolo detect train  model=/path/to/pretrained-model/weights/best.pt data=/path/to/my_yaml.yaml epochs=100 batch=16 imgsz=1184 device=0,1,2,3 seed=0 patience=0
```

### Environment

Ultralytics YOLOv8.1.27 🚀 Python-3.10.12 torch-1.13.1+cu117 CUDA:0 (Tesla T4, 14910MiB)
Setup complete ✅ (16 CPUs, 102.3 GB RAM, 210.8/393.5 GB disk)

OS                  Linux-4.19.0-25-cloud-amd64-x86_64-with-glibc2.28
Environment         Linux
Python              3.10.12
Install             git
RAM                 102.29 GB
CPU                 Intel Xeon 2.30GHz
CUDA                11.7

matplotlib          ✅ 3.6.3>=3.3.0
opencv-python       ✅ 4.8.1.78>=4.6.0
pillow              ✅ 9.5.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.3>=1.4.1
torch               ✅ 1.13.1+cu117>=1.8.0
torchvision         ✅ 0.14.1+cu117>=0.9.0
tqdm                ✅ 4.64.1>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 1.5.3>=1.1.4
seaborn             ✅ 0.13.0>=0.11.0

### Minimal Reproducible Example

```
yolo detect train  model=yolov8s.pt data=/path/to/first_yaml.yaml epochs=100 batch=16 imgsz=1184 device=0,1,2,3 seed=0 patience=0
```
```
yolo detect train  model=/path/to/pretrained-model/weights/best.pt data=/path/to/next_yaml.yaml epochs=100 batch=16 imgsz=1184 device=0,1,2,3 seed=0 patience=0
```

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
May resolve #9419 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the training process with improved fault tolerance and customization options. 🚀

### 📊 Key Changes
- Specified "backend" explicitly in distributed training setup.
- Added a condition to resume training only if `self.resume` is true, allowing more control over training resumption.
- Expanded argument updates for resuming training with reduced memory usage, adding "device" to "imgsz" and "batch".
- Simplified assertions and logging related to resuming training, making the process more straightforward and less error-prone.

### 🎯 Purpose & Impact
- **Better Fault Tolerance:** By enforcing a timeout in distributed training setups and allowing more flexible memory usage adjustments, the changes aim to reduce crash instances due to network issues or CUDA out-of-memory (OOM) errors. 🛡️
- **Enhanced Customization:** The addition of "device" to adjustable parameters when resuming training provides users more control over their training environment, potentially mitigating memory constraints. 🔧
- **Streamlined Training Resume Process:** These updates make resuming training more intuitive by removing unnecessary checks and clarifying logging messages. This leads to a smoother experience for users restarting training sessions. 🔄

In summary, these changes make the training process more robust, customizable, and user-friendly, particularly in distributed environments or when resuming after interruption.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved training resumption logic and package update checks in Ultralytics YOLO 🚀!

### 📊 Key Changes
- 🔼 Updated the version to 8.1.41.
- 🌐 Enhanced Distributed Data Parallel (DDP) setup by specifying the backend directly.
- 🔄 Improved the training resume feature to better handle model, device, and memory configurations.
- ⏭ Added robustness to auto-updating dependencies by allowing retries.
- 🛠 Fixed optimizer to properly handle non-float32 tensors in conversion for mixed precision training.

### 🎯 Purpose & Impact
- **Version Bump:** Keeps users on the latest, most stable release. 🆕
- **DDP Setup:** Ensures more reliable multi-GPU training by explicitly setting the backend, potentially improving performance and reducing bugs. ✔️
- **Resuming Training:** Makes it easier for users to pause and resume their training processes, even on different devices or with adjusted memory parameters, preventing loss of progress and improving user experience. 💾
- **Dependency Updates:** Increases the success rate of automatic dependency updates, reducing setup time and improving user experience. ⬆️
- **Optimizer Tweak:** Ensures more stable and accurate training in mixed precision, enhancing performance and reducing memory usage. 🚀

Together, these changes aim to enhance the usability, stability, and flexibility of Ultralytics YOLO, making advanced computer vision more accessible and efficient.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q I'm trying to solve a DDP training bug when starting from a partially completed checkpoint from a different dataset (with different class counts) in https://github.com/ultralytics/ultralytics/issues/9419 but I'm having a problem. 

This PR fixes the bug report, but it breaks DDP resume. I can't figure how to do both.

- To test the PR train COCO8, crash training after a few epochs, and try to train VOC.yaml DDP from the partially trained COCO8 model.
- To test DDP resume, just train COCO8 DDP, crash then resume it.

Both should work correctly but I can't figure it out right now.

**Comment by glenn-jocher** [comment]
@Laughing-q this PR also resolves #9329, user asking to change device on resume.

**Comment by Laughing-q** [comment]
@glenn-jocher ok found the reason. Let me check what's the best solution here.

**Comment by Laughing-q** [comment]
@glenn-jocher DDP resuming broken is because `self.args.resume` is set to `False` when loading args from last checkpoint:
https://github.com/ultralytics/ultralytics/blob/ea527507fecb72cbdb1881dbd8d46c246efce90b/ultralytics/engine/trainer.py#L650
`resume` int the `overrides` we read from trainer when generating ddp script hence remains `False`.https://github.com/ultralytics/ultralytics/blob/ea527507fecb72cbdb1881dbd8d46c246efce90b/ultralytics/utils/dist.py#L31
And this PR added an explicit condition to launch `resume_training` only if `self.args.resume` is explicitly set, then the DDP resuming broken.
Fixed in https://github.com/ultralytics/ultralytics/pull/9453/commits/97a247849e2d20eb39e3792cbf6cdbc88359366f

**Comment by glenn-jocher** [comment]
@Laughing-q I'm seeing a strange error when resuming. Resume works correctly, but then I get an error I've never seen before after a few successful resume epochs:

`RuntimeError: Tensors of the same index must be on the same device and the same dtype except `step` tensors that can be CPU and float32 notwithstanding`

Screenshot 2024-04-01 at 13 19 34


To reproduce on the server:

```
yolo train device=6,7
# CTRL+C after 10 epochs
yolo train device=6,7 model=/usr/src/ultralytics/runs/detect/train/weights/last.pt resume
```

**Comment by glenn-jocher** [comment]
@Laughing-q ok I think I fixed this in https://github.com/ultralytics/ultralytics/pull/9453/commits/c8523ead0a69ceb7d01cb227732849f3e1e04fd9

The `step` keys in the optimizer will stay as FP32 and now resume works fully. The step keys are very lightweight so will not increase checkpoint size.

Screenshot 2024-04-01 at 13 26 30

**Comment by glenn-jocher** [comment]
@Laughing-q merging this PR as 8.1.41 to get these fixes out while we figure out the LR-resume bug some more.

**Pull request merged**
