### PR TITLE
New JupyterLab Dockerfile

### PR DESCRIPTION
**Pull request by ambitious-octopus**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduced a new Docker image for Ultralytics YOLO with JupyterLab support, enhancing interactive development and usability.

### 📊 Key Changes
- Added a new JupyterLab Dockerfile (`Dockerfile-jupyter`) to build and run a Docker image with JupyterLab pre-installed.
- Updated the GitHub Actions workflow to build and push this new Docker image tagged as `latest-jupyter`.

### 🎯 Purpose & Impact
- **Interactive Development**: Users can now utilize JupyterLab for a more interactive development experience with YOLO, complete with tutorial notebooks. 📚
- **Enhanced Usability**: Facilitates an easier setup for data science workflows by allowing persistent data storage and seamless integration of Jupyter notebooks. 🚀
- **Broader Accessibility**: Simplifies getting started with YOLO for users who prefer a graphical interface and interactive coding environment. 🌍

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @ambitious-octopus, thank you for submitting a PR to the `ultralytics/ultralytics` 🚀 repository! This is an automated response to ensure a smooth review process, and an Ultralytics engineer will be in touch soon to provide further assistance. Please review the checklist below to maximize the efficiency of your contribution:

- ✅ **Define a Purpose**: Clearly outline the purpose of your PR in the description, linking to any relevant [issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear and align with project conventions.
- ✅ **Synchronize with Source**: Confirm your PR is up-to-date with the `main` branch of the repository. If necessary, update your branch by clicking the 'Update branch' button or running `git pull` and `git merge main`.
- ✅ **Ensure CI Checks Pass**: Verify that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. Please address any issues if the checks do not pass.
- ✅ **Update Documentation**: Update the [documentation](https://docs.ultralytics.com) to reflect any changes associated with new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to accommodate your changes, and ensure all tests are successful.
- ✅ **Sign the CLA**: If this is your first PR to Ultralytics, please sign the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by stating "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Ensure that your PR is limited to the essential changes necessary for introducing your feature or fix. _"It is not daily increase but daily decrease, hack away the unessential." — Bruce Lee_

Your addition of the new `Dockerfile-jupyter` and the updates to the GitHub Actions workflow are exciting enhancements, offering users greater flexibility with JupyterLab-based workflows. 🚀

For additional information, please refer to the project's [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to leave a comment if you have any questions. Thanks again for your valuable contribution to Ultralytics! 😊

**Comment by glenn-jocher** [comment]
@ambitious-octopus ah for images that depend on other base images there's a special process. Right now this occurs here for GitHub runner images that are built from -latest:

https://github.com/ultralytics/ultralytics/blob/654ed14935ad0929dd73cb97dc50b682777d4084/.github/workflows/docker.yaml#L178-L182

Can you update this PR to build these images only after their base images are done? Otherwise the new images will be based off of older images.

**Review by ambitious-octopus — COMMENTED** [review]
@glenn-jocher My fault I didn't think it was a parallel job. I fixed it, now the image is built and pushed only after Dockerfile-python.

**Comment by glenn-jocher** [comment]
@ambitious-octopus no, that's not how it works. Your change here will cause duplicated images to be built. All images are built by a single step, this is a github runner matrix. A single if statement in the step is all you need to build followon base images.

There is already an example that pointed you to before for the github runner images, please follow that. No additional steps or jobs are required.

**Review by ambitious-octopus — COMMENTED** [review]
I have little experience with github workflows, but this seems correct to me. Instead of using another step like as for therunner, here the idea is to use a separate step.
This way when it fails we know exactly at which step it failed. Also if the previous step fails we do not risk pushing old containers. In this case these two new steps run only when the image they depend on has been built and pushed:

```
matrix.dockerfile == 'Dockerfile-python'
```

@glenn-jocher Am I wrong?

**Comment by glenn-jocher** [comment]
@ambitious-octopus no, we want to push this using `runner` as an example. Please review the runner code. 

I mean just look at how many Docker image we are publishing (9) without any "extra" or "special" steps for each one. The code is very clean and concise, why would we add 2 extra steps for 1 more (the 10th) format when we haven't added any extra special steps for the first 9 formats?

**Comment by glenn-jocher** [comment]
@ambitious-octopus I've finally just done this myself in https://github.com/ultralytics/ultralytics/pull/17071/commits/7c9e7b464c7b63a3705793e57431e9097950d9ad

**Comment by glenn-jocher** [comment]
@ambitious-octopus after fixing your Action this PR is still not ready to merge because your Dockerfile is not standardized to the other 9. Please review the existing work and make yours match the existing 9 files. There are so many examples here for you to follow that you've completely ignored, i.e. add a license header, context, comments, etc. 

**Please have standard in your work and pay attention to detail**, this level is not acceptable.

Screenshot 2024-11-03 at 00 49 13

**Review by glenn-jocher — CHANGES_REQUESTED** [review]
This PR does not uphold the standards of commenting and following existing examples that are expected.

**Pull request merged**
