### PR TITLE
`ultralytics 8.0.56` PyTorch 2.0 support and minor fixes

### LINKED ISSUE #246: training on Apple M1 chip using Metal Performance Shaders (MPS) float64 issue
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

error when training with apple m1 MPS, due to MPS framework doesn't support float64. in train.py line 168. 
is there any workaround ? 

python3.10/site-packages/ultralytics/yolo/v8/detect/train.py", line 168, in __call__
    targets = self.preprocess(targets.to(self.device), batch_size, scale_tensor=imgsz[[1, 0, 1, 0]])
TypeError: Cannot convert a MPS Tensor to float64 dtype as the MPS framework doesn't support float64. Please use float32 instead.

### Environment

- Ultralytics YOLOv8.0.3 🚀 Python-3.10.0 torch-2.0.0.dev20230107 MPS
- Apple MacBook Pro M1
- Metal Performance Shaders (MPS) 

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements in CI workflows, package installation, new model addition, and environment setup.

### 📊 Key Changes
- 🔁 Expanded CI triggers to run on `updates` branch pushes.
- 🚀 Improved GitHub Actions benchmark summaries for better log visibility.
- 🛠️ Fixed package installations to be more consistent without using `-e '.[export]'`.
- 💻 Dropped unnecessary social platform logos and replaced others with new platform logos (e.g. TikTok).
- 🤖 Incorporated a new YOLOv8 model configuration file for object detection (`yolov8-p2.yaml`).
- 🔢 Introduced a static method to reset IDs in the tracking code.
- 📁 Added support for custom configuration directories via the `YOLO_CONFIG_DIR` environment variable.
- 📉 Addressed a potential performance bottleneck in dataset loading.
- 🖼️ Streamlined image result plotting to support optional confidence display and added ID to annotations.
- 🏗️ Enhanced environment checks for display capabilities and added support for the new `is_kaggle` check.
- ✅ Enabled the previously commented out functionality to save txt prediction results.
- ⚙️ Solved an issue with incorrect tensor dtype during segmentation training.

### 🎯 Purpose & Impact
- 🚀 Improves the continuous integration workflow, making development and testing more robust.
- 🌐 Changes to package installation ensure more uniform reproducibility across different user setups.
- ✨ Addition of a new YOLO model configuration could lead to better or more efficient object detection for users.
- ✔️ Tracking ID reset allows for more accurate and controlled tracking sessions when using object tracking features.
- 🖥️ Users can now specify a custom directory for storing `yolov8` configurations, which increases flexibility.
- 🧹 General cleanup of the social links in readme files could make the repository appear more organized and updated.
- 📊 Enhanced plotting functions lead to better visualization of predictions, which is helpful for end users analyzing detection results.
- 🔄 Additional checks ensure that image display functions will work correctly in various environments, avoiding crashes on platforms where display is not supported.
- 📝 The ability to save txt prediction results provides users with a necessary tool for downstream tasks, such as benchmarking or further analysis.
- 🐍 Python environment optimizations and bug fixes improve the overall stability and performance of `yolov8`.

### CODE REVIEW

**Comment by nikbobo** [comment]
Does it support using PyTorch 2.0 compiled model to speed up?

**Comment by glenn-jocher** [comment]
@N-Friederich I can confirm MPS inference is working in this PR! Initial result is slower, and NMS is slower, but for same image sizes like webcam/video, the speedup boost is significant.

```bash
yolo predict device=mps
WARNING ⚠️ 'model' is missing. Using default 'model=yolov8n.pt'.
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.0.56 🚀 Python-3.10.6 torch-2.0.0 MPS
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

image 1/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 381.9ms
image 2/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_4ch.png: 640x480 4 persons, 1 bus, 1 stop sign, 19.6ms
image 3/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus_greyscale.jpg: 640x480 3 persons, 1 bus, 16.7ms
image 4/4 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 384x640 2 persons, 1 tie, 367.9ms
Speed: 5.3ms preprocess, 196.5ms inference, 23.1ms postprocess per image at shape (1, 3, 640, 640)

```

**Comment by glenn-jocher** [comment]
> Does it support using PyTorch 2.0 compiled model to speed up?

@N-Friederich is working on this but it seems we are running into problems. On my Macbook M2 I'm unable to compile and train without errors (unrelated to the export errors).

**Comment by glenn-jocher** [comment]
@N-Friederich got it. Maybe I just have some environment issues. This PR definitely works, but torch.compile() won't work for me. It looks like the compile PR is also having issues that I don't understand.

**Pull request merged**
