### PR TITLE
Adjust box labels on right image side

### PR DESCRIPTION
**Pull request by jackwolfey**
related issue, see https://github.com/ultralytics/yolov5/issues/13118#issue-2365811181

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improves the alignment and readability of annotated labels in images by enhancing text padding and boundary checks.

### 📊 Key Changes
- Improved label positioning to ensure text does not overflow the image boundary.
- Added extra padding to the text for better readability.
- Updated condition checks for label placement outside the bounding box.

### 🎯 Purpose & Impact
- 🖼️ **Enhanced Readability**: Labels on images are now clearer and easier to read.
- 🔍 **Better Placement**: Prevents annotated text from extending outside the image, ensuring all information remains visible.
- 📏 **Consistency**: Applies consistent padding across different drawing libraries (PIL and cv2), enhancing the overall appearance of annotations.

These changes allow users to generate more professional and legible visual outputs.

### CODE REVIEW

**Comment by jackwolfey** [comment]
Quick examples showing what I'm doing in this PR.

xQEaiq7OVF
fOzCFi3pCt

**Comment by jackwolfey** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@jackwolfey PR merged! Thank you for your contributions!

**Comment by drcular** [comment]
rhe merged code has some mistakes
box_label_isuuse
we can fix it like this
image

**Comment by glenn-jocher** [comment]
Thank you for pointing out the issue with the merged code and providing a visual example. Your feedback is invaluable in ensuring the quality and accuracy of our codebase.

To address this effectively, could you please provide a minimal reproducible example that demonstrates the issue? This will help us understand the context better and ensure that the fix is comprehensive. You can refer to our guide on creating a reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest version of the packages, as updates may contain important fixes and improvements.

Looking forward to your example so we can resolve this promptly! 😊

**Pull request merged**
