### PR TITLE
Update exporter.py

### PR DESCRIPTION
**Pull request by john-rocky**
Changed coreml export extension to a working format. From ".mlmodel" to ".mlpackage".

reason:
If we leave it as .mlmodel, the following error message will appear because the pipeline model with nms added cannot be converted. "Exception: For an ML Program, extension must be .mlpackage (not .mlmodel)"

The .mlpackage format works fine.

Updated export.py to save Core ML models in the new .mlpackage format for better compatibility and flexibility.

mlpackage format
more flexible and compatible
cutting edge for Core ML

Walkthrough
Change the file extension for saving the Core ML model to .mlpackage to support the new format in Core ML Tools 5.0

### Summary
📦🔐🚀

Changed the file extension for Core ML export from `.mlmodel` to `.mlpackage` to support the new Core ML Package format. This allows for more advanced features and capabilities of Core ML for the YOLOv5 model.

> _`YOLOv5` exports_
> _Core ML Package for new features_
> _Cutting edge in fall_

### Walkthrough
*  Changed the file extension for Core ML Package export from `.mlmodel` to `.mlpackage` to support new features and capabilities of Core ML Package ([link](https://github.com/ultralytics/ultralytics/pull/2882/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdL390-R390))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR appears to be empty – no code changes were found.

### 📊 Key Changes
- No changes have been made to the codebase in this PR.

### 🎯 Purpose & Impact
- Since there are no changes, there is no direct impact on the users.
- It's possible this PR was opened by mistake or for administrative purposes.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@john-rocky if you want to propose this change you must modify this everywhere it is used. 

You've made  change to a single line but this format is in place in very many lines throughout the repository. I'd suggest doing a search and replace at the bare minimum.

Screenshot 2023-05-29 at 01 50 50
Screenshot 2023-05-29 at 01 50 56

**Comment by john-rocky** [comment]
change ".mlmodel" to ".mlpackage" in description of exporter.py.

**Comment by Kayzwer** [comment]
@john-rocky you need to sign the CLA by posting a new comment with content "I have read the CLA Document and I sign the CLA"

**Comment by john-rocky** [comment]
@Kayzwer Thank you.
"I have read the CLA Document and I sign the CLA"

**Comment by john-rocky** [comment]
"I have read the CLA Document and I sign the CLA"

**Comment by john-rocky** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@john-rocky hi there! Thank you for signing the CLA and for your interest in our YOLOv8 repo. How can we help you today? If you have any issues or questions regarding the YOLOv8 repository, please feel free to let us know and we'll do our best to assist you.

**Comment by john-rocky** [comment]
The current export.py cannot create a coreml pipeline model containing nms. Change the extension.

**Comment by john-rocky** [comment]
@glenn-jocher 

The current export.py cannot create a coreml pipeline model containing nms. Change the extension.

**Comment by glenn-jocher** [comment]
@john-rocky hello! Thank you for bringing this to our attention. We appreciate your feedback and are constantly working to improve our repository. 

Regarding your concern about the current export.py, it seems that the extension being used for Core ML export is causing issues when creating a pipeline model with NMS. One potential solution to this issue could be to change the file extension for Core ML export from ".mlmodel" to ".mlpackage". 

By changing the file extension to ".mlpackage", you can create a Core ML Package format which is more flexible and compatible and also cutting edge for Core ML. This updated export.py should then be able to save Core ML models in the new .mlpackage format for better compatibility and flexibility.

I hope this helps! Let us know if you have any further concerns or issues and we'll do our best to assist you.

**Comment by john-rocky** [comment]
@glenn-jocher 
I created a pull request with the extension changed to mlpackage.

**Comment by glenn-jocher** [comment]
@john-rocky thank you for submitting your pull request with the updated extension. We appreciate your contribution to the YOLOv8 repository. Our team will review your changes and provide feedback as soon as possible. 

In the meantime, if you have any other questions or concerns about YOLOv8, please feel free to reach out to us. Thank you again for your contribution to our project.

**Comment by glenn-jocher** [comment]
@john-rocky merged into https://github.com/ultralytics/ultralytics/pull/4043 for adoption of *.mlpackage standard. Thank you for your contributions!

**Comment by glenn-jocher** [comment]
@john-rocky @Kayzwer great news 😃! Your original issue may now be resolved ✅ in PR #4043 and published in `ultralytics 8.0.150`. This PR introduces support for Apple's new *.mlpackage export format. Usage remains the same and now exports CoreML models in the new format:

```bash
yolo export model=yolov8n.pt format=coreml  # produces yolov8n.mlpackage
yolo export model=yolov8n.pt format=mlmodel  # produces legacy yolov8n.mlmodel
```

To get this update:
- **[Git](https://github.com/ultralytics/ultralytics)** – Run `git pull` from within your `ultralytics/` directory or run `git clone https://github.com/ultralytics/ultralytics` again
- **[Pip](https://pypi.org/project/ultralytics/)** – Update with `pip install -U ultralytics`
- **[Notebooks](https://github.com/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb)** – Check out the updated notebooks  <a href="https://console.paperspace.com/github/ultralytics/ultralytics">Run on Gradient</a> <a href="https://colab.research.google.com/github/ultralytics/ultralytics/blob/main/examples/tutorial.ipynb">Open In Colab</a> <a href="https://www.kaggle.com/ultralytics/yolov8">Open In Kaggle</a>
- **[Docker](https://hub.docker.com/r/ultralytics/ultralytics)** – Run `sudo docker pull ultralytics/ultralytics:latest` to update your image <a href="https://hub.docker.com/r/ultralytics/ultralytics">Docker Pulls</a>

Thank you for spotting this issue and letting us know. Please confirm if this update fixes the issue for you, and don't hesitate to report any other **issues** you find or **feature requests** you may have. Happy training with YOLOv8 🚀!

**Pull request merged**
