### PR TITLE
New Docs Guide: Isolating Segmentation Objects

### PR DESCRIPTION
**Pull request by Burhan-Q**
# Guide

A walk through on how to extract isolated objects from prediction results. Inspired by questions from Discord community.

## Notes

- built and tested locally
- added to `guides/index.md` and included in `mkdocs.yaml/nav`
- animated GIF image currently hosted on branch
- locally building docs site required media beneath the guide to load (unclear as to why), so new directory added: `guides/media/seg-obj` for images
    - please let me know if this should be relocated elsewhere
- included breakdown of each step to include explanations and add length, realistically could _only_ include full code sample from end

## Preview

Intro image (see animation below)
image

animation

Included internal links to other Docs pages in Annotations
image

Image examples included for reference showing results of various steps
image

### Summary
📝🎨🌐

This pull request adds a new guide to the documentation that explains how to use Ultralytics segmentation to isolate objects from images. The pull request creates a new markdown file `docs/en/guides/segmented-object-isolation.md` for the guide content, adds a reference to the file in `docs/en/guides/index.md`, and updates the `docs/mkdocs.yml` file to include the guide in the navigation menu.

> _New guide for `nav`_
> _Segmented objects isolation_
> _A winter recipe_

### Walkthrough
* Add a new guide on segmented objects isolation to the documentation ([link](https://github.com/ultralytics/ultralytics/pull/6587/files?diff=unified&w=0#diff-885e47f194963a4be186adea4f0139764b27fec93b6eb9dae7b0e302dc09eaa2R29), [link](https://github.com/ultralytics/ultralytics/pull/6587/files?diff=unified&w=0#diff-8df923355a6ea8478e6781d1ce46b4e93b3944c683d13a0b7a4a5bfee46f39cfL1-R318), [link](https://github.com/ultralytics/ultralytics/pull/6587/files?diff=unified&w=0#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfR267))
  * Create a new markdown file `docs/en/guides/segmented-object-isolation.md` with the title, metadata, and content of the guide ([link](https://github.com/ultralytics/ultralytics/pull/6587/files?diff=unified&w=0#diff-8df923355a6ea8478e6781d1ce46b4e93b3944c683d13a0b7a4a5bfee46f39cfL1-R318))
  * Include the guide in the documentation index `docs/en/guides/index.md` under the segmentation task section ([link](https://github.com/ultralytics/ultralytics/pull/6587/files?diff=unified&w=0#diff-885e47f194963a4be186adea4f0139764b27fec93b6eb9dae7b0e302dc09eaa2R29))
  * Update the mkdocs configuration file `docs/mkdocs.yml` to add the guide to the navigation menu ([link](https://github.com/ultralytics/ultralytics/pull/6587/files?diff=unified&w=0#diff-7618337a88ea47f9b778a21f0e17d43eab2aba4880c6be2d95a7bf95e4b8b2dfR267))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
New guide on isolating segmented objects using Ultralytics.

### 📊 Key Changes
- 📝 Added a comprehensive guide titled "Isolating Segmentation Objects".
- 🖼️ Included instructions and example images showing how to extract objects from segmentation results.
- 🧠 Provided example code snippets for various image processing steps such as creating binary masks and isolating objects with black or transparent backgrounds.

### 🎯 Purpose & Impact
- 🎓 Educates users on advanced image processing techniques post-segmentation to enhance the utility of their segmentation models.
- 🌐 Expands the documentation to support developers in implementing custom workflows involving segmentation with Ultralytics.
- 🖥️ Gives non-expert users clear examples and explanations to facilitate a better understanding of instance segmentation output handling.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q awesome, nice guide!!

Looks like you've just got a few typos to clear up in the pre-commit action. PyCharm works really well to highlight typos automatically, it's pretty useful for me, here's an example:

Screenshot 2023-11-26 at 13 34 27

**Comment by Burhan-Q** [comment]
I'll get these cleared up. I got a little cut short on my time to work on this yesterday but wanted to open up the PR in case other changes were needed. I'll definitely get those typos fixed and push a commit today.

**Comment by glenn-jocher** [comment]
@Burhan-Q ok awesome! The spelling action is pretty useful, but it doesn't auto-update potential mispellings the way the linting actions do with auto-updating the code, so we have to either go in and resolve these manually or add them to the ignore file/word lists in the precommit cfg file.

**Comment by Burhan-Q** [comment]
@glenn-jocher typos corrected and did some gen-AI rephrasing edits, should be good to go unless there's anything else you'd like changed/fixed.

**Comment by glenn-jocher** [comment]
@Burhan-Q got it, thanks! Just one more typo is failing CI, I can fix that.

**Comment by Burhan-Q** [comment]
🤦‍♂️

**Comment by Burhan-Q** [comment]
# Compressed images
bus-crop-iso_person-1
bus-crop-iso_person-1-NO_BG
bus-full-iso_person-1
bus-full-iso_person-1-NO_BG
bus-mask_person-1

**Comment by glenn-jocher** [comment]
@Burhan-Q woohoo awesome!!!

**Pull request merged**
