### PR TITLE
Fix YOLOv10 dictionary Predict output

### PR DESCRIPTION
**Pull request by qianyue76**
A small fix when predict with PyTorch model the prediction is a dict.
[issue13587](https://github.com/ultralytics/ultralytics/issues/13587)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved handling of model prediction formats in the `non_max_suppression` function.

### 📊 Key Changes
- 🛠️ Added a check to convert prediction output from dictionary format to a tensor format expected by `non_max_suppression`.

### 🎯 Purpose & Impact
- 💡 **Purpose:** Ensure compatibility with different model output formats, specifically handling outputs from YOLOv8.
- 🚀 **Impact:** Increases robustness and flexibility, enabling smoother processing of various model outputs for developers and ensuring consistent performance.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary 
Enhancement to handle diverse prediction outputs in non-max suppression.

### 📊 Key Changes
- Added support for dictionary-based predictions (`one2many`, `one2one`).
- Improved handling for predictions provided as lists or tuples.

### 🎯 Purpose & Impact
- 🧠 **Flexibility**: Adapts to different output formats from models, enhancing compatibility.
- 🚀 **Efficiency**: Streamlines processing by selecting appropriate prediction data. 
- 📈 **User Benefit**: Reduces potential errors and improves model output handling.

### CODE REVIEW

**Comment by qianyue76** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@Laughing-q @Burhan-Q does this dict output occur in our latest YOLOv10 branch?

**Comment by Laughing-q** [comment]
@glenn-jocher nope I don't think so

**Comment by glenn-jocher** [comment]
@Laughing-q yes got it!

@qianyue76 I think the dict output is only enabled during training and validation, with the NMS function selecting the first index when there is a list or tuple, so no dict should be passed here. 

If you are experiencing issues please submit a minimum reproducible example, thank you!

**Comment by Laughing-q** [comment]
@qianyue76 @glenn-jocher Closing this since it's no longer needed! Thanks!

**Pull request closed without merging**
