### PR TITLE
Add YOLOv11-P2/P6 and YOLOv10n-P2/P6 Configuration Files

### LINKED ISSUE #16548: can we have a v11 p2 yaml file soon?
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

hello,
Great to see a new yolo version 11 in ultralytics family.
We see also a P2 yaml file soon;
thank you

### Additional

_No response_

### LINKED ISSUE #16844: Are there no P6 variants of Yolo-11?
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Why are there no P6 variants of the newer Yolo versions? The extra layer really helped us with big objects. But we would of course like to also use all the new features of yolo 9/10/11.

Is there a way to add the P6 layer to yolo-11?

### Additional

_No response_

### LINKED ISSUE #17081: Yolo11 small object detection
When in Yolov8, there is a Yolov8-p2 to enhance small object detection. Is there a similar version in Yolo11? If not how should I enhance it on small objects?

### PR DESCRIPTION
**Pull request by WangQvQ**
**PR Content:**
This pull request introduces two new configuration files for the YOLO project: `yolo11-P2/P6. yaml` and `yolo10n-P2/P6.yaml`.  These files provide pre-configured settings optimized for specific use cases.

I noticed some users asking about these YAML files in the issues, and since I've implemented them, feel free to use them if needed.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
New YOLOv11 and YOLOv10 versions with enhanced detection models (P2-P6 heads) were added, improving object detection capabilities with scalable configurations. 🚀

### 📊 Key Changes
- Added **YOLOv11-P2** and **YOLOv11-P6** model configurations with detailed architectures for improved detection across scales (P2-P5, P3-P6 respectively).
- Added **YOLOv10n-P2** and **YOLOv10n-P6** model configurations, optimizing YOLOv10 for smaller and efficient models (P2-P5, P3-P6 respectively).
- Introduced a new **`v11Detect`** head for YOLOv11, leveraging depth-wise and point-wise convolutions for enhanced detection performance.
- Integrated the new `v11Detect` head with other modules and architecture parsing workflows.

### 🎯 Purpose & Impact
- **Purpose**: Expand YOLO model offerings to cater to diverse use cases, from small-scale lightweight detection (YOLOv10n) to higher-resolution, multi-scale scenarios (YOLOv11).
- **Impact**:
  - **Enhanced Model Scalability**: Models scale better for different hardware and precision requirements.
  - **Improved Detection Performance**: The models' outputs now span different resolutions (P2-P6), improving accuracy in detecting objects of varying sizes. 📏
  - **Broader Applicability**: Provides users with more specialized YOLO versions to match specific detection tasks, from fast inference to detailed accuracy.

These updates are a significant upgrade, tailoring the YOLO family for even more real-world use cases! 🌍✨

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @WangQvQ, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response, and an Ultralytics engineer will assist you soon. In the meantime, please review the following checklist to ensure a smooth integration:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

Your additions of the `yolo11-p2.yaml` and `yolov10n-p2.yaml` config files look promising for enhancing object detection capabilities! 🎉

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

**Comment by LemonGraZ** [comment]
This is very nice!

**Comment by glenn-jocher** [comment]
@LemonGraZ thank you! The credit goes to the YOLO community and the Ultralytics team for their hard work. If you have any questions or need assistance, feel free to ask!

**Comment by Skillnoob** [comment]
@Laughing-q can you take a look at this?

**Comment by Egorundel** [comment]
Thank you for your hard work, but how can your P6 configuration be used in training?

Do I understand correctly that I need to change the file `train.py` as follows:
```python
model = YOLO("yolo11-p6.yaml").load("yolo11m.pt")
```

Or is it necessary in some other way?

**Comment by Egorundel** [comment]
@Skillnoob So with such a yaml structure, I can only upload it, and pre-workout weights won't help here?

So my code should look like this?
`model = YOLO("yolo11m-p6.yaml")`

**Comment by Egorundel** [comment]
@Skillnoob I have this output in the console at the beginning of the training.

Screenshot from 2025-01-14 08-39-47

**Comment by Skillnoob** [comment]
> @Skillnoob So with such a yaml structure, I can only upload it, and pretrained weights won't help here?
> 
> So my code should look like this?
> `model = YOLO("yolo11m-p6.yaml")`

Yes

**Comment by Y-T-G** [comment]
@WangQvQ You can open a PR in this repo for your custom configs.

https://github.com/Y-T-G/community

**Pull request closed without merging**
