### PR TITLE
Multi-head support for predict

### PR DESCRIPTION
**Pull request by Haodong-Lei-Ray**
多头detect预测输出，将输出可以适应lhd专门修改的融合head输出。

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the YOLO detection prediction process to handle multiple output heads more effectively.

### 📊 Key Changes
- Introduced handling for predictions with multiple output heads by checking the type of predictions and processing accordingly.
- Added logic to aggregate and adjust predictions from different heads, ensuring that results are combined correctly.
- Integrated the `torch` library, providing additional functionalities for prediction processing.

### 🎯 Purpose & Impact
- **Improved Prediction Handling**: Ensures that the YOLO model can handle complex prediction outputs efficiently, especially important for models with multiple output heads.
- **Better Performance and Flexibility**: Allows users to employ models with diverse architectures without needing additional adjustments, thus broadening the usability of the YOLO framework.
- **Potential User Benefits**: Users can expect more accurate and reliable predictions when using models with multiple heads, supporting a wider range of applications and enhancing model performance across diverse datasets.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@870572761 thank you for the PR! The update to `predict.py` for multi-head detection output is a great addition. It's good to see support for lhd-specific fusion head outputs being considered. 👍

Just to clarify, the changes will allow the `postprocess` function to handle outputs from models with multiple heads, and we've made sure that NMS can process these predictions effectively. Also, it's now possible to input images directly as `torch.Tensor`, which is super convenient!

If anyone needs to use this new feature, here's a quick example of how you might adjust your code:

```python
from ultralytics import YOLO

# Load your multi-head model
model = YOLO('path/to/your/multi-head-model.pt')

# Predict with a tensor input
tensor_img = torch.rand(1, 3, 640, 640)  # Example tensor
results = model.predict(tensor_img)
```

This should make the YOLO models even more versatile for various applications. Keep the feedback coming! 🚀

**Comment by 870572761** [comment]
> **CLA Assistant Lite bot:** Thank you for your submission, we really appreciate it. Like many open-source projects, we ask that you all sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA) before we can accept your contribution. You can sign the CLA by just posting a Pull Request Comment same as the below format.
> 
> I have read the CLA Document and I sign the CLA
> 
> **1** out of **2** committers have signed the CLA.✅ (UltralyticsAssistant)[https://github.com/UltralyticsAssistant]❌ @870572761You can retrigger this bot by commenting **recheck** in this Pull Request

It is my graduation project，I do not if you merge my project what will happen. So I will check it after I had graduated.

**Comment by 870572761** [comment]
> @870572761谢谢你的PR！更新到`predict.py`的多头检测输出是一个很好的补充。很高兴看到对lhd特定融合头输出的支持正在考虑中。👍
> 
> 澄清一下，这些更改将允许`postprocess`函数处理来自多个头的模型的输出，并且我们已经确保NMS可以有效地处理这些预测。此外，现在可以直接输入图像作为`torch.Tensor`，这是超级方便！
> 
> 如果有人需要使用这个新功能，这里有一个关于如何调整代码的快速示例：
> 
> ```python
> 来自ultralyticsimportYOLO
> 
> #加载您的多头模型
> model=YOLO（'path/to/your/multi-head-model.pt'）
> 
> #使用张量输入进行预测
> tensor_img=torch. 兰德（1，3，640，640）#张量示例
> 结果=模型。predict（tensor_img）
> ```
> 
> 这将使YOLO模型在各种应用中更加通用。保持反馈！🚀

So is it available in main branch? Or after I had pulled request it will be available?

**Comment by glenn-jocher** [comment]
Yes, the enhancements for multi-head detection output in `predict.py` will be available in the main branch once your pull request is merged. Before that happens, you can continue using and testing your changes locally or in your own fork of the repository. 😊

If you need to use these updates immediately in your projects, consider pulling from your branch or applying the changes manually to your local copy. Here's a quick way to do it if you're using Git:

```bash
git checkout -b multi-head-detection your-branch-name
```

This approach allows you to benefit from the new features right away. Once your contribution is merged, it'll be part of the official release, making it accessible to everyone. Thanks for contributing! 🌟

**Review by ambitious-octopus — COMMENTED** [review]
Hey @870572761, thanks for the PR. We don't have any official models that support multihead inference at the moment, so I think this feature is superfluous. Maybe we can consider this example in the future. Thanks again for the support.

**Pull request closed without merging**
