### PR TITLE
fix: fixes string escapes in tflite export for yolo

### LINKED ISSUE #3850: yolo tflite export fails for folders containing whitespace
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

when exporting yolo to tflite on windows for a filepath that contains spaces the export fails. 

### Environment

Yolo: ultralytics 8.0.138
OS: Windows 

### Minimal Reproducible Example

````python
"""
minimal reproduction of yolo export failure
"""
import pathlib
from ultralytics import YOLO


def main():
    # for this to work you need to dump a yolo training result in the evil temp folder
    evil_path = pathlib.Path("D:/temp evil")
    best_models = list(evil_path.rglob("best.pt"))
    print(f"found models to convert: {best_models}")
    for model in best_models:
        print(f"converting model {str(model)}")
        model = YOLO(str(model))
        model.export(format="tflite")


if __name__ == "__main__":
    main()

````

### Additional

This fix would not be important normally, but unfortunately, MS decided in its infinite wisdom that Onedrives synced folders for Windows must have spaces in them, if you have both a company/edu and a personal Onedrive folder on your system.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Gornoka**
### Summary
🗂️🛠️🌐

Wrap file paths in double quotes in `cmd` string in `ultralytics/engine/exporter.py`. This improves the ONNX to TensorFlow conversion process by avoiding errors from spaces or special characters in file paths.

> _`f_onnx`, `f` wrapped_
> _in double quotes for safety_
> _winter of errors_

### Walkthrough
*  Wrap file paths in double quotes to avoid errors with spaces or special characters ([link](https://github.com/ultralytics/ultralytics/pull/3851/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL589-R589))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced repository cleanliness and documentation clarity.

### 📊 Key Changes
- Updated `.gitignore` to exclude auto-generated files in the `ultralytics/assets` directory.
- Minor formatting correction in `CONTRIBUTING.md` for better readability.

### 🎯 Purpose & Impact
- 🗑️ Ignoring the `assets` directory helps maintain the repository's cleanliness by preventing unnecessary files from being tracked, which can clutter the codebase and complicate version control.
- 📝 The documentation update ensures consistency and clarity in the guidelines for future contributors, improving the overall quality of the contributions.

### CODE REVIEW

**Comment by Gornoka** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Gornoka** [comment]
addresses #3850

**Comment by Gornoka** [comment]
recheck

**Comment by Gornoka** [comment]
The tf.js  export is still  broken for spaces in filenames but I can not escape it in a way that the export can handle lol, I do have the hardware to run the Edgetpu script right now, so I can not test/ do any changes there. 
The tflite export works great tho.

**Comment by glenn-jocher** [comment]
@Gornoka ah this is a good point. I think `cmd.split()` is used in various places in Exporter. We should probably replace all usages of this with a list of commands instead. Can you do this for all Exporter instances of `cmd.split()`?

**Comment by Gornoka** [comment]
> @Gornoka ah this is a good point. I think `cmd.split()` is used in various places in Exporter. We should probably replace all usages of this with a list of commands instead. Can you do this for all Exporter instances of `cmd.split()`?

I replaced it for the last remaining position ( edgetpu ), however it still has issues with the JS conversion. as far as I understand it now the tfjs conversion script you are using is doing the parsing mistake internally.

**Comment by Gornoka** [comment]
The workaround for tfjs seems to work quite well, this would be the last change on this branch from my side, unless there is anything you deem too broken to merge.

**Comment by Gornoka** [comment]
copilot:all

**Comment by glenn-jocher** [comment]
Thank you for your patience and contributions, @Gornoka. I appreciate your efforts to improve our tfjs exports. It sounds like you've done an excellent job overcoming the challenges encountered. 

As for the remaining issues with the tfjs conversion, it seems we might need to dig deeper into the underlying script to find a viable solution. I'll take some time to review your changes thoroughly before proceeding. 

Thanks again for your work on this. It's through contributions from community members like yourself that we continually improve and expand YOLOv8's capabilities. I'll get back to you after reviewing your changes. Your patience is highly appreciated.

**Pull request merged**
