### PR TITLE
add an option to disable integration callbacks and turn off tqdm when not verbose

### PR DESCRIPTION
**Pull request by Rusteam**
### Summary
🎛️🔌🚀

Added options to control integration callbacks and progress bars in the engine module. Integration callbacks are functions that integrate the engine classes with external services or tools. The `INTEGRATION_CALLBACKS` variable from `ultralytics.utils` can be used to enable or disable these features globally or per class.

> _`INTEGRATION_CALLBACKS` are the chains that bind us_
> _We break them with the power of `YOLO`_
> _We control our destiny with `VERBOSE` and `ultralytics`_
> _We are the masters of the exporter, predictor, trainer and validator_

### Walkthrough
*  Add `INTEGRATION_CALLBACKS` variable to control integration callbacks ([link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL68-R68), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-9fa2bf7f1273283680da3daeb8bae8e20cf8d477f838575796d2bf3b415bc534L41-R41), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL30-R30), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L32-R32), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-067b5aadc258357e37c686a1a9bd895fa0532dbaf436334af483acd57a6b07faR38))
*  Add `VERBOSE` variable to control progress bars ([link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-9fa2bf7f1273283680da3daeb8bae8e20cf8d477f838575796d2bf3b415bc534L41-R41), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL30-R30), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L32-R32))
*  Call `callbacks.add_integration_callbacks` only if `INTEGRATION_CALLBACKS` is True in `Exporter`, `BasePredictor`, `BaseTrainer` and `BaseValidator` classes ([link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-b9f4cf4260fabd8ffb31e9a85b332a63d39fb49829ce1d98d980b2ec3549322cL144-R145), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-9fa2bf7f1273283680da3daeb8bae8e20cf8d477f838575796d2bf3b415bc534L109-R110), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL143-R143), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L122-R123))
*  Add `disable=not VERBOSE` argument to `tqdm` calls in `BaseTrainer` and `BaseValidator` classes ([link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL327-R327), [link](https://github.com/ultralytics/ultralytics/pull/4609/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L162-R163))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduced environment variable control for integration callbacks and verbose logging in various components of Ultralytics software.

### 📊 Key Changes
- Added a new environment variable `INTEGRATION_CALLBACKS` to control the addition of integration callbacks.
- Modified the addition of integration callbacks in `exporter.py`, `predictor.py`, `trainer.py`, and `validator.py` to respect the `INTEGRATION_CALLBACKS` flag.
- Introduced the `VERBOSE` environment variable to toggle tqdm progress bar visibility in `trainer.py` and `validator.py`.

### 🎯 Purpose & Impact
- 🎛️ **Customization**: The `INTEGRATION_CALLBACKS` flag allows users to enable or disable integration callbacks, giving more control over the behavior of their software environment.
- 🔕 **Quieter Output**: The `VERBOSE` flag permits users to reduce output clutter by hiding progress bars if desired, which could be useful in logs or non-interactive scripts.
- 🚀 **User Experience**: These changes empower users and system administrators by providing more options to configure the Ultralytics software behavior to better fit their use case or preferences.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Rusteam you can disable callbacks in settings, i.e. `yolo settings tensorboard=False`. 

See the Settings docs at https://docs.ultralytics.com/quickstart/#ultralytics-settings

Screenshot 2023-08-28 at 14 27 27

**Comment by Rusteam** [comment]
@glenn-jocher thanks I see now. It should work for me. How about disabling tqdm? I'm doing hyper parameter search with ray tune and tqdm logs look messy.

**Comment by glenn-jocher** [comment]
@Rusteam sure, you can disable tqdm logging during your hyperparameter search by updating the `tqdm` parameter in the `train.py` script. If you set it to `False`, the progress bars will not be shown, making your logs appear cleaner. Let me know if you need any further assistance!

**Comment by Rusteam** [comment]
> @Rusteam sure, you can disable tqdm logging during your hyperparameter search by updating the `tqdm` parameter in the `train.py` script. If you set it to `False`, the progress bars will not be shown, making your logs appear cleaner. Let me know if you need any further assistance!

Certainly, thanks. Do you think it's needed for others as well? I can add another env var to disable tqdm

**Comment by glenn-jocher** [comment]
@Rusteam, your suggestion to add an environment variable to control tqdm logging could indeed be a thoughtful enhancement. This would give users more control over their training output without having to modify the script directly. It might be something beneficial for other users who also aim to have cleaner logs. Please feel free to propose this change and we can discuss further on your pull request. Your contribution would be highly appreciated!

**Pull request closed without merging**
