### PR TITLE
Update to lowercase MkDocs admonitions

### PR DESCRIPTION
**Pull request by MatthewNoyce**
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

### 🌟 Summary
This PR updates documentation to standardize the format of section headers across various markdown files.

### 📊 Key Gradient/Color Range. The color key filter takes color from an image or video sequence and replaces it with a solid color or transparency.

Why is my motion effect not working in Premiere?

Each clip in a video production is arranged on a segment of a timeline. Adobe Premiere uses rendering to build previews in order to ensure high playback quality. In some cases, during an editing session, the render files become huge and are not useful anymore.

How do I fix effects in Premiere Pro?

Flicker, unsmooth, or wavey image in Program Monitor when an effect is applied

- Go to Preferences > General.
- Deselect Enable Display Color Management (requires GPU acceleration) If you don’t see the changes, take the cursor and move to another time code in the timeline.

What does ultra key effect do?

The Ultra Key applies these adjustments generally, to the entirely of your video clip. Whether they be Spill Suppression, Matte Generation, or Color Correction. If you want to be more specific about which parts of a clip you want to adjust, you can take advantage of the ability to mask the Ultra Key.

How do I smooth keyframes in Final Cut?

So we're just going to press ctrl and v so now you can see our keyframes. Here we have a keyframe spot right here and we want the speed to go from let's say 400.

Is green screen possible in iMovie?

iMovie makes editing out the green screen simple and quick as it allows you to change the background of your footage in just a few steps.

How do you fix shadow green screen in iMovie?

Create a blank green screen in a video editing app such as iMovie or VideoPad and put it over that dark shadow spot. Then on your original video apply a chroma key effect on the shadow spot.

Why is my green screen not working?

Your camera or mobile phone may not works well because of improper resolution settings. Also, the Microphone of a digital camera may not work well if there is any problems with sound driver. To fix the OBS studio green screen freezing problem, follow these steps: Check the camera and microphone settings.

How do I get rid of green screen on Facetime?

To change the appearance of your video, tap a filter at the bottom (swipe left or right to preview them). To turn off filters, tap , then tap Favorites or Original (depending on your iOS version) to remove the filter. To turn off the filter and return to the FaceTime menu, tap the close button or tap Done.
Jul 12, 2023

How do you use a green screen?

- Have Your Subject Wear a Different Color. …
- Shoot With a Narrow Depth of Field. …
- Set up Some Green Screen Lights. …
- Light the Subject Separately. …
- Use Chroma Key-Specific Lights for the Background.

How do you make a green screen background look natural?

While your green screen is likely distracting while you’re editing, using video editing software can help you easily add a background to your portrait. Ideally, it shouldn’t look Photoshopped, so make sure the lighting looks similar.

How do you use a green screen on a video?

Quote from video: A green screen and then I'm gonna just drop a background behind us now there's two ways to do this you can layer the background. So you can put all your b-roll on top of your regular video.

How do I change my video background?

How to Change Video Background Free: Step 1: Open Media.io and click the Choose Files button to import your video. Step 2: Click on the Start to Remove button to start the process. Hit the Download button to save your video without the background.

How do you add a background on iMovie without green screen?

It shouldn’t look photoshmark (tools, clothes) 
Mercari (clothes 
LetGo 

Can you really make money selling clothes online?

Selling your clothes online can be a great way to earn extra money while you also set yourself up for an exciting future. Come up with a consistent process to find good clothes to sell, post them, monitor them, and ship them out each time they sell.

Is selling clothes online easy?

Most of us have more gently-used clothing in our closets than we think. Thanks to a rising number of online consignment stores, selling those clothes for cash is easier than ever. While eBay and Craigslist have long been go-to places for selling clothes online, there are now many other online consignment shops to consider.

Where can I Sell my vintage clothes online?

You can also sell vintage clothes on eBay if you wish, since interpreters can be found quite easily. If you or your relatives have vintage pieces laying around in the closet, that would be the best place to start. We recommend: Sell My Clothes Online: Using eBay To Turn Old Closets Into New Cash 3. Have “influence”? Get Liquid with “ThredUp”!

What is the best way to sell second-hand clothing?

Using a local route to advertise your second-hand clothing has some noticeable advantages, the main benefit being that you don’t have to worry much about packaging. Some of the best local selling sites for selling clothes online include: OfferUp offers sellers the best of both worlds. It combines the functionality of Craigslist with Facebook.

### CODE REVIEW

**Comment by MatthewNoyce** [comment]
This is a continuation of pull request #15981

**Comment by jk4e** [comment]
Hi guys, I would like to add something to this PR:

This PR will **NOT** ensure consistency across the docs, it will just introduce more! Why?

- `!!! tip`(e.g. docs/en/usage/simple-utilities.md)
- `!!! Tip "Tip"`(e.g. docs/en/modes or docs/en/quickstart.md)
- `!!! Tip`(in the files changed by this PR: docs/en/tasks/)

The same goes for (may find more):
- `!!! warning` or `!!! Warning "Warning"` you can find both in docs
- Then it should be `!!! Quote ""`(as in docs) or `!!! Quote` or `!!! quote`? (same for example with no caption: `!!! Example`, `!!! Example ""` or `!!! example`?)
- ...

You should define a consistent style guide first, and then change all the doc files! Otherwise, this will just introduce more inconsistencies and in my opinion will not make the docs better in any way!

Thanks a lot! 🚀

**Comment by MatthewNoyce** [comment]
Thank you for bringing that up, I didnt realise it was across all sections of the docs. If we get a consistent style then i would be happy to go through and change it all

**Comment by glenn-jocher** [comment]
@jk4e great points! Not sure if the annotations here are case sensitive. 

It looks like they should all be lowercase: https://squidfunk.github.io/mkdocs-material/reference/admonitions/

Hmm.

**Comment by jk4e** [comment]
Thanks @glenn-jocher for the link you provided to get more information on so-called "admonitions" or "call-outs" in Material for MkDocs.

Personally, I would prefer to follow the style guide in those docs, which means that all type qualifiers should be **lowercase**. The Admonition extension is based on [[1](https://python-markdown.github.io/extensions/admonition/)], [[2](https://docutils.sourceforge.io/docs/ref/rst/directives.html#toc-entry-1)]. These all use lowercase throughout. I also did some quick research online that this seems to be the standard. (In general it also seems that these types are case-insensitive (we know because they seem to work in Ultralytics YOLO Docs), but in my opinion going with the style guide in mkdocs is the best approach for consistency and easy maintainability of YOLO Docs).

--> So follow the syntax strictly, form the [references](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) would be the best.

**Note**: For Citations (mostly used in datasets section) in docs I would leave it as it is (change to lowercase of course), i.e. `!!! quote ""` and not change it to `!!! quote`, because the generated heading with `" Quote` seems a bit misleading.


Maybe @glenn-jocher and/or @ambitious-octopus can approve this or add a comment, then @MatthewNoyce can start working on it and make his first merged PR in an Open Source project. 🔥🚀 (if I am right about his GitHub profile stats) 

Thanks guys!

**Comment by MatthewNoyce** [comment]
Yes you are correct about this being the first PR I have opened for an open source community. I used ultralytics all throughout my final dissertation in uni and I thought this would be a good way to help pay back for the help and resources i received. In regards to the PR, I would be more than happy to go through and alter all the pages in the docs to complete my first PR.

**Comment by jk4e** [comment]
@MatthewNoyce A few notes, as this appears to be your first PR or contribution to an open source project on GitHub:

- Here is the [Contributing Guide](https://docs.ultralytics.com/help/contributing/) for this project.
- CLA signing, you only have to do one thing. (You have already signed with your first PR successful)
- Creating a branch in your forked repo is good practice.
- You do not have to close and reopen a new PR for the same issue every time. This can help keep track of progress, information, and comments by having it all in one place. (but you already mentioned the old PR on your second PR, which was good)
- You can clone the forked repo locally and work in your IDE, or use the github.dev web-based editorin browser to save or make changes in more than one file before committing. This avoids a huge list of "micro" commits in the list, which in my opinion is often a mess.
- Online, you can find many resources that will guide and explain to you how to do a PR right, or ask for help from your favorite AI chatbot, their answers are often quite helpful for beginners in this case.

**Everyone started with their first PR on GitHub and was a beginner. You can do it! 🔥🚀**

**Comment by glenn-jocher** [comment]
@MatthewNoyce can you please update this PR to fix all the admonitions similarly (removing the duplicate string when it occurs and making them all lowercase)? You can use search-and-replace to speed this up. 

Thank you!

**Comment by glenn-jocher** [comment]
@MatthewNoyce PR merged, thank you for your contributions and @jk4e thank you for your help!

**Pull request merged**
