### PR TITLE
Setup template for community examples

### PR DESCRIPTION
**Pull request by AyushExel**
@glenn-jocher @Laughing-q thoughts?
Screenshot 2023-01-30 at 12 59 04 PM
I think we should also create an issue about this, something like - "Calling for examples from community" and pin it

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduction of a community-driven examples section to Ultralytics repository.

### 📊 Key Changes
- New `README.md` file for an examples directory created.
- A template for submitting example applications that use the Ultralytics framework.
- The first example, "Inventory management using YOLO", initiated by AyushExel.

### 🎯 Purpose & Impact
- **Purpose**: To encourage and guide community contributions to the Ultralytics ecosystem through real-world examples and applications.
- **Impact**: This will foster a collaborative environment, provide users with practical use-cases, and potentially improve the Ultralytics framework through community engagement. ☺️🤝

📝 *Note*: The 'inventory-management' example currently contains only a placeholder text indicating it is a dummy project.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@AyushExel looks good! perhaps we can also add tracker support in this example folder.

**Comment by glenn-jocher** [comment]
@AyushExel looks good, but should we use the existing `examples/` directory for this?

**Comment by AyushExel** [comment]
@glenn-jocher ohh yes. I forgot that exists. Let's use examples/

**Comment by AyushExel** [comment]
updated

**Comment by ichsan2895** [comment]
You are welcome to use my example notebook in this thread https://github.com/ultralytics/ultralytics/pull/526 👍

**Comment by AyushExel** [comment]
@glenn-jocher merging this. You need to create an issue titled something like - "We are accepting Ultralytics YOLO Example projects" and pin it

**Pull request merged**
