### PR TITLE
Add ability to disable EMA from sub-classes of BaseTrainer

### PR DESCRIPTION
**Pull request by corey-nm**
In some cases (like when model weights are pruned, or a model is quantized), it is not possible to use EMA. This PR adds a simple flag to ModelEMA class that allows disabling any updates to EMA.

The main use for this is when subclassing from the `BaseTrainer` class, where you have access to `self.ema`. In this case you can disable by running:
```python
self.ema.enabled = False
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements and refactoring in Ultralytics YOLO Torch utils for better maintainability and user control.

### 📊 Key Changes
- 🧹 Simplified import statements by removing unnecessary lines and merging related imports.
- 🚀 Introduced an `enabled` attribute in `ModelEMA` class to allow turning EMA (Exponential Moving Average) on and off.
- 🛠 Fixed assertions by commenting them and improved variable naming for clarity.
- 🔧 Extended the patience parameter in `EarlyStopping` class from 30 to 50 epochs to provide a longer evaluation period before stopping training.
- 📚 Updated method documentations to reflect new defaults and parameter usage more accurately.

### 🎯 Purpose & Impact
- 🌐 The import refactoring reduces clutter in the code, which makes it easier for developers to maintain.
- ✨ Adding an `enabled` attribute to `ModelEMA` gives users control to disable EMA if desired, enhancing usability.
- 🎈 The increased `EarlyStopping` patience offers potentially better training outcomes by allowing more time for model improvement before stopping.
- 📖 The updated comments and documentation improve code readability and make it easier for users to understand how to use the functionalities.

### CODE REVIEW

**Comment by corey-nm** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@corey-nm looks good. Thanks for the PR!

**Comment by glenn-jocher** [comment]
Merged into PR for 8.0.21 deployment

**Comment by corey-nm** [comment]
Awesome, thanks!!

**Comment by pderrenger** [comment]
@corey-nm you're welcome! 🎉 If you have any other questions or need further assistance, feel free to ask. Good job on the PR!

**Pull request merged**
