### PR TITLE
Improve NMS speed 

### PR DESCRIPTION
**Pull request by yermandy**
### Summary
🚀🧠🛠️

This pull request optimizes and cleans up the code in `ops.py` that handles the YOLO prediction tensor. It avoids copying and reshaping the tensor unnecessarily and uses a more modern and efficient method for filtering the boxes.

> _The file `ops.py` was quite slow_
> _And its code was hard to follow_
> _So the author made changes_
> _To avoid tensor exchanges_
> _And used `torch.where` instead of `nonzero`_

### Walkthrough
*  Prepare prediction tensor for filtering and NMS by cloning, transposing, and converting box coordinates ([link](https://github.com/ultralytics/ultralytics/pull/3467/files?diff=unified&w=0#diff-6ab52db19716f4198ed847132149ab432f032ed39c99c264a9de386446bf7f88R202-R205))
*  Simplify and optimize filtering and NMS operations by removing unnecessary transpose and conversion, and using torch.where instead of nonzero ([link](https://github.com/ultralytics/ultralytics/pull/3467/files?diff=unified&w=0#diff-6ab52db19716f4198ed847132149ab432f032ed39c99c264a9de386446bf7f88L208-R212), [link](https://github.com/ultralytics/ultralytics/pull/3467/files?diff=unified&w=0#diff-6ab52db19716f4198ed847132149ab432f032ed39c99c264a9de386446bf7f88L224-R230))
*  Avoid sorting and slicing boxes when number of boxes is below max_nms limit ([link](https://github.com/ultralytics/ultralytics/pull/3467/files?diff=unified&w=0#diff-6ab52db19716f4198ed847132149ab432f032ed39c99c264a9de386446bf7f88L244-R251))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Non-Max Suppression (NMS) Functionality in YOLO Utilities

### 📊 Key Changes
- Cloning of the `prediction` tensor to avoid modifying the original data.
- Switching dimensions of `prediction` using `transpose` for batch processing.
- Conversion of box dimensions from center-width-height (xywh) format to corner coordinates (xyxy) at an earlier stage in the code.
- Replaced a complex method of non-zero indexing with the more straightforward `torch.where` for readability and reliability.
- Conditional check to sort and remove excess boxes only if the number of boxes exceeds `max_nms`.

### 🎯 Purpose & Impact
- Ensuring that input data remains unaltered will prevent unexpected side effects, making the function safer when used as a component in larger pipelines.
- Streamlining tensor operations can potentially speed up the NMS process, making the code more efficient.
- Cleaner indexing with `torch.where` increases the maintainability of the code and can help prevent bugs.
- Adding a conditional check before sorting boxes by confidence and removing excess ones prevents unnecessary operations, optimizing performance for cases with fewer detections.

These changes should collectively improve the reliability, efficiency, and clarity of the NMS function within the YOLO utilities, positively impacting developers who rely on this function for object detection tasks. 🚀✨

### CODE REVIEW

**Comment by yermandy** [comment]
Profiling results. 
Old:
old
New:
new

**Comment by Laughing-q** [comment]
@yermandy hi, thanks for the PR! it looks good! But I think we'll need the `argsort` operation anyway for our internal mAP calculation and better plotting, even when `n < max_det`.

**Comment by yermandy** [comment]
> @yermandy hi, thanks for the PR! it looks good! But I think we'll need the `argsort` operation anyway for our internal mAP calculation and better plotting, even when `n < max_det`.

Hello, I do not think this is needed because [torchvision.ops.nms](https://pytorch.org/vision/stable/generated/torchvision.ops.nms.html) will sort detections anyway. So, this argsort is used only for selecting `max_det` best detections

**Comment by yermandy** [comment]
In other words, my PR and previous version will have same outputs

**Comment by Laughing-q** [comment]
@yermandy oh I don't know the returned idx from torchvision.ops.nms is also sorted. Then all looks good!
BTW please sign the CLA, just comment with `I have read the CLA Document and I sign the CLA` would be ok. :)

**Comment by yermandy** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@yermandy wow nice results!! I'm surprised that taking the xxyx2xywh() out of the for loop didn't hurt the speed there, but from your profiling results that part looks good.

How did you get these profiling results? I've used PyCharm profiler in the past but this looks different.

**Comment by yermandy** [comment]
@glenn-jocher thank you for your comment. My guess is that cloning operation (in xywh2xyxy) is quite inefficient and doing it many times hurts performance.

I decided to create [github gist](https://gist.github.com/yermandy/36ec8ab17c18d83bc8462f8a33e24da5) to share my profiling tools. I mainly use either `@cprofile()` or `@iprofile()` decorators. The first one will generate a file which can be displayed with `snakeviz`. The usage is straightforward and documented.

**Comment by glenn-jocher** [comment]
Hi there,

Thank you for sharing your thoughts and providing the profiling tools gist. Regarding the cloning operation in `xywh2xyxy`, you mentioned that it might be inefficient and could impact performance. 

Cloning operations can indeed add some overhead, especially if performed multiple times. One possible optimization could be to avoid unnecessary cloning by reusing the existing tensor or by modifying the tensor in-place.

As for the profiling tools gist you shared, the ` @yermandy()` and `@iprofile()` decorators seem like useful options for profiling the performance of your code. I appreciate the documentation and straightforward usage you provided.

If you have any further questions or updates, feel free to let us know. We are here to assist you.

Best regards,
Glenn Jocher

**Comment by yermandy** [comment]
I noticed that YOLOv8 also uses [context manager](https://github.com/ultralytics/ultralytics/blob/cd0bf05aa476c3499d72fab1407d011218124a5f/ultralytics/yolo/utils/ops.py#L19) for profiling. I also decided to add this functionality to the tools. If someone need it, they can be found [here](https://gist.github.com/yermandy/7a70d2ca6f139076becadbf5ea8bd47c)

**Comment by glenn-jocher** [comment]
@yermandy hi there,

Thank you for bringing up the profiling functionality in YOLOv8 and your interest in adding similar functionality to the tools. 

While YOLOv8 does indeed utilize a context manager for profiling, it's worth noting that the Ultralytics YOLOv8 repository focuses solely on YOLOv8 and does not include profiling tools or functionalities.

However, I appreciate your initiative in creating your own profiling tools and sharing them through the provided gist. This allows users who may need profiling capabilities to utilize your tools as an additional resource.

If you have any further questions or need assistance, please don't hesitate to reach out. Our team is more than happy to help.

Best regards,
Glenn Jocher

**Comment by glenn-jocher** [comment]
@yermandy PR merged! Thank you for your contributions and let us know if you see any slow areas in the Ultralytics package :)

**Pull request merged**
