### PR TITLE
update ort==2.0.0-rs.5 to support onnxruntime==1.19.x

### PR DESCRIPTION
**Pull request by yawnbright**
## 🌟 Summary
Update ort==2.0.0-rs.5 to support onnxruntime==1.19.x.

## 📊 Key Changes
Use ort==2.0.0-rs.5 to replace ort==1.6.3,   ort==1.6.3 can not infer the onnx model transformed by onnxruntime 1.19.x (the latest version so far).

## 🎯 Purpose & Impact
Ensures that users can use the newest onnxruntime.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR updates dependencies and improves the YOLOv8 ONNXRuntime Rust demo example, enhancing compatibility and performance with newer versions of tools.

### 📊 Key Changes
- **Dependencies Updated**: Libraries such as `image`, `imageproc`, `ndarray`, `ort`, and `rusttype` have been updated to newer versions.
- **New Feature Addition**: Added local font `ARIALN.TTF` for improved text rendering in the demo.
- **ONNXRuntime Update**: Updated ONNXRuntime version to `2.0.0-rc.5` with added support for CUDA and TensorRT.
- **Code Enhancements**: Various code refactoring and optimization, such as replacing tensor and array handling methods and updating device ID types from `u32` to `i32` for better compatibility.

### 🎯 Purpose & Impact
- **Enhanced Performance**: Updating dependencies like ONNXRuntime ensures faster and more efficient runtime processing, leveraging new features from CUDA and TensorRT 🚀.
- **Improved Usability**: Refactoring and code updates lead to more readable and maintainable code. The updated device ID handling ensures broader compatibility across different hardware 🛠️.
- **Better Text Rendering**: Including a local font enhances the visual output of the demo, leading to clearer and more consistent text displays in results ✨.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @yawnBright, thank you for submitting your pull request to the `ultralytics/ultralytics` 🚀 repository! Your contribution to update `ort` to version `2.0.0-rs.5` to support `onnxruntime` version `1.19.x` is much appreciated. Here's a checklist to ensure a smooth integration:

- ✅ **Define a Purpose**: Make sure the purpose of your update is clearly detailed in the PR description. If your update addresses specific issues, please link them in the description. You can find relevant [issues here](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear and convey the intent.
- ✅ **Synchronize with Source**: Please confirm your PR is up-to-date with the `main` branch of `ultralytics`. If it’s outdated, use the 'Update branch' button or run `git pull` and `git merge main` in your local environment.
- ✅ **Ensure CI Checks Pass**: All Ultralytics [Continuous Integration (CI) checks](https://docs.ultralytics.com/help/CI/) should pass. If any checks are failing, please investigate and resolve these issues.
- ✅ **Update Documentation**: Ensure documentation reflects your updates accurately. The full documentation is available at [Ultralytics Documentation](https://docs.ultralytics.com).
- ✅ **Add Tests**: If your changes impact functionality, include corresponding tests. Verify all tests pass successfully. 
- ✅ **Sign the CLA**: If this is your first contribution to Ultralytics, ensure you've signed the [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/). Please comment "I have read the CLA Document and I sign the CLA" within the PR.
- ✅ **Minimize Changes**: Double-check that your changes are the minimal edit necessary to achieve the desired functionality.

For more detailed guidance, visit our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to comment on the PR if you have questions or need clarification.

This is an automated response. A member of the Ultralytics team will review your submission and provide feedback soon. Thanks for your contribution! 😊

**Comment by glenn-jocher** [comment]
@yawnBright where is this font supposed to come from?

        let font: FontArc = FontArc::try_from_slice(include_bytes!("ARIALN.TTF")).expect("can't open this font");

**Comment by yawnBright** [comment]
Sorry, this is my first time to pull a request, which makes me confused. I just forget add this font file, I will pull another request later. Sorry for that again.&nbsp;



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2024年10月16日(星期三) 下午5:44
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] update ort==2.0.0-rs.5 to support onnxruntime==1.19.x (PR #16957)














 
@yawnBright where is this font supposed to come from?
     let font: FontArc = FontArc::try_from_slice(include_bytes!("ARIALN.TTF")).expect("can't open this font");

**Comment by glenn-jocher** [comment]
No worries! Feel free to submit another pull request with the font file included. Let us know if you need any assistance.

**Pull request closed without merging**
