### PR TITLE
Add ResNet50 and ResNet101 backbone RTDETR models

### PR DESCRIPTION
**Pull request by WangQvQ**
### Summary
📄🧠🚀

This pull request adds new modules and configurations for RT-DETR-ResNet models, which are object detection models that use ResNet backbones and a transformer-based decoder. It introduces a new `ResNetLayer` module in the `nn.modules` package, and two YAML files for the RT-DETR-ResNet50 and RT-DETR-ResNet101 model variants in the `cfg/models/rt-detr` folder. It also updates the `tasks.py` file to support these models.

> _We're building ResNet backbones for RT-DETR_
> _We need them to detect objects on the water_
> _We import the `ResNetLayer` module with care_
> _And parse it in the `tasks.py` file together_

### Walkthrough
*  Add new YAML files for RT-DETR-ResNet101 and RT-DETR-ResNet50 model configurations, which use ResNet101 and ResNet50 as backbones and output P3-P5 feature maps for object detection ([link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-f768ef28dc340a874e6a6e8a435113c112fb3dc3339cac87fa366f657c22cf6eR1-R42), [link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-25e88a373ec240fc1dcda1b60ca9229c382aa8db00ae89fbdb8085d4b252f797R1-R42))
* Define ResNetBlock and ResNetLayer classes in `block.py`, which implement ResNet blocks and layers with standard convolution layers, shortcut connections, and ReLU activations ([link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-70b1aad8c0068184a0e145431a251d90d480aed0226918c90c5a8ccd5a84f0f8L334-R374))
* Import ResNetLayer module from `block.py` in `__init__.py` and `tasks.py`, and add it to the `__all__` variable in both files, to enable the use of ResNetLayer by the RT-DETR-ResNet models and other modules ([link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-9cc0562cbdd5ea53281608fcca608bc46bcc52a41f78bbe8ed709f37f1e52590L21-R21), [link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-9cc0562cbdd5ea53281608fcca608bc46bcc52a41f78bbe8ed709f37f1e52590L33-R33), [link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-70b1aad8c0068184a0e145431a251d90d480aed0226918c90c5a8ccd5a84f0f8L12-R12), [link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L13-R13))
* Modify `parse_model` function in `tasks.py` to handle ResNetLayer module, and assign the correct output channel number and number of repeats based on the model configuration ([link](https://github.com/ultralytics/ultralytics/pull/6661/files?diff=unified&w=0#diff-e2650ac65b6525f6d9c0594a226066d396afbcba637c054d29abe04e62f410c4L703-R707))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the Ultralytics object detection model configurations, including cleanup and the introduction of ResNet layers. 🚀

### 📊 Key Changes
- Minor cleanup in `rtdetr-l.yaml` by removing extra spaces. 🧹
- New model configurations added for RT-DETR models using ResNet50 and ResNet101 backbones. 🆕
- Introduced `ResNetLayer` and `ResNetBlock` classes in `block.py`. 🌐
- Integrated `ResNetLayer` into the main `__init__.py` module for easier access and imports. 🛠️

### 🎯 Purpose & Impact
- The cleanup ensures a cleaner and more consistent codebase. ✨
- New RT-DETR model configurations with ResNet backbones can potentially improve object detection performance with these well-established architectures. 🎯
- The inclusion of `ResNetLayer` allows Ultralytics models to leverage standard ResNet blocks, often leading to more robust features and improved generalization. 💪
- By making `ResNetLayer` a part of the modules package, developers can now more conveniently use these layers in designing new neural network architectures. 🏗️

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@WangQvQ please see pre-commit CI failure, thank you!

**Comment by WangQvQ** [comment]
@glenn-jocher Ok, that problem has been solved.

**Comment by glenn-jocher** [comment]
@WangQvQ great to hear the issue has been resolved! If you encounter any more challenges or have further questions, don't hesitate to reach out. Happy coding! 😊

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel @fcakyon @RizwanMunawar @Burhan-Q another hybrid model PR

**Comment by ExtReMLapin** [comment]
@WangQvQ any plan to add P2 layer output ?

**Comment by WangQvQ** [comment]
I am not sure if the project needs this code enough, if so, I can continue to submit the yaml file code for P2 and P6. @ExtReMLapin @glenn-jocher

**Comment by ExtReMLapin** [comment]
If you don't think it's worth a PR, can you post it here at least ?

**Comment by WangQvQ** [comment]
Yes, I'd love to. I'll put it here a little later. Thank you for your attention.

**Comment by glenn-jocher** [comment]
@WangQvQ i appreciate your initiative on this, but kindly save it for a potential future GitHub issue or PR where it can be discussed in detail. Thanks for your understanding and contribution! 🙏

**Comment by WangQvQ** [comment]
@ExtReMLapin @glenn-jocher Thank you for waiting, please take a look at https://github.com/ultralytics/ultralytics/pull/7023

**Comment by glenn-jocher** [comment]
@WangQvQ Thanks for the update and for submitting the PR. We'll review it soon. Your contributions are much appreciated! 🚀

**Comment by prince0310** [comment]
@glenn-jocher  and @WangQvQ how to use this backbone in yolov8l model ? i have tried to replace the same backbone but encountered error i think in concatation layers.

**Comment by glenn-jocher** [comment]
@prince0310 the YOLOv8 architecture may require specific adjustments to accommodate a different backbone like the one in your PR. If you’re replacing the backbone in YOLOv8l, ensure that the output dimensions match the expected input dimensions of subsequent layers, especially at concatenation points. For detailed guidance on integrating new backbones, please refer to our documentation on Custom Model Development.

**Comment by WangQvQ** [comment]
@prince0310 
```
# Ultralytics YOLO 🚀, AGPL-3.0 license
# YOLOv8 object detection model with P3-P5 outputs. For Usage examples see https://docs.ultralytics.com/tasks/detect

# Parameters
nc: 80  # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  # n: [0.33, 0.25, 1024]
  # s: [0.33, 0.50, 1024]
  # m: [0.67, 0.75, 768]
  l: [1.00, 1.00, 512]   # YOLOv8l summary: 406 layers, 49291520 parameters, 49291504 gradients, 152.0 GFLOPs
  x: [1.00, 1.25, 512]

# YOLOv8.0n backbone
backbone:
  # [from, repeats, module, args]
  - [-1, 1, ResNetLayer, [3, 64, 1, True, 1]]  # 0-P1/2
  - [-1, 1, ResNetLayer, [64, 64, 1, False, 3]]  # 1-P2/4
  - [-1, 1, ResNetLayer, [256, 128, 2, False, 4]]  # 2-P3/8
  - [-1, 1, ResNetLayer, [512, 256, 2, False, 6]]  # 3-P4/16
  - [-1, 1, ResNetLayer, [1024, 512, 2, False, 3]]  # 4-P5/32

# YOLOv8.0n head
head:
  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 3], 1, Concat, [1]]  # cat backbone P4
  - [-1, 3, C2f, [512]]  # 7

  - [-1, 1, nn.Upsample, [None, 2, 'nearest']]
  - [[-1, 2], 1, Concat, [1]]  # cat backbone P3
  - [-1, 3, C2f, [256]]  # 10 (P3/8-small)

  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 7], 1, Concat, [1]]  # cat head P4
  - [-1, 3, C2f, [512]]  # 13 (P4/16-medium)

  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 4], 1, Concat, [1]]  # cat head P5
  - [-1, 3, C2f, [1024]]  # 16 (P5/32-large)

  - [[10, 13, 16], 1, Detect, [nc]]  # Detect(P3, P4, P5)
```

**Pull request merged**
