### PR TITLE
Fix conversion ops using `clone` and `copy`

### PR DESCRIPTION
**Pull request by Laughing-q**
### Summary
🔄📦🛠️

This pull request improves the robustness of bounding box conversion functions in `ultralytics/utils/ops.py` by using `clone` or `copy` instead of `empty_like` to create new tensors or arrays. This avoids unintended side effects when modifying the output values.

> _No more `empty_like` in the dark_
> _We clone and copy to leave our mark_
> _We shape the bounding boxes of our fate_
> _We resist the errors that await_

### Walkthrough
*  Replace `empty_like` with `clone` or `copy` to create new tensors or arrays with the same values as the input in four functions that convert bounding box coordinates between different formats (`xywh2ltwh`, `xyxy2ltwh`, `ltwh2xywh`, `ltwh2xyxy`) in `ultralytics/utils/ops.py` ([link](https://github.com/ultralytics/ultralytics/pull/4438/files?diff=unified&w=0#diff-4c045e45231b1287ae6222068d75c8a96d1e2bf450c5ecf9dc0959eaec04dfe6L449-R449), [link](https://github.com/ultralytics/ultralytics/pull/4438/files?diff=unified&w=0#diff-4c045e45231b1287ae6222068d75c8a96d1e2bf450c5ecf9dc0959eaec04dfe6L464-R464), [link](https://github.com/ultralytics/ultralytics/pull/4438/files?diff=unified&w=0#diff-4c045e45231b1287ae6222068d75c8a96d1e2bf450c5ecf9dc0959eaec04dfe6L477-R477), [link](https://github.com/ultralytics/ultralytics/pull/4438/files?diff=unified&w=0#diff-4c045e45231b1287ae6222068d75c8a96d1e2bf450c5ecf9dc0959eaec04dfe6L572-R572))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements in bounding box format conversions and download functions.

### 📊 Key Changes
- Refactored download-related code to use `TQDM_BAR_FORMAT` from `utils` without re-importing it.
- Improved `Bboxes` class in `instance.py` for clarity in comments and better representation of supported bounding box formats.
- Streamlined bounding boxes format conversion functions in `ops.py` with clearer documentation, assertions for input shape validations, and optimizations in cloning/copying arrays.
- Removal of dead code and comments for better code cleanliness.

### 🎯 Purpose & Impact
- 🔍 Provides a more robust download method by ensuring proper handling of progress bar formatting.
- 🧐 Enhances documentation, making the purpose and format of bounding boxes clearer to users and developers.
- 🚀 Improves efficiency and error handling in bounding box transformations, leading to potentially fewer bugs and better performance in machine learning tasks.
- 🧹 Reduces code complexity and clutter, making the codebase easier to maintain and understand.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher empty_like usage would make the value zero.

**Comment by Laughing-q** [comment]
@glenn-jocher other functions seems work fine since all the [0,1,2,3] indices are updated.

BTW I'm not sure if it's a good idea of using `empty_like` to replace `clone`, maybe it's faster? 
But imagine this usage:
Let's say there's a tensor or numpy with shape [N, 6] and the first four are box coordinates with `xyxy` format and the last two could be conf scores and cls, so I would use `ops.xyxy2xywh(x)` if I want to update the format from `xyxy` to `xywh`, if with `y=x.clone()` then this operation would be correct, box coordinates are updated and conf scores and cls remains, but with `y=torch.empty_lke(x)` the returned conf scores and cls would be gone to zero.
Here's my thoughts:
- If we're going to include the usage above, then probably using `x.clone()` would be a better option.
- If we're not going to include the usage and keep using `empty_like`, then we probably should add a `assert x.shape[-1] == 4` to make sure all the returned results are correct since we only do operations on the first four.

**Comment by glenn-jocher** [comment]
@Laughing-q oh yes you're right! Yes, the switch was made for speed and memory, since the empty_like skips a copy operation.

**Comment by glenn-jocher** [comment]
@Laughing-q ok I've added asserts. Yes I think while the option to pass larger tensors with the first 4 indices as the box looks nice in the code it may lead to more confusion, and then the .clone() op will also be copying extra/uneeded information, slowing it down more. 

In NMS function for example we already only pass the box, and then update only the box. I must have profiled this before and done this on purpose as I saw it was faster than cloning the entire prediction, which is 84 long.

https://github.com/ultralytics/ultralytics/blob/162e4035eb5dd2d1f5adcc729eea738f179f4c33/ultralytics/utils/ops.py#L195

**Comment by glenn-jocher** [comment]
@Laughing-q I also updated all the ops converters to allow for mulitdimensional tensors with x[...,0] instead of x[:,0]. 

This update also profiles faster for me:

```
x = torch.rand(1000,4)
%timeit x[:,3]
1.17 µs ± 10.5 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
%timeit x[...,3]
674 ns ± 4.55 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```

**Pull request merged**
