### PR TITLE
add a new solution, `illegal parking`

### PR DESCRIPTION
**Pull request by M4D-AI**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary

New documentation and script added for detecting illegal parking using Ultralytics YOLOv8.

### 📊 Key Changes

- 📄 Added `illegal-parking.md` guide for detecting illegal parking using YOLOv8.
- 📜 Introduced a Python script (`illegal_parking.py`) for real-time illegal parking detection using object tracking.

### 🎯 Purpose & Impact

- 🚗 **Enhanced Traffic Management**: Provides a framework for detecting illegal parking, useful for traffic control and reducing congestion.
- 🔍 **Real-Time Monitoring**: Enables real-time surveillance with accurate tracking and detection, improving urban management and safety.
- 🌍 **Broad Applications**: Applicable for tasks in traffic management, autonomous navigation, and security surveillance systems.

### CODE REVIEW

**Comment by M4D-AI** [comment]
I have read the CLA Document and I sign the CLA.

**Comment by M4D-AI** [comment]
image
After searching for this error, there is no relevant information. How should I solve this problem?

**Review by ambitious-octopus — CHANGES_REQUESTED** [review]
Hey @M4D-AI, thanks for the PR,  I haven't tested the solution yet because a test example is currently missing. Could you please add one? Additionally, we still need to create a documentation page for this solution. You can use the existing pages as a reference: [Ultralytics Solutions](https://docs.ultralytics.com/solutions/). Please add an example (including a video) with which I can test the solution.

**Comment by glenn-jocher** [comment]
@M4D-AI please ensure you are using the latest version of the Ultralytics package. If the issue persists, could you provide more details about the error message and the context in which it occurs? This will help us assist you better.

**Review by ambitious-octopus — COMMENTED** [review]
Hey @M4D-AI, this is because of the warnings:
image
image

**Comment by M4D-AI** [comment]
> Hey @M4D-AI, this is because of the warnings: image image

Hi, @ambitious-octopus. Thanks for your help, I solved these problems.

**Comment by glenn-jocher** [comment]
Thank you for your feedback. I will add a test video and complete the guide documentation in the guides section.

**Comment by M4D-AI** [comment]
> Thank you for your feedback. I will add a test video and complete the guide documentation in the guides section.

Good, that's cool. I also tried to find suitable videos to provide, but I couldn't find any. Although I use it to monitor illegal parking on urban roads and monitor breakdowns on highways, I can't provide it directly due to privacy reasons.

**Comment by glenn-jocher** [comment]
Thank you for understanding. Please proceed with adding the test video and guide documentation when you can. If you need any further assistance, feel free to reach out.

**Comment by M4D-AI** [comment]
> Thank you for understanding. Please proceed with adding the test video and guide documentation when you can. If you need any further assistance, feel free to reach out.

Thanks, I completed the illegal parking document with reference to the guidance document on speed estimation, but I commented out everything related to video production. I provided the test video in the attachment.
[video.zip](https://github.com/user-attachments/files/16862738/video.zip)

**Comment by M4D-AI** [comment]
> Thank you for understanding. Please proceed with adding the test video and guide documentation when you can. If you need any further assistance, feel free to reach out.

Hey @glenn-jocher ,I have improved the document of illegal parking with reference to the speed estimation document. I have excluded the video and picture display because I am not good at making videos and pictures. In addition, I have provided a video based on the Internet that can effectively display the test. Please see the attachment for details.[

https://github.com/user-attachments/assets/2246549f-3745-4443-82d6-cde80b3ca611

](url)

[vedio raw address](https://www.tiktok.com/@theunbelievable9/video/7292407877229169927)

**Comment by glenn-jocher** [comment]
Thank you for updating the documentation and providing a test video. If you need further assistance, feel free to ask.

**Comment by RizwanMunawar** [comment]
@M4D-AI Hi, thank you for the updates! After reviewing the PR, it looks very similar to our Ultralytics Parking Management System.

I was thinking it could be a great idea to integrate this new functionality into the existing [Parking Management System](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/solutions/parking_management.py) instead of creating a separate solution. I’d be more than happy to contribute and assist with the integration since it aligns so well with the current feature set.

Feel free to start updating the code, and if you need any help along the way, I’m here to support!

Thanks and best regards,  
The Ultralytics Team!

**Comment by M4D-AI** [comment]
> @M4D-AI Hi, thank you for the updates! After reviewing the PR, it looks very similar to our Ultralytics Parking Management System.
> 
> I was thinking it could be a great idea to integrate this new functionality into the existing [Parking Management System](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/solutions/parking_management.py) instead of creating a separate solution. I’d be more than happy to contribute and assist with the integration since it aligns so well with the current feature set.
> 
> Feel free to start updating the code, and if you need any help along the way, I’m here to support!
> 
> Thanks and best regards, The Ultralytics Team!

OK, thank you for your review. The current parking judgment is based on the IoU of the previous and next frames, which is similar to `Parking Management System` and is not enough to be a separate solution. As you said, it would be appropriate to incorporate it into parking management as a new feature.

**Comment by glenn-jocher** [comment]
Thank you for your understanding. Integrating it as a new feature sounds like a great approach. If you need any assistance during the process, feel free to reach out.

**Pull request closed without merging**
