### PR TITLE
Add Explorer CLI `model` and `data` args

### PR DESCRIPTION
**Pull request by Y-T-G**
The current explorer doesn't support custom models or datasets, making it unhelpful for most use-cases. This PR adds support for both custom models and datasets.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the Ultralytics Explorer functionality by adding support for specifying dataset and model parameters.

### 📊 Key Changes
- Updated the `yolo explorer` command to accept dataset (`data.yaml`) and model parameters (`yolov8n.pt`).
- Modified `handle_explorer` function to parse command line arguments and handle dataset and model settings.
- Enhanced `init_explorer_form` and `layout` functions to initialize and reset with specified dataset and model.
- Incorporated warnings for situations when `data.yaml` or model arguments are not provided, displaying default options.

### 🎯 Purpose & Impact
- **Ease of Use**: Users can now directly specify datasets and models when launching the Ultralytics Explorer GUI, making dataset exploration more flexible and straightforward. 🗂️
- **Customizable Insights**: Allows for tailored command execution, improving user experience by providing specific data analysis setups right from the start. 🎯
- **Better Feedback**: Added warnings to inform users when default datasets or models are being used, ensuring clarity. ⚠️

### CODE REVIEW

**Comment by Y-T-G** [comment]
I have read the CLA Document and I sign the CLA.

**Comment by glenn-jocher** [comment]
@Y-T-G thanks for the PR! 

The argument handling code seems to be duplicating the existing argument handling code. Ideally we'd use the existing code. Is this possible?

**Comment by Y-T-G** [comment]
@glenn-jocher I tried to find similar argument handling code in the file to make sure I wasn't duplicating any functionality. I found `merge_equals_args` and `parse_key_value_pair`:
https://github.com/ultralytics/ultralytics/blob/3de5d8b20964a3054dee56fa7bea57d0fc563100/ultralytics/cfg/__init__.py#L533-L544

Is there anything else I could use?

Or are you referring to the one here:
https://github.com/ultralytics/ultralytics/blob/3de5d8b20964a3054dee56fa7bea57d0fc563100/ultralytics/data/explorer/gui/dash.py#L274-L281

**Comment by glenn-jocher** [comment]
@Y-T-G merged into `explorer` branch to allow for CI with correct permissions, will merge to main in a separate PR.

**Pull request merged**
