### PR TITLE
[WIP] YOLO-World training implementation 

### LINKED ISSUE #8156: Add YOLO World training
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Related to #8039 and #8054

- [ ] add code for training for YOLO World models
- [ ] add validation code as well

### Use case

Language fine-tuning with corresponding image data

### Additional

- Establish requirements and/or features to be included

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by IamShubhamGupto**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to loss functions and training procedures for Ultralytics' YOLO models. closes #8156 

### 📊 Key Changes
- 🛠 Added a new `CoVMSELoss` class for variance-based loss calculations.
- 🔄 Updated pre-commit configuration to include `--unsafe-fixes` alongside `--fix`.
- 🍱 Integrated `MSELoss` as part of the DETR loss computation.
- 🚀 Added a new `WorldTrainer` for YOLO models with corresponding training utilities.
- 🧱 Created scaffolding for new 'world' predictor and validator in the YOLO model suite.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: 
  - To improve model performance by introducing a new loss metric that considers variance.
  - Streamline development with more comprehensive code formatting checks.
  - Expand training capabilities with a new dedicated trainer for 'world' tasks in YOLO models.

- 💥 **Impact**: 
  - Improved model accuracy and reliability by optimizing loss functions.
  - Smoother development experience with enforced code quality.
  - Enhanced flexibility for researchers and practitioners working with more complex YOLO model tasks.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added new loss functions and updated configurations for YOLO models.

### 📊 Key Changes
- Introduced `CoVMSELoss` and `MSELoss` classes for enhanced loss calculations.
- Updated `.pre-commit-config.yaml` to include `--unsafe-fixes` for Ruff.
- Modified YOLO model training logic to incorporate `CoVMSELoss`.

### 🎯 Purpose & Impact
- **Improved Loss Calculations**: Enhances how losses are computed, potentially improving model training efficiency and accuracy.
- **Enhanced Code Quality**: The configuration update may streamline code validation and maintenance.
- **Model Flexibility**: Supports new detection types, expanding YOLO's applicability to diverse scenarios.

### CODE REVIEW

**Comment by IamShubhamGupto** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by IamShubhamGupto** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@IamShubhamGupto awesome, thank you for your contributions here! What datasets would we train on here? Can you supply a small usage example with this PR branch?

@Laughing-q is our primary contributor contributor for World model inference and validation, looping him in here!

**Comment by IamShubhamGupto** [comment]
@glenn-jocher it'll be done soon

@Laughing-q ive been following your implementation of yolo world and I think I understand most of your implementation. My code coverage reports right now say the additional loss function ive implemented is not being used. I will debug that soon but in case you know how to fix that let me know.

**Comment by glenn-jocher** [comment]
@IamShubhamGupto it's great to see the progress on the YOLO-World training implementation. The addition of the `CoVMSELoss` class and the integration of `MSELoss` into the DETR loss computation are promising enhancements that could potentially improve the robustness and accuracy of the models. The introduction of the `WorldTrainer` and the new 'world' predictor and validator are also exciting developments that will likely expand the capabilities of the YOLO model suite.

The purpose of these changes aligns well with the goal of advancing the state-of-the-art in object detection and related tasks. By focusing on variance-based loss calculations and dedicated training utilities, the YOLO models can be better equipped to handle complex scenarios and datasets.

The impact of these changes is expected to be significant, offering improved model performance and a more streamlined development process. This will not only benefit the research community but also practitioners who rely on YOLO models for real-world applications.

Overall, the key changes outlined in the PR summary indicate a thoughtful approach to enhancing the YOLO models. The focus on loss functions, code quality, and training procedures demonstrates Ultralytics' commitment to continuous improvement and innovation in the field of computer vision.

**Comment by Laughing-q** [comment]
Hi @IamShubhamGupto

**Comment by IamShubhamGupto** [comment]
@Laughing-q hey sorry for the inactivity. I have not been able to pay attention to this branch due to other commitments. In case theres a timeline, feel free to work on your own implementation to bring training of yolo-world

**Comment by Laughing-q** [comment]
@IamShubhamGupto Hey! We are closing this PR since we've already supported yolo-world training. Please free feel to reopen this PR or open a branch new one if you feel something necessary to implement! Thanks!

**Pull request closed without merging**
