### PR TITLE
`ultralytics 8.0.136` refactor and simplify package

### PR DESCRIPTION
**Pull request by Laughing-q**
Changes in paths:

```
ultralytics.yolo.utils -> ultralytics.utils
ultralytics.yolo.cfg -> ultralytics.cfg
ultralytics.yolo.engine -> ultralytics.engine
ultralytics.yolo.v8 -> ultralytics.models.yolo
ultralytics.vit -> ultralytics.models

ultralytics.datasets -> ultralytics.cfg.datasets
ultralytics.models -> ultralytics.cfg.models

ultralytics.data.dataloaders.stream_loaders -> ultralytics.data.loaders
```

### Summary
🚚🛠️📝

This pull request updates the documentation files for the `ultralytics` package to match the new module structure. It changes the import statements and the module paths for the `tracker` and `vit` subpackages, which have been moved under `ultralytics.models`. It also fixes some broken links and typos in the documentation.

> _`ultralytics` has changed its form_
> _We must update the paths to conform_
> _The `tracker` and the `vit` have moved_
> _Don't let the code break, we must improve_

### Walkthrough
*  Update import statements for `ROOT`, `SAMPredictor`, `auto_annotate`, and `benchmark` to reflect the new module locations under `ultralytics` ([link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-5cfa04e1ac6cf15d3e088375fb3e6988979e65360130a6e837459fa22dd9c59cL13-R13), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-6d9ff66732e3f612566f6c8e4ad3b6db2cfab0c3f06f11776d72b39ea4213220L91-R91), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-6d9ff66732e3f612566f6c8e4ad3b6db2cfab0c3f06f11776d72b39ea4213220L111-R111), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-6d9ff66732e3f612566f6c8e4ad3b6db2cfab0c3f06f11776d72b39ea4213220L187-R187), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-bb5cf7919612f5a526e139896c15b09fba0cf48c14cfaf740566eb7d621aee7bL30-R30))
* Update links to `data/utils.py` and `Results` module reference documentation to reflect the new module locations under `ultralytics` ([link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-31a8e95fab032c4aff065cd0faacd330d81e4b154c017a7827c9f85d7f8dea49L319-R319), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-31a8e95fab032c4aff065cd0faacd330d81e4b154c017a7827c9f85d7f8dea49L454-R454))
* Update links to `tracker` config files to reflect the new module location under `ultralytics.models` ([link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-28a675294ad148751845f8d4fd08d1a73a30bde0bf27a269e7f8294d1537bbcfL82-R82), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-28a675294ad148751845f8d4fd08d1a73a30bde0bf27a269e7f8294d1537bbcfL100-L99))
* Update module paths for `tracker` and its submodules to reflect the new module location under `ultralytics.models` ([link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-130ab550842dea975a698f3d8fce119136db4525fce688be6cf6b77ac9fdcd03L8-R18), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-5feda0b68ca22e10adb19d472ae88a7113385ea57fd233078e2459533e29e9a0L8-R13), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-b42a44892f20daf3ae5bd602fd5973d6eb5f6961dc76ba90986224221c9de553L8-R13), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-8b1159e12d9087bab08d2c3566c30fa1966f3505d8e365f9d487ec7e0b8b4aacL8-R13), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-1854b02fc231f85ff89eaa8af68d1379cb9c37b61eb5ed648c7c76538fae5e0cL8-R8), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-5a14a091b5787436f63a311b0eda5d009df96946f365e6fb17b4b7a35bd600e9L8-R13), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-6a5076a91099af04bd71cd60b80bbcc494d7ed425fd1085442b41f31c1b71950L8-R63))
* Update module paths for `vit` and its submodules to reflect the new module location under `ultralytics.models` ([link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-285c2a6f3c1caa145c6d5ac8ac5a27a7a279a8cf8c78c37eac7c32532d52de09L8-R8), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-f1138c9c8ac5589ca64e51e17dd94314a36454e3c71d0bb37e4b5ce6f6092cccL8-R8), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-43d410e5da25e56709d2e8f7e141b8d58318113d761aa1f298ddac5d313846ffL8-R13), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-8a79a8093e3df323030b9827d6e876373cd80eef6a2d2ded5bd53b53c1bade13L8-R13), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-a202735b66a942ea58317337d24bf24ac592dc9d33d9f91e5dfc43a183fbbdc3L8-R88), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-a7c4f463206f7ad9bb606e48f1b7ba3262995f876ceb31992e517f455b28f8b3L8-R33), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-f6e26f4f069d8871b0da56d9f8a0e6bd28aea6db472cde6372413d0a74a1cfb2L8-R8), [link](https://github.com/ultralytics/ultralytics/pull/3748/files?diff=unified&w=0#diff-d0c84eef6d7bf71ae8f77a456b19c577211c0ac227cb013c56bf7a2d57312081L8-R13))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

**WARNING ⚠️** this PR is very large, summary may not cover all changes.

### 🌟 Summary
Enhancements in YAML file loading and exporting models in Ultralytics repositories.

### 📊 Key Changes
- Moved YAML files to a new `ultralytics/cfg` directory.
- Adjusted import statements to the new YAML file locations.
- Renamed `ultralytics/yolo` to `ultralytics/models/yolo` reflecting restructured code organization.
- Updated scripts related to downloading pretrained models and datasets to use the new paths.

### 🎯 Purpose & Impact
- 🔨 The changes improve codebase structure, making it easier to maintain and extend.
- 🏗️ User scripts importing from `ultralytics` may need to update the import paths impacted by this reorganization.
- 🚚 Affected users should expect file movement operations, ensuring they reference the new locations for continued functionality.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher @AyushExel @fcakyon ok this PR is ready on my side, basically everything is like I said before here https://github.com/ultralytics/ultralytics/pull/3410#issuecomment-1614181093. The current way to keep backward compatibility for `ultralytics/yolo` is much clean and light than the last refactor PR.
Oh and please update the official `classify` and `pose` models by the following script after this PR merged.
```python
import torch
for suffix in ["n", "s", "m", "l", "x"]:
    torch.save(torch.load(f"yolov8{suffix}-cls.pt"), f"yolov8{suffix}-cls.pt")
    torch.save(torch.load(f"yolov8{suffix}-pose.pt"), f"yolov8{suffix}-pose.pt")
```

**Comment by glenn-jocher** [comment]
@Laughing-q ok I'm working on this now. We can't change the assets we have uploaded though since then users with older packages won't be able to use the downloaded models anymore, we'll get a huge amount of bug reports.

**Comment by glenn-jocher** [comment]
@Laughing-q hey I had some update ideas, what do you think of this structure:




I think this is probably best as in the future the lines between yolo and vit will begin to blur, and it may not make sense to create such a strong distinction between them, i.e. FastSAM uses both in one model.

- I also moved tracker/cfg to cfg/trackers
- Maybe rename ultralytics/data to ultralytics/dataloaders ?
- Rename ultralytics/tracker to ultralytics/trackers (plural, same as models, dataloaders)
- Maybe rename ultralytics/models/yolov8 to ultralytics/models/yolo
- Maybe rename ultralytics/cfg/default.yaml to ultralytics/cfg/args/default.yaml?

What do you think?

**Comment by Laughing-q** [comment]
@glenn-jocher yeah actually today I wanted to move all our models into `models/` but I just not very sure about that since yolo models are our major ones. 
I totally agree with point 1, 3 and 4, not sure about renaming data/ to dataloaders/ since I actually prefer the former 😂, but both the names are okay to me. 
About the last one, I think we probably won't add more arg files like our `default.yaml` right? then it looks a little odd if we maintain only one file in one folder i.e `args/default.yaml`.

**Comment by glenn-jocher** [comment]
@Laughing-q ok perfect, let's just do 1, 3 and 4 then!

Then after that's done I'll take care of the docs, they're going to need some serious work I think, but I've got a few scripts to automate that offline.

**Comment by Laughing-q** [comment]
@glenn-jocher Are you already working on it? if not I can do it right now since I have some script to correct the python imports and path after these folder shifts.

**Comment by glenn-jocher** [comment]
No I haven't done any changes, go ahead and you do it!

**Comment by Laughing-q** [comment]
@glenn-jocher ok I've updated the folder structure, you can work on the docs now. :)

**Comment by glenn-jocher** [comment]
@Laughing-q ok awesome, I'll take it from here. Yeah good idea on the trackers, we don't need the extra folder. Maybe it makes sense to have a utils/ directory in models, I'll take a closer look.

**Comment by glenn-jocher** [comment]
@Laughing-q ok I think this is working, but I need to make a change to the model loading to intercept the older models so that they don't display a warning by default. i.e. with this PR I get path warning:

```
yolo predict model=yolov8n.pt source=ultralytics/assets/bus.jpg

WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.cfg' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.cfg' instead.
Ultralytics YOLOv8.0.135 🚀 Python-3.10.6 torch-2.0.1 CPU (Apple M2)
YOLOv8n summary (fused): 168 layers, 3151904 parameters, 0 gradients, 8.7 GFLOPs

image 1/1 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x480 4 persons, 1 bus, 1 stop sign, 53.1ms
Speed: 1.8ms preprocess, 53.1ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 480)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics/runs/detect/predict2

```

**Comment by glenn-jocher** [comment]
@Laughing-q oh so I realized the warnings are unrelated to loading models, i.e. i get them even when just checking settings:

```
yolo settings

WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.cfg' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.cfg' instead.
Printing '/Users/glennjocher/Library/Application Support/Ultralytics/settings.yaml'

datasets_dir: /Users/glennjocher/PycharmProjects/datasets
weights_dir: /Users/glennjocher/PycharmProjects/ultralytics/weights
runs_dir: /Users/glennjocher/PycharmProjects/ultralytics/runs
uuid: cb7aabe58c0c190db3a5a1ab1c2d66cc0aa9f2a979a3ec5aa00036a8e0c3d628
sync: true
api_key: ac0ab020186aeb50cc4c2a5272de17f58bbd2c05b5
settings_version: 0.0.3

```

**Comment by glenn-jocher** [comment]
@Laughing-q oh so I realized the warnings are unrelated to loading models, i.e. i get them even when just checking settings:

```
yolo settings

WARNING ⚠️ 'ultralytics.yolo.v8' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.models.yolo' instead.
WARNING ⚠️ 'ultralytics.yolo.cfg' is deprecated since '8.0.136' and will be removed in '8.1.0'. Please use 'ultralytics.cfg' instead.
Printing '/Users/glennjocher/Library/Application Support/Ultralytics/settings.yaml'

datasets_dir: /Users/glennjocher/PycharmProjects/datasets
weights_dir: /Users/glennjocher/PycharmProjects/ultralytics/weights
runs_dir: /Users/glennjocher/PycharmProjects/ultralytics/runs
uuid: cb7a...
sync: true
api_key: ac0...
settings_version: 0.0.3
```

**Comment by Laughing-q** [comment]
@glenn-jocher oh I didn't test cli mode. Detection and segmentation model loading is fine but pose and classify would still raise this warning msg.

**Comment by glenn-jocher** [comment]
@Laughing-q yeah it looks like pose and cls models have these paths inside them for some reason. Maybe I can remove them without affecting backwards compatibility, not sure.

Screenshot 2023-07-16 at 14 24 35

**Comment by glenn-jocher** [comment]
@Laughing-q ok I've implemented a context manager when loading models to give them temprorary access to the older module paths they need. We need 3 older modules for the Pose and Classify models. 

The Pose problem is that we are saving model.args as an IterableSimpleNamespace, which is a new class I created more recently that the older Detect, Segment models lack. This class is very easy to conver to a dict though (as in the older models, so I'll do that for the Pose models and re-upload those assets. This will be both forward and backward compatible and should reduce the older modules we need from 3 to 2 or 1.

Then I'll take a closer look at the Classify models. That have dataloader transforms attached which is probably causing the issue, not sure if there is a workaround there.

**Comment by glenn-jocher** [comment]
@Laughing-q ok I think this is all set. I've updated the Pose model assets and now we only need to temporarily import one older module when loading Classify files. 

The Classify files use CenterCrop and ToTensor modules in their transform attributes, but unfortunately these are are own custom classes instead of torchvision modules. If we could replace these custom classes with torchvision classes in the future that would probably be ideal, then we could eliminate any custom module paths on import for cls models also.

If this all looks good I'll go ahead and merge!

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel should we delete the dataloaders directory here? It only has 1 file in it.

Screenshot 2023-07-16 at 17 04 37

**Comment by AyushExel** [comment]
@glenn-jocher that file is used for loading the inference images, so if we delete that folder that file still needs to be somewhere

**Comment by glenn-jocher** [comment]
@AyushExel ah yes, I just meant we could bring it up a level. But we could also do the opposite, place the training dataloaders inside there.

**Comment by Laughing-q** [comment]
@glenn-jocher loading old pose model still gives me warning.
image

**Comment by AyushExel** [comment]
> @AyushExel ah yes, I just meant we could bring it up a level. But we could also do the opposite, place the training dataloaders inside there.

Let's move this file, as it'll be fewer changes compared to moving all data loader files? @Laughing-q ?

**Comment by Laughing-q** [comment]
> ah yes, I just meant we could bring it up a level. But we could also do the opposite, place the training dataloaders inside there.

@glenn-jocher moving it to `data/` folder would be the easiest way to do it I think.

**Comment by Laughing-q** [comment]
@AyushExel yeah exactly

**Comment by Laughing-q** [comment]
@glenn-jocher I tried reverting this commit then old pose model also works to me without any warnings. https://github.com/ultralytics/ultralytics/pull/3748/commits/04a39c44e7d153a037e097eda10267fc4a06aa5f

**Comment by glenn-jocher** [comment]
> @glenn-jocher I tried reverting this commit then old pose model also works to me without any warnings. [04a39c4](https://github.com/ultralytics/ultralytics/commit/04a39c44e7d153a037e097eda10267fc4a06aa5f)

Yeah, you're right I forgot we need these for all the older Pose models. I'll revert it.

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel @fcakyon refactor PR merged!!!! This is a huge step, I think this should keep things more organized for future growth.

**Comment by sschamp** [comment]
Q/
Since when are refactors like this done with a patch version bump?
Anyone using ~= in their requirements.txt will have gotten a breaking change.

Please read up on SemVer ;) https://semver.org

```
Collecting ultralytics~=8.0.53
Downloading ultralytics-8.0.126-py3-none-any.whl (612 kB)
```


Turned into:

```
Collecting ultralytics~=8.0.53
Downloading ultralytics-8.0.143-py3-none-any.whl (604 kB)
```


We use ~= to ensure we get the latest security fixes, without expecting to have backward-compatibility breaking changes.

**Comment by Laughing-q** [comment]
@sschamp Thanks for the information! Don't worry, these updates are fully backward compatible. :)
If you encounter any issues about breaking changes, please let us know. :)

**Comment by sschamp** [comment]
> @sschamp Thanks for the information! Don't worry, these updates are fully backward compatible. :)
> If you encounter any issues about breaking changes, please let us know. :)

`AttributeError: module 'ultralytics' has no attribute 'yolo'`

Failed our builds, so I went looking into the commit history and found these breaking changes.

**Comment by Laughing-q** [comment]
@sschamp ah that's strange...we still keep the `yolo` folder for backward compatibility.
mK5TlJhhr4
and I just tested `ultralytics.yolo` with the latest version and it works with no errors but warnings to me:
pic-230728-2034-13
can you tell me what's your usage like? probably we missed some usages in our tests.

**Comment by MuriloVenturin** [comment]
I work with @sschamp  who mentioned the problem in the comment above. The result of YOLO was the return of a method and it was typed as: `ultralytics.yolo.engine.results.Results`

Then we got the error: `AttributeError: module 'ultralytics' has no attribute 'yolo'`

@Laughing-q  try to import ultralytics.yolo.engine.results.Results, I believe you will be able to reproduce the problem.

**Comment by Laughing-q** [comment]
@MuriloVenturin strange...I'm still not able to reproduce it...
pic-230801-2046-38

**Comment by MuriloVenturin** [comment]
Correct, if we import the way you did there are no problems, but when I import just ultralytics and try to access classes and methods from there the problem happens

image

**Pull request merged**
