### PR TITLE
Correct SAHI definition from "Slicing, Analysis, and Healing of Images" to "Slicing Aided Hyper Inference"

### PR DESCRIPTION
**Pull request by felipe-parodi**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to the README file of the YOLOv8-SAHI-Inference-Video example to correct the definition of SAHI.

### 📊 Key Changes
- Corrected the acronym for SAHI from "Slicing, Analysis, and Healing of Images" to "Slicing Aided Hyper Inference."

### 🎯 Purpose & Impact
- **Accuracy**: Ensures that the documentation accurately reflects the correct name of the SAHI library.
- **Clarity**: Helps users better understand the functionality and purpose of the SAHI library when used with YOLOv8.

🔍📘

### CODE REVIEW

**Comment by felipe-parodi** [comment]
I have read the CLA Document and I sign the CLA

**Comment by felipe-parodi** [comment]
recheck

**Comment by glenn-jocher** [comment]
@felipe-parodi thank you for the correction!

**Comment by glenn-jocher** [comment]
@felipe-parodi PR merged, thank you for your contributions!

@fcakyon FYI acronym correction on SAHI here.

**Pull request merged**
