### PR TITLE
Added AP60 and mAP60 metrics to Metric class properties

### PR DESCRIPTION
**Pull request by vladimir-sashin**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced object detection metrics with added precision at IoU 0.6.

### 📊 Key Changes
- 🆕 New method `ap60()` added to calculate AP at IoU threshold 0.6 for all classes.
- 📈 New method `map60()` included to compute mean AP at IoU threshold 0.6.

### 🎯 Purpose & Impact
- 🎯 **Purpose:** To provide users with more granular control and evaluation metrics at different IoU thresholds, specifically at 0.6 which is stricter than the usual 0.5 but more lenient than 0.75.
- 🔍 **Impact:** Enables users and researchers to better understand model performance at various intersection thresholds, which could lead to more targeted improvements in object detection models.

### CODE REVIEW

**Comment by vladimir-sashin** [comment]
I have read the CLA Document and I sign the CLA

**Comment by vladimir-sashin** [comment]
recheck

**Comment by vladimir-sashin** [comment]
I'm sorry, made this PR by mistake.

**Comment by glenn-jocher** [comment]
@vladimir-sashin hi there! 

No worries, mistakes happen! If you made a pull request (PR) by mistake, you can simply close the PR and let us know if you have any questions or concerns. If there's anything else we can assist you with, please feel free to reach out. 

Thank you for your understanding!

**Pull request closed without merging**
