### PR TITLE
fix overlap_mask

### LINKED ISSUE #618: Option:  overlap_mask=False is available now?
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hi, I have a question about overlap_mask option,

Every time I run inference with this parameter set, I get an error message like below.
What is the cause of this?
I checked to see if there was a problem with my training label, but I didn't see anything odd.
Is this option not currently active?

Thank you.

```Transferred 381/417 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.001), 76 bias
train: Scanning /content/drive/MyDrive/roboflow/labels/train... 1047 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1047/1047 [11:48<00:00,  1.48it/s]
train: New cache created: /content/drive/MyDrive/roboflow/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /content/drive/MyDrive/roboflow/labels/val.cache... 7 images, 0 backgrounds, 0 corrupt: 100%|██████████| 7/7 [00:00<?, ?it/s]
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/segment/train3
Starting training for 250 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/66 [00:09<?, ?it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-1-7c2c22b68905>](https://localhost:8080/#) in <module>
      6 
      7 # Use the model
----> 8 results = model.train(data="data.yaml", epochs=250,imgsz=640,Transferred 381/417 items from pretrained weights
optimizer: SGD(lr=0.01) with parameter groups 66 weight(decay=0.0), 77 weight(decay=0.001), 76 bias
train: Scanning /content/drive/MyDrive/roboflow/labels/train... 1047 images, 0 backgrounds, 0 corrupt: 100%|██████████| 1047/1047 [11:48<00:00,  1.48it/s]
train: New cache created: /content/drive/MyDrive/roboflow/labels/train.cache
albumentations: Blur(p=0.01, blur_limit=(3, 7)), MedianBlur(p=0.01, blur_limit=(3, 7)), ToGray(p=0.01), CLAHE(p=0.01, clip_limit=(1, 4.0), tile_grid_size=(8, 8))
val: Scanning /content/drive/MyDrive/roboflow/labels/val.cache... 7 images, 0 backgrounds, 0 corrupt: 100%|██████████| 7/7 [00:00<?, ?it/s]
Image sizes 640 train, 640 val
Using 2 dataloader workers
Logging results to runs/segment/train3
Starting training for 250 epochs...

      Epoch    GPU_mem   box_loss   seg_loss   cls_loss   dfl_loss  Instances       Size
  0%|          | 0/66 [00:09<?, ?it/s]
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
[<ipython-input-1-7c2c22b68905>](https://localhost:8080/#) in <module>
      6 
      7 # Use the model
----> 8 results = model.train(data="data.yaml", epochs=250,imgsz=640,overlap_mask=False )  # train the model
      9 #results = model.val()  # evaluate model performance on the validation set
     10 #results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image

4 frames
[/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/segment/train.py](https://localhost:8080/#) in __call__(self, preds, batch)
    115                         gt_mask = torch.where(masks[[i]] == mask_idx.view(-1, 1, 1), 1.0, 0.0)
    116                     else:
--> 117                         gt_mask = masks[batch_idx == i][mask_idx]
    118                     xyxyn = target_bboxes[i][fg_mask[i]] / imgsz[[1, 0, 1, 0]]
    119                     marea = xyxy2xywh(xyxyn)[:, 2:].prod(1)

IndexError: The shape of the mask [73, 1] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0 )  # train the model
      9 #results = model.val()  # evaluate model performance on the validation set
     10 #results = model("https://ultralytics.com/images/bus.jpg")  # predict on an image

4 frames
[/usr/local/lib/python3.8/dist-packages/ultralytics/yolo/v8/segment/train.py](https://localhost:8080/#) in __call__(self, preds, batch)
    115                         gt_mask = torch.where(masks[[i]] == mask_idx.view(-1, 1, 1), 1.0, 0.0)
    116                     else:
--> 117                         gt_mask = masks[batch_idx == i][mask_idx]
    118                     xyxyn = target_bboxes[i][fg_mask[i]] / imgsz[[1, 0, 1, 0]]
    119                     marea = xyxy2xywh(xyxyn)[:, 2:].prod(1)

IndexError: The shape of the mask [73, 1] at index 0 does not match the shape of the indexed tensor [16, 160, 160] at index 0
```

``` 
# bbox loss
        if fg_mask.sum():
            loss[0], loss[3] = self.bbox_loss(pred_distri, pred_bboxes, anchor_points, target_bboxes / stride_tensor,
                                              target_scores, target_scores_sum, fg_mask)
            for i in range(batch_size):
                if fg_mask[i].sum():
                    mask_idx = target_gt_idx[i][fg_mask[i]] + 1
                    if self.overlap:
                        gt_mask = torch.where(masks[[i]] == mask_idx.view(-1, 1, 1), 1.0, 0.0)
                    else:
                        gt_mask = masks[batch_idx == i][mask_idx]
                    xyxyn = target_bboxes[i][fg_mask[i]] / imgsz[[1, 0, 1, 0]]
                    marea = xyxy2xywh(xyxyn)[:, 2:].prod(1)
                    mxyxy = xyxyn * torch.tensor([mask_w, mask_h, mask_w, mask_h], device=self.device)
                    loss[1] += self.single_mask_loss(gt_mask, pred_masks[i][fg_mask[i]], proto[i], mxyxy,
                                                     marea)  # seg loss
```

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
@AyushExel @glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced data augmentation with mask ratio and overlap options.

### 📊 Key Changes
- Introduced new hyperparameters `mask_ratio` and `mask_overlap` for better control over data augmentation.
- Adjusted mask index handling to accommodate the new overlap feature.

### 🎯 Purpose & Impact
- 🎨 The new hyperparameters allow for fine-tuning the data augmentation process, potentially improving model performance on tasks involving segmentation.
- 🛠️ The modifications may improve model training stability and accuracy by providing more realistic training examples.
- 🌐 Users with datasets that require precise mask augmentation will benefit greatly from these changes.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q awesome! Merging into PR for 8.0.21 later tonight.

**Comment by takyq** [comment]
It worked completely fine!
Thank you so much.

**Comment by pderrenger** [comment]
@takyq glad to hear that everything is working fine for you! If you have any more questions or need further assistance, feel free to ask. Great job, and thanks for using YOLOv8!

**Comment by cobaltautomationdev** [comment]
Thanks, guys, I got the point about the parameter overlap_mask=True or False. if true, it will ignore the overlap mask. if false, it will keep the mask of overlap instance.

**Comment by glenn-jocher** [comment]
@cobaltautomationdev That's correct! When `overlap_mask` is set to `True`, overlapping masks are ignored to ensure that each pixel is assigned to only one class, typically the one with a higher confidence score. However, when `overlap_mask` is set to `False`, pixels can belong to multiple class masks, allowing you to retain the overlap. This is useful for certain scenarios where class hierarchy or intersection is important. Remember, you can toggle this according to your specific use case requirements. Don't hesitate to reach out if there's anything else! 😊👍

**Pull request merged**
