### PR TITLE
Decouple dataset and dataloader

### PR DESCRIPTION
**Pull request by Laughing-q**
@glenn-jocher @AyushExel Decouple dataset and dataloader to `build_dataset` and `build_dataloader` for more flexible customization. 
Also I removed `build_classify_dataloader` and now detect/segment/pose is sharing `build_dataloader` with classify task which reduces maintenance costs.
example usage:
```python
from ultralytics.yolo.v8 import DetectionTrainer
from ultralytics.yolo.data import BaseDataset

class CustomDataset(BaseDataset):
    def build_transforms(self, ...):
        pass

class CustomTrainer(DetectionTrainer):
    def build_dataset(self, image_path):
        pass
# trainer
trainer = CustomTrainer(overrides={})
trainer.train()
```

### Summary
🗑️🛠️🔄

This pull request refactors the dataset building logic for the `ultralytics/yolo` package, making it more modular, reusable, and dynamic. It also removes the unused and deprecated `image_weights` option from the configuration files and the code, and improves the documentation of some classes and methods. The changes affect the `ultralytics/yolo/data`, `ultralytics/yolo/engine`, and `ultralytics/yolo/v8` modules, as well as the `docs/usage/cfg.md` file.

> _`image_weights` gone_
> _simplify configuration_
> _spring cleaning the code_

### Walkthrough
*  Remove the unused and deprecated `image_weights` option from the configuration files and code ([link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-a21b6f90c80bba2698f9a8e30b1a002078a425376e5eb2864f078e0a97d32a3bL97), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-daf1714127b012666c9fed39d0e75184c60be83f0c6bd3f9863f27113b1a6c22L72-R72), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-9d692d4ad15d420a92105fcd432fb1d2221b71d5af055bea3bd2b70523ce6743L28))
*  Refactor the dataset building logic and make it more modular and reusable, by introducing new functions and classes in the `ultralytics.yolo.data` package, such as `build_dataloader`, `build_yolo_dataset`, `ClassificationDataset`, and `InfiniteDataLoader` ([link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-63088a4a4384c21a3f08321d13a9b5eaf414756ae4618b82f68e479039f79bb7L4-R4), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-d4f87aa47a90813d564caeabb5ae15de1efa1d46df10306d374cbc1fac29fd2fL27-R37), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL10-R10), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL17-R17), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL41-R47), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL67-R110), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-9e341b944998965225e7749684518d7461f0a0ebc7e6dd53502ca840fb4e686fL24-R26), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-9e341b944998965225e7749684518d7461f0a0ebc7e6dd53502ca840fb4e686fL47-R44))
*  Enable dynamic changes of the dataset parameters during training and validation, by resetting the data loader iterator after each epoch, and using the `torch_distributed_zero_first` function to ensure the dataset cache is initialized only once if using distributed data parallel ([link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1R299), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-734f7c7d5e997138ddb17cffc50e37008364bb3fdba26403ee9d145ce2764f69L8-R11), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L10-R18))
*  Define abstract `build_dataset` methods in the `BaseTrainer` and `BaseValidator` classes, and implement them in the subclasses for classification and detection tasks, using the new functions and classes from the `ultralytics.yolo.data` package ([link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1R484-R487), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-7646fc7a670fe6bbcbf9e637a707139b362bd3b118be7faca28bff7d9b7450c3R210-R213), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-734f7c7d5e997138ddb17cffc50e37008364bb3fdba26403ee9d145ce2764f69L74-R83), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-96394c180886ae66c7b7b74458274315cc049499272c79ecf2ef04e34315f2fcL3-R3), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-96394c180886ae66c7b7b74458274315cc049499272c79ecf2ef04e34315f2fcL55-R62), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L24-R64), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02L9-R9), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-6e518634bff3eacf0c8b7755670115753754e2b4987f0a323bd54a0b83707f02L174-R206))
*  Update the docstrings of the `BaseDataset` and `YOLODataset` classes to make them more consistent and informative ([link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-d4f87aa47a90813d564caeabb5ae15de1efa1d46df10306d374cbc1fac29fd2fL27-R37), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-9e341b944998965225e7749684518d7461f0a0ebc7e6dd53502ca840fb4e686fL24-R26))
*  Remove the unused imports of `torch`, `DataLoader`, and `LOGGER` from the `ultralytics/yolo/data/build.py` file ([link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL10-R10), [link](https://github.com/ultralytics/ultralytics/pull/2212/files?diff=unified&w=0#diff-0826103e946e6152ff49d963d1235653adbfbf515878db39fdae798c3a15469fL17-R17))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
PR refactors data loader building and dataset configuration functions in YOLO.

### 📊 Key Changes
- Removed dependency on `numpy` in `requirements.txt`.
- Deleted `image_weights` option from YOLO config `default.yaml`.
- Replaced `build_classification_dataloader` with `build_dataloader` and `build_yolo_dataset`.
- Simplified `BaseDataset` class and `YOLODataset` construction methods with `*args, **kwargs`.
- Implemented `build_dataset` function stubs in `trainer.py` and `validator.py`.
- Enhanced plotting functionality with text box styles in `plotting.py`.
- Updated `train.py` and `val.py` for both classification and detection to use new data loader and dataset build functions.

### 🎯 Purpose & Impact
- 💼 **Maintainability:** Refactoring code to use more general functions and simplify classes improves code maintainability.
- 🚀 **Performance:** Removing redundant data preprocessing steps could potentially speed up dataset preparation.
- ✅ **Compatibility:** The removal of `numpy` in requirements reduces potential dependency conflicts.
- 🌐 **Flexibility:** Allowing `BaseDataset` and subclasses to initialize with arbitrary arguments (`*args` and `**kwargs`) permits more customized dataset configurations.
- 📉 **Reduction in Redundancy:** Merging multiple functions into generalized ones eliminates duplicate code lines.
- 🎨 **Visualization Improvements:** Plotting enhancements may lead to more informative visualization of model results and training data.

### CODE REVIEW

**Comment by Laughing-q** [comment]
just noticed this branch is based on my main branch😂, it has the same updates in #2206.

**Comment by Laughing-q** [comment]
supports `plot_images` and `plot_results` for classify task.
train_batch sample:
train_batch0
val_batch sample:
val_batch0_labels
result sample:
results

**Comment by AyushExel** [comment]
@Laughing-q perfect! looks good. The meituan link from the docs seems to be broken but which might be unrelated to this branch.
Also, I remember our discussion around pre trained arg. Is it working fine? I see the top1 and top5 accuracies are both low. Is it a problem that you're seeing or it's just because of the dataset?

**Comment by Laughing-q** [comment]
@AyushExel it works perfectly with pretrained weight. The curves above is just a sample generated by our example data imagenet100.

**Comment by glenn-jocher** [comment]
@Laughing-q super cool! I like the Classify mosaic!

**Pull request merged**
