### PR TITLE
Add `bgr` hyperparameter

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing the new `bgr` augmentation for versatile image processing!

### 📊 Key Changes
- Added `bgr` augmentation option across documentation, configs, and augmentation code.
- Augmentation involves flipping image channels from RGB to BGR with a specified probability.

### 🎯 Purpose & Impact
- **Enhanced Model Robustness**: Flipping channels from RGB to BGR aims to increase a model's robustness to incorrect channel ordering, a common issue in image processing tasks.
- **Dataset Diversity**: By introducing variability in the channel ordering, the `bgr` augmentation adds an extra layer of complexity, helping models learn more generalized features.
- **Flexible Usage**: The probability-based activation allows users to tailor the augmentation's intensity according to their dataset and model requirements, ensuring broad applicability across different scenarios.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher benchmark CI test is failing due to the download failure of pnnx.
pic-240320-1022-11

**Comment by glenn-jocher** [comment]
> @glenn-jocher benchmark CI test is failing due to the download failure of pnnx. pic-240320-1022-11

Thanks, got it. Yes I thought I'd fixed the PNNX download issue, it's due to rate limiting, but it seems I haven't fixed it fully.

**Comment by glenn-jocher** [comment]
@Laughing-q updated docs, everything looks good! Interested to see the lower 0.1 and 0.2 experiment results. Merging now!

**Comment by Laughing-q** [comment]
Experiment results:
| model             | mAP(RGB) | mAP(BGR) |
|-------------------|----------|----------|
| `yolov8n.pt`        | 37.7     | 33.8     |
| `yolov8n-bgr0.5.pt` | 37.2     | 37.2     |
| `yolov8n-bgr0.2.pt` | 37.3     | 37.1     |
| `yolov8n-bgr0.1.pt` | 37.3     | 36.7     |

**Pull request merged**
