### PR TITLE
Add Slicing Aided Hyper Inference (SAHI) to Docs Guides

### PR DESCRIPTION
**Pull request by WangQvQ**
Hello, I am an avid user of YOLOv8, and I recently found an interesting thing called slicing-aided-hyper-inference. I tried it with YOLOv8, and the effect was amazing. I can't help but share it with you, and I can contribute code if possible!

By the way. slicing-aided-hyper-inference does not need to change any file of the source code, it can be used directly!

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of SAHI for sliced inference in YOLOv8.

### 📊 Key Changes
- Added keywords "SAHI" and "Tiled Inference" for better discoverability.
- New documentation on using SAHI with YOLOv8 for sliced inference.
- Instructions for installation, standard and sliced inference, result handling, and batch processing with SAHI.

### 🎯 Purpose & Impact
- **Enhanced Usability for High-Resolution Images:** Allows better handling of large-scale images by slicing them into manageable pieces.
- **Improved Performance:** Reduces computational load, enabling the use of YOLOv8 on systems with less processing power.
- **Ease of Access:** Provides a comprehensive guide for users to leverage SAHI with YOLOv8, potentially expanding the model's applicability.
- **Batch Inference:** Streamlines the prediction process for image directories, boosting efficiency for larger projects.

### CODE REVIEW

**Comment by WangQvQ** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@WangQvQ thank you for the PR! 

@fcakyon can you review this please? Thank you!

**Comment by glenn-jocher** [comment]
@WangQvQ PR merged! Thank you for your contributions to YOLO :)

**Comment by fcakyon** [comment]
@WangQvQ amazing contribution!

**Pull request merged**
