### PR TITLE
Add new K-Fold cross validation guide in Docs

### PR DESCRIPTION
**Pull request by Burhan-Q**
New docs guide for performing KFold Cross Validation

Initial draft, needs review

### Summary
:memo::information_source::bookmark:

Added a header with metadata to the guide on `kfold_cross_validation.md`. This improves the readability and documentation of the guide, which explains how to use the Ultralytics library for object detection with K-Fold cross validation.

> _`Header` added_
> _Metadata for object detection_
> _Guide for k-fold `cross`_

### Walkthrough
* Added a header with author, date, and title information for the markdown document on K-Fold cross validation ([link](https://github.com/ultralytics/ultralytics/pull/3975/files?diff=unified&w=0#diff-5bde2e917098d4dfa3a8cace31911c63bd6409c1b574e64f4d2fb3e079e418d7R1-R294))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Ultralytics adds comprehensive tutorials and K-Fold Cross Validation guides, enhancing the YOLO documentation and model training robustness.

### 📊 Key Changes
- Added a tutorial section with guides for using YOLO in various aspects.
- Published an in-depth guide on implementing K-Fold Cross Validation within the Ultralytics ecosystem for object detection datasets.
- Refined internal documentation links and clarified integration instructions.

### 🎯 Purpose & Impact
- **For tutorials**: To assist users from novice to expert levels in understanding and utilizing YOLO models effectively in their projects.
- **For K-Fold Cross Validation**: To improve model reliability by demonstrating how to split datasets properly for training robust and generalizable object detection models.
- **Improved documentation usability**: By fixing and updating links, users are ensured smoother navigation and better access to resources within the Ultralytics documentation, enhancing the overall learning and development experience.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q super interesting! Ok I'll take a look when a get a bit of time.

**Comment by glenn-jocher** [comment]
@Burhan-Q ok this is all set. I've:

- Cleaned up the tutorial a bit.
- Removed author and date and the Ultralytics MkDocs plugin (https://github.com/ultralytics/mkdocs) parses and adds those automatically to our Docs at the bottom of each page.
- Replaced underscores with dashes (files use underscores, web uses dashes)
- Added the page to the mkdocs.yml file so they are recognized and added to docs.
- Added an index.md page to the guides/ directory so if someone just goes straight to /guides they see something and not a 404.
- Addressed a few minor MkDocs warnings.

TODO: Please make any edit of any kind to the new kfold-cross-validation.md file as I think in renaming it your authorship may have gotten stripped. If you make one new commit to it then we should be all set and you should automatically show in the authorship. 

Thanks!

**Comment by glenn-jocher** [comment]
@Burhan-Q please make an edit somewhere in the new kfold-cross-validation.md file as I think in renaming it your authorship may have gotten stripped. 

If you make one new commit to it then we should be all set and you should automatically show in the authorship. Then I can merge. Thanks!

**Comment by glenn-jocher** [comment]
@Burhan-Q awesome, PR merged! Nice work on this :)

**Comment by WangQvQ** [comment]
Good work, but I encountered a problem in use, which led to the code can not read the image, the original code is as follows:
`images = sorted((dataset_path / 'images').rglob("*.jpg"))`
Here are the changes I made：
`images = sorted(dataset_path.rglob("*images/*.jpg"))`
I don't know if this is caused by my improper use. If possible, can I contribute the code?

**Comment by Burhan-Q** [comment]
@WangQvQ 

> Good work, but I encountered a problem in use, which led to the code can not read the image, the original code is as follows:
> `images = sorted((dataset_path / 'images').rglob("*.jpg"))`
> Here are the changes I made：
> `images = sorted(dataset_path.rglob("*images/*.jpg"))`
> I don't know if this is caused by my improper use. If possible, can I contribute the code?

If I understand correctly, I think the issue you experienced is due to additional subdirectories.The assumption made for this guide was that all images are located in a single directory directly under the dataset path to simplify writing (same with the labels).

```
dataset_path
 | __ images
          | __ *. jpg 
 | __ labels
          | __ *.txt
```

If you are using directory names that are different, such as `my_images` as an example, then the modification you used would be appropriate. If instead your directory uses the same structure and names as the example, then there may be something else problematic, so please share your error so I can investigate.

I do have some additional edits that I want to make to the guide, so I will consider including additional content to make the example directory structure more clear. Obviously it will be impossible to account for all possible user configurations, and is left as an exercise for the reader to adapt the process of the guide to their specific circumstance. 

Glad you found the guide useful! If I misunderstood your concern, please help me to better understand. Thank you

**Pull request merged**
