### PR TITLE
Add `estimate_speed(region_color)` parameter

### PR DESCRIPTION
**Pull request by hisushanta**
## 🌞Summary:
Simple parameter to change the colour of the origin.

## 🗝️Key Changes
Enable to set colour for specific situations.

## 🎯Purpose & Impact
* Like everyone to change the origin colour when he or she builds an estimated speed project.
* And it's more flexible for the old one.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to speed estimation visualizations in Ultralytics solutions.

### 📊 Key Changes
- Added `region_color` parameter to the `estimate_speed` function to customize the color of the drawn regions.
- Adjusted internal use of the region color within the `estimate_speed` method to apply the new `region_color` parameter instead of a hardcoded value.

### 🎯 Purpose & Impact
- 🎨 Allows users to adjust the visual appeal of their analytics by changing the region color when performing speed estimation on video or image data.
- 🛠 Increases flexibility in the presentation layer of speed estimation, which could be beneficial for users needing to differentiate between various annotated regions or adhering to brand guidelines.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@hi-sushanta thanks for the PR! The addition of a `colors` parameter to customize the origin color is a great touch for personalization and clarity in speed estimation projects. It's always nice to see features that enhance user experience and flexibility. 👍 If anyone needs an example of how to use the new parameter, feel free to ask! 🎨🚀

**Comment by hi-sushanta** [comment]
> @hi-sushanta thanks for the PR! The addition of a `colors` parameter to customize the origin color is a great touch for personalization and clarity in speed estimation projects. It's always nice to see features that enhance user experience and flexibility. 👍 If anyone needs an example of how to use the new parameter, feel free to ask! 🎨🚀

Yes Of course.

**Comment by glenn-jocher** [comment]
@hi-sushanta thank you for your suggestion to add a parameter for color changes to the origin in the Ultralytics YOLOv8 repository. It sounds like you're proposing a feature that allows users to customize the color of the origin point in visualizations, which could be particularly useful in projects that estimate speed or require specific color coding for clarity.

To proceed with this suggestion, you could open a new issue on the GitHub repository with the following details:

1. **Title**: Feature Request: Customizable Origin Color Parameter
2. **Comment**:
   - **Summary**: Introduce a simple parameter to change the color of the origin in visualizations.
   - **Key Changes**: Add a new argument to enable setting a custom color for the origin.
   - **Purpose & Impact**:
     - Allow users to change the origin color to suit specific project needs, such as speed estimation visualizations.
     - Increase flexibility and customization options for users.

By opening an issue, you provide the Ultralytics team and the community with the opportunity to discuss the potential feature, its implementation, and its benefits. If the feature is well-received, it could be added to the project roadmap and eventually implemented.

Remember, when contributing ideas or code to open-source projects, it's important to follow the project's contribution guidelines and to communicate clearly and respectfully with the maintainers and community members.

**Comment by hi-sushanta** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@hi-sushanta PR merged, thank you for your contributions!

**Comment by hi-sushanta** [comment]
You're welcome🫡

**Comment by glenn-jocher** [comment]
@hi-sushanta thank you for the kind words! If you have any more questions or need assistance, just let us know. Happy coding! 😊🚀

**Pull request merged**
