### PR TITLE
Better assertion error for exported model batch size

### LINKED ISSUE #16931: Batch error with TensorRT Inference
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Predict, Export

### Bug

Exporting a model to tensort with an arbitrary batch size does not take the batch size into account during inference, resulting in a not-so-understandable error. Probably we should check the metadata from the exported model to ensure every argument is correct before actually doing the inference, in case users encounter the unreadable error.

### Environment

```
Ultralytics 8.3.13 🚀 Python-3.10.0 torch-2.4.1+cu121 CUDA:0 (NVIDIA GeForce RTX 3060, 11938MiB)
Setup complete ✅ (6 CPUs, 31.3 GB RAM, 516.3/574.7 GB disk)

OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.0
Install             git
RAM                 31.29 GB
Disk                516.3/574.7 GB
CPU                 Intel Core(TM) i5-8600K 3.60GHz
CPU count           6
GPU                 NVIDIA GeForce RTX 3060, 11938MiB
GPU count           1
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.10.0.84>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.4.1>=1.8.0
torchvision         ✅ 0.19.1>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
torch               ✅ 2.4.1!=2.4.0,>=1.8.0; sys_platform == "win32"
```

### Minimal Reproducible Example

Export:
`yolo export model=yolo11n.pt format=engine batch=2`
Inference 
`yolo predict model=yolo11n.engine batch=1`

### Additional

unreadable error from tensorrt package:
```bash
Loading yolo11n.engine for TensorRT inference...
[10/15/2024-16:56:56] [TRT] [I] Loaded engine size: 16 MiB
[10/15/2024-16:56:56] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +36, now: CPU 0, GPU 48 (MiB)

[10/15/2024-16:56:56] [TRT] [E] IExecutionContext::setInputShape: Error Code 3: API Usage Error (Parameter check failed, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape for images. Set dimensions are [1,3,640,640]. Expected dimensions are [2,3,640,640].)
[10/15/2024-16:56:56] [TRT] [E] IExecutionContext::executeV2: Error Code 1: Cuda Runtime (an illegal memory access was encountered)
Traceback (most recent call last):
  File "/home/laughing/anaconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/cfg/__init__.py", line 799, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/predictor.py", line 184, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/predictor.py", line 250, in stream_inference
    with profilers[0]:
  File "/home/laughing/codes/ultralytics/ultralytics/utils/ops.py", line 46, in __enter__
    self.start = self.time()
                 ^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/utils/ops.py", line 61, in time
    torch.cuda.synchronize(self.device)
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 892, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by ambitious-octopus**

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@ambitious-octopus not sure if this is right, the TRT --dynamic models can run up to a fixed batch size, they don't need to be equal.

**Comment by Laughing-q** [comment]
@glenn-jocher Yes you are right.
One question though, what's the case when the model is not dynamic but `im.shape != self.bindings["images"].shape`? I saw the if-else flow here considering two cases(dynamic or shape difference):
https://github.com/ultralytics/ultralytics/blob/af5f2473a9b020b1d5c3e57bed35e44774c9a03d/ultralytics/nn/autobackend.py#L504
The error info that @ambitious-octopus was trying to handle is when the model is static but user passes a different batch size. And the condition here is `or` then the input is still resized even it's a static model, then appears the unreadable error from TensorRT.
```bash
yolo export model=yolo11n.pt format=engine batch=2
yolo predict model=yolo11n.engine batch=1
```
```bash
Loading yolo11n.engine for TensorRT inference...
[10/15/2024-16:56:56] [TRT] [I] Loaded engine size: 16 MiB
[10/15/2024-16:56:56] [TRT] [I] [MemUsageChange] TensorRT-managed allocation in IExecutionContext creation: CPU +0, GPU +36, now: CPU 0, GPU 48 (MiB)

[10/15/2024-16:56:56] [TRT] [E] IExecutionContext::setInputShape: Error Code 3: API Usage Error (Parameter check failed, condition: engineDims.d[i] == dims.d[i]. Static dimension mismatch while setting input shape for images. Set dimensions are [1,3,640,640]. Expected dimensions are [2,3,640,640].)
[10/15/2024-16:56:56] [TRT] [E] IExecutionContext::executeV2: Error Code 1: Cuda Runtime (an illegal memory access was encountered)
Traceback (most recent call last):
  File "/home/laughing/anaconda3/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
             ^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/cfg/__init__.py", line 799, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/model.py", line 554, in predict
    return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/predictor.py", line 184, in predict_cli
    for _ in gen:  # sourcery skip: remove-empty-nested-block, noqa
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 36, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/predictor.py", line 250, in stream_inference
    with profilers[0]:
  File "/home/laughing/codes/ultralytics/ultralytics/utils/ops.py", line 46, in __enter__
    self.start = self.time()
                 ^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/utils/ops.py", line 61, in time
    torch.cuda.synchronize(self.device)
  File "/home/laughing/anaconda3/lib/python3.11/site-packages/torch/cuda/__init__.py", line 892, in synchronize
    return torch._C._cuda_synchronize()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: an illegal memory access was encountered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
```
Is it ok we update this to `self.dynamic and im.shape != self.bindings["images"].shape`? and then add an assert to check if it's dynamic when the shapes are different.

**Comment by Laughing-q** [comment]
@ambitious-octopus @glenn-jocher ok I saw there's a `and` to `or` change in the TRT10 PR. https://github.com/ultralytics/ultralytics/pull/9516

**Comment by Laughing-q** [comment]
@ambitious-octopus @glenn-jocher Submitted a PR to fix this. https://github.com/ultralytics/ultralytics/pull/16953
@ambitious-octopus In that PR the input wouldn't be resized if it's not a dynamic model and then we actually have a assert handling the error.
image

**Review by ambitious-octopus — COMMENTED** [review]
Thanks @Laughing-q, closing this one!

**Pull request closed without merging**
