### PR TITLE
unify write_results&&eliminate duplicated code

### LINKED ISSUE #1904: Result image is not saved in cli mode
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

I am using the latest version of Ultralytics YOLOv8 (8.0.70) with Anaconda on Windows.
 When I entered the command yolo predict model=yolov8n.pt source=image1.jpg` in the CLI mode, the inference was made successfully but the resulting image was not saved.

image

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
@glenn-jocher @AyushExel 
- eliminate duplicated code in `write_results`.
- fix [https://github.com/ultralytics/ultralytics/issues/1904#issuecomment-1500979594](https://github.com/ultralytics/ultralytics/issues/1904#issuecomment-1500979594)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced prediction results handling for easier output customization and added utilities for image saving.

### 📊 Key Changes
- Refactored the `write_results` method to consolidate result processing and logging.
- Included additional methods in the `results.py` file, such as `verbose`, `save_txt`, and `save_crop`, enabling straightforward result interpretation and exporting.
- Removed redundant code from prediction files (`predict.py`) of individual tasks (classification, detection, segmentation, pose estimation) to make use of new methods in the `results.py` class. 

### 🎯 Purpose & Impact
- **Purpose**: Streamline how results are processed, logged, and saved across different types of predictions to improve maintainability and extendability of the codebase.
- **Impact**: 
  - Developers can now more easily customize how results are handled after model predictions.
  - Users benefit from a standardized way to access and save predictions, potentially enhancing the integration into various workflows and applications.

### CODE REVIEW

**Comment by AyushExel** [comment]
Took a look. Looks great! Maybe also add a test for pose in the test_python.py->test_result() ?

**Comment by Laughing-q** [comment]
tested with the following script and compared the plotted image and saved labels/crops, all the functionalities `save_txt`, `save_crop` works correctly to me.
```
yolo classify predict model=yolov8n-cls.pt imgsz=224 save_txt
yolo detect predict model=yolov8n.pt imgsz=640 save_txt save_crop
yolo segment predict model=yolov8n-seg.pt imgsz=640 save_txt save_crop
yolo pose predict model=yolov8n-pose.pt imgsz=640 save_txt save_crop
```
for detect/segment/pose I also simulated the no-predictions case by adding `conf=1.0`, and saved images looks correctly.
```
yolo detect predict model=yolov8n.pt imgsz=640 save_txt save_crop conf=1.0
yolo segment predict model=yolov8n-seg.pt imgsz=640 save_txt save_crop conf=1.0
yolo pose predict model=yolov8n-pose.pt imgsz=640 save_txt save_crop conf=1.0
```

**Comment by Laughing-q** [comment]
@AyushExel you means like this?
image
I've added this already in another merged PR. :)

**Comment by AyushExel** [comment]
Oh yes exactly! Perfect!

**Comment by glenn-jocher** [comment]
@Laughing-q should we delete the update_results branch? I thought it auto-deleted but I see it's back now. Or maybe you pushed more recently to it?

**Comment by glenn-jocher** [comment]
@Laughing-q ah nevermind, I accidentally pushed to it. Deleted branch (again).

**Pull request merged**
