### PR TITLE
RTDETR invalid numeric entries fix

### PR DESCRIPTION
**Pull request by jordanesikati**
**Case of custom training with RT-DETR**
ultralytics/ultralytics/models/utils/ops.py
The error generated from
Line 108 gt_groups = torch.as_tensor([0, *gt_groups[:-1]]).cumsum_(0)
(ValueError: matrix contains invalid numeric entries)
**The solution that worked for me**
Line 106 C = C.view(bs, nq, -1).cpu()
Right below line 106:
Set invalid values (NaNs and infinities) to 0
C[C.isnan() | C.isinf()] = 0

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refined GitHub action workflows, CLA assistant version bump, patch for CUDA test, and improvement in numerical stability in matching algorithm.

### 📊 Key Changes
- Reordered the GitHub Actions input options for clarity.
- Added a 'Run Conda' input option to the GitHub Actions workflow.
- Updated condition for Conda job to include 'workflow_dispatch'.
- Bumped the CLA assistant GitHub action to a newer patch version (v2.3.1).
- Disabled the 'test_model_ray_tune' test due to an issue with RayTune.
- Included a fix to set invalid numerical entries (NaNs, infinities) to 0 in the ops.py module, enhancing stability.

### 🎯 Purpose & Impact
- The reordering and introduction of a new input for Conda in GitHub Actions make it clearer and more efficient for developers to choose their testing paths. 🎛️
- Updating the CLA assistant ensures smoother operation and better handling of contributor agreements for community contributions. ✍️
- Skipping the problematic test prevents CI failures, maintaining the integrity of the build process while the underlying issue is investigated. 🛠️
- The numerical stability fix helps to avoid errors during the matching process, resulting in more reliable operations, especially for machine learning models that rely on this code. 🧮🐛

Overall, these changes aim to improve the development workflow, maintain high code quality, and ensure the robustness of the software.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@jordanesikati thanks for the PR! Can you create a new PR scoped to just the RTDETR fix in the title?

Screenshot 2023-09-18 at 12 22 06

**Comment by glenn-jocher** [comment]
@jordanesikati PR merged, thank you for your contributions!

**Comment by rromanchuk** [comment]
@glenn-jocher have you been able to export an mlpackage?  exporter.py looks fine to me, but I broke out of coremltools max dependency locks and torch nightly, so might be related to deps on bleeding edge. Other exports are fine, can't tell if it's throwing during `torch.jit.trace` or somewhere else. Going to manually step through it 


```
>>> model.export(format='coreml', nms=True)
Ultralytics YOLOv8.0.193 🚀 Python-3.10.12 torch-2.0.1+cu117 CPU (Intel Xeon Platinum 8259CL 2.50GHz)
YOLOv8m-rtdetr summary: 354 layers, 29498636 parameters, 0 gradients

PyTorch: starting from 'weights/best.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 300, 20) (56.6 MB)
Torch version 2.0.1+cu117 has not been tested with coremltools. You may run into unexpected errors. Torch 2.0.0 is the most recent version that has been tested.

CoreML: starting export with coremltools 7.0...
CoreML: export failure ❌ 2.0s: split_with_sizes expects split_sizes to sum exactly to 300 (input tensor's size at dimension 1), but got split_sizes=[4, 16]

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ultralytics/engine/model.py", line 306, in export
    return Exporter(overrides=args, _callbacks=self.callbacks)(model=self.model)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 258, in __call__
    f[4], _ = self.export_coreml()
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 122, in outer_func
    raise e
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 117, in outer_func
    f, model = inner_func(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 532, in export_coreml
    ts = torch.jit.trace(model.eval(), self.im, strict=False)  # TorchScript model
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 794, in trace
    return trace_module(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/jit/_trace.py", line 1056, in trace_module
    module._c._create_method_from_trace(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1488, in _slow_forward
    result = self.forward(*input, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 1016, in forward
    xywh, cls = self.model(x)[0].transpose(0, 1).split((4, self.nc), 1)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/_tensor.py", line 803, in split
    return torch._VF.split_with_sizes(self, split_size, dim)
RuntimeError: split_with_sizes expects split_sizes to sum exactly to 300 (input tensor's size at dimension 1), but got split_sizes=[4, 16]
```

**Comment by glenn-jocher** [comment]
@rromanchuk it seems that you're encountering an export error during `torch.jit.trace` due to a `RuntimeError`. From the error message, this seems to occur when splitting the tensor that the model is outputting. The split is expecting sizes that sum to 300, but got split sizes of [4, 16] which is a mismatch.

The model might be configured with a different number of output classes and you're trying to split it into [4, 16] that won't match the output tensor size at that dimension. You would therefore need to check that the split sizes match your model's expected output size. 

In addition, take note of the Torch version in use since the message indicates that the current version 2.0.1+cu117 has not been tested with coremltools and could possibly lead to unexpected errors. Torch 2.0.0 is the most recently tested version. 

As you mentioned using bleeding edge dependencies, this could have an effect. You might want to consider reverting your dependencies to a stable version to see if this resolves your issue.

**Pull request merged**
