### PR TITLE
Fix the docstring of xywhr2xyxyxyxy

### PR DESCRIPTION
**Pull request by patel-zeel**
Addressing issue #8514 by fixing the docstring.

Context: The `xywhr2xyxyxyxy` function actually accepts rotation in radians and not degrees, but the docstring was saying otherwise, leading to potential bugs in the user codebase. This PR fixes it.

Old docstring:
`Convert batched Oriented Bounding Boxes (OBB) from [xywh, rotation] to [xy1, xy2, xy3, xy4]. Rotation values should be in degrees from 0 to 90.`
New docstring:
`Convert batched Oriented Bounding Boxes (OBB) from [xywh, rotation] to [xy1, xy2, xy3, xy4]. Rotation values should be in radians from 0 to pi/4.`

cc @glenn-jocher @YuriGagarine

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated bounding box rotation values from degrees to radians in utility functions.

### 📊 Key Changes
- Changed documentation in `xyxyxyxy2xywhr` function to indicate rotation values are now returned in radians (0 to pi/2).
- Modified `xywhr2xyxyxyxy` function documentation to specify that rotation values should be in radians (0 to pi/2).

### 🎯 Purpose & Impact
- 📏 **Consistency:** Improves the consistency of rotation value handling by standardizing to radians, a common unit in computational tasks.
- 🤖 **Accuracy:** Potentially increases the accuracy of bounding box calculations and manipulations.
- 🛠️ **Developer Clarity:** Provides clearer guidance to developers on the expected format of rotation values, reducing errors and confusion.

### CODE REVIEW

**Comment by patel-zeel** [comment]
I have read the CLA Document and I sign the CLA

**Comment by patel-zeel** [comment]
I have now updated the docstring of the sister function `xyxyxyxy2xywhr` as well.

**Comment by glenn-jocher** [comment]
@patel-zeel thank you for your contributions, these corrections will be super helpful for other users. Please don't hesitate to submit a new PR for any other docstrings issues you spot!

**Comment by patel-zeel** [comment]
Sure, @glenn-jocher, thank you for taking the time to merge this PR. happy to help!

**Comment by glenn-jocher** [comment]
Thank you for your contribution! If you encounter any other issues or have further improvements, feel free to let us know. Your efforts are greatly appreciated by the community.

**Pull request merged**
