### PR TITLE
Adding a feature that has capability to count from both direction as …

### PR DESCRIPTION
**Pull request by CharanPrasadK**
…per choice

adding another variable 'direction' to determine whatever direction you want to count which gives flexibility to code to count form 'left to right' or 'right to left'.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the object counting feature by adding customizable counting direction.

### 📊 Key Changes
- Introduced a new parameter `direction` to the `ObjectCounter` class to specify counting direction.
- Updated the logic for counting objects based on the new direction attribute.
- Simplified the object tracking and counting algorithm.

### 🎯 Purpose & Impact
- **Flexibility:** Users can now specify if the counting should be done "left_to_right" or "right_to_left". 🔄
- **Improved Accuracy:** Counting logic is more reliable by handling direction explicitly. 🎯
- **User-Friendly:** Simplifies customization for different counting scenarios, enhancing overall user experience. 😊

### CODE REVIEW

**Comment by CharanPrasadK** [comment]
I have read the CLA Document and I sign the CLA

**Comment by CharanPrasadK** [comment]
Raised an Issue: https://github.com/ultralytics/ultralytics/issues/16115

**Comment by CharanPrasadK** [comment]
@glenn-jocher
@RizwanMunawar 

As per current working process of object_counter.py is to count objects when moving and classify counts as in and out.
For example, If we use object_counter.py  for entry gate, when the people moving right to then the classification is reverse in and out counts.
To over come this issue, I added direction variable, which is to choose in what direction they want to count in and out counts of  people using 'left_to_right' and 'right_to_left'.

Review the code, and let me know, If their is an Idle way to achieve this feature other than I suggested.
Thank  You.

**Review by ambitious-octopus — COMMENTED** [review]
Warning :warning: ! This PR integrates a commit by JiaT75!

**Comment by CharanPrasadK** [comment]
@ambitious-octopus I don't understand, Why It integrates?

**Comment by ambitious-octopus** [comment]
Hey, @CharanPrasadK A few hours ago we had a problem with an unverified commit that seems to be present also in this PR. I have to close this PR, can you please create a new one starting from the new main branch? Thanks!

**Comment by CharanPrasadK** [comment]
@ambitious-octopus  Ok, Thank You.

**Comment by bcomnes** [comment]
Can someone clarify why JiaT75 commits are present in this repo?

**Comment by glenn-jocher** [comment]
Thank you for pointing this out. JiaT75's commits may have been introduced unintentionally. We'll review the history and address any discrepancies.

**Pull request closed without merging**
