### PR TITLE
Split TensorFlow 2.13 / 2.16 Support

### LINKED ISSUE #13019: TFlite INT8 Exports failing
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Export

### Bug

Screenshot 2024-05-22 at 13 00 43

### Environment

```
Ultralytics YOLOv8.2.18 🚀 Python-3.10.12 torch-2.3.0+cu121 CUDA:0 (Tesla T4, 15102MiB)
Setup complete ✅ (2 CPUs, 12.7 GB RAM, 32.1/78.2 GB disk)

OS                  Linux-6.1.85+-x86_64-with-glibc2.35
Environment         Colab
Python              3.10.12
Install             pip
RAM                 12.67 GB
CPU                 Intel Xeon 2.30GHz
CUDA                12.1

matplotlib          ✅ 3.7.1>=3.3.0
opencv-python       ✅ 4.8.0.76>=4.6.0
pillow              ✅ 9.4.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.31.0>=2.23.0
scipy               ✅ 1.11.4>=1.4.1
torch               ✅ 2.3.0+cu121>=1.8.0
torchvision         ✅ 0.18.0+cu121>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.5
py-cpuinfo          ✅ 9.0.0
thop                ✅ 0.1.1-2209072238>=0.1.1
pandas              ✅ 2.0.3>=1.1.4
seaborn             ✅ 0.13.1>=0.11.0
```

### Minimal Reproducible Example

```
!yolo export format=tflite imgsz=[320,320] int8
```

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
@sergiuwaxmann @Burhan-Q

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements in CI settings, TensorFlow compatibility, and export functionalities in Ultralytics. 🚀

### 📊 Key Changes
- **CI Updates:** Added conditions for installing additional dependencies (`pycocotools`, `mlflow`, `ray[tune]`) during certain GitHub actions. 🛠️
- **TensorFlow Compatibility:** Adjusted TensorFlow and TensorFlow.js dependencies to better support various platforms, specifically addressing a TF issue and including Keras explicitly. 🧩
- **Export Functionality:** Introduced optimizations for exporting models, including specific conditions for TensorFlow SavedModel exports and adjustments for compatibility across different platforms and Python versions. 🔄
- **New Tests:** Added tests for TFLite exports, ensuring compatibility and functionality across diverse scenarios. 🧪

### 🎯 Purpose & Impact
- **Improved Automation & Compatibility:** These changes aim to streamline development workflows, ensuring that dependencies are correctly managed across all actions, specifically improving support for slow tests. 🎛️
- **Expanded Support & Functionality:** Updating TensorFlow dependencies ensures broader compatibility, particularly for different architectures (including aarch64 and Raspberry Pi). This makes the library more accessible and usable across a wider range of devices. 🌍
- **Enhanced Export Capabilities:** By refining export functionalities and testing, users benefit from more reliable model conversion and deployment across various platforms, including TensorFlow and TFLite. This is crucial for deploying AI models in diverse environments. 📦
- **Overall, these updates enhance the library's robustness, compatibility, and user experience, paving the way for more efficient development and deployment of AI models.** 🌈

### CODE REVIEW

**Comment by lakshanthad** [comment]
@glenn-jocher I will investigate this today and feedback.

**Comment by lakshanthad** [comment]
@glenn-jocher I think `tensorstore` compiling for nearly 40min+ is the major issue right now. After that we can fix the export issues. So for the time being, we can fallback to `tensorflow 2.13.1` on ARM64 and I can create an issue in [tensorstore github](https://github.com/google/tensorstore) to talk about aarch64 binaries on pypi.

**Comment by glenn-jocher** [comment]
@lakshanthad ok got it, yes please raise a tensorstore issue and we'll leave this open for future updates to TF.

**Comment by glenn-jocher** [comment]
@lakshanthad when I pin everything to TF 2.13.1 then TFLite INT8 exports are failing on Raspberry PI, just like in my other Test Matrix PR where they fail for ubuntu instances.

So our options here are to fully upgrade all environments to TF 2.16 (with the 40-minute wheel builds), or perhaps to exclude TF-related exports from Raspberry Pi?

**Comment by lakshanthad** [comment]
@glenn-jocher understood. I will debug this locally running only `test_exports.py` so that I can do some trial and error quickly with different versions. After tomorrow, we can make a decision according to the ideas you mentioned.

**Comment by lakshanthad** [comment]
@glenn-jocher I did some testing locally but no luck so far. Would it be possible to skip only TFLite INT8 export on RPi for the time being?

**Comment by glenn-jocher** [comment]
@lakshanthad yes we could resort to that, though ideally we want to get https://github.com/ultralytics/ultralytics/pull/13176 working so we can simplify all TF installs to the latest :)

**Comment by glenn-jocher** [comment]
Closed in favor of #13176

**Pull request closed without merging**
