### PR TITLE
Return boxes for SAM prompts inference

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the prediction process in the Ultralytics model for improved output handling.

### 📊 Key Changes
- Introduced a `save` parameter to the prediction method for saving results.
- Adjusted how bounding boxes are handled when masks are absent.
- Ensured consistency with a placeholder for class info even if not provided.

### 🎯 Purpose & Impact
- 📁 **Save Functionality**: Allows users to easily save prediction results, enhancing usability.
- 📐 **Better Handling**: Improves accuracy of bounding boxes when mask data isn't available.
- 🔄 **Consistency**: Maintains uniform behavior across different prediction scenarios, ensuring reliable output.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Laughing-q, thank you for submitting your pull request to the `ultralytics/ultralytics` repository! 🚀 This is an automated response to provide initial guidance, and an Ultralytics engineer will assist you soon.

To ensure a smooth integration of your changes, here’s a checklist to review before finalizing your PR:

- ✅ **Define a Purpose**: Ensure your PR description clearly outlines the purpose of your changes and links to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Your commit messages should be clear and concise.
- ✅ **Sync with Main Branch**: Make sure your PR is up-to-date with the `main` branch. You can update it by clicking 'Update branch' or running `git pull` and `git merge main` in your local environment.
- ✅ **Pass CI Checks**: Ensure all [Continuous Integration (CI)](https://github.com/ultralytics/ultralytics/actions) checks pass. If they fail, please address these issues before proceeding.
- ✅ **Document Changes**: Update the relevant [documentation](https://docs.ultralytics.com) to reflect any new features or modifications.
- ✅ **Add/Improve Tests**: Verify that your changes are covered by existing tests or add new tests if necessary to ensure robustness and functionality.
- ✅ **Sign the CLA**: If this is your first contribution to Ultralytics, please sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA."

### Highlights from Your PR:

- **Enhanced Efficiency**: Refactored the `postprocess` method for better organization and clarity ✨.
- **Robust Handling**: Improved logic to ensure bounding boxes are accurately generated and scaled from masks when not directly provided 🎯.

For further details on contributing, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to comment if you have questions or need assistance—thank you for enhancing the Ultralytics project! 🙌

**Comment by Laughing-q** [comment]
@glenn-jocher @RizwanMunawar I noticed we don't return predicted boxes when doing prompts inference when SAM models and this PR is to add predicted boxes to be consistent with other segmentation models(yolov8-seg/FastSAM).
BTW I found this when I tried to do a prompt inference on SAM2 and encountered an error:
```python
  File "/home/laughing/codes/ultralytics/ultralytics/engine/predictor.py", line 338, in write_results
    self.plotted_img = result.plot(
                       ^^^^^^^^^^^^
  File "/home/laughing/codes/ultralytics/ultralytics/engine/results.py", line 527, in plot
    if pred_boxes.id is not None and color_mode == "instance"
       ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'id'
```
because the pred_boxes is None. 
And our tests didn't catch this issue is that we don't have `save=True` in our tests:
https://github.com/ultralytics/ultralytics/blob/c2068df9d981c5ae27fedee550bdaedddcec3c53/tests/test_cli.py#L104
hence no plotting process at all. I also added a `save=True` flag in our tests in this PR.

**Comment by glenn-jocher** [comment]
@Laughing-q nice! Good test improvement too.

**Comment by RizwanMunawar** [comment]
@Laughing-q, got it, nice catch! But in that case, wouldn’t we need to add a check for it? For example, if the user calls `show=True`, the code should account for `if pred_boxes.id is not None and color_mode == "instance"`, right?

**Pull request merged**
