### PR TITLE
added confusion matrix for classification

### PR DESCRIPTION
**Pull request by Ercalvez**
### Summary
📊🔎🏷️

The pull request improves the evaluation of classification models by using the `ConfusionMatrix` class from `ultralytics/yolo/utils/metrics.py`. It also extends the class to handle both detection and classification tasks, and to include the background class for classification.

> _Sing, O Muse, of the skillful coder who enhanced the `ConfusionMatrix`_
> _To measure both detection and classification with equal fairness_
> _And who kept the background class in the matrix, a wise decision_
> _To evaluate the models and the tasks with more completeness_

### Walkthrough
*  Modify `ConfusionMatrix` class to handle detection and classification tasks ([link](https://github.com/ultralytics/ultralytics/pull/1987/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL175-R198), [link](https://github.com/ultralytics/ultralytics/pull/1987/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL234-R255))
* Import and use `ConfusionMatrix` class for classification validation in `val.py` ([link](https://github.com/ultralytics/ultralytics/pull/1987/files?diff=unified&w=0#diff-96394c180886ae66c7b7b74458274315cc049499272c79ecf2ef04e34315f2fcL6-R6), [link](https://github.com/ultralytics/ultralytics/pull/1987/files?diff=unified&w=0#diff-96394c180886ae66c7b7b74458274315cc049499272c79ecf2ef04e34315f2fcR20-R21), [link](https://github.com/ultralytics/ultralytics/pull/1987/files?diff=unified&w=0#diff-96394c180886ae66c7b7b74458274315cc049499272c79ecf2ef04e34315f2fcL35-R39))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Expanding ConfusionMatrix utility to support classification tasks.

### 📊 Key Changes
- 🧩 Added `task` attribute to ConfusionMatrix to differentiate between detection and classification tasks.
- 📈 Modified ConfusionMatrix logic to handle confusion matrix creation for classification with an additional `process_preds` method.
- ✅ Updated `tp_fp` method to support both detection and classification tasks by considering background class only for detection.
- 🔄 Updated `ClassificationValidator` to utilize the expanded ConfusionMatrix capability for classification tasks.
- ➕ Additional processing step to aggregate predictions and targets and update the confusion matrix in `finalize_metrics`.

### 🎯 Purpose & Impact
- 💼 These changes allow for a unified ConfusionMatrix class that can be used across different tasks such as detection and classification, leading to cleaner and more maintainable code.
- 📏 With the updated metrics, users can now get a more comprehensive understanding of their models' performance for classification tasks using a confusion matrix, which could lead to better evaluation and tuning.
- 🚀 It potentially impacts users by providing them with enhanced evaluation metrics specifically tailored to their tasks, leading to a more robust assessment of model performance.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Ercalvez thanks for the PR! This looks pretty good. Have you created a Classification confusion matrix PNG file with this PR?

**Comment by glenn-jocher** [comment]
@Ercalvez also please write the below statement to accept the CLA:

I have read the CLA Document and I sign the CLA

**Comment by Ercalvez** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Ercalvez** [comment]
> @Ercalvez thanks for the PR! This looks pretty good. Have you created a Classification confusion matrix PNG file with this PR?

I tested with a debugger but I didn’t create a png file.

**Comment by glenn-jocher** [comment]
@Ercalvez oh, then we need to add a .plot() step to classify training and val just like detect has, i.e.

```python
        if self.args.plots:
            self.confusion_matrix.plot(save_dir=self.save_dir, names=list(self.names.values()))
```

**Pull request merged**
