### PR TITLE
`ultralytics 8.0.151` add `DOTAv2.yaml` for OBB training

### PR DESCRIPTION
**Pull request by glenn-jocher**
### Summary
🛰️🕵️📐

Add a new YAML file `ultralytics/cfg/datasets/DOTAv2.yaml` for the DOTA 2.0 dataset, which is a dataset for object detection in aerial images with oriented bounding boxes. This file enables users to train and evaluate YOLO models on the DOTA 2.0 dataset using the ultralytics framework.

> _`YOLO` learns to see_
> _Oriented boxes in sky_
> _Winter dataset `DOTA`_

### Walkthrough
*  Add a new YAML file for the DOTA 2.0 dataset ([link](https://github.com/ultralytics/ultralytics/pull/4258/files?diff=unified&w=0#diff-223396615b2db2e4d43c24cd83abf8b932b64b20e8238d910aad0774c2bc110bR1-R37))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
PR introduces changes to improve the YOLO model documentation and training results handling.

### 📊 Key Changes
- Modified documentation pages to include updated variable assignments capturing model training results.
- Refined BibTeX citations in the dataset documentation for better structure.
- Added a new dataset `DOTAv2` to the YOLO Oriented Bounding Box (OBB) documentation with an example usage.

### 🎯 Purpose & Impact
- The updated code assignments ensure that users correctly capture and utilize the results of model training.
- Improved BibTeX citations offer clarity and proper usage guidance for those looking to reference datasets in their research.
- Inclusion of the `DOTAv2` dataset enhances the YOLO model's functionality with OBB, catering to specific aerial image detection tasks, and broadens the model's application scope in research and development.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
Verification script for ops (currently incorrect results):

```
import torch
from ultralytics.utils.ops import *

corners = np.array([[0, 0, 4, 0, 4, 6, 0, 6], [1, 1, 3, 2, 2, 4, 0, 3]])

center = xyxyxyxy2xywhr(corners)
print(center)

new_corners = xywhr2xyxyxyxy(center)
print(new_corners)

# The same test can be repeated with torch tensors.
corners_torch = torch.tensor(corners, dtype=torch.float32)

center_torch = xyxyxyxy2xywhr(corners_torch)
print(center_torch)

new_corners_torch = xywhr2xyxyxyxy(center_torch)
print(new_corners_torch)
```

**Comment by glenn-jocher** [comment]
OBB plotting code

```python
def plot_obb(data, mode='corners'):
    """
    Plot Oriented Bounding Boxes (OBB) using matplotlib.

    Args:
        data (numpy.ndarray | torch.Tensor): Either the corners or center of the OBB.
        mode (str): 'corners' if the input is corners, 'center' if the input is [cx, cy, w, h, rotation].
    """
    import matplotlib.pyplot as plt
    import matplotlib.patches as patches

    fig, ax = plt.subplots(1)
    ax.set_aspect('equal')

    if mode == 'corners':
        if isinstance(data, torch.Tensor):
            data = data.cpu().numpy()

        for obb in data:
            polygon = patches.Polygon(obb.reshape(-1, 2), fill=False, edgecolor='r')
            ax.add_patch(polygon)

    elif mode == 'center':
        if isinstance(data, torch.Tensor):
            data = data.cpu().numpy()

        for obb in data:
            cx, cy, w, h, theta = obb
            rectangle = patches.Rectangle(
                (cx - w / 2, cy - h / 2), w, h, angle=-theta, fill=False, edgecolor='b')
            ax.add_patch(rectangle)

    ax.autoscale_view()
    plt.show()


```

**Comment by Kayzwer** [comment]
@glenn-jocher is there any new class in head.py to support OBB?

**Comment by glenn-jocher** [comment]
@Kayzwer yes, there is a new OBB() head in https://github.com/ultralytics/ultralytics/pull/1977 that we will use to create new i.e. yolov8n-obb.pt models. This PR is mainly intended to add DOTAv2 training to #1977.

**Comment by glenn-jocher** [comment]
修改-YOLOv5-源码在-DOTAv1 5-遥感数据集上进行旋转目标检测-20210509005417 (1)

**Comment by glenn-jocher** [comment]
https://pub.mdpi-res.com/remotesensing/remotesensing-11-02930/article_deploy/html/images/remotesensing-11-02930-g001.png?1577729834

image

**Comment by Zengyf-CVer** [comment]
@glenn-jocher Can OBB detection be used directly in the file https://github.com/ultralytics/ultralytics/blob/main/ultralytics/models/yolo/detect/predict.py?Or write a python program through `ultralytics`, input a remote sensing image, and then output the detected effect image?

**Comment by mbl1234** [comment]
请问怎么转换自己的旋转数据集呀

**Comment by glenn-jocher** [comment]
@mbl1234 您好！要转换您自己的旋转数据集，请按照我们的文档中提到的标准格式准备您的数据。每个样本应包括一个图像文件和相应的标注文件，标注文件中应包含旋转边界框（例如：中心点坐标、宽、高和旋转角度）。更多详细信息和指南，请查阅我们的文档！📘🔄

**Comment by mbl1234** [comment]
您好，很冒昧打扰您，是这样的，我下载了DOTAv2的数据集，并按照文档提供的方法进行转换，如附件所示，但是生成的文件夹和我自己的数据集生成效果一样，都是空文件夹没有内容，所以想询问一下您，我是哪一步出现了问题








------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ultralytics/ultralytics"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月25日(星期一) 晚上9:46
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ultralytics/ultralytics] `ultralytics 8.0.151` add `DOTAv2.yaml` for OBB training (PR #4258)





 
@mbl1234 您好！要转换您自己的旋转数据集，请按照我们的文档中提到的标准格式准备您的数据。每个样本应包括一个图像文件和相应的标注文件，标注文件中应包含旋转边界框（例如：中心点坐标、宽、高和旋转角度）。更多详细信息和指南，请查阅我们的文档！📘🔄

**Comment by glenn-jocher** [comment]
@mbl1234 您好！如果您在转换DOTAv2数据集时遇到生成的文件夹为空的问题，请确保您按照文档中的步骤正确地执行了转换流程。这可能包括：

1. 检查数据集路径是否正确。
2. 确保所有必要的转换脚本已经正确执行。
3. 查看转换日志，检查是否有任何错误信息。

如果问题仍然存在，您可以通过在我们的GitHub repo提交issue来提供更详细的描述，包括您遵循的步骤和任何输出日志，这样我们可以更好地帮助您解决问题。🛠️📊

**Pull request merged**
