### PR TITLE
Rename predictor postprocess `orig_img` to `orig_imgs`

### LINKED ISSUE #2875: model.predict(..., save=True) doesn't work as intended for batch prediction
During batch prediction of pose estimation, if `save=True`, all of the predictions are incorrectly drawn on the first image of the batch. For example, if we have two images in a list that are passed to the model for prediction:

image1:
img

image2:
img_1

The outputs are found in `runs/pose/predict` as given:

image1:
img

image2:
img_1

### PR DESCRIPTION
**Pull request by afifaniks**
Fixes #2875 

### Summary
:recycle::sparkles::camera:

Refactored the pose prediction module to handle multiple images. Changed the variable name `orig_img` to `orig_imgs` in `predict.py` to reflect this.

> _`orig_img` gone_
> _pose prediction now handles_
> _many `orig_imgs`_

### Walkthrough
*  Rename `orig_img` to `orig_imgs` in parameter and variable names to reflect plural form and support list input ([link](https://github.com/ultralytics/ultralytics/pull/2877/files?diff=unified&w=0#diff-1564811411239154c7f0b40eabff1f51a108b807b9ae746db09abbb70d5441bbL14-R14), [link](https://github.com/ultralytics/ultralytics/pull/2877/files?diff=unified&w=0#diff-1564811411239154c7f0b40eabff1f51a108b807b9ae746db09abbb70d5441bbL26-R26))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced image processing for predictions in YOLO's engine and pose modules.

### 📊 Key Changes
- Modified the `postprocess` method argument from `orig_img` to `orig_imgs` to indicate support for batches of images.
- Updated `postprocess` method in the pose module to handle lists of original images, ensuring predictions are correctly scaled to each individual image.

### 🎯 Purpose & Impact
- 🎨 The changes improve the handling of multiple images, allowing batch processing that is common in real-world applications.
- 📈 Potentially increases the efficiency of prediction post-processing, positively impacting the user experience by enabling faster and more accurate results on batches of images.
- 🏗️ Provides a foundation for further enhancements by standardizing the way original images are managed within the prediction process.

### CODE REVIEW

**Comment by afifaniks** [comment]
I have read the CLA Document and I sign the CLA

recheck

**Comment by afifaniks** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@afifaniks thank you for your contributions. This looks good to me.

**Comment by glenn-jocher** [comment]
@afifaniks is this a change that should be applied to all predictors? i.e. Pose, Detect, Segment, Classify?

**Comment by glenn-jocher** [comment]
@afifaniks it looks like we have multiple places we should make this change. Can you please do a search and update all the locations? Thank you!

Screenshot 2023-05-28 at 17 44 00

**Comment by afifaniks** [comment]
@glenn-jocher sure, I can.

**Comment by afifaniks** [comment]
@glenn-jocher by a quick look, other references look fine.

**Comment by glenn-jocher** [comment]
@afifaniks ok yes I see it now, we just needed to update the base postprocess class. I think it's all good now!

**Comment by glenn-jocher** [comment]
@afifaniks PR merged! Thank you for the fix and let us know if you see any other improvements we might make :)

**Comment by afifaniks** [comment]
Thank you. Sure, will do that. 

One thing I missed during debugging is type hints. You may consider integrating typehints in methods. But overall, it's a really clean codebase. Kudos!

**Comment by glenn-jocher** [comment]
@afifaniks thank you for the feedback and the kind words about our codebase! We welcome all suggestions for improving YOLOv8. Adding typehints to our methods is definitely a great idea and we'll consider implementing it in future updates to the code. Thanks again for taking the time to give us your thoughts.

**Pull request merged**
