### PR TITLE
Improve log message readability

### PR DESCRIPTION
**Pull request by maycuatroi1**
# Change:
- Improve log message readability

# Example:
image

## Note:
@glenn-jocher 
I have been working with `Ultralytics` for the past 6 months. I find it to be an excellent framework that I would like to continue using. I believe this small change can help improve log readability. 🙏 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved logging for better readability in model summaries by adding commas to separate large numbers.

### 📊 Key Changes
- Modified the logging format in `model_info()` to include commas in the output for layers, parameters, and gradients.

### 🎯 Purpose & Impact
- **Improved Readability**: 📈 Makes the model summaries easier to read and understand by clearly separating large numbers.
- **User Convenience**: 👍 Easier for developers and users to quickly grasp the scale and complexity of models.

### CODE REVIEW

**Comment by maycuatroi** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@maycuatroi nice improvement!!

**Comment by glenn-jocher** [comment]
@maycuatroi PR merged, thank you for your contributions!

**Comment by maycuatroi** [comment]
@glenn-jocher thank you, have a nice day 🤩

**Pull request merged**
