### PR TITLE
Update tensorflow versions according to architecture

### PR DESCRIPTION
**Pull request by lakshanthad**
Currently tensorflow PyPI includes pre-build binaries for all architectures. Therefore, there is no need to specify different architectures. https://pypi.org/project/tensorflow/2.15.0/#files

I have read the CLA Document and I hereby sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced TensorFlow exporting compatibility for Ultralytics models.

### 📊 Key Changes
- Introduced version restriction for TensorFlow dependency on non-ARM64 systems (now capped at `12.13.1`).
- Limited the maximum version of `flatbuffers` now to be less than `100` during requirement checks.

### 🎯 Purpose & Impact
- 🎯 Ensuring compatibility by preventing installation of incompatible TensorFlow versions on certain platforms, potentially avoiding runtime errors.
- 🔧 Addressing future-proofing of dependency `flatbuffers` by setting a maximum version threshold, thereby preventing unforeseen issues with future breaking changes in the `flatbuffers` library.

### CODE REVIEW

**Comment by lakshanthad** [comment]
@glenn-jocher FYI

**Comment by lakshanthad** [comment]
I wonder whether we still need this check @glenn-jocher. Because Tflite exports with the latest 2.15.0 are working fine.
https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L732-L738

**Comment by glenn-jocher** [comment]
@lakshanthad oh thanks for the PR. 

The reason for these different types is that tensorflow has many pip packages. It looks like the binaries you point to will install a hollow 'tensorflow' version and the same version as currently installed on environments like arm64 and macos, i.e. on my M2 macbook `pip install tensorflow-macos` will install normally, but if I run `pip install tensorflow` it will install two packages, and empty `tensorflow` binary and a link to the same `tensorflow-macos`, but now I've got both showing in pip list instead of just 1. 

Also we don't want to burden CPU-only users (and our own CPU-only images like `Dockerfile-cpu`) with larger un-needed CUDA code that comes packaged in the default `tensorflow` (475MB), which is why we direct them to `tensorflow-cpu` instead (207MB).

**Comment by glenn-jocher** [comment]
@lakshanthad also as I've mentioned before, TF 2.15 will not work with TFLite exports, we have bug reports open with Google on this such as https://github.com/tensorflow/tflite-support/issues/954 with simple code to reproduce that they have failed to take action on, preventing us from allowing any versions of TF higher than 2.13.1 that will not work correctly with Google's poorly maintained `tflite_support` package that we rely on to add metadata to our TFLite models.

You can experiment with removing the constraint and see what happens if you try to export TFLite models with TF 2.15.

**Comment by lakshanthad** [comment]
Thank you for the detailed clarification @glenn-jocher. I understand.

I agree with you regarding specifying the architecture version.

When I tried TF 2.15 on my X86 Linux machine, I have the same error as you have pointed out. But TF 2.15 on aarch (RPi and Jetson) has no such error and the model gets exported in tflite.

**Comment by lakshanthad** [comment]
> It looks like the binaries you point to will install a hollow 'tensorflow' version

It should be because of this:
https://www.tensorflow.org/install/pip#linux
image

Eventhough package is like this a couple kb:
image

It actually downloads `tensorflow-cpu-aws`:
image

image

**Comment by glenn-jocher** [comment]
@lakshanthad ah interesting, so then this must be why it also works on the macos-14 M1 runner in https://github.com/ultralytics/ultralytics-tests/pull/6

Well, do you think you could selectively apply version constraints based on the environment so that the <=2.13.1 constraint only applies to x86?

**Comment by lakshanthad** [comment]
@glenn-jocher Yes. will do this when I am back to work.

**Comment by lakshanthad** [comment]
@glenn-jocher It is all good now

**Comment by glenn-jocher** [comment]
@lakshanthad closing this PR in favor of #8395 which also includes these same changes.

**Comment by lakshanthad** [comment]
@glenn-jocher no problem. thanks

**Pull request closed without merging**
