### PR TITLE
Example ORT==2.0.0-rs.5 to support onnxruntime==1.19.x

### PR DESCRIPTION
**Pull request by yawnbright**
## 🌟 Summary
Update ort==2.0.0-rs.5 to support onnxruntime==1.19.x.

## 📊 Key Changes
Use ort==2.0.0-rs.5 to replace ort==1.6.3, ort==1.6.3 can not infer the onnx model transformed by onnxruntime 1.19.x (the latest version so far).

## 🎯 Purpose & Impact
Ensures that users can use the newest onnxruntime.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
The Rust demo for YOLOv8 with ONNX Runtime has been updated to enhance compatibility and performance through various dependency upgrades and code improvements.

### 📊 Key Changes
- **Dependency Updates**: Updated various dependencies like `image`, `imageproc`, `ndarray`, `ort`, and `rusttype` to newer versions.
- **ONNX Runtime Version**: ONNX Runtime upgraded to version 1.19.x.
- **Use of `ab_glyph` Library**: Introduced `ab_glyph` for handling fonts, replacing the `rusttype` font handling approach.
- **Device ID Type Change**: Changed the type of `device_id` from `u32` to `i32` for better integration with certain execution providers.
- **Font Handling Enhancements**: Implemented a new method to load fonts, which includes downloading and saving fonts if not available locally.
- **Execution Provider Updates**: Streamlined execution provider logic, accommodating newer ONNX features and improving usage of CUDA and TensorRT.

### 🎯 Purpose & Impact
- **Enhanced Compatibility**: By upgrading dependencies, the demo remains compatible with current libraries, improving robustness and future-proofing the code.
- **Improved Performance**: The changes in execution providers can enhance performance, especially when leveraging CUDA and TensorRT optimizations.
- **Better Font Management**: Introducing `ab_glyph` and its new font management approach allows smoother text rendering, which should improve the visual output from model predictions.
- **Broader Device Support**: The change in `device_id` type and updated execution providers allow for broader device compatibility and potentially easier deployment on diverse hardware configurations.

### CODE REVIEW

**Comment by yawnBright** [comment]
I have read the CLA Document and I sign the CLA

**Comment by UltralyticsAssistant** [comment]
👋 Hello @yawnBright, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to ensure a quick review, but rest assured, an Ultralytics engineer will assist you shortly. Here’s a quick checklist to help streamline the integration of your work:

- ✅ **Purpose and Description**: It seems you've outlined the purpose of your update to support the latest `onnxruntime==1.19.x`. Great work! Ensure that your description clearly states how this change impacts the project and remember to link any relevant [issues](https://github.com/ultralytics/ultralytics/issues) that might have prompted this update.
- ✅ **Branch Synchronization**: Double-check that your PR is in sync with the `main` branch of the `ultralytics/ultralytics` repository. If it's out of date, please update it by clicking 'Update branch' or by running `git pull` and `git merge main` locally.
- ✅ **Continuous Integration**: Make sure all [CI checks](https://docs.ultralytics.com/help/CI/) are passing. If there are any failures, investigate and resolve the reported issues.
- ✅ **Documentation**: If this update affects user-facing features, remember to update the relevant [documentation](https://docs.ultralytics.com) accordingly.
- ✅ **Testing**: It's essential to cover your changes with appropriate tests. Please make sure any new or existing tests relevant to your changes are passing.
- ✅ **Contributor License Agreement (CLA)**: If you haven't already done so, please sign our [CLA](https://docs.ultralytics.com/help/CLA/) by stating "I have read the CLA Document and I sign the CLA" in a comment below.
- ✅ **Changes Scope**: Aim to keep your changes minimal yet effective, focusing only on what's necessary to achieve your goals. As Bruce Lee said, _"It is not daily increase but daily decrease, hack away the unessential."_

For any further guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions, feel free to leave a comment here. Thank you for your efforts in keeping Ultralytics cutting-edge! 🌟💪

**Comment by glenn-jocher** [comment]
@yawnBright I see the +172 KB font file embedded here but we can not accept any non-code files in the repo. Fonts need to be local or downloaded remotely like we do with Arial.ttf

**Comment by yawnBright** [comment]
> @yawnBright I see the +172 KB font file embedded here but we can not accept any non-code files in the repo. Fonts need to be local or downloaded remotely like we do with Arial.ttf

@glenn-jocher I have removed this font file, and it will download if file does not  exist.

**Comment by glenn-jocher** [comment]
Thank you for updating the font handling. If you need further assistance, feel free to ask!

**Comment by yawnBright** [comment]
Will this PR be merged? I see this issue #16504 met an problem, which exactly is this pr fixed.

**Comment by glenn-jocher** [comment]
@yawnBright the decision to merge PRs is made by the maintainers based on various factors. Please monitor the PR and issue for updates.

**Comment by glenn-jocher** [comment]
@yawnBright PR merged, thank you for your contributions!

**Pull request merged**
