### PR TITLE
BUGFIX: Dataloading CPU bottleneck

### PR DESCRIPTION
**Pull request by AMoldskred**
I noticed while training that only 2 of my 8 cores were being utilized, even though I had configured for 8 workers.
After some digging I found this pytorch thread describing the same issue: https://github.com/pytorch/pytorch/issues/101850#issuecomment-1732412003

Adding this to the seed_worker fixed the issue and sped up training significantly🚀

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced data processing with optimized threading in the latest update 🚀.

### 📊 Key Changes
- Introduction of `NUM_THREADS` in data processing scripts.
- Optimized thread count calculation for YOLO multiprocessing tasks.
- Affinity setting for worker threads to improve processing efficiency.

### 🎯 Purpose & Impact
- **Purpose:** To improve the performance and efficiency of data handling, specifically aiming at enhancing the system's capability to process large datasets faster and more reliably.
- **Impact:**
  - For developers and expert users, this update means your models might train faster due to better CPU utilization 🖥️💨.
  - For non-expert users, expect a smoother experience with quicker data preparations and possibly shorter waiting times for results 🌈.
  - This change sets the foundation for more robust and scalable AI training capabilities across various hardware setups.

### CODE REVIEW

**Comment by AMoldskred** [comment]
I have read the CLA Document and I sign the CLA

**Comment by AMoldskred** [comment]
For reference, this was an issue that I [first noticed when training on the Yolov9 repository](https://github.com/WongKinYiu/yolov9/pull/312). Moving over to Ultralytics I faced the same problem, so would be nice to get this fixed.

**Comment by glenn-jocher** [comment]
@AMoldskred thanks for the bug fix! I've updated this slightly to use `NUM_THREADS` rather than os.cpu_count(), as larger servers like our A100 server with 128 CPUs need to be divided typically by the WORLD_SIZE, i.e. for 8 GPUs then each GPU would be allocated 16 CPUs at most so as not to saturate the system.

**Comment by AMoldskred** [comment]
@glenn-jocher Awesome! Thank you for the quick response!🙌🏻

**Comment by glenn-jocher** [comment]
@AMoldskred you're welcome! If you have any more questions or need further assistance, feel free to reach out. Happy coding! 😊🚀

**Comment by Bravehawk666666** [comment]
Hi, I came across this thread due to the following error::

```
build.py", line 84, in seed_worker
os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195
AttributeError: module 'os' has no attribute 'sched_setaffinity'
```

Environment: Windows 10, Python 3.9, Yolo 8.2.7 from today.

I started training like this:
`yolo detect train data=mydata.yaml model=yolov8x.pt epochs=200 device=0 `

Error occurs with device=0 and also with device=cpu.

As a quick fix i commented out the line 
`#os.sched_setaffinity(0, range(NUM_THREADS))`

Now my training runs again.

Regards!

**Comment by typeuser21** [comment]
Original Traceback (most recent call last):
  File "D:\Python\Python311\Lib\site-packages\torch\utils\data\_utils\worker.py", line 250, in _worker_loop
    init_fn(worker_id)
  File "D:\Python\Python311\Lib\site-packages\ultralytics\data\build.py", line 84, in seed_worker
    os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195
    ^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'os' has no attribute 'sched_setaffinity'

**Comment by glenn-jocher** [comment]
@typeuser21 hello!

It looks like you encountered an issue with `os.sched_setaffinity`, which isn't available on Windows platforms. This function is used to set the CPU affinity for the process, which is supported only on some Unix-based systems.

As a quick workaround, you can safely comment out or remove this line in your local setup if you're running on Windows. The script should continue to work without it, though with potentially non-optimal CPU utilization.

If you need to manage CPU affinity on Windows, you could explore using Windows-specific packages or tools, but that's generally more involved.

Thanks for reaching out, and let us know if you have any more questions! 🚀

**Comment by AMoldskred** [comment]
@glenn-jocher Didn't realize `sched_setaffinity` wasn't supported on Windows. Here is a PR to catch the error for Windows: https://github.com/ultralytics/ultralytics/pull/11232

**Comment by EliteMandy** [comment]
`def seed_worker(worker_id):  # noqa
    """Set dataloader worker seed https://pytorch.org/docs/stable/notes/randomness.html#dataloader."""
    worker_seed = torch.initial_seed() % 2**32
    np.random.seed(worker_seed)
    random.seed(worker_seed)
    #os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195`
    
Even though i have commented the line i am getting this error now, please help 
`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 20.00 MiB. GPU`

**Comment by glenn-jocher** [comment]
Hello!

It looks like you're encountering a CUDA out of memory error. This usually happens when your GPU doesn't have enough available memory to allocate what your model needs. Here are a few ways you could try to resolve this:

1. **Reduce Batch Size**: Decreasing the batch size in your training settings might reduce the memory required per training step.
2. **Lower Image Size**: Reducing the resolution of the input images (`imgsz` argument) can also help lessen memory usage.
3. **Use `torch.cuda.empty_cache()`**: Occasionally clearing the cache can help if the memory isn't being properly released. You can run `torch.cuda.empty_cache()` between your training loops or during an epoch end.

Make sure no other processes are using the GPU memory by checking it with `nvidia-smi` command.

If you need further assistance, feel free to reach out! 🚀

**Comment by luohanke** [comment]
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 235, in _worker_loop
    init_fn(worker_id)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/data/build.py", line 85, in seed_worker
    os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195
OSError: [Errno 22] Invalid argument

**Comment by luohanke** [comment]
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/cfg/__init__.py", line 582, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/model.py", line 673, in train
    self.trainer.train()
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 353, in _do_train
    for i, batch in pbar:
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/data/build.py", line 50, in __iter__
    yield next(self.iterator)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 235, in _worker_loop
    init_fn(worker_id)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/data/build.py", line 85, in seed_worker
    os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195
OSError: [Errno 22] Invalid argument

**Comment by glenn-jocher** [comment]
Hi there! It looks like you're encountering an issue with `os.sched_setaffinity` which is not fully supported across all platforms, especially if you're using a non-Unix system or the assigned range is out of bounds for your setup.

A quick fix is to remove or comment out this line if it's causing issues:

```python
# os.sched_setaffinity(0, range(NUM_THREADS))
```

This won't affect the functionality of your training apart from the intended CPU core affinity settings. We'll consider adding a platform check or a try-except block in future versions to handle such cases gracefully! Thanks for pointing this out. 😊🚀

**Comment by luohanke** [comment]
0%|          | 0/264 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/bin/yolo", line 8, in <module>
    sys.exit(entrypoint())
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/cfg/__init__.py", line 582, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/model.py", line 673, in train
    self.trainer.train()
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 353, in _do_train
    for i, batch in pbar:
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/data/build.py", line 50, in __iter__
    yield next(self.iterator)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 235, in _worker_loop
    init_fn(worker_id)
  File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/data/build.py", line 85, in seed_worker
    os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195
OSError: [Errno 22] Invalid argument

I have removed # os.sched_setaffinity(0, range(NUM_THREADS)).

**Comment by Hasan26ozcan** [comment]
0%|          | 0/38 [00:00<?, ?it/s]
  0%|          | 0/38 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "C:\anaconda3\envs\torchhot\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\anaconda3\envs\torchhot\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\anaconda3\envs\torchhot\Scripts\yolo.exe\__main__.py", line 7, in <module>
    sys.exit(entrypoint())
  File "C:\anaconda3\envs\torchhot\lib\site-packages\ultralytics\cfg\__init__.py", line 582, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "C:\anaconda3\envs\torchhot\lib\site-packages\ultralytics\engine\model.py", line 673, in train
    self.trainer.train()
  File "C:\anaconda3\envs\torchhot\lib\site-packages\ultralytics\engine\trainer.py", line 199, in train
    self._do_train(world_size)
  File "C:\anaconda3\envs\torchhot\lib\site-packages\ultralytics\engine\trainer.py", line 353, in _do_train
...
  File "C:\anaconda3\envs\torchhot\lib\site-packages\ultralytics\data\build.py", line 84, in seed_worker
    os.sched_setaffinity(0, range(NUM_THREADS))  # fix https://github.com/ultralytics/ultralytics/pull/11195
AttributeError: module 'os' has no attribute 'sched_setaffinity'

**Comment by Hasan26ozcan** [comment]
@glenn-jocher actually ı'm using gpu ?

**Comment by glenn-jocher** [comment]
Hi there! If you're using a GPU and encountering issues, make sure your PyTorch is set up to utilize CUDA. You can check this by running:

```python
import torch
print(torch.cuda.is_available())
```

This should return `True` if your GPU is set up correctly with PyTorch.

Also, ensure your training command is properly set to use the GPU (typically by making sure the device parameter is set correctly). Let us know if you're still having trouble! 😊🚀

**Comment by luohanke** [comment]
0%| | 0/264 [00:00<?, ?it/s]
Traceback (most recent call last):
File "/root/miniconda3/envs/myconda/bin/yolo", line 8, in
sys.exit(entrypoint())
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/cfg/init.py", line 582, in entrypoint
getattr(model, mode)(**overrides) # default args from model
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/model.py", line 673, in train
self.trainer.train()
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 199, in train
self._do_train(world_size)
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/engine/trainer.py", line 353, in _do_train
for i, batch in pbar:
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/tqdm/std.py", line 1181, in iter
for obj in iterable:
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/data/build.py", line 50, in iter
yield next(self.iterator)
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 521, in next
data = self._next_data()
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
return self._process_data(data)
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
data.reraise()
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/_utils.py", line 425, in reraise
raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 235, in _worker_loop
init_fn(worker_id)
File "/root/miniconda3/envs/myconda/lib/python3.9/site-packages/ultralytics/data/build.py", line 85, in seed_worker
os.sched_setaffinity(0, range(NUM_THREADS)) # fix https://github.com/ultralytics/ultralytics/pull/11195
OSError: [Errno 22] Invalid argument

I have removed # os.sched_setaffinity(0, range(NUM_THREADS)).
@glenn-jocher

**Comment by glenn-jocher** [comment]
Hi there! It looks like you've encountered an `OSError` related to the `sched_setaffinity` call, which isn't supported on all operating systems. Since you've already commented out the `sched_setaffinity` line, if you're still seeing errors, please ensure there aren't any environment-specific configurations causing issues.

Make sure to:
- Restart your training script after making code changes.
- Ensure your data loader's `num_workers` is set appropriately for your system.

If you continue to have trouble, you might want to experiment with reducing the `num_workers` to `0` just to see if the data loading mechanism itself is causing issues.

If you need further assistance, please provide the specific error message you're now seeing, and I'll be glad to help! 😊🚀

**Pull request merged**
