### PR TITLE
Add shufflev2block

### PR DESCRIPTION
**Pull request by AnthonyF333**
#395 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of ShuffleNet V2 Blocks and StemBlock into the Ultralytics neural network modules.

### 📊 Key Changes
- **Added channel_shuffle function:** A method to rearrange the channels of the input tensor.
- **Introduced ShuffleV2Block class:** Adds a new neural network block that utilizes depthwise convolutions, batch normalization, and the channel shuffle operation.
- **Execution branching in ShuffleV2Block:** Depending on the stride, the block dynamically adjusts its layers, allowing two different pathways for the input tensor.
- **Included StemBlock class:** A new building component for convolutional networks, performing convolutions, pooling, and channel concatenations as a preliminary processing step.

### 🎯 Purpose & Impact
- **Enhancement of model architectures:** By incorporating these new blocks, the Ultralytics framework is now equipped with more advanced network components for building efficient and powerful models.
- **Performance improvements:** These blocks are designed to reduce computational complexity while maintaining model accuracy, making them suitable for resource-constrained environments.
- **Broader applications:** With the addition of these new blocks, developers using the Ultralytics framework can explore new model designs tailored to specific tasks that could potentially benefit from these efficient architectural components.

### CODE REVIEW

**Comment by AyushExel** [comment]
please resolve conflicts and fix CI. let me know if you need any help with that

**Comment by AnthonyF333** [comment]
> please resolve conflicts and fix CI. let me know if you need any help with that

How can I solve the CLA Assistant error?

**Comment by AyushExel** [comment]
Write " I have read the CLA Document and I sign the CLA"

**Comment by AnthonyF333** [comment]
I have read the CLA Document and I sign the CLA

**Comment by AyushExel** [comment]
yes

**Comment by AnthonyF333** [comment]
I have read the CLA Document and I sign the CLA

**Pull request closed without merging**
