### PR TITLE
Add Tips to Start Contributing Docs Page

### PR DESCRIPTION
**Pull request by abirami-vina**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
A new guide has been added to help users start contributing effectively to Ultralytics' open-source projects.

### 📊 Key Changes
- 🆕 Introduced a new document, "Tips to Start Contributing," in the help section.
- 📄 Updated the navigation structure to include the new contribution tips guide.
- 👥 Added contact details for an additional email in the documentation authors file.

### 🎯 Purpose & Impact
- 📚 **Educate New Contributors**: The new guide provides practical advice and best practices for those looking to contribute, making it easier for newcomers to get involved.
- 🔧 **Improve Contribution Quality**: Enhances contributor understanding, helping maintain high standards in contributions and integration processes.
- 🌐 **Strengthen Community**: Encourages broader participation by demystifying the contribution process, potentially increasing collaboration and contributions to the project.

### CODE REVIEW

**Review by Burhan-Q — COMMENTED** [review]
Great work so far! I have added my thoughts in a few areas but I also have a few overall thoughts:

- To be honest, I think that "contributing to the docs" could be a standalone page (see more near end of this comment). What are your thoughts?
- Thinking that for "code contributions" that there could be more content around how to open a PR, what do when getting comments/review on a PR, setting expectations around PR reviews or acceptance, making sure to keep the PR up to date with `main`, checking that the CI tests are passing (if not check by running tests locally), making changes based on feedback, linking any related Issues, signing the CLA, and probably even more on the actual code contributions
- I would like to see more emphasis on participating in Discussions and Issues (no code contributions). I think that for some users this might be the best and easiest way for them to contribute. This section could be coupled with the PR reviews, but prioritizing participation in helping answer Issues or to engage in Discussions (or in the Discord/Subreddit/Forums) as a means for contributions

Really I could see this as three sections (single page or multiple pages):
- no code contributions (issues/discussions)
- documentation contributions
- code contributions
- PR reviews (for other community members work, but I'd downplay this a bit as I worry it could get to noisy)

Pointing out the order/layout specifically, with the no code contributions being the biggest area where people can make a difference with less effort and time. For docs contributions, it might be good to point to some tools like Code Spell Checker for VS Code, PyCharm, etc. to find/fix spelling errors as well.

Finally, any ideas for a header image?

**Comment by abirami-vina** [comment]
@Burhan-Q Thanks for your input! I think I'll address the line-by-line edits first. Then, I'll go back and restructure the document to consist of the sections you mentioned.I would ideally like to keep this as one docs page - since we already have a contributing guide, and I feel like it's better to keep relevant info on the same page as much as possible. However, as you mentioned, it might be too much content for one docs page.

**Comment by RizwanMunawar** [comment]
@abirami-vina @Burhan-Q, the [Contributing docs](https://docs.ultralytics.com/help/contributing/) page is already available, so I’m not sure why we need to create a new one.

Instead of making a new docs page, @abirami-vina, please incorporate any changes you'd like into the existing page, perhaps by adding a separate heading like *Tips for Contributions*. Additionally, let me know when the updated docs page is ready for approval, and I'll review it.

Thanks!

**Comment by glenn-jocher** [comment]
I think @RizwanMunawar is right here, we already have a contributing guide in place officially for Ultralytics at https://github.com/ultralytics/ultralytics/blob/main/CONTRIBUTING.md which we just updated and which is published to the docs at https://docs.ultralytics.com/help/contributing. It includes all the steps and Google-style docstring guidelines, CLA signing instructions, etc.

Maybe this content would be better as a Medium or LinkedIn article or Website blog?

**Comment by abirami-vina** [comment]
@glenn-jocher @RizwanMunawar @Burhan-Q Thank you all for your helpful inputs. I discussed your feedback with Nuvola and we'll be reworking this doc draft as a blog post.

**Comment by glenn-jocher** [comment]
You're welcome! That sounds like a great plan. Looking forward to reading the blog post.

**Comment by RizwanMunawar** [comment]
@abirami-vina Hi, I am closing this PR. Since you are already writing blogs on this topic! Thanks

**Pull request closed without merging**
