### PR TITLE
Align `test_exports.py` with export docs

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR simplifies and improves export tests for YOLO models by removing redundant parameters and ensuring compatibility across configurations. 🧪

### 📊 Key Changes
- **Parameter Simplification**: Removed the `dynamic` parameter in the "TorchScript," "CoreML," and "TFLite" export tests as it was unused or redundant.
- Adjusted test configurations to exclude scenarios where both `int8` and `half` precision are enabled simultaneously (invalid combination).
- Updated TorchScript test cases to use fixed image sizes and cleaned up redundant code ensuring efficiency and clarity.

### 🎯 Purpose & Impact
- **Cleaner Test Suites**: Streamlines and declutters the export tests, making them easier to maintain and interpret. 🛠️
- **Improved Compatibility**: Ensures invalid configurations are excluded, reducing false-positive or misleading results during testing. ✅
- **Developer Efficiency**: Speeds up test runs and reduces potential confusion for developers working on exports. ⚡ 

This update improves the test structure while maintaining robust validation for multiple export formats. 🚀

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any relevant issues. Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics Continuous Integration (CI) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant documentation for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our Contributor License Agreement (CLA) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For more guidance, please refer to our Contributing Guide. Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@RizwanMunawar only tests that are failing are OpenVINO with `dynamic`, which is supported. Are these unsupported tests that are passing correctly? 

@Y-T-G can you please review this?

**Comment by RizwanMunawar** [comment]
@glenn-jocher No tests were not failing for other exports except OpenVINO, but our document for export is incorrect than. maybe then we need to update the documentation?
Screenshot 2024-12-22 221217

**Comment by RizwanMunawar** [comment]
@glenn-jocher Closing this in favor of #18353

**Pull request closed without merging**
