### PR TITLE
Add Albumentations Integrations Docs Page

### PR DESCRIPTION
**Pull request by abirami-vina**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces new documentation detailing the integration of Albumentations with YOLO11, enhancing data augmentation for improved model performance.

### 📊 Key Changes
- Added a comprehensive guide (`albumentations.md`) on using Albumentations with YOLO11.
- Included information about various image transformation techniques like blur, median blur, grayscale, and CLAHE.
- Updated documentation navigation to include Albumentations under the integrations section.

### 🎯 Purpose & Impact
- **Enhanced Data Augmentation**: By integrating Albumentations, users can apply a wide range of image transformations, enriching datasets to improve model accuracy and adaptability.
- **Improved Model Performance**: This integration helps in training more robust YOLO11 models, capable of generalizing better across varied datasets.
- **Streamlined User Experience**: Provides clear, step-by-step instructions on implementing the integration, making it easier for users to leverage advanced data augmentation techniques in their computer vision projects.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @abirami-vina, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response to guide you through the PR process, and a member of our Ultralytics team will be with you soon to assist further. Here's a checklist to ensure a smooth integration of your documentation update:

- ✅ **Define a Purpose**: You've added a guide for integrating Albumentations with YOLO11 to enhance data augmentation. Please ensure your PR description is complete and links to any [relevant issues](https://github.com/ultralytics/ultralytics/issues) for context.
- ✅ **Synchronize with Source**: Make sure your branch is up-to-date with the latest `main` branch of `ultralytics/ultralytics`. You can do this by clicking the 'Update branch' button or executing `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Check that all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are green. If you encounter any failures, please address them.
- ✅ **Update Documentation**: It looks like you've added new documentation! Make sure this is consistent with our existing [documentation](https://docs.ultralytics.com) style and standards.
- ✅ **Sign the CLA**: If this is your first contribution to Ultralytics, remember to sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by adding a comment stating "I have read the CLA Document and I sign the CLA."
- ✅ **Minimize Changes**: Keep your changes focused on the document addition for Albumentations. If other changes have crept in, consider splitting them into separate PRs. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For more details on contributing to Ultralytics, please check the [Contributing Guide](https://docs.ultralytics.com/help/contributing). Feel free to reach out if you have any questions or need further clarification. Thank you for enhancing the Ultralytics documentation with your contribution! 🌟🚀

**Comment by glenn-jocher** [comment]
@abirami-vina great Docs page, thank you!

**Comment by glenn-jocher** [comment]
@abirami-vina is PR ready to review and merge? I see it's still in Draft mode.

**Comment by abirami-vina** [comment]
@glenn-jocher I marked it as a draft so that Francesco could review it. He mentioned he’ll take a look on Monday. But, in general it is ready to be reviewed.

**Comment by glenn-jocher** [comment]
Thanks for the update! We'll wait for Francesco's review on Monday. Let us know if you need anything else in the meantime.

**Review by ambitious-octopus — APPROVED** [review]
Hey @glenn-jocher @abirami-vina PR is ready, I just updated images from `jpg` to `avif`. Great job @abirami-vina .

**Comment by glenn-jocher** [comment]
Great, thank you @abirami-vina and @ambitious-octopus, PR merged!

**Pull request merged**
