### PR TITLE
Add YOLOv8-resnet50 and YOLOv8-resnet101 Backbone

### PR DESCRIPTION
**Pull request by WangQvQ**
@prince0310 @PremVarma5142 This is the structure that you want, but I didn't experiment with the accuracy, you can try it.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing new model configurations for YOLOv8 with ResNet backbones! 🚀

### 📊 Key Changes
- Added YOLOv8 model configurations using ResNet101 and ResNet50 backbones.
- Defined the number of classes (nc) to be 80 for both models.
- Specified scales for varying the depth, width, and maximum channels of the model.
- Outlined the structure of backbones and heads for both YOLOv8 models with ResNet layers and upsampling, concatenation, and detection layers.

### 🎯 Purpose & Impact
- **Expand Choices:** Users now have access to YOLOv8 models utilizing the ResNet architecture, offering more options for object detection tasks.
- **Improved Performance:** With ResNet backbones, YOLOv8 may potentially improve in terms of accuracy and feature extraction capability.
- **Flexibility:** Offering different scale configurations (l and x) allows for performance adjustments based on the computational power available.

### CODE REVIEW

**Comment by prince0310** [comment]
@WangQvQ  Thanks for this PR.

**Comment by PremVarma5142** [comment]
@WangQvQ Thankyou Sir

**Comment by ExtReMLapin** [comment]
Any reason behind N S M sizes being disabled ? @WangQvQ

**Comment by WangQvQ** [comment]
@ExtReMLapin Nothing, just l size is the same as the original resnet paper, n,s,m,l,x are all usable.

**Comment by ExtReMLapin** [comment]
Thanks for the quick answer.
When going to N size, I see the backbone is still HUGE, how would you suggest to scale it down ? Would you think it's a bad idea ?

image

**Comment by WangQvQ** [comment]
@ExtReMLapin  Of course, I have also noticed this problem, I think it must be adjusted, my writing is just to restore the original paper, but in fact, I do not recommend using this channel number directly.

**Comment by ExtReMLapin** [comment]
Alright, trainning is still running I'll post results when it's "far enough" in the training, should take few hours.

**Comment by glenn-jocher** [comment]
@ExtReMLapin looking forward to seeing your results! If you have any further questions or need assistance, feel free to reach out. Happy training! 🚀

**Comment by ExtReMLapin** [comment]
Medium sized model vs normal sized r50 backbone +medium sized neck and head

image
image

**Comment by glenn-jocher** [comment]
@ExtReMLapin the choice between a medium-sized model and a normal-sized ResNet50 backbone with a medium-sized neck and head depends on the specific requirements of your minutiae detection task. If you're seeking a balance between model complexity and performance, a medium-sized model might be more suitable. However, for potentially better feature extraction, the ResNet50 backbone could be advantageous. Keep in mind that the optimal configuration often requires experimentation, as it's highly dependent on the unique characteristics of your dataset and use case. 🧐 Keep us updated on your findings!

**Comment by ahmedfarouk99** [comment]
@WangQvQ hey and sorry for bothering but i have a few questions if i want to train custom dataset on yolov8-resnet50:
1-how can i perform that?
2- where can i find the resnet50 pretrained weight?
3- any advice or tips to follow if you don't mind
thanks in advance.

**Comment by ahmedfarouk99** [comment]
@ExtReMLapin  hey and sorry for bothering but i have a few questions if i want to train custom dataset on yolov8-resnet50:
1-how can i perform that?
2- where can i find the resnet50 pretrained weight?
3- any advice or tips to follow if you don't mind
thanks in advance

**Comment by ExtReMLapin** [comment]
Download the files from his PR and run the training on his model. 

You won't find pretrained weights

**Comment by ahmedfarouk99** [comment]
@ExtReMLapin thanks for your reply but can you explain it in more details as i got confused

**Comment by ExtReMLapin** [comment]
in your command line args you usualy have something like `model=yolov8.yaml` here instead of yolov8.yaml you put the path of this file you will download https://raw.githubusercontent.com/WangQvQ/ultralytics/9ba24bdcdd22ae530d4784823cf1bd3cb5075a43/ultralytics/cfg/models/v8/yolov8-resnet101.yaml

You can't train from pretrained so you need enough data to generalize

**Comment by ahmedfarouk99** [comment]
@ExtReMLapin you mean to write in CLI 
"yolo detect train data=data.yaml model=yolov8-resnet101.yaml  epochs=100 imgsz=640 ?
that's for training my model on custom datasets or i can not do that?

**Comment by ExtReMLapin** [comment]
yes

**Comment by ahmedfarouk99** [comment]
@ExtReMLapin thanks for your reply and sorry for bothering but i have other questions please
1- i want to ask if yolov8 use both BCE and DFL or use BCE?
2- what is the used activation function in yolov8 and how to change it?
thanks, in advance.

**Comment by ExtReMLapin** [comment]
i have no idea

**Comment by ahmedfarouk99** [comment]
@WangQvQ @ExtReMLapin  i got stacked in that error
This is the error by the way (RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 16 for tensor number 1 in the list.) did you managed to solve this problem?
this error occurs when adding ([-1, 1, SPPF, [1024, 5]]) to the backbone and adding (- [-1, 1, Conv, [1024, 3, 2]]) to the first head block in the modified yolov8-resnet50
can you help me please
this is my code :


and how can i print each resnet layer output shape?

**Comment by ExtReMLapin** [comment]
I didn't have this error

**Comment by ahmedfarouk99** [comment]
@ExtReMLapin every thing is working ok when i used yolov8-resnet50 as it is, but when i add the (SPPF) layer " ([-1, 1, SPPF, [1024, 5]])" after ResNetLayer, and adding "(- [-1, 1, Conv, [1024, 3, 2]])" before concatenate in the first head layer, this error occurs"RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 8 but got size 16 for tensor number 1 in the list.)..
can you help me to solve it....

**Comment by atifabedeen** [comment]
Hi! Is it possible to load a pretrained resnet50 encoder with this yolo architecture? I have weights that I want to load up and use this encoder for feature extraction and object detection. Many Thanks!

**Pull request closed without merging**
