### PR TITLE
Support ncnn inference

### PR DESCRIPTION
**Pull request by triple-mu**
### Summary
🚀🐍🧠

This pull request adds ncnn support for ultralytics neural networks and YOLO models. It modifies `autobackend.py` to handle ncnn inference and `benchmarks.py` to skip unnecessary tests.

> _Sing, O Muse, of the swift and skillful coder_
> _Who added ncnn support to the image tool_
> _And made `autobackend.py` run smoother and faster_
> _By importing `os` and using `pyncnn` as a rule_

### Walkthrough
*  Add ncnn support for `AutoBackend` class in `autobackend.py` ([link](https://github.com/ultralytics/ultralytics/pull/3617/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9R6), [link](https://github.com/ultralytics/ultralytics/pull/3617/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L256-R268), [link](https://github.com/ultralytics/ultralytics/pull/3617/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L369-R381))
  - Import `os` module to set number of threads for ncnn inference ([link](https://github.com/ultralytics/ultralytics/pull/3617/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9R6))
  - Use `pyncnn` alias for imported ncnn module and set network options based on CPU cores and `cuda` argument ([link](https://github.com/ultralytics/ultralytics/pull/3617/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L256-R268))
  - Handle input image as single tensor and adjust shape and pixel type of ncnn input and output ([link](https://github.com/ultralytics/ultralytics/pull/3617/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L369-R381))
* Skip benchmarking for non-ncnn formats in `benchmarks.py` ([link](https://github.com/ultralytics/ultralytics/pull/3617/files?diff=unified&w=0#diff-c038bb1fb2230068e97816bf63a783fbad880483c14f4517404d9fc3fe8e8510R80-R81))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR updates the CI workflow, documentation, and inference backends to include `ncnn` support and optimize usage.

### 📊 Key Changes
- Adjusted GitHub Actions CI to not specify branches for pull requests.
- Updated documentation formatting, including benchmark and export-related markdown files.
- Renamed "NCNN" format to lowercase "ncnn" across documentation to standardize naming conventions.
- Modified AutoBackend logic in `autobackend.py` to include ncnn support, handle multithreading, and Vulkan compute options.
- Enhanced ncnn backend inference capabilities in the forward method by ensuring memory continuity and normalization.

### 🎯 Purpose & Impact
- The CI change allows for more flexibility with branch testing, potentially streamlining development processes.
- Documentation updates improve clarity and accessibility for users, leading to better understanding and usage of the project's features.
- With the integration of ncnn support for inference, users gain more backend options for deploying their models, which can be especially beneficial for platforms where ncnn is optimized.
- Enhanced backend processing and added support for ncnn may result in faster, more efficient inference, particularly on devices favored by ncnn, like mobile or embedded systems.

📈 These changes can lead to broader model deployment capabilities and increased performance for Ultralytics users.

### CODE REVIEW

**Comment by triple-Mu** [comment]
Hello! 
Thank you so much for supporting ncnn!
I see that you have some problems about ncnn inference, so let me help you!
@glenn-jocher

**Comment by glenn-jocher** [comment]
@triple-Mu oh wow, thanks for the help! This looks much better :)

**Comment by glenn-jocher** [comment]
Oh it looks like CI is not running on this PR since it's not targeting main branch. Maybe I'll remove that constraint to allow it to run CI, hold on.

**Comment by triple-Mu** [comment]
I can not debug `benchmark.py` because when I run, it will hold on.

**Comment by glenn-jocher** [comment]
@triple-Mu ah nevermind, it's working now!! PR merged.

**Comment by glenn-jocher** [comment]
Hi @triple-Mu,

Thank you for raising your concern. I understand that you are facing difficulty constructing an `ncnn.Mat` object using a float ndarray.

To address this issue, you can use the `ncnn.Mat.from_pixels` method to construct an `ncnn.Mat` object from a float ndarray. This method allows you to specify the width, height, and number of channels in the ndarray. Additionally, you can set the `normalize` parameter to `True` if your ndarray contains pixel values in the range [0, 1].

In summary, you can use `ncnn.Mat.from_pixels` to create an `ncnn.Mat` object from your float ndarray, and don't forget to specify the size and channel information correctly.

I hope this explanation helps, and please let me know if you have any further questions or clarifications.

Best regards,
Glenn Jocher

**Pull request merged**
