### PR TITLE
`ultralytics 8.1.42` add YOLOv9 Segment models

### LINKED ISSUE #9295: YOLOv9 new task
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Add new YOLOv9 task `segment` for instance segmentation.
- [ ] create YOLOv9-seg model configuration YAML files
- [ ] include YOLOv9c-seg pretrained on COCO
- [ ] include YOLOv9e-seg pretrained on COCO
- [ ] update YOLOv9 docs page performance table

### Use case

```py
from ultralytics import YOLO

model = YOLO("yolov9c-seg.pt")
results = model.predict("ultralytics/assets/bus.jpg")
...
```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Burhan-Q**
Adds YOLOv9 instance segmentation task.

- [x] create YOLOv9-seg model configuration YAML files
- [x] include YOLOv9c-seg pretrained on COCO
  - [x] add to assets
- [x] include YOLOv9e-seg pretrained on COCO
  - [x] add to assets
- [x] update YOLOv9 docs page performance table

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved AI model documentation and configurations for enhanced queue management and object detection.

### 📊 Key Changes
- Added documentation for `queue_management.py` with a direct link to the source code for easy access and contribution.
- Introduced new model configurations (`yolov9c-seg.yaml` and `yolov9e-seg.yaml`) for advanced segmentation tasks.
- Updated model configuration files to reflect recent advancements and optimizations in YOLOv9 models for object detection and segmentation.
- Streamlined documentation across various guides, ensuring clear and concise instructions for utilizing AI models on different platforms like NVIDIA Jetson.

### 🎯 Purpose & Impact
- **Enhanced Accessibility:** By providing direct links to source code and detailed documentation, users and contributors can easily understand and improve queue management solutions.
- **Advanced Capabilities:** The new segmentation configurations enable users to tackle more complex tasks, expanding the potential applications of Ultralytics AI models.
- **Optimized Performance:** Updates to model configurations ensure that users have access to the latest advancements in AI for more accurate and efficient object detection and segmentation.
- **Broader Support:** Improved guides and documentation facilitate the deployment of AI models across various platforms, making powerful AI capabilities more accessible to a wider audience.

🚀 These changes contribute to making Ultralytics AI models more user-friendly, versatile, and powerful, catering to both beginner and advanced users interested in cutting-edge AI solutions.

### CODE REVIEW

**Comment by johncf** [comment]
Hello. Just curious if this also adds support for the panoptic model that was released recently:

- [gelan-c-pan.pt](https://github.com/WongKinYiu/yolov9/releases/download/v0.1/gelan-c-pan.pt)

**Comment by glenn-jocher** [comment]
@johncf hello! 😊 Currently, the updates mentioned specifically enhance segmentation capabilities within the YOLOv9 models. While the inclusion of a dedicated panoptic model like `gelan-c-pan.pt` is not mentioned explicitly in this update, we're always working on expanding the versatility and capabilities of YOLO models. Your interest in panoptic segmentation models is appreciated and is certainly valuable feedback for our roadmap. Stay tuned for future updates!

**Comment by glenn-jocher** [comment]
@Burhan-Q just checked the server, I'm guess these models are still training?

**Comment by Burhan-Q** [comment]
@glenn-jocher these _did_ finish and am going to be uploading them later today. I started another set of training runs for the COCO OBB models with the resources that were freed up, but can cancel them if you need me to

**Comment by glenn-jocher** [comment]
@Burhan-Q ok got it! These multiple YAMLs for YOLOv9 are a little frustrating. I put so much effort into creating a single YOLOv8 YAML that scales seamlessly to different sizes that all these new v9 YAMLs just look like lack of effort with substantial duplication of code to me, but I guess what it is.

**Comment by Burhan-Q** [comment]
It's not obvious to me how much effort this would require, but I do have an idea on how to reduce the number of YAML configurations for all models, so I'd look to @glenn-jocher and @Laughing-q for feedback on feasibility with this idea. Using the YAML aliasing syntax, the YOLOv8 models could all be specified in a single config file like this:

<details><summary>Single YAML config file</summary>
<p>

```yaml

# Parameters
nc: &nc 80 # number of classes
scales: # model compound scaling constants, i.e. 'model=yolov8n.yaml' will call yolov8.yaml with scale 'n'
  # [depth, width, max_channels]
  n: [0.33, 0.25, 1024] # YOLOv8n summary: 225 layers,  3157200 parameters,  3157184 gradients,   8.9 GFLOPs
  s: [0.33, 0.50, 1024] # YOLOv8s summary: 225 layers, 11166560 parameters, 11166544 gradients,  28.8 GFLOPs
  m: [0.67, 0.75, 768] # YOLOv8m summary: 295 layers, 25902640 parameters, 25902624 gradients,  79.3 GFLOPs
  l: [1.00, 1.00, 512] # YOLOv8l summary: 365 layers, 43691520 parameters, 43691504 gradients, 165.7 GFLOPs
  x: [1.00, 1.25, 512] # YOLOv8x summary: 365 layers, 68229648 parameters, 68229632 gradients, 258.5 GFLOPs

# YOLOv8.0n backbone
backbone: &backbone
  # [from, repeats, module, args]
  - [-1, 1, Conv, [64, 3, 2]] # 0-P1/2
  - [-1, 1, Conv, [128, 3, 2]] # 1-P2/4
  - [-1, 3, C2f, [128, True]]
  - [-1, 1, Conv, [256, 3, 2]] # 3-P3/8
  - [-1, 6, C2f, [256, True]]
  - [-1, 1, Conv, [512, 3, 2]] # 5-P4/16
  - [-1, 6, C2f, [512, True]]
  - [-1, 1, Conv, [1024, 3, 2]] # 7-P5/32
  - [-1, 3, C2f, [1024, True]]
  - [-1, 1, SPPF, [1024, 5]] # 9

  # YOLOv8.0n head
head: &head
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 6], 1, Concat, [1]] # cat backbone P4
  - [-1, 3, C2f, [512]] # 12
  
  - [-1, 1, nn.Upsample, [None, 2, "nearest"]]
  - [[-1, 4], 1, Concat, [1]] # cat backbone P3
  - [-1, 3, C2f, [256]] # 15 (P3/8-small)
  
  - [-1, 1, Conv, [256, 3, 2]]
  - [[-1, 12], 1, Concat, [1]] # cat head P4
  - [-1, 3, C2f, [512]] # 18 (P4/16-medium)
  
  - [-1, 1, Conv, [512, 3, 2]]
  - [[-1, 9], 1, Concat, [1]] # cat head P5
  - [-1, 3, C2f, [1024]] # 21 (P5/32-large)

detect:
  backbone: *backbone
  head: *head
  final: 
    - [[15, 18, 21], 1, Detect, [*nc]] # Detect(P3, P4, P5)

segment:
  backbone: *backbone
  head: *head
  final: 
    - [[15, 18, 21], 1, Segment, [*nc, 32, 256]] # Segment(P3, P4, P5)

pose:
  kpt_shape: [17, 3]
  backbone: *backbone
  head: *head
  final:
    - [[15, 18, 21], 1, Pose, [*nc, kpt_shape]] # Pose(P3, P4, P5)

obb:
  backbone: *backbone
  head: *head
  final:
    - [[15, 18, 21], 1, OBB, [*nc, 1]] # OBB(P3, P4, P5)
```

Then maybe it would just be a matter of using something like:

```py
d = yaml.safe_load(file)
d_task = d.get(task)
layers = d_task["backbone"] + d_task["head"] + d_task["final"]
```

</p>
</details> 

If that looks like a good idea, I can certainly do something like this for the YOLOv9 models.

**Comment by Burhan-Q** [comment]
The YOLOv9c and YOLOv9e structures _might_ be able to do something similar, but these look like they have quite different backbone structuring, so it would be have to be a bit different, which might require a few other changes to the code for parsing the YAML files

**Comment by Burhan-Q** [comment]
## Notes on YOLOv9 docs page updates/changes

<details><summary><b>Added</b> Multi-tab performance table and question admonition</summary>
<p>

- Design now consistent with other pages
- Since `s` and `m` variants were included, updated to also include `t` variant as well
- Tabbed for `detect` and `segment` performance
- Added `segment` models performance results, includes links to `assets` repo
- Both headers now show `mAP` (not shown in screenshot here)

## Tabbed performance metrics table

image

## Expanded admonition

- Common question asked about models.

image

</p>
</details> 

<details><summary><b>Update</b> Naming Schema</summary>
<p>

- Changed from `YOLOv9-C` to `YOLOv9c` naming in text and tables, to make consistent with filenames and other docs pages

</p>
</details> 

<details><summary><b>Update</b> Supported Tasks and Modes Table</summary>
<p>

- Design now consistent with other pages
- Moved links to weights to be exclusively in the Performance table (same as other pages)

## Design Consistent Tasks and Modes Table

image

</p>
</details> 

<details><summary><b>Added</b> Trailing note</summary>
<p>

- Included to address the **many** common questions about resource requirements and training time (compared to YOLOv8) for YOLOv9

## Resources warning

image

</p>
</details>

**Comment by Burhan-Q** [comment]
@glenn-jocher ready for review 🚀

**Comment by Laughing-q** [comment]
@Burhan-Q About the `Trailing warning`, I feel like using `Note` in the docs is better and more friendly maybe than a `Warning`? since what we want is to inform user and reduce the times of asking from them.

@Burhan-Q Also no worries about the model.yaml files, I believe @glenn-jocher was trying to say it's better we can merge two yolov9 yamls(yolov9c and yolov9e) into one, but it can't be done since the architecture are quite different designed by the author.

**Comment by Burhan-Q** [comment]
@Laughing-q understood thank you for the clarification! With respect to the trialing note, I think it would be good to highlight in a different color, so what if I change the header text to show like this instead?

<details><summary>Revised trailing note</summary>
<p>

image

</p>
</details>

**Comment by Burhan-Q** [comment]
🤔 taking a quick look at the `Note` admonition, I think you're right, it's better to change it. I will make this update to the PR

**Comment by Burhan-Q** [comment]
<details><summary>Trialing note finalized style</summary>
<p>

image

</p>
</details>

**Comment by johncf** [comment]
I'm very excited to try out the newly trained YOLOv9 segmentation models. Thanks for all the hard work. Just a quick question regarding the readme, currently the [models section](https://github.com/ultralytics/ultralytics?tab=readme-ov-file#models) shows the mAP and speed values of YOLOv8 variants:

Screenshot from 2024-04-01 19-16-09

Do you think it might be worth adding at least mAP values of YOLOv9 variants here since they're freshly trained?

**Comment by Burhan-Q** [comment]
@johncf I think updating the repo main READEME is a decision for @glenn-jocher to make and probably would be a new/different PR. For now (at least in this PR) the goal was to only update the performance results in the documentation for the `models/yolov9` page, which will be published when this PR is merged.

**Comment by glenn-jocher** [comment]
@Burhan-Q PR merged! Great job on this!!

**Review by glenn-jocher — COMMENTED** [review]
Approved!

**Comment by johncf** [comment]
I have a question regarding checkpoint sizes. `yolov8x.pt` is 131 MB, and `yolov8x-seg.pt` is 137 MB. `yolov9e.pt` is 112 MB, but `yolov9e-seg.pt` is 232 MB! Why such a large difference is file size for 9E (and similarly for 9C)?

**Comment by Laughing-q** [comment]
@johncf nice catch!
@Burhan-Q @glenn-jocher Looks like yolov9-seg weights are not stripped, I'll do it and re-upload.

**Comment by Laughing-q** [comment]
@johncf ok I've updated the weights, now the size looks good to me. You can re-download it if you'd like. :)
image

**Comment by nielsen** [comment]
Excited to see additional sizes for the lower end of the model architecture!

**Comment by glenn-jocher** [comment]
Thanks for your enthusiasm! 😊 We're excited too. Stay tuned for updates, and feel free to explore the current models. If you have any specific needs or questions, let us know! 🚀

**Pull request merged**
