### PR TITLE
Add hyperparameter search space to Docs

### PR DESCRIPTION
**Pull request by Y-T-G**
User doesn't understand how to define search space because there are no examples.
https://github.com/ultralytics/ultralytics/issues/18240#issuecomment-2545467686

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Enhanced hyperparameter tuning documentation for YOLO with detailed default search space info and customizability. 📚✨  

### 📊 Key Changes  
- Added **detailed tables** listing default hyperparameter search space parameters (e.g., learning rates, augmentations, etc.).  
- Explained each parameter's **type, range, and purpose**, improving clarity for users.  
- Provided a **custom search space example** for defining specific tuning parameters.  

### 🎯 Purpose & Impact  
- **Purpose**: Makes hyperparameter tuning more understandable and accessible for users by documenting defaults and flexibility.  
- **Impact**: Boosts user ability to fine-tune YOLO models efficiently, especially for different datasets or tasks. 💡

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a smooth and efficient review process, please take a moment to review the checklist below:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description and ensure it effectively addresses the linked issue (e.g., https://github.com/ultralytics/ultralytics/issues/18240). This helps us understand the scope of your contribution and its potential impact.  
- ✅ **Synchronize with Source**: Ensure your PR is up-to-date with the latest `main` branch of the repository. You can use the 'Update branch' button if it's available, or run `git pull` and `git merge main` locally to resolve any conflicts.  
- ✅ **Ensure CI Checks Pass**: Confirm that all automated [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks have passed. If any checks fail, feel free to reach out or investigate the logs to resolve the issues.  
- ✅ **Update Documentation**: Since this PR modifies documentation files, ensure that the changes are consistent with the latest format and style guidelines. You can review the [documentation contribution guide](https://docs.ultralytics.com/help/contributing/#documentation).  
- ✅ **Minimize Changes**: Keep your changes minimal and focused. This not only simplifies the review process but also ensures the enhancements are laser-focused and effective.  

Additionally, to further streamline the review process:

- If you have not already done so, please ensure you have signed our [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA" in this thread.
- If there are HyperParameter Tuning details that require usage demonstrations, feel free to include or expand upon them within the PR context. This can greatly aid in user understanding and adoption. 🎛️📚

This is an automated message 🤖 to help keep our community and contributions organized. An Ultralytics engineer will review your proposed changes and provide feedback soon. Thank you for contributing to Ultralytics! 🚀

**Review by ambitious-octopus — COMMENTED** [review]
Nice idea @Y-T-G ! I suggest trimming down the number of example parameters as it's currently quite extensive. What are your thoughts on this?

image

**Comment by Y-T-G** [comment]
@ambitious-octopus Sure. I copy-pasted it from the code.

https://github.com/ultralytics/ultralytics/blob/a3d807be13af2d8fa008f522020411d2d37e4860/ultralytics/engine/tuner.py#L77

Maybe I can make it similar to ray tune docs?

https://docs.ultralytics.com/integrations/ray-tune/#default-search-space-description

It documents the search space for that.

**Comment by glenn-jocher** [comment]
@Y-T-G @ambitious-octopus PR merged, this is a great change, nice work!

**Pull request merged**
