### PR TITLE
Addition to clear GPU memory after epoch 

### LINKED ISSUE #784: Cuda out of memory when training
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi,When training any YOLOv5su model, the memory usage on my GPU continues to get higher and higher as training continues.

<details> 
    <summary>Command Train Log</summary>

```
 $ yolo task=detect mode=train model=yolov5su.pt data=./data/mydata.yaml  batch=-1 epochs=100 imgsz=960  device=\'3\' rect=true


Ultralytics YOLOv8.0.25 🚀 Python-3.10.9 torch-1.13.1+cu117 CUDA:3 (NVIDIA GeForce RTX 3080 Ti, 12045MiB)
yolo/engine/trainer: task=detect, mode=train, model=yolov5su.pt, data=./data/crowdhuman.yaml, epochs=100, patience=50, batch=-1, imgsz=960, save=True, cache=False, device=3, workers=8, project=None, name=None, exist_ok=False, pretrained=False, optimizer=SGD, verbose=True, seed=0, deterministic=True, single_cls=False, image_weights=False, rect=True, cos_lr=False, close_mosaic=10, resume=False, overlap_mask=True, mask_ratio=4, dropout=0.0, val=True, save_json=False, save_hybrid=False, conf=None, iou=0.7, max_det=300, half=False, dnn=False, plots=True, source=None, show=False, save_txt=False, save_conf=False, save_crop=False, hide_labels=False, hide_conf=False, vid_stride=1, line_thickness=3, visualize=False, augment=False, agnostic_nms=False, classes=None, retina_masks=False, boxes=True, format=torchscript, keras=False, optimize=False, int8=False, dynamic=False, simplify=False, opset=None, workspace=4, nms=False, lr0=0.01, lrf=0.01, momentum=0.937, weight_decay=0.0005, warmup_epochs=3.0, warmup_momentum=0.8, warmup_bias_lr=0.1, box=7.5, cls=0.5, dfl=1.5, fl_gamma=0.0, label_smoothing=0.0, nbs=64, hsv_h=0.015, hsv_s=0.7, hsv_v=0.4, degrees=0.0, translate=0.1, scale=0.5, shear=0.0, perspective=0.0, flipud=0.0, fliplr=0.5, mosaic=1.0, mixup=0.0, copy_paste=0.0, cfg=None, v5loader=False, save_dir=runs/detect/train4
Overriding model.yaml nc=80 with nc=2

                   from  n    params  module                                       arguments
  0                  -1  1      3520  ultralytics.nn.modules.Conv                  [3, 32, 6, 2, 2]
  1                  -1  1     18560  ultralytics.nn.modules.Conv                  [32, 64, 3, 2]
  2                  -1  1     18816  ultralytics.nn.modules.C3                    [64, 64, 1]
  3                  -1  1     73984  ultralytics.nn.modules.Conv                  [64, 128, 3, 2]
  4                  -1  2    115712  ultralytics.nn.modules.C3                    [128, 128, 2]
  5                  -1  1    295424  ultralytics.nn.modules.Conv                  [128, 256, 3, 2]
  6                  -1  3    625152  ultralytics.nn.modules.C3                    [256, 256, 3]
  7                  -1  1   1180672  ultralytics.nn.modules.Conv                  [256, 512, 3, 2]
  8                  -1  1   1182720  ultralytics.nn.modules.C3                    [512, 512, 1]
  9                  -1  1    656896  ultralytics.nn.modules.SPPF                  [512, 512, 5]
 10                  -1  1    131584  ultralytics.nn.modules.Conv                  [512, 256, 1, 1]
 11                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 12             [-1, 6]  1         0  ultralytics.nn.modules.Concat                [1]
 13                  -1  1    361984  ultralytics.nn.modules.C3                    [512, 256, 1, False]
 14                  -1  1     33024  ultralytics.nn.modules.Conv                  [256, 128, 1, 1]
 15                  -1  1         0  torch.nn.modules.upsampling.Upsample         [None, 2, 'nearest']
 16             [-1, 4]  1         0  ultralytics.nn.modules.Concat                [1]
 17                  -1  1     90880  ultralytics.nn.modules.C3                    [256, 128, 1, False]
 18                  -1  1    147712  ultralytics.nn.modules.Conv                  [128, 128, 3, 2]
 19            [-1, 14]  1         0  ultralytics.nn.modules.Concat                [1]
 20                  -1  1    296448  ultralytics.nn.modules.C3                    [256, 256, 1, False]
 21                  -1  1    590336  ultralytics.nn.modules.Conv                  [256, 256, 3, 2]
 22            [-1, 10]  1         0  ultralytics.nn.modules.Concat                [1]
 23                  -1  1   1182720  ultralytics.nn.modules.C3                    [512, 512, 1, False]
 24        [17, 20, 23]  1   2116822  ultralytics.nn.modules.Detect                [2, [128, 256, 512]]
YOLOv5s summary: 262 layers, 9122966 parameters, 9122950 gradients, 24.0 GFLOPs

Transferred 421/427 items from pretrained weights
AutoBatch: Computing optimal batch size for imgsz=960
AutoBatch: CUDA:0 (NVIDIA GeForce RTX 3080 Ti) 11.76G total, 0.07G reserved, 0.07G allocated, 11.62G free
      Params      GFLOPs  GPU_mem (GB)  forward (ms) backward (ms)                   input                  output
     9122966        54.1         0.698         184.3         35.74        (1, 3, 960, 960)                    list
     9122966       108.2         1.168         68.04         34.16        (2, 3, 960, 960)                    list
     9122966       216.4         2.017         51.43         41.66        (4, 3, 960, 960)                    list
     9122966       432.8         3.660         116.2         37.55        (8, 3, 960, 960)                    list
     9122966       865.6         7.403         97.85         75.22       (16, 3, 960, 960)                    list
AutoBatch: Using batch-size 17 for CUDA:0 7.93G/11.76G (67%) ✅
optimizer: SGD(lr=0.01) with parameter groups 69 weight(decay=0.0), 76 weight(decay=0.00053125), 75 bias
WARNING ⚠️ 'rect=True' is incompatible with DataLoader shuffle, setting shuffle=False
......
Image sizes 960 train, 960 val
Using 8 dataloader workers
Logging results to runs/detect/train4
Starting training for 100 epochs...

      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
      1/100       8.6G      1.759      3.058      1.441       1165        960:   2%|▏         | 18/883 [00:29<23:24,  1.62s/it]
Traceback (most recent call last):

torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 3.12 GiB (GPU 0; 11.76 GiB total capacity; 3.92 GiB already allocated; 1.19 GiB free; 7.10 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
Sentry is attempting to send 2 pending error messages

```    

</details>

<details> 
    <summary>pip list</summary>
  
```
Package                  Version
------------------------ --------------------
absl-py                  1.4.0
asttokens                2.2.1
backcall                 0.2.0
cachetools               5.3.0
certifi                  2022.12.7
charset-normalizer       3.0.1
contourpy                1.0.7
cycler                   0.11.0
decorator                5.1.1
executing                1.2.0
fonttools                4.38.0
google-auth              2.16.0
google-auth-oauthlib     0.4.6
grpcio                   1.51.1
idna                     3.4
ipython                  8.9.0
jedi                     0.18.2
kiwisolver               1.4.4
Markdown                 3.4.1
markdown-it-py           2.1.0
MarkupSafe               2.1.2
matplotlib               3.6.3
matplotlib-inline        0.1.6
mdurl                    0.1.2
numpy                    1.24.1
nvidia-cublas-cu11       11.10.3.66
nvidia-cuda-nvrtc-cu11   11.7.99
nvidia-cuda-runtime-cu11 11.7.99
nvidia-cudnn-cu11        8.5.0.96
oauthlib                 3.2.2
onnx                     1.13.0
onnx-simplifier          0.4.13
opencv-python            4.7.0.68
packaging                23.0
pandas                   1.5.3
parso                    0.8.3
pexpect                  4.8.0
pickleshare              0.7.5
Pillow                   9.4.0
pip                      22.3.1
prompt-toolkit           3.0.36
protobuf                 3.20.3
psutil                   5.9.4
ptyprocess               0.7.0
pure-eval                0.2.2
pyasn1                   0.4.8
pyasn1-modules           0.2.8
Pygments                 2.14.0
pyparsing                3.0.9
python-dateutil          2.8.2
pytz                     2022.7.1
PyYAML                   6.0
requests                 2.28.2
requests-oauthlib        1.3.1
rich                     13.3.1
rsa                      4.9
scipy                    1.10.0
seaborn                  0.12.2
sentry-sdk               1.14.0
setuptools               65.6.3
six                      1.16.0
stack-data               0.6.2
tensorboard              2.11.2
tensorboard-data-server  0.6.1
tensorboard-plugin-wit   1.8.1
thop                     0.1.1.post2209072238
torch                    1.13.1
torchvision              0.14.1
tqdm                     4.64.1
traitlets                5.9.0
typing_extensions        4.4.0
ultralytics              8.0.25
urllib3                  1.26.14
wcwidth                  0.2.6
Werkzeug                 2.2.2
wheel                    0.37.1

```

</details>

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Burhan-Q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimization of GPU memory usage during training in the Ultralytics YOLO framework. 

### 📊 Key Changes
- Added a line of code to clear the GPU's VRAM cache at the end of each training epoch.

### 🎯 Purpose & Impact
- **Purpose**: To prevent out-of-memory errors that can occur during intensive training sessions by freeing up unused GPU memory.
- **Impact**:
  - Users may experience more stable training sessions with reduced chance of interruption due to memory issues.
  - Could potentially allow for the use of larger batch sizes or more complex models within the same GPU memory constraints.

### CODE REVIEW

**Comment by Burhan-Q** [comment]
Still need to collect performance deltas.

**Comment by Burhan-Q** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@Burhan-Q thanks! Let us know if this frees memory during training for you.

**Comment by Burhan-Q** [comment]
## Test setup:

```python
from ultralytics import YOLO

w = "yolov8n.pt" # first two runs
w = "yolov8x.pt" # second two runs

m = YOLO(w)
m.to('cuda')
m.overrides['data'] = 'coco128.yaml'

m.train(epochs=30)
```

## Results

`Ultralytics YOLOv8.0.55 Python-3.11.0 torch-2.0.0+cu117 CUDA:0 (NVIDIA RTX A4000, 16376MiB)`

### Run 1 
YOLOv8-nano
No code change
vRAM min = 2.71G
vRAM max = 3.32G

### Run 2
YOLOv8-nano
After code change
vRAM min = 2.48G
vRAM max = 2.64G

### Run 3
YOLOv8-xtra_lorge
No code change
vRAM min = 13.7G
vRAM max = 15.4G

### Run 4
YOLOv8-xtra_lorge
After code change
vRAM min = 13.7G
vRAM max = 14.1G

## Notes
Not really an appreciable difference in training time for these tests, but on custom dataset (not shareable unfortunately), I observed training time per epoch decrease from 1:00 (one minute) to 0:42. There should be a noticeable difference in vRAM usage with the addition of clearing the CUDA cache at the end of each epoch

**Comment by glenn-jocher** [comment]
@Burhan-Q thank you for sharing your test setup and results. It's good to hear that clearing the CUDA cache at the end of each epoch helped reduce vRAM usage. It's also interesting to note that there was a decrease in training time per epoch on your custom dataset. Keep up the good work!

**Comment by Burhan-Q** [comment]
PR from discussion on Issue #784

**Comment by Burhan-Q** [comment]
I'm happy to have contributed at all, and thank you and your team for all you do!

**Comment by glenn-jocher** [comment]
@Burhan-Q thank you for bringing this to our attention. We appreciate any contribution, however, it seems that this specific pull request may not be aligned with the goals and vision of our project.
We strive to provide a product that is easy to use and reliable, while maintaining a clear and maintainable codebase. 

We encourage you to continue contributing to the project, and we invite you to consult our documentation to ensure that your code aligns with the project's goals and coding standards.

Thank you again for your interest in and support for our project.

**Comment by glenn-jocher** [comment]
@Burhan-Q thank you very much for your kind words! Our team is happy to be able to provide support for Ultralytics YOLOv8, and we greatly appreciate any contributions to the project. If you have any further questions or concerns, please don't hesitate to reach out to us.

**Comment by glenn-jocher** [comment]
@Burhan-Q PR merged into updates branch for publishing with 8.0.59 later today. Thank you for your contributions!

**Pull request merged**
