### PR TITLE
Add C# example and tracker Docs

### PR DESCRIPTION
**Pull request by AyushExel**
@glenn-jocher @Laughing-q 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancement of Ultralytics YOLO with new documentation for object tracking and updated examples.

### 📊 Key Changes
- 📝 Added a new `tracking.md` document for multi-object tracking, including usage examples for both Python and CLI.
- 🔍 Implemented tracking algorithms Bot-Sort and ByteTrack, with Bot-Sort set as the default.
- ✨ Enabled tracking for both detection and segmentation models.

### 🎯 Purpose & Impact
- 🤖 **Purpose**: To provide users with comprehensive information on how to use the Ultralytics object tracking features, as well as to improve and update example applications.
- 🎉 **Impact**: Users can now easily integrate object tracking into their video processing tasks, enhancing the capabilities of Ultralytics YOLO models. The updated example applications showcase practical implementations, helping developers to better understand and apply YOLO models in various programming environments.
- 🚀 **Possible Uses**: These changes open up new possibilities for advanced real-time video analysis, potentially benefiting applications in surveillance, sports analytics, and more, where tracking the movement of objects is essential.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel is this good to merge?

**Comment by AyushExel** [comment]
@glenn-jocher yeah it's good to go from my side. 
I think we should wait for @Laughing-q to review.

**Comment by Laughing-q** [comment]
@AyushExel updated the `tracking.md`.
But there are conflicts as `8.0.41` merged, I wanted to resolve it but I'm not sure I can do it correctly since I don't really know which parts you've modified.

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q sorry guys, this PR got all messed up because I changed the commit branch to updates but then merged updates for 8.0.40 without this, which reset it back to main and caused the problems.

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q I'll see if I can fix it, if not I'll close and we'll make a new one.

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q ok this PR is deconflicted now and ready to merge into updates branch for 8.0.41. Can you guys please update this and let me know when it's ready to merge? Thanks!

**Comment by AyushExel** [comment]
Yes its ready @glenn-jocher

**Comment by glenn-jocher** [comment]
@AyushExel PR merged!

**Pull request merged**
