### PR TITLE
Update TRT Workspace docs to float

### PR DESCRIPTION
**Pull request by Eunchan24**
Good day, I think the type of 'workspace' has changed to int. I will update the document 'export.md ' accordingly.
Please check it out. Thank you

### Summary
Change from float type to int type 

### Minimal Reproducible Example

```python
# ultralytics==8.1.37
import os 
ROOT_PATH = os.path.dirname(os.getcwd())
from PIL import Image
from ultralytics import YOLO 

model = YOLO("yolov8n.pt")
imgsz = 1280
half = False 
dynamic = True
workspace = 8.
model.export(format="engine", imgsz=imgsz, half=half, dynamic=dynamic, workspace=workspace)
```
_Error message_
```
TypeError: 'workspace=8.0' is of invalid type float. 'workspace' must be an int (i.e. 'workspace=8')
```
---
I have read the CLA Document and I hereby sign the CLA

### CODE REVIEW

**Comment by Eunchan24** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Eunchan24** [comment]
recheck

**Comment by Eunchan24** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by Eunchan24** [comment]
recheck

**Comment by Eunchan24** [comment]
recheck

**Comment by Eunchan24** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Eunchan24** [comment]
recheck

**Comment by glenn-jocher** [comment]
@Eunchan24 your code works correctly for me. Ah I see, you just want to update the docs from int to float, got it!

Screenshot 2024-04-02 at 11 48 16

**Comment by glenn-jocher** [comment]
@Eunchan24 oh ok I've got it now, sorry for the confusion. `workspace` has been updated to float recently, please update your package for this to work. Docs are aligned with latest package version:

```
pip install -U ultralytics
```

**Pull request merged**
