### PR TITLE
check value bounded between 0 and 1

### PR DESCRIPTION
**Pull request by Kayzwer**
### Summary
🐛📏🖼️

Fixed a bug in `ultralytics/data/utils.py` that caused out-of-range keypoints. Added a validation check to `verify_image_label` to ensure that keypoint and bounding box coordinates are normalized and within the image bounds.

> _`verify_image_label`_
> _Keeps keypoints in the frame_
> _Autumn bug fixing_

### Walkthrough
*  Fix keypoint label validation to prevent out-of-range errors ([link](https://github.com/ultralytics/ultralytics/pull/5229/files?diff=unified&w=0#diff-ec08ff3087043c4949ebd4c16ec17073bdb827e25ff1840d1eb7c87841b8911cL118-R122))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updating label verification to streamline label checks in Ultralytics software.

### 📊 Key Changes
- Refined assertion checks for label normalization and boundaries by concentrating on relevant points.
- Simplified label shape validation for keypoints and non-keypoints.
- More intuitive checking of maximum class labels against the dataset class count.
- Consolidation of empty label array creation into a single line.

### 🎯 Purpose & Impact
- **Improved Code Clarity:** Reducing complexity and making the code more readable for developers.
- **Robust Error Checking:** Enhanced checks for label data help ensure data integrity for training robustness.
- **Streamlined Label Validation:** Optimizing the way keypoints and labels are validated for different conditions, making the process more efficient.
- **Less Redundancy:** Fewer lines of code to achieve the same purpose means less room for error and easier maintenance. 

The impact is primarily behind the scenes, with potential for fewer bugs, easier debugging, and maintaining label-handling code. ☔ Users working with Ultralytics software for machine learning tasks should experience smoother validation of their label data, leading to better model performance and reduced risk of errors due to mislabeled data. 🎯

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Kayzwer I see the intention here. I've implemented this in a slightly different way with some new optimizations that speedup the checks by about 2x

**Comment by glenn-jocher** [comment]
Should be good now. I'll let the CI run and then merge into dev branch for 8.0.193

**Comment by Kayzwer** [comment]
> @Kayzwer I see the intention here. I've implemented this in a slightly different way with some new optimizations that speedup the checks by about 2x

I really want to know how you optimize that, please tell me

**Comment by glenn-jocher** [comment]
Oh it turns out getting the max and min value and then checking the inequality is about 2x faster than doing the inequality on the array and then doing .all()

**Comment by glenn-jocher** [comment]
@Kayzwer PR merged!! 

Thank you for your contributions.

**Pull request merged**
