### PR TITLE
Allows any PyTorch install except `torch==2.4.0` on Windows

### PR DESCRIPTION
**Pull request by Burhan-Q**
Update `pyproject.toml` to allow for _any_ install except for PyTorch 2.4.0 when on Windows.

[PyTorch 2.4.1 released](https://github.com/pytorch/pytorch/releases/tag/v2.4.1) which fixes CPU inference issues (see #15049)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Fixes compatibility issues with PyTorch on Windows systems.

### 📊 Key Changes
- Adjusted dependency rules to exclude PyTorch 2.4.0 on Windows.
- Updated warning message logic for PyTorch version 2.4.0.

### 🎯 Purpose & Impact
- ⚙️ **Purpose**: Prevent known errors caused by PyTorch 2.4.0 on Windows CPUs.
- 🚀 **Impact**: Enhances stability and reliability for Windows users by avoiding a problematic version of PyTorch, guiding them to more stable versions.

### CODE REVIEW

**Comment by Burhan-Q** [comment]
Tested locally (using older `ultralytics` version) in `venv` that uses `torch==2.4.0`

```
Package            Version
------------------ ------------
certifi            2024.7.4    
charset-normalizer 3.3.2       
colorama           0.4.6       
contourpy          1.2.1       
cycler             0.12.1      
filelock           3.13.1      
fonttools          4.53.1      
fsspec             2024.2.0    
idna               3.7
Jinja2             3.1.3
kiwisolver         1.4.5
MarkupSafe         2.1.5
matplotlib         3.9.1
mpmath             1.3.0
networkx           3.2.1
numpy              1.26.3
opencv-python      4.10.0.84
packaging          24.1
pandas             2.2.2
pillow             10.2.0
pip                22.3.1
psutil             6.0.0
py-cpuinfo         9.0.0
pyparsing          3.1.2
pyreadline3        3.4.1
python-dateutil    2.9.0.post0
pytz               2024.1
PyYAML             6.0.1
requests           2.32.3
scipy              1.14.0
seaborn            0.13.2
setuptools         65.5.0
six                1.16.0
sympy              1.12
torch              2.4.0+cu124
torchvision        0.19.0+cu124
tqdm               4.66.4
typing_extensions  4.9.0
tzdata             2024.1
ultralytics-thop   2.0.0
urllib3            2.2.2
```

```
pip install -e .\ultralytics\ --dry-run

Looking in indexes: https://pypi.org/simple, https://pypi.ngc.nvidia.com
Obtaining file:///ultralytics

  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: py-cpuinfo in .ultra/lib/site-packages (from ultralytics==8.2.68) (9.0.0)
Requirement already satisfied: pandas>=1.1.4 in .ultra/lib/site-packages (from ultralytics==8.2.68) (2.2.2)
Requirement already satisfied: scipy>=1.4.1 in .ultra/lib/site-packages (from ultralytics==8.2.68) (1.14.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (1.26.3)
Requirement already satisfied: torchvision>=0.9.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (0.19.0+cu124)
Collecting torch!=2.4.0,>=1.8.0
  Downloading torch-2.4.1-cp310-cp310-win_amd64.whl (199.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 199.4/199.4 MB 46.7 MB/s eta 0:00:00
Requirement already satisfied: opencv-python>=4.6.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (4.10.0.84)
Requirement already satisfied: pillow>=7.1.2 in .ultra/lib/site-packages (from ultralytics==8.2.68) (10.2.0)
Requirement already satisfied: requests>=2.23.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (2.32.3)
Requirement already satisfied: tqdm>=4.64.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (4.66.4)
Requirement already satisfied: psutil in .ultra/lib/site-packages (from ultralytics==8.2.68) (6.0.0)
Requirement already satisfied: seaborn>=0.11.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (0.13.2)
Requirement already satisfied: ultralytics-thop>=2.0.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (2.0.0)
Requirement already satisfied: matplotlib>=3.3.0 in .ultra/lib/site-packages (from ultralytics==8.2.68) (3.9.1)
Requirement already satisfied: pyyaml>=5.3.1 in .ultra/lib/site-packages (from ultralytics==8.2.68) (6.0.1)
Requirement already satisfied: cycler>=0.10 in .ultra/lib/site-packages (from matplotlib>=3.3.0->ultralytics==8.2.68) (0.12.1)
Requirement already satisfied: contourpy>=1.0.1 in .ultra/lib/site-packages (from matplotlib>=3.3.0->ultralytics==8.2.68) (1.2.1)
Requirement already satisfied: python-dateutil>=2.7 in .ultra/lib/site-packages (from matplotlib>=3.3.0->ultralytics==8.2.68) (2.9.0.post0)
Requirement already satisfied: kiwisolver>=1.3.1 in .ultra/lib/site-packages (from matplotlib>=3.3.0->ultralytics==8.2.68) (1.4.5)
Requirement already satisfied: packaging>=20.0 in .ultra/lib/site-packages (from matplotlib>=3.3.0->ultralytics==8.2.68) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in .ultra/lib/site-packages (from matplotlib>=3.3.0->ultralytics==8.2.68) (3.1.2)
Requirement already satisfied: fonttools>=4.22.0 in .ultra/lib/site-packages (from matplotlib>=3.3.0->ultralytics==8.2.68) (4.53.1)
Requirement already satisfied: pytz>=2020.1 in .ultra/lib/site-packages (from pandas>=1.1.4->ultralytics==8.2.68) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in .ultra/lib/site-packages (from pandas>=1.1.4->ultralytics==8.2.68) (2024.1)
Requirement already satisfied: idna<4,>=2.5 in .ultra/lib/site-packages (from requests>=2.23.0->ultralytics==8.2.68) (3.7)
Requirement already satisfied: certifi>=2017.4.17 in .ultra/lib/site-packages (from requests>=2.23.0->ultralytics==8.2.68) (2024.7.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in .ultra/lib/site-packages (from requests>=2.23.0->ultralytics==8.2.68) (2.2.2)
Requirement already satisfied: charset-normalizer<4,>=2 in .ultra/lib/site-packages (from requests>=2.23.0->ultralytics==8.2.68) (3.3.2)
Requirement already satisfied: fsspec in .ultra/lib/site-packages (from torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (2024.2.0)
Requirement already satisfied: jinja2 in .ultra/lib/site-packages (from torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (3.1.3)
Requirement already satisfied: typing-extensions>=4.8.0 in .ultra/lib/site-packages (from torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (4.9.0)
Requirement already satisfied: networkx in .ultra/lib/site-packages (from torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (3.2.1)
Requirement already satisfied: sympy in .ultra/lib/site-packages (from torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (1.12)
Requirement already satisfied: filelock in .ultra/lib/site-packages (from torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (3.13.1)
Collecting torchvision>=0.9.0
  Downloading torchvision-0.19.1-cp310-cp310-win_amd64.whl (1.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 85.2 MB/s eta 0:00:00
Requirement already satisfied: colorama in .ultra/lib/site-packages (from tqdm>=4.64.0->ultralytics==8.2.68) (0.4.6)
Requirement already satisfied: six>=1.5 in .ultra/lib/site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics==8.2.68) (1.16.0)       
Requirement already satisfied: MarkupSafe>=2.0 in .ultra/lib/site-packages (from jinja2->torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (2.1.5)
Requirement already satisfied: mpmath>=0.19 in .ultra/lib/site-packages (from sympy->torch!=2.4.0,>=1.8.0->ultralytics==8.2.68) (1.3.0)
Would install torch-2.4.1 torchvision-0.19.1 ultralytics-8.2.68
```

**Comment by Skillnoob** [comment]
The version check of the following lines
https://github.com/ultralytics/ultralytics/blob/bd696a1b8eff84e358229acf8ed2379bc51d85de/ultralytics/utils/torch_utils.py#L48-L52
should be changed to:
```python
if WINDOWS and check_version(torch.__version__, "==2.4.0"):  # reject all versions of 2.4 on Windows
    LOGGER.warning(
        "WARNING ⚠️ Known issue with torch==2.4.0 on Windows with CPU, recommend upgrading to torch>=2.4.1 to resolve "
        "https://github.com/ultralytics/ultralytics/issues/15049"
    )
```

**Comment by Burhan-Q** [comment]
@Skillnoob thanks for pointing that out, I updated in ee538433224dda0b140a4de269017314b625d4e7 with a minor tweak (there's a check for `torch==2.4.0` just a few lines above, so reusing that).

**Comment by Skillnoob** [comment]
The `TORCH_2_4` check is also true for `torch==2.4.1` because `check_version` defaults to `>=` and not `=='`. The string to check would need to be `"==2.4.0"`.

**Comment by Burhan-Q** [comment]
Yup, you're right, I put it back to the way you had it. Thank you again!

**Comment by glenn-jocher** [comment]
@Burhan-Q @Skillnoob thanks guys, PR merged!

**Pull request merged**
