### PR TITLE
Add obb_segment and obb_pose

### PR DESCRIPTION
**Pull request by yzqxy**
On my own segment dataset, the results obtained from training with "**obb_segment**" are superior to those obtained from training with "segment".So, providing "**obb_segment**" as an optional training option for users to utilize.
"**obb_pose**" is added as a training option specifically to address specialized task requirements.
You can replace the "segment" command in the training script with "obb_segment" to train a model that outputs rbboxes and segmentation. Similarly, replace "pose" with "obb_pose" to train a model that outputs rbboxes and keypoints. Please note that for keypoints, the original bboxes xywh annotations need to be replaced with the format of rbboxes xyxyxyxy.
The configuration file has been updated to include yolov8-obb-pose.yaml and yolov8-obb-segment.yaml.
I have read the CLA Document and I sign the CLA.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR introduces new tasks for Oriented Bounding Box (OBB) segmentation and pose estimation, adding support for them throughout the Ultralytics codebase.

### 📊 Key Changes
- **New Tasks and Modes:**
  - Added "obb_segment" and "obb_pose" to task and mode definitions.
  
- **Model Definitions:**
  - Created new model configurations (`yolov8-obb-pose.yaml` and `yolov8-obb-segment.yaml`).
  
- **Dataset Handling:**
  - Updated data loaders to handle new tasks "obb_segment" and "obb_pose".
  
- **Model Training and Validation:**
  - Added modules for training, validating, and predicting with the new OBB segmentation and pose models.
  - Specific trainers, validators, and predictors for "obb_segment" and "obb_pose".

- **Neural Network Modules:**
  - Introduced new heads (`OBB_Segment`, `OBB_Pose`) in `nn/modules/head.py`.

- **Loss Functions:**
  - Added new loss functions to handle OBB segmentation and pose estimation.

### 🎯 Purpose & Impact
- **Enhanced Object Detection:**
  - Supports new tasks aimed at more specialized object detection requirements like oriented bounding boxes with pose keypoints or segmentation masks.
  
- **Application Expansion:**
  - Opens up new possibilities for applications requiring precise object orientation and keypoint detection, such as robotics, medical imaging, and advanced surveillance.
  
- **Improved Accuracy:**
  - Better segmentation and pose accuracy due to tailored models and loss functions. 

Overall, these changes significantly broaden the capabilities of the Ultralytics YOLO models, making them more versatile and powerful for a wide range of tasks.🚀

### CODE REVIEW

**Comment by 15738281321** [comment]
hello,This is my train info
import warnings
warnings.filterwarnings('ignore')
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/models/v8/yolov8-obb-pose.yaml')
    model.train(data=r'/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/datasets/mydata.yaml',
        cache=False,
        imgsz=640,
        epochs=5,
        batch=4,
        close_mosaic=10,
        workers=0,
        device='0',
        optimizer='Adam',
        amp=True,
        lr0=0.001,
        project='runs/train',
        name='exp',
    )
    Used your coco_obb_pose.yaml document.And mydata.yaml 
    path: /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose
train: images/train
val: images/val

kpt_shape: [3, 2] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
flip_idx: [0, 1, 2]
# Classes
names:
  0: windmill
My labelTxt context is
0 0.0722 0.1414 0.1220 0.0994 0.1962 0.1875 0.1463 0.2295 0.1163 0.1406 0.1319 0.1771 0.1545 0.1944 
0 0.7543 0.3659 0.8273 0.3044 0.8941 0.3837 0.8211 0.4452 0.8073 0.3542 0.8247 0.3715 0.8420 0.4028
0 0.2059 0.5453 0.2593 0.5002 0.3264 0.5799 0.2729 0.6249 0.2535 0.5417 0.2622 0.5729 0.2812 0.5972
0 0.2122 0.7698 0.2806 0.7324 0.3490 0.8576 0.2806 0.8950 0.2674 0.7882 0.2830 0.8177 0.2986 0.8368
I don't no why my training is wrong with this info
train: Scanning /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/labels/train.cache... 5 images, 0 backgrounds, 5 corrupt: 100%|
train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/00052.jpg: ignoring corrupt image/label: labels require 11 columns each
train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/00693.jpg: ignoring corrupt image/label: labels require 11 columns each
train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/02214.jpg: ignoring corrupt image/label: labels require 11 columns each
train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/03345.jpg: ignoring corrupt image/label: labels require 11 columns each
train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/03707.jpg: ignoring corrupt image/label: labels require 11 columns each
WARNING ⚠️ No images found in /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance.
Traceback (most recent call last):
  File "train.py", line 9, in <module>
    model.train(
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/model.py", line 674, in train
    self.trainer.train()
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 199, in train
    self._do_train(world_size)
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 313, in _do_train
    self._setup_train(world_size)
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 277, in _setup_train
    self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train")
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader
    dataset = self.build_dataset(dataset_path, mode, batch_size)
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset
    return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs)
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/build.py", line 87, in build_yolo_dataset
    return dataset(
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 271, in __init__
    super().__init__(*args, data=data, task=task, **kwargs)
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 70, in __init__
    super().__init__(*args, **kwargs)
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/base.py", line 74, in __init__
    self.labels = self.get_labels()
  File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 168, in get_labels
    len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths))
ValueError: not enough values to unpack (expected 3, got 0)

Can you help me?please Thank you!!!

**Comment by glenn-jocher** [comment]
Hello @15738281321,

Thank you for providing detailed information about your training setup and the issue you're encountering. Let's work through this step-by-step to identify and resolve the problem.

### Key Points to Address:

1. **Label Format**: The error message indicates that your labels are not in the expected format. For `obb_pose`, the labels should include the oriented bounding box (OBB) coordinates and keypoints in the format `class x1 y1 x2 y2 x3 y3 x4 y4 kpt1_x kpt1_y kpt2_x kpt2_y ...`. Each line should have 11 columns for a single keypoint (8 for OBB + 3 for keypoints).

2. **Dataset Validation**: Ensure that your dataset adheres to the required format. The warning messages suggest that the labels are not correctly formatted, leading to the training process ignoring these images.

### Steps to Resolve:

1. **Verify Label Format**:
   - Ensure each label file has the correct number of columns. For `obb_pose`, each line should have the format:
     ```
     class x1 y1 x2 y2 x3 y3 x4 y4 kpt1_x kpt1_y kpt2_x kpt2_y ...
     ```
   - For example, if you have 3 keypoints, each label line should have 14 columns (1 for class + 8 for OBB + 6 for keypoints).

2. **Check Dataset Configuration**:
   - Ensure your `mydata.yaml` file correctly points to the dataset paths and includes the necessary configurations for keypoints.
   - Example:
     ```yaml
     path: /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose
     train: images/train
     val: images/val
     kpt_shape: [3, 2]  # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible)
     flip_idx: [0, 1, 2]
     names:
       0: windmill
     ```

3. **Update and Re-run**:
   - Ensure you are using the latest versions of `torch` and `ultralytics`. You can update them using:
     ```bash
     pip install --upgrade torch ultralytics
     ```
   - Re-run your training script after verifying the label format and dataset configuration.

### Example Code for Training:

Here’s an example of how your training script should look:

```python
import warnings
warnings.filterwarnings('ignore')
from ultralytics import YOLO

if __name__ == '__main__':
    model = YOLO('/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/models/v8/yolov8-obb-pose.yaml')
    model.train(
        data='/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/datasets/mydata.yaml',
        cache=False,
        imgsz=640,
        epochs=5,
        batch=4,
        close_mosaic=10,
        workers=0,
        device='0',
        optimizer='Adam',
        amp=True,
        lr0=0.001,
        project='runs/train',
        name='exp',
    )
```

### Additional Resources:
For more detailed guidance on dataset formatting, you can refer to our [dataset formatting documentation](https://docs.ultralytics.com/datasets).

If you continue to experience issues, please provide a minimum reproducible example of your dataset and code. This will help us investigate further and provide a more accurate solution.

**Comment by Alarmod** [comment]
obb_segment are most waitable for me

**Comment by glenn-jocher** [comment]
Thank you for your interest in `obb_segment`. Please ensure you're using the latest version of the package and follow the updated documentation for implementation. If you encounter any issues, feel free to report them.

**Comment by 1369355119** [comment]
> hello,This is my train info import warnings warnings.filterwarnings('ignore') from ultralytics import YOLO
> 
> if **name** == '**main**': model = YOLO('/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/models/v8/yolov8-obb-pose.yaml') model.train(data=r'/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/datasets/mydata.yaml', cache=False, imgsz=640, epochs=5, batch=4, close_mosaic=10, workers=0, device='0', optimizer='Adam', amp=True, lr0=0.001, project='runs/train', name='exp', ) Used your coco_obb_pose.yaml document.And mydata.yaml path: /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose train: images/train val: images/val
> 
> kpt_shape: [3, 2] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible) flip_idx: [0, 1, 2]
> 
> # Classes
> names: 0: windmill My labelTxt context is 0 0.0722 0.1414 0.1220 0.0994 0.1962 0.1875 0.1463 0.2295 0.1163 0.1406 0.1319 0.1771 0.1545 0.1944 0 0.7543 0.3659 0.8273 0.3044 0.8941 0.3837 0.8211 0.4452 0.8073 0.3542 0.8247 0.3715 0.8420 0.4028 0 0.2059 0.5453 0.2593 0.5002 0.3264 0.5799 0.2729 0.6249 0.2535 0.5417 0.2622 0.5729 0.2812 0.5972 0 0.2122 0.7698 0.2806 0.7324 0.3490 0.8576 0.2806 0.8950 0.2674 0.7882 0.2830 0.8177 0.2986 0.8368 I don't no why my training is wrong with this info train: Scanning /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/labels/train.cache... 5 images, 0 backgrounds, 5 corrupt: 100%| train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/00052.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/00693.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/02214.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/03345.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/03707.jpg: ignoring corrupt image/label: labels require 11 columns each WARNING ⚠️ No images found in /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance. Traceback (most recent call last): File "train.py", line 9, in model.train( File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/model.py", line 674, in train self.trainer.train() File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 199, in train self._do_train(world_size) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 313, in _do_train self._setup_train(world_size) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 277, in _setup_train self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train") File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader dataset = self.build_dataset(dataset_path, mode, batch_size) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/build.py", line 87, in build_yolo_dataset return dataset( File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 271, in **init** super().**init**(*args, data=data, task=task, **kwargs) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 70, in **init** super().**init**(*args, **kwargs) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/base.py", line 74, in **init** self.labels = self.get_labels() File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 168, in get_labels len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths)) ValueError: not enough values to unpack (expected 3, got 0)
> 
> Can you help me?please Thank you!!!

hello，How to solve the problem？thanks！

**Comment by 15738281321** [comment]
sorry,I can't solve it.Because my labels are not match the input.And I don't do this now.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年11月28日(星期四) 晚上7:56
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] Add obb_segment and obb_pose (PR #13381)














  
hello,This is my train info import warnings warnings.filterwarnings('ignore') from ultralytics import YOLO
 
if name == 'main': model = YOLO('/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/models/v8/yolov8-obb-pose.yaml') model.train(data=r'/home/fengcui/ultralytics-obb_segment-main/ultralytics/cfg/datasets/mydata.yaml', cache=False, imgsz=640, epochs=5, batch=4, close_mosaic=10, workers=0, device='0', optimizer='Adam', amp=True, lr0=0.001, project='runs/train', name='exp', ) Used your coco_obb_pose.yaml document.And mydata.yaml path: /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose train: images/train val: images/val
 
kpt_shape: [3, 2] # number of keypoints, number of dims (2 for x,y or 3 for x,y,visible) flip_idx: [0, 1, 2]
 
Classes
 
names: 0: windmill My labelTxt context is 0 0.0722 0.1414 0.1220 0.0994 0.1962 0.1875 0.1463 0.2295 0.1163 0.1406 0.1319 0.1771 0.1545 0.1944 0 0.7543 0.3659 0.8273 0.3044 0.8941 0.3837 0.8211 0.4452 0.8073 0.3542 0.8247 0.3715 0.8420 0.4028 0 0.2059 0.5453 0.2593 0.5002 0.3264 0.5799 0.2729 0.6249 0.2535 0.5417 0.2622 0.5729 0.2812 0.5972 0 0.2122 0.7698 0.2806 0.7324 0.3490 0.8576 0.2806 0.8950 0.2674 0.7882 0.2830 0.8177 0.2986 0.8368 I don't no why my training is wrong with this info train: Scanning /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/labels/train.cache... 5 images, 0 backgrounds, 5 corrupt: 100%| train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/00052.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/00693.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/02214.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/03345.jpg: ignoring corrupt image/label: labels require 11 columns each train: WARNING ⚠️ /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/images/train/03707.jpg: ignoring corrupt image/label: labels require 11 columns each WARNING ⚠️ No images found in /home/fengcui/ultralytics-obb_segment-main/ultralytics/datasets/DIOR_pose/labels/train.cache, training may not work correctly. See https://docs.ultralytics.com/datasets for dataset formatting guidance. Traceback (most recent call last): File "train.py", line 9, in model.train( File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/model.py", line 674, in train self.trainer.train() File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 199, in train self._do_train(world_size) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 313, in _do_train self._setup_train(world_size) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/engine/trainer.py", line 277, in _setup_train self.train_loader = self.get_dataloader(self.trainset, batch_size=batch_size, rank=RANK, mode="train") File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/models/yolo/detect/train.py", line 49, in get_dataloader dataset = self.build_dataset(dataset_path, mode, batch_size) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/models/yolo/detect/train.py", line 43, in build_dataset return build_yolo_dataset(self.args, img_path, batch, self.data, mode=mode, rect=mode == "val", stride=gs) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/build.py", line 87, in build_yolo_dataset return dataset( File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 271, in init super().init(*args, data=data, task=task, **kwargs) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 70, in init super().init(*args, **kwargs) File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/base.py", line 74, in init self.labels = self.get_labels() File "/home/fengcui/ultralytics-obb_segment-main/ultralytics/data/dataset.py", line 168, in get_labels len_cls, len_boxes, len_segments = (sum(x) for x in zip(*lengths)) ValueError: not enough values to unpack (expected 3, got 0)
 
Can you help me?please Thank you!!!
  
hello，How to solve the problem？thanks！

**Comment by glenn-jocher** [comment]
Thank you for clarifying! The issue stems from label misformatting. For `obb_pose` training, each label must follow the format: `class x1 y1 x2 y2 x3 y3 x4 y4 kpt1_x kpt1_y...` where the number of columns depends on your object and keypoint specifications. Ensure every label file meets this requirement. Refer to [Ultralytics dataset formatting guide](https://docs.ultralytics.com/datasets) for additional details. Let us know if further assistance is needed!

**Pull request closed without merging**
