### PR TITLE
`ultralytics 8.0.43` optimized `Results` class and fixes

### PR DESCRIPTION
**Pull request by glenn-jocher**
@AyushExel @Laughing-q I've tried to optimize Results class here. Now that I've reviewed it I understand the issue better. It looks like this is simple and it's working so for now let's keep using it until we have time to review more thoroughly.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updates CI workflow, Python compatibility, and improves benchmarking logic.

### 📊 Key Changes
- CI now includes Python 3.7 to 3.10 for matrix tests.
- Benchmark step in CI generalized for different model names.
- Added Python 3.10 compatibility (previously restricted to <=3.9).
- New `save` flag in configuration for saving images with results.
- License reference in `setup.cfg` now allows multiple files.
- Adapted tests to be more robust and support additional image formats.
- Bumped Ultralytics version to 8.0.43.
- Introduced a new `register_tracker` function for tracking.
- Added a `track` mode option.
- Streamlined image loader to support non-standard image metadata.
- Clarified usage instructions in the HUB dataset statistics.
- Enhanced YOLOv8 with benchmarking and tracking abilities.
- Improved result output handling and modularity in the Results class.
- Trainer now prepares plots for training labels visualization.
- Added descriptions and annotations to several modules for better clarity.
- Optimized benchmarking to include device selection, downloading assets, and running predictions.
- Some plotting utility optimizations and added functionality for label plotting.
- Several internal refactoring changes for code cleanliness and maintainability.

### 🎯 Purpose & Impact
- Expands CI testing to ensure compatibility across a wider range of Python versions, enhancing reliability for users on different setups.
- Allows dynamic benchmarking across various models, offering more versatile testing capabilities to users.
- The new `save` option gives users control over saving output images directly through configuration, improving usability.
- The introduction of YOLOv8 tracking features and export benchmarking opens up new performance evaluation and application possibilities.
- Result class enhancements improve the workflow for developers working with predictions and encourage modular use in custom scripts.

These changes enhance the functionality and reliability of the Ultralytics software suite, paving the way for broader application in real-world scenarios and research, and ensuring compatibility with a wider array of environments. 🚀

### CODE REVIEW

**Comment by AyushExel** [comment]
Looks good!

**Comment by glenn-jocher** [comment]
@AyushExel do you think we should hide attributes that aren't relevant to the current results, i.e. only define results.masks if it's a segmentation result rather than set it to None?

**Comment by AyushExel** [comment]
@glenn-jocher what do you mean by hide? Currently if for detection tasks result.masks will be None. Do you want to hide it from the repr string? If so, yeah I guess we can.

**Comment by glenn-jocher** [comment]
@AyushExel oh by "hide" I mean to just not define it if it is None, i.e.:
```
if masks is not None
    self.masks = ...
```

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q per #1078 I think we need to add greyscale and PNG with alpha image loading with cv2 and PIL to tests.

**Comment by AyushExel** [comment]
@glenn-jocher I can't really view any code until Thursday so you guys take over and do whatever seems right. I'll get upto speed when we meet on friday.

**Comment by glenn-jocher** [comment]
@AyushExel ok got it!

@AyushExel @Laughing-q I've added tests for greyscale and RGBA image inference using filename, cv2 and PIL in https://github.com/ultralytics/ultralytics/pull/1069/commits/7e58604b13baecd7be59886efe824b89d1e4975c

```python
SOURCE = ROOT / 'assets/bus.jpg'
SOURCE_GREYSCALE = Path(f'{SOURCE.parent / SOURCE.stem}_greyscale.jpg')
SOURCE_RGBA = Path(f'{SOURCE.parent / SOURCE.stem}_4ch.png')

def test_predict_grey_and_4ch():
    model = YOLO(MODEL)
    for f in SOURCE_RGBA, SOURCE_GREYSCALE:
        for source in Image.open(f), cv2.imread(str(f)), f:
            model(source, save=True, verbose=True)
```

**Pull request merged**
