### PR TITLE
disable tqdm with YOLO_DISABLE_TQDM=True

### PR DESCRIPTION
**Pull request by Rusteam**
Discussed this here #4609 

### Summary
🔇🚀🛠️

Added a global option to disable tqdm progress bars in `ultralytics` modules. This can improve performance and reduce output verbosity when using the `YOLO_DISABLE_TQDM` environment variable.

> _Oh we are the coders of the YOLO crew_
> _And we like to make our code run fast and true_
> _So we set the `DISABLE_TQDM` to our liking_
> _And we heave away the progress bars with a hoo and a hikin'_

### Walkthrough
*  Add global option to disable tqdm progress bars ([link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL30-R30), [link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L32-R32), [link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-067b5aadc258357e37c686a1a9bd895fa0532dbaf436334af483acd57a6b07faR38))
  - Import `DISABLE_TQDM` variable from `ultralytics.utils` in `trainer.py` and `validator.py` ([link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL30-R30), [link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L32-R32))
  - Define `DISABLE_TQDM` variable in `ultralytics.utils` as the boolean value of the environment variable `YOLO_DISABLE_TQDM` ([link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-067b5aadc258357e37c686a1a9bd895fa0532dbaf436334af483acd57a6b07faR38))
  - Pass `disable=DISABLE_TQDM` argument to `tqdm` function calls in `_do_train` and `__call__` methods of `BaseTrainer` and `BaseValidator` classes ([link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-49b2ec280b0d3c7e2f0040660ce399d51e26311a122e7a8052ef0d57fc40aadeL329-R329), [link](https://github.com/ultralytics/ultralytics/pull/4668/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L162-R162))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduction of an environment variable to globally disable tqdm progress bars.

### 📊 Key Changes
- A new environment variable `DISABLE_TQDM` is added to allow the toggling of tqdm progress bars.
- The `trainer.py` and `validator.py` files are updated to make use of the `DISABLE_TQDM` variable.

### 🎯 Purpose & Impact
- **Purpose**: This change allows users with the `YOLO_DISABLE_TQDM` environment variable set to `true` to disable tqdm progress bars if they find them unnecessary or if they are running scripts in environments where progress bars can clutter the output (e.g., logging systems, CI environments).
- **Potential Impact**: Users who prefer a cleaner console or need to save log storage space can easily turn off progress bars. This will not affect the code's functionality or performance, only the user interface in the terminal. 🚀

### CODE REVIEW

**Comment by Kayzwer** [comment]
@Rusteam sign the CLA by comment `I have read the CLA Document and I sign the CLA`

**Comment by Rusteam** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
recheck

**Comment by glenn-jocher** [comment]
@Rusteam PR merged! Thank you for your contributions. I think I'm going to inherit TQDM disable from the global verbose argument, but I like this initial step.

**Comment by glenn-jocher** [comment]
@Rusteam oh just found this out, super cool.

Yes, you can hide the TQDM progress bar by setting the `bar_format` parameter to `None` or an empty string `''`. This will effectively disable the bar from displaying while still running the loop.

Here's an example:

```python
from tqdm import tqdm

# To completely hide the bar, set bar_format to None or ''
for i in tqdm(range(10), bar_format=None):
    # Your code here
    pass
```

Alternatively, you can conditionally set the `bar_format` based on your requirement:

```python
show_bar = False  # Set this based on your condition
bar_format = '{l_bar}{bar}| {n_fmt}/{total_fmt} [{elapsed}<{remaining}, {rate_fmt}{postfix}]' if show_bar else None

for i in tqdm(range(10), bar_format=bar_format):
    # Your code here
    pass
```

This way, you can control whether the TQDM progress bar is shown based on some condition. Setting `bar_format` to `None` will completely hide the progress bar while still allowing you to utilize TQDM's other features.

**Comment by Rusteam** [comment]
@glenn-jocher great discovery. It's much cleaner this way

**Comment by glenn-jocher** [comment]
@Rusteam thank you for your positive feedback! We continually aim to ensure that the YOLOv8 repo is user-friendly and easy to navigate. Clean and organized code not only improves the readability but also makes the development and debugging process more efficient. If you have more suggestions or ideas to further improve the repository, please feel free to share!

**Comment by Rusteam** [comment]
Great to hear! I'll try to contribute with code and ideas more frequently

**Comment by glenn-jocher** [comment]
@Rusteam that sounds wonderful! We're thrilled to hear that you're interested in contributing more frequently to the YOLOv8 project. Your ideas and contributions are immensely valuable. Remember, every contribution, no matter how small, can make a big difference. We are looking forward to seeing your future contributions. If you have any questions or if there is anything you need help with, feel free to ask. Thank you for being a part of our open-source community!

**Pull request merged**
