### PR TITLE
Bug: remove reversed function in the segmentation detection

### LINKED ISSUE #743: wrong report of classes on the txt file for the segmentation detection
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Detection

### Bug

When running the segmentation detection for a multi-class segmentation, the class plotted on the image (correct) does not match the class saved in the text file. 

### Environment

_No response_

### Minimal Reproducible Example

yolo task=segment mode=predict model=best.pt data=data.yaml save_txt=True imgsz=1152 save_conf=True line_thickness=1 retina_masks=True conf=0.25 iou=0.45 name=full_data source=./images

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by mehran66**
When running the segmentation detection for a multi-class segmentation, the class plotted on the image (correct) does not match the class saved in the text file. Looking more exactly in the txt file, I noticed that classes are reported in the reverse way that is wrong.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Maintenance PR with no code changes included.

### 📊 Key Changes
- There are no code changes to report in this PR.

### 🎯 Purpose & Impact
- Since there are no changes, there is no direct impact or benefits to the users from this PR.
- It could indicate preparatory work for future changes or a PR that serves administrative or housekeeping purposes.

### CODE REVIEW

**Comment by mehran66** [comment]
"Error: committers of Pull Request number 745 have to sign the CLA". what is this error?

**Comment by AyushExel** [comment]
comment "I have read the CLA Document and I sign the CLA" on this thread

**Comment by glenn-jocher** [comment]
@mehran66 thanks for the PR! This reversed is in place to plot annotations with lowest confidence first, so that on a final annotated image the highest probability results overlay the lowest probability results.

It seems there is a bug though, so I think the safest way forward is to reverse the sort order at the NMS output and remove this reversed in all places, including detection.

**Comment by glenn-jocher** [comment]
With OP original solution applied we can see that the lowest confidence boxes are now overlaying the highest confidence boxes, which is not what we want. 

bus

**Comment by glenn-jocher** [comment]
@mehran66 I've implemented a revised fix in https://github.com/ultralytics/ultralytics/pull/745/commits/74bd4d70f88eced14edb14f3d291bd88d9158b49 that should maintain plotting order and fix the segment order bug. Can you verify this fix works and then we'll merge into main? Thanks!

Also please write in a new comment: I have read the CLA Document and I sign the CLA

**Comment by mehran66** [comment]
@glenn-jocher tested the change and it works all fine.

**Comment by glenn-jocher** [comment]
@mehran66 PR merged! Thank you for spotting this bug :)

**Pull request merged**
