### PR TITLE
Object Counter improvements

### PR DESCRIPTION
**Pull request by hdnh2006**
## 🛠️ PR Summary
This PR significantly enhances the object counter solution developed by Ultralytics.

While utilizing the object counter, I encountered multiple challenges:

1. The region counter disappears in the absence of detected objects.
2. The [counter for polygons](https://github.com/ultralytics/ultralytics/blob/2071776a3672eb835d7c56cfff22114707765ac6/ultralytics/solutions/object_counter.py#L196) inaccurately measured distances as if dealing with a linear scenario to determine object presence within or outside the polygon, using the formula: `if (box[0] - prev_position[0]) * (self.counting_region.centroid.x - prev_position[0]) > 0`.
3. The centroid calculation was overlooked for polygons.
4. The window title was hardcoded, causing issues with tracking multiple objects.
5. The polygon-based object counter logic initiated counting before an object had actually traversed the designated region.

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the Ultralytics Object Counter for improved object tracking and counting.

### 📊 Key Changes
- Introduced a new window name variable for better identification.
- The counting list has been replaced with a dictionary for efficient tracking.
- Support for polygonal counting regions with 3 or more points, in addition to line regions with exactly 2 points.
- Improved handling and validation of region points for counting.
- Optimized tracking and counting logic to handle objects within polygonal regions.
- Maintained region display even when no objects are detected in the frame.
- Minor adjustments to mouse callback and window display functions.

### 🎯 Purpose & Impact
- 📈 Improves usability by providing descriptive window titles and ensuring consistent region display.
- 🚀 Allows users to count objects in customizable polygonal areas, enhancing flexibility for different use cases.
- 🐞 Reduces potential errors by validating the number of region points and by using a dictionary for tracking unique identifiers.
- 💻 Offers a cleaner interface and more robust tracking, resulting in a better user experience.

### TODO
- [X] Implement inteligent logic for line counter (Done)

### 🤓 Demo
Here you will find a before and after demo

**Before**:
before

**After**
after

I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to Ultralytics' object counter for improved versatility in object tracking and UI display.

### 📊 Key Changes
- **Window Title Addition**: A window title, "Ultralytics YOLOv8 Object Counter," is now hardcoded to improve user interface clarity.
- **Data Structure Update**: Counting list converted to a dictionary for more efficient tracking of object counts.
- **Counting Logic Adjustment**: Modified to support counting within polygons (regions with 3 or more points) alongside the original line (2 points) counting method.
- **Counting Method Corrections**: Improved error messages for invalid region points and ensured consistent counting even with no object tracks.
- **Annotation Enhancements**: Annotator now initializes and draws the region regardless of whether there are objects, and region drawing occurs only if the environment permits display updates.

### 🎯 Purpose & Impact
- **Interface Usability**: Users will benefit from a more descriptive window title during object counting sessions.
- **Counting Accuracy**: The shift to a dictionary for counting paves the way for more accurate and adaptable object tracking and counting mechanisms.
- **Flexibility in Application**: The system can now handle more complex regions for counting, like polygons, making it more versatile for different counting scenarios.
- **Error Handling**: Users receive more intuitive error messages regarding region point specifications, reducing confusion in the setup process.
- **Visualization Improvements**: With annotator enhancements, users get a consistent visual feedback experience, regardless of object presence, enhancing debugging and setup processes.

### CODE REVIEW

**Comment by hdnh2006** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@hdnh2006 wow, really nice! @RizwanMunawar take a look at this PR please, results look great.

**Review by RizwanMunawar — APPROVED** [review]
@hdnh2006 Great job on this! It looks like we can now define a region with 3 or more points. Previously, regions were limited to only 4 points, which may not be effective in every scenario!!!

@glenn-jocher I think we can merge the PR 🚀

Thank guys!!!

**Comment by glenn-jocher** [comment]
@hdnh2006 PR merged! Thanks for the super awesome improvements :)

This should be live in `8.1.25` later today!

**Comment by hdnh2006** [comment]
> @hdnh2006 PR merged! Thanks for the super awesome improvements :)
> 
> This should be live in `8.1.25` later today!

Thanks to you and all Ultralytics team for changing Vision AI forever.

**Comment by glenn-jocher** [comment]
We're thrilled to hear your kind words, @hdnh2006! 🚀 It's contributions like yours that help push the boundaries of what's possible. Keep an eye out for version `8.1.25`! Happy coding! 🎉

**Pull request merged**
