### PR TITLE
Add color palette tables to docs

### PR DESCRIPTION
**Pull request by jk4e**
Hi,

Add color palettes 🎨 to docs reference. A valid link was missing for a color palette in docstring, and also cannot find a palette in docs. Think would be best to have access directly on docs and not link to `https://ultralytics.com/` (as mentioned in the old docstring link). So create tables for the available color palettes. May help people to get an overview of build in default colors, color selection, style and design in Ultralytics YOLO package. Also eliminate the need for a color visualizer or use of a color picker.

Here are screenshots of what it looks like in docs:

img-color-palette

img-color-palette2

Thanks! 🚀

**Note**: Alternative may be to add a section at the end of https://www.ultralytics.com/brand for color palette if my solution is not wanted or unacceptable.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated color palette documentation in the Ultralytics plotting utilities.

### 📊 Key Changes
- Enhanced documentation with a detailed table of colors in the Ultralytics and Pose color palettes.
- Included HEX and RGB values for each color.
- Added visual color squares using HTML for better visualization.

### 🎯 Purpose & Impact
- 📘 **Improved Documentation**: Makes it easier for users to understand and use available color palettes in their projects.
- 👀 **Visual Clarity**: The use of icons provides a clear and immediate understanding of each color's appearance.
- 🎨 **Consistency**: Ensures consistent use of official colors in various applications, benefiting brand alignment.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@jk4e wow this is very cool! 

We have a slight problem though, the reference/**/*.md files are created automatically here, so this work may get lost if there are changes in the underlying python files. Maybe we could put the tables or the macros directly in the docstrings, though not sure if that would render properly?

https://github.com/ultralytics/ultralytics/blob/17477066ec2fd61d08652a22897e23d2040ff3e6/docs/build_reference.py#L39-L82

**Comment by jk4e** [comment]
Ah, OK, I see. @glenn-jocher thanks for the feedback! I will try and test your suggestions and get back to you. If that doesn't work, I would suggest creating a separate page.

**Comment by glenn-jocher** [comment]
@jk4e you're welcome! Feel free to reach out if you have more questions after testing.

**Comment by jk4e** [comment]
@glenn-jocher You were right. Thanks for your help and comments! After running `build_reference.py`, my added tables get lost. (overwritten) The solution you described of including the tables directly in the docstring worked and was rendered correctly in docs. Including the tables via macro link did not work.

My new commit should fix this. 🚀 (add tables directly to docstring)

How it looks:

img-color-palette3

**Comment by glenn-jocher** [comment]
@jk4e wow this is amazing, great work!

**Comment by glenn-jocher** [comment]
@jk4e PR merged, awesome addition, thanks for the effort here and the update!

**Comment by Krupskaya** [comment]
Hi @jk4e , great work! I am a tech recruiter at Ultralytics. We noticed your contributions and would like to discuss possible job opportunities. Unfortunately, we didn't find your contact information. Could you please send a message to olga@ultralytics.com? We will appreciate it. Thanks!

**Comment by jk4e** [comment]
Hi @Krupskaya,

Thanks for reaching out! I wasn't aware that GitHub had removed private messages, so I apologize for the delay. (I don't regularly check my GitHub inbox).

I appreciate the offer and your trust in me. I'm just someone who likes the product and the great community and team here, and I'm just contributing because I want to help improve the project. There wasn’t any plan behind it.

I'll send you an email as soon as possible. Thanks again! 🚀

**Pull request merged**
