### PR TITLE
`ultralytics 8.2.56` Streamlit tracking app

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced model selection and configuration in the YOLOv8 Streamlit demo for improved ease of use and functionality.

### 📊 Key Changes
- Updated YOLOv8 example URL in the Rust README.
- Incremented the version number from 8.2.55 to 8.2.56.
- Streamlined model selection menu from a static list to dynamically pulling available models.
- Improved configuration options in the Streamlit demo, including:
  - Enabled model tracking toggle.
  - Changed threshold sliders to set Confidence and IoU thresholds.

### 🎯 Purpose & Impact
- 📖 **Documentation Update**: Corrected the YOLOv8 Rust example URL for better navigation.
- 🚀 **Version Increment**: Signals new changes and improvements.
- 🎛️ **Enhanced UI**: Dynamic model selection makes the Streamlit demo easier to maintain and more adaptable.
- 🔍 **Improved User Control**: Additional configuration options and tracking enablement provide users with more precise control over model behavior, enhancing the application’s functionality.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar should be able to automatically determine available models now from GITHUB_ASSETS_STEMS in https://github.com/ultralytics/ultralytics/pull/14269/commits/f45bf65178d781419de92ba6f176b2ca275e044b

**Comment by glenn-jocher** [comment]
@RizwanMunawar I've renamed NMS threshold to IoU threshold to match the iOS app, and I've moved the float() operation from inside the for loop (which will be slower as it's repeated on every frame) to outside so it's only done once. 

We have to be attentive to the details!

image

**Comment by RizwanMunawar** [comment]
Great catch, @glenn-jocher! Thank you for the quick fixes.

Let's keep this PR open; I'll work on additional features such as validation, benchmarking, and multi-pages.

**Comment by glenn-jocher** [comment]
@RizwanMunawar ok sounds good, I'll keep it open!

**Comment by glenn-jocher** [comment]
@RizwanMunawar I'm going to get this merged just to not leave it hanging so we don't have to keep updating it.

**Comment by RizwanMunawar** [comment]
ok got it @glenn-jocher no worries. I can then open the new PR later :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar ok perfect. Merging now!

**Pull request merged**
