### PR TITLE
`ultralytics 8.0.75` fixes and updates

### LINKED ISSUE #1941: Offline training may report an error
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

_No response_

### Bug

 File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\ultralytics\yolo\utils\checks.py", line 131, in check_latest_pypi_version
    response = requests.get(f'https://pypi.org/pypi/{package_name}/json')
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\WYANING\.conda\envs\tracking\lib\site-packages\requests\adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='pypi.org', port=443): Max retries exceeded with url: /pypi/ultralytics/json (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1131)')))

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

shall we add verify=False here？ or we have other solution？
response = requests.get(f'https://pypi.org/pypi/{package_name}/json',verify=False)

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
### Summary
📝🐛🎨

This pull request improves the documentation, code quality, and performance of the `ultralytics` package and its submodules, especially the `yolo` module. It updates the Chinese README file, refactors some classes and methods, adds a common decorator for matplotlib plots, fixes some bugs and errors, and increments the package version.

> _`ultralytics` grows_
> _refining plots and docs_
> _autumn of code_

### Walkthrough
*  Translate section titles and table headers in `README.zh-CN.md` from English to Chinese ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L98-R98), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L108-R119), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L127-R138), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L146-R157), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L165-R181), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L215-R214), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L224-R223), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-13f564fa6ce92394f8423bbcea359aef7e9ebc4f79763efc0d791d9ce5b6f987L231-R230))
* Update the `__version__` attribute of the `ultralytics` package to '8.0.75' in `ultralytics/__init__.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-b6202fa6738a34b56894dce00b24b8a4e4d7f4b1cbf1b04db6860f6b0f9635ceL3-R3))
* Use f-strings for file path formatting in `ultralytics/datasets/VisDrone.yaml` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-394efce4dee4a06c2bab30eb03ac48a520c1eee8e6a33b66f87e880c1abf0f1bL59-R59))
* Rename `tensor` attribute to `_data` and use `super().__init__` in the `BaseTensor` class in `ultralytics/yolo/engine/results.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L24-R24), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L34-R35), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L46-R44))
* Remove unused and redundant `example` argument from the `plot` method of the `Results` class and the `Annotator` class in `ultralytics/yolo/engine/results.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L167), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L186), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L204-R209))
* Correct and update docstrings of the `plot` and `verbose` methods of the `Results` class in `ultralytics/yolo/engine/results.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L186), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L239-R239), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L245-R245))
* Add `plt_settings` decorator to the `plot` methods of the `ConfusionMatrix`, `PRCurve`, `ROCCurve`, and `OKSCurve` classes in `ultralytics/yolo/engine/results.py` and `ultralytics/yolo/utils/metrics.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L349-R350), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcR237), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcR281), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcR304))
* Deprecate and replace `boxes` and `masks` attributes by `data` property in the `Boxes` and `Masks` classes in `ultralytics/yolo/engine/results.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L356-R368), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L389-R391), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L419-R420), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L435-R436), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-c3050afb0dfa35a0115c36c0acd91e2587f4349023d5f8a47e8c44e6b30121c5L443-R449))
* Import `matplotlib.pyplot` as `plt` and define `plt_settings` function in `ultralytics/yolo/utils/__init__.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137R20), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-4a5fdbc973a408779ed550a87d5b6bd0d01693002dcc225876d7fb8a3c6d3137R168-R200))
* Add `verify` argument to `requests.get` call in `check_latest_pypi_version` function in `ultralytics/yolo/utils/checks.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-d922fcb35a1250f2fd0185742d3da8123d5baffd4ec5ba7d313e2fca7b001305L131-R131))
* Remove unused `matplotlib` module imports from `ultralytics/yolo/utils/metrics.py` and `ultralytics/yolo/utils/plotting.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL14-R14), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L8))
* Add `plt_settings` decorator to `plot_images`, `plot_labels`, and `plot_evolution` functions in `ultralytics/yolo/utils/plotting.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756R211), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L231), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L259), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756R398))
* Remove redundant `matplotlib.rc` and `matplotlib.use` calls from `ultralytics/yolo/utils/plotting.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L21-R20), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L231), [link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L259))
* Reduce image size and number of boxes to plot in `plot_labels` function in `ultralytics/yolo/utils/plotting.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-7e75b3f968b9868ef6f0a86148cf6c16a5224e7fdd45f5c2eb5e9bc0fc744756L247-R245))
* Remove unnecessary `to(dtype)` call from `batch['bboxes']` tensor in `__call__` method of the `SegLoss` class in `ultralytics/yolo/v8/segment/train.py` ([link](https://github.com/ultralytics/ultralytics/pull/1967/files?diff=unified&w=0#diff-69b3b40601c35cc60cecb5a813fe62a36840599d895ebd439501a87a91f85581L82-R82))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Upgrade to YOLO v8.0.75 with readability improvements and documentation update in multiple languages.

### 📊 Key Changes
- Updated software version to `8.0.75`.
- Improved code readability by replacing direct string manipulations with formatted strings.
- Enhanced results plotting by encapsulating settings in the `plt_settings` decorator.
- Fixed security concerns by disabling insecure requests warnings.
- Streamlined `BaseTensor` attribute references and naming.
- Pruned unused or redundant code segments.
- Updated documentations in several sections for better clarity and understanding.
- Fixed string comparisons in `__str__` methods to include protected attributes.
- Code refactoring and optimizations for better performance and structure.

### 🎯 Purpose & Impact
- 🔍 This update focuses on refining the codebase for better maintainability and readability.
- 🚀 Improved plotting functions may result in clearer and more consistent visual outputs for users.
- 🛡️ Security improvements reduce potential risks when checking for package updates.
- 📄 Documentation cleanup across various README files improves user comprehension and interaction with the project.
- 📈 These changes, while mostly internal, contribute to a healthier, more sustainable codebase, leading to a more stable and user-friendly platform for both developers and end-users.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q something's not right with our Results, i.e.:

```bash
from ultralytics import YOLO

model = YOLO()
results = model()
```

When I select the first result its of type Results as it should be
```bash
results[0]
ultralytics.yolo.engine.results.Results object with attributes ...
```

When I select the first .boxes from results it says it's deprecated, and then it shows the .boxes data in triple with `_data`, `boxes` and `data`. Before the data was only shown once, now 3X.


```bash
results[0].boxes
WARNING ⚠️ 'Boxes.boxes' is deprecated. Use 'Boxes.data' instead.
ultralytics.yolo.engine.results.Boxes object with attributes:
_data: tensor([[3.9381e+02, 6.5680e+02, 6.2836e+02, 8.6397e+02, 6.8751e-01, 5.6000e+01],
        [7.0997e+02, 5.8242e+02, 8.1472e+02, 6.8972e+02, 5.2551e-01, 0.0000e+00],
        [8.3078e+02, 6.0748e+02, 1.1370e+03, 7.3874e+02, 4.8483e-01, 5.7000e+01],
        [1.0703e+03, 6.6398e+02, 1.2664e+03, 8.5953e+02, 4.1799e-01, 5.6000e+01],
        [5.5329e+02, 5.8056e+02, 7.2784e+02, 7.4867e+02, 4.1620e-01, 0.0000e+00],
        [8.1260e+02, 6.6969e+02, 8.5986e+02, 7.1923e+02, 3.9858e-01, 4.1000e+01],
        [1.7014e+03, 4.6567e+02, 1.7759e+03, 5.8436e+02, 3.1450e-01, 0.0000e+00],
        [8.1100e+02, 6.5722e+02, 8.6173e+02, 7.1995e+02, 3.1296e-01, 5.8000e+01],
        [5.5275e+02, 5.8141e+02, 7.2755e+02, 8.2654e+02, 3.0507e-01, 0.0000e+00],
        [1.0098e+03, 5.2612e+02, 1.0877e+03, 6.2431e+02, 2.8780e-01, 5.8000e+01],
        [1.1471e+03, 5.5251e+02, 1.2287e+03, 6.9449e+02, 2.5049e-01, 0.0000e+00]])
boxes: tensor([[3.9381e+02, 6.5680e+02, 6.2836e+02, 8.6397e+02, 6.8751e-01, 5.6000e+01],
        [7.0997e+02, 5.8242e+02, 8.1472e+02, 6.8972e+02, 5.2551e-01, 0.0000e+00],
        [8.3078e+02, 6.0748e+02, 1.1370e+03, 7.3874e+02, 4.8483e-01, 5.7000e+01],
        [1.0703e+03, 6.6398e+02, 1.2664e+03, 8.5953e+02, 4.1799e-01, 5.6000e+01],
        [5.5329e+02, 5.8056e+02, 7.2784e+02, 7.4867e+02, 4.1620e-01, 0.0000e+00],
        [8.1260e+02, 6.6969e+02, 8.5986e+02, 7.1923e+02, 3.9858e-01, 4.1000e+01],
        [1.7014e+03, 4.6567e+02, 1.7759e+03, 5.8436e+02, 3.1450e-01, 0.0000e+00],
        [8.1100e+02, 6.5722e+02, 8.6173e+02, 7.1995e+02, 3.1296e-01, 5.8000e+01],
        [5.5275e+02, 5.8141e+02, 7.2755e+02, 8.2654e+02, 3.0507e-01, 0.0000e+00],
        [1.0098e+03, 5.2612e+02, 1.0877e+03, 6.2431e+02, 2.8780e-01, 5.8000e+01],
        [1.1471e+03, 5.5251e+02, 1.2287e+03, 6.9449e+02, 2.5049e-01, 0.0000e+00]])
cls: tensor([56.,  0., 57., 56.,  0., 41.,  0., 58.,  0., 58.,  0.])
conf: tensor([0.6875, 0.5255, 0.4848, 0.4180, 0.4162, 0.3986, 0.3145, 0.3130, 0.3051, 0.2878, 0.2505])
data: tensor([[3.9381e+02, 6.5680e+02, 6.2836e+02, 8.6397e+02, 6.8751e-01, 5.6000e+01],
        [7.0997e+02, 5.8242e+02, 8.1472e+02, 6.8972e+02, 5.2551e-01, 0.0000e+00],
        [8.3078e+02, 6.0748e+02, 1.1370e+03, 7.3874e+02, 4.8483e-01, 5.7000e+01],
        [1.0703e+03, 6.6398e+02, 1.2664e+03, 8.5953e+02, 4.1799e-01, 5.6000e+01],
        [5.5329e+02, 5.8056e+02, 7.2784e+02, 7.4867e+02, 4.1620e-01, 0.0000e+00],
        [8.1260e+02, 6.6969e+02, 8.5986e+02, 7.1923e+02, 3.9858e-01, 4.1000e+01],
        [1.7014e+03, 4.6567e+02, 1.7759e+03, 5.8436e+02, 3.1450e-01, 0.0000e+00],
        [8.1100e+02, 6.5722e+02, 8.6173e+02, 7.1995e+02, 3.1296e-01, 5.8000e+01],
        [5.5275e+02, 5.8141e+02, 7.2755e+02, 8.2654e+02, 3.0507e-01, 0.0000e+00],
        [1.0098e+03, 5.2612e+02, 1.0877e+03, 6.2431e+02, 2.8780e-01, 5.8000e+01],
        [1.1471e+03, 5.5251e+02, 1.2287e+03, 6.9449e+02, 2.5049e-01, 0.0000e+00]])
id: None
is_track: False
orig_shape: tensor([1013, 1800])
shape: torch.Size([11, 6])
xywh: tensor([[ 511.0821,  760.3849,  234.5513,  207.1650],
        [ 762.3490,  636.0707,  104.7510,  107.3077],
        [ 983.9067,  673.1131,  306.2474,  131.2615],
        [1168.3489,  761.7522,  196.1859,  195.5527],
        [ 640.5636,  664.6157,  174.5494,  168.1030],
        [ 836.2305,  694.4597,   47.2548,   49.5424],
        [1738.6372,  525.0115,   74.5161,  118.6883],
        [ 836.3651,  688.5819,   50.7266,   62.7330],
        [ 640.1505,  703.9775,  174.8080,  245.1294],
        [1048.7350,  575.2151,   77.9337,   98.1862],
        [1187.8655,  623.4977,   81.5752,  141.9746]])
xywhn: tensor([[0.2839, 0.7506, 0.1303, 0.2045],
        [0.4235, 0.6279, 0.0582, 0.1059],
        [0.5466, 0.6645, 0.1701, 0.1296],
        [0.6491, 0.7520, 0.1090, 0.1930],
        [0.3559, 0.6561, 0.0970, 0.1659],
        [0.4646, 0.6855, 0.0263, 0.0489],
        [0.9659, 0.5183, 0.0414, 0.1172],
        [0.4646, 0.6797, 0.0282, 0.0619],
        [0.3556, 0.6949, 0.0971, 0.2420],
        [0.5826, 0.5678, 0.0433, 0.0969],
        [0.6599, 0.6155, 0.0453, 0.1402]])
xyxy: tensor([[ 393.8064,  656.8024,  628.3577,  863.9675],
        [ 709.9735,  582.4169,  814.7245,  689.7245],
        [ 830.7830,  607.4824, 1137.0304,  738.7438],
        [1070.2560,  663.9758, 1266.4419,  859.5286],
        [ 553.2889,  580.5642,  727.8383,  748.6672],
        [ 812.6031,  669.6885,  859.8579,  719.2309],
        [1701.3792,  465.6674, 1775.8953,  584.3557],
        [ 811.0018,  657.2154,  861.7284,  719.9484],
        [ 552.7465,  581.4128,  727.5544,  826.5422],
        [1009.7681,  526.1221, 1087.7018,  624.3082],
        [1147.0779,  552.5104, 1228.6531,  694.4850]])
xyxyn: tensor([[0.2188, 0.6484, 0.3491, 0.8529],
        [0.3944, 0.5749, 0.4526, 0.6809],
        [0.4615, 0.5997, 0.6317, 0.7293],
        [0.5946, 0.6555, 0.7036, 0.8485],
        [0.3074, 0.5731, 0.4044, 0.7391],
        [0.4514, 0.6611, 0.4777, 0.7100],
        [0.9452, 0.4597, 0.9866, 0.5769],
        [0.4506, 0.6488, 0.4787, 0.7107],
        [0.3071, 0.5740, 0.4042, 0.8159],
        [0.5610, 0.5194, 0.6043, 0.6163],
        [0.6373, 0.5454, 0.6826, 0.6856]])

```

**Comment by Laughing-q** [comment]
@glenn-jocher oh that's because I made `_data` a protected variable since we probably do not want users to modify it. is there a way we do not include protected variable(with `_`) in our __str__?

**Comment by glenn-jocher** [comment]
@Laughing-q yeah it's strange because this repr is supposed to not show protected attributes. Maybe I just need to check the `__repr__` method. 

Are you sure these 3 are sharing memory though? (we want them to)

**Comment by glenn-jocher** [comment]
@Laughing-q but wait, also don't we want users to continue using `results[0].boxes`? This seems like a natural usage, but now the usage would change to `results[0].data` which isn't super clear.

EDIT: nevermind, I see what's happening. The repr method is printing all the attributes, including the deprecated .boxes of the Boxes object, causing the warning to show. Hmm, this is a little confusing.

```
results[0].boxes
# shows warning that .boxes is deprecated
```

**Comment by glenn-jocher** [comment]
@Laughing-q ok I updated repr to not print protected variables in https://github.com/ultralytics/ultralytics/pull/1967/commits/e91a25ee1eee9c65a34a696185840ca28f3528fc, and then I simplified the Results a bit by removing self._data and just using self.data in its place (and then removing the self.data attribute). 

So now we only have Boxes.data and Boxes.boxes (deprecated).

**Comment by Laughing-q** [comment]
> @Laughing-q but wait, also don't we want users to continue using `results[0].boxes`? This seems like a natural usage, but now the usage would change to `results[0].data` which isn't super clear.
> 
> EDIT: nevermind, I see what's happening. The repr method is printing all the attributes, including the deprecated .boxes of the Boxes object, causing the warning to show. Hmm, this is a little confusing.
> 
> ```python
> results[0].boxes
> # shows warning that .boxes is deprecated
> ```

@glenn-jocher yes surely they're sharing the same memory.
BTW the usage update is not from `result[0].boxes` to `result[0].data`, it's from `result[0].boxes.boxes` to `result[0].boxes.data` when users want to access the original tensor variable.

**Pull request merged**
