### PR TITLE
Update exporter.py

### PR DESCRIPTION
**Pull request by hamedgorji**
https://github.com/ultralytics/ultralytics/issues/1312#issuecomment-1461290850

### Summary
🚀🔢🏁

Added full integer quantization mode for Edge TPU model in `exporter.py`. This mode can enhance the performance of the YOLOv5 model on the Edge TPU device.

> _`edgetpu_compiler`_
> _Adds `-sa` flag for speed_
> _Winter of quantized_

### Walkthrough
* Enable full integer quantization mode for Edge TPU model by adding `-sa` flag to `edgetpu_compiler` command ([link](https://github.com/ultralytics/ultralytics/pull/1351/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdL640-R640))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated Edge TPU export command for improved functionality.

### 📊 Key Changes
- Modified the command for Edge TPU compilation by adding the `-a` flag to `edgetpu_compiler`.

### 🎯 Purpose & Impact
- **Enhanced Export**: The `-a` flag enables advanced optimizations, potentially improving model performance on Edge TPU devices.
- **User Benefit**: Users may experience more efficient model deployment on Edge TPU hardware, resulting in faster inference times and better overall performance. 🏎️✨

### CODE REVIEW

**Comment by glenn-jocher** [comment]
I don't see `a` in the list of supported arguments:

Screenshot 2023-03-09 at 18 08 54

**Comment by glenn-jocher** [comment]
@hamedgorji I've left a question for the Edge TPU team about whether this is a recommended change in https://github.com/google-coral/edgetpu/issues/317#issuecomment-1462558714

**Comment by pderrenger** [comment]
@hamedgorji you're welcome! Thanks for your patience. If the Edge TPU team confirms this change, it could be a valuable addition to the YOLOv5 model for Edge TPU devices. Keep up the good work!

**Review by ambitious-octopus — COMMENTED** [review]
Closing because the `-a `flag is still experimental and our models perform better without compiling using this flag.

**Pull request closed without merging**
