### PR TITLE
Add turkish language support

### PR DESCRIPTION
**Pull request by sezer-muhammed**
## Notes

- I added All translations except Yolov5 folder docs.
- I translated using GPT assistance. I read all the translations and made the necessary edits and localizations. I added brief notes and explanations for some terms that are missing in Turkish.
- I added Turkish as the first language support as detailed and extensive as English for Yolov8.

## Description
This PR introduces Turkish language translations for the Ultralytics documentation. With this addition, Turkish-speaking users will be able to understand and utilize the Ultralytics tools and resources more effectively.

## Motivation and Context
- **Accessibility**: By providing translations in Turkish, we're making the resources available to a broader community of developers and users who prefer to work in their native language.
- **Community Engagement**: Translations help in building a more inclusive and diverse community around Ultralytics products, encouraging more contributions and feedback from different parts of the world.
- **User Convenience**: Turkish-speaking users will find it easier to learn and implement Ultralytics solutions with documentation in their native language, potentially increasing the adoption and user base.

## Checklist:
- ✅ I have read the [CONTRIBUTING](https://github.com/ultralytics/ultralytics/blob/master/CONTRIBUTING.md) guide.
- ✅ I have performed a self-review of my own code.
- ✅ I have commented my code, particularly in hard-to-understand areas.
- ✅ I have made corresponding changes to the documentation.
- ✅ My changes generate no new warnings.
- ✅ I have added tests that prove my fix is effective or that my feature works.
- ✅ Added mkdocs_tr.yml

I have read the CLA Document and I sign the CLA

copilot:all

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This Pull Request (PR) appears to be a placeholder or possibly opened in error, as there are no actual code changes included.

### 📊 Key Changes
- None (There are no code changes in the PR)

### 🎯 Purpose & Impact
- Since there are no changes, there's no direct impact or benefit to the users or the codebase at this time.
- This PR might be an initial step or a mistake, and may need to be followed up with actual content changes or be closed.

### CODE REVIEW

**Comment by sezer-muhammed** [comment]
I have read the CLA Document and I sign the CLA

**Comment by sezer-muhammed** [comment]
I have read the CLA Document and I sign the CLA

Recheck

**Comment by sezer-muhammed** [comment]
recheck

**Comment by sezer-muhammed** [comment]
@glenn-jocher it gives error due to code spell:

```
codespell................................................................Failed
- hook id: codespell
- exit code: 65

docs/tr/guides/workouts-monitoring.md:9: Bu ==> By, Be, But, Bug, Bun, Bud, Buy, Bum
...
```
Is it a problem? if yes how can I solve it?

**Comment by glenn-jocher** [comment]
@sezer-muhammed hello! The `codespell` error is indicating a potential typo in the specified file. The word "Bu" on line 9 of `docs/tr/guides/workouts-monitoring.md` might be incorrect. 

To solve this issue, please review the flagged word in the context it is used to determine if it is indeed a typo or a correct word in Turkish. If it is a correct word, you can add it to a custom dictionary list for `codespell` to ignore or use inline ignore flags. If it is a typo, correct it in the document. 

After making the necessary changes, you can push the update to rerun the checks. Thanks for contributing! 💪

**Comment by sezer-muhammed** [comment]
@glenn-jocher Hi again!

I think translation for turkish is ready now.

**Comment by sezer-muhammed** [comment]
@glenn-jocher Hi, I tested and made final touches. It seems ready to publish. Could you also have a look?

image

**Comment by glenn-jocher** [comment]
Hello @sezer-muhammed! Great work on getting to this stage. I'll review the updates shortly. Your contributions help make YOLOv8 even more accessible to our community! 🌟

**Comment by sezer-muhammed** [comment]
> Hello @sezer-muhammed! Great work on getting to this stage. I'll review the updates shortly. Your contributions help make YOLOv8 even more accessible to our community! 🌟

Hi, Could you check the updates?

**Comment by glenn-jocher** [comment]
Hello @sezer-muhammed! I'll take a look at the updates as soon as possible. Thank you for your patience and for contributing to the YOLOv8 project! 🚀

**Pull request closed without merging**
