### PR TITLE
Cleanup Focus module code and docstring

### PR DESCRIPTION
**Pull request by Burhan-Q**
Came across a recent [paper](https://www.mdpi.com/2504-446X/8/9/453) referring to `space-to-depth` convolutional module. Checked and found `Focus` module performs the same operation, so updated the docstring for a bit more information and also tried to tidy up the code. I didn't see that `Focus` was used anywhere, so it's not hyper critical, but figured since I was looking at it, was quick to make some minor QoL changes.

- updates `Focus` module doc string
- attempt to tidy up code
- removed comments (no `Contract` module found in repo)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the `Focus` class to simplify its implementation and improve clarity.

### 📊 Key Changes
- Rewritten docstring with a clearer explanation of the Focus functionality.
- Simplified the code of the `forward` method using list comprehensions.
- Removed unused code and comments.

### 🎯 Purpose & Impact
- **Improved Readability**: Clearer comments and docstrings make it easier for developers to understand the purpose and functionality of the `Focus` class. 📝
- **Code Simplification**: The refactoring leads to more maintainable and cleaner code, reducing the complexity of the `forward` method. 🧹
- **No Functional Change**: The behavior of the class remains the same, ensuring that existing models and functionality work without modification. 🔄

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q yes I created this for the first versions of YOLOv5 in 2020 to speedup the slowest initial convolutions that had to traverse the largest width and height dimensions. I called it Focus since I was channeling the spatial dims into the color dims, but since then I've seen it also as "pixel shuffle" or "space to depth" etc, but I've also discontinued it in the models after discovering I could merge it with the next convolution in an interesting stride 2 6x6 convolution.

But if it's not used anywhere here may as well delete. 

There's some plugins to find "dark" code like this, but of course we also have codecov results here in https://app.codecov.io/gh/ultralytics/ultralytics

Codecov says there is coverage here though:
Screenshot 2024-09-04 at 10 36 53

**Comment by glenn-jocher** [comment]
https://github.com/ultralytics/yolov5/blob/f44db0100518c65023095a47e71518c12aa1db90/models/common.py#L343-L358

**Comment by Laughing-q** [comment]
@Burhan-Q @glenn-jocher How about keep it as it is? no need to remove, kinda feel like it's a legacy from yolov5 haha

**Comment by glenn-jocher** [comment]
Yes I agree, let's leave this as is.

**Comment by glenn-jocher** [comment]
@Burhan-Q thanks for the effort here but let's leave alone as we'd have to mirror changes in the YOLOv5 repo and it's probably best to leave it as legacy as @Laughing-q mentioned.

**Pull request closed without merging**
