### PR TITLE
Update CLI usage

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher I have tried to solve the CLI arguments issue.

- If a user inputs incorrect arguments like `yolo etect est pretrain mode=train data=coco8.yaml epochs=2 imgsz=640 model=yolov8n.pt abc`, the code currently throws an error. Instead, we can show a warning and set the `detect` task as the default automatically.
- If the user passes additional arguments, It will help the code to stop execution. Instead the new changes will show the warnings :)

**Best Example**
```CLI
[
/opt/conda/bin/yolo,
task=d,
etect,
mode=train,
model=yolov5m.pt,
data=/kaggle/working/football-players-detection-1/data.yaml,
epochs=100,
imgsz=640
]
```

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved error handling and default task assignment in configuration.

### 📊 Key Changes
- Changed a `SyntaxError` to a warning message when invalid arguments are detected.
- Updated the handling of invalid tasks by logging a warning and defaulting to "detect".

### 🎯 Purpose & Impact
- 🛠️ Provides users with clearer warnings instead of abrupt errors, enhancing user experience.
- 🔄 Automatically defaults to a viable task, reducing configuration issues for users.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response, and an Ultralytics engineer will assist you soon. Meanwhile, please review the following checklist to ensure a smooth integration:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@RizwanMunawar so these are tough ones but I'd say we do need to keep throwing errors when we don't recognize an argument as we need to balance CLI success with making sure we are going with the correct user commands. 

I think the export approach where we look for close matches works well, and then fall back to an error, but we don't want to replace all faulty tasks with 'detect' because then this may result in silent errors where the code runs but does not do what the user intended.

**Comment by glenn-jocher** [comment]
We do need to fix one other CLI issue which is spaces between brackets, i.e. `yolo train device=[0, 1]` as these spaces are being interpreted as a second argument.

**Comment by glenn-jocher** [comment]
Maybe also with classes, i.e. `yolo predict classes=[5, 10, 16]`

**Comment by glenn-jocher** [comment]
I think in general we need to ensure every open bracket/parenthesis is matched with a closing one somehow in the same value

**Pull request closed without merging**
