### PR TITLE
New `is_raspberrypi` function

### PR DESCRIPTION
**Pull request by glenn-jocher**
@lakshanthad this should help us better define environments for RPi ops, as current checks are not very clear to the user.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced environment detection in Ultralytics utils, introducing Raspberry Pi detection.

### 📊 Key Changes
- Improved Docker detection: Simplified code for checking if the script is running inside a Docker container using exception handling.
- Added Raspberry Pi detection: New function to determine if the Python environment is running on a Raspberry Pi by checking the device model information.

### 🎯 Purpose & Impact
- **Enhanced Reliability:** The use of `contextlib.suppress(Exception)` in Docker detection makes the code more robust, preventing crashes if the file cannot be opened. 👍
- **Broader Support:** By introducing a method to detect Raspberry Pi environments, Ultralytics expands its support to more diverse hardware, making it more accessible for IoT projects and edge computing applications. 🚀
- **User Friendly:** These changes aim to provide a smoother experience for developers working in various environments, ensuring that the software behaves optimally across different platforms. 🌐

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@lakshanthad can you verify that this new function works and implement it in our RPi CI PR? Thanks!

**Comment by lakshanthad** [comment]
@glenn-jocher The kernel documentation suggests `/proc/device-tree` symlink

https://github.com/torvalds/linux/blob/v5.9/Documentation/ABI/testing/sysfs-firmware-ofw#L14-L17

Therefore, I have changed to, `/proc/device-tree/model`. Please check.

This is what RPi 5 outputs for me:
```sh
pi@raspberrypi:~ $ cat /proc/device-tree/model
Raspberry Pi 5 Model B Rev 1.0

**Comment by glenn-jocher** [comment]
@lakshanthad awesome, looks good! I'm working on improving environment definitions in https://github.com/ultralytics/ultralytics/pull/9827 also, so I'll merge this and then that one, and then we should have a new constant available called IS_RASPBERRYPI

**Comment by lakshanthad** [comment]
Sounds super!

**Pull request merged**
