### PR TITLE
Fix bug that requires config to end in .yaml

### LINKED ISSUE #4081: Validation fails if config name does not end in .yaml
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Validation

### Bug

When using `yolo detect train data=/path/to/config.yaml...`, a validation step is automatically performed after training. This validation step [requires the data file to end in `.yaml`](https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/validator.py#L129). The train step does not require this, however, so I initially tried with `config.yml` (yml vs yaml). The training completes, but then I got the error below:

```
# yolo detect train data=/opt/workspace/config.yml model=yolov8n.pt device=0
...
100 epochs completed in 0.029 hours.                                                                                                                                                          
Optimizer stripped from /usr/src/ultralytics/runs/detect/train/weights/last.pt, 6.2MB                                                                                                         
Optimizer stripped from /usr/src/ultralytics/runs/detect/train/weights/best.pt, 6.2MB

Validating /usr/src/ultralytics/runs/detect/train/weights/best.pt...                                                                                                                          
Ultralytics YOLOv8.0.145 🚀 Python-3.10.11 torch-2.0.1 CUDA:0 (NVIDIA GeForce GTX 1650 Ti, 3904MiB)                                                                                           
Model summary (fused): 168 layers, 3006233 parameters, 0 gradients, 8.1 GFLOPs                                                                                                                
Traceback (most recent call last):                                                                                                                                                            
  File "/opt/conda/bin/yolo", line 33, in <module>                                                                                                                                            
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())                                                                                                                    
  File "/usr/src/ultralytics/ultralytics/cfg/__init__.py", line 423, in entrypoint                                                                                                            
    getattr(model, mode)(**overrides)  # default args from model                                                                                                                              
  File "/usr/src/ultralytics/ultralytics/engine/model.py", line 377, in train                                                                                                                 
    self.trainer.train()                                                                                                                                                                      
  File "/usr/src/ultralytics/ultralytics/engine/trainer.py", line 192, in train
    self._do_train(world_size)                                                                 
  File "/usr/src/ultralytics/ultralytics/engine/trainer.py", line 400, in _do_train      
    self.final_eval()                          
  File "/usr/src/ultralytics/ultralytics/engine/trainer.py", line 555, in final_eval
    self.metrics = self.validator(model=f)                                                     
  File "/opt/conda/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)                                                                                                                                                              
  File "/usr/src/ultralytics/ultralytics/engine/validator.py", line 134, in __call__
    raise FileNotFoundError(emojis(f"Dataset '{self.args.data}' for task={self.args.task} not found ❌"))
FileNotFoundError: Dataset '/opt/workspace/config.yml' for task=detect not found ❌
```

This is especially confusing because the error thrown is `FileNotFoundError`, but the file definitely exists, and was used for the training already.

As far as I can tell, the extension being `.yaml` is undocumented and not really a requirement - just a quirk of how the inference is being handled.

### Environment

**OS:** Ubuntu 23.04
**Nvidia-container-tools:** 1.13.5-1
**Nvidia driver:** 535.54.03-0ubuntu
**Kernel:** 6.2.0-26-generic
**Docker:** 24.0.5, build ced0996
**Container:** ultralytics/ultralytics:latest

### Minimal Reproducible Example

With any otherwise valid config/training setup, change the extension from `yaml` to `yml:

```
yolo detect train data=/path/to/config.yml model=yolov8n.pt
```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by ChristopherRogers1991**
Fixes https://github.com/ultralytics/ultralytics/issues/4081

### Summary
📦🛠️🚀

Improved data validation in `validator.py` by using `isfile` function. This allows loading data from different sources and avoids errors.

> _`isfile` checks data_
> _Loading becomes more robust_
> _Autumn leaves no bugs_

### Walkthrough
* Import `isfile` function from `os.path` module to check file paths ([link](https://github.com/ultralytics/ultralytics/pull/4082/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7R24))
* Use `isfile` function instead of file extension to check if `self.args.data` is a YAML file in `Validator.__init__` method ([link](https://github.com/ultralytics/ultralytics/pull/4082/files?diff=unified&w=0#diff-01e0aaa194c770fed7f7a0cc941222f0acfa857d478bfeba933eed1bcb1f65e7L129-R130))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced compatibility with dataset file extensions in validation logic.

### 📊 Key Changes
- Adjusted dataset file extension checking to support both `.yaml` and `.yml`.

### 🎯 Purpose & Impact
- **Purpose**: To broaden the dataset file extension compatibility, allowing users to supply configuration files with both `.yaml` and `.yml` extensions without facing issues.
- **Impact**: Users can now reference dataset configuration files with either `.yaml` or `.yml` extensions without modifying their existing file naming conventions, simplifying the user experience and reducing potential confusion.

### CODE REVIEW

**Comment by ChristopherRogers1991** [comment]
I have read the CLA Document and I sign the CLA

**Comment by ChristopherRogers1991** [comment]
It looks like the tests and benchmarks are failing because they pass in dummy file paths (paths ending in `.yaml`, but that don't actually exist on disk). It feels a little less than ideal that those files appear to not be used, but have to be passed in. That's probably a lot more to untangle though, and perhaps not worth the effort for such a small bug.

This PR could be updated to just allow `.yaml` or `.yml`, which would probably cover most users (I don't expect anyone would use an extension other than those two), and/or update the error message to indicate proper naming. Please let me know your thoughts.

**Comment by ChristopherRogers1991** [comment]
hmm... sorry, I should have searched around in the code to see where else `yaml` appeared. What I find interesting is that `check_yaml(...)` function (last result in your search) does look for both endings. It looks like that might do more than we're interested in here, though (I don't think we want to try to download the file if it doesn't exist).

We could make a different util function though, that takes either a string or a Path, and checks if it ends with `yaml` or `yml`. Something like `is_yaml_path(path: str | Path)`, so it doesn't imply that it is a file (exists on disk), and doesn't imply that it will search/download anything (as the other function does). I could implement that, and start replacing the existing checks, if that sounds reasonable to you.

**Comment by glenn-jocher** [comment]
@ChristopherRogers1991 PR merged into a larger *.yml support PR! Thank you for your contributions.

**Pull request merged**
