### PR TITLE
Add DVC experiments logger with DVCLive

### PR DESCRIPTION
**Pull request by shcheklein**
Adds [DVC](https://dvc.org) experiments logger with [DVCLive](https://dvc.org/doc/dvclive). It gives local experience (+ VS Code extension to see the table of experiments, plots, etc) similar to the existing `runs` directory, but with a way to track in real-time, compare all plots side by side for multiple experiments, capturing weights into DVC (can be pushed to S3, Google Drive, any other storage).

Here is how it looks like on Codespaces with GPU (not GA yet):

## Live plots and metrics

https://github.com/ultralytics/ultralytics/assets/3659196/6b8d2465-d7fa-45f6-af70-b37beeae1fc4

## Compare experiments tab

https://github.com/ultralytics/ultralytics/assets/3659196/13528bac-eccf-4f1e-ae1a-c0425c17f145

## Compare experiment plots

https://github.com/ultralytics/ultralytics/assets/3659196/8c2ffa61-fa88-43ca-936f-6adfd805c9fe

## (Optional) Studio integration

https://github.com/ultralytics/ultralytics/assets/3659196/945d16fe-65bb-477f-ad9b-4ecdd259365b

### Summary
📈🎨🕵️‍♂️

This pull request adds DVCLive integration to the ultralytics/yolo package, which enables users to track and compare their machine learning experiments using `dvc`. It introduces a new `callbacks.dvc` module that defines the DVCLive callbacks and their logic, and modifies the `metrics` module to support logging the precision-recall curves and mAP to DVCLive.

> _If you want to track your YOLO runs_
> _With DVCLive and plots for fun_
> _Use `callbacks.dvc`_
> _And `dvc` with ease_
> _And see how your metrics are done_

### Walkthrough
*  Add DVCLive integration callbacks for logging metrics, plots, images, artifacts, and parameters during training and evaluation ([link](https://github.com/ultralytics/ultralytics/pull/2792/files?diff=unified&w=0#diff-9fc76880dc9f2de05ad711555618b1501ea5a833756ff6884e0839fe2b150f0bR201), [link](https://github.com/ultralytics/ultralytics/pull/2792/files?diff=unified&w=0#diff-9fc76880dc9f2de05ad711555618b1501ea5a833756ff6884e0839fe2b150f0bL208-R209), [link](https://github.com/ultralytics/ultralytics/pull/2792/files?diff=unified&w=0#diff-052c6262efa033fb56c6ac6241d151d7eb373ee01daa36cf70077f332078a216R1-R134))
  * Import `dvc` module from `callbacks` subpackage in `base.py` ([link](https://github.com/ultralytics/ultralytics/pull/2792/files?diff=unified&w=0#diff-9fc76880dc9f2de05ad711555618b1501ea5a833756ff6884e0839fe2b150f0bR201))
  * Add `dvc_cb` dictionary to the list of integration callbacks in `base.py` ([link](https://github.com/ultralytics/ultralytics/pull/2792/files?diff=unified&w=0#diff-9fc76880dc9f2de05ad711555618b1501ea5a833756ff6884e0839fe2b150f0bL208-R209))
  * Define DVCLive callbacks and their logic in `dvc.py` ([link](https://github.com/ultralytics/ultralytics/pull/2792/files?diff=unified&w=0#diff-052c6262efa033fb56c6ac6241d151d7eb373ee01daa36cf70077f332078a216R1-R134))
* Add `on_plot` argument to the `ap_per_class` function call in `metrics.py` ([link](https://github.com/ultralytics/ultralytics/pull/2792/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL710-R716))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of DVCLive for enhanced training metrics and logging.

### 📊 Key Changes
- Added `dvclive` as a dependency in `requirements.txt`.
- Incorporated DVCLive callback functions for various training stages.
- Established a new `callbacks/dvc.py` file that defines DVCLive callback methods.

### 🎯 Purpose & Impact
- Allows logging of training metrics, images, and model artifacts 📈.
- Enhances visualization and tracking of model performance using DVCLive 🎨.
- Facilitates better experiment tracking and model evaluation, which can be beneficial for both researchers and practitioners 🔍.

### CODE REVIEW

**Comment by AyushExel** [comment]
Thanks for the PR. Looks great! can't wait to try it out.
Regarding the optional studio integration, is there any extra step needed to enable that? I think studio integration would probably be the most useful as we collaborate from remote locations.

**Comment by shcheklein** [comment]
hey @AyushExel , thanks!

> Regarding the optional studio integration, is there any extra step needed to enable that?

It requires a token from Studio (account is free for a small team) and set it up with DVC or VS Code extension. Here are the details https://dvc.org/doc/studio/user-guide/projects-and-experiments/live-metrics-and-plots#set-up-an-access-token. Or in VS Code the `DVC Setup` page can guide users. Again, it's optional to use Studio.

> I get this tip to track files after every epoch. I guess we should print this suggestion only after 1st epoch. What do you think?

I think we need to denoise it, yes (and we have a ticket for this). For now, I'll make `log_artifact` run only only when train is done. That should be enough for this setup and resolve the noise issue. Thanks for the good catch!

**Comment by AyushExel** [comment]
Perfect! thanks. Let us know when this is good to go.

**Comment by shcheklein** [comment]
@AyushExel it should be good to go. I've de-noised, and simplified it a bit. Also added the `ULTRALYTICS_DVC_DISABLED` to disable it if someone has a DVC / DVCLive repo already and they don't need this auto-logging.

**Comment by AyushExel** [comment]
Awesome

**Review by AyushExel — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@shcheklein looks good. PR merged!

**Pull request merged**
