### PR TITLE
`ultralytics 8.0.77` Ray[Tune] for hyperparameter optimization

### PR DESCRIPTION
**Pull request by glenn-jocher**
### Summary
📈📊🐛

This pull request adds hyperparameter tuning functionality to the ultralytics package using Ray Tune and Weights & Biases. It also fixes some minor issues in the comments, the Dockerfiles, the setup file, and the argument order of a method. It also updates the package version.

> _Sing, O Muse, of the glorious deeds of the ultralytics team,_
> _Who trained and tuned the swift-footed YOLO model with skill and care,_
> _And exported it to many formats, with TensorFlow as their guide and friend,_
> _And logged their metrics and artifacts to Weights & Biases and Ray Tune, the mighty twins of optimization._

### Walkthrough
*  Simplify the `export` option for installing TensorFlow in different operating systems by relying on TensorFlow's automatic version selection ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-944291df2c9c06359d37cc8833d182d705c9e8c3108e7cfe132d61a06e9133ddL79-R81), [link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-60f61ab7a8d1910d86d9fda2261620314edcae5894d5aaa236b821c7256badd7L42-R43))
* Add the `tensorboard` package to the `pip install` command in the Dockerfiles to enable TensorBoard logging and visualization for the YOLO model ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcL33-R33), [link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-c52a8c890ecaade885331e8cd123fc999392dc5165e25a15d2f5db677bd9cc74L29-R29))
* Add the `tune` method to the `YOLO` class in `ultralytics/yolo/engine/model.py` to allow running hyperparameter tuning using Ray Tune ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-555e5fdee1244b9d95b48487cfd502d068e5bfcd51001d5f5b3f4a33007bda7cR384-R466))
* Import and add the `raytune` and `wb` modules to the `add_integration_callbacks` function in `ultralytics/yolo/utils/callbacks/base.py` to enable reporting and logging the metrics to Ray Tune and Weights & Biases ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-9fc76880dc9f2de05ad711555618b1501ea5a833756ff6884e0839fe2b150f0bL157-R161))
* Add the `raytune.py` and `wb.py` files to the `ultralytics/yolo/utils/callbacks` folder to define the callback functions for Ray Tune and Weights & Biases ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-fc87378d52ab79f3c996bad383d2e49722c2841db7c7414ceb8876aff0f6a2c8R1-R17), [link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-1365dac64b857511656e6f9948f7c04022f4a9c14f7732ee26b4ca29d930f0a2R1-R48))
* Add the `tuner.py` file to the `ultralytics/yolo/utils` folder to define the default hyperparameter search space and the task metric map for the YOLO model ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-b1729b763cbaa3709b267481a09ee9bae7455750784b32e2acacefccfd97934eR1-R43))
* Update the `__version__` variable in `ultralytics/__init__.py` to reflect the new release of the ultralytics package ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-b6202fa6738a34b56894dce00b24b8a4e4d7f4b1cbf1b04db6860f6b0f9635ceL3-R3))
* Change the order of the arguments in the `get_dataloader` method of the `DetectionTrainer` class in `ultralytics/yolo/v8/detect/train.py` to match the order of the arguments in the `get_dataloader` method of the `BaseTrainer` class in `ultralytics/yolo/engine/trainer.py` ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-c55f9a098f49780316e7ec36ccd2ae059a0dbf9129072e2cb9ce20bbbd5de940L24-R24))
* Change the comments in the `__init__` and `_setup_train` methods of the `BaseTrainer` class in `ultralytics/yolo/engine/trainer.py` to reflect the correct terminology and capitalization ([link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L116-R116), [link](https://github.com/ultralytics/ultralytics/pull/2014/files?diff=unified&w=0#diff-1dc4dec7a1716e080109cc732dc44c6e843b30bcdd324e0141e679ebf718c2b1L246-R246))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refined CI workflow and package configurations with new hyperparameter tuning capabilities. 🎛️🧠✨

### 📊 Key Changes
- **CI Workflow Adjustments:** Removed `updates` branch from the pull request trigger in the GitHub Actions CI workflow.
- **Installation Steps Streamlined:** Simplified package installation for macOS and CPU environments by using a unified `export` group.
- **Dockerfile Updates:** Included `tensorboard` in Dockerfile installations for better visualization support.
- **Setup Simplifications:** Cleaned up `setup.py` to remove redundant TensorFlow installation options.
- **New YOLO Model Capabilities:** Added hyperparameter tuning functionality using Ray Tune.
- **Integration Callbacks:** Introduced new callback functions for tuning and logging.

### 🎯 Purpose & Impact
- **Consistency and Maintenance:** The CI update helps maintain a cleaner workflow, making it easier to manage automated testing and integration.
- **Ease of Setup:** Installation simplification ensures consistent environments across different setups and reduces confusion during setup.
- **Tools for Insight:** TensorBoard integration provides users with better tools for training visualization and model understanding.
- **Performance Optimization:** The hyperparameter tuning feature allows users to optimize their models' performance more effectively and systematically.
- **Enhanced Logging:** Improved callbacks ensure comprehensive logging during model training, which is crucial for monitoring and diagnosing training processes.

### CODE REVIEW

**Comment by darouwan** [comment]
recheck

**Comment by glenn-jocher** [comment]
@darouwan as a response to your request for a recheck, I would like to remind you to sign the Ultralytics Contributor License Agreement (CLA) by adding a comment with the following message: 

"I have read the CLA Document and I sign the CLA."

Once you and the other contributor(s) have signed the CLA, we will be able to process your PR for review. Additionally, thank you for your contribution to Ultralytics YOLOv8, we appreciate your help!

**Comment by darouwan** [comment]
I have read the CLA Document and I sign the CLA.

**Comment by darouwan** [comment]
So I only need to sign the CLA here once and not need to sign again for next PR, right?

**Comment by darouwan** [comment]
recheck

**Comment by darouwan** [comment]
recheck

**Comment by glenn-jocher** [comment]
@darouwan based on my previous message to you, once you have signed the Ultralytics Contributor License Agreement (CLA), you will not need to sign it again for future pull requests to Ultralytics YOLOv8. This is a one-time requirement to ensure that all contributions are made under the same terms and conditions. Thank you for taking the time to sign the CLA and contribute to Ultralytics YOLOv8.

**Pull request merged**
