### PR TITLE
`ultralytics 8.3.21` NVIDIA DLA export support

### PR DESCRIPTION
**Pull request by justincdavis**
Add flags to the export mode which allow for the [NVIDIA DLA](https://developer.nvidia.com/deep-learning-accelerator) to be used instead of GPU onboard the NVIDIA Jetson devices. The NVDLA allows for energy efficient inference compared to GPU at the cost of added latency. 

Since GPU and DLA both use TensorRT and CUDA, only changes to exporting to engine format are needed. These changes have been tested and verified working with an Orin AGX 64Gb development kit.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR enhances the support for NVIDIA Jetson devices by integrating the use of NVIDIA Deep Learning Accelerator (DLA) for more efficient model inference.

### 📊 Key Changes
- Updated documentation to guide on using TensorRT and NVIDIA DLA for model conversion and inference on Jetson devices.
- Introduced support for exporting models to TensorRT format with DLA on Jetson devices, allowing the use of `DLA` cores.
- Added a new `device` option in export arguments to specify devices like DLA cores during export.
- Version bump from 8.3.20 to 8.3.21 to reflect these updates.

### 🎯 Purpose & Impact
- **Enhanced Performance**: Utilizing DLA reduces power consumption and improves efficiency for inference on Jetson devices, which is beneficial for embedded systems and real-time applications. ⚡️
- **Broader Device Compatibility**: With this support, users can optimize Ultralytics models on more specialized hardware, providing greater flexibility and efficiency in deployment scenarios. 🌍
- **Ease of Use**: With clear documentation updates, users are now guided more effectively in leveraging these advancements without major code overhauls. 📘

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @justincdavis, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response, and an Ultralytics engineer will also assist soon.

Please review the following checklist to ensure a seamless integration of your work:

- ✅ **Define a Purpose**: Clearly explain the purpose of your change in the PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues).
- ✅ **Synchronize with Source**: Ensure your PR is up-to-date with the `ultralytics/ultralytics` `main` branch. If necessary, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: All Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks should be passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If needed, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: If this is your first Ultralytics PR, please sign our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Try to limit your changes to the **minimum** necessary for your feature addition or fix. 

For further guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀💡

**Comment by justincdavis** [comment]
I have read the CLA Document and I sign the CLA

**Review by ambitious-octopus — COMMENTED** [review]
Hey @justincdavis, thanks for the PR. @lakshanthad, can you test this?

**Comment by justincdavis** [comment]
Hi @lakshanthad 

The issue with the above command is that the DLA can only do computation using float16 or interger8 datatypes.
You can refer to the documentation here: https://docs.nvidia.com/deeplearning/tensorrt/developer-guide/index.html#dla_layers
It lists that fp16 is the highest supported precision level available. 

I think having a check that returns an error when enabling DLA without half or int8 would be sufficient. 

As for the performance issues mentioned in #14999 that is to be expected since the DLA is not designed to increase inference time compared to the onboard GPU on Jetsons. It is meant to be a more power efficient alternative. This [page](https://github.com/NVIDIA/Deep-Learning-Accelerator-SW) describes and showcases the benefits of using the hardware (which is application dependent).

My environment is:
Orin AGX 64gb development kit
Jetpack 6.0 revision 2
PyTorch 2.3.0 from NVIDIA
Torchvision 0.18.0 from NVIDIA

**Comment by lakshanthad** [comment]
Got it @justincdavis. I will make the necessary changes and commit

**Comment by lakshanthad** [comment]
@justincdavis I have updated codes and docs accordingly.

@glenn-jocher Please help to review and merge.

**Comment by Laughing-q** [comment]
@lakshanthad @justincdavis Nice work! 
If I understand this correctly this feature is only for Jetson devices right? perhaps we should get https://github.com/ultralytics/ultralytics/blob/75b3b695be3f7ddb3cfa5987857aa65339095644/ultralytics/utils/__init__.py#L803C1-L803C10 involved.
```python
if IS_JETSON and self.args.dla:
   ...
```
Also is there any performance differences between `dla_core=0` and `dla_core=1`? I'm thinking about the necessity of introducing the `dla_core` argument.

**Comment by justincdavis** [comment]
@Laughing-q There is no performance difference between DLA cores since each core is actually a standalone DLA unit (two separate accelerators). However, since they are distinct accelerators you can run concurrent models across them. I guess is anyone other than me and potentially a few others going to use both DLAs? I would argue for it since all Jetsons with DLAs have 2.

As for the IS_JETSON check I would think it would be beneficial to raise an error if dla=True or dla_core=0/1 are passed on a system which is not a Jetson. From my user perspective that could help reduce usage errors.

**Comment by lakshanthad** [comment]
@Laughing-q I have implemented the necessary checks for DLA. Additionally, regarding DLA cores, this should be beneficial for executing multiple inference jobs simultaneously on distinct DLA cores.

**Comment by Laughing-q** [comment]
@lakshanthad @justincdavis Thanks for the explanation and updates! I'm not very sure if we are going to introduce two args for this though...can you just introduce one argument? keep `dla` or `dla_core` and the logic could be:
- `dla=None`: no dla gets involved
- `dla=0`: use dla and dla_core=0
- `dla=1`: use dla and dla_core=1

**Comment by lakshanthad** [comment]
@Laughing-q good idea! Thanks! I have made the changes accordingly.

**Comment by Mertcikla** [comment]
I tried this with yolov8m on Jetson Orin 64gb running Jetpack 6.0 and tensorrt 8.6

There seem to be a few layers unsupported on DLA cores causing them to fallback to GPU execution, which I believe sort of defeats the purpose. Log details are below.

The model exported successfully at the end but I was unable to load the engine with trtexec for profiling. Got error `Serialization assertion plan->header.magicTag == rt::kPLAN_MAGIC_TAG failed.` which possibly is related to [this](https://github.com/NVIDIA/TensorRT/issues/2915#issuecomment-1809680918).

```
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Gather_output_0' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Constant_5_output_0' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Constant_6_output_0' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Div: DLA cores do not support DIV ElementWise operation.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Div' (ELEMENTWISE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Reshape' (SHUFFLE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Reshape_1' (SHUFFLE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Reshape_2' (SHUFFLE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Concat_3: DLA only supports concatenation on the C dimension.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Concat_3' (CONCATENATION): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Split: DLA only supports slicing 4 dimensional tensors.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Split' (SLICE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Split_19: DLA only supports slicing 4 dimensional tensors.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Split_19' (SLICE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/dfl/Reshape' (SHUFFLE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/dfl/Reshape_1' (SHUFFLE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 305) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] (Unnamed Layer* 306) [Concatenation]: DLA only supports concatenation on the C dimension.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 306) [Concatenation]' (CONCATENATION): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 307) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 308) [Gather]' (GATHER): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 309) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 311) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 315) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 318) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Slice: DLA only supports slicing 4 dimensional tensors.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Slice' (SLICE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 321) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] (Unnamed Layer* 322) [Concatenation]: DLA only supports concatenation on the C dimension.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 322) [Concatenation]' (CONCATENATION): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 323) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 324) [Gather]' (GATHER): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 325) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] (Unnamed Layer* 326) [Concatenation]: DLA only supports concatenation on the C dimension.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 326) [Concatenation]' (CONCATENATION): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 327) [Gather]' (GATHER): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 328) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 330) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 334) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 337) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 339) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 343) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 347) [Constant]' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Slice_1: DLA only supports slicing 4 dimensional tensors.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Slice_1' (SLICE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Constant_9_output_0' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Constant_10_output_0' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Constant_11_output_0' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 357) [Shuffle]' (SHUFFLE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Div_1: DLA cores do not support DIV ElementWise operation.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Div_1' (ELEMENTWISE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Concat_4: DLA only supports concatenation on the C dimension.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Concat_4' (CONCATENATION): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Constant_12_output_0' (CONSTANT): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] Layer '(Unnamed Layer* 361) [Shuffle]' (SHUFFLE): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:52:59] [TRT] [W] /model.22/Concat_5: DLA only supports concatenation on the C dimension.
[10/14/2024-23:52:59] [TRT] [W] Layer '/model.22/Concat_5' (CONCATENATION): Unsupported on DLA. Switching this layer's device type to GPU.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/dfl/Softmax. Switching to GPU fallback.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/dfl/conv/Conv. Switching to GPU fallback.
[10/14/2024-23:53:01] [TRT] [W] Input tensor has less than 4 dimensions for /model.22/Sub. At least one shuffle layer will be inserted which cannot run on DLA.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/Sub. Switching to GPU fallback.
[10/14/2024-23:53:01] [TRT] [W] Input tensor has less than 4 dimensions for /model.22/Add_1. At least one shuffle layer will be inserted which cannot run on DLA.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/Add_1. Switching to GPU fallback.
[10/14/2024-23:53:01] [TRT] [W] Input tensor has less than 4 dimensions for /model.22/Add_2. At least one shuffle layer will be inserted which cannot run on DLA.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/Add_2. Switching to GPU fallback.
[10/14/2024-23:53:01] [TRT] [W] Input tensor has less than 4 dimensions for /model.22/Sub_1. At least one shuffle layer will be inserted which cannot run on DLA.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/Sub_1. Switching to GPU fallback.
[10/14/2024-23:53:01] [TRT] [W] Input tensor has less than 4 dimensions for /model.22/Sigmoid. At least one shuffle layer will be inserted which cannot run on DLA.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/Sigmoid. Switching to GPU fallback.
[10/14/2024-23:53:01] [TRT] [W] Input tensor has less than 4 dimensions for /model.22/Mul_2. At least one shuffle layer will be inserted which cannot run on DLA.
[10/14/2024-23:53:01] [TRT] [W] Dimension: 3 (8400) exceeds maximum allowed size for DLA: 8192
[10/14/2024-23:53:01] [TRT] [W] Validation failed for DLA layer: /model.22/Mul_2. Switching to GPU fallback.

```

**Comment by justincdavis** [comment]
@Mertcikla Unfortunately, the DLA is missing support for some layers used in the modern versions of YOLO. However, TensorRT on the Orin systems is still able to handle the GPU fallback and the energy efficiency of the entire inference is still increased. 

As for loading the model with trtexec, the metadata added to the engine file results in trtexec being unable to read the engine. If you want the model to be runnable with trtexec you should compile the engine from the onnx version.

**Comment by Laughing-q** [comment]
@lakshanthad The `dla` should only be either 0 or 1 right? then we should have an `assert` to check if the value is in `[0, 1]` if it's not None. After that I think it's ready to go. :)

**Comment by glenn-jocher** [comment]
@lakshanthad can we update this with the changes discussed on Monday, treating `dla` as a device with index, i.e. `device="dla:0"` for `"dla:1"`?

**Review by glenn-jocher — CHANGES_REQUESTED** [review]
Please treat `dla` as a device rather than adding new extra arguments.

**Comment by lakshanthad** [comment]
@glenn-jocher got it. will work on it accordingly.

**Comment by lakshanthad** [comment]
@glenn-jocher After discussing with @Laughing-q, the functionality for DLA is implemented as requested. Thank you Jing for your support on this! I have also added a `device` argument in the export docs to reflect this.

**Review by Laughing-q — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@justincdavis @lakshanthad @Laughing-q PR merged! Nice work!!

This covers DLA export, but how can users run DLA inference, does it work without any changes or do we need an additional PR for this?

**Comment by lakshanthad** [comment]
Thanks @glenn-jocher !

This is the basic workflow.

1. Export to TensorRT on Jetson with DLA enabled 
2. Run exported `.engine` file as usual for inference. Then it will use GPU + DLA for inference.

**Review by Jacksonearl2468 — APPROVED** [review]

**Comment by DanaHan** [comment]
YoloV11 can run with DLA, But a lot of layers are not supported by DLA. So in my test, the latency from 20ms to 530ms because of data copy between GPU and DLA.

**Comment by glenn-jocher** [comment]
Thank you for sharing your experience. The DLA is designed for energy efficiency, but as you've noted, some layers may fall back to the GPU, affecting latency.

**Pull request merged**
