### PR TITLE
Update Docs for YOLO-World Training ✅

### PR DESCRIPTION
**Pull request by glenn-jocher**
@RizwanMunawar @Burhan-Q @Laughing-q 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated YOLO world models to enable training capabilities and adjusted rate limits for better performance.

### 📊 Key Changes
- Enabled training for all YOLO world models (`YOLOv8s-world`, `YOLOv8s-worldv2`, `YOLOv8m-world`, etc.), allowing users to refine models on their datasets.
- Increased the checkpoint (`ckpt`) rate limit from 90 seconds to 900 seconds in the session configuration, reducing potential rate limit errors during model training and usage.

### 🎯 Purpose & Impact
- **Enhanced Flexibility**: Users can now train YOLO world models on their data, improving model accuracy and making it more adaptable to specific needs. 🎓
- **Improved Usability**: With the extended checkpoint rate limit, users will experience fewer disruptions due to rate limiting, making for a smoother workflow. 🛠

These updates are aimed at providing a more robust experience for developers and researchers working on object detection projects, enhancing the adaptability and efficiency of their workflows.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q I updated the docs page here with green checkmarks for YOLO-World training, but I got myself confused as to whether training is enabled for YOLO-World (v1?)

**Comment by glenn-jocher** [comment]
@RizwanMunawar @Laughing-q should we add YOLO-World results Table to the LVIS dataset page?
https://docs.ultralytics.com/datasets/detect/lvis

**Comment by Laughing-q** [comment]
@glenn-jocher We also support the yolo-worldv1 training! Thanks for the nice catch BTW! I forgot about updating the ✅ table.
Yeah I think we should add yolo-world results to LVIS dataset page since we did the same thing(added yolov8 results) to COCO dataset page.

**Comment by glenn-jocher** [comment]
@RizwanMunawar could you add the updated YOLO-World training table to the LVIS dataset please? Thanks!

**Pull request merged**
