### PR TITLE
fix onnx example code to get same results

### PR DESCRIPTION
**Pull request by MagicCodess**
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced color handling for YOLOv8 model inference using OpenCV in Python.

### 📊 Key Changes
- Modified the `blobFromImage` function call to include the `swapRB=True` argument.

### 🎯 Purpose & Impact
- 🎨 Ensures accurate color representation by swapping the red and blue channels when processing images.
- 🔍 Improves model inference accuracy since the YOLOv8 model was likely trained on images with the standard RGB format.
- 👁‍🗨 Reduces user confusion by preventing unexpected color-related inference issues, potentially enhancing user satisfaction with Ultralytic's YOLOv8 implementations.

### CODE REVIEW

**Comment by MagicCodess** [comment]
https://github.com/ultralytics/ultralytics/issues/1644

**Comment by glenn-jocher** [comment]
@MagicCodess thank you for your interest in contributing to Ultralytics YOLOv8! We appreciate your effort to improve the software. Before we proceed with reviewing your pull request, we kindly ask you to sign the Ultralytics Contributor License Agreement (CLA) by writing the following statement in a PR comment:

"I have read the CLA Document and I sign the CLA"

Once you've signed the CLA, we will review your pull request and respond as soon as possible. If you have any questions, please feel free to ask. Thanks again!

**Comment by MagicCodess** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@MagicCodess PR merged into updates branch for publishing with 8.0.62 soon. Thank you for your contributions!

**Pull request merged**
