### PR TITLE
modified_predicted.py for object counting 

### PR DESCRIPTION
**Pull request by prince0310**
Object Counting using Yolov8 . 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Upgrade to YOLOv8 detection with live count display.

### 📊 Key Changes
- Introduced import of `cv2` (OpenCV library) for image processing.
- Added a dictionary to store class counts during detection (`found_class`).
- Implemented live display of detection counts on the image with positioning and styling using OpenCV.

### 🎯 Purpose & Impact
- **Purpose:** To enhance visual feedback by showing a live count of detected objects directly on the image, giving the user instant insights into the detection results.
- **Impact:** Users can now see real-time detection information overlaid on the images, making the output more informative and user-friendly, especially for visual presentations or quick result assessments.

### CODE REVIEW

**Comment by prince0310** [comment]
I have read the CLA Document and I sign the CLA

**Comment by prince0310** [comment]
cheak again

**Comment by AyushExel** [comment]
Hey, would you like to implement this feature?

**Comment by prince0310** [comment]
i have created new request please look once

**Comment by pderrenger** [comment]
@prince0310 of course! I'll take a look at your pull request right away. Thank you for your contribution!

**Pull request closed without merging**
