### PR TITLE
Avoid Python 3.9 with_stem

### PR DESCRIPTION
**Pull request by democat3457**
Fixes crash when exporting `tflite` models using a Python version < 3.9, as the `Path.with_stem` method was only introduced in Python 3.9.

copilot:all

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refined model naming and CI configuration in Ultralytics repository.

### 📊 Key Changes
- Removed a specific model (YOLOv5n) from the continuous integration (CI) testing matrix.
- Updated file renaming processes for YAML model loading and TFLite model exporting.

### 🎯 Purpose & Impact
- **CI Streamlining**: 
  - By omitting YOLOv5n in CI tests, the team might be adjusting their test suite for efficiency or relevance.
- **Improved Consistency**:
  - The modifications in file renaming ensure that the file's extension is preserved, preventing potential issues with file recognition and usage by users or other systems.
- **User Experience**:
  - These changes could improve the clarity of model naming for users, making it easier to identify and work with different model files.

### CODE REVIEW

**Comment by democat3457** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@democat3457 ah got it! Thank you for the PR! 

I think we are only testing all export in Python 3.10 so that would explain why we didn't catch this...

**Comment by glenn-jocher** [comment]
3.11 failing due to lack of paddlepaddle support for 3.11. Raised in https://github.com/PaddlePaddle/Paddle/issues/52607 and https://github.com/PaddlePaddle/Paddle/issues/48200. Unrelated to this PR.

**Comment by glenn-jocher** [comment]
@democat3457 PR merged! Thank you for your contributions.

**Pull request merged**
