### PR TITLE
Add SIoU Loss in `ultralytics/utils/metrics.py`

### PR DESCRIPTION
**Pull request by sketcch**
### Summary
🆕📝🔧

Added Shape IoU metric to `bbox_iou` function in `ultralytics/utils/metrics.py`. This metric improves the accuracy of bounding box evaluation by accounting for the shape of the objects.

> _Oh we're the coders of the bounding box_
> _And we work on the `bbox_iou` function_
> _We added a shape metric to the mix_
> _To give the user more options_

### Walkthrough
*  Add a new parameter `SIoU` to the `bbox_iou` function in `metrics.py` to enable Shape IoU calculation for bounding box overlap ([link](https://github.com/ultralytics/ultralytics/pull/4253/files?diff=unified&w=0#diff-fb567871ecb755681f83f6e1edeb903d3a5757316d9caa1a28bd2be993bf4fc8L75-R75), [link](https://github.com/ultralytics/ultralytics/pull/4253/files?diff=unified&w=0#diff-fb567871ecb755681f83f6e1edeb903d3a5757316d9caa1a28bd2be993bf4fc8L87-R91), [link](https://github.com/ultralytics/ultralytics/pull/4253/files?diff=unified&w=0#diff-fb567871ecb755681f83f6e1edeb903d3a5757316d9caa1a28bd2be993bf4fc8L114-R115), [link](https://github.com/ultralytics/ultralytics/pull/4253/files?diff=unified&w=0#diff-fb567871ecb755681f83f6e1edeb903d3a5757316d9caa1a28bd2be993bf4fc8R127-R145))
*  Update the `bbox_iou` function docstring and return statement to reflect the new parameter and its possible values ([link](https://github.com/ultralytics/ultralytics/pull/4253/files?diff=unified&w=0#diff-fb567871ecb755681f83f6e1edeb903d3a5757316d9caa1a28bd2be993bf4fc8L87-R91))
*  Implement the Shape IoU formula as a new branch in the `bbox_iou` function logic based on the distance, shape, and angle costs of the bounding boxes ([link](https://github.com/ultralytics/ultralytics/pull/4253/files?diff=unified&w=0#diff-fb567871ecb755681f83f6e1edeb903d3a5757316d9caa1a28bd2be993bf4fc8R127-R145))
*  Optimize the `bbox_iou` function logic to compute the convex width and height only when needed for the selected IoU variant ([link](https://github.com/ultralytics/ultralytics/pull/4253/files?diff=unified&w=0#diff-fb567871ecb755681f83f6e1edeb903d3a5757316d9caa1a28bd2be993bf4fc8L114-R115))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduced SIoU evaluation for bounding box comparison.

### 📊 Key Changes
- Added a new parameter `SIoU=True` as an option in the `bbox_iou` function.
- Modified the `forward` method in `loss.py` to use SIoU (`SIoU=True`) for IoU loss calculation instead of CIoU.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: Integration of SIoU (Scale Invariant Intersection over Union) aims to provide a more accurate measure for bounding box comparison that takes into account shape and scale changes.
- 💡 **Impact**: The update should enhance the model's ability to evaluate object detection performance, potentially leading to better training outcomes and more precise object detection. This could improve the model's robustness, especially in scenarios with varying object sizes and aspect ratios.

### CODE REVIEW

**Comment by KanaMeisa** [comment]
I have read the CLA Document and I sign the CLA

**Comment by KanaMeisa** [comment]
The SIoU Loss incorporates angle loss. I tried it on my own dataset and found that using SIoU performs better compared to CIoU, resulting in improved precision, recall and mAP.

**Comment by KanaMeisa** [comment]
@glenn-jocher I haven’t trained it on the COCO yet, but I think I can give it a try to validate the performance of the SIoU loss.

**Comment by glenn-jocher** [comment]
That sounds great @KanaMeisa! Testing on the COCO dataset would indeed provide valuable insights into the performance of the SIoU loss. Keep us updated with your progress and results. Your experiences and efforts would be a great addition to the Ultralytics YOLOv8 repo community. Looking forward to your updates, and don't hesitate to reach out if you encounter any challenges during the process.

**Comment by glenn-jocher** [comment]
@KanaMeisa I'm testing currently on COCO, the results seem very similar to baseline, it's hard to identify any improvements. So far I have this:

Screenshot 2023-08-11 at 12 53 11
Screenshot 2023-08-11 at 12 52 57

**Comment by KanaMeisa** [comment]
@glenn-jocher I've trained to 292 epochs so far and have also achieved almost the same results as baseline at epoch 292. I think SIoU is not very useful for large general datasets like COCO.

**Pull request closed without merging**
