### PR TITLE
Skip Docs push if no changes

### PR DESCRIPTION
**Pull request by glenn-jocher**
May resolve https://github.com/ultralytics/ultralytics/actions/runs/10443083890/job/28916090792

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the documentation workflow to handle cases where no changes are detected.

### 📊 Key Changes
- Added a check to verify if there are any staged changes before attempting a commit and push.
- If no changes are found, the script now prints "No changes to commit" instead of attempting a commit.

### 🎯 Purpose & Impact
- **Efficiency**: Prevents unnecessary commits and pushes when there's nothing to update. ⏱️
- **Clarity**: Provides clear feedback by notifying when no changes are available, improving the workflow's transparency. 📣
- **Resource Saving**: Reduces redundant operations, saving computational resources and CI/CD run time. 💡

### CODE REVIEW

**Comment by AdnaneKhan** [comment]
@glenn-jocher this docs workflow is 1 bug fix away from a Critical Poisoned Pipeline execution vulnerability (luckily the repository is set to the wrong context variable so it fails for forks). I would advise permission checks on the workflow since it is privileged if a user runs it from a fork PR.

**Comment by glenn-jocher** [comment]
Thank you for the feedback. We'll review the permissions and implement necessary checks to enhance security in the workflow.

**Comment by AdnaneKhan** [comment]
> Thank you for the feedback. We'll review the permissions and implement necessary checks to enhance security in the workflow.

Would recommend reading through https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/. `pull_request_target` can be dangerous if used incorrectly.

**Comment by glenn-jocher** [comment]
Thank you for the recommendation. We'll review the provided resource to ensure our workflow is secure.

**Pull request merged**
