### PR TITLE
Update `analytics` solution

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher I am working on this PR, will be ready tomorrow :)

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Revamped analytics documentation and code to streamline data processing and graph updates.

### 📊 Key Changes
- Simplified analytics setup by combining various plot types into a single processing function.
- Removed redundant YOLO imports and tracking code from examples.
- Fixed video output resolution to 1920x1080.
- Updated YAML configuration for default analytics type.
- Introduced a new approach to manage class-based color cycles and legend updates.

### 🎯 Purpose & Impact
- **Simplification**: Makes it easier for developers to implement and extend analytics features using a unified class structure.
- **Clarity**: Enhanced documentation for better user comprehension.
- **User Experience**: More intuitive setup with predefined settings for video and graph outputs, benefiting both new and experienced users.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @RizwanMunawar, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_ — Bruce Lee

If you're reporting a bug and haven't provided a minimum reproducible example (MRE), please do so. It helps us understand the issue better. 😊

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). Don’t hesitate to leave a comment if you have any questions. An Ultralytics engineer will assist soon. Thank you for contributing to Ultralytics! 🌟🚀

**Comment by glenn-jocher** [comment]
@RizwanMunawar please resolve Docs CI errors

**Comment by RizwanMunawar** [comment]
@glenn-jocher Yes I am working on this PR. It will take a day or two to be ready :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar good to review now? Note you can set these to drafts to let reviewers know they're still under development like this:
Screenshot 2024-10-12 at 20 51 42

**Comment by RizwanMunawar** [comment]
@glenn-jocher Yes this PR is good to review :) 

Thanks

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@RizwanMunawar great, PR merged!

**Pull request merged**
