### PR TITLE
Fix Annotator PIL Image size (width, height) order

### LINKED ISSUE #14225: Label position when extending beyond image
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Predict

### Bug

When I try to validate the models, the results plot such as val_batch0_labels.jpg looks like this:
val_batch0_labels
the labels on the second column's width is wrong, so they are shown at the first column.

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by SheffeyG**
As described in #14225 , the labels' width ware set to a wrong value when they near the right side of the image, cause they ware compared and set to a wrong image width
```py
if p1[0] > self.im.size[1] - w:  # check if label extend beyond right side of image
    p1 = self.im.size[1] - w, p1[1]
```
the `size[1]` is not the whole image's width, we should use `im.width` instead of `im.size[1]`. 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR corrects references to the width of an image in the plotting utilities.

### 📊 Key Changes
- Adjusted the way the image width is referenced in the box labeling code from `self.im.size[1]` and `self.im.shape[1]` to `self.im.width`.

### 🎯 Purpose & Impact
- **Precision Enhancement**: These changes ensure the code accurately references image width, preventing potential errors or misplacements of labels outside the image bounds.
- **User Experience**: Improves the reliability of visualizations, ensuring labels are correctly positioned within the image frame, which is crucial for clarity in data interpretation.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Fixes an issue with label placement logic in image plotting to ensure labels are rendered correctly.

### 📊 Key Changes
- Corrected the condition checking the image dimensions:
  - Changed from checking image height to checking image width when ensuring labels fit within the image boundaries.
  - Adjusted index access for both `self.im.size` and `self.im.shape` attributes to properly fit labels.

### 🎯 Purpose & Impact
- **Purpose**: Ensure that labels are placed correctly on the right side of the images, preventing them from extending beyond image boundaries.
- **Impact**: Improves the visual accuracy and aesthetics of plotted images, making sure labels are always fully visible and properly aligned, enhancing user experience and reducing confusion.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@SheffeyG CI is failing because numpy arrays have no `width` attribute. Did you mean to apply this only to the PIL images?

**Comment by SheffeyG** [comment]
@glenn-jocher Not sure if the cv2 part has the same issue, is there any way to test these images as numpy array?

**Comment by glenn-jocher** [comment]
Hi @SheffeyG,

Thank you for your question! To test if the issue persists with images as numpy arrays, you can use the following code snippet to simulate the scenario:

```python
import cv2
import numpy as np

# Create a dummy image
image = np.zeros((480, 640, 3), dtype=np.uint8)

# Define a function to draw a label near the right edge
def draw_label(image, text, position):
    font = cv2.FONT_HERSHEY_SIMPLEX
    font_scale = 0.5
    font_thickness = 1
    text_size, _ = cv2.getTextSize(text, font, font_scale, font_thickness)
    text_width, text_height = text_size

    # Adjust position if the text extends beyond the image width
    if position[0] + text_width > image.shape[1]:
        position = (image.shape[1] - text_width, position[1])

    cv2.putText(image, text, position, font, font_scale, (255, 255, 255), font_thickness)

# Draw a label near the right edge
draw_label(image, "Test Label", (600, 50))

# Display the image
cv2.imshow("Image with Label", image)
cv2.waitKey(0)
cv2.destroyAllWindows()
```

This code will help you verify if the label positioning issue occurs with numpy arrays. If you encounter any problems, please ensure you are using the latest versions of the packages. If the issue persists, providing a minimum reproducible example would be very helpful. You can find more information on creating one here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Feel free to reach out if you have any further questions or need additional assistance! 😊

**Comment by SheffeyG** [comment]
@glenn-jocher property `im.size` returns (width, height), 
```
self.im.size[1]
1100
self.im.width
1920
self.im.size
(1920, 1100)
```
so we should use `im.size[0]` instead of `im.size[1]` as image width, and np array's shape is (rows, columns), so use `im.shape[1]` as iamge width is fine I guess.

**Comment by glenn-jocher** [comment]
Hi @SheffeyG,

Thank you for the clarification! You are absolutely right. For PIL images, `im.size[0]` should be used to get the width, and for numpy arrays, `im.shape[1]` is indeed the correct way to reference the image width.

Here's the corrected code snippet:

```python
if p1[0] > self.im.size[0] - w:  # check if label extends beyond right side of image
    p1 = self.im.size[0] - w, p1[1]
```

And for numpy arrays:

```python
if p1[0] > self.im.shape[1] - w:  # check if label extends beyond right side of image
    p1 = self.im.shape[1] - w, p1[1]
```

This should ensure that the labels are correctly positioned within the image bounds for both PIL images and numpy arrays. If you encounter any further issues, please let us know!

**Comment by SheffeyG** [comment]
@glenn-jocher Thanks for your reply, and I use `im.width` in the commit as it's more intuitive.
so will it be fixed in the next release?

**Comment by glenn-jocher** [comment]
Hi @SheffeyG,

Thank you for your prompt response and for the clarification regarding the use of `im.width`. Your approach is indeed intuitive for PIL images. However, to ensure compatibility across different image types (PIL and numpy arrays), we should use `im.size[0]` for PIL images and `im.shape[1]` for numpy arrays.

Here's the updated code snippet for clarity:

```python
if isinstance(self.im, np.ndarray):
    if p1[0] > self.im.shape[1] - w:  # check if label extends beyond right side of image
        p1 = self.im.shape[1] - w, p1[1]
else:
    if p1[0] > self.im.size[0] - w:  # check if label extends beyond right side of image
        p1 = self.im.size[0] - w, p1[1]
```

This ensures that the label positioning works correctly for both image types. We appreciate your contribution and will review and integrate the fix in the upcoming release. Stay tuned for updates! 😊

If you have any further questions or suggestions, feel free to let us know.

**Comment by glenn-jocher** [comment]
@SheffeyG PR merged! Thank you for your contributions.

**Pull request merged**
