### PR TITLE
Add https://youtu.be/96NkhsV-W1U to docs and `heatmaps` fix

### LINKED ISSUE #6911: YOLOv8 heatmap documentation
I referred to the YOLOv8 heatmap documentation and successfully created a heatmap video. 
However, I have a question: why doesn't the color gradually fade away when an object doesn't appear for some time? 
For example, in the video between 1:26 and 1:39, there's a noticeable period where no cars are present in the middle lane, but the heatmap color persists.
video
https://drive.google.com/file/d/1lGdE1D8H8066Y28LobicQHIEgYQhNsUq/view?usp=sharing

result video
https://drive.google.com/file/d/1E0fIR3M8JGYvvqWXknhnPufL40hJ6-Zz/view?usp=sharing

image

```
from ultralytics import YOLO
from ultralytics.solutions import heatmap
import cv2

model = YOLO("yolov8m.pt")   # YOLOv8 custom/pretrained model
cap = cv2.VideoCapture("456.mp4")
assert cap.isOpened(), "Error reading video file"

# Video writer
video_writer = cv2.VideoWriter("heatmap_output.mp4",
                               cv2.VideoWriter_fourcc(*'mp4v'),
                               int(cap.get(5)),
                               (int(cap.get(3)), int(cap.get(4))))

classes_for_heatmap = [0, 2]

# Heatmap init
heatmap_obj = heatmap.Heatmap()
heatmap_obj.set_args(colormap=cv2.COLORMAP_TURBO,
                     imw=cap.get(4),  # should same as im0 width
                     imh=cap.get(3),  # should same as im0 height
                     view_img=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        exit(0)
    results = model.track(im0, persist=True, classes=classes_for_heatmap, device=0, tracker="botsort.yaml")
    im0 = heatmap_obj.generate_heatmap(im0, tracks=results)
    video_writer.write(im0)
```

I wish the heatmap could dynamically adjust color intensity based on time. If there's a period without object tracking, I hope the heatmap color gradually fades or disappears.

thanks.

### PR DESCRIPTION
**Pull request by RizwanMunawar**
### Highlights

- Address user feedback #6911, this PR ensures the heatmap plotting will be not done when there are no detected objects in the frame, resolving the reported issue.
- Previously, the output video stream only stored heatmap frames, skipping empty frames. This issue has been fixed in `solutions/heatmap.py` & `solutions/object_counter.py`

@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Integration of a YouTube tutorial video and minor code improvements for better performance and consistency.

### 📊 Key Changes
- 📹 Added an embedded YouTube video tutorial to the guides section of the documentation.
- 💻 Ensured consistent return values from `generate_heatmap`, `start_counting`, and `estimate_speed` functions by returning `im0`.
- 🛠 Introduced a check to initialize `self.heatmap` only if tracks are present, optimizing the heatmap generation process.

### 🎯 Purpose & Impact
- 📚 Empower users with a visual overview tutorial that supplements the written guides, enhancing learning and user experience.
- 💡 Improve code reliability in heatmap, object counting, and speed estimation features, ensuring they return an image even when no tracks are detected.
- 🚀 Potentially improved memory management and execution flow by avoiding unnecessary initializations, offering a more robust tool for developers and users.

### CODE REVIEW

**Comment by Burhan-Q** [comment]
@RizwanMunawar so the tracks decay when I test this, but using the following, python crashes at the end of the `while`-loop. I'm not sure why and I unfortunately don't have time to diagnose the issue today as I have other tasks I have to work on. If the crash doesn't occur for you, it's likely something to do with Windows and the `cv2.VideoWriter` (I've had issues in the past with it, and suspect this might be the cause).

```py
import cv2
from ultralytics import YOLO
from ultralytics.solutions import heatmap

model = YOLO("yolov8m.pt")   # YOLOv8 custom/pretrained model
cap = cv2.VideoCapture(r"F:\Downloads\traffic_video.mp4")

# Video writer
video_writer = cv2.VideoWriter("heatmap_output.mp4",
                               cv2.VideoWriter_fourcc(*'mp4v'),
                               int(cap.get(cv2.CAP_PROP_FPS)),
                               (int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT)), int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))))

classes_for_heatmap = [2] # cars only

# Heatmap init
heatmap_obj = heatmap.Heatmap()
heatmap_obj.set_args(colormap=cv2.COLORMAP_TURBO,
                     imw=cap.get(cv2.CAP_PROP_FRAME_WIDTH),  # should same as im0 width
                     imh=cap.get(cv2.CAP_PROP_FRAME_HEIGHT),  # should same as im0 height
                     view_img=True)

while cap.isOpened():
    success, im0 = cap.read()
    if not success:
        exit(0)
    results = model.track(im0, persist=True, classes=classes_for_heatmap, device=0, tracker="botsort.yaml")
    im0 = heatmap_obj.generate_heatmap(im0, tracks=results)
    video_writer.write(im0)

# NOTE crash occurs here, but likely due to Windows issue with cv2.VideoWriter configuration

cap.release()
video_writer.release()
cv2.destroyAllWindows()
```

That said, the preview of the video looks good.

**Comment by glenn-jocher** [comment]
@RizwanMunawar great thanks! Can you check the issue @Burhan-Q is running into? Is it related or should I merge while you test?

**Comment by RizwanMunawar** [comment]
@glenn-jocher, I have verified the functionality, and it is functioning correctly. We can merge this :) 

@Burhan Q's thanks for testing things :), but the issue at hand was not about testing imshow. The actual issue was that when no objects were detected in the frame, the heatmap visuals were not being removed. This PR will hopefully resolve this issue :)

**Comment by glenn-jocher** [comment]
@burhan absolutely, happy to help! 🚀 It sounds like you're encountering an issue with heatmap visuals not updating correctly when no objects are detected. This PR addresses that by ensuring heatmap visuals are only generated when there are detected objects. Here's a quick snippet to illustrate the fix:

```python
if len(tracks) > 0:
    # Generate heatmap
    heatmap = generate_heatmap(tracks)
else:
    # Clear previous heatmap visuals
    heatmap = clear_heatmap()
```

This ensures your heatmap visuals stay accurate and up-to-date. Let us know if this solves your issue or if there's anything else we can assist with!

**Pull request merged**
