### PR TITLE
Plot both normalized and absolute confusion matrices

### PR DESCRIPTION
**Pull request by darouwan**
### Summary
📊🆕🔎

Updated `ConfusionMatrix` class to plot both normalized and count matrices in `ultralytics/yolo/utils/metrics.py`. This improves the visualization and analysis of model accuracy and data imbalance.

> _See the truth in the `ConfusionMatrix`_
> _Reveal the flaws of your prediction_
> _Normalize and count the subplots_
> _Don't let the data cause your affliction_

### Walkthrough
*  Add and plot a new attribute `count_matrix` to the `ConfusionMatrix` class in `metrics.py` to show the number of samples in each cell of the confusion matrix ([link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcR228), [link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL317-R320), [link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL325-R328), [link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL335-R362))
*  Modify the `plot` function of the `ConfusionMatrix` class in `metrics.py` to create two subplots instead of one, one for the normalized confusion matrix and one for the count confusion matrix, with different color maps and annotations ([link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL317-R320), [link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL325-R328), [link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL335-R362))
*  Add titles to the subplots of the confusion matrix in `metrics.py` to distinguish them ([link](https://github.com/ultralytics/ultralytics/pull/2444/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL335-R362))

Add the confusion matrix with the actual data count. 
The current confusion matrix file will be like this:

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced confusion matrix visualization with options for both normalized and non-normalized plots.

### 📊 Key Changes
- Introduced a dynamic title for the confusion matrix that reflects whether it's normalized or not.
- Modified file naming for saved confusion matrix images to include the type (normalized or not) in the file name.
- Updated validation scripts for classification and detection to generate and save both normalized and non-normalized confusion matrices.

### 🎯 Purpose & Impact
- 🎨 Improves clarity of the confusion matrix by clearly indicating whether the plot is normalized, aiding users in better understanding their model's performance.
- 📁 Streamlines workflow by automatically naming confusion matrix files based on their type, enhancing file organization and retrieval.
- 🔄 Offers a more comprehensive evaluation of model predictions by providing both perspectives (normalized and non-normalized), which can help in identifying model biases or errors more effectively.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@darouwan thanks for the PR! This is good idea, but we can just run the plot command twice, once with normalize=True and once without. 

We can't increase the font size because then the matrix won't scale to larger datasets like COCO with 80 classes where the squares are much smaller.

**Comment by JeremyMahieu** [comment]
This is a nice feature. I want it.

**Comment by darouwan** [comment]
@JeremyMahieu  Currently the train function will generate 2 confusion matrices, confusion_matrix.png and confusion_matrix_normalized.png by default, where the confusion_matrix_normalized.png is the original one.

**Comment by darouwan** [comment]
@glenn-jocher I noticed the latest code will generate the plot with float to present data count, we can show it in int. 
And currently the clearml will not upload the file confusion_matrix_normalized.png. 

I can create another pr to fix these two issues.

**Comment by JeremyMahieu** [comment]
Will I see both in clearml?

**Comment by darouwan** [comment]
I create a new PR #2472 to fix known issues.

**Comment by glenn-jocher** [comment]
@darouwan thanks for bringing this to our attention. We appreciate your willingness to contribute to YOLOv8. For showing integers in the plot, we can use the `astype` method to convert the matrix to integers before plotting. As for the issue with ClearML uploading the file `confusion_matrix_normalized.png`, it's possible that it may be caused by the file being too large. You can try to reduce the file size or limit its dimensions to see if it can be uploaded successfully. We look forward to your next PR and thanks again for your contributions.

**Pull request merged**
