### PR TITLE
Improve docs for Ultralytics version in benchmarks

### PR DESCRIPTION
**Pull request by lakshanthad**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Enhanced the Raspberry Pi guide by making the benchmark version dynamically adjustable for easier updates. 🚀  

### 📊 Key Changes  
- Replaced hardcoded benchmark version (`v8.3.39`) with a dynamic placeholder (`{{ benchmark_version }}`) in the Raspberry Pi documentation.  
- Added a `benchmark_version` variable to the documentation metadata for streamlined version control.  

### 🎯 Purpose & Impact  
- **Purpose**: Ensures the guide stays consistent and easier to maintain when updating benchmark versions. Simplifies future updates for developers and users.  
- **Impact**: Improves documentation accuracy, reduces maintenance overhead, and promotes clarity for users referencing benchmarks. 🎉

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @lakshanthad, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a smooth review and integration process, please have a look at the checklist below:

- ✅ **Define a Purpose**: Ensure your PR description explains the purpose of the changes (in this case, improving benchmark versioning in the Raspberry Pi guide). Linking to any [relevant issues](https://github.com/ultralytics/ultralytics/issues) will provide additional context and help the team assess the PR more effectively.
- ✅ **Synchronize with Source**: Verify that your branch is synchronized with the `ultralytics/ultralytics` `main` branch. If it's outdated, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Make sure all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please investigate and resolve them.
- ✅ **Update Documentation**: The PR modifies documentation files, so ensure all changes are clearly reflected and consistent throughout the documentation. 
- ✅ **Add Tests**: Since this PR modifies documentation, additional tests may not apply. However, if any unintended impacts on other files or features are detected, tests should be included or updated accordingly.
- ✅ **Sign the CLA**: Please confirm that you’ve signed our [Contributor License Agreement (CLA)](https://docs.ultralytics.com/help/CLA/) by commenting "I have read the CLA Document and I sign the CLA" if this is your first Ultralytics contribution.
- ✅ **Minimize Changes**: Keep the changes in your PR limited to the purpose of the submission. It looks great so far in terms of focused modifications! 🧑‍🔧

For your specific changes, switching to dynamic versioning with `{{ benchmark_version }}` is a fantastic touch! This will undoubtedly improve documentation maintainability and enhance user clarity for benchmarks. 🎉

If any edits or updates are required, please feel free to make the changes and push to your branch. Refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing) for further assistance. 

An Ultralytics engineer will review and provide additional feedback or approval soon. Thank you once again for contributing to the Ultralytics community! 🤗🚀

**Comment by lakshanthad** [comment]
This is just an idea. Let me know your thoughts @glenn-jocher @ambitious-octopus @Laughing-q @RizwanMunawar 

With the change of Ultralytics versions, the benchmark numbers are changing as you can [see here](https://github.com/ultralytics/ultralytics/pull/17910#issuecomment-2510806602)
This is something we can add to the docs moving forward.

Thank you.

**Comment by Laughing-q** [comment]
@lakshanthad From the #17910 PR these improvements you got is because of some updates from our repo or mostly from these packages themselves?

**Comment by RizwanMunawar** [comment]
@lakshanthad Hi, I like the idea, but it's a bit of a manual process as for every release, we will need to adjust the release version, Can we optimize this with JavaScript to auto-update the release version?

Screenshot 2024-12-03 133117

**Comment by glenn-jocher** [comment]
PR merged!

**Comment by lakshanthad** [comment]
> @lakshanthad From the #17910 PR these improvements you got is because of some updates from our repo or mostly from these packages themselves?

@Laughing-q Some updates from our repo. But mostly I think the benchmark numbers are changing when 3rd party packages for different exports are updated. For example, with the latest `openvino` for arm, inference time is 5x than before.

**Comment by Laughing-q** [comment]
> > @lakshanthad From the #17910 PR these improvements you got is because of some updates from our repo or mostly from these packages themselves?
> 
> @Laughing-q Some updates from our repo. But mostly I think the benchmark numbers are changing when 3rd party packages for different exports are updated. For example, with the latest `openvino` for arm, inference time is 6.5x than before.

@lakshanthad Well then people might consider the differences/improvements of performance marked by different ultralytics versions are coming from our repo, than the fact these improvements are mostly from the updates of 3rd party packages.

**Pull request merged**
