### PR TITLE
Fix plot function not working when pil=True.

### PR DESCRIPTION
**Pull request by CNH5**
when pil=True, Annotator.im is new Image object, draw operation act on it but never used.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimized image plotting in YOLO's results visualization.

### 📊 Key Changes
- Simplified the creation of `Annotator` by directly passing a deep-copied image.
- Changed the source image for mask overlays from `img` to `annotator.im`.
- Updated the method's return statement to provide the annotated image in the appropriate format based on the `pil` flag.

### 🎯 Purpose & Impact
- 🎨 Improves readability and maintainability of the visualization code by reducing redundancy.
- 🖼️ Ensures consistency in image transformation for mask overlays, using the image from the `Annotator` instance.
- 👨‍💻👩‍💻 Provides developers and users with a more flexible image output that is automatically adjusted based on the chosen output type.
- 🚀 These changes can lead to a smoother user experience when visualizing results with YOLO, as they streamline how images are processed and returned.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@CNH5 thanks for the PR! I've resolved the CI error. Please write the following line in a new message for the CLA bot:

I have read the CLA Document and I sign the CLA

**Comment by CNH5** [comment]
I have read the CLA Document and I sign the CLA
&nbsp;


@风雨同行@
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2023年3月9日(星期四) 凌晨2:56
收件人: ***@***.***&gt;; 
抄送: "@风雨同行@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] Fix plot function not working when pil=True. (PR #1316)





 
Assigned #1316 to @CNH5.

**Comment by CNH5** [comment]
Please write the following line in a new message for the CLA bot
&nbsp;


@风雨同行@
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Glenn ***@***.***&gt;; 
发送时间: 2023年3月9日(星期四) 凌晨2:56
收件人: ***@***.***&gt;; 
抄送: "@风雨同行@***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [ultralytics/ultralytics] Fix plot function not working when pil=True. (PR #1316)






@CNH5谢谢你的公关！我已经解决了CI错误。请在CLA bot的新消息中写入以下行:

我已阅读CLA文件并签署CLA

—
直接回复此邮件，在GitHub上查看或取消订阅.
***@***.***与&gt;.

**Comment by CNH5** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@CNH5 merged into updates branch for deployment to main and 8.0.52 today. Thank you for your contributions!

**Pull request merged**
