### PR TITLE
`ultralytics 8.3.36` unpin OpenVINO ARM install version

### PR DESCRIPTION
**Pull request by adrianboguszewski**
The issue `NEReductionOperationKernel.cpp:1702: Not supported` mentioned in #10280 has been fixed in OV 2024.3

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Update to improve OpenVINO export compatibility and dependency management.

### 📊 Key Changes
- Updated version of the Ultralytics package from 8.3.35 to 8.3.36.
- Modified OpenVINO export requirements, ensuring compatibility with OpenVINO version 2024.5.0 or later.
- Adjusted NNCF (neural network compression framework) requirements to version 2.14.0 or later.

### 🎯 Purpose & Impact
- **Enhanced Compatibility**: This change ensures that the software is compatible with the latest versions of OpenVINO, eliminating potential issues, especially on macOS systems. 🖥️
- **Improved Performance**: By using updated versions of dependencies, users might experience better efficiency and capability in model exports. 🚀
- **Streamlined Use**: Makes it easier for developers to manage dependencies effectively, reducing setup headaches and improving overall usability. 👍

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @adrianboguszewski, thank you for submitting a PR to the `ultralytics/ultralytics` repository! 🚀 This is an automated response, and an Ultralytics engineer will assist you soon.

To ensure a seamless integration of your improvements, please review the following checklist:

- ✅ **Define a Purpose**: Clearly outline the purpose of your fix or feature in the PR description. Link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Make sure your commit messages are clear and follow the project's conventions.
- ✅ **Synchronize with Source**: Confirm your branch is up-to-date with `main`. Use the 'Update branch' button or execute `git pull` and `git merge main` locally if needed.
- ✅ **Ensure CI Checks Pass**: Make sure all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. Address any failures accordingly.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include tests for your changes and ensure all existing tests are passing.
- ✅ **Sign the CLA**: Ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) by stating "I have read the CLA Document and I sign the CLA" if this is your first PR.
- ✅ **Minimize Changes**: Keep your changes minimal and focused. _"It is not daily increase but daily decrease, hack away the unessential."_ — Bruce Lee

If you haven't already, please provide a Minimum Reproducible Example (MRE) if your PR addresses a bug. For further guidance, see our [Contributing Guide](https://docs.ultralytics.com/help/contributing).

Thank you for your contribution and helping improve Ultralytics! 🎉

**Comment by adrianboguszewski** [comment]
@lakshanthad @glenn-jocher @ambitious-octopus 

@alvoron @DimaPastushenkov

**Review by ambitious-octopus — COMMENTED** [review]
@adrianboguszewski Have you tested?

**Comment by adrianboguszewski** [comment]
No. I kindly ask any of you (who has an ARM machine) to run benchmarks from #10280. 

Or @alvoron you can test?

**Comment by lakshanthad** [comment]
@adrianboguszewski Currently our RPi CI is on a scheduled run (run once daily). I have now enabled it for this PR and the Tests/ Benchmarks from this PR will run on RPi CI.

**Comment by alvoron** [comment]
@lakshanthad this issue is also known and already fixed: https://github.com/openvinotoolkit/openvino/pull/26500
However, this fix will be included into the next release only.
@adrianboguszewski could you please try to replace `openvino` with `openvino-nightly` in `explorer.py`?

**Comment by alvoron** [comment]
@adrianboguszewski I'd suggest to try just to make sure that the CI is passed.
If it's not we need to fix it before 2024.5 CF.
If it is - OK, just put this PR on hold until 2024.5 release.

**Comment by adrianboguszewski** [comment]
Ok, let's see

**Comment by lakshanthad** [comment]
@adrianboguszewski @alvoron CI is passing now.
https://github.com/ultralytics/ultralytics/actions/runs/11144141678/job/30970748216?pr=16600

So do we hold this until 2024.5?

**Comment by adrianboguszewski** [comment]
@lakshanthad yes please

**Comment by alvoron** [comment]
@lakshanthad it's going to be released at the end of November.

**Comment by lakshanthad** [comment]
Thank you @alvoron. Looking forward to it!

**Comment by alvoron** [comment]
@lakshanthad OpenVINO 2024.5 has been published.
We can resume the activity.

**Comment by lakshanthad** [comment]
@alvoron This is great news! I have started the CI. Let's see once it finishes.

**Comment by lakshanthad** [comment]
@glenn-jocher This is ready to go! RPi CI passing!

**Pull request merged**
