### PR TITLE
Non-Deterministic Training Despite deterministic=True

### LINKED ISSUE #15960: Non-Deterministic Training Despite deterministic=True and Fixed Seed
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### Ultralytics YOLO Component

Train

### Bug

When launching training with `deterministic=True` and a fixed `seed`, the expected behavior is that the training process should be entirely deterministic. However, when setting `cache="ram"` or `cache="memory"`, the training becomes non-deterministic. This issue appears to stem from the use of `ThreadPool` in the `cache_images` method of the `BaseDataset` class, which can alter the order in which data is processed and loaded, leading to variability in training outcomes.

https://github.com/ultralytics/ultralytics/blob/1a497f174c21993e2464725d96482e2a4a52758b/ultralytics/data/base.py#L182-L196

### Environment

```
Ultralytics YOLOv8.2.86 🚀 Python-3.10.0 torch-2.3.0+cu121 CUDA:0 (NVIDIA GeForce RTX 2060, 5741MiB)
Setup complete ✅ (6 CPUs, 31.3 GB RAM, 451.1/574.7 GB disk)

OS                  Linux-6.9.3-76060903-generic-x86_64-with-glibc2.35
Environment         Linux
Python              3.10.0
Install             git
RAM                 31.29 GB
CPU                 Intel Core(TM) i5-8600K 3.60GHz
CUDA                12.1

numpy               ✅ 1.26.4<2.0.0,>=1.23.0
matplotlib          ✅ 3.9.0>=3.3.0
opencv-python       ✅ 4.9.0.80>=4.6.0
pillow              ✅ 10.3.0>=7.1.2
pyyaml              ✅ 6.0.1>=5.3.1
requests            ✅ 2.32.2>=2.23.0
scipy               ✅ 1.13.0>=1.4.1
torch               ✅ 2.3.0>=1.8.0
torchvision         ✅ 0.18.0>=0.9.0
tqdm                ✅ 4.66.4>=4.64.0
psutil              ✅ 5.9.8
py-cpuinfo          ✅ 9.0.0
pandas              ✅ 2.2.2>=1.1.4
seaborn             ✅ 0.13.2>=0.11.0
ultralytics-thop    ✅ 2.0.0>=2.0.0
```

### Minimal Reproducible Example

# Test 1
```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.train(device=0, data="coco128.yaml", seed=42, epochs=50, batch=2, deterministic=True, cache="ram")
```
## Output

```
Model summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-9
                   all        128        929      0.743       0.71      0.767      0.579
                person         61        254      0.938      0.626      0.798      0.575
               bicycle          3          6      0.595      0.333      0.396      0.355
                   car         12         46      0.846      0.238      0.376      0.227
            motorcycle          4          5      0.797          1      0.962      0.834
              airplane          5          6      0.959          1      0.995      0.919
                   bus          5          7      0.833      0.714      0.829      0.707
                 train          3          3      0.818          1      0.995      0.732
                 truck          5         12      0.872        0.5      0.569      0.397
                  boat          2          6       0.53       0.57      0.562      0.313
         traffic light          4         14      0.794      0.214      0.319      0.197
             stop sign          2          2      0.764          1      0.995      0.821
                 bench          5          9      0.876      0.889      0.902      0.644
                  bird          2         16      0.886      0.976      0.988      0.686
                   cat          4          4      0.652          1      0.995      0.848
                   dog          9          9      0.821      0.889      0.951       0.74
                 horse          1          2       0.82          1      0.995      0.747
              elephant          4         17      0.822      0.941      0.975      0.791
                  bear          1          1      0.726          1      0.995      0.995
                 zebra          2          4      0.892          1      0.995      0.973
               giraffe          4          9      0.836          1      0.973      0.757
              backpack          4          6      0.602      0.333      0.423      0.294
              umbrella          4         18      0.674      0.833      0.842      0.559
               handbag          9         19      0.826      0.263      0.416       0.27
                   tie          6          7      0.804      0.857      0.858       0.66
              suitcase          2          4      0.317          1      0.745      0.441
               frisbee          5          5      0.716        0.8       0.68      0.548
                  skis          1          1      0.683          1      0.995      0.597
             snowboard          2          7      0.201          1      0.718      0.424
           sports ball          6          6          1      0.276        0.6      0.373
                  kite          2         10      0.743        0.6      0.678      0.286
          baseball bat          4          4      0.654        0.5      0.512      0.291
        baseball glove          4          7      0.857      0.429      0.432      0.319
            skateboard          3          5      0.793        0.6      0.681       0.46
         tennis racket          5          7          1      0.425      0.648      0.359
                bottle          6         18      0.414      0.354      0.484      0.299
            wine glass          5         16      0.705          1      0.894      0.504
                   cup         10         36      0.776      0.417      0.602      0.405
                  fork          6          6      0.666      0.167      0.325      0.263
                 knife          7         16      0.384      0.562      0.539      0.374
                 spoon          5         22      0.908      0.448      0.553      0.349
                  bowl          9         28      0.763       0.75      0.755      0.625
                banana          1          1          1          0      0.995      0.796
              sandwich          2          2      0.598          1      0.995      0.995
                orange          1          4      0.788          1      0.895      0.537
              broccoli          4         11       0.61      0.273      0.409      0.286
                carrot          3         24      0.824      0.779      0.793       0.54
               hot dog          1          2       0.52          1      0.995      0.995
                 pizza          5          5      0.801          1      0.995      0.826
                 donut          2         14      0.535          1      0.908      0.779
                  cake          4          4       0.83          1      0.995      0.897
                 chair          9         35      0.609      0.571      0.666      0.424
                 couch          5          6       0.84      0.667      0.841      0.678
          potted plant          9         14       0.77      0.716      0.842      0.666
                   bed          3          3      0.833          1      0.995      0.895
          dining table         10         13      0.931      0.615      0.702      0.568
                toilet          2          2      0.592          1      0.995      0.896
                    tv          2          2      0.823          1      0.995      0.946
                laptop          2          3      0.878          1      0.995      0.852
                 mouse          2          2          1          0       0.12      0.024
                remote          5          8      0.925       0.75       0.75      0.613
            cell phone          5          8      0.486      0.125      0.251      0.166
             microwave          3          3      0.565          1      0.995      0.798
                  oven          5          5      0.629        0.6        0.5      0.404
                  sink          4          6       0.59      0.723      0.735        0.4
          refrigerator          5          5      0.833      0.999      0.962      0.807
                  book          6         29      0.646      0.448      0.559      0.325
                 clock          8          9      0.932      0.889      0.922      0.811
                  vase          2          2      0.571          1      0.995      0.945
              scissors          1          1          1          0      0.995     0.0995
            teddy bear          6         21      0.487      0.762      0.719      0.456
            toothbrush          2          5      0.778          1      0.995      0.698
```
# Test 2
```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.train(device=0, data="coco128.yaml", seed=42, epochs=50, batch=2, deterministic=True)
```

## Output
```
Model summary (fused): 168 layers, 3,151,904 parameters, 0 gradients, 8.7 GFLOPs
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|██████████| 32/32 [00:01<00:00, 17.84it/s]
                   all        128        929      0.763      0.596      0.685      0.525
                person         61        254      0.907      0.615      0.773      0.547
               bicycle          3          6      0.911        0.5      0.503      0.321
                   car         12         46      0.976      0.217       0.34      0.217
            motorcycle          4          5      0.652          1      0.962      0.833
              airplane          5          6      0.842          1      0.995      0.883
                   bus          5          7      0.918      0.714      0.735      0.627
                 train          3          3      0.916          1      0.995      0.708
                 truck          5         12      0.788        0.5      0.561      0.377
                  boat          2          6      0.747      0.333      0.492      0.286
         traffic light          4         14      0.599      0.143      0.205      0.139
             stop sign          2          2      0.693        0.5      0.745      0.596
                 bench          5          9      0.671      0.556      0.747      0.553
                  bird          2         16          1      0.875      0.952      0.637
                   cat          4          4      0.892          1      0.995      0.865
                   dog          9          9      0.835      0.889      0.928      0.697
                 horse          1          2       0.72          1      0.995      0.597
              elephant          4         17      0.599      0.882      0.897      0.688
                  bear          1          1      0.669          1      0.995      0.895
                 zebra          2          4       0.89          1      0.995      0.931
               giraffe          4          9      0.806      0.889      0.893      0.723
              backpack          4          6      0.649      0.315      0.355      0.187
              umbrella          4         18      0.692      0.611      0.683      0.456
               handbag          9         19      0.738       0.15      0.249      0.162
                   tie          6          7          1      0.544      0.794      0.608
              suitcase          2          4      0.743          1      0.995      0.631
               frisbee          5          5      0.462        0.8      0.663      0.561
                  skis          1          1      0.649          1      0.995      0.697
             snowboard          2          7      0.231      0.857      0.661        0.4
           sports ball          6          6          1      0.173      0.401      0.264
                  kite          2         10      0.637      0.355      0.554      0.245
          baseball bat          4          4          1          0      0.308      0.204
        baseball glove          4          7      0.605      0.429      0.364      0.242
            skateboard          3          5          1      0.574      0.601       0.52
         tennis racket          5          7      0.732      0.286      0.402      0.279
                bottle          6         18      0.507      0.343       0.49      0.338
            wine glass          5         16      0.858       0.25      0.457      0.301
                   cup         10         36      0.626      0.279      0.363      0.265
                  fork          6          6      0.627      0.167      0.184      0.181
                 knife          7         16      0.299      0.688      0.592      0.377
                 spoon          5         22          1      0.205      0.367      0.229
                  bowl          9         28      0.762      0.688      0.697      0.545
                banana          1          1          1          0      0.199     0.0896
              sandwich          2          2          1      0.638      0.995      0.946
                orange          1          4          1          0      0.995      0.649
              broccoli          4         11      0.767      0.182       0.24      0.196
                carrot          3         24      0.619       0.75      0.803      0.512
               hot dog          1          2      0.561          1      0.828       0.73
                 pizza          5          5      0.771          1      0.995      0.918
                 donut          2         14      0.646          1      0.947      0.831
                  cake          4          4      0.876          1      0.995      0.885
                 chair          9         35      0.558      0.433      0.518      0.322
                 couch          5          6      0.595      0.667      0.654      0.501
          potted plant          9         14      0.861      0.714      0.838      0.568
                   bed          3          3      0.772          1      0.995       0.93
          dining table         10         13      0.781      0.462      0.552       0.47
                toilet          2          2      0.554      0.661      0.828      0.795
                    tv          2          2      0.442          1      0.995      0.995
                laptop          2          3      0.708      0.333      0.753      0.546
                 mouse          2          2      0.649        0.5      0.545      0.355
                remote          5          8      0.822       0.75      0.762      0.603
            cell phone          5          8       0.65       0.25      0.319      0.195
             microwave          3          3      0.804      0.667      0.693      0.514
                  oven          5          5      0.767        0.6      0.608      0.505
                  sink          4          6          1      0.259      0.558      0.417
          refrigerator          5          5      0.769          1      0.995      0.803
                  book          6         29      0.599      0.414      0.581      0.344
                 clock          8          9      0.862      0.699      0.883      0.738
                  vase          2          2          1      0.783      0.995      0.895
              scissors          1          1          1          0          0          0
            teddy bear          6         21      0.895      0.571      0.724       0.51
            toothbrush          2          5          1      0.667      0.962      0.714
```

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by ambitious-octopus**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated mosaic augmentation method to use dataset caching more efficiently.

### 📊 Key Changes
- Removed `buffer` parameter from `get_indexes` method.
- Introduced `self.buffer` attribute to determine caching strategy based on dataset settings.

### 🎯 Purpose & Impact
- **Efficiency**: Improves the decision-making process for image selection by aligning with dataset cache settings.
- **Simplicity**: Simplifies the method's usage by automatically handling image selection based on internal logic.
- **User Benefit**: Users can expect more intuitive behavior when configuring datasets, especially with large-scale data tasks.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@ambitious-octopus I've got 2 alternate implementations here. Can you test both of these? Here's a good description of imap vs map, but it says the the current `imap` should already be returning the results ordered, as there is also `imap_unordered`. Are you sure this is the source of the problem?

https://github.com/ultralytics/ultralytics/blob/1a497f174c21993e2464725d96482e2a4a52758b/ultralytics/data/base.py#L182-L197

## Use pool.map instead of pool.imap

```python
    def cache_images(self):
        """Cache images to memory or disk."""
        b, gb = 0, 1 << 30  # bytes of cached images, bytes per gigabytes
        fcn, storage = (self.cache_images_to_disk, "Disk") if self.cache == "disk" else (self.load_image, "RAM")
        with ThreadPool(NUM_THREADS) as pool:
            results = pool.map(fcn, range(self.ni))
            pbar = TQDM(enumerate(results), total=self.ni, disable=LOCAL_RANK > 0)
            for i, x in pbar:
                if self.cache == "disk":
                    b += self.npy_files[i].stat().st_size
                else:  # 'ram'
                    self.ims[i], self.im_hw0[i], self.im_hw[i] = x  # im, hw_orig, hw_resized = load_image(self, i)
                    b += self.ims[i].nbytes
                pbar.desc = f"{self.prefix}Caching images ({b / gb:.1f}GB {storage})"
            pbar.close()
```

## Use futures

```python
from concurrent.futures import ThreadPoolExecutor, as_completed
from tqdm import tqdm

def cache_images(self):
    """Cache images to memory or disk deterministically with tqdm progress bar."""
    b, gb = 0, 1 << 30  # bytes of cached images, bytes per gigabytes
    fcn, storage = (self.cache_images_to_disk, "Disk") if self.cache == "disk" else (self.load_image, "RAM")
    
    with ThreadPoolExecutor(max_workers=NUM_THREADS) as executor:
        future_to_index = {executor.submit(fcn, i): i for i in range(self.ni)}
        results = [None] * self.ni
        
        with tqdm(total=self.ni, desc=f"{self.prefix}Caching images", disable=LOCAL_RANK > 0) as pbar:
            for future in as_completed(future_to_index):
                index = future_to_index[future]
                x = future.result()
                
                if self.cache == "disk":
                    b += self.npy_files[index].stat().st_size
                else:  # 'ram'
                    self.ims[index], self.im_hw0[index], self.im_hw[index] = x
                    b += self.ims[index].nbytes
                
                pbar.update(1)
                pbar.set_postfix({'GB': f"{b / gb:.1f}", 'Storage': storage})
```

**Comment by glenn-jocher** [comment]
@ambitious-octopus also can you test https://github.com/ultralytics/ultralytics/pull/15959 to see if this has any effect?

**Review by ambitious-octopus — COMMENTED** [review]
@glenn-jocher both `pool.map` and `futures` do not solve the problem, the same thing for PR #15959 does not solve the problem. I suspect it is not `ThreadPool's` fault. For now I would merge this PR, just to add the warning, meanwhile I will continue to investigate.

**Comment by Laughing-q** [comment]
@glenn-jocher @ambitious-octopus The inconsistent results between the ones with and without `cache="ram"` is because they generate `self.buffer` differently hence affecting the mosaic augmentation and result different training images.
- cache=None, the `buffer` would be updated along with the training process every time we call `load_image`: 
https://github.com/ultralytics/ultralytics/blob/5dce4917e0ce01f18e25256c8082b7baac05120f/ultralytics/data/base.py#L172
8n5eD9Wbsp
- cache="ram", the `buffer` would be updated within all images in advance while we call `load_image` for `cache_images`: https://github.com/ultralytics/ultralytics/blob/5dce4917e0ce01f18e25256c8082b7baac05120f/ultralytics/data/base.py#L185
ckw4kozy4L

To fix this I guess we need to disable using `buffer`, but not sure if we are going to do that since `buffer` speeds up every training launched within our package, and I bet there're only a few users who might face the non-deterministic issue with `cache="ram"`.

Also to clarify, this issue was discovered by @ambitious-octopus when he's debugging the non-deterministic issue I'm facing, but still it's not the root in my case since I'm not using `cache="ram"` in my training.

**Comment by ambitious-octopus** [comment]
Thanks, @Laughing-q , for the update. With this fix, training is now deterministic across runs. This means that launching two training sessions with cache="ram" will yield identical results. However, running one training session with cache=None and another with cache="ram" generates different results due to the buffer. The buffer is deactivated when caching on RAM, which slightly slows down the training process.

**Comment by glenn-jocher** [comment]
@ambitious-octopus @Laughing-q I've closed the other deterministic PR that I opened as it didn't work. What's the status of this PR, should we merge or close?

**Comment by ambitious-octopus** [comment]
@glenn-jocher The issue arises from how the buffer is handled during Mosaic augmentation when using `cache=ram`. In this mode, the buffer isn't properly updated, leading to non-deterministic behavior, even with `deterministic=True` set. You can verify this by starting two trainings with these parameters.

```python
from ultralytics import YOLO
model = YOLO("yolov8n.pt")
model.train(data="coco8.yaml", epochs=1, seed=42, deterministic=True, cache="ram")
```

This pull request addresses the problem by removing the buffer when `cache=ram` is used, ensuring deterministic training at the cost of a slight performance decrease due to the Mosaic augmentation no longer being cached.

Alternatively, we could add a warning that when both `cache=ram` and `deterministic=True` are used, training will not be deterministic due to this issue. **Thinking about it carefully, I would be in favor of this solution.**

> [!NOTE]
> A third, more complex solution would involve modifying the dataloader logic. When `cache=ram` is enabled, images could be stored in an accumulator that functions like a buffer. However, this approach requires more memory and significantly changes the data loading process.

What do you think @glenn-jocher @Laughing-q ?

**Comment by glenn-jocher** [comment]
@ambitious-octopus @Laughing-q actually the mosaic buffer should be mostly useless if cache='ram' is used as it's serving the same purpose (keeping a trailing cache of the latest images to stuff into the 3 other mosaic indices). I wouldn't expect any performance drop by disabling the mosaic buffer on cache='ram'.

@Laughing-q what should we do here? Is this PR required for the best reproducibility or should we close and move on?

**Comment by Laughing-q** [comment]
@ambitious-octopus @glenn-jocher Let's remain the `buffer` or there would be more inconsistency between `cache=ram` and `cache=None` i.e. the latter does mosaic within the 1000 samples, and the former would do mosaic sampling in the entire dataset if disable `buffer`.
I think we can endure the different results between `cache=ram` and `cache=None` as after all it's not exactly the same command(one with ram and one with None). 
@ambitious-octopus One question though, have you seen different results in multiple runs with `cache=ram`? if so then let's add a warning msg that the results might not be 100% reproducible with `cache=ram`, if not then let's close this PR.

**Comment by ambitious-octopus** [comment]
Yes, `cacehe=ram` is not deterministic:

Code:
```python
from ultralytics import YOLO
model = YOLO('yolov8n.pt')
model.train(device=0, data='coco128.yaml', epochs=1, deterministic=True, cache="ram", seed=42)
```

## Train 1:
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      2.55G      1.191      1.427      1.251        153        640: 100%|██████████| 8/8 [00
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|████████
                   all        128        929      0.666      0.516      0.613      0.455
```

## Train 2:
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      2.54G       1.17      1.352      1.243        158        640: 100%|██████████| 8/8 [00
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|████████
                   all        128        929      0.653      0.522      0.614      0.455
```

## Train 3:
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      2.57G      1.207      1.418       1.26        134        640: 100%|██████████| 8/8 [00
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|████████
                   all        128        929      0.665      0.516      0.612      0.454
```

## Train 4:
```
      Epoch    GPU_mem   box_loss   cls_loss   dfl_loss  Instances       Size
        1/1      2.62G      1.227      1.475       1.27        182        640: 100%|██████████| 8/8 [00
                 Class     Images  Instances      Box(P          R      mAP50  mAP50-95): 100%|████████
                   all        128        929      0.661      0.521      0.617      0.455
```

**Comment by ambitious-octopus** [comment]
@glenn-jocher @Laughing-q added just a warning!

**Review by glenn-jocher — APPROVED** [review]

**Comment by glenn-jocher** [comment]
@ambitious-octopus @Laughing-q looks good. All this work for just a little warning at the end 😂

**Pull request merged**
