### PR TITLE
Add YOLOv5 training with HUB

### PR DESCRIPTION
**Pull request by kalenmike**
This allows training with HUB.

- Connect with an API Key
- Download model information from HUB
- Train with callbacks for checkpoints, metrics, final weights

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced Ultralytics HUB training integration with new export format support and refined API interactions.

### 📊 Key Changes
- Removed hardcoded training parameters and refactored startup logic.
- Added support for more export formats, including `ultralytics_tflite` and `ultralytics_coreml`.
- Simplified the API key request process with a dedicated function.
- Streamlined model exportation verification by asserting correct HTTP response and export format.
- Updated `HubTrainingSession` class to better manage heartbeats and signal handling.
- Added functionality to upload training metrics and final models to the HUB.
- Included model parameter count, GFLOPs, and inference speed in the initial upload metrics.

### 🎯 Purpose & Impact
- 📈 Improves usability by simplifying the process to start training and exporting models.
- 🤖 Extends model compatibility with additional export formats for broader deployment options.
- 🚀 Enables efficient model progression tracking and enhanced HUB communication for better user experience.
- 🛠️ Facilitates better resource management in Colab environments and avoids unnecessary heartbeat signals post-training.

### CODE REVIEW

**Comment by kalenmike** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
@kalenmike should we update to handle older names arrays? We have a function to do this here:

https://github.com/ultralytics/ultralytics/blob/3633d4c06b806a971f444919c389ac6e889cdb23/ultralytics/nn/autobackend.py#L21-L29

**Comment by glenn-jocher** [comment]
@kalenmike I went to go add backwards compat for array-style dataset names, but I see it's already present here when loading a dataset:
https://github.com/ultralytics/ultralytics/blob/2e7a533ac3e6bde645797abc3394d6d7bdf6274f/ultralytics/yolo/data/utils.py#L203-L212

So I'm not sure where else to add it. I'll go ahead and merge this into 8.0.31 and we can update via additional PRs.

**Comment by glenn-jocher** [comment]
@kalenmike ok I made a few cleanup changes. emojis() is not required with LOGGER.info() or LOGGER.warning(), but is required if using emojis when raising errors like `raise TypeError(emojis(str_with_emojis))`

I also grabbed the export_format() list from yolo/engine/exporter.py

**Pull request merged**
