### PR TITLE
`RTDETRDetectionModel` TorchScript, ONNX Predict and Val support

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Upgrades and tweaks in YOLO and RT-DETR models for enhanced performance and flexibility.

### 📊 Key Changes
- **Benchmark Naming:** Renamed a benchmark task to better reflect its specific model focus. 🚀
- **RT-DETR Enhancements:** Removed model file extension check for RT-DETR, offering more flexibility in model sources. 🌐
- **Prediction Adjustments:** Updated prediction handling in RT-DETR for consistency across different model inference outputs. 🛠
- **Validation Improvements:** Adjusted the postprocess method to accommodate varied prediction outputs, improving model validation accuracy. 🎯
- **File Handling:** Enhanced file search functionality to find model files more effectively, reducing user frustration. 🔍
- **Model Updates Utility:** Introduced a utility function to facilitate YOLO models updates, including name updates from a dataset YAML, aiming at better model management. 🔄

### 🎯 Purpose & Impact
- The changes aim to **improve user experience** by making models more flexible and easier to manage.
- **Enhanced benchmarking and file search** functionalities lead to **smoother development workflows** and **quicker setup times** for new projects.
- **RT-DETR adjustments** allow users to work with a broader range of model formats, **increasing the framework's adaptability**.
- The **new utility function** for updating models streamlines maintenance tasks, **ensuring models are up-to-date** with minimal effort, thus benefiting developers and users aiming for optimal model performance.

These improvements collectively make the framework more robust, user-friendly, and versatile for various machine learning tasks. 🚀🔧👥

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q RTDETR error seems related to self.names:

```
  File "/Users/runner/work/ultralytics/ultralytics/ultralytics/engine/results.py", line 327, in verbose
    log_string += f"{n} {self.names[int(c)]}{'s' * (n > 1)}, "
                         ~~~~~~~~~~^^^^^^^^
KeyError: 141
```

**Comment by glenn-jocher** [comment]
@Burhan-Q @Laughing-q the RTDETR models are definitely missing names. Not sure if this will fix benchmarks but we should add them anyway manually and re-upload assets, this is no good.

```bash
yolo predict model=rtdetr-l.pt
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/rtdetr-l.pt to 'rtdetr-l.pt'...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63.4M/63.4M [00:01<00:00, 41.8MB/s]
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.1.25 🚀 Python-3.11.2 torch-2.2.0 CPU (Apple M2)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients, 103.8 GFLOPs

image 1/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x640 4 0s, 1 5, 1 9, 1 10, 2 27s, 521.2ms
image 2/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 640x640 2 0s, 2 27s, 521.7ms
Speed: 2.8ms preprocess, 521.5ms inference, 1.0ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics/runs/detect/predict
💡 Learn more at https://docs.ultralytics.com/modes/predict
```

**Comment by glenn-jocher** [comment]
@Burhan-Q added class names to the official models now:

Screenshot 2024-03-09 at 20 02 38


```bash
yolo predict model=rtdetr-l.pt
Downloading https://github.com/ultralytics/assets/releases/download/v8.1.0/rtdetr-l.pt to 'rtdetr-l.pt'...
100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 63.4M/63.4M [00:01<00:00, 37.4MB/s]
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Ultralytics YOLOv8.1.25 🚀 Python-3.11.2 torch-2.2.0 CPU (Apple M2)
rt-detr-l summary: 494 layers, 32148140 parameters, 0 gradients, 103.8 GFLOPs

image 1/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x640 4 persons, 1 bus, 1 traffic light, 1 fire hydrant, 2 ties, 515.3ms
image 2/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 640x640 2 persons, 2 ties, 508.5ms
Speed: 2.5ms preprocess, 511.9ms inference, 0.8ms postprocess per image at shape (1, 3, 640, 640)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics/runs/detect/predict2
💡 Learn more at https://docs.ultralytics.com/modes/predict
```

**Comment by Burhan-Q** [comment]
Just adding for reference that this worked. There's also Glenn's [comment](https://github.com/ultralytics/ultralytics/pull/8580#issuecomment-1975306499) from #8580 
```py
from ultralytics import YOLO, RTDETR

model = RTDETR("rtdetr-l.pt")
yolo = YOLO("yolov8n.pt")

# Set COCO class names
model.model.names = yolo.names.copy()

# Save copy with class names
model.save("rtdetr-l-names.pt")
```

**Comment by Burhan-Q** [comment]
Well, I guess my previous comment is irrelevant 😆 Glenn too fast!

**Comment by glenn-jocher** [comment]
@Burhan-Q @Laughing-q I've made updates now to support exported model inference for RTDETR. It looks like most formats have export issues, but at least TorchScript and ONNX RTDETR models do work:

```bash
WARNING ⚠️ 'source' is missing. Using default 'source=/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets'.
Loading /Users/glennjocher/PycharmProjects/ultralytics/rtdetr-l.onnx for ONNX Runtime inference...

image 1/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg: 640x640 4 persons, 1 bus, 1 traffic light, 1 fire hydrant, 2 ties, 392.9ms
image 2/2 /Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/zidane.jpg: 640x640 2 persons, 2 ties, 385.2ms
Speed: 2.6ms preprocess, 389.0ms inference, 0.5ms postprocess per image at shape (1, 3, 640, 640)
💡 Learn more at https://docs.ultralytics.com/modes/predict
```

**Comment by glenn-jocher** [comment]
@Burhan-Q @Laughing-q merging this PR with RTDETR predict and val mode support for exported models, as well as model.names added to RTDETR assets.

Benchmarks left out as only YOLO benchmarks are currently supported, but we can revisit once we have a "meta" model class that can load all models.

**Pull request merged**
