### PR TITLE
Fix Triton inference without explicit metadata

### PR DESCRIPTION
**Pull request by zeograd**
When model type is pt, triton or nn_module, task may not be defined in constructor while expected during inference.

Current code, introduced in august in 76c271d0d6af7a45715a9446d32374e47974cc25, was expecting 'task' to be defined, ending up with error `AttributeError: 'AutoBackend' object has no attribute 'task'` when performing inference as per the triton integration documentation (https://docs.ultralytics.com/guides/triton-inference-server/#running-triton-inference-server)

Just allowing this field to be missing during the check for task being "segment" fixes this error.

Another person was getting the exact same behaviour as per this comment: https://github.com/ultralytics/ultralytics/discussions/8241#discussioncomment-10599465

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improved condition handling in autobackend for undefined segments and names.

### 📊 Key Changes
- Modified a conditional check to ensure `self.task` is accessed safely using `getattr`.

### 🎯 Purpose & Impact
- **Safety Enhancement**: Prevents potential errors if `self.task` is not set, leading to more robust code.
- **User Benefit**: Reduces the risk of unexpected crashes, improving reliability for users working with segmentation tasks.

### CODE REVIEW

**Comment by zeograd** [comment]
I have read the CLA Document and I sign the CLA

**Comment by UltralyticsAssistant** [comment]
👋 Hello @zeograd, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response, and an Ultralytics engineer will assist you soon. Meanwhile, please take a moment to review the checklist below to ensure a smooth integration:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear and concise.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. Update it if necessary by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. Address any issues if checks fail.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. 🛠️

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If your PR is a bug report and you haven't provided a minimum reproducible example (MRE), please do so to facilitate our review. Don’t hesitate to leave a comment if you have any questions. Thank you for contributing to Ultralytics! 🚀🔍

**Comment by glenn-jocher** [comment]
@zeograd if `task` is missing preferred solution would be that it's not missing. Change L129:

```python
        model, metadata = None, None
```

to add `task=None`

**Comment by zeograd** [comment]
@glenn-jocher thanks for the review.

Locally tested and PR updated accordingly

**Comment by glenn-jocher** [comment]
Thank you for updating the PR and testing it locally. We'll review the changes soon.

**Comment by glenn-jocher** [comment]
@zeograd PR merged!

**Pull request merged**
