### PR TITLE
Add attribute error msgs

### PR DESCRIPTION
**Pull request by AyushExel**
@glenn-jocher @Laughing-q 
I've only added Logger.info lever msgs. Maybe it's better to throw Exception instead?

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced attribute error handling for YOLO result objects.

### 📊 Key Changes
- Added `__getattr__` methods to `Results`, `Boxes`, and `Masks` classes.
- These methods provide detailed attribute error messages, listing valid properties when an invalid attribute is accessed.

### 🎯 Purpose & Impact
- 🎓 **Educational**: Helps developers understand the correct attributes they can use.
- ⚡️ **User-friendly**: Offers a detailed guide on what valid attributes are available, reducing confusion and improving debugging.
- 🔍 **Improved Readability**: Presents organized information when an attribute-related error occurs, enhancing the overall user experience with clear guidance.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel oh awesome! Nice discovery!!

**Comment by glenn-jocher** [comment]
@AyushExel when I run this branch it seems results.xyxy is not affected:

Screenshot 2023-01-19 at 13 57 58

**Comment by glenn-jocher** [comment]
Also if I run this I get a for loop with very many outputs:
Screenshot 2023-01-19 at 14 00 26

**Comment by AyushExel** [comment]
> @AyushExel when I run this branch it seems results.xyxy is not affected:
> 
> Screenshot 2023-01-19 at 13 57 58

This we cannot fix. You're calling -> [Results].xyxy.. It's the inbuilt python `List` type. We can only intercept error msgs if you do `Results.attribute`

**Comment by AyushExel** [comment]
> Also if I run this I get a for loop with very many outputs: Screenshot 2023-01-19 at 14 00 26

Hmm this might be ipython issue.. I don't get this on my mac. Maybe raising and exception will make this better.

**Comment by glenn-jocher** [comment]
@AyushExel oh ok, I get you, the output is a list of Results objects. 

We could alternatively output a single Results object that has list methods, i.e. __getitem__ and __next__ etc, but this would be a substantial change.

**Comment by AyushExel** [comment]
This is what happens on my mac.
Screenshot 2023-01-19 at 6 51 52 PM
This is what happens after changing it from msg to Exception

Screenshot 2023-01-19 at 6 55 03 PM

**Pull request merged**
