### PR TITLE
force torch.cuda.is_available() = False when using cpu

### PR DESCRIPTION
**Pull request by developer0hye**
### Summary
🚫🌐🚀

The pull request enhances the device compatibility of the YOLOv5 model by overriding `torch.cuda.is_available` in `torch_utils.py` to respect the device argument. This prevents CUDA from being used when it is not available or not desired.

> _`torch.cuda` lies_
> _when device is cpu or mps_
> _autumn of CUDA_

### Walkthrough
*  Override `torch.cuda.is_available` to return False for cpu or mps devices ([link](https://github.com/ultralytics/ultralytics/pull/2669/files?diff=unified&w=0#diff-b19b7e7ce0f018a381bc8c238cc1554454d0b5ea2b4c2880a822b732f05535d8L64-R66)) to avoid using CUDA when not supported or desired

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced compatibility with non-CUDA environments.

### 📊 Key Changes
- Modified the `select_device` function to explicitly set `torch.cuda.is_available()` to return `False` when using CPU or Apple MPS.
- Added a lambda function to override `torch.cuda.is_available` conditionally based on the specified device.
- Ensured the `CUDA_VISIBLE_DEVICES` environment variable is set accordingly.

### 🎯 Purpose & Impact
- **Purpose:** To ensure that YOLO runs smoothly on systems without Nvidia GPU support, especially those using CPUs or Apple's MPS.
- **Impact:** Improves user experience by automatically adapting to different hardware setups, preventing potential errors when CUDA is not available. This makes Ultralytics software more accessible and user-friendly for a broader range of devices and platforms. 🍏💻🚫🔥

### CODE REVIEW

**Comment by developer0hye** [comment]
`os.environ['CUDA_VISIBLE_DEVICES'] = '-1'` is not working.

**Comment by glenn-jocher** [comment]
@developer0hye thank you for bringing this to our attention. In order to properly disable the use of CUDA, you should override `torch.cuda.is_available()` in `torch_utils.py`, as setting `os.environ['CUDA_VISIBLE_DEVICES']` only controls which GPU devices are seen by CUDA, but doesn't disable CUDA entirely. Overriding `torch.cuda.is_available()` to return `False` when running on CPU should prevent any CUDA-related errors.

**Comment by developer0hye** [comment]
@glenn-jocher Is it still being reviewed?

**Comment by glenn-jocher** [comment]
@developer0hye hello! Thank you for reaching out. Can you please provide me with more context regarding what you're referring to specifically? That way, I can give you a more accurate answer. In general, our team is constantly reviewing and addressing any issues that are reported on the YOLOv8 repo, so if you have an issue to report, please feel free to create a new issue or comment on an existing one. Thank you!

**Comment by developer0hye** [comment]
@glenn-jocher 

`os.environ['CUDA_VISIBLE_DEVICES'] = '-1'` doesn't work like we intended.

image

image

**Comment by glenn-jocher** [comment]
@developer0hye hello! Thank you for bringing this to our attention. Setting `os.environ['CUDA_VISIBLE_DEVICES'] = '-1'` is not sufficient on its own to disable the use of CUDA in YOLOv8. Instead, please override `torch.cuda.is_available()` in `torch_utils.py` to return `False` when running on CPU. This should prevent any CUDA-related errors. Let us know if you have any further questions or issues. Thank you!

**Comment by glenn-jocher** [comment]
@developer0hye I think one problem with setting the lambda function is that we want to be able to to switch back and forth between cuda and cpu, i.e. this code should work:

```python
from ultralytics import YOLO

for d in (0, 'cpu', 0, 'cpu'):
  model = YOLO()
  results = model.predict(source='https://ultralytics.com/images/bus.jpg', device=d)
```

In Colab here you can see the fast and slow speeds of the different devices:
Screenshot 2023-05-23 at 01 05 59

Does this still work with this PR?

**Comment by glenn-jocher** [comment]
@developer0hye You're welcome! I'm glad I could help. If you have any further questions or issues, please don't hesitate to ask. We are always happy to assist with any YOLOv8-related concerns.

**Pull request closed without merging**
