### PR TITLE
Update ai_gym.py

### PR DESCRIPTION
**Pull request by yo-WASSUP**
Fix the bug where the elbow angle being less than 90 degrees also triggers counting when the human's arm is freely swinging below the shoulder.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced the AI Gym module to improve accuracy in counting exercises.

### 📊 Key Changes
- Added a condition to verify keypoint positions before incrementing the exercise count.

### 🎯 Purpose & Impact
- **Improved Accuracy:** Ensures that counts are only incremented when specific keypoint criteria are met, reducing false positives. 🏋️‍♂️
- **User Benefit:** Provides more reliable exercise tracking, improving user experience and data accuracy. 📈

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar can you review this PR please?

@yo-WASSUP please sign the CLA by commenting this in a new message: 

I have read the CLA Document and I sign the CLA

**Comment by yo-WASSUP** [comment]
> @RizwanMunawar can you review this PR please?
> 
> @yo-WASSUP please sign the CLA by commenting this in a new message:
> 
> I have read the CLA Document and I sign the CLA

I have read the CLA Document and I sign the CLA

**Comment by yo-WASSUP** [comment]
I have read the CLA Document and I sign the CLA

**Review by RizwanMunawar — CHANGES_REQUESTED** [review]
@yo-WASSUP! Thank you for your pull request. After reviewing it, I noticed that you've implemented a condition to check for selected key points. i.e if the first key point is greater than the second key point, only increment the counts. While this condition is not necessary here, the key points are differ for every exercise i.e, pullups, abworkouts and pushups.  

The tested video sample is attached for your reference.

Everything appears to function correctly for ab workouts without your changes. If you encounter any issues with dual counting during the same repetition, adjusting the `poseup_angle` or `posedown_angle` values could potentially improve the results. Don't forget, that we have included documentation that offers a comprehensive guide on how to modify arguments without altering the codebase. You can access more details here: https://docs.ultralytics.com/guides/workouts-monitoring/#real-world-applications

We eagerly anticipate the new pull requests you'll submit, as we greatly value community support and collaborative feature development!

Thanks
Ultralytics Team!

https://github.com/ultralytics/ultralytics/assets/62513924/019dc000-f480-40f9-b00a-7391edf18f72

**Comment by RizwanMunawar** [comment]
@yo-WASSUP Thanks for your PR! Following my previous feedback, I haven't seen any updates on it, so I will be closing this PR for now. However, feel free to submit a new one if you encounter any issues or have suggestions for improving the `ultralytics` codebase.

We look forward to your future contributions!

cc: @glenn-jocher @ambitious-octopus

Best regards,  
The Ultralytics Team

**Pull request closed without merging**
