### PR TITLE
Add https://youtu.be/aeAX6vWpfR0 to docs & `african-wildlife` dataset docs page

### PR DESCRIPTION
**Pull request by RizwanMunawar**
@glenn-jocher 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing the African Wildlife Dataset for Advanced Animal Detection 🦓🐘🦬

### 📊 Key Changes
- **New African Wildlife Dataset:** A valuable addition focusing on animals like buffalo, elephant, rhino, and zebra for machine learning models.
- **Dataset Structure:** Organized into training (1052 images), validation (225 images), and testing (227 images) sets, all with corresponding annotations.
- **Educational and Research Applications:** Ideal for tasks such as object detection, tracking, and broad wildlife studies.
- **Enhanced Documentation:** Includes dataset details, sample usage for YOLO models, and links to download the dataset YAML configuration.
- **Pose Estimation Videos:** Added a new video tutorial for pose estimation, expanding learning resources.
- **Navigation Update:** The dataset is now easily accessible through updated website navigation.

### 🎯 Purpose & Impact
- **Conservation and Research:** Aids in wildlife conservation efforts and ecological research by providing a robust tool for animal identification and tracking in their natural habitats.
- **Machine Learning:** Enables researchers and developers to train more effective models on animal detection, contributing to advancements in computer vision.
- **Educational Value:** Offers a rich resource for students and professionals looking to dive into wildlife recognition and related AI technologies.

By making machine learning more accessible and applicable to real-world scenarios, this dataset not only pushes the boundaries of technology but also contributes significantly towards the conservation and understanding of wildlife.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@RizwanMunawar ah I just realized we are missing bullet points for the previous dataset and this one in https://github.com/RizwanMunawar/ultralytics/blob/african_wildlife_docs/docs/en/datasets/index.md, can you add those?

**Comment by RizwanMunawar** [comment]
@glenn-jocher modifications applied :)

**Comment by glenn-jocher** [comment]
@RizwanMunawar thanks for the fixes, looks good!

**Review by glenn-jocher — COMMENTED** [review]
Looks good!

**Pull request merged**
