### PR TITLE
Removed redundency in RTDETRDecoder

### PR DESCRIPTION
**Pull request by sebastian-stapf**
Changed the order of operations in RTDETRDecoder._get_decoder_input
By first selecting the top k features and selecting the top k anchors, one can reduce the input to the linear layer by a large margin.

### Summary
:zap::top::broom:

This pull request enhances the `encoder_bbox_head` module to use more relevant features and anchors for bounding box prediction. It also removes some redundant or unnecessary code from `ultralytics/nn/modules/head.py`.

> _`encoder_bbox_head`_
> _Faster with top k features_
> _Winter pruning code_

### Walkthrough
*  Use top k features and anchors instead of encoder output bboxes for decoder input and loss computation ([link](https://github.com/ultralytics/ultralytics/pull/4118/files?diff=unified&w=0#diff-06038a7c9e9c565760881118b974c2f2fe7aee7c78bb6c142d1498d0d9614639L310-L311), [link](https://github.com/ultralytics/ultralytics/pull/4118/files?diff=unified&w=0#diff-06038a7c9e9c565760881118b974c2f2fe7aee7c78bb6c142d1498d0d9614639L319-R322), [link](https://github.com/ultralytics/ultralytics/pull/4118/files?diff=unified&w=0#diff-06038a7c9e9c565760881118b974c2f2fe7aee7c78bb6c142d1498d0d9614639L333-R334))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Optimization of encoder-to-decoder data flow in the Ultralytics neural network architecture.

### 📊 Key Changes
- Removed the addition of anchors at every encoder output position, now adding dynamically generated anchors only to selected top-k positions.
- Avoided redundant computation by sharing the computation between reference bounding boxes and embedding features for non-learnt queries.
- Ensured detachment of certain tensors during training to prevent undesired gradient calculations.

### 🎯 Purpose & Impact
- 🔍 **Increased Efficiency:** Focusing computation on top-k features reduces computational load and potentially increases inference speed.
- 🛠️ **Code Simplification:** The changes simplify the data preparation process from encoder to decoder, making the code more maintainable.
- 🏋️‍♂️ **Training Stability:** Detaching specific tensors during training helps in avoiding unintended backpropagation, leading to more stable training updates.

### CODE REVIEW

**Comment by Wiqzard** [comment]
I have read the CLA Document and I sign the CLA

**Comment by glenn-jocher** [comment]
recheck

**Comment by Laughing-q** [comment]
@Wiqzard @glenn-jocher This looks great! It works smoothly like before and even saves slight cuda memory in my tests.
Thanks for the PR! @Wiqzard

**Comment by Wiqzard** [comment]
recheck

**Comment by glenn-jocher** [comment]
@Laughing-q @Wiqzard awesome, nice improvement!

PR merged! Thank you for your contributions.

**Pull request merged**
