### PR TITLE
Check PyTorch model status for all `YOLO` methods

### PR DESCRIPTION
**Pull request by glenn-jocher**
@AyushExel @Laughing-q this PR allows predict and val for all model types (PyTorch, ONNX, TensorRT etc.), but restrict other methods (train, export, info, fuse, etc.) to only PyTorch models. Raise TypeError is restricted operation is attempted, i.e. attempt to train a TensorRT model.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Updated dependencies and functionalities for improved compatibility and features.

### 📊 Key Changes
- Upgraded minimum PyTorch version from `1.7.0` to `1.8.0`.
- Improved installation requirements for consistency across setups.
- Enhanced CI configuration for better integration and testing.
- Updated README to reflect completed YOLOv8 aspects and community support channels.
- Introduced SECURITY.md outlining security practices and vulnerability reporting.
- Expanded and organized documentation, including security details.
- Streamlined testing by simplifying and correcting CLI commands.
- Code refactoring for better clarity and maintenance.

### 🎯 Purpose & Impact
- Ensures compatibility with newer versions of PyTorch and associated libraries 🔄.
- Aids users in understanding Ultralytics' commitment to security 👮‍♂️.
- Simplifies contribution process for developers by specifying security contact points 🛡️.
- Enhances user experience with updated documentation and testing procedures 📑.
- Minor version bump signifies non-breaking but significant updates 🚀.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel now if a user tries an incorrect operation they get this message:

```bash
yolo export model=yolov8n.onnx

WARNING ⚠️ 'format' is missing. Using default 'format=torchscript'.
Traceback (most recent call last):
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/bin/yolo", line 33, in <module>
    sys.exit(load_entry_point('ultralytics', 'console_scripts', 'yolo')())
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/yolo/cfg/__init__.py", line 304, in entrypoint
    getattr(model, mode)(**overrides)  # default args from model
  File "/Users/glennjocher/PycharmProjects/ultralytics/venv/lib/python3.10/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/yolo/engine/model.py", line 198, in export
    self._check_is_pytorch_model()
  File "/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/yolo/engine/model.py", line 110, in _check_is_pytorch_model
    raise TypeError(f"model='{self.model}' must be a PyTorch model, but is a different type. Other model "
TypeError: model='yolov8n.onnx' must be a PyTorch model, but is a different type. Other model formats, i.e. ONNX, TensorRT etc. are not supported by this operation. Try i.e. model='yolov8n.pt' instead.
```

**Comment by glenn-jocher** [comment]
@AyushExel @Laughing-q PR also assumes defaults classify transforms if they are missing, i.e. for exported cls models like yolov8n-cls.onnx, so the following code now works correctly:

```bash
yolo export yolov8n-cls.pt format=onnx imgsz=224
yolo predict yolov8n-cls.onnx imgsz=224
```

**Comment by Laughing-q** [comment]
@glenn-jocher TensorFlow exports is supported right? and now DDP resume is fixed, probably we should remove these two or check the box?

**Comment by glenn-jocher** [comment]
> @glenn-jocher TensorFlow exports is supported right? and now DDP resume is fixed, probably we should remove these two or check the box?

@Laughing-q oh yeah, good point. TF exports now work using onnx2tf package, so yes they are technically working. I haven't verified predict and val on TF models yet though, but I agree we should check the two boxes in README, I'll do that.

**Comment by glenn-jocher** [comment]
@Laughing-q BTW I made a change to DDP command in https://github.com/ultralytics/ultralytics/pull/945/commits/a594f63d63353477a62b263110b11927e3bc07b2 to address security vulnerability scans in https://snyk.io/advisor/python/ultralytics that didn't like that we were passing sys.argv() straight to os.system(), so now I pass all parsed trainer.args except for save_dir. I think this is correct and I've tested a single DDP training (CLI and python) both work, but haven't tested resume.

**Comment by Laughing-q** [comment]
> @Laughing-q BTW I made a change to DDP command in [a594f63](https://github.com/ultralytics/ultralytics/commit/a594f63d63353477a62b263110b11927e3bc07b2) to address security vulnerability scans in https://snyk.io/advisor/python/ultralytics that didn't like that we were passing sys.argv() straight to os.system(), so now I pass all parsed trainer.args except for save_dir. I think this is correct and I've tested a single DDP training (CLI and python) both work, but haven't tested resume.

the server is occupied so I'm not able to test resume but logically I think resume should work as well.

**Pull request merged**
