### PR TITLE
Fix: mlflow integration issues

### LINKED ISSUE #4930: mlflow on_pretrain_routine_end fails if the experiment name does not exist
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

code causing the bug https://github.com/ultralytics/ultralytics/blob/e7401f5872ec0eca6239474a6f3afbd85753fb9d/ultralytics/utils/callbacks/mlflow.py#L33
````python
       experiment_name = os.environ.get('MLFLOW_EXPERIMENT_NAME') or trainer.args.project or '/Shared/YOLOv8'
        run_name = os.environ.get('MLFLOW_RUN') or trainer.args.name
        experiment = mlflow.get_experiment_by_name(experiment_name)
        if experiment is None:
            mlflow.create_experiment(experiment_name)
        mlflow.set_experiment(experiment_name)

        prefix = colorstr('MLFlow: ')
        try:
            run, active_run = mlflow, mlflow.active_run()
            if not active_run:
                active_run = mlflow.start_run(experiment_id=experiment.experiment_id, run_name=run_name)
````
`if experiment is None` block does not reset it to a value, resulting in an Attribute error if that was the case.

changing it to the following will fix the bug, as mlflow now does the automatic creation internally (presumably since mlflow 2.0)
````python
experiment = mlflow.set_experiment(experiment_name)
````
There are other things broken with the MLFLOW-related callbacks.
Would you be interested in a PR fixing that for recent versions of mlflow, or do you plan to drop the support for it entirely?
(I am just wondering since it is not part of your official Documentation)

### Environment

_No response_

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Gornoka**
### Summary
🛠️📦🧠

Enhanced MLFlow support in `ultralytics/utils/callbacks/mlflow.py` by streamlining code and enabling more features.

> _`mlflow.py` changed_
> _Modules, constants, logging_
> _Simplified in spring_

### Walkthrough
*  Import `os` and `re` modules and define `PREFIX` constant for logging messages ([link](https://github.com/ultralytics/ultralytics/pull/4959/files?diff=unified&w=0#diff-1d0709c6f7ef2e65b3174d19938d0feaa0c9f8445b82377265cb4c94b76a45fcL2-R5), [link](https://github.com/ultralytics/ultralytics/pull/4959/files?diff=unified&w=0#diff-1d0709c6f7ef2e65b3174d19938d0feaa0c9f8445b82377265cb4c94b76a45fcL12-R16))
*  Enable automatic logging of parameters, metrics, and artifacts with `mlflow.autolog` and create experiment if not exists with `mlflow.set_experiment` ([link](https://github.com/ultralytics/ultralytics/pull/4959/files?diff=unified&w=0#diff-1d0709c6f7ef2e65b3174d19938d0feaa0c9f8445b82377265cb4c94b76a45fcL28-R34))
*  Log trainer save directory as an artifact with `run.log_artifact` and end run with `mlflow.end_run` ([link](https://github.com/ultralytics/ultralytics/pull/4959/files?diff=unified&w=0#diff-1d0709c6f7ef2e65b3174d19938d0feaa0c9f8445b82377265cb4c94b76a45fcL61-R71))
*  Comment out unnecessary and inefficient logging of entire virtual environment and codebase with `run.pyfunc.log_model` ([link](https://github.com/ultralytics/ultralytics/pull/4959/files?diff=unified&w=0#diff-1d0709c6f7ef2e65b3174d19938d0feaa0c9f8445b82377265cb4c94b76a45fcL61-R71))
*  Add debug logging statements for tracking uri and run end with `LOGGER.debug` ([link](https://github.com/ultralytics/ultralytics/pull/4959/files?diff=unified&w=0#diff-1d0709c6f7ef2e65b3174d19938d0feaa0c9f8445b82377265cb4c94b76a45fcL28-R34), [link](https://github.com/ultralytics/ultralytics/pull/4959/files?diff=unified&w=0#diff-1d0709c6f7ef2e65b3174d19938d0feaa0c9f8445b82377265cb4c94b76a45fcL61-R71))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to the MLFlow integration with Ultralytics software.

### 📊 Key Changes
- Simplified the import statements by removing `ROOT` from the list.
- Introduced a prefixed log message format for MLFlow-related messages.
- Streamlined MLFlow experiment creation and setting within the existing codebase.
- Enabled MLFlow's automatic logging feature.
- Refined the `on_train_end` function to log artifacts and properly end the MLFlow run with clearer logging output.

### 🎯 Purpose & Impact
- Removing the unused `ROOT` import makes the code cleaner and potentially more efficient.
- The prefixed log messages (`PREFIX = colorstr('MLFlow:')`) improve visibility of MLFlow-related logs, aiding debugging and user understanding.
- By updating the experiment creation and setting to rely on MLFlow's defaults, the code becomes more robust and less prone to errors, making experiment tracking simpler for users.
- Enabling automatic logging (`mlflow.autolog()`) simplifies tracking of parameters, metrics, and models - this means enhanced tracking with minimal user intervention.
- Refined artifact logging and a clear end-run signal provide better resource management and user feedback on run completion, ensuring that users have a clear indicator when MLFlow runs end and what artifacts have been logged.

👩‍💻👨‍💻 These changes aim to streamline user interaction with MLFlow for training models, simplifying the user experience, and providing more clarity during the model training and logging process.

### CODE REVIEW

**Comment by Gornoka** [comment]
This PR does 1 change that should be discussed properly,
The old implementation of the end of run log logged the entire working folder of the training run, this PR will not log all files from the training directory, just the commit hash of the training directory, and the output directory.

**Comment by glenn-jocher** [comment]
@Gornoka thanks for the PR! I've made some minor edits. Please either delete or uncomment the commented code block and then this should be good to go.

**Comment by Gornoka** [comment]
> @Gornoka thanks for the PR! I've made some minor edits. Please either delete or uncomment the commented code block and then this should be good to go.

thanks for the quick review

**Comment by glenn-jocher** [comment]
> This PR does 1 change that should be discussed properly, The old implementation of the end of run log logged the entire working folder of the training run, this PR will not log all files from the training directory, just the commit hash of the training directory, and the output directory.

Oh I just read this. The training directory contains many useful images and results, but also contain the weight/last.pt and weights/best.pt files. If the current code is logging everything but the *.pt files then it probably makes sense to keep this, as users may start reporting bugs about missing training results if this is removed.

**Comment by Gornoka** [comment]
> training

the result directory is now uploaded, just not the directory of the execution location.
example after changes:
image

example before changes: 
image

**Comment by glenn-jocher** [comment]
@Gornoka ah got it, looks much better :)

PR merged!

**Pull request merged**
