### PR TITLE
`ultralytics 8.0.129` add YOLOv8 Tencent NCNN export

### LINKED ISSUE #726: how to convert .pt -> ONNX -> NCNN for android deployment???
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hello everyone,

I have trained yolov8n-seg on my custom dataset and would like to do inference using NCNN framework. For thaT, I have to convert model to ONNX and then to NCNN supported param and bin files. 

Anyone has tried to run on NCNN then can you please help me out how to deploy it?

Thank you in advance. 

### Additional

_No response_

### LINKED ISSUE #1048: Running train.py got the error \ultralytics\yolo\utils\tal.py", line 215, in make_anchors      _, _, h, w = feats[i].shape
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Running train.py got the error \ultralytics\yolo\utils\tal.py", line 215, in make_anchors
     _, _, h, w = feats[i].shape
ValueError: not enough values to unpack (expected 4, got 3) in version 8.0.40, but everything works fine in version 8.0.31

Traceback (most recent call last):
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 217, in <module>
    train()
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 213, in train
    trainer.train()
  File "D:\ultralytics-main-20230219\ultralytics\yolo\engine\trainer.py", line 187, in train
    self._do_train(RANK, world_size)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\engine\trainer.py", line 306, in _do_train
    self.loss, self.loss_items = self.criterion(preds, batch)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 76, in criterion
    return self.compute_loss(preds, batch)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\v8\detect\train.py", line 169, in __call__
    anchor_points, stride_tensor = make_anchors(feats, self.stride, 0.5)
  File "D:\ultralytics-main-20230219\ultralytics\yolo\utils\tal.py", line 215, in make_anchors
    _, _, h, w = feats[i].shape
ValueError: not enough values to unpack (expected 4, got 3)

### Environment

Ultralytics YOLOv8.0.40  Python-3.7.9 torch-1.10.0+cu113 CUDA:0 (NVIDIA GeForce RTX 3060, 12287MiB)
win10

### Minimal Reproducible Example

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### LINKED ISSUE #1472: Model modification running on Android
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

I am referring to this project to modify the model conversion, but after the version update changes do not seem to work, in Android can not detect any items, modified is nn/modules.py,line182 and line404, is there any way to modify the run in github.com/FeiGeChuanShu/ncnn-android-yolov8.git
url: https://medium.com/@gary.tsai.advantest
image
image
image
Screenshot_2023-03-18-11-35-24-944_com tencent yolov8ncnn

### Additional

_No response_

### LINKED ISSUE #3412: Why is export to ncnn not supported out of the box?
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

I see that everyone is following some magic woodu steps when exporting to ncnnn. It basically includes some obscure ultralitics code modification in a couple of places. 
It is described here 
- https://medium.com/@gary.tsai.advantest/top-tutorials-for-deploying-custom-yolov8-on-android-%EF%B8%8F-dd6746afc1e6. #3379 
- https://github.com/FeiGeChuanShu/ncnn-android-yolov8/issues/8
- https://github.com/ultralytics/ultralytics/issues/726

Wouldn't it be better to have it integrated and what would result in an option to have truly performant deployment of an awesome yolov8 model?

### Use case

Deployment on mobile and embedded systems where ncnn works way faster.

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by glenn-jocher**
This PR adds official support for Ultralytics YOLOv8 NCNN export! You can export with CLI:
```
yolo export model=yolov8n.pt format=ncnn
```

or Python:
```python
from ultralytics import YOLO

# Create a model
model = YOLO('yolov8n.pt')

# Export the model to NCNN with arguments
model.export(format='ncnn', half=True, imgsz=640)
```

Output is a `yolov8n_ncnn_model/` directory containing `model.bin`, `model.param` and `metadata.yaml`, along with extra PNNX files. For details see https://github.com/pnnx/pnnx

### Resolves NCNN export issues:

- https://github.com/ultralytics/ultralytics/issues/726
- https://github.com/ultralytics/ultralytics/issues/1048
- https://github.com/ultralytics/ultralytics/issues/1472
- https://github.com/ultralytics/ultralytics/issues/3412

### Summary
🆕📝🛠️

This pull request adds support for exporting YOLOv8 models to NCNN format, a lightweight inference framework for mobile devices. It updates the documentation, the AutoBackend class, the Exporter class, and the benchmarks.py module to handle the new format. It also improves the download and unzip functionality of the `ultralytics/yolo/utils/downloads.py` module and increments the version number of the `ultralytics` package.

> _`ultralytics` grows_
> _NCNN export for YOLO_
> _Winter of mobile_

### Walkthrough
*  Increment the version number of the `ultralytics` package to 8.0.129 for NCNN export feature ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-b6202fa6738a34b56894dce00b24b8a4e4d7f4b1cbf1b04db6860f6b0f9635ceL3-R3))
*  Add NCNN as a new export format for YOLOv8 models in the `ultralytics.nn.autobackend` and `ultralytics.yolo.engine.exporter` modules ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L82-R83), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9R256-R257), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdR19), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdL90-R94), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdL156-R160), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdL234-R238), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdR261-R262), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdR404-R454))
*  Update the export formats tables in the documentation files `docs/modes/export.md`, `docs/tasks/classify.md`, `docs/tasks/detect.md`, `docs/tasks/pose.md`, and `docs/tasks/segment.md` to include NCNN and its properties ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-152ed106e8ed56d94526c0c8fcdc1e50bffb2ace88ffed252030d7f6771c1d37L4-R4), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-152ed106e8ed56d94526c0c8fcdc1e50bffb2ace88ffed252030d7f6771c1d37R87), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-a1a4bd3ddfbcef91068c9a46f93c16283474fb8bae9aed652e5999df7fb12abcL179-L177), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-597c0ff446990af3bc46d0ec8bf12cd047c250472b8155ba60aa2dbc6eaec6f3L170-L168), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-315c549028b862e841c5597869bc1b00ccc48aa4494bc2adb459bc87ad6a3d7aL184-L182), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-6c5aa10a7e1f72b933f0873902a94468bd6cc633d9f5ada357bf50f7266807c3L184-L182))
*  Copy the `docs/modes/val.md` file to the `docs/modes/export.md` file as a template for the export mode documentation and remove the redundant export formats table from the latter ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-74b90ccc22a7bc2090af95f3501c89ffe7b4c02228118951b3d32191d01a49ecL9-R9), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-74b90ccc22a7bc2090af95f3501c89ffe7b4c02228118951b3d32191d01a49ecL19-R17), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-74b90ccc22a7bc2090af95f3501c89ffe7b4c02228118951b3d32191d01a49ecL49-R46), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-74b90ccc22a7bc2090af95f3501c89ffe7b4c02228118951b3d32191d01a49ecL73-L91))
*  Import the `shutil` module and the `ROOT` and `get_github_assets` functions in the `ultralytics.yolo.engine.exporter` module to use them for NCNN export ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdR54), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-89bbf0a641e1fc4302b73181ac7fccc773b5213720cae9b5cae8aa2393c982fdL65-R70))
*  Change the TF.js inference from not supported to not currently supported in the `ultralytics.nn.autobackend` module to indicate a possible future implementation ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9L240-R241))
*  Raise a `NotImplementedError` for NCNN inference in the `ultralytics.nn.autobackend` and `ultralytics.yolo.utils.benchmarks` modules as it is not supported ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-2e3ad5da4ba57eb68a9b5aaddf0c40c784d888b7619ed337ce31dfea4f6380f9R256-R257), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-c038bb1fb2230068e97816bf63a783fbad880483c14f4517404d9fc3fe8e8510L101-R102))
*  Show the missing packages, the time elapsed, and the success message for AutoUpdate in the `ultralytics.yolo.utils.checks` module ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-d922fcb35a1250f2fd0185742d3da8123d5baffd4ec5ba7d313e2fca7b001305R11), [link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-d922fcb35a1250f2fd0185742d3da8123d5baffd4ec5ba7d313e2fca7b001305L238-R248))
*  Rename the `github_assets` function to `get_github_assets` and move it outside the `attempt_download_asset` function in the `ultralytics.yolo.utils.downloads` module to make it more reusable and modular ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-9bc1504ab4553f31c8ad4205083c67ac4fac833eea921bdea0c2dcee0bd57c03L204-R215))
*  Show the absolute path of the unzip directory in the `safe_download` function in the `ultralytics.yolo.utils.downloads` module for clarity ([link](https://github.com/ultralytics/ultralytics/pull/3529/files?diff=unified&w=0#diff-9bc1504ab4553f31c8ad4205083c67ac4fac833eea921bdea0c2dcee0bd57c03L192-R192))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to Ultralytics model export capabilities, including support for NCNN formats.

### 📊 Key Changes
- Addition of Tencent NCNN to model export keywords in documentation.
- Documentation refinements for clarity and removal of redundant information.
- Support for exporting models to the Tencent NCNN format.
- General code improvements and version bump from 8.0.128 to 8.0.129.

### 🎯 Purpose & Impact
- The inclusion of Tencent NCNN format 🚀 expands compatibility with more deployment environments, potentially improving the reach and usability of models.
- Documentation updates 📝 aim to simplify information, enhancing understanding for users.
- These updates have the potential to streamline development workflows, as well as open up new use cases for the models in mobile and edge devices due to NCNN's optimization for such platforms.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@sergiossm I think I've got the PR in a good place now, but I still need to examine the architecture updates proposed in https://github.com/FeiGeChuanShu/ncnn-android-yolov8

Is the repo above the best resource to start from?

**Comment by glenn-jocher** [comment]
@sergiossm @kalenmike ok I've worked on this a bit more, export is creating files now, not sure if they are fully correct yet, Sergio can you check? The output directory looks like this:

Reproduce with:
```bash
yolo export model=yolov8n.pt format=ncnn
```

Screenshot 2023-07-05 at 19 39 09

**Comment by glenn-jocher** [comment]
@FeiGeChuanShu here is our official NCNN support PR that includes architecture updates based on your ideas in https://github.com/FeiGeChuanShu/ncnn-android-yolov8. Can you please review the changes and let us know if they seem correct?

**Comment by glenn-jocher** [comment]
@sergiossm the model.param file can open successfully with Netron, i.e.:


Screenshot 2023-07-05 at 19 52 50

**Comment by glenn-jocher** [comment]
@sergiossm @kalenmike full NCNN support is likely a ways off. There are some extreme limitations here that I don't think we can overcome anytime soon without significant support from Tencent or the community. The YOLOv8 models that are created by https://github.com/FeiGeChuanShu/ncnn-android-yolov8 are missing the DFL portion of the model and will create reduced-accuracy boxes.

Pose is not supported, and Classify is not supported either. Segment models suffer from the same missing DFL problem above. Also I don't know how to run inference with NCNN models, so the exported models are unable to operate with the package for prediction and validation.

All other export formats are fine in all regards above, they export with all part of the architecture, support all 4 tasks and are compatible with ultralytics predict and val modes.

**Comment by nihui** [comment]
Because onnx often produces incompatibilities and glue operators, we have deprecated the onnx2ncnn tool and recommend using the pnnx tool to convert models from torchscript to pnnx/ncnn format

0. download pnnx binary from https://github.com/pnnx/pnnx/releases

1. export to torchscript
```shell
yolo mode=export model=yolov8n.pt format=torchscript
```

2. torchscript to pnnx and ncnn, this will produce converted model and inference scripts
```shell
./pnnx yolov8n.torchscript inputshape=[1,3,640,640]
```

3. check if pnnx and ncnn inference result is same
```python
import yolov8n_pnnx
yolov8n_pnnx.test_inference()

import yolov8n_ncnn
yolov8n_ncnn.test_inference()
```

pnnx is the representation of the pytorch model, using the top-level python operator definition, compatible with pytorch, and supports text editor viewing and editing and netron visualization.

more info at https://github.com/Tencent/ncnn/tree/master/tools/pnnx

**Comment by glenn-jocher** [comment]
@nihui thanks for the info, this is super helpful! I will try these steps.

**Comment by glenn-jocher** [comment]
@nihui it works!! The YOLOv8 export works correctly to NCNN using this method. I'll update this PR for this workflow, thank you.

**Comment by glenn-jocher** [comment]
@nihui ok I've updated the YOLOv8 export code to now use PNNX! I manually tested that all four YOLOv8 tasks were supported (Detect, Segment, Classify, Pose), and CI should now run more comprehensive tests. 

Is there any way to support PyTorch inference of NCNN models after export?

**Comment by yrik** [comment]
I will try to test it. What kind of inference code should work with it? In the approach of https://github.com/FeiGeChuanShu/ncnn-android-yolov8  they have replaced the split operation with slice (I assume it's also done here) and also removed the logic from the head part (it is then recreated in C++). How does it work here? Is everything out of the box or it needs some implementation of a custom code for the head part?

**Comment by glenn-jocher** [comment]
@yrik our approach for YOLOv8 export is different from the one used in the repository you mentioned (https://github.com/FeiGeChuanShu/ncnn-android-yolov8). We don't replace the split operation with slice, and we keep the logic intact in the head part.

When exporting to PNNX format, the YOLOv8 model is converted from PyTorch to PNNX using the pnnx tool. This tool handles the conversion automatically without the need for custom code implementation. The PNNX format represents the PyTorch model with the top-level Python operator definition, making it compatible with PyTorch.

Once the model is in PNNX format, you can use the PNNX model for inference. You can load the model with the PNNX inference script and pass inputs to it to get predictions.

Please let us know if you have any further questions or need more clarification.

**Comment by glenn-jocher** [comment]
@yrik @nihui once place I need some help is in getting NCNN models to run inference correctly. Most of the Ultralytics export formats can be used directly with the package just like a PyTorch model, i.e. you can export to ONNX, OpenVINO, CoreML, etc and then use that exported model to predict or val:

```python
from ultralytics import YOLO

# Load a PyTorch model
model = YOLO('yolov8n.pt')

# Export to ONNX
model.export(format='onnx')

# Load an ONNX model
model_onnx = YOLO('yolov8n.onnx')

# Run inference on a source with PyTorch and ONNX models
source = 'https://ultralytics.com/images/bus.jpg'
results = model.predict(source)
results_onnx = model_onnx.predit(source)  # equal to 'results' to numerical precision
```

We use this capability to validate all export formats to make sure they don't lose any accuracy. You can see this in my CI here:
https://github.com/ultralytics/ultralytics/actions/runs/5491624795/jobs/10008335998
Screenshot 2023-07-08 at 18 02 17

I need help constructing this for NCNN please. The relevant code for loading an NCNN model and running inference with it would be here in the Autobackend class. I put a placeholder for NCNN:

https://github.com/ultralytics/ultralytics/blob/d9db6cd42d8935e51d8f69639024c2b86c53d1a8/ultralytics/nn/autobackend.py#L41-L458

**Pull request merged**
