### PR TITLE
W&B updates

### PR DESCRIPTION
**Pull request by AyushExel**
I realized the previous PR already added all plots in a sort of a global variable so I've just used that. One advantage is that there is no more file name hardcoding.

### Summary
📈🎨🐛

Added a feature to log plots to wb in the `WandbCallback` class. Refactored some code to avoid duplication and enable passing a callback function to the `ap_per_class` function.

> _To log plots to wb with ease_
> _The `WandbCallback` class has a new piece_
> _A helper function `_log_plots`_
> _That does the job and avoids the knots_
> _And the `ap_per_class` function takes a callback as a lease_

### Walkthrough
*  Add `_log_plots` function to `wb.py` to log plots to Weights and Biases (wb) without duplication ([link](https://github.com/ultralytics/ultralytics/pull/2895/files?diff=unified&w=0#diff-1365dac64b857511656e6f9948f7c04022f4a9c14f7732ee26b4ca29d930f0a2L14-R21))
*  Call `_log_plots` function in `WandbCallback` class methods to log plots generated by trainer and validator at the end of each epoch ([link](https://github.com/ultralytics/ultralytics/pull/2895/files?diff=unified&w=0#diff-1365dac64b857511656e6f9948f7c04022f4a9c14f7732ee26b4ca29d930f0a2R30-R31), [link](https://github.com/ultralytics/ultralytics/pull/2895/files?diff=unified&w=0#diff-1365dac64b857511656e6f9948f7c04022f4a9c14f7732ee26b4ca29d930f0a2L32-R47))
*  Remove empty line at the beginning of `wb.py` to follow PEP8 style guide ([link](https://github.com/ultralytics/ultralytics/pull/2895/files?diff=unified&w=0#diff-1365dac64b857511656e6f9948f7c04022f4a9c14f7732ee26b4ca29d930f0a2L2))
*  Remove redundant code for logging train batch images in `WandbCallback` class ([link](https://github.com/ultralytics/ultralytics/pull/2895/files?diff=unified&w=0#diff-1365dac64b857511656e6f9948f7c04022f4a9c14f7732ee26b4ca29d930f0a2L32-R47))
*  Modify `ap_per_class` function in `metrics.py` to accept `on_plot` argument for executing a callback function after each plot ([link](https://github.com/ultralytics/ultralytics/pull/2895/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL711-R711))
*  Pass `_log_plots` function as `on_plot` argument in `WandbCallback` class to log plots generated by `ap_per_class` function to wb ([link](https://github.com/ultralytics/ultralytics/pull/2895/files?diff=unified&w=0#diff-344fba8bdb2b27681f38b96c45c1182aecb1f9bbcff5976dccce1ebd1d6f25dcL711-R711))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced logging of plots with deduplication in Weights & Biases integration for Ultralytics YOLO.

### 📊 Key Changes
- 🖼️ Introduced a `_log_plots` function to log image plots to Weights & Biases (W&B).
- 🚫 Added deduplication to avoid re-logging plots that haven't changed (based on timestamp).
- 🔀 Integrated `_log_plots` function within various stages of the training process (epoch end, train end).
- ✨ Altered `Validator` class to support passing an `on_plot` callback function for custom plot processing.

### 🎯 Purpose & Impact
- 🛠️ The purpose of these changes is to streamline the process of logging visual data during training, enabling better monitoring and analysis through W&B dashboards.
- 👀 Users will benefit from more informative and clutter-free logs, gaining the ability to track model performance over time with more relevant visual updates.
- 📈 The impact on end-users will likely be an improved experience with monitoring model training progress, leading to potential enhancements in model debugging and iteration processes.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@AyushExel oh this is really cool that we can use trainer.plots. But since this runs at epoch 0 and then at final epoch then some plots will be shown twice in W&B right? Is that ok?

**Comment by AyushExel** [comment]
@glenn-jocher here's the run from this branch https://wandb.ai/cayush/YOLOv8/runs/hpkp6f1x?workspace=user-cayush
Do you see a problem of double logging here?

**Comment by glenn-jocher** [comment]
@AyushExel looks good!

Do you think we could use the same groupings as the YOLOv5 logger though? It looks like we've got 3: Results, Labels, Mosaics

Screenshot 2023-05-30 at 20 02 57
Screenshot 2023-05-30 at 20 02 47

**Comment by glenn-jocher** [comment]
YOLOv5 run I was showing BTW:
https://wandb.ai/glenn-jocher/YOLOv5_v70_official

**Comment by glenn-jocher** [comment]
@AyushExel wait I just realized for multiple-models maybe the current setup works well? Here's main branch:

Screenshot 2023-05-30 at 20 38 32

**Comment by AyushExel** [comment]
@glenn-jocher yeah this PR will be like the main branch, just with more images under the media panel. 
See this project with 2 runs from this branch -> https://wandb.ai/cayush/YOLOv8/workspace?workspace=user-cayush

**Pull request merged**
