### PR TITLE
Fix model `names` docstring type to `dict`

### PR DESCRIPTION
**Pull request by yuefanhao**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR updates the handling of class names from using tuples to dictionaries in multiple functions and classes.

### 📊 Key Changes
- Changed the return type of `Model.names` from a list to a dictionary.
- Modified function parameters in `metrics.py` to expect dictionaries instead of tuples for class names.
- Updated `DetMetrics` class to use dictionaries for class names.

### 🎯 Purpose & Impact
- 🛠 **Purpose**: Enhances the clarity and efficiency of class name handling by associating class IDs directly with names.
- 🌟 **Impact**: 
  - **Developers**: Improved readability and easier access to class names via IDs.
  - 📈 **Users**: More intuitive access to object detection results, leading to a better user experience.

### CLA
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This PR updates various functions and methods to standardize the data type for class names from a list to a dictionary.

### 📊 Key Changes
- The `names` method in `model.py` now returns a dictionary instead of a list.
- Updated plot functions (`plot_pr_curve`, `plot_mc_curve`) and the DetMetrics class to use dictionaries for class names.
- Changes across `metrics.py` to ensure consistency with the new dictionary format for class names.

### 🎯 Purpose & Impact
- 🧩 **Consistency:** The change to dictionaries ensures a more structured and consistent approach to handling class names.
- 📈 **Enhanced Precision:** Precision-recall plotting and metric calculations become clearer and less prone to indexing errors.
- 🚀 **User Clarity:** Users now get a clear mapping of class indices to names, which is easier to understand and less ambiguous.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
@yuefanhao thank you for the PR! Please comment in a new message to sign the contributor license agreement with:

I have read the CLA Document and I sign the CLA

**Comment by yuefanhao** [comment]
I have read the CLA Document and I sign the CLA

**Comment by yuefanhao** [comment]
> @yuefanhao thank you for the PR! Please comment in a new message to sign the contributor license agreement with:
> 
> I have read the CLA Document and I sign the CLA

done

**Comment by glenn-jocher** [comment]
@yuefanhao PR merged! Thank you for your contributions :)

**Pull request merged**
