### PR TITLE
`ultralytics 8.1.21` Add YOLOv8-World-v2 models

### LINKED ISSUE #8579: Integrate YOLO-Worldv2 updates
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

[YOLO-World-v2 Update Notes](https://github.com/AILab-CVC/YOLO-World/blob/master/docs/updates.md)

- [ ] migrate weights
- [ ] add/modify configurations (as needed)
- [ ] update documentation
- [ ] ...

### Use case

_No response_

### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing enhanced YOLOv8-World models and improved export capabilities.

### 📊 Key Changes
- **CI Pipeline Update**: Added benchmarking for the new "YOLOv8s-Worldv2" model.
- **Documentation Enhancement**: Included new YOLOv8-Worldv2 models and updated metrics in the models' documentation.
- **Model Version Increment**: The Ultralytics library version is bumped from 8.1.20 to 8.1.21.
- **Export Functionality**: Expanded with warnings for YOLOWorld (original) model, which is not supported for export.
- **Model Saving Update**: Integrated metadata including versioning and documentation links in the saved model checkpoints.
- **YOLO Model Enhancements**: YOLOv8 initialization now detects and switches to YOLOWorld models based on the file name.
- **New YOLOWorldv2 models**: Introduced in various sizes (s, m, l, x) with updated configurations and detection heads.
- **Benchmark Utility Improvements**: Adjusted for compatibility with YOLOWorld models and export capabilities.
- **Downloads**: Added new pre-trained YOLOv8-Worldv2 model weights to the download list.

### 🎯 Purpose & Impact
- The addition of **YOLOv8-Worldv2** models aims to provide users with more advanced versions of pre-trained weights, offering better performance and export options.
- The **library version update** ensures users have the latest features and bug fixes.
- **Improved export warnings and capabilities** enhance model portability and deployment across different platforms, which is crucial for production environments.
- **Updated documentation** ensures users have accurate and up-to-date information about model performance and capabilities.
- **Metadata in saved models** helps in tracking model versions and related documentation, improving model management.
- The CI pipeline and benchmarking updates ensure that the models' performance is consistently tracked and that the models maintain a high standard of quality.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Laughing-q @Burhan-Q hey guys, not sure what naming convention to use here. Should we always just support the latest without a version number i.e. `yolov8x-world.pt`, or should be attempt to support multiple versions, i.e. `yolov8x-world-v2.pt`?

The versioned filename is probably more precise, but will create many more assets for us to track and maintain too.

**Comment by Burhan-Q** [comment]
I think for external models, unless is a _major_ difference/change, we should only keep the most recent or up-to-date version with the base-name. So for this one, since the changes didn't _seem_ to be too big, I think that `yolov8x-world.pt` makes sense to me.

**Comment by Laughing-q** [comment]
@glenn-jocher @Burhan-Q Hey guys, after some thinking I prefer to keep both two versions:
- From the official paper and the [update notes](https://github.com/AILab-CVC/YOLO-World/blob/master/docs/updates.md), actually v1 models got slightly better evaluation values on LVIS dataset. The only problem is that it's hard to export to other formats because of `I-PoolingAttention` module, so I figure there are users who want this version(that has better metrics but only pytorch available).
- The main difference between v1 and v2 is that v2 has chance to support exporting other formats(and I believe we'll support in near future). And if we simply replace the weights with v2 version then there's no way to identify v2 and old v1 weights, and once we support exporting v2, users who has downloaded v1 models are going to ask questions about why their weights can not be exported.
- As the topic of yolo-world is still hot I think, supporting both its v1 and v2 versions would have positive impact on traffic.

**Comment by glenn-jocher** [comment]
@Laughing-q ok got it. Then should we rename the first weights as v1 or leave them without a version number?

**Comment by glenn-jocher** [comment]
@Laughing-q also have you verified export functionality for v2? Should we green-checkmark the export column for the v2 models here?
Screenshot 2024-03-03 at 19 02 20

**Comment by glenn-jocher** [comment]
Export seems to work well for torchscript and ONNX 

```
(venv) glennjocher@Glenns-MacBook-Air-2 ultralytics % yolo export model=yolov8s-worldv2.pt
WARNING ⚠️ 'format' is missing. Using default 'format=torchscript'.
Ultralytics YOLOv8.1.20 🚀 Python-3.11.2 torch-2.2.0 CPU (Apple M2)
YOLOv8s-worldv2 summary (fused): 195 layers, 12749288 parameters, 0 gradients, 50.8 GFLOPs

PyTorch: starting from 'yolov8s-worldv2.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (24.7 MB)

TorchScript: starting export with torch 2.2.0...
TorchScript: export success ✅ 1.3s, saved as 'yolov8s-worldv2.torchscript' (49.3 MB)

Export complete (1.7s)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics
Predict:         yolo predict task=detect model=yolov8s-worldv2.torchscript imgsz=640  
Validate:        yolo val task=detect model=yolov8s-worldv2.torchscript imgsz=640 data=None  
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export
(venv) glennjocher@Glenns-MacBook-Air-2 ultralytics % yolo export model=yolov8s-worldv2.pt format=onnx
Ultralytics YOLOv8.1.20 🚀 Python-3.11.2 torch-2.2.0 CPU (Apple M2)
YOLOv8s-worldv2 summary (fused): 195 layers, 12749288 parameters, 0 gradients, 50.8 GFLOPs

PyTorch: starting from 'yolov8s-worldv2.pt' with input shape (1, 3, 640, 640) BCHW and output shape(s) (1, 84, 8400) (24.7 MB)

ONNX: starting export with onnx 1.15.0 opset 17...
ONNX: export success ✅ 0.9s, saved as 'yolov8s-worldv2.onnx' (49.9 MB)

Export complete (1.3s)
Results saved to /Users/glennjocher/PycharmProjects/ultralytics
Predict:         yolo predict task=detect model=yolov8s-worldv2.onnx imgsz=640  
Validate:        yolo val task=detect model=yolov8s-worldv2.onnx imgsz=640 data=None  
Visualize:       https://netron.app
💡 Learn more at https://docs.ultralytics.com/modes/export
(venv) glennjocher@Glenns-MacBook-Air-2 ultralytics % 

```

**Comment by glenn-jocher** [comment]
@Laughing-q I noticed the v2 models were saved using `dill`, could you re-save them after uninstalling `dill`? 

The way the `ultralytics` package works I think is it might use it when saving if it's available, but our official models should not require it as it not in our pyproject.toml
Screenshot 2024-03-03 at 19 51 03

**Comment by glenn-jocher** [comment]
@Laughing-q @Burhan-Q ok I've gotten export to work for a few formats, added World to benchmarks for the supported export formats, re-saved and re-uploaded all YOLO-World assets without `dill` usage (script below). I think this is all good now.

### Strip-`dill` script
```python
from pathlib import Path

# Ensure you have the Ultralytics YOLO package installed
from ultralytics import YOLO  # This might need adjustment based on the actual package structure


def resave_models(model_names, source_dir, target_dir):
    """Load and resave YOLOv8 models using the Ultralytics package."""
    for model_name in model_names:
        model_path = source_dir / model_name
        print(f"Loading model from {model_path}")

        # Load model
        model = YOLO(model_path)
        model.half()

        # Define new save path
        save_path = target_dir / model_name

        # Save model using model.save()
        print(f"Resaving model to {save_path}")
        model.save(save_path, use_dill=False)

        print(f"Model {model_name} resaved successfully.")


if __name__ == "__main__":
    # Define source and target directories
    source_dir = Path(".")
    target_dir = Path("./resaved_models")
    target_dir.mkdir(parents=True, exist_ok=True)  # Ensure target directory exists

    # List of model names to process
    model_names = [f"yolov8{size}-world{version}.pt" for size in "smlx" for version in ("", "v2")]

    # Run the resave process
    resave_models(model_names, source_dir, target_dir)

```

**Comment by glenn-jocher** [comment]
The benchmarks look like this:
Screenshot 2024-03-03 at 21 28 03

**Comment by glenn-jocher** [comment]
@Laughing-q PR merged! Awesome work on this!!

**Pull request merged**
