### PR TITLE
Add basic trackers: IOU, Centroid

### PR DESCRIPTION
**Pull request by mlurbur**
Hi all, I added two classic, basic trackers: IOU and centroid. ByteTrack is a very fancy IOU tracker, this adds a bare-bones IOU tracker without Kalman filters. The centroid tracker is another basic tracker that matches detections based on the euclidean distance between centroids of bounding boxes. These trackers are significantly faster than BoT-SORT and ByteTrack, particularly useful in situations where compute is limited (ie edge devices).

- Added a centroid tracker. Performs basic multi-object tracking by matching detections based on euclidean distance of bounding box centroids. 
- Centroid tracker is 15% faster than ByteTrack and 30% faster than BoT-SORT as tested locally
- Added IOU tracker. Performs basic multi-object tracking by matching detections based on IOU. (Note: ByteTrack and many other newer trackers use IOU in conjunction with Kalman filters and other post processing). This is a much simpler and faster tracker.
- IOU tracker is 13% faster than ByteTrack and 28% faster than BoT-SORT

NOTE: HOTA scores for all ultralytics trackers would be a great addition as serve as a nice verification of proper implementation

_I have read the CLA Document and I hereby sign the CLA_

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Support for new tracking algorithms and various minor code improvements.

### 📊 Key Changes
- **Expanded Tracker Types**: Added support for `ioutrack` and `centroidtrack` in the tracker configuration files (`botsort.yaml`, `bytetrack.yaml`).
- **New Tracker Files**: Introduced `iou_tracker.py` and `centroid_tracker.py` containing implementations for IOU and Centroid tracking methods.
- **Updated Imports**: Minor adjustments and clean-ups of import statements across multiple files.
- **Initialization Fixes**: Corrected some inconsistencies and updated tracking initialization processes.

### 🎯 Purpose & Impact
- **Enhanced Tracking Options**: Users now have more flexibility with new tracking algorithms (`ioutrack` and `centroidtrack`), enhancing object tracking capabilities.
- **Improved Code Quality**: Minor fixes and import adjustments ensure better maintainability and readability of the code.
- **User Flexibility**: The added tracker types provide more options for users to tweak and experiment with different tracking methods, hence improving model performance and personalization.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@mlurbur hi there! 👋 That's great news! 🎉

Adding basic trackers like the IOU and centroid trackers can indeed enhance the flexibility of our object tracking capabilities, especially for scenarios where resource efficiency is crucial. They serve as valuable alternatives for users working with edge devices or in compute-constrained environments.

Your contributions toward a simpler, faster IOU tracker, and the introduction of a centroid tracker based on the euclidean distance of bounding box centroids are very much appreciated. They broaden the toolkit available to our community, allowing for quicker deployments and potentially better performance in certain contexts.

Regarding HOTA scores, that's a fantastic suggestion! Having metrics like these would indeed help in comparing and verifying the implementation's effectiveness. We'll consider incorporating these into our future updates.

For those interested in trying out the new trackers, here's a quick snippet to get started:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model.track(source='video.mp4', tracker='centroidtrack')  # Or use 'ioutrack' for the IOU tracker
```

Thank you for signing the CLA and for your valuable contribution! Looking forward to seeing how these additions improve our tracking capabilities. 😊

Keep the ideas and contributions coming!

_Made with ❤️ by the Ultralytics Team_

**Comment by mlurbur** [comment]
> @mlurbur hi there! 👋 That's great news! 🎉
> 
> Adding basic trackers like the IOU and centroid trackers can indeed enhance the flexibility of our object tracking capabilities, especially for scenarios where resource efficiency is crucial. They serve as valuable alternatives for users working with edge devices or in compute-constrained environments.
> 
> Your contributions toward a simpler, faster IOU tracker, and the introduction of a centroid tracker based on the euclidean distance of bounding box centroids are very much appreciated. They broaden the toolkit available to our community, allowing for quicker deployments and potentially better performance in certain contexts.
> 
> Regarding HOTA scores, that's a fantastic suggestion! Having metrics like these would indeed help in comparing and verifying the implementation's effectiveness. We'll consider incorporating these into our future updates.
> 
> For those interested in trying out the new trackers, here's a quick snippet to get started:
> 
> ```python
> from ultralytics import YOLO
> 
> model = YOLO('yolov8n.pt')
> results = model.track(source='video.mp4', tracker='centroidtrack')  # Or use 'ioutrack' for the IOU tracker
> ```
> 
> Thank you for signing the CLA and for your valuable contribution! Looking forward to seeing how these additions improve our tracking capabilities. 😊
> 
> Keep the ideas and contributions coming!
> 
> _Made with ❤️ by the Ultralytics Team_
A note on that LLM generated code ;)

The `tracker` argument expects a `.yaml` file. So the code snippet should be:
```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model.track(source='video.mp4', tracker='centroidtrack.yaml')  # Or use 'ioutrack.yaml' for the IOU tracker
```

**Comment by glenn-jocher** [comment]
Hey @mlurbur! 😄

Absolutely thrilled with your contributions on IOU and centroid trackers - they're a boon for efficiency-driven scenarios! 💥 Your work enriches our toolbox, making Ultralytics YOLO more versatile and streamlined for various use cases.

And yes, you're spot right about the `tracker` argument needing a `.yaml` file. Thanks for pointing that out! Here’s the correct snippet for folks eager to dive in:

```python
from ultralytics import YOLO

model = YOLO('yolov8n.pt')
results = model.track(source='video.mp4', tracker='centroidtrack.yaml')  # Or 'ioutrack.yaml' for the IOU tracker
```

Your insights on HOTA scores as a validation measure are on our radar for future enhancements. 🌟

Thanks a ton for your engagement and contributions. Can't wait to see where your innovations take us next!

**Comment by mlurbur** [comment]
closing

**Comment by glenn-jocher** [comment]
Hi there!

Thank you for your message. It seems like you might be experiencing an issue. To help us assist you better, could you please provide a minimum reproducible code example? This will allow us to replicate the issue on our end and investigate a solution. You can find guidelines on how to create a minimum reproducible example here: [Minimum Reproducible Example](https://docs.ultralytics.com/help/minimum_reproducible_example).

Additionally, please ensure that you are using the latest versions of `torch` and `ultralytics`. Sometimes, bugs are fixed in newer releases, and updating your packages might resolve the issue. You can upgrade your packages using the following commands:

```bash
pip install --upgrade torch
pip install --upgrade ultralytics
```

Once you have the reproducible code and have verified that you are on the latest versions, please share the details with us, and we'll be happy to assist you further.

Looking forward to your response! 😊

**Pull request closed without merging**
