### PR TITLE
Add guide on how to use the Coral Usb Accelerator with Raspberry Pi's

### PR DESCRIPTION
**Pull request by Skillnoob**
This PR add a guide that explains in a detailed manner on how to use a Coral USB Accelerator with Raspberry Pi's.
The current existing guide by Coral is outdated and their current builds of libedgetpu do not work with modern python versions and tflite-runtime versions. This guide explains how to use custom and updated libedgetpu builds with new versions of the tflite-runtime.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Guide for enhancing Raspberry Pi ML performance with Coral Edge TPU and Ultralytics YOLOv8.

### 📊 Key Changes
- 📝 New documentation on using Coral Edge TPU with Raspberry Pi for advanced ML inference.
- 🛠️ Installation guidelines for an updated Edge TPU runtime compatible with the latest TensorFlow Lite.
- 🔄 Instructions on exporting Ultralytics PyTorch models to Edge TPU-compatible formats.
- 🚀 Running predictions on Raspberry Pi using the Edge TPU-optimized models.

### 🎯 Purpose & Impact
- 🎯 **Purpose**: Provide a reliable, updated guide to leverage Coral Edge TPU on Raspberry Pi for improved machine learning performance.
- 🏃‍♂️ **Impact for Users**: 
  - Users will experience significantly faster ML inference on Raspberry Pi devices, making it viable for more real-time or near-real-time applications.
  - Provides a pathway for utilizing Ultralytics models on low-power, portable devices with accelerated hardware.
  - Offers solutions to Google's abandonment of the Coral project by providing alternative instructions and resources.

### CODE REVIEW

**Comment by Skillnoob** [comment]
I have read the CLA Document and I hereby sign the CLA

**Comment by glenn-jocher** [comment]
@Skillnoob super cool! Thank you for the docs page!

recheck

**Comment by Burhan-Q** [comment]
@glenn-jocher FYI, I added some edits to the doc that @Skillnoob contributed to better fit with the Ultralytics Documentation formatting. Also, @Skillnoob is a long time Ultralytics Discord member and holds the top-spot in helping other members of the community 🚀

**Comment by Skillnoob** [comment]
recheck

**Comment by Skillnoob** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Skillnoob** [comment]
@glenn-jocher the CLA check now also passes. somehow didn't before. but now everything is ready to merge.

**Comment by glenn-jocher** [comment]
Great to hear that, @Skillnoob! Thanks for signing the CLA and for your contribution. We'll review the PR shortly. 🚀

**Comment by Burhan-Q** [comment]
@lakshanthad by chance do you have a Coral TPU and could try this out?

**Comment by glenn-jocher** [comment]
@lakshanthad yes if you could review this PR that would be great. 

2 additions are required as well:

- Add to this category's index.md, i.e. integrations/index.md
- Add to mkdocs.yml or this page will be completely ignored during Docs build.

Additionally content that relates to a specific company belongs in `integrations` rather than guides. Once there is an `integration` page for it then you're free to create additional guides but since this is the first Coral Edge TPU page it must be moved from guides to integrations.

**Comment by Burhan-Q** [comment]
I went ahead and relocated the file to `integrations`, added the entry to `integrations/index.md`, and added the entry to `mkdocs.yml` so we're all set there (pending all CI passes)

**Comment by glenn-jocher** [comment]
@Skillnoob @Burhan-Q PR merged, thanks guys!!

**Pull request merged**
