### PR TITLE
`ultralytics 8.1.31` NCNN and CLIP updates

### PR DESCRIPTION
**Pull request by glenn-jocher**
## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced configuration validation, version bump, and streamlined codebase for better usability and performance.

### 📊 Key Changes
- 📝 Added documentation for `check_cfg` in configuration reference.
- 🆙 Updated package version to 8.1.31.
- 🔧 Improved configuration settings by using sets for mode and task definitions, enhancing code clarity and lookup efficiency.
- 🛠 Introduced `check_cfg` function to strengthen type and value validation across configurations, improving error handling and user feedback.
- 💡 Modified several list definitions to sets for configuration keys, optimizing for performance and consistency.
- 🎉 Enhanced `tojson` and introduced `summary` methods in results processing for more versatile data handling.
- 🧹 Refined the neural network backend interaction, especially with NCNN, for cleaner and more efficient code execution.
- 🌍 Updated `WorldModel` initialization to include a CLIP model placeholder, preparing for future integrations.
- 🚀 General codebase improvements, including changing some data structure definitions to sets for efficiency and clarity.

### 🎯 Purpose & Impact
- 🚀 **Efficiency and Clarity:** These changes aim to make the code more efficient, particularly in configuration handling and data structure operations, resulting in faster execution times and clearer code.
- 🔍 **Improved Validation:** Enhanced configuration validation helps prevent common errors earlier, improving user experience by ensuring configurations are correctly set before runtime.
- 📈 **Version Update:** The new version (8.1.31) indicates incremental improvements and fixes, reassuring users of ongoing support and development.
- 🌐 **Future-Proofing:** Preparing for CLIP model integrations and streamlining JSON data handling are forward-looking steps to incorporate more advanced features and usability enhancements in future updates.

These updates strive to make the Ultralytics framework more robust, user-friendly, and capable of handling more complex tasks seamlessly.

### CODE REVIEW

**Comment by Burhan-Q** [comment]
@glenn-jocher just checking, would anything done in #8967 help with what you're looking to do with `ultralytics.engine.results.Results`? Been working with the author on getting that in a good place and it looks like it could be related. Just wanted to make sure you were aware in case you hadn't seen that yet, as it covers all tasks to generate `dict` and `pandas.DataFrame` results, which _could_ also modify the `tojson` method (hadn't changed it yet as I wasn't certain if it would impact anything else).

**Comment by glenn-jocher** [comment]
@Burhan-Q oh yeah let me explain this one (haven't seen the other PR). This PR separates out the Results summary from the JSON creation into two separate functions, nothing else. 

This resolves an issue in my upcoming inference API where the JSON was being turned into a dict to combine with other metadata before converting again into a JSON, so this PR coupled with the assistants update with eliminate this `Dict > JSON > Dict` roundtrip when using `.tojson()` before to now using `.summary()` to output the `> Dict` by itself.

Also includes some NCNN improvements I profiled while on the plane.

**Comment by glenn-jocher** [comment]
@Burhan-Q more clearly from the assistants PR:

Screenshot 2024-03-22 at 18 30 04

**Comment by Burhan-Q** [comment]
Understood. In the other PR there's a new `Results.asdict()` which is where I thought there could be some overlap

**Comment by glenn-jocher** [comment]
@Burhan-Q hmm ok, I'll wait and take a look at that one later today first then!

**Comment by glenn-jocher** [comment]
@Burhan-Q merging this to not delay further, and also because this PR introduces only very minimal results changes compared to #8967 which proposes extensive changes that will need review and tests etc.

**Comment by glenn-jocher** [comment]
@Burhan-Q also I get a bit worried when I see a PR with only additions and no deletions (i.e. +300 -0), as this is a much simpler (for users) but less maintainable (for Ultralytics) route for users to attempt with PRs and can lead to creep in the codebase and more pain for us in the long run. 

This PR is a good example, with +77 -60, which generally indicates a better understanding of the codebase and more effort put in to modify areas as appropriate instead of only adding new code (and sometimes ignoring existing code).

**Comment by Burhan-Q** [comment]
Understood. I did add tests into the other PR, but maybe went overboard. I didn't remove anything as I wasn't 100/% if anything relied on the structure of the `.tojson()` method formatting vs what I added. I did also include the changes added with 8.1.31 into the other PR without any conflicts. Certainly appreciate there could be lots to clean up or optimize in #8967

**Pull request merged**
