### PR TITLE
New SimpleClass and Stream Warning

### LINKED ISSUE #1624: _reach_out_prediction_result
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

Hi, In the #1483 issue @glenn-jocher shared validation results. Thanks to this I finally reach out the precision and recall results for validation. Could you please share this results for training and prediction. Thank you

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Laughing-q**
@AyushExel @glenn-jocher 
add warning when user are trying to predict steams/videos and the case that image folder contains over 1000 images.
probably this is the best way for now to resuce the `OOM` issues before we figure out a smooth solution for Results.
pic-full-230325-1738-57

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhancements to object detection and prediction flow, with improved debugging and stream handling.

### 📊 Key Changes
- Added a `mode` attribute to `LoadTensor` to identify data as images.
- Introduced a `STREAM_WARNING` alert for large or long-running inference streams.
- Enhanced the `__call__` method in `BasePredictor` to handle streaming better.
- Simplified `Results` and related classes (`Boxes`, `Masks`) by inheriting from a new `SimpleClass`.
- Improved human-readable string representations in utility classes for easier debugging.
- Metrics classes (`Metric`, `DetMetrics`, `SegmentMetrics`, `ClassifyMetrics`) now inherit from `SimpleClass`.

### 🎯 Purpose & Impact
- The `mode` attribute helps in recognizing the nature of data during loading, improving data handling. 🗂️
- `STREAM_WARNING` serves to alert users of potential memory issues when processing large or prolonged data streams, aiding in preventing crashes. ⚠️
- Streamlined prediction calls facilitate more efficient streaming inference, ensuring smoother processing and better resource management. 🚀
- Refactoring result-oriented classes with `SimpleClass` leads to a more unified codebase, allows for cleaner string representations, and clearer error messages, improving the developer's experience and reducing bugs. 🛠️
- Enhanced utility classes contribute to overall code tidiness and reduce potential user confusion when interpreting debug messages and errors. 🧐

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher hey, saw you removed `time.sleep(5)`. I thought it would be better to leave the warning for a while so users would notice, since I think many of the users usually just ignore the warning.😂 And this warning is kind of important or they'll encounter OOM.

**Comment by glenn-jocher** [comment]
@Laughing-q yes I removed the wait time, we probably don't want to introduce intentional delays in the commands. I think if we want it more prominent we could insert a newline before and after? 

Maybe we could also wrap the predict(stream=False) command in a Try: Except and Except CUDA OOM and memory errors with special handling to repeat the warning.

We can also monitor RAM usage with psutil and also start creating warnings if we want to get extra fancy.

**Comment by AyushExel** [comment]
What do you guys think about introducing a different color text for warning. It'll be hard to miss that way

**Comment by glenn-jocher** [comment]
@AyushExel we could do that. A big issue is that we need to consolidate logger.warning customizations in one place. Right now we have a messy system, i.e. the current default warning message is `WARNING ⚠️ ...` but this is duplicated everywhere. We need to use the correct logger way to introduce this only once in the logger config, and then remove it everywhere else, and then any change we make in that one place will be applied to all warnings. 

I tried this before, but couldn't manage to figure it out. Can you take a look?

```python
logger.WARNING('WARNING ⚠️ SegmentationModel has not supported augment inference yet!')
```

https://github.com/ultralytics/ultralytics/blob/ef03e6732aecc91134275a3f5a62f2e0f82ab4bf/ultralytics/yolo/utils/__init__.py#L148-L155

**Comment by glenn-jocher** [comment]
@Laughing-q @AyushExel I've created a new SimpleClass in this PR with improved error handling and debugging utils that I'm not using to create all Results and Metrics classes.

This is much better and more centralized than what I had before, and allowed me to remove many `__repr__()`, `__str__()` and `__getattr__()` methods from the Results and Metrics classes that I'd been defining individually.

```python
class SimpleClass:
    """
    Ultralytics SimpleClass is a base class providing helpful string representation, error reporting, and attribute
    access methods for easier debugging and usage.
    """

    def __str__(self):
        """Return a human-readable string representation of the object."""
        attr = []
        for a in dir(self):
            v = getattr(self, a)
            if not callable(v) and not a.startswith('__'):
                if isinstance(v, SimpleClass):
                    # Display only the module and class name for subclasses
                    s = f'{a}: {v.__module__}.{v.__class__.__name__} object'
                else:
                    s = f"{a}: {repr(v)}"
                attr.append(s)
        return f'{self.__module__}.{self.__class__.__name__} object with attributes:\n\n' + '\n'.join(attr)

    def __repr__(self):
        """Return a machine-readable string representation of the object."""
        return self.__str__()

    def __getattr__(self, attr):
        """Custom attribute access error message with helpful information."""
        name = self.__class__.__name__
        raise AttributeError(f"'{name}' object has no attribute '{attr}'. See valid attributes below.\n{self.__doc__}")
```

Usage for this is below, should help everyone understand what these instances contain i.e.:

`print(results[0])` or just `results[0]`

```ultralytics.yolo.engine.results.Results object with attributes:
_keys: ('boxes', 'masks', 'probs')
boxes: ultralytics.yolo.engine.results.Boxes object
keys: ['boxes']
masks: None
names: {0: 'person', 1: 'bicycle', 2: 'car', 3: 'motorcycle', 4: 'airplane', 5: 'bus', 6: 'train', 7: 'truck', 8: 'boat', 9: 'traffic light', 10: 'fire hydrant', 11: 'stop sign', 12: 'parking meter', 13: 'bench', 14: 'bird', 15: 'cat', 16: 'dog', 17: 'horse', 18: 'sheep', 19: 'cow', 20: 'elephant', 21: 'bear', 22: 'zebra', 23: 'giraffe', 24: 'backpack', 25: 'umbrella', 26: 'handbag', 27: 'tie', 28: 'suitcase', 29: 'frisbee', 30: 'skis', 31: 'snowboard', 32: 'sports ball', 33: 'kite', 34: 'baseball bat', 35: 'baseball glove', 36: 'skateboard', 37: 'surfboard', 38: 'tennis racket', 39: 'bottle', 40: 'wine glass', 41: 'cup', 42: 'fork', 43: 'knife', 44: 'spoon', 45: 'bowl', 46: 'banana', 47: 'apple', 48: 'sandwich', 49: 'orange', 50: 'broccoli', 51: 'carrot', 52: 'hot dog', 53: 'pizza', 54: 'donut', 55: 'cake', 56: 'chair', 57: 'couch', 58: 'potted plant', 59: 'bed', 60: 'dining table', 61: 'toilet', 62: 'tv', 63: 'laptop', 64: 'mouse', 65: 'remote', 66: 'keyboard', 67: 'cell phone', 68: 'microwave', 69: 'oven', 70: 'toaster', 71: 'sink', 72: 'refrigerator', 73: 'book', 74: 'clock', 75: 'vase', 76: 'scissors', 77: 'teddy bear', 78: 'hair drier', 79: 'toothbrush'}
orig_img: array([[[119, 146, 172],
        [121, 148, 174],
        [122, 152, 177],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],
       [[120, 147, 173],
        [122, 149, 175],
        [123, 153, 178],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],
       [[123, 150, 176],
        [124, 151, 177],
        [125, 155, 180],
        ...,
        [161, 171, 188],
        [160, 170, 187],
        [160, 170, 187]],
       ...,
       [[183, 182, 186],
        [179, 178, 182],
        [180, 179, 183],
        ...,
        [121, 111, 117],
        [113, 103, 109],
        [115, 105, 111]],
       [[165, 164, 168],
        [173, 172, 176],
        [187, 186, 190],
        ...,
        [102,  92,  98],
        [101,  91,  97],
        [103,  93,  99]],
       [[123, 122, 126],
        [145, 144, 148],
        [176, 175, 179],
        ...,
        [ 95,  85,  91],
        [ 96,  86,  92],
        [ 98,  88,  94]]], dtype=uint8)
orig_shape: (1080, 810)
path: '/Users/glennjocher/PycharmProjects/ultralytics/ultralytics/assets/bus.jpg'
probs: None
speed: {'preprocess': 0.6489753723144531, 'inference': 58.18009376525879, 'postprocess': 0.4279613494873047}
```

**Comment by Laughing-q** [comment]
> @Laughing-q yes I removed the wait time, we probably don't want to introduce intentional delays in the commands. I think if we want it more prominent we could insert a newline before and after? 
> 
> Maybe we could also wrap the predict(stream=False) command in a Try: Except and Except CUDA OOM and memory errors with special handling to repeat the warning.
> 
> We can also monitor RAM usage with psutil and also start creating warnings if we want to get extra fancy.

@glenn-jocher yeah but the warning will be immediately swamped by the following predict logs so users won't notice that msg.

I was also thinking about using a try...except to catch the OOM cases and throw a warning but sometimes OOM also could happen even with stream=True when users do not have enough memory(cuda or cpu) to run inference at the first place, then the try...except does not work as we expect and might mislead users.
And yes we also can catch the increasing of memory and throw the warning but sometimes memory also increases in other cases, not just stream=False.
I prefer to make this workflow simpler(just simply throw a warning when users run video/streams/folder without `stream=True`) until we figure out a smooth solution for result.
what do you think?

**Comment by glenn-jocher** [comment]
@Laughing-q It's ok, don't worry, most users will notice the warning, there's not many multi-line warnings right now.

Also remember some users will want to run `streams=False` anyways, and they won't like waiting extra time for inference to start, especially if they are running inference often.

I think the only time delay in the repo right now is 500ms when showing images with show=True, but this delay makes sense as users have complained before that the images show too quickly.

**Pull request merged**
