### PR TITLE
Update LICENSE to AGPL-3.0

### PR DESCRIPTION
**Pull request by glenn-jocher**
This pull request updates the license of the YOLOv8 project from GNU General Public License v3.0 (GPL-3.0) to [GNU Affero General Public License v3.0](https://choosealicense.com/licenses/agpl-3.0/) (AGPL-3.0).

We at Ultralytics have decided to make this change in order to better protect our intellectual property and ensure that any larger work that incorporates YOLOv8 and is provided as a service over a network will also be open-sourced under AGPL-3.0.

AGPL-3.0 is very similar to GPL-3.0, but with an additional clause to address the use of software over a network. This change ensures that if someone uses YOLOv8 as part of a larger work and provides that larger work as a service over a network (e.g., through a web application or API), they must make the source code of the larger work, including any YOLOv8 modifications, available to users of the service under the AGPL-3.0 license.

This update includes the following changes:
- Replace the `LICENSE` file with the AGPL-3.0 license text
- Update the license reference in the `README.md` file
- Update the license headers in source code files

We believe that this change will promote a more collaborative environment and help drive further innovation within the YOLOv8 community.

### Summary
🔄🌐➕

The `LICENSE` file was changed to use the GNU Affero General Public License, which covers software that runs on a network server. This license requires that users who interact with the software through a network have access to the source code.

> _Sing, O Muse, of the noble code that changed its sacred license_
> _From the GNU that guards the freedom of the users and the hackers_
> _To the GNU that adds more terms for those who run it on a server_
> _And requires them to share the source with all who interact remotely_

### Walkthrough
*  Switch the license from GNU General Public License to GNU Affero General Public License, which has additional terms for network server software ([link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L1-R2), [link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L10-R18), [link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L75-R63), [link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L552-R578), [link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L638-R636), [link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L645-R661))
*  Simplify and reorganize the section on the responsibilities of the users who distribute or modify the software ([link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L29-R55))
*  Update the notice on how to provide the source code for network software and remove the paragraph on the incompatibility with proprietary programs ([link](https://github.com/ultralytics/ultralytics/pull/2031/files?diff=unified&w=0#diff-c693279643b8cd5d248172d9c22cb7cf4ed163a3c98c8a3f69c2717edd3eacb7L645-R661))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
PR updates license details and workflow names in the Ultralytics repository.

### 📊 Key Changes
- License updated from **GPL-3.0** to **AGPL-3.0** in multiple files.
- Workflow names in `.github/workflows/` files have been modified.

### 🎯 Purpose & Impact
- 📜 The license change to AGPL-3.0 strengthens the copyleft provision, particularly for network server software, ensuring any modified version running on a network server must make its source code available to users.
- 🔧 Modifying workflow names likely aims to improve clarity and management of automated processes in the repository.

🔒 The change in license will impact users who run modified versions of the software on network servers, as they will now be required to comply with the stricter AGPL-3.0 requirements.

### CODE REVIEW

**Comment by bottledmind** [comment]
Makes it virtually unusable in a lot of cases

**Comment by glenn-jocher** [comment]
@adrianosantospb thank you for bringing up your concerns about the recent license change to the AGPL-3.0 for YOLOv8. While the change does have the added requirement that any larger work incorporating YOLOv8 and provided as a network service must also be released under the AGPL-3.0 license, this is a standard requirement of AGPL-3.0 and is in line with the goal of promoting a more collaborative and open development environment.

Regarding your question, no, these modifications will not restrict you from engaging in activities related to the usage of YOLOv8. You can still train your models, create your services, and market them as before. Only if you create a larger work that incorporates YOLOv8 and provides it as a service over a network will you have to release the source code of that larger work under the AGPL-3.0 license. Additionally, you can still use the API for your services as you did before.

Thank you for your understanding, and please let us know if you have any further questions or concerns. We appreciate your interest in YOLOv8 and support of the open-source community.

**Comment by v3ss0n** [comment]
great question @andressrodrl  . @glenn-jocher  That is the biggest concern i have now over using YOLOv8 with AGPL license . AGPL License is avoided by almost all workplaces , from slolo devs , small startups to Large companies - because it is very vague when it says `Larger Work` . Thats why all corporate lawyers ban it.  It is more of a legal trap even if you say "Its OK to use on commercial applications that doesn't just outright modify YOLO Sources code" you also have to mean it in LICENSE file. Please check with your lawers about it - because by short : by default AGPL itself , if someone use it , the whole service need to be opensourced , the lib is modify or not.

**Comment by glenn-jocher** [comment]
Hello @v3ss0n,

Thank you for your insightful question and for raising your concerns regarding the AGPL-3.0 license.

The AGPL-3.0 license indeed has specific requirements that can be challenging to navigate, particularly for commercial applications. To clarify, under AGPL-3.0, if you use YOLOv8 as part of a larger work that is provided as a service over a network, you must release the source code of that larger work under the same AGPL-3.0 license. This includes any modifications or additions you make to the YOLOv8 code.

However, if you are using YOLOv8 as a library within your project without modifying its source code, and your project does not provide YOLOv8 as a service over a network, you may not be required to open-source your entire project. It is always best to consult with a legal professional to understand how the AGPL-3.0 license applies to your specific use case.

To address your request for clarity, we are working on providing comprehensive guidelines that outline what can and cannot be done with YOLOv8 under the AGPL-3.0 license. This document will help users understand the implications of the license and ensure compliance.

In the meantime, if you have any specific scenarios or further questions, please feel free to share them here. We are committed to supporting our community and ensuring that everyone can use YOLOv8 effectively while adhering to the license terms.

Thank you for your understanding and support.

**Comment by kosukekurimoto** [comment]
Hello @glenn-jocher ,
Could you please tell me who needs to have access to the following deliverables in my use case?
- Source code of the Front API
- Source code of the Backend API
- Weights of the custom model in the Backend API

[Front API]
This is an API that provides endpoints to customers. It offers image processing functionalities. As part of the image processing, it calls the Backend API (server-to-server).

[Backend API]
This is an object detection API using yolov8. The model fine-tuned with the original dataset is stored here. This endpoint is not public and customers do not have direct access to execute it.

Thanks

**Comment by glenn-jocher** [comment]
Hello @kosukekurimoto,

Thank you for your question. Under the AGPL-3.0 license, the requirements for sharing source code depend on how the software is used and accessed. Here’s a breakdown based on your use case:

1. **Source Code of the Front API**:
   - If the Front API provides image processing functionalities to customers and calls the Backend API, you need to make the source code of the Front API available to your customers if it incorporates or interacts with the AGPL-3.0 licensed YOLOv8 code.

2. **Source Code of the Backend API**:
   - Since the Backend API uses YOLOv8 and is not directly accessed by customers, you are not required to share its source code with customers. However, if the Backend API is provided as a service over a network, you must make its source code available to anyone who interacts with it over the network.

3. **Weights of the Custom Model in the Backend API**:
   - The weights of the custom model are considered part of the software. If the Backend API is provided as a service over a network, you must make the weights available under the AGPL-3.0 license to those who interact with the service.

In summary, you need to provide access to the source code of any part of your system that interacts with the AGPL-3.0 licensed YOLOv8 code and is provided as a service over a network. This includes making the source code available to users who interact with the service, not just internal or server-to-server interactions.

For more detailed guidance, please consult with a legal professional to ensure compliance with the AGPL-3.0 license in your specific scenario.

**Comment by kosukekurimoto** [comment]
Hi @glenn-jocher,

Thank you for the detailed explanation.

I have a question about the case where the yolov8 code is not embedded in the Front API, as shown in the diagram below.

Customer -> HTTP -> Front API -> HTTP -> Backend API (yolov8)

In this case, the Front API does not include the yolov8 code. Do we still need to make the Front API code available to the customer?

It’s akin to creating a website for trending word rankings using Twitter’s API.

If we need to release the source code even in this pattern, it seems like it would make commercial use virtually impossible.

**Comment by glenn-jocher** [comment]
Hi @kosukekurimoto,

Thank you for your question and for providing a clear diagram of your setup.

In your scenario, where the Front API does not embed the YOLOv8 code and merely acts as an intermediary between the customer and the Backend API, you are not required to release the source code of the Front API under the AGPL-3.0 license. The key factor is that the Front API does not incorporate or modify the YOLOv8 code directly.

To draw a parallel with your example, using Twitter's API to create a website does not require you to open-source your website's code, as long as you are not embedding or modifying Twitter's code.

However, the Backend API, which uses YOLOv8, must comply with the AGPL-3.0 license. This means you need to make the source code of the Backend API, including any modifications to YOLOv8, available to users who interact with it over the network.

I hope this clarifies your concerns. If you have any further questions, feel free to ask! 😊

**Comment by kosukekurimoto** [comment]
@glenn-jocher 

Thank you for your detailed explanation and for providing reassurance; your response truly helped ease my concerns.

I do, however, have one more question. In our scenario, customers do not directly access the Backend API. Instead, customers interact solely with the Front API, which utilizes the Backend API as part of its image processing functionality. The interaction flow is as follows:
Customer -> HTTP -> Front API (image editing features) -> HTTP -> Backend API (YOLOv8).

In this case, who would be the appropriate party to whom we should provide access to the source code and fine-tuned model used in the Backend API?

Thank you again for your assistance! 😊

Best regards,
Kosuke

**Comment by glenn-jocher** [comment]
Hi @kosukekurimoto,

Thank you for your kind words and for providing additional details about your setup.

In your scenario, since customers interact solely with the Front API and do not directly access the Backend API, you are not required to provide the source code or fine-tuned model of the Backend API to your customers. The AGPL-3.0 license requires you to provide the source code to users who interact with the software over a network. Since the Backend API is not directly exposed to your customers, they do not fall under this requirement.

However, if you were to provide access to the Backend API directly to any third party, you would need to make the source code and fine-tuned model available to them under the AGPL-3.0 license.

I hope this clarifies your question. If you have any further concerns, feel free to ask! 😊

**Comment by v3ss0n** [comment]
Here is my Setup 
`django_api` : It is For frontned and Database and there is zero `import` of Yolov8. But it is Showing  Object counts returned by the `vision_api`

`vision_api` :  is just runs that yolov8 segment on self trained model and insert the results to database. It never modifies yolov8 source code : it imports the `ultralytics` . 

Then , am i suppose to opensource `vision_api` ?

**Comment by pderrenger** [comment]
Hi @v3ss0n,

Given your setup, since the `vision_api` is not exposed to third parties and is only used internally within your intranet, you are not required to open-source the `vision_api` under the AGPL-3.0 license. The key factor is that the API is not provided as a service over a network to external users.

**Comment by glenn-jocher** [comment]
@kosukekurimoto @v3ss0n to clarify, **any larger work**, regardless of network usage or not, that utilizes an AGPL-3.0 licensed work like Ultralytics must also be open-sourced under AGPL-3.0 to comply with the license terms. This is summarized well in GitHub's own license header at https://github.com/ultralytics/ultralytics/blob/main/LICENSE.

Screenshot 2024-07-14 at 04 18 31

If your organization would prefer not to open-source your larger solutions that use YOLO models, this is what we have the Enterprise License available for at https://ultralytics.com/license. Over a thousand companies have requested Enterprise Licenses, so don't hesitate to apply for one if your business use case legally requires it.

**Pull request merged**
