### PR TITLE
`ultralytics 8.0.143` add `Model` base class

### LINKED ISSUE #3739: 'args.yaml' file missed parameter(s) while using 'rtdetr-l.yaml' for training
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar bug report.

### YOLOv8 Component

Training

### Bug

Hello ultralytics, 

firstly, thank you very much for updating the **RT-DETR** in available YOLOv8 models.

Sadly, I met a problem while using **rtdetr-l.yaml** for training.
Training itself has no problem, it can run successfully. But in its generated folder (e.g. 'train' folder), the file **args.yaml** probably missed 1 (or more) parameter(s).
One example is here: 
Screenshot from 2023-07-14 13-05-30
The third line is info for used model, and I believe it should show **_rtdetr-l.yaml_** or the **path leads to it**.
In my case, it's _**null**_, so I think this may be a mistake.
And probably because here doesn't have the correct value, in the **corresponding project run** on **wandb**, it also missed this part.

I used the same code on **docs for RT-DETR**, section **Python API** ([https://docs.ultralytics.com/models/rtdetr/?h=rt#python-api](url)).

Other than the **Python API** demo code, do I need to write something extra to assign some specific parameters as some fixed value/string? Or is it because some part responsible for recording args is not running?

Hope to hear from you soon!
Tianyu

### Environment

- YOLO: Ultralytics YOLOv8.0.134 🚀 Python-3.8.16 torch-2.0.0+cu117 CUDA:0 (NVIDIA GeForce RTX 3090 Ti, 24245MiB)
- OS: Ubuntu 20.04
- Python: 3.8.16

### Minimal Reproducible Example
```
from ultralytics import RTDETR
import wandb


model = RTDETR("rtdetr-l.yaml")
model.info()

train_data = 'blended_floor.yaml' # Set training data path
model.train(data=train_data)   # train


wandb.init(
    # set the wandb project where this run will be logged
    project="YOLOv8-rtdetr",
    
    # track hyperparameters and run metadata
    config={
    "architecture": "RT-DETR",
    "dataset": "dataset_2019", # 'blended_floor.yaml'
    }
)

wandb.finish()
```
### Additional

_No response_

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by Laughing-q**
### Summary
🔄🚀💬

Refactored the Model class and its subclasses to support multiple task types and dynamic loading of model components. Updated the imports and interfaces of the RTDETR, SAM, FastSAM, and YOLO models to inherit from the Model class. Added support for prompts in the SAM/FastSAM predictor.

> _`Model` class evolves_
> _Supports multiple tasks and prompts_
> _Winter of refactoring_

### Walkthrough
*  Rename YOLO class to Model and make it the base class for all models in ultralytics ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L18-R20), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-9def6b664eba2171d902af8018c9ab7945baa3c72c103c5c95330aa092b6bf43L2-R28), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-9ce365012deaf8956910db15edf201452e8f6593724e464964068f1e9c20e06aL5-R7), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-9ce365012deaf8956910db15edf201452e8f6593724e464964068f1e9c20e06aL22-R24), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-4873ecb0574ef04a3aeebe3174bc48a5bdc9087759aa5d3f0a20b0645926035fR7), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-4873ecb0574ef04a3aeebe3174bc48a5bdc9087759aa5d3f0a20b0645926035fL13-R37), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-d85395b639979a65be5ffda459dd071688c28222abea583cf25df1780d0e0d07R1-R38))
*  Remove import of YOLO from `ultralytics/engine/model.py` and `ultralytics/__init__.py` and add import of YOLO from `ultralytics/models/yolo/model.py` to `ultralytics/models/__init__.py` and `ultralytics/models/yolo/__init__.py` ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-b6202fa6738a34b56894dce00b24b8a4e4d7f4b1cbf1b04db6860f6b0f9635ceL5-R6), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L9-R10), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-4754c26aff77c4b3c424413ec8507c7d57053252d665b867f0aca19cc081dfdcL3-R5), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-7bb0bb8a018eb6885d35c69879091dc25b89a04046f5b3ce71e82ddb1c6f65b7L4-R6))
*  Add task argument to Model class __init__ method and pass it to parent class __init__ method ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R77), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L84))
*  Add model argument to Model class _new method and use it to assign model attribute ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L125-R112), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R119), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L137-R126))
*  Add predictor argument to Model class predict method and use it to assign predictor attribute ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L220-R209), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R217), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L248-R241))
*  Add prompts argument to Model class predict method and use it to pass additional inputs for SAM/FastSAM models ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R229-R230), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R247-R249), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-abae5c0cfe4087dc193f98a5d67d7c726ac769ae8a58b3abda232a7657c69edeR31-R32), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-abae5c0cfe4087dc193f98a5d67d7c726ac769ae8a58b3abda232a7657c69edeR97-R100), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-abae5c0cfe4087dc193f98a5d67d7c726ac769ae8a58b3abda232a7657c69edeR357-R360))
*  Add validator argument to Model class val method and use it to assign validator attribute ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L280-R276), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R282), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L298-R300))
*  Add trainer argument to Model class train method and use it to assign trainer attribute ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L347-R350), [link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00L371-R371))
*  Add smart_load, __getattr__, and task_map methods to Model class to dynamically load classes based on task type, raise error for invalid attribute, and provide class mapping, respectively ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R440-R462))
*  Add task_map property to SAM class to provide class mapping for SAM model ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-4873ecb0574ef04a3aeebe3174bc48a5bdc9087759aa5d3f0a20b0645926035fR47-R50))
*  Add import of inspect to `ultralytics/engine/model.py` to get function name in smart_load method ([link](https://github.com/ultralytics/ultralytics/pull/3934/files?diff=unified&w=0#diff-cb649199881b55cff01fb5d1a216adf39d007be25e815089340a5b4f074cba00R4))

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Refactoring to introduce a unified `Model` class and update documentation.

### 📊 Key Changes
- Replaced the `YOLO` class with a new `Model` class that serves as a base class for all models.
- Created a separate document for YOLO model class and updated the model's reference in the documentation.
- Updated the `__init__.py` files to include the new `YOLO` reference where needed.
- Simplified various model files (`FastSAM`, `NAS`, `RTDETR`, `SAM`) to use the new `Model` base class.
- Introduced properties and methods such as `task_map` and `smart_load` to facilitate the new class structure.

### 🎯 Purpose & Impact
- ⚙️ The refactor streamlines the model architecture, making it easier to maintain, extend, and comprehend.
- 📑 Improved documentation structure helps users and developers locate model-specific details with greater ease.
- 🔄 These updates may affect how models are imported and used in existing scripts, so users should verify compatibility with the new structure.

### CODE REVIEW

**Comment by Laughing-q** [comment]
@glenn-jocher ok I've added our basemodel here which named `Model` in engine.py since we already have a `BaseModel` calss for model definition in task.py. 
This PR removes many duplication across different models and currently the behavior of all the models are consistent, like we used to have predicted images saved with SAM/predict api by default but other models would not save it by default with python interface, now all the models won't save predicted images including SAM.

In this PR the workflow of adding a new model interface would be implementing trainer/validator/predictor for the model and add these to `task_map` in a new model class, like following YOLO model:
```python
class YOLO(Model):
    """
    YOLO (You Only Look Once) object detection model.
    """

    @property
    def task_map(self):
        """Map head to model, trainer, validator, and predictor classes"""
        return {
            'classify': {
                'model': ClassificationModel,
                'trainer': yolo.classify.ClassificationTrainer,
                'validator': yolo.classify.ClassificationValidator,
                'predictor': yolo.classify.ClassificationPredictor, },
            'detect': {
                'model': DetectionModel,
                'trainer': yolo.detect.DetectionTrainer,
                'validator': yolo.detect.DetectionValidator,
                'predictor': yolo.detect.DetectionPredictor, },
            'segment': {
                'model': SegmentationModel,
                'trainer': yolo.segment.SegmentationTrainer,
                'validator': yolo.segment.SegmentationValidator,
                'predictor': yolo.segment.SegmentationPredictor, },
            'pose': {
                'model': PoseModel,
                'trainer': yolo.pose.PoseTrainer,
                'validator': yolo.pose.PoseValidator,
                'predictor': yolo.pose.PosePredictor, }, }
```
the format to add task_map is: 
```python
{"task": {"model":.., "trainer":..., "validator":..., "predictor":...}}
```
I also implemented a `smart_load` method to manage these `trainer/validator/predictor`, which would raise an error says it doesn't support the mode for the task if users miss some keys, here's an example:
For FastSAM we only support `predict` and `val` mode for `segment` task hence we only add `predictor` and `validator` in `task_map`:
```python
    @property
    def task_map(self):
        return {'segment': {'predictor': FastSAMPredictor, 'validator': FastSAMValidator}}
```
if someone uses FaseSAM for training then it'll raise an error like this:
pic-230725-1102-34

**Comment by Laughing-q** [comment]
@glenn-jocher oh and I also added extra args `predictor/trainer/validator` for `model.predict/train/val` respectively for better custom experience. 
Let's say If some users want to do some custom design for their trainer, current way is to inherit from our BaseTrainer or probably DetectionTrainer then launch training by `custom_trainer.train()`, like this:
```python
from ultralytics.engine.trainer import BaseTrainer
class CustomTrainer(BaseTrainer):
    def __init__():
        ...
# launch training
CustomTrainer.train()
```
This way custom trainer would only be launched by `trainer.train()`, which is not consistent with our recommended way:
```python
# create model first and launch training
model = YOLO()
model.train()
```
And actually we have some checks and settings in `model.train()` function before calling `trainer.train()` to make trainer work more smoothly, which these parts are lacked if users launch their custom trainer. The same is true for custom validator and predictor.

So I added these args then users can launch their custom modules by:
```python
from ultralytics.engine.trainer import BaseTrainer
class CustomTrainer(BaseTrainer):
    def __init__():
        ...

model = YOLO()
model.train(data=..., trainer=CustomTrainer)
model.predict(data=..., trainer=CustomPredictor)
model.val(data=..., trainer=CustomValidator)
```

**Comment by glenn-jocher** [comment]
@Laughing-q this looks awesome! I'm going to merge all the smaller PRs and push a new pip update and then I'll work on reviewing this PR for the next pip update ok?

**Comment by Laughing-q** [comment]
@glenn-jocher yeah sounds good. :)

**Comment by glenn-jocher** [comment]
@Laughing-q this looks good! I don't think it needs any changes, but are you sure that we need the trainer/validator/predictor argument here in https://github.com/ultralytics/ultralytics/pull/3934#issuecomment-1648987270?

I think we want everyone to use the model.train() usage, but you're saying that it's not possible without updating the base code?

**Comment by Laughing-q** [comment]
@glenn-jocher It's not required but it would be more convenient with trainer/validator/predictor argument when users create their own custom trainer/validator/predictor.
Or the way they launch custom trainer/validator/predictor would only be:
```python
custom_trainer.train()
custom_validator()
custom_predictor()
```
and it's not as smooth as they launch our yolo model like:
```python
model = YOLO()
model.train()
model.val()
model.predict()
```

**Comment by Laughing-q** [comment]
@glenn-jocher It's not required but it would be more convenient with trainer/validator/predictor argument when users create their own custom trainer/validator/predictor.
Or the way they launch custom trainer/validator/predictor would only be:
```python
custom_trainer.train()
custom_validator()
custom_predictor()
```
and it's not as smooth as they launch our yolo model like:
```python
model = YOLO()
model.train()
model.val()
model.predict()
```

EDIT: I think we should keep these if we want to encourage everybody to use the model.train() usage.

**Comment by glenn-jocher** [comment]
@Laughing-q ok got it!

**Comment by glenn-jocher** [comment]
@Laughing-q PR merged as 8.0.143! Nice work on this, this removes a lot of redundant code and should make it easier in the future to create new models and support new tasks.

**Pull request merged**
