### PR TITLE
Display Val images per class

### LINKED ISSUE #12149: Better evaluation results show.
### Search before asking

- [X] I have searched the YOLOv8 [issues](https://github.com/ultralytics/ultralytics/issues) and found no similar feature requests.

### Description

Is it more reasonable to print the number of images for each category in the current evaluation script results, rather than uniformly printing the total number of evaluation images?

### Use case

This is the current result.
image

This is the modified result.
image

### Additional

I am not sure if this optimization is beneficial.

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

### PR DESCRIPTION
**Pull request by sunmooncode**
Add a new parameter for users to choose from in the detected val script. The function of this parameter is to control the output method of images in the val result.

For more details please refer to [here](https://github.com/ultralytics/ultralytics/issues/12149)!

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced tracking of object detection, pose estimation, and segmentation metrics in YOLO models. 📈

### 📊 Key Changes
- **CI Configuration**: Removed a redundant line setting `slow` dependencies, ensuring dependencies are now conditionally installed based on the event that triggers the workflow. 🧹
- **Detection, Pose, and Segmentation**: Introduced tracking of unique images alongside class and prediction statistics to improve metric accuracy and reporting. 🖼️
- **Metric Reporting**: Enhanced metric reporting to include per-image statistics in addition to per-class statistics for deeper insights. This involves changes to logging and the calculation of `nt_per_class` and the newly added `nt_per_image`. 📊

### 🎯 Purpose & Impact
- **Better Dependency Management**: The update in CI configuration tidies up the dependency installation process, making the CI runs more efficient and less prone to errors. 🛠️
- **Improved Accuracy & Insights**: Adding `nt_per_image` allows developers and users to gain a clearer understanding of model performance on a per-image basis. This can lead to better-targeted improvements and more detailed performance analysis. 🔍
- **Enhanced User Awareness**: By including additional logging details, users can now receive a more granular breakdown of how the model is performing across different classes and images, enriching the user experience and aiding in debugging and model optimization. 🚀

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@sunmooncode hey great, this looks like a nice improvement. Once change is that can you please remove the argument so we use this change by default? Thanks!

**Comment by sunmooncode** [comment]
I deleted the optional parameter and used it by default.

**Comment by glenn-jocher** [comment]
That sounds great, @sunmooncode! Making the feature default simplifies the usage while providing enhanced insights consistently. Thanks for your contribution! 🚀 If anything else needs to be adjusted, feel free to let us know.

**Comment by glenn-jocher** [comment]
@sunmooncode can you please delete the `detail_per_class: False # (bool) detailed per-class results` argument entirely and we'll use this as the new default? Thank you!

**Comment by sunmooncode** [comment]
@glenn-jocher Of course. Please wait for me for a moment.

**Comment by glenn-jocher** [comment]
Sure thing, @sunmooncode! Take your time. 😊

**Pull request merged**
