### PR TITLE
Dwell time Analyzer

### PR DESCRIPTION
**Pull request by Muhammad-237**
I have read the CLA Document and I sign the CLA

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Added a new feature: **Dwell Time Analyzer** for precise monitoring of object movements and interactions within defined zones in video streams. 🚶‍♂️🕒  

---

### 📊 Key Changes  
- Introduced a **DwellTimeAnalyzer** class in the `solutions` module.  
   - Tracks **dwell time**: How long objects stay in specific zones.  
   - Records **zone transitions**: Sequence of zones visited by each object.  
   - **Advanced analytics**:  
     - Funnel analysis for multi-stage zone interactions.  
     - Average dwell time computations.  
   - **Flexible configurations**: Custom FPS, object-class filtering, and zone setup.  
- Added interactive zone selection for defining analysis areas in videos.  
- Enhanced visualization: Displays dwell times, object counts, and funnel insights directly on video frames.  

---

### 🎯 Purpose & Impact  
- **Purpose**: To improve object detection capabilities by analyzing zone-specific behaviors. Useful in scenarios like retail analytics, facility monitoring, and event tracking. 🎥📈  
- **Impact**:  
   - Enables users to monitor **entry/exit patterns**, **dwell durations**, and **conversion rates** through predefined zones.  
   - Provides visual feedback and insights on frame overlays, simplifying complex movement tracking.  
   - Facilitates better decision-making with detailed analytics, like average dwell times and zone visitation frequency. 💡

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Muhammad-237, thank you for submitting your `Dwell Time Analyzer` 🚀 PR to the [ultralytics/ultralytics repository](https://github.com/ultralytics/ultralytics)! To ensure a smooth review process and integration of your awesome contribution, please review the following checklist:

- ✅ **Define a Purpose**: You've provided a detailed summary of your `Dwell Time Analyzer` 🎯. If possible, link to any related [issues](https://github.com/ultralytics/ultralytics/issues) or larger discussions for context.
- ✅ **Synchronize with Source**: Ensure your branch is up-to-date with the `main` branch. If needed, click 'Update branch' or run `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify that all [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks pass. Address any failing checks and resolve conflicts if applicable.
- ✅ **Update Documentation**: Check that your new feature is reflected in the [Ultralytics documentation](https://docs.ultralytics.com). Documenting the use cases, implementation, and examples for the `DwellTimeAnalyzer` is key to improving user adoption! 📝
- ✅ **Add Tests**: Include or update any applicable tests to validate your feature or changes. Ensure that all tests pass to maintain project reliability. ⚙️
- ✅ **Sign the CLA**: You've already noted that you’ve signed the [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/)—thank you! 🙌
- ✅ **Minimize Changes**: Aim to keep your changes concise and focused on the new functionality you've introduced for efficient reviewing and merging.

For more detailed guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing).  

Don’t hesitate to ask questions or provide additional clarifications if needed. This is an automated response to guide you through the process, but rest assured that an Ultralytics engineer will review your PR and provide feedback soon. Thank you for taking the time to contribute and enhance the Ultralytics ecosystem! 🚀🌟

**Comment by Muhammad-237** [comment]
I have read the CLA Document and I sign the CLA.

**Comment by Muhammad-237** [comment]
I have read the CLA Document and I sign the CLA

**Comment by RizwanMunawar** [comment]
Hi @Muhammad-237,  

Thank you for your PR! I'll review it soon and provide feedback. Appreciate your contribution!

**Comment by Muhammad-237** [comment]
Thanks for your response, i am looking forward for your feedback.

**Comment by glenn-jocher** [comment]
@Muhammad-237 thank you for your patience! Your contribution will be reviewed soon, and feedback will be provided promptly.

**Comment by Muhammad-237** [comment]
@glenn-jocher thanks for your response i am looking forward to your response as i am very curious to launch this new feature

**Comment by Muhammad-237** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Muhammad-237** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Muhammad-237** [comment]
I have read the CLA Document and I sign the CLA

**Comment by Muhammad-237** [comment]
@RizwanMunawar as for now i have signed the CLA then why CLA Assistant is failing.

**Comment by RizwanMunawar** [comment]
@Muhammad-237 Hi, I’m closing this PR for now. Could you please create a new branch by forking the latest Ultralytics repository and then open a fresh PR? The Ultralytics package was compromised last week, so there might be some files in your current PR with outdated or affected details. 

Thanks, and I look forward to your updated PR!

**Pull request closed without merging**
