### PR TITLE
`ultralytics 8.3.39` fix classification validation loss scaling

### LINKED ISSUE #16428: yolo8  differences in the values ​​of the validation and training loss functions
### Search before asking

- [X] I have searched the Ultralytics YOLO [issues](https://github.com/ultralytics/ultralytics/issues) and [discussions](https://github.com/ultralytics/ultralytics/discussions) and found no similar questions.

### Question

When training YOLOv8-cls (small and nano), I noticed a significant difference between validation and training loss values. Training loss decreased from 0.21 to 0.027, while validation loss only slightly improved from 0.34 to 0.31. Initially, I thought it might be underfitting, but validation accuracy improved from 0.98 to 0.995, and the test results showed good performance.

I compared YOLOv8-cls with other models like ResNet-18 and generally did not see such large discrepancies in losses. It’s commonly believed that large gaps between training and validation losses can indicate underfitting.

In issue #4684, different scales and the lack of normalization were mentioned, but I don’t fully understand the cause. Is there an additional factor affecting validation loss calculations that’s not present in training?
results

### Additional

_No response_

### PR DESCRIPTION
**Pull request by Y-T-G**
Closes https://github.com/ultralytics/ultralytics/issues/16428

Also brought up in https://community.ultralytics.com/t/loss-function-in-classification-yolov8/544/4

I don't know if there's a better way to check we're in validation state vs. prediction.

**Without PR**

**With PR**

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary  
Updated version to 8.3.39 with refinements to classification prediction and neural network behavior.

### 📊 Key Changes  
- 🔢 **Version Increment**: Updated the library version from `8.3.38` to `8.3.39`.  
- 🧠 **Classification Prediction**: Adjusted the `postprocess` logic to explicitly apply `softmax` only to class probabilities in predictions when processing.  
- 🤖 **Neural Network Head**: Removed the `softmax` operation during inference for the `head` module, outputting raw logits instead.  

### 🎯 Purpose & Impact  
- 🏋️‍♂️ **Improved Flexibility**: The prediction outputs now offer more modular behavior by decoupling `softmax` from certain pipeline steps, letting users choose how to handle model outputs.  
- 🚀 **Performance Optimizations**: Removing `softmax` in the forward pass can help in certain downstream tasks where raw logits are required (e.g., advanced loss calculations or post-processing).  
- 🔒 **Backward Compatibility**: Changes are minor and should seamlessly integrate with existing workflows.  

These updates fine-tune the library for power users while maintaining ease of use. 🌟

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @Y-T-G, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! To ensure a seamless integration of your work, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). It’s great that you linked issue `#16428` and referenced a community discussion—this helps provide context for your changes. Please ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: If your changes modify any functionality, please ensure the relevant [documentation](https://docs.ultralytics.com) is up to date.
- ✅ **Add Tests**: Include or update tests to cover your changes. If applicable, confirm all tests are passing successfully to ensure your adjustments are robust and reliable.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Check Implementation Logic**: Reading through your changes, your new logic for evaluating `requires_grad` seems thoughtful. However, as you pointed out in your description, there may be alternative methods to distinguish validation mode. If you have additional questions or ideas about other approaches, feel free to share them!
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you're introducing behavior related to the validation state and `softmax`, consider providing a small, **minimum reproducible example (MRE)** that demonstrates how this change improves loss scaling or fixes the issue. This can aid in validating the change and ensure alignment between the codebase and the expected results. 😊 

Don’t hesitate to leave a comment if you have any other questions or need further clarification. An Ultralytics engineer will also review your PR soon. Thank you for contributing to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@Y-T-G oh these are batch-size invariant on purpose to make it easy to compare train vs val losses inside a single training run, and then of course between training runs at different batch sizes.

**Comment by glenn-jocher** [comment]
In general validation loss should be smaller than val loss due to lack of augmentations in the val loader.

**Comment by Y-T-G** [comment]
@glenn-jocher The issue in this particular case is validation loss is calculated on softmaxed output (since `self.training` is  False in when the model is in evaluation mode during validation):
https://github.com/ultralytics/ultralytics/blob/c1554935e6568ec4b27fc0c25d7e36bb32aaa24c/ultralytics/nn/modules/head.py#L299

So it's always higher than training loss as in the first image:



If you fix that, then it results in a loss lower than training loss as in the second image:

**Comment by glenn-jocher** [comment]
@Y-T-G OH it's a softmax issue, got it, I thought it was a batch-size issue. Then yes we should fix this!

**Comment by glenn-jocher** [comment]
@Y-T-G PR merged, nice work!

**Comment by rromanchuk** [comment]
@Y-T-G  Something in yolo11-cls has regressed between 8.3.31 to current release when exporting to coreml, both as coremltools6 nueralnetwork or mlprogram with coremltools8.  `VNClassificationObservation` label is correct but confidence values are nonsensical.

I'm looking through diffs and this looks suspicious....

**Comment by rromanchuk** [comment]
I'm guessing this line would be directly impacted https://github.com/ultralytics/ultralytics/blob/main/ultralytics/engine/exporter.py#L712

Screenshot 2024-12-06 at 12 08 24 PM

**Comment by Y-T-G** [comment]
@rromanchuk 

You would need to apply softmax manually if you're using it outside of Ultralytics

**Comment by Y-T-G** [comment]
@rromanchuk Are you using it in Ultralytics or in some external environment?

**Comment by Y-T-G** [comment]
If it's external, then you would need to apply softmax to the confidences in the post-processing.

**Comment by Y-T-G** [comment]
Not applying softmax doesn't affect the ordinal relationship. As in the best class would still be best. It just means the outputs are raw logits and not softmaxed to sum to 1.

**Comment by rromanchuk** [comment]
@Y-T-G right, so when you open your export, hit the preview tab, run a prediction you're going to get nonsensical results, or if you display a VNClassificationObservation confidence. I get it's just not normalized in the expectated domain but not immediately obvious 

imho, `yolo export model=yolo11n-cls.pt format=mlmodel`  or coreml mlprogram if you fix the missing `ct_model.user_defined_metadata["com.apple.coreml.model.preview.type"] = "imageClassifier"` **should not** not display predictions with 697% confidence "Out of the Box" 

The export task goes through the effort to setup platform specific requirements for the most ubiquitous coreml tasks, ie `IOSDetectModel`, `ct.ClassifierConfig`, `ct.ImageType`  so it has not been my expectation I'd be manipulating layers back in coremltools. For example, you would not be able to demonstrate a "Hello World" petrained classification model without A. skipping the export step completely and explaining `torch.jit.trace` and configuring input/output  manually.  B. override Xcode auto generated classes `MLFeatureProvider` 

ironically though, that softmaxing was also preventing `builder.make_updatable` via `neural_network.NeuralNetworkBuilder` without  a bunch of layer manipulation.    TLDR: coremltools sucks 👼

**Comment by Laughing-q** [comment]
@Y-T-G wait I think this PR did break the classify export right? now it's not including the `softmax` layer in the exported formats I think.

**Pull request merged**
