### PR TITLE
Update pyproject.toml to include lxml

### PR DESCRIPTION
**Pull request by MatthewNoyce**
When testing the pr from #16267 (thank you @ambitious-octopus for the advice) I ran into a problem with a completely fresh install that the `lxml` package isnt installed with the ultralytics package which then was installed automatically but needed me to rerun the script. It might be worth adding `lxml` to `pyproject.toml` to prevent this from needing to be done every time that someone new runs the method.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Added a new dependency for improved XML handling.

### 📊 Key Changes
- Introduced `lxml>=4.8.0` to the project dependencies in `pyproject.toml`.

### 🎯 Purpose & Impact
- **Enhanced XML Processing**: Enables more robust and efficient XML result handling.
- **User Benefit**: Users requiring XML functionality will experience improved performance and reliability.

### CODE REVIEW

**Comment by UltralyticsAssistant** [comment]
👋 Hello @MatthewNoyce, thank you for submitting an `ultralytics/ultralytics` 🚀 PR! This is an automated response, and an Ultralytics engineer will assist soon. To help us integrate your contribution smoothly, please review the following checklist:

- ✅ **Define a Purpose**: Clearly explain the purpose of your fix or feature in your PR description, and link to any [relevant issues](https://github.com/ultralytics/ultralytics/issues). Ensure your commit messages are clear, concise, and adhere to the project's conventions.
- ✅ **Synchronize with Source**: Confirm your PR is synchronized with the `ultralytics/ultralytics` `main` branch. If it's behind, update it by clicking the 'Update branch' button or by running `git pull` and `git merge main` locally.
- ✅ **Ensure CI Checks Pass**: Verify all Ultralytics [Continuous Integration (CI)](https://docs.ultralytics.com/help/CI/) checks are passing. If any checks fail, please address the issues.
- ✅ **Update Documentation**: Update the relevant [documentation](https://docs.ultralytics.com) for any new or modified features.
- ✅ **Add Tests**: If applicable, include or update tests to cover your changes, and confirm that all tests are passing.
- ✅ **Sign the CLA**: Please ensure you have signed our [Contributor License Agreement](https://docs.ultralytics.com/help/CLA/) if this is your first Ultralytics PR by writing "I have read the CLA Document and I sign the CLA" in a new message.
- ✅ **Minimize Changes**: Limit your changes to the **minimum** necessary for your bug fix or feature addition. _"It is not daily increase but daily decrease, hack away the unessential. The closer to the source, the less wastage there is."_  — Bruce Lee

Your update to include `lxml` in the `pyproject.toml` helps ensure a smoother installation process for users working with XML data. 📄🔍

For more guidance, please refer to our [Contributing Guide](https://docs.ultralytics.com/help/contributing). If you have any questions, feel free to leave a comment. Thank you for contributing to Ultralytics! 🚀

**Comment by glenn-jocher** [comment]
@MatthewNoyce thanks for the PR! We strive to reduce dependencies as much as possible, so the maximum we could do here would be to include it as an optional dependency, but I think even on hearing the result on your system (which doesn't seem to be the case in any of our CI runners, nor my experience locally), we do have a warning message on auto-install. The main reason an auto-install should fail would be if a package was already imported in that environment prior to upgrading.

On pandas for example I see an error when running to_xml() without the lxml install, so I think we are already going above and beyond here, importantly not affecting the majority of users that likely won't want the lxml package installed.

**Comment by MatthewNoyce** [comment]
@glenn-jocher that makes complete sense. Thank you for explaining the reasoning behind not wanting it included with the pyproject file.

**Comment by glenn-jocher** [comment]
You're welcome! If you have any more questions or need further assistance, feel free to ask.

**Comment by Laughing-q** [comment]
@MatthewNoyce Hey thanks for the PR! However I think we might not want this as an official dependency since it's only used in the results.to_xml() function and we already have a `check_requirement("lxml")` to automatically install the package when calling `results.to_xml()`.
https://github.com/ultralytics/ultralytics/blob/6dcc4a0610bf445212253fb51b24e29429a2bcc3/ultralytics/engine/results.py#L896

**Pull request closed without merging**
