### PR TITLE
fix-FLOPs-calculation-temporary

### PR DESCRIPTION
**Pull request by alanli1997**
I have read the CLA Document and I hereby sign the CLA

This is a temporary workaround to get FLOPs calculations correct, which requires the user to manually enter the _imgsz_ being inferred. I've tried to avoid requiring the user to enter this parameter, but I've found that doing so can result in a lot of code being modified. I'll submit the final fix once I have time. #9350 

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introducing dynamic image size input for model info queries.

### 📊 Key Changes
- Added prompt for users to enter desired image size (imgsz) for model inference.
- Included error handling for non-integer inputs, reverting to default size (640) if input is invalid.

### 🎯 Purpose & Impact
- **Enhances Flexibility**: Allows users to dynamically specify image size directly, making it easier to see how different image sizes affect model performance.
- **Improves User Experience**: By incorporating input validation, the feature ensures the system remains robust and user-friendly, defaulting to a safe value if needed.
- **Potential Impact**: Users can now tailor their model information queries more closely to their specific needs, potentially leading to better informed decisions about model deployment and performance optimization. 🚀

### CODE REVIEW

**Comment by AlanLi1997** [comment]
I have read the CLA Document and I sign the CLA

**Comment by AlanLi1997** [comment]
recheck

**Comment by Burhan-Q** [comment]
Could try using this:

`model_info(self, detailed=detailed, verbose=verbose, imgsz=getattr(self, "args", {}).get("imgsz", None) or imgsz)`

I tested with this change:

```py
from ultralytics import YOLO

model = YOLO("yolov8n.pt")

model.info()
>>> YOLOv8n summary: 225 layers, 3157200 parameters, 0 gradients, 8.9 GFLOPs
>>> (225, 3157200, 0, 8.8575488)

model.overrides["imgsz"] = 1280
model.info()
>>> YOLOv8n summary: 225 layers, 3157200 parameters, 0 gradients, 35.4 GFLOPs
>>> (225, 3157200, 0, 35.4301952)
```

Might not be the _best_ solution, but seems a bit better than prompting. Also, @AlanLi1997 maybe mark the PR as a `Draft` if you're still planning to do additional work on this.

**Comment by glenn-jocher** [comment]
Closing as not intended, but thank for the PR @AlanLi1997 and please feel free to submit any improvements you find in the future!

**Pull request closed without merging**
