### PR TITLE
Set invisible Pose points to 0.0

### PR DESCRIPTION
**Pull request by glenn-jocher**
Test with

```python
from ultralytics import YOLO

# Load a model
model = YOLO('yolov8n-pose.pt')

# Predict with the model
results = model()

# Show raw results
results[0].keypoints.data
```

Screenshot 2023-10-03 at 21 04 33

### Summary
🕵️‍♂️🎭🚫

This pull request improves the filtering of keypoints with low confidence in `ultralytics/engine/results.py`. It adds a check for the keypoints array shape and a mask to zero out the coordinates of the keypoints with confidence below 0.5.

> _`keypoints` array_
> _filter by confidence mask_
> _zero out the rest_

### Walkthrough
*  Filter out low-confidence keypoints by masking their coordinates ([link](https://github.com/ultralytics/ultralytics/pull/5212/files?diff=unified&w=0#diff-24af401e53ffc5ce49197395e1e3d7111344ad31b08cbb2bee9377614da98955R492-R494)) in `results.py`

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Enhanced keypoints initialisation with smart inference and visibility check in Ultralytics engine.

### 📊 Key Changes
- Introduced `smart_inference_mode` decorator to optimize the keypoints initialization.
- Added a condition to zero out (x, y) coordinates of keypoints with a confidence score less than 0.5, indicating non-visible points.

### 🎯 Purpose & Impact
- 🚀 **Purpose**: The update seeks to improve performance during the keypoints object initialization and ensure that non-visible points do not affect downstream processing.
- ✅ **Impact**: Users can expect more efficient and reliable keypoints handling, especially when dealing with occluded or partially visible points in images, leading to better detection accuracy.

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@Burhan-Q fix for setting invisible Pose points to 0.0

**Comment by MABatin** [comment]
Hi there, why??? JUST WHY?

**Comment by glenn-jocher** [comment]
@MABatin hi, could you please provide more details about the issue you're experiencing? This will help us assist you better. Thank you!

**Comment by MABatin** [comment]
> @MABatin hi, could you please provide more details about the issue you're experiencing? This will help us assist you better. Thank you!

Hi, the issue I faced is described [here](https://github.com/ultralytics/ultralytics/issues/15929). I couldn't quite understand the reason for defining _invisible_ keypoints by setting them to zero. Surely any downstream task that needs distinction for the _invisible_ keypoints could implement this method right?

**Comment by glenn-jocher** [comment]
Thank you for your feedback. The decision to set invisible keypoints to zero is to standardize the output for downstream tasks, ensuring consistency and simplifying further processing. If you have specific requirements, you can modify this behavior in your implementation.

**Comment by Y-T-G** [comment]
We have reverted this change in a recent PR

https://github.com/ultralytics/ultralytics/pull/21165

**Pull request merged**
