### PR TITLE
read all files in all the subdirectories

### PR DESCRIPTION
**Pull request by developer0hye**
### Summary
:mag::file_folder::cloud:

Improved image loading from nested folders by changing the glob pattern in `stream_loaders.py`. This enables the use of Google Drive folders as data sources for the `LoadImages` class.

> _`LoadImages` class_
> _Glob pattern now recursive_
> _Finds nested folders_

### Walkthrough
*  Modify glob pattern for recursive file search to include subdirectories ([link](https://github.com/ultralytics/ultralytics/pull/2137/files?diff=unified&w=0#diff-be9cf5c74e77e0cde8d630f233c18b23147891ede552e737c1ad702c08f7b652L188-R188)). This enables the `LoadImages` class in `stream_loaders.py` to load images from nested folders, such as Google Drive folders with subfolders.

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Improvement in file path globbing for data loading in YOLO.

### 📊 Key Changes
- Modified the glob pattern used to recursively include all files in a specified path.

### 🎯 Purpose & Impact
- **Purpose**: To ensure all nested files are included when specifying a directory for data loading.
- **Impact**: Users can now expect more consistent and comprehensive data file inclusions, especially when working with deeply nested directory structures. This effectively improves the robustness of data input handling.

### CODE REVIEW

**Comment by developer0hye** [comment]
The original code cannot catch all files with the below data structure.

```
path/
 folder1/
  file
 folder2/
  folder3/
   file
```

**Comment by glenn-jocher** [comment]
@developer0hye hi there, by default, the glob pattern only searches for files in the current directory and does not include subdirectories. In order to catch all files with the nested structure that you provided, the glob pattern needs to be modified to include subdirectories. One way to achieve this is by using a recursive glob pattern, which searches all subdirectories and returns a list of all matching file paths. This modified glob pattern can then be used with the `LoadImages` class in `stream_loaders.py` to load images from all subdirectories in a given directory, such as Google Drive folders with subfolders. Let me know if you have any further questions or need more information.

**Comment by developer0hye** [comment]
@glenn-jocher How about adding new options for it?

Example: 
```python
 if '**/*' in p:
```

**Comment by glenn-jocher** [comment]
@developer0hye, thank you for your suggestion. Modifying `p` to include the `**/*` pattern is actually a common and simple way of enabling a recursive search in glob patterns, as it includes all files and subdirectories. Adding a new option for this might add complexity to the codebase and user interface, and may not be necessary as the existing solution is clear and widely used. However, I appreciate your input and ideas for improving the project, and please let me know if you have any more questions or concerns.

**Comment by developer0hye** [comment]
@glenn-jocher I agree with you! Thanks! I

**Comment by glenn-jocher** [comment]
@developer0hye, You're welcome! I'm glad that I could help. It's always great to hear suggestions and ideas from contributors like yourself to improve the project. I hope this helps to clarify the approach for enabling recursive search in glob patterns. Let me know if you have any other questions or concerns.

**Comment by blueclowd** [comment]
Can I check if the nested data structure is supported now in YOLOv11?

Cause I still got a warning message when i configure the number of classes = 2:  `found xxxx images in 11 classes: ERROR requires 2 classes not 11`

11 is total number of subfolders in the 2nd layer

However, the training still proceeded with the above the warning message. May I know if i can ignore the message?

**Comment by glenn-jocher** [comment]
The warning indicates a mismatch between the configured number of classes and the detected classes. Ensure your dataset configuration file correctly specifies the number of classes and their labels. If the training proceeds and results are satisfactory, you might be able to ignore it, but it's best to align the configuration with your dataset structure.

**Pull request closed without merging**
