### PR TITLE
Added save_period for PR at #908

### PR DESCRIPTION
**Pull request by fabian57fabian**
Added enhancement described in #908 

Saved file will be in same dir as last.pt and best.pt, named epochX.pt . 
Usage: default.yaml is set to -1, add 'save_period=10' to args to save each 10 epochs. 
Added description in cfd.md .

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
Introduced checkpoint saving intervals by epoch during training.

### 📊 Key Changes
- A new configuration parameter `save_period` added to control checkpoint interval.
- The `trainer.py` logic updated to save checkpoints according to the `save_period`.

### 🎯 Purpose & Impact
- **Purpose**: To give users more control over how frequently they save training checkpoints.
- **Impact**: Users can now have fine-grained checkpoints, which can be helpful for long training runs or when needing to resume from specific epochs. This feature also may assist in reducing storage space by allowing less frequent saves.

### CODE REVIEW

**Comment by fabian57fabian** [comment]
Used wrong credentials for commit. Closing and opening again

**Comment by pderrenger** [comment]
@fabian57fabian no worries! Feel free to close and reopen the PR with the correct credentials. If you encounter any issues, please let us know, and we'll be happy to assist! 👍

**Comment by fabian57fabian** [comment]
Already solved in #911

**Comment by glenn-jocher** [comment]
That's great to hear, @fabian57fabian! Thank you for the update and for your contribution to improving the YOLOv8 repository. Your efforts help us all. Keep up the good work! 🚀 If you have any further questions or ideas, don't hesitate to share them with the community.

**Pull request closed without merging**
