### PR TITLE
Add Reddit link to documentation and templates

### PR DESCRIPTION
**Pull request by Y-T-G**
It would require merging this icon: https://github.com/ultralytics/assets/pull/65

## 🛠️ PR Summary

<sub>Made with ❤️ by [Ultralytics Actions](https://github.com/ultralytics/actions)<sub>

### 🌟 Summary
This pull request improves community engagement by adding Reddit links to various documentation and setup files.

### 📊 Key Changes
- Added Reddit community links to GitHub issue templates.
- Updated welcoming messages in GitHub workflows.
- Enhanced README files to include Reddit references for user support.
- Included Reddit icon and link in the documentation configuration.

### 🎯 Purpose & Impact
- **Increased Community Support**: Helps users find support and discussions on Reddit, enhancing community interaction options. 🗣️
- **Better User Engagement**: Welcomes new contributors more effectively with updated messages, helping streamline the contribution process. 📢
- **Improved Accessibility**: Offers more platforms for users to ask questions, share projects, and engage with the Ultralytics community. 🌐

### CODE REVIEW

**Comment by Burhan-Q** [comment]
https://github.com/ultralytics/assets/pull/65 has been merged.

**Comment by Y-T-G** [comment]
@Burhan-Q Marking ready for review.

**Comment by glenn-jocher** [comment]
@Y-T-G badge seems to be rendering improperly:
Screenshot 2024-08-12 at 20 58 14

**Comment by Burhan-Q** [comment]
I'm going to check this out and build the docs locally. I'll push any changes that are needed and then added the TODO label when I think we're ready. Probably will be tomorrow for me (locally) as I have a few personal appointments today

**Comment by Y-T-G** [comment]
@glenn-jocher Fixed.

image

**Comment by Burhan-Q** [comment]
Badge and icon looks good, thank you @Y-T-G! I updated a sentence to flow a little better and using ChatGPT + Google Translate, included the changes in the Chinese Readme file.

**Review by Burhan-Q — APPROVED** [review]
🚀

**Comment by glenn-jocher** [comment]
@Y-T-G @Burhan-Q I'm going to strip this PR of all org-level changes like the social icons and badges. Everything else I'll leave and then we can get this merged.

**Comment by glenn-jocher** [comment]
@Y-T-G @Burhan-Q PR merged with all repo-level changes. Thank you for your contributions!

**Pull request merged**
